### ISSUE TITLE
HEVC tiles in current display

### ISSUE THREAD

**Issue by 21praveen** [gpac/gpac#1003]
Hi,
 While playing HEVC SRD tiles in Mp4client, it is possible to get tile numbers that are in current view in 360 mode inside compositor.c or any other relevant file.

**Comment by jeanlf** [comment]
tile visibility testing is done in src/compositor/hardcoded_protos.c, function TraverseVRGeometry

HTH

**Comment by 21praveen** [comment]
Thank you for the guidance :)

I tried TraverseVRGeometry but I realized that it is not working due to always returning from: 

if (!tr_state->appear || ! ((M_Appearance *)tr_state->appear)->texture)
   		return;
