### ISSUE TITLE
"Feature Not Supported" when dashing encrypted mp4

### ISSUE THREAD

**Issue by sandersaares** [gpac/gpac#1005]
Version:  gpac-0.7.2-DEV-latest-master-x64.exe

Command: `mp4box.exe -dash 4000 -out out\Manifest.mpd "V0-media-H264-288p-400k.mp4"`

Expected result: dashed video.

Actual result:

```
DASH-ing file: 4.00s segments 4.00s fragments single sidx per segment
DASHing file V0-media-H264-288p-400k.mp4
Error while DASH-ing file: Feature Not Supported
Error DASHing file: Feature Not Supported
```

Without encryption, the same input works fine.

Input file: https://media.axprod.net/Issues/mp4box_feature_not_supported_2018-02/V0-media-H264-288p-400k.mp4

The input file was encrypted using the following crypt.xml file:

```
<GPACDRM type="cbcs">
  <CrypTrack trackID="1" IsEncrypted="1" saiSavedBox="senc" skip_byte_block="9" crypt_byte_block="1" constant_IV_size="16" constant_IV="0x4123DFEE5BD1C569162DE5FA983B21FC">
    <key KID="0x073A4DCB6B124E4CB4FF0EF2EA731ED9" value="0x283EA8B8EF351F06EFF0184219AB82D4" />
  </CrypTrack>
</GPACDRM>
```

Input file before encryption: https://media.axprod.net/Issues/mp4box_feature_not_supported_2018-02/clear-V0-media-H264-288p-400k.mp4

**Comment by jeanlf** [comment]
indeed - cbcs is not fully supported yet, and what we do is not 100% compliant (first byte of first block shall be the first full byte after the slice header, which we don't implement). We'll try to fix this but not sure when ...

**Comment by sandersaares** [comment]
I see. I hope you manage to cover it - with HLS now targeting CMAF this has become quite an important feature.

**Comment by jeanlf** [comment]
This should now be implemented (slice header alignment in bothe AVC and HEVC + various cbcs/cens fixes) - could you check everything works for you ?

**Comment by sandersaares** [comment]
With `gpac-0.7.2-DEV-rev454-g02582a22-master-x64` I still get the same behavior as in the original post of this issue:

```
Error while DASH-ing file: Feature Not Supported
Error DASHing file: Feature Not Supported
```
