### ISSUE TITLE
Unable to play the video after tiling a video and encoding it using kvazaar, MP4Box

### ISSUE THREAD

**Issue by ashrithhc** [gpac/gpac#1006]
I'm trying to tile multiple videos using kvazaar and then encode it through MP4Box, I'm unable to figure out what I'm doing wrong here, as the output video is not playable.

Step 1) Tile a video
```kvazaar -i input_1280x720.mp4 --input-res 1280x720 -o output_1280x720.hvc --tiles 6x4 --slices tiles --mv-constraint frametilemargin --input-fps 30 -q 30 -p 30```

Step 2) Encode a video
```MP4Box -add output_1280x720.hvc:split_tiles -fps 30 -new output_1280x720.mp4```

Once the above steps are executed, a tiled mp4 video is expected, which can be dashed using MP4Box with different resolutions of the same video.
```MP4Box -dash 1000 -rap -frag-rap -profile live -out dash_tiled.mpd output_1280x720.mp4 output_1920x1080.mp4 output_2560x1440.mp4```

I am unsure if I am doing something incorrect fundamentally here. Appreciate your help!

**Comment by ashrithhc** [comment]
The issue was that kvazaar takes only .yuv files as input. Converting the input file to yuv prior to these steps resolved the issue.

**Comment by hirwaam** [comment]
Hi Ashish,

I was facing the same issue as yours and based on your experience, converted an mp4 to yuv first before proceeding with kvazaar. However, I can still find issue with the codecs after the encoding step:

bitnami@ip-172-31-41-171:~/htdocs/DASH/360_video/tiled/2$ MP4Box -add video_tiled.hevc:split_tiles -fps 30 -new video_tiled.mp4
HEVC import - frame size 4096 x 2048 at 30.000 FPS
HEVC Import results: 928 samples (9284 NALUs) - Slices: 279 I 8073 P 0 B - 929 SEI - 279 IDR
Saving video_tiled.mp4: 0.500 secs Interleaving
bitnami@ip-172-31-41-171:~/htdocs/DASH/360_video/tiled/2$ ls -l
total 11469052
-rw-rw-r-- 1 bitnami bitnami    33652620 Jan 25 11:38 video_tiled.hevc
-rw-rw-r-- 1 bitnami bitnami    33708136 Jan 25 11:42 video_tiled.mp4
-rw-rw-r-- 1 bitnami bitnami 11676942336 Jan 25 11:19 video.yuv

bitnami@ip-172-31-41-171:~/htdocs/DASH/360_video/tiled/2$ ffprobe video_tiled.mp4
ffprobe version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2007-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xe547a0] Could not find codec parameters for stream 0 (Video: none (hvc2 / 0x32637668), none, 4096x2048, 5 kb/s): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xe547a0] Could not find codec parameters for stream 1 (Video: none (hvt1 / 0x31747668), none, 1344x640, 565 kb/s): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xe547a0] Could not find codec parameters for stream 2 (Video: none (hvt1 / 0x31747668), none, 1344x640, 647 kb/s): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xe547a0] Could not find codec parameters for stream 3 (Video: none (hvt1 / 0x31747668), none, 1408x640, 599 kb/s): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xe547a0] Could not find codec parameters for stream 4 (Video: none (hvt1 / 0x31747668), none, 1344x704, 772 kb/s): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xe547a0] Could not find codec parameters for stream 5 (Video: none (hvt1 / 0x31747668), none, 1344x704, 1012 kb/s): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xe547a0] Could not find codec parameters for stream 6 (Video: none (hvt1 / 0x31747668), none, 1408x704, 795 kb/s): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xe547a0] Could not find codec parameters for stream 7 (Video: none (hvt1 / 0x31747668), none, 1344x704, 1227 kb/s): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xe547a0] Could not find codec parameters for stream 8 (Video: none (hvt1 / 0x31747668), none, 1344x704, 1462 kb/s): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xe547a0] Could not find codec parameters for stream 9 (Video: none (hvt1 / 0x31747668), none, 1408x704, 1617 kb/s): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
video_tiled.mp4: Operation not permitted
bitnami@ip-172-31-41-171:~/htdocs/DASH/360_video/tiled/2$

Your support will be appreciated.
