### ISSUE TITLE
Header bytes before each keyframe in segmented mp4 file (styp)

### ISSUE THREAD

**Issue by PedroRomanoBarbosa** [gpac/gpac#1010]
I segmented a file using dash into segment files and for each keyframe in the segment the size is always bigger than the actual frame size in the original mp4. In he case of my files the differenci in size is 37 bytes:

00 00 00 19 67 4D 40 1F EC A0 28 02 DD 80 88 00 00 03 00 08 00 00 03 01 84 78 C1 8C B0 00 00 00 04 68 EF BC 80

What do these bytes represent?

**Comment by jeanlf** [comment]
Looks like you are dashing using inband parameter sets. use -bs-switching no to prevent that
