### ISSUE TITLE
MP4Box: ttxt screen positioning issue.

### ISSUE THREAD

**Issue by MikZyth** [gpac/gpac#1012]
Hello.
As far as I know, MP4Box ttxt format supports subtitle screen positioning, but I just can’t get it to work.
I want a subtitle to appear at top of the screen. But regardless of "top" attribute I set in ttxt, it’ll always appear at bottom.

Sample from `http://gpac.sourceforge.net/downloads/ttxt_sample_streams.tar.gz` also doesn’t seem to work (3GP_test_08.ttxt), QuickTime Player always shows "Unknown error -12710".

MP4 file was made using MP4Box `gpac_0.7.2-DEV-rev434-g9d4fd39b-master_amd64` official nightly build on Ubuntu 16.04 LTS 64 bit.
The file was tested in QuickTime Player on latest macOS High Sierra (version 10.13.) and MP4Client from the same build.

Is it a bug or I’m doing something wrong?
Any help will be appreciated.

Best regards.

**Comment by MikZyth** [comment]
Hello again.
Seems like I've found a solution. Subtitle positioning works if txtflags is set to some particular value.
If there's just one subtitle track, then `0x20000000`, `0x30000000`, `0x60000000` or `0x70000000` values work.
If there are two subtitle tracks and I want the first to be set forced (hidden), then `0xA0000000`, `0xB0000000`, `0xE0000000`, `0xF0000000` values work.

Perhaps, the value also depends on track position/number in the resulting file (and the command line).

But what this "txtflags" option really mean and which value is correct?
GPAC docs have no info about this.

Example command line with one subtitle track:
`mp4box -add video.x264 -add en.ttxt:group=2:txtflags=0x20000000:name="":lang=eng output2.m4v`

Example command line with two subtitle tracks:
`mp4box -add video.x264:name="":lang=eng -add ru.aac:group=1:name="":lang=rus -add en.aac:group=1:disabled:name="":lang=eng -add ru_f.ttxt:group=2:txtflags=0xF0000000:name="":lang=rus -add en.srt:layout=-1:group=2:disabled:name="":lang=eng output000F.m4v`
Here is my sample subtitle: https://yadi.sk/d/9Ewsz82V3VHhgu.

Can anyone help with this "txtflags" option?

**Comment by jeanlf** [comment]
the txtflags sets the flags of the text track header, without inspecting them. Most of the flags won't mean anything in MP4 or 3GP context but may mean a lot in QT/iOS - please check the QTFF spec to find out the meaning of the various flags
