### ISSUE TITLE
Buffer level in dash_client for SRD 

### ISSUE THREAD

**Issue by 21praveen** [gpac/gpac#1014]
Hi,
   As of now, dash_client maintain buffer level for the entire group. Even if we turn off few tiles, it shows the highest value of buffer occupancy. Is it possible to measure buffer occupancy for individual tile?

**Comment by fujunustc** [comment]
May i ask how you turn off few tiles, which does not affect display?

**Comment by 21praveen** [comment]
@fujunustc Don't turn off first tile. It has the necessary information for decoding. 

Can you please help me with the buffer?

**Comment by fujunustc** [comment]
In my opinions, the definition of buffer occupancy is the remain time of playback. In hevc, when all selected tiles are downloaded, the buffer occupancy will add the duration of tiles. 
About turning off few tiles, could you have a look at #987 ？
Thank for your time~

**Comment by jeanlf** [comment]
For hevc mcts tiling this won’t be possible because what is dispatched in the decoding buffer is the aggregated frame with all the tiles. For non  mcts, streams are kept seperated so buffer level is per stream
