### ISSUE TITLE
GPAC LINKING ISSUE

### ISSUE THREAD

**Issue by swetheendra84** [gpac/gpac#1015]
I am Using GPAC source code for my Project. I am calling gf_dash_setup_period() defined in src/media_tools/dash_client.c from applications/mp4client/main.c  by including it in header file dash.h. 
However Im unable to make it as I am getting "Undefined reference to gf_dash_setup_period ". It is getting compiled properly and object file is getting generated.

But there is problem while linking and main.o is failing. MakeFile also seems to be proper. Can I get any lead on this issue of how to resolve and proceed further ?

**Comment by rbouqueau** [comment]
Could you share a minimal example on github so that we an reproduce?

**Comment by swetheendra84** [comment]
Hi Romain,
Thanks for your Reply.
This is url to my code  https://github.com/swetheendra84/GPAC-Client.git.
Inside *applications/mp4client/main.c* in *eventproc()* *mouse move* case
(line 856), I am trying to call *gf_dash_setup_period1()* similar to
*gf_dash_setup_period()* but instead of fetching all tiles i am passing
only tile  requiring to fetch as parameter. (I am using selective tiling
and then trying to fetch some of missing tiles dynamically from mouse
movements)
This function  *gf_dash_setup_period1()*  is defined in
src/media_tools/dash_client.c. Linking this function is causing problem. I
have declared this new function in gpac/dash.h

Thanks,
Swetheendra

**Comment by rbouqueau** [comment]
Have you tried to add ```GF_EXPORT``` before the function definition?

**Comment by swetheendra84** [comment]
That Worked!. Thankyou.
