### ISSUE TITLE
360video.mp4  split to M Segments and N*N tiles

### ISSUE THREAD

**Issue by fuxingyang** [gpac/gpac#1016]
How to split the 360video.mp4 to M Segments and N*N tiles?I have installed MP4Box,but i can't know how to generate DASH files about 360video.I want to achieve the goal as shown in the figure below.
Can you give me some ideas?Thank you!
![clipboard](https://user-images.githubusercontent.com/20569009/37380679-b7c06fb0-2774-11e8-8c79-38ae78903c46.png)

**Comment by jeanlf** [comment]
for HEVC tiling, cf https://gpac.wp.imt.fr/2017/02/01/hevc-tile-based-adaptation-guide/

for regular encoding, you need an external tool (eg ffmpeg) to spatially split the source in NxM  videos and encode them, see https://gpac.wp.imt.fr/2016/05/25/srdtuto/

**Comment by fuxingyang** [comment]
@jeanlf Thank you for the reply!My 360video isn't for HEVC but just for h.264 as shown in the figure below.
Can I use Mp4Box directly to spatially split the 360video in NxM videos? 
![qq 20180314153310](https://user-images.githubusercontent.com/20569009/37388873-1507f22e-279d-11e8-8490-b34f448fb3e3.png)

**Comment by fuxingyang** [comment]
For 360video,I want to get M Segments by time and every segment have X*Y spatial tiles .How can i make it?
Can you give me the correct Mp4Box command  to achieve it?
Thank you!Best wishes!

**Comment by fuxingyang** [comment]
Hello, @jeanlf @kazuki @pclouds @tieleman @wiiaboo !
@jeanlf:`for HEVC tiling, cf https://gpac.wp.imt.fr/2017/02/01/hevc-tile-based-adaptation-guide/`
I follow gpac's tutorial but can't get the same results as the tutorial.
![image](https://user-images.githubusercontent.com/20569009/38295635-3201193e-3821-11e8-8a82-0e94f9eb109b.png)

Details are as follows:

> `1.kvazaar --input AerialCity50.yuv --input-res=3840x1920   --tiles 3x3 --slices tiles --mv-constraint frametilemargin  --output aerialcity50tilemargin.hvc;` 
` 2. MP4Box -add aerialcity50tilemargin.hvc:split_tiles -new video_tiled.mp4;` 

> **result**:Cannot find file aerialcity50tilemargin.hvc:split_tiles
Cannot find file aerialcity50tilemargin.hvc:split_tiles
Error importing aerialcity50tilemargin.hvc:split_tiles: Requested URL is not valid or cannot be found

As it show above,I can't get correct result.
Can you  give me some ideas?Thank you!
