### ISSUE TITLE
Issues about dashing two tiled video of different resolution

### ISSUE THREAD

**Issue by ZhangkaiKevin** [gpac/gpac#1018]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by ZhangkaiKevin** [comment]
I used kvazaar to turn raw .yuv sequences to hevc video.
kvazaar --input ShakeNDry_1920x1080_120fps_420_8bit_YUV.yuv --output out_1920x1080.hevc --tiles 2x3 --slices tiles --mv-constraint frametilemargin
kvazaar --input ShakeNDry_3840x2160.yuv --output out_3840x2160.hevc --tiles 2x3 --slices tiles --mv-constraint frametilemargin
And then I used mp4box to generate the mpd file.
mp4box -add out_1920x1080.hevc:split_tiles -new out_1920x1080.mp4
mp4box -add out_3840x2160.hevc:split_tiles -new out_3840x2160.mp4
mp4box -dash 1000 -profile live -out dash_tiled.mpd out_3840x2160.mp4 out_1920x1080.mp4
However, its mpd shows like below.

<?xml version="1.0"?>

<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H0M12.000S" maxSegmentDuration="PT0H0M2.560S" profiles="urn:mpeg:dash:profile:isoff-live:2011">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>dash_tiled.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H0M12.000S">
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="1920" maxHeight="1080" maxFrameRate="25" par="16:9" lang="und">
   <EssentialProperty schemeIdUri="urn:mpeg:dash:srd:2014" value="1,0,0,0,0"/>
   <SegmentTemplate initialization="dash_tiled_set1_init.mp4"/>
   <Representation id="1" mimeType="video/mp4" codecs="hev2.1.6.L186.80" width="1920" height="1080" frameRate="25" sar="1:1" startWithSAP="1" bandwidth="8242">
    <SegmentTemplate media="out_1920x1080_dash_track1_$Number$.m4s" timescale="25000" startNumber="1" duration="25000"/>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="960" maxHeight="320" maxFrameRate="25" par="960:320" lang="und">
   <SupplementalProperty schemeIdUri="urn:mpeg:dash:srd:2014" value="1,0,0,960,320"/>
   <Representation id="1_2" mimeType="video/mp4" codecs="hvt1.1.6.L186.80" width="960" height="320" frameRate="25" sar="1:1" startWithSAP="1" bandwidth="637250" dependencyId="1">
    <SegmentTemplate media="out_1920x1080_dash_track2_$Number$.m4s" timescale="25000" startNumber="1" duration="25000"/>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="960" maxHeight="320" maxFrameRate="25" par="960:320" lang="und">
   <SupplementalProperty schemeIdUri="urn:mpeg:dash:srd:2014" value="1,960,0,960,320"/>
   <Representation id="1_3" mimeType="video/mp4" codecs="hvt1.1.6.L186.80" width="960" height="320" frameRate="25" sar="1:1" startWithSAP="1" bandwidth="1307036" dependencyId="1">
    <SegmentTemplate media="out_1920x1080_dash_track3_$Number$.m4s" timescale="25000" startNumber="1" duration="25000"/>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="960" maxHeight="384" maxFrameRate="25" par="960:384" lang="und">
   <SupplementalProperty schemeIdUri="urn:mpeg:dash:srd:2014" value="1,0,320,960,384"/>
   <Representation id="1_4" mimeType="video/mp4" codecs="hvt1.1.6.L186.80" width="960" height="384" frameRate="25" sar="1:1" startWithSAP="1" bandwidth="1616782" dependencyId="1">
    <SegmentTemplate media="out_1920x1080_dash_track4_$Number$.m4s" timescale="25000" startNumber="1" duration="25000"/>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="960" maxHeight="384" maxFrameRate="25" par="960:384" lang="und">
   <SupplementalProperty schemeIdUri="urn:mpeg:dash:srd:2014" value="1,960,320,960,384"/>
   <Representation id="1_5" mimeType="video/mp4" codecs="hvt1.1.6.L186.80" width="960" height="384" frameRate="25" sar="1:1" startWithSAP="1" bandwidth="2554133" dependencyId="1">
    <SegmentTemplate media="out_1920x1080_dash_track5_$Number$.m4s" timescale="25000" startNumber="1" duration="25000"/>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="960" maxHeight="376" maxFrameRate="25" par="960:376" lang="und">
   <SupplementalProperty schemeIdUri="urn:mpeg:dash:srd:2014" value="1,0,704,960,376"/>
   <Representation id="1_6" mimeType="video/mp4" codecs="hvt1.1.6.L186.80" width="960" height="376" frameRate="25" sar="1:1" startWithSAP="1" bandwidth="1371679" dependencyId="1">
    <SegmentTemplate media="out_1920x1080_dash_track6_$Number$.m4s" timescale="25000" startNumber="1" duration="25000"/>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="960" maxHeight="376" maxFrameRate="25" par="960:376" lang="und">
   <SupplementalProperty schemeIdUri="urn:mpeg:dash:srd:2014" value="1,960,704,960,376"/>
   <Representation id="1_7" mimeType="video/mp4" codecs="hvt1.1.6.L186.80" width="960" height="376" frameRate="25" sar="1:1" startWithSAP="1" bandwidth="1425802" dependencyId="1">
    <SegmentTemplate media="out_1920x1080_dash_track7_$Number$.m4s" timescale="25000" startNumber="1" duration="25000"/>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="3840" maxHeight="2160" maxFrameRate="25" par="16:9" lang="und">
   <EssentialProperty schemeIdUri="urn:mpeg:dash:srd:2014" value="1,0,0,0,0"/>
   <SegmentTemplate initialization="dash_tiled_set8_init.mp4"/>
   <Representation id="2" mimeType="video/mp4" codecs="hev2.1.6.L186.80" width="3840" height="2160" frameRate="25" sar="1:1" startWithSAP="1" bandwidth="8238">
    <SegmentTemplate media="out_3840x2160_dash_track1_$Number$.m4s" timescale="25000" startNumber="1" duration="25000"/>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="1920" maxHeight="704" maxFrameRate="25" par="1920:704" lang="und">
   <SupplementalProperty schemeIdUri="urn:mpeg:dash:srd:2014" value="1,0,0,1920,704"/>
   <Representation id="2_9" mimeType="video/mp4" codecs="hvt1.1.6.L186.80" width="1920" height="704" frameRate="25" sar="1:1" startWithSAP="1" bandwidth="4807460" dependencyId="2">
    <SegmentTemplate media="out_3840x2160_dash_track2_$Number$.m4s" timescale="25000" startNumber="1" duration="25000"/>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="1920" maxHeight="704" maxFrameRate="25" par="1920:704" lang="und">
   <SupplementalProperty schemeIdUri="urn:mpeg:dash:srd:2014" value="1,1920,0,1920,704"/>
   <Representation id="2_10" mimeType="video/mp4" codecs="hvt1.1.6.L186.80" width="1920" height="704" frameRate="25" sar="1:1" startWithSAP="1" bandwidth="6154512" dependencyId="2">
    <SegmentTemplate media="out_3840x2160_dash_track3_$Number$.m4s" timescale="25000" startNumber="1" duration="25000"/>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="1920" maxHeight="704" maxFrameRate="25" par="1920:704" lang="und">
   <SupplementalProperty schemeIdUri="urn:mpeg:dash:srd:2014" value="1,0,704,1920,704"/>
   <Representation id="2_11" mimeType="video/mp4" codecs="hvt1.1.6.L186.80" width="1920" height="704" frameRate="25" sar="1:1" startWithSAP="1" bandwidth="5404312" dependencyId="2">
    <SegmentTemplate media="out_3840x2160_dash_track4_$Number$.m4s" timescale="25000" startNumber="1" duration="25000"/>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="1920" maxHeight="704" maxFrameRate="25" par="1920:704" lang="und">
   <SupplementalProperty schemeIdUri="urn:mpeg:dash:srd:2014" value="1,1920,704,1920,704"/>
   <Representation id="2_12" mimeType="video/mp4" codecs="hvt1.1.6.L186.80" width="1920" height="704" frameRate="25" sar="1:1" startWithSAP="1" bandwidth="7075794" dependencyId="2">
    <SegmentTemplate media="out_3840x2160_dash_track5_$Number$.m4s" timescale="25000" startNumber="1" duration="25000"/>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="1920" maxHeight="752" maxFrameRate="25" par="1920:752" lang="und">
   <SupplementalProperty schemeIdUri="urn:mpeg:dash:srd:2014" value="1,0,1408,1920,752"/>
   <Representation id="2_13" mimeType="video/mp4" codecs="hvt1.1.6.L186.80" width="1920" height="752" frameRate="25" sar="1:1" startWithSAP="1" bandwidth="4943756" dependencyId="2">
    <SegmentTemplate media="out_3840x2160_dash_track6_$Number$.m4s" timescale="25000" startNumber="1" duration="25000"/>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="1920" maxHeight="752" maxFrameRate="25" par="1920:752" lang="und">
   <SupplementalProperty schemeIdUri="urn:mpeg:dash:srd:2014" value="1,1920,1408,1920,752"/>
   <Representation id="2_14" mimeType="video/mp4" codecs="hvt1.1.6.L186.80" width="1920" height="752" frameRate="25" sar="1:1" startWithSAP="1" bandwidth="5055214" dependencyId="2">
    <SegmentTemplate media="out_3840x2160_dash_track7_$Number$.m4s" timescale="25000" startNumber="1" duration="25000"/>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>

**Comment by ZhangkaiKevin** [comment]
I thought that it should had 2X3+1 adaptionsets and each adaptionset had two segments with different resolutions. But actually, it has 14 adaptionsets(each resolution with 7 sets). It is definitely incorrect. Where is wrong?

**Comment by jeanlf** [comment]
You cannot mix different tile resolutions in GPAC as a single set of adaptation sets, this is not supported because switching quality of one of the tile would require mixing two base tile tracks (ie decode with conflicting pps/sps for a single picture). You need to have the same resolution with different bitrates, or use completely independent videos (not MCTS HEVC).

**Comment by phananh1010** [comment]
Hello, I am having the same issues.
Since multiple resolutions have been used in many paper, could you consider implement this feature? Specifically, can you support streaming where client can chose one of many resolution available at the server?
