### ISSUE TITLE
MP4Box -dump-item into a specific location: problem with path ?.

### ISSUE THREAD

**Issue by jalba69** [gpac/gpac#1019]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/
______________________
Hello,

Using latest nightly build _gpac-0.7.2-DEV-rev438-gc107b22d-master-x64.exe_ from your website and _win7 x64_  
From windows command prompt I'm trying to use _-dump-item_ to drop the files into specific locations  :

`MP4Box -dump-item 1:path="H:\item1.hevc" "H:\image.heic"`

This returns : 
```
[IsoMedia] Extracting item type  not supported

        Error: Feature Not Supported
```

The following ones work : 
```
MP4Box -dump-item 1:path=item1.hevc "H:\image.heic"
MP4Box -dump-item 1:path="item1.hevc" "H:\image.heic"
MP4Box -dump-item 1:path="..\item1.hevc" "H:\image.heic" 
```
 _(last one correctly drops the file into MP4Box parent folder)_

I suspect the colon in the path is the problem, i tried the few variations i know to escape the paths but no dice until now and running out of ideas so i came here to ask if a good soul have an idea about this or if it's somehow not possible to get this working like i want

Thank you very much,
Merci d'avance :)

**Comment by aureliendavid** [comment]
you're right, that's a bug, should be fixed now, reopen if needed

thanks for the report

**Comment by jalba69** [comment]
Seems all good now with 0.7.2-DEV-rev441 from your website.

Thanks a lot for the quick fix and for this nice tool.

**Comment by jalba69** [comment]
Hello again,

I'm not sure if the following is linked or not to the previous issue but it's similar and I hesitated between creating a new report or re-opening this one, 

Command : 
`MP4Box -add-image "H:\video1.hvc":primary:name=Pic1 -add-image "H:\video2.hvc":name="picture2" -ab heic "H:\image.heic"`

This correctly adds first frames from videos 1 & 2 with the names I indicated in the command line, no matter if i put the name between quotes or not here as there is no spaces.

 If i try something like a name with a space while between the quotes it works too, like:
`:name="Pic1 20-03-2018 "`
And of course doesn't work if the quotes are not present in this example.

But if i try a name having a colon in it it like this 
`:name="Pic1 20-03-2018 15:20:00"`
 it throws me an error :
`[Importer] Unknown input file type for "00"

        Error: Requested URL is not valid or cannot be found` 
or if it's only `name="Pic1 20-03-2018 :"` it returns this:
`[Importer] Unknown input file type for ""

        Error: Requested URL is not valid or cannot be found`

I'm not sure if it's another parsing issue for things inside quotes or normal behavior here.

_______________________________
Also if i may ask a little question while i'm experimenting with all this  : 
Is it somehow possible to choose the frame(s) we want from the video, or a frame from an exact timestamp or not possible at all ?

I read about the `file.hvc:time=1.2` that will import the next **IDR frame** after the given time but what i'd like is select a precise frame position or time and get the frame(s) imported, not sure if it's possible or not so better ask.

Thanks a lot again :)

**Comment by aureliendavid** [comment]
> `:name="Pic1 20-03-2018 15:20:00"`

yeah this is a bit more tricky - you currently can't use a colon (`:`) inside a parameter value with this syntax

the quotes are actually processed by the command line (to build the argument list properly when there are spaces) so the program doesn't see them

as such we can't easily tell the difference between the `:` as an options separator, and the `:` inside an option value

you can open an issue about that as a feature request, but this is not a trivial fix like the previous one

----- 

as for your other question I don't really know if it's possible, you can open a separate issue for that too so maybe someone else can answer

**Comment by jalba69** [comment]
Thanks for the quick reply,

No worries then, I'll simply format the timestamps without using the colon symbol in them, did not knew if it was normal or not, and after previous issue better ask :) 

For the other question i will make another post and ask about it a bit later yes, either it is possible and someone knows how to do it or it will end up as a feature request for something that could be (imo) an interesting option to have.

Currently testing and experimenting with heif/heic support and a lot of possibilities are offered by this container format, i'm glad you guys provide support for it in MP4box so early already :)

Thanks again for the all help.
