### ISSUE TITLE
MP4box visualProfileLevelIndication changing?

### ISSUE THREAD

**Issue by richardbushell** [gpac/gpac#102]
Hi Jean

I have an issue with the visualProfileLevelIndication value changing between the original file and the raw/m4v intermediate file.

Using the same original file as before, located here: http://living.tv/mob/ibeani_i4_mcstdlow.mp4

Using -DISO on this original file I see visualProfileLevelIndication="255" in the IOD (which I believe is the correct value)

When I extract the RAW video track with MP4box -raw option, then -add it to create a new m4v file, then using -DISO on this m4v file shows visualProfileLevelIndication="21" (which I believe is now incorrect?). This then reports a conformance error in the DASH Validator.

Is this a bug? Or could this value change for any reason?

Richard

**Comment by jeanlf** [comment]
There was indeed a bug, the assigned PL code for AVC in MPEG-4 Systems  is 0x7F not 0x15, now fixed.

BTW 255 might not be the best value to set for PL since its meaning is "no visual capability required" . I'll check what I can do.

**Comment by richardbushell** [comment]
Hi Jean
OK, the DASH Conformance Validator got past that warning, but now says:
### Validate_IODS: visualProfileLevelIndication ( IOD: 127 (0x7f) ) signalled .. but there seems to be no video track
Any ideas?

**Comment by richardbushell** [comment]
p.s. We also get a similar error for the Audio track:
Validate_IODS: ISMA expects no-capability(0xFF) or Hi-Quality@L1/L2 (0x0E, 0x0F) or AAC@L4 (0x2a) or HE-AAC@L2 (0x2c) for audioProfileLevelIndication.

**Comment by jeanlf** [comment]
hmm strange, there is a video track no ?

**Comment by richardbushell** [comment]
Are you referring to: Class_ES_ID_IncTag?
The DASH Conformance Validator did also report these as missing too for the Video and Audio representations.

**Comment by jeanlf** [comment]
Well this is a bit of a mess: the iod was supposed to be used only for mpeg4 systems players, however the only way to indicate aac profiles is through the iod :(
And the iod can only contain bifs or od so in case of pure av files we end up with an empty iod. Isma used to mandate default bifs and od streams (hence the -isma option in gpac) but no one uses this ...
Not sure what the validator message is supposed to mean, especially in non isma cases

**Comment by richardbushell** [comment]
This is definitely above my level of knowledge or understanding.
I know that the original MP4 file: http://living.tv/mob/ibeani_i4_mcstdlow.mp4
(before processing with MP4box) contains through -DISO:
Descr
   esDescrInc
      ES_ID_Inc trackID="1"
      ES_ID_Inc trackID="2"
BUT after processing just an EMPTY descriptions for both the video and audio.
Is this fixable? I am not sure what impact this has, if any, but the validator doesn't like it...
As I said, it is above my knowledge or understanding unfortunately...

**Comment by richardbushell** [comment]
Also, just for clarification, I am unsure of the correct current standard for the Audio Profile Levels.
Under ISO/IEC 14496-3:2009, should it currently be:
0x29 AAC Profile L2
OR is this now correct:
0x51 AAC Profile L2
whiich I saw referenced here:
http://itscj.ipsj.or.jp/sc29/open/29view/29n14342t.doc
Which are the correct values under the latest standard?
Can you advise please as I am confused as to which is the latest correct standard?
