### ISSUE TITLE
MP4Box Heif/heic : Is it possible to select a specific frame number/position in the video input ? 

### ISSUE THREAD

**Issue by jalba69** [gpac/gpac#1021]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/
_____________
Hello,
I'm currently experimenting/testing with MP4box and heif/heic and would like to know if the following is possible or not : 

Right now i can add the first frame from a video into a heic , like :  

`MP4Box -add-image "H:\video1.hvc":primary:name="Frame1" -ab heic -new "H:\image.heic"`

Or first frame from 2 different videos sources into a single heic , something like : 

`MP4Box -add-image "H:\video1.hvc":primary:name="Picture1" -add-image "H:\video2.hvc":name="Picture2" -ab heic "H:\image.heic"`

I also read about _file.hvc:time=1.2_ that will import _the next IDR frame_ after the given time : 

`MP4Box -add-image "H:\video1.hvc":primary:name="Frame1":time=1.2 -ab heic -new "H:\image.heic"`

But what i will be interested in is selecting the frame(s) i want from a given video, either by specifying the frame number of the desired frame(s) or the timestamp where the frame i want is located ( maybe as _00:00:00:000_ timestamps, frame number will be simpler tho, something like _:framepos=150_ maybe, the number being the frame position desired to be extracted from the the video and sent to the heic file, also something like this could be a solution for multiple frames in a single command  _:framepos="100,200,500,1000"_  ) 

I don't know if this is possible for now and i am maybe missing the correct infos/documentation to achieve this or if it is simply not possible with MP4Box, 

If it isn't possible then please consider this as a request feature that could bring something very interesting to this container format used within MP4Box.

Thank you for any hints or help,
Merci d'avance :)

**Comment by jalba69** [comment]
Sorry for bumping this but after testing more and reading about the various possibilities in the help files i thought about the `:delay=delay_ms` option.

I'm not sure if this could be implemented but as it exists already in the code maybe it will be possible to translate this for the add-image option , something like : 

MP4Box -add-image "H:\video1.hvc":primary:name="Frame1"**:delay=45000** -ab heic -new "H:\image.heic"

As long as the delay value is not limited when it comes to very high values in MS and able to cover the entire length of a video input it could be an alternative not too hard to add to MP4Box to achieve the possibility to select the frame we want for the heic file.

Thank you very much.

**Comment by jeanlf** [comment]
I think a :frames option will be simpler. We’ll look at it

**Comment by jalba69** [comment]
Thank you very much, It will be great to have this possibility.

**Comment by jeanlf** [comment]
Done (0.9.0 only), and that was more fun than expected. Rather than specifying frames to import, here is the design:
- possibility to insert a filter chain in the importers (-add or -add-image) just before the muxer; this means you can now invoke pretty much anything (including encoders) at import time. 
- time=-1 in -add-image implies adding all samples from the source
- added :frames option to reframer filter

You can have a look at [this script](https://github.com/gpac/gpac/blob/filters/tests/scripts/heif.sh), but in a nutshell
- to import all IDRs as items from a source file:
```MP4Box -add-image source.hvc:time=-1:@@reframer:saps=1 -new test.heif```

- to import frames 1, 100 and 122 from a source file:
```MP4Box -add-image source.hvc:time=-1:@@reframer:frames=1,100,122 -new test.heif```

Enjoy!

**Comment by jalba69** [comment]
Hello,

Thank you for adding the option so fast and sorry for posting on this after it have been closed but after spending a few days trying to get this sorted and banging my head against a wall it seems i just cannot manage to get this done : 

the following command works : 
`MP4Box -add-image "H:\testvid.hevc":time=-1:@@reframer:saps=1 -new "H:\test1.heic"`

It extracts all keyframes/IDR's from the input source.

But I have no success with trying to extract specific frames using the command : 
`MP4Box -add-image "H:\testvid.hevc":time=-1:@@reframer:frames=1,100,122 -new "H:\test1.heic"`

I get this error message : 
```
←[32mItem Importing HEVC - Width 1280 Height 720 FPS 60/1 SAR 1/1
←[32mHEVC Import results: 54001 samples (54008 NALUs) - Slices: 217 I 11016 P 42768 B - 1 SEI - 217 IDR
←[0m←[32mHEVC Stream uses forward prediction - stream CTS offset: 4 frames
←[0m←[32mHEVC Max NALU size is 18596 - stream could be optimized by setting nal_length=2
←[0m←[32mAdding sample from time 0.000 as item 1
←[0m←[31mError some imported samples are not sync samples
←[0m
        Error: Bad Parameter
```

Started to dig into the documentation and closed issues and tried this : 
`MP4Box -add-image "H:\testvid.hevc":forcesync:@@reframer:frames=1,100,122 -new "H:\test1.heic"`

But it extracts only one item, the first frame, trying to use time=-1 in the command line returns an error message similar to the one above.

Trying this command : 
`MP4Box -add "H:\testvid.hevc":forcesync:@@reframer:frames=1,100,122 -new "H:\test1.heic"`

just using "-add" and not "-add-image", this seems to work and creates a moovie having 3 items according to the MP4Box -info command : 
```
Mp4box -info "H:\test1.heic"
* Movie Info *
        Timescale 600 - 1 track
        Computed Duration 00:00:02.000 - Indicated Duration 00:00:02.000
        Fragmented File: no
        File suitable for progressive download (moov before mdat)
        File Brand iso4 - version 1
                Compatible brands: iso4
        Created: GMT Tue Jul  9 06:41:04 2019
        Modified: GMT Tue Jul  9 06:41:04 2019

File has no MPEG4 IOD/OD

Track # 1 Info - TrackID 1 - TimeScale 60
Media Duration 00:00:02.033 - Indicated Duration 00:00:02.033
Track has 1 edit lists: track duration is 00:00:02.000
Media Info: Language "Undetermined (und)" - Type "vide:hvc1" - 3 samples
Visual Track layout: x=0 y=0 width=1280 height=720
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x23
HEVC Video - Visual Size 1280 x 720
        HEVC Info: Profile Main @ Level 4 - Chroma Format YUV 4:2:0

        NAL Unit length bits: 32 - general profile compatibility 0x60000000

        Parameter Sets: 1 VPS 1 SPS 1 PPS
        SPS resolution 1280x720
        Bit Depth luma 8 - Chroma 8 - 1 temporal layers
        VPS#1 hash: 404DE42FD661F021A6D65558D6262919A28BB2DC
        SPS#1 hash: C6604209C86D0DA759FA05169E3E7B1DA596A5E6
        PPS#1 hash: 476CC254A14C7C38F1EC443B8C1E3E48B9736FDF

Self-synchronized
        RFC6381 Codec Parameters: hvc1.1.6.L120.90
        Only one sync sample
```
But i'd like to have this as picture items using -add-image so i can open all this later in Gimp for example.

Tried also other things like : 
```
MP4Box -add-image "H:\testvid.hevc":time=-1:hdlr=pict:@@reframer:frames=1000,3000 -ab heic -new "H:\test1.heic"

MP4Box -add-image "H:\testvid.hevc":forcesync:hdlr=pict:@@reframer:frames=1000,3000 -ab heic -new "H:\test1.heic"

MP4Box -add-image "H:\testvid.hevc":forcesync:hdlr=pict:@@reframer:frames=1000,3000 -new "H:\test1.heic"

MP4Box -add-image "H:\testvid.hevc":forcesync:@@reframer:refs=true:frames=1,100,122 -ab heic -new "H:\test1.heic"

MP4Box -add-image "H:\testvid.hevc":forcesync:@@reframer:refs=true:frames=1,100,122  -new "H:\test1.heic"

```

No luck, either error messages or importing only the first frame.

This one import all frames of the input as movie : 
`MP4Box -add "H:\testvid.hevc":forcesync:time=-1:@@reframer:frames=1,100,122 -new "H:\test1.heic" `


Tried many other combinations for the command line, can't get to extract the frames i want with -add-image, not sure if i am doing something wrong or if my video inputs are messed up or if it's something else that i am missing.

Spent time looking the test scripts you put in link, reading the wiki & searching in closed issues but i am now banging my head against a wall with no more ideas of what is going wrong on my tests...

> Tested under win7 x64 using the  console, using various pre-built versions of GPAC 9.x.x from your site and also own built MP4Box using VS2017 and gpac_mp4box_mini.sln under windows.


Thank you.

**Comment by jeanlf** [comment]
Only IDR frames can be added as image items, and the importer complains and fails if one item is not IDR. So very likely your frames 100 and 122 are not IDR. You can check your sap types  using `gpac -i source.hevc inspect:deep` (see [file instpection](https://github.com/gpac/gpac/wiki/inspecting) howto)

**Comment by jalba69** [comment]
That's what i as suspecting :/.

Tried this time indicating the IDR frames correctly and it works, it extracts and add the frames indicated, thanks a lot.

Only remains a small issue:  i can not open the resulting file in Gimp , 

> " Le chargement de l’image HEIF a échoué : Invalid input: No 'pitm' box"

Same trying : 

`MP4Box -add-image "H:\testvid.hevc":time=-1:@@reframer:frames=1,251,501 -ab heic "H:\image.heic"`
 
This said, if i  do the following, first create a initial heic and specify the primary parameter : 

 `MP4Box -add-image "H:\testvid2.hevc":primary -new "H:\image.heic"`
or
`MP4Box -add-image "H:\testvid2.hevc":primary -ab heic "H:\image.heic"`

then add the 3 other IDR's from another vid using  : 

`MP4Box -add-image "H:\testvid.hevc":time=-1:@@reframer:frames=1,251,501 -ab heic "H:\image.heic" `

It works,  i get my 4 items and able to open the resulting file in Gimp ;)

Not sure if it should be like this or not, but better let you know.

Thank you very much for all.

**Comment by jeanlf** [comment]
OK I think we miss a default primary item when importing directly, I'll have a look at it
