### ISSUE TITLE
data codec string got into video codec name in mpd file

### ISSUE THREAD

**Issue by jamichen** [gpac/gpac#1022]
I have this input progressive file(attached), and when I use the following mp4box command to convert it to dash, it gives me this weird codec name for video: codecs="avc1.640015,tmcd"

`MP4Box -dash 2000 -profile dashavc264:onDemand -bs-switching no -rap -frag-rap -out v4_passthrough.mpd v4_passthrough_sd.mp4
`

My player cannot recognize this video codec so it fail to play.
I looked into the input stream, tmcd is the codec_tag_string of the data stream. How could this tag string got into the video codec in mpd? Is there any option to avoid this? 

I use MP4Box - GPAC version 0.7.2-DEV-rev386-gc66782d8-master
[v4_passthrough_sd.mp4.zip](https://github.com/gpac/gpac/files/1835501/v4_passthrough_sd.mp4.zip)

**Comment by rbouqueau** [comment]
How was this file generated? It strongly looks more like an advanced Apple Mov file than MP4.

**Comment by rbouqueau** [comment]
Execute ```MP4Box -diso file.mp4``` and you'll see the list of things that are not handled by MP4Box for this file. MP4Box is one of the most complete tools for MP4 files.

I am trying to understand how this file was generated.

One option could be to remux the elementary streams.

**Comment by jamichen** [comment]
You are right. The original input is quicktime mov format as in ffprobe:

'format' => array (
'tags' => array (
'description' => "This video is about Millenial Creep The Shubies",
'title' => "Millenial Creep The Shubies",
'major_brand' => "qt ",
'minor_version' => "0",
'keywords' => "iMovie",
'compatible_brands' => "qt ",
'creation_time' => "2018-03-13 00:45:40",
),
'format_name' => "mov,mp4,m4a,3gp,3g2,mj2",
'nb_streams' => 3,
'nb_programs' => 0,
'size' => "2802561",
'bit_rate' => "209262",
'filename' => "/dir1/temp-IgVYFifG5G",
'format_long_name' => "QuickTime / MOV",
'start_time' => "0.000000",
'duration' => "107.140367",
'probe_score' => 100,
),

We did a quick remux and generate a mp4 output. What do you think we can do better to avoid this issue?

**Comment by rbouqueau** [comment]
If we know how the original file was generated, that would help proposing a sensible solution.

**Comment by jeanlf** [comment]
The codec string is not "weird", it actually means you have a muxed representation with both avc1 and tmcd tracks.
I would suggest importing only the video track to a new file, and dashing that file.
