### ISSUE TITLE
Linking new file in Ubuntu

### ISSUE THREAD

**Issue by 21praveen** [gpac/gpac#1023]
I added a new module written in c++ inside media_tools folder that I am calling from dash_client in Ubuntu 16.04. I am not able to set correct flags in Makefile in src folder. Can you please tell me the modification that I should do in Makefile to link and compile correctly.

**Comment by rbouqueau** [comment]
If it is in media_tools, then it is not a "module" but simply a file. You need to add it in gpac/src/Makefile.

**Comment by 21praveen** [comment]
That's true. My issue is, Makefile is designed according to c files. My file is a cpp. So when I am adding it to gpac/src/Makefile I am getting errors like " undefined reference to `operator new[](unsigned long)'". Can you please tell me the flags that I need to modify.

**Comment by rbouqueau** [comment]
That's not a GPAC problem, that's a Makefile issue.

At this place you need to add the CPP support: https://github.com/gpac/gpac/blob/master/src/Makefile#L302

```
.deps/%.dep: %.cpp
	@mkdir -p $(dir $@)
	$(CXX) -MM $(CFLAGS) "$<" -MT "$*.o" -MF "$@"
```

**Comment by 21praveen** [comment]
Thanks for the help. 
I am getting same error now as well. 
Do I also need to change:
DEPS := $(SRCS:%.c=.deps/%.dep)

**Comment by 21praveen** [comment]
I realized that to link cpp with c, I need to link all files using $(CXX), i.e. at  https://github.com/gpac/gpac/blob/master/src/Makefile#L302  https://github.com/gpac/gpac/blob/master/src/Makefile#L281 https://github.com/gpac/gpac/blob/master/src/Makefile#L273.
