### ISSUE TITLE
GDB

### ISSUE THREAD

**Issue by swetheendra84** [gpac/gpac#1024]
I am trying to debug gpac code using GDB. I ahve configured with ./configure --enable-debug. After that when I was trying to put break point it is showing **no debugging symbols** found. 
**file bin/gcc/MP4Client** command is also displaying no debugging symbols found. 
How can I resolve this ?

Thanks

**Comment by aureliendavid** [comment]
are you sure you rebuilt it properly after the configure? 

if I try: 

**release build:**
```
$ make clean ; ./configure ; make -j
$ gdb bin/gcc/MP4Client
...
Reading symbols from bin/gcc/MP4Client...(no debugging symbols found)...done.
```

**debug build:**
```
$ make clean ; ./configure --enable-debug ; make -j
$ gdb bin/gcc/MP4Client
...
Reading symbols from bin/gcc/MP4Client...done.
```

it seems to work

**Comment by rbouqueau** [comment]
To check the dependencies, use the ```ldd``` tool. If the libgpac.so used is not in the right folder, you can use ```LD_LIBRARY_PATH``` to tell where you shared libraries are (e.g. LD_LIBRARY_PATH=bin/gcc bin/gcc/MP4Client).

**Comment by swetheendra84** [comment]
Hi Romain/David,
Can you help me to figure out where buffer mangement is done in
dash_client.c. When tiles are downloaded where are they getting stored? If
possible can you specify structure in which buffer exist.

Thanks,
Swetheendra
