### ISSUE TITLE
Why these two files have different IDR and PTS after DASH

### ISSUE THREAD

**Issue by jamichen** [gpac/gpac#1027]
I met many cases which have the same issue as this one:
I have an original video, then 
in path 1, I do a simple remux and get an output (I call 

passthrough_sd.mp4)
in path 2, I do a transcoding with exact IDR alignment as original and get an output (I call passthroughaligned_sd.mp4)
These two output have the exact IDR and PTS info. Run ffprobe, 
`ffprobe -hide_banner -i v4_passthrough_dash.mp4 -select_streams v -show_frames -show_entries frame=key_frame,pict_type,pkt_pts_time -print_format csv | grep 'I'|grep 'frame,1'`

frame,1,0.000000,I
frame,1,1.100000,I
frame,1,2.101667,I
frame,1,3.101667,I
frame,1,4.103333,I

Then I apply mp4box to both outputs with command (I am using MP4Box - GPAC version 0.7.2-DEV-rev386-gc66782d8-master)
`MP4Box -dash 2000 -profile dashavc264:onDemand -bs-switching no -rap -frag-rap -out input.mpd input.mp4
`

I get DASHed files for both, but their IDR and PTS differ
for passthrough_sd.mp4, after DASH, ffprobe show the same as before DASH:
frame,1,0.000000,I
frame,1,1.100000,I
frame,1,2.101667,I
frame,1,3.101667,I
frame,1,4.103333,I

but for passthroughaligned_sd.mp4, it has very different IDR and PTS:
rame,1,0.000000,I
frame,1,1.100000,I
frame,1,2.968333,I
frame,1,3.970000,I

What is it about these two files that result in complete different IDR after DASH? Is there anything I can do in remux stage for the first output to make the IDR align after DASH? Thank you!

[passthroughaligned_sd.mp4.zip](https://github.com/gpac/gpac/files/1869748/passthroughaligned_sd.mp4.zip)
[passthrough_sd.mp4.zip](https://github.com/gpac/gpac/files/1869749/passthrough_sd.mp4.zip)

**Comment by jeanlf** [comment]
The only difference between the dashed and non dashed version are that the DASHed one has the dependsOn flag set to 2 (no dependency = I) for I frames, the rest is the same (sync sample flag at the same place). Maybe an issue in ffprobe ?
