### ISSUE TITLE
Play ERP or other Projection formats by MP4Client.

### ISSUE THREAD

**Issue by JamesXu20150314** [gpac/gpac#1028]
Hello,

Who knows which function I should modify, such as src/compositor/hardcoded_protos.c/TraverseVRGeometry to play ERP or other projection formats?

Thanks,

**Comment by 21praveen** [comment]
https://photos.app.goo.gl/3CrJo5Ijddd0jxoB3

Here are the numbered tiles with/without 360 views. It might help you to understand

**Comment by JamesXu20150314** [comment]
Thank you.

However, I want to modify the code of GPAC. 
So, I want to know where is this source code file?
