### ISSUE TITLE
Question about the generation of tiled HEVC MPEG-DASH content

### ISSUE THREAD

**Issue by GertMoesen** [gpac/gpac#1031]
I’m trying to create a tiled HEVC/H.265 MPEG DASH video that allows for changing quality of a tile in the multi-tiled video.
So far I’m able to play and change the quality of a tile in the demo video provided on: http://download.tsi.telecom-paristech.fr/gpac/SRD/srd_hevc/multi_rate_p60/

I’m creating my own test videos with the commands found in these tutorials:
https://gpac.wp.imt.fr/2017/02/01/hevc-tile-based-adaptation-guide/
https://github.com/gpac/gpac/wiki/Tiled-Streaming

The exact commands I used in order are:
```
.\kvazaar.exe -i test.yuv --input-res 3840x2160 -o output_qp22.hvc --tiles 3x3 --slices tiles --mv-constraint frametilemargin -q 22 --period 24 --input-fps 24`
.\kvazaar.exe -i test.yuv --input-res 3840x2160 -o output_qp37.hvc --tiles 3x3 --slices tiles --mv-constraint frametilemargin -q 37 --period 24 --input-fps 24`
MP4Box -add output_qp22.hvc:split_tiles -fps 24 -new output_qp22.mp4
MP4Box -add output_qp37.hvc:split_tiles -fps 24 -new output_qp37.mp4
MP4Box -dash 5000 -rap -frag-rap -profile live -out .\two_qualities\dash_tiled.mpd output_qp22.mp4 output_qp37.mp4
```

When I run my own generated content in the player and change the quality of one tile (tile 6 in this case) I get this as a result:
![capture2](https://user-images.githubusercontent.com/32326528/38548229-8b647310-3cb1-11e8-8f53-8c7003284500.PNG)

Am I using a wrong setting when generating the content? What am I doing wrong while generating the content? I also noticed that in the provided demo there is only one track1 while my generated content has 2 in the MPEG-DASH context.

Any help is much appreciated.

Tested versions:
Kvazaar 1.1.0
MP4Box - GPAC version 0.7.0-rev0-gbd5c9af-master
MP4Box - GPAC version 0.7.2-DEV-rev449-g4c3f4423-master
I get not errors/warnings while generating the content. All commands are executed on Windows 64-bit.

**Comment by 21praveen** [comment]
Which player are you using?? Sometimes there is a decoding issue with MP4Client if you set the quality using **-q**. Instead, use **bitrate** The image doesn't seem like MP4Client.

**Comment by jeanlf** [comment]
regarding QP: changing the value used by kvazaar will result in PPS having different initial QPs, and therefore PPS not compatible per different tile quality, so different qualities of tiles can no longer be mixed. Setting the same QP adjusting the bitrate won't have that effect.
Also be carefull of the order of the tile when you remux, they have to be in raster scan order in the bitstream for most decoder to accept them.
HTH

**Comment by cavalieronly727** [comment]
How did you play and change the quality of the tiles provided in the following example video: http://download.tsi.telecom-paristech.fr/gpac/SRD/srd_hevc/multi_rate_p60/

**Comment by alstj908** [comment]
> 다음 예제 비디오에 제공된 타일의 품질을 어떻게 재생하고 변경 했습니까? http://download.tsi.telecom-paristech.fr/gpac/SRD/srd_hevc/multi_rate_p60/ Did you solve it? If you did, can I know how?
