### ISSUE TITLE
Question: Is it possible to stream 3gpp-tt via rtp with MP4Box

### ISSUE THREAD

**Issue by middleLB** [gpac/gpac#1036]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

-] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
yes tx3g (and apple tt) are supported by the streamer and the hinter

**Comment by middleLB** [comment]
Give that the answer to that question is yes, then I need to understand why
I cant seem to get it to work. The sequence of steps I tried are listed
below

 1) MP$Box -add sample.srt guardians.mp4
 2) MP4Box -hint guardians.mp4
 3) MP4Box guardians.mp4 -rtp -dst-rtp 235.10.11.12:1234

 I get the following errors when I attempt to stream

    Could not initialize RTP streamer: No error
    Cannot create file streamer
