### ISSUE TITLE
Encrypting encrypted file should fail with an error message

### ISSUE THREAD

**Issue by cconcolato** [gpac/gpac#1039]
If you happen to run twice a command like:
MP4Box -add file.264 -crypt drm_file.xml out.mp4
The second time, it fails with a "Bad Parameter" error, while it could fail with an error message: "Trying to encrypt an already encrypted track".

**Comment by rbouqueau** [comment]
I've added a clearer error message.

Now I get:
```
VC-H264 import - frame size 128 x 128 at 25.000 FPS
AVC Import results: 173 samples (178 NALUs) - Slices: 2 I 96 P 75 B - 0 SEI - 2 IDR
[iso file] cannot set protection entry: file is already encrypted.

        Error: Bad Parameter
```

Please close if ok.
