### ISSUE TITLE
MP4box visualProfileLevelIndication and audioProfileLevelIndication changing?

### ISSUE THREAD

**Issue by richardbushell** [gpac/gpac#104]
Hi Jean

Sorry, I saw you closed this issue but we still have an issue. Is there a way to re-open an issue my end? Anyway, I've posted this as a new issue in case closed comments aren't seen.

Using the same original file as before, located here: http://living.tv/mob/ibeani_i4_mcstdlow.mp4

The DASH Conformance Validator got past the original warning, but now says:
Validate_IODS: visualProfileLevelIndication ( IOD: 127 (0x7f) ) signalled .. but there seems to be no video track

Also the Audio error is thrown:
Validate_IODS: ISMA expects no-capability(0xFF) or Hi-Quality@L1/L2 (0x0E, 0x0F) or AAC@L4 (0x2a) or HE-AAC@L2 (0x2c) for audioProfileLevelIndication.

Both were 255 in the original. The audio is AAC LOW.

Richard

**Comment by jeanlf** [comment]
see #102
