### ISSUE TITLE
SENC differences when using different sized encryption IVs

### ISSUE THREAD

**Issue by meflynn32684** [gpac/gpac#1040]
I'm using mp4box to create cenc encrypted dash stream.  I have noticed that the SENC box is generated differently for audio segments depending on what size IV I use and I was hoping I could get feedback on why.

I'm using the latest dev nightly: 0.7.2-DEV-rev459-g07f44028-master
I saw same behavior with version 0.6.0 as well

**First case: 128bit IV**

Crypt.xml:

    <?xml version="1.0" encoding="UTF-8" ?>
        <GPACDRM type="CENC AES-CTR">
            <DRMInfo type="pssh" version="0">
                <BS ID128="EDEF8BA979D64ACEA3C827DCD51D21ED"/>
                <BS data64="AAAAQ3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAACMSEPPF4DYeZlSyj4BJx3iyOUYiD3Rlc3QgY29udGVudCBpZA=="/> 
           </DRMInfo>
           <CrypTrack trackID="1" IsEncrypted="1" IV_size="16" first_IV="0x12345678123456781234567812345678" saiSavedBox="senc">
                <key KID="0xf3c5e0361e6654b28f8049c778b23946" value="0xa4631a153a443df9eed0593043db7519"/>
            </CrypTrack>
    </GPACDRM>

Mp4Box Commands:

    $ MP4Box -crypt crypt.xml -out ${OUTPUT_DIR}/96kps.aac input/96kps.aac
    $ MP4Box -crypt crypt.xml -out ${OUTPUT_DIR}/256kps.aac input/256kps.aac
    $ MP4Box -dash ${DURATION_MS} -segment-name segment_%s -out ${OUTPUT_DIR}/output.mpd ${OUTPUT_DIR}/256kps.aac ${OUTPUT_DIR}/96kps.aac

In this setup with 128bit IV I get a SENC that has subsample decryption disabled (flags != 0x2) and I just have a list of IVs for each sample in the segment.  This is what I would expect, the binary looks like:

`73 656e 6300 0000 0000 0000 d712 3456 7812 3456 7812 3456 7812 3456 7812 3456 7812 3456 7812 3456 7812 3456 8d`

The above translates to:

    senc header: 0x73656e63
    flags: 0x0
    Num Samples: 0xd7
        Sample IV: 0x12345678123456781234567812345678
        Sample IV: 0x1234567812345678123456781234568d

**Second case: 64bit IV**

Crypt.xml:

    <?xml version="1.0" encoding="UTF-8" ?>
        <GPACDRM type="CENC AES-CTR">
            <DRMInfo type="pssh" version="0">
                <BS ID128="EDEF8BA979D64ACEA3C827DCD51D21ED"/>
                <BS data64="AAAAQ3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAACMSEPPF4DYeZlSyj4BJx3iyOUYiD3Rlc3QgY29udGVudCBpZA=="/> 
           </DRMInfo>
           <CrypTrack trackID="1" IsEncrypted="1" IV_size="8" first_IV="0x22ee7d4745d3a26a" saiSavedBox="senc">
                <key KID="0xf3c5e0361e6654b28f8049c778b23946" value="0xa4631a153a443df9eed0593043db7519"/>
            </CrypTrack>
    </GPACDRM>

Mp4Box Commands:

    $ MP4Box -crypt crypt.xml -out ${OUTPUT_DIR}/96kps.aac input/96kps.aac
    $ MP4Box -crypt crypt.xml -out ${OUTPUT_DIR}/256kps.aac input/256kps.aac
    $ MP4Box -dash ${DURATION_MS} -segment-name segment_%s -out ${OUTPUT_DIR}/output.mpd ${OUTPUT_DIR}/256kps.aac ${OUTPUT_DIR}/96kps.aac

In this setup with 64bit IV I get a SENC that has subsample decryption enabled (flags == 0x2).  I see an subsample encryption array for each sample with a single entry that lists 0 unencrypted bytes and all protected bytes.  Example Binary is:

`73 656e 6300 0000 0200 0001 ae22 ee7d 4745 d3a2 6a00 0100 0000 0002 e722 ee7d  4745 d3a2 6b00 0100 0000 0002 e7`

The above translates to:

    senc header: 0x73656e63
    flags: 0x2
    Num Samples: 0x1ae
        Sample IV: 0x22ee7d4745d3a26a
        Subsample Count: 0x1
            BytesOfClearData: 0x0
            BytesOfProtectedData: 0x2e7
        Sample IV: 0x22ee7d4745d3a26b
        Subsample Count: 0x1
           BytesOfClearData: 0x0
           BytesOfProtectedData: 0x2e7

So as you can see the 64bit IV is causing subsample encryption to be enabled and I don't understand why.

Can you please explain this difference?

Thanks

**Comment by jeanlf** [comment]
I cannot reproduce this with current git and simple aac file. Could you share your source ?
