### ISSUE TITLE
MP4Box is unable to mux idx/sub extracted by MkvExtract

### ISSUE THREAD

**Issue by SelfDestructor** [gpac/gpac#1044]
MP4Box says VobSub subtitles extracted from MKV files by MkvExtract has corrupted data and is not able to import/mux the subtitles.

This can be replicated by using any MKV file with VobSub subtitles and extracting them with MkvExtract, then using MP4Box to add the subtitle to a new or existing MP4 file.

>PS E:\Movie Rips\The Tribe\Season 1\myspaf5j.2c5> .\mkvextract.exe tracks '.\The Tribe S01E01 - Episode 1.mkv' 2:subtitle
>Extracting track 2 with the CodecID 'S_VOBSUB' to the file 'subtitle.sub'. Container format: VobSubs
>Writing the VobSub index file 'subtitle.idx'.
>Progress: 100%
>PS E:\Movie Rips\The Tribe\Season 1\myspaf5j.2c5> .\MP4Box.exe -add .\subtitle.idx test.mp4
>VobSub import - subpicture stream 'nor'
>Corrupted data found in file .\subtitle.sub
>Error importing .\subtitle.idx: Bad Parameter
>PS E:\Movie Rips\The Tribe\Season 1\myspaf5j.2c5> 

I've downloaded the latest GPAC, gpac-0.7.2-DEV-rev461-g01391a0c-master-x64 from the download page.
MkvToolNix/MkvExtract is version v22.0.0 ('At The End Of The World') 64-bit.
OS is Windows 10 64 bit version 1709 build 16299.371.

This issue is also reported to MKVToolNix.

**Comment by rbouqueau** [comment]
Hi,

Thanks for following up of this. If you provide us with a sample, we'll fix it in MP4Box as well. We have an anonymous dropbox if needed (let us know here if you upload a file): https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by SelfDestructor** [comment]
A zip file named "1044 SelfDestructor - Sample files" has been uploaded. It includes the idx/sub files extracted with MkvExtract v22 as well as an MKV file with the subtitles so you can extract it yourself if needed.

**Comment by rbouqueau** [comment]
Thank you. Should be fixed. Please re-open if needed.
