### ISSUE TITLE
[MP4Box] 8 byte initialization vectors (IVs) must be allowed for cbc1 CENC content.

### ISSUE THREAD

**Issue by vladimir-kazakov** [gpac/gpac#1048]
MP4Box doesn't allow using 8 byte IVs while creating cbc1 content:
https://github.com/gpac/gpac/blob/02582a2236cb384d65442cc9856c3bc6cb993f3c/src/media_tools/ismacryp.c#L229

As a result, the warning `[CENC] Using AES-128 CBC: IV_size should be 16` is being shown, and MP4Box switches to using 16 byte IVs.

I guess this limitation comes from the second edition of the CENC standard. That being said, in the third version of the CENC standard, there's no such limitation anymore. According to the section 10, both 8 and 16 byte IVs are allowed for all protection schemes (cenc, cens, cbc1 and cbcs).

**Comment by jeanlf** [comment]
fixed, thanks for the report
