### ISSUE TITLE
[HLS] Starting in paused state.

### ISSUE THREAD

**Issue by canatella** [gpac/gpac#105]
Hello,

I'm trying to implement pause/play correctly and I notice this, when using

    gf_term_connect_from_time(term, url, 0, GF_TRUE);

and later do a

    gf_term_set_option(term, GF_OPT_PLAY_STATE, GF_STATE_PLAYING);

the stream does not play. It's reproducible on pc using the -pause option, when connected, pressing p in the terminal does not start the stream.

**Comment by nguyen-viet-thanh-trung** [comment]
It should be fixed !
