### ISSUE TITLE
[MP4Box] How to merge tiles into a segment?

### ISSUE THREAD

**Issue by MariaTV** [gpac/gpac#1051]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/
Hello,

For a project on adaptive 360 VR video streaming, I want to be able to merge the tiles of each segment back together into a full segment before displaying at the client. 

To achieve this, I have encoded, tiled and dashed the video following these instructions (https://github.com/gpac/gpac/wiki/Tiled-Streaming). I have dashed a video of 10 seconds, 4 tiles and segments of 1 second. I have obtained a set of 5 init files (set1_init.mp4, track2_init.mp4, track3_init.mp4, track4_init.mp4) and a set of files with the extension .m4s corresponding to tile number and segment (for example, video_1_dash_track1_1.m4s). 

The next step is to merge the tiles back into a video. I had expected to have an mp4 init file per segment and a set of m4s tiles, concatenate them with a cat command, extract the hevc with the raw command and repackage in MP4Box. However, I don't know how to do this with all the init files or which ones to use. I have had an extensive look for an explanation of the working principles of this but I have not succeeded so far. 

 Does anyone have a suggestion on how to manually merge the tiles back together into a playable segment?

Thank you,
Maria

**Comment by 21praveen** [comment]
There is a minor issue with the details on https://github.com/gpac/gpac/wiki/Tiled-Streaming. Don't use **-q** to set quality level. Instead use **-bitrate**. MP4Client automatically merge the tiles before rendering.
**MP4Client http://url/file.mpd#360**  
If you want to merge the tiles manually using your own player, it could be difficult, as decoder would need hardware support. Other than that, all tiles are dependent on tile 1 for decoding in each segment. So when you create 4 tiles, you will get one additional tile file that is required for decoding of all the other tiles in each segment. Take care of that.

**Comment by jeanlf** [comment]
Merging can be done manually using MP4Box. You need to remove the desired tile track (say 4) from the aggregated Q1 file :
`MP4Box -rem 4 Q1.mp4`

and add the track from the other aggregated Q2 file with the right references:
 
`MP4Box -add Q2.mp4#6 -ref 4:tbas:1 -ref 1:sabt:6 Q1.mp4`

And then dump the tile base track (usually 1) 
`MP4Box -raw 1 Q1.mp4`

Be carefull we don't reorder tiles in the file during the extraction so a decoder may not accept such a bitstream (openHEVC / ffmpeg does, most HW decoders won't accept it).
To avoid that, you will have to add one by one all the tile tracks from Q1 and Q2

**Comment by AnatoliyZabrovskiy** [comment]
`MP4Box -add Q2.mp4#6 -ref 4:tbas:1 -ref 1:sabt:6 Q1.mp4`

Can you explain these options "#6 -ref 4:tbas:1 -ref 1:sabt:6"? I try to merge tiles with different qualities, but it doesn't work. Thanks!

**Comment by jeanlf** [comment]
This is used to resetup the track reference between the tile base track (type hev2/hvc2) and the tile track (sorry there was a typo in the :sabt: track ref, now fixed)

**Comment by wuchlei** [comment]
@MariaTV Hi, maria,
Have  you been able to solve this problem?
I also don't know how to pack separated tiles into one mp4 file.

**Comment by wuchlei** [comment]
@jeanlf 
Hi, jean
I don't think your answer solved the problem.
I'm also having trouble merge tiled dash segments back into a playable video, i.e., combining tiled_set1_init.mp4, sample_dash_track*_*.mp4 and sample_dash_track*_*.m4s into a single playable file.
