### ISSUE TITLE
DashCast appears to hang, no output generated

### ISSUE THREAD

**Issue by wedgef5** [gpac/gpac#1054]
I am trying to run DashCast in low-latency mode on RHEL 7.3 Server to capture output from an Epiphan capture device. It appears to hang, and no output is created.

Command line...

DashCast -vf video4linux2 -v4l2f yuv420p -vfr 25 -vres 2560x1440 -v /dev/video0 -conf dashcast.conf -low-delay -frag 200 -insert-utc -seg-marker eods -min-buffer 0.2 -ast-offset -800 -pixf yuv420p -live

Output...

MPD refresh time not set in live - defaulting to segment duration
Options:
    video source: /dev/video0
    video format: video4linux2
    v4l2 format: yuv420p
    video framerate: 25
    video resolution: 2560x1440
    video crop: 0x0
    audio source: 
Configurations:
    id:v1	res:1920x1080	vbr:800000
[video4linux2,v4l2 @ 0x6cdf40] Dequeued v4l2 buffer contains corrupted data (0 bytes).
Input #0, video4linux2,v4l2, from '/dev/video0':
  Duration: N/A, start: 0.000000, bitrate: 1105920 kb/s
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 2560x1440, 1105920 kb/s, 25 fps, 25 tbr, 1000k tbn, 1000k tbc
AVCTX give frame duration of 1/25 - keeping requested rate 25, but this may result in unexpected behaviour.
Error while decoding video.
An error occurred while reading video frame.

DashCast appears to hang at this point with nothing being written to the output directory. When I press 'q' to quit, I get this...

q
Keyboard thread exit
Duration: PT00H00M00.000S
Video scaler got an end of input tbuffer!
Press q or Q to exit...
[libx264 @ 0x7f1144000940] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
[libx264 @ 0x7f1144000940] profile High, level 4.0
Cannot parse AVC/H264 SPS/PPS
Bad Parameter: dc_gpac_video_write_config
Bad Parameter: gf_isom_start_segment
Cannot open output video file.

The ffmpeg against which I built gpac will stream this device OK. I have tried both with and without the -pixf switch, and it makes no difference.

Any suggestions?

**Comment by jeanlf** [comment]
dashcast is deprecated, please use GPAC 0.9.0
