### ISSUE TITLE
Query: Parallel download of segments

### ISSUE THREAD

**Issue by 21praveen** [gpac/gpac#1055]
Is there an existing module for parallel download of multiple video segments?

**Comment by 21praveen** [comment]
While streaming Tiled HEVC, many tiles are very small in size and suffer from the slow start of TCP resulting in low throughput download. GPAC use the same socket to mitigate the issue, but still, throughput tends to be very low. I am trying to start the download of multiple of tiles in parallel to see if we can improve the throughput.

**Comment by jeanlf** [comment]
have you tried using the DASH:ThreadedDownload option ?

**Comment by 21praveen** [comment]
@jeanlf Yeah, I tried  **dash_download_threaded**. But it calls **dash_download_group** once for entire group from where all tiles get downloaded sequentially.

**Comment by jeanlf** [comment]
yes dependent groups, just like complementary reps, can only be processed once all the dependencies are downloaded, so the code doesn't offer the possibility to download in parallel dependent segments. You will need to heavily patch the segment download code for that, not sure if the results are worth it.

**Comment by 21praveen** [comment]
Thanks for the input  :)

**Comment by 21praveen** [comment]
@jeanlf I am able to download the tiles in parallel. The downloader is first downloading tile 1 and 2  in sequence as they are required for decoding of other tiles. Then, I am downloading other tiles in parallel. But while decoding, only tile 2 (i.e. the first visible tile) is only getting displayed. I checked that all tiles (sequential and parallelly downloaded) are downloaded successfully and the buffer is updated. 
Do you have any idea what might be going wrong?
