### ISSUE TITLE
JS API Problem

### ISSUE THREAD

**Issue by JamesXu20150314** [gpac/gpac#1057]
Hello,

Who knows what is the reason for the following error:

![image](https://user-images.githubusercontent.com/11470231/40056932-62864b14-587f-11e8-99d0-becc5d90896d.png)

I use Xcode 9.3.1 to build the GPAC project. How can I fix it.
Here is my libmozjs185 path:

![image](https://user-images.githubusercontent.com/11470231/40057245-49bad8a6-5880-11e8-8068-f6a67ead2cbf.png)

Thanks,
James Xu.

**Comment by jeanlf** [comment]
the install path for spidermonkey on OSX is assumed to be in /opt/local/  change libgpac xcode proj settings to fit your install
