### ISSUE TITLE
Crash for MP4Client

### ISSUE THREAD

**Issue by JamesXu20150314** [gpac/gpac#1058]
Hello,

Who knows why the procedure will crash when I play dash_tile.mpd (for tile-based 360 video).
As follows:
![image](https://user-images.githubusercontent.com/11470231/40184719-84f92f72-5a23-11e8-89f7-a7f3d8854817.png)

I use Xcode 9.
The MPD file looks like this:

![image](https://user-images.githubusercontent.com/11470231/40184933-06e8eb9e-5a24-11e8-8c1c-1e0b58a21efb.png)

Thanks.

**Comment by JamesXu20150314** [comment]
Helle Jeanlf,

Here is my MPD file: [http://www.xuzhimin.cc/Segments/Source-ERP-2304x1152.mpd](http://www.xuzhimin.cc/Segments/Source-ERP-2304x1152.mpd)

Here are my tiles and segments. [http://www.xuzhimin.cc/Segments/](http://www.xuzhimin.cc/Segments/)

Thanks.

**Comment by jeanlf** [comment]
Which platform / gpac version are you using ? Your content plays fine here, both 2D and VR

**Comment by JamesXu20150314** [comment]
I am using the [master branch](https://github.com/gpac/gpac) of GPAC in Xcode 9. It can play my contents well, both 2D and VR. 
However, it also encountered some other problems. Such as follows (I am trying to solve it):
![image](https://user-images.githubusercontent.com/11470231/40362588-8a505dd0-5dff-11e8-94db-3cd8fdbb10f9.png)

(When I only play Field-of-View (FOV) tiles).

Thank you.
