### ISSUE TITLE
DashCast unstable, stops generating content after a few hours

### ISSUE THREAD

**Issue by Jamie0** [gpac/gpac#1062]
When using DashCast for long periods, it eventually will stop working. The stream can originally be played in dash.js, but after a few hours it stops being playable. dash.js will HTTP request and load the segments closest to bleeding-edge/live, and then for some reason seek back about 10 minutes and load segments from then. In neither cases is any content playable. The stream is audio-only. 

We're launching DashCast with this command:
`/usr/bin/DashCast -a "$URI" -live -conf /dashcast.conf -out /srv/dash -time-shift 300 -seg-dur ${DASH_SEGLENGTH} -frag-dur ${DASH_SEGLENGTH} -mpd ${INGEST_NAME}.mpd`

Where:
- URI is an Icecast stream, but the issue seems apparent when using other ffmpeg connections, formats, and codecs. The input is stable and realtime. 
- DASH_SEGLENGTH is 5000 (5s)

In this cast, dashcast.conf looks like:

    [a256]
    type=audio
    bitrate=256000
    [a128]
    type=audio
    bitrate=128000

We're compiling DashCast against ffmpeg 3.3, all within a Docker container. This is available at https://github.com/InsanityRadio/AudioEngine/blob/a61b682246f481dd018f66ed134b51de6059a065/docker/dash/Dockerfile, so replicating the exact environment should be very straightforward. 

According to logs, 

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...).

**Comment by jeanlf** [comment]
dashcast is deprecated, please use 0.9.0
