### ISSUE TITLE
MP4Box issues warning when 'sdtp' box is present in 'traf'

### ISSUE THREAD

**Issue by cconcolato** [gpac/gpac#1064]
The current code defines the 'sdtp' box as a child of 'stbl' only:
https://github.com/gpac/gpac/blob/71effb905f13152cb29406fa84eb12b599e1e3dd/src/isomedia/box_funcs.c#L845
In PIFF files, 'sdtp' is allowed in 'traf', according to https://go.microsoft.com/?linkid=9682897. We should allow that.

**Comment by jeanlf** [comment]
hmm no I don't think we should, this clearly is a mistake from their spec: the sdtp box carries exactly the same info as the traf sample flags (is_leading, depends_on, is_depended_on and has_redundancy); this introduces a duplication of info, which one to trust, trun or sdtp ?

**Comment by rbouqueau** [comment]
It seems like PIFF is not as ISOBMFF-compliant as we thought. Same as QT. Couldn't we have different rules here?
