### ISSUE TITLE
print statistics shown by MP4Client GUI to a txt file

### ISSUE THREAD

**Issue by yuqijin** [gpac/gpac#1069]
Hi, I am running GPAC version 0.7.2-DEV on Ubuntu 16.04(64 bits), and I compiled it by myself. 
For research purpose, I want to print the statistics such as the "buffer", "rate", "quality" etc. of the videos, which can be shown through GUI when I run the MP4Client, to a txt file. I think it should be easier if I change the gui javascript code to implement this feature, but I just found I cannot open the filesystem and write anything to the local files by changing the javascript code. Does anyone has some suggestions to help me with this implementation? Thanks!

**Comment by jeanlf** [comment]
Each module of the GUI has its own storage space, located in .gpac/Storage/

I would recommend dumping the stats to json, and do (cf extensions/player/playlist.js)
`this.extension.set_option("Stats", json_string)`
