### ISSUE TITLE
MP4Box mini - Compilation warning "C4018" in VS2017 

### ISSUE THREAD

**Issue by jalba69** [gpac/gpac#1072]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

-------------------
Hello,

Trying to compile MP4_mini ( release for win x64 ) using **\gpac\build\msvc14\gpac_mp4box_mini.sln** 
from latest version " **0.7.2-DEV-rev554-gb58ae1a78-master** " 
with _Microsoft Visual Studio Community 2017, Version 15.7.3, VisualStudio.15.Release/15.7.3+27703.2026_

Importing the .sln file above, then targeting "Visual Studio 2017(v141)" and "SDK 10.0.17134.0" as i don't have v140 installed.

All seems to compile fine but i get this warning : 
> Avertissement	C4018	'<' : incompatibilité signed/unsigned	libgpac	h:\gpac\src\media_tools\dash_segmenter.c	778	

picture ( click to enlarge ) :
![2018-06-03_083330](https://user-images.githubusercontent.com/15131985/40884014-c1092316-670a-11e8-8207-e200436bbfef.png)

Warning leads to this : [docs.microsoft.com](https://docs.microsoft.com/fr-fr/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4018?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DFR-FR%26k%3Dk(C4018)%26rd%3Dtrue)

Not sure if it's important or not, i am not a coder, can compile simple stuff but that's pretty much all i can do when it comes to this, didn't had such warnings previously on the mp4box_mini versions i compiled using the same steps.

I have not yet tested much the compiled .exe for now, seems to work for the stuff i do, but the file reported in the warning is for the dash_segmented apparently and i don't use those functions in mp4box so...

Probably not important or a big deal but i prefer to let you know just in case.

Thank you.

**Comment by aureliendavid** [comment]
you can indeed ignore it

it will be fixed along with other commits but it won't impact your usage 

thanks for the report
