### ISSUE TITLE
How to get the tile index in the FoV at Android Osmo4 while playing 360 dash video?

### ISSUE THREAD

**Issue by xgw** [gpac/gpac#1073]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [√] I looked for a similar issue and couldn't find any.
- [√] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [√] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I have built a Osmo4 player on my Android phone(Nexus5 Android 7.1), and wanna use it to play 360 tiled dash video. It works but I don't know how to get the tile(adaptation) index. It's important for my current work so I wanna ask how to get the information of the tiles in Field-of-View?
Truly thanks!

**Comment by jeanlf** [comment]
I assume you use tiles and SRD to rebuild the sphere -  the tile visibility is computed in function TraverseVRGeometry, src/compositor/hardcoded_protos.c. The info is then send back to the dash client engine via a GF_NET_CHAN_VISIBILITY_HINT event processed in modules/mpd_in/mpd_in.c

**Comment by ceiliafneg** [comment]
I can't find function TraverseVRGeometry in version 0.9.0-DEV. Would you tell me where id the function code in version 0.9.0-DEV?
