### ISSUE TITLE
mp4box produces file with wrong duration when changing par

### ISSUE THREAD

**Issue by unconnected** [gpac/gpac#1075]
I use mp4box to change the par of a mp4 which I've recorded from a rtmp stream with vlc. Everything works fine with the vlc 2.x branch, but when changing the par of a video which I've recorded using the vlc 3.x branch, the mp4 file produced by mp4box has a duration of over half an hour, while the video is only a few seconds. I tried the last (dev-master) version of mp4box, but the output is the same. Maybe someone knows what's going on?

Here are the test files. This one works perfectly (recorded using vlc 2.x):

http://www.unconnected.nl/vlc-recordings/vlc-2-recording.mp4

this is the file after running mp4box using (note that this video plays with the correct aspect ratio)
> mp4box vlc-2-recording.mp4 -par 2=4:3

http://www.unconnected.nl/vlc-recordings/vlc-2-recording-after-mp4box.mp4

this file is recorded using vlc 3.x and when running the same mp4box command, the output file will have a duration of over half an hour:

http://www.unconnected.nl/vlc-recordings/vlc-3-recording.mp4
http://www.unconnected.nl/vlc-recordings/vlc-3-recording-after-mp4box.mp4

when you look at the generated file, the audio and video track now also has different lengths:

Found 2 Tracks
Track 1:
  flags:        1 ENABLED
  id:           1
  type:         Audio
  duration: 13952 ms
  language: und
  media:
    sample count: 218
    timescale:    16000
    duration:     223232 (media timescale units)
    duration:     13952 (ms)
    bitrate (computed): 32.000 Kbps
  Sample Description 0
    Coding:      mp4a (MPEG-4 Audio)
    Stream Type: Audio
    Object Type: MPEG-4 Audio
    Max Bitrate: 35250
    Avg Bitrate: 32000
    Buffer Size: 1048576
    Codecs String: mp4a.40.2
    MPEG-4 Audio Object Type: 2 (AAC Low Complexity)
    MPEG-4 Audio Decoder Config:
      Sampling Frequency: 16000
      Channels: 1
    Sample Rate: 16000
    Sample Size: 16
    Channels:    1
Track 2:
  flags:        1 ENABLED
  id:           2
  type:         Video
  duration: 2290189 ms
  language: und
  media:
    sample count: 347
    timescale:    90000
    duration:     1249200 (media timescale units)
    duration:     13880 (ms)
    bitrate (computed): 200.174 Kbps
  display width:  469.000000
  display height: 288.000000

Is there a way to keep the correct video length? Or is there something vlc does wrong?

**Comment by jeanlf** [comment]
The vlc-3-* video track indicates an edit list with duration of ~38 minutes, while the v2-* has an edit list indicating a duration of ~8 sec. When remuxing, MP4Box uses information from edit list when present to update the track header duration, this explains your results. I don't think there is anything wrong with MP4Box here.
