### ISSUE TITLE
Generating IDs for AdaptationSets

### ISSUE THREAD

**Issue by BucherTomas** [gpac/gpac#1078]
Would it be possible to start adding ids to AdaptationSets the same way they are being added to Representations , i.e. `<AdaptationSet id="1" segmentAlignment="true" ...>` ?

The purpose is to have the ability to utilize `urn:mpeg:dash:adaptation-set-switching:2016` supplemental property which references AdaptationSet ids in order to group content from different adaptation sets together as per section _3.8. Switching across Adaptation Sets_ in DASH-IF specs.

**Comment by jeanlf** [comment]
this i snow supported in GPAC 0.9.0 through the `ASID`property
