### ISSUE TITLE
Split MCTS HEVC tiles into different tracks/file

### ISSUE THREAD

**Issue by bayirp** [gpac/gpac#1079]
I tried to split the HEVC frames with multiple motion constrained tiles (one slice for all tiles) and it does not work. It works only when each tile has one slice. Please let me know if just tiles can be split up.
Also, is it possible to just get the split tiles instead of writing them into mp4 tracks?

**Comment by jeanlf** [comment]
at te current time there is not bitstream rewrite of any kind, so you must have one or more slice per tile for this to work; N tiles contained in a single slice cannot be split
