### ISSUE TITLE
[HLS] No GF_EVENT_EOS received after playing and then seek till the end

### ISSUE THREAD

**Issue by canatella** [gpac/gpac#108]
Start a HLS stream, let it play for 5 seconds then seek at the end of the stream. The GF_EVENT_EOS is never received. Here with a test stream of 1385 seconds:

    Osmo4 -exit http://...
    Using config file in /Users/dam/.gpac directory
    System info: 16384 MB RAM - 8 cores
    Modules Found : 33
    Loading GPAC Terminal
    Terminal Loaded in 110 ms
    Opening URL http://...
    Service Connected

[wait 5 seconds]

    T
    Duration: 00:23:05.000 - Current Time: 00:00:04.096
    Enter seek time (Format: s, m:s or h:m:s):
    1370
    [socket] cannot select, BAD descriptor

and the application never exits. It seems it behave as if the seek time was relative but from what I understand, it should be absolute: if I repeatedly seek to 1 second in the stream it always restart at 1 second.

**Comment by nguyen-viet-thanh-trung** [comment]
fixed now
