### ISSUE TITLE
Encrypting with multiple mp4box instances in parallel creates corrupted files

### ISSUE THREAD

**Issue by sandersaares** [gpac/gpac#1083]
If I start 10 instances of mp4box in parallel to encrypt different tracks, I end up with corrupted files. All of these files are encrypted with no problem if I process them sequentially.

The problem goes away if I give a unique `-tmp` path to each instance, so it seems that there is some conflict with the temporary files written to `%TEMP%`.

Tried some build from the last 14 days (the one with all the `cbcs` fixes), on Windows 10.

Crypt.xml used (same for all tracks):

```
<GPACDRM type="cbcs">
  <CrypTrack trackID="1" IsEncrypted="1" saiSavedBox="senc" skip_byte_block="9" crypt_byte_block="1" constant_IV_size="16" constant_IV="0x56E67A0691920986A83C7BCD59800251">
    <key KID="0x1C82A777296D49C4AAF5E7381E37DB6B" value="0xB2F89E509678A0EF924D90ED0FD3C02B" />
  </CrypTrack>
</GPACDRM>
```

**Comment by aureliendavid** [comment]
hm, it's very possible that we have tmp files collisions 

to be sure about your use case though, can you give details on the commands you're using for the test? 

thanks

**Comment by sandersaares** [comment]
The command is just `-crypt crypt.xml input.mp4 -out out.mp4`

I notice the filenames do not appear to have all that much randomness in them (lots of zeroes, even many similar bytes in the different filenames): https://i.imgur.com/PIoeAUS.png

**Comment by aureliendavid** [comment]
I can't seem to be able to reproduce it yet. 

Some questions to narrow it down: 

 * the image of your previous post is taken when using `-tmp` right?
 * are you using an installer or a custom build?
 * are you launching from cmd/cygwin/powershell/other?
 * how are you launching multiple instances in parallel?
 * when not using `-tmp`, if you add `-logs core@info` to the command line do you see a line that says: `[Win32] system failure for tmpfile(): 0x00000005`?
 * does the problem still exists if you execute from an elevated prompt?
 * when you says "tracks", are you encrypting different input files or different tracks of the same input file?
 * what's the content of your TMP and TEMP environment variable?
 * how do you see that the resulting files are corrupted? (is it just that -decrypt fails?)


thanks

**Comment by sandersaares** [comment]
> the image of your previous post is taken when using -tmp right?
Right.

> are you using an installer or a custom build?
Installer.

> are you launching from cmd/cygwin/powershell/other?
Launching programmatically by creating mp4box.exe processes using .NET Framework APIs.

> how are you launching multiple instances in parallel?
Doing multiple calls to .NET `Process.Start()` API.

> when not using -tmp, if you add -logs core@info to the command line do you see a line that says: [Win32] system failure for tmpfile(): 0x00000005?
I will check and report back.

> does the problem still exists if you execute from an elevated prompt?
I will check and report back.

> when you says "tracks", are you encrypting different input files or different tracks of the same input file?
Different input files.

> what's the content of your TMP and TEMP environment variable?
Both point to `C:\Users\saares\AppData\Local\Temp`

> how do you see that the resulting files are corrupted? (is it just that -decrypt fails?)
Failure to play back in iOS Safari browser.

I will give it a try and see if I can come up with some easy repro for you and fill in more of the blanks.

**Comment by sandersaares** [comment]
> when not using -tmp, if you add -logs core@info to the command line do you see a line that says: [Win32] system failure for tmpfile(): 0x00000005?

Yes. This line is visible in the log of all tracks.

> does the problem still exists if you execute from an elevated prompt?

No. Also, the log line mentioned above is no longer present.

I confirm that `-decrypt` is a good way to observe the issue - the outputs from this command are broken when the issue occurs. Here is a PowerShell script that reproduces the issue (at least one of the decrypted outputs is broken within the first 10 seconds of content on most of the runs on my PC):

```powershell
param(
    [switch]$useTmp
)

$ErrorActionPreference = "Stop"

$inputFiles = @(
    "V0-video-H264-2160p-6000k.mp4",
    "V0-video-H264-1440p-4500k.mp4",
    "V0-video-H264-1080p-3000k.mp4",
    "V0-video-H264-480p-1200k.mp4",
    "V0-video-H264-360p-800k.mp4",
    "V0-video-H264-288p-400k.mp4",
    "V0-video-H264-720p-2100k.mp4"
)

$inputPaths = $inputFiles | % { Join-Path $PSScriptRoot $_ }
$cryptPath = Join-Path $PSScriptRoot "crypt.xml"
$mp4boxPath = Join-Path $PSScriptRoot "mp4box.exe"

$jobs = @()

Write-Host "Encrypting files"
foreach ($inputPath in $inputPaths) {
    $outputPath = [IO.Path]::ChangeExtension($inputPath, ".encrypted.mp4")
    Remove-Item $outputPath -ErrorAction SilentlyContinue

    $logfile = [IO.Path]::ChangeExtension($inputPath, ".log")
    Remove-Item $logfile -ErrorAction SilentlyContinue

    $args = @("-crypt", $cryptPath, $inputPath, "-out", $outputPath, "-logs", "core@info", "-log-file", $logfile)

    if ($useTmp) {
        $filename = [IO.Path]::GetFileNameWithoutExtension($inputPath)
        $tmpPath = Join-Path $PSScriptRoot "Tmp-$filename"
        Remove-Item $tmpPath -Recurse -Force -ErrorAction SilentlyContinue
        New-Item -ItemType Directory $tmpPath -ErrorAction SilentlyContinue | Out-Null

        $args += "-tmp"
        $args += $tmpPath
    }

    $instance = Start-Process $mp4boxPath -ArgumentList $args -PassThru

    $jobs += @{
        InputPath  = $inputPath
        OutputPath = $outputPath
        Instance   = $instance
    }
}

Write-Host "Waiting for mp4box to finish"
foreach ($job in $jobs) {
    $job.Instance | Wait-Process
}

Write-Host "Decrypting files"
foreach ($job in $jobs) {
    $decryptedPath = [IO.Path]::ChangeExtension($job.InputPath, ".decrypted.mp4")
    Remove-Item $decryptedPath -ErrorAction SilentlyContinue

    Start-Process $mp4boxPath -ArgumentList @("-decrypt", $cryptPath, $job.OutputPath, "-out", $decryptedPath) -Wait
}
```

Archive with my input files (1.5 GB): https://media.axprod.net/mp4box/parallel_mp4box_repro.zip

Verified with current win64 nightly installer available on gpac website.

**Comment by aureliendavid** [comment]
thanks this helps a lot 

there were indeed some name collisions for temp files caused by multiple factors: 

* the standard way to get a temp file is to use `tmpfile()` that returns a handle to a temp file that is auto deleted when closed
* however on windows, since vista and for obscure reasons, this function needs admin privileges to work most of the time
* when it fails we use `tempnam()` which returns a temp filename that we handle ourselves 
* to add extra uniqueness we add a random prefix to that name

2 problems with this when running concurrent instances:

1. we seed the RNG with `time()`, which is in seconds, so every instances launched in the same second will have the same random numbers
2. `tempnam()` only guarantees that the filename returned doesn't exist **at this precise moment** - if another process makes another call to `tempnam()` before we actually `fopen()` it to create it, it will get the same filename 

As a simple solution, I added the PID to the prefix thereby making sure each temp filename is unique to an instance. The RNG seed should probably be revisited too but the current fix should be enough for this particular issue. 

thanks for the report

**Comment by sandersaares** [comment]
Thanks for the fix. I confirm that it appears to work in latest nightly build!
