### ISSUE TITLE
Zero-length string for name in MP4 hdlr valid?

### ISSUE THREAD

**Issue by GyanD** [gpac/gpac#1084]
Does ISO 14496-12 or 14496-14 allow an empty string for the name field in hdlr atoms?

This is what 14496-12 fifth edition says,

> name is a null-terminated string in UTF-8 characters which gives a human-readable name for the track type (for debugging and inspection purposes).

Length requirements are unspecified. FFmpeg does not allow empty strings at present and a user has requested that feature.

GPAC allows them as per src/isomedia/box_code_base.c but it may have been to accommodate [QTFF](https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFChap2/qtff2.html#//apple_ref/doc/uid/TP40000939-CH204-25621) which expressly permits an empty string:

> A (counted) string that specifies the name of the component—that is, the media handler used when this media was created. This field may contain a zero-length (empty) string

My own interpretation is that 'debugging and inspection purposes' precludes an empty string in compliant MP4s.

**Comment by jeanlf** [comment]
The spec doesn't put any requirement on the string length, so an empty string would be valid - doesn't mean this is well handled by players though...
