### ISSUE TITLE
Tiled dashing with one second duration

### ISSUE THREAD

**Issue by mdasari823** [gpac/gpac#1085]
Hi,
I am facing an issue while dashing a video (one minute) into tiled segments. I am getting same number of tiled segments when I dash with one second and two segment duration, as opposed to double the number of segments in case of one second segments. However, when I dash with more than two seconds, like three or four second duration segments, the number of segments decrease perfectly. Is there any problem dashing a video with one second tiled segments? Please let me know. Thanks. 

These are the commands that I followed.

`kvazaar --input sample.yuv --input-res 3840x2048 --input-fps 30 --bitrate 10000000 --tiles 5x5 --slices tiles --mv-constraint frametilemargin --output sample.hvc`

`MP4Box -add sample.hvc:split_tiles -new sample.mp4`

`MP4Box -dash 1000 -profile live -out sample.mpd -segment-name segments_1/%s sample.mp`

**Comment by mdasari823** [comment]
Solved the issue. There were too few I frames in the video. So, I inserted more I frames and the video does not break when segmented with 1 second tiles.

**Comment by 21praveen** [comment]
@mdasari823 How did you inserted more I frames?

**Comment by mdasari823** [comment]
You can use the **_period_** option in kvazaar encoder.
