### ISSUE TITLE
Representations are not adapted to screen on Safari/Explorer

### ISSUE THREAD

**Issue by chanof** [gpac/gpac#1087]
##### Environment

- [] The MPD passes the DASH-IF Conformance Tool on http://dashif.org/conformance.html
- [X] The stream has correct Access-Control-Allow-Origin headers (CORS)
- [X] There are no network errors such as 404s in the browser console when trying to play the stream
- [X] The issue observed is not mentioned on https://github.com/Dash-Industry-Forum/dash.js/wiki/FAQ
- [X] The issue occurs in the latest reference client on http://reference.dashif.org/dash.js/ and not just on my page
* Link to playable MPD file:  https://www.allibrante.com/live/manifest.mpd
* Dash.js version: v2.7.0-89f738a1, 2018-05-30T13:16:50Z
* Browser name/version: Safari 11.1.1
* OS name/version: High Sierra

Hello to all,
I always get some error with the dash conformance tool.
But before switching to high sierra the visualization of the representations was correct.
By passing to high sierra I got an issue about the visualization of adaptive streaming:
The representations are not adapted to the screen, the green screen appears around the representations.
[This is a link to a screenshot of the bug](https://i.stack.imgur.com/8B8Ru.jpg)
Only the largest representation is correctly displayed.
This happen on Safari of high Sierra but In previous versions OSX there was not issues, I found that the problem also happens on Explorer but it never happens on Chrome
I try to update video.min.js , dash.all.min.js and videojs-dash.min.js but the problem remains.

This is the MP4box command:

> MP4Box -dash-live 2000 -subdur 4000 -bound -profile dashavc264:live -mpd-refresh 4 -time-shift 16 -min-buffer 2000 -url-template -insert-utc -run-for 86400000 -dash-ctx /var/www/allibrante.com/public/live/log.txt -out /var/www/allibrante.com/public/live/manifest.mpd 1080set.mp4:bandwidth=4800000#video 720set.mp4:bandwidth=2400000#video 360set.mp4:bandwidth=800000#video 180set.mp4:bandwidth=400000#video audio.mp4:bandwidth=384000#audio

I use to specify the bandwidth cause i notice that the manifest generated with auto-detected bandwidth was wrong. this was the why ABR test fail every time.
It could be caused by the encoding of 480p videos on 1080p to do my ABR tests.

Please is there anyone who can help me understand where the mistake is, and please may i ask an help to fix the manifest to pass the validator conformance tool?

Thanks a lot!

**Comment by BucherTomas** [comment]
There is one specific validator error in your stream that could be probably ignored. It concerns avc3 type not being compatible with mpeg-dash specs and there is a bug filed for that at https://github.com/Dash-Industry-Forum/Conformance-Software/issues/352 .

On the other hand, inband storing of parameters declared by avc3 could cause some issues with decoders and it should be safer to disable this feature by adding `-bs-switching no` to your command, which changes the type to more common avc1. This should also force the player/decoder to read init segment of the variant stream it is switching to in order to obtain its parameters.
Try to add it to see if it makes any difference.

**Comment by chanof** [comment]
Hi @BucherTomas thanks for support, now it running with the add of -bs-switching no flag, but has i understand it is not possible to displays other representations when needed by low bandwidth.
Any advice?
Thanks!

**Comment by chanof** [comment]
I noticed that the explorer view of windows 8 is wrong: now the display is considerably oversized compared to the screen. Using Chrome is always fine displayed.

**Comment by BucherTomas** [comment]
The remaining validator errors do not seem to be something you could affect, those would be for MP4Box devs to consider, although the atoms and brand warnings are very low severity and should not have impact on anything.
You can try to experiment with `-subsegs-per-sidx 0` or `-subsegs-per-sidx -1` to see if it fixes the moof reference errors, but that is just a wild guess.

Oversized view on Explorer sounds more like a scaling issue with either player or the page css, it is not related to the stream itself.

**Comment by chanof** [comment]
@BucherTomas  your "wild guess" its damn right i got near to 0 error this time! thank you! i need to pass it to excludes all issues i can to understand why Safari 11 continues to present several errors during loading and viewing, currently 1/3 of the times fails to displaying the live, but the next step is check video.js html syntax, especially the script for the play after a long pause, which I fear does not work properly on safari leaving the play point on the living edge of the buffer.
However there is only one more mistake about the audio representation i think which i post the result:

```
'tkhd' alternateGroup must be 0 not 1
Validate_ES_Descriptor: ES_ID should be 0 not 1 in media tracks

WARNING: unknown sample table atom 'sgpd'
WARNING: unknown mvex atom 'trep'
WARNING: unknown/unexpected atom 'meta'
Brand 'lmsg' not found as a compatible brand for the last segment (number 3); violates Section 3.2.3. of Interoperability Point DASH264: If the MPD@type is equal to "dynamic" or if it includes MPD@profile attribute in-cludes "urn:mpeg:dash:profile:isoff-live:2011", then: if the Media Segment is the last Media Segment in the Representation, this Me-dia Segment shall carry the 'lmsg' compatibility brand
WARNING: unknown file atom 'prft'
WARNING: unknown file atom 'prft'
tfdt base media decode time 803.981333 not equal to accumulated decode time 0.000000 for track 1 for the first fragment of the movie. This software does not handle incomplete presentations. Applying correction.
### error: 
### grouping_type roll in sbgp is not found for any sgpd in moof number 1
### error: 
### grouping_type roll in sbgp is not found for any sgpd in moof number 1
### error: 
[...]
```
I think to understand that is better specify the ID for audio, im not sure, i need some try & error time.

**Comment by jeanlf** [comment]
closing this - open a new issue if you have conformance issues with the outputs generated by GPAC
