### ISSUE TITLE
Cannot concatenate GoPro MP4 files

### ISSUE THREAD

**Issue by winedog** [gpac/gpac#1089]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x ] I looked for a similar issue and couldn't find any.
- [x ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: 

Hi,

I was hoping that I could use MP4Box to join two MP4 files together without any re-encoding.  The videos were taken using a GoPro and everything I try doesn't work.  I keep getting the error

No suitable media tracks to cat

I've tried using the -force-cat option and that doesn't help either.

I can join them using FFMPEG, but I'd prefer MP4Box because there are some nice front-end tools for MP4Box for this task (e.g. MP4Joiner).

Output from MP4Box:

`[iso file] Unknown box type FIRM
[iso file] Unknown box type LENS
[iso file] Unknown box type CAME
[iso file] Unknown box type SETT
[iso file] Unknown box type AMBA
[iso file] Unknown box type MUID
[iso file] Unknown box type HMMT
[iso file] Unknown box type BCID
[iso file] Unknown box type alis
[iso file] nclc colour profile not supported, not parsing
[iso file] Unknown box type alis
[iso file] Unknown box type gmhd
[iso file] Unknown box type gmin
[iso file] Unknown box type tmcd
[iso file] Unknown box type tcmi
[iso file] Unknown box type alis
[iso file] Unknown box type tmcd
[iso file] Read Box type .... (0x00000002) has size 0 but is not at root/file level, skipping
[iso file] Unknown box type gmhd
[iso file] Unknown box type gmin
[iso file] Unknown box type fdsc
[iso file] Unknown box type alis
[iso file] Unknown box type fdsc
[iso file] more than one stts entry at the end of the track with sample_delta=0 - forbidden ! Fixing to 1
No suitable media tracks to cat in 1.MP4 - skipping
[iso file] Unknown box type FIRM
[iso file] Unknown box type LENS
[iso file] Unknown box type CAME
[iso file] Unknown box type SETT
[iso file] Unknown box type AMBA
[iso file] Unknown box type MUID
[iso file] Unknown box type HMMT
[iso file] Unknown box type BCID
[iso file] Unknown box type alis
[iso file] nclc colour profile not supported, not parsing
[iso file] Unknown box type alis
[iso file] Unknown box type gmhd
[iso file] Unknown box type gmin
[iso file] Unknown box type tmcd
[iso file] Unknown box type tcmi
[iso file] Unknown box type alis
[iso file] Unknown box type tmcd
[iso file] Read Box type .... (0x00000002) has size 0 but is not at root/file level, skipping
[iso file] Unknown box type gmhd
[iso file] Unknown box type gmin
[iso file] Unknown box type fdsc
[iso file] Unknown box type alis
[iso file] Unknown box type fdsc
[iso file] more than one stts entry at the end of the track with sample_delta=0 - forbidden ! Fixing to 1
No suitable media tracks to cat in 2.MP4 - skipping
Saving outputNOW.mp4: 0.500 secs Interleaving`

Here's the details on the MP4 file:

`General 
Complete name : D:\Dropbox\000-Temp-Private\1.MP4 
Format : MPEG-4 
Format profile : Base Media / Version 1 
Codec ID : mp41 (mp41) 
File size : 101 MiB 
Duration : 28 s 70 ms 
Overall bit rate mode : Variable 
Overall bit rate : 30.3 Mb/s 
Encoded date : UTC 2015-05-18 20:20:53 
Tagged date : UTC 2015-05-18 20:20:53 
AMBA : x 

Video 
ID : 1 
Format : AVC 
Format/Info : Advanced Video Codec 
Format profile : High@L4.1 
Format settings : CABAC / 1 Ref Frames 
Format settings, CABAC : Yes 
Format settings, RefFrames : 1 frame 
Format settings, GOP : M=1, N=12 
Codec ID : avc1 
Codec ID/Info : Advanced Video Coding 
Duration : 28 s 70 ms 
Bit rate mode : Variable 
Bit rate : 30.0 Mb/s 
Width : 1 920 pixels 
Height : 1 080 pixels 
Display aspect ratio : 16:9 
Frame rate mode : Constant 
Frame rate : 23.976 (24000/1001) FPS 
Color space : YUV 
Chroma subsampling : 4:2:0 
Bit depth : 8 bits 
Scan type : Progressive 
Bits/(Pixel*Frame) : 0.603 
Stream size : 101 MiB (100%) 
Title : GoPro AVC 
Language : English 
Encoded date : UTC 2015-05-18 20:20:53 
Tagged date : UTC 2015-05-18 20:20:53 
Color range : Full 
Color primaries : BT.709 
Transfer characteristics : BT.709 
Matrix coefficients : BT.709 

Audio 
ID : 2 
Format : AAC 
Format/Info : Advanced Audio Codec 
Format profile : LC 
Codec ID : mp4a-40-2 
Duration : 28 s 53 ms 
Bit rate mode : Constant 
Bit rate : 128 kb/s 
Channel(s) : 2 channels 
Channel positions : Front: L R 
Sampling rate : 48.0 kHz 
Frame rate : 46.875 FPS (1024 SPF) 
Compression mode : Lossy 
Stream size : 439 KiB (0%) 
Title : GoPro AAC 
Language : English 
Encoded date : UTC 2015-05-18 20:20:53 
Tagged date : UTC 2015-05-18 20:20:53 

Other #1 
ID : 3 
Type : Time code 
Format : QuickTime TC 
Duration : 28 s 70 ms 
Title : GoPro TCD 
Language : English 
Encoded date : UTC 2015-05-18 20:20:53 
Tagged date : UTC 2015-05-18 20:20:53 

Other #2 
Type : Time code 
Time code of first frame : 20:19:49:19 
Time code, striped : Yes 
Bit rate mode : VBR 
`

Dropbox links to the two test files if this helps:

https://www.dropbox.com/s/bdsf13t15oow9xf/1.MP4?dl=0
https://www.dropbox.com/s/yt3v0uig030szby/2.MP4?dl=0

**Comment by jeanlf** [comment]
sorry I missed your upload, could you repost these files again and reopen ?
