### ISSUE TITLE
[DASH/HLS] Crash when disconnecting while dash thread is running

### ISSUE THREAD

**Issue by canatella** [gpac/gpac#110]
On PC, start a dash or HLS stream and send q to the terminal before the service connected message appears, it will trigger a crash in the dash thread as soon as the service is connected. On unix, for example:
 
    echo q | /Applications/Osmo4.app/Contents/MacOS/Osmo4 http://dash.edgesuite.net/dash264/TestCases/1a/netflix/exMPD_BIP_TC1.mpd 

It's a problem because on android, the application can be paused at any moment.

**Comment by jeanlf** [comment]
Did #111 fixed this ?

**Comment by rbouqueau** [comment]
Did #111 fixed this ?
