### ISSUE TITLE
Can I make custom player for tied video?? or How can I play my custom tiled video other video player??

### ISSUE THREAD

**Issue by dksshddl** [gpac/gpac#1105]
Hi!

I'm studying for 360 tile-based streaming.

I can make my video to tiled-video.

 http://117.17.184.137:8081/dash/dashed_tiled.mpd

The url is tiled video that I made using ultravideo's test sequence video.

I follow the gpac's guide

https://github.com/gpac/gpac/wiki/Tiled-Streaming,
https://gpac.wp.imt.fr/2017/02/01/hevc-tile-based-adaptation-guide/

I can play the video in mp4client(version 0.7.0).

And I want to make my custom ABR(Adaptive Bit Rate) rules.

To constuct custom ABR rules, I tried to play the tiled video in browser.

But the tiled video didn't work any other player(dash, shaka...) except mp4client for codec problem.

So my question is

- Can i make my custom player using mp4clinet??

- or Are there any way to play my tiled video on other player..?

Thank you!

**Comment by jeanlf** [comment]
sorry for the late reply
- custom ABR: can be added to the [dash client](https://github.com/gpac/gpac/blob/filters/src/media_tools/dash_client.c) but you will have to code it yourself
- other players: not that I know of
