### ISSUE TITLE
ERROR: MP4Box -hint -mtu 1024 -fps 30 -add bus_cif.m4v bus_cif.mp4

### ISSUE THREAD

**Issue by hilladamanik** [gpac/gpac#1106]
dear all, can help me?

ajn16lts@ajn16lts-p2-1350l:~/ns-allinone-2.35/ns-2.35/Evalvid in NS2/example$ MP4Box -hint -mtu 1024 -fps 30 -add bus_cif.m4v bus_cif.mp4

MP4Box: symbol lookup error: MP4Box: undefined symbol: gf_f64_open ajn16lts@ajn16lts-p2-1350l:~/ns-allinone-2.35/ns-2.35/Evalvid in NS2/example$

i try convert m4v to mp4, what mean error and solved this error?

Thanks.

**Comment by jeanlf** [comment]
you have a build issue with gpac, probably two libgpac on your system. Please clenup everything, rebuild and retry
