### ISSUE TITLE
Merge tiled dash segments back into a playable file manually

### ISSUE THREAD

**Issue by wuchlei** [gpac/gpac#1107]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hi, guys, 
I'm having trouble merging tiled dash segments back into a playable video.

By now, I've been able to encode a 360 video using kvazaar and prepare the tiled dash segments.
The commands are:
```
1. kvazaar --input sample.yuv --input-res 2560x1440 --input-fps 30 --period 30 --bitrate 3000000 --tiles 3x3 --slices tiles --mv-constraint frametilemargin --output sampe.hvc

2. MP4Box -add sampe.hvc:split_tiles -new sampe.mp4

3. MP4Box -dash 1000 -profile live -out ./dash./tiled.mpd sample.mp4
```
Then I got a lot of init, m4s and mp4 files. 
I don't know how to combine these tiled_set1_init.mp4, sample_dash_track*.mp4 and sample_dash_track*.m4s into a single playable file,
that is, extracting the raw hevc stream.

I also extracted each track from the original sample.mp4 file and tried to combine these tracks (tiles) back to a playable file.
I can pack 1 tile back into a mp4 file by doing:
`MP4Box -add sampe_track2.hvc:split_tiles -new test.mp4`
The obtained video can play successfully.
But I can't merge more tiles (i.e. two or more files) into this mp4 file.
I've tried:
`MP4Box -add sample_track3.hvc:split_tiles test.mp4`
and
`MP4Box -cat sample_track3.hvc:split_tiles test.mp4`
These all didn't work.

The related issues is [this](https://github.com/gpac/gpac/issues/1051), however the problem wasn't solved.
Can anyone help, please?

**Comment by wuchlei** [comment]
@jeanlf Could you please take a look?

**Comment by wuchlei** [comment]
solved

**Comment by jamesmagnus** [comment]
Hi @wuchlei 

I'm trying to merge segments from tiled video into a single playable file like you. 
Can you tell me how you solved your problem ?

Thank you

**Comment by jamesmagnus** [comment]
Thank you. So basically you concatenate the init file and all the segments for each tile, then you extract the raw hevc stream with MP4Box ?

**Comment by wuchlei** [comment]
Yes. And those commands are listed in that repo.
