### ISSUE TITLE
Framerate is not copied or used as hint when remuxing AV1 streams from IVF files

### ISSUE THREAD

**Issue by jamrial** [gpac/gpac#1108]
I have an ivf file with timebase of 1/24 but after remuxing with mp4box using gpac git the resulting mp4 file is reported by ffmpeg as having a timebase of 1/25000, meaning the result is a 24fps file is remuxed into a 25fps file.

I'll upload it to the mediafire link with the name fwd.ivf

**Comment by rbouqueau** [comment]
Hi, thanks for reporting. It is a known limitation of our AV1 implementation. Let me have a look.

**Comment by rbouqueau** [comment]
It should be ok now. Reopen if needed.
