### ISSUE TITLE
What does "quality" mean when using Osmo4 play MPD file

### ISSUE THREAD

**Issue by lutchenxl** [gpac/gpac#1111]
What does "quality" mean when using Osmo4 play MPD file？ Are there ways to get the PSNR or SSIM of MPD to evaluate the quality of the video?
![ba100000000 20s](https://user-images.githubusercontent.com/32415988/43163056-90d5c7ba-8f52-11e8-8c64-6483264ee811.jpg)

**Comment by jeanlf** [comment]
the quality stat is the sum of all the bandwidth of the selected object, including dependent objects. There is currently no way of performing image-based quality evaluation on the result in gpac.
