### ISSUE TITLE
Request for extended VP9 codec info in mpd manifest

### ISSUE THREAD

**Issue by BucherTomas** [gpac/gpac#1114]
When dashing, mp4box currently generates for VP9 video in mp4 container `vp09` codec info in mpd manifest. This is no longer supported on all recent browsers that can decode VP9. The codec string needs to include all the details such as profile, level, etc. as per https://www.webmproject.org/vp9/mp4/#codecs-parameter-string . 

This can be demonstrated by using this nifty webtool by one of your developers http://cconcolato.github.io/media-mime-support/ on Chrome or recent Firefox.

Existing `video/mp4;codecs="vp09"` on the page already says that `MediaSource.isTypeSupported = false`.

However, if you enter `vp09.00.50.08` (as generated for example from FFmpeg dash muxer for UHD content with level 5, 8-bit) into the testing box, then `MediaSource.isTypeSupported = true`

Default mpd manifest from mp4box with vp09 codec info is incompatible with any browser, once I manually edit the codec info to vp09.00.50.08, the codec negotiation is successful and the stream starts to play.

It would be great to have mp4box generate the codec info properly by itself as it does for avc1 or hevc.

**Comment by aureliendavid** [comment]
(see #1115 for a follow up)

**Comment by aureliendavid** [comment]
should be fixed, reopen if needed

**Comment by BucherTomas** [comment]
@aureliendavid It looks like you are reading the vaules from vpcC box as hexadecimal, however, they are stored as decimal. The documentation version I referred to unfortunately lacks the emphasis, but for example https://github.com/webmproject/vp9-dash/blob/f8d543ef1006b9c5b4661141b822dde67d955283/VPCodecISOMediaFileFormatBinding.md states it understandably enough.

**Comment by aureliendavid** [comment]
dammit you're right

looks like it's just for the `level` field, which of course is the only one that ffmpeg doesn't set itself so my test sequences were wrong (should be set with `-level 0x50` and not `-level 50` in ffmpeg) 

(as far as I understood the link, other fields are regular uints, for the bit depth for example, if it's 10bit it will be encoded a `0x0a` and not `0x10`)

there's always something, isn't there..

**Comment by BucherTomas** [comment]
Thanks, now it looks good.

Since you mentioned it - I'm using FFmpeg built from master and it actually allows you to enter level for vp9 with decimal point only as `-level 5.0`, not as `-level 50`. All the same, this argument is ignored when setting higher level than needed, the level in the final encode is assigned automatically. When setting lower level than necessary, the process aborts with error message that one of the parameters is above level limit. So it is looked at during encoding, but if encoding succeeds, manually specified level is not used at all.

On that note, I don't need to try to set the level manually, neither when remuxing VP9 to mp4 from webm nor when transcoding to VP9 directly. That https://github.com/FFmpeg/FFmpeg/commit/5b6cc3a73acb90df0d4fe5ca8f51527b64592bf8 patch you mentioned in the other ticket seems to be in effect in my case and you are maybe just using older FFmpeg build?

**Comment by aureliendavid** [comment]
It is indeed in effect if you build ffmpeg from master but it is not in any release yet (for people downloading binaries).

the last ffmpeg release is 4.0.2 which takes the level from the command line or sets it a 0: https://github.com/FFmpeg/FFmpeg/blob/n4.0.2/libavformat/vpcc.c#L74

**Comment by BucherTomas** [comment]
@aureliendavid  I have lead you astray. Rigth after my tests with content created by FFmpeg, its developers patched the way the level and other values in vpcC box are written.

The values are supposed to be decimal, that part is correct, but it is up to the parser to interpret them that way. Level 5.0 is not stored as 50, as I thought, but as 32.

Based on those patches, aside from level, also bitdepth and profile should be handled as decimal.

Here's my discussion with FFmpeg devs https://trac.ffmpeg.org/ticket/7471 .

Sorry.

**Comment by aureliendavid** [comment]
Looks like the confusion came from this version of the spec: https://github.com/webmproject/vp9-dash/blob/f8d543ef1006b9c5b4661141b822dde67d955283/VPCodecISOMediaFileFormatBinding.md wich explicitly mentions **binary coded decimal** for the level field (which would mean 0x50 for 50 instead of 0x32). 

But it's not in the master version of the spec: https://github.com/webmproject/vp9-dash/blob/master/VPCodecISOMediaFileFormatBinding.md Here it's defined as a standard int (so 0x32 for 50). 

I reverted the change, let's hope it's final.

**Comment by BucherTomas** [comment]
Reading level from vpcC appears to be broken again in GPAC 0.9.0 filters branch, albeit differently.

Level is written for example as `1e` , i.e. decimal `30`, but dasher reads it as is and codecs attribute in mpd is then `vp09.00.1e.08.00.02.02.02.00` instead of `vp09.00.30.08.00.02.02.02.00`.

**Comment by aureliendavid** [comment]
haha, this is endless

it should be ok on filters now too

**Comment by mart-jansink** [comment]
@aureliendavid it appears that this broke again: I'm getting `vp09.00.28.08.00.02.02.02.00` where I'd expect `vp09.00.40.08.00.02.02.02.00` (`0x28 == 40`). Looking at https://github.com/gpac/gpac/blob/6f4ed0c29a36452873451624b5b7903ef689eeab/src/media_tools/isom_tools.c#L4019-L4023 I see that `%02x` is again incorrectly used for the the `vpcc->level`. I've made a pull request to fix this.
