### ISSUE TITLE
request about com_enst_mp4box_mp4terminal_run() native method not found

### ISSUE THREAD

**Issue by sandyradhia** [gpac/gpac#1116]
i finaly compiled with success ligpac.so and libmp4box.so and when i call errors = loadAllLibraries(); all librairies load with succes but when a want to use function native void run() it give me error "native function not found"
please can someone help me to know how to call com_enst_mp4box_mp4termina_run() in my java projet

thanks

**Comment by rbouqueau** [comment]
Hi,

Have you had a look at https://github.com/gpac/gpac/tree/master/applications/osmo4_android_studio ? Could you make it work? How different is it from your usecase?

**Comment by sandyradhia** [comment]
hi @rbouqueau thanks for taking a litle bit of your precious times to answers me . and sorry for my english to be so bad

when i follow your link all libraries have been build with succes excepted libgpacWrapper.so  Therefore there is no Osmo4.apk inside <GPAC_DIR>/applications/osmo4_android_studio/app/build/outputs/
and this is the error that i received

PS my projet consist to just build and simple audio live streaming for a part of my master thesis using android studio 2.1.2 . GPAC 0.7.2 -DEV and NDK r16b . hundred millions times for support

[armeabi] Install        : libgm_osd.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_osd.so
[armeabi] Compile++ thumb: gpacWrapper <= wrapper_jni.cpp
[armeabi] Compile++ thumb: gpacWrapper <= wrapper.cpp
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:182:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:307:2: warning: '/*' within block comment [-Wcomment]
        /*LOGI("Before Thread exist, detach the JavaVM from Thread for thread %p...\n", gf_th_current());
        ^
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:311:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:712:6: warning: address of array 'this->m_cfg_dir' will always evaluate to 'true' [-Wpointer-bool-conversion]
        if (m_cfg_dir) {
        ~~  ^~~~~~~~~
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:738:30: warning: address of array 'this->m_cfg_dir' will always evaluate to 'true' [-Wpointer-bool-conversion]
        m_user.config = gf_cfg_init(m_cfg_dir ? m_cfg_filename : NULL, NULL);
                                    ^~~~~~~~~ ~
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:837:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
6 warnings generated.
[armeabi] SharedLibrary  : libgpacWrapper.so
oduLefileDirbuild/intermediates/ndk/obj/local/armeabi/objs/gpacWrapper/__/__/__/__/applications/osmo4_android_studio/app/src/main/jni/wrapper.o: In function `jni_destroy_env_func(void*)':
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:94: undefined reference to `gf_free'
oduLefileDirbuild/intermediates/ndk/obj/local/armeabi/objs/gpacWrapper/__/__/__/__/applications/osmo4_android_studio/app/src/main/jni/wrapper.o: In function `CNativeWrapper::getEnv()':
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:323: undefined reference to `gf_malloc'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:333: undefined reference to `gf_th_id'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:341: undefined reference to `gf_th_id'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:337: undefined reference to `gf_free'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:330: undefined reference to `gf_free'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:342: undefined reference to `gf_th_current'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:345: undefined reference to `gf_th_current'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:345: undefined reference to `gf_register_before_exit_function'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:346: undefined reference to `gf_th_current'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:348: undefined reference to `gf_free'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:351: undefined reference to `gf_th_id'
oduLefileDirbuild/intermediates/ndk/obj/local/armeabi/objs/gpacWrapper/__/__/__/__/applications/osmo4_android_studio/app/src/main/jni/wrapper.o: In function `CNativeWrapper::Shutdown()':
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:258: undefined reference to `gf_term_disconnect'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:260: undefined reference to `gf_mx_del'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:266: undefined reference to `gf_term_del'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:269: undefined reference to `gf_cfg_del'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:273: undefined reference to `gf_modules_del'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:278: undefined reference to `gf_sys_close'
oduLefileDirbuild/intermediates/ndk/obj/local/armeabi/objs/gpacWrapper/__/__/__/__/applications/osmo4_android_studio/app/src/main/jni/wrapper.o: In function `CNativeWrapper::setJavaEnv(_JavaEnvTh*, _JNIEnv*, _jobject*)':
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:286: undefined reference to `gf_th_id'
oduLefileDirbuild/intermediates/ndk/obj/local/armeabi/objs/gpacWrapper/__/__/__/__/applications/osmo4_android_studio/app/src/main/jni/wrapper.o: In function `CNativeWrapper::GPAC_EventProc(void*, GF_Event*)':
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:565: undefined reference to `gf_error_to_string'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:590: undefined reference to `gf_set_progress'
oduLefileDirbuild/intermediates/ndk/obj/local/armeabi/objs/gpacWrapper/__/__/__/__/applications/osmo4_android_studio/app/src/main/jni/wrapper.o: In function `CNativeWrapper::disconnect()':
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:851: undefined reference to `gf_term_disconnect'
oduLefileDirbuild/intermediates/ndk/obj/local/armeabi/objs/gpacWrapper/__/__/__/__/applications/osmo4_android_studio/app/src/main/jni/wrapper.o: In function `CNativeWrapper::navigate(GF_Event*)':
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:648: undefined reference to `gf_term_is_supported_url'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:650: undefined reference to `gf_term_navigate_to'
oduLefileDirbuild/intermediates/ndk/obj/local/armeabi/objs/gpacWrapper/__/__/__/__/applications/osmo4_android_studio/app/src/main/jni/wrapper.o: In function `CNativeWrapper::SetupLogs()':
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:679: undefined reference to `gf_mx_p'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:680: undefined reference to `gf_cfg_get_key'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:680: undefined reference to `gf_log_set_tools_levels'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:681: undefined reference to `gf_log_set_callback'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:682: undefined reference to `gf_cfg_get_key'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:692: undefined reference to `gf_mx_v'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:694: undefined reference to `gf_log_tool_level_on'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:694: undefined reference to `gf_log_lt'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:694: undefined reference to `gf_log'
oduLefileDirbuild/intermediates/ndk/obj/local/armeabi/objs/gpacWrapper/__/__/__/__/applications/osmo4_android_studio/app/src/main/jni/wrapper.o: In function `CNativeWrapper::init(_JNIEnv*, void*, _jobject**, int, int, char const*, char const*, char const*, char const*, char const*, char const*)':
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:727: undefined reference to `gf_malloc'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:734: undefined reference to `gf_mx_new'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:738: undefined reference to `gf_cfg_init'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:739: undefined reference to `gf_set_progress_callback'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:750: undefined reference to `gf_cfg_set_key'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:751: undefined reference to `gf_cfg_set_key'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:752: undefined reference to `gf_cfg_set_key'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:753: undefined reference to `gf_cfg_get_key'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:755: undefined reference to `gf_modules_new'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:756: undefined reference to `gf_modules_get_count'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:778: undefined reference to `gf_sys_init'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:779: undefined reference to `gf_fm_request_set_callback'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:781: undefined reference to `gf_term_new'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:793: undefined reference to `gf_term_set_option'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:798: undefined reference to `gf_term_set_size'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:800: undefined reference to `gf_cfg_get_key'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:807: undefined reference to `gf_term_connect'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:811: undefined reference to `gf_cfg_save'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:759: undefined reference to `gf_modules_del'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:760: undefined reference to `gf_cfg_del'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:785: undefined reference to `gf_modules_del'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:787: undefined reference to `gf_cfg_del'
oduLefileDirbuild/intermediates/ndk/obj/local/armeabi/objs/gpacWrapper/__/__/__/__/applications/osmo4_android_studio/app/src/main/jni/wrapper.o: In function `CNativeWrapper::connect(char const*)':
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:825: undefined reference to `gf_cfg_get_key'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:828: undefined reference to `gf_cfg_set_key'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:829: undefined reference to `gf_term_connect'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:833: undefined reference to `gf_term_connect_from_time'
oduLefileDirbuild/intermediates/ndk/obj/local/armeabi/objs/gpacWrapper/__/__/__/__/applications/osmo4_android_studio/app/src/main/jni/wrapper.o: In function `CNativeWrapper::setGpacPreference(char const*, char const*, char const*)':
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:842: undefined reference to `gf_cfg_set_key'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:843: undefined reference to `gf_cfg_save'
oduLefileDirbuild/intermediates/ndk/obj/local/armeabi/objs/gpacWrapper/__/__/__/__/applications/osmo4_android_studio/app/src/main/jni/wrapper.o: In function `CNativeWrapper::step(void*, void*)':
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:871: undefined reference to `gf_term_process_step'
oduLefileDirbuild/intermediates/ndk/obj/local/armeabi/objs/gpacWrapper/__/__/__/__/applications/osmo4_android_studio/app/src/main/jni/wrapper.o: In function `CNativeWrapper::resize(int, int)':
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:890: undefined reference to `gf_term_set_size'
oduLefileDirbuild/intermediates/ndk/obj/local/armeabi/objs/gpacWrapper/__/__/__/__/applications/osmo4_android_studio/app/src/main/jni/wrapper.o: In function `CNativeWrapper::onMouseDown(float, float)':
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:909: undefined reference to `gf_term_user_event'
oduLefileDirbuild/intermediates/ndk/obj/local/armeabi/objs/gpacWrapper/__/__/__/__/applications/osmo4_android_studio/app/src/main/jni/wrapper.o: In function `CNativeWrapper::onMouseUp(float, float)':
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:927: undefined reference to `gf_term_user_event'
oduLefileDirbuild/intermediates/ndk/obj/local/armeabi/objs/gpacWrapper/__/__/__/__/applications/osmo4_android_studio/app/src/main/jni/wrapper.o: In function `CNativeWrapper::onMouseMove(float, float)':
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:940: undefined reference to `gf_term_user_event'
oduLefileDirbuild/intermediates/ndk/obj/local/armeabi/objs/gpacWrapper/__/__/__/__/applications/osmo4_android_studio/app/src/main/jni/wrapper.o: In function `CNativeWrapper::onKeyPress(int, int, int, int, int)':
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:957: undefined reference to `gf_term_user_event'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:963: undefined reference to `gf_term_user_event'
oduLefileDirbuild/intermediates/ndk/obj/local/armeabi/objs/gpacWrapper/__/__/__/__/applications/osmo4_android_studio/app/src/main/jni/wrapper.o:G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:1088: more undefined references to `gf_term_user_event' follow
oduLefileDirbuild/intermediates/ndk/obj/local/armeabi/objs/gpacWrapper/__/__/__/__/applications/osmo4_android_studio/app/src/main/jni/wrapper.o: In function `CNativeWrapper::setGpacLogs(char const*)':
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:1093: undefined reference to `gf_log_set_tools_levels'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [oduLefileDirbuild/intermediates/ndk/obj/local/armeabi/libgpacWrapper.so] Error 1

Process finished with exit code 2

thanks hundred millions times for support

**Comment by aureliendavid** [comment]
You can look at https://github.com/gpac/gpac/tree/master/build/android to see how we build for android, and specifically the script at https://github.com/gpac/gpac/blob/master/build/android/jni/gpac_build_android

You can also look at http://gpacvm-ext.enst.fr/buildbot/#/builders/6 to see our android builder live.

We don't actually use android studio, only command line tools, but I guess it can be done.

**Comment by sandyradhia** [comment]
thanks @aureliendavid for your precious advices and sorry again for my englis i'm french speaker 

i read with attention all the README file in gpac-master inside <GPAC_DIR>\build\android\README and i follow all steps to reach at last line
4 - ii Building Osmo4.apk with Android Studio
but all librairies are generated with success 
[armeabi] Install        : libgpac.so => G:\MyApplication\app/src/main/libs/armeabi/libgpac.so
[armeabi] Install        : libgm_bifs_dec.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_bifs_dec.so
[armeabi] Install        : libgm_ctx_load.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_ctx_load.so
[armeabi] Install        : libgm_dummy_in.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_dummy_in.so
[armeabi] Install        : libgm_ft_font.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_ft_font.so
[armeabi] Install        : libgm_img_in.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_img_in.so
[armeabi] Install        : libgm_ismacryp.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_ismacryp.so
[armeabi] Install        : libgm_isom_in.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_isom_in.so
[armeabi] Install        : libgm_laser_dec.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_laser_dec.so
[armeabi] Install        : libgm_odf_dec.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_odf_dec.so
[armeabi] Install        : libgm_rtp_in.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_rtp_in.so
[armeabi] Install        : libgm_saf_in.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_saf_in.so
[armeabi] Install        : libgm_soft_raster.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_soft_raster.so
[armeabi] Install        : libgm_svg_in.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_svg_in.so
[armeabi] Install        : libgm_timedtext.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_timedtext.so
[armeabi] Install        : libjavaenv.so => G:\MyApplication\app/src/main/libs/armeabi/libjavaenv.so
[armeabi] Install        : libgm_droidout.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_droidout.so
[armeabi] Install        : libgm_droidaudio.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_droidaudio.so
[armeabi] Install        : libgm_gpac_js.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_gpac_js.so
[armeabi] Install        : libgm_mp3_in.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_mp3_in.so
[armeabi] Install        : libgm_mpegts_in.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_mpegts_in.so
[armeabi] Install        : libgm_aac_in.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_aac_in.so
[armeabi] Install        : libgm_mpd_in.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_mpd_in.so
[armeabi] Install        : libgm_widgetman.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_widgetman.so
[armeabi] Install        : libgm_droid_cam.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_droid_cam.so
[armeabi] Install        : libgm_droid_mpegv.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_droid_mpegv.so
[armeabi] Install        : libgm_osd.so => G:\MyApplication\app/src/main/libs/armeabi/libgm_osd.so
[armeabi] Compile++ thumb: gpacWrapper <= wrapper.cpp

arrived at compile gpacWrapper error occured started by 
[armeabi] SharedLibrary  : libgpacWrapper.so
oduLefileDirbuild/intermediates/ndk/obj/local/armeabi/objs/gpacWrapper/__/__/__/__/applications/osmo4_android_studio/app/src/main/jni/wrapper.o: In function `jni_destroy_env_func(void*)':
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:99: undefined reference to `gf_free'
oduLefileDirbuild/intermediates/ndk/obj/local/armeabi/objs/gpacWrapper/__/__/__/__/applications/osmo4_android_studio/app/src/main/jni/wrapper.o: In function `CNativeWrapper::getEnv()':
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:328: undefined reference to `gf_malloc'
G:/MyApplication/app/src/main/jni/gpac-master/build/android/jni/mp4box/../../../../applications/osmo4_android_studio/app/src/main/jni/wrapper.cpp:338: undefined reference to `gf_th_id'

in different tutorials i readed about undefined error sometimes due to toolchain so i change my toolchain an it still be the same error so how could i resolve this error . 
 
thanks for your support gentlemen

**Comment by sandyradhia** [comment]
I finaly solved the issues by adding libgpac.so inside <NDK DIR>\platforms\android-14\arch-x86\usr\lib 
thanks to you all @rbouqueau @aureliendavid for your support and your advices you are a gentelmen . please can you tell me what is the next step by helping me to answers this few questions
1 - how to to generated .mpd file after build all libraries. ?
2 - where to put Osmo4.apk to make it build whit existing android projet ?
thanks you hundred millions times to all contributors for your help . will comme back if necessary

**Comment by Duna** [comment]
> i finaly compiled with success ligpac.so and libmp4box.so and when i call errors = loadAllLibraries(); all librairies load with succes but when a want to use function native void run() it give me error "native function not found"
> please can someone help me to know how to call com_enst_mp4box_mp4termina_run() in my java projet
> 
> thanks

Can you hare the android project that you manage to include mp4box.so?
