### ISSUE TITLE
mp4box crashes on dash generation from live ts file

### ISSUE THREAD

**Issue by ishaan-shringi** [gpac/gpac#1117]
I'm new to mp4box and mpeg-dash. I'm dumping live mpeg-2 transport stream output to a file `live_stream.ts`. 
I use the below command using mp4box : 

    mp4box -dash-live 1000 -out manifest.mpd live_stream.ts
It gives me following output and crashes : 

    [MPEG-2 TS] PID 1001 reused across programs 1 and 1, not completely supported
I wonder why it is reading single program twice? Details of my mpeg file are as follows :

    program number : 1
    total programs : 1
    video : H.264
    audio : AAC

---
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by sandyradhia** [comment]
@ishaan-shringi i'm also new to mp4box can't u help me please ? want to build a audio live stream in a school projet . i compiled libgpac.so for android but don't know how to call native method run() inse my java code. thanks

**Comment by rbouqueau** [comment]
@ishaan-shringi Could you share the TS file with us? You can use this anonymous dropbox (https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95) but you should then let us know here a file has been updated (+ its name).

How was this TS generated?

**Comment by ishaan-shringi** [comment]
I'm receiving this transport stream input from UDP. A single process reads the transport stream and dumps it into a growing file say 'live_stream.ts'.
On a separate process, I use the mp4box command to generate dash.

    mp4box -dash-live 1000 -out manifest.mpd live_stream.ts

I have uploaded a sample chunk of the transport stream. Please check it out.

File Name : sample_transport_stream.ts
Description : sample transport stream chunk for dash segmentation

I suspect it has something to do with the PMT parsing.

**Comment by rbouqueau** [comment]
Which version of MP4Box do you use? (```MP4Box -version```)

**Comment by ishaan-shringi** [comment]
mp4box -version output : 

    MP4Box - GPAC version 0.7.2-DEV-rev625-gc956332c-master
    (c) Telecom ParisTech 2000-2018 - Licence LGPL v2
    GPAC Configuration: (static configuration file)
    Features: GPAC_64_BITS GPAC_MEMORY_TRACKING GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG

**Comment by rbouqueau** [comment]
Ok. The MP4Box command-line you gave above (```mp4box -dash-live 1000 -out manifest.mpd live_stream.ts```) is not compatible with the version you mention. Could you give me a command-line that I can execute?

For the record I just used -info, -add, and -dash successfully on the sample with the latest rev.

**Comment by rbouqueau** [comment]
It is the same command-line. You just provide TS files instead of MP4 files.

**Comment by jeanlf** [comment]
No news closing
