### ISSUE TITLE
Update AV1 support to be compliant with the Release Candidate of the spec

### ISSUE THREAD

**Issue by jamrial** [gpac/gpac#1118]
The AV1 in ISOBMFF spec was updated and will enter a Release Candidate phase now. GPAC should update its implementation to be compliant with it.

The most notable changes are the several additions to the AV1CodecConfigurationRecord struct inside the AV1CodecConfigurationBox (which it itself is now a box instead of a fullbox), that OBUs of type TILE_LIST are not allowed on samples anymore, and that mdcv and clli boxes can be used to signal HDR metadata.

**Comment by rbouqueau** [comment]
@cconcolato Can the new AV1 in ISOBMFF be considered stable enough for this?

**Comment by cconcolato** [comment]
@rbouqueau Yes. I agree it would be good to update to the latest spec. We entered a 2-week review period to get any remaining comment before formal approval and publication, planned Aug 31st. We might have some further changes but they should be minor (e.g. metadata sample groups).

**Comment by rbouqueau** [comment]
Let me know if you see any issue.

**Comment by jamrial** [comment]
Hi, just tested and looked at the commit, and I found some issues.

You forgot to change the av1C from a fullbox to a box, so it's writing four invalid bytes at the beginning. It is also not trying to read the required values for av1C from the sequence header if the source is not an mp4 file (obu, ivf, annex-b, etc, which are the most likely source when using aomenc), so they are always written as zero in that case.
The commit also doesn't seem to be filtering out TILE_LIST OBUs from sample data.

**Comment by rbouqueau** [comment]
Thanks for your feedback. The tile support is a WiP.

PS: just pushed 0297f694a85ec5efe78be3187e44f0b5247ae935.
