### ISSUE TITLE
Tiles are invisible in player

### ISSUE THREAD

**Issue by SASR75** [gpac/gpac#1119]
Hi, 
I have converted a 360-degree video into tiles with multiple resolutions and encoded with Kvazaar. Then I split the tiles with mp4box and generated dashed segments. After that, I played the MPD file through mp4client. The player doesn't show any kind of tiles in the stream. 
However, I played the Tear of Steal and tiles are visible. http://download.tsi.telecom-paristech.fr/gpac/SRD/tears_of_steal/tos_srd_hd.mpd.
Thanks

**Comment by jeanlf** [comment]
did you follow [the tile adaptation guide](https://gpac.wp.imt.fr/2017/02/01/hevc-tile-based-adaptation-guide/) ?

**Comment by jeanlf** [comment]
No news closing

**Comment by sergeygross** [comment]
The same problem with tiles. Kvazaar 1.3. I do exactly what guide tells:

kvazaar -i tears420.yuv --input-res 1280x720 -o tears_test.265 --tiles 3x3 --slices tiles --mv-constraint frametilemargin --frames 100
MP4Box -add tears_test.265:split_tiles -new video_tiled.mp4
Saving video_tiled.mp4: 0.500 secs Interleaving
[video_tiled.mp4.zip](https://github.com/gpac/gpac/files/3833543/video_tiled.mp4.zip)

File video_tiled.mp4 is practically empty (228 bytes). Next steps are not working. Tried all day with diff videos, diff versions of kvazaar and gpac with the same result:

MP4Box -rem 3 video_tiled.mp4 -out test_tile_lost.mp4
Error Removing track ID 3: Bad Parameter
Error: Bad Parameter

I see in pps that tile structure described by NumTileRowsMinus1/NumTileColumnsMinus1. But no tools see it.
