### ISSUE TITLE
mp4box -raw and mp4box -add *.h264 do not match

### ISSUE THREAD

**Issue by grylem** [gpac/gpac#1125]
mp4box -raw 1 test.mp4
mp4box -add 2_track1.h264 test1.mp4
mp4box -raw 1 test1.mp4
repeat
each time *.h264 has a different size
for *.aac this problem is not present
MP4Box - GPAC version 0.7.2-DEV-rev643-g1d2a52e7-master

**Comment by jeanlf** [comment]
this is likely due to an extra copy of PPS or SPS info. Could you upload a sample file ?

**Comment by grylem** [comment]
but you can reproduce it with any *.mp4
for this
mp4box -add out_track1.h264 -new test.mp4
mp4box -raw 1 test.mp4
сheck size/checksum - *.h264 is different
with old 0.5.2 version *.h264 have the same size and checksum sha1 or other.
[out_track1.h264.zip](https://github.com/gpac/gpac/files/2323758/out_track1.h264.zip)

**Comment by jeanlf** [comment]
thanks, now fixed.

**Comment by grylem** [comment]
sorry , with -add all fine, but -raw add extra byte in comparison with 0.5.2 version

**Comment by jeanlf** [comment]
What commands are youusing ? Here, no extra byte:
`
$ MP4Box -add out_track1.h264 -new test.mp4
AVC-H264 import - frame size 640 x 360 at 25.000 FPS
AVC Import results: 374 samples (2253 NALUs) - Slices: 20 I 935 P 915 B - 375 SEI - 20 IDR
Saving test.mp4: 0.500 secs Interleaving
$ MP4Box -raw 1 test.mp4 -out out_track1_1.h264 
Extracting MPEG-4 AVC-H264 stream to h264
$ ls -la out_track1*
-rw-r--r--  1 lefeuvre  admin  1894313 27 aoû 14:01 out_track1.h264
-rw-r--r--  1 lefeuvre  admin  1894313 31 aoû 16:30 out_track1_1.h264
`

**Comment by grylem** [comment]
v0.5.2
mp4box -raw 1 test.mov
v0.7.2
mp4box -raw 1 test.mov
please see attached with test.mov and *.h264 with the corresponding names
[extra.zip](https://github.com/gpac/gpac/files/2340766/extra.zip)

**Comment by grylem** [comment]
any news?

**Comment by aureliendavid** [comment]
from what I can see the difference between the two attached files (0.5.2 and 0.7.2) is that 0.7.2 contains the 0x07 and 0x08 NALs copied 3 times more in the file

looking for why we're doing this leads to here: https://github.com/gpac/gpac/blame/master/src/media_tools/media_export.c#L1436 and this commit: https://github.com/gpac/gpac/commit/a9f1973febc8682dbaae08afb1f833619a59799f

so it looks like it's done on purpose to fix a bug and it's the 0.5.2 version that is incorrect 

if we are indeed supposed to copy SPS/PPS before each IDR frame then I think we can close this?

**Comment by grylem** [comment]
in my opinion should be so:
mp4box -raw 1 test.mp4
mp4box -add test.h264 -new test1.mp4
mp4box -raw 1 test1.mp4
and test.h264 and test1.h264 must be identical.
Now its true for 0.5.2 but not for 0.7.2

**Comment by jeanlf** [comment]
This depends on how the test.mp4 was produced in the first place. For your test to be correct, you will have to first dump to h264 and re-import, than do your test with that new file.

**Comment by aureliendavid** [comment]
yes it's stable once it has been -add with MP4Box (then successive -raw/-add/-raw produce identical files), but -raw extracted from files from external sources can have extra PPS nals.

**Comment by grylem** [comment]
any chance to fix it?
