### ISSUE TITLE
Support for encryption of VP9 video

### ISSUE THREAD

**Issue by BucherTomas** [gpac/gpac#1126]
Attempt to encrypt mp4 with VP9 video by latest mp4box version 0.7.2-DEV-rev646-ge148a8dd-master ends with error 

`mp4box -crypt cenc.xml vp9.mp4 -out vp9drm.mp4`
`Error: Bad Parameter`

The same cenc.xml using CENC AES-CTR encryption scheme can be used without problems for mp4 with h.264 or hevc video, senc box for saiSavedBox attribute should be usable for VP9 as well, so I would think that this cenc.xml can be used also for VP9 with required subsample encryption as per documentation.

All the same, GPAC does not have full support for VP9 video (and VP8 for that matter) at the moment and encryption is probably also one of the missing key points.

Can you please take a look?

**Comment by rbouqueau** [comment]
Related to #1114 and #1115

**Comment by BucherTomas** [comment]
Looks good so far! One comment, though.

If VP9 requires unconditionally `blockAlign="always"` , wouldn't it be better to just notify the user in the log, but enable the attribute automatically and continue with encryption, so that the same encryption xml can be used for other formats as well, where this attribute could remain at default settings?

Or alternatively, if it makes any sense, how about adding new value `auto` for `blockAlign`, which would use appropriate value based on known constraints of the format, aka `default` for everything but VP9, where it would use `always` and it could be used in the future for other formats as well, should they have the same constraints.

The reason behind this being to avoid juggling with settings in xml based on input video format.

**Comment by rbouqueau** [comment]
> If VP9 requires unconditionally ```blockAlign="always"```, wouldn't it be better to just notify the user in the log, but enable the attribute automatically

Well catched! We're having this discussion this internally. The flag is set automatically with AV1. However are checking with its authors that the VP9 specification is clear enough. If it is the case I am in favour of activating it automatically.

**Comment by BucherTomas** [comment]
@rbouqueau Have you managed to find out, if setting `blockAlign="always"` automatically is feasible?

**Comment by rbouqueau** [comment]
Thanks for touching base, this came out of my head. I'll do it shortly.

**Comment by rbouqueau** [comment]
Ok I need to achieve more interop tests before taking care of this. Let me know if you have any feedback on the implement or about what you could test in case it can help me.

**Comment by BucherTomas** [comment]
I've done a couple of tests with assorted VP9-based MP4 content, various pixel formats, various resolutions up to 4k and have not encountered any issues with playback on Firefox, Chrome and Android (just a subset of content was tested here), with the exception of pixel formats, where I cannot vouch for everything. Mp4box was able to dash and encrypt it without problems, but I could not always verify playback due to limited support in clients.

**Comment by rbouqueau** [comment]
Thank you, much appreciated.

**Comment by BucherTomas** [comment]
Thank you, from my side it now behaves as I want, i.e. same crypt xml for all video formats, so this is complete as far as I  am concerned personally and you can close it once you are satisfied.
