### ISSUE TITLE
Can't concatenate these HEVC valid files

### ISSUE THREAD

**Issue by avibrazil** [gpac/gpac#1128]
Having [this valid set of video files](https://avi.alkalay.net/clipboard/gpac-bug-hevc-concat.zip), the following command fails:

`MP4Box -cat v1.mov -cat v2.mov -cat v3.mov -new new.mov`

Note that these video files contain subtitles and several metadata, which are expected to be preserved in the resulting file. At least the concatenated subtitles.

Using GPAC 0.7.1 on Fedora Linux.

**Comment by jeanlf** [comment]
indeed, now fixed on git - thanks for the report and test seq.
