### ISSUE TITLE
Cannot compile latest commit

### ISSUE THREAD

**Issue by Noctem** [gpac/gpac#1129]
When trying to compile 23a35f884dc0483460cc1d107e4265eae23f0a43 with clang on macOS through homebrew (`brew install --HEAD --with-ffmpeg gpac`), it failed with 20 errors in *av_parsers.c*. The same errors occurred on your buildbot [here](http://gpacvm-ext.enst.fr/buildbot/#/builders/5/builds/332), and apparently also on [other platforms](https://travis-ci.org/gpac/gpac/builds/422738176).

b6f7409 compiled fine.

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...).

**Comment by yan12125** [comment]
Got the same issue on Arch Linux x86_64.

**Comment by rbouqueau** [comment]
Let me have a look

**Comment by rbouqueau** [comment]
Let me have a look

**Comment by rbouqueau** [comment]
Thanks for reporting. Should be fixed by ad75e5388f, I missed a file when committing. Sorry for the inconvenience.

**Comment by Noctem** [comment]
Thanks for the quick fix.
