### ISSUE TITLE
Add support for flac in mp4

### ISSUE THREAD

**Issue by jyavenard** [gpac/gpac#1133]
As per title.

attempting to encrypt an mp4 with an opus or flac trac gives:
[iso file] Unknown box type fLaC
[iso file] Unknown box type dfLa

or:
[iso file] Unknown box type Opus
[iso file] Unknown box type dOps

the file generated is also garbage, with no moov box

**Comment by rbouqueau** [comment]
FYI Opus has made good progress: https://github.com/gpac/gpac/pull/1219

**Comment by jeanlf** [comment]
opus is done, reaming

**Comment by jeanlf** [comment]
now in GPAC 0.9.0
