### ISSUE TITLE
Osmo4

### ISSUE THREAD

**Issue by alexkyu** [gpac/gpac#1140]
I'd like to try it out, as its advertised on gpac's webpage. I've got all the deps, wxGTK, wxPython... Cloned the git master. And the make is still not building it.
After digging in source I found its been disabled in the /applications/Makefile 8 years ago, ehh. So I uncommented those 3 lines in hope to get osmo4 finally compiled: 
```
#APPDIRS+=osmo4_wx
#V4STUDIODIR=V4Studio
#INSTDIRS+=osmo4_wx
```
But naturally I'm now encountering some compile time errors. I don't know is it trivial or not to fix them, or is it possible or not to compile Osmo4 nowdays. Here is what I get:
```

make[2]: Leaving directory `/root/Downloads/GGPAC/gpac/applications/dashcast'
make[2]: Entering directory `/root/Downloads/GGPAC/gpac/applications/osmo4_wx'
  CC wxOsmo4.cpp
g++ -Wall -fno-strict-aliasing -I"/root/Downloads/GGPAC/gpac/include" -I/usr/lib/wx/include/gtk2-unicode-release-2.8 -I/usr/include/wx-2.8 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXGTK__ -c -o wxOsmo4.o wxOsmo4.cpp
In file included from /root/Downloads/GGPAC/gpac/include/gpac/setup.h:54:0,
                 from /root/Downloads/GGPAC/gpac/include/gpac/maths.h:38,
                 from /root/Downloads/GGPAC/gpac/include/gpac/events.h:49,
                 from /root/Downloads/GGPAC/gpac/include/gpac/user.h:53,
                 from /root/Downloads/GGPAC/gpac/include/gpac/terminal.h:56,
                 from wxOsmo4.h:50,
                 from wxOsmo4.cpp:28:
/root/Downloads/GGPAC/gpac/include/gpac/configuration.h:163:2: error: #error "Unknown target platform used with static configuration file"
make[2]: *** [wxOsmo4.o] Error 1
make[2]: Leaving directory `/root/Downloads/GGPAC/gpac/applications/osmo4_wx'
make[1]: *** [apps] Error 2
make[1]: Leaving directory `/root/Downloads/GGPAC/gpac/applications'
make: *** [all] Error 2
 

```
Hopefully somone can give some attention to this issue, and if Osmo4 is really not being built for past 8 years maybe update the gpac webpage.

**Comment by sandyradhia** [comment]
hi 
the error tell you that "Unknown target platform used with static configuration file"  inside /root/Downloads/GGPAC/gpac/include/gpac/configuration.h

to fix it 
open with text editor as notepad++ configuration.h file and edit default line 30 by changing

#define GPAC_CONFIGURATION "(static configuration file)" 
by 
#define <your GPAC configuration option>

for exemple to use GPAC for android i configure 
#define GPAC_CONFIG_ANDROID

you also have others parameters option such as
GPAC_CONFIG_DARWIN
GPAC_IPHONE

you can found more option inside configuration.h 


hope i will solved your issue

**Comment by alexkyu** [comment]
Ah, I managed to compile it after I removed a portion of code from that file and then I had to do few more minor fixes and it finally compiled. Tho I see gcc built the osmo4 binary, looks like it is never auto installed, never been added to main makefile? hm, why

**Comment by jeanlf** [comment]
this is deprecated and was no longer maintained
