### ISSUE TITLE
MP4Box and iTunNORM, iTunSMPB

### ISSUE THREAD

**Issue by grylem** [gpac/gpac#1141]
MP4Box destroys iTunNORM and iTunSMPB atoms.
MP4Box  -itags tool=MP4Box test.m4a
or any other action destroys iTunNORM, iTunSMPB names, values etc.
Regards.

**Comment by jeanlf** [comment]
could you upload a sample file?

**Comment by grylem** [comment]
Yes.
test.m4a - file with normal iTunNORM, iTunSMPB
test_processed.m4a - after MP4Box -itags.....
[test.zip](https://github.com/gpac/gpac/files/2406505/test.zip)

**Comment by jeanlf** [comment]
This was fixed by 87f11d6, reopen if needed
