### ISSUE TITLE
Playing AV1 contents using MP4Client

### ISSUE THREAD

**Issue by irrz** [gpac/gpac#1147]
Hi there 
I have a quick question and really I couldn't solve it

I have encoded videos using the AV1 then I wrapped them into .mp4, and then i dashed them using the MP4Box

Now, on the another side, I cannot retreive the segmented videos!!
PFA

Your help in this issue is fully appreciated
![av1 issue](https://user-images.githubusercontent.com/16091677/46264483-4c4e8700-c515-11e8-8747-dda241f8802d.PNG)

**Comment by rbouqueau** [comment]
Simple question: can you play an equivalent MPD with H264?

**Comment by jeanlf** [comment]
no followup, closing
