### ISSUE TITLE
Main Profile SIDX box timing errors

### ISSUE THREAD

**Issue by richardbushell** [gpac/gpac#115]
We seem to have working DASH for our Baseline Profile tests, but are now testing our Main Profile files and we get SIDX box timing errors reported in DASH Validator.
Here is our test file:  http://living.tv/mob/test.mp4
This is Main Profile 3.1 at 25fps.
The strict keyframes are 3.84 seconds (3840ms).
We used:-
MP4Box -raw 1:output=test.h264 test.mp4 -new
MP4Box -add test.h264 -fps 25 -new test.m4v
MP4Box -dash 3840 -frag 3840 -rap -frag-rap -no-frags-default -profile dashavc264:live -new -segment-name $RepresentationID$\seg_ -url-template -out "out\test.mpd" test.m4v:id=testVideo
I can confirm that the video segments do correctly report as being 3840ms each.
The resulting mpd can be found here:  http://living.tv/mob/test.mpd
The DASH Conformance Validator ( http://dashif.org/conformance.html ) reports the following problems with the SIDX timings:-
-----
### Referenced track duration 0.120000 of track 1 does not match to subsegment_duration 3.840000 for leaf with EPT 45.960000, difference 3.720000e+000, threshold 4.000000e-005 (Leaf count 14)
-----
We have also tried it without -raw using the mp4 directly as the video and get the same.
Is MP4Box writing the wrong figures in the SIDX box?
Richard

**Comment by jeanlf** [comment]
hmm there could be an issue with timing precision. Have you tried using -dash 4000 and no frag dur ? With -rap given MP4Box will cut at GOP boundaries

**Comment by jeanlf** [comment]
Could you try with latest git ? I fixed a wrong RAP detection bug that should solve your issue

**Comment by richardbushell** [comment]
Hi Jean
Great, well done with the bug fix, it works perfectly now. No timing errors reported.
Please close the issue.
Thanks.
Richard
