### ISSUE TITLE
MP4Box *.mov to *.mp4 error

### ISSUE THREAD

**Issue by grylem** [gpac/gpac#1150]
MP4Box -add test.mov -new test.mp4
multiple errors like
[iso file] Read Box "mp4a" failed (Invalid IsoMedia File) - skipping
[isom] not enough bytes in box text: 36 left, reading 51 (file isomedia/box_code_3gpp.c, line 339)

**Comment by jeanlf** [comment]
this should be fixed in 0.8.0, please retry and reopen if needed
