### ISSUE TITLE
Dash-if profiles creating invalid files

### ISSUE THREAD

**Issue by BucherTomas** [gpac/gpac#1152]
Using dash-if (dashavc264:live or dashavc264:onDemand) profiles is now apparently creating invalid files, alll the other profiles are ok. This started happening sometime between 0.7.2-DEV-rev646-ge148a8dd-master and current master 0.7.2-DEV-rev801-g04de29dc-master

Simple `mp4box -dash 4000 -rap -frag-rap -sample-groups-traf -profile dashavc264:live -bs-switching no videotrack.mp4 -out manifest.mpd` successfully dashes the input mp4 with just video track, but when attempting to play it in Chrome or Opera, it fails, browser complaining about `CHUNK_DEMUXER_ERROR_APPEND_FAILED: Append: stream parsing failed`.

Playing it in mp4client helped, because it hinted at the underlying issue:

`[iso file] TREX with default sample desription set to 0, likely broken! Fixing to 1` . When looking at the trex box, I found it to be true, default sample description byte was 00 and correcting it to 01 fixed the playback in Chrome and Opera.

Not sure, if I am expected to modify the command line somehow to use dash-if profiles with recent GPAC builds, or if it is just a bug.

**Comment by jeanlf** [comment]
this is a wrong warning from gpac and a bug from browsers since such files use no default in trex. I just patched this to never write trex.defaultSampleDescription to 0, use 1 instead. Tell us if that fixes your issue

**Comment by BucherTomas** [comment]
Just tested with 0.7.2-DEV-rev814-g5847199a-master and yes, it does, thank you.
