### ISSUE TITLE
Cannot build under Debian Jessie

### ISSUE THREAD

**Issue by SoftCreatR** [gpac/gpac#1153]
I am experiencing the same issues as in #616, but on Debian Jessie using `OpenSSL 1.1.0f  25 May 2017`:

```
LIBS -lm -L/usr/local/lib  -lz -lssl -lcrypto -ljpeg -lpng -lpthread -ldl
utils/downloader.o: In function `gf_dm_connect':
downloader.c:(.text+0x237d): undefined reference to `SSLeay_add_all_algorithms'
collect2: error: ld returned 1 exit status
Makefile:265: recipe for target '../bin/gcc/libgpac.so' failed
make[1]: *** [../bin/gcc/libgpac.so] Error 1
make[1]: Leaving directory '/root/gpac-0.7.1/src'
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 2
```

I am using the latest stable release, 0.7.1, but earlier versions also fail for the same reason.

EDIT:

Just downgraded OpenSSL to `1.0.1t` and libssl to `1.0.0`. However, the configure script didn't recognize OpenSSL at all, but building was successful.

**Comment by aureliendavid** [comment]
Can you try with the latest git version? 

I think this was fixed by https://github.com/gpac/gpac/commit/e64a7d229fdcb5c190064b7860ade50124dcc735

**Comment by jeanlf** [comment]
no news, closing
