### ISSUE TITLE
How to split the tiles of enhancement layer?

### ISSUE THREAD

**Issue by l-Lawliet-l** [gpac/gpac#1154]
I have encoded a two-layered SHVC tiled video with SHM, and want to split the tiles of each layer for video streaming.
I have tried these commands to split the tiles, but only the tiles of base layer succeed.

`MP4Box -add str.bin:FMT=SHVC:svcmode=splitnox:fps=30 -new out.mp4`
`MP4Box -add out.mp4#1:split_tiles -new out1.mp4`
`MP4Box -add out.mp4#2:split_tiles -new out2.mp4`

The output file of base layer (out1.mp4) has N+1 tracks (N is the number of tiles), but the output file of enhancement layer (out2.mp4) has only one track.

**Comment by jeanlf** [comment]
Not possible at the moment, but interesting. Could you upload a test sample?

**Comment by jeanlf** [comment]
closing for now - if anyone is interested, reopen with a sample file
