### ISSUE TITLE
How to get output from -info

### ISSUE THREAD

**Issue by iamlion12** [gpac/gpac#1155]
Hello, everyone! I'm really sorry for asking this. Can some tell me how to export line "Visual Track Layout" for video file into the python?

**Comment by rbouqueau** [comment]
Hello, which python are you talking about?

**Comment by iamlion12** [comment]
Ya, sorry, I mean how to get output from this command. In python we can use subprocess module for execution system commands and then getting the stdout output. But I guess Mp4box prints information not in stdout. Maybe exist some option for saving output in xml format?

**Comment by rbouqueau** [comment]
It is written in stderr. Can you dump stderr?

**Comment by aureliendavid** [comment]
> maybe exist some option for saving output in xml format or json or whateversuitableformat?

there isn't at the moment, you'll have to parse the text output

in python you can use something like 

`x,y,w,h = re.findall(r'Visualll Track layout: x=(\d+) y=(\d+) width=(\d+) height=(\d+)', txt)[0]`
