### ISSUE TITLE
Facing Decoder Issue

### ISSUE THREAD

**Issue by swetheendra84** [gpac/gpac#1156]
I am trying to play gpac video through mp4client and facing floowing issue

Cannot find decoder for stream type MPEG-H HEVC Video
Stream Setup Failure: Media Codec not found.

I have installed ffmpeg.
my ./configure is showing  

OpenSVCDecoder: no
OpenHEVCDecoder: no
I am using Ubuntu 14.04 version OS.

How can I resolve this?

Thanks

**Comment by aureliendavid** [comment]
@swetheendra84 : checkout the discussion here, it might help: https://github.com/gpac/gpac/issues/979

**Comment by swetheendra84** [comment]
Infact, I have referenced it but still not clear how to proceed with it. I
have cloned openHEVC from git but dont know how to build ffmpeg_update. Can
you provide steps?
I have copied sample program mentioned and compiled it, its giving
error *cannot
find lopenhevc.* How can I resolve this*? *

Thanks,
Swetheendra.
ᐧ

**Comment by jeanlf** [comment]
please check https://github.com/gpac/gpac/wiki/Build-Introduction
