### ISSUE TITLE
MP4Box uuid atom value in m4v, broken and undesirable atoms(tag)

### ISSUE THREAD

**Issue by grylem** [gpac/gpac#1157]
MP4Box -add test.mp4 -new test.m4v
MP4Box write uuid atom (avc1 box) for test.m4v but value always is 00000000-0000-0000-0000-000000000000.

test.mp4 with copyright, copyright value is word "TEST"
MP4Box -ab "avc1"  test.mp4 and now value for copyright is empty.

Also MP4Box write for some mp4 2 strange atoms "----" in moov/udta/meta/ilst  with empy values

**Comment by cconcolato** [comment]
You need to provide an example file for people to reproduce your problem.

**Comment by grylem** [comment]
test.mov - source
MP4Box -add test.mov -new test.m4v
test.m4v with uuid 00000000-0000-0000-0000-000000000000
tagged.m4v -source, test3.m4v is copy of the tagged.m4v
MP4Box -rb "M4A " test3.m4v
test3.m4v with empty "Copyright" and strange "----"
test.m4a - file with 2 tags iTunSMPB and iTunNORM, wrong_tag.m4a - copy of the test.m4a
MP4box -rb isom wrong_tag.m4a
now wrong_tag.m4a have wrong "----" instead iTunSMPB and iTunNORM
Regards and I hope this will help you
[test_files.zip](https://github.com/gpac/gpac/files/2666905/test_files.zip)
P.S.
I think that MP4Box converts unknown tags to "----"

**Comment by jeanlf** [comment]
This should now be fixed, thanks for the files
