### ISSUE TITLE
MP4Box mpd file is not playing properly in dash.js

### ISSUE THREAD

**Issue by gsandeep828** [gpac/gpac#1158]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by gsandeep828** [comment]
Generated mpd file for an mp4 file using the following command:
MP4Box -dash 2000 -profile dashavc264:live -bs-switching multi -url-template test.mp4#trackID=1:id=vid0:role=vid0 test.mp4#trackID=2:id=aud0:role=aud0 -out test.mpd;

GPAC version is:
MP4Box -version MP4Box - GPAC version 0.5.1-DEV-rev4065 GPAC Copyright (c) Telecom ParisTech 2000-2012 GPAC Configuration: --disable-wx --prefix=/usr/local/Cellar/gpac/0.5.2 --mandir=/usr/local/Cellar/gpac/0.5.2/share/man --disable-x11-shm --disable-x11-xv Features: GPAC_64_BITS GPAC_HAS_SSL

Then tried playing this file using dash.all.min.js(V 2.9.0) in angularjs application and facing issue while playing the video. The video gets paused and doesnt get played again after sometime.If forwarded or backwarded the video doesn't play and gets paused.

**Comment by rbouqueau** [comment]
Could you upload your test.mp4 file somewhere ? (anonymous dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95 - please ping us after uploading and put a relevant filename with issue number in it)

Is there a way to test with dash.js v2.9.0 from their public URL and confirm it doesn't work?

**Comment by jeanlf** [comment]
does it work when using -bs-switching no ?

**Comment by gsandeep828** [comment]
@rbouqueau 
I have uploaded the video(NatGeoLive.mp4) to the link u posted.This is not the problem with only one file but all mp4 files. Is the command to dash the mp4 file correct or should I try a different one?

**Comment by gsandeep828** [comment]
@jeanlf 
No it is not working even with -bs-switching no.

**Comment by aureliendavid** [comment]
you seem to be using quite an old version - can you try with a recent build ? (https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/ or building it yourself)

**Comment by aureliendavid** [comment]
@gsandeep828 

Looking at your video, it isn't aligned for 2s segments. 

see https://gpac.wp.imt.fr/2015/11/02/check-key-frame-alignment-with-mp4box/

or using a command like 

```
$ ffprobe www/NatGeoLive.mp4 -select_streams v:0 -show_entries frame=key_frame,pkt_pts_time,coded_picture_number -of csv=print_section=0  | egrep "^1,"

1,0.000000,0
1,5.405400,162
1,10.410400,312
1,15.482133,464
1,17.650967,529
1,20.653967,619
1,21.988633,659
1,26.126100,783
1,31.531500,945
1,36.770067,1102
1,40.040000,1200
1,42.175467,1264
1,43.843800,1314
1,45.678967,1369
```

We see that the video has a keyframe every 5s or so. You need to increase the segment duration (or reencode the video to fit a smaller segment duration). 

I tried with 10s and dash.js seemed to play the video well (with the latest version of gpac): 

`MP4Box -dash 10000 -profile dashavc264:live -bs-switching multi -url-template www/NatGeoLive.mp4#trackID=1:id=vid0:role=vid0 www/NatGeoLive.mp4#trackID=2:id=aud0:role=aud0 -out www/manifest.mpd`

(with recent gpac versions you can also play with the `-closest` and `-bound` options to see if it increases the stability of the dashed video - see `MP4Box -h dash` for help)

**Comment by gsandeep828** [comment]
@aureliendavid 
Thanks for the reply.I see that for different mp4 files the keyframe is different.How can i provide the duration in the above command dynamically for different mp4 files?

**Comment by aureliendavid** [comment]
> How can i provide the duration in the above command dynamically for different mp4 files?

You can't directly (at least not to my knowledge). You have to know what you're dashing (how it was encoded) to get the parameters right. Usually videos made for dashing are encoded with the segment duration in mind (see http://www.gpac-licensing.com/2014/11/03/bitmovin-leverage-mp4box-package-contents-bitdash-player/)

For other videos, it might be possible to write a script to guesstimate a suitable segment duration based on the commands in https://gpac.wp.imt.fr/2015/11/02/check-key-frame-alignment-with-mp4box/

I haven't done it though.

**Comment by gsandeep828** [comment]
Thank you for your comments. I have reviewed the links and generated segment duration. I could see different segments being generated. I'm stuck now as I have files with size 100-500MB. Is there a way i can pass these values to generate segments? We need to make it dynamic to create the segments correctly.

<SyncSampleEntry sampleNumber="1"/>
<SyncSampleEntry sampleNumber="61"/>
<SyncSampleEntry sampleNumber="121"/>
<SyncSampleEntry sampleNumber="181"/>
<SyncSampleEntry sampleNumber="241"/>
<SyncSampleEntry sampleNumber="301"/>
<SyncSampleEntry sampleNumber="361"/>
<SyncSampleEntry sampleNumber="421"/>
<SyncSampleEntry sampleNumber="465"/>
<SyncSampleEntry sampleNumber="525"/>
<SyncSampleEntry sampleNumber="585"/>
<SyncSampleEntry sampleNumber="645"/>

**Comment by gsandeep828** [comment]
I have seen that even Youtube uses Dashing in playing the videos.I wonder how they are able to play various files without any issue using dashing.
Any help is appreciated.

**Comment by Murmur** [comment]
@gsandeep828 Can you re-encode to align keyframes? Try this code, also rule number one use the latest mp4box and ffmpeg tools.
- If input file is 25fps then 75(3*fps) gop closedgop, scenecut disabled.
- audio rate as dash scale, segment 6sec(6*scale), one sidx entry, live profile even for vod content.
- feel free to change bitrates, this is just an example.
```
ffmpeg -i video.mp4 -threads 4 -preset veryfast -c:v libx264 -profile:v main -level 4.0 -s:v 1280x720  -b:v 1500k -pix_fmt yuv420p -refs 3 -bf 3 -g 75 -keyint_min 25 -b_strategy 1 -flags +cgop -sc_threshold 0 -movflags negative_cts_offsets+faststart -an -y temp-v1.mp4
ffmpeg -i video.mp4 -threads 4 -preset veryfast -c:v libx264 -profile:v main -level 4.0 -s:v 1920x1080 -b:v 2100k -pix_fmt yuv420p -refs 3 -bf 3 -g 75 -keyint_min 25 -b_strategy 1 -flags +cgop -sc_threshold 0 -movflags negative_cts_offsets+faststart -an -y temp-v2.mp4
ffmpeg -i video.mp4 -threads 4 -c:a aac -strict experimental -b:a 128k -maxrate:a 128k -bufsize:a 128k -af aresample=44100 -ar 44100 -ac 2 -vn -y temp-a1.mp4
MP4Box -dash 264600 -frag 264600 -dash-scale 44100 -bound -mem-frags -rap -profile dashavc264:live -min-buffer 12000 -bs-switching no -sample-groups-traf -single-traf -subsegs-per-sidx -1 -segment-name "$RepresentationID$/$Number$$Init=i$" -out manifest.mpd temp-v1.mp4#trackID=1:id=v1:period=p0 temp-v2.mp4#trackID=1:id=v2:period=p0 temp-a1.mp4#trackID=1:id=a1:period=p0
```

Use Dashjs(nightly) and GoogleShaka for testing. You must select `(custom asset)` in shaka then can input mpd url.
http://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html
https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html
https://shaka-player-demo.appspot.com/demo/#build=uncompiled

**Comment by jeanlf** [comment]
I think we can close this one - reopen if needed
