### ISSUE TITLE
MP4Box add additional PTS after dash

### ISSUE THREAD

**Issue by rainliu** [gpac/gpac#1160]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [*] I looked for a similar issue and couldn't find any.
- [*] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [*] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). 

I use the following command to do the dash for sample.mp4:
./MP4Box -dash 2000 -profile dashavc264:onDemand -bs-switching no -rap -frag-rap -out output.mpd sample.mp4

The sample.mp4 has the following pkt_pts, pkt_pts_time for key frames:
~/ffprobe -loglevel error -skip_frame nokey -select_streams v:0 -show_entries frame=pkt_pts,pkt_pts_time -of csv=print_section=0 sample.mp4
1248,0.065000
58848,3.065000
116448,6.065000
174048,9.065000

But the sample_dashinit.mp4 generated by MP4Box,
~/ffprobe -loglevel error -skip_frame nokey -select_streams v:0 -show_entries frame=pkt_pts,pkt_pts_time -of csv=print_section=0 sample_dashinit.mp4
2496,0.130000
60096,3.130000
117696,6.130000
175296,9.130000

Please note that sample.mp4 has edts box with two elst:
segment duration,  media time, 
65 , -1
9967, 1280

Looks like MP4Box still keep edts box untouched, but inserted 1248 into sidx box's earliest_presentation_time. This cause PTS shift, which cause potential A/V sync issue.

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/
[
[sample.mp4.zip](https://github.com/gpac/gpac/files/2544440/sample.mp4.zip)
[sample_dashinit.mp4.zip](https://github.com/gpac/gpac/files/2544441/sample_dashinit.mp4.zip)

](url)

**Comment by jeanlf** [comment]
doing a -dtsx on each file gives the same file, so the DTS/CTS timestamps are exactly the same in both file. Beware that the timing in the sidx is the Presentation time, i.e. the sample composition time with edit list applied
