### ISSUE TITLE
MP4Box generated mp4 and QuickTime Pro 7

### ISSUE THREAD

**Issue by grylem** [gpac/gpac#1161]
MP4Box -add test.mov test.mp4
MP4Box -add test.aac test.h264 test1.mp4
QT7 cannot open/view mp4
![qt7](https://user-images.githubusercontent.com/16815041/47950378-b6fa4480-df51-11e8-9b37-ac5ebc250b63.jpeg)

**Comment by jeanlf** [comment]
Is your AAC more than 2 channels ? If so please use a very recent version of GPAC and check the asemode import switch (the default behaviour should be compatible MP4 and QT7)

**Comment by jeanlf** [comment]
should now be supported, thanks for the report
