### ISSUE TITLE
how to create a working manifest file for HECV

### ISSUE THREAD

**Issue by Engin92** [gpac/gpac#1165]
Hi, i am learning how to dash videos with different encoding formats to stream them adaptively on a HTML page.

I could create easily AVC/x264 and VP9, but my HEVC manifest file wont work for some reason. I can create the different video files & the manifest.mpd file, but it doesn't start on html when i bind it to my web player. These are the commands i am using:

1080p: ffmpeg -i input.avi -s 1920x1080 -c:v libx265 -crf 28 -b:v 3000k -g 90 -an hevc_1080p.mp4
720p: ffmpeg -i input.avi -s 1280x720 -c:v libx265 -crf 28 -b:v 1500k -g 90 -an hevc_720p.mp4
480p: ffmpeg -i input.avi -s 854x480 -c:v libx265 -crf 28 -b:v 500k -g 90 -an hevc_480p.mp4
360p: ffmpeg -i input.avi -s 640x360 -c:v libx265 -crf 28 -b:v 400k -g 90 -an hevc_360p.mp4
180p: ffmpeg -i input.avi -s 320x180 -c:v libx265 -crf 28 -b:v 250k -g 90 -an hevc_180p.mp4

this is the part, where the problem is (i guess):
manifest file: mp4box -dash 10000 -rap -profile:v -mpd-title BBB -out manifest.mpd -frag 4000 audio.mp4 hevc_180p.mp4 fate_hevc_360p.mp4 hevc_480p.mp4 hevc_720p.mp4 hevc_1080p.mp4

PS: i tried the same commands for AVC, but instead of "-profile:v", i used "dashavc264:onDemand " and it worked! But both of them wont work for hecv. GPAC creates the mpd file, but the video starts only with Audio but no Video.

-------------------------

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by rbouqueau** [comment]
Not many browsers support HEVC: https://caniuse.com/#search=hevc. Is yours compatible?

**Comment by Engin92** [comment]
Wow, that was my fault. I was trying to play it on Mozilla the whole time. It works (partly) on Edge. I will try it on Safary. Thank you for the hint!
