### ISSUE TITLE
how to split the tiles

### ISSUE THREAD

**Issue by navid-mahmoudian** [gpac/gpac#1168]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hello,

I used Kvazaar to encode my yuv file with HEVC with single tile per slice. Using this useful  [tutorial](https://gpac.wp.imt.fr/2017/02/01/hevc-tile-based-adaptation-guide/) I noticed that I am able to split the tiles of each frame into different tracks using:
`MP4Box -add video_tiled.hvc:split_tiles -new video_tiled.mp4`
 What I need is that I want to extract a stream per tile which each stream is separately decodable using HEVC HM software. For example, for a 3x3 tiling I am looking for 9 streams that I am able to decode each one separately and after decoding I have the reconstructed region related to the area of the tiles. Is it possible to do this with GPAC?

**Comment by mdasari823** [comment]
I believe the MP4Client decoder from gpac can do that. I think it decodes the tiles individually.

**Comment by navid-mahmoudian** [comment]
Thanks a lot for your answer. The question is how?
The first problem is that I need a stream per each tile. The command
`MP4Box -add video_tiled.hvc:split_tiles -new video_tiled.mp4`
gives a single mp4 file and I don't have access to the stream of each tile. So, first I need a way to extract my 9 streams (3x3 tiles). This is my first problem. 
Second problem is that I want each of these streams to be separately decodable with HEVC HM decoder software.

**Comment by jeanlf** [comment]
You need to remove the tiles you don't want (MP4Box -rem) then  extract the tile base track ( MP4Box -raw 1 ) . 

Note however that the resulting bitstream still has the original resolution, and might not be decodable if you don't have the first tile of the picture:  first_slice_in_pic would never be seen, which might not be well supported by most decoders.
