### ISSUE TITLE
Question: Using GPAC Client in HMDs such as Occulus Rift or Google Cardboard

### ISSUE THREAD

**Issue by mdasari823** [gpac/gpac#1169]
Hi,
I was wondering if we can play 360 videos in MP4Client/Osmo4 on Android using HMDs like Occulus Rift or Google Cardboard. If so, I am not sure how GPAC can communicate with the HMDs. Any idea? Thanks.

**Comment by jeanlf** [comment]
We have a draft support for psvr you can check. Basically MP4Clien already supports side by side 360 rendering, the first part is to get the gyro info from the hmd and inject it into the player. Then for better quality you might have to modify the shader code to compensate lens distortion but that might depend on the sdk used
