### ISSUE TITLE
CAMERA to HTTP Live video

### ISSUE THREAD

**Issue by didierjeanphi** [gpac/gpac#1174]
Good afternoon,

I am developping an acquisition program that uses an industrial camera. This camera generate a raw bytes array that I should broadcast via HTTP. Note that I can save a recording using openCV but the requirement is to have a live stream.

I have downloaded gpac and ffmpeg but do not really know where to start. Could someone be kind enough and explain to me how I can use Gpac to solve my problem?

Thank you

**Comment by jeanlf** [comment]
check documentations and forum on the web, reopen if needed
