### ISSUE TITLE
modify the mp4client

### ISSUE THREAD

**Issue by yaobing1341** [gpac/gpac#1175]
Dear sirs,

I would like to add new stream to the MP4Client and keep two bitwidth streams to be drawn at the same time.
However,after one month investigation of codes.I found it is not workable because the present codes structure is not easy to change for that.

Any positive help would be highly appreciated.

Best regards
Kevin Yoo

**Comment by jeanlf** [comment]
What do you mean by "two bitwidth" ?

If you need to draw two videos at the same time, you can either
- modify gf_scene_regenerate in gpac/src/terminal/scene to inlcude more than one main media, but this might be a bit complex
- load your streams through an svg or bt/xmt file declaring two video objects (see bifs,laser or svg samples in gpac/tests/media/), each object pointing to a different url

**Comment by yaobing1341** [comment]
yes,I found that.I add create_image function referring to create_movie function in gf_scene_regenerate function by imagetexture node.
I also revised the mpd xml file by adding another stream.
Now I have to modify other codes.
Anyway thank you very much!
BTW,your code is very nice and complicated.

**Comment by yaobing1341** [comment]
I have a difficulty that for another stream I have added,in the function of "gf_odm_setup_object" the codes can not enter the else branch of "else if ( ((odm->flags & GF_ODM_NO_TIME_CTRL) || (odm->flags & GF_ODM_NOT_IN_OD_STREAM)) && gf_odm_should_auto_select(odm) && (odm->parentscene->selected_service_id == odm->OD->ServiceID))" to call gf_odm_start to call gf_odm_play to call MPD_Servicecommand to call gf_dash_group_select to let another base_group to be GF_DASH_GROUP_SELECTED.

**Comment by yaobing1341** [comment]
Dear Sir,

Could you please give me any tips?
I really do not know how to go ahead.

Best regards
Yaobing

**Comment by yaobing1341** [comment]
Dear Jean,

I can collect the two streams by two index base groups.
But in the thread of dash_main_thread_proc,it can not download the two streams continually.
It is might caused by the cache problem.
It is too complicated for me.
Could you please explain more to me?
Your answer is highly appreciated.

Thanks and best regards
Yaobing

**Comment by jeanlf** [comment]
Actually the simplest approach would be to use 
`MP4Client mosaic://URL1:URL2`
This will generate a side by side of the two services. Reopen if needed
