### ISSUE TITLE
Issue with MP4Client

### ISSUE THREAD

**Issue by irrz** [gpac/gpac#1178]
Hello guys 

I have encoded videos using the ffmpeg and the encoder i am using is the libx265.
However, now it is not playing via MP4Client tool when i want to play the dashed videos; although these videos are palyable when using the ffplay!

Please find the attached photo

Many thanks 
![mp4client issue](https://user-images.githubusercontent.com/16091677/50028823-d1abe880-ffe8-11e8-9f01-6ec8ce6805b4.PNG)

**Comment by aureliendavid** [comment]
it looks like it's saying that the mpd url is unreachable

are you sure you're able to download the hevc500_dash.mpd from that url with wget or by pasting the url in a browser?
