### ISSUE TITLE
Replacing a .m4s segment with some other .m4s segment

### ISSUE THREAD

**Issue by mdasari823** [gpac/gpac#1189]
Hi,

I created DASH segments (set of *.m4s files and an mpd file) using MP4Box. The MP4Client plays the mpd file perfectly. I am trying to replace one of these .m4s files with some other random .m4s file. I see the obvious errors such as _incorrect sequence number_ as shown below. I tried to edit the .m4s file to match the original one but I am failed to so successfully.

```
[iso file] Warning: wrong sequence number: got 1 but last one was 29031
Sample 2 (size 17955) rewrite: corrupted NAL Unit (size 50200577)
Sample 3 (size 22180) rewrite: corrupted NAL Unit (size 2204911855)
[iso file] Invalid nal size 0 in sample 4
[hevc @ 0x7fb41403cd60] Invalid NAL unit 0, skipping.
[hevc @ 0x7fb41403cd60] Invalid NAL unit size.
[hevc @ 0x7fb41403cd60] Error splitting the input into NAL units.
[hevc @ 0x7fb414056860] Invalid NAL unit size.
[hevc @ 0x7fb414056860] Error splitting the input into NAL units.
[hevc @ 0x7fb414068320] Invalid NAL unit size.
[hevc @ 0x7fb414068320] Error splitting the input into NAL units.

```

There is an existing thread [here](https://sourceforge.net/p/gpac/discussion/327349/thread/de499f7f/). Some of the answers are from **Romain**. But, I still I haven't figured out how to modify the .m4s file with correct details. Any comments? Thank you.

**Comment by rbouqueau** [comment]
The sequence number message is a warning and should not impact you. The other point mentioned by Jean in the old thread is the TFDT (an absolute decode time) that could be more problematic. 

However from your log message it seems like you have other issues with your content. Could you share two samples so that I investigate your errors?

Could you tell us more about your use-case?

**Comment by mdasari823** [comment]
The use-case is that I am using a machine learning model to generate some of the tile segments instead of fetching them from the server. So, once generate the images, I am trying to make a segment in .m4s format so the client can play it as if it were downloaded this segment from the cloud. The high level goal is to reduce the bandwidth by not bringing some segments from cloud.

You can find the two samples [here](https://drive.google.com/drive/folders/1prI7sUlbgeMoW_DHZ8Dv_zvnMMru7Eo9?usp=sharing)

Actually, I am also guessing the reason behind Invalid NAL units is that the two segments have very different characteristics. For example, the original segment is small tile segment (384x384) which is part of large 4K frame (i.e, divided into 5x10 tiles). Where as the one I am replacing it with, is a complete 1x1 tile segment which is of 384x384 frame in size. Not sure if this is bringing problems.

**Comment by jeanlf** [comment]
Also another thing you need to be careful about is your usage of sample flags in track runs. It might be worth using a video analyzer on your segments. Closing since there's not much we can do to help here.
