### ISSUE TITLE
MP4Box static has a depency on libpthread

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#119]
Most MP4Box users don't need streaming features that use threading.

This causes issues with toolchains or libc where pthread is not completely implemented (e.g. bionic, the android libc).

**Comment by bearcave9** [comment]
@rbouqueau I'd like to work on this. Could you please get me started. Thanks

**Comment by rbouqueau** [comment]
Ideally you wold need an environment where libthread-dev is not present. A cross toolchain (building from one platform to another e.g. linux to win32 or to android) is likely to trigger more bugs (and then make your work easier).

The aim is to see which features/functions use threading and disable then using a ```#ifdef``` such as:
https://github.com/gpac/gpac/blob/master/include/gpac/configuration.h

The aim is to be able to build GPAC with zero external lib dependency.

See also ```--disable-core``` in https://github.com/gpac/gpac/blob/master/configure.

**Comment by jeanlf** [comment]
hmm no, this would require removing a few things from MP4Box (mpd ripper, ATSC3 ripper)
