### ISSUE TITLE
How to stream mpd and mp4 videos

### ISSUE THREAD

**Issue by dorcatty** [gpac/gpac#1191]
Hello all,
Thanks to MP4Box I can generated my own video segments (m4s) and mpd files. But I have some difficulties to put them on the server. I was wondering whether .mpd file needs a specific Web Server ? 

First I tried with my personal Http Web Server, by given the http://www.aaaa.com/file.mpd my browser just display the xml file <title> content. However, with some online .mpd file examples,  after putting the mpd address in my browser, it asked me whether i would like to donwload it as a file. 

I also tested putting MP4Box generated files (a set of m4s files and mpd) to my AWS EC2 instance. But it remains the same, my browser just displayed the pure text of the <title>, no download request as the online examples. As far as I know, the AWS EC2 is CORS enabled.

I need a special server to store these generated mpd and m4s files ? or I need to do to some configurations on my AWS EC2 instance ? any suggestions ?

thanks a lot

**Comment by aureliendavid** [comment]
hi, 

the browser can't play an mpd file directly (it is just an xml file), you need a video player like dash.js

see the example here: https://github.com/Dash-Industry-Forum/dash.js/blob/development/README.md#quick-start-for-users

you put all your m4s files and your mpd on your web server, add an html page with the sample in the example where the src of the video element is your mdp, and then point your browser to that html page on your web server, and it should play

there are a bunch of dash tutorials on the web that give more details, for example here: https://blogs.msdn.microsoft.com/interoperability/2014/01/03/mpeg-dash-tutorial-embedding-an-adaptive-streaming-video-within-your-html5-application/

good luck

**Comment by aureliendavid** [comment]
if you use an android player, you don't need the html page with dash.js

however it can useful to test if your setup works with dash.js in the browser (and if not, why not)

as to why it doesn't work with the android app, I can't help you with that (make sure all the m4s segments mentioned in the mpd are reachable through your web server)

**Comment by dorcatty** [comment]
Do you think a classical web server is enough to host the mpd and m4s files ?
I have tested with IINA, (my local media player), open URL.. works well with my generated mpd and m4s files on my web server. I can play the stream videos on my local OS.  this means my resources (m4s) are reachable.

But with all the given examples on the web, hosted by google storage, etc. my browser asked me to download the mpd (pop up a window). 
With all the 'download requested' videos, i can play with my Android player. 
in this case, i guess my Android player only works with these 'download request' mpd files. 

and all the example (address with .mpd) i found on the internet, when i browse them, i always have 'download window' pops up. 

So i would like to know whether i need special settings on my web server. 
Do you know the reason ?
