### ISSUE TITLE
is this possible to convert MPTS live  AVC-H264 to Mp2

### ISSUE THREAD

**Issue by sachin0606** [gpac/gpac#1193]
Hi All, 

thanks for this tool, can we transcode the live mpts udp input stream of  AVC-H264 to MPEG2 ts over UDP?

**Comment by jeanlf** [comment]
you should be able to do that using GPAC 0.9.0, setup demuxer, [encoders](https://github.com/gpac/gpac/wiki/encoding) and use udp ts as output
