### ISSUE TITLE
4K Video: Cannot open file video for dashing

### ISSUE THREAD

**Issue by nityapurnima** [gpac/gpac#1194]
Hi I want to use mpeg dash.So I have multiple resolutions of a single video.I referred this link:https://blog.desgrange.net/post/2017/04/17/encode-videos-dynamic-adaptive-streaming-http.html

But I tried adding a 4K version also.I executed the following command:

MP4Box -dash 1000 -rap -frag-rap -profile onDemand -out video.mpd video4k.mp4 video-1080.mp4 video-720.mp4 video-480.mp4 video-360.mp4 video-240.mp4 video-audio.mp4

It gives me error:
[DASH] Cannot open file video4k.mp4 for dashing: Requested URL is not valid or cannot be found
DASH Setup Error: Requested URL is not valid or cannot be found

**Comment by jeanlf** [comment]
Make sure the file is here and valid using `MP4Box -info video4k.mp4`
