### ISSUE TITLE
unable to generate a single mpd and corresponding segments for multi-bitrate videos

### ISSUE THREAD

**Issue by nityapurnima** [gpac/gpac#1195]
I have a single video which is re-encoded to various bit rates. I have generated the corresponding mpd file also.It plays using MP4Client. I used the following command:

MP4Box -dash 4000 -frag 4000 -rap -profile onDemand -segment-name %s/segment_ -url-template -out manifest.mpd  video-240.mp4#video video-360.mp4#video video-480.mp4#video video-720.mp4#video video-audio.mp4#audio

But it generates only a single segment for each bit rate.how to generate the corresponding segments(i.e segment list) also for all the bit rates.

**Comment by jeanlf** [comment]
you have to use different profiles than onDemand, try live, main or full

**Comment by nityapurnima** [comment]
I tried with all options but its not generating the segments:

I gave this command for a single video:
MP4Box -dash 4000 -frag 4000 -rap -segment-name segment_ 1-720.mp4
1-720.mpd generated
It generates all the segments.
I want to generate these segments for all the videos with a single mpd file mentioning the segment list for each bit rate video.

**Comment by nityapurnima** [comment]
Thanks 
MP4Box -dash 4000 -frag 4000 -rap -profile simple -segment-name %s/segment_ -url-template -out manifest.mpd video-240.mp4#video video-360.mp4#video video-480.mp4#video video-720.mp4#video video-audio.mp4#audio

does the trick..

**Comment by Swapn-nil** [comment]
HI guys 
I am trying to generating my own MPDs from this side https://www.instructables.com/id/Making-Your-Own-Simple-DASH-MPEG-Server-Windows-10/
I have split the videos with different resolution
But final generating MPD command is not working properly something is wrong with this command
mp4box -dash 5000 -rap -profile dashavc264:onDemand -mpd-title BBB -out manifest.mpd -frag 2000 input_audio_128k.mp4 input_video_160x90_250k.mp4 input_video_320x180_500k.mp4 input_video_640x360_750k.mp4 input_video_640x360_1000k.mp4 input_video_1280x720_1500k.mp4

**Comment by Swapn-nil** [comment]
I have solve my issue with above cmd ..... MP4Box -dash 4000 -frag 4000 -rap -profile simple -segment-name %s/segment_ -url-template -out manifest.mpd ...Now everything is working fine 
Thank you
