### ISSUE TITLE
Conversion from m3u8 to mpd missing timescale value

### ISSUE THREAD

**Issue by PolynomialDivision** [gpac/gpac#1199]
If you are converting from m3u8 to mpd the timescale value is missing.

For example:

    <SegmentList duration="4000" startNumber="0">

has to be edited to

    <SegmentList duration="4000" timescale="1000" startNumber="0">

Gpac Version:
0.7.2-DEV-rev999-g7f11cd65d-master

**Comment by jeanlf** [comment]
thanks for the report, now fixed
