### ISSUE TITLE
Playing from cache should work when not connected to a network

### ISSUE THREAD

**Issue by cconcolato** [gpac/gpac#12]
When playing DASH content and keeping files in cache:
[DASH]
KeepFiles=yes
MemoryStorage=no

[Downloader]
CleanCache=no

Replay of the same URL when disconnected from a network should work, at least until no new segment is needed.

**Comment by jeanlf** [comment]
This is now partially implemented (offline cache), however if adaptive bitrate was used chances are that different URLs will be generated and the session won't be re-playable
