### ISSUE TITLE
Average segment duration?

### ISSUE THREAD

**Issue by delbinwen** [gpac/gpac#120]
Hi,

I'm using MP4Box to create MPEG-DASH stream with below commands.

```MP4Box -noprog -dash 5005 -frag 10000 -rap -segment-name %s_ -url-template -bs-switching no -mpd-title "sample mpd" -tmp "/tmp" -out "movie_tmp.mpd" /private/tmp/tmpB0bWPr/audio_p0.mp4#audio:id=32k /private/tmp/tmpB0bWPr/audio_p1.mp4#audio:id=64k /private/tmp/tmpB0bWPr/audio_p2.mp4#audio:id=96k /private/tmp/tmpB0bWPr/audio_p3.mp4#audio:id=128k /private/tmp/tmpB0bWPr/video_p0.mp4#video:id=240p_80k /private/tmp/tmpB0bWPr/video_p1.mp4#video:id=240p_200k /private/tmp/tmpB0bWPr/video_p2.mp4#video:id=240p_350k /private/tmp/tmpB0bWPr/video_p3.mp4#video:id=480p_700k /private/tmp/tmpB0bWPr/video_p4.mp4#video:id=480p_1200k /private/tmp/tmpB0bWPr/video_p5.mp4#video:id=480p_2000k /private/tmp/tmpB0bWPr/video_p6.mp4#video:id=720p_2500k /private/tmp/tmpB0bWPr/video_p7.mp4#video:id=720p_4000k /private/tmp/tmpB0bWPr/video_p8.mp4#video:id=720p_7000k```

I expect the segment duration should be 150150 (=5.005 * 30000), but it looks like the value of duration is average segment duration (49.68 / 10 * 30000). Below is the snippet of the result MPD.

```xml
<?xml version="1.0" encoding="utf-8"?>
<MPD maxSegmentDuration="PT0H0M5.00S" mediaPresentationDuration="PT0H0M49.68S" minBufferTime="PT1.500000S" profiles="urn:mpeg:dash:profile:full:2011" type="static" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:cenc="urn:mpeg:cenc:2013" xmlns:mspr="urn:microsoft:playready">
 <ProgramInformation>
  <Title>
   sample mpd
  </Title>
 </ProgramInformation>
 <Period duration="PT0H0M49.68S">
  <AdaptationSet segmentAlignment="true">
   <SegmentTemplate duration="149046" initialization="1429516988_dash/$RepresentationID$/init.mp4" media="1429516988_dash/$RepresentationID$/$Number$.m4s" startNumber="1" timescale="30000"/>
   <Representation bandwidth="87141" codecs="avc1.640015" frameRate="30000/1001" height="240" id="240p_80k" mimeType="video/mp4" sar="640:639" startWithSAP="1" width="426">```


I remember SegmentTemplate@duration should be constant, not average one; am I correct? And constant duration makes the player easy to locate segment(s).

Thanks,
Wesley

**Comment by delbinwen** [comment]
Okay. After looking into the code, this behavior was later changed by this commit, https://github.com/gpac/gpac/commit/0c0efac10ce926a16ff9719085ff27fabddcb930. And the value of the segment duration looks expected now.

**Comment by Murmur** [comment]
Why is `-dash 5005 -frag 10000` durations, should [frag value](http://gpac.wp.mines-telecom.fr/mp4box/dash/) always be <= dash?

**Comment by delbinwen** [comment]
I just check with my colleague. The reason he suggests to use -frag 10000 could be a workaround or trick. The objective is to force MP4Box to create just one fragment in each segment.

**Comment by rbouqueau** [comment]
> should frag value always be <= dash?

Yes

> Why is -dash 5005 -frag 10000 durations

These values are wrong. One expects an integer number of fragments per segments. Please read: http://gpac.wp.mines-telecom.fr/2011/02/02/mp4box-fragmentation-segmentation-splitting-and-interleaving/

> I just check with my colleague. The reason he suggests to use -frag 10000 could be a workaround or trick. The objective is to force MP4Box to create just one fragment in each segment.

```-frag``` is optional. By default segment duration (set with ```-dash```) is the frag duration (hence one frag per segment).

**Comment by Murmur** [comment]
> These values are wrong. One expects an integer number of fragments per segments
That's what I thought but your last comment puzzles me. Syntax is `-dash 10000 -frag 5000` to give 10sec segment_x.m4s files and two mp4 fragment boxes inside it. Its not -dash 10000 -frag 2 as your comment made me, right.

**Comment by rbouqueau** [comment]
Correct. The syntax of ```-frag``` is this way because you can fragment without using ```-dash```
