### ISSUE TITLE
Conversion from m3u8 with variable segment duration to mpd

### ISSUE THREAD

**Issue by PolynomialDivision** [gpac/gpac#1200]
If I convert a m3u8 with

    #EXTM3U
    #EXT-X-VERSION:7
    #EXT-X-TARGETDURATION:7
    #EXT-X-MEDIA-SEQUENCE:0
    #EXT-X-MAP:URI="init.mp4"
    #EXTINF:4.416667,
    bunny0.m4s
    #EXTINF:4.000000,
    bunny1.m4s
    #EXTINF:7.333333,
    bunny2.m4s
    #EXTINF:4.000000,
    bunny3.m4s
    #EXTINF:3.291667,
    bunny4.m4s
    #EXTINF:4.000000,
    bunny5.m4s
    #EXTINF:2.958333,
    bunny6.m4s
    #EXT-X-ENDLIST

I get something like this

    <SegmentList duration="7000" startNumber="0">
    <Initialization sourceURL="init.mp4"/>
    <SegmentURL media="bunny0.m4s"/>
    <SegmentURL media="bunny1.m4s"/>
    <SegmentURL media="bunny2.m4s"/>
    <SegmentURL media="bunny3.m4s"/>
    <SegmentURL media="bunny4.m4s"/>
    <SegmentURL media="bunny5.m4s"/>
    <SegmentURL media="bunny6.m4s"/>
    </SegmentList>

To get it working I have to change it to

    <SegmentTemplate timescale="1000" initialization="init.mp4" media="bunny$Number%01d$.m4s" startNumber="0">
    <SegmentTimeline>
      <S t="0" d="4416" />
      <S d="4000" />
      <S d="7333" />
      <S d="4000" />
      <S d="3291" />
      <S d="4000" />
      <S d="2958" />
    </SegmentTimeline>
    </SegmentTemplate>

Gpac Version:
0.7.2-DEV-rev999-g7f11cd65d-master

**Comment by jeanlf** [comment]
thanks for the report, now fixed
