### ISSUE TITLE
Question. Generating multi-period MPD

### ISSUE THREAD

**Issue by arodrigoca** [gpac/gpac#1202]
Platform: ubuntu 18.04
GPAC version: 0.7.1

Hi, just a question. I'm trying to make a multi-period MPD. I want every period to correspond with an .mp4 file which will have different segment duration, bitrate, etc. In addition, I want the manifest to use SegmentTemplate for segment localization. I've tried using -url-template and -out file1.mp4:period=<name> but dash.js will play the first 2 periods and get stuck on the third. I know it can be done for a fact because I have an example mpd that was generated with gpac by someone else, that works (ezample from DASH-IF Testvectors). http://dash.akamaized.net/dash264/TestCasesIOP33/multiplePeriods/4/manifest_multiple_Periods_Different_SegmentDuration.mpd

 I also read that parameters for each periods can be done by referencing a text file, but I cannot find much info about it on the doc. Thank you in advance.

**Comment by rbouqueau** [comment]
Why is the dash.js error when it stops?

**Comment by jeanlf** [comment]
no news, closing
