### ISSUE TITLE
MP4Client: How to get the displayed video into a file?

### ISSUE THREAD

**Issue by gabriel7771** [gpac/gpac#1206]
Hello,
I'm doing some video transmission experiments over SDNs, and i need to obtain the same exactly video that is being displayed in MP4Client. The video is played from an HTTP server, when the network bit rate is too low it freezes (what's expected), and i need that video with the frozen part into a file, e.g. If the video have a duration of 40 seconds and it freezes at second 23, the last frame displayed must be the same in the last 17 seconds. I'm able to get a video in the cache directory but it only contains the fluid part (so this video only lasts 23 seconds, not 40). 

Is there any way to 'screen record' what MP4Client is playing on the client side through time? In other words, can i get exactly what the client is seeing into a file?

**Comment by jeanlf** [comment]
This is now possible using GPAC 0.9.0 DEV , see [wiki](https://github.com/gpac/gpac/wiki/olay-composition)
