### ISSUE TITLE
For more details on chapter file syntax...broken link

### ISSUE THREAD

**Issue by malaterre** [gpac/gpac#1208]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

The man page point to broken link:

[...]
       -chap chap_file
              adds chapter information contained in chap_file to
movie. For more details on chapter file syntax, cf
http://gpac.sourceforge.net/auth_mp4box.php.
[...]

While:

$ HEAD http://gpac.sourceforge.net/auth_mp4box.php
404 Not Found
Connection: close
Date: Tue, 07 Apr 2015 19:54:39 GMT
Via: 1.1 varnish
Age: 0
Server: Apache/2.2.15 (CentOS)
Vary: Host
Content-Length: 1677
Content-Type: text/html
Client-Date: Tue, 07 Apr 2015 19:54:40 GMT
Client-Peer: 216.34.181.96:80
Client-Response-Num: 1
X-Varnish: 838453151

**Comment by jeanlf** [comment]
man pages have been fixed in GPAC 0.9.0 (not in 0.8.0 where they are still terribly outdated). Thanks for the report
