### ISSUE TITLE
AAC-HE not creating valid MPDs or segment info in MP4box using -SBR Explicit Backwards-Compatibility Signaling

### ISSUE THREAD

**Issue by richardbushell** [gpac/gpac#121]
Hi Jean,

A few weeks back you changed some code to fix -SBRX explicit signaling for Audio using AAC-HE. Could you also do the same please for -SBR explicit BACKWARDS-COMPATIBLE signaling. These currently don't record the correct info in the MPD (still reporting AAC-LC at half the sample rate).

Our test file is here:  http://living.tv/mob/test_3840_baseline_he.mp4

DASH IOP 3.0 (Page 96) states: For all HE-AAC and HE-AACv2 bitstreams, EXPLICIT BACKWARDS-COMPATIBLE SIGNALING should be used to indicate the use of the SBR and PS coding tools.

And I note that some browsers (e.g. Chrome) only seem to be supporting Explicit Backwards-Compatible Signaling. On a separate note I believe Apple do the same for HLS too.

Please fix asap and advise.

Richard

**Comment by jeanlf** [comment]
should now be available. However the spec is not clear what samplerate (or channels for PS) should be used in such a case ... for the time being the base AAC LC sample rate/channels are used

**Comment by richardbushell** [comment]
Hi Jean
Tried -SBR again, and that seems to imprrove things!
Our test file now plays in IE8 and Chrome so that's great.
TWO questions.
Q1) I think your code now needs to just change the value recorded in the: audioProfileLevelIndication
This is currently recording the value of 40 (decimal) according to DISO on the m4a intermediate file generated, but the DASH Conformance Validator throws an error stating:
Validate_IODS: ISMA expects no-capability(0xFF) or Hi-Quality@L1/L2 (0x0E, 0x0F) or AAC@L4 (0x2a) or HE-AAC@L2 (0x2c) for audioProfileLevelIndication
So, I think audioProfileLevelIndication should be recording the decimal value of 44 (to correspond with (0x2c) as expected within the error message.
I would have to check, but I think your -SBRX version generated 44 anyway, but might be worth checking that too at the same time.
Q2) You state: 
"However the spec is not clear what samplerate (or channels for PS) should be used in such a case".
Are talking here about what are the correct text values to write to the MPD text file??? Is that what you mean? If so, I agree that I don't know whether you should write 24000 or 48000 for both the audioSamplingRate and timescale. I see my MPD file generated have 24000 for both of these values, presumably relating to the underlying AAC samplerate. We should perhaps seek clarification of whether these should be 48000 relating to the SBR instead, or not! Would be good to get this confirmed now so this issue can be fully clarified now.
Thanks
Richard

**Comment by jeanlf** [comment]
Glad it helped.
Q1: not sure where the DASH-IF IOP states that the ISOBMFF file audio profile has to be changed, I only read that the MPD signaling shall be modified to "explicit backward"
 
Q2: yes further clarifications would be needed

Q3: I'll have a look

**Comment by richardbushell** [comment]
Thanks Jean,
With regards to:
Q1) We create -RAW (which I believe strips the MP4Sys info) then use ADD to create a M4A intermediate. I am sure that your -SBRX creates the Audio Profile Level Indicator of value 44, but -SBR is writing 40 for this value and should obviously be 44 too. As I understand it, ss defined in ISO/IEC 14496-3:2009   Information technology -- Coding of audio-visual objects -- Part 3: Audio
0x28   AAC Profile L1
0x29   AAC Profile L2
0x2A   AAC Profile L4
0x2B   AAC Profile L5
0x2C   High Efficiency AAC v1 Profile L2
0x2D   High Efficiency AAC v1 Profile L3
0x2E   High Efficiency AAC v1 Profile L4
0x2F   High Efficiency AAC v1 Profile L5
0x30   High Efficiency AAC v2 Profile L2
0x31   High Efficiency AAC v2 Profile L3
0x32   High Efficiency AAC v2 Profile L4
0x33   High Efficiency AAC v2 Profile L5
So, I am sure that 0x2C (44 in decimal) should be used.
As stated, I believe -SBRX already writes 44, so -SBR should too. Do you agree?
Q2) We have also looked for confirmation here:
https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/50
Q3) Yes, please check -SBRX should still write mp4a.40.5 as before -SBR fix.
Thanks
Richard

**Comment by jeanlf** [comment]
Q1: why should SBR implicit be signaled as SBR profile ? We use AAC base profile because that is what is signaled in the file
Q2: OK let's see 
Q3: fixed

**Comment by richardbushell** [comment]
Q1) 0x2C High Efficiency AAC v1 Profile L2 surely states the correct audio profile for ALL HE-AAC v1 audio, whether Implicit Signalling, Explicit Backwards, or Explicit Non-Backwards.
All of these are HE-AAC v1 audio, just different signalling methods.

**Comment by jeanlf** [comment]
The spec is not really clear about what should be put there. The issue is that if HEAACv1 is signaled as a profile in the iods for an sbr with implict signaling, then a player doing only aac base will not read the file, which defeats the goal of the implicit signaling no ?

**Comment by richardbushell** [comment]
I confess, I genuinely do not know either, hopefully the DASH-IF query above (about what samplerate to write in the MPD file) may also address or answer this too.

If we are writing AAC-LC to the Audio Profile Level Indicator shouldn't this be 41 (0x29) for STEREO rather than 40 (0x28) anyway, i.e. AAC-LC@L2 ?

**Comment by richardbushell** [comment]
One further question, should -SBR write values in Audio Decoder Specific Info (esds) too?
Both these values show as 0 when checking the M4A file generated.
Sbr Flag 0 (should this be 1?)
Ext audio object type 0 (should this be 5?)
Any thoughts on this too please? Sorry, this SBR issue is very confusing!?

**Comment by jeanlf** [comment]
This is GPAC's behaviour upon import of aac:

without any sbr flag: write AudioSpecInfo base object type = 2

-sbrx: write AudioSpecInfo base object type = 5

-sbr: write AudioSpecInfo base objet type = 2, and append extra data to AudioSpecInfo with SBR object type = 5 (might be called Sbr Flag / Ext audio object type, not sure about the spec's naming)

**Comment by richardbushell** [comment]
Hi Jean

Yes, that was my exact understanding of the correct behaviour too.

But my tests seem to give different results, as follows.

Our test file is here: http://living.tv/mob/test_3840_baseline_he.mp4

Here's our process:-
MP4Box -raw 2:output=test.aac test_3840_baseline_he.mp4 -new
MP4Box -add test.aac -sbr -new test.m4a

We then test this M4A file.

I don't think it shows the SBR Flag and Ext Audio Object information using -DISO (or an GPAC program we know of) so we've been checking the M4A intermediate file created using a free program called 'MP4 Reader'.
http://www.thinmultimedia.co.kr/products/MP4Reader_download.html

-SBRX reports in 'MP4 Reader':
Audio Decoder Specific Info:-
Audio object type 2 (0X00000002) 
Sampling freq index 6 (0X00000006)  
Sbr Flag 1 (0X00000001) 
Ext audio object type 5 (0X00000005) 
Ext sampling freq index 3 (0X00000003)
(on a separate note it does record 44 in the audioProfileLevelIndication as shown by -DISO)

-SBR reports in 'MP4 Reader':
Audio Decoder Specific Info:-
Audio object type 2 (0X00000002) 
Sampling freq index 6 (0X00000006)
Sbr Flag 0 (0X00000000) 
Ext audio object type 0 (0X00000000) 
Ext sampling freq index 0 (0X00000000) 
(on a separate note it does record 40 in the audioProfileLevelIndication as shown by -DISO) (also, should this be 41 for stereo, if not 44, as discussed)

Very strange if these values written are correct.
-SBRX seems to write the values I would have expected from -SBR, i.e. 2 for AOT, 5 for EAOT. I would have expected AOT = 5, and no EAOT for SBRX.
-SBR seems to write AAC-LC expected values.

I could be reading this wrongly, have you got your own tools or programs to test the resulting files from the test file as shown above?

Richard

**Comment by jeanlf** [comment]
using MP4Box -info you should have:
for the explicit signaling:
'MPEG-4 Audio SBR - 2 Channel(s) - SampleRate 24000 - SBR SampleRate 48000'

for the implicit signaling:
'MPEG-4 Audio LC - 2 Channel(s) - SampleRate 24000 - SBR SampleRate 48000'

Checking the Audio DecSpecInfo is indeed not exposed in MP4Box, but you can inspect its values using -diso

For explicit SBR, It seems that MP4Reader shows the object type after parsing rather than what is written in the bitstream, hence you have "audioObjectType=2" and "extensionAudioObjectType=5", but what is written in the bitstream is indeed "audioObjectType=5" and in the SBR section, audioObjectType=2

For SBR SBR implicit, the signaling is appended at the end of the audio DSI , and it seems MP4Reader does not show this one, only audioObjectType=2 is shown.

Hope this helps

**Comment by richardbushell** [comment]
Hi Jean
Just for clarification, in your answer above, when you talk about "implicit signaling" did you mean "explicit backwards compatible signaling" where you state:
for the implicit signaling...
For SBR implicit...
And when you talk about "explicit signaling" did you mean "explicit non-backwards compatible signaling"
???
Please check you answer and verify/confirm between "implicit", "explicit backwards", and "explicit non-backwards".
Thanks
Richard
