### ISSUE TITLE
Don't Working for Windows 10 build 1803 ( 17134.590)

### ISSUE THREAD

**Issue by surikat1978** [gpac/gpac#1211]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ Yes !] I looked for a similar issue and couldn't find any.
- [ Yes ! ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [  Yes! ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I insert different commands like:  

MP4Box -frag 10000 C:\video\111.mp4
  
And after the errors : Enter new video cache memory in kBytes (current 0d)

I tried all versions of  Gpac...

<img width="960" alt="1" src="https://user-images.githubusercontent.com/10182540/53597550-294efe80-3bab-11e9-9f62-5b17e508155f.png">

**Comment by jeanlf** [comment]
looks like you are using MP4Client and not MP4Box, can you confirm ?
