### ISSUE TITLE
How does MP4client choose representations when playing from a local storage for a hevc-coded tile-based stream which uses SRD?

### ISSUE THREAD

**Issue by mrezajamali** [gpac/gpac#1214]
Can MP4client change the quality of each tile (select the representation of each tile) based on the viewport. If so how we determine the viewport? By moving around in the gui?
Following you see how I am generating the tile-based video which I wanna play locally (so no discussion on bandwidth):

kvazaar -i Dance_Left_1920x960.yuv --input-res 1920x960 -o Dance_Left_1920x960_rep1.hvc --tiles 3x3 --slices tiles --mv-constraint frametilemargin -q 22 --input-fps 30

kvazaar -i Dance_Left_1920x960.yuv --input-res 1920x960 -o Dance_Left_1920x960_rep2.hvc --tiles 3x3 --slices tiles --mv-constraint frametilemargin -q 37 --input-fps 30

MP4Box -add Dance_Left_1920x960_rep1.hvc:split_tiles -fps 30 -new Dance_Left_1920x960_rep1.mp4

MP4Box -add Dance_Left_1920x960_rep2.hvc:split_tiles -fps 30 -new Dance_Left_1920x960_rep2.mp4

MP4Box -dash 1000 -profile live -out Dance_Left_1920x960.mpd Dance_Left_1920x960_rep1.mp4 Dance_Left_1920x960_rep2.mp4

Now when I am playing this mpd by MP4client always representation 2 is chosen for all tiles and all segments (which is the representation with the lower bitrate)

And if MP4client cannot detect the viewport how can I force it to select specific representations for each tile?

Thanks,

**Comment by jeanlf** [comment]
Just added (0.9.0 DEV) viewport adaptation for 2D, it was only implemented for 3D.
You will need to enable gaze simulation through mouse (--sgaze), the tile under the mouse will be given 100%, others 0% 

Otherwise (and this is in 0.8.0), you only have static adaptation using the tile adaptation mode (TileAdaptation in 0.8.0 or less,  dashin:tile_mode in 0.9.0)

**Comment by aureliendavid** [comment]
v0.9 is the `filters` branch: https://github.com/gpac/gpac/tree/filters

**Comment by beibeii** [comment]
I used the v0.9.0 version of MP4box to get the following mpd file, but I can't use MP4client to play. What parameters do I need to add during playback?

The program did not report an error, but the player displayed a black screen.

MP4Box -dash 5000 -profile live a.mp4 b.mp4 -out c.mpd

MP4Client  c.mpd


![image](https://user-images.githubusercontent.com/14730487/69035115-cdb8ef80-0a1d-11ea-9155-f40f55e4f5d4.png)

**Comment by ForgetMe17** [comment]
> I used the v0.9.0 version of MP4box to get the following mpd file, but I can't use MP4client to play. What parameters do I need to add during playback?
> 
> The program did not report an error, but the player displayed a black screen.
> 
> MP4Box -dash 5000 -profile live a.mp4 b.mp4 -out c.mpd
> 
> MP4Client c.mpd
> 
> ![image](https://user-images.githubusercontent.com/14730487/69035115-cdb8ef80-0a1d-11ea-9155-f40f55e4f5d4.png)

I have also met this problem, can you give some advice on this? @jeanlf
