### ISSUE TITLE
Compile and archive osmo4ios Failed

### ISSUE THREAD

**Issue by tongtianxing** [gpac/gpac#1215]
Xcode 10.1
I finish the procedures in README_IOS.
And when I execute the "gpac/build/xcode/generate_ios.sh" script.it was failed.

ld: library not found for -laom
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **

What should I do?

**Comment by aureliendavid** [comment]
argh, we have to update our dependencies process, the ffmpeg provided in the `gpac_extra_libs.zip` is out of date

in the meantime you can download this file: http://www.mediafire.com/file/bo66hp9ordqfh39/ffmpeg_ios.tar.gz/file

and replace the `ffmpeg_ios` directory in the `gpac_extra_libs` package with the one extracted for the file. 

Then run `CopyLibs2Public4iOS.sh` again (or run the equivalent commands for your gpac source directory name)

Then retry `generate_ios.sh`

**Comment by tongtianxing** [comment]
Thanks for help
