### ISSUE TITLE
[Android] Crash in the audio driver due to JNI

### ISSUE THREAD

**Issue by canatella** [gpac/gpac#122]
In the android audio driver, in the WriteAudio callback, the java audio buffer is filled like this:

```
pBuffer = (*env)->GetPrimitiveArrayCritical(env, ctx->buff, NULL);
if (pBuffer)
{
    written = dr->FillBuffer(dr->audio_renderer, pBuffer, ctx->mbufferSizeInBytes);
    (*env)->ReleasePrimitiveArrayCritical(env, ctx->buff, pBuffer, 0);
    ...
}
```

It uses the GetPrimitiveArrayCritical and ReleasePrimitiveArrayCritical to try to have a direct memory access to the buffer behind the java Array. In between those call, no JNI call can occur. 

It might happen that, when calling FillBuffer, a buffering event is triggered due to having to download more data I suppose. In order to report that event to the java layer, some JNI call must be made which than triggers the crash.

This is not reproducible in Osmo for Android because the buffering events are not reported to the java layer there. But I think the description here is pretty clear. 

Do you have any suggestion on how to avoid this ? Would it be possible to queue the buffering events to make sure they are triggered out of the critical section in the Android audio driver JNI code ?

**Comment by jeanlf** [comment]
a quick fix would be to ensure this in your JNI code, maybe adding a mutex for the android audio that you can also lock from the gpac event callback proc . I'll have a look at event queuing but this may need quite some changes

**Comment by canatella** [comment]
As a workaround, I'm registering a callback proc to the audio driver so it can notify me of the critical sections and I'm buffering events in that case.

**Comment by jeanlf** [comment]
this more generic than just audio, logs / messages or events can be triggered at any time. For now it is up to the java application to make sure reporting these events is safe
