### ISSUE TITLE
using -lang in mp4box on mp4 video creates low quality copy 

### ISSUE THREAD

**Issue by gmagdna** [gpac/gpac#1220]
Using the current release of gpac/mp4box via cmd on a Win 10 machine.

I have several mp4 videos where the Audio Language is **und** or otherwise marked as unspecified. The audio track is primarily English but there are scenes in a foreign language for which I need subtitles inserted. I use Emby to play the media and it has a Smart subtitle setting that inserts subs into only non-English scenes but to do that the Audio Language needs to be set to English. **mp4box -lang en-US file.mp4** creates a 480p copy of the 1080p file. I thought I had read somewhere that **-lang**  would just overwrite the original audio tag but that's not happening, and I'd be ok with a new file if it was the same quality as the original.

I've searched a good bit for this issue before posting so if I missed a discussion please direct me to it. TIA.

**Comment by rbouqueau** [comment]
MP4Box doesn't touch the video track. Your issue may be related to something else.

Would you mind uploading a sample (with an appropriate filename referencing the issue number) at https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95 ?

**Comment by gmagdna** [comment]
A sample of the original media? new? or both?

**Comment by gmagdna** [comment]
Odd behavior... I ran the same command again and got another 480p copy. I ran it a third time but used the trackID switch, running it once on each track, and no 480p copy was created, and the audio tag is now set to English.

**Comment by rbouqueau** [comment]
Original + command-line so that we can reproduce your issue.

**Comment by jeanlf** [comment]
no news, closing
