### ISSUE TITLE
Import metadata (picture, etc;) from Ogg into MP4

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#1221]
Sample: https://people.xiph.org/~tterribe/opus/36-11-pictures.opus

We need to wait for @jeanlf to merge the 'filters' branch as he mentioned to have modifications on the Ogg container part.

**Comment by rbouqueau** [comment]
See https://wiki.xiph.org/VorbisComment

**Comment by jeanlf** [comment]
Also we need to rework how meta-data tags are passed in filters, for now this is not unified (id3 tags, isobmf/itunes tags, ...)

**Comment by rbouqueau** [comment]
Ok let us know when you have some progress!

**Comment by jeanlf** [comment]
The provided link to sample file is dead, do you have another sample with comments/etc  ?

**Comment by rbouqueau** [comment]
Copy at https://www.gpac-licensing.com/downloads/tmp/36-11-pictures.opus

**Comment by jeanlf** [comment]
now in master, file is used in test suite
