### ISSUE TITLE
how to choose my options?

### ISSUE THREAD

**Issue by aranmohyeddin** [gpac/gpac#1222]
I want to convert some h264 mp4 videos to clearkey encrypted dash. For now I want to serve them on localhost. So I don't have bandwidth limitations. There are a few things I'm confused about. I'm assuming I should use dashavc264:onDemand profile with static mpd since my videos are not live and they are offline.

1. How should I decide what segment duration I should use? does it depend on how often I have keyframes in my video? how does it affect seeking/trickplay performance? Does it affect anything else?

2. Since I'm using onDemand profile, where each media presentation is a single segment, should I have subsegments for my single subsegment of each segment? What is the use of setting subsegments for my single subsegment of each segment? How does the duration affect other things?

3. Why would I not force my segments to begin with random access points?
4. what about my fragments?
If I understood correctly random access points are my iframes. my intuition tells me that segments should always start with I-frames. I think I don't really understand the correct meaning and purpose of segments and subsegments. Are they simply random cuts in the media stream so as to split it into chunks? What is the difference between a segment, a subsegment, and a subsegment of a subsegment.

5. Should I use segment-timeline?

6. Should I add a box of type \’MARK\’ at the end of each DASH segment. 

7. What min buffer time should I use?

8. what is the advantage of storing PSSH boxes in first moof of each segment instead of in movie box?

Thank you in advance for any help you might be willing to give.

**Comment by rbouqueau** [comment]
I'm happy to answer the non-trivial questions and the ones related to GPAC. I leave the others to a few queries on any search engine.

>  I'm assuming I should use dashavc264:onDemand

On-demand is when you only want one file. Use the 'live' profiles if you need to have several segment files. Both are valid options depending on your use-case.

> Why would I not force my segments to begin with random access points?

It depends on the players you target.

> Should I add a box of type \’MARK\’ at the end of each DASH segment.

Probably not.

> What min buffer time should I use?

Is there an issue on playback with the value set by MP4Box?

**Comment by aranmohyeddin** [comment]
@rbouqueau: I remember there was an option in bento4 to have different segments in different files or to have them all in one file and use range queries instead. is this live vs onDemand thing the same thing as that?
The player I target is dashjs. but what would be the benefit of not having the segments begin with i frames. I understand that I can achieve segments with exactly the same length but what is the point with that? Also I'm assuming forcing Iframes is the most compatible option right?

can you elaborate on the 'MARK' box thing, I actually don't really no what it does and why would somebody do it.
Yes I do have playback issues. but I'm not sure if the buffer is the reason. but since I want to play the videos locally and I have little bandwidth limitation I was wondering if It was better to set min buffer infinite or something. What happens if I set it too low/ too high?

**Comment by rbouqueau** [comment]
> I remember there was an option in bento4 to have different segments in different files or to have them all in one file and use range queries instead. is this live vs onDemand thing the same thing as that?

Yes. The names of the options of GPAC are taken from the DASH spec.

> I'm assuming forcing Iframes is the most compatible option right?

Yes.

> can you elaborate on the 'MARK' box thing, I actually don't really no what it does and why would somebody do it.

e.g. see 'eods' in http://biblio.telecom-paristech.fr/cgi-bin/download.cgi?id=14719.

> What happens if I set it too low/ too high?

The value is constraint. Setting it too high increase the latency, setting it too low decrease the latency with the risk of underflowing.

**Comment by aranmohyeddin** [comment]
@rbouqueau should I use rap-frag for onDemand or rap?

**Comment by jeanlf** [comment]
neither, setting the profile will turn the right frag-rap/rap options for you (rap is always on, frag-rap is off since some players may complain if a segment has several fragments in onDemand)
