### ISSUE TITLE
How do I use gpac in my own app

### ISSUE THREAD

**Issue by tongtianxing** [gpac/gpac#1223]
Xcode 10.1
I follow the instructions of gpac/build/xcode/ readme_ios.txt and finish Compilation.
I see 
** ARCHIVE SUCCEEDED **
*** Generate IPA ***
*** GPAC generation for iOS completed (0.7.2-DEV-rev1039-gc42257165-master)! ***
it only generate a "osmo4-0.7.2-DEV-rev1039-gc42257165-master-ios.ipa"
So how do I use gpac in my own app on xcode.

**Comment by tongtianxing** [comment]
How can i get the static library which use in xcode.

**Comment by aureliendavid** [comment]
In xcode you can open the `build/xcode/gpac4ios.xcodeproj` project and build just the `libgpac_static` scheme

Or in command line, from `build/xcode`: 

`
xcodebuild build -project gpac4ios.xcodeproj -scheme libgpac_static
`

In both cases, by default, the output library will be in `/tmp/gpac4ios.dst/usr/local/lib/libgpac_static.a`

You can the copy it wherever you need it.

**Comment by tongtianxing** [comment]
thanks for hlep
