### ISSUE TITLE
unable to run apk on android

### ISSUE THREAD

**Issue by azhar5678** [gpac/gpac#1224]
on android when i install osmo4 apk i get below errors
i search other similar issue , but iam having 32 bit windows
and intruction to build apk from gpack extra libs shows for ubuntu not for windows on gpac website

as  i have 32 bit window, i dont have cmake in android studio

$Revision$
Thu Mar 28 23:56:22 GMT+05:30 2019

*** Configuration

GpacAppDirectory=/data/data/com.gpac.Osmo4/
GpacModulesDirectory=/data/data/com.gpac.Osmo4/lib/
GpacFontDirectory=/system/fonts/
GpacCacheDirectory=/data/data/com.gpac.Osmo4/cache
GpacGuiDirectory=/data/data/com.gpac.Osmo4/gui/
GpacShaderDirectory=/data/data/com.gpac.Osmo4/shaders/

Loading library GLESv2...Loading library log...Loading library jpegdroid...Loading library javaenv...Loading library mad...Loading library editline...Failed to load editline, error=Cannot load library: soinfo_relocate(linker.cpp:992): cannot locate symbol "tcgetattr" referenced by "libeditline.so"... :: UnsatisfiedLinkError
Loading library ft2...Loading library js_osmo...Failed to load js_osmo, error=Cannot load library: soinfo_link_image(linker.cpp:1652): could not load library "libeditline.so" needed by "libjs_osmo.so"; caused by find_library(linker.cpp:903): "libeditline.so" failed to load previously :: UnsatisfiedLinkError
Loading library openjpeg...Loading library png...Loading library z...Loading library stlport_shared...Loading library stdc++...Loading library faad...Loading library gpac...Failed to load gpac, error=Cannot load library: soinfo_link_image(linker.cpp:1652): could not load library "libjs_osmo.so" needed by "libgpac.so"; caused by find_library(linker.cpp:903): "libjs_osmo.so" failed to load previously :: UnsatisfiedLinkError
Loading library gm_droid_cam...Failed to load gm_droid_cam, error=Cannot load library: soinfo_link_image(linker.cpp:1652): could not load library "libgpac.so" needed by "libgm_droid_cam.so"; caused by find_library(linker.cpp:903): "libgpac.so" failed to load previously :: UnsatisfiedLinkError
Loading library gm_droid_mpegv...Failed to load gm_droid_mpegv, error=Cannot load library: soinfo_link_image(linker.cpp:1652): could not load library "libgpac.so" needed by "libgm_droid_mpegv.so"; caused by find_library(linker.cpp:903): "libgpac.so" failed to load previously :: UnsatisfiedLinkError
Loading library gm_mediacodec_dec...Failed to load gm_mediacodec_dec, error=Cannot load library: soinfo_link_image(linker.cpp:1652): could not load library "libgpac.so" needed by "libgm_mediacodec_dec.so"; caused by find_library(linker.cpp:903): "libgpac.so" failed to load previously :: UnsatisfiedLinkError
Loading library avutil...Loading library swscale...Loading library swresample...Loading library avcodec...Loading library avformat...Loading library avfilter...Loading library gpacWrapper...Failed to load gpacWrapper, error=Cannot load library: soinfo_link_image(linker.cpp:1652): could not load library "libgpac.so" needed by "libgpacWrapper.so"; caused by find_library(linker.cpp:903): "libgpac.so" failed to load previously :: UnsatisfiedLinkError
*** Libs listing: /data/data/com.gpac.Osmo4/lib/
  libjavaenv.so [13728 bytes]
  libgm_img_in.so [26164 bytes]
  libstlport_shared.so [399384 bytes]
  libavfilter.so [1504740 bytes]
  libgm_saf_in.so [21976 bytes]
  libopenjpeg.so [89296 bytes]
  libgm_aac_in.so [26128 bytes]
  libgm_mpegts_in.so [34316 bytes]
  libgm_mediacodec_dec.so [30168 bytes]
  libavdevice.so [51108 bytes]
  libgm_widgetman.so [67088 bytes]
  libgm_ctx_load.so [26124 bytes]
  libgm_mpd_in.so [46632 bytes]
  libgm_droidout.so [21976 bytes]
  libjs_osmo.so [523656 bytes]
  libgm_mp3_in.so [22032 bytes]
  libfaad.so [221720 bytes]
  libgm_bifs_dec.so [13784 bytes]
  libeditline.so [30552 bytes]
  libft2.so [345604 bytes]
  libavcodec.so [12116216 bytes]
  libgm_timedtext.so [34320 bytes]
  libgpac.so [3287392 bytes]
  libgm_laser_dec.so [13784 bytes]
  libgm_svg_in.so [17880 bytes]
  libgm_soft_raster.so [42456 bytes]
  libgm_ismacryp.so [21976 bytes]
  libmad.so [99844 bytes]
  libgm_droid_cam.so [21976 bytes]
  libgm_isom_in.so [54800 bytes]
  libz.so [87632 bytes]
  libgm_osd.so [17884 bytes]
  libgm_rtp_in.so [54744 bytes]
  libpng.so [120376 bytes]
  libgm_ft_font.so [22052 bytes]
  libavutil.so [255452 bytes]
  libgpacWrapper.so [100068 bytes]
  libgm_droidaudio.so [17880 bytes]
  libswscale.so [320908 bytes]
  libswresample.so [75148 bytes]
  libjpegdroid.so [157188 bytes]
  libgm_ffmpeg_in.so [42516 bytes]
  libgm_odf_dec.so [17880 bytes]
  libavformat.so [1666644 bytes]
  libgm_gpac_js.so [42508 bytes]
  libgm_droid_mpegv.so [17880 bytes]
  libgm_dummy_in.so [22028 bytes]
*** Modules listing: /data/data/com.gpac.Osmo4/lib/
  libjavaenv.so [13728 bytes]
  libgm_img_in.so [26164 bytes]
  libstlport_shared.so [399384 bytes]
  libavfilter.so [1504740 bytes]
  libgm_saf_in.so [21976 bytes]
  libopenjpeg.so [89296 bytes]
  libgm_aac_in.so [26128 bytes]
  libgm_mpegts_in.so [34316 bytes]
  libgm_mediacodec_dec.so [30168 bytes]
  libavdevice.so [51108 bytes]
  libgm_widgetman.so [67088 bytes]
  libgm_ctx_load.so [26124 bytes]
  libgm_mpd_in.so [46632 bytes]
  libgm_droidout.so [21976 bytes]
  libjs_osmo.so [523656 bytes]
  libgm_mp3_in.so [22032 bytes]
  libfaad.so [221720 bytes]
  libgm_bifs_dec.so [13784 bytes]
  libeditline.so [30552 bytes]
  libft2.so [345604 bytes]
  libavcodec.so [12116216 bytes]
  libgm_timedtext.so [34320 bytes]
  libgpac.so [3287392 bytes]
  libgm_laser_dec.so [13784 bytes]
  libgm_svg_in.so [17880 bytes]
  libgm_soft_raster.so [42456 bytes]
  libgm_ismacryp.so [21976 bytes]
  libmad.so [99844 bytes]
  libgm_droid_cam.so [21976 bytes]
  libgm_isom_in.so [54800 bytes]
  libz.so [87632 bytes]
  libgm_osd.so [17884 bytes]
  libgm_rtp_in.so [54744 bytes]
  libpng.so [120376 bytes]
  libgm_ft_font.so [22052 bytes]
  libavutil.so [255452 bytes]
  libgpacWrapper.so [100068 bytes]
  libgm_droidaudio.so [17880 bytes]
  libswscale.so [320908 bytes]
  libswresample.so [75148 bytes]
  libjpegdroid.so [157188 bytes]
  libgm_ffmpeg_in.so [42516 bytes]
  libgm_odf_dec.so [17880 bytes]
  libavformat.so [1666644 bytes]
  libgm_gpac_js.so [42508 bytes]
  libgm_droid_mpegv.so [17880 bytes]
  libgm_dummy_in.so [22028 bytes]
*** Fonts listing: 
/system/fonts/
  AndroidClock.ttf [5116 bytes]
  AndroidClock_Highlight.ttf [4824 bytes]
  AndroidClock_Solid.ttf [4824 bytes]
  AndroidEmoji.ttf [448680 bytes]
  AnjaliNewLipi-light.ttf [47408 bytes]
  Clockopia.ttf [6880 bytes]
  DroidNaskh-Regular-SystemUI.ttf [111520 bytes]
  DroidNaskh-Regular.ttf [89456 bytes]
  DroidSans-Bold.ttf [79620 bytes]
  DroidSans.ttf [79396 bytes]
  DroidSansArmenian.ttf [13856 bytes]
  DroidSansDevanagari-Regular.ttf [123372 bytes]
  DroidSansEthiopic-Regular.ttf [227928 bytes]
  DroidSansFallback.ttf [791684 bytes]
  DroidSansGeorgian.ttf [21096 bytes]
  DroidSansHebrew-Bold.ttf [30280 bytes]
  DroidSansHebrew-Regular.ttf [30024 bytes]
  DroidSansMono.ttf [119380 bytes]
  DroidSansTamil-Bold.ttf [36448 bytes]
  DroidSansTamil-Regular.ttf [36308 bytes]
  DroidSansThai.ttf [35480 bytes]
  DroidSerif-Bold.ttf [185228 bytes]
  DroidSerif-BoldItalic.ttf [190304 bytes]
  DroidSerif-Italic.ttf [177560 bytes]
  DroidSerif-Regular.ttf [172916 bytes]
  Lohit-Bengali.ttf [139296 bytes]
  Lohit-Gujarati.ttf [60264 bytes]
  Lohit-Gurblipi.ttf [51000 bytes]
  Lohit-Kannada.ttf [196664 bytes]
  Lohit-Oriya.ttf [97220 bytes]
  Lohit-Telugu.ttf [171892 bytes]
  MTLmr3m.ttf [2871020 bytes]
  NanumGothic.ttf [1429144 bytes]
  Roboto-Bold.ttf [79620 bytes]
  Roboto-BoldItalic.ttf [82880 bytes]
  Roboto-Italic.ttf [82580 bytes]
  Roboto-Light.ttf [108216 bytes]
  Roboto-LightItalic.ttf [111440 bytes]
  Roboto-Regular.ttf [79396 bytes]
  Roboto-Thin.ttf [113996 bytes]
  Roboto-ThinItalic.ttf [117512 bytes]
  RobotoCondensed-Bold.ttf [105684 bytes]
  RobotoCondensed-BoldItalic.ttf [109028 bytes]
  RobotoCondensed-Italic.ttf [108428 bytes]
  RobotoCondensed-Regular.ttf [105140 bytes]
  SecDroidSansFallbackFull.ttf [4529044 bytes]
*** Exceptions:
gm_mediacodec_dec: Cannot load library: soinfo_link_image(linker.cpp:1652): could not load library "libgpac.so" needed by "libgm_mediacodec_dec.so"; caused by find_library(linker.cpp:903): "libgpac.so" failed to load previously(class java.lang.UnsatisfiedLinkError)
js_osmo: Cannot load library: soinfo_link_image(linker.cpp:1652): could not load library "libeditline.so" needed by "libjs_osmo.so"; caused by find_library(linker.cpp:903): "libeditline.so" failed to load previously(class java.lang.UnsatisfiedLinkError)
gpacWrapper: Cannot load library: soinfo_link_image(linker.cpp:1652): could not load library "libgpac.so" needed by "libgpacWrapper.so"; caused by find_library(linker.cpp:903): "libgpac.so" failed to load previously(class java.lang.UnsatisfiedLinkError)
gm_droid_cam: Cannot load library: soinfo_link_image(linker.cpp:1652): could not load library "libgpac.so" needed by "libgm_droid_cam.so"; caused by find_library(linker.cpp:903): "libgpac.so" failed to load previously(class java.lang.UnsatisfiedLinkError)
editline: Cannot load library: soinfo_relocate(linker.cpp:992): cannot locate symbol "tcgetattr" referenced by "libeditline.so"...(class java.lang.UnsatisfiedLinkError)
gm_droid_mpegv: Cannot load library: soinfo_link_image(linker.cpp:1652): could not load library "libgpac.so" needed by "libgm_droid_mpegv.so"; caused by find_library(linker.cpp:903): "libgpac.so" failed to load previously(class java.lang.UnsatisfiedLinkError)
gpac: Cannot load library: soinfo_link_image(linker.cpp:1652): could not load library "libjs_osmo.so" needed by "libgpac.so"; caused by find_library(linker.cpp:903): "libjs_osmo.so" failed to load previously(class java.lang.UnsatisfiedLinkError)

**Comment by azhar5678** [comment]
anyone please answer

**Comment by kahanikaar** [comment]
If you want to compile the GPAC packages, you can refer to 
https://gpac.wp.imt.fr/compiling-gpac-for-android/

This shows the usage of GPAC on a Galaxy Tab
https://www.youtube.com/watch?v=himalbWpga4

if you want the osmo4 apk, try downloading this,
https://download.tsi.telecom-paristech.fr/gpac/release/0.8.0/osmo4-0.8.0-rev1-gc1990d5c-master.apk

**Comment by jeanlf** [comment]
also try latest git, we've been doing quite some fixes for 1.0
