### ISSUE TITLE
Ts dash content generated using MP4Box period switching not happening.

### ISSUE THREAD

**Issue by karthik098** [gpac/gpac#1225]
I have created the Ts dash related MPD by the following command 
MP4Box -dash 10000 -profile mp2t-simple  --url-template newtest.ts:period=0 newtest.ts:period=1
 and the mpd genrated looks like below :

```
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500000S" type="static" mediaPresentationDuration="PT0H2M2.26S" profiles="urn:mpeg:dash:profile:full:2011">
<ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
<Title>newtest_dash.mpd generated by GPAC</Title>
</ProgramInformation>
<Period id="0" duration="PT0H1M1.13S">
<AdaptationSet segmentAlignment="true" maxWidth="480" maxHeight="272" par="480:272" subsegmentAlignment="true">
<ContentComponent id="256" contentType="video"/>
<ContentComponent id="257" contentType="audio"/>
<Representation id="1" mimeType="video/mp2t" width="480" height="272" audioSamplingRate="44100" startWithSAP="0" bandwidth="3540522">
<SegmentTemplate timescale="90000" duration="900000" startNumber="1" media="newtest_dash$Number$.ts" index="newtest_dash.six" presentationTimeOffset="126000"/>
</Representation>
</AdaptationSet>
</Period>
<Period id="1" duration="PT0H1M1.13S">
<AdaptationSet segmentAlignment="true" maxWidth="480" maxHeight="272" par="480:272" subsegmentAlignment="true">
<ContentComponent id="256" contentType="video"/>
<ContentComponent id="257" contentType="audio"/>
<Representation id="2" mimeType="video/mp2t" width="480" height="272" audioSamplingRate="44100" startWithSAP="0" bandwidth="3540522">
<SegmentTemplate timescale="90000" duration="900000" startNumber="1" media="newtest_dash$Number$.ts" index="newtest_dash.six" presentationTimeOffset="126000"/>
</Representation>
</AdaptationSet>
</Period>
</MPD>
```

using this mpd the playback of first period is fine but it fails to switch to other period .
 
- [ yes ] I looked for a similar issue but it was for mp4 ,with the same command as mentioned above i have generated stream for  mp4  dash content it works fine .

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by rbouqueau** [comment]
Without providing your content + the player, we cannot reproduce your issue. So we won't be able to help you.

**Comment by karthik098** [comment]
hello, I am using MP4Box to create the ts dash content ,can any body help me to know  what exactly  -rap (random access points) attribute  does,and what  if we don't use that,what can be possible drawbacks.

**Comment by jeanlf** [comment]
We need player info to help

-rap cuts ts at idr boundaries for quality switching, check our [wiki pages](https://github.com/gpac/gpac/wiki/MP4Box-Introduction)
