### ISSUE TITLE
Merging multiple tracks of HEVC DASH segments into single segment for playback

### ISSUE THREAD

**Issue by JuheonYi** [gpac/gpac#1227]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hello, following the tutorials provided, I have successfully managed to encode the video into tiles with HEVC, split each tiles as separate .mp4 files, and merge them back into a single .mp4 file.

Moving forward, my goal is to implement a tile-based DASH video streaming, where a client requests only some number of tiles (not the full frame).

For start, I DASHed the video divided into 2x2 tiles and got the following files:
init.mp4 (containing 1+2*2 tracks)
track1_init.mp4 (containing 1 track)
track2_init.mp4
...
track5_init.mp4

track1_bitrate1_segment1.m4s
...
track1_bitranteN_segment1.m4s
track2_bitrate1_segment1.m4s
...
track2_bitrateN_segment1.m4s
...

My question is, how can I merge different tile segments back into a single segment, that can be playbacked in the client?

In case of .mp4 files without DASH, all I had to do was merge different tracks with the commands like
MP4Box -add Q2.mp4#6 -ref 4:tbas:1 -ref 1:sabt:4 Q1.mp4

However, in case of DASH, I have no idea which files I should merge (init.mp4, track1_init.mp4, track1_bitrate1_segment1.m4s, ...etc.)

I would really appreciate if someone could tell me the solution.

Thanks very much in advance.

**Comment by jeanlf** [comment]
you need to physically concatenate, eg with cat, the global init (eg init.mp4) and then for each segment, a file of a given quality for each track in the order of the tiles, always starting with the base track. You don't need to update the track references as they should be properly setup in the global init segment
