### ISSUE TITLE
Encoding each tiles in a HEVC video in different bitrates

### ISSUE THREAD

**Issue by JuheonYi** [gpac/gpac#1228]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hello, 

I am trying to implement a tile-based DASH streaming, where a client can adapt bitrates for each tile in the frame.

In order to achieve the goal, I want to obtain each tiles in video with different bitrates, for example
tile_1_1Mbps.mp4
tile_1_2Mbps.mp4
...
tile_2_1Mbps.mp4
tile_2_2Mbps.mp4
...

However, using ffmpeg I cannot encode each tracks, 
("ffmpeg could not find codec parameters" error shows up...guess maybe the problem comes from the fact that each tile.mp4 has hvc2 format, which ffmpeg does not support?)
and encoding the whole video in a bitrate and dividing to tracks results in each tile bitrate different from the designated bitrate.

Could someone help with the issue?

Thanks in advance

**Comment by mdasari823** [comment]
Why are you using ffmpeg? I am not sure what your goal is, but you can use Kvazaar encoder for transcoding the videos. See below link for the tiled ABR streaming.

[Tiled Streaming](https://github.com/gpac/gpac/wiki/Tiled-Streaming)

**Comment by jeanlf** [comment]
Yes, try with kvazaar
