### ISSUE TITLE
error in c++

### ISSUE THREAD

**Issue by tongtianxing** [gpac/gpac#1229]
I completed the compilation according to the README_IOS.txt guide.
I can use gpac on my project normally. But now I need to wrap the mp4 method in C++ and there are some problems.
Undefined symbols for architecture arm64:
   "gf_media_hevc_read_sps(char*, unsigned int, _hevc_state*)", referenced from:
       CRecWriterMP4::WriteH265Nalu(unsigned char**, int*) in RecWriterMP4.o
   "gf_media_hevc_read_pps(char*, unsigned int, _hevc_state*)", referenced from:
       CRecWriterMP4::WriteH265Nalu(unsigned char**, int*) in RecWriterMP4.o
   "gf_media_hevc_read_vps(char*, unsigned int, _hevc_state*)", referenced from:
       CRecWriterMP4::WriteH265Nalu(unsigned char**, int*) in RecWriterMP4.o
Ld: symbol(s) not found for architecture arm64
Clang: error: linker command failed with exit code 1 (use -v to see invocation)
Those methods I can compile on ObjectC.
I do not know what to do.

**Comment by nanshuii** [comment]
how to fix ?
