### ISSUE TITLE
buffers should all be u8*, not char*

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#123]
As of GPAC 0.6.1, there are many places where data pointers are `char *` while not being strings. It would be better to deal with type `u8 *` (wrapper around `unsigned char *`) for generic data.

Examples:
- gf_bs (bitstream): https://github.com/gpac/gpac/blob/9e3d1939b30331cf58088a39a01d62f14ea7b0b3/include/gpac/bitstream.h#L70
- https://github.com/gpac/gpac/blob/9e3d1939b30331cf58088a39a01d62f14ea7b0b3/src/utils/xml_parser.c#L151
- https://github.com/gpac/gpac/blob/9e3d1939b30331cf58088a39a01d62f14ea7b0b3/src/terminal/media_memory.h#L100
- src\scenegraph\x3d_nodes.c
- src\scenegraph\vrml_tools.c
- src\scene_manager\scene_manager.c
- src\odf\odf_code.c(2425):        ipmp->opaque_data = (char*)gf_malloc(size + 1);
- src\odf\ipmpx_code.c(90):    ba->data = (char_)gf_malloc(sizeof(char)_size);
- src\media_tools\mpegts.c(3405):          ts->buffer = (char_)gf_realloc(ts->buffer, sizeof(char)_ts->alloc_size);
- src\media_tools\media_import.c(5848):                    slc->data = (char_)gf_malloc(sizeof(char)_slc->size);
- src\media_tools\dsmcc.c(245):        DownloadInfoRequest->privateDataByte = (char*)gf_calloc(DownloadInfoRequest->privateDataLength,sizeof(char));
- and a lot more ...

**Comment by bearcave9** [comment]
@rbouqueau  I'd like to work on this. How should I start and could you provide other details that will help solving this issue.

**Comment by rbouqueau** [comment]
I am going to complete the description. There is another issue that is look-alike and is simpler IMHO: https://github.com/gpac/gpac/issues/47 . Would you consider looking at it?

**Comment by jeanlf** [comment]
done in 0.9.0 for all public API and internal headers (should have fixed most of them)
