### ISSUE TITLE
encrypt vedio for android

### ISSUE THREAD

**Issue by azhar5678** [gpac/gpac#1230]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

i encrypt the vedio with mp4box on win 7 with clear key
 but the vedio is not playing on osmo4 android it stop after file opening.

also why the  vedio not loading from pendrive in osmo4

**Comment by jeanlf** [comment]
we don't support any key management system at the moment, not even clearkey.
what do you mean by not loading from pendrive?

**Comment by azhar5678** [comment]
That means I cannot play mp4 encrypted vedios on Android with gpac anyhow.
I am sure there is some way like in Windows.

**Comment by azhar5678** [comment]
From pendrive I mean ,showing pendrive in gpac GUI in Android and playing
vedios directly from there.

**Comment by azhar5678** [comment]
how to play encrypted vedio on android

**Comment by azhar5678** [comment]
if osmo4 can play encrypted vedio on linux,
then it should not having any problem in android

beacause android is just linux and nothing
