### ISSUE TITLE
gpac nhml common encryption breakdown example explaination BS tags.

### ISSUE THREAD

**Issue by aranmohyeddin** [gpac/gpac#1231]
I'm sorry if this is a sort of a trivial question but I fail to actually understand what BS tags are for. maybe it's because I don't have a good enough knowledge about MSE and I'm a newcomer in these stuff.
I read the [nhml docs](https://gpac.wp.imt.fr/mp4box/media-import/nhml-format/) and also the [common encryption docs](https://gpac.wp.imt.fr/mp4box/encryption/common-encryption/) but I still fail to really understand the format. I would really appreciate it if you could be so kind as to break down and compare these three xml files:

> ctr example from [here](https://github.com/gpac/gpac/blob/master/tests/media/encryption/ctr.xml)

```
<?xml version="1.0" encoding="UTF-8" ?>
<GPACDRM type="CENC AES-CTR">

<!-- example for GPAC - keys are listed after the content and UL follows -->
<DRMInfo type="pssh" version="1" cypherOffset="9" cypherKey="0x6770616363656E6364726D746F6F6C31" cypherIV="0x00000000000000000000000000000001">
<BS ID128="6770616363656E6364726D746F6F6C31"/>
<BS value="1" bits="32"/>
<BS ID128="0x279926496a7f5d25da69f2b3b2799a7f"/>
<BS bits="8" string="CID=Toto"/>
<BS ID128="0x5544694d47473326622665665a396b36"/>
</DRMInfo>

<CrypTrack trackID="1" IsEncrypted="1" IV_size="16" first_IV="0x0a610676cb88f302d10ac8bc66e039ed" saiSavedBox="senc">
<key KID="0x279926496a7f5d25da69f2b3b2799a7f" value="0x5544694d47473326622665665a396b36"/>
</CrypTrack>

</GPACDRM>
```

> The file used by [this guy](https://github.com/Dash-Industry-Forum/dash.js/issues/1346)

```
<GPACDRM type="CENC AES-CTR">
  <DRMInfo type="pssh" version="1">
    <BS ID128="1077efecc0b24d02ace33c1e52e2fb4b"/>
    <BS bits="32" value="1"/>
    <BS ID128="cd7eb9ff88f34caeb06185b00024e4c2"/>
  </DRMInfo>
  <CrypTrack IV_size="8" first_IV="0x603f39bfdb3d9799" isEncrypted="1" saiSavedBox="senc" trackID="1">
    <key KID="0xcd7eb9ff88f34caeb06185b00024e4c2" value="0x63cb5f7184dd4b689a5c5ff11ee6a328"/>
  </CrypTrack>
</GPACDRM>
```

> The advanced example in [gpac docs](https://gpac.wp.imt.fr/mp4box/encryption/common-encryption/)

```
<?xml version="1.0" encoding="UTF-8"?>
<GPACDRM type="CENC AES-CTR">
<DRMInfo type="pssh" version="1" cypherOffset="9" cypherKey="0x6770616363656E6364726D746F6F6C31" cypherIV="0x00000000000000000000000000000001">
<BS ID128="6770616363656E6364726D746F6F6C31"/>
<BS value="4" bits="32"/>
<BS ID128="0x279926496a7f5d25da69f2b3b2799a7f"/>
<BS ID128="0x597669572e55547e656b56586e2f6f68"/>
<BS ID128="0x205b2b293a342f3d3268293e6f6f4e29"/>
<BS ID128="0x32783e367c2e4d4d6b46467b3e6b5478"/>
<BS bits="8" string="CID=Toto"/>>
<BS ID128="0x5544694d47473326622665665a396b36"/>
<BS ID128="0x7959493a764556786527517849756635"/>
<BS ID128="0x3a4f3674376d6c48675a273464447b40"/>
<BS ID128="0x3e213f6d45584f51713d534f4b417855"/>
</DRMInfo>
<CrypTrack trackID="1" IsEncrypted="1" IV_size="16" first_IV="0x0a610676cb88f302d10ac8bc66e039ed" selectiveType="RAP" saiSavedBox="senc" keyRoll="roll=5">
<key KID="0x279926496a7f5d25da69f2b3b2799a7f" value="0x5544694d47473326622665665a396b36"/>
<key KID="0x597669572e55547e656b56586e2f6f68" value="0x7959493a764556786527517849756635"/>
<key KID="0x205b2b293a342f3d3268293e6f6f4e29" value="0x3a4f3674376d6c48675a273464447b40"/>
<key KID="0x32783e367c2e4d4d6b46467b3e6b5478" value="0x3e213f6d45584f51713d534f4b417855"/>
</CrypTrack>
</GPACDRM>
```

Is there any reason why one might not only encrypt RAPs for a movie? I can understand that in some types of videos for example a video with some critical text encrypting only the RAPs would not be enough but what about for a movie. is there any disadvantage?

Also I don't understand why the first one doesn't have the key in the DRMInfo tag.

By The Way, Here is the xml I tried to make myself but it doesn't work:
```
<?xml version="1.0" encoding="UTF-8" ?>
<GPACDRM type="CENC AES-CTR">
    <DRMInfo type="pssh" version="1">
        <BS ID128="1077efecc0b24d02ace33c1e52e2fb4b"/>
        <BS bits="32" value="1"/>
        <BS ID128="cd7eb9ff88f34caeb06185b00024e4c2"/>
    </DRMInfo>
    <CrypTrack trackID="1" IsEncrypted="1" IV_size="8" first_IV="0x603f39bfdb3d9799" saiSavedBox="senc" selectiveType="RAP">
        <key KID="0xcd7eb9ff88f34caeb06185b00024e4c2" value="0x63cb5f7184dd4b689a5c5ff11ee6a328"/>
    </CrypTrack>
</GPACDRM>
```
Also I read in the docs:

> trackID : specifies the track ID to encrypt. If not set, this crypt configuration applies to all tracks for which no CryptTrack with a trackID is specified.
So I expect to get moth audio and video tracks encrypted if I don't specify trackID but if I don't specify it nothing happens. So I just duplicate the `CrypTrack` tag, one with trackID="1" and the other with trackID="2" is that the right way of encrypting both tracks with the same key?

**Comment by jeanlf** [comment]
<BS> tags are used to describe binary structure rather than do it manually with another tool, as explained in NHML doc.

The file using selective RAP encryption is a test file, up to you to do it or not :)

The key is usually not present in the DRMInfo, but at least the KID is.

The behaviour you experience when no trackID is specified has been fixed in 0.8.0
