### ISSUE TITLE
mp4 to mpd strange issue

### ISSUE THREAD

**Issue by dorcatty** [gpac/gpac#1232]
Thanks everyone here to improve MP4box,

Recently we had an strange issue while play mpd file in our mobile VR (android system with Exoplayer).

We have tested with the demo of SDK, comes with a .mpd file on google cloud storage: 
https://storage.googleapis.com/daydream-deveng.appspot.com/japan360/dash/japan_day06_eagle2_shot0005-2880px_40000kbps.mpd
With this URL, we can successfully play .mpd file with VR rendering.

However, when we tried to generate our mp4 to mpd with mp4box, the generated mpd file can be played by MediaPlayer (e.g. IINA), but not on Android system. 

We would like to ask the question here just make sure our generated .mpd is correct, here is the link:
http://18.185.102.182/ClassroomTest1/Scene_1_dash.mpd

With the same Exoplayer, we can play demo mpd files from google storage but not ours. However, both mpd files can be played via local MediaPlayer.

We were using :https://github.com/Cloudoki/mp4-to-mpegdash script to convert our mp4 to mpd manifest. file. 

thanks everyone

**Comment by jeanlf** [comment]
one big difference is that your failing MPD indicates usage of avc3 (inband parameter sets) which may not be supported on your android system. Try generating avc1 files instead

**Comment by dorcatty** [comment]
Thanks a lot i will change the parameters to have anothe try and come back
to you soon.
Thanks a lot!

**Comment by dorcatty** [comment]
hello jeanlf

another question regarding to avc1/avc3, we change to avc1 while ffmpeg
command or mp4box command ?
because we first used ffmpeg to generate several resolutions then mp4box to
generate mpd...
could you please figure me out how to use mp4box to set codecs to avc1 ?
using -v avc1 ?
thanks a lot!

**Comment by dorcatty** [comment]
Hello Jeanlf

i have test with mp4box *-bs-switching* *no,* the mpd file change to avc1
but still no video when i tested with android player.
do you think it is a problem of mp4 source file ?i need to change codec of
source mp4 file ?

Thanks a lot

**Comment by jeanlf** [comment]
Hard to say, check if regular playback of the non-fragmented file works. Closing for now as I don't think this is an issue with GPAC
