### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by nanshuii** [gpac/gpac#1233]
Undefined symbols for architecture arm64:
  "_ASN1_STRING_get0_data", referenced from:
      _gf_dm_connect in libgpac_static.a(downloader.o)
  "_OPENSSL_sk_num", referenced from:
      _sk_GENERAL_NAME_num in libgpac_static.a(downloader.o)
  "_OPENSSL_sk_value", referenced from:
      _sk_GENERAL_NAME_value in libgpac_static.a(downloader.o)
  "_TLS_client_method", referenced from:
      _ssl_init in libgpac_static.a(downloader.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jeanlf** [comment]
hmm strange could you post the stdout of your ./configure and the config.log?

**Comment by jeanlf** [comment]
reopen once you send us the platforms details and configure logs
