### ISSUE TITLE
How to combine specific mpeg-dash segments (ex int.mp4 + seg_1.m4s +seg_3.m4s) into one single mp4 file

### ISSUE THREAD

**Issue by iamgmujtaba** [gpac/gpac#1236]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I give enough information for contributors to reproduce my issue (meaningful title, GitHub labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hi There,
Currently I am trying to combine/concatenate specific MPEG-DASH video segments(m4s ex:int.mp4, seg_1.m4s, seg3,m4s,sge5.m4s) into one mp4 file. [example](https://i.stack.imgur.com/ve5Bu.jpg) .This question is also asked in [here](https://stackoverflow.com/questions/55701262/combine-specific-mpeg-dash-segments-ex-int-mp4-seg-1-m4s-seg-3-m4s-into-one)

I have used this command which works perfectly while combining all the m4s segments, but when I am trying to use specific segments then there is a problem.
cat init.mp4 $(ls -vx seg_*.m4s) > source.mp4

cat init.mp4 > source.mp4
cat segment-1.m4s >> source.mp4
cat segment-3.m4s >> source.mp4
cat segment-5.m4s >> source.mp4

I will be glad for any help or direction to solve this problem.

**Comment by rbouqueau** [comment]
> when I am trying to use specific segments then there is a problem.

What is the problem?

**Comment by iamgmujtaba** [comment]
Thank you for instant response.

In my use case, the duration of each segment is 10 second. When the first segment ends then frame freeze for 10 second until the video reached into the third segment. I have to wait 10 sec (depends on segment length).
Regards

**Comment by rbouqueau** [comment]
And what's the log of your player?

**Comment by iamgmujtaba** [comment]
I have played the video in the VLC player, this the message 

mp4 info: Fragment sequence discontinuity detected 1 != 0
mp4 info: Fragment sequence discontinuity detected 4 != 3

I have used this command for concatenation the segments.
cat browser_init.mp4 > source2.mp4
cat browser_1.m4s >> source2.mp4
cat browser_2.m4s >> source2.mp4
cat browser_4.m4s >> source2.mp4

**Comment by rbouqueau** [comment]
It is expected that fragments seq nums and media timestamps encounter discontinuity. I don't know how VLC handles that.

If you think this is not a GPAC issue, please close it. Otherwise let us know how we can help you.

**Comment by iamgmujtaba** [comment]
I have extracted the header information using the [Bento4](https://github.com/axiomatic-systems/Bento4) tool.  I have checked the video combined file with different media players all behave similarly.  I think the header needs to modify/update while combining different segment parts.

`File:
  major brand:      iso6
  minor version:    1
  compatible brand: iso6
  compatible brand: dash
  fast start:       yes

Movie:
  duration:   0 ms
  time scale: 1000
  fragments:  yes

Found 1 Tracks
Track 1:
  flags:        3 ENABLED IN-MOVIE
  id:           1
  type:         Video
  duration: 0 ms
  language: und
  media:
    sample count: 0
    timescale:    12288
    duration:     0 (media timescale units)
    duration:     0 (ms)
    bitrate (computed): 0.000 Kbps
    sample count with fragments: 0
    duration with fragments:     0
    duration with fragments:     0 (ms)
  display width:  1920.000000
  display height: 1080.000000
  Sample Description 0
    Coding:      avc1 (H.264)
    Width:       1920
    Height:      1080
    Depth:       24
    AVC Profile:          100 (High)
    AVC Profile Compat:   0
    AVC Level:            40
    AVC NALU Length Size: 4
    AVC SPS: [67640028acd940780227e5c044000003000400000300c03c60c658]
    AVC PPS: [68ebe3cb22c0]
    Codecs String: avc1.640028`

**Comment by iamgmujtaba** [comment]
More header information.

[ftyp] size=8+16
  major_brand = iso6
  minor_version = 1
  compatible_brand = iso6
  compatible_brand = dash
[free] size=8+0
[free] size=8+68
[moov] size=8+797
  [mvhd] size=12+96
    timescale = 1000
    duration = 0
    duration(ms) = 0
  [mvex] size=8+48
    [mehd] size=12+4
      duration = 161667
    [trex] size=12+20
      track id = 1
      default sample description index = 1
      default sample duration = 512
      default sample size = 0
      default sample flags = 10000
  [trak] size=8+527
    [tkhd] size=12+80, flags=3
      enabled = 1
      id = 1
      duration = 0
      width = 1920.000000
      height = 1080.000000
    [edts] size=8+28
      [elst] size=12+16
        entry count = 1
        entry/segment duration = 0
        entry/media time = 1024
        entry/media rate = 1
    [mdia] size=8+391
      [mdhd] size=12+20
        timescale = 12288
        duration = 0
        duration(ms) = 0
        language = und
      [hdlr] size=12+33
        handler_type = vide
        handler_name = VideoHandler
      [minf] size=8+306
        [vmhd] size=12+8, flags=1
          graphics_mode = 0
          op_color = 0000,0000,0000
        [dinf] size=8+28
          [dref] size=12+16
            [url ] size=12+0, flags=1
              location = [local to file]
        [stbl] size=8+242
          [stsd] size=12+162
            entry-count = 1
            [avc1] size=8+150
              data_reference_index = 1
              width = 1920
              height = 1080
              compressor = 
              [avcC] size=8+48
                Configuration Version = 1
                Profile = High
                Profile Compatibility = 0
                Level = 40
                NALU Length Size = 4
                Sequence Parameter = [67 64 00 28 ac d9 40 78 02 27 e5 c0 44 00 00 03 00 04 00 00 03 00 c0 3c 60 c6 58]
                Picture Parameter = [68 eb e3 cb 22 c0]
              [pasp] size=8+8
          [stts] size=12+4
            entry_count = 0
          [stsc] size=12+4
            entry_count = 0
          [stsz] size=12+8
            sample_size = 0
            sample_count = 0
          [stco] size=12+4
            entry_count = 0
  [udta] size=8+90
    [meta] size=12+78
      [hdlr] size=12+21
        handler_type = mdir
        handler_name = 
      [ilst] size=8+37
        [.too] size=8+29
          [data] size=8+21
            type = 1
            lang = 0
            value = Lavf58.20.100

**Comment by rbouqueau** [comment]
You either need to get a player that is aware of your time manipulations, or you need to package just-in-time. How could we help you?

**Comment by iamgmujtaba** [comment]
If it possible for you can you guide me, any open-source library to modify the header file(init.mp4) and DASH segments (m4s). Thank you for your help.

**Comment by rbouqueau** [comment]
Ok. When do you know the list of MP4s you need to concatenate?

**Comment by iamgmujtaba** [comment]
Thank you for your help. Sorry, but I could not fully understand your question. So I am explaining the entire method.

After generation DASH segments, then I am trying to combine random segments in sequential order. Such as int.mp4 + seg_1.m4s + seg_3.m4s + seg_5.m4s. I am a newbie in multimedia, and there is a lot of information in the header file. So, I am not aware of that which information needs to be modified with certain tool/library. I am reading about DASH form this [link](http://helixproducts.real.com/hmdp/documentation/helixserver/1512_LR/html/home_Left.html#CSHID=HelixHelp%2FHLS_Mount_Points.htm|StartTopic=Content%2FHelixHelp%2FHLS_Mount_Points.htm|SkinName=Server%20Skin)
Best Regards,

**Comment by jeanlf** [comment]
you will need to patch the tfdt box(es) of each non-first segment to match the duration of the previous segment, which migh be tricky.
Alternate way: cat init+segN into fileN, for all N you are interested in, then use MP4Box to concatenate the media streams: `MP4Box -cat file1 -cat fileN -new result.mp4`

**Comment by dajoker** [comment]
I know this issue is closed and all, and I'm not a gpac user at all, but just thinking about Linux and logic, if one command works:

 cat init.mp4 $(ls -vx seg_*.m4s) > source.mp4

and another set of commands which seemingly do the same thing do not work

cat init.mp4 > source.mp4
cat segment-1.m4s >> source.mp4
cat segment-3.m4s >> source.mp4
cat segment-5.m4s >> source.mp4

then logically the second set of commands does not do the same thing as the first command, so just figure out why as clearly the files work (see first command).  Knowing how 'ls' works, I would guess you have committed a human logic error and forgotten the number zero (0), as in segment-0.m4s, thus all of the other files were ten (10) seconds early, which would explain your errors in VLC..
