### ISSUE TITLE
mpeg-dash vp9 issue

### ISSUE THREAD

**Issue by irrz** [gpac/gpac#1237]
Hello there
I have encoded raw video using the ffmpeg tool, I used the libvpx-vp9 and the container used was .webm. then, i transcode it using the ffmpeg -i file.webm -c:v copy out.mp4. and then dashed it using the mp4box.
the issue is that I cannot play it back using the mp4client as it can be seen in the attached photo.
Hence, I can play it in the THEOplayer website perfectly.
![vp9 issue](https://user-images.githubusercontent.com/16091677/56267397-9fb9a880-60e6-11e9-8f56-5db8c01b014b.PNG)

**Comment by rbouqueau** [comment]
Hi,

Thanks for reporting.

Could you share:
 - some content (anonymous dropbox if useful https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95)
 - your MP4Box command-line to dash

so that we can reproduce?

**Comment by irrz** [comment]
Hi 
I uploaded the output files of the transformed .mp4 files and the dashed ones, alongside with the .webm files that were transcoded ones

The mp4box command line to dash:
Mp4box -dash 1000 250.mp4 750.mp4 1250.mp4 1750.mp4 -mpd-title 1ssegvp9 -out 1ssegvp9

All regards,

**Comment by rbouqueau** [comment]
I can reproduce.

I can't play 250.mp4 in MP4Client.

If I extract the vp9 with ffmpeg (ffmpeg -i 250.mp4 -c:v copy -f ivf 250.ivf), I can reimport it but it doesn't play (hint: the duration is a few ms - MediaInfo advertise the source as 16000fps!).

**Comment by rbouqueau** [comment]
With c60469eb7b90dbcd5a40d872017bccccfc30a187 and the commits mentioned above, your issue should be fixed. You need to wait for a few minutes to get the automated build from our buildbot.

Please close if it works for you.
