### ISSUE TITLE
Is there any existing feature to enable SPS and PPS to be added to avc Config

### ISSUE THREAD

**Issue by snehithala** [gpac/gpac#1238]
Hi, I am using a third party packager that creates DASH manifests from the mp4 stream that is created by MP4Box. I am using x264/x265 to produce a raw h264/hevc stream which gets packaged by MP4Box, these streams have repeated headers. Accordingly, I am using the xps_inband tag to create a avc3/hev1 MP4 stream which I can confirm have repeated headers in the media data. This means unlike avc1 and hvc1, the VPS/SPS/PPS are missing from the avcC and hvcC box. This is causing the third party packager to behave unpredictably. I would like to retain the SPS/VPS/PPS in the configuration boxes besides it being in the stream. Can you please point to the particular code where I can make changes after forking the project for my particular use case. 

This is a sample command I am using
mp4box -add raw_stream.hevc:xps_inband -new output.mp4

Thanks

**Comment by jeanlf** [comment]
That’s a good point, we will see what we can do

**Comment by jeanlf** [comment]
now in GPAC 0.9.0
