### ISSUE TITLE
saving streamed video

### ISSUE THREAD

**Issue by irrz** [gpac/gpac#1239]
Hi there 
I have produced various video contents and now I can play them perfectly with MP4Client.
I  am wondering if there is a way I can save all the streams in one mp4 file or any file types?
Hence, I read the issues in #2 and #11 but they are refferening to reading from the saved segments, whereas I want to save all segments in one playable file

Many thanks

**Comment by rbouqueau** [comment]
If you concatenate (physically e.g. with ```cat``` on unix or ```type``` on windows) the init segment and consecutive segments, you get a valid mp4 file.

**Comment by Murmur** [comment]
Very raw simple bat script to try out, this is what I have used few times.

```
@REM Merge audio segments "a1/i.mp4", "a1/1.m4s", "a1/2.m4s", ..
copy /B a1\i.mp4 a1.mp4
set IDX=0
call :MERGESEGS a1

@REM Merge audio segments "v1/i.mp4", "v1/1.m4s", "v1/2.m4s", ..
copy /B v1\i.mp4 v1.mp4
set IDX=0
call :MERGESEGS v1

@REM Merge audio and video streams to a mp4 file
ffmpeg -i v1.mp4 -i a1.mp4 -c:v copy -c:a copy -movflags faststart -y myvideo.mp4
goto :END

:MERGESEGS
set /A IDX=%idx%+1
rem set IDXT=000000%IDX%
rem set IDXT=%IDXT:~-6%
IF NOT EXIST "%1\%IDX%.m4s" GOTO :EOF
@echo %1\%IDX%
copy /B %1.mp4 + %1\%IDX%.m4s %1.mp4
GOTO :MERGESEGS

:END
pause
```

**Comment by jeanlf** [comment]
closed it a bit too early, this gave me an idea since then: in GPAC 0.9.0, using `split_as`, you can now tell the dash client to stream all qualities as if they where each in a dedicated adaptation set. This should works for DASH, HLS and Smooth, whether the file is local or remote.
