### ISSUE TITLE
mp4box generates a single frame mp4 file when several I frames are grouped

### ISSUE THREAD

**Issue by s0m30n3** [gpac/gpac#1240]
Hi,

For a test case of my own program, I generated an elementary stream containing SPS/PPS bytes then the same I frame data over and over. When I try to use mp4box to wrap the .264 file to a MP4 file, I get "AVC Import results: 1 samples (126 NALUs) - Slices: 124 I 0 P 0 B - 0 SEI - 124 IDR", resulting in a single frame file.
Compare files produced by "MP4Box -add sample.264 -new sample-mp4box.mp4" and "ffmpeg -i sample.264 sample-ffmpeg.mp4"

For reference, I used ffmpeg smptehdbars input to generate a .264 file and extract the test case data. See [sample.zip](https://github.com/gpac/gpac/files/3100528/sample.zip)

If you generate a sample file using "ffmpeg -f lavfi -i smptehdbars=300x200 -t 4 -r 25 -force_key_frames "expr:1" test.264", you'll see I-frames are interleaved with SPS/PPS data blocks. I'm not aware of such constraint but the H.264 format is so complex I may have missed some rules.

Anyway, thanks for you work, it's really helpful for us.

**Comment by rbouqueau** [comment]
I can reproduce. The issue is that since you repeat the same frame, the internal AVC/H264 counters never increase. A solution to this is to add a separating NALU such as an AUD (access unit delimiter). Is it possible in your case?

**Comment by s0m30n3** [comment]
Thanks for the explanation.

We don't have control over source data so two consecutive intra-frame is perfectly possible.
But since we manually build the elementary stream file we can forge and insert AUD if needed.

Anyway, I have to first ask my supervisor about it.
I'll be back once I had an official answer.

Thanks again for the quick answer, have a nice weekend!

**Comment by s0m30n3** [comment]
My supervisor was Ok for the change so I implemented it.
We checked and found AUD NAL units are not inserted in the final MP4 file.
It only impacts the generated .264 temp file.

Ideally, we shouldn't have to insert optional data to make your parser happy but it works so you can close the bug if you want.
Thanks for your help!

For reference, I added 0x00000169FF80 after each frame (I or not).
