### ISSUE TITLE
Ghostscript_tiger.svg can not be correctly rendered/rasterized

### ISSUE THREAD

**Issue by mhfan** [gpac/gpac#1242]
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). 

Please find the obvious issue in the following images' comparing:

![image](https://user-images.githubusercontent.com/1171428/56890967-854fd980-6aad-11e9-963d-03cb8ec61499.png)

![image](https://user-images.githubusercontent.com/1171428/56889848-3785a200-6aaa-11e9-9128-754e242c4ce6.png)

The first image is captured from GPAC output with ill region marked in red.

Platform: macOS, Macbook Pro
Built from current git master branch (commit id: fe8de95b)
Compiler: Apple LLVM version 10.0.0 (clang-1000.10.44.4) Target: x86_64-apple-darwin17.7.0
Nightly built gpac-0.7.2-DEV-rev1089-gfe8de95b-master.pkg

Download the original SVG file from: [Ghostscript Tiger](https://upload.wikimedia.org/wikipedia/commons/f/fd/Ghostscript_Tiger.svg)

**Comment by mhfan** [comment]
Note: There is a third ill rendering region up on the left eye in gray.

**Comment by mhfan** [comment]
Can anyone respond to this issue?

**Comment by aureliendavid** [comment]
I can confirm that I see the same artifacts on windows with the latest version of gpac

I'm not sure how to debug this thought

**Comment by aureliendavid** [comment]
ok I think I found the bug and it should be fixed by the commit above

for reference: 

the bug comes from the interpretation of the `s` command in svg paths

the specs say: (https://www.w3.org/TR/SVG2/paths.html#ReflectedControlPoints)

> Draws a cubic Bézier curve from the current point to (x,y). The first control point is assumed to be the reflection of the second control point on the previous command relative to the current point. **(If there is no previous command or if the previous command was not an C, c, S or s, assume the first control point is coincident with the current point.)**

and from https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths 

> if it follows another `S` command or a `C` command, the first control point is assumed to be a reflection of the one used previously. If the `S` command doesn't follow another `S` or `C` command, then the current position of the cursor is used as the first control point. **In this case the result is the same as what the `Q` command would have produced with the same parameters**

In other words: `S` is a shorthand for `C` iif it's following another `S` or `C`, otherwise it is shorthand for `Q`

this "otherwise" wasn't implemented in gpac

**Comment by mhfan** [comment]
Thanks @aureliendavid , it was perfect fixed!

And I forgot to mention one more issue, that when you look at the output image from GPAC (the above one) carefully, you can see all the edges are far to be smooth as the output from a modern browser (the below one), the former seems not been processed by anti-aliasing.

Why is that? Can it be optimized?

**Comment by aureliendavid** [comment]
well this is a bit out of my depth to be honest 

I don't see big differences in rendering on my machine between firefox and mp4client

I know there's a setting about antialiasing mentioned on this page https://github.com/gpac/gpac/wiki/Player-Config but I don't know if it changes svg rendering
