### ISSUE TITLE
Bandwidth explanation with MP4Box

### ISSUE THREAD

**Issue by dorcatty** [gpac/gpac#1244]
Dear all,

Thanks a lot for the discussion here to help me moving forward in my projects.
I am wondering in how the Bandwidth works in MP4Box? here are the tests I made an my Android phone (Samsung S9+):

with ffmpeg and MP4Box, I generated 3 different resolutions video clips (960px*960px, 1440px*1440px, 2160px*2160px) and MP4Box them into mpd files. here is the command MP4Box -dash 2000 -frag 2000 -rap -frag-rap -profile live filename
However, on my Android phone I can only play the medium resolution (1440px) video even the higher bandwidth is available.  

I did another test with 2160px and 2560px resolutions in a mpd file, then 2160px streaming video can be fluently played with the same player on Android. 

So i was wondering how the bandwidth is working regarding to resolution?
 
Or it might be a player related issue ?

thanks a lot for your helps

**Comment by rbouqueau** [comment]
The bandwidth choice with MPEG DASH is made at the client side. Which player are you using?

**Comment by jeanlf** [comment]
I believe this is a player issue. Clarify and reopen if needed

**Comment by dorcatty** [comment]
I found the reason recently. It was a problem of https and http.
