### ISSUE TITLE
When Dashing a file set that inculdes a subtitle process hangs

### ISSUE THREAD

**Issue by dkhill01** [gpac/gpac#1245]
Hi
We've been trying to dash a file set containing 1 video, several audios & a subtitle file. Without the subtitle file everything works fine. Adding the subtitle makes everything hang. There is no error of progress report. The video & audios are generated using ffmpeg, the subtitles are coming out of ccextractor. We've tried various formats, all seem valid, but the result is always the same, namely mp4box hangs.

The command line I am using is – 
mp4box -dash 5000 -frag 2000 -rap -profile dashavc264:onDemand -mpd-title Example-Title -out output101.mpd subtitle1.mp4:role=subtitle

Any help is much appreciated 

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by dkhill01** [comment]
I have been doing some more investigation but still haven’t got to the bottom of this. 

I have found that the subtitle wrap completes if the subs do not span over a second, example - 

subtitle wrap works - 
00:00.019 --> 00:00.020
[meowing]

00:00.020 --> 00:00.020
Give me that!

00:00.021 --> 00:00.021
All MAD-hands on deck!

Subtitle Wrap fails - 
00:19.397 --> 00:20.064
[meowing]

00:20.076 --> 00:20.510
Give me that!

00:20.521 --> 00:20.977
All MAD-hands on deck!

Again, any help\advice is much appreciated

**Comment by rbouqueau** [comment]
Hi, thanks for reporting. Would you be kind enough to provide us with a sample so that we can reproduce?

PS: we have an anonymous dropbox in case it can help: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95.

**Comment by jeanlf** [comment]
This should now be fixed in 0.9.0
