### ISSUE TITLE
MP4Box loses the 6th chapters added

### ISSUE THREAD

**Issue by adrienbricchi** [gpac/gpac#1246]
Hi, and thanks for your project.  

## How to reproduce

The AAC is a 40mo french podcast, here we mux with and without chapters :
```bash
$ wget https://drive.google.com/uc?export=download\&id=1oLQ75ddUgjUt2uOlKQKZUl9eDpmBZ7GO -O s01e01.aac
$ wget https://drive.google.com/uc?export=download\&id=1xgRG_cy13qOYMbA0t8mHPruGm6vPANJZ -O s01e01.ttxt
$ MP4Box -add s01e01.aac#audio s01e01_nochap.m4a
$ MP4Box -add s01e01.aac#audio -add s01e01.ttxt:chap s01e01_chap.m4a
```

## Issue

I've been, truggeling with a simple chapter file, in a straightforward M4A output.

The given AAC is a `58'15` length file.  
And I want to add this chapter file :
```xml
<!-- (...) -->
<TextSample sampleTime="00:00:00.000">Intro</TextSample>
<TextSample sampleTime="00:02:35.000">Impose ton style - Le Trou</TextSample>
<TextSample sampleTime="00:14:20.000">Impose ton style - L'Évadé d'Alcatraz</TextSample>
<TextSample sampleTime="00:25:17.000">Impose ton style - Les Poings contre les murs</TextSample>
<TextSample sampleTime="00:41:03.000">Quartier libre</TextSample>
<TextSample sampleTime="00:48:44.000">Le Jeu</TextSample>
<TextSample sampleTime="00:55:43.000">Outro</TextSample>
<!-- (...) -->
```

The `nochap` file is muxed nicely into a `58'15` length M4A.  
The `chap` one outputs a weird `1'02'42` M4A file, with a buggy end.  
(obviously : no audio in the last minutes).  

I tried with many players (Quicktime, Podcast Addict, VLC), same result.  
And... the last chapter seems skipped in the output file.

Weird results in my tests :
- If I remove any chapter in the file, everything's fine. The bug seems to appear if there is a 6th one.
- Removing accentuated chars doesn't change anything.
- If I change the timestamp of the last chapter, I have another total-length, without consistency.

## Environment

System : `MacOS 10.14.4 (18E226)`  
MP4Box : `0.7.2-DEV-rev1092-g9991b44c-master` (Downloaded from the given nightly builds)

I already seen a few "chapters" bug reports, but on other specific cases :
- Merging tracks, not this case.
- Problem with milliseconds, not this case either : all my milliseconds are 000.

I'll take any hint.
Thanks, and cheers from France.

**Comment by aureliendavid** [comment]
Hi, 

Thanks for the thorough report. Here's what I think is happening: 

In the `s01e01_chap.m4a` created, the audio track is (rightly) `58:15`, but the text track is `1:02:42`. That's why you're seeing a `1:02:42` duration in the player, but it skips when the audio track is finished (at least vlc does that). 

(you can see this with `MP4Box -info s01e01_chap.m4a`)

Now the reason why the text track is `1:02:42` comes from this little nugget that I found buried in the docs: 

> _Note_: By default, when importing ttxt with MP4Box, the duration of the last text sample is the same as the duration of the previous sample. To specify the duration of the last sample, add an extra text sample at the end with no text content.

(https://github.com/gpac/gpac/wiki/TTXT-Format-Documentation)

which would make the duration of the 7th chapter the same as the 6th, with is `6:59`, and `55:43+6:59=1:02.42`!

The solution seem to be to add an extra empty chapter at the end:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<TextStream version="1.1">
   <TextStreamHeader width="480" height="368" layer="0" translation_x="0" translation_y="0">
      <TextSampleDescription horizontalJustification="center" verticalJustification="bottom" backColor="0 0 0 0" verticalText="no" fillTextRegion="no" continuousKaraoke="no" scroll="None">
         <FontTable>
            <FontTableEntry fontName="Arial" fontID="1" />
         </FontTable>
         <TextBox top="0" left="0" bottom="368" right="480" />
         <Style styles="Normal" fontID="1" fontSize="32" color="ff ff ff ff" />
      </TextSampleDescription>
   </TextStreamHeader>
   <TextSample sampleTime="00:00:00.000">Intro</TextSample>
   <TextSample sampleTime="00:02:35.000">Impose ton style - Le Trou</TextSample>
   <TextSample sampleTime="00:14:20.000">Impose ton style - L'Évadé d'Alcatraz</TextSample>
   <TextSample sampleTime="00:25:17.000">Impose ton style - Les Poings contre les murs</TextSample>
   <TextSample sampleTime="00:41:03.000">Quartier libre</TextSample>
   <TextSample sampleTime="00:48:44.000">Le Jeu</TextSample>
   <TextSample sampleTime="00:55:43.000">Outro</TextSample>
   <TextSample sampleTime="00:58:15.262"></TextSample>
</TextStream>
```

If you mux that ttxt file with your audio, it looks ok.

**Comment by adrienbricchi** [comment]
Nice !
Everything works as expected, like this.
Thank you.
