### ISSUE TITLE
MP4box doesn't report proper codec information with HEVC/HDR10

### ISSUE THREAD

**Issue by nicoweilelemental** [gpac/gpac#1247]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x ] I looked for a similar issue and couldn't find any.
- [x ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Hi,
I uploaded an init segment for HEVC/HDR10 on MediaFire (name: 175_video_cmaf_2_init.mp4) which is reported as using hvc1.1.6.L21 as video codec by MP4box, while it's actually using hvc1.2.4.L150.B0 as shown in the attached screenshot from MP4box.js.
If someone can check what's going on there, that would be great. Thanks !
![mp4box_output](https://user-images.githubusercontent.com/38870794/57721679-a120b700-7639-11e9-849e-9ce4b24f3ef6.png)

**Comment by nicoweilelemental** [comment]
MP4box executable actually outputs the same value than MP4box.js 

$ mp4box.exe -info 175_video_cmaf_2_init.mp4
* Movie Info *
        Timescale 24000 - 1 track
        Computed Duration 00:00:00.000 - Indicated Duration 00:00:00.000
        Fragmented File: yes - duration 00:00:00.000
0 fragments - 0 SegmentIndexes
        File suitable for progressive download (moov before mdat)
        File Brand isom - version 1
                Compatible brands: isom avc1 dash
        Created: GMT Tue May 14 18:00:01 2019
        Modified: GMT Tue May 14 18:00:01 2019

File has root IOD (233 bytes)
Scene PL 0xff - Graphics PL 0xff - OD PL 0xff
Visual PL: Not part of MPEG-4 Visual profiles (0xfe)
Audio PL: No audio capability required (0xff)

Track # 1 Info - TrackID 1 - TimeScale 24000
Media Duration 00:00:00.000 - Indicated Duration 00:00:00.000
Track is present in Root OD
Media Info: Language "Undetermined (und)" - Type "vide:hvc1" - 0 samples
Fragmented track: 0 samples - Media Duration 00:00:00.000
Visual Track layout: x=0 y=0 width=0 height=540
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x23
HEVC Video - Visual Size 960 x 540
        HEVC Info: Profile Main @ Level 0.7 - Chroma Format YUV 4:2:0

        NAL Unit length bits: 32 - general profile compatibility 0x60000000

        Parameter Sets: 1 VPS 1 SPS 1 PPS
        SPS resolution 960x540 - Pixel Aspect Ratio 1:1 - Indicated track size 0 x 540
        Bit Depth luma 8 - Chroma 8 - 0 temporal layers
        VPS#1 hash: A592F7FAA9DB1FF8F5A3DBA796B5083235199B08
        SPS#1 hash: 8037D5A159A26BC092B9001266D3883EF41E7AAC
        PPS#1 hash: 26209F81D80647ED4F9BFB0DC33FCDBC48351612

Self-synchronized
        **RFC6381 Codec Parameters: hvc1.1.6.L21.0**
        All samples are sync

**Comment by rbouqueau** [comment]
Hi Nico!

The HEVC config record contains the values reported by MP4Box/mp4box.js. However I confirm that the array of NALUs (type 33,33,34,39) that contradicts the higher level values.

What is the source of this stream?

I'll spend more time trying to see what's the correct value in this situation.

**Comment by rbouqueau** [comment]
I confirm the file is broken.

**Comment by nicoweilelemental** [comment]
Hi Romain,
Thanks for looking into this, I uploaded the file again on mediafire, I will send it over email if the second upload is broken too. This is an init segment produced by MediaPackage, based on an Elemental Live encoding.

**Comment by rbouqueau** [comment]
Ah ah sorry for the confusion. The file is complete but not compliant.

When the higher-level config record is in contradiction with the lower level NALUs, the highest level (i.e. config record) is right. So MP4Box is right reporting in its codec information.

You need your MP4 to report the right codec info in the codec record.

**Comment by nicoweilelemental** [comment]
In which box are you finding the config record?

**Comment by rbouqueau** [comment]
'hvcC'

**Comment by jeanlf** [comment]
Closing as this seems a pb with the source file
