### ISSUE TITLE
how to increase speed for encrypting in mp4box by in increasing buffer ssize

### ISSUE THREAD

**Issue by azhar5678** [gpac/gpac#1248]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by azhar5678** [comment]
i need to increase speed in mp4box crypt 
to send to pendrive
file size 1gb current time 3 minutes 

i need to reduce to 1 minute

**Comment by rbouqueau** [comment]
I can reproduce these figures. It can be drastically faster by running I/Os on a RAM drive. Also note that the version following our next GPAC release should improve these numbers.

**Comment by azhar5678** [comment]
We don't have a ram drive, is other option to increase speed.

**Comment by rbouqueau** [comment]
Can you wait for a few months to try the next dev version out?

**Comment by azhar5678** [comment]
OK.

**Comment by Murmur** [comment]
@azhar5678  Do you use `-mem-frags` argument so that temp files are not written to disk? Maybe you save few seconds but I guess most progress need a next dev release.

```
MP4Box -dash 264600 -frag 264600 -dash-scale 44100 -bound -mem-frags -rap -profile dashavc264:live \ 
  -min-buffer 6000 -bs-switching no -sample-groups-traf -single-traf -subsegs-per-sidx -1 \
  -segment-name "$RepresentationID$/$Number$$Init=i$" \
  -out manifest.mpd \
  temp-v1.mp4#trackID=1:id=v1:period=p0 \
  temp-a1.mp4#trackID=1:id=a1:period=p0
```

**Comment by jeanlf** [comment]
Can you try 0.9.0 Dev and do
`gpac -i source cecrypt:cfile=crypt.drm @ null:ext=mp4`
And measure the time?
This will do the whole crypto process without writing any blocks to drive.
Also if you want to speed up the process, use fragmentation or flat store modes
`gpac -i source cecrypt:cfile=crypt.drm @ null:ext=mp4:store=frag`
`gpac -i source cecrypt:cfile=crypt.drm @ null:ext=mp4:store=flat`

**Comment by jeanlf** [comment]
no news, closing
