### ISSUE TITLE
Generating an MPD file for HEVC tile based live streaming 

### ISSUE THREAD

**Issue by R04921040** [gpac/gpac#1251]
Hello,
I want to build a live streaming system for 4K VR video with DASH SRD.
I can use the nginx-rtmp server to build a live streaming server with DASH, and I know MP4Box is able to generate tile-based MPD file for a static video.
Does MP4Box or any other software support to generate an MPD file for  HEVC tile-based live streaming?
thanks

**Comment by jeanlf** [comment]
This depends on how your live is fed into the dasher:
- as a continuous stream : you will need to use gpac app from 0.9.0DEV
- as a serie of small files: usual MP4Box operations should work
 
Clarify and reopen if needed

**Comment by a23232390** [comment]
@R04921040  hello
are you use nginx-rtmp make mp4 and then mp4w ith  bash script to make mpeg dash hevc tiles
Is this process
