### ISSUE TITLE
How to live stream video that comes in multiple mp4 files

### ISSUE THREAD

**Issue by Maciejszuchta** [gpac/gpac#1252]
Hello
First of all, thank you for great tool :)
I'm wondering if such a scenario is possible.
I'm recording 5 seconds long videos on Android device as mp4 files. After each video is recorded it is sent via web sockets to my server (byte array). On that server, I would like to actively wait for those chunks of the video. When they arrive on my server I have to create dash content from them to have m4s files and allow my web client to consume those files. What is puzzling me the most is if GPAC is able to notice that those mp4 files are in fact the same video.

Any bits of advice/suggestions will be appreciated.
Regards

**Comment by jeanlf** [comment]
use `MP4Box -cat` to recreate your MP4 file, and then dash the result, possibly using -dash-ctx if this is a live session.

**Comment by Maciejszuchta** [comment]
Could you explain to me how -dash-ctx works here? I don't understand it from the documentation. Also is there a possibility to provide an example on how to use -dash-ctx option in my case?

**Comment by jeanlf** [comment]
We need a wiki entry on this, yes. `-dash-ctx` allows you to store and resume a dash session (usefull for live). Assuming you are sure your segments are always around 5 seconds, you can call at each new segment
`MP4Box -dash 10000 -dash-ctx context.txt -profile live -mpd-refresh 5 -dynamic [other opts] concatenated_file.mp4 -out live.mpd`

The first call will create the dash context, the subsequent calls will reuse that context to produce the dash session. Note that you have to concatenate your files before dashing to reconstruct the timeline, each MP4 file starting at 0. The `10000`value for dash is chose such that it is larger than each of the segment. If you wand smaller segments (e.g. 1s), you can still use `-dash 1000` , the dasher will process all samples that were not processed in the previous call.

**Comment by Maciejszuchta** [comment]
So as I assume every time the new mp4 file comes I have to first append my file with 
`MP4Box -add output.mp4 -cat newmp4file.mp4 output.mp4`
and them dash it again with your command like:
`MP4Box -dash 10000 -dash-ctx context.txt -profile live -mpd-refresh 5 -dynamic  output.mp4 -out live.mpd`

**Comment by Maciejszuchta** [comment]
Also, I have got another question isn't it overkill for CPU if on every new 5-second segment I concatenate it with already existing concatenated_file.mp4 which over time grows to very large size. Concatenation can take a very long time if concatenated_file.mp4 has e.g 200 MB.

**Comment by jeanlf** [comment]
You are correct but currently in order to recompute the timeline from different non-fragmented MP4 only concatenation can be used. With 0.9.0 you can try using the `flist` filter but that will only work if the filter chain is permanently running (ie no dash context). I will look at a way to provide the same functionality with the dash context, I'll let you know.

**Comment by jeanlf** [comment]
My bad, I forgot I actually already patched this in the dasher in 0.9.0, you don't need to cat the input but you will have to keep the same source file name otherwise this will trigger a period switch.

**Comment by Maciejszuchta** [comment]
So every new incoming file should have the same name, right ?
So when new file arrives I have to just call 
`MP4Box -dash 10000 -dash-ctx context.txt -profile live -mpd-refresh 5 -dynamic fileWithTheSameName.mp4 -out live.mpd`

**Comment by Maciejszuchta** [comment]
> My bad, I forgot I actually already patched this in the dasher in 0.9.0, you don't need to cat the input but you will have to keep the same source file name otherwise this will trigger a period switch.

How do I get GPAC v 0.9.0 on Windows ?

**Comment by rbouqueau** [comment]
https://gpac.wp.imt.fr/downloads/gpac-filters-branch/

**Comment by Maciejszuchta** [comment]
@jeanlf, I used your solution using gpac 0.9.0. My pipeline looks like this.
1. New mp4 file arrives at the server.
2. I save it with name 9887a8334f4b49314e.mp4
3. I run command `mp4box -dash 10000 -dash-ctx context.txt -profile live -mpd-refresh 6 -dynamic 9887a8334f4b49314e.mp4 -out live.mpd`
4. The output of this command are files:
- `9887a8334f4b49314e_dashinit.mp4`
- `9887a8334f4b49314e_dash58.mp4` <- I assume that these are next parts of my video that my webclient should request for
- `live-Period_GENID_DEF.mpd`
- `live.mpd`
- `context.txt`
However my WebClient (rx-player), using generated .live.mpd file requests for files like 1563889049_dash496.m4s

**Comment by jeanlf** [comment]
Yes, apart from the `live-Period_GENID_DEF.mpd`: this should no longer exist in 0.9.0, make sure you reset your output dir.

The `context.txt` is actually a valid MPD file representing the current session, with some XML extensions to store the dasher state.

One quick way to check your session is to do one final call using `-last-dynamic` (make sure te get the latest revision/installer, I patched a bug on this a few hours ago):
`mp4box -dash 10000 -dash-ctx context.txt -profile live -mpd-refresh 6 -last-dynamic 9887a8334f4b49314e.mp4 -out live.mpd`

this will turn the live.mpd into a static MPD that you can then give to your favorite player - this will help you make sure the content is valid and playable independently from dynamic MPD offering

**Comment by Maciejszuchta** [comment]
I took the command `mp4box -dash 10000 -dash-ctx context.txt -profile live -mpd-refresh 6 -last-dynamic 9887a8334f4b49314e.mp4 -out live.mpd`

This gives me such mpd file 

```
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.7.0-rev0-gbd5c9af-master  at 2019-07-24T10:24:35.279Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="dynamic" publishTime="2019-07-24T10:24:35Z" availabilityStartTime="2019-07-24T10:20:02.803Z" timeShiftBufferDepth="PT0H0M0.000S" minimumUpdatePeriod="PT0H0M6.000S" maxSegmentDuration="PT0H0M30.000S" profiles="urn:mpeg:dash:profile:isoff-live:2011">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>live.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period id="GENID_DEF" start="PT0H0M0.000S">
  <AdaptationSet segmentAlignment="true" maxWidth="1440" maxHeight="2960" maxFrameRate="90000/2902" par="94371840:193986560" lang="und">
   <Representation id="1" mimeType="video/mp4" codecs="avc3.428034" width="1440" height="2960" frameRate="90000/1573" sar="65536:65536" startWithSAP="1" bandwidth="3839075">
    <SegmentTemplate timescale="90000" media="9887a8334f4b49314e_dash$Number$.m4s" startNumber="1" duration="2700000" initialization="9887a8334f4b49314e_dashinit.mp4"/>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```

as I assume `mp4box -dash 10000 ...` will always store as many m4s files on disk as can fit in 10-second segment. In my case, it is 13 .m4s files. So if I start the stream it progressively creates 13 files 
`9887a8334f4b49314e_dash1.m4s` --- `9887a8334f4b49314e_dash13.m4s`
Then for next incoming files shifts the files so its:
`9887a8334f4b49314e_dash2.m4s` --- `9887a8334f4b49314e_dash14.m4s` and so on.

However my player using this mpd file is requesting weird files. e.g I have file 251-264 the client requests file 40.

**Comment by Maciejszuchta** [comment]
![image](https://user-images.githubusercontent.com/12434636/61790657-1b2ea280-ae18-11e9-9272-63961057e507.png)
I'm struggling with this issue. Can I avoid gpac to remove past m4s so my player can always grab file that exists ?

**Comment by jeanlf** [comment]
> Then for next incoming files shifts the files so its:
9887a8334f4b49314e_dash2.m4s --- 9887a8334f4b49314e_dash14.m4s and so on.

no, the next run should produce xx_dash14.m4s --- xx_dash26.m4s. If not the case something is wrong.
Looking at your MPD:
- the segments are 30s long, not 10s. 
- you are still using version 0.7.0, not 0.9.0

To avoid deleting files when running the dasher, use `-time-shift -1`

**Comment by Maciejszuchta** [comment]
```<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.9.0-DEV-rev2609-g759c91dc-filters at 2019-07-25T06:16:59.484Z -->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="dynamic" availabilityStartTime="2019-07-25T06:14:58.263Z" publishTime="2019-07-25T06:16:59.484Z" minimumUpdatePeriod="PT0H0M6.000S" maxSegmentDuration="PT0H0M2.991S" profiles="urn:mpeg:dash:profile:isoff-live:2011">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>live.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period id="DID1" start="PT0H0M0.000S">
  <AdaptationSet segmentAlignment="true" maxWidth="1440" maxHeight="2960" maxFrameRate="31" par="1440:2960" lang="und" startWithSAP="1">
   <SegmentTemplate media="9887a8334f4b49314e_dash$Number$.m4s" initialization="9887a8334f4b49314e_dashinit.mp4" timescale="90000" startNumber="1" duration="900000"/>
   <Representation id="1" mimeType="video/mp4" codecs="avc1.428034" width="1440" height="2960" frameRate="90000/2870" sar="1:1" bandwidth="3274732">
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```


@jeanlf Now files are progressively creating, that's great. However, for this .mpd file client doesn't request for .m4s files.

![image](https://user-images.githubusercontent.com/12434636/61850545-defd4f80-aeb4-11e9-992b-8cf89ee49fd3.png)

**Comment by jeanlf** [comment]
which player are you using ?

**Comment by Maciejszuchta** [comment]
I was using rx-player  https://github.com/canalplus/rx-player.
I also tried dash.js. The player was able to display the content but my video was far behind my live content https://github.com/Dash-Industry-Forum/dash.js/issues/3036#issuecomment-516019372

**Comment by jeanlf** [comment]
From what you described on dash.js forum, it looks like the dasher is producing content faster than expected (in your case every 10 seconds). Could you check this is the case (the logs should tell you there is nothing to do for the next X seconds)
