### ISSUE TITLE
[MP4Box] How to decrypt CBCS content?

### ISSUE THREAD

**Issue by dprestegard** [gpac/gpac#1254]
Hello!

I'm interested in using MP4Box to decrypt CBCS encrypted fMP4 files. According to the built-in help, the tool only supports CTR:

```$ mp4box -h crypt
ISMA Encryption/Decryption Options
 -crypt drm_file      crypts a specific track using ISMA AES CTR 128
 -decrypt [drm_file]  decrypts a specific track using ISMA AES CTR 128
                       * Note: drm_file can be omitted if keys are in file
 -set-kms kms_uri     changes KMS location for all tracks or a given one.
                       * to address a track, use 'tkID=kms_uri'
```

However, I see some issues in git related to CBCS, so I think it DOES support it (maybe some documentation needs to be updated - which I'd be happy to submit a patch for once I know how to do this ;))

Assuming I have an fMP4 file encrypted with CBCS per FairPlay Streaming, and I have the KID, IV, and CEK, how do I tell MP4Box to decrypt it into clear fMP4?

- [x ] I looked for a similar issue and couldn't find any.
- [ x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
CBCS support should work properly as of 0.8.0. To decrupt your file, you need to rebuild an XML file indicating the IV, KID and key value - check the [test suite scripts](https://github.com/gpac/gpac/tree/master/tests/media/encryption)

**Comment by dprestegard** [comment]
Confirmed, I neglected to update this ticket :)

An XML like this did the trick:

`<?xml version="1.0" encoding="UTF-8" ?>
<GPACDRM type="cbcs">

<CrypTrack trackID="1" IsEncrypted="1" IV_size="16" first_IV="0x$$$IV_IN_HEX$$$" saiSavedBox="senc">
<key KID="0x$$$KID_IN_HEX$$$" value="0x$$$CEK_IN_HEX$$$"/>
</CrypTrack>

</GPACDRM>`

**Comment by tiffsequence** [comment]
> CBCS support should work properly as of 0.8.0. To decrupt your file, you need to rebuild an XML file indicating the IV, KID and key value - check the [test suite scripts](https://github.com/gpac/gpac/tree/master/tests/media/encryption)

For posterity, above link is 404'ing, currently lives [here](https://github.com/gpac/testsuite/tree/3444dabe40dba17d3883d3750b248ec953c34d5d/media/encryption)
