### ISSUE TITLE
fast switching while DASH streaming

### ISSUE THREAD

**Issue by irrz** [gpac/gpac#1255]
Hello there
I have dashed my produced representations with different segment sizes using the MP4Box.
I noticed that when I play the segment size=1sec (using the MP4Client), the quality switching occurs after almost 8-10 seconds! and this degrades the overall of the QoE.

My question is that:
Is there anyway I can push the configurations to increase the quality of representations immediately? 
Hence, the available bandwidth is higher than the highest quality's bitrate with no less than 5folds of the bitrate.

One of the expected answers I may get is that to change the StartRepresntation to be =MaxQuality. If I do so, then I gain the highest quality but when I enforce very low bandwidth, I get a stalling for the video and the video playback gets interrupted!!

I look forward to hearing back from you guys 
Regards,
Irrz

**Comment by jeanlf** [comment]
You can try also playing with `SwitchProbeCount` , `AgressiveSwitching` and `NetworkAdaptation` options as well. I’ll have a look to see if there is a bug on our side. Reopen if needed
