### ISSUE TITLE
equal_picture_interval AV1 field is being misparsed

### ISSUE THREAD

**Issue by jamrial** [gpac/gpac#1256]
https://github.com/gpac/gpac/blob/a1225c5748c6b11548628395f97e9e15250e39ad/src/media_tools/av_parsers.c#L1655

It's reading three bits, when the spec defines it as one: https://aomediacodec.github.io/av1-spec/#timing-info-syntax. Changing it fixes muxing AV1 samples with timing information.

**Comment by rbouqueau** [comment]
Fixed, thank you!
