### ISSUE TITLE
"Box has extra bytes" after processing mp4 file twice

### ISSUE THREAD

**Issue by mkauf** [gpac/gpac#1257]
I have created an mp4 file (with ffmpeg) that contains chapters in iTunes format: https://test.michael-kaufmann.ch/test.mp4

mp4box does not know the box type "text", but apart from that, everything seems to work:

```
mp4box.exe -new -add test.mp4 test2.mp4
[iso file] Unknown box type text in parent gmhd
[iso file] Unknown box type text in parent gmhd
IsoMedia import test.mp4 - track ID 1 - Video (size 640 x 480)
[iso file] Unknown box type text in parent gmhd
IsoMedia import test.mp4 - track ID 2 - Audio (SR 48000 - 2 channels)
[iso file] Unknown box type text in parent gmhd
IsoMedia import test.mp4 - track ID 3 - media type "text:text"
Saving test2.mp4: 0.500 secs Interleaving
```

When processing the file that has just been created for a second time, a new warning about extra bytes appears:

```
mp4box.exe -new -add test2.mp4 test3.mp4
[iso file] Unknown box type text in parent gmhd
[iso file] Box "text" (start 5360) has 20 extra bytes
[iso file] Unknown box type text in parent gmhd
[iso file] Box "text" (start 5360) has 20 extra bytes
IsoMedia import test2.mp4 - track ID 1 - Video (size 640 x 480)
[iso file] Unknown box type text in parent gmhd
[iso file] Box "text" (start 5360) has 20 extra bytes
IsoMedia import test2.mp4 - track ID 2 - Audio (SR 48000 - 2 channels)
[iso file] Unknown box type text in parent gmhd
[iso file] Box "text" (start 5360) has 20 extra bytes
IsoMedia import test2.mp4 - track ID 3 - media type "text:text"
Saving test3.mp4: 0.500 secs Interleaving
```

So probably there is a bug and mp4box adds some extra bytes when writing unknown boxes.

I have used this nightly build for testing: https://download.tsi.telecom-paristech.fr/gpac/new_builds/win32/gpac-0.7.2-DEV-rev1172-gc23d54ed-master-win32.exe

**Comment by jeanlf** [comment]
Indeed, we we not parsing child boxes for text although adding them (files were compliant, but import incomplete). Now fixed

**Comment by mkauf** [comment]
Thank you very much for the bugfix!
