### ISSUE TITLE
GPAC 0.9.0 on Windows - ANSI escape sequences

### ISSUE THREAD

**Issue by BucherTomas** [gpac/gpac#1258]
Testing the "filters" branch with 0.9.0-DEV-rev2428-gfb72027b-filters build on Windows 10 revealed possible issue with the way ANSI escape sequences are processed.

The sequences are handled as plain text and corrupt the output.

 I tried older and newer Windows 10 revisions between 1607 to 1809 in order to eliminate the possibility of system error as support for this was missing at Windows 10 launch and was added in 1511, but result is always the same for both cmd and powershell.

![aes](https://user-images.githubusercontent.com/18445121/60432743-4cde9000-9c03-11e9-93bc-4ba41a6e149c.png)

**Comment by jeanlf** [comment]
should now be fixed, reopen if needed
