### ISSUE TITLE
GPAC 0.9.0 on Windows - dasher unable to work with paths incl. drive letters

### ISSUE THREAD

**Issue by BucherTomas** [gpac/gpac#1259]
The simplest command to reproduce this `gpac -i test.mp4 -o c:\test\test.mpd` results in 

`No filter chain found for PID PID1 in filter dasher to any loaded filters - NOT CONNECTED`

The process now hangs, stopping with CTRL+C shows possilbe reason as badly interpreting `:` after drive letter
`Unknown argument ":\test\test.mpd" set but not used by any filter - no matching argument found`

Relative paths without drive letter work as expected. Tested with 0.9.0-DEV-rev2428-gfb72027b-filters.

**Comment by Murmur** [comment]
Does it work with `-o c:/test/test.mpd` or `-o /c:/test/test.mpd`  filename format as a quick fix?

**Comment by BucherTomas** [comment]
@Murmur  thanks, but no, it doesn't. I already tried the first method before I wrote the ticket, the second one doesn't help either.

If I run command line based on original mp4box syntax `mp4box {params} -out c:\test\test.mpd` , it fails as well and mp4box prints `Wrong argument value splitx:#Representation=1:\test\file.mpd for unsigned int arg smode enum split|splitx|single - using 0`

**Comment by aureliendavid** [comment]
argh, this %*$! problem again.. 

the path handling needs to be more centralized and refactored ; it's done properly in some places but not others

it's done correctly here: https://github.com/gpac/gpac/blob/filters/src/filter_core/filter_session.c#L1983

but not there: https://github.com/gpac/gpac/blob/filters/src/filter_core/filter_pid.c#L6018

or there: https://github.com/gpac/gpac/blob/filters/src/filter_core/filter.c#L56

it's done yet another way here: https://github.com/gpac/gpac/blob/filters/src/filter_core/filter_pid.c#L2993

there no point in fixing specific instances, there needs to be a `get_colon_after_filename()` or something that is called everywhere we need to do this

i'll try to do this soon (i'm mostly posting this as a reminder)

**Comment by jeanlf** [comment]
now fixed / cleaned up, thanks for the report - we need to find a way to add absolute path testing in our test suite ...
