### ISSUE TITLE
Compiling branch=filters gpac 0.9.x mp4box.exe creeates GPAC.cfg file?

### ISSUE THREAD

**Issue by Murmur** [gpac/gpac#1261]
Compiling and running mp4box.exe from the filters branch even without any arguments creates `$workdir/Storage/, $workdir/GPAC.cfg`  folder and file.

I did have some problems with compiling in MSYS2+MingGW due to a new dependency on libavformat.h ffmpeg files. I am using the isolated msys2 console for compiling so had to do some manual copypaste header+lib files from the ffmpeg project.

I am missing some enable/disable flags? I don't think mp4box should create a folder and cfg file?
```
MP4Box.exe=6.4MB filesize
MP4Box.exe -version
MP4Box - GPAC version 0.9.0-DEV-revUNKNOWN-filters
(c) 2000-2019 Telecom ParisTech distributed under LGPL v2.1+ - http://gpac.io
GPAC Configuration: --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/build_custom --disable-shared --enable-static --static-mp4box
```

**Comment by jeanlf** [comment]
Behaviour for config has changed in 0.9.0, we always have a config file, regardless of the apps (MP4Box, MP4Client or gpac). This allows overriding any libgpac core options and filter options, as [explained here](https://github.com/gpac/gpac/wiki/core_config).
