### ISSUE TITLE
GPAC 0.9.0 - unable to encrypt H.264 and HEVC content

### ISSUE THREAD

**Issue by BucherTomas** [gpac/gpac#1273]
Using `mp4box -crypt crypt.xml input.mp4 -out output.mp4` works fine in GPAC 0.7.2, however, 0.9.0-DEV-rev2522-ge29dba15-filters is unable to encrypt any H.264 or HEVC content I tried using the same crypt.xml based on AES-CTR. VP9 is ok, haven't tested AV1.

Alternative approach with `gpac -i input.mp4 cecrypt:cfile=crypt.xml @ -o output.mp4` yields the same error with H.264 or HEVC content as mp4box itself.

`ISOBMF: Error Bad Parameter writing box senc`
`[iso file] Box trak wrote 12731 bytes but size is 24731`
`ISOBMF: Error Bad Parameter writing box trak`
`[iso file] Box moov wrote 12847 bytes but size is 25530`
`[MP4Mux] Failed to write file: Bad Parameter`

I can provide crypt.xml upon request.

**Comment by jeanlf** [comment]
could you please provide the xml ? we might have a hole in the test suite

**Comment by BucherTomas** [comment]
Uploaded to your MediaFire share as crypt.zip with comment "GPAC-1273".

**Comment by jeanlf** [comment]
thanks for the report - the issue only happens with large file, should now be fixed (both mp4box and gpac)
