### ISSUE TITLE
Encrypted multichannel audio declared as stereo after dashing

### ISSUE THREAD

**Issue by BucherTomas** [gpac/gpac#1274]
If dashing encrypted multichannel 5.1 audio with 0.8.0-rev1-gc1990d5c-master and older revisions, resulting dash manifest claims that there are just two channels.
`<AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>` even though `mp4box -info aac51encrypted.mp4` correctly reports all 6 channels.

If dashing unencrypted 5.1 audio, channels are declared correctly as
`<AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="6"/>`

This is already corrected in the new 0.9.0 filters branch, but can it please be backported also into 0.8.0 master branch that is as of now more stable and in some procedures much faster?

Circumstances surrounding channel detection in this scenario don't seem to be related to recent fix in https://github.com/gpac/gpac/issues/881 for GPAC 0.9.0.

I've uploaded clear and encrypted multichannel test content to your MediaFire storage for you to verify as multichannel.zip.

**Comment by jeanlf** [comment]
I will have a look at it. Could you please elaborate on the difference of performances you observe between 0.8.0 and 0.9.0 (please open a new issue) ?

**Comment by jeanlf** [comment]
should now be fixed, thanks for the report
