### ISSUE TITLE
Compiling gpac and using pipes in gpac

### ISSUE THREAD

**Issue by marlocarlo** [gpac/gpac#1275]
Hello,
I tried compiling GPAC and I got MP4Box installed after following the instructions here  : https://gpac.wp.imt.fr/2011/04/20/compiling-gpac-on-ubuntu/
 I am able to use MP4Box but not gpac. How do I use the gpac binary? How do I build and get it?

I am trying to follow https://github.com/gpac/gpac/wiki/pipes on using gpac for pipes.

How to compile the gpac executable on my system so that I can try out gpac for pipes?

Thanks

**Comment by aureliendavid** [comment]
Hi, 

while they are still in beta, you need to build the **`filters`** branch of the project to get the gpac binary and all the new features. 

You can find updated build instructions here: https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux#full-gpac-build

Just replace 

`git clone https://github.com/gpac/gpac gpac_public`

with 

`git clone --branch filters https://github.com/gpac/gpac gpac_public`

Or, if you've already cloned, add a 

`git checkout filters`

before the `./configure`
