### ISSUE TITLE
Performance disparity between filters and master branches

### ISSUE THREAD

**Issue by BucherTomas** [gpac/gpac#1276]
I'm experiencing a huge difference in perfomance of mp4box between filters and master  branches when dashing.

For the test I used a 288p 5-minute video as source. It does not seem like fine-tuning arguments play any role in performance nor what kind of content is being processed, so the comparison here is made with simple commandline `mp4box -dash 2000 source.mp4#video -out manifest.mpd`

Windows build 0.8.0-rev18-gb2e67a99-master is able to dash such content in 1.5 second on an Intel i5@2,5Ghz CPU with SSD.

Windows build 0.9.0-DEV-rev2567-g2fb6b79d-filters requires whopping 34 seconds to finish on the same system.

**Comment by jeanlf** [comment]
this is not normal indeed. I tried with a 4h 640p file (6s on OSX i7@2.5Ghs) and cannot notice such a big difference. Could you upload your test file ?

**Comment by BucherTomas** [comment]
Thanks. Uploaded as colorbars.mp4, but to me it doesn't matter what the source is, each file behaves the same way.

**Comment by jeanlf** [comment]
hmm mediafire blocks the download of the file (__"Mustangs Fc" by Unspecified may be available for download from Amazon"__), could you zip/crypt it ?

**Comment by jeanlf** [comment]
never mind, I managed to get it. It looks mostly like a console issue while displaying the  progress, could you try using `-quiet`and see if this helps ? I'll investigate further

**Comment by BucherTomas** [comment]
Yes, it is caused by displaying progress and `-quiet` brings it down again to expected duration of 2 seconds.

**Comment by jeanlf** [comment]
OK I'll patch the refresh rate of the progress. Note that 0.9.0 has an unavoidable overhead compared to 0.8.0 due to the filter architecture, but it should be very small (my test on an 8 hour movie show 1 sec overhead compared to 0.8.0). We're checking if/how we can further optimize this

**Comment by jeanlf** [comment]
this should be better now without -quiet or -noprog, could you give it a try?

**Comment by BucherTomas** [comment]
Thank you! I can confirm that printing progress to console no longer slows mp4box down.
