### ISSUE TITLE
Question - How to get previous and next random access samples

### ISSUE THREAD

**Issue by maureendaum** [gpac/gpac#1278]
I am looking for a way to get the sample number's of the previous and next random access points for a given sample. I looked at `gf_isom_get_sample_for_media_time` using `GF_ISOM_SEARCH_SYNC_FORWARD` and `GF_ISOM_SEARCH_SYNC_BACKWARD`, but it does more work than I want because I don't actually need the sample data.

The function `stbl_GetSampleRAP` does exactly what I want, but it is not exported.

Is there any way to achieve what I want using public API, or if not, is there any chance that such functionality could be exposed in public API?

- [ X ] I looked for a similar issue and couldn't find any.
- [ NA ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ NA ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
I think passing NULL for the sample but not null for the sample number should work, could you check ? (We really need to update the isobmf lib doxygen ...)

**Comment by maureendaum** [comment]
I tried that out, but I get a `GF_BAD_PARAM` error when the sample is `NULL` in `gf_isom_get_sample_for_media_time`.

**Comment by jeanlf** [comment]
Which version do you use ? this works on 0.9.0 only

**Comment by jeanlf** [comment]
checked with latest git on 0.9.0, cannot reproduce
