### ISSUE TITLE
STSC entry_count is zero after doing CENC encryption

### ISSUE THREAD

**Issue by delbinwen** [gpac/gpac#128]
Hi,

We do CENC encryption and then generate MPEG-DASH stream; both steps use MP4Box. We encoded several MP4 (with various bitrate) files and do CENC one-bye-one. And then running MP4Box to do MPEG-DASH. The problem is MP4Box failed to dash one of the MP4 files, and reports invalid IsoMedia file.

I did some code trace and noticed the reason MP4Box thought the file is invalid is due to enctry_count of stsc box is zero. So, my question is why CENC encryption does not generate stsc entryies correctly.

I see there is code snippet at isom_store.c:1204 to compare firstSize and finalSize. I did not understand what they mean, but what I can tell is those two values are different for the problematic file.

Does anyone could provide some hint for me that I can help identify the issue? I believe you could easily resolve the issue with the clip, but we can't share it due to legal problem.

Oh. The file size (before encryption) is 4293562962 bytes.

Thanks,
Wesley

**Comment by jeanlf** [comment]
indeed something was buggy here, could you check latest git ?

**Comment by delbinwen** [comment]
thank you jeanif!

I just pull the code and run it; the entry_count of STSC box now has value. I could double check if we could dash it successfully.

**Comment by delbinwen** [comment]
Good. I can now successfully dash the encrypted MP4 files.
