### ISSUE TITLE
Add option to consider preroll when splitting

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#1280]
For example when splitting Opus MP4s, we should add an option to add overlapping samples. At the moment we only split the samples, so the splitted content rendered in a playlist would contain some gaps.

**Comment by jeanlf** [comment]
Audio samples overlapping the split range are now signaled in reframer (unless disabled using `--no_audio_seek`).
If priming is used in the stream, split range start is adjusted to include priming data.
