### ISSUE TITLE
does not start with sync marker

### ISSUE THREAD

**Issue by ComputerUser-CU** [gpac/gpac#1281]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

-----------------------------------------------------------------------------------------------------------

[The video ](https://drive.google.com/open?id=1M8gJMd_-OhX6qJD5KTxBHkavU64w-_WY) was being HLS streamed using AES-128. Even though I could view it perfectly fine in the browser, VLC doesn't play the downloaded video file. It doesn't seem to contain any metadata or codec information either.

I thought re-encoding it with ffmpeg might solve the issue. But ffmpeg throws these exceptions irrespective of the operation I try to perform:
`[mov,mp4,m4a,3gp,3g2,mj2 @ 000002a477298a80] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 000002a477298a80] moov atom not found
4.mp4: Invalid data found when processing input`

Google search led me to mp4box. But running `MP4Box -add 4.mp4 41.mp4`, `MP4Box -inter 0 4.mp4` or `MP4Box -add 4.h265 41.mp4` show exceptions such as:

- Incomplete MDAT while file is not read-only

- Invalid IsoMedia File

- [MPEG-2 TS] TS Packet 1 is scrambled - not supported

- [MPEG-2 TS] TS Packet 2 has error (PID could be 1792)

- [MPEG-2 TS] TS Packet 3 does not start with sync marker

- Error importing 4.mp4: Corrupted Data in file/stream

- Cannot find HEVC start code

- Error importing 4.h265: BitStream Not Compliant

The actual logs are [here](https://pastebin.com/u97hZvBS).

Any idea how I can make this video download work? 

Notes:

- It's actually a 2hr 49min 10sec long video.

- I've installed gpac-0.8.0-rev23-g2929c6df-master-x64.exe on Windows 10 64-bit platform.

**Comment by rbouqueau** [comment]
The content is entirely ciphered. Therefore it is a stream of random bytes until you can decipher it. What the decryption key?

**Comment by ComputerUser-CU** [comment]
I guess, for the decryption key, we'd need the URI and the IV, right? I didn't save the m3u8 manifest for that.. Let me download another file and save its m3u8 manifest. I'll come back to you with that..

**Comment by ComputerUser-CU** [comment]
If it's possible, please let me know how I may generate the decryption key from the URI, IV etc..

**Comment by rbouqueau** [comment]
It is not possible. The decryption key comes from your DRM. If you don't operate your own DRM service, there's usually a secured path (e.g. CDM in a browser) that sends the encrypted data to a hidden zone which knows about the decryption key. Getting the decryption key is out of scope for this forum but the decryption process is. Let us know when you have the key!
