### ISSUE TITLE
play encrypted vedio on android with osmo4

### ISSUE THREAD

**Issue by azhar5678** [gpac/gpac#1282]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

mp4 box encrypt file on windows
how do i play encrypted vedio on android with osmo4 , clear key

how do i start

**Comment by jeanlf** [comment]
see #239 - we don't have ClearKey support for now, not sure when/if we will add this. Check other players support for decryption.
