### ISSUE TITLE
play encrypted vedio in exoplayer

### ISSUE THREAD

**Issue by azhar5678** [gpac/gpac#1284]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

MP4Box -crypt drm_file.xml movie.mp4 -out movie_encrypted.mp4
file encrypted above , will it play in exoplayer offline from sd card ie both key and vedio are in sd card

**Comment by jeanlf** [comment]
Don't know and not a gpac issue, check exoplayer docs.

**Comment by azhar5678** [comment]
fmpeg -i input.mkv -an -c copy video.mp4

ffmpeg -i input-video.avi -vn -acodec copy output-audio.m4a
iam able to run on exoplayer with these commands but on mp4client it crahes on rewind
MP4Box -dash-strict 2000 -rap -frag-rap  -bs-switching no -profile dashavc264:live  d:/dashvedio1/vkkk.mp4 d:/dashvedio1/output-audio.aac -out d:/dashvedio1/manifest.mpd


MP4Box -dash 4000 -strict 20000 -rap -frag 4000   -bs-switching no -profile "dashavc264:live" "d:/dashvedio1/vkkk.mp4" "d:/dashvedio1/audio.m4a"  -out "d:/dashvedio1/manifest.mpd"
