### ISSUE TITLE
dumping Dash from mpd 

### ISSUE THREAD

**Issue by irrz** [gpac/gpac#1287]
Hello guys
I used to dump easily the segments while streaming for post streaming tests. However, now I only can find the mpd file and the text file that contains the mpd details on the temp folder (where i directed the streaming to be stored).
If i use the MP4Client to stream each segment (NOT requesting the MPD), I can get these streamed files in the directory, but I get them in one mp4 file not multi mp4 files

I checked the configuration in https://github.com/gpac/gpac/issues/2 , but they are not working with me!

**Comment by jeanlf** [comment]
I'm not sure I understand your issue, could you give more details incl. command line and OS used ?

**Comment by irrz** [comment]
Hi Jean
I had yuv video and created 12 different qualities (different resolutions and bitrates), those produced video representations were dashed using the following command:
MP4Box -dash 1000 -dash-profile onDemand -rap -bs-switching no E:\Raw_videos\Jockey_256x144_100K_AVC.mp4 E:\Raw_videos\Jockey_320x180_200K_AVC.mp4 E:\Raw_videos\Jockey_384x216_240K_AVC.mp4 E:\Raw_videos\Jockey_384x216_375K_AVC.mp4 E:\Raw_videos\Jockey_512x288_550K_AVC.mp4 E:\Raw_videos\Jockey_640x360_750K_AVC.mp4 E:\Raw_videos\Jockey_768x432_1000K_AVC.mp4 E:\Raw_videos\Jockey_1024x576_1500K_AVC.mp4 E:\Raw_videos\Jockey_1280x720_3000K_AVC.mp4 E:\Raw_videos\Jockey_1280x720_3000K_AVC.mp4 E:\Raw_videos\Jockey_1920x1080_4300K_AVC.mp4 E:\Raw_videos\Jockey_1920x1080_5800K_AVC.mp4

the outcomes of dashing is attached in the attached photo
![dashing outcomes](https://user-images.githubusercontent.com/16091677/61997771-b5a01780-b09e-11e9-9128-347e7dd8a050.PNG)

then I play the streamed files using MP4Client:
mp4client -gui http://192.168.1.102/dash/avc/dashing%20test/1s/avc_1s.mpd

 please find the attached gpac.cfg where has the configuration including the storage of the video segments.
Also, I am working on Windows OS.
[GPAC.TXT](https://github.com/gpac/gpac/files/3438434/GPAC.TXT)

Thanks

**Comment by irrz** [comment]
Any ideas guys :-)

**Comment by aureliendavid** [comment]
let's see if I understand your issue

you have some dashed content on a server, and you're trying to keep the downloaded segments from the gpac cache by playing the mpd with mp4client, is that right? 

does the playback with mp4client actually works properly?

in your screenshot you have a `Jockey_....mpd` and then a command line with `avc_1s.mpd`, why is that?

you can try to add `-logs networking@debug` to your mp4client command line to see what is actually being downloaded

**Comment by irrz** [comment]
Thanks aureliendavid for the reply

I will answer you point by point:
1. you have some dashed content on a server, and you're trying to keep the downloaded segments from the gpac cache by playing the mpd with mp4client, is that right?
Yes exactly, and the reason behind that is to do a VoD comparisons for different segment sizes.

2. does the playback with mp4client actually works properly?
Yes it does although there is some distortions while streaming

3. in your screenshot you have a Jockey_....mpd and then a command line with avc_1s.mpd, why is that?
I did it by mistake

4. you can try to add -logs networking@debug to your mp4client command line to see what is actually being downloaded
I did that even with another video codec (hevc) but still i get the same issue
The MP4client command:
mp4client -logs network@debug -gui http://192.168.1.102/dash/hevc/1s/hevc_1s.mpd
![debug outcomes](https://user-images.githubusercontent.com/16091677/62246249-21ee8400-b3db-11e9-81b8-c3630d2819e1.PNG)
The MPD file is 
[hevc_1s.txt](https://github.com/gpac/gpac/files/3453798/hevc_1s.txt)

However, I don't get any segments in the Temp folder (where i directed the files to be saved)
![mp4client outcomes](https://user-images.githubusercontent.com/16091677/62246385-6712b600-b3db-11e9-9246-1b749e677078.PNG)
------------

I remember while back ago, I used to do live streaming using the DashCast, and then I get the segments with an extensions of .m4s (if not wrong)
Do you think I can get something similar so I can easily download them into my directory. and later i simply concatante them with the init.mp4 using the ffmpeg for the evaluations?

Many thanks

**Comment by aureliendavid** [comment]
According to your logs, the downloaded pieces are cached in memory and not in files, that's why you're not seeing them. 

In your `GPAC.cfg`, in the `DASH` section, try setting:

```
[DASH]
...
MemoryStorage=no
....
```

and check in the networking logs if it is saving a file.

**Comment by irrz** [comment]
It works now my friend

Thanks a lot

**Comment by jeanlf** [comment]
You can also play with the dash input filter split_as option to rip the different qualities to standalone files using url templates. I’ll write a howto after my vacations

**Comment by irrz** [comment]
Enjoy it Jean and I am looking forward to it :-)

**Comment by irrz** [comment]
Hi guys 
I have managed dumping the files but with another dashing code:
MP4Box -dash 1000 -dash-profile onDemand -rap -frag 500 Jockey_256x144_100K_AVC.mp4 Jockey_320x180_200K_AVC.mp4 Jockey_384x216_240K_AVC.mp4 Jockey_384x216_375K_AVC.mp4 Jockey_512x288_550K_AVC.mp4 Jockey_640x360_750K_AVC.mp4 Jockey_768x432_1000K_AVC.mp4 Jockey_1024x576_1500K_AVC.mp4 Jockey_1280x720_3000K_AVC.mp4 Jockey_1280x720_3000K_AVC.mp4 Jockey_1920x1080_4300K_AVC.mp4 Jockey_1920x1080_5800K_AVC.mp4 -mpd-title AVC -out AVC_1s.mpd

and for the same for hevc, vp9 and av1, I replicate the above command accordingly.

I have 2 questions:
1. I noticed that the MP4Client does not adapt with AV1, although there is higher bandwidth available. Is there anyway I can apply to ensure the adaptation?
2. How can I concatanate the dumped segments into one file that has one FHD resolution?

Please find the gpac.cfg
[GPAC.txt](https://github.com/gpac/gpac/files/3478939/GPAC.txt)

With my thanks in anticipations
irrz
