### ISSUE TITLE
GPAC 0.9 Illegal instruction: 4

### ISSUE THREAD

**Issue by grylem** [gpac/gpac#1288]
Hi
If file aac contains 5.1 channels
v8
$ MP4Box -raw 1 -raw 2 in.mp4
Extracting MPEG-4 AVC-H264 stream to h264
Extracting MPEG-4 AAC

v9
$ MP4Box -raw 1 -raw 2 in.mp4
Exporting MPEG-4 AVC|H264 Video - Size 1280x720
RFADTS] Mismatch betwwen container number of channels (2) and AAC config (6), using AAC config
Exporting MPEG-4 AAC Audio - SampleRate 44100 2 channels 16 bits per sample

Ok.
For files extracted with v8
v8
$ MP4Box -add in.h254 -add in.aac out.mp4
[avc-h264] Possible Variable Frame Rate: VUI "fixed_frame_rate_flag" absent.
AVC-H264 import - frame size 1280 x 720 at 24.000 FPS
AVC Import results: 200 samples (405 NALUs) - Slices: 2 I 198 P 0 B - 1 SEI - 2 IDR
AAC ADTS import  - sample rate 44100 - MPEG-4 audio - 6 channels

but MP4Box - GPAC version 0.9.0-DEV-rev2669-g548d4fcc-filters
$ MP4Box -add in.h254 -add in.aac out.mp4
Illegal instruction: 4

[5.1 Surround Sound AAC Test.mp4.zip](https://github.com/gpac/gpac/files/3440992/5.1.Surround.Sound.AAC.Test.mp4.zip)

**Comment by aureliendavid** [comment]
I can't reproduce this with the file you provided on any macos version. I tried with building from source and using the installers on gpac.io and it works fine in both cases. 

Please check your build / install. In particular, if you're using both 0.8 and 0.9 version, check you don't have conflicts in terms of libraries, environment variables, config file. etc. that would result in one version using the libraries of the other.

**Comment by grylem** [comment]
Extracted
MP4Box - GPAC version 0.9.0-DEV-rev2669-g548d4fcc-filters from gpac.io
$ MP4Box -add in.h254 -add in.aac out.mp4
Illegal instruction: 4

High Sierra, case sensitive.
[extracted.zip](https://github.com/gpac/gpac/files/3441964/extracted.zip)

**Comment by aureliendavid** [comment]
look I get it but I still can't reproduce it: 

```shell
$ sw_vers 
ProductName:    Mac OS X
ProductVersion: 10.13.6
BuildVersion:   17G6030

$ which MP4Box
/Applications/GPAC.app/Contents/MacOS//MP4Box

$ MP4Box 
Not enough arguments - check usage with -h
MP4Box - GPAC version 0.9.0-DEV-rev2669-g548d4fcc-filters
(c) 2000-2019 Telecom ParisTech distributed under LGPL v2.1+ - http://gpac.io

$ wget -q "https://github.com/gpac/gpac/files/3441964/extracted.zip"   
$ unzip extracted.zip 
Archive:  extracted.zip
  inflating: 5.1 Surround Sound AAC Test_track1.h264  
  inflating: 5.1 Surround Sound AAC Test_track2.aac  

$ MP4Box -add 5.1\ Surround\ Sound\ AAC\ Test_track1.h264 -add 5.1\ Surround\ Sound\ AAC\ Test_track2.aac out.mp4
[AVC|H264] Possible Variable Frame Rate: VUI "fixed_frame_rate_flag" absent
Track Importing MPEG-4 AVC - Width 1280 Height 720 FPS 96/4 SAR 1/1
AVC|H264 Import results: 200 samples (406 NALUs) - Slices: 3 I 198 P 0 B - 1 SEI - 2 IDR
Track Importing AAC  - SampleRate 44100 Num Channels 6
Saving to out.mp4: 0.500 secs Interleaving

$ echo $?                        
0
```

**Comment by rbouqueau** [comment]
@grylem could you give more information about your hardware?

**Comment by jeanlf** [comment]
Cannot reproduce here either (OSX mojave) - please give more details on your config and reopen if still crashing
