### ISSUE TITLE
EBU-TT-D: fix whitespace on div level message

### ISSUE THREAD

**Issue by basicmaster** [gpac/gpac#1290]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...).

----

When whitespace is present on `div` level (see [whitespace_below_div.xml.log](https://github.com/gpac/gpac/files/3444159/whitespace_below_div.xml.log); remove `.log`), messages are shown that the namespace should be checked:

```
[TTML] ignored "
			" node, check your namespaces
[TTML] ignored "
		" node, check your namespaces
```

Used cmdline: `MP4Box -add whitespace_below_div.xml:ext=ttml test.mp4`

However the reason is that on `div` level just text nodes (consisting of spaces) are found, as the file contains indentation. As these text nodes are already ignored on `body` level, the same should be done on `div` level, in order to prevent such false positives - as actual text content can only be present on `p` or `span` level anyway.

**Comment by rbouqueau** [comment]
Thanks. I merged your PR so I assume I can close here!
