### ISSUE TITLE
[MP4BOX] [MP4] Meridian Lossless Packing (Dolby TRUEHD) support

### ISSUE THREAD

**Issue by likeadoc** [gpac/gpac#1292]
Build used: http://gpac.io/downloads/gpac-nightly-builds/
It seems that packaging a TRUEHD/MLP stream into a mp4 container isn't supported by any currently available software - despite the capabilities of the MP4 container.

References:
http://mp4ra.org/#/codecs - see codec mlpa - (clearly states support for Dolby MLP)
https://developer.dolby.com/globalassets/technology/dolby-truehd/dolbytruehdbitstreamswithintheisobasemediafileformat.pdf  - describes the storage of Dolby® TrueHD (MLP) audio bitstreams in a file format compliant with the ISO base media file format
https://en.wikipedia.org/wiki/Comparison_of_video_container_formats - see audio coding formats support - also clearly states support for TRUEHD in mp4.

**Comment by rbouqueau** [comment]
Dolby seem to provide a muxer: https://github.com/DolbyLaboratories/dlb_mp4base. I haven't tested my self and am interested in any feedback on their tool.

Once your content is in MP4 you can do split/dash/whatever operation on it without having to deal with its semantics.

**Comment by likeadoc** [comment]
Unfortunately dlb_mp4base only works with the usual suspects (AC3 & AAC)

**Comment by rbouqueau** [comment]
It seems like there are no samples publicly available. Would you mind asking Dolby for more information on this?

**Comment by likeadoc** [comment]
I have contacted Dolby today and am awaiting their response.

**Comment by likeadoc** [comment]
@rbouqueau Unfortunately Dolby has not responded to my inquiry up until now - but the ffmpeg team was able to integrate Dolby TrueHD support for  the mp4 container it with this commit: http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=808a6717e0c584738c60a109afd6d47f4973d619 (based on the Dolby whitepaper that is mentioned in the first post)

**Comment by rbouqueau** [comment]
As an addition it seems that FFmpeg is able to encode/decode TrueHD streams!

**Comment by jeanlf** [comment]
now on git

**Comment by gacopl** [comment]
hi @jeanlf are there any special switches needed ? I have plain truehd track with atmos (not truehd+ac3 core) and i get following when adding it to mp4
```[Importer] Error importing 5.eng.thd
Failure while importing media: BitStream Not Compliant
Error importing 5.eng.thd:lang=eng:name=Eng.TrueHDAtmos: BitStream Not Compliant```

**Comment by jeanlf** [comment]
Hmm never tried that, could you upload a sample file ?

**Comment by jeanlf** [comment]
should now be fixed thanks for the report
