### ISSUE TITLE
GPAC 0.9.0 - mp4box not using -pssh correctly

### ISSUE THREAD

**Issue by BucherTomas** [gpac/gpac#1293]
Mp4box provides `pssh` parameter to specify where cenc protection data are supposed to be placed. This parameter is working fine in master branch, however, filters branch is either ignoring the values or printing error `Wrong argument value moof for unsigned int arg pssh enum v|f|mv|mf|m|n - using 0`

For instance using `-pssh=mv` no error is printed, but pssh data are missing in the mpd manifest, they are only in init segments.
Using `-pssh=m` prints the above mentioned error and again, pssh data are obviously missing in the manifest, but this time they are wrongly present in init segments.

Similar unexpected behavior can be observed with the rest of pssh values as well, they all seem to default to `-pssh=v`.

Seen with 0.9.0-DEV-rev2670-g88c73eb3-filters.

**Comment by aureliendavid** [comment]
I think it should be fixed now, hopefully I didn't break anything else in the process. 

Please retry and let me know. 

Thanks.

**Comment by BucherTomas** [comment]
Fixed, thank you!
