### ISSUE TITLE
AV1 adaptation and concatenation

### ISSUE THREAD

**Issue by irrz** [gpac/gpac#1297]
Hi guys
I have managed dumping the files ( https://github.com/gpac/gpac/issues/1287) but with another dashing code:
MP4Box -dash 1000 -dash-profile onDemand -rap -frag 500 Jockey_256x144_100K_AVC.mp4 Jockey_320x180_200K_AVC.mp4 Jockey_384x216_240K_AVC.mp4 Jockey_384x216_375K_AVC.mp4 Jockey_512x288_550K_AVC.mp4 Jockey_640x360_750K_AVC.mp4 Jockey_768x432_1000K_AVC.mp4 Jockey_1024x576_1500K_AVC.mp4 Jockey_1280x720_3000K_AVC.mp4 Jockey_1280x720_3000K_AVC.mp4 Jockey_1920x1080_4300K_AVC.mp4 Jockey_1920x1080_5800K_AVC.mp4 -mpd-title AVC -out AVC_1s.mpd

and for the same for hevc, vp9 and av1, I replicate the above command accordingly.

I have a question

I noticed that the MP4Client does not adapt with AV1, although there is higher bandwidth available. Is there anyway I can apply to ensure the adaptation?
Hence, I played AVC, HEVC and VP9 mpds and they are all perfectly playable
Please find the gpac.cfg
[GPAC.txt](https://github.com/gpac/gpac/files/3481385/GPAC.txt)

With my thanks in anticipation
Irrz

**Comment by irrz** [comment]
Any ideas guys :-)

**Comment by jeanlf** [comment]
Are you playing from local storage or through http?

**Comment by irrz** [comment]
Hi
It's through http server XAMPP

**Comment by irrz** [comment]
Hi JeanIf
I have updated the issue as i managed concatenating the dumped files but still i have the issue with AV1 adaptation.
I will be grateful if you can figure my issue out

**Comment by jeanlf** [comment]
sorry for late followup, can you reproduce this using GPAC 1.0 / latest master ?

**Comment by jeanlf** [comment]
I cannot reproduce here, AV1 adaptation is OK. If needed, post sample content and reopen
