### ISSUE TITLE
Question about command line in MPEG-DASH SRD example.

### ISSUE THREAD

**Issue by Wociao** [gpac/gpac#1298]
Hi, I am using win10 and I test SRD with GPAC-0.8.0 and GPAC-0.6.2 in my PC. I have several questions about the [**MPEG-DASH SRD and HEVC tiling for VR videos**](https://gpac.wp.imt.fr/2016/05/25/srdtuto/).

1. I followed the example command: 

> "MP4Box -dash 1000 [other dash params]  source.mp4:desc_as=<SupplementalProperty schemeIdUri= \"urn:mpeg: dash :srd:2014\" value=\"0,0,1,1,1,2,2\"/>" 

and set my own command as 

> "MP4Box -dash 1000 -frag 1000 -rap - segment-name TileTest_  myOwnVideo.mp4:desc_as=<SupplementalProperty schemeIdUri= \"urn:mpeg: dash :srd:2014\" value=\"0,0,1,1,1,2,2\"/>"

. But in the terminal, I got error, which is "The syntax of the command is incorrect". I firstly test this function with GPAC-0.8.0 and then test this function with GPAC-0.6.2. And I got the same error. 

2. In [**MPEG-DASH SRD and HEVC tiling for VR videos**](https://gpac.wp.imt.fr/2016/05/25/srdtuto/), I am not clear how the command 

> indicates that source.mp4 is placed at X=0, Y=1 with width 1 and height 1 on a tiling grid of size 2×2.

3. Based on the paper, this work could help set different resolution for different tiles. I did not find any instrunction about SRD in the [MP4Box document](https://gpac.wp.imt.fr/mp4box/mp4box-documentation/)

Thank you very much.

When I testing the MP4box functionality, I set the system path independently for 

- [x ] I looked for a similar issue and couldn't find any.
- [ x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by venn29** [comment]
Hello, have you solved this problem?
I also met the same problem as yours. If you solved this problem, would you please give me any advice?

**Comment by jeanlf** [comment]
1 For setting dash descriptors, check:
https://github.com/gpac/testsuite/blob/filters/scripts/dash-descriptor.sh

2 DASH SRD Descriptor
> 0,0,1,1,1,2,2
The first value is a sourceID (usually ignored), the next 2 values are X and Y (from top-left), the next two are width and height of the tile, the last two are total width and height of the SRD region

For example, `0,0,720,1280,720,1280,1440`will indicate the upper half of a 1280x1440 area, and `0,0,0,1280,720,1280,1440` will indicate the lower part.
