### ISSUE TITLE
Urgent: Dead links for GPAC installers at https://gpac.wp.imt.fr/downloads/

### ISSUE THREAD

**Issue by facorread** [gpac/gpac#1299]
I imagine it is some script error. Please visit https://gpac.wp.imt.fr/downloads/; all links are dead. I used "Urgent" because I am not able to set a priority/severity level for this issue. Well, it is a showstopper of course.

**Comment by aureliendavid** [comment]
oops that's my bad, should be fixed now, thanks for the report
