### ISSUE TITLE
when concatenating incompatible H264 files, mp4box creates mixed avc1/avc3 mp4 files

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#13]
I can't share files here, please contact me to be able to reproduce. The only difference is the presence of the `aspect_ratio_info_present_flag` flag in the SPS.

The streams are generated with FFmpeg and I couldn't figure out with the SPS were different yet.

GPAC could either have:
- a better comparison algorithm for AVCConfig (especially for descriptors) ;
- change the behaviour and use multiple "sample descriptions" with 'avc1' or switch completely to 'avc3' - check if compatible with existing players.

Opinions? CC @gpac/owners

**Comment by JeffroDH** [comment]
I have seen this behavior with streams encoded with Handbrake.  2 files joined flawlessly, remained in H.264, and the next 2, encoded with the exact same settings encoded to AVC3 and won't import into iTunes.  I built the latest version of GPAC this week.

**Comment by rbouqueau** [comment]
@JeffroDH As mentioned above, the SPS from FFmpeg are really different. Do you have any idea why?

**Comment by JeffroDH** [comment]
No idea.

**Comment by rbouqueau** [comment]
From #235:

> I need to find the reference, but FFmpeg was "randomly" (i.e. from our perspective) inserting AR information in the SPS on similar streams. So we had added a SPS comparison (xPS hash displayed by 'MP4Box -info').

**Comment by jeanlf** [comment]
mutliple sample descriptions are now used when doing concatenation of files with incompatible codecs.

Also note that for avc or hevc, the global option `--xps_inband=mix` can be used but only using playlist files with gpac, not with MP4Box.
