### ISSUE TITLE
best way to dash vedios, 1gb file

### ISSUE THREAD

**Issue by azhar5678** [gpac/gpac#1301]
iam facing a problem with large vedios
i first divide a vedio file into vedio and audio seprate file
ffmpeg -i input.mkv -an -c copy video.mp4

ffmpeg -i input-video.avi -vn -acodec copy output-audio.m4a

then i dash the vedios
MP4Box -dash-strict 20000 -rap -frag-rap  -bs-switching no -profile "dashavc264:live" "d:/dashvedio1/vkkk.mp4" "d:/dashvedio1/audio.m4a"  -out "d:/dashvedio1/manifest.mpd"

but when iplay manifest.mpd file with mp4 client , when i forward it has no problem,but on backward mp4client crahes
do i need dash in large chunks or small chunk or any other suggestion

**Comment by jeanlf** [comment]
backward playback is not yet supported in MP4Client
