### ISSUE TITLE
Cannot split file

### ISSUE THREAD

**Issue by personaNonGrataUelGrata** [gpac/gpac#1302]
I have recorded some .ts file which I now want to split, however I am getting output which I am not sure if I understand correctly.
Seems like the file is corrupted or something, which causes `-split` or `-splits` to fail. I assume any operation on that file would fail

Below is the output
```
mp4box -splits 1499000 video_to_split.ts
[MPEG-2 TS] PID 256 - same PTS 714557970 for two consecutive PES packets
[MPEG-2 TS] PID 256 - same DTS 714557970 for two consecutive PES packets
[MPEG-2 TS] PID 256 - same PTS 714647970 for two consecutive PES packets
[MPEG-2 TS] PID 256 - same DTS 714647970 for two consecutive PES packets
Import probing results for video_to_split.s:
File has 3 tracks
Duration: 5276.55 s
	Track 258 type: Metadata (ID3 ) - Program 1
	Track 256 type: Video (H264) - Program 1
	Track 257 type: Audio (MP4A) - Program 1
```

Is there any way to make it work?

**Comment by jeanlf** [comment]
split options only work for MP4 files not TS, I will patch the messages to be more explicit. 
In 0.8.0 or below, you can try to split your TS by dashing it, but this has not been well tested, and might fail with ID3 PIDs.
In 0.9.0, we currently don't have tools allowing spliting of a ts without demuxing and remuxing it.
