### ISSUE TITLE
Gpac installlation problem

### ISSUE THREAD

**Issue by azhar5678** [gpac/gpac#1303]
After copying api ms win crt runtime 1.1.0
dll to system 32 and winsows64
It saying unable to start mp4box error code
o*77...
windows 7 64 bit. Vc runtime 15. 08 gpac

**Comment by aureliendavid** [comment]
Just copying this dll manually won't be enough. 

You need to reinstall gpac and check the "VS2015 C++ re-distribuable Package" in the install options. 

Alternatively you can download and install the redist package from here: https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by azhar5678** [comment]
Solved after installing .net  and visual studio.
