### ISSUE TITLE
MPEG2 TS Stream fitness test with gpac

### ISSUE THREAD

**Issue by frispete** [gpac/gpac#1305]
Hi,

sorry, if this question is misplaced, but the SF forums seems down, and point here. 

Given a lot of SD and HD content, that was received by VDR from a satellite dish during the last decade, I looking for a method to rate those records.

Is gpac able to check such streams (VDR just saves the TS streams verbatim) and rate the quality and fitness of such streams, e.g. analyse stream failures (drop outs, inconsistencies, invalid framing of audio, video, and other streams)?

From the project description, it might fit. I'm currently using 0.8.0 on openSUSE Tumbleweed, but packaging/using current git is fine as well.

**Comment by jeanlf** [comment]
Not really: you will see parsing log warning or errors on drops, but this is far from being a full TS analysis. We are not planning to write any TS conformance checker in GPAC.
