### ISSUE TITLE
SVG clipPath is not honored

### ISSUE THREAD

**Issue by ElBartel** [gpac/gpac#1310]
I've checked out the latest version of the filters branch (Merge branch 'master' into filters)  and compiled this on Ubuntu 14.04.In the top-level source directory I used the following command:
   bin/gcc/gpac -i /tmp/a.svg compositor:fps=25:dur=4:osize=256x256 -o /tmp/a.mp4
The resulting mp4 does not show any respect to the defined clip-path attributes. Neither for
the static rectangle nor the animated circle.

I've attached the /tmp/a.svg and the resulting /tmp/a.mp4.

**Comment by ElBartel** [comment]
Sorry cannot attach svg or mp4 here. So, the SVG comes here litterally:

<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     viewBox="0 0 1024 1024">
  <g>
    <defs>
      <clipPath id="cp0">
        <path d="M 0 500 L 1024 500 L 1024 524 L 0 524 L 0 500 Z"/>
      </clipPath>
    </defs>
    <rect x="0" y="0" width="1024" height="1024" fill="#c0c0c0" clip-path="url(#cp0)"/>
    <circle cx="512" cy="512" fill="#0000ff" r="6" clip-path="url(#cp0)">
      <animate attributeName="r" attributeType="XML" from="6" to="120" fill="freeze" begin="0ms" dur="1500ms"/>
    </circle>
  </g>
</svg>

**Comment by ElBartel** [comment]
Sorry cannot attach SVG and/or mp4. At least the SVG is here literally:

<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     viewBox="0 0 1024 1024">
  <g>
    <defs>
      <clipPath id="cp0">
        <path d="M 0 500 L 1024 500 L 1024 524 L 0 524 L 0 500 Z"/>
      </clipPath>
    </defs>
    <rect x="0" y="0" width="1024" height="1024" fill="#c0c0c0" clip-path="url(#cp0)"/>
    <circle cx="512" cy="512" fill="#0000ff" r="6" clip-path="url(#cp0)">
      <animate attributeName="r" attributeType="XML" from="6" to="120" fill="freeze" begin="0ms" dur="1500ms"/>
    </circle>
  </g>
</svg>

**Comment by ElBartel** [comment]
Last  try, the SVG comes here:
```
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     viewBox="0 0 1024 1024">
  <g>
    <defs>
      <clipPath id="cp0">
        <path d="M 0 500 L 1024 500 L 1024 524 L 0 524 L 0 500 Z"/>
      </clipPath>
    </defs>
    <rect x="0" y="0" width="1024" height="1024" fill="#c0c0c0" clip-path="url(#cp0)"/>
    <circle cx="512" cy="512" fill="#0000ff" r="6" clip-path="url(#cp0)">
      <animate attributeName="r" attributeType="XML" from="6" to="120" fill="freeze" begin="0ms" dur="1500ms"/>
    </circle>
  </g>
</svg>
```

**Comment by jeanlf** [comment]
Yep this is not implemented, not sure when we'll have time to add that

**Comment by jeanlf** [comment]
clip-path now supported, with following restrictions: no nesting, pointer events not clipped and `clipPathUnits=userSpaceOnUse` only
