### ISSUE TITLE
Best Replacement for DashCast

### ISSUE THREAD

**Issue by behoyh** [gpac/gpac#1311]
Hello,

I am trying to stream live event video from a connected input, and have the resulting live stream playable on iOS, Android, and Mac/Windows.

Right now the video stream plays fine on desktop using

`-vf avfoundation -vres 848x480 -v "Example Camera" -vfr 30 -live -pixf yuyv422 -conf dashcast.conf -live -v4l2f mjpeg -low-delay`

but Android and iOS do not load the video. I read somewhere that I need to split the stream into one that is M3u8/HLS. 

Anyways, from reading the other issues here on GitHub, I see that DashCast is deprecated. Is there any drop in replacement for DashCast to achieve what I'm looking for?

[sample](https://github.com/behoyh/bottle-nose), I use cloud ssh to publish local ports externally for testing

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
There is no drop-in replacement, but with a few change in your command line you can achieve the similar results using the gpac app (and this will give you support for dual HLS and DASH output). See:
- [this test](https://github.com/gpac/gpac/blob/filters/tests/scripts/dash-encode.sh) for dash with encoding
- [this test](https://github.com/gpac/gpac/blob/filters/tests/scripts/hls-gen.sh) for dual MPD and m3u8 output
- [encoding howto](https://github.com/gpac/gpac/wiki/encoding) page
