### ISSUE TITLE
AddressSanitizer: failed to allocate memory

### ISSUE THREAD

**Issue by HongxuChen** [gpac/gpac#1312]
When running `mp4box -diso $FILE` where files are mp4 shared on https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95, it reports error messages like "cannot allocate *** bytes" error when binary is cmpiled with ASAN. With regular compilation, it segfaults.

[ALLOC_gpac.zip](https://github.com/gpac/gpac/files/3668683/ALLOC_gpac.zip)
(In case mediafire cannot share correctly; will remove this attachment if requested.)

**Comment by aureliendavid** [comment]
Should be fixed now. Reopen if needed.

Thanks for the report.

**Comment by HongxuChen** [comment]
Hi, as of 57ffacc12, another mp4 may cause a similar allocation error.


[ALLOC_gpac_2.zip](https://github.com/gpac/gpac/files/3679878/ALLOC_gpac_2.zip)

**Comment by aureliendavid** [comment]
you're right, 203c6c0 should fix your second example

I found a bunch of similar cases just by grepping.

Hopefully the fuzzer we're currently setting up will catch these when it's properly running.

**Comment by HongxuChen** [comment]
Confirmed that this was fixed by 203c6c0. Will try to fuzz to see whether there are other issues.
