### ISSUE TITLE
Multiple Crashes/Hangs

### ISSUE THREAD

**Issue by HongxuChen** [gpac/gpac#1313]
We applied our fuzzer for running `MP4Box -diso $FILE` against 57ffacc12 and detected several crashes or unexpected hangs. And these are reproducible on 203c6c0 (HEAD).
The corresponding files (specially, proof-of-crashes are associated with ASAN error messages) are available [here](https://github.com/ntu-sec/pocs/tree/master/gpac/57ffacc12).

**Comment by HongxuChen** [comment]
A few other crashes detected by fuzzing against 203c6c0 and reproducible on b15b77a24 (HEAD), available [here](https://github.com/ntu-sec/pocs/tree/master/gpac/203c6c093/crashes).

**Comment by aureliendavid** [comment]
Thanks for these. We'll combine them with the results of our internal fuzzer and process them in bulk as a security update at some point.

**Comment by aureliendavid** [comment]
as of bb2d29d these should all be ok
