### ISSUE TITLE
"No SPS or PPS found in the bitstream" from adding raw h265 to MP4 container

### ISSUE THREAD

**Issue by kaspera** [gpac/gpac#1316]
[sample-001.zip](https://github.com/gpac/gpac/files/3724744/sample-001.zip)

My command line with latest GPAC version:
`MP4Box.exe -add "myVideo.h265#video:lang=eng -add "myAudio.m4a#audio:lang=eng -new "myContainer".mp4`
results in 

> "No SPS or PPS found in the bitstream | nothing imported"

 and 

> "Bitstream not compliant"

Sample with raw h265 attached. Any help? Thanks.

**Comment by rbouqueau** [comment]
How was this file generated? I confirm it misses some needed information to be processable.

@jeanlf The log with filters is very verbose (involving some ffmpeg parsing?) (while ok with 0.8)

```

**Comment by rbouqueau** [comment]
It works here:
```
> ffmpeg.exe -i /d/Works/gpac/seq/counter_video_180.mp4 -pix_fmt yuv420p10le -strict -1 -f 
yuv4mpegpipe - | ./x265-10bit-lite.exe --y4m --input - gpac.h265

> MP4Box -add gpac.h265 -new tmp.mp4
Track Importing HEVC - Width 320 Height 180 FPS 25/1 SAR 1/1
OpenGOP detected - adjusting file brand
HEVC Import results: 3077 samples (3082 NALUs) - Slices: 13 I 832 P 2232 B - 1 SEI - 1 IDR
HEVC Stream uses forward prediction - stream CTS offset: 4 frames
HEVC Max NALU size is 3320 - stream could be optimized by setting nal_length=2
Saving tmp.mp4: 0.500 secs Interleaving
```

What differs in your use-case?

**Comment by kaspera** [comment]
Now I know what was different this time: I do transcoding by batch processing and the `chapters.txt` was missing in the transcoding folder, MP4 muxing had worked right after transcoding had finished though. So I converted the new MP4 back to MKV using `mkvmerge.exe -o target.mkv =source.mp4`, then demuxed with `eac3to.exe target.mkv -demux`. Added the `chapters.txt` to the folder and tried 
`MP4Box.exe -add "myVideo.h265#video:lang=eng -add "myAudio.m4a#audio:lang=eng -chap chapters.txt -new "myContainer".mp4` and got the errors. I just reproduced this. Is it possible that converting and demuxing erased some of the hevc metadata?

**Comment by rbouqueau** [comment]
> Is it possible that converting and demuxing erased some of the hevc metadata?

It seems so!

**Comment by kaspera** [comment]
Is there a safe way to completely demux a MP4box container?

**Comment by rbouqueau** [comment]
MP4Box is safe:
```MP4Box -raw 1 file.mp4```

The ```'1'``` is the trackId that you can get with ```MP4Box -info file.mp4```

**Comment by kaspera** [comment]
Okay, thanks. I think `MP4Box -raw * file.mp4` is what I will use from now on.
