### ISSUE TITLE
[ProRes] No color info present in visual track, defaulting to BT709

### ISSUE THREAD

**Issue by microchip8** [gpac/gpac#1319]
Hi,

I always get when creating MOV files this warning from MP4Box 0.8.0. This is also true if the input (mp4/mov) contains valid colormatrix/trasfer/coefficients info

[ProRes] No color info present in visual track, defaulting to BT709

How to add the correct color info? is there a flag in MP4Box to do it? I Googled a lot but couldn't find anything

Thanks

**Comment by rbouqueau** [comment]
Hi,

> I always get when creating MOV files this warning from MP4Box 0.8.0.

First it looks like the log level is agressive, but that's a conformace issue:
```
	//todo: patch colr
	e = gf_isom_get_color_info(mp4, video_tk, 1, &colour_type, &colour_primaries, &transfer_characteristics, &matrix_coefficients, &full_range_flag);
	if (e==GF_NOT_FOUND) {
		GF_LOG(GF_LOG_WARNING, GF_LOG_AUTHOR, ("[ProRes] No color info present in visual track, defaulting to BT709\n"));
```

> This is also true if the input (mp4/mov) contains valid colormatrix/trasfer/coefficients info

I can't reproduce. Which command-line do you use? And is it possible to share a sample file? (anonymous dropbox at https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95).

> How to add the correct color info? is there a flag in MP4Box to do it?

You can manually add it with the ```colr=``` flags, cf help:
```
	        " \":colr=OPT\"           sets color profile for imported video content (see ISO/IEC 23001-8). OPT is formatted as:\n"
	        "                         - \"nclc,p,t,m\" : with p colour primary, t transfer characteristics and m matrix coef\n"
	        "                         - \"nclx,p,t,m,r\" : same as nclx with r full range flag\n"
	        "                         - \"prof,path\" : with path indicating the file containing the ICC color profile\n"
	        "                         - \"rICC,path\" : with path indicating the file containing the restricted ICC color profile\n"
```

**Comment by microchip8** [comment]
Hi,

I don't understand how to use the colr option. Can you provide a full MP4Box example for it? I tried using 

MP4Box -add myfile.mp4#video:colr=nclc,bt470bg,bt470bg,bt470bg -mpeg4 -new out.mov

but it says bad parameter

I've uploaded the input file to your Dropbox. It's called colormatrix-input.mp4

**Comment by rbouqueau** [comment]
> I don't understand how to use the colr option. Can you provide a full MP4Box example for it?

https://github.com/gpac/gpac/search?q=%3Acolr%3D&unscoped_q=%3Acolr%3D

> I've uploaded the input file to your Dropbox. It's called colormatrix-input.mp4

There is no 'colr' box in this file. But if you reimport it, GPAC will set the colr box properly:
```
MP4Box -raw 1 colormatrix-input.mp4
MP4Box -add colormatrix-input_track1.h264 colr.mp4
```

**Comment by microchip8** [comment]
Hi,

I still don't get it. When I inspect the colormatrix-input.mp4 file, MediaInfo reports that it has color info

Color range                              : Limited
Color primaries                          : BT.601 PAL
Transfer characteristics                 : BT.470 System B/G
Matrix coefficients                      : BT.470 System B/G

This file was created with FFmpeg with the appropriate color/transfer/matrix information

If I extract the video bitstream using your example and add it back to MP4Box, it still displays the same warning that no color info is present and defaults to BT709

If I again inspect the raw colormatrix-input_track1.h264 track with MediaInfo, it reports it has color characteristics present

Color range                              : Limited
Color primaries                          : BT.601 PAL
Transfer characteristics                 : BT.470 System B/G
Matrix coefficients                      : BT.470 System B/G

**Comment by rbouqueau** [comment]
> I still don't get it. When I inspect the colormatrix-input.mp4 file, MediaInfo reports that it has color info
> 
> Color range : Limited
> Color primaries : BT.601 PAL
> Transfer characteristics : BT.470 System B/G
> Matrix coefficients : BT.470 System B/G

I confirm I see the same on colormatrix-input.mp4 and if I remux it (```MP4Box -add colormatrix-input.mp4 remux.m4```).

> If I extract the video bitstream using your example and add it back to MP4Box, it still displays the same warning that no color info is present and defaults to BT709

I ,don't reproduce:
 - ```-add colormatrix-input_track1.h264 -new tmp.mov```
 - ```-add colr.mp4 -new tmp.mov```

Are you sure your GPAC version is up to date? I implemented this a few months ago (probably after 0.8.0 was tagged).

**Comment by microchip8** [comment]
OK. I'm using GPAC 0.8.0. I will try with GPAC 0.9.0 and report back

**Comment by rbouqueau** [comment]
Take a nightly instead: http://gpac.io/downloads/gpac-nightly-builds/

**Comment by microchip8** [comment]
There's no RPM there. I'm on openSUSE Leap 15.1

**Comment by microchip8** [comment]
OK, so I cloned GPAC from here and installed it. I still get the warning. I'm uploading a file called bt2020-out.mp4 to your dropbox that has color information (bt2020/PQ/bt2020nc)

When I try to output a MOV with MP4Box from git, I still get the "no color information preset". Inspecting the output.mov file with MediaInfo, it reports color/transfer/coefficients as BT709 and has additional fields ending in _Original with the original color info

Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
colour_primaries_Original                : BT.2020
transfer_characteristics_Original        : PQ
matrix_coefficients_Original             : BT.2020 non-constant

This is the command: MP4Box -add bt2020-out.mp4 -mpeg4 -new output.mov

**Comment by microchip8** [comment]
UPDATE

when I use colr=nclc,3,3,3 it output correct color info and does not add BT709

**Comment by rbouqueau** [comment]
> When I try to output a MOV with MP4Box from git, I still get the "no color information preset". 

That's because the initial MP4 does not contain the 'colr' box. MediaInfo gets this info from the raw bitstream. I'll se if I can improve this when I add the HDR SEIs parsing (so that the 'colr' box is properly filled from the bitstream information instead of default or manual values).

Note that we plan to improve HDR with GPAC before the end of the year. So I'm happy you are raising these issues :)

**Comment by microchip8** [comment]
OK, understood. Still want to ask:

How come when output is MP4, I do not get this warning and color info is transferred correctly. It only happens when output is MOV

**Comment by rbouqueau** [comment]
> I do not get this warning

It is a ProRes post-check warning. It doesn't happen in MP4.

> color info is transferred correctly

Because the ProRes warning leads MP4Box to add a 'colr' box with some defaults info. MediaInfo apparently stops here (there are contradictory information in the 'color' box and in the bitstream).

**Comment by jeanlf** [comment]
This should now work properly when adding a mp4 to a mov, color info is extracted from avc/hevc/av1 config when present.
Also note that `-colr` only sets a colr box in the track but does not change the bitstream. You need to use `:colorprim`and such to modify the bitstream.
