### ISSUE TITLE
extracting bitstream

### ISSUE THREAD

**Issue by landat** [gpac/gpac#1323]
Trying to demux sample mp4 for futher decoding and converting to cv::Mat gives me zero `bytesRead` in code modified from ['bmp4demux' ](https://github.com/gpac/gpac/blob/master/applications/testapps/bmp4demux/main.c) :

    #include <iostream>
    #include <boost/filesystem.hpp>
    #include <gpac/internal/isomedia_dev.h>
    #include <gpac/isomedia.h>
    #include <gpac/bitstream.h>
 
    void readVideo(const boost::filesystem::path& i_filename)
    {
        GF_ISOFile* movie = gf_isom_open(i_filename.string().c_str(), GF_ISOM_OPEN_READ, nullptr);
        GF_Err err_open = gf_isom_last_error(movie);
        if (err_open != 0)
          std::cout << "open err " << err_open << std::endl;
     
        GF_BitStream* bitstream = movie->movieFileMap->bs;
     
        u64 bufSize = gf_bs_get_size(bitstream);
        char* pDemuxedBuf = (char*)malloc(sizeof(char) * bufSize);
        memset(pDemuxedBuf, 0, sizeof(sizeof(char) * bufSize));
     
        u32 bytesRead = gf_bs_read_data(bitstream, pDemuxedBuf, bufSize);
        if (bytesRead == 0 || pDemuxedBuf == nullptr)
          std::cout << "nothing read\n";
     
        gf_isom_close(movie);
    }
     
    int main() {
    	readVideo("name.mp4");
    	return 0;
    }

Could you please tell me what am I doing wrong?

**Comment by rbouqueau** [comment]
> Could you please tell me what am I doing wrong?

You have modified the sample so much that I can't recognize it. Coming back to something closer to the original should improve your issue.

Please let us know here about your progress.

**Comment by landat** [comment]
I can't figure out where is the place in bmp4demux example where I could take demuxed bitstream with start codes for further decoding with, for example, openh264? Which function is responsible for demuxing? What is the purpose of while-cycle there?

**Comment by rbouqueau** [comment]
The line https://github.com/gpac/gpac/blob/master/applications/testapps/bmp4demux/main.c#L72 is responsible for getting the data back.

**Comment by landat** [comment]
Am I miss something that should be done with a sample before passing to decoder? I'm getting DECODING_STATE dsBitstreamError at line 64 in https://ideone.com/WoXUj2

**Comment by rbouqueau** [comment]
Ok, then you need GPAC to rewrite the start code. And probably also to inline descriptors before each RAP. Please add the following at line 33 of your example:
```gf_isom_set_nalu_extract_mode(movie, track_number, GF_ISOM_NALU_EXTRACT_INBAND_PS_FLAG | GF_ISOM_NALU_EXTRACT_ANNEXB_FLAG);```

Is it better for you?

**Comment by landat** [comment]
Thanks, this way data has been decoded, though I get image like that with this code https://ideone.com/xqx9Jb
Probably this issue is not related to gpac/openh264 but to my opencv part of code

![bgr](https://user-images.githubusercontent.com/20404682/67962191-d0d67200-fc0d-11e9-8072-381d72a9c0f0.jpg)
