### ISSUE TITLE
CBCS Encrypted Audio will not decrypt. senc without tenc box error assuming microsoft piff

### ISSUE THREAD

**Issue by zetabeam** [gpac/gpac#1324]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X ] I looked for a similar issue and couldn't find any.
- [X ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I am trying to decrypt an audio file encrypted with the cbcs encryption scheme, it is eac3 / ec3 audio. I do have the correct key as i can decrypt the AC3 and AAC tracks however the eac3 track will not decrypt. they are all cbcs, I tried mp4decrypt from the bento4 axiom tools and after decryption the track still remained encrypted with no change.

the audio is segmented so the moov / initialization is supplied separately and the moof data fragments are separate also. I will link the initialization segment with a few moof fragments alongside the key below. I merged the moov / initialization fragment by using the linux cat command: cat init.mp4 $(ls -vx segment-*.mp4) > encrypted_audio.mp4.

This returned the file to decrypt, i checked its boxes with mp4dump and they seemed fine and were similar to the AC3 initialization as they were encrypted using the same key. I tried merging the AC3 initialization with the EAC3 segments however the same thing happened, it would not decrypt. From there i tried using mp4box and i passed it the command: mp4box.exe -decrypt crypt.xml encrypted_audio.mp4 -out decrypted_audio.mp4 and it returned this warning and error:
[iso file] Unknown box type dec3 in parent enca
[iso file] senc box without tenc, assuming MS smooth+piff

        Error: I/O Error

the file isn't ism smooth or piff, it is known as mp41, mp42, isom and hlsf. the crypt.xml is also attached below. I don't know what is wrong with the file as i have tried everything i can, does anyone know what the issue could be?
crypt.xml looks like this:

<?xml version="1.0" encoding="UTF-8"?>

-<GPACDRM type="cbcs">

-<CrypTrack saiSavedBox="senc" first_IV="0x00000000000000000000000000000001" IV_size="16" IsEncrypted="1" trackID="1">

<key value="0x33b54799efeae9dd0771313eca516e24" KID="00000000000000000000000000000000"/>

</CrypTrack>

</GPACDRM>

audios - https://mega.nz/#!fmZBCQLB!wmzCi_ZFU6GicFIFWO3JT6kiK4uxaXHjekQjS_w1yXI
crypt.xml - https://mega.nz/#!SqRHlAaK!lGRO3wZVw-g1yAcOLkaZolqxuxbiQQLio-pD6iTwkPw

Is there anything that can be done to decrypt the audio file?

**Comment by jeanlf** [comment]
Thanks for the files. We had a few issue with ec-3 parsing, now fixed in 0.8.0. Please note that your segments use the wrong sample description index (2 instead of 1), I added a patch as well.
The decryption seems to work properly but I cannot decode the result, don't know if this is a problem with the key or the source bitstream. Could you check the result and close if OK ?
