### ISSUE TITLE
H264WriteMp4 File error in ios13

### ISSUE THREAD

**Issue by tongtianxing** [gpac/gpac#1325]
When I upgraded iOS13, I wrote MP4. This code suddenly had a problem, often caused by memory management problems. But it was very stable in ios12. I checked it and found that as long as I commented out WriteH264Nalu or WriteFrameToFile, There will be no problems. Can you help me see if there is memory management problem in these two pieces of code, if not, I can continue to find other places.
`
int CRecWriterMP4::WriteFrameToFile(unsigned char *pData, int nSize, bool bKey, long nTimeStamp)
{
    if (m_TimeStamp == -1 && bKey)
    {
        m_TimeStamp = nTimeStamp;
    }
    if (m_TimeStamp != -1)
    {
        GF_ISOSample *pISOSample = gf_isom_sample_new();
        pISOSample->IsRAP = (SAPType)bKey;
        pISOSample->dataLength = nSize;
        pISOSample->data = (char *)pData;
        pISOSample->DTS = nTimeStamp - m_TimeStamp;
        pISOSample->CTS_Offset = 0;
        GF_Err gferr = gf_isom_add_sample(m_pFile, m_nTrackID, m_nStreamIndex, pISOSample);
        if (gferr == -1)
        {
            pISOSample->DTS = nTimeStamp - m_TimeStamp + 1000 / (m_nFps * 2);
            gf_isom_add_sample(m_pFile, m_nTrackID, m_nStreamIndex, pISOSample);
        }
        pISOSample->data = NULL;
        pISOSample->dataLength = 0;
        gf_isom_sample_del(&pISOSample);
        pISOSample = NULL;
    }
    return TTX_S_OK;
}
int CRecWriterMP4::WriteH264Nalu(unsigned char **ppNaluData, int *pNaluLength)
{
    m_nTrackID = gf_isom_new_track(m_pFile, 0, GF_ISOM_MEDIA_VISUAL, 1000);
    gf_isom_set_track_enabled(m_pFile, m_nTrackID, 1);
    
    GF_AVCConfig *pstAVCConfig = gf_odf_avc_cfg_new();
    gf_isom_avc_config_new(m_pFile, m_nTrackID, pstAVCConfig, NULL, NULL, &m_nStreamIndex);
    gf_isom_set_visual_info(m_pFile, m_nTrackID, m_nStreamIndex, m_nWidth, m_nHeight);
    
    pstAVCConfig->configurationVersion = 1;
    pstAVCConfig->AVCProfileIndication = ppNaluData[AF_NALU_SPS][1];
    pstAVCConfig->profile_compatibility = ppNaluData[AF_NALU_SPS][2];
    pstAVCConfig->AVCLevelIndication = ppNaluData[AF_NALU_SPS][3];
    GF_AVCConfigSlot stAVCConfig[AF_NALU_MAX];
    memset(stAVCConfig, 0, sizeof(stAVCConfig));
    for (int i = 0; i < AF_NALU_MAX; i++)
    {
        if (i == AF_NALU_VPS)
            continue;
        
        stAVCConfig[i].size = pNaluLength[i];
        stAVCConfig[i].data = (char *)ppNaluData[i];
        if (i == AF_NALU_SPS)
        {
            gf_list_add(pstAVCConfig->sequenceParameterSets, &stAVCConfig[i]);
        }
        else if (i == AF_NALU_PPS)
        {
            gf_list_add(pstAVCConfig->pictureParameterSets, &stAVCConfig[i]);
        }
    }
    gf_isom_avc_config_update(m_pFile, m_nTrackID, 1, pstAVCConfig);
    pstAVCConfig->pictureParameterSets = NULL;
    pstAVCConfig->sequenceParameterSets = NULL;
    gf_odf_avc_cfg_del(pstAVCConfig);
    pstAVCConfig = NULL;
    return 0;
}
`

**Comment by rbouqueau** [comment]
Do you have a version of you code that works on a desktop and shows the issue? That would allow to use traditional tools to detect runtime errors.
