### ISSUE TITLE
M4A with chapters added by MP4Box does not show chapters in iTunes

### ISSUE THREAD

**Issue by robinbrinkler** [gpac/gpac#134]
Hi there,

When I add chapters to an M4A using MP4Box, the chapters do not display within iTunes. This behaviour happens when the file is progressively downloading / pseudo streaming and has not already been downloaded. I'm observing the behaviour on podcasts.

If playback is paused immediately, the chapters menu does normally appear. Otherwise, it may take a long time to appear or might not appear at all.

Here is a comparison of the output from the AtomicParsley -T command, for a file chaptered with MP4Box, versus one made with Garageband 6.0.5:

Garageband M4A

Atom ftyp @ 0 of size: 28, ends @ 28

Atom moov @ 28 of size: 1485207, ends @ 1485235

Atom mvhd @ 36 of size: 108, ends @ 144

Atom trak @ 144 of size: 801, ends @ 945

Atom tkhd @ 152 of size: 92, ends @ 244

Atom load @ 244 of size: 24, ends @ 268

~

Atom edts @ 268 of size: 36, ends @ 304

Atom elst @ 276 of size: 28, ends @ 304

Atom mdia @ 304 of size: 641, ends @ 945

Atom mdhd @ 312 of size: 32, ends @ 344

Atom hdlr @ 344 of size: 57, ends @ 401

Atom minf @ 401 of size: 544, ends @ 945

Atom gmhd @ 409 of size: 76, ends @ 485

Atom dinf @ 485 of size: 36, ends @ 521

Atom dref @ 493 of size: 28, ends @ 521

Atom url @ 509 of size: 12, ends @ 521

Atom stbl @ 521 of size: 424, ends @ 945

Atom stsd @ 529 of size: 80, ends @ 609

Atom tx3g @ 545 of size: 64, ends @ 609

Atom ftab @ 591 of size: 18, ends @ 609

Atom stts @ 609 of size: 144, ends @ 753

Atom stsc @ 753 of size: 28, ends @ 781

Atom stsz @ 781 of size: 84, ends @ 865

Atom stco @ 865 of size: 80, ends @ 945

Atom trak @ 945 of size: 903833, ends @ 904778

Atom tkhd @ 953 of size: 92, ends @ 1045

Atom edts @ 1045 of size: 36, ends @ 1081

Atom elst @ 1053 of size: 28, ends @ 1081

Atom tref @ 1081 of size: 24, ends @ 1105

Atom chap @ 1089 of size: 16, ends @ 1105

Atom mdia @ 1105 of size: 903673, ends @ 904778

Atom mdhd @ 1113 of size: 32, ends @ 1145

Atom hdlr @ 1145 of size: 58, ends @ 1203

Atom minf @ 1203 of size: 903575, ends @ 904778

Atom smhd @ 1211 of size: 16, ends @ 1227

Atom dinf @ 1227 of size: 36, ends @ 1263

Atom dref @ 1235 of size: 28, ends @ 1263

Atom url @ 1251 of size: 12, ends @ 1263

Atom stbl @ 1263 of size: 903515, ends @ 904778

Atom stsd @ 1271 of size: 103, ends @ 1374

Atom mp4a @ 1287 of size: 87, ends @ 1374

Atom esds @ 1323 of size: 51, ends @ 1374

Atom stts @ 1374 of size: 24, ends @ 1398

Atom stsc @ 1398 of size: 211660, ends @ 213058

Atom stsz @ 213058 of size: 621156, ends @ 834214

Atom stco @ 834214 of size: 70564, ends @ 904778

Atom trak @ 904778 of size: 500, ends @ 905278

Atom tkhd @ 904786 of size: 92, ends @ 904878

Atom edts @ 904878 of size: 36, ends @ 904914

Atom elst @ 904886 of size: 28, ends @ 904914

Atom mdia @ 904914 of size: 364, ends @ 905278

Atom mdhd @ 904922 of size: 32, ends @ 904954

Atom hdlr @ 904954 of size: 58, ends @ 905012

Atom minf @ 905012 of size: 266, ends @ 905278

Atom vmhd @ 905020 of size: 20, ends @ 905040

Atom dinf @ 905040 of size: 36, ends @ 905076

Atom dref @ 905048 of size: 28, ends @ 905076

Atom url @ 905064 of size: 12, ends @ 905076

Atom stbl @ 905076 of size: 202, ends @ 905278

Atom stsd @ 905084 of size: 102, ends @ 905186

Atom jpeg @ 905100 of size: 86, ends @ 905186

Atom stts @ 905186 of size: 24, ends @ 905210

Atom stsc @ 905210 of size: 28, ends @ 905238

Atom stsz @ 905238 of size: 20, ends @ 905258

Atom stco @ 905258 of size: 20, ends @ 905278

Atom udta @ 905278 of size: 579957, ends @ 1485235

Atom meta @ 905286 of size: 579949, ends @ 1485235

Atom hdlr @ 905298 of size: 32, ends @ 905330

Atom ilst @ 905330 of size: 577849, ends @ 1483179

Atom ©cmt @ 905338 of size: 130, ends @ 905468

Atom data @ 905346 of size: 122, ends @ 905468

Atom ©nam @ 905468 of size: 48, ends @ 905516

Atom data @ 905476 of size: 40, ends @ 905516

Atom ©ART @ 905516 of size: 29, ends @ 905545

Atom data @ 905524 of size: 21, ends @ 905545

Atom covr @ 905545 of size: 577594, ends @ 1483139

Atom data @ 905553 of size: 577586, ends @ 1483139

Atom ©too @ 1483139 of size: 40, ends @ 1483179

Atom data @ 1483147 of size: 32, ends @ 1483179

Atom free @ 1483179 of size: 2056, ends @ 1485235

Atom free @ 1485235 of size: 8, ends @ 1485243

Atom free @ 1485243 of size: 8, ends @ 1485251

Atom mdat @ 1485251 of size: 146012301, ends @ 147497552

~ denotes an unknown atom

­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­

Total size: 147497552 bytes; 82 atoms total. AtomicParsley from svn built on Mar 25 2010 (utf8)

Media data: 146012301 bytes; 1485251 bytes all other atoms (1.007% atom overhead).

Total free atom space: 2072 bytes; 0.001% waste. Padding available: 2072 bytes.

­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­

Fraunhofer / MP4Box / AtomicParsley M4A

Atom ftyp @ 0 of size: 36, ends @ 36

Atom moov @ 36 of size: 2322651, ends @ 2322687

Atom mvhd @ 44 of size: 108, ends @ 152

Atom iods @ 152 of size: 21, ends @ 173

Atom trak @ 173 of size: 651264, ends @ 651437

Atom tkhd @ 181 of size: 92, ends @ 273

Atom tref @ 273 of size: 24, ends @ 297

Atom chap @ 281 of size: 16, ends @ 297

Atom edts @ 297 of size: 36, ends @ 333

Atom elst @ 305 of size: 28, ends @ 333

Atom mdia @ 333 of size: 651104, ends @ 651437

Atom mdhd @ 341 of size: 32, ends @ 373

Atom hdlr @ 373 of size: 45, ends @ 418

Atom minf @ 418 of size: 651019, ends @ 651437

Atom smhd @ 426 of size: 16, ends @ 442

Atom dinf @ 442 of size: 36, ends @ 478

Atom dref @ 450 of size: 28, ends @ 478

Atom url @ 466 of size: 12, ends @ 478

Atom stbl @ 478 of size: 650959, ends @ 651437

Atom stsd @ 486 of size: 91, ends @ 577

Atom mp4a @ 502 of size: 75, ends @ 577

Atom esds @ 538 of size: 39, ends @ 577

Atom stts @ 577 of size: 32, ends @ 609

Atom stsc @ 609 of size: 64, ends @ 673

Atom stsz @ 673 of size: 621164, ends @ 621837

Atom stco @ 621837 of size: 29600, ends @ 651437

Atom trak @ 651437 of size: 714, ends @ 652151

Atom tkhd @ 651445 of size: 92, ends @ 651537

Atom mdia @ 651537 of size: 614, ends @ 652151

Atom mdhd @ 651545 of size: 32, ends @ 651577

Atom hdlr @ 651577 of size: 74, ends @ 651651

Atom minf @ 651651 of size: 500, ends @ 652151

Atom nmhd @ 651659 of size: 12, ends @ 651671

Atom dinf @ 651671 of size: 36, ends @ 651707

Atom dref @ 651679 of size: 28, ends @ 651707

Atom url @ 651695 of size: 12, ends @ 651707

Atom stbl @ 651707 of size: 444, ends @ 652151

Atom stsd @ 651715 of size: 80, ends @ 651795

Atom tx3g @ 651731 of size: 64, ends @ 651795

Atom ftab @ 651777 of size: 18, ends @ 651795

Atom stts @ 651795 of size: 144, ends @ 651939

Atom stsc @ 651939 of size: 52, ends @ 651991

Atom stsz @ 651991 of size: 84, ends @ 652075

Atom stco @ 652075 of size: 76, ends @ 652151

Atom trak @ 652151 of size: 500, ends @ 652651

Atom tkhd @ 652159 of size: 92, ends @ 652251

Atom mdia @ 652251 of size: 400, ends @ 652651

Atom mdhd @ 652259 of size: 32, ends @ 652291

Atom hdlr @ 652291 of size: 94, ends @ 652385

Atom minf @ 652385 of size: 266, ends @ 652651

Atom vmhd @ 652393 of size: 20, ends @ 652413

Atom dinf @ 652413 of size: 36, ends @ 652449

Atom dref @ 652421 of size: 28, ends @ 652449

Atom url @ 652437 of size: 12, ends @ 652449

Atom stbl @ 652449 of size: 202, ends @ 652651

Atom stsd @ 652457 of size: 102, ends @ 652559

Atom jpeg @ 652473 of size: 86, ends @ 652559

Atom stts @ 652559 of size: 24, ends @ 652583

Atom stsc @ 652583 of size: 28, ends @ 652611

Atom stsz @ 652611 of size: 20, ends @ 652631

Atom stco @ 652631 of size: 20, ends @ 652651

Atom udta @ 652651 of size: 1670036, ends @ 2322687

Atom meta @ 652659 of size: 1670028, ends @ 2322687

Atom hdlr @ 652671 of size: 33, ends @ 652704

Atom free @ 652704 of size: 2000, ends @ 654704

Atom ilst @ 654704 of size: 1667983, ends @ 2322687

Atom ©nam @ 654712 of size: 48, ends @ 654760

Atom data @ 654720 of size: 40, ends @ 654760

Atom ©too @ 654760 of size: 37, ends @ 654797

Atom data @ 654768 of size: 29, ends @ 654797

Atom ©ART @ 654797 of size: 29, ends @ 654826

Atom data @ 654805 of size: 21, ends @ 654826

Atom rtng @ 654826 of size: 25, ends @ 654851

Atom data @ 654834 of size: 17, ends @ 654851

Atom ©cmt @ 654851 of size: 130, ends @ 654981

Atom data @ 654859 of size: 122, ends @ 654981

Atom covr @ 654981 of size: 1667706, ends @ 2322687

Atom data @ 654989 of size: 1667698, ends @ 2322687

Atom free @ 2322687 of size: 48, ends @ 2322735

Atom mdat @ 2322735 of size: 145897902, ends @ 148220637

Atom free @ 148220637 of size: 8, ends @ 148220645

Atom free @ 148220645 of size: 59, ends @ 148220704

­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­

Total size: 148220704 bytes; 81 atoms total. AtomicParsley from svn built on Mar 25 2010 (utf8)

Media data: 145897902 bytes; 2322802 bytes all other atoms (1.567% atom overhead).

Total free atom space: 2115 bytes; 0.001% waste. Padding available: 2048 bytes.

­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­

**Comment by robinbrinkler** [comment]
This short video demonstrates the behaviour:
https://dl.dropboxusercontent.com/u/28171300/Work/iTunes/bug%20report%20chapters.mp4

**Comment by jeanlf** [comment]
hmm I can see a 'load' box in the track which could be responsible for the described behaviour - cf QT spec:

https://developer.apple.com/library/mac/documentation/QuickTime/QTFF/QTFFChap2/qtff2.html#//apple_ref/doc/uid/TP40000939-CH204-32983

I'll see what I can do about this

**Comment by robinbrinkler** [comment]
Thanks for your email Jean. I really appreciate your time in looking at
this.

The load box seems to be different but present in files chaptered by both
Garageband and Rogue Amoeba Fission. Fission's files seem to take longer to
buffer however.

Interestingly removing the load atom completely with AtomicParsley, and
editing the values in a Hex Editor (hopefully being careful not to change
offset) seemed to make no difference.

I welcome a second opinion though!

I have some notes from my last experiments and will send them over if I
think anything could be of use. :)

Best regards

Robin

On Tuesday, 30 June 2015, jeanlf <notifications@github.com> wrote:

> hmm I can see a 'load' box in the track which could be responsible for the
> described behaviour - cf QT spec:
>
>
> https://developer.apple.com/library/mac/documentation/QuickTime/QTFF/QTFFChap2/qtff2.html#//apple_ref/doc/uid/TP40000939-CH204-32983
>
> I'll see what I can do about this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gpac/gpac/issues/134#issuecomment-117215375>.
>


-- 
Robin Brinkler

*Podtree*
*podtree.com <http://podtree.com>*

**Comment by robinbrinkler** [comment]
Hi Jean,

I have included my notes below:

Found that Rogue Amoeba's Fission 2.2.4 can re-save an M4A already
> chaptered with MP4Box and AtomicParsley. It then makes the chapters load up
> first time in iTunes, desktop client.
> The chapters work fine in the Podcasts app on iPad 2 Mini, iOS 8.3 (latest
> as of 21st June 2015).
> The general time to seek the file initially is always much slower, by
> 10-20 seconds on Fission. Files chaptered with Garageband 6.0.5 load / seek
> to buffered audio within seconds, much quicker than Fission file.


> qtfaststart python script seemed to make a broken file, and one that
> Fission could not read.
> It had been run with the -e parameter.


I ran some tests, changing values of the load box with a hex editor. More
tests are on this test podcast feed:

http://podtree.com/test/feed/TEST1%201.xml

I tried changing the load contents of a file saved with Fission, to reflect
those of the load box content generated by Garageband and it seemed to make
no difference. Having deleted the atom in a file chaptered by Garageband,
it still works (progressive stream) and chapters load as normal.

At the moment I am writing AppleScript to control GarageBand as a stop gap
solution, then will keep working on a solution which doesn't need
GarageBand, hopefully!

Cheers

Robin


On 30 June 2015 at 17:39, Robin Brinkler <robin@neutroncore.com> wrote:

> Thanks for your email Jean. I really appreciate your time in looking at
> this.
>
> The load box seems to be different but present in files chaptered by both
> Garageband and Rogue Amoeba Fission. Fission's files seem to take longer to
> buffer however.
>
> Interestingly removing the load atom completely with AtomicParsley, and
> editing the values in a Hex Editor (hopefully being careful not to change
> offset) seemed to make no difference.
>
> I welcome a second opinion though!
>
> I have some notes from my last experiments and will send them over if I
> think anything could be of use. :)
>
> Best regards
>
> Robin
>
>
> On Tuesday, 30 June 2015, jeanlf <notifications@github.com> wrote:
>
>> hmm I can see a 'load' box in the track which could be responsible for
>> the described behaviour - cf QT spec:
>>
>>
>> https://developer.apple.com/library/mac/documentation/QuickTime/QTFF/QTFFChap2/qtff2.html#//apple_ref/doc/uid/TP40000939-CH204-32983
>>
>> I'll see what I can do about this
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/gpac/gpac/issues/134#issuecomment-117215375>.
>>
>
>
> --
> Robin Brinkler
>
> *Podtree*
> *podtree.com <http://podtree.com>*
>
>
>
>
>


-- 
Robin Brinkler

*Podtree*
*podtree.com <http://podtree.com>*

**Comment by jeanlf** [comment]
We'll need a working and a broken sample files to figure this out, if this is still the case - chaptering is working fine in QT with current version. I'm closing this until we get more data/reports.
