### ISSUE TITLE
Best way to prepare videos for dash

### ISSUE THREAD

**Issue by chanof** [gpac/gpac#1349]
Hi there, may someone help me to understand which is the best way to automate the video coding to get the right format, multiple video concatenation and the right duration to stream it without issues with mp4box? Currently im using ffmpeg with bash shell script that encode, concat and reduce the final video duration to get even second lenght to be able to stream a loop.
thanks you in advance!

**Comment by jeanlf** [comment]
That's a bit too vague, please provide more description of what you are doing (command lines at least is a good start) and what kind of issues are you experiencing, and reopen.
