### ISSUE TITLE
remux h264 and AAC to mp4 using GPAC lib

### ISSUE THREAD

**Issue by apleton** [gpac/gpac#1351]
Hello. 
I would like to pack h264 and AAC audio streams into a mp4 container using mp4box library (not CLI). I can't find any documentation on this and the comments found in the huge codebase are not really explicit. The only thing I found is the project https://github.com/Keemotion/TS2MP4 but it uses an old version of Mp4Box and is not maintained anymore. 

Any help on how to use the Demuxer/muxer of mp4Box would be great.

**Comment by jeanlf** [comment]
I would suggest using the [media importer](https://doxygen.gpac.io/group__mimp__grp.html) functions, as the API is the same between 0.8.0 and 0.9.0

We're doing our best to improve the doc, but it's a long task where help is always welcome :)
