### ISSUE TITLE
Query about merging and display two tiled-based HEVC streams with different resolution

### ISSUE THREAD

**Issue by peipeiguo** [gpac/gpac#1353]
Hello, whether GPAC support merging and display two **tiled-based HEVC streams** with **different resolution**? If not, is there any plan to support it in future? 
Thanks!

**Comment by jeanlf** [comment]
You need 0.9.0 for this, and make sure your encoding configurations are the same on both streams. Check the testsuite example here:
https://github.com/gpac/testsuite/blob/filters/scripts/hevcsplit.sh

**Comment by peipeiguo** [comment]
@jeanlf Hi Jean, I want to run the testcase, but I can not access the website to download test medias ("http://download.tsi.telecom-paristech.fr/gpac/gpac_test_suite/resources/media/"). It seems something wrong with the website. Is there anyway to get the test media files?

```
root@ubuntu:~/src/gpac_public/testsuite/external_media# wget -q -m -nH --no-parent --cut-dirs=4 --reject "*.gif" --reject "index.html*" --restrict-file-names=nocontrol "http://download.tsi.telecom-paristech.fr/gpac/gpac_test_suite/resources/media/"
root@ubuntu:~/src/gpac_public/testsuite/external_media# ls -l
total 0
root@ubuntu:~/src/gpac_public/testsuite/external_media#
```

**Comment by aureliendavid** [comment]
see https://github.com/gpac/testsuite/issues/1
