### ISSUE TITLE
How to make gpac0.9.0 use openhevc decoder

### ISSUE THREAD

**Issue by beibeii** [gpac/gpac#1354]
Gpac0.9.0 version uses ffmpeg decoder by default, I want to use openhevc, please ask how to do it, thank you

I want to play video with MP4Client, use openhevc to decode

**Comment by aureliendavid** [comment]
you can use the `blacklist` option to prevent from using ffmpeg (see https://github.com/gpac/gpac/wiki/core_options) 

something like `-blacklist=ffdec` should do it

**Comment by beibeii** [comment]
thank you
