### ISSUE TITLE
What's the core difference between tileagg and hevcmerge in GPAC0.9

### ISSUE THREAD

**Issue by Wilson-Ian** [gpac/gpac#1356]
Hi experts,  I newly read the code in gpac 0.9 branch and noticed two useful filters : tileagg and hevcmerge.  

Would it be possible to provide more info about their differences?  
From the WIKI document I can tell tileagg is to aggregate two tile streams to one stream; and hevcmerge is to merge more PIDs into single PID.

From the  code I can see the tileagg mainly rewrite  the NAL without changing the PS info, while hevcmerge did more validations and works in SPS/PPS etc to make sure same DTS etc.  It seems hevcmerge needs to  recalculate the height and width after the merge of  the tiles, while tileagg doesn't care the position info of each tile stream, but why tileagg doesn't care, if more tile streams are aggregated to one stream, the spatial info still needs to be considered in the final stream so that the stream can present the whole picture after the aggregation of tile streams as I understood.  But I'm sure I must missed some points or misunderstood.

From the test suite,  I can see the tileagg is used to aggregate tile-based dash-srd; and hevcmerge is to merge more hevc tilebased files to one integral file.

Could anyone help give a hint what the core difference between them, or what the core scenarios of them?   Thanks very much!

Wilson

**Comment by jeanlf** [comment]
Doc needs a bit of clarification I agree.

- tileagg is a very basic filter aggregating tile tracks (hvt1 in ISOBMFF) into a single HEVC bitstream. It does not modify the input NALUs at all, it's just designed to move from N tile hevc streams to 1 hevc stream, assuming the tiles all come from the same encoding (same SPS/PPS/VPS). The main use case is playback of a tiled ISOBMFF file, where all tiles come from the same source MCTS bitstream. This filter will not be able to merge streams coming from different sources (with the exception of sources with exactly the same SPS/PPS/VPS config but different rates)

- hevcmerge is a more complex filter: it takes N HEVC input streams (hvc1/hev1 in ISOBMFF) originally encoded with proper motion constraints and potentially slightly different encoding configurations; it performs a layout of the tiles based on filter parameters, recomputes a SPS/PPS for that tile grid layout and rewrite all slice headers to match the PPS tiling. The goal is to be able to decode with a single decoder a set of tiles with different resolutions/QPs, for later consumption by the composition layer (eg player). The main use case here is obviously viewport-dependent 360 video streaming in DASH.

If that's clear enough, I'll add this to the respective filter documentation.
