### ISSUE TITLE
gpac-0.9.0 Unable to play mpd

### ISSUE THREAD

**Issue by beibeii** [gpac/gpac#1361]
I use the following command to make a video with the same resolution and different bitrate as mpd, but I can't play it with MP4client, black screen，Where am I doing it incorrectly?

Gpac0.8.0 can work, but 0.9.0 does not work.

1. MP4Box -add 2.hevc:split_tiles -new 2.mp4
2. MP4Box -add 8.hevc:split_tiles -new 8.mp4
3. MP4Box -dash 5000 -profile live 2.mp4 8.mp4 -out 2_8.mpd

**Comment by beibeii** [comment]
Make mpd with MP4 with different bitrate
Mpd file made using MP4box0.8.0 is like picture 1. An AdaptationSet contains two representations, which correspond to two bit rates. MP4client that uses 0.8.0 can play， but mpd made with MP4box0.9.0, such as picture 2 one AdaptationSet contains only a Representation and cannot be played using mp4client of 0.9.0
![image](https://user-images.githubusercontent.com/14730487/69604553-c2d31000-1058-11ea-939f-cc89708e6733.png)
![image](https://user-images.githubusercontent.com/14730487/69604827-7d631280-1059-11ea-8e52-07578d5a0bf0.png)

**Comment by jeanlf** [comment]
fixed some time ago
