### ISSUE TITLE
MP4Box generates all segments but unable to play on dash.js

### ISSUE THREAD

**Issue by mike1011** [gpac/gpac#1362]
I am using MP4Box and FFMPEG to encode and generate DASH compatible video to be played on a commercial website.It uses S3(where all my files including init.mp4 and vv_1.mp4, vv_2.mp4 are stored) and CloudFront for asset hosting of videos. For videos encoded using FFMPEG(mp4/webm), the video player is able to play seamlessly using bitmovin player/dashjs.But when i try to dashify the files using MP4Box, it never works and giving the error shown below using dashjs, same error is being given by bitmovin for my mpd file here - https://d3mjcniiaj83ix.cloudfront.net/video/checking-and-go/video.mpd

**MY MPD FILE -** 
```

<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.8.0-revUNKNOWN_REV  at 2019-11-28T00:49:13.069Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H0M37.542S" maxSegmentDuration="PT0H0M5.542S" profiles="urn:mpeg:dash:profile:isoff-live:2011,http://dashif.org/guidelines/dash264">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>1175</Title>
 </ProgramInformation>

 <Period duration="PT0H0M37.542S">
  <AdaptationSet segmentAlignment="true" maxWidth="1280" maxHeight="720" maxFrameRate="24" par="16:9" lang="und" startWithSAP="1">
   <SegmentTemplate media="vv_$Number$.mp4" initialization="vv_init.mp4" timescale="24000" startNumber="1" duration="96000"/>
   <Representation id="1" mimeType="video/mp4" codecs="avc1.4D401F" width="1280" height="720" frameRate="24" sar="1:1" bandwidth="2400176">
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" lang="und" startWithSAP="1">
   <SegmentTemplate media="vv_$Number$.mp4" initialization="vv_init.mp4" timescale="48000" startNumber="1" duration="192000"/>
   <Representation id="2" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="48000" bandwidth="2278">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```
**ERROR GIVEN BY BITMOVIN PLAYER -** 

`"CHUNK_DEMUXER_ERROR_APPEND_FAILED: Failure parsing MP4: Detected unfragmented MP4. Media Source Extensions require ISO BMFF moov to contain mvex to indicate that Movie Fragments are to be expected."`

**ERRORS GIVEN BY DASH.JS-** 

```
////copying errors from console(f12)
SourceBufferSink error video 
getAllBufferRanges exception: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source. 
Video Element Error: MEDIA_ERR_SRC_NOT_SUPPORTED (CHUNK_DEMUXER_ERROR_APPEND_FAILED: Failure parsing MP4: Detected unfragmented MP4. Media Source Extensions require ISO BMFF moov to contain mvex to indicate that Movie Fragments are to be expected.) 
```
 
**FFMPEG AND MP4Box versions**

```
ubuntu:~/environment/test (new_layout) $ MP4Box -version
MP4Box - GPAC version 0.8.0-revUNKNOWN_REV
(c) Telecom ParisTech 2000-2018 - Licence LGPL v2
GPAC Configuration: 
Features: GPAC_64_BITS GPAC_HAS_SSL GPAC_DISABLE_3D 
ubuntu:~/environment/test (new_layout) $ ffmpeg -version
ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
```

To Encode - 

I have referred the [bitmovin page to dashify using MP4Box ](https://bitmovin.com/mp4box-dash-content-generation-x264/)to get some help - 

**My Commands**

```
  ###removed dynamic parameters to simplify 
  `MP4Box -dash 4000 -frag 4000 -profile dashavc264:live -subsegs-per-sidx 4 -mpd-title #{model.id} -segment-ext mp4 -segment-name vv_ -rap /tmp/dashing/test/output_2400k.mp4 /tmp/dashing/test/video_audio.mp4#audio -out /tmp/dashing/test/video.mpd`
```
The above command generates all files mpd, all segments like vv_1.mp4...vv_4.mp4, vv_init.mp4, video_audio.mp4.

I also get the audio file before dashifying using MP4Box - 

``ffmpeg -y -i input_file_path -c:a aac -b:a 128k -vn /some/path `

What is that my mpd file is missing OR Am i using some wrong commands or missing some parameters to use during dashifying?

Kindly help me or let me know any suggestions.

**Comment by jeanlf** [comment]
Something is wrong with the segment name you use, you end up having the same name in both media - could you try without the `-segment-name` and check if that solves the issue?

**Comment by mike1011** [comment]
Hi @jeanlf , Thanks for the quick response. I tried to dashify by removing `-segment-name`, but still its giving me the same error..

**My Command to dashify(modified)**
`
`MP4Box -dash 4000 -frag 4000 -profile dashavc264:live -subsegs-per-sidx 4 -mpd-title test -segment-ext mp4 -rap /tmp/dashing/test/output_2400k.mp4 #{Rails.root}/tmp/dashing/#{model.id}/video_audio.mp4#audio -out /tmp/dashing/test/video.mpd``

`MY MPD FILE`
```

<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.8.0-revUNKNOWN_REV  at 2019-11-28T10:10:59.510Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H0M14.042S" maxSegmentDuration="PT0H0M4.011S" profiles="urn:mpeg:dash:profile:isoff-live:2011,http://dashif.org/guidelines/dash264">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>1177</Title>
 </ProgramInformation>

 <Period duration="PT0H0M14.042S">
  <AdaptationSet segmentAlignment="true" maxWidth="1280" maxHeight="720" maxFrameRate="24" par="16:9" lang="und" startWithSAP="1">
   <SegmentTemplate media="output_2400k_dash$Number$.mp4" initialization="output_2400k_dashinit.mp4" timescale="24000" startNumber="1" duration="96000"/>
   <Representation id="1" mimeType="video/mp4" codecs="avc1.4D401F" width="1280" height="720" frameRate="24" sar="1:1" bandwidth="2013064">
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" lang="und" startWithSAP="1">
   <SegmentTemplate media="video_audio_dash$Number$.mp4" initialization="video_audio_dashinit.mp4" timescale="48000" startNumber="1" duration="192000"/>
   <Representation id="2" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="48000" bandwidth="128140">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="6"/>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```

**Console log**

`"CHUNK_DEMUXER_ERROR_APPEND_FAILED: Failure parsing MP4: Detected unfragmented MP4. Media Source Extensions require ISO BMFF moov to contain mvex to indicate that Movie Fragments are to be expected."`

**observation using network tab in browser console(f12)**
```
video.mpd - 200
output_2400k_dashinit.mp4 - 200
video_audio_dashinit.mp4 - 200
video_audio_dash1.mp4 - 200
output_2400k_dash1.mp4 - 200
video_audio_dash2.mp4 - cancelled

```
Let me know if these details were any help to you.

**Comment by jeanlf** [comment]
also try using m4s rather than mp4 for segment extensions. If still not working, could you upload the generated init seg and first 2 audio and video segments?

**Comment by mike1011** [comment]
Hi @jeanlf , i removed segment extensions, however, i am still getting the same errors and console logs as mentioned above.Moreover, as yourequested, i am sharing all the audio/video segments generated and indicated in mpd file.

Sharing my Gdrive link with all the uploaded files - https://drive.google.com/file/d/1Tv-U-EFBXh0an9UrhNXS12jAovLWWGCn/view?usp=sharing

Let me know if you need any more details.
Thanks.

**Comment by mike1011** [comment]
Hi @jeanlf , Let me know if you got chance to go through the files and kindly let me know if you have any suggestions.

**Comment by BucherTomas** [comment]
@mike1011 there appears to be some mismatch of your fragmented content with your previous attempts maybe as your init segments output_2400k_dashinit.mp4 and video_audio_dashinit.mp4 are in fact binary copies of the input files output_2400k.mp4 and video_audio.mp4, respectively. That is why the browser complains that the content is in fact unfragmented.

I would suggest deleting the contents of your  `/tmp/dashing/test/video.mpd` directory and running the last used command again. Check afterwards that the init segments then only have a couple of hundred bytes as they should.
