### ISSUE TITLE
Impossible to build MP4Box.exe from the "Filters" branch

### ISSUE THREAD

**Issue by jalba69** [gpac/gpac#1363]
Hello,

trying to build the gpac_mp4box_mini.sln (release>  x64) from the filters branch using Visual Studio 2017 and having this error at the end :

> 1>libgpac.vcxproj -> H:\gpac\build\msvc14\../../bin/x64\Release - MP4Box_only/libgpac_static.lib
> 1>Génération du projet "libgpac.vcxproj" terminée.
> 2>------ Début de la génération : Projet : mp4box, Configuration : Release - MP4Box_only x64 ------
> 2>filedump.c
> 2>fileimport.c
> 2>live.c
> 2>Génération de code en cours...
> 2>main.c
> 2>libgpac_static.lib(isom_store.obj) : error LNK2019: symbole externe non résolu gf_gz_compress_payload_ex référencé dans la fonction gf_isom_write_compressed_box
> 2>../../bin/x64\Release - MP4Box_only/mp4box.exe : fatal error LNK1120: 1 externes non résolus
> 2>Génération du projet "mp4box.vcxproj" terminée -- ÉCHEC.
> ========== Génération : 1 a réussi, 1 a échoué, 0 mis à jour, 0 a été ignoré ==========

the .lib file seems to be created but the .exe fails, note sure if it's on my end or something incorrect in the code files and as there is no binaires to download from the site for now...

Also note that doing the following :
\>git clone -b filters https://github.com/gpac/gpac.git
Or downloading the zip file from the filter branch,
leaves the "testsuite @ 3e45092" folder empty, the local folder created from git command or the folder inside the downloaded zip is named only "testsuite" and empty, no files and no folders inside, not sure if the @ symbol breaks something here or if it's something else.
Probably not related to the build problem but better report it.

Wanted to play a bit with heic and see if the reframer for heic had been modified since this discussion among other things.
https://github.com/gpac/gpac/issues/1021#issuecomment-510362157

Thanks a lot

**Comment by rbouqueau** [comment]
Thanks for reporting! Your build issue should be fixed.

**Comment by jalba69** [comment]
Thank you, 
it builds now but the resulting exe seems to have issues.

I previously compiled using VS2017, since my bug report I installed VS2019 and removed VS2017 so I'm not sure if it's VS2019 messing up things or if it's the exe that have issues.

For example trying all those commands crash mp4box with message exe has stopped to work : 
```
MP4Box -add-image "H:\test.hevc":@@reframer:frames="1,251,284" -ab heic -new "H:\test1.heic" > crash
MP4Box -add-image "H:\test.hevc":primary:name="Frame1" -ab heic -new "H:\image.heic" > crash
MP4Box -add-image test.hevc:primary -ab heic -new image.heic > crash
MP4Box -add "H:\test.hevc":forcesync:@@reframer:frames=1,251,284 -new "H:\test1.heic" > crash
mp4box -itags cover="test.jpg" -add "test.hevc" -new Result.mp4 > crash
mp4box -add "test.hevc" -new Result.mp4 > crash
mp4box -add "test.264" -new Result.mp4 > crash
mp4box -add "test.264" Result.mp4 > crash
mp4box -add test.264 Result.mp4 > crash
```

This works as usual : 
```
mp4box -info file.mp4 > works
MP4box -dump-cover -dump-chap-ogg -raw * -srt * "H:\test.mp4" > works
```

Also the Mp4Box -h command gives a weird formatted list as result : 
```
MP4Box [option] input [option]


←[32mGeneral Options:←[0m

←[32m-h←[0m (string):                             print help
        * ←[33mgeneral←[0m: general options help
        * ←[33mhint←[0m: hinting options help
        * ←[33mdash←[0m: DASH segmenter help
        * ←[33mimport←[0m: import options help
        * ←[33mencode←[0m: encode options help
        * ←[33mmeta←[0m: meta handling options help
        * ←[33mextract←[0m: extraction options help
        * ←[33mdump←[0m: dump options help
        * ←[33mswf←[0m: Flash (SWF) options help
        * ←[33mcrypt←[0m: ISMA E&A options help
        * ←[33mformat←[0m: supported formats help
        * ←[33mlive←[0m: BIFS streamer help
        * ←[33matsc←[0m: ATSC3 reader help
        * ←[33mcore←[0m: libgpac core options
        * ←[33mall←[0m: all options are printed

←[32m-nodes←[0m:                                  list supported MPEG4 nodes
←[32m-node←[0m (string):                          get given MPEG4 node syntax and QP infolist
←[32m-xnodes←[0m:                                 list supported X3D nodes
←[32m-xnode←[0m (string):                         get given X3D node syntax
←[32m-snodes←[0m:                                 list supported SVG nodes
←[32m-languages←[0m:                              list supported ISO 639 languages
←[32m-boxes←[0m:                                  list all supported ISOBMF boxes and their syntax
←[32m-fstat←[0m:                                  print filter session statistics (import/export/encrypt/decrypt/dashing)
←[32m-fgraph←[0m:                                 print filter session graph (import/export/encrypt/decrypt/dashing)
←[32m-v←[0m:                                      verbose mode
←[32m-version←[0m:                                get build version
←[32m---←[0m  INPUT:                              escape option if INPUT starts with 
```

Might try to install again VS2017 in a couple of days to see if it's the switch from 2017 to 2019 versions causing the problems but it's a bit a pain in the rear to get it up again :/ 

Thank you.

**Comment by jalba69** [comment]
Well scratch that, 

redownloaed the filters branch files, compiled it gain and no more issues using mp4box, ( -h command still have weird displayed results but was there before so ) 

not sure what went wrong before, maybe i should wait after 8am and a few coffees to start messing with this.

Sorry for the false alarm on previous post.

**Comment by jeanlf** [comment]
regarding the help formatting, it looks like prompt color mode doesn't work or prompt type is not properly detected. Which prompt & windows version are you using ?

**Comment by jalba69** [comment]
Hi,

using the cmd prompt from win7, 

The following screenshot shows the formatting with the 0.8 version then the filters 0.9 version with strange formatting : 
 
![2019-12-05_163520_cr](https://user-images.githubusercontent.com/15131985/70250044-936d8300-177d-11ea-85c8-47ca9e61f43a.jpg)

Thank you.

**Comment by jeanlf** [comment]
thanks - we'll check on win7 what is happening

**Comment by jalba69** [comment]
Thank you, not a big deal so no need to hurry with this,

Thanks again for all :)
