### ISSUE TITLE
No initialization specified in mpd when multiple hevc-tiles representation

### ISSUE THREAD

**Issue by MinhaoTang** [gpac/gpac#1365]
Hi,

I was trying to use mp4box to generate a dash descriptor with multiple hevc-tiles representations.
The command line I used was:
`mp4box.exe -dash 1000 -rap -frag-rap -profile live -out test/test.mpd high_quality.mp4 low_quality.mp4`
There is no initialization information in each hvt1 representation.

**Comment by jeanlf** [comment]
this is normal, they depend on the base tile track (type hvc2) and inherit its init segment
