### ISSUE TITLE
change the position of the tile

### ISSUE THREAD

**Issue by beibeii** [gpac/gpac#1367]
I use MP4client to play the mpd file and want to change the position of the tile, but modify the EssentialProperty and value of the mpd file does not work. What should I do? Thank you
![image](https://user-images.githubusercontent.com/14730487/70985945-f5bc7100-20f7-11ea-88d2-3ef1ee1170a1.png)

**Comment by jeanlf** [comment]
you are using hvt1 tile tracks, you cannot move tiles around in this mode their position is frozen in the bitstream. You will need to rewrite the tile tracks as regular hevc tracks for this. If you need a single decoder output for the video in your MPD, you will need to insert an hevcmerge filter after the dash demuxer.
