### ISSUE TITLE
DASH MPD: characters are never escaped which leads to non-compliant XMLs

### ISSUE THREAD

**Issue by rayfoss** [gpac/gpac#1368]
I found a stray broken MPD... because the path to it has an ampersand and the program info element inserts the path unfiltered.

```
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>dash/1 T&D Systems Overview/video.mpd generated by GPAC</Title>
 </ProgramInformation>
```

Workaround: `-mpd-title "TD PowerSkills Training Video"`

https://github.com/gpac/gpac/blob/451c1a87af5c99b98bb7d1b30812517d4c99e9f9/src/media_tools/dash_segmenter.c#L5639

**Comment by rbouqueau** [comment]
Hi, thanks for reporting. This is indeed an important limitation. I'm going to rename the issue and I hope one of us can have a look before the next release.

**Comment by aureliendavid** [comment]
I'll try to take a look at it

**Comment by aureliendavid** [comment]
should be ok now, see the discussion in #1369
