### ISSUE TITLE
one bug: dashin filter always set group 0 (adaptation set 0) as the udata of opid

### ISSUE THREAD

**Issue by peipeiguo** [gpac/gpac#1371]
Hi all,

In dashin filter `dashdmx_configure_pid` function, when figure out group for input pid, it always set group 0 (adaptation set 0) as the udata of opid. It call `dashdmx_group_idx_from_pid` function which only return its the parent's index. 

https://github.com/gpac/gpac/blob/1de1f8d3b53f88bf0228f53f74cad6221701f1bd/src/filters/dmx_dash.c#L981

https://github.com/gpac/gpac/blob/1de1f8d3b53f88bf0228f53f74cad6221701f1bd/src/filters/dmx_dash.c#L693

I think it is a bug. `dashdmx_configure_pid` should set corresponding group index of each input pid. `dashdmx_group_idx_from_pid` function should return group index for the pid not its parent. 

Whether my understand is correct or not?
Thanks.

**Comment by jeanlf** [comment]
no, the code is correct (although a bit tricky), it assigns to the output pid's udta the corresponding dash group (which is not always 0), and assigns the output pid to the  input pid's udta.
