### ISSUE TITLE
Is there a way to download only the AdaptationSets in the field of view while playing?

### ISSUE THREAD

**Issue by LeoKingLong** [gpac/gpac#1372]
In gpac-filter branch，if I put 10 AdaptationSets in one mpd file , Is there a way to download only the AdaptationSets in the field of view while playing?
For example，AdaptationSets  1 2 3 4 5 is in the field of view ,  so only  1 2 3 4 5 AdaptationSets  will be downloaded,  is it possible for this branch？
Thanks.

**Comment by jeanlf** [comment]
Yes, this is controlled by the `GF_FEVT_VISIBILITY_HINT` event for single texture/AdaptationSets,  and by the `GF_FEVT_QUALITY_SWITCH` event for multiple textures/AdaptationSets. 

These are fired by the compositor filter (look for gf_mo_hint_visible_rect and gf_mo_hint_quality_degradation functions)
