### ISSUE TITLE
MP4Box Filters Problem when inserting cover using -itags cover="path"

### ISSUE THREAD

**Issue by jalba69** [gpac/gpac#1373]
Hello,

With last version of MP4Box from the Filters Branch trying the following under windows console command leaves MP4Box in a sort of endless loop, stuck somehow : 

```
MP4Box.exe -add video.mp4#video -add video.mp4#audio -itags cover="H:\cover.jpg" -new output.mp4
←[32mIsoMedia import video.mp4 - track ID 1 - Video (size 1280 x 720)
←[32mIsoMedia import video.mp4 - track ID 2 - Audio (SR 48000 - 2 channels)
-
```
The console stays with this displayed and stuck at this point, i have to close the command console to exit.

However this command with no path for the cover pic works :
`MP4Box.exe -add video.mp4#video -add video.mp4#audio -itags cover=cover.jpg -new output.mp4`

This works too with cover.jpeg encapsulated in " " symbols : 
`MP4Box.exe -add video.mp4#video -add video.mp4#audio -itags cover="cover.jpg" -new output.mp4`

Not sure what is wrong with the full path for the cover but something seems to happen when using it.

Thanks a lot.

**Comment by jeanlf** [comment]
indeed, now fixed - thanks for the report
