### ISSUE TITLE
How to install on Ubuntu 18.04?

### ISSUE THREAD

**Issue by psytechno604** [gpac/gpac#1379]
Hello.
What I did:

wget https://download.tsi.telecom-paristech.fr/gpac/new_builds/linux64/gpac/gpac_0.8.0-rev95-g00dfc933-master_amd64.deb
apt install ./gpac_0.8.0-rev95-g00dfc933-master_amd64.deb

The result is:

The following packages have unmet dependencies:
--
gpac : Depends: libavcodec-ffmpeg56 (>= 7:2.4) but it is not installable or
libavcodec-ffmpeg-extra56 (>= 7:2.4) but it is not installable
Depends: libavdevice-ffmpeg56 (>= 7:2.4) but it is not installable
Depends: libavformat-ffmpeg56 (>= 7:2.4) but it is not installable
Depends: libavutil-ffmpeg54 (>= 7:2.4) but it is not installable
Depends: libmozjs185-1.0 (>= 1.8.5-1.0.0+dfsg) but it is not installable
Depends: libopenjpeg5 (>= 1.3+dfsg) but it is not installable
Depends: libpng12-0 (>= 1.2.13-4) but it is not installable
Depends: libswresample-ffmpeg1 (>= 7:2.4) but it is not installable
Depends: libswscale-ffmpeg3 (>= 7:2.4) but it is not installable

Where to find the links for these packages? "apt install" does not work. Google does not help, it says only that in Ubuntu 18.04 "..56" was replaced with "..57" and they are completely different or so..

https://askubuntu.com/questions/852605/are-ffmpeg56-and-ffmpeg54-packages-discontinued/852608#852608

**Comment by aureliendavid** [comment]
Hi, 

I think you'll have to rebuild it yourself for ubuntu 18 (https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux) since the binary packages are built for 16.04 and the dependencies seem too different. 

We should probably update our build system to the latest ubuntu LTS soon.

**Comment by aureliendavid** [comment]
> We should probably update our build system to the latest ubuntu LTS soon.

The official packages are now built on ubuntu 18.04, the debs should be installable directly
