### ISSUE TITLE
How to set availabilityStartTime="1970-01-01T00:00:00Z"?

### ISSUE THREAD

**Issue by psytechno604** [gpac/gpac#1382]
- [ YES ] I looked for a similar issue and couldn't find any.
- [ YES ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ YES ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). 

Hello. Is there a way to generate proper working DASH streams with manifests like that: https://live.unified-streaming.com/scte35/scte35.isml/.mpd?

Key features that I need:
1) availabilityStartTime="1970-01-01T00:00:00Z" (zero unix time)
2) segment template depending on representation id and time (not on index or so): media="scte35-$RepresentationID$-$Time$.dash"

P.S. I tried many ways with different software. The requirement (2) can be fulfilled with ffmpeg + rtmp plugin for nginx, but when I try to "move" all timings in manifest (renaming the files accordingly) - then it works only in VLC, most online players will not play. I suppose that there is some timecode inside the segments, that prevents them from being played if it does not match the actual time. For example, if I have generated stream with availabilityStartTime close to current time, then just setting it to 01.01.1970 and renaming the <SegmentTimeline> elements and files will not work.

**Comment by jeanlf** [comment]
- to set AST, use `-start-date` option of MP4Box
- to change the template, use `-segment-template=scte35-$RepresentationID$-$Time$ -segment-ext=dash`
