### ISSUE TITLE
How to create live DASH stream from single mp4 file?

### ISSUE THREAD

**Issue by psytechno604** [gpac/gpac#1383]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ YES] I looked for a similar issue and couldn't find any.
- [ YES] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ YES] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...).

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hello. I need to create live DASH stream from single mp4 file, that will be continuously played in a loop. Is it possible with GPAC?

**Comment by kahanikaar** [comment]
Have you checked the details mentioned here?
https://github.com/gpac/gpac/wiki/DASH-Introduction
