### ISSUE TITLE
Pseudo live loop encode settings

### ISSUE THREAD

**Issue by chanof** [gpac/gpac#1384]
Hi there, i try get more clear,

This is my command line:

`MP4Box -dash-live 2000 -subdur 4000 -bound -profile dashavc264:live -mpd-refresh 4 -time-shift 16 -min-buffer 2000 -url-template -insert-utc -run-for 86400000 -dash-ctx /var/www/site.com/public/live/log.txt -out /var/www/site.com/public/live/manifest.mpd 1080set.mp4:bandwidth=4800000#video 720set.mp4:bandwidth=2400000#video 360set.mp4:bandwidth=800000#video 180set.mp4:bandwidth=400000#video audio.mp4:bandwidth=384000#audio`

I use it with video.js/dash.js on browsers

I use to concat more videos, to get a big one video with FFMPEG, but i get issues to obtain a video with the duration in seconds without any decimal, i need to stream this video over and over without no pauses, so the users can't understand when the loop start again. (and they don't need to refresh the player page every time the video restarts)
I try to get it more stable i can, so please may i ask you which config i need to choose? i think that -no-loop does not allow me to auto restart, and a little decimal's delta mulitplied over and over as the loop could involve in error.
May i ask which is the better strategy?
Thanks

**Comment by jeanlf** [comment]
see comments in #1514
