### ISSUE TITLE
Dolby track extraction does not copy dac3 box

### ISSUE THREAD

**Issue by grukx** [gpac/gpac#1385]
Hi,

I am trying to use MP4Box to extract a dolby (ac-3/ec-3) track (from mp4 to mp4). What I have found is that the dac3 box is not copied to the new file.

MP4Box does this correctly when going from mp4->es->mp4, but direct mp4->mp4 is wrong.

The input has the following information:
```
Box Type 'stbl', size 327:
          Box Type 'stsd', size 63, version 0, flags 000000
            Data size 51
            entry_count 1
            Box Type 'ac-3', size 47:
              reserved 00 00 00 00 00 00 
              data_reference_index 1
              channelcount 2
              samplesize 16
              samplerate 48000
              Box Type 'dac3', size 11:
                fscod 0
                bsid 6
                bsmod 0
                acmod 7
                lfeon 1
                bit_rate_code 15 => 448
                reserved 0
```

but after extraction (MP4Box -add CosmosLaundromat_448k_dolby_5.1.m4a#audio -new test.mp4) I get:

```
Box Type 'stsd', size 72, version 0, flags 000000
            Data size 60
            entry_count 1
            Box Type 'ac-3', size 56:
              reserved 00 00 00 00 00 00 
              data_reference_index 1
              channelcount 6
              samplesize 16
              samplerate 48000
              Box Type 'btrt', size 20:
                bufferSizeDB 1792
                maxBitrate 473088
                avgBitrate 448000
```

So I have gotten the bitrate information, but lost the codec/channel information.

I have tested this with the latest master from github as well as the latest released version.

Regards,
Geir

**Comment by jeanlf** [comment]
seems fine in filters but broken in master, I'll have a look

**Comment by jeanlf** [comment]
should now be fixed, can you check and close?

**Comment by grukx** [comment]
That was fast! World class response time :dancer: :zap: 

I will check and close today :D

Thanks a lot,
Geir

**Comment by grukx** [comment]
Worked perfectly!
