### ISSUE TITLE
Cannot launch the program under Windows 10 64bit

### ISSUE THREAD

**Issue by Polda18** [gpac/gpac#1386]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

-------------

Hi. I just installed latest version of GPAC and launching it does nothing. Only a console window appears for a glimpse of a second and quickly disappears. Nothing else. I've installed 64bit Windows binaries. I couldn't read what the console window had to say, it was way too fast, but it seems that it was just an empty console window, nothing else. I don't know where shall I look for error log, if any was created. It's like looking for a needle in a hay bale. I can narrow down the locations where could I find the error log, which is usually inside %appdata% or inside the program folder itself. However I do not know if that was how the program was constructed in case of error, it is possible that the error log is elsewhere, or does not exist at all.

Right now it seems like the program does nothing or doesn't work.

**Comment by aureliendavid** [comment]
which file did you download?

you can check in `%appdata%\GPAC` if you have a previous `GPAC.cfg` file and delete it, then retry

to see the console messages you can run `MP4Client` or `MP4Box` from `cmd.exe` (the install dir should be in your PATH, otherwise cd to it)

**Comment by Polda18** [comment]
It works now. MP4Box is just command line tool and MP4Client seems to have only Player available. There's no GUI for multiplexing?

**Comment by aureliendavid** [comment]
no the only gui is the mp4client player

all file operations are done with the mp4box command line tool (see the wiki for some documentation)
