### ISSUE TITLE
-hint in mp4box static

### ISSUE THREAD

**Issue by jb-alvarado** [gpac/gpac#139]
Hello gpac team, 
we compile mp4box from you with that script:
https://github.com/jb-alvarado/media-autobuild_suite
In the past it was working normal, but now we can not use `-hint` in the static compilation anymore. When we compile it with a shared lib, `-hint` works normal.

Do you have any idea?

**Comment by rbouqueau** [comment]
Hi, I can reproduce, thanks for reporting.

@jeanlf when building the static mp4box, the 'disable player ' is also activate which disables streaming, see https://github.com/gpac/gpac/commit/9acf553071142907a63e93638ac4487b003673c8#diff-e2d5a00791bce9a01f99bc6fd613a39dR2349 . Opinion?

**Comment by Selur** [comment]
-hint is ment to hint the given file for RTP/RTSP, so would be nice if this would work again.
(never used the player, but I like to use mp4box for multiplexing files which are ment to be sent over rtp)
-> would be nive if this could be fixed :)

**Comment by rbouqueau** [comment]
Yes sorry there was indeed a regression at the beginning of 2015. Can you try again and close if ok?

**Comment by wiiaboo** [comment]
I wonder if it would be possible to add this too? Since dynamic libs aren't build with --static-mp4box there's no need for `make install-lib` to end with an error.

```
diff --git a/Makefile b/Makefile
index 820c49b..34f957d 100644
--- a/Makefile
+++ b/Makefile
@@ -218,7 +218,9 @@ ifeq ($(GPAC_ENST), yes)
 endif
 	mkdir -p "$(DESTDIR)$(prefix)/$(libdir)"
 	$(INSTALL) $(INSTFLAGS) -m 644 "./bin/gcc/libgpac_static.a" "$(DESTDIR)$(prefix)/$(libdir)"
+ifneq ($(MP4BOX_STATIC), yes)
 	$(MAKE) installdylib
+endif
 
 uninstall-lib:
 	rm -rf "$(prefix)/include/gpac/internal"
```

**Comment by rbouqueau** [comment]
> I wonder if it would be possible to add this too? Since dynamic libs aren't built with --static-mp4box there's no need for make install-lib to end with an error.

Yes, thank you. Done.

> And mingw64 has -fPIC on by default so it keeps spamming -fPIC ignored for target (all code is position independent) for every file so it should be safe to not add it.

It is a little more complex than that. Done anyway.

Please close if ok.

**Comment by wiiaboo** [comment]
>It is a little more complex than that. Done anyway.

It should probably be silenced somewhere in GCC since it's a useless warning.

Ping @jb-alvarado, it should be ok to close.

**Comment by jb-alvarado** [comment]
Thank you for fixing! Very nice!
