### ISSUE TITLE
GPAC assumes wrong character encoding

### ISSUE THREAD

**Issue by Polda18** [gpac/gpac#1390]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

----
Hi. I recently updated to 0.9.0 (latest build), and it seems like character encoding has been broken:
```
E:\Videa>mp4box -info "Zpěv na benzínce.avi"
Cannot create directory "C:\Users\Marek PolßŔek": last error 5
Cannot create directory "C:\Users\Marek PolßŔek\AppData": last error 5
Cannot create directory "C:\Users\Marek PolßŔek\AppData\Roaming": last error 5
Cannot create directory "C:\Users\Marek PolßŔek\AppData\Roaming\GPAC": last error 5
[Core] system failure for file opening of "C:\Users\Marek PolßŔek\AppData\Roaming\GPAC\GPAC.cfg" in mode "wt": 0x00000005
[core] Cannot create config file GPAC.cfg in C:\Users\Marek PolßŔek\AppData\Roaming\GPAC directory
Fatal error: failed to initialize GPAC global configuration
```
I have user name with space and accents, which made it quite problematic for it to work with. It didn't happen in previous version (0.8.0). Correct user folder name should be `Marek Poláček`. What went wrong?

**Comment by jeanlf** [comment]
will look into that - meanwhile you can check with adding `-p=0` to your command line

**Comment by Polda18** [comment]
Thank you :)

**Comment by Polda18** [comment]
I guess I'll leave it like that. The imported video is sped up, completely misalignign with audio and subtitles :( Looks like MKV format is better choice in this case.

**Comment by jeanlf** [comment]
Yes I noticed that this video declares 60 fps - you can change the FPS at import:
`MP4Box -add source.avi:fps=30 -new res.mp4`

**Comment by aureliendavid** [comment]
@Polda18 > latest commit should fix the charset issue, can you retest and confirm? thx

**Comment by Polda18** [comment]
Confirmed. Although it works for settings only, not for displaying correct filenames. But I don't mind as long as it actually saves correct filenames. Thank you a lot :)
