### ISSUE TITLE
The install and cache paths are hard coded for Android, how can it be customzed?

### ISSUE THREAD

**Issue by peipeiguo** [gpac/gpac#1391]
Dear all,

I found the install and cache paths are hard coded as `com.gpac.Osmo4` for Android. Code as bellow:
- in `DEFAULT_ANDROID_PATH_APP` macro:
https://github.com/gpac/gpac/blob/1d9c6805d930a22f9bb6c8ea44cc8520e8ad2400/src/utils/os_config_init.c#L63
- in `gf_get_default_cache_directory` function:
https://github.com/gpac/gpac/blob/1d9c6805d930a22f9bb6c8ea44cc8520e8ad2400/src/utils/os_divers.c#L1774

How can it be customzed, such as `com.abc.mytest`? Is there any way to set it from config or something else?
Thanks.

**Comment by jeanlf** [comment]
The app path should not be changed once compiled, but you can modify it manually.
With GPAC 1.0, the cache dir is set by the core option [-cache](https://github.com/gpac/gpac/wiki/core_options#cache), which means you can override the cache in the config file by adding:

```
[core]
cache=/sdcard/my_gpac/cache
```
