### ISSUE TITLE
HbbTV 1.5: map scan type according to content

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#1395]
HbbTV 1.5 mandates ```@scanType``` (E2.3):
> The profile-specific MPD shall provide the following information for all Representations, whether defined as part of the Representation or inherited.
> -  For video Representations: @width, @height, @frameRate and @scanType

For GPAC >= 0.9 (filters), the ```scanType``` is applied from the external ```interlaced``` attribute. This attribute is only displayed when content is interlaced.

The executor of this issue would have to (if still relevant):
 - force the writing of the ```scanType``` also for progressive content when the HbbTV 1.5 profile is enabled, and
 - detect the scanType properly from the DecoderConfigDescriptor

**Comment by jeanlf** [comment]
should now be fixed
