### ISSUE TITLE
Bug in GF_DASH_THREAD_ALL  mode，out of memory error（filter branch）

### ISSUE THREAD

**Issue by LeoKingLong** [gpac/gpac#1396]
1. I  changed the dash thread mode to GF_DASH_THREAD_ALL in dashdmx_initialize method of dmx_dash.c file:
ctx->dash = gf_dash_new(&ctx->dash_io, GF_DASH_THREAD_ALL, 0, ctx->auto_switch, (ctx->store==2) ? GF_TRUE : GF_FALSE, (ctx->algo==GF_DASH_ALGO_NONE) ? GF_TRUE : GF_FALSE, ctx->start_with, ctx->timeshift);

2.Then I run the gpac play , and found the following Call chain：
dash_setup_period_and_groups-->gf_dash_download_resource-->dashdmx_io_create

3.In the dashdmx_io_create method, show the hint,so it return null:
	//we work in non-threaded mode, only MPD fetcher is allowed
	if (group_idx>=0)
		return NULL;

4. So finally gf_dash_download_resource return  out memory error：
	if (! *sess) {
		*sess = dash_io->create(dash_io, persistent_mode ? 1 : 0, url, group_idx);
		if (!(*sess)) {
			if (dash->atsc_clock_state)
				return GF_IP_NETWORK_EMPTY;
			GF_LOG(GF_LOG_ERROR, GF_LOG_DASH, ("[DASH] Cannot try to download %s... out of memory ?\n", url));
			return GF_OUT_OF_MEM;
		}
	}

Is it a bug ? 
How to set the dash run in GF_DASH_THREAD_ALL  mode?
Thanks!

**Comment by jeanlf** [comment]
You simply cannot, the dash demux filters uses the unthreaded version of the DASH client in GPAC (which is why the threading mode is not exposed as a configurable option). The segment downloads are made in parallel by the filter session. Is there any specific tool you need from the threaded mode not exposed in dashdmx ?

**Comment by LeoKingLong** [comment]
For example，if the MPD file has 10 adaptationSets in one period, when I play the video with gpac,
I found the program will download the track file in sequence：
for example：
        track1_1.m4s, then track2_1.m4s,then track3_1.m4s  ....... then  track10_1.m4s;
then track1_2.m4s, then track2_2.m4s,then track3_2.m4s  ....... then  track10_2.m4s;

Is there any way to download the track files in the same time(filter branch)?
For example，download track1_1.m4s, track2_1.m4s, track3_1.m4s  .......  track10_1.m4s  the same time.
Thanks!

**Comment by jeanlf** [comment]
are you using MP4Client or gpac app?

**Comment by LeoKingLong** [comment]
yes ,I use MP4Client and gpac app both

**Comment by jeanlf** [comment]
The dash demux will schedule current segment for each active adaptation so that they are downloaded in parallel - wether their download finishes in the scheduling sequence order depends on network io
