### ISSUE TITLE
Segment based encryption in fmp4

### ISSUE THREAD

**Issue by Aditya343** [gpac/gpac#1398]
I want to know whether segment based encryption is supported in fmp4. I tried doing it through MP4Box but was not successful. Any idea about how to do in GPAC?

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [1] I looked for a similar issue and couldn't find any.
- [1] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [1] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
Yes with filters branch, see this test:
https://github.com/gpac/testsuite/blob/filters/scripts/encryption_segment.sh

**Comment by Aditya343** [comment]
Hi,
What I have understood is running encryption_segment.sh will convert the .264 into fmp4 and then generate the .mpd after encryption. Is it like that?

Also I have getting error which is as mentioned below:

Checking test suite config
- Reference hashes available - enabling hash tests
- External media dir available
gpac not found (ret 127) - exiting
- GPAC not compiled with memory tracking

GPAC version: 0.8.0-rev167-gcccb740f9-master

Evaluating Test Suite
not found ./results/temp/dst_dash1.m4s
not found ./results/temp/dst_dash2.m4s
not found ./results/temp/source_dash2_info.xml
not found ./results/temp/dst_dash2_info.xml
encryption-segment: diso-seg2:HashSourceNotFound diso-crypt-seg2:HashSourceNotFound crypt-seg2:HashSourceNotFound crypt-seg1:HashSourceNotFound crypt-init:HashFail diso-crypt-seg2:Fail diso-seg2:Fail crypt-seg2:Fail crypt-seg1:Fail
Number of Tests 158 - 568 subtests - Executed: 158 (100 %) - Cached: 0 (0 %)
Tests passed 157 (99 %) - 568 sub-tests
Tests failed 1 (0 % of subtests)
Tests Unknown 0 (0 % of subtests)
Tests HASH total 542 - fail 5 (0 % of subtests)


Thanks for the help

**Comment by jeanlf** [comment]
you need the filter branch of GPAC, not master

**Comment by Aditya343** [comment]
Hi,

Thanks. But after I run the script, the error comes - "Option -init-seg unknown. Please check usage"

Thanks

**Comment by jeanlf** [comment]
I think you're still on master, check `MP4Box`

**Comment by Aditya343** [comment]
My branch is filters only. This is the outcome when I run MP4Box

Not enough arguments - check usage with -h
MP4Box - GPAC version 0.8.0-rev167-gcccb740f9-master
(c) Telecom ParisTech 2000-2018 - Licence LGPL v2

**Comment by jeanlf** [comment]
filters is 0.9.0, I huess you forgot to uninstall/reinstall

**Comment by Aditya343** [comment]
Hi,

You are right. I was not updated with the latest one. Got it working now :)
Thanks

**Comment by Aditya343** [comment]
Hi,

I encrypted the fmp4 as mentioned by you. Any suggestions for decryption?

**Comment by jeanlf** [comment]
same approach using `-decrypt`

**Comment by Aditya343** [comment]
Hi,

Can you please explain the decryption part. I am trying to use the same commands with -decrypt whatever is mentioned in encryption.sh using the same ctr.xml. I am getting error - "[CENC] Packet encrypted but no SAI info nor constant IV"

Do I need to add something in the .mpd file or in .xml?

**Comment by Aditya343** [comment]
Hi,

After encrypting with ctr.xml, following files were generated:
dec_init.mp4, dst_dash1.m4s, dst_dast2.m4s, dst_dash2_info.xml

Now, I am running the same commands with -decrypt option for decryption. The commands that I ran are:

-> MP4Box -decrypt ../../media/encryption/ctr.xml dst_dashinit.mp4 -out dec_init.mp4

[CENC] Packet encrypted but no SAI info nor constant IV
Decrypting:  100.00 %
	Error: Internal Service Error
->MP4Box -decrypt ../../media/encryption/ctr.xml -init-seg dst_dashinit.mp4 dst_dash1.m4s -out dec1.m4s
->MP4Box -decrypt ../../media/encryption/ctr.xml -init-seg dst_dashinit.mp4 dst_dash2.m4s -out dec2.m4s

Now for running the decrypted content, my file.mpd looks like:

<?xml version="1.0"?>

<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H0M10.080S" maxSegmentDuration="PT0H0M5.000S" profiles="urn:mpeg:dash:profile:isoff-live:2011">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>file.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H0M10.080S">
  <AdaptationSet segmentAlignment="true" maxWidth="640" maxHeight="360" maxFrameRate="25" par="16:9" lang="und" startWithSAP="1">
   <SegmentTemplate media="dec$Number$.m4s" initialization="dec_init.mp4" timescale="100" startNumber="1" duration="500"/>
   <Representation id="1" mimeType="video/mp4" codecs="avc1.42C01E" width="640" height="360" frameRate="25" sar="1:1" bandwidth="225776">
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>


Now when I try to run the .mpd via mplayer, following error comes:

MPlayer 1.3.0 (Debian), built with gcc-7 (C) 2000-2016 MPlayer Team

Playing file.mpd.
libavformat version 57.83.100 (external)
libavformat file format detected.
[dash @ 0x7fdbf335b2a0]Opening 'dec_init.mp4' for reading
[dash @ 0x7fdbf335b2a0]Could not read complete fragment.
[dash @ 0x7fdbf335b2a0]Opening 'dec1.m4s' for reading
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fdbf335b2a0]Found duplicated MOOV Atom. Skipped it
[dash @ 0x7fdbf335b2a0]Opening 'dec2.m4s' for reading
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fdbf335b2a0]Found duplicated MOOV Atom. Skipped it
[dash @ 0x7fdbf335b2a0]Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 640x360): unspecified pixel format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[lavf] stream 0: video (h264), -vid 0
LAVF: Program 0 
VIDEO:  [H264]  640x360  24bpp  100.000 fps    0.0 kbps ( 0.0 kbyte/s)
Failed to open VDPAU backend libvdpau_i965.so: cannot open shared object file: No such file or directory
[vdpau] Error when calling vdp_device_create_x11: 1
==========================================================================
Opening video decoder: [ffmpeg] FFmpeg's libavcodec codec family
libavcodec version 57.107.100 (external)
Selected video codec: [ffh264] vfm: ffmpeg (FFmpeg H.264)
==========================================================================
Load subtitles in ./
Audio: no sound
Starting playback...
V:   0.0   0/  0 ??% ??% ??,?% 0 0 


Exiting... (End of file)


Hope you will get something

**Comment by jeanlf** [comment]
my bad, segment decryption was not implemented ! This should now be fixed on git, and test suite updated accordingly, thanks for your tests

**Comment by Aditya343** [comment]
Ok. I will try now. Thanks for the help :)
