### ISSUE TITLE
Converting mpd links to m3u8

### ISSUE THREAD

**Issue by Kanekid2m** [gpac/gpac#1400]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hi,

there is a streaming platform that I used to download everything from and it was easy downloading series and episodes with ffmpeg from it but while ago they updated their website and now the streaming platform is protected with mpd. I am kind of Newbie and I dont actually now if GPAC can convert m3u8 links to mpd or just files but I wanted to ask if there is anyway to convert mpd links to m3u8. I tried it using following command : 

`MP4Box -mpd link.mpd -out output.m3u8`

and then I got this error :

`Error converting Smooth mpd link) to MPD (output.m3u8): Feature Not Supported`

So that is when I made sure that gpac converts only files and does not convert links but I wanted to ask for your help anyway so if there is anyone who can help me I will really appreciate it.

**Comment by jeanlf** [comment]
it really depends on the files you fetched and the MPD profile used...
Could you give more details:
- is each quality stored in a single file or are there multiple segment files per quality
- could you post the MPD somewhere?

**Comment by jeanlf** [comment]
no news, closing
