### ISSUE TITLE
mp3/aac trim precision issue

### ISSUE THREAD

**Issue by chanof** [gpac/gpac#1401]
Due to mp3/aac codec doesn't support that level of trim precision:

```
ffprobe -v error -show_entries format=duration \
>   -of default=noprint_wrappers=1:nokey=1 output_audio.mp4
372.006000
```

```
[...]
Next generation scheduled in 3895 ms (DASH time 412006 ms)
```

My command:
MP4Box -dash-live 2000 -subdur 4000 -bound -segment-timeline -no-cache -profile dashavc264:live -subsegs-per-sidx -1 -mpd-refresh 4 -time-shift 16 -min-buffer 2000 -url-template -insert-utc -bs-switching no -run-for 86400000 -dash-ctx ../../live/log.txt -out ../../live/manifest.mpd ../current/output_1080.mp4:bandwidth=4800000#video ../current/output_720.mp4:bandwidth=2400000#video ../current/output_360.mp4:bandwidth=800000#video ../current/output_audio.mp4:bandwidth=384000#audio

after 50% of the advertised duration an error will occur (probably)
I say probably because the time for testing it is very long so may ask if the mp4box command provide for a stable loop or if the error will occur, and if yes, it will occur, may ask an help to debug my command line on mp4box to avoid this issue?
Im sorry but trial and error it's too long since every try is about 24 hours..
Dash.js web based purpose.
Thansk in advance!

**Comment by chanof** [comment]
The error will occur, please i need help 
Thanks!
![dp](https://user-images.githubusercontent.com/30214298/73198607-8e043780-4133-11ea-8dc0-04f5d97e1da1.png)

**Comment by jeanlf** [comment]
see comments in #1514
