### ISSUE TITLE
FFMPEG

### ISSUE THREAD

**Issue by Shikhaagrawal08** [gpac/gpac#1403]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

PATH="/home/shikha/buildroot.old/output/host/bin:/home/shikha/buildroot.old/output/host/sbin:/home/shikha/buildroot.old/output/host/usr/bin:/home/shikha/buildroot.old/output/host/usr/sbin:/home/jemish/bin:/home/jemish/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/jemish/Downloads/gcc-linaro-5.5.0-2017.10-x86_64_aarch64-linux-gnu/bin:/home/jemish/workspace/lu500/CodeSourcery/arm-2009q1/bin" /usr/bin/make -j5 CC=/home/shikha/buildroot.old/output/host/usr/bin/aarch64-linux-gnu-g++ CXX=/home/shikha/buildroot.old/output/host/usr/bin/aarch64-linux-gnu-g++ -C /home/shikha/buildroot.old/output/build/c2play-1.0.0 c2play
==== Building c2play (debug) ====
Creating obj/Debug/c2play
main.cpp
Image.cpp
Buffer.cpp
Mutex.cpp
AmlCodec.cpp
MediaPlayer.cpp
In file included from ../../src/Media/Buffer.cpp:17:0:
../../src/Media/Buffer.h: In destructor ‘virtual AVPacketBuffer::~AVPacketBuffer()’:
../../src/Media/Buffer.h:429:3: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
   ^
../../src/Media/Buffer.h:429:23: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
                       ^
../../src/Media/Buffer.h: In member function ‘void AVPacketBuffer::Reset()’:
../../src/Media/Buffer.h:465:3: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
   ^
../../src/Media/Buffer.h:465:23: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
                       ^
In file included from ../../src/Media/Codec.h:32:0,
                 from ../../src/Media/Pin.h:19,
                 from ../../src/Media/AmlCodec.h:26,
                 from ../../src/Media/AmlCodec.cpp:17:
../../src/Media/Buffer.h: In destructor ‘virtual AVPacketBuffer::~AVPacketBuffer()’:
../../src/Media/Buffer.h:429:3: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
   ^
../../src/Media/Buffer.h:429:23: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
                       ^
../../src/Media/Buffer.h: In member function ‘void AVPacketBuffer::Reset()’:
../../src/Media/Buffer.h:465:3: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
   ^
../../src/Media/Buffer.h:465:23: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
                       ^
MediaSourceElement.cpp
AudioCodec.cpp
In file included from ../../src/Media/Codec.h:32:0,
                 from ../../src/Media/MediaSourceElement.h:19,
                 from ../../src/Media/MediaPlayer.h:19,
                 from ../../src/main.cpp:39:
../../src/Media/Buffer.h: In destructor ‘virtual AVPacketBuffer::~AVPacketBuffer()’:
../../src/Media/Buffer.h:429:3: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
   ^
../../src/Media/Buffer.h:429:23: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
                       ^
../../src/Media/Buffer.h: In member function ‘void AVPacketBuffer::Reset()’:
../../src/Media/Buffer.h:465:3: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
   ^
../../src/Media/Buffer.h:465:23: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
                       ^
In file included from ../../src/Media/Codec.h:32:0,
                 from ../../src/Media/MediaSourceElement.h:19,
                 from ../../src/Media/MediaPlayer.h:19,
                 from ../../src/Media/MediaPlayer.cpp:17:
../../src/Media/Buffer.h: In destructor ‘virtual AVPacketBuffer::~AVPacketBuffer()’:
../../src/Media/Buffer.h:429:3: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
   ^
../../src/Media/Buffer.h:429:23: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
                       ^
../../src/Media/Buffer.h: In member function ‘void AVPacketBuffer::Reset()’:
../../src/Media/Buffer.h:465:3: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
   ^
../../src/Media/Buffer.h:465:23: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
                       ^
Thread.cpp
In file included from ../../src/Media/Codec.h:32:0,
                 from ../../src/Media/AudioCodec.h:25,
                 from ../../src/Media/AudioCodec.cpp:17:
../../src/Media/Buffer.h: In destructor ‘virtual AVPacketBuffer::~AVPacketBuffer()’:
../../src/Media/Buffer.h:429:3: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
   ^
../../src/Media/Buffer.h:429:23: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
                       ^
../../src/Media/Buffer.h: In member function ‘void AVPacketBuffer::Reset()’:
../../src/Media/Buffer.h:465:3: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
   ^
../../src/Media/Buffer.h:465:23: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
                       ^
In file included from ../../src/Media/Codec.h:32:0,
                 from ../../src/Media/MediaSourceElement.h:19,
                 from ../../src/Media/MediaSourceElement.cpp:17:
../../src/Media/Buffer.h: In destructor ‘virtual AVPacketBuffer::~AVPacketBuffer()’:
../../src/Media/Buffer.h:429:3: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
   ^
../../src/Media/Buffer.h:429:23: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
                       ^
../../src/Media/Buffer.h: In member function ‘void AVPacketBuffer::Reset()’:
../../src/Media/Buffer.h:465:3: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
   ^
../../src/Media/Buffer.h:465:23: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
                       ^
../../src/main.cpp: In function ‘int main(int, char**)’:
../../src/main.cpp:341:2: warning: ‘void av_register_all()’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavformat/avformat.h:2050) [-Wdeprecated-declarations]
  av_register_all();
  ^
../../src/main.cpp:341:18: warning: ‘void av_register_all()’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavformat/avformat.h:2050) [-Wdeprecated-declarations]
  av_register_all();
                  ^
LockedQueue.cpp
../../src/Media/MediaSourceElement.cpp: In member function ‘void MediaSourceElement::SetupPins()’:
../../src/Media/MediaSourceElement.cpp:107:44: warning: ‘AVStream::codec’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavformat/avformat.h:885) [-Wdeprecated-declarations]
   AVCodecContext* codecCtxPtr = streamPtr->codec;
                                            ^
../../src/Media/MediaSourceElement.cpp:107:44: warning: ‘AVStream::codec’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavformat/avformat.h:885) [-Wdeprecated-declarations]
../../src/Media/MediaSourceElement.cpp:163:11: error: ‘CODEC_ID_MPEG2VIDEO’ was not declared in this scope
      case CODEC_ID_MPEG2VIDEO:
           ^
../../src/Media/MediaSourceElement.cpp:175:11: error: ‘CODEC_ID_MPEG4’ was not declared in this scope
      case CODEC_ID_MPEG4:
           ^
../../src/Media/MediaSourceElement.cpp:181:11: error: ‘CODEC_ID_H264’ was not declared in this scope
      case CODEC_ID_H264:
           ^
../../src/Media/MediaSourceElement.cpp:194:11: error: ‘CODEC_ID_VC1’ was not declared in this scope
      case CODEC_ID_VC1:
           ^
../../src/Media/MediaSourceElement.cpp:245:11: error: ‘CODEC_ID_MP2’ was not declared in this scope
      case CODEC_ID_MP2:
           ^
../../src/Media/MediaSourceElement.cpp:251:11: error: ‘CODEC_ID_MP3’ was not declared in this scope
      case CODEC_ID_MP3:
           ^
../../src/Media/MediaSourceElement.cpp:257:11: error: ‘CODEC_ID_AAC’ was not declared in this scope
      case CODEC_ID_AAC:
           ^
../../src/Media/MediaSourceElement.cpp:263:11: error: ‘CODEC_ID_AC3’ was not declared in this scope
      case CODEC_ID_AC3:
           ^
../../src/Media/MediaSourceElement.cpp:269:11: error: ‘CODEC_ID_DTS’ was not declared in this scope
      case CODEC_ID_DTS:
           ^
../../src/Media/MediaSourceElement.cpp:346:12: error: ‘CODEC_ID_HDMV_PGS_SUBTITLE’ was not declared in this scope
      case  CODEC_ID_HDMV_PGS_SUBTITLE:
            ^
../../src/Media/MediaSourceElement.cpp:351:12: error: ‘CODEC_ID_DVB_SUBTITLE’ was not declared in this scope
      case  CODEC_ID_DVB_SUBTITLE:
            ^
../../src/Media/MediaSourceElement.cpp:356:12: error: ‘CODEC_ID_TEXT’ was not declared in this scope
      case  CODEC_ID_TEXT:
            ^
../../src/Media/MediaSourceElement.cpp:361:12: error: ‘CODEC_ID_XSUB’ was not declared in this scope
      case  CODEC_ID_XSUB:
            ^
../../src/Media/MediaSourceElement.cpp:365:12: error: ‘CODEC_ID_SSA’ was not declared in this scope
      case  CODEC_ID_SSA:
            ^
../../src/Media/MediaSourceElement.cpp:369:12: error: ‘CODEC_ID_MOV_TEXT’ was not declared in this scope
      case  CODEC_ID_MOV_TEXT:
            ^
../../src/Media/MediaSourceElement.cpp:374:12: error: ‘CODEC_ID_DVB_TELETEXT’ was not declared in this scope
      case  CODEC_ID_DVB_TELETEXT:
            ^
../../src/Media/MediaSourceElement.cpp:379:12: error: ‘CODEC_ID_SRT’ was not declared in this scope
      case  CODEC_ID_SRT:
            ^
../../src/Media/AudioCodec.cpp: In member function ‘void AudioCodecElement::ProcessBuffer(AVPacketBufferSPTR, AVFrameBufferSPTR)’:
../../src/Media/AudioCodec.cpp:128:13: warning: ‘int avcodec_decode_audio4(AVCodecContext*, AVFrame*, int*, const AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4779) [-Wdeprecated-declarations]
   int len = avcodec_decode_audio4(soundCodecContext,
             ^
../../src/Media/AudioCodec.cpp:131:7: warning: ‘int avcodec_decode_audio4(AVCodecContext*, AVFrame*, int*, const AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4779) [-Wdeprecated-declarations]
    pkt);
       ^
../../src/Media/AudioCodec.cpp:209:6: warning: ‘int64_t av_frame_get_best_effort_timestamp(const AVFrame*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavutil/frame.h:683) [-Wdeprecated-declarations]
      av_frame_get_best_effort_timestamp(frame->GetAVFrame()) *
      ^
../../src/Media/AudioCodec.cpp:209:60: warning: ‘int64_t av_frame_get_best_effort_timestamp(const AVFrame*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavutil/frame.h:683) [-Wdeprecated-declarations]
      av_frame_get_best_effort_timestamp(frame->GetAVFrame()) *
                                                            ^
Codec.cpp
AmlVideoSink.cpp
c2play.make:181: recipe for target 'obj/Debug/c2play/MediaSourceElement.o' failed
make[3]: *** [obj/Debug/c2play/MediaSourceElement.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from ../../src/Media/Codec.h:32:0,
                 from ../../src/Media/AmlVideoSink.h:27,
                 from ../../src/Media/AmlVideoSink.cpp:17:
../../src/Media/Buffer.h: In destructor ‘virtual AVPacketBuffer::~AVPacketBuffer()’:
../../src/Media/Buffer.h:429:3: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
   ^
../../src/Media/Buffer.h:429:23: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
                       ^
../../src/Media/Buffer.h: In member function ‘void AVPacketBuffer::Reset()’:
../../src/Media/Buffer.h:465:3: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
   ^
../../src/Media/Buffer.h:465:23: warning: ‘void av_free_packet(AVPacket*)’ is deprecated (declared at /home/shikha/buildroot.old/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/libavcodec/avcodec.h:4473) [-Wdeprecated-declarations]
   av_free_packet(avpkt);
                       ^
Makefile:16: recipe for target 'c2play' failed
make[2]: *** [c2play] Error 2
package/pkg-generic.mk:195: recipe for target '/home/shikha/buildroot.old/output/build/c2play-1.0.0/.stamp_built' failed
make[1]: *** [/home/shikha/buildroot.old/output/build/c2play-1.0.0/.stamp_built] Error 2
Makefile:36: recipe for target '_all' failed
make: *** [_all] Error 2

**Comment by Shikhaagrawal08** [comment]
make c2play generates this error. Can someone please help me, its a bit urgent.

**Comment by jeanlf** [comment]
wrong forum ...
