### ISSUE TITLE
Incorporate saio, saiz tags in .m4s encrypted file

### ISSUE THREAD

**Issue by Aditya343** [gpac/gpac#1404]
Hi,

Can you tell me like why these tags are used in fragmented files and how I could I incorporate them in .m4s with the data. I have encrypted the data part by openssl but I think I these tags are necessary to decrypt the content.

Thanks in advance

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
these boxes are required to store CENC side data for each sample: IV for the sample and list of clear/protected byte range

**Comment by Aditya343** [comment]
I am not doing CENC encryption. I am doing aes_128ctr encryption via openssl. So, in order to play the videos, do I still have to include these boxes in the encrypted files because these boxes are not generated while doing aes_ctr128 encryption?

**Comment by jeanlf** [comment]
no since you are not following CENC, but don't expect a regular player to understand your files. And you will likely need a side mechanism (either a box or external file) to signal the IV you have at the begining of each sample if you want to be able to seek.

**Comment by Aditya343** [comment]
Hi,

I am trying to decrypt via shaka player but it throws parsing error. I was going through shaka packager code to understand how they are including saiz, saio boxes so that I can get some relevant info. but it is very large and complicated and I am new to this. 
Can you help by explaining in a more detail way or any help which I can get from any websites?

Thanks

**Comment by Aditya343** [comment]
Hi,

If my encryption is CENC, then how to include the saiz, saio boxes so that the decryption is successful via shaka player. Can you help me with this? 

Thanks

**Comment by jeanlf** [comment]
Use MP4Box or gpac , check wiki
