### ISSUE TITLE
MP4 conversion optimisation

### ISSUE THREAD

**Issue by Hubertnator** [gpac/gpac#1407]
Is there a way to speed up h264 to mp4 conversions? When I convert a long (around 20 minutes) HD video the process can take up to a minute, and if I convert even larger videos, then some of the video can be lost.

The situation can be really bad, as 1920x1080@25Hz videos that are 5 mins long take around 2-3mins.

**Comment by jeanlf** [comment]
You need to provide more details:
- GPAC version
- OS are you using
- command line you are using
- if possible, bench of file IO on your device

**Comment by Hubertnator** [comment]
Hardware: Raspberry Pi 3 Model B
GPAC version: 0.5.2
OS: Raspbian Stretch, Release: 9.11
Command line: Linux terminal (BASH)

**Comment by jeanlf** [comment]
I would suggest to try 0.8 or 0.9.
With 0.8 or 0.9, could you check the timing of the following (this produces a non-interleaved file):
`MP4Box -add source.264 -flat -new dest.mp4`

With 0.9, could you check the timing of the following (this produces an interleaved file with no extra storage requirements):
`MP4Box -add source.264 -newfs dest.mp4`

**Comment by jeanlf** [comment]
No news closing
