### ISSUE TITLE
gf_isom_set_last_sample_duration() doesn't take into account the edit lists

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#141]
I don't know if this is a real issue, but the duration computed in SetTrackDuration() states:

```
//if we have an edit list, the duration is the sum of all the editList
//entries' duration (always expressed in MovieTimeScale)
```

which seems contradictory. I think gf_isom_set_last_sample_duration() should update the edit lists but I don't know how. Ideas?

**Comment by rbouqueau** [comment]
Same for ```dur = (Double) gf_isom_get_media_duration(in, i+1);``` in ```dasher_isom_get_input_components_info()```. It prevents #142 from working.

**Comment by jeanlf** [comment]
hmm no gf_isom_set_last_sample_duration() is intended to adjust the duration in the media timescale, not without edit list (ie it adjusts the last stts entry). The track duration is always the sum of the edits if present, if you need to change that you have to modify the last edit manually

**Comment by rbouqueau** [comment]
@cconcolato Didn't you plan to make modifications on this? Is it already on the trunk?
