### ISSUE TITLE
How to playback the demo of MPEG-DASH SRD and HEVC tiling VR videos?

### ISSUE THREAD

**Issue by eric3120925** [gpac/gpac#1410]
I wanna to try to use MP4Client to playback the demo of tiling video on GPAC official website (https://gpac.wp.imt.fr/2016/05/25/srdtuto/), but the player display nothing.

The video URL:
http://download.tsi.telecom-paristech.fr/gpac/SRD/srd_hevc/multi_rate_p60/hevc_srd.mpd

**Comment by jeanlf** [comment]
discussion in  #1491
