### ISSUE TITLE
CMAF packaging

### ISSUE THREAD

**Issue by JesusAguilar95** [gpac/gpac#1412]
Dear gpac community,

I want to perform a CMAF packaging, measuring the time that takes to do it.
I use GPAC 0.8.0 that has this CMAF feature as the description, but I cannot see any documentation about that.

Could you please tell me what command lines should I use to perform CMAF packaging?

Thank you, kind regards. 

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by rbouqueau** [comment]
Hi,

There is no specific option. We are waiting for some additional inputs from MPEG about testability to add a '-cmaf' option.

In any way the time needed to make the packaging won't change significantly.

**Comment by jeanlf** [comment]
see #1066
