### ISSUE TITLE
NULL pointer occured when split a big hevc file when use gpac-filter

### ISSUE THREAD

**Issue by wchnjstar123** [gpac/gpac#1413]
The input file is 240 tiles，when I run hevcsplit，NULL pointer error occured, pid is NULL:
![image](https://user-images.githubusercontent.com/38243755/74639875-9a673780-51a9-11ea-95d6-182c5de3bd1a.png)

The stack info is as follows:
![image](https://user-images.githubusercontent.com/38243755/74640003-d7cbc500-51a9-11ea-915b-6daff7e4b46b.png)

entryCount=152，but tile num is 240, so gpac collapsed.

Is there any method to fix it?

**Comment by aureliendavid** [comment]
Hi, 

Can you upload a sample input where this bug happens? (to https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95 or other)

Also can you add the command line used and the gpac version. 

Thanks

**Comment by wchnjstar123** [comment]
command:  
gpac -i D:\testsuite-filters\test\12_20.hevc  hevcsplit:FID=1 -o  D:\testsuite-filters\output\file_0x0.hvc:SID=1#CropOrigin=*

gpac version:  0.9.0-DEV-rev3302-gf0160968-filters

**Comment by aureliendavid** [comment]
does it work if you run the same command with this input file: http://download.tsi.telecom-paristech.fr/gpac/gpac_test_suite/resources/media/counter/counter_1280_720_I_25_tiled_qp20.hevc ?

can you upload your input file somewhere?

**Comment by wchnjstar123** [comment]
Hi，it works well with counter_1280_720_I_25_tiled_qp20.hevc.  And I make a smaller file with 160 tiles, then the same error ocurrs.  I guess there are some logistic error. 

I have uploaded this file, please check. 
https://www.mediafire.com/file/kfe5c0i9hbycuhy/football-16_10.hevc/file

The info as follow:
![image](https://user-images.githubusercontent.com/38243755/74717879-1d50c680-526c-11ea-829a-958babadf684.png)

**Comment by aureliendavid** [comment]
thanks for the file

there indeed was a bug in hevcsplit preventing it to work on rectangular tilings and only worked on squared configurations

it should be fixed with the commit above, please close the issue if you confirm that it works for you

**Comment by wchnjstar123** [comment]
It works well，thanks a lot.
