### ISSUE TITLE
The dash manifest is not not well-formed when using -segment-timeline and -single-file

### ISSUE THREAD

**Issue by grukx** [gpac/gpac#1414]
When using the combination of the -segment-timeline and -single-file we see that the SegmentList element is not closed, i.e. missing '>'

MP4Box -dash 1 -frag-rap -segment-timeline -single-file video.mp4

```
<Period duration="PT0H18M30.600S">
  <AdaptationSet segmentAlignment="true" maxWidth="1280" maxHeight="720" maxFrameRate="25" par="16:9" lang="und" startWithSAP="1">
   <SegmentList timescale="1000"
    <SegmentTimeline>
     <S t="0" d="5000" r="221"/>
     <S d="600"/>
    </SegmentTimeline>
   </SegmentList>
```

**Comment by aureliendavid** [comment]
Hi, 

This is indeed not great. 

Should be fixed by the commit above. 

Thanks for the report.
