### ISSUE TITLE
How to get the position of metadata?

### ISSUE THREAD

**Issue by SteveBlackHumor** [gpac/gpac#1419]
I have checked the documentation, finding out that we do have ways to read the metadata for a video, but the way to locate that whether the metadata is at the beginning or the end of the video is not clarified.

**Comment by jeanlf** [comment]
what kind of metadata are you talking about?

**Comment by SteveBlackHumor** [comment]
I mean the metadata contained within the video which holds the title, length, resolution of the video. Because some videos may store these info at the last frame, which makes streaming them online impossible, I wanna check if a given video stores the metadata at the first or the last frame, so that I can decide whether to reformat it and make sure the metadata appear at the first frame.

**Comment by jeanlf** [comment]
OK. 
This metadata is exposed inside the moov box of MP4 files:
`MP4Box -info source.mp4`
you should see for files with meta-data first:
`	File suitable for progressive download (moov before mdat)`

HTH

**Comment by SteveBlackHumor** [comment]
Thanks, that solved my problem.
