### ISSUE TITLE
Always miss the first line of captions

### ISSUE THREAD

**Issue by vibes24** [gpac/gpac#1420]
I tried to find similar issue before writing this.

I have videos that are split up with associating caption file (TTML)
file1.mp4
file1.ttml

file2.mp4
file2.ttml

Combining videos (concat) works fine. My issue lies in the fact that when I concate ttml into the mp4 file. No matter which video/file, the first line of captions are always skipped then all captions plays beautifully.

I use this command line:
MP4Box -add file1.ttml file1.mp4

This imports captions but skips the first line of any video no matter how late the first line is being spoken in the video.  I have no plans to covert to SRT because SRT loses important information. I want to preserve original caption positions in TTML file.

I tried with multiple different video sources and first line is always skipped. Therefore it is a bug. I hope this is something the developers would look into, please and thank you.

**Comment by aureliendavid** [comment]
hi, 

can you upload samples of your ttml/video files used and detail your version of MP4Box and the exact command lines used?

thanks

**Comment by vibes24** [comment]
The files are downloaded from nick website. FYI: their own TOS says that videos are allowed to be downloaded for personal use so there shouldn't be an issue.

**Version**
mp4box -version
MP4Box - GPAC version 0.8.0-rev1-gc1990d5c-master
(c) Telecom ParisTech 2000-2018 - Licence LGPL v2
GPAC Configuration: (static configuration file)
Features: GPAC_64_BITS GPAC_MEMORY_TRACKING GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG

**Command**
c:\Story Time with Blue>mp4box -add "Story Time with Blue S1.ttml" "Story Time with Blue S1.mp4"
TTML EBU-TTD Import
The given code is not a valid one: , using 'und' as 3-letter code
[TTML] ignored "body" node, check your namespaces
[TTML] ignored "body" node, check your namespaces
[TTML] ignored "body" node, check your namespaces
[TTML] ignored "body" node, check your namespaces
[TTML] ignored "body" node, check your namespaces
[TTML] ignored "body" node, check your namespaces
[TTML] ignored "body" node, check your namespaces
[TTML] ignored "body" node, check your namespaces
[TTML] ignored "body" node, check your namespaces
[TTML] ignored "body" node, check your namespaces
Note: TTML import - EBU-TTD detected
Saving Story Time with Blue S1.mp4: 0.500 secs Interleaving

**Files - on onedrive**
https://1drv.ms/u/s!AkLAeorUKMhCkFXtXDUyltEp29ug?e=eOqfRy

**Notes**
Using VLC player.
1. When file1.mp4 and file1.ttml are in the same directory the video loads and plays the captions by default.
2.  After importing the ttml to file1.mp4 - 2 things happen: the VLC player does not play captions by default and the first line of caption is skipped. (Recommend you to either delete the ttml after importing or move mp4 file to other directory to see only one track in VLC player since VLC will automatically add ttml file as 2nd track).

This bug is related to skipping first line of caption. I've tried with various videos and subtitle files with the same result. (Unrelated: is there a way to make the caption play by default after importing?).

I wish to preserve TTML and not convert to SRT. Thank you for looking into this.

**Comment by vibes24** [comment]
Hello. how is it going? Let me know if you need more sample files. Since most streams are divided into multiple streams - 5 to 6 in my case, it means a complete video after concatenating will always be missing 5 or 6 lines of captions. There is no way to add texts unless it's converted to SRT which I prefer to not. Also a deaf person would be unable to correctly add text and time it.

**Comment by jeanlf** [comment]
The imported ttml track has all the ttml samples from the source, you can check that by dumping the content of the track (with id N):
`MP4Box -raws N file.mp4`

Playing it with last git version of GPAC shows all subs.

I think that's a VLC issue here, not GPAC related.
