### ISSUE TITLE
GPAC can't open in Mac OS

### ISSUE THREAD

**Issue by Lanjiejie** [gpac/gpac#1428]
I download it from http://gpac.sourceforge.net/ and install it, but when I open it, it meets some errors: 
<img width="874" alt="屏幕快照 2020-03-09 下午7 20 05" src="https://user-images.githubusercontent.com/39023511/76208726-3204f680-623b-11ea-88ff-8480beefe604.png">
seems like because version of liblzma.5.dylib is too old, but how to update this library?

**Comment by aureliendavid** [comment]
what is your macos version?

if you have homebrew you can try to:

`brew install xz`

(see https://stackoverflow.com/questions/31612086/cannot-get-ffmpeg-to-work-after-installing-from-homebrew)

**Comment by Lanjiejie** [comment]
Thank you for your help, its work now @aureliendavid
