### ISSUE TITLE
New to MP4Box expert advice requested

### ISSUE THREAD

**Issue by calmchess** [gpac/gpac#1429]
I hope this is the proper place to ask this question I'm using MP4Box and FFmpeg to generate dash files everything seems to be working great but I'm generating 4 files but in .mpd only 3 are listed. Why am I getting a 4th file?  I've separated the video and audio from the source .mp4 using FFmpeg then I dash those. Here is the commands I use. Yes the only way it works is if I specify MP4Box twice. I'm new to this so please forgive me if this isn't the correct way to do things.

MP4Box  MP4Box  -add test0.aac" -dash 10000 -frag 1000 -rap  test1.mp4"

How do I verify that the files I'm using are streaming correctly? Is their ability to play enough?

Thanks ahead of time.

--calmchess

**Comment by jeanlf** [comment]
could you upload your test file?
You can check playback with gpac, VLC or dash.js for example

**Comment by calmchess** [comment]
Here are the 4 files in question the video plays fine in the dash player I'm using I just need to know if all 4 files are necessary? I have a script processing these videos and I'll have to modify it to include the 4th file if all files are necessary for dash to work correctly. I have no idea how to test a dash video to see what files are currently streaming or needed.


https://www.dropbox.com/sh/dnce1t99uzb7o51/AAC5xC96s_Kv33CcOFHN9Xkza?dl=0

**Comment by jeanlf** [comment]
>  I have no idea how to test a dash video to see what files are currently streaming or needed

The client decides which file to use, so as long as a quality is listed in the mpd, the source must be considered in use.
