### ISSUE TITLE
[Android-BUG] Crash when quickly reopen

### ISSUE THREAD

**Issue by echoaiya** [gpac/gpac#143]
Download the latest code source, and compile it.
Change Osmo4.java as follows:

```
/**
 * @see com.gpac.Osmo4.GpacCallback#onGPACReady()
 */
@Override
public void onGPACReady() {
    startupProgress.dismiss();
    Log.i(LOG_OSMO_TAG, "GPAC is ready"); //$NON-NLS-1$
    String url = "http://www.digitalprimates.net/dash/streams/mp4-live-template/mp4-live-mpd-AV-BS.mpd";
    openURLasync(url);
}
```

...

```
@Override
public boolean onKeyDown(int keyCode, KeyEvent event) {
    // Handle the back button
    if (keyCode == KeyEvent.KEYCODE_BACK) {
        // Stop the activity
        if ( mGLView != null )
            mGLView.disconnect();
        Osmo4.this.finish();

        return true;
    } else {
        return super.onKeyDown(keyCode, event);
    }

}
```

Install "Osmo4_android" and reopen it quickly. Repeat several times, I got "Unfortunately, Osmo4 has stopped".
Crash message as follows:

{
05-12 16:34:26.441: V/GPAC_WRAPPER(9330): MessageBox start Disconnected
05-12 16:34:26.443: D/Osmo4(9330): Disconnected
05-12 16:34:26.443: V/GPAC_WRAPPER(9330): MessageBox done Disconnected
05-12 16:34:26.447: V/GPAC_WRAPPER(9330): disconnected ...
05-12 16:34:26.447: V/WRAPPER_JNI(9330): disconnect::end
05-12 16:34:26.449: D/GraphicBuffer(9330): close handle(0x605722d0) (w:720 h:1184 f:2)
05-12 16:34:26.454: D/ActivityThread(9330): ACT-AM_ON_PAUSE_CALLED ActivityRecord{41cf0060 token=android.os.BinderProxy@41cef8e8 {com.gpac.Osmo4/com.gpac.Osmo4.Osmo4}}
05-12 16:34:26.456: D/ActivityThread(9330): ACT-PAUSE_ACTIVITY_FINISHING handled : 0 / android.os.BinderProxy@41cef8e8
05-12 16:34:26.459: I/Osmo4(9330): onStop called on activity
05-12 16:34:26.460: D/dalvikvm(9330): threadid=11: exiting
05-12 16:34:26.460: D/dalvikvm(9330): threadid=11: bye!
05-12 16:34:26.465: D/Osmo4(9330): Disconnecting instance...
05-12 16:34:26.465: D/Osmo4(9330): Destroying GPAC instance...
05-12 16:34:26.466: I/SurfaceView(9330): updateWindow -- onWindowVisibilityChanged, visibility = 8
05-12 16:34:26.466: I/SurfaceView(9330): Changes: creating=false format=false size=false visible=true left=false top=false mUpdateWindowNeeded=false mReportDrawNeeded=false redrawNeeded=false forceSizeChanged=false mVisible=true mRequestedVisible=false
05-12 16:34:26.467: I/SurfaceView(9330): Cur surface: Surface(name=null)/@0x41dc2b80
05-12 16:34:26.473: I/SurfaceView(9330): New surface: Surface(name=null)/@0x41dc2c50, vis=false, frame=Rect(0, 0 - 720, 1184)
05-12 16:34:26.473: I/SurfaceView(9330): Callback --> surfaceDestroyed
05-12 16:34:26.473: I/SurfaceView(9330): surfaceDestroyed callback +
05-12 16:34:26.499: V/WRAPPER_JNI(9330): disconnect::start
05-12 16:34:26.499: V/GPAC_WRAPPER(9330): disconnecting
05-12 16:34:26.499: V/GPAC_WRAPPER(9330): disconnected ...
05-12 16:34:26.499: V/WRAPPER_JNI(9330): disconnect::end
05-12 16:34:26.532: V/WRAPPER_JNI(9330): disconnect::start
05-12 16:34:26.533: V/GPAC_WRAPPER(9330): disconnecting
05-12 16:34:26.533: V/GPAC_WRAPPER(9330): disconnected ...
05-12 16:34:26.533: V/WRAPPER_JNI(9330): disconnect::end
05-12 16:34:26.533: V/WRAPPER_JNI(9330): free::start
05-12 16:34:26.533: V/GPAC_WRAPPER(9330): ~CNativeWrapper()
05-12 16:34:26.533: V/GPAC_WRAPPER(9330): shutdown
05-12 16:34:26.535: D/dalvikvm(9330): threadid=14: threadExitCheck(0x62cc4f30) count=0
05-12 16:34:26.536: D/dalvikvm(9330): threadid=14: thread exiting, not yet detached (count=0)
05-12 16:34:26.536: I/GPAC_WRAPPER(9330): Destroying a thread with attached data, env=0x62b92c78.
05-12 16:34:26.536: D/dalvikvm(9330): threadid=14: bye!
05-12 16:34:26.537: D/DROID_VIDEO(9330): Android Shutdown
05-12 16:34:26.537: D/DROID_VIDEO(9330): Android Delete Texture
05-12 16:34:26.537: E/libEGL(9330): call to OpenGL ES API with no current context (logged once per thread)
05-12 16:34:26.541: V/DROID_VIDEO(9330): Android Delete Texture DONE
05-12 16:34:26.541: V/DROID_VIDEO(9330): Android Shutdown DONE
05-12 16:34:26.541: D/DROID_VIDEO(9330): Android Shutdown
05-12 16:34:26.541: D/DROID_VIDEO(9330): Android Delete Texture
05-12 16:34:26.541: V/DROID_VIDEO(9330): Android Delete Texture DONE
05-12 16:34:26.541: V/DROID_VIDEO(9330): Android Shutdown DONE
05-12 16:34:26.541: D/DROID_VIDEO(9330): Android vout deinit
05-12 16:34:26.620: V/GPAC Android Audio(9330): [Android Audio] Shutdown START.
05-12 16:34:26.621: D/AudioTrack(9330): audiotrack 0x62dec680 stop done
05-12 16:34:26.621: D/AudioTrack(9330): ~audioTrack 0x62dec680
05-12 16:34:26.621: D/AudioTrackCenter(9330): removeTrack, trackPtr:0x62dec680
05-12 16:34:26.621: D/dalvikvm(9330): threadid=15: bye!
05-12 16:34:26.623: D/dalvikvm(9330): threadid=13: bye!
05-12 16:34:26.623: V/GPAC Android Audio(9330): [Android Audio] Shutdown DONE.
05-12 16:34:26.624: D/IPCThreadState(9330): [DN #5] BR_CLEAR_DEATH_NOTIFICATION_DONE cookie 0x62deea98
05-12 16:34:26.643: I/dalvikvm(9330): JNI ERROR (app bug): accessed deleted global reference 0x1d20040a
05-12 16:34:26.643: E/dalvikvm(9330): VM aborting
05-12 16:34:26.644: A/libc(9330): Fatal signal 6 (SIGABRT) at 0x00002472 (code=-6), thread 9345 (Thread-646)
}

How to solve the problem? Please help!

**Comment by canatella** [comment]
Could you try with my branch ? I think I had the same problem as you:

https://github.com/canatella/gpac/tree/cleanup-android-audio-driver

It's a pending pull request for now.

**Comment by echoaiya** [comment]
Hi canatella, what is the difference between your branch and gpac? Just cleanup? I tried your branch and still had the same problem.

**Comment by canatella** [comment]
I thought you're problem could be linked to having the java variable reference hold as global variables in gpac instead of a per driver variable which I fixed in my branch but it seems your problem is different. Could you build a debug release and use the android ndk addr2line tool too fetch the full stack trace of the abort?

**Comment by echoaiya** [comment]
I built a debug release and I got this:

05-13 09:53:36.625: I/DEBUG(6082): handle_request(15)
05-13 09:53:36.626: I/DEBUG(6082): check process 5913 name:com.gpac.Osmo4
05-13 09:53:36.626: I/DEBUG(6082): tid 5934 abort msg address is:0
05-13 09:53:36.626: I/DEBUG(6082): BOOM: pid=5913 uid=10122 gid=10122 tid=5934
05-13 09:53:36.627: I/DEBUG(6082): [OnPurpose Redunant in preset_info] pid: 5913, tid: 5934, name: Thread-313  >>> com.gpac.Osmo4 <<<
05-13 09:53:36.679: I/DEBUG(6082): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-13 09:53:36.680: I/DEBUG(6082): Build fingerprint: 'Sky/Sky_Device/Sky_Device:4.4.2/KOT49H/1421907856:user/test-keys'
05-13 09:53:36.680: I/DEBUG(6082): pid: 5913, tid: 5934, name: Thread-313  >>> com.gpac.Osmo4 <<<
05-13 09:53:36.680: I/DEBUG(6082): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
05-13 09:53:36.786: I/DEBUG(6082):     r0 00000000  r1 0000172e  r2 00000006  r3 00000000
05-13 09:53:36.786: I/DEBUG(6082):     r4 00000006  r5 00000000  r6 0000172e  r7 0000010c
05-13 09:53:36.786: I/DEBUG(6082):     r8 00004000  r9 40d55b74  sl 00000000  fp 63082adc
05-13 09:53:36.786: I/DEBUG(6082):     ip 00004000  sp 63082588  lr 400702b1  pc 4007f1f4  cpsr 000f0010
05-13 09:53:36.789: I/DEBUG(6082): backtrace:
05-13 09:53:36.789: I/DEBUG(6082):     #00  pc 000261f4  /system/lib/libc.so (tgkill+12)
05-13 09:53:36.789: I/DEBUG(6082):     #01  pc 000172ad  /system/lib/libc.so (pthread_kill+48)
05-13 09:53:36.789: I/DEBUG(6082):     #02  pc 000174c1  /system/lib/libc.so (raise+10)
05-13 09:53:36.789: I/DEBUG(6082):     #03  pc 000161f5  /system/lib/libc.so
05-13 09:53:36.789: I/DEBUG(6082):     #04  pc 00025aa4  /system/lib/libc.so (abort+4)
05-13 09:53:36.789: I/DEBUG(6082):     #05  pc 00001def  /system/lib/liblog.so (__android_log_assert+86)
05-13 09:53:36.789: I/DEBUG(6082):     #06  pc 00053927  /system/lib/libmedia.so (android::ClientProxy::releaseBuffer(android::Proxy::Buffer*)+98)
05-13 09:53:36.789: I/DEBUG(6082):     #07  pc 00050fc7  /system/lib/libmedia.so (android::AudioTrack::releaseBuffer(android::AudioTrack::Buffer*)+50)
05-13 09:53:36.789: I/DEBUG(6082):     #08  pc 00052af9  /system/lib/libmedia.so (android::AudioTrack::write(void const*, unsigned int)+168)
05-13 09:53:36.789: I/DEBUG(6082):     #09  pc 00085621  /system/lib/libandroid_runtime.so (writeToTrack(android::sp<android::AudioTrack> const&, int, signed char*, int, int)+44)
05-13 09:53:36.789: I/DEBUG(6082):     #10  pc 0008621f  /system/lib/libandroid_runtime.so
05-13 09:53:36.789: I/DEBUG(6082):     #11  pc 0008626b  /system/lib/libandroid_runtime.so
05-13 09:53:36.789: I/DEBUG(6082):     #12  pc 0001e74c  /system/lib/libdvm.so (dvmPlatformInvoke+112)
05-13 09:53:36.789: I/DEBUG(6082):     #13  pc 0004fa91  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+484)
05-13 09:53:36.789: I/DEBUG(6082):     #14  pc 00000214  /dev/ashmem/dalvik-jit-code-cache (deleted)
05-13 09:53:36.789: I/DEBUG(6082): stack:
05-13 09:53:36.790: I/DEBUG(6082):          63082548  00004000  
05-13 09:53:36.790: I/DEBUG(6082):          6308254c  00004000  
05-13 09:53:36.790: I/DEBUG(6082):          63082550  40d55b74  /system/lib/libmedia.so
05-13 09:53:36.790: I/DEBUG(6082):          63082554  00000000  
05-13 09:53:36.790: I/DEBUG(6082):          63082558  63082adc  [stack:5934]
05-13 09:53:36.790: I/DEBUG(6082):          6308255c  40085470  /system/lib/libc.so (snprintf+124)
05-13 09:53:36.790: I/DEBUG(6082):          63082560  74707572  
05-13 09:53:36.790: I/DEBUG(6082):          63082564  62206465  /data/app-lib/com.gpac.Osmo4-1/libavcodec.so
05-13 09:53:36.790: I/DEBUG(6082):          63082568  630825e4  [stack:5934]
05-13 09:53:36.790: I/DEBUG(6082):          6308256c  00000000  
05-13 09:53:36.790: I/DEBUG(6082):          63082570  4005496d  /system/lib/liblog.so
05-13 09:53:36.790: I/DEBUG(6082):          63082574  40d2f07c  /system/lib/libmedia.so
05-13 09:53:36.790: I/DEBUG(6082):          63082578  630825ec  [stack:5934]
05-13 09:53:36.790: I/DEBUG(6082):          6308257c  00000000  
05-13 09:53:36.790: I/DEBUG(6082):          63082580  00000015  
05-13 09:53:36.790: I/DEBUG(6082):          63082584  5d0e78c0  
05-13 09:53:36.790: I/DEBUG(6082):     #00  63082588  00000006  
05-13 09:53:36.790: I/DEBUG(6082):          6308258c  00000000  
05-13 09:53:36.790: I/DEBUG(6082):          63082590  0000172e  
05-13 09:53:36.790: I/DEBUG(6082):          63082594  00004000  
05-13 09:53:36.790: I/DEBUG(6082):          63082598  00004000  
05-13 09:53:36.790: I/DEBUG(6082):          6308259c  400702b1  /system/lib/libc.so (pthread_kill+52)
05-13 09:53:36.790: I/DEBUG(6082):     #01  630825a0  00000006  
05-13 09:53:36.790: I/DEBUG(6082):          630825a4  639f7320  
05-13 09:53:36.791: I/DEBUG(6082):          630825a8  41dc3a70  /dev/ashmem/dalvik-heap (deleted)
05-13 09:53:36.791: I/DEBUG(6082):          630825ac  400704c5  /system/lib/libc.so (raise+14)
05-13 09:53:36.791: I/DEBUG(6082):     #02  630825b0  630825bc  [stack:5934]
05-13 09:53:36.791: I/DEBUG(6082):          630825b4  4006f1f9  /system/lib/libc.so
05-13 09:53:36.794: I/DEBUG(6082): memory near r1:
05-13 09:53:36.794: I/DEBUG(6082):     0000170c ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.794: I/DEBUG(6082):     0000171c ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.794: I/DEBUG(6082):     0000172c ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.794: I/DEBUG(6082):     0000173c ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.794: I/DEBUG(6082):     0000174c ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.794: I/DEBUG(6082):     0000175c ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.794: I/DEBUG(6082):     0000176c ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.794: I/DEBUG(6082):     0000177c ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.794: I/DEBUG(6082):     0000178c ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.794: I/DEBUG(6082):     0000179c ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.795: I/DEBUG(6082):     000017ac ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.795: I/DEBUG(6082):     000017bc ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.795: I/DEBUG(6082):     000017cc ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.795: I/DEBUG(6082):     000017dc ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.795: I/DEBUG(6082):     000017ec ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.795: I/DEBUG(6082):     000017fc ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.795: I/DEBUG(6082): memory near r6:
05-13 09:53:36.795: I/DEBUG(6082):     0000170c ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.795: I/DEBUG(6082):     0000171c ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.795: I/DEBUG(6082):     0000172c ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.795: I/DEBUG(6082):     0000173c ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.795: I/DEBUG(6082):     0000174c ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.795: I/DEBUG(6082):     0000175c ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.795: I/DEBUG(6082):     0000176c ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.795: I/DEBUG(6082):     0000177c ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.795: I/DEBUG(6082):     0000178c ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.795: I/DEBUG(6082):     0000179c ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.795: I/DEBUG(6082):     000017ac ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.795: I/DEBUG(6082):     000017bc ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.795: I/DEBUG(6082):     000017cc ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.796: I/DEBUG(6082):     000017dc ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.796: I/DEBUG(6082):     000017ec ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.796: I/DEBUG(6082):     000017fc ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.796: I/DEBUG(6082): memory near r8:
05-13 09:53:36.796: I/DEBUG(6082):     00003fe0 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.796: I/DEBUG(6082):     00003ff0 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.796: I/DEBUG(6082):     00004000 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.796: I/DEBUG(6082):     00004010 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.796: I/DEBUG(6082):     00004020 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.796: I/DEBUG(6082):     00004030 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.796: I/DEBUG(6082):     00004040 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.796: I/DEBUG(6082):     00004050 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.796: I/DEBUG(6082):     00004060 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.796: I/DEBUG(6082):     00004070 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.796: I/DEBUG(6082):     00004080 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.796: I/DEBUG(6082):     00004090 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.796: I/DEBUG(6082):     000040a0 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.796: I/DEBUG(6082):     000040b0 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.796: I/DEBUG(6082):     000040c0 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.796: I/DEBUG(6082):     000040d0 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.796: I/DEBUG(6082): memory near r9:
05-13 09:53:36.796: I/DEBUG(6082):     40d55b54 40d54998 40d54770 40d54528 40d54620  
05-13 09:53:36.796: I/DEBUG(6082):     40d55b64 40d3e4a0 40d3e494 40d55528 40d554f8  
05-13 09:53:36.796: I/DEBUG(6082):     40d55b74 00000000 00000000 00000000 4008a18c  
05-13 09:53:36.796: I/DEBUG(6082):     40d55b84 40089fd0 400fa029 400ce960 4007e6d4  
05-13 09:53:36.797: I/DEBUG(6082):     40d55b94 4007e654 4007d658 40071705 400547ad  
05-13 09:53:36.797: I/DEBUG(6082):     40d55ba4 40068d00 40068c3c 400fb823 400fa0d1  
05-13 09:53:36.797: I/DEBUG(6082):     40d55bb4 4006858c 400687b0 400688b4 400fa14d  
05-13 09:53:36.797: I/DEBUG(6082):     40d55bc4 400fa117 40054cb5 400fa22d 400fa601  
05-13 09:53:36.797: I/DEBUG(6082):     40d55bd4 40054d99 40049d9c 4015028f 400fa89d  
05-13 09:53:36.797: I/DEBUG(6082):     40d55be4 400853f4 4007d53c 400fa6f1 4006f1c1  
05-13 09:53:36.797: I/DEBUG(6082):     40d55bf4 400fb5f5 40068cc0 40068d24 400fb49d  
05-13 09:53:36.797: I/DEBUG(6082):     40d55c04 400fa06f 400fa21b 401502a9 400fb759  
05-13 09:53:36.797: I/DEBUG(6082):     40d55c14 4014f9b5 400ce94c 40049dbc 40151229  
05-13 09:53:36.797: I/DEBUG(6082):     40d55c24 40150fc7 400fb67d 400aacb8 40150fcd  
05-13 09:53:36.797: I/DEBUG(6082):     40d55c34 4007e674 40095414 400aabe0 40d6be4d  
05-13 09:53:36.797: I/DEBUG(6082):     40d55c44 40068f0c 40068f1c 4007f348 4007d354  
05-13 09:53:36.797: I/DEBUG(6082): memory near fp:
05-13 09:53:36.797: I/DEBUG(6082):     63082abc 418e4750 00002000 00000002 630a4f58  
05-13 09:53:36.797: I/DEBUG(6082):     63082acc 00000001 00000005 41df8960 63082d54  
05-13 09:53:36.797: I/DEBUG(6082):     63082adc 41915a95 630a4f58 5a56dde6 401e725d  
05-13 09:53:36.797: I/DEBUG(6082):     63082aec 62f62c10 00000000 00000000 00000000  
05-13 09:53:36.797: I/DEBUG(6082):     63082afc 00000000 00000000 400c0bc8 00000000  
05-13 09:53:36.798: I/DEBUG(6082):     63082b0c 00000000 00000000 00000000 00000000  
05-13 09:53:36.798: I/DEBUG(6082):     63082b1c 00000000 00000000 00000000 00000000  
05-13 09:53:36.798: I/DEBUG(6082):     63082b2c 00000000 00000000 00000000 00000000  
05-13 09:53:36.798: I/DEBUG(6082):     63082b3c 0000009c 004e0ccc 00000000 6077f9f8  
05-13 09:53:36.798: I/DEBUG(6082):     63082b4c 00000000 00000000 00000000 00005df7  
05-13 09:53:36.798: I/DEBUG(6082):     63082b5c 62f629b8 61ac7504 5f47b8c0 0000fa00  
05-13 09:53:36.798: I/DEBUG(6082):     63082b6c 61d79878 017d1ee3 00000000 000003e8  
05-13 09:53:36.798: I/DEBUG(6082):     63082b7c 000003e8 00000000 017d1ee3 00000000  
05-13 09:53:36.798: I/DEBUG(6082):     63082b8c 61ac7504 62f85000 62f6292c 63082bd4  
05-13 09:53:36.798: I/DEBUG(6082):     63082b9c 61d77940 63082dd0 62f629b8 00000004  
05-13 09:53:36.798: I/DEBUG(6082):     63082bac 00000015 63082be4 61ac826c 63082bc0  
05-13 09:53:36.798: I/DEBUG(6082): memory near ip:
05-13 09:53:36.798: I/DEBUG(6082):     00003fe0 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.798: I/DEBUG(6082):     00003ff0 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.798: I/DEBUG(6082):     00004000 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.798: I/DEBUG(6082):     00004010 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.798: I/DEBUG(6082):     00004020 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.798: I/DEBUG(6082):     00004030 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.798: I/DEBUG(6082):     00004040 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.798: I/DEBUG(6082):     00004050 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.798: I/DEBUG(6082):     00004060 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.798: I/DEBUG(6082):     00004070 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.799: I/DEBUG(6082):     00004080 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.799: I/DEBUG(6082):     00004090 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.799: I/DEBUG(6082):     000040a0 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.799: I/DEBUG(6082):     000040b0 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.799: I/DEBUG(6082):     000040c0 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.799: I/DEBUG(6082):     000040d0 ffffffff ffffffff ffffffff ffffffff  
05-13 09:53:36.799: I/DEBUG(6082): memory near sp:
05-13 09:53:36.799: I/DEBUG(6082):     63082568 630825e4 00000000 4005496d 40d2f07c  
05-13 09:53:36.799: I/DEBUG(6082):     63082578 630825ec 00000000 00000015 5d0e78c0  
05-13 09:53:36.799: I/DEBUG(6082):     63082588 00000006 00000000 0000172e 00004000  
05-13 09:53:36.799: I/DEBUG(6082):     63082598 00004000 400702b1 00000006 639f7320  
05-13 09:53:36.799: I/DEBUG(6082):     630825a8 41dc3a70 400704c5 630825bc 4006f1f9  
05-13 09:53:36.799: I/DEBUG(6082):     630825b8 00000000 ffffffdf 00000000 00000000  
05-13 09:53:36.799: I/DEBUG(6082):     630825c8 00000000 7c2f364f 00000000 40d2f07c  
05-13 09:53:36.799: I/DEBUG(6082):     630825d8 639f7320 4007eaa8 4005496d 40054df3  
05-13 09:53:36.799: I/DEBUG(6082):     630825e8 00000000 65737341 6f697472 6166206e  
05-13 09:53:36.799: I/DEBUG(6082):     630825f8 64656c69 2821203a 70657473 6e756f43  
05-13 09:53:36.800: I/DEBUG(6082):     63082608 3d3c2074 6e556d20 656c6572 64657361  
05-13 09:53:36.800: I/DEBUG(6082):     63082618 20262620 726e556d 61656c65 20646573  
05-13 09:53:36.800: I/DEBUG(6082):     63082628 6d203d3c 6d617246 756f4365 0029746e  
05-13 09:53:36.800: I/DEBUG(6082):     63082638 00000000 00000000 00000000 00000000  
05-13 09:53:36.800: I/DEBUG(6082):     63082648 00000000 00000000 00000000 00000000  
05-13 09:53:36.800: I/DEBUG(6082):     63082658 00000000 00000000 00000000 00000000  
05-13 09:53:36.800: I/DEBUG(6082): code around pc:
05-13 09:53:36.800: I/DEBUG(6082):     4007f1d4 e8bd00f0 e3700a01 912fff1e e2600000  
05-13 09:53:36.800: I/DEBUG(6082):     4007f1e4 ea00b702 e92d50f0 e3a07f43 ef000000  
05-13 09:53:36.800: I/DEBUG(6082):     4007f1f4 e8bd50f0 e3700a01 912fff1e e2600000  
05-13 09:53:36.800: I/DEBUG(6082):     4007f204 ea00b6fa e92d50f0 e3a070ee ef000000  
05-13 09:53:36.800: I/DEBUG(6082):     4007f214 e8bd50f0 e3700a01 912fff1e e2600000  
05-13 09:53:36.800: I/DEBUG(6082):     4007f224 ea00b6f2 00000000 00000000 e92d400f  
05-13 09:53:36.800: I/DEBUG(6082):     4007f234 e1a03000 e1a00001 e1a01003 eb000040  
05-13 09:53:36.800: I/DEBUG(6082):     4007f244 e8bd400f e12fff1e e320f000 e92d403f  
05-13 09:53:36.800: I/DEBUG(6082):     4007f254 e2522040 ba00002c e1a05001 e2455c01  
05-13 09:53:36.800: I/DEBUG(6082):     4007f264 f5d5f000 f5d5f040 f5d5f080 f5d5f0c0  
05-13 09:53:36.801: I/DEBUG(6082):     4007f274 e2411040 e2400040 e1a05000 e1a04001  
05-13 09:53:36.801: I/DEBUG(6082):     4007f284 f424020d f424420d f405022d f405422d  
05-13 09:53:36.801: I/DEBUG(6082):     4007f294 e2522040 ba00001c e2411040 e2400040  
05-13 09:53:36.801: I/DEBUG(6082):     4007f2a4 e1a05000 e1a04001 f424020d f424420d  
05-13 09:53:36.801: I/DEBUG(6082):     4007f2b4 f405022d f405422d e2522040 ba000012  
05-13 09:53:36.801: I/DEBUG(6082):     4007f2c4 e2411040 e2400040 e1a05000 e1a04001  
05-13 09:53:36.801: I/DEBUG(6082): code around lr:
05-13 09:53:36.801: I/DEBUG(6082):     40070290 447b4b13 42b3e010 4812d10e 44786a1e  
05-13 09:53:36.801: I/DEBUG(6082):     400702a0 eb08f7f8 e9d8f00d 46224631 ef9cf00e  
05-13 09:53:36.801: I/DEBUG(6082):     400702b0 d00a3001 e00b2400 2b00681b 480ad1eb  
05-13 09:53:36.801: I/DEBUG(6082):     400702c0 44782403 eaf6f7f8 f001e002 6804fa1b  
05-13 09:53:36.801: I/DEBUG(6082):     400702d0 fa18f001 46206005 bf00bd70 0005095a  
05-13 09:53:36.801: I/DEBUG(6082):     400702e0 0005094e 00050946 00050922 bf7ef7ff  
05-13 09:53:36.801: I/DEBUG(6082):     400702f0 43f0e92d 4a3d4b3c 589c447b 6823b08b  
05-13 09:53:36.802: I/DEBUG(6082):     40070300 460d4606 f0019309 46a1f9fd 8000f8d0  
05-13 09:53:36.802: I/DEBUG(6082):     40070310 d0482d00 f00f4628 280ffed5 d8444604  
05-13 09:53:36.802: I/DEBUG(6082):     40070320 ffe4f7ff d1064286 4629200f e8a2f00d  
05-13 09:53:36.802: I/DEBUG(6082):     40070330 d03c2800 482ee02e f7f84478 482dea3a  
05-13 09:53:36.802: I/DEBUG(6082):     40070340 e0154478 d11342b0 482b6a06 f7f84478  
05-13 09:53:36.802: I/DEBUG(6082):     40070350 4a2aeab2 447a2120 a8014633 e84af015  
05-13 09:53:36.802: I/DEBUG(6082):     40070360 a8012101 ef52f021 46061c42 e011d104  
05-13 09:53:36.802: I/DEBUG(6082):     40070370 28006800 e02cd1e6 46294630 f00d4622  
05-13 09:53:36.802: I/DEBUG(6082):     40070380 1c43e8de d11e4607 f9bcf001 29046801  



But I do not know how to use addr2line to fetch stack trace.

**Comment by davideberra** [comment]
Did you sort it out? I have the same crash with my app and I really don't have a clue about it
