### ISSUE TITLE
MP4Box writes audio object type 0x67 incorrectly

### ISSUE THREAD

**Issue by jkcalhoun** [gpac/gpac#1430]
When MP4Box imports an ADTS file that indicates that it contains an MPEG-2 AAC encoding, as opposed to an MPEG-4 AAC encoding, it writes it using object type indication 0x67 instead of object type indication 0x40, presumably in order to distinguish it as compatible with MPEG-2.

This in itself is problematic, because object type 0x67 is far less interoperable than object type 0x40, which is also capable of carrying MPEG-2 AAC encodings.

But even worse for interoperability, MP4Box writes object type 0x67 incorrectly. According to ISO/IEC 14496-3 § 9.D.2.1, for object types 0x66, 0x67, and 0x68 the decSpecificInfo is supposed to be an adif_Header(), the first four bytes of which are ‘ADIF’. But MP4Box is instead writing the same AudioSpecificConfig() that it writes for mp4a.40.2, correctly in that case but incorrectly in this case.

The best possible interoperability would be achieved if MP4Box were always to store AAC encodings using object type 0x40, regardless of whether they are imported from a file that indicates that they are compatible with MPEG-2.

Attaching an MPEG-2 AAC encoding in an ADTS file.
[Kimiko Ishizaka - Bach - Well-Tempered Clavier, Book 1 - 29 Prelude No. 15 in G major, BWV 860.FhG.MPEG-2.adts.zip](https://github.com/gpac/gpac/files/4333140/Kimiko.Ishizaka.-.Bach.-.Well-Tempered.Clavier.Book.1.-.29.Prelude.No.15.in.G.major.BWV.860.FhG.MPEG-2.adts.zip)

**Comment by jeanlf** [comment]
You are correct. I just deprecated this mode - this should now be fixed in master and filters, thanks for the report and analysis
