### ISSUE TITLE
What DRM file i have to use for decrypt this mp4 file? 

### ISSUE THREAD

**Issue by bangladino** [gpac/gpac#1432]
**I have this infor about the mp4 file** 

[iso file] Unknown box type senc in parent stbl
* Movie Info *
        Timescale 1000 - 2 tracks
        Computed Duration 00:21:00.233 - Indicated Duration 00:21:00.233
        Fragmented File: no
        File Brand isom - version 512
                Compatible brands: isom iso2 avc1 mp41
        Created: UNKNOWN DATE   Modified: UNKNOWN DATE
File has no MPEG4 IOD/OD

iTunes Info:
        Encoder Software: Lavf58.22.100
1 UDTA types: meta (1)

Track # 1 Info - TrackID 1 - TimeScale 16000
Media Duration 00:21:00.233 - Indicated Duration 00:21:00.233
Track has 1 edit lists: track duration is 00:21:00.233
Media Info: Language "Undetermined (und)" - Type "vide:encv" - 37807 samples
Visual Track layout: x=0 y=0 width=1600 height=900
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x21
AVC/H264 Video - Visual Size 1600 x 900
        AVC Info: 1 SPS - 1 PPS - Profile High @ Level 4
        NAL Unit length bits: 32
        Chroma format YUV 4:2:0 - Luma bit depth 8 - chroma bit depth 8
        SPS#1 hash: EDD294F245B490F4D26FD250F0CFD33EF72EDA97
        PPS#1 hash: A3EE4CDCBCFE65012A7D3860B430E3AC70377532
Self-synchronized

*Encrypted stream - CENC scheme cenc (version: major=1, minor=0)
Initialization Vector size: 64 bits
        RFC6381 Codec Parameters: avc1.640028
        Average GOP length: 227 samples

Track # 2 Info - TrackID 2 - TimeScale 44100
Media Duration 00:21:00.169 - Indicated Duration 00:21:00.169
Track has 1 edit lists: track duration is 00:21:00.170
Media Info: Language "Undetermined (und)" - Type "soun:enca" - 54271 samples
MPEG-4 Config: Audio Stream - ObjectTypeIndication 0x40
MPEG-4 Audio AAC LC - 2 Channel(s) - SampleRate 44100
Synchronized on stream 1

*Encrypted stream - CENC scheme cenc (version: major=1, minor=0)
Initialization Vector size: 64 bits
        RFC6381 Codec Parameters: mp4a.40.2
Alternate Group ID 1
        All samples are sync

**Comment by jeanlf** [comment]
you need a DRM file describing the keyID/key for both tracks, the rest of the parameters will be ignored. Example files are [available here](https://github.com/gpac/testsuite/tree/filters/media/encryption).

**Comment by bangladino** [comment]
> you need a DRM file describing the keyID/key for both tracks, the rest of the parameters will be ignored. Example files are [available here](https://github.com/gpac/testsuite/tree/filters/media/encryption).


I have already tried isma.xml
but the terminal stops working when I run the command

**Comment by jeanlf** [comment]
did you try to decrypt it using MP4Box ?

**Comment by bangladino** [comment]
> did you try to decrypt it using MP4Box ?

yes i tried to decrypt with MP4Box 

`mp4box -decrypt isma.xml test.mp4 -out  decrypted.mp4`

**Comment by jeanlf** [comment]
what is the output of the command line?

**Comment by bangladino** [comment]
> what is the output of the command line?

i don't understand .. 

How can I trace the drm file used to encrypt the video?

**Comment by jeanlf** [comment]
> i don't understand ..
is the execution of `MP4Box -decrypt ...` saying anthing ?

> How can I trace the drm file used to encrypt the video?
you can't, but you can extract the KID used in the stream: do `MP4Box -diso encrypted.mp4` and checj the 'tenc' box for the default KID used (and potentially 'seig' box if rolling keys are used). You will then need to get the key for each of the KID used

**Comment by bangladino** [comment]
> MP4Box -diso encrypted.mp4

i have this result with   `MP4Box -diso test.mp4 -out test.txt`


<?xml version="1.0" encoding="UTF-8"?>

<IsoMediaFile xmlns="urn:mpeg:isobmff:schema:file:2016" Name="test.mp4">
<FileTypeBox Size="32" Type="ftyp" Specification="p12" Container="file" MajorBrand="isom" MinorVersion="512">
<BrandEntry AlternateBrand="isom"/>
<BrandEntry AlternateBrand="iso2"/>
<BrandEntry AlternateBrand="avc1"/>
<BrandEntry AlternateBrand="mp41"/>
</FileTypeBox>
<FreeSpaceBox Size="8" Type="free" Specification="p12" Container="*" dataSize="0">
</FreeSpaceBox>
<MediaDataBox Size="99883818" Type="mdat" Specification="p12" Container="file" dataSize="99883810">
</MediaDataBox>
<MovieBox Size="2648179" Type="moov" Specification="p12" Container="file" >
<MovieHeaderBox Size="108" Type="mvhd" Version="0" Flags="0" Specification="p12" Container="moov" CreationTime="0" ModificationTime="0" TimeScale="1000" Duration="1260233" NextTrackID="3">
</MovieHeaderBox>
<TrackBox Size="1449646" Type="trak" Specification="p12" Container="moov" >
<TrackHeaderBox Size="92" Type="tkhd" Version="0" Flags="3" Specification="p12" Container="trak" CreationTime="0" ModificationTime="0" TrackID="1" Duration="1260233" Width="1600.00" Height="900.00">
<Matrix m11="0x00010000" m12="0x00000000" m13="0x00000000" m21="0x00000000" m22="0x00010000" m23="0x00000000" m31="0x00000000" m32="0x00000000" m33="0x40000000"/>
</TrackHeaderBox>
<EditBox Size="36" Type="edts" Specification="p12" Container="trak" >
<EditListBox Size="28" Type="elst" Version="0" Flags="0" Specification="p12" Container="edts" EntryCount="1">
<EditListEntry Duration="1260233" MediaTime="1067" MediaRate="1"/>
</EditListBox>
</EditBox>
<MediaBox Size="1449510" Type="mdia" Specification="p12" Container="trak" >
<MediaHeaderBox Size="32" Type="mdhd" Version="0" Flags="0" Specification="p12" Container="mdia" CreationTime="0" ModificationTime="0" TimeScale="16000" Duration="20163728" LanguageCode="und">
</MediaHeaderBox>
<HandlerBox Size="45" Type="hdlr" Version="0" Flags="0" Specification="p12" Container="mdia meta minf" hdlrType="vide" Name="VideoHandler" reserved1="0" reserved2="data:application/octet-string,000000000000000000000000">
</HandlerBox>
<MediaInformationBox Size="1449425" Type="minf" Specification="p12" Container="mdia" >
<VideoMediaHeaderBox Size="20" Type="vmhd" Version="0" Flags="1" Specification="p12" Container="minf" >
</VideoMediaHeaderBox>
<DataInformationBox Size="36" Type="dinf" Specification="p12" Container="minf meta" >
<DataReferenceBox Size="28" Type="dref" Version="0" Flags="0" Specification="p12" Container="dinf" >
<URLDataEntryBox Size="12" Type="url " Version="0" Flags="1" Specification="p12" Container="dref" >

</URLDataEntryBox>
</DataReferenceBox>
</DataInformationBox>
<SampleTableBox Size="1449361" Type="stbl" Specification="p12" Container="minf" >
<SampleDescriptionBox Size="231" Type="stsd" Version="0" Flags="0" Specification="p12" Container="stbl" >
<MPEGVisualSampleDescriptionBox Size="215" Type="encv" Specification="p12" Container="stsd"  DataReferenceIndex="1" Width="1600" Height="900" XDPI="4718592" YDPI="4718592" BitDepth="24">
<AVCConfigurationBox Size="49" Type="avcC" Specification="p15" Container="avc1 avc2 avc3 avc4 encv resv ipco" >
<AVCDecoderConfigurationRecord configurationVersion="1" AVCProfileIndication="100" profile_compatibility="0" AVCLevelIndication="40" nal_unit_size="4" chroma_format="YUV 4:2:0" luma_bit_depth="8" chroma_bit_depth="8">
<SequenceParameterSet size="26" content="data:application/octet-string,67640028ACD94064073F9E10000003001000000303C8F1831960"/>
<PictureParameterSet size="4" content="data:application/octet-string,68EF8FCB"/>
</AVCDecoderConfigurationRecord>
</AVCConfigurationBox>
<ProtectionSchemeInfoBox Size="80" Type="sinf" Specification="p12" Container="ipro sample_entry" >
<OriginalFormatBox Size="12" Type="frma" Specification="p12" Container="sinf rinf" data_format="avc1">
</OriginalFormatBox>
<SchemeTypeBox Size="20" Type="schm" Version="0" Flags="0" Specification="p12" Container="sinf rinf" scheme_type="cenc" scheme_version="65536" >
</SchemeTypeBox>
<SchemeInformationBox Size="40" Type="schi" Specification="p12" Container="sinf rinf" >
<TrackEncryptionBox Size="32" Type="tenc" Version="0" Flags="0" Specification="cenc" Container="schi" isEncrypted="1" IV_size="8" KID="0x2E0D5EB4B1C87D0A03E57C7BAD27102B">
</TrackEncryptionBox>
</SchemeInformationBox>
</ProtectionSchemeInfoBox>
</MPEGVisualSampleDescriptionBox>
</SampleDescriptionBox>

**Comment by bangladino** [comment]
I need to solve this situation...  it's possible to build a player for this encrypted file...or to decrypt with the    `KID="0x2E0D5EB4B1C87D0A03E57C7BAD27102B"`

**Comment by jeanlf** [comment]
a KID is not a key value it's just an ID, you need to get the original key value used somehow to decrypt the file...

**Comment by bangladino** [comment]
> decrypt


what can I do with KID then?

**Comment by jeanlf** [comment]
not much if you don't have the associated key ...

**Comment by bangladino** [comment]
> not much if you don't have the associated key ...

ok sir. Thanks for you assistance
