### ISSUE TITLE
ffdec filter: avcodec_open2  has warnings，when decoding with avcodec_decode_video2, there's error 

### ISSUE THREAD

**Issue by wchnjstar123** [gpac/gpac#1434]
Hi,
avcodec_alloc_context3->avcodec_open2, then ffmpeg prints warnings:
![image](https://user-images.githubusercontent.com/38243755/77052912-7dbc5a80-6a08-11ea-9859-fa226d20e085.png)
According to ffmeg, the parameters such as width/height are wrong, I check  ctx->decoder, its info like the pic shows:
![image](https://user-images.githubusercontent.com/38243755/77055428-d2ada000-6a0b-11ea-9f58-927e3c4396e9.png)

when I set width/height, the same problem is still existing.  How to fix it ?  By the way, I run on win10.

**Comment by jeanlf** [comment]
could you upload your source file?

**Comment by wchnjstar123** [comment]
[ff_dec.zip](https://github.com/gpac/gpac/files/4355174/ff_dec.zip)

The code segment is between line 677 and 706.

**Comment by wchnjstar123** [comment]
According debug info,  the data format in extradata shuld be as follows, I already check the content, it's correct.  So I'd like to assure how to fill the extradata for setting sps/pps.

ps: For H264, just set sps+pps

aligned(8) class HEVCDecoderConfigurationRecord
{
    unsigned int(8) configurationVersion = 1;
    unsigned int(2) general_profile_space;
    unsigned int(1) general_tier_flag;
    unsigned int(5) general_profile_idc;
    unsigned int(32) general_profile_compatibility_flags;
    unsigned int(48) general_constraint_indicator_flags;
    unsigned int(8) general_level_idc;
    bit(4) reserved = ‘1111’b;
    unsigned int(12) min_spatial_segmentation_idc;
    bit(6) reserved = ‘111111’b;
    unsigned int(2) parallelismType;
    bit(6) reserved = ‘111111’b;
    unsigned int(2) chroma_format_idc;
    bit(5) reserved = ‘11111’b;
    unsigned int(3) bit_depth_luma_minus8;
    bit(5) reserved = ‘11111’b;
    unsigned int(3) bit_depth_chroma_minus8;
    bit(16) avgFrameRate;
    bit(2) constantFrameRate;
    bit(3) numTemporalLayers;
    bit(1) temporalIdNested;
    unsigned int(2) lengthSizeMinusOne;
    unsigned int(8) numOfArrays;
    for (j=0; j < numOfArrays; j++)
    {
        bit(1) array_completeness;
        unsigned int(1) reserved = 0;
        unsigned int(6) NAL_unit_type;
        unsigned int(16) numNalus;
        for (i=0; i< numNalus; i++)
        {
            unsigned int(16) nalUnitLength;
            bit(8*nalUnitLength) nalUnit;
        }
    }
}

**Comment by jeanlf** [comment]
I meant what is the content you are trying to decode, not the source code - I know where this one is :)

**Comment by jeanlf** [comment]
No news closing
