### ISSUE TITLE
.m3u8 video ignores audio track

### ISSUE THREAD

**Issue by dreamindigital** [gpac/gpac#1437]
version: 0.9.0-DEV-rev3352-gaf6005729-filters

MP4Box -dash 4000 -profile dashavc264:live video.mp4#video audio.m4a#audio -out finalvideo.m3u8

This results in expected video playback but without an audio track. Adding :dual to the output produces an .mpd manifest that works as expected. 

The audio track is referenced in the manifest:
#EXT-X-STREAM-INF:BANDWIDTH=196269,CODECS="mp4a.40.2"
finalvideo_2.m3u8

The contents of that file are never loaded.

**Comment by jeanlf** [comment]
indeed we were not producing correct component description. Could you check with latest git ?

**Comment by dreamindigital** [comment]
This appears to do the trick

**Comment by jeanlf** [comment]
good, closing
