### ISSUE TITLE
MP4Box should mark HEVC CRA as sync samples

### ISSUE THREAD

**Issue by cconcolato** [gpac/gpac#144]
This issue was initially raised on SourceForge (https://sourceforge.net/p/gpac/discussion/287547/thread/ae1ad5e4/?limit=25#8d7b).

According to ISO/IEC 14496-15:2014 and Cor1, CRA samples are sync samples.

**Comment by rbouqueau** [comment]
I did this because of an email of Thomas Stockhammer, see the involved commit:
https://sourceforge.net/p/gpac/code/5424/

Maybe this info is now outdated?

**Comment by cconcolato** [comment]
Don't know but the link you gave in the commit is broken. The DASH-IF document that talks about HEVC is now: http://dashif.org/wp-content/uploads/2015/04/DASH-IF-IOP-v3.0.pdf

**Comment by jeanlf** [comment]
Wrong issue -  CRA are not sync samples unless we are sure they don't references (which is usually not the case). They are however mapped to the 'rap ' sample group and are of sap type 3.
