### ISSUE TITLE
bitstream will not be compliant, try increasing segment duration or reencoding for better keyframe alignment

### ISSUE THREAD

**Issue by dilida2019** [gpac/gpac#1442]
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Hello,I'm using MP4box inside a web server to generate livestream.
I'm having trouble since it started.

ffmpeg encoding:
`ffmpeg -i E:/video/input.mp4 -threads 4 -preset veryfast -c:v libx264 -profile:v main -level 4.0 -s:v 640x360 -b:v 300k -pix_fmt yuv420p -refs 3 -bf 3 -g 75 -keyint_min 25 -b_strategy 1 -flags +cgop -sc_threshold 0 -movflags negative_cts_offsets+faststart -an -y dilida/input_video_360P.mp4`

mp4box encoding:
`MP4Box -dash 264600 -frag 264600 -dash-scale 44100 -bound -mem-frags -rap -profile dashavc264:live -min-buffer 12000 -bs-switching no -sample-groups-traf -single-traf -subsegs-per-sidx -1 -segment-name "input/$RepresentationID$/$Number$$Init=i$" -out E:/video/dilida/two/output.mpd E:/video/dilida/input_video_360P.mp4#trackID=1:id=360P:period=p0 E:/video/dilida/input_video_480P.mp4#trackID=1:id=480P:period=p0 E:/video/dilida/input_video_720P.mp4#trackID=1:id=720P:period=p0 E:/video/dilida/input_video_1080P.mp4#trackID=1:id=1080P:period=p0 E:/video/dilida/input_video_1080P+.mp4#trackID=1:id=1080P+:period=p0 E:/video/dilida/input_audio_128k.m4a#trackID=1:id=128k:period=p0`

All work fine on all common browsers,but set playback rate sometimes calls the wait event.

warning:
`[DASH] Files have non-proportional track layouts (640x360 vs 853x480) but sample size and aspect ratio match, assuming precision issue`

error:
`[DASH] Segment E:/video/dilida/two/input/360P/38.m4s (Number #38): drift between MPD timeline and tfdt exceeds 50% of segment duration (MPD time minus TFDT 3.031250 secs) - bitstream will not be compliant, try increasing segment duration or reencoding for better keyframe alignment [DASH] Segment E:/video/dilida/two/input/360P/50.m4s (Number #50): drift between MPD timeline and tfdt exceeds 50% of segment duration (MPD time minus TFDT 3.084375 secs) - bitstream will not be compliant, try increasing segment duration or reencoding for better keyframe alignment`

Thanks!

**Comment by jeanlf** [comment]
looks like you have a problem of key frame alignment across your sources. Did you try to inspect the encoded source key frames (eg, `MP4Box -diso source.mp4`and look for stss box in xml) ?
