### ISSUE TITLE
Does MP4Client support seeking during playing at branch filters?

### ISSUE THREAD

**Issue by zhao-l13** [gpac/gpac#1443]
I have downloaded your filters  branch code and built it following the wiki. It shows that it is ok to use the MP4Client to play MP4 and MPD file. But when I drag the time line to seek during playing, both the MP4 and MPD with get stuck. And MP4 will resume after about 10 seconds, MPD  will not.
So I want to confirm that does the MP4Client support seeking during playing or any plan to support it?
Thanks very much.
LULU

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by zhao-l13** [comment]
Hi,
   I pull the latest code, and find that it is ok in the master branch to seek for MP4Client. But I build the filters branch and build failed.
   I still want to know if the filters branch support seek in MP4Client ?
Thanks.

**Comment by jeanlf** [comment]
seeking should be working fine from local playback, we're currently fixing a few issues for http-based playback, stay tuned.

**Comment by jeanlf** [comment]
Should now be fixed reopen if needed
