### ISSUE TITLE
[IsoMedia] Track 3 is disabled, ignoring track - you may retry by specifying alltk option

### ISSUE THREAD

**Issue by dwgero** [gpac/gpac#1447]
There is no "alltk" option in the mp4box documentation.

Command line: mp4box -frag 10000 foo.mp4

foo.mp4 had 5 tracks.  Track 3 was a second audio track.

There was also a Track 5 that had Chapters info.  It too was disabled.

How do I get all the tracks?  I just want a straight-thru copy with fragmenting.

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
mp4box does not document the entire set of options of GPAC, I need to add a howto on that topic.
The alltk is an option of the MP4 demuxer, see `gpac -hx mp4dmx` 
To enable the option, either pass it locally to the source:
`MP4Box -add source.mp4:sopt:alltk -new dest.mp4`

or globally for all sources:
`MP4Box -frag 1000 source.mp4 --alltk`
