### ISSUE TITLE
E-AC3 support and the ability to swap Track order

### ISSUE THREAD

**Issue by teb** [gpac/gpac#1448]
hi, im trying to make a compliant mp4 file with the following components:
1. AVC video
2. AAC-LC audiotrack as the first audio
3. E-AC3 audiotrack as the second audio
4. stpp (TTML) Sub track as the first track.

Version: MP4Box - GPAC version 0.8.0-rev217-g5b37b21ad-master
1. Mp4box doesnt seem to mux my e-ac3 track so i had to use ffmpeg to remux my TS to mp4. Am i doing something wrong?
2. Problem is that ffmpeg is complaining on my aac track and i had to extract it and remerge it via mp4box where it placed it self AFTER the e-ac3 track with a UND language as well
3.Tried to figure out how i can swap the track order, but the -swap.track-id just change the ID-string not the order

```
MP4Box -info test6.mp4
* Movie Info *
        Timescale 1000 - 4 tracks
        Computed Duration 02:09:12.234 - Indicated Duration 02:09:12.234
        Fragmented File: no
        File suitable for progressive download (moov before mdat)
        File Brand isom - version 512
                Compatible brands: isom iso2 avc1 mp41
        Created: UNKNOWN DATE   Modified: UNKNOWN DATE
File has root IOD (9 bytes)
Scene PL 0xff - Graphics PL 0xff - OD PL 0xff
Visual PL: ISO Reserved Profile (0x15)
Audio PL: AAC Profile @ Level 2 (0x29)
No streams included in root OD

iTunes Info:
        Encoder Software: Lavf58.42.100
1 UDTA types: meta (1)

Track # 1 Info - TrackID 1 - TimeScale 90000
Media Duration 02:09:12.200 - Indicated Duration 02:09:12.200
Track has 1 edit lists: track duration is 02:09:12.200
Media Info: Language "Undetermined (und)" - Type "vide:avc1" - 193805 samples
Visual Info: width=1920 height=1080 (depth=24 bits)
Visual Track layout: x=0 y=0 width=1920 height=1080
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x21
AVC/H264 Video - Visual Size 1920 x 1080
        AVC Info: 1 SPS - 1 PPS - Profile High @ Level 4.1
        NAL Unit length bits: 32
        Pixel Aspect Ratio 1:1 - Indicated track size 1920 x 1080
        Chroma format YUV 4:2:0 - Luma bit depth 8 - chroma bit depth 8
        SPS#1 hash: 9C41178E52936C4C2425E2AABBA0CBC9C5B0C529
        PPS#1 hash: C1F6BE0ACBB8ADDB9680327BEEAF0D852C9D3146
Self-synchronized
        RFC6381 Codec Parameters: avc1.640029
        Average GOP length: 100 samples

Track # 2 Info - TrackID 3 - TimeScale 48000
Media Duration 02:09:12.224 - Indicated Duration 02:09:12.224
Track has 1 edit lists: track duration is 02:09:12.224
Media Info: Language "English (eng)" - Type "soun:ec-3" - 242257 samples
        EC-3 stream - Sample Rate 48000 - 5.1 channel(s) - bitrate 448
        RFC6381 Codec Parameters: ec-3
Alternate Group ID 1
        All samples are sync

Track # 3 Info - TrackID 2 - TimeScale 48000
Media Duration 02:09:12.234 - Indicated Duration 02:09:12.234
Media Info: Language "Undetermined (und)" - Type "soun:mp4a" - 363386 samples
MPEG-4 Config: Audio Stream - ObjectTypeIndication 0x40
MPEG-4 Audio AAC LC (AOT=2 implicit) - 2 Channel(s) - SampleRate 48000
Synchronized on stream 1
        RFC6381 Codec Parameters: mp4a.40.2
        All samples are sync

Track # 4 Info - TrackID 4 - TimeScale 1000
Media Duration 02:09:02.400 - Indicated Duration 02:09:02.400
Media Info: Language "Norwegian (nor)" - Type "subt:stpp" - 1825 samples
XML Subtitle Stream - namespace http://www.w3.org/ns/ttml
 Size 0 x 0 - Translation X=0 Y=0 - Layer 0
        RFC6381 Codec Parameters: stpp
        All samples are sync

```

**Comment by jeanlf** [comment]
1) eac-3 support is in 0.9.0, checkout filters branch

2) You cannot change track order of a file, you need to re-import the tracks in the desired order, for example:
```
MP4Box -add $SRC#Video -add $SRC#ID=AAC_ID  -add $SRC#ID=EAC_ID -new $DST
```

**Comment by teb** [comment]
thx! ill test

**Comment by teb** [comment]
Running dev 9.0 branch i still get :

` ./MP4Box  -add Test10_CRF18_maxrate15mb.mp4 -add 46273_8-FIN_Tarhapiv_TRL-FIN_1080p_25.ec3# -add 46273_Tarhapiv_TRL_nor_Full_25.ttml -add 46273_Tarhapiv_TRL_dan_Full_25.ttml test2.mp4
[iso file] Track with no samples but duration defined, ignoring duration
IsoMedia import AiB_Test10_CRF18_maxrate15mb.mp4 - track ID 1 - Video (size 1920 x 1080)
[iso file] Track with no samples but duration defined, ignoring duration
IsoMedia import AiB_Test10_CRF18_maxrate15mb.mp4 - track ID 2 - Audio (SR 48000 - 2 channels)
[Importer] Error probing 46273_8-FIN_Tarhapiv_TRL-FIN_1080p_25.ec3
Error importing 46273_8-FIN_Tarhapiv_TRL-FIN_1080p_25.ec3#ID=EAC_ID: Filter not found for the desired type`

**Comment by jeanlf** [comment]
make sure you use the latest git (1.0, not 0.9). If still here, this must be source-related - could you upload your input ec3 file ?
