### ISSUE TITLE
Segment replacement or discarding with AgressiveSwitching

### ISSUE THREAD

**Issue by mdasari823** [gpac/gpac#1450]
Hi, I am using AgressiveSwitching for my ABR algorithm in MP4Client. I think it is switching faster, but I thought it would also switch fast and replace or discard the existing low bitrate segments by downloaidng high bitrate segments if the network bandwidth becomes better. But right now, I don't see any such discarding or redownloading of the same segment with better quality. Does MP4Client has this?

**Comment by jeanlf** [comment]
This is only possible when manually switching qualities through the `gf_dash_switch_quality`; in automatic adaptation the client never trashes a completed segment.
Note that this will no longer be supported at all in 0.9.0
