### ISSUE TITLE
MP4Box inserts only 1024 bytes of 65588

### ISSUE THREAD

**Issue by CoSoCo** [gpac/gpac#1451]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...).. I can share files if necessary.

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

As I was not able to reopen a issue, I open a new one.

I have tried to insert a 65588 bytes udta box in a .MOV video, but only 1024 bytes were inserted.

For the details please see: https://github.com/gpac/gpac/issues/1431#issuecomment-607541897

**Comment by jeanlf** [comment]
see #1431
