### ISSUE TITLE
UUID is read incorrectly

### ISSUE THREAD

**Issue by mc0re** [gpac/gpac#1456]
According to the type definition `GF_PIFFProtectionSystemHeaderBox` and to the standard, the UUID box has a version byte and 3-byte flags field.
But when reading, this information is not read out by `gf_isom_full_box_read` - the "max_version_plus_one" is set to 0.
I tried just setting it to one, but then some length warnings appeared. Please, fix.
---
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by mc0re** [comment]
These are the warnings I get when setting the version to 1 (changed `BOX_DEFINE_S` to `FBOX_DEFINE_S` for box `GF_ISOM_BOX_TYPE_PSSH` in `box_funcs.c`:
```
[iso file] Box uuid wrote 900 bytes but size is 904
[iso file] Box moov wrote 205166 bytes but size is 205170
```

**Comment by jeanlf** [comment]
Watch out, a UUID box is NOT a full box by default.
The PIFF PSSH box is a UUID box, and also has version and flags in its main body, but we don't handle PIFF boxes as generic full boxes. 

The pssh code was indeed missing reading these version and flags but was writing them ... 
This should now be fixed, could you cross-check?

**Comment by mc0re** [comment]
Ok, thanks, no warnings.
I don't understand, though, why when decrypting a PlayReady file, the PSSH is *written* into the decrypted file. And why the decrypted version is not playable...

**Comment by jeanlf** [comment]
hmm that's not normal indeed. Do you have a sample encrypted file and associated DRM XML file for us to reproduce ?

**Comment by mc0re** [comment]
Yes, how to send it to you?

**Comment by jeanlf** [comment]
see link in first post of this issue

**Comment by mc0re** [comment]
Here you are: https://mega.nz/file/8t4FyTrB#wsTZfa2fUoA22zmcsQBHTAjjfw5Q3-xL_R_oYrwxIUE
The "de.bat" is supposed to decrypt the fMP4 file. "gp.xml" is the DRM XML file which I intend to use for both encryption and decryption.

**Comment by mc0re** [comment]
Also uploaded to MediaFire for your convenience - https://www.mediafire.com/file/nuch2ilfoez3hdy/PlayReady.zip/file

**Comment by jeanlf** [comment]
thanks, we indeed had some bugs not removing PSSH in PIFF files using 'piff' as scheme type, this should now be fixed. I cannot however play the decrypted file, are the keys ok?

I also added mode 'piff' in teh DRM file so that it automatically sets UUID PIFF boxes for pssh, tenc and senc

**Comment by mc0re** [comment]
Thanks a lot.
As for the keys, this file was encrypted by Microsoft Azure Media Services with this key, which I specified explicitly. So it should be okay. I don't know "first_IV", though, but it shouldn't matter, I guess.

**Comment by jeanlf** [comment]
hmm that's strange - the KID in the encrypted file does not match the KID in your config,  are you sure this is the right key?

**Comment by mc0re** [comment]
The KID in the config is `0xb65422ef473b4845bbedc811b70b2d1a`, when converted to `Guid` gives `ef2254b6-3b47-4548-bbed-c811b70b2d1a`.
```
new Guid(new byte[]{0xb6, 0x54, 0x22, 0xef, 0x47, 0x3b, 0x48, 0x45, 0xbb, 0xed, 0xc8, 0x11, 0xb7, 0x0b, 0x2d, 0x1a});
```

The KID in the file (inside `WRMHEADER`) is `tlQi70c7SEW77cgRtwstGg==`, converted from Base64 and to `Guid` gives `ef2254b6-3b47-4548-bbed-c811b70b2d1a`.
```
new Guid(Convert.FromBase64String("tlQi70c7SEW77cgRtwstGg=="))
```

Moreover, the file can be played back with a PlayReady-enabled player, and the checksum from `WRMHEADER` is also correct, meaning that both key ID and value received from the license server match those written in the `WRMHEADER`.

**Comment by jeanlf** [comment]
OK decryption should now work fine. 
However, the KID you indicate in the DRM config file must be the exact KID binary string as used (decrypt) / injected (encrypt) in the file, in your case `0xef2254b63b474548bbedc811b70b2d1a`.

MP4Box will now throw an error when no KID is matched - we were silently defaulting to first key, which is not really nice. You now have the possibility to define a key with no KID when decrypting, it will match any KID value in the file.

Please cross-check and close

**Comment by mc0re** [comment]
`src/media_tools/ismacryp.c`: `memset(blank_key, 0, 15)`
Are you sure it should be 15, not 16?

**Comment by mc0re** [comment]
But yay, it works! :-)  Thanks a mountain!

**Comment by jeanlf** [comment]
ooops yes 16 my bad...

**Comment by mc0re** [comment]
You don't do the same validation when encrypting, do you?

**Comment by jeanlf** [comment]
you should be able to do so, provided you have the right PSSH blob to inject. What seems to be the problem? Could you check for major differences in the encrypted file structure (-diso FILE, check for sinf, pssh and senc boxes)

**Comment by mc0re** [comment]
The mp4box-encrypted file does not have `<BrandEntry AlternateBrand="piff"/>`.
I don't see `PIFFProtectionSystemHeaderBox` in it, `ProtectionSystemHeaderBox` took its place.
It's probably because I need to force fMP4 / smooth / PIFF format?

**Comment by jeanlf** [comment]
for brands, use
`-ab piff`

Injecting `PIFFProtectionSystemHeaderBox` is available in 0.9.0 (filters), I'll backport in 0.8.0 asap

**Comment by mc0re** [comment]
Can I use branch "filters"?

**Comment by mc0re** [comment]
Can I force fMP4 format?

**Comment by mc0re** [comment]
Checked the "filters" branch. It cannot yet read the sample file (`[iso file] Read Box "uuid" (start 152) failed (Invalid IsoMedia File) - skipping`) and writes the PlayReady header into `pssh` instead of `uuid`.

**Comment by jeanlf** [comment]
With latest git on filters:
```
% MP4Box -decrypt gp.xml DjiDeath.mp4 -out test.mp4
[iso file] Track with no samples but duration defined, ignoring duration
[iso file] Track with no samples but duration defined, ignoring duration
[CENC/ISMA] Invalid scheme version 00010001 for scheme type piff, results might be wrong
[iso file] Track with no samples but duration defined, ignoring duration
[iso file] Track with no samples but duration defined, ignoring duration

% ffplay test.mp4
```
all ok.
Are you sure you fetch the latest ?

**Comment by mc0re** [comment]
Okay, `git checkout` was not enough, needed `git pull` as well, thanks for the hint!
