### ISSUE TITLE
gpac deb install error

### ISSUE THREAD

**Issue by LeoKingLong** [gpac/gpac#1459]
1. Download the lastest gpac deb file   gpac_0.9.0-DEV-rev3617-g36c21e0b-filters_amd64.deb;
2. Os information:
Ubuntu 18.04.4 LTS 
Linux c3a605ff71fc 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
3. Install command: 
dpkg -i gpac_0.9.0-DEV-rev3617-g36c21e0b-filters_amd64.deb
4.Error message printed:
(Reading database ... 6749 files and directories currently installed.)
Preparing to unpack gpac_0.9.0-DEV-rev3617-g36c21e0b-filters_amd64.deb ...
Unpacking gpac (0.9.0-DEV-rev3617-g36c21e0b-filters) over (0.9.0-DEV-rev3617-g36c21e0b-filters) ...
dpkg: dependency problems prevent configuration of gpac:
 gpac depends on liba52-0.7.4; however:
  Package liba52-0.7.4 is not installed.
 gpac depends on libfaad2 (>= 2.7); however:
  Package libfaad2 is not installed.
 gpac depends on libglu1-mesa | libglu1; however:
  Package libglu1-mesa is not installed.
  Package libglu1 is not installed.
 gpac depends on libjpeg62 (>= 6b1); however:
  Package libjpeg62 is not installed.
 gpac depends on libmad0 (>= 0.15.1b-3); however:
  Package libmad0 is not installed.
 gpac depends on libpng12-0 (>= 1.2.13-4); however:
  Package libpng12-0 is not installed.
 gpac depends on libssl1.1 (>= 1.1.0); however:
  Package libssl1.1 is not installed.

dpkg: error processing package gpac (--install):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Errors were encountered while processing:
 gpac

So  who can I fix this error? 
Thanks

**Comment by aureliendavid** [comment]
you need to install the dependencies that dpkg reports 

you can try running `sudo apt-get install -f` after the `dpkg -i` command, or installing with `sudo apt install ./gpac[...].deb`

see https://askubuntu.com/questions/40011/how-to-let-dpkg-i-install-dependencies-for-me for more info

**Comment by kahanikaar** [comment]
Try installing the dependencies which are required as shown and follow the steps mentioned by @aureliendavid for using the -f flag for fixing the broken packages.
Moreover, you can also try installing the dependencies manually one by one.Just run the following commands in the terminal:
` sudo apt-get install -y liba52-0.7.4 `
`sudo apt-get install libfaad2`
` sudo apt-get install -y libglu1-mesa `
` sudo apt-get install -y libjpeg62-dev `
` sudo apt-get install -y libmad0-dev `
` sudo apt-get install -y libpng12-0 `
` sudo apt-get install -y libssl1.1 `

**Comment by jeanlf** [comment]
Can we close this?

**Comment by SivanLiu** [comment]
> Try installing the dependencies which are required as shown and follow the steps mentioned by @aureliendavid for using the -f flag for fixing the broken packages.
> Moreover, you can also try installing the dependencies manually one by one.Just run the following commands in the terminal:
> `sudo apt-get install -y liba52-0.7.4`
> `sudo apt-get install libfaad2`
> `sudo apt-get install -y libglu1-mesa`
> `sudo apt-get install -y libjpeg62-dev`
> `sudo apt-get install -y libmad0-dev`
> `sudo apt-get install -y libpng12-0`
> `sudo apt-get install -y libssl1.1`

ibpng12-0 need to change the source.list
deb http://security.ubuntu.com/ubuntu xenial-security main 
sudo apt-get update

 sudo gdebi  xxx.deb
