### ISSUE TITLE
Drift between minCTS of segment and MPD start time is 4.18294e+11 s

### ISSUE THREAD

**Issue by delbinwen** [gpac/gpac#146]
Hi,

I'm trying to use segment timeline instead but MP4Box stopped. Below is the command I used to create MPD; (use audio only for simplicity).
MP4Box -dash 5005 -rap -segment-name seg_$Bandwidth$_$Time$ -url-template -segment-timeline -bs-switching no audio_p0.mp4

And the output of the command is
DASH-ing file: 5.00s segments 5.00s fragments single sidx per segment
Spliting segments at GOP boundaries
DASHing file audio_p0.mp4
[DASH]: Drift between minCTS of segment and MPD start time is 4.18294e+11 s
Assertion failed: (diff>0), function gf_media_isom_segment_file, file media_tools/dash_segmenter.c, line 1711.
Abort trap: 6

Some notes here;
* No problem if segment template is used
* No problem for video part

Any suggestion to investigate the issue further?

-wesley

**Comment by nguyen-viet-thanh-trung** [comment]
Could you please post your source mp4 somewhere ? I couldn't reproduce it with my source.

**Comment by delbinwen** [comment]
Yes, I think I could upload just the audio part somewhere; please allow me to figure out.

At the moment, I just observe that the first timestamp of audio stream is -2048, does it cause problem?

**Comment by delbinwen** [comment]
hi, you can get the media file at https://www.dropbox.com/s/qxnpwdz8ku8yzxy/audio_e.mp4?dl=0. And you should be able to repro the issue with cmd I posted.

The media file I uploaded was encrypted by MP4Box. Encryption should not be the issue as I can repro with clear media file.

**Comment by Murmur** [comment]
I had this same error message today after compiling fresh git GPAC in [media-autobuild_suite for Windows](https://github.com/jb-alvarado/media-autobuild_suite/issues/88). Does not happen if I take installer GPAC mp4box.exe binary.

[media_tools/dash_segmenter.c, Line 1711](https://github.com/gpac/gpac/blob/master/src/media_tools/dash_segmenter.c) tries to drift in time but `assert(diff>0)` always makes a fatal error. It never reach next `if(diff>=1)..` block. Is this assert a left over from development?

installer works: GPAC version 0.5.2-DEV-rev105-gde453e7-master
git compile assert failed: GPAC version 0.5.2-DEV-rev384-gaa0f405-master

**Comment by delbinwen** [comment]
hi @nguyen-viet-thanh-trung, do you have chance to look at the issue with the clip I uploaded? :-)

**Comment by delbinwen** [comment]
Hi @jeanlf,

I pull the latest code with your fix and I can now successfully dash the streams.

Thanks,
Wesley
