### ISSUE TITLE
Failed to build filters branch as missing file raster2d.h

### ISSUE THREAD

**Issue by peipeiguo** [gpac/gpac#1460]
Hi,

Failed to build filters branch as missing file raster2d.h. I have copyed the file from master branch to the include path, then it build success.

The compiling error as below:
```
  CC compositor/mpeg4_gradients.c
  CC compositor/mpeg4_grouping.c
make[1]: *** No rule to make target '/home/gpac_public/include/gpac/modules/raster2d.h', needed by 'compositor/mpeg4_grouping_2d.o'.  Stop.
make[1]: Leaving directory '/home/gpac_public/src'
Makefile:13: recipe for target 'all' failed
make: *** [all] Error 2
```

Just report this issue.

**Comment by aureliendavid** [comment]
I don't think you should need it

by any chance did you build in the same directory where you built the master branch before ? 

if so you need to run `make distclean` before building as you may have leftovers `.depend` files that can cause this type of errors

**Comment by jeanlf** [comment]
my guess is you are rebuilding in the same tree as master branch and your dependencies are now broken. Do:
```
make distclean
./configure [OPT]
make
```

To avoid this when switching between branches, I would recommend building out of the source tree, eg:
```
mkdir bin/filters
cd bin/filters
../../configure [OPT]
make
```

**Comment by peipeiguo** [comment]
Yes, I built master before, and then checkout filters branchs and build filters in same directory.
It works after `make distclean`. Thank you.
