### ISSUE TITLE
Capitalization of Opus mime type breaks playback?

### ISSUE THREAD

**Issue by dominic-p** [gpac/gpac#1462]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I'm seeing a strange issue with Opus audio. It might be a bug in MP4Box or elsewhere, so I apologize if this is the wrong place for this. Here is what I'm seeing:

1. Take this [example opus file](https://people.xiph.org/~giles/2012/opus/ehren-paper_lights-96.opus) and then put it into an MP4 containers like this:

```
MP4Box -add ehren-paper_lights-96.opus opus.mp4
```

2. DASH the MP4 and create a manifest

```
MP4Box -dash 8000 opus.mp4
```

3. The manifest has a section like this: `<Representation id="1" mimeType="audio/mp4" codecs="Opus" audioSamplingRate="48000" bandwidth="92408">`.

4. The problem is that Firefox (and Chromium from a little testing) doesn't think it can play this stream. If I run `MediaSource.isTypeSupported('audio/mp4; codecs="Opus"');` it returns `false`, but if I change `Opus` to `opus`, it returns `true`, and Firefox will play the DASH stream (I tested with dash.js). I see the same capitalized codec if I run `MP4Box -info opus.mp4`.

On the face of it I would assume this is a Firefox bug (be liberal in what you accept...), but since Chromium is doing the same thing, I thought I would post it here.

**Comment by aureliendavid** [comment]
Hm, that's interesting, it might be an issue on the browser / MSE side from what I understand but I might be mistaken

according to https://www.w3.org/TR/mse-byte-stream-format-isobmff/

> This section specifies the parameters that can be used in the MIME-type passed to isTypeSupported() or addSourceBuffer().
>
> MIME-types for this specification MUST conform to the rules outlined for "audio/mp4" and "video/mp4" in RFC 6381. 

according to [RFC6381](https://tools.ietf.org/html/rfc6381#section-3.3) which defines the `codecs` parameter of a mime type: 

> For the ISO Base Media File Format, and the QuickTime movie file
   format, the first element of a 'codecs' parameter value is a sample
   description entry four-character code as registered by the MP4
   Registration Authority [MP4RA].  Values are case sensitive.

and according to the [mp4ra](http://mp4ra.org/#/codecs) Opus is defined as `Opus` (with a capital O). 

apparently there was some unresolved discussion about a similar problem with flac here: https://github.com/w3c/media-source/issues/188

I'm not sure where to go from here, maybe open an issue at https://github.com/w3c/media-source or on the firefox/chromium issue trackers?

**Comment by dominic-p** [comment]
Thanks for the thorough reply. I went ahead and filed a [Firefox bug here](https://bugzilla.mozilla.org/show_bug.cgi?id=1629589).

**Comment by jeanlf** [comment]
closing for now as this does not seem to be a GPAC issue
