### ISSUE TITLE
Can not find listed boxes in hex view

### ISSUE THREAD

**Issue by CoSoCo** [gpac/gpac#1470]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I share the original file anonymously with this dropbox: https://cloud.disroot.org/s/fBeePRoA4JGZNMB

Hi, I have this output:
```
$ MP4Box -v MVI_1324.MOV
[iso file] Starting to parse a top-level box at position 0
[iso file] Read Box type ftyp size 24 start 0
[iso file] Starting to parse a top-level box at position 24
[iso file] Read Box type moov size 98280 start 24
[iso file] Read Box type udta size 65596 start 32
[iso file] Read Box type CNCV size 20 start 40
[iso file] Read Box type CNDM size 12 start 60
[iso file] Read Box type CNTH size 65552 start 72
[iso file] Read Box type CNDA size 9452 start 0
[iso file] Read Box type 4CF2D149 size 3078257872 start 9452
[iso file] Delete box type UNKN
[iso file] Delete box type UNKN
[iso file] Read Box type mvhd size 108 start 65628
[.....]
```
The udta box is from 32 to 65627.
Inside this box there are 5 boxes. The first 3 boxes I can see in hex view from 40 to 65623, but not the last 2. Instead there is a gap of 4 bytes before the following mvhd box, starting at 65628:
```
00065600   DB AE 5B F0 46 FE AF E8 A8 2E 0D 5C E0 7F E7 D5 72 E9 27 4B E0 26 02 23 00 00 00 00 00 00 00 6C   Û®[ðFþ¯è¨..\à.çÕré'Kà&.#.......l
00065632   6D 76 68 64 00 00 00 00 DA 60 D3 57 DA 60 D3 57 00 00 75 30 00 0D 51 A8 00 01 00 00 01 00 00 00   mvhd....Ú`ÓWÚ`ÓW..u0..Q¨........
```
So my question is: What is the meaning of this 2 additional invisible boxes?

"start 0" for CNDA box seems also weird!

**Comment by CoSoCo** [comment]
Please also reopen https://github.com/gpac/gpac/issues/1453

**Comment by jeanlf** [comment]
how did you produce the file? Any chance you can share it?

**Comment by jeanlf** [comment]
some files (such as yours) set in udta a 4 bytes trailer set to 0, that explains your gap. If you use start+size of the udta box you end up at the start of the mvhd box.

the message of unknown boxes and weird start in the the udta parsing comes from the fact that we attempt at parsing the content of each unknown udta child as a box array, triggering these logs. I have cleanup the log to silence the udta unknonw child parsing.
