### ISSUE TITLE
MP42TS unable to segment live ATSC source

### ISSUE THREAD

**Issue by grkblood13** [gpac/gpac#1471]
I'm piping the output of a USB ATSC tuner tuned with a zap tool to a named fifo pipe.

When feeding this pipe into MP42TS I receive the following:

[alarm@alarmpi record]$ MP42TS -src /home/alarm/local-channels/pipe.ts -segment-dir /tmp/live/
Error opening /home/alarm/local-channels/pipe.ts - not a supported input media, skipping.
Error: Destination argument not found
Error: No Programs are available

The source is valid. The following url is a short sample of the captured terrestrial broadcast.  Any idea how to segment this in a live mode?

https://file.io/aeJmUM7X

**Comment by jeanlf** [comment]
pipes are not supported in 0.8.0, you need to use 0.9.0 (and no more MP42TS in 0.9.0):

`gpac -i pipe://pipe.ts [whatever output]`

**Comment by grkblood13** [comment]
So I got v0.9 built. Having trouble getting an output from this though. I found this page, which I'm guessing is what I want to use:

https://github.com/gpac/gpac/wiki/tssplit

What I want to do is feed my pipe at /path/to/pipe.ts into gpac and have the chunks outputted in /tmp/record.

I don't see where I can specify an output directory though, only file with "-o". My best guess was this (even though I don't care your the m3u8 playlist):

$ gpac -i /path/to/pipe.ts -o /tmp/record/out.m3u8 tssplit

This doesn't work, but it seems to be doing something with the pipe as its getting a PID from it.

...
[MPEG-2 TS] TS Packet 839 has error (PID could be 49)
[MPEG-2 TS] TS Packet 850 has error (PID could be 49)
[MPEG-2 TS] TS Packet 852 has error (PID could be 49)
[MPEG-2 TS] TS Packet 867 has error (PID could be 49)
[MPEG-2 TS] TS Packet 896 has error (PID could be 49)
[MPEG-2 TS] TS Packet 901 has error (PID could be 49)
...

Nothing is ever generated in /tmp/record/

any ideas?

**Comment by grkblood13** [comment]
@jeanlf , do you get updates on this issue when I comment since it's closed? Just want to make sure you're seeing my input.

**Comment by jeanlf** [comment]
tssplit will not be of much help here, it’s mostly designed to redistribute/store single program TS out of mpts.

You shoud rather create a dynamically instantiated pipeline:
```
gpac -i pipe://mypipe.ts -o session_$ServiceID$.mpd:SID=#ServiceID=
```
See [this testsuite example](https://github.com/gpac/testsuite/blob/filters/scripts/mpeg2ts.sh)

Also check the session demux is ok:
```
gpac -i pipe://mypipe.ts inspect:deep
```

**Comment by grkblood13** [comment]
@jeanlf neither of those commands are outputting anything for me.

**Comment by jeanlf** [comment]
Hmm strange - could you post a sample rip file (the link provided in your first post does not work)

You can also try to debug pipes:
`gpac -i pipe://yourpipe inspect:deep -logs=mmio@debug`

 or demux:
`gpac -i pipe://yourpipe inspect:deep -logs=container@debug`

**Comment by grkblood13** [comment]
@jeanlf new sample: https://file.io/u4OqbN09

**Comment by grkblood13** [comment]
[alarm@alarmpi live]$ gpac -i pipe:///home/alarm/local-channels/pipe.ts -logs=mmio@debug
[NVDec] dlopen "libcuda.so" failed!
[PipeIn] opening /home/alarm/local-channels/pipe.ts
[PipeIn] configuring stream 5000 probe bytes
[PipeIn] sending 5000 bytes
No filter chain found for PID pipe.ts in filter pin to any loaded filters - NOT CONNECTED

[alarm@alarmpi live]$ gpac -i pipe:///home/alarm/local-channels/pipe.ts -logs=container@debug
No filter chain found for PID pipe.ts in filter pin to any loaded filters - NOT CONNECTED

**Comment by jeanlf** [comment]
I keep getting a 404 on your sample - could you upload it using the link provided in our issue template?

**Comment by grkblood13** [comment]
https://www.mediafire.com/file/kyyy0jqwhks8iuq/sample3.ts/file

**Comment by jeanlf** [comment]
the file is not a conformant TS, it's missing PAT and PMT tables (in fact it only has PIDs for audio and video), GPAC cannot demux this. You need to check how your tuner outputs the data and if it can be configured to output the complete TS with PAT and PMT
