### ISSUE TITLE
unable to compile gpac v0.9.0 on rpi3

### ISSUE THREAD

**Issue by grkblood13** [gpac/gpac#1472]
Building on Raspberry Pi 3 running Manjaro archlinux

$  uname -a 
Linux alarmpi 5.4.18-udlv7+ #1 SMP Sun Feb 16 10:11:01 CST 2020 armv7l GNU/Linux

$ git checkout filters
$ make distclean
$ ./configure
$ make -j4

runs for a while and then craps out here:

  CC filters/write_vtt.c
  CC ../modules/dektec_out/dektec_video_decl.c
  CC filters/dec_openhevc.c
In file included from ../modules/dektec_out/dektec_video_decl.c:27:
../modules/dektec_out/dektec_video.h:47:12: fatal error: emmintrin.h: No such file or directory
   47 | #  include <emmintrin.h>
      |            ^~~~~~~~~~~~~
compilation terminated.
make[1]: *** [../config.mak:157: ../modules/dektec_out/dektec_video_decl.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/alarm/gpac/src'
make: *** [Makefile:13: all] Error 2

**Comment by jeanlf** [comment]
oops my bad - should now be fixed, can you check ?

**Comment by grkblood13** [comment]
Looks good. Thanks.
