### ISSUE TITLE
[Filters] String formatting overflow possible in multiple places

### ISSUE THREAD

**Issue by RodolpheFouquet** [gpac/gpac#1474]
Hey everyone,

While compiling GPAC with GCC 9, I encountered the format-overflow warning in multiple places, for example here: https://github.com/gpac/gpac/blob/master/src/utils/os_config_init.c#L610

gui_path is 4096 bytes max, and so is szPath.

So sprintf(gui_path, "%s%cgui.bt", szPath, GF_PATH_SEPARATOR) can be, at most:
-  4095 bytes (szPath minus its termination char)
- plus 1 byte for the separator
- plus gui.bt (7 bytes counting its \0)

Which would lead to a nasty overflow.

Possible fixes:

1. use snprintf instead of sprintf https://en.cppreference.com/w/c/io/fprintf and check for truncations
2. pre-check before sprintf

--------

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
yes we're aware of that we need to do a big cleanup here ...

**Comment by jeanlf** [comment]
we did a big cleanup recently, could you check we catched all of these?

**Comment by RodolpheFouquet** [comment]
Hi, it still happens on GCC 10

**Comment by aureliendavid** [comment]
hey all, 

i think i fixed most of them in the commit above (hopefully without breaking anything)

two things i learned on this subject: 

1. truncation warnings with `snprintf` can be removed by actually using the return value (https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html)

2. `strncpy` is a pain, some good alternatives are discussed here: https://meyering.net/crusade-to-eliminate-strncpy/ ([`memccpy` ](https://man7.org/linux/man-pages/man3/memccpy.3.html) is interesting and should probably be used more often)
