### ISSUE TITLE
Why is surface destroyed immediately after creation?

### ISSUE THREAD

**Issue by LeoKingLong** [gpac/gpac#1489]
In filters branch, dec_mediacodec_jni.c  line 176:

```
	surfaceTex->texture_id = tex_id;
	// create objects
	otmp = (*env)->NewObject(env, cSurfaceTexture, mSurfaceTexConstructor, surfaceTex->texture_id);
	surfaceTex->oSurfaceTex = (jobject) (*env)->NewGlobalRef(env,otmp);
	if(!surfaceTex->oSurfaceTex) goto create_surface_failed;
	
	oSurface = (*env)->NewObject(env, cSurface, mSurfaceConstructor, surfaceTex->oSurfaceTex);
	if(!oSurface) goto create_surface_failed;
	
	*window = ANativeWindow_fromSurface(env, oSurface);
	*surface_rendering = (*window) ? GF_TRUE : GF_FALSE;
	(*env)->CallVoidMethod(env, oSurface, mSurfaceRelease);
	if ((*env)->ExceptionCheck(env)) {
		HandleJNIError(env);
	}

```

**Why you release the surface after window is created?
And because the surface is released( is invalid),  when you call  AMediaCodec_releaseOutputBuffer  function， there is no surface , so Where is the image rendered?** 

I create a new filter and init OpenGL in it , how can I render the iamge from mediacodec filter with my own filter(maybe these two filter in different thread)?

Thanks!

**Comment by jeanlf** [comment]
We only keep the associated native window, not the java Surface which is why we delete it right away.
The image is rendered through an openGL texture (see mcdec_update_surface and mcdec_hw_get_gl_texture), using GL_TEXTURE_EXTERNAL_OES.
