### ISSUE TITLE
[Bug]Mediacodec loss  frame 

### ISSUE THREAD

**Issue by LeoKingLong** [gpac/gpac#1492]
I used mcdec filter(MediaCodec decoder) to decode some hevc stream，when the  input is end，the filter inputEOS was set to true  and set the flags  AMEDIACODEC_BUFFER_FLAG_END_OF_STREAM.
```
	 ctx->inputEOS = GF_TRUE;
        flags = AMEDIACODEC_BUFFER_FLAG_END_OF_STREAM;
```

But the outputbuffer still had some pck remaining to be decoded,  but  the  gpac exited and destroyed the session ，so the pck in the output buffer  was lost.

Here is the log :
```
[0xc32ff970]:Filter MediaCodec hardware HEVC|H265 PID PID1 destroying packet CTS 1096000
[0xc32ff970]:Filter MediaCodec hardware HEVC|H265 PID PID1 has 0 shared packets out
[0xc32ff970]:[Filter] fovexporter removed from scheduler - blocking 0
[0xc32ff970]:Filter MediaCodec hardware HEVC|H265 process
[0xc32ff970]:[Filter] MediaCodec hardware HEVC|H265 removed from scheduler - blocking 0
[0xc32ff970]:Session stop
[0xc32ff970]:Session destroy begin
```

**Comment by jeanlf** [comment]
I doubt this is the reason, the outputEOS flag is only set when the AMediaCodec_dequeueOutputBuffer gives an info with AMEDIACODEC_BUFFER_FLAG_END_OF_STREAM set , so the output (decompressed) pid is only marked as EOS when the output MediaCodec buffer is empty.

Could you try with `logs=codec@debug` ?

**Comment by LeoKingLong** [comment]
> I doubt this is the reason, the outputEOS flag is only set when the AMediaCodec_dequeueOutputBuffer gives an info with AMEDIACODEC_BUFFER_FLAG_END_OF_STREAM set , so the output (decompressed) pid is only marked as EOS when the output MediaCodec buffer is empty.
> 
> Could you try with `logs=codec@debug` ?

I reschedule the process to finish all the pck , thanks

**Comment by jeanlf** [comment]
Good, but is there a bug in the mediacodec filter?

**Comment by LeoKingLong** [comment]
> Good, but is there a bug in the mediacodec filter?

Yes ,I think so ....
The filter session will be destroyed before the mediacodec process all the pcks in outputbuffer(because the mediacodec cannot get process task ), but I tested on my own branch( a branch fork from old filter branch) not the lastest filter branch~
