### ISSUE TITLE
Missing SegmentURL on segmentation

### ISSUE THREAD

**Issue by dustinkerstein** [gpac/gpac#1493]
Using the latest nightly OSX build (gpac-0.8.0-rev1-gc1990d5c-master) I am running the following command:

`mp4box -dash 1000 -frag 1000 -rap hd.mp4`

The video above has 360 frames total (100% I-Frames) and is 1fps. The DASHed output mp4 correctly has 360 frames and 1fps timing, but the resulting mpd file only contains 359 segments. 

I was originally using a much older build (though not sure from exactly when) that does not exhibit this issue. Is this the expected behavior, or is this possibly a bug?

Here are the test files - https://www.dropbox.com/sh/31qccctsnw9moum/AACwP48pnKrWbg564kNL7NoBa?dl=0

**Comment by jeanlf** [comment]
The result MPD and mp4 are correct, it's just that the last segment has 2 samples instead of 1. I patched master to fix this, the dasher should now produce the expected number of segments.
