### ISSUE TITLE
Add conda-forge builds of mp4box

### ISSUE THREAD

**Issue by faroit** [gpac/gpac#1499]
- there is a lack of tools to process mp4 containers directly from python. 
- many python users rely on the conda package manager to install non-python packages. 
- [conda-forge](https://conda-forge.org/) allows to distribute these packages so that they are installable from conda

It would be great to add mp4box builds for win/mac/linux to conda-forge. While this could be done by any user, it would be great if the code-owners of mp4box could provide some help or possibly offer the ability to maintain such a package.

What do you think?

**Comment by jeanlf** [comment]
feel free to submit a patch/howto, but that's outside the scope of the project.
