### ISSUE TITLE
Does dec_mediacodec.c support audio hard decoding？

### ISSUE THREAD

**Issue by beibeii** [gpac/gpac#1500]
hello
Does dec_mediacodec.c support audio hard decoding, and if not, are there other supported methods

**Comment by jeanlf** [comment]
no for now we only have hardware video decoding support, audio is decoded in software on all platforms.

**Comment by beibeii** [comment]
thanks

**Comment by rbouqueau** [comment]
See https://github.com/gpac/gpac/issues/1503 in case anyone wants to contribute :)
