### ISSUE TITLE
Some help for implementation and some guidance

### ISSUE THREAD

**Issue by fabiomagnoni** [gpac/gpac#1502]
I need to do a project where there is a local server and multiple users will read video, audio content from this local server.

To avoid performance struggle, I would like to make it as video on demand, but in local environment.

It is simple, to display few videos on a local html and users can consume those videos.

Any  "Hello world" project for it would be very helpful

**Comment by jeanlf** [comment]
that's a bit vague but using 0.9.0 you can setup an http server using gpac to deliver your video, check [these tests](https://github.com/gpac/testsuite/blob/filters/scripts/out_http.sh)
