### ISSUE TITLE
Invalid AV1 warning about color characteristics

### ISSUE THREAD

**Issue by cconcolato** [gpac/gpac#1504]
MP4Box (filters branch) emits a wrong warning when processing the attached file [gradient.mp4.zip](https://github.com/gpac/gpac/files/4726849/gradient.mp4.zip)
:
```
[AV1] incoherent color characteristics primaries 0 transfer 0 matrix 0 color range 0
```
Relevant code is here:
https://github.com/gpac/gpac/blob/filters/src/media_tools/isom_tools.c#L3746-L3790

The state is initialized to 0, then supposed to be overwritten by the sequence header OBU in the av1c->config field. But if the file does not contain an OBU in the config field, the color fields remain 0, reaching the 'else' statement.

Either the OBU should be fetched from the media or the color fields should be initialize to 2 instead of 0.

**Comment by rbouqueau** [comment]
Both branches do use a wrong 0 default value instead of 2. Fixing.
