### ISSUE TITLE
Using "splitz" option with mp4box does not allow an output name to be specified

### ISSUE THREAD

**Issue by msrdanov** [gpac/gpac#151]
I've noticed that when using "-splitz" the value for the output filename ("-out") parameter is ignored.  Using "-splitx" does seem to work properly.  This seems to be the case even using versions as far back as 0.5.0.  Below is a sample using the nightly build (windows under cygwin - 0.5.2-DEV-rev388-gd9aea85-master)

$ mp4box -splitx 60:120 BigBuckBunny_320x180.mp4 -out bb-splitx.mp4
Adjusting chunk start time to previous random access at 60.00 sec
Extracting chunk bb-splitx.mp4 - duration 60.00s (60.00s->120.00s)

$ mp4box -splitz 60:120 BigBuckBunny_320x180.mp4 -out bb-splitz.mp4
Adjusting chunk start time to previous random access at 60.00 sec
Adjusting chunk end time to previous random access at 120.00 sec
Extracting chunk BigBuckBunny_320x180_60_120.mp4 - duration 60.00s (60.00s->120.00s)

$ ls -l
total 74M
-rwxr-xr-x  1 marko None 6.1M May 21 17:53 bb-splitx.mp4*
-rwxrwx---+ 1 marko None  62M May 21 17:51 BigBuckBunny_320x180.mp4*
-rwxr-xr-x  1 marko None 6.1M May 21 17:54 BigBuckBunny_320x180_60_120.mp4*

$ mp4box -version
MP4Box - GPAC version 0.5.2-DEV-rev388-gd9aea85-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: (static configuration file)
Features: GPAC_64_BITS GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG

**Comment by rbouqueau** [comment]
Well catched!
And thanks for the very precise report. WIsh we had more of them :)

Should be solved now. Please close is ok.

**Comment by msrdanov** [comment]
Hi Romain, Thanks for the quick response and fix!  I'm away right now but I
will download the latest version and will close the issue by early next
week.  No problem for the report.  If I notice anything else, I'll be sure
to let you know.

**Comment by msrdanov** [comment]
Hi,  The changes that were made definitely fixed the issue.  Thanks again!
