### ISSUE TITLE
DOCUMENTATION for build 1.0.0 still needs update (completion)

### ISSUE THREAD

**Issue by ricardollovera** [gpac/gpac#1510]
- [x ] I looked for a similar issue and couldn't find any.
- [ x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...).

Hi, 

I commented on the #1508 issue, but it was closed too soon. I confronted some lack of documentation that led me to another issue that i already resolved myself (this setup issue due to BAD documentation)

I got this error when I did "make install":
dh_link /usr/local/share/gpac/res/gpac.png /usr/local/share/pixmaps/gpac.png
make: dh_link: Command not found
Makefile:114: recipe for target 'install' failed
make: *** [install] Error 127
Always

As said, I had a Fedora ,

`#uname -a
Linux pc-01 4.11.12-100.fc24.x86_64 #1 SMP Fri Jul 21 17:35:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
#cat /etc/fedora-release
Generic release 24 (Generic)`

### So the solution was to simply install correctly debhelper package in Fedora

This solved my issue in linux, please update required packages...
`dnf install debhelper`

And particularly I had to restart procedure all over because for a dash chunked generation I had this message while performing it (another problem I might be opening issue)
`Adaptation` sets in period are of unequal duration min 545.994 max 937.96 seconds `
(in loop and of course varying the quantity of the the min/max)

So a regression against MP4Box - GPAC version 0.8.0-rev267-gd9d3533-master? but I have to be more sure Install is good with all extra dep for linux...

I am trying a correct full install also because if I didn't, then the old 0.62 MP4Box version in this old Fedora (or something like that) in the system was taking over. 
**TY very much for the change of the Upgrading Versions Documentation already** 

BTW,  you could also improve DOCUMENTATION adding this optional command:
 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/gpac_public/bin/gcc

And Deleting this web page or section: https://github.com/gpac/gpac/wiki/GPAC-build-MP4Box-only-all-platforms
Or PLEASE specify which versions deserves it.

  Regards,

**Comment by aureliendavid** [comment]
yes that's a bug, installing debhelper works but you shouldn't have to have it

I fixed the make install in https://github.com/gpac/gpac/commit/4710737bed502534499754afd730601c7ffb3d7b it should now work without debhelper

**Comment by jeanlf** [comment]
> So a regression against MP4Box - GPAC version 0.8.0-rev267-gd9d3533-master? but I have to be more sure Install is good with all extra dep for linux...

that's a possibility, please open an issue if you confirm it

> BTW, you could also improve DOCUMENTATION adding this optional command:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/gpac_public/bin/gcc

Not sure what you mean here, add a section about running if not root?

> And Deleting this web page or section: https://github.com/gpac/gpac/wiki/GPAC-build-MP4Box-only-all-platforms
Or PLEASE specify which versions deserves it.


Now I'm lost :) That section still applies to 1.0 why remove it ?

**Comment by ricardollovera** [comment]
Hi jeanlf,
When you said "Im lost" I was refering to the part of this page:
https://github.com/gpac/gpac/wiki/GPAC-build-MP4Box-only-all-platforms#buildmp4box-with-make
that is different to this page:
https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux#mp4box-only

In the former you have added:
**--use-zlib=no** (in config, when is ok and for what/why is yes zlib? )
**make -j4** (what/why is that -j4 in our case?)

It was and is not still clear to me. Sorry if it is doubts of beginner.

Many thanks; havent had time for the other checks.

**Comment by jeanlf** [comment]
OK I see - I updated the former to state that `--use-zlib=no` is optional.

The `-j` is a make option to specify the number of jobs (threads) for compilation, nothing to do with GPAC.
