### ISSUE TITLE
Bad call to dh_link in main Makefile

### ISSUE THREAD

**Issue by marillat** [gpac/gpac#1512]
dh_link must be called without DESTDIR otherwise the link is created in teh wrong path

debian/gpac/src/gpac-1.0.1/debian/tmp/usr/share/pixmaps/gpac.png

Otherwise this call to dh_link is really necessary ?

````
--- a/Makefile
+++ b/Makefile
@@ -168,7 +168,7 @@ ifeq ($(IS_DEB_MAKE),undefined)
 	ln -sf $(DESTDIR)$(prefix)/share/gpac/res/gpac.png $(DESTDIR)/usr/share/pixmaps/gpac.png
 	$(INSTALL) $(INSTFLAGS) -m 644 $(SRC_PATH)/share/gpac.desktop "$(DESTDIR)/usr/share/applications/"
 else
-	dh_link $(DESTDIR)$(prefix)/share/gpac/res/gpac.png $(DESTDIR)$(prefix)/share/pixmaps/gpac.png
+	dh_link $(prefix)/share/gpac/res/gpac.png $(prefix)/share/pixmaps/gpac.png
 	$(INSTALL) $(INSTFLAGS) -m 644 $(SRC_PATH)/share/gpac.desktop "$(DESTDIR)$(prefix)/share/applications/"
 endif
````

**Comment by aureliendavid** [comment]
> Otherwise this call to dh_link is really necessary ?

It's not and I don't know why I did that in the first place, we can just install this file like the others. 

We still have an issue with the gpac.application file though where the icon path is hardcoded. It will work ok with the debian package but fail to find the icon if there was a prefix. 

It should be generated by the configure to take the prefix into account like we do with gpac.pc

But I'll do that tomorrow..

**Comment by aureliendavid** [comment]
> We still have an issue with the gpac.application file though where the icon path is hardcoded. It will work ok with the debian package but fail to find the icon if there was a prefix.
> 
> It should be generated by the configure to take the prefix into account like we do with gpac.pc
> 

did that, hopefully the make install makes more sense now

i'm (optimistically) closing this issue but feel free to reopen if there are further issues

thanks
