### ISSUE TITLE
mp4client does not playback encrypted DASH

### ISSUE THREAD

**Issue by go4shoe** [gpac/gpac#1513]
Take 

http://www.mediafire.com/file/b83yw4dicwl3cl2/audio.mp4/file
http://www.mediafire.com/file/h2ky74i1ypyr685/video-720p.mp4/file
http://www.mediafire.com/file/z5i76qrzteva1tg/drm_file_gpac_clear.xml/file

create encrypted audio:
mp4box -encrypt drm_file_gpac_clear.xml audio.mp4

create encrypted video:
mp4box -encrypt drm_file_gpac_clear.xml video-720p.mp4

create DASH:
mp4box -dash 3000 audio_enc.mp4 video-720p_enc.mp4

Trying to play the resulting encrypted DASH package with mp4client will fail.

console output with logging turned on

No filter chain found for PID AS1 in filter dashin to any loaded filters - NOT CONNECTED
No filter chain found for PID AS2 in filter dashin to any loaded filters - NOT CONNECTED

I also tested:
- mp4 playback works
- encrypted mp4 playback works
- DASH playback works
- encrypted DASH does NOT work.

**Comment by jeanlf** [comment]
this should now be fixed, thanks for the report

**Comment by go4shoe** [comment]
Works like a charm - thank you for fixing!
