### ISSUE TITLE
Generating and playing a live MPD based stream. 

### ISSUE THREAD

**Issue by aliasif1** [gpac/gpac#1514]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ -] I looked for a similar issue and couldn't find any.
- [ -] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ -] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by aliasif1** [comment]
Here is what I am trying to achieve. 

- I am trying to generate and play a live stream

- I get a 2 second video segment after every 2 seconds and then I use mp4box to update the mpd file after every 2 seconds. The command I use is:

MP4Box -dash 10000 -dash-ctx context.txt -dynamic -profile live -min-buffer 2000 -mpd-refresh 2 -time-shift 4000-rap -no-frags-default -segment-name \'live_$RepresentationID$_\' -bs-switching no -url-template -out live.mpd -cat new_videosegment.mp4 output.mp4.

- I run this command every 2 seconds to take into account new segments which have just become available for streaming.

- This generates the mpd file but I am having trouble playing it

- OSMO player is able to play the MPD but after it has asked for all the valid segments(which are available) it goes on asking for segments which are not valid. For example suppose at the time Osmo player started playback 5 videos had been dashed, then OSMO player is able to play upto those 5 segments but then instead of waiting for segment6_1.mp4 to become available it request for segment6_1.m4s(which is not yet available but will be availabe at some later point). Then instead of waiting for segment6_1.m4s to become available it asks for segment6_2.m4s, segment6_3.m4s...... and so on. The playback essentailly stops after a 404 not found. And instead of requesting for the same valid segment (segment6_1.m4s) again and again till it becomes avaialbe the player asks for invalid segments which are in fact nevere generated.

- In summary Osmo player only plays upto that point till it gets valid segments and instead of waiting for new segments to become availabe it then asks for invalid segments which are never generated


- While DASH player throws this error and nevere plays the mpd
Multiplexed representations are intentionally not supported, as they are not compliant with the DASH-AVC/264 guidelines 

- Even vlc player is not able to parse and play the mpd. 

- I was wondering whats going on wrong in here. Is the command which I am using to generate the MPD correct. There is lot of resources available for stored/static videos but for live streaming when all the segments are not avaialbe at a time but instead they arrive after some time, little documentation is available.

In short I am trying to generate and play a live mpd file when segments arrive after 2 seconds and the mpd should be updated after 2 segments to take into account the new segment which just arrived. 

I am really stuck and I would appreciate any help. 
Also apart from GPAC and ffmpeg is their any other library to generate live MPD files for streaming media.

**Comment by jeanlf** [comment]
For the multiplexed problem, use `output.mp4#video output.mp4#audio`instead of `output.mp4`.

For the 404 problem, I think this comes from the fact that you are trying to generate 10s segments with incoming segments every 2s, you should try to use 2s for segment durations as well.

Another possibility to use less IOs would be to use gpac and the [flist filter](https://github.com/gpac/gpac/wiki/flist):

```
gpac -i input.m3u -o dash.mpd:profile=live
```
 
(see [dasher](https://github.com/gpac/gpac/wiki/flist) for the possible options).

By appending the new filename to `input.m3u` you should be able to do the same without concatenating into an intermediate file.

**Comment by aliasif1** [comment]
Thanks you for your response.
I checked out this link and it helped. [GPAC_Live_streaming](https://github.com/gpac/gpac/issues/1252). 
The command I use now is 
When ever a new mp4 file comes to the system (after every 2 seconds) I rename it to sample.mp4 and then run:

`MP4Box -dash 10000 -dash-ctx context.txt -profile live -mpd-refresh 2 -time-shift -1 -dynamic sample.mp4#video -out live.mpd`.

I am able to play the MPD using dash player.

But the player downloads a segment (suppose sample_dash123.m4s) plays it and then requests for the next segment (sample_dash124.m4s). This causes bit of stall at the player playback. How to update the MPD file so that the player instead of waiting for a segment goes ahead and downloads next segments (assuming segments are available). 

How to get a smooth playback so that the player does not buffer or stall

Also I get this dasher warning : 

`[Dasher] First CTS 431104 in segment 15 drifting by -27.9333 (more than half a segment duration) from segment time, consider reencoding or using segment timeline
` 
the GPAC version i am using is 1.0.0

Can you please comment on whats wrong with the MPD file or the commands

**Comment by jeanlf** [comment]
if your input files are 2s and comming in every 2s you must not use 10s dash duration but 2s. Each call to mp4box will create one or more full segments; in your case, the mpd advertises 10s duration but each segment end up being 2s.

**Comment by jeanlf** [comment]
I added a [force_flush](https://github.com/gpac/gpac/wiki/dasher#force_flush) option to the dasher that might be useful in your case. The option will force to generate a single segment from the input, which can be handy if you know that the average length is 2s but some segments may be slightly longer with potential IDRs after 2s, which would trigger a new segment. 
This means you can now use the proper target segment duration and not a large-enough number as was previously the case:
`MP4Box -dash 2000 --force_flush [...]`

Note that in any case, if your segment durations are not constant, using batch processing is likely to drift and you should use segment timeline signaling.

**Comment by a23232390** [comment]
@aliasif1  how to make live stream 
is use rtmp to mp4  and Use script make mpd
