### ISSUE TITLE
cross-compiling under mingw64 failing

### ISSUE THREAD

**Issue by hydra3333** [gpac/gpac#1515]
Hello, it looks like inconsistent capitalisation may be causing build failures under mingw64.
During the build, "Windows.h" cannot be found.

In almost all of gpac source lowercase windows.h is present and is found, whereas in these three files 
```
include/gpac/thread.h
src/filters/dec_nvdec_sdk.c
src/filters/dec_nvdec_sdk.h
```
the first letter is capitalised, i.e. `Windows.h` 

Can you please make these three lowercase to be consistent with the rest ?

Thank you.

**Comment by hydra3333** [comment]
PS the same with WinBase.h

**Comment by aureliendavid** [comment]
you're right, thanks

fixed in the last commit

**Comment by hydra3333** [comment]
Great !

Thank you.
