### ISSUE TITLE
mp4box no longer cross-compiles

### ISSUE THREAD

**Issue by hydra3333** [gpac/gpac#1517]
Hello. 

mp4box does not cross-compiles under mingw64 (in ubuntu) for target Win10 x64, any more.  This only came to light as I tried to build it after a week or so absence.

I had to swap to use commit ce9a843ffcd941d3d17a7bab20749b94a8e3c43c which is the prevailing top of the tree 'legacy' and that did cross-compile successfully.

So, it's the new master branch in which has lot has changed, that causes mp4box to no longer cross-compile.

By the way, thanks for fixing the case in 'Windows.h' and 'WinBase.h' to lowercase ... I didn't realise what else was going on as the original "breaking" change appeared to come from a very old commit (April 8th) and yet it had build successfully more recently, which threw me since I do not track this git.

The failed mp4box cross-compilaton console log is attached.

I may be doing something wrong under "old build scheme assumptions", in which case please just let me know.

Advice on "where to next" would be very much welcomed.

Thank you.

[mp4box.log](https://github.com/gpac/gpac/files/4805359/mp4box.log)

**Comment by aureliendavid** [comment]
I hadn't tested the case mingw+static-modules but 86a34ca should fix your case

can you retest and report back?

thanks

**Comment by hydra3333** [comment]
Yes, it builds now.
Thank you.
Glad you're on top of your game !
