### ISSUE TITLE
MP4Box writes "EXT-X-ENDLIST" tag to Master HLS playlist

### ISSUE THREAD

**Issue by thenickdude** [gpac/gpac#1519]
MP4Box 1.0.0 writes the tag "EXT-X-ENDLIST" to the end of the Master HLS playlist file, but this tag is only specified to belong to Media playlists, not Master playlists:

https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-07

As far as I can see, this tag has no meaning in a Master playlist and its presence is erroneous there.

The presence of this tag [causes Google's Shaka player](https://github.com/google/shaka-player/blob/76c4c674dc02c4b6dd166f2f75857b5e1c9cb037/lib/hls/manifest_text_parser.js#L287) to misidentify the Master playlist as a Media playlist, since it knows that this tag may only appear in Media playlists, and this prevents it from playing the video.

**Comment by jeanlf** [comment]
indeed, now fixed - thanks for the report
