### ISSUE TITLE
HLS: regression with master-only playlists

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#152]
It was introduced by 375a0a9c1da48d369c03ec379cee50043ff297f5.

A way to reproduce is to play http://d3sporhxbkob1v.cloudfront.net/bill/vod/sample-video/400k.m3u8

**Comment by rbouqueau** [comment]
@nguyen-viet-thanh-trung any news on this?

**Comment by nguyen-viet-thanh-trung** [comment]
it should be fixed in rev 430 !
