### ISSUE TITLE
Building MP4Box using MBAS/mingw fails

### ISSUE THREAD

**Issue by Selur** [gpac/gpac#1520]
I'm using MBAS (https://github.com/m-ab-s/media-autobuild_suite) and it fails building the latest version this was reported there (https://github.com/m-ab-s/media-autobuild_suite/issues/1716) and seems like it's a bug in the gpac code.

**Comment by aureliendavid** [comment]
it's weird that I don't see the same error in our mingw builds but I do see it with mbas

anyway, should be fixed in the latest commit, thanks for the report

**Comment by Selur** [comment]
I can confirm building works again!
Thanks for fixing it. :)
