### ISSUE TITLE
Generate MPD from existing segments

### ISSUE THREAD

**Issue by rustyguts** [gpac/gpac#1521]
Hello,

I'd like to use existing segments to create a DASH mpd. I'm being fed these segments from a parallel chunk based transcoder. The folder structure is as follows.

```
source.mp4
source.aac
segments/
  source/
    0.mp4
    1.mp4
  1080p/
    0.mp4
    1.mp4
```

Right now I have to concatenate the segments into a single file before I can use them to generate an MPD.

```
ffmpeg -i 1080p.txt -f concat -c copy 1080p.mp4
```

Is it possible to skip the concatenation step and send the segments directly to MP4Box? Ideally I would like to use the exact same segments. I have the source file on hand too, if more metadata is needed.

**Comment by jeanlf** [comment]
That was fun to do :)

- I added [some tests](https://github.com/gpac/testsuite/blob/filters/scripts/dash-genmanifest.sh)
- check the [dasher](https://github.com/gpac/gpac/wiki/dasher#manifest-generation-only-mode) help for more details.
- you will need a playlist, check the [flist](https://github.com/gpac/gpac/wiki/flist) help
 
This has not yet been tested for dynamic segment offering, we would need to change a bit the flist behavior upon end of playlist, I'll investigate.

Feedback more than welcome!

**Comment by jeanlf** [comment]
I just added a keepalive for the playlist - it is now possible to push new segment name as they arrive without closing the playlist for live cases

**Comment by rustyguts** [comment]
I built from master and got a segfault

```sh
cat seglist.txt

segments/0.mp4
segments/1.mp4
segments/2.mp4
segments/3.mp4

gpac -i seglist.txt -o dash.mpd:sigfrag
Segmentation fault
```

Same for a full file, as shown in the [docs](https://github.com/gpac/gpac/wiki/dasher)

```
gpac -i source.mp4 -o dash.mpd:sigfrag
Segmentation fault
```

**Comment by jeanlf** [comment]
hmm I think there's an issue related to the source, could you upload it ?

**Comment by rustyguts** [comment]
Thanks for the help, here are some of my test files.

The segments were prepared with the following command

`ffmpeg -i source.mp4 -f segment -segment_time 10 -an ./segments/%0d.mp4`

```
https://dev-cdn.bken.io/tests/segments/0.mp4
https://dev-cdn.bken.io/tests/segments/1.mp4
https://dev-cdn.bken.io/tests/segments/2.mp4
https://dev-cdn.bken.io/tests/segments/3.mp4

https://dev-cdn.bken.io/tests/source.mp4
```

**Comment by jeanlf** [comment]
crash is fixed, thanks for the file

However what you are testing is not what you asked for: the files are not ISOBMFF segments, they are plain ISOBMFF files, with moov after media data, hence not compatible at all with HTTP streaming formats (CMAF/HLS/DASH/...). I'll add a warning/error in :sigfrag mode for that.

To properly segment the file from your source:
```
MP4Box -dash 10000 -profile live -out ./segments/live.mpd source.mp4
```
or

```
gpac -i source.mp4 -o ./segments/live.mpd:segdur=10:profile=live
```

The remove the generated live.mpd and test manifest generation.
