### ISSUE TITLE
Unable to create HEIC or MP4 from raw single-frame HEVC streams

### ISSUE THREAD

**Issue by Noctem** [gpac/gpac#1524]
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95
---
As of gpac 1.0 I'm no longer able to pack single-frame HEVC streams into HEIC or MP4 using either `MP4Box` or gpac as a library. Here's a command which worked on gpac 0.8 but not on 1.0, along with its output:
```
$ MP4Box -add-image Lenna.hvc:primary -new Lenna.heic
Track Importing HEVC - Width 1024 Height 1024 FPS 1/1 SAR 0/0
HEVC Import results: 1 samples (6 NALUs) - Slices: 1 I 0 P 0 B - 1 SEI - 1 IDR
Warning sample description index for sync sample differ from config
No sample found for requested time

        Error: Bad Parameter

```
This same command works if the stream is contained in an MP4 (`-add-image Lenna.mp4`) but not with the raw stream.

Alternatively trying to create an MP4 from the same image with the following command on 1.0:
```bash
MP4Box -add Lenna.hvc -new Lenna.mp4
```
emits no errors but creates a 774-byte file with metadata and no image data.

Tested on macOS 10.15.5 using gpac 1.0 compiled with clang. [Here is a sample HEVC stream](https://send.firefox.com/download/eb0ebba04f55be31/#xvwHe7t_-mCk2_zK7vaUVQ), but I've had the same results with every single-frame HEVC stream I've tried.

**Comment by jeanlf** [comment]
indeed, now fixed - thanks for report and test content

**Comment by Noctem** [comment]
Thanks for the fix!
