### ISSUE TITLE
forcesync no longer working

### ISSUE THREAD

**Issue by Noctem** [gpac/gpac#1526]
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95
---
I regularly use `:forcesync` (in MP4Box) and `GF_IMPORT_FORCE_SYNC` (in my own code) flags to force the creation of sync samples for HEVC files that would otherwise only be created with one (apparently for [this reason](https://github.com/gpac/gpac/issues/463#issuecomment-200816181)).

This worked until version 1.0 and subsequent commits, now my x265 encoded files are created with only one sync sample regardless of the flags used. Seeking in such files is fine with libav but very slow with Apple's decoder.

Reproduce:
```bash
#ffmpeg -i BigBuckBunny.mkv -c:v libx265 -crf 18 -an -sn BigBuckBunny.hevc
MP4Box -add BigBuckBunny.hevc:forcesync -new BigBuckBunny.mp4

# check number of sync samples:
#MP4Box -info BigBuckBunny.mp4
```

**Comment by jeanlf** [comment]
my bad, I forgot to port this option to filters - now fixed on git and [test](https://github.com/gpac/testsuite/blob/filters/scripts/mp4box-gdr.sh) added, thanks for the report!

**Comment by Noctem** [comment]
Thanks!
