### ISSUE TITLE
Can't build test app

### ISSUE THREAD

**Issue by lgbaldoni** [gpac/gpac#1527]
Namely udptsseg on openSUSE Tumbleweed.

Using gpac 1.0.0, see [log snippet](https://github.com/gpac/gpac/files/4840545/udptsseg.txt).

**Comment by aureliendavid** [comment]
Hi, 

Is it something you actually use or is the broken build just stopping some script or something like that?

I suspect some of the testapps should be deprecated but if they're used we may need to update them.

**Comment by lgbaldoni** [comment]
I'm updating the gpac package for openSUSE linux. That app was being shipped in the past, but if deprecated, I'll simply remove it.

**Comment by aureliendavid** [comment]
I think you can remove all the testapps from the package and we'll be moving them to deprecated. Maybe if there is demand to update specific ones we'll do that.

**Comment by lgbaldoni** [comment]
I see. How about osmo4_wx? Do you think it's salvageable?

**Comment by jeanlf** [comment]
not without a lot of code rewrite I'm afraid - these UIs app haven't been maintained for almost 10 years...
