### ISSUE TITLE
full screen issue

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#153]
Revert 375a0a9c1da48d369c03ec379cee50043ff297f5 (see #152) to be able to play http://d3sporhxbkob1v.cloudfront.net/bill/vod/sample-video/400k.m3u8

Double-click to full screen. When typing on the 'escape' key, the full screen is black with the image at tits original resolution on the bottom left corner, no window. Alt-tab was stuck, I had to do ctrl+alt+sup on Windows to get control again.

Thanks for your help :)

**Comment by jeanlf** [comment]
Is this still valid ?
