### ISSUE TITLE
Crash of gpac when trying dasher with stl option

### ISSUE THREAD

**Issue by ricardollovera** [gpac/gpac#1530]
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hi,

### Introduction (you can skip this to address the crash)
I am starting to use dasher to try to manufacture homemade CMAF stream for tests.

I have performed several 'experiments' of gpac and mp4box using these references of documentation (among other doc webpages):

https://github.com/gpac/gpac/wiki/dasher
https://github.com/gpac/gpac/wiki/mp4box-dash-opts
Specially: https://dl.acm.org/doi/pdf/10.1145/3339825.3394929 

My purpose indeed is not to achieve tl, but I was trying different options to understand as Documentation is hard for beginners. My objective is to have Dash of ~6s segments with Chunks of ~600ms and preferably in template (more or less as my commented line in my older MP4box command line). 

A plus knoledg would be to KNOW HOW to control the WINDOW of available segments and chunks in the servers before any flush. Sometimes MP4Box creates all the segments once or "it never ends", thats why I want to learn gpac filters, because it seems in the good way, as per results of subfolder 6 (cf. Logs) 

### Actions / Steps / Observations
I execute the bash inside the folders..
`~]# ./gpac_experiment.bash`
inside it is only: 
`~]# gpac -i /var/www/html/onDemand/videos/1.mp4#video -i /var/www/html/onDemand/videos/1.mp4#audio reframer:rt=on @ -o /var/www/html/experiment_gpac_public/master.mpd:segdur=4.0:stl=true:tpl=false:dmode=dynamic`

In my destination folder, which I also copied, I achieve only 8 segments for each track, the 2 init and the mpd.

Suddenly it crashes with Segmentation fault. Systematic. And also verified with the HEAD.

### Problem
This is the bt:

> (gdb) bt
> #0  0x00007f1e63531884 in gf_mpd_segment_url_free () from /usr/local/lib/libgpac.so.10
> #1  0x00007f1e636b6450 in dasher_update_period_duration.isra () from /usr/local/lib/libgpac.so.10
> #2  0x00007f1e636c4d9b in dasher_process () from /usr/local/lib/libgpac.so.10
> #3  0x00007f1e636aab43 in gf_filter_process_task () from /usr/local/lib/libgpac.so.10
> #4  0x00007f1e6369b635 in gf_fs_thread_proc () from /usr/local/lib/libgpac.so.10
> #5  0x00007f1e6369edb0 in gf_fs_run () from /usr/local/lib/libgpac.so.10
> #6  0x000000000040c50b in gpac_main ()
> #7  0x00007f1e62edb731 in __libc_start_main (main=0x403d60 <main>, argc=9, argv=0x7ffd986816a8, init=<optimized out>,
>     fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd98681698) at ../csu/libc-start.c:289
> #8  0x0000000000403d99 in _start ()

### Condition
Version: gpac - GPAC command line filter engine - version 1.0.0-rev59-g5a10a36-master
Setup: 4.11.12-100.fc24.x86_64 #1 SMP Fri Jul 21 17:35:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Logs
LOGS 10 & 11 for the same crash (script, outputdir, backtrace, coredump)
Other logs (other folders) containing anomalies or bad tryouts/manipulations . Only the 6th is the best tryout or nearest to what I want, but no idea on how to have chunks correctly :(
https://www.mediafire.com/file/a9jcoekjo97jw9c/experiments.7z/file

----------------

My best regards, special salutation to Jean, Aurelian and Romain :)

**Comment by jeanlf** [comment]
looks like the bug comes from the source material, I cannot reproduce with my test files.

Any chance you can upload the audio and video files so that I can have a deeper look ?

And any suggestion to improve the doc is more than welcome :)  I want to have a howto on that topic in the wiki, might be the right opportunity!

Cheers,
Jean.

**Comment by ricardollovera** [comment]
Hi,

It is BBB content, I have tested it a bit with other segmenters such as ffmpeg.
Hope that you find the upload here, I share: https://www.mediafire.com/file/tdu59ueqiho0ba9/BBB_renamed_to_1.mp4/file

My suggestion to improve the doc is to really unify it and try to give more examples. The perspective of these examples should be from a Results standpoint or point of view.

Other suggestion is to take for example the website of FFMPEG's wiki.
They overall wiki is: https://trac.ffmpeg.org/wiki
One particular subject of example, the compilation guide for Debian alike platforms: https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu

For retesting in the HEAD of the master branch for example I had to repeat the install erasing repertories (no real upgrade documentation or i dont know how to use git in that only purpose.

I really hope that this new step forward of GPAC in v-1.0 gives it a leap for its global further adoption (server and client) and thedocumentation is important in the way that it allows to do so reducing support.

Regards, keep me posted please regarding that CMAF desire or chunk parametrization in different dash types.

**Comment by ricardollovera** [comment]
Hi,

Thanks for the patch, no longer seen the crash. Although other behaviors (I'd file other issue if details)... And I still don't know how to control the window number and number of chunks for CMAF.

**Revision tested and without crash:** 
```
~]# /usr/local/bin/gpac -version
Nothing to do, check usage "gpac -h"
gpac - GPAC command line filter engine - version 1.0.0-rev69-gac77318-master
(c) 2000-2020 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io
```

I think you can close the ticket.

Regards,
