### ISSUE TITLE
config.h gpac.pc were not installed properly

### ISSUE THREAD

**Issue by zhoub** [gpac/gpac#1531]
Hi !

Using latest commit `7f0075ebc4cbc008b79c6da9daa8939e6809f24e` from master branch.

Enter source folder, type command line
```bash
./configure --prefix=`pwd`/dist-master
```

then `make -j10 install`.

Under prefix folder `dist-master`, there is no `gpac.pc` file installed, it seems that the script checks if the folder exists, which is not true when using customized prefix path as following output
```
if [ -d /home/user/gpac-repo/dist-master/lib/pkgconfig ] ; then \
install  -m 644 gpac.pc "/home/user/gpac-repo/dist-master/lib/pkgconfig" ; \
fi
```

Another very annoying thing is that generated config.h was not installed to prefix, the file `dist-master/include/gpac/configuration.h` would not be replaced by generated one.

Once external program which needs to include gpac would always report ```#error "Unknown target platform used with static configuration file```.

Please have a look, thanks.

**Comment by aureliendavid** [comment]
> Under prefix folder `dist-master`, there is no `gpac.pc` file installed, it seems that the script checks if the folder exists, which is not true when using customized prefix path as following output
> 
> ```
> if [ -d /home/user/gpac-repo/dist-master/lib/pkgconfig ] ; then \
> install  -m 644 gpac.pc "/home/user/gpac-repo/dist-master/lib/pkgconfig" ; \
> fi
> ```
> 

Yes I think this was done in order to avoid creating a /usr/lib/pkgconfig directory on systems where pkgconfig is not installed. But I agree that your case it's a problem. I'm not sure which solution is best. Should we create the directory regardless?

> Another very annoying thing is that generated config.h was not installed to prefix, the file `dist-master/include/gpac/configuration.h` would not be replaced by generated one.
> 
> Once external program which needs to include gpac would always report `#error "Unknown target platform used with static configuration file`.
> 

Try `make install-lib` (see https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux#install-for-developers)

It should probably be done on make install too since we already copy the includes. 

I'll have a look.

**Comment by zhoub** [comment]
Hi !

About the .pc file, usually it's possible to build and install library to customized party location rather than ```/usr/local```, and user could set ```PKG_CONFIG_PATH``` to let ```pkg-config``` locate the library as usual.

I'm using latest master branch, from `make help`, I could not see a target named *install-lib*
```bash
user@ubuntu16:~/gpac-repo$ make help
Input to GPAC make:
depend/dep: builds dependencies (dev only)
all (void): builds main library, programs and plugins
lib: builds GPAC library only (libgpac.so)
apps: builds programs only
modules: builds modules only
instmoz: build and local install of osmozilla
sggen: builds scene graph generators

clean: clean src repository
distclean: clean src repository and host config file

install: install applications and modules on system
uninstall: uninstall applications and modules
```

Thanks a lot !

**Comment by aureliendavid** [comment]
> I'm using latest master branch, from `make help`, I could not see a target named _install-lib_

that's a good catch, an indentation error cut the help message short and prevented displaying the rest, I hadn't noticed that

I push some changes to the Makefile (hopefully I didn't break anything) including for your purpose always installing gpac.pc and config.h

**Comment by zhoub** [comment]
Hi

thanks for the fixed, another small issue on `make install-lib`
```
user@ubuntu16:~/Development/gpac-repo$ make install-lib
install -d "/home/user/gpac-repo/dist-master/include/gpac"
install -d "/home/user/gpac-repo/dist-master/include/gpac/internal"
install -d "/home/user/gpac-repo/dist-master/include/gpac/modules"
install  -m 644 /home/user/gpac-repo/include/gpac/*.h "/home/user/gpac-repo/dist-master/include/gpac"
install  -m 644 /home/user/gpac-repo/include/gpac/internal/*.h "/home/user/gpac-repo/dist-master/include/gpac/internal"
install  -m 644 /home/user/gpac-repo/include/gpac/modules/*.h "/home/user/gpac-repo/dist-master/include/gpac/modules"
install  -m 644 config.h "/home/user/gpac-repo/dist-master/include/gpac/configuration.h" || true
install -d "/home/user/gpac-repo/dist-master/lib"
install  -m 644 "./bin/gcc/libgpac_static.a" "/home/user/gpac-repo/dist-master/lib" || true
install -d /home/user/gpac-repo/dist-master/lib/pkgconfig
install  -m 644 gpac.pc "/home/user/gpac-repo/dist-master/lib/pkgconfig"
make installdylib
make[1]: Entering directory '/home/user/gpac-repo'
install -d "/home/user/gpac-repo/dist-master/lib"
install  -m 755 bin/gcc/libgpac.so.10.0.0 /home/user/gpac-repo/dist-master/lib/libgpac.so.10.0.0
ln -sf libgpac.so.10.0.0 /home/user/gpac-repo/dist-master/lib/libgpac.so.10
ln -sf libgpac.so.10.0.0 /home/user/gpac-repo/dist-master/lib/libgpac.so
ldconfig || true
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
make[1]: Leaving directory '/home/user/gpac-repo'
```

At the last step there is `/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied`, is that mandatory to acquire administration permission for this if user just installed to local path rather than `/usr/local` ?

Thanks a lot !

**Comment by aureliendavid** [comment]
> At the last step there is `/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied`, is that mandatory to acquire administration permission for this if user just installed to local path rather than `/usr/local` ?

It's not mandatory and the message is not an error. The command run is `ldconfig || true` meaning if we can't (like for a local install) continue without error. The message is still displayed but can be ignored (you can check that make install exists with a success return code). 

If they aren't anymore problem with the make install please close the issue. Thanks.
