### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by s0m30n3** [gpac/gpac#1532]
Hi there,

I'm using the gpac library in my own project and from time to time, I update and recompile the project to get new features like HEVC support.

I recently faced a really strange issue I do not explain:
- gf_sys_init has a single parameter at [39367c29f21232e61f6883607c1d1c677bc28ccd ](https://github.com/gpac/gpac/blob/39367c29f21232e61f6883607c1d1c677bc28ccd/include/gpac/tools.h)(June 5, 2020)
- the next commit [44af1e163e53ab1d6f40921fdc033edd78aa6c51](https://github.com/gpac/gpac/blob/44af1e163e53ab1d6f40921fdc033edd78aa6c51/include/gpac/tools.h) it has one more parameter
- until commit [31f15a73c69f8e019a2a83d7dcbeef3c68a48ee0](https://github.com/gpac/gpac/blob/31f15a73c69f8e019a2a83d7dcbeef3c68a48ee0/include/gpac/tools.h) (June 11, 2020) where function go back to a single parameter
- and again, the following commit [ddc5db70b3f0df1f531882a11fb9c6900013b958](https://github.com/gpac/gpac/blob/ddc5db70b3f0df1f531882a11fb9c6900013b958/include/gpac/tools.h) have a gf_sys_init function with two parameters

I get the history from [here](https://github.com/gpac/gpac/commits/master?after=7f0075ebc4cbc008b79c6da9daa8939e6809f24e+104) and my local tree is at 39367c29f21232e61f6883607c1d1c677bc28ccd (June 5, 2020) and gf_sys_init has a single parameter.

I tracked down the change to commit 4ada86964068854dada4c4a2121d193ca63ba5fd which happened .. 2 years ago!
How did my git clone from the 5th of june may not have that commit applied?

And since I'm creating a new issue, please be careful when modifying public function prototypes, it breaks all project using your library. You may add a number at the end of the function name like gf_sys_init2 or add a single gf_sys_init_ex that takes a structure whose content may evolve at will.

Thanks!

**Comment by jeanlf** [comment]
We merged the dev version (0.9.0-dev) into master in june, which explains why you didn't see the change in early june on master (was still 0.8)
We try to pay attention on API compatibility (although this could be improved), ande usually try to suffix function names when it make sense to keep the old API. However for 1.0 there were a lot of changes in many APIs, and moving all of the changes as FOO_ex would have been a real burden.

Note that for 1.0 we changed the major version of libgpac (macro GPAC_VERSION_MAJOR in version.h) to 10 so that one can detect the changes at compil time.

**Comment by s0m30n3** [comment]
For your information, I was manually adding a text/subtitle stream to an existing MP4 file using:
- gf_odf_desc_new(GF_ODF_TX3G_TAG)
- gf_isom_new_text_description
- gf_isom_new_text_sample
- gf_isom_text_add_text
- gf_isom_text_to_sample
- gf_isom_add_sample
but you removed gf_isom_text_to_sample in 56a228e391da55275937db1d1feaf1a1bdceb70c considering it was unused yet publicly exported.

I will stick to the old version for now and try to find an alternative.

**Comment by jeanlf** [comment]
oh sorry about that, we can add that back - did you find any other functions from libisomedia that we removed but you still need ?

**Comment by s0m30n3** [comment]
Thanks for your proposal but I do think the best option for us is to modify our code to use ffmpeg (libav*) and drop the libgpac dependency.

Using libgpac was a first (easy) step but now our needs evolved and using a full-featured multimedia framework seems more natural.

Anyway, thanks for your hard work!

**Comment by jeanlf** [comment]
ok - just so you know gpac 1.0 has full support for libav*
