### ISSUE TITLE
Documentation for dasher missing some clarification (low latency applications)

### ISSUE THREAD

**Issue by ricardollovera** [gpac/gpac#1533]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

-----

Hi Gpac team,

I wish to have information about the usage of the DASHER for CMAF alike generation, and the documentation of some options.

In https://dl.acm.org/doi/abs/10.1145/3339825.3394929 some examples for low latency are shown in chapter 5.

> MP4Box −dash− l i v e 1000 −f r a g 100 −f r a g −r t −
> a s t − o f f s e t 900 − p r o f i l e l i v e q1 .mp4 q2 .
> mp4 −out h t t p : / / foo . ba r / l i v e .mpd : hmode=
> push
> 
> 
> The new architecture also provides an HTTP server designed
> for low latency DASH streaming, capable of both writing to disk
> and pushing to the client(s). This ensures that client connecting to
> the live edge will be pushed segments as they are delivered by the
> dasher, while other clients will be delivered segments as stored on
> disk. The operation does not require any file system monitoring
> nor complex signaling (ad-hoc boxes in segments).
> 
> 
> gpac −i q1 .mp4 −i q2 .mp4 r e f r ame r : r t =on @ −
> out h t t p : / / l o c a l h o s t : 8 0 / l i v e .mpd : gpac :
> r d i r s = . / temp : wdir = . / temp : cdur = 0 . 1 : a s t o
> = 0 . 9 : dmode=dynamic
> 
> 
> Thanks to the support for live grabbers and encoders, the input
> can be audio and video from a live webcam:
> 
> 
> gpac −i av : / / enc : c=avc : b=2M: f i n t r a =1 : FID=V
> enc : c= aac : b =128 k : FID=A −out h t t p : / / foo .
> ba r / l i v e .mpd : gpac : SID=V,A: r d i r s = . / temp :
> wdir = . / temp : cdur = 0 . 1 : a s t o = 0 . 9 : dmode=
> dynamic

But in the help of the binary (/usr/local/bin/gpac -hx dasher or /usr/local/bin/gpac -ha dasher or general) we dont have explanations of some parameter options (eg. cdur, rdirs, wdirs). 

In the gpac wiki site, filters site I didnt find anything neither.

Although the names of option seem intuitive, the actual usage for CHUNKS parametrization is unknown for me. And the using of the option have not generated me any chunk (subdivision of the dash segment).

The control of the windows size (number of segments or chunks, whatever the case, in the server)  is unknown for me.

Thank you a lot for your help !
 
-----
Regards,

**Comment by jeanlf** [comment]
Have you read the [general concepts](https://github.com/gpac/gpac/wiki/filters_general) page ? The section on [argument inheriting](https://github.com/gpac/gpac/wiki/filters_general#arguments-inheriting) will help you there.

In short, in this example, the options are specified on one destination but do not apply only to the destination, they may target any filters dynamically loaded to solve the graph.

 The help is also available for options (I just updated the general help, it was missing this part):

```
% gpac -h cdur      
No such filter "cdur" but found filters with matching options:
mp4mx.cdur: chunk duration for interleaving and fragmentation modes
	* 0: no specific interleaving but moov first
	* negative: defaults to 1.0 unless overridden by storage profile
```
 
The help will also try to give you a list of possible options if none matched:

```
% gpac -h wdi 
No such filter "wdi"
Closest matching filter option:
nhmlw.dims 
vout.disp 
m2tsmx.disc 
httpout.wdir 
```

I'll update the wiki with a bit more examples (and a page on LLDASH)

**Comment by ricardollovera** [comment]
Hello,

Yes Jean, I read it for a second time with your message, it is always good to read a re-read to understand better.

I suggest to make it more visible, and in other font color maybe, the explanation of the examples in each syntax (option of the filter, each parameter and each filter working/or ignored as per syntax). One single correction is to separate more the paragraph once the example 'above' finished.

I am looking forward to this LL DASH samples (specially the window control, chunk size control, etc).

Best regards,

**Comment by ricardollovera** [comment]
Hi all,

Hope you are doing good. I was wondering if you forgot or have some exif you already have some examples of Ultra Low Latency (using the different evoked filters) or if you are still preparing a new wiki-page.

Best regards,

**Comment by jeanlf** [comment]
Here you go !

[https://github.com/gpac/gpac/wiki/dash_low_latency](https://github.com/gpac/gpac/wiki/dash_low_latency)

**Comment by jeanlf** [comment]
I would suggest you first try locally between two gpac instances to see if your setup is correct:

- streamer
```gpac
//source
-i source.mp4
//realtime regulation
reframer:rt=on
//dashing in dynamic mode (default dur 1s), 100ms chunks and logging GET requests
 @ -o http://localhost:8080/live.mpd:rdirs=temp:wdir=temp:cdur=0.1:reqlog=GET:dynamic
```

- client
```gpac -play http://localhost:8080/live.mpd```

You chould see in the server logs:

`[HTTPOut] REQ#4 127.0.0.1 GET source_dash_track1_2.m4s start chunk-transfer`

indicating that chunk transfer is used (player is on the live edge).

Once you are sure this is OK, you can start looking at other players behaviors.

PS: I'll update the server to expose 'Accept-Ranges', that's indeed missing in the request but it is supported

**Comment by ricardollovera** [comment]
Hi Jean,


Thank you very much for your suggestions and I apologize to you in advance for writing you in this "closed" ticket.



Indeed that extra last comment is something **very useful** that can be incorporated in a Documentation for CMAF and **to know if setup is correct**.

While performing some tests I realized that my environnement was not very well since the player didn't launched in the same linux, and it crashed when I tried in one other version of a remote windows (when I downloaded and tried to see in another machine that had Graphical interface, but let's not loose focus).

1. **I Installed all over gpac and created a script for full install in fedora**. Maybe to add in the wiki Docs for Building in Linux. Upgrade procedure already described in the wiki is not 100% reliable for me. _So, I give it to you as a gift since it eases an update_ (pkg names are completely different for those distributions of Linux and please observe that the typically installed packages for that environnement are maybe not necessary all of them or redundant). [ATTACHMENT]


2. I realized that **I had to uninstall all existing ffmpeg** in that environnement to be able to "make" gpac_public (I later put it also in the same install script) :o) 💯 
[IT WAS PRODUCING THIS BUILD ERROR: `filters/ff_common.c: In function ‘ffmpeg_arg_translate’:
filters/ff_common.c:510:7: error: ‘AV_OPT_TYPE_UINT64’ undeclared (first use in this function)
  case AV_OPT_TYPE_UINT64:
`]


3. It finally recompiled and when I was about to launch "gpac -play..." it was giving me Audio errors. I added all pkg containing the word 'audio' in that Fedora, it didn't help (I really don't know, so I left all these in the bash). At the end I wondered if installing "Audacity" software (free audio editor software) via the Linux GUI I also had to install arranged for itself or some sort of dependencies. It seems it did completed audio dependencies lacks/problems resolved. It worked  "gpac -play..." later after this 👍 !!! So I was very happy. :) :) :) :)
[IT WAS PRODUCING ME OVERALL THIS ERROR: `[SDL] Audio output format not supported
[AudioOut] Could not setup module SDL Audio Output
Error I/O Error while instantiating filter aout
Failed to load filter "aout": I/O Error`]


4. Finally, last and not least, I saw that the command you gave me produced of course a segment duration of 1s and chunks of 0.1s; but player was TOO much advanced in time or in other words it was in the FUTURE of live edge (of about 5-8s). Since I didn't find other options for the "gpac -play..." command such as introducing artificial ast delay, I "tunned" or "tweaked" your suggestion in order to avoid this. I did avoided it by making segdur=10 and cdur=1 at first try. Player was not that hurried and I could see the trace I was looking for... ;)



###  SUCCESS.

`[21:37:39.098Z] GPAC Session Status: mem     665157 kb CPU  0
30min_countdown.mp4 (fin): 30min_countdown.mp4: EOS (dispatch canceled after 5000 b, file size 85845943 b)
reframer: 2 input PIDs      10743 pck 2 output PIDs      10743 pck
manifest_mpd (httpout): File 3 input PIDs        655 pck
30min_countdown.mp4 (mp4dmx): File 1 input PIDs          2 pck 2 output PIDs      10744 pck - EOS
dasher: PDID1 AS#1.1(V) seg #16 7.56s (75.60 %) AS#2.1(A) seg #16 7.57s (75.71 %) / MPD 157.57s 8 %
V1 (mp4mx): mux segments 15 (frags 8) next 1.6e+02 TK1(V): 15 8 %
A2 (mp4mx): mux segments 15 (frags 8) next 1.6e+02 TK2(A): 29 8 %
Active filters: 7`

`Logs:
[21:37:15.371Z] [HTTPOut] REQ#22 GET done: reply 200 - 981 bytes in 994 ms at 7.89137 kbps
[21:37:15.371Z] [HTTPOut] REQ#23 127.0.0.1 GET experiment_gpac_jean/30min_countdown_dash_track2_init.mp4 start
[21:37:15.371Z] [HTTPOut] REQ#23 GET done: reply 200 - 889 bytes in 0 ms at 82.6977 mbps
[21:37:21.378Z] [HTTPOut] REQ#24 127.0.0.1 GET experiment_gpac_jean/30min_countdown_dash_track1_14.m4s start chunk-transfer   <<<<<<<=============== HERE :) :) :)
[21:37:25.373Z] [HTTPOut] REQ#25 127.0.0.1 GET experiment_gpac_jean/test.mpd start
[21:37:25.373Z] [HTTPOut] REQ#25 GET done: reply 200 - 1631 bytes in 0 ms at 100.369 mbps
[21:37:31.271Z] [HTTPOut] REQ#24 GET done: reply 200 - 347402 bytes in 9892 ms at 280.935 kbps
[21:37:36.379Z] [HTTPOut] REQ#26 127.0.0.1 GET experiment_gpac_jean/test.mpd start
[21:37:36.379Z] [HTTPOut] REQ#26 GET done: reply 200 - 1631 bytes in 0 ms at 112.483 mbps
`


Please find scripts and test in the file attachment.

Conversation
=========
User-Agent: GPAC/1.0.0-rev188-g2aa266d-master
Server: GPAC 1.0.0


Best regards,

[bash_and_test.zip](https://github.com/gpac/gpac/files/5019005/bash_and_test.zip)

**Comment by ricardollovera** [comment]
Hi Dear @jeanlf , 

Hope everything is well and doing alright. I estimate you are in holidays and the team too for well deserved rest. Please dont forget to verify last comment and bash for improvements of the project. I'm also affraid that you cant see this comment.

Looking fwd to continue testing ull dash with passion!
My best regards
