### ISSUE TITLE
360 video play

### ISSUE THREAD

**Issue by SivanLiu** [gpac/gpac#1537]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I have try play 360 video on android huawei nexus6p(Android 10)，but the result is the same as 2D video, there should be no back projection and can't swipe to switch perspective.

![image](https://user-images.githubusercontent.com/8191309/86871470-edb43500-c10c-11ea-93ba-fb4935545f05.png)

I have another question about
![image](https://user-images.githubusercontent.com/8191309/86871674-556a8000-c10d-11ea-8f6a-d6f9c803b809.png)

the full name of EQR is Equi-Rectangular Projection? and I have to use the video be projection of EQR can work well?

**Comment by jeanlf** [comment]
how to you open the video ? 360 for now must be activated manually by long-clicking on the file and selecting "view as 360". This works fine on my test device (htc10)

**Comment by SivanLiu** [comment]
> how to you open the video ? 360 for now must be activated manually by long-clicking on the file and selecting "view as 360". This works fine on my test device (htc10)

1、Thanks for your help, the way to open the video by your way and it works well, but it can't swipe to switch perspective and only rotate the phone to switch the angle of view

I‘m sorry for ask for your another question:
2、"The player also support 360 video(EQR projection only for now)"
the full name of EQR is Equi-Rectangular Projection? and I have to use the video be projection of EQR can work well?

thanks

**Comment by jeanlf** [comment]
> it can't swipe to switch perspective and only rotate the phone to switch the angle of view
you have to switch the navigation mode (the 4-arrows button) to "mouse and keyboard" rather than device sensor

> the full name of EQR is Equi-Rectangular Projection? and I have to use the video be projection of EQR can work well?

Yes we only support equi-rectangular projection ( = EQR), no cube maps or others for the time being. So the source has to be in this format

**Comment by SivanLiu** [comment]
> > it can't swipe to switch perspective and only rotate the phone to switch the angle of view
> > you have to switch the navigation mode (the 4-arrows button) to "mouse and keyboard" rather than device sensor
> 
> > the full name of EQR is Equi-Rectangular Projection? and I have to use the video be projection of EQR can work well?
> 
> Yes we only support equi-rectangular projection ( = EQR), no cube maps or others for the time being. So the source has to be in this format

Thanks for your help, I understand.
