### ISSUE TITLE
h.264 tiles

### ISSUE THREAD

**Issue by a23232390** [gpac/gpac#1538]
I have this problem  i use MP4BOX but i cant run 

PS D:\360\GPAC> MP4Box -dash 1000 hight.mp4:desc_as=<SupplementalProperty schemeIdUri=\"urn:mpeg:dash:srd:2014\" value=\"0,0,1,1,1,2,2\"/>
[DASH] Cannot open file schemeIdUri=\urn for dashing: Requested URL is not valid or cannot be found
DASH Setup Error: Requested URL is not valid or cannot be found

**Comment by jeanlf** [comment]
You must quote your xml, potentially escaping internal XML quotes, otherwise arguments won't properly be passed to the app's main() :

% MP4Box -dash 1000 hight.mp4:desc_as="<SupplementalProperty schemeIdUri=\"urn:mpeg:srd:2014\" value=\"0,0,1,1,1,2,2\"/>"`
