### ISSUE TITLE
OpenSVCDecoder DLL needed by MP4Box not included when installing MP4Box only on Windows

### ISSUE THREAD

**Issue by mjb2010** [gpac/gpac#1539]
When only MP4Box is installed on Windows, attempting to run mp4box.exe results in a System Error: _The program can't start because OpenSVCDecoder.dll is missing from your computer. Try reinstalling the program to fix this problem._

Steps to reproduce:

On a Windows system that does not have GPAC installed, download and install the latest Win x64 nightly build (e.g. 1.0.0 for x64 revision 112-g09fb485a). During installation, enable MP4box only. (Naturally, gpac core remains enabled too, since it cannot be disabled.)

Try to run %Program Files%\GPAC\mp4box.exe and observe the System Error dialog.

Repeating the install process did not help. However, doing a full installation (leaving all the tickboxes enabled) resulted in the installation of the missing DLL, so presumably it is installed with another component—perhaps GPAC Player?

**Comment by aureliendavid** [comment]
you're right, some of the things that should be installed in gpac core were installed only with the player

should be fixed in https://download.tsi.telecom-paristech.fr/gpac/new_builds/win64/gpac-1.0.0-rev115-g502bae14-master-x64.exe

thanks for the report

**Comment by mjb2010** [comment]
Yup, that new installer worked as expected. Thanks!
