### ISSUE TITLE
Custom Prefix Location = Can not Run Program

### ISSUE THREAD

**Issue by zhoub** [gpac/gpac#1540]
Hi !

Tried to compile and install to a customized prefix path rather than `/usr/local`, for example `/home/user/Downloads/gpac/dist`, if setup the **LD_LIBRARY_PATH** to `/home/user/Downloads/gpac/dist/lib`, then tried to run either gpac or MP4Box under `bin` folder, it always prints 
```bash
[Core] default modules not found
[core] Cannot create config file GPAC.cfg in /home/user/.gpac directory
Fatal error: failed to initialize GPAC global configuration
```
Even created the folder `.gpac` in `$HOME` folder but it still not work, it just could not create the config file. Not sure why. Please have a look.

Thanks a lot.

**Comment by aureliendavid** [comment]
thanks for the report, it should be fixed now

can you test and report back? thanks

**Comment by zhoub** [comment]
Yes, it works, thanks for fixing.
