### ISSUE TITLE
Failed to Parse Segment File from Bitmovin

### ISSUE THREAD

**Issue by zhoub** [gpac/gpac#1541]
Hi !

Please check the uploaded zip file [hls_fMP4_by_Bitmovin.zip](https://github.com/gpac/gpac/files/4918255/hls_fMP4_by_Bitmovin.zip) which contains 3 files
* init.mp4
* segment_0.m2s
* init_seg_0_1.mp4

The 3rd file was concated from 1st and 2nd file. They're generated from GPAC 0.53 .

Write a very simple program to parse `segment_0.m2s`, but crashed, here is the error
```C++
#include <iostream>

#include <gpac/avparse.h>
#include <gpac/isomedia.h>

int main(int argc, char *argv[])
{
    const char *filePath = argv[1];
    u32 fileType = gf_isom_probe_file(filePath);
    std::cout << fileType << std::endl;
    
    GF_ISOFile *file = gf_isom_open(filePath, GF_ISOM_OPEN_READ, NULL);
    
    u32 brand = 0, version = 0;
    Bool hasSeg = gf_isom_has_segment(file, &brand, &version);
    if (hasSeg == GF_TRUE) {
        std::cout << brand << ' ' << version << std::endl;
    }

    return 0;
}
```

It outputs
```bash
3
[iso file] Movie fragment but no moov (yet) - possibly broken parsing!
[iso file] Error: moov not received before merging fragment
Segmentation fault (core dumped)
```

According document, 3 = media segment, it's correct. But the `segment_0.m4s` file doesn't have any [ftyp] box, here is its layout
```
[styp] (unsupported box type) Size=24 Data=[...] (use -a option to show all)
[sidx] (unsupported box type) Size=44 Data=[...] (use -a option to show all)
[moof] Size=888 
  [mfhd] Size=16 Version=0 Flags=0x000000 SequenceNumber=1
  [traf] Size=864 
    [tfhd] Size=16 Version=0 Flags=0x020000 TrackID=1
    [tfdt] Size=16 Version=0 Flags=0x000000 BaseMediaDecodeTimeV0=0
    [trun] Size=824 ... (use -a option to show all)
[mdat] Size=490058 Data=[...] (use -mdat option to expand)
```
So it onlyl contains the samples for the TrackID=1.

Another question is how to generate the file similar to `segment_0.m4s` by API ?

Thanks a lot.

**Comment by jeanlf** [comment]
gf_isom_open returns NULL in this case, because the file is not a full file but only a segment. Your segfault comes from the fact that you are passing a NULL pointer to the gf_isom_XXX functions which assume a non-null pointer.

The proper way to do this is:
- open the init segment file in read mode
- then open segment using gf_isom_open_segment
- fetch your samples
- then close segments using gf_isom_release_segment, reseting sample numbers if needed using gf_isom_reset_fragment_info
