### ISSUE TITLE
MI9 MIUI12.0.2 Android10 gui not work

### ISSUE THREAD

**Issue by SivanLiu** [gpac/gpac#1542]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

The lastest Osmo4 client not work on Mi9 MIUI 12.0.2(Android 10)，the gui not work normally, the menu button click disappear
and click again, it appears， but it can't perform a function normally.The log and operation video are below:
Please help, Thanks.

[Mi9 Android10 log.txt](https://github.com/gpac/gpac/files/4922479/Mi9.Android10.log.txt)

[The video of osmo4 opertaion log](https://c-t.work/s/9db9b1d62f844e)

**Comment by jeanlf** [comment]
is it the same behaviour with each button (file open, playlist, osom4 logo) ?

**Comment by SivanLiu** [comment]
> is it the same behaviour with each button (file open, playlist, osom4 logo) ?

Yes, the same behaviour with each button(file open, playlist, osom4 logo not work)

**Comment by SivanLiu** [comment]
> is it the same behaviour with each button (file open, playlist, osom4 logo) ?

I have delved into this issue and I have found that it was caused by a problem with the screen adaptation. There are two main reasons:
1. The gui not work normally on notch screen of some device;
2. the focus of open file、home button etc foucs not entire button icon and it only responses below half of icons.

**Comment by jeanlf** [comment]
this should now be fixed on master
