### ISSUE TITLE
Full help output is redirected partially to both stdout and stderr

### ISSUE THREAD

**Issue by LigH-de** [gpac/gpac#1543]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. **I built it myself in MSYS2/MinGW using media-autobuild suite**
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

----

MP4Box built from HEAD revision in MSYS2/MinGW, using media-autobuild suite.
```
MP4Box - GPAC version 1.0.0-rev115-g502bae149-ab-suite
(c) 2000-2020 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io
GPAC Configuration: --prefix=/local64 --disable-shared --enable-static --static-mp4box
Features: GPAC_CONFIG_WIN32 GPAC_64_BITS GPAC_MINIMAL_ODF GPAC_HAS_QJS  GPAC_DISABLE_3D 
```

When I tried to redirect the full help output of MP4Box to a text file to read it later, I realized that one part of the output was sent to **stdout** but another part got sent to **stderr**. Merging it in a linked redirection `2>&1` is unreliable under Windows because it may be bound to output buffer dimensions (e.g. merged at KiB boundaries, not at end-of-line characters).

`MP4Box.exe -h all > MP4Box_out.txt 2> MP4Box_err.txt`

Results attached:

[MP4Box_out.txt](https://github.com/gpac/gpac/files/4925211/MP4Box_out.txt)
[MP4Box_err.txt](https://github.com/gpac/gpac/files/4925212/MP4Box_err.txt)

I would strongly recommend to have a consistent behaviour. In general, **stdout** should be reserved to payload data and **stderr** to console output.

**Comment by jeanlf** [comment]
thanks for the report, now fixed on git

In GPAC:
- in help mode, help output is on stdout
- in non help mode, console/log messages are output on stderr  and data, if any, on stdout

**Comment by LigH-de** [comment]
Thank you for fixing and clarifying.
