### ISSUE TITLE
DASH IFrame based Trick mode sample generation

### ISSUE THREAD

**Issue by harishnb** [gpac/gpac#1547]
Hi,
I am looking for simple commands to generate assets which will support IFrame based Trick mode Forward and reverse. 
I found asset at http://dash.akamaized.net/dash264/TestCases/9a/qualcomm/1/ but would like to generate multiple such assets with different codec. If you can provide set of commands to generate IFrame assets in forward and reverse order it would be of great help.

**Comment by jeanlf** [comment]
The reframer filter can be used to filter out non-IDRs:

```gpac -i source.mp4#video reframer:saps=1 @ -o iframes.mp4```
