### ISSUE TITLE
[HLS] Audio tracks not connected to output filter

### ISSUE THREAD

**Issue by fsteffen-aip** [gpac/gpac#1548]
Hi everybody !

I cannot package an asset to HLS with MPEG2 TS segments. It cannot connect the audio streams.

When I run the command:

`gpac -i variants/video_145000.mp4 -i variants/audio_96000_fra.mp4 -o gpac/index.m3u8:m2ts:segdur=6`

It results with the following error:

```
No filter chain found for PID audio_96000_fra.mp4 in filter dasher to any loaded filters - NOT CONNECTED
[Filter] dasher in error / not responding properly: 2694685 consecutive errors in 1000000 us with no packet discarded or sent
	discarding all inputs and notifying end of stream on all outputs
```

I tried with raw ADTS instead of MPEG4 audio in input, but the result is identical.

The same command with the same assets is working fine with MPEG4 segments, it is only failing with MPEG2 segments.

The problem is arising with GPAC v1.0 (from brew) and latest dev build (version 1.0.0-rev118-g20e9b1de-master from gpac web site). I'm running on MacOS X 10.15.6.

-----------

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
Indeed this was not really working, should now be fixed. could you check ?

Also, when specifying different inputs with gpac, these are by default mapped to different representations. To use muxed representations:

```gpac -i vid.mp4:#Representation=1 -i aud.mp4:#Representation=1 -o res.mpd:m2ts```

I also updated the [test suite](https://github.com/gpac/testsuite/blob/filters/scripts/dash-ts.sh) to check more dash+m2ts cases

**Comment by fsteffen-aip** [comment]
Many thanks, it is working now !

I follow up on your comment about representation. My use case as multiple audio (fra, qaa and qad) and I want to keep the output unmuxed. In DASH the behaviour can be altered with Representation and ASID, but what about HLS ? Right now the output defines multiple renditions, one per audio source, instead of one rendition with alternate. Is there a way to specify this ? I tried to specify the `EXT-X-MEDIA GROUP-ID` with `:#GroupID=`, but it doesn't work.

Here is the command I run:

```
gpac \
    -i variants/video_145000.mp4 \
    -i variants/video_440000.mp4 \
    -i variants/video_978000.mp4 \
    -i variants/video_1588000.mp4 \
    -i variants/video_3190000.mp4 \
    -i variants/audio_96000_fra.mp4 \
    -i variants/audio_96000_qaa.mp4 \
    -i variants/audio_96000_qad.mp4 \
    -o gpac/index.m3u8:m2ts:segdur=6
```

The master playlist is like this (I omitted the various bandwidths for brevity):

```
#EXTM3U
#EXT-X-VERSION: 3
#EXT-X-INDEPENDENT-SEGMENTS

#EXT-X-STREAM-INF:BANDWIDTH=127670,CODECS="avc1.64000D,mp4a.40.2",RESOLUTION=256x144,FRAME-RATE="25",AUDIO="audio2"
index_1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=127670,CODECS="avc1.64000D,mp4a.40.2",RESOLUTION=256x144,FRAME-RATE="25",AUDIO="audio3"
index_1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=127670,CODECS="avc1.64000D,mp4a.40.2",RESOLUTION=256x144,FRAME-RATE="25",AUDIO="audio4"
index_1.m3u8

...

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio2",NAME="6",LANGUAGE="fra",AUTOSELECT=YES,URI="index_6.m3u8",CHANNELS="2"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio3",NAME="7",LANGUAGE="qaa",AUTOSELECT=YES,URI="index_7.m3u8",CHANNELS="2"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio4",NAME="8",LANGUAGE="qad",AUTOSELECT=YES,URI="index_8.m3u8",CHANNELS="2"
```

What I would like to achieve:

```
#EXTM3U
#EXT-X-VERSION: 3
#EXT-X-INDEPENDENT-SEGMENTS

#EXT-X-STREAM-INF:BANDWIDTH=127670,CODECS="avc1.64000D,mp4a.40.2",RESOLUTION=256x144,FRAME-RATE="25",AUDIO="audio2"
index_1.m3u8

...

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio2",NAME="6",LANGUAGE="fra",AUTOSELECT=YES,URI="index_6.m3u8",CHANNELS="2"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio2",NAME="7",LANGUAGE="qaa",AUTOSELECT=YES,URI="index_7.m3u8",CHANNELS="2"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio2",NAME="8",LANGUAGE="qad",AUTOSELECT=YES,URI="index_8.m3u8",CHANNELS="2"
```

**Comment by jeanlf** [comment]
You can now use `:#HLSGroup` to set a common HLS group to your inputs, see [this test](https://github.com/gpac/testsuite/blob/filters/scripts/hls-gen.sh).

Note that the code does not validate the group, so you'd better not mix codecs in the same group...

**Comment by fsteffen-aip** [comment]
Nice ! Thanks, that was quick !

**Comment by fsteffen-aip** [comment]
I noticed two small things in the generated output.

With the previous command, the playlists have a `#EXT-X-MAP:URI="..."` at the top. I don't think an init segment is necessary with a MPEG2 TS container, and anyway the init segment itself is not generated. This renders the asset unplayable.

Also, in the #EXT-X-MEDIA tag, the name is an index. Since this name is used by the players to choose an alternate tracks, it is not really helpful to have a number. Would it be possible to specify a custom name from the command line options for that ?

**Comment by jeanlf** [comment]
The extra `#EXT-X-MAP:URI` in TS multi file is now fixed.

For the NAME attribute, its value is the equivalent DASH representation ID, which defaults to an index if not set. You can overwrite it using `-i source:#Representation=MyName`.

**Comment by fsteffen-aip** [comment]
Great job, thanks !
