### ISSUE TITLE
AES-CTR / CENC IV not incrementing 

### ISSUE THREAD

**Issue by greg80303** [gpac/gpac#155]
I've run into a bug in 'MP4Box -crypt' which I will get 2 identical IVs in a row in the 'senc' box.  InternetExplorer 11 will not play the file when this happens.  The changed that introduced the bug was a36e8d85.  If I checkout right before this change the problem goes away and my encrypted files will play in IE11.

I don't understand the code completely, but the CENC refactor in the change referenced above now looks at the first byte in the IV and only increments the counter if this byte is not 0.  I understand that this first byte is not actually a part of the IV (since the IV buffer is 17 bytes instead of 16), but I don't quite understand what it is used for.  In my test case, this first byte ends up being 0 on the 8th sample and the IV counter is not incremented.

To reproduce, [I have shared the media file and the crypt file here](https://www.dropbox.com/sh/nskuvzticp31su7/AAATNaeVUqGoTaiq9KhVMt0ca?dl=0).

```
MP4Box -crypt pr_video.xml -out encrypted.mp4 video_512x288_h264-360k.mp4
```

**Comment by nguyen-viet-thanh-trung** [comment]
The first byte in the IV is the  current counter position, 0 means that this counter has not been used, and so we don't need to increment it for next sample. I will try to reproduce your case whether we have a bug

**Comment by nguyen-viet-thanh-trung** [comment]
@greg80303  Please check out the lastest version it should be fixed now.

**Comment by greg80303** [comment]
@nguyen-viet-thanh-trung Thank you!  I have confirmed the fix.
