### ISSUE TITLE
MP4Client can t work!

### ISSUE THREAD

**Issue by RoyE3BBB** [gpac/gpac#1550]
when i try to use MP4Client to play a video or mpd, it warning that

> [Compositor] Failed to load a video output module.
> Error I/O Error while instantiating filter compositor
> [Terminal] Failed to load compositor filter: I/O Error
> 
> Init error - check you have at least one video out and one rasterizer...
> Found modules:
> Available modules:
> 	gm_validator.dylib

did i missing any lib?

**Comment by jeanlf** [comment]
you very likely have a configuration problem - did you compile yourself?

**Comment by RoyE3BBB** [comment]
> you very likely have a configuration problem - did you compile yourself?

No, i use brew to install it
`brew install gpac`
i also can t use it after reinstall
