### ISSUE TITLE
Insert rec709 color information into video without re-encoding

### ISSUE THREAD

**Issue by dcsimpson** [gpac/gpac#1552]
Is it possible using mp4box to change the color space information of a video without re-encoding the file?

**Comment by jeanlf** [comment]
You can try specifying the color profile (see `MP4Box -h import`): 
`MP4Box -add source.mp4#video:colr=nclc,1,1,1 -new test.mp4`

Note that this does not rewrite the bitstream, but players should check this added information rather than the bitstream info (according to the spec).

**Comment by dcsimpson** [comment]
It looks like this did change some parameters but not enough to accomplish my goal.  I should explain further.  I am attempting to import rec2020 footage into Adobe Premiere for editing but when you import a rec 2020 HDR10 clip into Premiere it auto converts it into something nasty.  To get around this I have been re-encoding and embedding rec709 parameters into my video file so that when I import it into Premiere the full rec2020 comes in untouched and Premiere doesn't attempt to convert it because it's tricked into thinking it's 709.    Here's the media info for a file that works using this method.  Keep in mind despite the media info you see here this is indeed in fact a rec2020 HDR10 file.    
![Capture](https://user-images.githubusercontent.com/68758284/88564306-0d9a9280-d001-11ea-9def-36e113109296.JPG)

And these are the parameters of my file after modifying them the way you suggested.  Something is still triggering Premiere to still think this is a Rec2020 file.  Is it possible to modify further parameters or even strip them away such as Format Profile or HDR Format as listed in the MediaInfo or whatever other parameter that causes Premiere to think its an HDR file?  And to reiterate I do not want to change the video file itself, just the metadata that tells Premiere what the file is.     
![Capture2](https://user-images.githubusercontent.com/68758284/88564425-34f15f80-d001-11ea-9623-0c9d61b31f95.JPG)

**Comment by jeanlf** [comment]
I think the issue is that premiere is still looking at the info in the video bitstream, I guess that this is the info reported in MediaInfo by `colour_primaries_Original` , `transfer_characteristics_Original` and `matrix_coefficients_Original`. 
Could you upload a small subset of your file (`MP4Box -add src:dur=10 -new short.mp4`)  ?

**Comment by dcsimpson** [comment]
The files are quite large even at 10 sec but can be downloaded here.  Source and output
https://wetransfer.com/downloads/527169184ca81e64eea63a474087f1d720200727163757/01063d047fe4450dda125e31f77c0b8220200727163825/404ff6
