### ISSUE TITLE
CENC - Clear Key encryption with Key rotation not working using MP4Box

### ISSUE THREAD

**Issue by mkcdot** [gpac/gpac#1555]
I am trying to encrypt a video content with key rotation using MP4Box. i.e. I want to encrypt different segments in a 4 min video with different keys.
I am following crypt sample provided by gpac for key rotation.
`<?xml version="1.0" encoding="UTF-8"?>
<GPACDRM type="CENC AES-CTR">

    <DRMInfo type="pssh" version="1" cypherOffset="9" cypherKey="0x6770616363656E6364726D746F6F6C31" cypherIV="0x00000000000000000000000000000001">
        <BS ID128="6770616363656E6364726D746F6F6C31"/>
        <BS value="4" bits="32"/>
        <BS ID128="0x279926496a7f5d25da69f2b3b2799a81"/>
		<BS ID128="0x597669572e55547e656b56586e2f6f68"/>
		<BS ID128="0x205b2b293a342f3d3268293e6f6f4e29"/>
		<BS ID128="0x32783e367c2e4d4d6b46467b3e6b5478"/>
        <BS bits="8" string="CID=Toto"/>
        <BS ID128="0xeee0f2b3b279926496a7f5d25da692f6"/>
		<BS ID128="0x7959493a764556786527517849756635"/>
		<BS ID128="0x3a4f3674376d6c48675a273464447b40"/>
		<BS ID128="0x3e213f6d45584f51713d534f4b417855"/>
    </DRMInfo>
    <CrypTrack trackID="1" IsEncrypted="1" IV_size="16" first_IV="0x0a610676cb88f302d10ac8bc66e039ed" saiSavedBox="senc" keyRoll="roll=4">
        <key KID="0x279926496a7f5d25da69f2b3b2799a81" value="0xeee0f2b3b279926496a7f5d25da692f6"/>
		<key KID="0x597669572e55547e656b56586e2f6f68" value="0x7959493a764556786527517849756635"/>
		<key KID="0x205b2b293a342f3d3268293e6f6f4e29" value="0x3a4f3674376d6c48675a273464447b40"/>
		<key KID="0x32783e367c2e4d4d6b46467b3e6b5478" value="0x3e213f6d45584f51713d534f4b417855"/>
    </CrypTrack>
</GPACDRM>`

I am encrypting the content (audio and video streams separately) using this crypt file with following command:
`MP4Box -crypt crypt.xml input_filename -out output_filename`

Then I am packaging the encrypted content in dash format (onDemand profile) using following command:
`MP4Box -dash 2000 -rap -bs-switching no -sample-groups-traf -profile onDemand  -out dash.mpd audio_aac-lc_128k.mp4 audio_aac-lc_192k.mp4 video_512x288_h264-360k.mp4 video_704x396_h264-620k.mp4 video_896x504_h264-1340k.mp4 video_1280x720_h264-2500k.mp4 video_1920x1080_h264-4500k.mp4 `

I get a manifest (mpd) file (with dash_init file for each content file) with information about only one period i.e. Period 0.
Generated Dash manifest file is attached here.
[dash.txt](https://github.com/gpac/gpac/files/4980970/dash.txt)

There should be multiple period information in manifest file along with KID used for those periods. When I play this dash content on exoplayer, it playback fails immediately without playing.

Can anyone tell whether key rotation is supported for clearkey in MP4Box? If yes, what is wrong in my commands/procedure?

**Comment by jeanlf** [comment]
> There should be multiple period information in manifest file along with KID used for those periods. 

No, key rotation does not impact period assignment, since it is perfectly legal to have one stream with key rotation inside a single period. If you want each of your content in different period, you must specify the period ID of the source content. Also, if you want keys to be listed per representation and not per adaptations set, you must specify it using `-cp-location`.

**Comment by mkcdot** [comment]
How can I encrypt all streams with only one period but with key rotation?

**Comment by jeanlf** [comment]
> Can you tell how can I encrypt all streams with only one period but with key rotation?
That's what you did, just repeat that

> And in this case how would manifest file look like? Will it contain list of KIDs or first KID only or no KID information?
Only the default KID (usually the first) will be listed in the manifest.

I'm not sure how well key rotation is supported by players though ...

**Comment by mkcdot** [comment]
Can you reopen the issue? I am still not clear about how key rotation is supported by MP4Box.

> No, key rotation does not impact period assignment, since it is perfectly legal to have one stream with key rotation inside a single period. If you want each of your content in different period, you must specify the period ID of the source content. Also, if you want keys to be listed per representation and not per adaptations set, you must specify it using `-cp-location`.

Though MP4Box supports key rotation, I am not getting any information about how it can be used correctly. Can you help me with this? I have shared all information and commands/codes for the same. Is there anything wrong in my commands/codes?

As per your previous reply, key rotation is different from multi-period scenario. I did not find where can I assign period ID to different periods of the content. 
If possible, can you give more info on this? How can I generate multi-period content with different key for different period?

**Comment by jeanlf** [comment]
> Though MP4Box supports key rotation, I am not getting any information about how it can be used correctly. Can you help me with this? I have shared all information and commands/codes for the same. Is there anything wrong in my commands/codes?

You are using it correctly and from what I saw there is nothing wrong in your drm config. The problem is likely at the player side. Maybe start investigating by using a single media for your period.

> I did not find where can I assign period ID to different periods of the content.
See `MP4Box -h dash`, you need to set `:period=NAME` on your different inputs.
And obviously you will have to encrypt media of each period with a single key.

**Comment by mkcdot** [comment]
> > Though MP4Box supports key rotation, I am not getting any information about how it can be used correctly. Can you help me with this? I have shared all information and commands/codes for the same. Is there anything wrong in my commands/codes?
> 
> You are using it correctly and from what I saw there is nothing wrong in your drm config. The problem is likely at the player side. Maybe start investigating by using a single media for your period.
> 
As of now, what I observe is exoplayer is not requesting next keys after first key is acquired. So playback stops after approx.20 sec if I use roll=1000 during encryption.
Now I am trying out with different player.

> > See `MP4Box -h dash`, you need to set `:period=NAME` on your different inputs.
> > And obviously you will have to encrypt media of each period with a single key.

Does it mean that for all periods same key should be used?
Can I give different key for different periods? For this, during encryption process we need to specify period-wise keys.
But there is no option in crypt file to define periods for the content. Only trackID option is available.

**Comment by jeanlf** [comment]
> exoplayer is not requesting next keys after first key is acquired.

Did you check this: https://exoplayer.dev/drm.html

> Does it mean that for all periods same key should be used?

It depends on players, it looks like exoplayer handles different key in the same way as key rotation

> Can I give different key for different periods? 

This should not be a problem

> But there is no option in crypt file to define periods for the content. 

No, each period will need its own input files, you need to split your input files first (using `MP4Box -split`for example)

**Comment by mkcdot** [comment]
> > Does it mean that for all periods same key should be used?
> 
> It depends on players, it looks like exoplayer handles different key in the same way as key rotation
> 
> > Can I give different key for different periods?
> 
> This should not be a problem
> 
Got it now. I will try multi-period content generation with this info.

> > exoplayer is not requesting next keys after first key is acquired.
> 
> Did you check this: https://exoplayer.dev/drm.html

Yes. Before posting this issue, I had tried all options provided on that page. It helped for playing a ready-made multi-period test video from axinom. As soon as different period starts, exoplayer sends request for new key based on manifest file.
But the key rotation case is not working.For exoplayer configuration, only one setting is required to support key rotation i.e. setting `"drm_multi_session": true` for that content in media.exolist.json file.
Hence I thought that there may be problem in content generation. So I raised issue here.
I am trying out other players as you suggested to check if its exoplayer issue.

**Comment by mkcdot** [comment]
On exoplayer side, I am able to play widevine-key rotation content without any issue.
There is some issue with MP4Box generated content.

I have attached "mp4box -diso " command output of mp4box generated key-rotation dash content with clearkey drm.
[mp4box_clearkey_key_rotation_video_dashinit_info.txt](https://github.com/gpac/gpac/files/5014408/mp4box_clearkey_key_rotation_video_dashinit_info.txt)

I have also attached "mp4box -diso " command output of widevine key-rotation dash sample content.
[widevine_key_rotation_sample_video_info.txt](https://github.com/gpac/gpac/files/5014410/widevine_key_rotation_sample_video_info.txt)

I can see that key-id information is not contained in every segment of the media when key is changed. It is present only in the beginning of the media file. Please let me know what is the issue during content generation. Do I need to add any extra options when generating dash content?

**Comment by mkcdot** [comment]
Any update on above key rotation issue for clearkey?

**Comment by jeanlf** [comment]
your mp4box setup uses sample group description for KIDs only in the init segment while the widevine repeats them in each segment. Both config are legal, but it could be that your widevine+exoplayer expects the later approach.
  
Try adding `-sample-groups-traf` to your dashing command line.
