### ISSUE TITLE
how to change mp4box client code

### ISSUE THREAD

**Issue by a23232390** [gpac/gpac#1558]
i want to change filter chain to openHEVC so i can heve tile
![1](https://user-images.githubusercontent.com/68137277/88908900-0f788600-d28d-11ea-9b01-061a8e68eead.png)
![123](https://user-images.githubusercontent.com/68137277/88908911-130c0d00-d28d-11ea-87e3-63376af2a16c.png)

**Comment by jeanlf** [comment]
add `-blacklist=nvdec` to prevent nvdec from being used.

Note that tiles are re-aggregated in a single stream at the output of the dash demux, that stream _should_ be playable with nvdec (you can check by playing the source HEVC stream before spliting it).

**Comment by a23232390** [comment]
> add `-blacklist=nvdec` to prevent nvdec from being used.
> 
> Note that tiles are re-aggregated in a single stream at the output of the dash demux, that stream _should_ be playable with nvdec (you can check by playing the source HEVC stream before spliting it).

Thanks for your reply 
I didn't understand when I just touched it
-blacklist=nvdec is in cmd hit MP4Box.exe -blacklist=nvdec or what

**Comment by jeanlf** [comment]
in the client command line, not in mp4box (no playback in mp4box)

**Comment by a23232390** [comment]
![11](https://user-images.githubusercontent.com/68137277/89114513-e2f08400-d4af-11ea-850c-9e7ee9f2e017.png)


What instructions can I choose encoder
i hit this it change  ffdec but i want chage openHEVC
gpac -gui 987.mpd -blacklist=nvdec 

> 在客戶端命令行中，而不是在mp4box中（在mp4box中無法播放）

**Comment by jeanlf** [comment]
use

` gpac -gui 987.mpd -blacklist=nvdec,ffdec`

**Comment by Ziwen-Ye** [comment]
hello, it's my first time try to use MP4Client, and I have a question, I hope you can give me a help!
I just use "MP4Client xxx.mp4", and it shows that "No filter chain found for PID V1 in filter mp4dmx to any loaded filters - NOT CONNECTED No filter chain found for PID A2 in filter mp4dmx to any loaded filters - NOT CONNECTED", and the MP4Client is black screen, I want to know what should I do? How to set " filter chain"?
Thank you so much!
