### ISSUE TITLE
Strange MPD result generated with MP4Box

### ISSUE THREAD

**Issue by delbinwen** [gpac/gpac#156]
Hi,

I follow the [link](http://www.gpac-licensing.com/2014/08/21/ibc-2014-dash-avc264-support-in-gpac/) to generate MPD with SegmentTimeline support. Below is my command;

$MP4Box -dash 10000 -rap -dash-profile dashavc264:live -bs-switching no -url-template -segment-timeline -segment-name seg_$Bandwdth$_$Time$ -out ooxx.mpd audio.mp4 video.mp4

The command generated the file as below;
$ls
audio.mp4       seg_ls$1.m4s    seg_ls$3.m4s    seg_ls$5.m4s    seg_ls$init.mp4
ooxx.mpd        seg_ls$2.m4s    seg_ls$4.m4s    seg_ls$6.m4s    video.mp4
The naming is much different from the segment-name I specified; I don't know where 'ls' come from.

And here is the MPD;
```xml
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.5.2-DEV-rev405-g3cd5ef1-master  at 2015-05-27T08:47:27.170Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H0M49.749S" maxSegmentDuration="PT0H0M9.984S" profiles="urn:mpeg:dash:profile:isoff-live:2011,http://dashif.org/guidelines/dash264">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>ooxx.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H0M49.749S">
  <AdaptationSet segmentAlignment="true" lang="und">
   <SegmentTemplate timescale="1000" media="seg_ls$$Number$.m4s" startNumber="1" initialization="seg_ls$init.mp4">
    <SegmentTimeline>
     <S t="0" d="9984" r="3"/>
     <S d="9786"/>
    </SegmentTimeline>
   </SegmentTemplate>
   <Representation id="1" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="48000" startWithSAP="1" bandwidth="34069">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" maxWidth="1440" maxHeight="1080" maxFrameRate="30000/1001" par="4:3" lang="und">
   <SegmentTemplate timescale="1000" media="seg_ls$$Number$.m4s" startNumber="1" initialization="seg_ls$init.mp4">
    <SegmentTimeline>
     <S t="0" d="10009"/>
     <S d="8908"/>
     <S d="8476"/>
     <S d="8908"/>
     <S d="7541"/>
     <S d="5905"/>
    </SegmentTimeline>
   </SegmentTemplate>
   <Representation id="2" mimeType="video/mp4" codecs="avc1.640028" width="1440" height="1080" frameRate="30000/1001" sar="4:3" startWithSAP="1" bandwidth="114907">
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```
Why $Time$ was substituted with $Number$?

I pulled the latest version from GitHub, and here is the version I used;
$MP4Box -version
MP4Box - GPAC version 0.5.2-DEV-rev405-g3cd5ef1-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: --enable-debug
Features: GPAC_64_BITS GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG

**Comment by jeanlf** [comment]
you have used $Bandwdth$ or $Bandwidth$ ? 
We likely have an issue when unrecognized keywords are used in the segment template, I'll have a look

**Comment by delbinwen** [comment]
I used $Bandwidth$; $Bandwdth$ probably caused by copy&paste.

**Comment by delbinwen** [comment]
It's strange; I noticed $Bandwidth$ was replaced by my last shell command. As you can see in my original post, $Bandwidth$ was replaced with 'ls'.

However, I can't repro it if I debug MP4Box with LLDB. Could it be my environment issue? I'm using OSX.

**Comment by delbinwen** [comment]
If I use single quote to enclose the string, like 'seg_$Bandwidth$_$Time$', this issue could be resolved.
