### ISSUE TITLE
Latest version of mp4box does not split by size correctly

### ISSUE THREAD

**Issue by tieTYT** [gpac/gpac#1562]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ x] I looked for a similar issue and couldn't find any.
- [ x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

I tried this with 2 files: `mp4box -splits 490000 filename.mp4`

Each time, it added one extra part that was unnecessary. This last part was about 140kb. The previous part had hundreds of megabytes available before using up all the space. if I specified a size larger than the file, this still occurred.

I installed the latest, in the problem no longer occurred.

**Comment by jeanlf** [comment]
indeed, now fixed on master
