### ISSUE TITLE
-no-loop wrong behavior

### ISSUE THREAD

**Issue by chanof** [gpac/gpac#1563]
Hi, try to use -no-loop instead calculate with ffprobe the video duration and place the variable inside -run-for, but no loop give me the wrong behavior, the segmentation process is without sleep, not what I need for live purpose. 

MP4Box -h dash -no-loop:  disables looping content in live mode and uses period switch instead.
Im not able to get it working, I do not understand what it mean for "uses period switch" may I ask how to correct my command to be able to live dash my content till the end of video without use -run-for ?

GPAC 0.8.0

`MP4Box -dash-live 2000 -subdur 4000 -closest -no-cache -profile dashavc264:live -subsegs-per-sidx -1 -mpd-refresh 8 -time-shift 12 -min-buffer 2000 -url-template -insert-utc -bs-switching no -run-for $DUR -dash-ctx ../../live/log.txt -out ../../live/manifest.mpd ../current/1080.mp4#video ../current/720.mp4#video ../current/360.mp4#video ../current/180.mp4#video ../current/audio.mp4:#audio `

**Comment by chanof** [comment]
Please, I can't figure out how to use -no-loop instead ffprobe/-run-for

**Comment by jeanlf** [comment]
there's no wrong behavior, `-no-loop` does what it states: create a new DASH period upon looping, which may result in non-seamless playback depending on the players.

You shouldn't use `-run-for`, this is mostly for test purposes and will abort your live.

If you want to trim the duration of your sources, set `:dur=$DUR` on your source files (see `MP4Bo x-h dash`).

**Comment by chanof** [comment]
Thank you!
