### ISSUE TITLE
osmo4 client doesn't play 360 video online, but 2d video is ok

### ISSUE THREAD

**Issue by SivanLiu** [gpac/gpac#1572]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

How to play 360 video online? I put the 360 video url[https://bitmovin.com/player-content/playhouse-vr/progressive.mp4] at the Enter Address below, and it doesn't play and result is below.
Thanks!
![image](https://user-images.githubusercontent.com/8191309/89872317-58183380-dbeb-11ea-8372-ddcbef36238e.png)

**Comment by SivanLiu** [comment]
> Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!
> 
> * [x]  I looked for a similar issue and couldn't find any.
> * [x]  I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
> * [x]  I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95
> 
> Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/
> 
> How to play 360 video online? I put the 360 video url[https://bitmovin.com/player-content/playhouse-vr/progressive.mp4] at the Enter Address below, and it doesn't play and result is below.
> Thanks!
> ![image](https://user-images.githubusercontent.com/8191309/89872317-58183380-dbeb-11ea-8372-ddcbef36238e.png)
I  have found the solution,Please close it.Thanks.

**Comment by SivanLiu** [comment]
> Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!
> 
> * [x]  I looked for a similar issue and couldn't find any.
> * [x]  I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
> * [x]  I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95
> 
> Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/
> 
> How to play 360 video online? I put the 360 video url[https://bitmovin.com/player-content/playhouse-vr/progressive.mp4] at the Enter Address below, and it doesn't play and result is below.
> Thanks!
> ![image](https://user-images.githubusercontent.com/8191309/89872317-58183380-dbeb-11ea-8372-ddcbef36238e.png)

I have found the solution for playing 360 live video online, please close it.Thanks.

**Comment by EricPengShuai** [comment]
@SivanLiu Sorry to disturb you. Have you sovled it? Recently I have tried to download Osmo4 app to play 360 videos, but I failed. In addition, I can't even play 2d videos with Osmo4.

**Comment by rbouqueau** [comment]
> I can't even play 2d videos with Osmo4.

Please open a separate issue with relevant information if you need help on this.
