### ISSUE TITLE
Errors in gpac.spec

### ISSUE THREAD

**Issue by perrfect** [gpac/gpac#1577]
Hi.
I build .rpm for Centos7.
The gpac.spec has issues:
**1.** error: bad date in %changelog: Jun 16 2020 Jean Le Feuvre
**Fix**: add Tue in the line `Jun 16 2020 Jean Le Feuvre`

**2.** Error: No Package found for libjack-devel
**Fix.** For Centos not have package libjack-devel. This package should replaced by jack-audio-connection-kit

**3.** install: cannot create directory '/usr//usr': Permission denied
**Fix.** Use sudo, but i don't know why happened this error. 

**4.** cp: cannot stat 'AUTHORS': No such file or directory
**Fix.** Replace this string `%doc AUTHORS BUGS Changelog COPYING README.md TODO` by `%doc Changelog README.md`

**5.** 
```
Processing files: gpac-1.0.0-1.0.0.x86_64
Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.aqbsQP
error: File not found by glob: /builddir/build/BUILDROOT/gpac-1.0.0-1.0.0.x86_64/usr/lib64/*
+ umask 022
+ cd /builddir/build/BUILD
+ cd gpac
+ DOCDIR=/builddir/build/BUILDROOT/gpac-1.0.0-1.0.0.x86_64/usr/share/doc/gpac-1.0.0
+ export DOCDIR
+ /usr/bin/mkdir -p /builddir/build/BUILDROOT/gpac-1.0.0-1.0.0.x86_64/usr/share/doc/gpac-1.0.0
+ cp -pr Changelog /builddir/build/BUILDROOT/gpac-1.0.0-1.0.0.x86_64/usr/share/doc/gpac-1.0.0
+ cp -pr README.md /builddir/build/BUILDROOT/gpac-1.0.0-1.0.0.x86_64/usr/share/doc/gpac-1.0.0
+ exit 0

RPM build errors:
    File not found by glob: /builddir/build/BUILDROOT/gpac-1.0.0-1.0.0.x86_64/usr/lib64/*
ERROR: Exception(SRPMS/x86_64/gpac-1.0.0-1.0.0.src.rpm) Config(epel-7-x86_64) 3 minutes 33 seconds
INFO: Results and/or logs in: gpac
```
**Fix.**. I don't know how fix this issue and need some help.

**Comment by jeanlf** [comment]
now fixed, thanks for the report
