### ISSUE TITLE
Feature Request ISO/IEC 23001-9

### ISSUE THREAD

**Issue by blackjack4494** [gpac/gpac#1578]
As I don't have access to that ISO/IEC and haven't really found any other open source project that actually have an implementation of ISO/IEC 23001-9 I would like to know if there are plans or considerations to do so. The more interesting part would be the encryption of mpeg (ts/m2ts) and secondly enc_m2ts -> enc_mp4 and vice versa.

If you know of any implementation let me know.

**Comment by jeanlf** [comment]
I'm not aware of any implementation of this one and haven't seen any bitstream using it. We are not planning on supporting this, sorry.
