### ISSUE TITLE
Timescale of segment-timeline is not identical to timescale of 'sidx' box

### ISSUE THREAD

**Issue by delbinwen** [gpac/gpac#158]
Hi,
I'm considering this might be a potential MP4Box bug. Here is the command I used to generate MPD with segment-timeline.

MP4Box -dash 5005 -dash-profile dashavc264:live -bs-switching no -url-template -segment-timeline 
-segment-name 'seg_$Bandwidth$_$Time$' -out ooxx.mpd audio.mp4 video.mp4

The generated MPD and media segments could be played with dash.js, but not Silverlight. After several trial & error, I found SegmentTemplate@timescale is not expected by Silverlight. From the segment request pattern, I found Silverlight expected timescale of 'sidx' box. Actually, there is a sentence in 5.3.9.6.1 ISO/IEC 23009-1, it says
— the value of @timescale shall be identical to the value of the timescale field in the first ‘sidx’ box

In my case, the timescale value of 'sidx' box of the first (audio) media segment is 48000. Here is the partial dump via MP4Box -info -diso seg_33624_0.m4s;

``` xml
<!--MP4Box dump trace-->
<IsoMediaFile Name="seg_33624_0.m4s">
<SegmentTypeBox MajorBrand="msdh" MinorVersion="0">
<BoxInfo Size="24" Type="styp"/>
<BrandEntry AlternateBrand="msdh"/>
<BrandEntry AlternateBrand="msix"/>
</SegmentTypeBox>
<SegmentIndexBox reference_ID="1" timescale="48000" earliest_presentation_time="0" first_offset="0">
<BoxInfo Size="44" Type="sidx"/>
```

And the segment-timeline of audio representation is listed below. The timescale is the default value, 1000, of MP4Box.

``` xml
<AdaptationSet segmentAlignment="true" lang="und">
   <SegmentTemplate timescale="1000" media="seg_$Bandwidth$_$Time$.m4s" startNumber="1" initialization="seg_$Bandwidth$_.mp4">
    <SegmentTimeline>
     <S t="0" d="4992" r="8"/>
     <S d="4794"/>
    </SegmentTimeline>
   </SegmentTemplate>
   <Representation id="1" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="48000" startWithSAP="1" bandwidth="33624">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
   </Representation>
  </AdaptationSet>
```

Video adaptationset has the same issue too.

Please kindly let me if the issue could be addressed with correct options. Let me know if my interpretation is incorrect. Welcome for the discussion.

Thanks,
Wesley

**Comment by jeanlf** [comment]
this should have been fixed some time ago, please check
