### ISSUE TITLE
Gpac key

### ISSUE THREAD

**Issue by shome** [gpac/gpac#1580]
Hi,

I am try to use gpac to create encrypted video, I have follow the gpac code but not understand how can I get the keys for encryption and also how I can play in media player for decrypt the video and play.
And also tell me is I need to purchase the key or its free.
I have upload my detail report regarding the issue I have face, please see the attachment
[gpac.docx](https://github.com/gpac/gpac/files/5103906/gpac.docx)

**Comment by Murmur** [comment]
See topics to encrypt using mp4box tool. You can use any byte string(hex) for KeyID and ContentKey values it's up to you generate values.
https://github.com/w3c/encrypted-media/issues/436
https://github.com/gpac/gpac/issues/932

Use dashjs player in Window10/MSEdge browser to have a playready support. Use Chrome/Firefox for Widevine decryption. Use `ShowOptions/DrmOptions`to specify laurl license url.
https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html

You can use a free Playready test server where you give an encryption key in `contentkey:$Base64` argument. This is your laurl license url for playback.
`https://test.playready.microsoft.com/service/rightsmanager.asmx?cfg=(kid:header,sl:2000,persist:false,contentkey:EjQSNBI0EjQSNBI0EjQSNg==)`

**Comment by SAMYEL06** [comment]
Sorry to reopen but, @Murmur can you explain how to create a xml file like this one ? 

`<?xml version="1.0" encoding="UTF-8" ?>
<GPACDRM type="CENC AES-CTR">
 


<DRMInfo type="pssh" version="1">
  <BS ID128="1077efecc0b24d02ace33c1e52e2fb4b"/>
  <BS bits="32" value="1"/>
  <BS ID128="43215678123412341234123412341234"/>
</DRMInfo>

<CrypTrack trackID="1" IsEncrypted="1" IV_size="8" first_IV="0x22ee7d4745d3a26a" saiSavedBox="senc">
  <key KID="0x43215678123412341234123412341234" value="0x12341234123412341234123412341234"/>
</CrypTrack>

</GPACDRM>`

Is there some tool to create those ? :x 

Thanks ! (been searching but only found samples, no method on how to proceed to generate one)

**Comment by Murmur** [comment]
Just use any text editor, python script or static file for `gpacdrm.xml` content. WideWine and CENC does not need any generator but Playready WRMHEADER xml object need more work to do. See this simple helper generator supporting multidrm with just one encryption key. 
https://github.com/HbbTV-Association/ReferenceApplication/blob/7b800ce4a53671d81a2dbabaedcfc279ca435446/tools/java/src/org/hbbtv/refapp/DashDRM.java#L63

```
PlayReadyLaURL:
https://test.playready.microsoft.com/service/rightsmanager.asmx?cfg=(kid:header,sl:2000,persist:false,contentkey:EjQSNBI0EjQSNBI0EjQSNg==)

<?xml version="1.0" encoding="UTF-8" ?>
<GPACDRM type="CENC AES-CTR">
<!-- 
  kid=0x43215678123412341234123412341236
  key=0x12341234123412341234123412341236
  iv=0x22ee7d4745d3a26a
--> 

<!-- Playready -->
<DRMInfo type="pssh" version="0">
  <BS ID128="9A04F07998404286AB92E65BE0885F95"/>
  <BS bits="32" endian="little" value="828"/>
  <BS bits="16" endian="little" value="1"/>
  <BS bits="16" endian="little" value="1"/>
  <BS bits="16" endian="little" value="818"/>
  <BS data64="PABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgBlAEYAWQBoAFEAegBRAFMATgBCAEkAUwBOAEIASQAwAEUAagBRAFMATgBnAD0APQA8AC8ASwBJAEQAPgA8AEMASABFAEMASwBTAFUATQA+ACsAOQBrAGkANwAvAHQAdABzAGUAQQA9ADwALwBDAEgARQBDAEsAUwBVAE0APgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcABzADoALwAvAHQAZQBzAHQALgBwAGwAYQB5AHIAZQBhAGQAeQAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBzAGUAcgB2AGkAYwBlAC8AcgBpAGcAaAB0AHMAbQBhAG4AYQBnAGUAcgAuAGEAcwBtAHgAPwBjAGYAZwA9ACgAawBpAGQAOgBoAGUAYQBkAGUAcgAsAHMAbAA6ADIAMAAwADAALABwAGUAcgBzAGkAcwB0ADoAZgBhAGwAcwBlACwAYwBvAG4AdABlAG4AdABrAGUAeQA6AEUAagBRAFMATgBCAEkAMABFAGoAUQBTAE4AQgBJADAARQBqAFEAUwBOAGcAPQA9ACkAPAAvAEwAQQBfAFUAUgBMAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA="/>
</DRMInfo>

<!-- Widevine -->
<DRMInfo type="pssh" version="0">
  <BS ID128="EDEF8BA979D64ACEA3C827DCD51D21ED"/>
  <BS data="0x08011210"/>
  <BS ID128="43215678123412341234123412341236"/>
</DRMInfo>

<!-- CENC -->
<DRMInfo type="pssh" version="1">
  <BS ID128="1077efecc0b24d02ace33c1e52e2fb4b"/>
  <BS bits="32" value="1"/>
  <BS ID128="43215678123412341234123412341236"/>
</DRMInfo>

<CrypTrack trackID="1" IsEncrypted="1" IV_size="8" first_IV="0x22ee7d4745d3a26a" saiSavedBox="senc">
  <key KID="0x43215678123412341234123412341236" value="0x12341234123412341234123412341236"/>
</CrypTrack>

</GPACDRM>
```

**Comment by SAMYEL06** [comment]
I'll try to do it manually then, because I'm not a dev and DashDRM.java doesn't work on my PC x)

Thought there was some python tool or something for it, but whatever, it'll make me think a bit lol thanks @Murmur ^^

**Comment by rbouqueau** [comment]
Thanks @Murmur . @SAMYEL06 we indeed have identified this as being a pain point for users. It is still unclear how we would solve it but the python script option is on the table.
