### ISSUE TITLE
HLS master playlist issues

### ISSUE THREAD

**Issue by akkermansadriaan** [gpac/gpac#1582]
When using command `gpac -i subtitles.mp4 -i video.mp4 dst=master.mpd:dual:profile=onDemand:segdur=10` the resulting master.m3u8 is:
```
#EXTM3U
#EXT-X-VERSION: 6
#EXT-X-INDEPENDENT-SEGMENTS

#EXT-X-MEDIA:TYPE=SUBTITLE,GROUP-ID="subs1",NAME="1",LANGUAGE="eng",AUTOSELECT=YES,URI="master_1.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=5743027,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE="25",AUDIO="audio3",SUBTITLE="subs"1"
master_2.m3u8

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio3",NAME="3",LANGUAGE="nld",AUTOSELECT=YES,URI="master_3.m3u8",CHANNELS="2"
```

There are 2 issues that prohibit successfully playing these assets in the Safari browser:
- TYPE for subtitles should be SUBTITLES both in the EXT-X-MEDIA tag and the EXT-X-STREAM-INF tag.
-  Note the `SUBTITLE="subs"1"`. It seems like there's an extra quote that shouldn't be there.

**Comment by jeanlf** [comment]
indeed, now fixed. Thanks for the report
