### ISSUE TITLE
mp4box -dump-chap and -dump-chap-ogg give the exact same ouput !

### ISSUE THREAD

**Issue by 44vince44** [gpac/gpac#1584]
Checks
- [x] I looked for a similar issue and couldn't find any. **SIMILAR, yes, but not this exact one, and it is closed.**
- [x ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95
--------------------------------------------

Hello GPAC Team,
Please consider this issue:
mp4box -dump-chap-ogg is documented as extracting a chapter file as OGG format. However it extract file as ttxt, exactly as when using -dump-chap ! Isn't it supposed to give a different output?

Here is the command used:
MP4Box.exe -dump-chap-ogg "TimecodeSample25FpsWithChapts.mp4" -out "Timechaptersogg.txt"

Here is the ouput file, with -dump-chap and **-dump-chap-ogg**:

![SNAG-0002](https://user-images.githubusercontent.com/17828567/91656837-b76bb400-eac4-11ea-9d40-e76ff4f4e3e1.jpg)

[Timechaptersogg.txt](https://github.com/gpac/gpac/files/5146643/Timechaptersogg.txt)

[Here is the link to the source file](https://www.mediafire.com/file/kqnpfk30vjmqm4q/TimecodeSample25FpsWithChapts.mp4/file), created by handbrake for this testing purpose.

Thanks again !

**Comment by jeanlf** [comment]
Indeed, code was quite old and not really consistent between track chapters and udta chapters. This is now fixed: 
```
-dump-chap: dumps as TTXT
-dump-chap-ogg: dumps as OGG
-dump-chap-zoom: dumps as Zoom
```

Thanks for the report

**Comment by 44vince44** [comment]
@jeanlf Thanks very much, mille mercis a vous tous!
