### ISSUE TITLE
No conformance with DASHIF low latency validator (related to or due to documentation improvement need #1533)

### ISSUE THREAD

**Issue by ricardollovera** [gpac/gpac#1585]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). 

------

Hi,

DASHIF proposes a validator (https://conformance.dashif.org/)

to which the mpd generated thru gpac command is not LL compliant with this result:

Log No | MPD Validation Report
-- | --
1 | 0XLink resolving successful
2 | MPD validation successful - DASH is valid!
3 | Schematron validation successful - DASH is valid!
4 | DASH-IF IOP CR Low Latency Live warning section 9.X.4.1: "A Media Presentation that follows a DASH-IF Low-Latency Service Offering according to this specification SHOULD be signalled with the @profiles identifier 'http://www.dashif.org/guidelines/low-latency-live-v5'", specified identifier is not found in the MPD.
5 | DASH-IF IOP CR Low Latency Live check violated Section 9.X.4.2: "At least one ServiceDescription element SHALL be present", ServiceDescription element not found in neither MPD nor Period 1.
6 | DASH-IF IOP CR Low Latency Live check violated Section 9.X.4.2: "At least one UTC timing description SHALL be present and be restricted with @schemeIdUri set to one of {urn:mpeg:dash:utc:http-xsdate:2014, urn:mpeg:dash:utc:http-iso:2014, urn:mpeg:dash:utc:http-ntp:2014}", UTCTiming element not found in the MPD.
7 | DASH-IF IOP Low Latancy Live check warning Section 9.X.4.2: "Low latency content SHOULD provide a LeapSecondInformation element providing correction for leap seconds", LeapSecondInformation element is not found in the MPD

The mpd in output is "master.mpd" (attached to this ticket indented) and the command for gpac generation was:
`gpac -r -i /var/www/html/onDemand/videos/30min_countdown.mp4#video reframer:rt=on @ \
 -o http://localhost:8091/experiment_gpac_public/master.mpd --rdirs=/var/www/html --dmode=dynamic --cdur=1 --asto=7 --segdur=8 --reqlog=GET --profile=live --stl=false --tpl=true --tsb=180 --sreg=true --utcs=xsd@`

So the ServiceDescription element and the UTC timing tags seems to be missing. Didnt find neither how to include this in the documentation.

Best,

[from browser gpac.zip](https://github.com/gpac/gpac/files/5161216/from.browser.gpac.zip)

**Comment by jeanlf** [comment]
fixed [here](https://github.com/gpac/gpac/commit/eec71e759b9b35944b2c5e8a8bf060004592ed35) (sorry, issue ref is wrong...) - you will need to use `profile=dashof.ll` to inject the ServiceDescription, and that profile will automatically set `utcs` to time.akamai.com if not set.
