### ISSUE TITLE
mp4box doesn't seem to be able to import it's own chapters

### ISSUE THREAD

**Issue by LeeThompson** [gpac/gpac#159]
Now, I'm perfectly willing to say this is "pilot error" but so far I don't think so.

I am doing some remuxing of mp4 files using mp4box and overall it works great except for chapters.

I initially imported chapters in this format:

```
00:00:00.000 Chapter 1
00:06:30.307 Chapter 2
00:13:59.589 Chapter 3
00:21:06.515 Chapter 4
```

The command:

```
mp4box -chap chapters_file.txt
```

... imports it fine.

However, when it's exported as raw, it produces a binary file that appears to just have the chapter labels in it.   mp4box doesn't seem to understand this file at all for import.

If I use dump-chap I get two files, the same binary file above and a XML format file containing the timecodes but not the labels for the chapters.   Again, I haven't been able to then reimport this using -add or -chap.

It would be nice if it could just export the chapters in a text file with the "HH:MM:SS.MS LABEL" format or at least some single file with all the information that it could reimport ok.

**Comment by saurabhshri** [comment]
Facing similar issue. 

I imported chapters using ` ./MP4Box -chap insert.chap chapters.mp4 ` , where `insert.chap` contained chapters in specified format. The import is successful and I can even see the subtitles with `-info`.

But when using `-dump-chap` the file that is created doesn't contain these Chapters, but rather this :

```
AddChapterBySecond(0,test1)
AddChapterBySecond(90,test2)
AddChapterBySecond(180,test3)
AddChapterBySecond(270,test4)

```

The content in insert.chap is :

```
CHAPTER1=00:00:00
CHAPTER1NAME=test1
CHAPTER2=00:01:30
CHAPTER2NAME=test2
CHAPTER3=00:03:00
CHAPTER3NAME=test3
CHAPTER4=00:04:30
CHAPTER4NAME=test4

```

And the `-info` param displays this successfully.

```
File has no MPEG4 IOD/OD

Chapters:
        Chapter #1 - 00:00:00.000 - "test1"
        Chapter #2 - 00:01:30.000 - "test2"
        Chapter #3 - 00:03:00.000 - "test3"
        Chapter #4 - 00:04:30.000 - "test4"

iTunes Info:

```

**Comment by aureliendavid** [comment]
@saurabhshri : the `-dump-chap-ogg` option will dump the chapters in the same original format as your example

as for the original issue, both `-dump-chap` and `-dump-chap-ogg` now contain the labels of the chapters and can be reimported to other mp4s, so I guess this has been fixed?
