### ISSUE TITLE
Duplicate cts/broken framing in rfnalu

### ISSUE THREAD

**Issue by VShell** [gpac/gpac#1590]
In rfnalu, if [this condition](https://github.com/gpac/gpac/blob/24c98a3a464c9318625ce0c808b46535131b848b/src/filters/reframe_nalu.c#L2935) is hit on an [input packet marked as an AU start](https://github.com/gpac/gpac/blob/24c98a3a464c9318625ce0c808b46535131b848b/src/filters/reframe_nalu.c#L2074), rfnalu can output one packet marked as an AU start with a cts and dts later than it should be, followed by one packet marked as an AU start with the same cts. Inevitably the first packet is very small, so I doubt it is actually a valid frame.

To find this, I instrumented rfnalu with extra logging, ran `srt-live-transmit srt://0.0.0.0:3800?mode=server file://con | gpac -logs=parser@debug src=stdin dst=test.mp4`, and pointed OBS at it - although I imagine this is triggerable in other ways to get the same result. I have uploaded the test.mp4 [here](https://www.mediafire.com/file/so8zlifi446o3nc/test.mp4/file), and the broken samples are 601/602 on track 256, with cts 1809000.

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by VShell** [comment]
Commenting out that section still results in duplicate CTS, although timestamps are now monotonic aside from that (i.e. there's no jump in cts).

**Comment by jeanlf** [comment]
I don't think this is the issue here, the framing of nal/samples is correct. The problem comes from the fact that the reframer detects b-frames in the middle of the stream, resulting in a wrong cts offset. Checking the raw bitstream, it looks like some frames are missing (sudden gop increase>1, or 59->4 gop loop) which is quite strange.

I extended the strict_poc mode to try to cover this, eg `gpac src=foo dst=bar.mp4:strict_poc=error` 

Can you check if that helps ?

**Comment by VShell** [comment]
I can confirm that this doesn't help, unfortunately. I've recorded the input MPEG-TS stream, along with a handful of outputs:

```
test.ts = raw input stream
test.mp4 = gpac -logs=all@info src=test.ts dst=test.mp4
test2.mp4 = gpac -logs=all@info src=test.ts dst=test2.mp4:strict_poc
test3.mp4 = gpac -logs=all@info src=test.ts dst=test3.mp4:strict_poc=error
```

The input MPEG-TS stream will be missing packets as it's transfered over SRT, which is a lossy transport by default, but my impression is that MPEG-TS should be resilient to packet loss (i.e. PES packets with missing data should be dropped correctly).

There appears to be only one frame with the issue in this stream, and I get warnings that 4 more PES packets are dropped. Comparing the number of PES packets from tsanalyze with the number of samples in test.mp4, that makes five PES packets missing in PID 256, of which one is not warned about/dropped by m2tsdmx - this then feels like the actual source of this error?

**Comment by VShell** [comment]
I've got it! The framing in the MPEG-TS file is OK. The access unit with PTS 6069000 - payload size 45 - contains three NALs - an access unit delimiter, SEI, and a slice of a non-IDR picture. The first two get skipped over correctly, then the slice, with size 23, hits [this condition](https://github.com/gpac/gpac/blob/24c98a3a464c9318625ce0c808b46535131b848b/src/filters/reframe_nalu.c#L2476) and its processing is delayed until the next input packet to rfnalu. On the next input packet, ctx->cts is updated to 6072000, then the previous access unit is processed with the updated PTS - resulting in both packets having the same PTS, 6072000.

I'm not sure what would be the best way to go about fixing this, unfortunately - I don't understand why this condition exists - or I'd have a go.

**Comment by jeanlf** [comment]
Thanks for the great analysis, I wish all bug reports were as detailed as yours :)
This should now be fixed, could you cross-check ?

**Comment by VShell** [comment]
I just tried with v1.0.1 which includes this patch, this appears to work - just did a few new streams without this issue. Thank you!
