### ISSUE TITLE
DASH duration and Segment duration

### ISSUE THREAD

**Issue by LouHan-0325** [gpac/gpac#1591]
Hi community:

When I  used the MP4Clinet to play .mpd file some error occurred. As shown in the figure below.
![批注 2020-09-07 184846](https://user-images.githubusercontent.com/57747741/92381046-ba0d7f80-f13c-11ea-9eff-756683e89d5f.png)

I encoded the video:
 `kvazaar -i MyVideo.yuv --input-res 1280x720 -o MyVideo.hvc --tiles 3x3 --slices tiles --mv-constraint frametilemargin`
The default GOP(group of pictures) is 64.

Then I used MP4Box to split tiles and FPS is 30:
`MP4Box -add MyVideo.hvc:split_tiles -fps 30 -new MyVideo-tiled.mp4`

Then to generate MPD file and segment length is 2200ms :
`MP4Box -dash 2200 -rap -frag-rap -profile live -out MyVideo.mpd MyVideo-tiled.mp4 `

 I will be grateful for any help.

**Comment by jeanlf** [comment]
something is wrong with your encoding, the average gop length is 4.2 sec and not 2.2. Check with `MP4Box -info VideoTrackID source.mp4`to see the reported average gop duration

**Comment by LouHan-0325** [comment]
> something is wrong with your encoding, the average gop length is 4.2 sec and not 2.2. Check with `MP4Box -info VideoTrackID source.mp4`to see the reported average gop duration
I checked and  the reported average gop duration is 2.2 sec. 
![批注 2020-09-08 104654](https://user-images.githubusercontent.com/57747741/92428212-14502400-f1c1-11ea-80d0-ef7a272d9b32.png)
Appreciate for any help on this issue.

**Comment by jeanlf** [comment]
could you upload your test file somewhere?

**Comment by LouHan-0325** [comment]
> could you upload your test file somewhere?

There is `MyVideo-tiled.mp4` https://github.com/LouHan-0325/Test-Video

**Comment by jeanlf** [comment]
your dash duration 2.2 sec is greater than the first SAP period 2.166 sec. Using 2160 as dash duration reports no warnings.
