### ISSUE TITLE
Prebuilt Debian/Ubuntu package and libpng12 dependency unresolved on Ubuntu 18 / 20

### ISSUE THREAD

**Issue by gnanet** [gpac/gpac#1592]
The fix for #1131 and the resulting commit 6d54d215c29984c84433eb128c27b12276315078  switching to the libpng-dev package dependency has a bad side effect:
In Debian 10 (Buster) the libpng12 and libpng16 coexsist,but in Ubuntu 18 / 20 (Bionic / Focal) there is no more libpng12 causing the packages available at https://gpac.wp.imt.fr/downloads/ for **Linux 32 bits (debian/ubuntu)** **Linux 64 bits (debian/ubuntu)** only work with Debian out of the box, and for Ubuntu a workaround needs to be done, by downloading and installing an Ubuntu 16 (Xenial) package of libpng12-0 ; and i assume to build successfully i assume, the libpng12-dev is required, because looking at the source here, you still has headers and code depending on libpng 1.2.33

**Comment by aureliendavid** [comment]
hi,

thanks for the report

there isn't actually any code that requires libpng12 or 16, both work

however our ubuntu18 build machine still had libpng12-dev installed, so the debian packager picked it up has a dependency 

I rebuilt the latest installer (https://download.tsi.telecom-paristech.fr/gpac/new_builds/linux64/gpac/gpac_1.0.0-rev236-gb02f3646-master_amd64.deb) against libpng16 and it should install properly on ubuntu. 

I'll see if I can rebuild the older "rev0" installers.

**Comment by gnanet** [comment]
For the prvoius versions i think a note about the workaround to use the xenial libpng12-0 would be fine enough.

**Comment by aureliendavid** [comment]
I was able to rebuild the rev0 installers, should be ok now on this point
