### ISSUE TITLE
Multifragment(MOOF,MDAT) segmenting missing TFDT(mediaDecodeTime) fields

### ISSUE THREAD

**Issue by Murmur** [gpac/gpac#1593]
Multifragmenting segments to have multiple `MOOF,MDAT` pairs writes broken segments. it's only **the first pair having** TFDT atom but the following pairs missing one. Player dashjs goes like 10x steps speed until encounter missing segments.

```
MP4Box.exe
Not enough arguments - check usage with -h
MP4Box - GPAC version 1.0.0-rev204-g348365dd1-ab-suite
(c) 2000-2020 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io

MP4Box.exe -dash 384000 -frag 48000 -dash-scale 48000 -closest -mem-frags -rap -profile dashavc264:live ^
  -min-buffer 8000 -bs-switching no -sample-groups-traf -single-traf -subsegs-per-sidx 0 ^
  -segment-name $RepresentationID$/$Number$$Init=i$  ^
  -out manifest.mpd ^
  temp-v1.mp4#trackID=1:id=v1:period=p0 ^
  temp-v2.mp4#trackID=1:id=v2:period=p0 ^
  temp-v3.mp4#trackID=1:id=v3:period=p0 ^
  temp-a1.mp4#trackID=1:id=a1:period=p0 ^
  temp-a1-1.mp4#trackID=1:id=a1-1:period=p0
```

ps: Is this mp4box.exe still valid now and a future? Some examples start to use gpac.exe binary with a pipeline argument syntax, mp4box support only an old skool arguments and missing some new param tricks?

**Comment by jeanlf** [comment]
There is no bug, the first moof in a segment shall have a tfdt in each traf, it is optional for the others moof.traf in the segment. This can be changed using `--tfdt_traf` (see `MP4Box -h tfdt_traf` or `gpac -h mp4mx.tfdt_traf`).

Is this behavior mandatory in dash IOP ? If so we need to patch the profile setup.

**Comment by rbouqueau** [comment]
> Is this behavior mandatory in dash IOP ?

Not seen in IOP v3.

**Comment by Murmur** [comment]
Using `--tfdt_traf` argument fixed a playback problem (TFDT is now found in all MOOF-MDAT pairs). Dashjs is jumping like 10x speed without tfdt atoms. I made this simplified test with just one video+audio track.

[dashjs nightly](http://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html)
```
MP4Box.exe
MP4Box - GPAC version 1.0.0-rev204-g348365dd1-ab-suite
(c) 2000-2020 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io

MP4Box.exe -dash 384000 -frag 48000 --tfdt_traf -dash-scale 48000 -closest -mem-frags -rap ^
  -profile dashavc264:live -min-buffer 4000 -bs-switching no ^
  -sample-groups-traf -single-traf -subsegs-per-sidx -1 ^
  -segment-name $RepresentationID$/$Number$$Init=i$  ^
  -out manifest.mpd ^
  temp-v1.mp4#trackID=1:id=v1:period=p0 ^
  temp-a1.mp4#trackID=1:id=a1:period=p0 
```

**Comment by Murmur** [comment]
FYI, I made a dashjs ticket about the problem and it came back to a browser limitation really. Dashjs and ShakaPlayer Chrome/Firefox/EdgeChromium playback failed if just one TFDT was written.
