### ISSUE TITLE
UDP Port parsing issue

### ISSUE THREAD

**Issue by RodolpheFouquet** [gpac/gpac#1595]
When I run gpac with and UDP input, it looks like the port is interpreted as an argument, even though the pipeline works and displays correctly the video.

P.S: is there a way to print the PIDs of the input? ( it is mpegts)

```
gpac -i udp://127.0.0.1:4123:FID=1 @ vout
No filter chain found for PID P1V2 in filter m2tsdmx to any loaded filters - NOT CONNECTED
[MPEG-2 TS] PES 256: Packet discontinuity (5 expected - got 13) - trashing PES packet
Unknown argument ":4123" set but not used by any filter - no matching argument found
```

Tested on commit c6ca4f24dcc257b08606b5f1d7356d57056bd2e9

-----------------------------------------------------------
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by rbouqueau** [comment]
Yes you need to escape it with the keyworkd ```gpac```: ```gpac -i udp://127.0.0.1:4123:gpac:FID=1 @ vout```

Look for "escape" in https://github.com/gpac/gpac/wiki/filters_general and https://github.com/gpac/gpac/wiki/sockets

**Comment by RodolpheFouquet** [comment]
It should really appear here then: https://github.com/gpac/gpac/wiki/sockin

**Comment by RodolpheFouquet** [comment]
Reopening because it did not work

```
 gpac -i udp://127.0.0.1:4123:gpac:FID=1 @ vout
No filter chain found for PID P1A3 in filter m2tsdmx to any loaded filters - NOT CONNECTED
[MPEG-2 TS] PES 256: Packet discontinuity (15 expected - got 7) - trashing PES packet
Unknown argument ":4123" set but not used by any filter - no matching argument found
```


It only works with a trailing slash
```

gpac -i udp://127.0.0.1:4123/:gpac:FID=1 @ vout
No filter chain found for PID P1A3 in filter m2tsdmx to any loaded filters - NOT CONNECTED
[MPEG-2 TS] PES 256: Packet discontinuity (8 expected - got 0) - trashing PES packet
[MPEG-2 TS] PES 256: Packet discontinuity (3 expected - got 8) - may have lost end of previous PES
```

**Comment by jeanlf** [comment]
both syntax (trailing slash or `:gpac` separator) are valid and working, however there was a bug in argument inheriting reporting the port number as an option of intermediate filters. This is now fixed and sockin/sockout doc updated, thanks for the report.
