### ISSUE TITLE
how to create new srd control??

### ISSUE THREAD

**Issue by a23232390** [gpac/gpac#1596]
I want to create my own rules
![image](https://user-images.githubusercontent.com/68137277/93740312-d28d9780-fc1c-11ea-9370-91b8aae0ca40.png)
i create the new one but where can i create my own rules
![image](https://user-images.githubusercontent.com/68137277/93740380-f05afc80-fc1c-11ea-9bf2-406ef16c6bac.png)

**Comment by jeanlf** [comment]
the tile adaptation modes are listed in the GF_DASHTileAdaptationMode enum. You will need to patch the function gf_dash_get_tiles_quality_rank in  src/media_tools/dash_client.c to implement your own rules

**Comment by a23232390** [comment]
my terminal hit this
gpac -src 1.mpd dashin:tile_mode=2:start_with=max_bw mp4dmx tileagg compositor vout

src / media_tools / dash_client.c 
add this
	case GF_DASH_ADAPT_TILE_2:
		return tile_group->srd_row_idx;

/home/a123/gpac_public/include/gpac/dash.h
add this
typedef enum
{
	/*! each tile receives the same amount of bitrate (default strategy)*/
	GF_DASH_ADAPT_TILE_NONE=0,
	/*! bitrate decreases for each row of tiles starting from the top, same rate for each tile on the row*/
	GF_DASH_ADAPT_TILE_ROWS,
	/*! bitrate decreases for each row of tiles starting from the bottom, same rate for each tile on the row*/
	GF_DASH_ADAPT_TILE_ROWS_REVERSE,
	/*! bitrate decreased for top and bottom rows only, same rate for each tile on the row*/
	GF_DASH_ADAPT_TILE_ROWS_MIDDLE,
	/*! bitrate decreases for each column of tiles starting from the left, same rate for each tile on the column*/
	GF_DASH_ADAPT_TILE_COLUMNS,
	/*! bitrate decreases for each column of tiles starting from the right, same rate for each tile on the column*/
	GF_DASH_ADAPT_TILE_COLUMNS_REVERSE,
	/*! bitrate decreased for left and right columns only, same rate for each tile on the column*/
	GF_DASH_ADAPT_TILE_COLUMNS_MIDDLE,
	/*! bitrate decreased for all tiles on the edge of the picture*/
	GF_DASH_ADAPT_TILE_CENTER,
	/*! bitrate decreased for all tiles on the center of the picture*/
	GF_DASH_ADAPT_TILE_EDGES,
	GF_DASH_ADAPT_TILE_1,
	GF_DASH_ADAPT_TILE_2,
	GF_DASH_ADAPT_TILE_3,
} GF_DASHTileAdaptationMode;
but i have this Wrong 
Wrong argument value 2 for unsigned int arg tile_mode enum none|rows|rrows|mrows|cols|rcols|mcols|center|edges - using 0

**Comment by jeanlf** [comment]
you need to modify the "tile_mode" option of the dashing filter - as you can see, the string enum of the option matches the GF_DASHTileAdaptationMode enum

**Comment by jeanlf** [comment]
it's an option of the dashin filter (src/filters.dashin.c)

**Comment by a23232390** [comment]
i use var1.0.1 but i cant find it
