### ISSUE TITLE
Error encountered when make: use of undeclared identifier 'kCMVideoCodecType_HEVC'

### ISSUE THREAD

**Issue by yahbeloved** [gpac/gpac#1599]
Hi 

I am trying to install MP4Box on my mac and encountered the following errors while trying to build.
I was following the instructions for MP4Box only at https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-OSX
and it fails at the make command.

make -C src all
  CC filters/dec_vtb.c
**filters/dec_vtb.c:510:20: error: use of undeclared identifier
      'kCMVideoCodecType_HEVC'**
                        ctx->vtb_type = kCMVideoCodecType_HEVC;
                                        ^
1 error generated.
make[1]: *** [filters/dec_vtb.o] Error 1
make: *** [all] Error 2

Appreciate any help rendered.

Thanks,
EL

**Comment by jeanlf** [comment]
looks like an old mac, the code assumes HEVC support in videotoolbox - we'll patch the code. Until then, you can try commenting out the whole `case GF_CODECID_HEVC` block starting at line 471 in dec_vtb

**Comment by yahbeloved** [comment]
Yes, an old mac. I commented that block and make but encountered other un-compatibility issues.

....
  "_gf_url_colon_suffix", referenced from:
      _make_fileio in main.o
  "_gf_url_concatenate", referenced from:
      _gpac_main in main.o
      _fio_open in main.o
  "_my_str_lwr", referenced from:
      _gpac_main in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [gpac] Error 1
make[1]: *** [apps] Error 2
make: *** [all] Error 2

**Comment by jeanlf** [comment]
hmm these symbols are exported from the lib, that's really strange. Which OSX and compiler/version are you using ?

**Comment by yahbeloved** [comment]
I am using OSX 10.10.2. It was a long list of "referenced from" errors starting with

make -C applications all
set -e; for i in gpac mp4box  ; do make -C $i all; done 
/bin/sh: pkg-config: command not found
Undefined symbols for architecture x86_64:
  "_gf_4cc_to_str", referenced from:
      _gpac_main in main.o
      _dump_all_props in main.o
      _dump_caps in main.o
...
...

Do I need to install pkg-config or something?

**Comment by jeanlf** [comment]
do you get any errors building libgpac (`make -C src`) ?

**Comment by yahbeloved** [comment]
Not sure if I did correctly. Have lost all I learned abt c and make in college. :P
Below is the command entered and output.

el$ make -C src
Makefile:1: ../config.mak: No such file or directory
Libs.private: -lgpac_static   -lz  -framework CoreFoundation -framework CoreVideo -framework CoreMedia -framework VideoToolbox -framework CoreFoundation -framework CoreVideo -framework CoreMedia -framework VideoToolBox 
cc -MM -I"/include"   "utils/os_divers.c" -MT "utils/os_divers.o" -MF ".deps/utils/os_divers.dep"
utils/os_divers.c:26:10: fatal error: 'gpac/tools.h' file not found
#include <gpac/tools.h>
         ^
1 error generated.
make: *** No rule to make target `../config.mak'.  Stop.

**Comment by jeanlf** [comment]
you need to run configure script first

**Comment by yahbeloved** [comment]
Sorry abt that. Yes, I get a bunch of "no symbols" errors with libgpac

....
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../bin/gcc/libgpac_static.a(mesh_tesselate.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../bin/gcc/libgpac_static.a(mpeg4_background.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../bin/gcc/libgpac_static.a(mpeg4_geometry_3d.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../bin/gcc/libgpac_static.a(mpeg4_layer_3d.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../bin/gcc/libgpac_static.a(mpeg4_lighting.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../bin/gcc/libgpac_static.a(svg_filters.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../bin/gcc/libgpac_static.a(visual_manager_3d.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../bin/gcc/libgpac_static.a(visual_manager_3d_gl.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../bin/gcc/libgpac_static.a(ff_common.o) has no symbols

**Comment by jeanlf** [comment]
these are warnings due to leaving out a bunch of things in mp4box only builds. You should still have libgpac_static.a in bin/gcc no?

**Comment by yahbeloved** [comment]
Yes, I have libgpac_static.a in bin/gcc.

Do you mean I should be able to run MP4box now?
Got "command not found" when I tried bin/gcc/MP4Box.

**Comment by jeanlf** [comment]
check you have bin/gcc/MP4box - if not put the full log of `make`

**Comment by yahbeloved** [comment]
No MP4box in bin/gcc. No make log. But there are errors in config.log
A long list of errors. I am only posting the start and end.


Logs for GPAC configure --static-mp4box
./configure: line 467: pkg-config: command not found
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.1.1
Thread model: posix
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.1.1
Thread model: posix
*** CC/CXX Test Failed (args -I/Users/home/gpac_public/extra_lib/include/platinum -L/usr/local/lib -L/Users/home/gpac_public/extra_lib/lib/gcc -lPlatinum -lPltMediaServer -lPltMediaConnect -lPltMediaRenderer -lNeptune -lZlib -lpthread) : 

ld: library not found for -lPlatinum
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Source was: 
#include <dlfcn.h>
int main( void ) { dlopen("foo", 0); return 0; }


*** CC/CXX Test Failed (args -o /var/folders/0v/24h286y578l0v3bs4jgnxrjm0000gn/T//gpac-conf-4410-46419-24000.o /var/folders/0v/24h286y578l0v3bs4jgnxrjm0000gn/T//gpac-conf-13994-46419-7107.c -L/usr/local/lib -lavcap) : 

/var/folders/0v/24h286y578l0v3bs4jgnxrjm0000gn/T//gpac-conf-22280-46419-22957.cpp:1:10: fatal error: 'Platinum.h' file not found
#include <Platinum.h>
         ^
1 error generated.
/var/folders/0v/24h286y578l0v3bs4jgnxrjm0000gn/T//gpac-conf-13994-46419-7107.c:1:10: fatal error: 'avcap/avcap.h' file not found
#include <avcap/avcap.h>
         ^
1 error generated.

Source was: 
#include <avcap/avcap.h>
using namespace avcap;
int main( void ) {
  const DeviceCollector::DeviceList& dl = DEVICE_COLLECTOR::instance().getDeviceList();
  DeviceDescriptor* dd = 0;
  for (DeviceCollector::DeviceList::const_iterator i = dl.begin(); i != dl.end(); i++) {
    dd = *i;
    std::cout << dd->getName().c_str() << "\n";
  }
  return 0;
}
...
...
Source was: 
#include <directfb.h>
int main( void ) { return 0; }


*** CC/CXX Test Failed (args -I/usr/X11R6/include -L/usr/X11R6/lib -L/usr/local/lib) : 

/var/folders/0v/24h286y578l0v3bs4jgnxrjm0000gn/T//gpac-conf-13994-46419-7107.c:1:10: fatal error: 'X11/Xlib.h' file not found
#include <X11/Xlib.h>
         ^
1 error generated.

Source was: 
#include <X11/Xlib.h>
int main( void ) { return 0; }


*** CC/CXX Test Failed (args -lhidapi-hidraw -L/usr/local/lib) : 

/var/folders/0v/24h286y578l0v3bs4jgnxrjm0000gn/T//gpac-conf-13994-46419-7107.c:1:10: fatal error: 'hidapi/hidapi.h' file not found
#include <hidapi/hidapi.h>
         ^
1 error generated.

Source was: 
#include <hidapi/hidapi.h>
int main( void ) { hid_init(); hid_exit(); return 0; }


*** CC/CXX Test Failed (args -I/usr/local/include -llzma -L/usr/local/lib) : 

/var/folders/0v/24h286y578l0v3bs4jgnxrjm0000gn/T//gpac-conf-13994-46419-7107.c:1:10: fatal error: 'lzma.h' file not found
#include <lzma.h>
         ^
1 error generated.

Source was: 
#include <lzma.h>
int main( void ) { lzma_options_lzma opt_lzma2; lzma_lzma_preset(&opt_lzma2, 9); return 0; }


./configure: line 2166: type: sdl2-config: not found
./configure: line 2201: type: sdl-config: not found

**Comment by jeanlf** [comment]
by `make`log, I mean command line output of `make`
it is normal that config.log has errors

**Comment by yahbeloved** [comment]
Here's the make log. 
[lsk.log](https://github.com/gpac/gpac/files/5331142/lsk.log)

**Comment by jeanlf** [comment]
no errors here, what's the full logs of `make -C applications/mp4box`?

**Comment by jeanlf** [comment]
Old vtb without HEVC support now detected by configure. Thanks for the report. Closing this, reopen a new issue if needed for your build
