### ISSUE TITLE
mod-dirs doesn't work when passed on the command line

### ISSUE THREAD

**Issue by VShell** [gpac/gpac#1600]
gpac "-mod-dirs=$root/lib/gpac;/some/other/directory" the_filter results in:

```
Failed to find filter "the_filter"
No filter with similar name found, see gpac -h filters
```

This is in gpac 1.0.1. Adding the other directory to mod-dirs in GPAC.cfg does work. I believe this is due to mod-dirs being read as part of gf_sys_init (after a few levels of indirection resulting in gf_modules_get_module_directories), rather than after gf_sys_set_args.

For context, I can't just put gf_the_filter.so in $root/lib/gpac as the contents of $root can't be modified after building gpac, due to my operating system/package manager (NixOS).

---

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
indeed that was kind of messy. I did a bit of cleanup:
- the default module directory is now in a dedicated key in the config and cannot be not modified through options
- -mod-dirs (from cfg file or as arg) specifies additional directories to scan  

Could you please cross-check ?

**Comment by VShell** [comment]
Can confirm this patch works for me (passing -mod-dirs=/some/other/directory on a clean profile), thank you!
