### ISSUE TITLE
some AAC files are not recognized by MP4Box after upgrade of gpac from version 0.7.1 to 1.0.1

### ISSUE THREAD

**Issue by vlad312** [gpac/gpac#1601]
Greetings,

I was using MP4Box from gpac version 0.7.1 on Debian amd64 - binaries could be downloaded from:
https://snapshot.debian.org/archive/debian/20190414T034649Z/pool/main/g/gpac/gpac_0.7.1%2Bdfsg1-3_amd64.deb
https://snapshot.debian.org/archive/debian/20190414T034649Z/pool/main/g/gpac/libgpac7_0.7.1%2Bdfsg1-3_amd64.deb

After upgrading to gpac 1.0.1 (binary package from deb-multimedia.org), some of the AAC files started to generate an error when trying to process them with MP4Box.

1) MP4Box version 0.7.1 - no error:

$ MP4Box -version
MP4Box - GPAC version 0.7.1-revVersion: 0.7.1+dfsg1-3
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --libdir=lib/x86_64-linux-gnu --mandir=${prefix}/share/man --extra-cflags=-Wall -fPIC -DPIC -I/usr/include/mozjs -DXP_UNIX -Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -fdebug-prefix-map=/build/gpac-b3cjzz/gpac-0.7.1+dfsg1=. -fstack-protector-strong -Wformat -Werror=format-security --extra-ldflags=-Wl,-z,relro --enable-joystick --enable-debug --disable-ssl --verbose
Features: GPAC_64_BITS GPAC_HAS_JPEG GPAC_HAS_PNG 

$ MP4Box -strict-error -noprog -hint -add input.aac output.m4a
AAC ADTS import  - sample rate 22050 - MPEG-4 audio - 2 channels
Setting up iTunes/iPod file...
Hinting file with Path-MTU 1450 Bytes
Hinting track ID 1 - Type "mp4a:mp4a" (mpeg4-generic) - BW 63 kbps
Saving to output.m4a: 0.500 secs Interleaving

2) MP4Box version 1.0.1 - error:

$ MP4Box -version
MP4Box - GPAC version 1.0.1-revUNKNOWN_REV
(c) 2000-2020 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io

Please cite our work in your research:
	GPAC Filters: https://doi.org/10.1145/3339825.3394929
	GPAC: https://doi.org/10.1145/1291233.1291452

GPAC Configuration: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --moddir=${prefix}/lib/x86_64-linux-gnu/gpac --use-js=no --extra-cflags=-DXP_UNIX -g -O2 -fdebug-prefix-map=/src/gpac-1.0.1+really1.0.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 --enable-pic --enable-debug --extra-ldflags=-Wl,-z,relro --libdir=lib/x86_64-linux-gnu --use-freenect=no --use-a52=system
Features: GPAC_CONFIG_LINUX GPAC_64_BITS GPAC_HAS_IPV6 GPAC_HAS_SSL GPAC_HAS_SOCK_UN GPAC_MINIMAL_ODF GPAC_HAS_QJS GPAC_HAS_FAAD GPAC_HAS_MAD GPAC_HAS_LIBA52 GPAC_HAS_JPEG GPAC_HAS_PNG GPAC_HAS_FFMPEG GPAC_HAS_JP2 GPAC_HAS_THEORA GPAC_HAS_VORBIS GPAC_HAS_XVID GPAC_HAS_LINUX_DVB  

$ MP4Box -strict-error -noprog -hint -add input.aac output.m4a
[MPEG-2 TS] TS Packet 2 has error (PID could be 5488)
[MPEG-2 TS] TS Packet 3 does not start with sync marker
[MPEG-2 TS] TS Packet 4 does not start with sync marker
[MPEG-2 TS] TS Packet 5 does not start with sync marker
[MPEG-2 TS] TS Packet 6 has error (PID could be 994)
[MPEG-2 TS] TS Packet 7 does not start with sync marker
[MPEG-2 TS] TS Packet 8 does not start with sync marker
[... skipped ...]
[MPEG-2 TS] TS Packet 274 does not start with sync marker
[MPEG-2 TS] TS Packet 275 does not start with sync marker
[MPEG-2 TS] TS Packet 276 does not start with sync marker
[MPEG-2 TS] TS Packet 277 does not start with sync marker
[MPEG-2 TS] TS Packet 278 does not start with sync marker
[Importer] No valid track to import in input file "input.aac"
Error importing input.aac: Feature Not Supported

I've attached the source file "input.aac" which could be used to replicate the described problem.
Note that this behavior happens not with all the AAC files, but only with some of them.
The AAC files I'm using were generated with "fdkaac".

Thanks for the gpac suite, and hope that this bug report will help improving the gpac.
[test-input.zip](https://github.com/gpac/gpac/files/5304763/test-input.zip)

Best wishes,
Vladimir

**Comment by jeanlf** [comment]
our data probers might need refinement yes, I'll have a look at that thanks for the file. Meanwhile you can disable data probing by using `-no-probe` option

**Comment by vlad312** [comment]
Thanks. I confirm that adding the `-no-probe` option solves the problem.

**Comment by jeanlf** [comment]
Now fixed, thanks for the test file.
