### ISSUE TITLE
strike-Tag is imported incorrectly

### ISSUE THREAD

**Issue by amuth** [gpac/gpac#1605]
Hi,

the &lt;strike&gt; tag is incorrectly imported into an Mp4 file. &lt;i&gt; and &lt;font&gt; works correctly.

srt subfile:

1
00:12:35,838 --> 00:12:38,926
"Abc&lt;strike&gt;cde&lt;/strike&gt;fgh"

When I look at the mp4 file or extract the subtile, I see the following:  "Abc&gt;cde&gt;fgh"

**Comment by jeanlf** [comment]
indeed, parsing now fixed for unrecognized tags, and strikeout style added (import,export and renderer). Thanks for the report
