### ISSUE TITLE
mp4box unable to set individual track/stream label metadata in mp4/m4v files

### ISSUE THREAD

**Issue by eharris** [gpac/gpac#1606]
I'm trying to use mp4box to set track/stream metadata labels, and it doesn't seem to work.  No error is produced, but the UDTA atom isn't getting set either.  The documentation for `-set-meta` seems like this should work.  Specifically, I'm trying to set the UDTA `name` atom, which is displayed by vlc and other players to identify/differentiate multiple streams.

Example:
```
> mp4box -set-meta 'name;3=Commentary' output.m4v
Setting up iTunes/iPod file...
Saving output.m4v: 0.500 secs Interleaving
> mp4box -info output.m4v
...
Track # 3 Info - TrackID 3 - TimeScale 48000
Media Duration 01:47:56.394 - Indicated Duration 01:47:56.394
Track has 1 edit lists: track duration is 01:47:55.373
Track is disabled
Media Info: Language "English (eng)" - Type "soun:mp4a" - 303581 samples
MPEG-4 Config: Audio Stream - ObjectTypeIndication 0x40
MPEG-4 Audio AAC LC (AOT=2 implicit) - 2 Channel(s) - SampleRate 48000
Synchronized on stream 1
        RFC6381 Codec Parameters: mp4a.40.2
Alternate Group ID 1
        All samples are sync
        Max sample duration: 1024 / 48000
```

Yet this is the info output of a different file produced by Handbrake that has the stream name set correctly (note the UDTA line that was missing in the mp4box produced file):
```
Track # 3 Info - TrackID 3 - TimeScale 48000
Media Duration 01:47:56.394 - Indicated Duration 01:47:56.394
Track has 1 edit lists: track duration is 01:47:56.373
Track is disabled
Media Info: Language "English (eng)" - Type "soun:mp4a" - 303581 samples
1 UDTA types: name (1) 
MPEG-4 Config: Audio Stream - ObjectTypeIndication 0x40
MPEG-4 Audio AAC LC (AOT=2 implicit) - 2 Channel(s) - SampleRate 48000
Synchronized on stream 1
        RFC6381 Codec Parameters: mp4a.40.2
Alternate Group ID 1
        All samples are sync
        Max sample duration: 1024 / 48000
```

Version: 1.0.1-rev0-gd8538e8ae-HEAD (compiled from latest release source)
OS: Debian buster amd64

Reference info:
https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFChap2/qtff2.html

**Comment by jeanlf** [comment]
`-meta` is usually for HEIF or MPEG 21 files, not for user data boxes - you need to use `-udta` for this.

I just patched the syntax so you can specify a string directly, rather than reading the content from a file as was the case before:
```
MP4Box -udta TRACKID:type=name:str="Name of My Track" file.mp4 
```

**Comment by eharris** [comment]
That seems to work great! Thanks so much!

As a side note, it would be really great if there was a way to display the contents of shorter udta atoms (like `name` as part of the -info display rather than only showing the type.
