### ISSUE TITLE
fmp4 encrypted content only playing first I-frame

### ISSUE THREAD

**Issue by alberaj** [gpac/gpac#1607]
Hello,

I have been trying to encrypt fmp4 chunks with the feature from https://github.com/gpac/gpac/issues/924 and I believe it is well configured but when playing on dash-if or bitmovin players, they are only able to show the first I-frame of each chunk. So I only see frames in 2 second jumps.
It seems the IV matches for the first frame but than it goes wrong, i can't think of anything else.

I tried doing changes from issues I found here, but it either gets worse and doesnt play at all, or the same issue continues.

I ran the commands
MP4Box -crypt drm.xml header.m4s -out header_myenc.mp4
MP4Box -crypt drm.xml -init-seg header.m4s [layer]_clear/segment.m4s -out [layer]/segment.m4s

with the drm.xml
<?xml version="1.0" encoding="UTF-8"?>
<GPACDRM type="CENC AES-CTR">
	<DRMInfo type="pssh" version="0">
		<BS ID128="EDEF8BA979D64ACEA3C827DCD51D21ED"/>
		<BS data="0x08011210"/>
		<BS ID128="0x783d17c9498e4330a9267b20848e0864"/>
		<BS data="0x220430313237"/>
	</DRMInfo>
	<CrypTrack IsEncrypted="1" IV_size="16" first_IV="0x0a610676cb88f302d10ac8bc66e039ed" saiSavedBox="senc">
		<key KID="0x783d17c9498e4330a9267b20848e0864" value="0x1e74f5182c02b6e39a610676567cd84a"/>
	</CrypTrack>
</GPACDRM>

I checked the pssh data on the init file and it was correct.
I also notice the trun box is losing information from the clear version to the encrypted version, but I don't think the issue is caused by that.

I also tested changing the key value so the player gets the wrong key and can't decrypt and as expected it doesn't play anything. Having the correct key atleast decrypts the first I-frame, so something is working :)

Attached 10 seconds of dummy content I was using to test. Hope you can give me some insight on what may be failing here, cause at this point I ran out of ideas. Thank you.

[manifests_chucks.zip](https://github.com/gpac/gpac/files/5339558/manifests_chucks.zip)

**Comment by jeanlf** [comment]
the issue was not in the crypto but in the timing: the crypted version has no default duration set nor sample duration in truns, because the muxer was using defaults computed from the media properties instead of using the original trex info.

This is now fixed, thanks for the report and test files

**Comment by jeanlf** [comment]
recompile mp4box (static) or the full gpac. I suspect you are still using the old version. When encrypting your segments, add `-fgraph` to check the filter graph, you should see the option `regrag` has been set on the muxer

**Comment by alberaj** [comment]
Yep you are right... fout is showing the old version without regrag

Back to investigating what I did wrong

**Comment by alberaj** [comment]
It works now!

Thanks for the help
