### ISSUE TITLE
Can't display 360° videos when changing the ABR algorithm

### ISSUE THREAD

**Issue by leejinxi** [gpac/gpac#1608]
Hello,

I am now trying to change the default ABR algorithm in dash transmission task while display the video in a panorama view through gpac v1.1.0.

I found that use this command  `gpac -gui /home/out.mpd#VR` can show the panorama view,
and I also found that in the filter way, use `gpac fin:src=/home/out.mpd dashin:algo=bolao vout` can change the default ABR algorithm.

But the question is, I can't combine the two approaches to achieve both results at the same time. such like
`gpac fin:src=/home/out.mpd#VR compositor:player=gui dashin:algo=bolao` or
`gpac fin:src=/home/out.mpd#VR dashin:algo=bolao compositor:nav=vr vout`

Thank you.

**Comment by jeanlf** [comment]
We indeed had an issue forwarding the fragment URL from flist / dashin to compositor in non-gui modes, this is now fixed, thanks for the report !

Notes:

1. VR requires the compositor to transform input video(s) into the view sphere. `vout` can only display a video as is.

2. You don't need to explicitly load the dashin filter to set its options.

You can do with option inheritance:
`gpac -gui source.mpd#VR:algo=bolao`

or with global params:
`gpac --algo=bolao -gui source.mpd#VR`

3. If you need to redirect the compositor output to vout, just use:

`gpac -i source.mpd#VR:algo=bolao compositor @ vout`
