### ISSUE TITLE
MP4Box dashing of EBU-TT-D does not support multiple regions

### ISSUE THREAD

**Issue by SoleneChiche** [gpac/gpac#161]
Hello,

Here is a problem I've encountered while testing EBU-TT-D content: if a document contains several captions in different regions, but active at the same time, the import will give me this result:

Document:

```
<styling>
            <style id="s0" tts:fontStyle="normal" tts:fontFamily="sansSerif" tts:fontSize="100%" tts:lineHeight="normal" ebutts:linePadding="0.5c" tts:textAlign="center" tts:wrapOption="noWrap"/>
            <style id="s1" tts:backgroundColor="#000000" tts:color="#FFFFFF"/>
            <style id="s2" tts:backgroundColor="#000000" tts:color="#FFFF00"/>
</styling>
<layout>
        <region id="r0" tts:origin="5% 80%" tts:extent="90% 20%" tts:overflow="visible" tts:displayAlign="before"/>
        <region id="r1" tts:origin="5% 50%" tts:extent="90% 20%" tts:overflow="visible" tts:displayAlign="before"/>
</layout>
</head>
    <body style="s0">
        <div>
            <p id="sub0" begin="00:00:14.40" end="00:00:17.28" region="r0"><span style="s1">At the left we can see...</span></p>
            <p id="sub0" begin="00:00:14.40" end="00:00:17.28" region="r1"><span style="s1">At the left we can see...</span></p>
.....
```

MP4Box import:

```
TTML: timing overlapping not supported: "begin" is 14040 , last "end" was 17028. Abort.

Unsupported TTML file - only EBU-TTD is supported (root shall be "tt", got tt)
Importing as generic TTML
Saving elephantsdream_25fps-multipleRegions.mp4: 0.500 secs Interleaving
```

MP4Box does not support timing overlapping, however EBU-TT-D needs the support of several active regions at the same time and my guess is that probably other subtitle XML based will need that too? 

Thanks

**Comment by rbouqueau** [comment]
Thanks for reporting. I wish we could have had all these samples when we implemented the first EBU-TTD import :)

It may take some time before we can handle it. I give the priority to bugs over new features. It could be a good idea to have some sponsorship if you need to accelerate this development.

In the meantime, I'll try to add a test to display a better error message.

**Comment by tairt** [comment]
Fully understand this. The question is if this is a feature request. From my perspective it seems more a bug. It would probably be good to list the things that are currently not supported so people know from the beginning with which content they can use.

**Comment by rbouqueau** [comment]
Thanks for your feedback. "Regions" were not implemented by lack of samples (and time too). MP4Box should display "not implemented" ; it doesn't which is indeed a bug.

I prefer to mark this issue as "new feature" so that we know it requires additional developments. Generally speaking, we now have a better understanding of TTML and its derivatives. Improving the support would require a refactoring of the actual code. Overlapping times would be very useful too :)

I agree we should update a page with what is supported and what is not. I propose to update http://gpac.io/2014/08/23/ebu-ttd-support-in-gpac/.

For now only the regression tests that were provided at the time of the implementation are covered: https://github.com/gpac/gpac/tree/master/regression_tests/ttml . I plan to fix bugs for the features covered by these.

What do you think?

**Comment by tairt** [comment]
Thanks, Romain. Yes, this sound like a good plan. http://gpac.io/2014/08/23/ebu-ttd-support-in-gpac/ is the the right place for me too. 

I agree with you that sufficient samples are critical and we should try to gather more. I see if I can contribute some more.

I also agree that a good separation between bugs and fearture request is important. This keeps it transparent what the priority is in terms of implementation and where further (external) support is needed.

**Comment by rbouqueau** [comment]
http://gpac.io/2014/08/23/ebu-ttd-support-in-gpac/ updated. Feedback is welcome.

**Comment by SoleneBuet** [comment]
>- DASH segmentation is fully supported.

DASH segmentation is fully supported? What do you mean exactly? It may be necessary to explain the duplication of samples or maybe the approach of the segmentation, as even me testing it, I'm not quite sure of what's really happening when dashing.

For the test files I'm working on it and I can make them available after it's been validated as correct.

>- There are still a few open questions which are on their way to standardization.

What do you mean by that?

>- You can expect a few minor improvements in the future.

That is great!

>- No <region> element.

Again what do you mean here? I can parse all right the region tags. So not sure of what's not supported.

Thanks a lot for this work.

**Comment by tairt** [comment]
Thanks for updating http://gpac.io/2014/08/23/ebu-ttd-support-in-gpac/

Some comments:

* No images
  * Andreas: this can be taken out. EBU-TT-D does not support image based subtitles.

* No namespace prefix for the TTML namespaces, e.g. “xmlns:tt”.
  * Andreas: this may to little information. Maybe something more like: "It is expected that the default namespace of the source EBU-TT-D document is set to 'http://www.w3.org/ns/ttml'. Documents where this namespaces is bound to prefix is currently not supported"

* No regions:
  * Andreas: That has to be checked. You also need at least one region in EBU-TT-D document. We should make it more concrete what is not supported in respect to regions.

**Comment by rbouqueau** [comment]
@both thank you for your feedback.

@SoleneBuet Keep in mind this page was written months ago, not yesterday :)

> DASH segmentation is fully supported? What do you mean exactly? It may be necessary to explain the duplication of samples or maybe the approach of the segmentation, as even me testing it, I'm not quite sure of what's really happening when dashing.

I am unhappy too by the way TTML is stored in ISOBMF. If you think it can be useful to other people, please feel free to write an explanation about how TTML is DASHed. We'll be happy to help you and publish it on our blog (we have a huge traffic so it should help).

@tairt Page updated.

**Comment by rbouqueau** [comment]
> No namespace prefix for the TTML namespaces, e.g. “xmlns:tt”.

Now added, see #197. Website limitation page amended. Feedback welcome.

**Comment by jeanlf** [comment]
overlapping samples (wether in same or multiple regions) are now supported.
