### ISSUE TITLE
Writing a GPMF Track With libgpac

### ISSUE THREAD

**Issue by lehne** [gpac/gpac#1610]
I am trying to mux GPMF metadata to an mp4 file. GPMF is an ATOM based format designed to be written into an mp4. [https://gopro.github.io/gpmf-parser/](https://gopro.github.io/gpmf-parser/) 

To write it properly, I need to add a track that has a custom sample description (gpmd) and media information header. I cannot find a way to do this within libgpac. Trying to add a text track did not work properly and I get a GF_BAD_PARAM when I try to write the sample with gf_isom_add_sample. When I look at the resulting file, it is missing the sample description. 

This code does not work for me for adding the track information:
 ```
GF_TextSampleDescriptor *sd;
	sd = (GF_TextSampleDescriptor*)gf_odf_desc_new(GF_ODF_TX3G_TAG);
	sd->fonts = (GF_FontRecord*)gf_malloc(sizeof(GF_FontRecord));
	sd->font_count = 1;
	sd->fonts[0].fontID = 1;
	sd->fonts[0].fontName         = gf_strdup("Serif");
	sd->back_color                = 0x00000000;//transparent
	sd->default_style.fontID      = 1;
	sd->default_style.font_size   = 18;         //TTXT_DEFAULT_FONT_SIZE;
	sd->default_style.text_color  = 0xFFFFFFFF;	//white
	sd->default_style.style_flags = 0;
	sd->horiz_justif = 1; //center of scene
	sd->vert_justif = (s8) -1;	//bottom of scene
	sd->default_pos.top = sd->default_pos.left = sd->default_pos.right = sd->default_pos.bottom = 0;

	gf_isom_new_text_description(pIsoFile, trackNumber, sd, NULL, NULL, &streamIdx);
	
	gf_odf_desc_del((GF_Descriptor *)sd);
```
It does not error but when I call gf_isom_add_sample I get an error.

Is there a way to do this within the current API that libgpac provides?

**Comment by jeanlf** [comment]
not without patching the code. What is needed:
- define a new media handler type  - currently the NewMedia() function will imply that a 'meta' handler uses a 'nmhd', instead of a 'gmhd' in this case. 
- implement the 'gpmd' box required in minf.gmhd (this looks like a full box with version=0, flags=0)
- implement the 'gpmd' box required in stsd (this looks like a sample entry extended by 4 bytes set to 0, but I haven't check their spec/example in details). This part can be achieved using gf_isom_new_generic_sample_description

I would define a new media type GPMD to force a 'meta' handler type with the right name and a 'gmhd' media header.

Then the samples can be added as usual

**Comment by rbouqueau** [comment]
@lehne Please don't misunderprets Jean's closing the issue as a discouragement to do this. It is just our procedure since we use github for "issues" but we don't have a place for new features discussion. So let's continue here. And don't hesitate if you have any questions :)

**Comment by lehne** [comment]
No discouragement at all! I very much appreciate the response. How do I define a new media handler type? Do I need to just need to change the type with GF_4CC() after I make the track? How do I resize a box? Is it enough to just change the size property?

**Comment by jeanlf** [comment]
in isomedia.h, add after GF_ISOM_MEDIA_META a :
```
GF_ISOM_MEDIA_META2		= GF_4CC( 'm', 'e', 't', '2' ),
```

in track.c, NewMedia add a new case:

```
		case GF_ISOM_MEDIA_META2:
			mediaInfo = gf_isom_box_new(GF_ISOM_BOX_TYPE_GMHD);
			str = "GPAC Timed MetaData Handler";
			MediaType = GF_ISOM_MEDIA_META; //override back to meta
			break;

```

and then I would suggest adding a new function to create the gpmd sample entry similar to the tmcd one (gf_isom_tmcd_config_new), so that you can create the minf.gmhd.gmpd and stsd.gmpd in that function

**Comment by lehne** [comment]
Thank you for all the help!  I was able to get everything working except the stsd.gpmd. When I try to change the type it does not save to the file: 
	```
GF_GenericSampleEntryBox *sampleEntryBox = (GF_GenericSampleEntryBox *) gf_isom_box_new(GF_ISOM_BOX_TYPE_GNRM);

	if (!sampleEntryBox) return GF_OUT_OF_MEM;
	
	sampleEntryBox->size=20;
	sampleEntryBox->type=GF_4CC('g','p','m','d');
	sampleEntryBox->dataReferenceIndex=dataRefIndex;

	e = gf_list_add(trak->Media->information->sampleTable->SampleDescription->other_boxes, sampleEntryBox);
```

**Comment by jeanlf** [comment]
you modify the type of the box, which won't work for GNRM. You need to set the 'EntryType' field (which indicates the final 4CC to write for generic entries):

```
sampleEntryBox->EntryType=GF_4CC('g','p','m','d');
```

**Comment by lehne** [comment]
Hi Jean, thank you for all of the help so far. I've gotten it correct except for adding the 4 bytes of 0 padding onto a box. If I change the size property, the file ends up unreadable. Do I need to call another function after changing the size property?

**Comment by lehne** [comment]
Update:
I have the SampleDescription correct now.  This is how I did it:
```c
sampleEntryBox->data=(char*)gf_malloc(sizeof(char) * 4);
memset(sampleEntryBox->data,0,4);
sampleEntryBox->data_size=4;
```

I am having trouble with the gmhd->gpmd box though. I've tried this but it results in very strange results:
 ```c
	gpmd = (GF_UnknownBox *)gf_isom_box_new(GF_ISOM_SUBTYPE_TEXT);
	gpmd->type = GF_4CC('g','p','m','d');
	gpmd->data=(char*)gf_malloc(sizeof(char) * 4);
	//set them to 0
	memset(gpmd->data,0,4);
	gpmd->dataSize=4;
	gf_isom_box_add_default((GF_Box *)trak->Media->information->InfoHeader, (GF_Box *)gpmd);
```
What am I missing?

**Comment by jeanlf** [comment]
What are the "strange results" you see ?

**Comment by lehne** [comment]
The data size is 52 bytes instead of 4. This is what I get:
![image](https://user-images.githubusercontent.com/4531382/97299887-0ebfa380-182c-11eb-82ec-5e3075a9c5bc.png)
I was expecting this:
![image](https://user-images.githubusercontent.com/4531382/97299958-2565fa80-182c-11eb-80a6-5c2e4c94902f.png)
