### ISSUE TITLE
dash wvtt subtitles DTS issues, do not pass DASH-IF compliance

### ISSUE THREAD

**Issue by blacktrash** [gpac/gpac#1611]
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/

```sh
MP4Box -add test.vtt -lang en test-vtt.mp4
MP4Box -dash 2000 -profile dashavc264.onDemand -out test.mpd \
test-vtt.mp4:role=subtitle test-108p.mp4#audio \
test-108p.mp4#video [...] test-720p#video
```
gives me several DTS warnings/adjustments like ```[MP4Mux] PID T3 Sample 8 with DTS 7960 less than previous sample DTS 7960, adjusting prev sample duration```.

Indeed some subtitles are duplicated or triplicated, disappear and reappear etc.

MPD demonstrating the issue: https://d2b3xtj80vdo5b.cloudfront.net/dev/lshtrailer-cc.mpd
Symptoms can be observed e.g. in the dashjs sample player at https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/

DASH-IF conformance tool https://conformance.dashif.org/ reports for the subtitle track:
```
Log No	Segment Validation Report
1	### error: moov-1:trak-1 ### ../src/ValidateAtomList.cpp : 789 : ### error: moov-1:trak-1 ### Non-visual/audio track has non-zero trackVolume, trackWidth, or trackHeight
2	(12 repetition\s) ### error: ### ../src/PostprocessData.cpp : 233 : ### error: ### tfdt base media decode time 19.760000 not equal to accumulated decode time 22.000000 for track 1 for sequence_number 12 (fragment absolute count 12)
3	### error: ### ../src/PostprocessData.cpp : 1142 : ### error: ### According to DASH-IF IOP Section 3.2.8 @bandwidth of the Representation (154 bps) is set too low given the @minimumBufferTime (1 s), the minimum @bandwidth value required to conform is 1351 bps.
```
Video and audio tracks are conformant.

```sh
$ MP4Box -version
MP4Box - GPAC version 1.1.0-DEV-rev63-g70a812c75-master
(c) 2000-2020 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io

Please cite our work in your research:
        GPAC Filters: https://doi.org/10.1145/3339825.3394929
        GPAC: https://doi.org/10.1145/1291233.1291452

GPAC Configuration: --prefix=/usr/local --extra-cflags=-I/usr/local/include -I/opt/sw/include --extra-ldflags=-L/usr/loc
al/lib -L/opt/sw/lib
Features: GPAC_CONFIG_DARWIN GPAC_64_BITS GPAC_HAS_IPV6 GPAC_HAS_SOCK_UN GPAC_MINIMAL_ODF GPAC_HAS_QJS GPAC_HAS_FFMPEG G
PAC_HAS_JP2 GPAC_HAS_XVID
```

**Comment by blacktrash** [comment]
FWIW, same behaviour with `dashavc264.live` profile, MPD: https://d2b3xtj80vdo5b.cloudfront.net/dev/lshtrailer-ccx.mpd ; the DASH-IF conformance tool reports a few more errors for the subtitle track (again, none for the other tracks), maybe that helps:
```
***Legend: Errors, Warnings, Information ***
Log No	Segment Validation Report
1	### error: moov-1:trak-1 ### ../src/ValidateAtomList.cpp : 789 : ### error: moov-1:trak-1 ### Non-visual/audio track has non-zero trackVolume, trackWidth, or trackHeight
2	(12 repetition\s) ### error: ### ../src/PostprocessData.cpp : 233 : ### error: ### tfdt base media decode time 19.760000 not equal to accumulated decode time 22.000000 for track 1 for sequence_number 12 (fragment absolute count 12)
3	(23 repetition\s) ### error: ### ../src/PostprocessData.cpp : 865 : ### error: ### Referenced moof earliest_presentation_time 8.000000 does not match to reference EPT 7.960000 for sidx number 5 at reference count 0
4	(23 repetition\s) ### error: ### ../src/PostprocessData.cpp : 911 : ### error: ### starts_with_SAP declared but the first sample's composition time does not match, for sidx number 5 at reference count 0 (checking sample 1 of trun 1, traf 1, moof 5)
5	(23 repetition\s) ### error: ### ../src/PostprocessData.cpp : 925 : ### error: ### SAP not found at the expected presentation time for sidx number 5 at reference count 0
6	### error: ### ../src/PostprocessData.cpp : 1142 : ### error: ### According to DASH-IF IOP Section 3.2.8 @bandwidth of the Representation (154 bps) is set too low given the @minimumBufferTime (1 s), the minimum @bandwidth value required to conform is 1651 bps.
7	(38 repetition\s) ###error- DASH ISO/IEC 23009-1, 7.2.1: 'The maximum tolerance of segment duration shall be +/-50% of the signaled segment duration (@duration)',violated for segment 1, with duration 0 while signaled @duration is 2
```

**Comment by jeanlf** [comment]
could you upload the test VTT file ?

**Comment by blacktrash** [comment]
@jeanlf - thanks, you can grab it from [here](https://blacktrash.org/media/lshtrailer-en.vtt).

**Comment by jeanlf** [comment]
indeed, we had a bug when a sample to split cover 3 or more segments. Now fixed on git and added to [testsuite](https://github.com/gpac/testsuite/blob/filters/scripts/dash-subtitle.sh), thanks for the file and report.

**Comment by blacktrash** [comment]
@jeanlf - thank you, it's kind of there, no user-visible errors when playing in dashjs.

MPD: https://d2b3xtj80vdo5b.cloudfront.net/dev/lshtrailer-l0.mpd
This is what's still happening with `dashavc264.live` profile:

1.
MP4Box -dash [...] runs through, but gives the warning:
```
[Dasher] Adaptation sets in period are of unequal duration min 108.24 max 114.674 seconds
```
2.
DASH-IF conformance still barks at subtitle track:
```
Log No | Segment Validation Report
-- | --
1 | ### error: moov-1:trak-1  ###        ../src/ValidateAtomList.cpp : 789 : ### error: moov-1:trak-1  ###        Non-visual/audio track has non-zero trackVolume, trackWidth, or trackHeight
2 | ###  error:   ###        ../src/PostprocessData.cpp : 1142 : ### error:   ###        According to DASH-IF IOP Section 3.2.8 @bandwidth of the  Representation (154 bps) is set too low given the @minimumBufferTime (1  s), the minimum @bandwidth value required to conform is 1651 bps.
3 | (38 repetition\s) ###error- DASH ISO/IEC 23009-1, 7.2.1: 'The maximum  tolerance of segment duration shall be +/-50% of the signaled segment  duration (@duration)',violated for segment 1, with duration 0 while  signaled @duration is 2
```
3.
dashjs tries to GET a non-existent last subtitle segment, throwing a 403

Will try `dashavc264.onDemand` when I find time.

**Comment by blacktrash** [comment]
With `dashavc264.onDemand` no 403, and only the first 2 validation errors.
Checking the validation logs of the green success ticked streams also yield the error 2 regarding bandwidth. Hm.

**Comment by jeanlf** [comment]
> Non-visual/audio track has non-zero trackVolume, trackWidth, or trackHeight

I believe that's a bug in the validator, CMAF clearly indicates for tkhd  "Subtitle tracks may set width and height to an intended layout size"

> @bandwidth of the  Representation (154 bps) is set too low
We'll look into this

 > 'The maximum tolerance of segment duration shall be +/-50% of the signaled segment duration (@duration)',violated for segment 1, with duration 0 while signaled @duration is 2

clearly a bug from the validator, the first segment has one sample of 2s duration. I think the validator does not handle truns with all default values used.

**Comment by blacktrash** [comment]
@jeanlf - thanks a lot for taking a close look and explaining. I also suspected bugs in the validator, however I expected the duration related error to be the one causing the request for the non-existent segment.

**Comment by jeanlf** [comment]
sure ;) 
BTW, do you have any clue how the dash validator computes the `@min_buffer_time` vs `@bandwidth` ?

**Comment by blacktrash** [comment]
> BTW, do you have any clue how the dash validator computes the `@min_buffer_time` vs `@bandwidth` ?
Nope, I just copied the error message and left the hard work to you ;)
Come to think of it, I just don't understand, either the resource requires the bps in the manifest or not ...? Additionally, the manifest says `minBufferTime="PT1.500S"` which looks a lot like 1.5 seconds to me, whereas the validation error talks about 1s. But then I don't know where the `minBufferTime` is set, whether it's some kind of default value in the standard etc. Is this some kind of minimum bit rate thing? Obviously the bit rate of the subtitle mp4 is very low.

**Comment by rbouqueau** [comment]
@blacktrash It could be useful to report the issue at https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/issues

**Comment by blacktrash** [comment]
@rbouqueau - I agree; I hope to find the time to do it. Thank you.
