### ISSUE TITLE
Compiling latest MP4Box has weird formatting in the CLI

### ISSUE THREAD

**Issue by jlw4049** [gpac/gpac#1614]
This is my first time building, but I followed this guide

https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Windows

It builds perfectly, x86/x64 but when I use the mp4box.exe in command prompt it looks weird like this

```
C:\Users\jlw_4>"C:\BuildMP4Box\gpac_static\bin\x64\Release - MP4Box_only\mp4box.exe" -h
MP4Box [option] input [option]


←[32mGeneral Options:←[0m

←[32m-h←[0m (string):                   print help
        * ←[33mgeneral←[0m: general options help
        * ←[33mhint←[0m: hinting options help
        * ←[33mdash←[0m: DASH segmenter help
        * ←[33mimport←[0m: import options help
        * ←[33mencode←[0m: encode options help
        * ←[33mmeta←[0m: meta handling options help
        * ←[33mextract←[0m: extraction options help
        * ←[33mdump←[0m: dump options help
        * ←[33mswf←[0m: Flash (SWF) options help
        * ←[33mcrypt←[0m: ISMA E&A options help
        * ←[33mformat←[0m: supported formats help
        * ←[33mlive←[0m: BIFS streamer help
        * ←[33mcore←[0m: libgpac core options
        * ←[33mall←[0m: print all the above help screens
        * ←[33mopts←[0m: print all options
        * ←[33mVAL←[0m: search for option named ←[33m←[3mVAL←[0m (without ←[33m←[3m-←[0m or ←[33m←[3m--←[0m) in MP4Box, libgpac core and all filters

←[32m-hx←[0m (string):                  look for given string in all possible options
←[32m-nodes←[0m:                        list supported MPEG4 nodes
←[32m-node←[0m (string):                get given MPEG4 node syntax and QP infolist
←[32m-xnodes←[0m:                       list supported X3D nodes
←[32m-xnode←[0m (string):               get given X3D node syntax
←[32m-snodes←[0m:                       list supported SVG nodes
←[32m-languages←[0m:                    list supported ISO 639 languages
←[32m-boxes←[0m:                        list all supported ISOBMF boxes and their syntax
←[32m-fstat←[0m:                        print filter session statistics (import/export/encrypt/decrypt/dashing)
←[32m-fgraph←[0m:                       print filter session graph (import/export/encrypt/decrypt/dashing)
←[32m-v←[0m:                            verbose mode
←[32m-version←[0m:                      get build version
←[32m---←[0m  INPUT:                    escape option if INPUT starts with ←[33m←[3m-←[0m character
```

I tried this in both Windows 7 x64 and Windows 10 x64 with the same results

Running the same compiled mp4box.exe in GitBash on Windows works perfectly fine and looks correct

**Comment by jeanlf** [comment]
Yes we still have some issues detecting prompt type on windows to disable colored output - until we fix that you can add -logs=ncl to remove this

I can’t reproduce on my win10 here, could you give more info on your win10 version?

**Comment by jlw4049** [comment]
Latest Windows 10 update. Ill post back tomorrow will full build etc once I get to my pc in the AM. 

Is there anything specific you are looking for?

**Comment by jeanlf** [comment]
dunno :(
could you retry with the latest git, and run with `-logs=core@info` to see what is the detected console type ?

**Comment by jlw4049** [comment]
Unless I'm running `-logs=core@info` in the wrong spot, I don't see any changes with latest compiled .exe

`Microsoft Windows [Version 10.0.19041.508]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\jlw_4>"C:\BuildMP4Box\gpac_public\bin\x64\Release - MP4Box_only\mp4box.exe"
Not enough arguments - check usage with -h
MP4Box - GPAC version 1.1.0-DEV-rev85-gd7e3b156e-master
(c) 2000-2020 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io

Please cite our work in your research:
        GPAC Filters: https://doi.org/10.1145/3339825.3394929
        GPAC: https://doi.org/10.1145/1291233.1291452


C:\Users\jlw_4>"C:\BuildMP4Box\gpac_public\bin\x64\Release - MP4Box_only\mp4box.exe" -logs=core@info
MP4Box [option] input [option]


←[32mGeneral Options:←[0m

←[32m-h←[0m (string):                   print help
        * ←[33mgeneral←[0m: general options help
        * ←[33mhint←[0m: hinting options help
        * ←[33mdash←[0m: DASH segmenter help
        * ←[33mimport←[0m: import options help
        * ←[33mencode←[0m: encode options help
        * ←[33mmeta←[0m: meta handling options help
        * ←[33mextract←[0m: extraction options help
        * ←[33mdump←[0m: dump options help
        * ←[33mswf←[0m: Flash (SWF) options help
        * ←[33mcrypt←[0m: ISMA E&A options help
        * ←[33mformat←[0m: supported formats help
        * ←[33mlive←[0m: BIFS streamer help
        * ←[33mcore←[0m: libgpac core options
        * ←[33mall←[0m: print all the above help screens
        * ←[33mopts←[0m: print all options
        * ←[33mVAL←[0m: search for option named ←[33m←[3mVAL←[0m (without ←[33m←[3m-←[0m or ←[33m←[3m--←[0m) in MP4Box, libgpac core and all filters

←[32m-hx←[0m (string):                  look for given string in all possible options
←[32m-nodes←[0m:                        list supported MPEG4 nodes
←[32m-node←[0m (string):                get given MPEG4 node syntax and QP infolist
←[32m-xnodes←[0m:                       list supported X3D nodes
←[32m-xnode←[0m (string):               get given X3D node syntax
←[32m-snodes←[0m:                       list supported SVG nodes
←[32m-languages←[0m:                    list supported ISO 639 languages
←[32m-boxes←[0m:                        list all supported ISOBMF boxes and their syntax
←[32m-fstat←[0m:                        print filter session statistics (import/export/encrypt/decrypt/dashing)
←[32m-fgraph←[0m:                       print filter session graph (import/export/encrypt/decrypt/dashing)
←[32m-v←[0m:                            verbose mode
←[32m-version←[0m:                      get build version
←[32m---←[0m  INPUT:                    escape option if INPUT starts with ←[33m←[3m-←[0m character`

**Comment by jeanlf** [comment]
try `MP4Box -logs=core@info -h`

**Comment by jlw4049** [comment]
> try `MP4Box -logs=core@info -h`

I did try that, makes no difference at all.

**Comment by jeanlf** [comment]
you should see a line at the beginning indicating which console mode has been detected, either:
```[Console] Detected MSys/MinGW/Cygwin TTY, will use VT for coloring```

or

```[Console] Detected Windows shell, will use SetConsoleTextAttribute for coloring```

**Comment by jlw4049** [comment]
> you should see a line at the beginning indicating which console mode has been detected, either:
> `[Console] Detected MSys/MinGW/Cygwin TTY, will use VT for coloring`
> 
> or
> 
> `[Console] Detected Windows shell, will use SetConsoleTextAttribute for coloring`



```
Microsoft Windows [Version 10.0.19041.508]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\jlw_4>C:\Users\jlw_4\Desktop\MP4Box\x64\mp4box.exe -logs=core@info -h
MP4Box [option] input [option]


←[32mGeneral Options:←[0m

←[32m-h←[0m (string):                   print help
        * ←[33mgeneral←[0m: general options help
        * ←[33mhint←[0m: hinting options help
        * ←[33mdash←[0m: DASH segmenter help
        * ←[33mimport←[0m: import options help
        * ←[33mencode←[0m: encode options help
        * ←[33mmeta←[0m: meta handling options help
        * ←[33mextract←[0m: extraction options help
        * ←[33mdump←[0m: dump options help
        * ←[33mswf←[0m: Flash (SWF) options help
        * ←[33mcrypt←[0m: ISMA E&A options help
        * ←[33mformat←[0m: supported formats help
        * ←[33mlive←[0m: BIFS streamer help
        * ←[33mcore←[0m: libgpac core options
        * ←[33mall←[0m: print all the above help screens
        * ←[33mopts←[0m: print all options
        * ←[33mVAL←[0m: search for option named ←[33m←[3mVAL←[0m (without ←[33m←[3m-←[0m or ←[33m←[3m--←[0m) in MP4Box, libgpac core and all filters

←[32m-hx←[0m (string):                  look for given string in all possible options
←[32m-nodes←[0m:                        list supported MPEG4 nodes
←[32m-node←[0m (string):                get given MPEG4 node syntax and QP infolist
←[32m-xnodes←[0m:                       list supported X3D nodes
←[32m-xnode←[0m (string):               get given X3D node syntax
←[32m-snodes←[0m:                       list supported SVG nodes
←[32m-languages←[0m:                    list supported ISO 639 languages
←[32m-boxes←[0m:                        list all supported ISOBMF boxes and their syntax
←[32m-fstat←[0m:                        print filter session statistics (import/export/encrypt/decrypt/dashing)
←[32m-fgraph←[0m:                       print filter session graph (import/export/encrypt/decrypt/dashing)
←[32m-v←[0m:                            verbose mode
←[32m-version←[0m:                      get build version
←[32m---←[0m  INPUT:                    escape option if INPUT starts with ←[33m←[3m-←[0m character
```

```
jlw_4@jlwDesktop MINGW64 ~
$ /c/Users/jlw_4/Desktop/MP4Box/x64/mp4box.exe -logs=core@info -h
MP4Box [option] input [option]


General Options:

-h (string):                   print help
        * general: general options help
        * hint: hinting options help
        * dash: DASH segmenter help
        * import: import options help
        * encode: encode options help
        * meta: meta handling options help
        * extract: extraction options help
        * dump: dump options help
        * swf: Flash (SWF) options help
        * crypt: ISMA E&A options help
        * format: supported formats help
        * live: BIFS streamer help
        * core: libgpac core options
        * all: print all the above help screens
        * opts: print all options
        * VAL: search for option named VAL (without - or --) in MP4Box, libgpac core and all filters

-hx (string):                  look for given string in all possible options
-nodes:                        list supported MPEG4 nodes
-node (string):                get given MPEG4 node syntax and QP infolist
-xnodes:                       list supported X3D nodes
-xnode (string):               get given X3D node syntax
-snodes:                       list supported SVG nodes
-languages:                    list supported ISO 639 languages
-boxes:                        list all supported ISOBMF boxes and their syntax
-fstat:                        print filter session statistics (import/export/encrypt/decrypt/dashing)
-fgraph:                       print filter session graph (import/export/encrypt/decrypt/dashing)
-v:                            verbose mode
-version:                      get build version
---  INPUT:                    escape option if INPUT starts with - character

jlw_4@jlwDesktop MINGW64 ~

```

**Comment by aureliendavid** [comment]
to be more precise: this only happens with MP4Box static mini build on windows, so console detection / coloration must be a disabled feature of this mode, I haven't looked at it yet to see if it can be enabled on static mp4box

**Comment by jeanlf** [comment]
ha ok, I'll check why that differs on mp4box static

**Comment by aureliendavid** [comment]
in https://github.com/gpac/gpac/blob/master/src/utils/error.c#L407 the console detection is only done if GPAC_CONFIG_WIN32 is defined

GPAC_CONFIG_WIN32 is not defined in mini builds, it's defined from the configure script or in https://github.com/gpac/gpac/blob/master/include/gpac/configuration.h#L78

2 options:
 - enable GPAC_CONFIG_WIN32 in mini builds (but it's also used elsewhere so there's a need to check if it doesn't enable anything else that we don't want)
 - replace GPAC_CONFIG_WIN32  in error.c with ifdef WIN32 to enable console detection in all windows builds (seems easier)

on the whole i'm not sure what GPAC_CONFIG_WIN32 is actually supposed to represent and I think it is used at some places in the code as a general shortcut for "if windows" so we might need to clarify its use

**Comment by jlw4049** [comment]
Well, just let me know, I'm down to test more stuff out :)

**Comment by jeanlf** [comment]
now fixed, thanks for all the feedback. I also added a disclaimer for MINI builds to avoid confusion ...

**Comment by jlw4049** [comment]
Working great now!
