### ISSUE TITLE
[MP4Box] -dash with -cues produces only one output segment

### ISSUE THREAD

**Issue by Lachpost** [gpac/gpac#1615]
- [ x ] I looked for a similar issue and couldn't find any.
- [ x ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ x ] I give enough information for contributors to reproduce my issue

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Version:** I tried this with the MP4Box dasher from GPAC version 1.1.0-DEV-rev81-g55293a88-master downloaded precompiled form the website, running on a 64-bit Ubuntu 18.04.5 VM.

**Overview:** I'm trying to produce variable-length DASH segments, with each segment separately downloadable (for bitrate switching later) using the `-cues` flag. I currently use only one resolution for testing (no switching yet).

**Input I get:** A video gets split into variable length stand-alone MP4 files using a custom segmentation process. I have only access to all the resulting (ordered) short clips, with lengths of between less than a second and ~5 seconds.

**Goal:** Prepare this for use with DASH-player using the segmentation from the input (i.e. one clip == one downloadable DASH segment). I use the [DASH-IF reference player](https://reference.dashif.org/dash.js/v3.1.2/samples/dash-if-reference-player/index.html) for testing.

**Pipeline so far:**
First I concatenate all clips into one using ffmpeg:
`ffmpeg -f concat -safe 0 -i path/to/concatlist.txt -c copy path/to/concated.mp4`
Next I assemble the dts timings for the `-cues` option using ffprobe:
I run
`ffprobe -show_packets -of json path/to/filename.mp4 > path/to/filename.json`
on the concatenated file, as well as each clip seperately. I use a python script to generate the `cue_timing.xml` as follows:
For each clip, in order, get the number of _packets_ it consists of (as reported by ffprobe). Jump this many packets ahead in the _packet list_ of the concatenated file, read out the dts value of that packet, and put it into the `cue_timing.xml`. This way the dts at which I'd like to start a new segment corresponds to what once was the start of a clip, which also means that there is already a keyframe at that position.

**What I try to do:** Use `MP4Box -dash` with the `-cues` option on the concatenated file like so:
`MP4Box -dash 1000 -cues path/to/cue_timing.xml -strict-cues -min-buffer 1000 -url-template -segment-timeline -segment-name $Path=path/to/output/$1920x1080/ -out path/to/output/concat_split_single.mpd path/to/concated.mp4`

**Issue:**
Expected result: DASH segments according to the dts values given in `cue_timing.xml`, and the `init.mp4`.
Actual result: The `init.mp4` and one (1) segment `0.m4s` (segment at time==0, when used with $Number$ in template it is `1.m4s`). The MPD reflects the same by only listing one segment in the timeline, spanning the entire duration of the video.
The only way I was able to generate multiple segment files was to also use `-frag`, but doing so ignores the cue timings and creates segments with `-dash-dash_duration` length. Adding `-profile live` above also results in just one segment.

I'm not sure if I interpret the `-cues` option correctly, therefore I don't know if the problem lies with me or MP4Box. Any insight is greatly appreciated.

&nbsp;
This is the example I'm trying to get to work.
You can download the files from here: https://www.dropbox.com/sh/nbbr3tr3lp40bfv/AAAPb8Z84E6xR30UIRa5Tg8ea?dl=0
It includes:
- `concated_1920x1080.mp4`: ~15 second video, result of ffmpeg concat command used, composed of 5 variable length clips.
- `concated_1920x1080.json`: output of ffprobe command used on the concatenated file.
- `cue_timing.xml`: cues-file used.
- `output/` contains the DASH ready files to go on the server: the MPD and inside `1920x1080/` the output of the command above: `init.mp4` and the single `0.m4s` segment.
- `source_files/`: in case it is of help, the source files I receive.

&nbsp;
&nbsp;
P.S.: The `-cues` entry in the [DASH Options on the Wiki](https://github.com/gpac/gpac/wiki/mp4box-dash-opts) has a reference to the renamed `tests/media/dash_cues`, which should now be `testsuite/media/dash_cues`.

**Comment by jeanlf** [comment]
That is interesting, thanks for using this feature ;)

# Your problem
1. First the timescale in your cue file is wrong, it should be 12288

2. then the DTS you list are what is listed by ffprobe, which uses negative DTS, while the dasher expects GPAC internal timing (no negative DTS). Two possibilities here:
- set the `ts_offset` attribute (new feature) of the cue stream to `-1024` in this case
- grab the SAP times using GPAC: `gpac -i concated_1920x1080.mp4 reframer:saps=1 @ inspect:deep` 

This will fix your issue

# My problem
I like your approach, but I'd rather avoid file IOs if not required. So I updated the [flist](flist) and  [dasher](dasher) filters to use inband segmentation:

```
#playlist.m3u
source_files/0.mp4
source_files/1.mp4
source_files/2.mp4
source_files/3.mp4
source_files/4.mp4
```

then (using stl option as the duration will likely vary a lot):

```
gpac -i playlist.m3u:sigcues -o result/live.mpd:stl
```

HTH,

**Comment by Lachpost** [comment]
This is awesome! Thank you for the answer to my problem, and even more for improving my pipeline with the 'sigcues' filter.
