### ISSUE TITLE
MP4box often fails to extract hevc from HEIF images.

### ISSUE THREAD

**Issue by bluenlive** [gpac/gpac#1617]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hello.
Thanks for your great work. I have been using MP4box for years.

# 1. Overview
Some versions of MP4box often fail to extract hevc from HEIF images.
I have confirmed that this problem occurs in the same way in the version downloaded from [GPAC Nightly Builds](https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/) and versions compiled with Visual Studio 2019 by myself.

# 2. System environment
Windows 10 / Version 2004 (OS Build 19041.508) / 64bit

# 3. Compiler
Visual Studio Community 2019, version 16.7.5

# 4. Problem
[Attached files](https://www.mediafire.com/file/pgmnly3ge9fnz81/sampleheifs.rar/file) are 2 HEIF files.
Extracting hevc from these HEIF files using MP4box fails.
These 2 files were created by iOS 13 (iPhone 11 Pro) and were randomly selected. The same thing happens with countless other pictures.

You can easily check the error with those images by entering a command like this:

```mp4box.exe -dump-item 5:path=p1_05.hevc problem1.heic
mp4box.exe -dump-item 11:path=p1_11.hevc problem1.heic
mp4box.exe -dump-item 15:path=p1_15.hevc problem1.heic
mp4box.exe -dump-item 20:path=p1_20.hevc problem1.heic
mp4box.exe -dump-item 26:path=p1_26.hevc problem1.heic
mp4box.exe -dump-item 29:path=p1_29.hevc problem1.heic
mp4box.exe -dump-item 35:path=p1_35.hevc problem1.heic
mp4box.exe -dump-item 48:path=p1_48.hevc problem1.heic

mp4box.exe -dump-item 3:path=p2_03.hevc problem2.heic
mp4box.exe -dump-item 11:path=p2_11.hevc problem2.heic
mp4box.exe -dump-item 20:path=p2_20.hevc problem2.heic
mp4box.exe -dump-item 32:path=p2_32.hevc problem2.heic
mp4box.exe -dump-item 37:path=p2_37.hevc problem2.heic
mp4box.exe -dump-item 47:path=p2_47.hevc problem2.heic
```

# 5. The MP4box version that is having problems
The issue occurs with [3efc028, Commits on Jun 12, 2020](https://github.com/gpac/gpac/commit/3efc028b16718ba9c56e91ee80e46bbbae5a38c7) and later versions(of course including lastest version) released.
The immediate previous release, [e90526f, Commits on Jun 12, 2020](https://github.com/gpac/gpac/commit/e90526f3d2ec0dee4cddc5244eb115668f10341f) and earlier versions, did not have this problem at all.

This problem occurs in the same way for the compiled version and the downloaded official version.

You can download [Attached files from here](https://www.mediafire.com/file/pgmnly3ge9fnz81/sampleheifs.rar/file).

Thanks for reading.
Hope this will be resolved soon.

**Comment by jeanlf** [comment]
indeed, we were also missing a test for that - now fixed, thanks for the report
