### ISSUE TITLE
Option to specify subitle zero

### ISSUE THREAD

**Issue by dadosch** [gpac/gpac#1618]
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...).

It is quite a common industry praxis to specify a time offset in subtitles.  This time offset is called "subtitle zero". Often, an offset of 10 hours is used. More can be found here: https://bbc.github.io/subtitle-guidelines/#Subtitle-zero

It would be great, if the subtitle zero could be passed to MP4Box via an argument, so that it offsets all subtitles by the given amount.

Example ttml subtitle with a 10 hour offset: https://classic.ardmediathek.de/subtitle/258167

**Comment by nigelmegitt** [comment]
@dadosch Thanks for linking to the BBC subtitle guidelines! 

Normally the subtitle zero and offset approach is used for archive and exchange subtitles, such as EBU-TT Part 1, and not for distribution subtitles like the ones you linked to. 

In your case, I would expect the system that generates the EBU-TT-D-Basic-DE profile distribution subtitle to adjust for the offset, not a downstream packager like GPAC. Is there a reason it does not do so in your case? 

Happy to discuss in a less public forum and not pollute this thread with possibly irrelevant conversation.

**Comment by jeanlf** [comment]
@nigelmegitt yes that was what I was also thinking, no sure this really applies here

**Comment by dadosch** [comment]
@nigelmegitt @jeanlf Thank you both for your responses. To be honest, I'm not sure why the ARD even serves subtitle with this 10 hour offset. Interestingly, the subtitles for the Tagesschau for example, a news show, are served without the offset (https://classic.ardmediathek.de/subtitle/441249). (I'm not affiliated with them in any way). 

VLC seems to read subtitles from a ttml file automatically if it has the same name and offsets it automatically (not sure how it does it), but if its embedded into to media file with MP4Box, it doesn't adjust the offset of course.

If this is not a wanted feature for gpac/MP4Box, then I'm fine with closing this issue, it was just an idea for improvement. It is easily possible to use a short script which processes the subtitle file and adjusts the times for the offset.

**Comment by jeanlf** [comment]
OK I think I get your point, you will need to update the entire TTML to trash the initial chapter, which is painful indeed. The issue is that we don't rewrite TTML during the import, we just split the XML in different XML docs, and rewriting the timing is heavy and also error-prone.

I would suggest that you add the ttml as is, but specify a negative delay (in ms) equal to the subtitle_zero duration
```
MP4Box -add source.ttml:delay=-360000000 res.mp4
```
 
and check if the resulting file is played fine.
The drawback is that the TTML track now uses an edit list, which might not be properly supported by players.

**Comment by jeanlf** [comment]
late christmas gift - now on git

**Comment by dadosch** [comment]
Thank you very much :) Have a nice new year, hopefully better than the last one. 😄
