### ISSUE TITLE
mp4box question - Import chapter into mp4 file

### ISSUE THREAD

**Issue by Venus642** [gpac/gpac#1621]
Hello.

How I can import a new chapter txt file to "mp4" file with 
changes for menü #1 and menü #2?

Ok. The command for import is:
mp4box.exe -chap chapterlist.txt file.mp4

The chapterlist.txt overwrites the chapter menü #2 and not menü #1 + #2 (please see attachment file).
But how I can overwrite menü #1?

Sorry. I found not information how I can do it.

![menue](https://user-images.githubusercontent.com/72867951/96010612-48fb6f00-0e42-11eb-8c78-c352f141ec08.jpg)

**Comment by jeanlf** [comment]
not sure what you are trying to do here, could you detail more ? Do you want to setup an other chapter with a different language ?

**Comment by jeanlf** [comment]
no follow up, closing - feel free to reopen with more detailed use case
