### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by AimerYi** [gpac/gpac#1623]
when I use this command to start my ghtorrent:ruby -Ilib bin/ght-retrieve-repo -c config.yaml gousiosg github-mirror;
It will  generate this warning:
WARN, 2020-10-15T18:29:16+08:00, ghtorrent -- api_client.rb: Failed request. URL: https://api.github.com/users/gousiosg?per_page=100, Status code: 401, Status: Unauthorized, Access: place your , IP: 0.0.0.0, Remaining: 59
WARN, 2020-10-15T18:29:16+08:00, ghtorrent -- api_client.rb: Unauthorised request with token: place your github token here
WARN, 2020-10-15T18:29:16+08:00, ghtorrent -- ghtorrent.rb: Transaction failed (989 ms)
401 Unauthorized
seems like Permissions issue

**Comment by aureliendavid** [comment]
wrong repo?
