### ISSUE TITLE
How to enable customized FFMPEG libraries in gpac

### ISSUE THREAD

**Issue by barrelo89** [gpac/gpac#1625]
My environment:
ubuntu 16.04 LTS desktop x64

Question: How to enable customized FFMPEG when compiling gpac

Since GPAC supports full FFMPEG as mentioned in the release note, I am trying to enable my customized FFMPEG in GPAC:

Full FFMPEG support:
Encoding/decoding through FFMPEG libavcodec.
Multiplexing/demultiplexing through FFMPEG libavformat.
Device grabbers through FFMPEG libavdevice.
Raw audio and video filters through FFMPEG libavfilter.

First, I referred to this issue page about how to enable openhevc in gpac: https://github.com/gpac/gpac/issues/979

I download gpac source code from https://github.com/gpac/gpac and ffmpeg source code from https://ffmpeg.org/download.html

As stated in GPAC Build Guide, I first tried to configure in such a way that I could use my customized FFMPEG (I made some minor changes in the way of video decoding)

step 1: ./configure --use-ffmpeg=local

and the following is a part of the configure result.

** Extra Libraries used **
FreeType: system
JPEG: system
OpenJPEG: no
PNG: system
MAD: no
FAAD: no
XVID: no
FFMPEG: local
LZMA: yes
Xiph OGG: system
Platinum UPnP: no
AVCap: no
Xiph Vorbis: no
Xiph Theora: system
A52 (AC3): no
OpenSVCDecoder: no
OpenHEVCDecoder: no
Freenect: system

As shown above, FFMPEG is set to 'local'. 

After that, I copied 'libavcodec.a', 'libavdevice.a', 'libavfilter.a', 'libavformat.a', 'libavutil.a', 'libpostproc.a', 'libswresample.a', and 'libswscale.a'. to gpac_public/extra_lib/lib/gcc, which was automatically created after ./configure --use-ffmpeg=local.  

step 2: make

If I run 'make', I encounter the following error message: 

/usr/bin/ld: /usr/local/lib/libswscale.a(swscale.o): relocation R_X86_64_PC32 against symbol `ff_M24A' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:346: recipe for target '../bin/gcc/libgpac.so' failed
make[1]: *** [../bin/gcc/libgpac.so] Error 1
make[1]: Leaving directory '/home/duin/Downloads/gpac_public/src'
Makefile:13: recipe for target 'all' failed
make: *** [all] Error 2

I recompiled FFMPEG by enabling PIC and tried it again, but it is still not working.

Could anyone give some help on this issue?

Thanks in advance.

**Comment by aureliendavid** [comment]
you have the right approach but it looks like it's still trying to link against your system version of libswscale

i'll try to reproduce it to see if there's a priority issue in the configure/make

in the meantime you can try to run `make SHELL='sh -x'` to see the exact command that fails and maybe rearrange the `-L`s to link against the right libs

(another workaround would be to remove/hide your ffmpeg system libs to see if that's really the issue but it's not a great solution)

**Comment by aureliendavid** [comment]
After doing some test I could reproduce the issue. 

There seems to be some (known) issues when linking static ffmpeg libraries to an external shared library (like libgpac.so), even when PIC is enabled. 

There are 3 solutions:

**1. build ffmpeg dynamically**

```
ffmpeg configure tested: ./configure --enable-shared --disable-static --disable-doc --disable-ffmpeg --disable-ffplay --disable-ffprobe --disable-symver --disable-programs --disable-debug --enable-pic  --disable-everything

gpac configure tested: ./configure --use-ffmpeg=local
```

it removes relocation problems all together 

_Disadvantage:_ you'll have to either `make install` your custom ffmpeg libs on your system or point LD_LIBRARY_PATH to where they are at runtime (and probably at compile time too)

**2. static ffmpeg with Bsymbolic**

```
ffmpeg configure tested: ./configure --disable-shared --enable-static --disable-doc --disable-ffmpeg --disable-ffplay --disable-ffprobe --disable-symver --disable-programs --disable-debug --enable-pic --disable-everything

gpac configure tested: ./configure --use-ffmpeg=local  --extra-ldflags='-Wl,-Bsymbolic'
```

The ffmpeg documentation suggest doing that: https://ffmpeg.org/platform.html#toc-Advanced-linking-configuration

_Disadvantage:_ I don't know if using that extra linker flag has an impact on the linking of other libs to libgpac. I'm pretty sure there's no issue but I tried reading https://docs.oracle.com/cd/E19957-01/806-0641/chapter4-16/index.html and got an instant headache

**3. static ffmpeg without asm**

```
ffmpeg configure tested: ./configure --disable-shared --enable-static --disable-doc --disable-ffmpeg --disable-ffplay --disable-ffprobe --disable-symver --disable-programs --disable-debug --enable-pic --disable-everything --disable-asm

gpac configure tested: ./configure --use-ffmpeg=local 
```

The ffmpeg PIC issues seem to come from asm code. By disabling it it links properly. 

_Disadvantage:_ I suppose there's a performance hindrance to disabling asm code in ffmpeg

**Comment by barrelo89** [comment]
Hello, Thanks for the quick and detailed reply to my inquiry!

After numerous trials of configuration and compilation, I finally made it!

The solution for the problem is technically in the same approach of your suggested solutions.

The key part was to set '--enable-shared' in FFMPEG configuration.

The following is the step-by-step building for GPAC with customized FFMPEG libraries.

1) Configure FFMPEG:
`
./configure --enable-libx264 --enable-gpl --cc='gcc -m64 -fPIC' --enable-shared
`
2) Compile and Install FFMPEG:
`
sudo make -j6; sudo make install
`

4) Configure gpac (interestingly, as my customized ffmpeg libraries are located in '/usr/local/lib' after FFMPEG installation, even without '--use-ffmpeg=local' options, gpac is using my customized FFMPEG library):
`
./configure --use-ffmpeg=local
`
5) Compile and Install gpac
`
sudo make; sudo make install
`

After this, the changes in FFMPEG source code (for test, I simply added printf("WE ARE INSIDE FFMPEG H264 CODEC!") in decode.c of FFMPEG source code) were taking effect in MP4Client as shown below:
`
###########$ MP4Client original.mp4 
System info: 15921 MB RAM - 8 cores
Loading GPAC Terminal
Terminal Loaded in 133 ms
Opening URL original.mp4
Service Connected
WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!
Buffer :  CODEC!Service Disconnected
Deleting terminal... No filter chain found for PID V1 in filter NVidia HWGL AVC|H264 to any loaded filters - NOT CONNECTED
done (in 196 ms) - ran for 6031 ms
GPAC cleanup ...
WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!WE ARE INSIDE FFMPEG H264 CODEC!
`

**Comment by rbouqueau** [comment]
Could you give more details? e.g. your platform/os, the versions of FFmpeg and GPAC, and your command-lines... Anything that would help someone to reproduce to help you.

**Comment by aureliendavid** [comment]
as a guess: make sure your gpac build uses the right headers for your local ffmpeg binaries and version - you can overwrite files in `extra_lib/include/libav*` with the headers from you own ffmpeg build for example

**Comment by shubhamchdhary** [comment]
I'm using Ubuntu 20.0.4. I'm trying to build GPAC 2.2.0 with local FFmpeg 6.0. binary.

For building FFmpeg, I used:
```
./configure --enable-gpl --enable-libkvazaar --extra-libs=-lpthread --enable-libx264 --enable-libx265 --enable-libvpx --enable-libaom --enable-nonfree --enable-shared --disable-static --enable-pic
```

This built FFmpeg successfully. Then tried building GPAC with
```
./configure --use-ffmpeg=local
```
This throws below errors on building.
```/usr/bin/ld: filters/ff_common.o: in function `ffmpeg_build_register':
ff_common.c:(.text+0x1a80): undefined reference to `avio_protocol_get_class'
/usr/bin/ld: ff_common.c:(.text+0x26e7): undefined reference to `avio_protocol_get_class'
```

**Comment by aureliendavid** [comment]
looks to me like a headers version problem, see my message above

also if you try to build with ffmpeg 6 you should use the latest master of gpac and not the 2.2 tag as per https://github.com/gpac/gpac/issues/2406

**Comment by aureliendavid** [comment]
I think #2406 would be a later error than yours

The error you pasted is probably because NO_AVIO_PROTO is not defined here https://github.com/gpac/gpac/blob/master/src/filters/ff_common.c#L935 because the versions found in the headers are not correct

**Comment by shubhamchdhary** [comment]
Yes, then? How do you think I could fix the problem?

**Comment by aureliendavid** [comment]
it's hard to say without knowing your specific set up 

how did you build/install your ffmpeg libraries? where are they located? where are the headers?

(you can try doing it the same way as the post above: https://github.com/gpac/gpac/issues/1625#issuecomment-712311708)

you need to check what the gpac configure script is actually detecting

you can check post your `config.log`  to see what's happenging

you can also run configure with `sh -x configure [your parameters] > configure_result.log` and post the results

you can run make with `make SHELL='sh -x' > make_result.log` also

**Comment by aureliendavid** [comment]
while I'm here

if you can't make install ffmpeg system-wide you can do something like this:

```shell
~/dev/gpac/FFmpeg (release/6.0) $  mkdir localinstall
~/dev/gpac/FFmpeg (release/6.0) $  make prefix=localinstall install
~/dev/gpac/FFmpeg (release/6.0) $  rm -rf ../gpac_public/extra_lib/include/libav*
~/dev/gpac/FFmpeg (release/6.0) $  cp -a localinstall/include/* ../gpac_public/extra_lib/include/
~/dev/gpac/FFmpeg (release/6.0) $  cp -a localinstall/lib/* ../gpac_public/extra_lib/lib/gcc/
```

then for gpac

```shell
# this can be done many other ways but it's a quick way to make sure the libs will found a compile and runtime
~/dev/gpac/gpac_public (master *) export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/dev/gpac/gpac_public/extra_lib/lib/gcc:~/dev/gpac/gpac_public/bin/gcc

~/dev/gpac/gpac_public (master *) make distclean ; ./configure --use-ffmpeg=local  ; make -j
```

check it works

```shell
~/dev/gpac/gpac_public (master *) $ ldd bin/gcc/gpac | grep avcodec
        libavcodec.so.60 => /home/adavid/dev/gpac/gpac_public/extra_lib/lib/gcc/libavcodec.so.60 (0x00007fb98d100000)
~/dev/gpac/gpac_public (master *) $ bin/gcc/gpac
Nothing to do, check usage "gpac -h"
gpac - GPAC command line filter engine - version 2.3-DEV-rev313-ge73160fbd-master
```

**Comment by shubhamchdhary** [comment]
I tried the exact same steps as above. Built FFmpeg 6.0 successfully. Copied files to gpac extra_lib/. Still it throws the following errors on building

```
filters/ff_mx.c: In function ‘ffmx_close_seg’:
filters/ff_mx.c:506:65: error: ‘AVIOContext’ {aka ‘struct AVIOContext’} has no member named ‘written’
  506 |  evt.seg_size.media_range_end = ctx->muxer->pb ? (ctx->muxer->pb->written-1) : 0;
      |                                                                 ^~
filters/ff_mx.c: In function ‘ffmx_configure_pid’:
filters/ff_mx.c:1016:48: error: ‘const struct AVOutputFormat’ has no member named ‘query_codec’
 1016 |  if (ctx->muxer->oformat && ctx->muxer->oformat->query_codec) {
      |                                                ^~
filters/ff_mx.c:1017:28: error: ‘const struct AVOutputFormat’ has no member named ‘query_codec’
 1017 |   res = ctx->muxer->oformat->query_codec(ff_codec_id, 1);
      |                            ^~
make[1]: *** [../config.mak:183: filters/ff_mx.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:13: all] Error 2
```

**Comment by aureliendavid** [comment]
It's not the same error as before so there's progress. 

You are now in the case of #2406 and you need to use the latest master version of gpac from git to build against ffmpeg 6

Otherwise you can use ffmpeg 5 with gpac 2.2.1

**Comment by shubhamchdhary** [comment]
Yes, it's different :)
I'll try with the latest version of GPAC.

**Comment by shubhamchdhary** [comment]
Hi @aureliendavid, thank using https://github.com/gpac/gpac/issues/1625#issuecomment-1581185023 worked. I can now use Kvazaar directly from GPAC (v2.3.0 with the latest FFmpeg). But when trying to use the fragmented mode like this
```
gpac -i video://:fmt=x11grab:framerate=30:video_size=1280x720:dev=: --kvazaar-params=tiles=4x4,slices=tiles,mv-constraint=frametilemargin,input-fps=30,input-res=1280x720 enc:c=libkvazaar tilesplit @ -o p1:ext=mp4:frag
```

It throws a warning like this
```
[MP4Mux] Cannot add track to already finalized movie in fragmented file, will request a new muxer for that track
No filter chain found for PID video1_tile1 in filter mp4mx to any loaded filters - NOT CONNECTED
```

The generated output file has only one stream, which should be 17 for a 4x4 tiled video, right?
I'm not able to use fragmented mode properly.

**Comment by aureliendavid** [comment]
hi, 

glad the build worked

please open a separate issue for this since this is not directly related to building custom ffmpeg with gpac

thanks

**Comment by acrilique** [comment]
Hi, I'm trying to build gpac with a custom ffmpeg shared library with kvazaar enabled in a windows 11 x86_64 system. I've successfully built the ffmpeg binaries using media_autobuild_suite which is an automatic builder for a whole suite of media utilities including ffmpeg. I've added to my user's Path environment variable the path to the executables. 
`PS C:\dev\gpac\gpac_public\build\msvc14> ffmpeg
ffmpeg version N-113317-g9c21477452 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev3, Built by MSYS2 project)
  configuration:  --disable-static --enable-shared --pkg-config=pkgconf --cc='ccache gcc' --cxx='ccache g++' --ld='ccache g++' --extra-cxxflags=-fpermissive --extra-cflags=-Wno-int-conversion --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-schannel --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-libkvazaar --enable-gmp --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libaom --disable-debug --extra-libs=-liconv --extra-cflags=-DKVZ_STATIC_LIB --enable-gpl --enable-version3 --shlibdir=/local64/bin-video
  libavutil      58. 36.101 / 58. 36.101
  libavcodec     60. 37.100 / 60. 37.100
  libavformat    60. 20.100 / 60. 20.100
  libavdevice    60.  4.100 / 60.  4.100
  libavfilter     9. 17.100 /  9. 17.100
  libswscale      7.  6.100 /  7.  6.100
  libswresample   4. 13.100 /  4. 13.100
  libpostproc    57.  4.100 / 57.  4.100
Universal media converter
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'`

I tried building gpac with visual studio (msvc) method, and I copied everything from my custom ffmpeg build (libav folders and .lib and .dll files) to the gpac dependencies folder. Then after building (build is completed sucessfully) I tested `gpac -h ffenc:libkvazaar` and kvazaar isn't available because the build process just overrode my custom ffmpeg files. I might have probably missed something, or this isn't a good approach to do this. 

Has anyone attempted this on windows? Is there a proper way to do this? I'm really in need of a gpac windows binary with kvazaar enabled. 
Thanks for your time, I'll quickly respond if you ask for the characteristics of my system or anything like that.

**Comment by aureliendavid** [comment]
> I tried building gpac with visual studio (msvc) method, and I copied everything from my custom ffmpeg build (libav folders and .lib and .dll files) to the gpac dependencies folder.

Hi,

What did you copy where exactly?

Since you're using msvc, my advice would be: 

- follow the guide at https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Windows#full-gpac-build
- ***before*** doing the step called "Copying dependencies" :
 . go to the `deps_windows/lib/x64/release` folder and replace all the av* (.libs and .dlls) with yours
 . you might also have to replace the headers in `deps_windows/include` (so replace the libav* folders with the headers for your custom build)
- then continue the guide by copying dependencies and building gpac

This is basically what I do when upgrading the ffmpeg version for the official gpac builds. 

To get an indication of which files to change, you can take a look at this commit for example: https://github.com/gpac/deps_windows/commit/601531175fe9d6b42b531eba30df91913832bcec

**Comment by acrilique** [comment]
Indeed, what I did wrong was copying all the stuff before actually building the dependencies, so they got overwritten. 
Now `gpac -h ffenc:libkvazaar` works as expected. 
Thanks a lot.
