### ISSUE TITLE
USAC/xHE-AAC support

### ISSUE THREAD

**Issue by Kurtnoise** [gpac/gpac#1627]
Hi,

Since an open source USAC/xHE-AAC encoder [is now available](https://gitlab.com/ecodis/exhale), it would be great to have its support into gpac library.

A sample has been uploaded [here](https://filebin.net/u8vfpxonrwcdjqxj). 

A basic patch also can be found there : http://pastebin.fr/69313

Thanks in advance.

Regards,

**Comment by jeanlf** [comment]
thanks for the info, I just added support for usac import/export (latm for raw stream).
