### ISSUE TITLE
Is there any similar  Multiple Object Tracking function

### ISSUE THREAD

**Issue by a23232390** [gpac/gpac#1629]
I want to track people in the HEVC TILES video
![image](https://user-images.githubusercontent.com/68137277/97173263-3c283500-17cb-11eb-99cb-5a92ec760c91.png)

**Comment by jeanlf** [comment]
No, you will need to use openCV or similar libraries for that.
If you want to do this with GPAC, my recommended way would be to use the GPAC python bindings (latest git) together with openCV python, and build your CV images from GPAC packets.

Alternatively, you can dump the video to raw YUV, RGB or frames (see [wiki](https://github.com/gpac/gpac/wiki/raw-formats) ) and do the analysis off-line. 

Also,  I'm not sure what is the relationship with tiling here.

**Comment by a23232390** [comment]
Thank you very much for your answer
I am doing related research
I want to adjust the quality of each tiles by tracking
