### ISSUE TITLE
Recursive looping through folders

### ISSUE THREAD

**Issue by WimVDK** [gpac/gpac#1630]
I'm far from an expert on MP4box or even CLI but with the help of other's i've managed to semi get where i want to go. I have a ton of video files organised like this
```

<root folder>
  <Subfolder1>
    <final folder 1>
      file1.mp4
      file2.mp4
    <final folder 2>
      file1.mp4
   <subfolder2>
   <subfolder3>
```

etc. There's a ton of video files in them all with english audio, but plenty without the proper header so Plex lists them as "Unknown audio". I was referred to MP4box as it should be able to do this, but the ones recommending it to me arent fully versed in it either.

I currently have the following line in a batch file in the root folder

> for /R %%a in ("*.mp4") do MP4Box -add "%%a#1:lang=en" -add "%%a#2:lang=en" -new "%%~na.mp4"
> pause

The problem with that is that it creates a new file (probably due to the -new) in the ROOT folder where the batch file is located. I'm trying to UPDATE the existing files with the proper audio language header, and have MP4box place the updated file in the same folder either by simply updating the existing file, or replacing the existing file with the audio flag updated file.

Can anyone fix that commandline for me? I'd be very grateful!

**Comment by jeanlf** [comment]
If you only need to patch the language tag, you don't have to reimport nor create a new file, just do:
```MP4Box -lang 1=en -lang 2=en source.mp4```

**Comment by WimVDK** [comment]
Tried and failed

> for /R %%a in ("*.mp4") do MP4Box -lang 1=en -lang 2=en source.mp4
> pause

results in

> MP4Box -lang 1=en -lang 2=en source.mp4
> Error opening file source.mp4: Requested URL is not valid or cannot be found

**Comment by jeanlf** [comment]
in your case, `source.mp4` would be `%%~na.mp4`, I imagine

**Comment by WimVDK** [comment]
No dice 

> F:\Complete Series>MP4Box -lang 1=en -lang 2=en Another Life (2019) - S01E01 - Across the Universe.mp4
Error - 2 input names specified, please check usage

**Comment by jeanlf** [comment]
If your file names have space, you must quote the filename, i.e. `"%%~na.mp4"` otherwise the prompt will interpret each word as an argument

**Comment by WimVDK** [comment]
Still no dice

> for /R %%a in ("*.mp4") do MP4Box -lang 1=en -lang 2=en "%%~na.mp4"
pause

Result

> F:\Complete Series>for /R %a in ("*.mp4") do MP4Box -lang 1=en -lang 2=en "%~na.mp4"
> F:\Complete Series>MP4Box -lang 1=en -lang 2=en "Another Life (2019) - S01E01 - Across the Universe.mp4"
Error opening file Another Life (2019) - S01E01 - Across the Universe.mp4: Requested URL is not valid or cannot be found

That particulare file for example is located in
F:\Complete Series\Another Life (2019)\S01

What i'm after is to place the batch file in the root folder, have it browse through the subfolders, look for the subfolders of that and then update the files in it. When all sub-subfolders have been done. Go back to the root, and browse the next

**Comment by jeanlf** [comment]
you need the full path, not just the filename - I'm no expert in DOS batch, but this should be %%~fA

**Comment by WimVDK** [comment]
No dice,
> f:\Complete Series>BatchAssignAudioLanguage.bat
%~fA was unexpected at this time.

f:\Complete Series>for /R %~fA in ("*.mp4") do MP4Box -lang 1=en -lang 2=en %~na.mp4

I'm all ears if you have a better idea of doing this :)

**Comment by jeanlf** [comment]
more like:

```for /R %%a in ("*.mp4") do MP4Box -lang 1=en -lang 2=en "%%~fa"```

see [this thread](https://stackoverflow.com/questions/9252980/how-to-split-the-filename-from-a-full-path-in-batch) on SO for DOS batch file name manipulation

**Comment by WimVDK** [comment]
SUCCESS! You're the best. That last line did the trick. Succesfully updated file in that 1st sub-subfolder, then jumped to the 2nd subfolder and proceeded from there
