### ISSUE TITLE
Playready, Widevine key rotation per X seconds?

### ISSUE THREAD

**Issue by Murmur** [gpac/gpac#1631]
How do `keyRoll="roll=5"` parameter actually works and how do this number relates to segment durations? Say I have a `segment.duration=4s, segment.fragment=1s (four moof/mdat pairs in segX.m4s file), fps=25, gop=50` structure, 

I would like to test a new key every 3 minutes(180s / 4s = every 45th segment file)?
Do keys go around if vod media duration was longer than `keyCount+keyRoll=N` iteration?

> roll=N : Common Encryption allows groups of samples within the track to use different keys. The encryption parameters (i.e KID, initialization vector size and encryption flag) are contained in a 'SampleGroupDescriptionBox' and will override the default parameters for this track. If this option is set, each N encrypted samples will share the same key supported by the DRM system.

GPAC-DRMSystem example with key rotation in an another issue.
https://github.com/gpac/gpac/wiki/Common-Encryption
https://github.com/gpac/gpac/issues/1555
```
<?xml version="1.0" encoding="UTF-8"?>
<GPACDRM type="CENC AES-CTR">
<DRMInfo type="pssh" version="1" cypherOffset="9" cypherKey="0x6770616363656E6364726D746F6F6C31" cypherIV="0x00000000000000000000000000000001">
<BS ID128="6770616363656E6364726D746F6F6C31"/>
<BS value="4" bits="32"/>
<BS ID128="0x279926496a7f5d25da69f2b3b2799a7f"/>
<BS ID128="0x597669572e55547e656b56586e2f6f68"/>
<BS ID128="0x205b2b293a342f3d3268293e6f6f4e29"/>
<BS ID128="0x32783e367c2e4d4d6b46467b3e6b5478"/>
<BS bits="8" string="CID=Toto"/>>
<BS ID128="0x5544694d47473326622665665a396b36"/>
<BS ID128="0x7959493a764556786527517849756635"/>
<BS ID128="0x3a4f3674376d6c48675a273464447b40"/>
<BS ID128="0x3e213f6d45584f51713d534f4b417855"/>
</DRMInfo>
<CrypTrack trackID="1" IsEncrypted="1" IV_size="16" first_IV="0x0a610676cb88f302d10ac8bc66e039ed" selectiveType="RAP" saiSavedBox="senc" keyRoll="roll=5">
<key KID="0x279926496a7f5d25da69f2b3b2799a7f" value="0x5544694d47473326622665665a396b36"/>
<key KID="0x597669572e55547e656b56586e2f6f68" value="0x7959493a764556786527517849756635"/>
<key KID="0x205b2b293a342f3d3268293e6f6f4e29" value="0x3a4f3674376d6c48675a273464447b40"/>
<key KID="0x32783e367c2e4d4d6b46467b3e6b5478" value="0x3e213f6d45584f51713d534f4b417855"/>
</CrypTrack>
</GPACDRM>
```

**Comment by jeanlf** [comment]
Encryption and segmentation are completely de-correlated. At 25fps and rolling every 3min, you will need to use N=4500.

If new key index is greater than defined keys, the key index is looped (I'll add that to the doc)
