### ISSUE TITLE
Question: How to input a @scheme/@value?

### ISSUE THREAD

**Issue by quantizationbit** [gpac/gpac#1632]
Hi --

I am looking to build a MPD with a particular @scheme/@value and a specific brand.  For the scheme/value I am looking for "2094-40" per  [DASH-IOP](https://dashif-documents.azurewebsites.net/DASH-IF-IOP/master/DASH-IF-IOP.html#codecs-hevc-hdr-smpte209440).  For the brand I am trying to make ftyp equal to 'chd1,cdm4'.

I've tried the following unsuccessfully and also tried to use gpac instead of mp4box but I couldn't get as far

$ mp4box -dash 3000 -brand chd1:cdm4 File.mp4 -out FILE_dash.mpd:kind="http://dashif.org/metadata/hdr"="SMPTE2094-40"

For the 'kind' I was expecting to get a new "EssentialProperty" line in the output MPD with the schemeIdURI/value and for the brand I was expecting to have the ftype updated. I'm unable to verify the brand, I used mp4box -diso to dump the ISOBMFF but I don't see the brand values I applied in the command. 

Best Regards,
Bill

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X ] I looked for a similar issue and couldn't find any.
- [X ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
for the brands, -brand is ignored during dashing, it only modifies brand of a file before writing it (as a general rule, only the options listed in `MP4Box -h dash` are considered during dashing, plus `-out`).

You can however modify the brands property (`IsoAltBrands`) associated with the source file.

For kind, at the current time you need to specify the MPD descriptor manually, in this case using an AdaptationSet (`:desc_as`) descriptor.

`MP4Box -dash 3000 File.mp4:desc_as="<EssentialProperty schemeId=\"http://dashif.org/metadata/hdr\" value=\"SMPTE2094-40\"/>":#IsoAltBrands=chd1,cdm4 -out temp/live.mpd`


We might want to expose kind as a PID property in the near future, I'll look into that.

**Comment by quantizationbit** [comment]
Hi thankyou --

 I was able to insert a "SupplementalProperty" using the syntax you provided.  
    (from MPD:)   <SupplementalProperty schemeId="http://dashif.org/metadata/hdr" value="SMPTE2094-40"/>


I think the #IsoAltBrands did not go into the ftyp properly or I am not targetting the right ftyp that CMAF wants.  I ended up trying the following commands: I am aiming to have the file be CMAF brand 'chd1' with 'cdm4' as a compatible brand

(case 1: tried chd1,cdm4)
$ mp4box -dash 3000 hdr10plus.mp4:desc_as="<SupplementalProperty schemeId=\"http://dashif.org/metadata/hdr\" value=\"SMPTE2094-40\"/>":#IsoAltBrands=chd1,cdm4 -out hdr10plus_dash.mpd

<FileTypeBox Size="32" Type="ftyp" Specification="p12" Container="file" MajorBrand="isom" MinorVersion="1">
<BrandEntry AlternateBrand="isom"/>
<BrandEntry AlternateBrand="413F3A80"/>
<BrandEntry AlternateBrand="iso6"/>
<BrandEntry AlternateBrand="dash"/>
</FileTypeBox>

(case 2: tried brand/alt)
$ mp4box -dash 3000 hdr10plus.mp4:desc_as="<SupplementalProperty schemeId=\"http://dashif.org/metadata/hdr\" value=\"SMPTE2094-40\"/>":#IsoBrand='chd1':#IsoAltBrands='cdm4' -out hdr10plus_dash.mpd

and when using mp4box -diso on the output _dashinit.mp4 I get the following XML:
<IsoMediaFile xmlns="urn:mpeg:isobmff:schema:file:2016" Name="hdr10plus_dashinit.mp4">
<FileTypeBox Size="28" Type="ftyp" Specification="p12" Container="file" MajorBrand="chd1" MinorVersion="1">
<BrandEntry AlternateBrand="chd1"/>
<BrandEntry AlternateBrand="iso6"/>
<BrandEntry AlternateBrand="dash"/>
</FileTypeBox>

(case 3 tried only cdm4)
If I try only putting one alternate brand it seems to get but it is not clear why the ftyp is not 'chd1' automatically since the mp4 is and HDR10 asset
$ mp4box -dash 3000 hdr10plus.mp4:desc_as="<SupplementalProperty schemeId=\"http://dashif.org/metadata/hdr\" value=\"SMPTE2094-40\"/>":#IsoAltBrands='cdm4' -out hdr10plus_dash.mpd 

<FileTypeBox Size="32" Type="ftyp" Specification="p12" Container="file" MajorBrand="isom" MinorVersion="1">
<BrandEntry AlternateBrand="isom"/>
<BrandEntry AlternateBrand="F8733C90"/>
<BrandEntry AlternateBrand="iso6"/>
<BrandEntry AlternateBrand="dash"/>
</FileTypeBox>

**Comment by jeanlf** [comment]
you need to pull/recompile we had a parsing issue with lists of 4CCs
