### ISSUE TITLE
MP4Box fullrange flag

### ISSUE THREAD

**Issue by TheoTheCaptain** [gpac/gpac#1636]
Hello,

For a few years I have been using a script with a quite older version of MP4Box  to modify the fullrange flag to off in videos from Gopro cameras. The reason was that after editing said videos to reduce file size, the video looked kind of washed out. After research, the reason for that seemed to be that gopro incorrectly flagged the videos as full range colour, when in reality they are limited range.

For that reason, I used to modify the fullrange flag to off with the following command  
on  MP4Box - GPAC version 0.4.6-DEV (internal rev. 7) 

mp4boxmod -add filename.mp4:fullrange=off newFilename.mp4 

which solved the problem and produced excellent videos after encoding.

Now I have switched to using a newer Gopro 8, which uses h264 + HEVC options. 
The older Mp4Box would throw an error related to hvc1, so I updated to the latest Mp4Box version

MP4Box - GPAC version 1.0.1-rev0-gd8538e8a-master
On this newer version when trying to run my command for turning fullrange flag to off I get the following error:

Unrecognized import option fullrange=off, ignoring
[FileIn] Failed to open C:*Filepath*\GX011821.MP4:fullrange=off [Importer] Cannot load filter for input file "C:*MyFilepath*\GX011821.MP4:fullrange=off" Error importing 
C:*MyFilepath*\GX011821.MP4:fullrange=off: Requested URL is not valid or cannot be found

Has the command been changed /deprecated or am I misusing it?

**Comment by jeanlf** [comment]
The option was never part of GPAC, you were using [this fork](https://github.com/golgol7777/gpac) ...

I back-ported a few of the changes there in the master branch, including `fullrange` and general VUI edition (for these ones the syntax has slightly changed), and made that available for HEVC as well. 

Thanks for feedback!
