### ISSUE TITLE
mux hevc es data to mp4 file,the result is missing 1 frames

### ISSUE THREAD

**Issue by lancodec** [gpac/gpac#1640]
[test.zip](https://github.com/gpac/gpac/files/5550699/test.zip)

the input hevc file is 3789 frames. but the output test.mp4 is 3788 frames.

 MP4Box   -add /test.265 -tmp /test/  -new /test.mp4

**Comment by jeanlf** [comment]
indeed, now fixed, thanks for the report and test file!
