### ISSUE TITLE
Question : DRM decryption from client ?

### ISSUE THREAD

**Issue by jaseemkm** [gpac/gpac#1642]
Is there any way to get IV from DRM Clear key ASE-128 CTR encrypted file. 
how do we manually decrypt this file from client.

**Comment by jeanlf** [comment]
in CTR mode the IV is per sample, you can see it using `MP4Box -diso source.mp4` or `gpac -i source.mp4 inspect:deep`.
The key is NOT in the content, and we don't deal with key delivery in GPAC. 

If you want to decrypt the content (assuming you have the key), setup a DRM config file for the key, using the indicated keyID in the file and decrypt using gpac or MP4Box - see [our wiki](https://github.com/gpac/gpac/wiki/Common-Encryption).
