### ISSUE TITLE
MacOS decryption error with CBCS

### ISSUE THREAD

**Issue by alberaj** [gpac/gpac#1643]
Hello,
I have been trying to use cbcs encryption on fmp4 content to be played by Apple devices. Testing it in Safari with jwplayer

Basically player isn't playing with error: "An error occurred when attempting to decrypt the Fairplay stream with the session key. Equivalent to Safari's "webkitkeyerror" event."

I checked with another packager, using the same keys and encryption, and the content plays out fine. I also check the content inside mdat and it is exactly equal to MP4box output, every byte.
This leads me to believe it may be something related with the header boxes before mdat?
senc box seems a match too, so I don't understand what might be the problem with the key in mp4box

Could some important config on drm.xml be missing? I tried to look for info on it but didn't find anything that pointed to a problem in my drm.xml

I also tried to decrypt the file output from -crypt with -decrypt and got the error:
**mp4box.exe -decrypt drm_cbcs.xml -init-seg 01.mp4 cbcs_constantIV.m4s -out decrypt_cbcs.m4s**
_[iso file] Unknown top-level box type 00020034
[iso file] Unknown top-level box type 001C0000
Error IsoMedia File is truncated while instantiating filter mp4dmx
[Decrypter] Cannot load demux filter for source file
        Error: IsoMedia File is truncated_

Attached the drm.xml, the clear header file, clear chunk, mp4box cbcs chunk and the comparison chunk that works.
I can attach content for a complete playout if needed.
Using nightly build MP4Box - GPAC version 1.1.0-DEV-rev90-g98d790119-master

Thank you for the help
[cbcs_constantIV.zip](https://github.com/gpac/gpac/files/5559711/cbcs_constantIV.zip)

**Comment by jeanlf** [comment]
for decryption, you need to pass the encrypted init segment to `-init-seg`

The archive does not include the init segments for the chunks, could you upload them ?

**Comment by jeanlf** [comment]
FYI, I just fixed the `Unknown top-level box type` bug in your decrypt command

**Comment by alberaj** [comment]
The header files after encryption
[headers.zip](https://github.com/gpac/gpac/files/5559889/headers.zip)

Also decrypt worked with correct header and output is fine. Thanks!

**Comment by jeanlf** [comment]
apart from 32-bits vs 64 bits duration which shouldn't be an issue, I see some differences:
- keyID is 0x00000000000000000000000000000000 in other packager case
- senc is not optimized in other packager case, leading to varying sample size info
- trun is not optimized in other packager, leading to larger runs description
- senc is before trun in GPAC, after in other packager (both are perfectly legal)

I think the last difference could be the source of the problem. I just patched the code to support changing this order: pull/ recompile and add `--truns_first` to your encryption command line, and let me know if that works.

**Comment by alberaj** [comment]
It is working with that fix! Such a simple detail of ordering having that kind of impact...

Thank you for the help
