### ISSUE TITLE
-Not really an issue- How to generate the xml file ? Is there a tool ? 

### ISSUE THREAD

**Issue by SAMYEL06** [gpac/gpac#1649]
Hello,

I've found a sample xml file for testing & then created a dash manifest and played it = no issue, it worked PERFECTLY !.

My question is : How do I produce the xml file ? (to avoid using one I found online..) 

Is there a tool to use or is it all manual ? And if so, please, how to proceed ? 

Sorry for this dumb question but it's been 3 days and haven't been able to find specific docs about it other than [this one](https://github.com/gpac/gpac/wiki/Common-Encryption) that explains what it is, but not how to produce one :/

Btw, I'm looking to produce a "CENC AES-CTR" xml one, not a commercial DRM or anything ^^"

Thanks and sorry for the issue :x

**Comment by Murmur** [comment]
Answered here
https://github.com/gpac/gpac/issues/1580
