### ISSUE TITLE
Final srt subtitles are incorrect

### ISSUE THREAD

**Issue by alitteration** [gpac/gpac#1650]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Good day,
`
<AdaptationSet id="0" contentType="text" lang="en" segmentAlignment="true">
      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="subtitle"/>
      <Representation id="0" bandwidth="794" codecs="wvtt" mimeType="application/mp4">
        <SegmentTemplate timescale="1000" initialization="xxx_caption_DFXP/vtt_init.m4v" media="xxx_caption_DFXP/seg_$Number$.m4s" startNumber="1">
          <SegmentTimeline>
            <S t="0" d="6000" r="23"/>
            <S t="144000" d="2146"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>`

Subtitles_Mp4: http://www.mediafire.com/file/u98nb4cfpw18s45/subs.mp4/file

I'm basically an issue extracting the webvtt from that webvtt dash subtitles. I tried "MP4Box -srt Subs.mp4" but the final .srt is incorrect.
I also tried : "MP4Box -raw 1 subs.mp4" but the generated vtt have wrong end timestamps.
I keep on getting a warning message whenever I try to extract the subtitles saying :
"[iso file] Unknown box type vlab in parent wvtt"

Can you help me generateing .srt or webvtt for it?

Thanks a lot

**Comment by jeanlf** [comment]
indeed the dump was pretty much broken - now fixed on git, thanks for the report

**Comment by alitteration** [comment]
Hello,
I appreciate the quick fix, sadly the timestamps still seem broken

The .srt timestamps should be in the form of 
[hours]: [minutes]: [seconds], [milliseconds]

While the output I get from Mp4box with -srt flag are in that form :
00:06.000 --> 00:06.040
they should be : 
00:00:06,000 --> 00:00:06,040

Also for the embedded webvtt, the Timestamps seems broken:
00:06.000 --> 00:06.040 position:10%,start line:85% size:80%
they should be:
00:00:04.040 --> 00:00:06.040 position:10%,start line:85% size:80%

Thanks again !

**Comment by jeanlf** [comment]
I've fixed the srt (and other issues in vtt dump), thanks for the report 

I'm not sure what you mean with the vtt issue, could you elaborate ?

**Comment by alitteration** [comment]
Hello, 
I'm sorry for multi-posting. Thanks for the quick fix too.
I just meant that the timestamp is also missing the hours part, the final exported from Mp4box look like:

00:04.040 --> 00:06.000 position:10%,start line:85% size:80%
while the correct timestamp also for webvtt should include the hours' timestamp as in
00:00:04.040 --> 00:00:06.040 position:10%,start line:85% size:80%

Hope I'm clear with explaining that.

Thanks again

**Comment by jeanlf** [comment]
why should the vtt timestamp include the hour part ? It's not mandatory in webvtt spec

**Comment by alitteration** [comment]
I honestly never knew this myself,  thanks for pointing out that.
I have seen several vtt before and I don't recall seeing ones missing the hours' timestamp. 
I have this in hand atm so I'm doing a comparison based on it: https://pastebin.com/raw/wYvCR9qd
I just feel it would be more verbose in case it was there, thanks again!

**Comment by jeanlf** [comment]
cf https://www.w3.org/TR/webvtt1/#webvtt-timestamp

**Comment by alitteration** [comment]
> cf https://www.w3.org/TR/webvtt1/#webvtt-timestamp

I looked,and you're indeed right, I also couldn't find an Episode of more than an hour length :D to test on, but I'd assume that if the media length is more than an hour, MP4Box exported subtitles output will show up as "01:00:00.000" in the final .vtt timestamp.

If that is the case, then I feel it's perfectly fine, I believe It was me getting used to seeing it that way.

If there was an option to actually add it, It would be great, but for now, things looking good after some checks I've done on the final .srt. I appreciate the fixes again, thanks and you can close the issue for now :)

**Comment by jeanlf** [comment]
Yes I can add a switch to force hours dump

**Comment by alitteration** [comment]
That would be great indeed :)

**Comment by jeanlf** [comment]
done, use `-webvtt-hours`

**Comment by alitteration** [comment]
Thanks again jeanlf, appreciate it
