### ISSUE TITLE
Android compilation environment is too old

### ISSUE THREAD

**Issue by sunpan3213** [gpac/gpac#1651]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

The entire compilation environment is too old!
Can you adapt NDK-r21b before you can compile arm64

**Comment by sunpan3213** [comment]
The entire compilation environment is too old!
Can you adapt NDK-r21b before you can compile arm64

**Comment by jeanlf** [comment]
That would break compatibility with old devices - what is the issue you have ?

**Comment by sunpan3213** [comment]
I want to compile the gpac dynamic library. However, due to the environment of the project and other solutions, I cannot compile the armv7-a and arm64 dynamic libraries. In this way, libx264 supports gpac. Can you help me compile it or give me a script that can be compiled under ubuntu

**Comment by aureliendavid** [comment]
I don't really understand what you're trying to do or the problem you're encountering. But you can try following the guide at https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Android and adapting it to a newer ndk if you need it.

**Comment by sunpan3213** [comment]
ffmpeg enable libx264，libx264 enable gpac。so i need compile gpac



发自我的iPhone


------------------ Original ------------------

**Comment by sunpan3213** [comment]
> I don't really understand what you're trying to do or the problem you're encountering. But you can try following the guide at https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Android and adapting it to a newer ndk if you need it.

this solution can do compile ffmpeg4.3.1 support mp4 mp3lame freetype?

**Comment by sunpan3213** [comment]
can you give me a gpac.so file,i compile failed

**Comment by jeanlf** [comment]
please give more details on your compilation issues, closing until then.
