### ISSUE TITLE
Final Srt/webvtt timestamps are not correct

### ISSUE THREAD

**Issue by alitteration** [gpac/gpac#1652]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Hello,
I appreciate the quick fix in https://github.com/gpac/gpac/issues/1650 but, sadly the timestamps still seem broken

The .srt timestamps should be in the form of

[hours]: [minutes]: [seconds], [milliseconds]

While the output I get from Mp4box with -srt flag are in that form missing the Hours part and the "." should be "," :

00:06.000 --> 00:06.040
they should be :
00:00:06,000 --> 00:00:06,040

Also for the embedded webvtt, the Timestamps seems broken:

00:06.000 --> 00:06.040 position:10%,start line:85% size:80%
they should be:
00:00:04.040 --> 00:00:06.040 position:10%,start line:85% size:80%

Thanks again !

**Comment by jeanlf** [comment]
please don't multi-post, keep discussion in #1650
