### ISSUE TITLE
mingw-w64 compilation failed quickjs.c:53736:5: error: unknown type name 'pthread_cond_t'

### ISSUE THREAD

**Issue by 1480c1** [gpac/gpac#1655]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

platform: windows 10
compiler: mingw-w64 x86_64 gcc compiler from msys2

errors out with
```c
C:/MinGW64/build/gpac-git/src/quickjs/quickjs.c: At top level:
C:/MinGW64/build/gpac-git/src/quickjs/quickjs.c:53736:5: error: unknown type name 'pthread_cond_t'
53736 |     pthread_cond_t cond;
      |     ^~~~~~~~~~~~~~
C:/MinGW64/build/gpac-git/src/quickjs/quickjs.c:53740:8: error: unknown type name 'pthread_mutex_t'
53740 | static pthread_mutex_t js_atomics_mutex = PTHREAD_MUTEX_INITIALIZER;
      |        ^~~~~~~~~~~~~~~
C:/MinGW64/build/gpac-git/src/quickjs/quickjs.c:53740:43: error: 'PTHREAD_MUTEX_INITIALIZER' undeclared here (not in a function)
53740 | static pthread_mutex_t js_atomics_mutex = PTHREAD_MUTEX_INITIALIZER;
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~
```
full log:
[ab-suite.make.log](https://github.com/gpac/gpac/files/5648344/ab-suite.make.log)
relevant lines start from 5092

trying to look at the file in question, my best intuition guess is due to pthread.h being defined out if `WIN32`, I can try compiling after changing it to `_MSC_VER` instead
related: https://github.com/m-ab-s/media-autobuild_suite/issues/1875

**Comment by jeanlf** [comment]
thanks for the report, mingw-w32 and mingw-w64 are now fixed.
