### ISSUE TITLE
Problems inserting subtitle (*.srt) files that contain certain pairs of words (e.g. "children", "Group")

### ISSUE THREAD

**Issue by adaviding** [gpac/gpac#1656]
I am trying to insert subtitles from a `children.srt` file into an mp4 file using a command like this:

```
mp4box.exe -add input.mp4 -add children.srt:hdlr=sbtl:group=2:layer=-1:name=MyCaptions -new output.mp4
```

You can use any mp4 file for this example.  The `children.srt` file contains:
```
1
00:00:00,000 --> 00:00:05,000
We have the words "children" and "Group" here.

2
00:00:05,000 --> 00:00:13,000
We have the words "children" and "OrderedGroup" here.

3
00:00:13,000 --> 00:00:22,000
We have the words "children" and "Layer2D" here.

4
00:00:22,000 --> 00:00:32,000
We have the words "children" and "Layer3D" here.
```

The problem is that mp4box uses the `btplay` filter to read the SRT file because of the probe code in `load_bt_xml.c`.

```c
} else if ( strstr(probe_data, "children") &&
			(strstr(probe_data, "Group") || strstr(probe_data, "OrderedGroup") || strstr(probe_data, "Layer2D") || strstr(probe_data, "Layer3D"))
) {
	mime_type = "application/x-bt";
```

It should be using the `txtin` filter (which it uses for `*.srt` files).

There are several ways to fix this problem.  For example, if a file has the `.srt` extension then you might prefer the `txtin` filter over `btplay`.

**Comment by jeanlf** [comment]
oops - I'll cleanup the prober which is indeed a bit too vague...

Meanwhile you can run the same command line and disable probing (`-no-probe`) that should do the trick

**Comment by adaviding** [comment]
That worked, thanks @jeanlf

**Comment by jeanlf** [comment]
should now be fixed, thanks for the report
