### ISSUE TITLE
MP4Box dash return different output with the same input 

### ISSUE THREAD

**Issue by kocoten1992** [gpac/gpac#1657]
- [x] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Step to reproduce:
1. create an random audio file
```
ffmpeg -f lavfi -i "sine=frequency=1000:duration=10" -ac 8 test.mp4
```
2. use that audio file to create mpd and output
```
MP4Box -dash 2000 -rap -frag-rap  -bs-switching no -profile "onDemand" "test.m4a" -out "output1.mpd"
```
```
mv test_dashinit.mp4 test_dashinit.mp4.bak
```
```
MP4Box -dash 2000 -rap -frag-rap  -bs-switching no -profile "onDemand" "test.m4a" -out "output2.mpd"
```

I've notice that md5 of `test_dashinit.mp4` and `test_dashinit.mp4.bak` are not identical, I've assumed we use some sort of timestamp when create dashinit.

Is there anyway I could eliminate that timestamp and make it identical ?

Thank you very much.

**Comment by jeanlf** [comment]
You can use the `-for-test` option which disables all varying stuff (dates, libgpac version numbers etc) in produced files (that's what we use in the test suite).

The MP4Box `-keep-utc` option is not yet integrated for dashing, I'll look into that asap.

**Comment by jeanlf** [comment]
-keep-utc now forwarded to the various filter sessions, thanks for the report
