### ISSUE TITLE
Impossible to opt-out of X11 linkage when X11 exists

### ISSUE THREAD

**Issue by DomT4** [gpac/gpac#166]
Platform: OS X
Version: 10.8 - 10.10.4
Tested against 0.5.2 & current Git master build.

It seems to be impossible to opt-out of linking `gpac` to `x11` when X11 is available on the machine, even when you tell `configure` you don't want the X11 elements.

```
./configure --prefix=/Users/Dominyk/Downloads/gpac-0.5.2/TESTING --disable-x11-shm --disable-x11-xv --X11-path=no
```

`config.mak` sets:
```
CONFIG_X11=yes
X11_LIB_PATH=no/lib
X11_INC_PATH=no/include
```

And then `make` blows up:

```
In file included from x11_out.c:26:
./x11_out.h:38:10: fatal error: 'X11/Xlib.h' file not found
#include <X11/Xlib.h>
         ^
1 error generated.
make[2]: *** [x11_out.o] Error 1
make[1]: *** [plugs] Error 2
make: *** [all] Error 2
```

Not setting any `--X11-path` doesn't work either. `config.mak` ends up with:

```
CONFIG_X11=yes
X11_LIB_PATH=/usr/X11R6/lib
X11_INC_PATH=/usr/X11R6/include
```

And then configures in `x11` availability even though I specifically requested it doesn't:

```
~> otool -L gpac-0.5.2/TESTING/lib/gpac/* | grep x11
gpac-0.5.2/TESTING/lib/gpac/gm_x11_out.dylib:
	../../bin/gcc/gm_x11_out.dylib (compatibility version 0.0.0, current version 0.0.0)
```

**Comment by rbouqueau** [comment]
I confirm. There is no option to make X11 optional.

GPAC contains a player and it would make no sense not to have X11 on MacOS where this is the only available display output.

If you don't need the player, use '--disable-player' or even '--static-mp4box' (for a static mp4box build).

What is your exact need?

**Comment by DomT4** [comment]
Is it not possible that some users would want to use only the command-line interface?

X11 isn't always available on recent OS X versions - It has to be manually downloaded and installed, and opportunistically scooping up X11 rather than having it as a feature that a user can enable/disable as desired makes it [difficult](https://github.com/Homebrew/homebrew/pull/38890) to package.

It was just a surprise that the X11 linkage remained default even if `--disable-x11-shm --disable-x11-xv --X11-path=no` were passed. It wasn't obvious that `--disable-player` was the recommended way to opt-out of X11 inclusion.

**Comment by jeanlf** [comment]
This was indeed a bug, if you have SDL on OSX you shouldn't need x11. You can now exclude it using --disable-x11 at configure, thanks for the report.

**Comment by DomT4** [comment]
Thanks for the quick fix, Appreciated!
