### ISSUE TITLE
Windows UNC not working

### ISSUE THREAD

**Issue by baerlein** [gpac/gpac#1663]
Importing and exporting files with UNC paths is not working. Example:

mp4box.exe -add \\server\d\video.264 \\server\d\muxed.mp4

results in error:

[Importer] No valid track to import in input file "\\server\d\video.264"
Error importing \\server\d\video.264: Feature Not Supported

This used to work in an older version which I have: 0.7.0-rev0-gbd5c9af-master

Checked with both gpac-1.0.1-rev0-gd8538e8a-master-x64.exe and gpac-1.1.0-DEV-latest-master-x64.exe.
(In my original post, there are two backslashes before "server" as required. The editor removes one)

**Comment by jeanlf** [comment]
should now be fixed, thanks for the report
