### ISSUE TITLE
SIDX DUMP

### ISSUE THREAD

**Issue by jp557198** [gpac/gpac#1664]
How do I dump the sidx of a mp4 file ?

Thanks!

**Comment by jeanlf** [comment]
Only XML dump is possible:

`MP4Box -diso file.mp4`.

If you need trun/senc info as well, you may need to use `MP4Box -init-seg init_url.mp4 segment.m4s`.

**Comment by jp557198** [comment]
thanks very much.. i had one more follow up question.
can mp4box generate a list of URLs given a DASH mpd ? 
complete with the byte ranges needed for each segment listed in the sidx?

**Comment by jp557198** [comment]
Disregard.. All the offsets are listed when running -diso against the complete mp4. 
The offsets will not be listed if only reading the init and sidx. Only the lenths of the segments are listed in the sidx, which of course can be used to derive/calculate the offsets.

Thanks!
