### ISSUE TITLE
Problem with image size VVC

### ISSUE THREAD

**Issue by Jamaika1** [gpac/gpac#1667]
Happy New Year

mp4box -info input_1280x720.266
```
[VVC] Picture header in slice header incomplete support, cannot guess slice type
Import probing results for input.266:
File has 1 tracks
Duration: 1 s
        Track 1 type: Video Codec VVC Video (ID 1987470112)
        Size 95x79 @ 25 FPS
```
https://github.com/fraunhoferhhi/vvenc/issues/16
VVEncoderApp.exe -v 5 -t 4 -s 1280x720 -r 30 -c yuv420 -b 8 -g 16 --preset medium --profile main10 --level 6.3 --tier high -i input.yuv -o output.266

Input screenshot
https://vcgit.hhi.fraunhofer.de/jvet/VVCSoftware_VTM
```
[VVC] Picture header in slice header incomplete support, cannot guess slice type
Import probing results for output.266:
File has 1 tracks
Duration: 1 s
        Track 1 type: Video Codec VVC Video (ID 1987470112)
        ???
```
EncoderApp.exe --SummaryVerboseness --InputFile=image_21447_24bit.yuv --BitstreamFile=image_21447_24bit.266 --SourceWidth=1563 --SourceHeight=1558 --FrameRate=25.000 --InputBitDepth=8 --OutputBitDepth=8 --MSBExtendedBitDepth=8 --MatrixCoefficients=0 --InputColorPrimaries=-1 --LMCSSignalType=2 --ConformanceWindowMode=1 --FramesToBeEncoded=1 --HashME=1 --IBC=1 --DecodingRefreshType=1 --Profile=auto --InputSampleRange=1 --AspectRatioInfoPresent=1 --ChromaLocInfoPresent=1 --MaxCUWidth=16 --MaxCUHeight=16 --CTUSize=32 --MaxBTLumaISlice=32 --MaxBTChromaISlice=32 --MaxBTNonISlice=32 --MaxTTLumaISlice=32 --MaxTTChromaISlice=32 --MaxTTNonISlice=32 --CostMode=lossless --InputChromaFormat=444 --ChromaFormatIDC=444 --QP=0 --BDPCM=1 --ColorTransform=1 --VideoFullRange=1 --ChromaTS=1 --DepQuant=0 --LMCSEnable=0 --RDOQ=0 --RDOQTS=0 --SBT=0 --ISP=0 --MTS=0 --LFNST=0 --JointCbCr=0 --LoopFilterDisable=1 --SAO=0 --TransformSkip=1 --TransformSkipFast=1 --TransformSkipLog2MaxSize=5 --SAOLcuBoundary=0 --Log2MaxTbSize=5 --ALF=0 --CCALF=0 --BIO=0 --PROF=0 --InternalBitDepth=0 --IntraPeriod=1 --GOPSize=1 --SearchRange=64 --QpInValCb="17 22 34 42" --QpOutValCb="17 23 35 39" --BCW=0 --BcwFast=0 --BIO=0 --CIIP=0 --Geo=0 --AffineAmvr=0 --LMCSUpdateCtrl=1 --LMCSOffset=0 --DMVR=0 --SMVD=0 --PROF=0 --ISPFast=1 --FastMIP=1 --FastLFNST=1 --FastLocalDualTreeMode=0 --AffineAmvrEncOpt=0 --MmvdDisNum=8 --OnePictureOnlyConstraintFlag=1 --GciPresentFlag=1 --Level=15.5 --Tier=high --RateControl=0 --SubpicDecodedPictureHash=1 --MaxLayers=1 --CbQpOffset=1 --CrQpOffset=1 --TemporalSubsampleRatio=1 --LCTUFast=1 --TemporalFilter=0 --DualITree=1 --MinQTLumaISlice=8 --MinQTChromaISliceInChromaSamples=4 --MinQTNonISlice=8 --MaxMTTHierarchyDepth=3 --MaxMTTHierarchyDepthISliceL=3 --MaxMTTHierarchyDepthISliceC=3 --MMVD=1 --Affine=1 --SbTMVP=1 --MaxNumMergeCand=6 --LMChroma=1 --IMV=1 --MRL=1 --IBC=0 --AllowDisFracMMVD=1 --MIP=1 --PBIntraFast=1 --FastMrg=1 --AMaxBT=1 --HadamardME=1 --FEN=1 --FDM=1 --VerCollocatedChroma=1 --EnableDecodingCapabilityInformation=1 --EnableOperatingPointInformation=1 --DefaultPtlDpbHrdMaxTidFlag=1

https://github.com/mpeg5/xeve
```
Import probing results for output.266:
File has no selectable tracks
```
xeve_app.exe -i "input.yuv" -o "output.266" -v 2 -q 0 -d 8 -w 1280 -h 720 -z 30 -f 200 --profile 1 --level 6.2 --amvr 1

**Comment by Jamaika1** [comment]
Here are some examples
https://www.sendspace.com/file/ajdgdw

**Comment by jeanlf** [comment]
now fixed for vvc - evc is not on the roadmap for the time being

**Comment by Jamaika1** [comment]
Thx 👍
