### ISSUE TITLE
fix potential NULL pointer dereference in filters/reframe_qcp.c

### ISSUE THREAD

**Issue by XidongWang-coder** [gpac/gpac#1669]
In function qcpdmx_configure_pid() in file filters/reframe_qcp.c, ctx->opid should be checked before passed to gf_filter_pid_remove in case of potential NULL pointer dereference.  
https://github.com/gpac/gpac/blob/4228658a9b7dcc50622dcbbe8d14cd63bfeaa460/src/filters/reframe_qcp.c#L82-L96
 A similar fix is in [https://github.com/gpac/gpac/commit/570b527cf9b64a9a50672c1395d3dd8f5aafe143](url).

I've already submitted a pull request. [https://github.com/gpac/gpac/pull/1668](url)

**Comment by jeanlf** [comment]
indeed, now fixed on git thanks for the report
