### ISSUE TITLE
How to use libgpac.py add ABR algorithm 

### ISSUE THREAD

**Issue by a23232390** [gpac/gpac#1672]
i want add ABR (bolao ) to choose the high quality or low quality
Is there a template?

**Comment by jeanlf** [comment]
bola-o is natively implemented in gpac , cf [gpac -h dashin](https://github.com/gpac/gpac/wiki/dashin#algo)

If you want to implement your own version of the algo, check the [python howto](https://github.com/gpac/gpac/wiki/python#dash-client)
