### ISSUE TITLE
potential NULL pointer dereference in filters/filelist.c

### ISSUE THREAD

**Issue by XidongWang-coder** [gpac/gpac#1676]
In function filelist_next_url() in /src/filters/filelist.c, fentry should be checked before used in case it's NULL.

https://github.com/gpac/gpac/blob/9f143de8c6180be433259329ecfac302f39e5df1/src/filters/filelist.c#L439-L446

**Comment by jeanlf** [comment]
there shouldn't be a case where this is null, file_list_idx is an internal variable between 0 and number of items in list
