### ISSUE TITLE
Unable to merge segments to mp4

### ISSUE THREAD

**Issue by alitteration** [gpac/gpac#1679]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Hello, 
It might not be an issue but I was wondering if it's possible to actually merge those segments of similar m3u8 as :
https://content-ause2-ur-discovery1.uplynk.com/ce6f6a0e4c0c440ca22f05e5e14a82a4/f.m3u8?pbs=294fa09c22a04e4fba447b20c5ee7f0c

into one mp4.

Those segments are AES 128 encrypted with IV in every segment.
I tried using MP4Box following what was written in here "https://github.com/gpac/gpac/issues/1236" but I was unsuccessful with it.

Any Help would be appreciated.

Thanks in advance

**Comment by jeanlf** [comment]
That was on my todo for some time, now available on git.

The implementation assumes that the key URI (local file or http(s) URL) resolves directly to the 128 bit key.
This works for both TS and MP4 and support key roll.
Tests are available [here](https://github.com/gpac/testsuite/blob/master/scripts/hls.sh).
