### ISSUE TITLE
How do I use gpac in my own  android app

### ISSUE THREAD

**Issue by Daktm** [gpac/gpac#1680]
I am a VR developer. I want to play high resolution video in vr headest,so I found the gpac.
I read this build/android/README file,this file guid how to make a gpac apk.
Q: how to complie gpac library for android?

**Comment by aureliendavid** [comment]
You can read https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Android

then check the script here https://github.com/gpac/gpac/blob/master/build/android/jni/gpac_build_android and extract just the steps you want if you don't want the full apk

**Comment by jeanlf** [comment]
Following the guide will give you libgpac for android. 

The default [JNI libgpac wrapper](https://github.com/gpac/gpac/tree/master/applications/osmo4_android_studio/app/src/main/jni) gives access to the terminal API (MP4Client/Osmo). If you need direct access to the filter session, you will have to extend this wrapper (or define a new one).
