### ISSUE TITLE
MP4Box not handling complex IMSC1 profile ttml caption files

### ISSUE THREAD

**Issue by mabuge90** [gpac/gpac#1681]
Hello, I am trying to package and DASHify an IMSC1 profile ttml file using the following commands:

# To wrap the ttml file around and the mp4 container:
mp4box -add <imsc1_file>.ttml -new <imsc1_ttml>.mp4

#To segment the mp4 file into 1s segments:
mp4box -dash 1000 -profile live -rap <imsc1_file>.mp4 -out <output_dir>/MPD.mpd

I understand that MP4Box currently supports only the EBU-TTD-TTML profile. As I mentioned earlier, my document has the IMSC1 profile and consists of several regions active at the same time to test various ttml parameters. 

The problem I am encountering is that MP4Box currently repeats the entire document in each sample without a different start and end time and without the ‘redundant’ flag. This means the player does not know that it should just extend the presentation of the previous sample.

In practice this can impose a lot of strain on the decoder since it will have to parse and decode the same TTML document repeatedly. In theory I could break the TTML document into smaller ones but that requires a lot of overhead in order to break it up and package each file individually. 

[mp4box_ttml.log](https://github.com/gpac/gpac/files/5836744/mp4box_ttml.log)

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
could you post a sample file? Also which version of MP4Box are you using ?

**Comment by mabuge90** [comment]
Hi, I am using MP4Box - GPAC version 1.0.0-rev0-ga99c032b-master.
The ttml file in question can be found at https://dash.akamaized.net/dash264/CTA/imsc1/IT1-T-20171026.ttml

I've uploaded 4 samples + 1 init file:
 it1_ttml_dashinit.mp4
it1_ttml_dash1.m4s
it1_ttml_dash2.m4s
it1_ttml_dash3.m4s
it1_ttml_dash4.m4s

in https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

thanks

**Comment by jeanlf** [comment]
Please use 1.1-DEV (git master) for better TTML import, 1.0 does not support TTML overlaps. I also just added support for multiple div in the TTML importer and exporter.

I also checked the dashing, segments are produced with redundant flag set using latest master.

**Comment by mabuge90** [comment]
Thank you! I will try the Dev branch you suggest
