### ISSUE TITLE
make: *** [ffbuild/common.mak:67: libavfilter/vf_nnedi.o] Error 1

### ISSUE THREAD

**Issue by Madhuraank** [gpac/gpac#1682]
Am compiling and installing FFMPEG  on Raspberry Pi 4
Have installed all the other depnedenices and then I enter the following:

cd ~/ffmpeg_sources && wget -O ffmpeg-snapshot.tar.bz2 https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 && tar xjvf ffmpeg-snapshot.tar.bz2 && cd ffmpeg && PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure   --prefix="$HOME/ffmpeg_build"   --pkg-config-flags="--static"   --extra-cflags="-I$HOME/ffmpeg_build/include"   --extra-ldflags="-L$HOME/ffmpeg_build/lib"   --extra-libs="-lpthread -lm"   --bindir="$HOME/bin"   --enable-gpl   --enable-gnutls      --enable-libass   --enable-libfdk-aac   --enable-libfreetype   --enable-libmp3lame   --enable-libopus   --enable-libsvtav1   --enable-libvorbis   --enable-libvpx   --enable-libx264   --enable-libx265   --enable-nonfree && PATH="$HOME/bin:$PATH" make && make install && hash -r

and at the end am getting the following error,

In file included from libavfilter/vf_mcdeint.c:54:

./libavcodec/avcodec.h:1781:35: note: declared here
   
  attribute_deprecated AVFrame *coded_frame;
                                   ^~~~~~~~~~~

CC	libavfilter/vf_median.o
CC	libavfilter/vf_mergeplanes.o
CC	libavfilter/vf_mestimate.o
CC	libavfilter/vf_midequalizer.o
CC	libavfilter/vf_minterpolate.o
CC	libavfilter/vf_misc_vaapi.o
CC	libavfilter/vf_mix.o
CC	libavfilter/vf_mpdecimate.o
CC	libavfilter/vf_neighbor.o
CC	libavfilter/vf_nlmeans.o
CC	libavfilter/vf_nnedi.o

libavfilter/vf_nnedi.c:819:13: error: conflicting types for ‘read’
 static void read(float *dst, size_t n, const float **data)
             ^~~~

In file included from ./libavutil/timer.h:35,
                 from ./libavutil/internal.h:42,
                 from ./libavutil/common.h:532,
                 from libavfilter/vf_nnedi.c:24:
/usr/include/unistd.h:360:16: note: previous declaration of ‘read’ was here
 extern ssize_t read (int __fd, void *__buf, size_t __nbytes) __wur;
                ^~~~

make: *** [ffbuild/common.mak:67: libavfilter/vf_nnedi.o] Error 1

**Comment by jeanlf** [comment]
please report this to ffmpeg devs
