### ISSUE TITLE
Codec information missing after packaging of HEVC video | DASH | 360 video

### ISSUE THREAD

**Issue by chitragupt** [gpac/gpac#1683]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ x] I looked for a similar issue and couldn't find any.
- [ x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I'm creating MPEG-DASH-SRD content using following guide.
https://github.com/gpac/gpac/wiki/HEVC-Tile-based-adaptation-guide

I have different versions available in DASH content and I'm creating a final video by selecting appropriate quality for particular tile by concatenating the tracks on the base.
MP4Client is playing the final video properly as per my requirement.
But codec information is missing in the metadata.

As per steps in the above mentioned guide codec information is present in the hvc file.

After performing following step codec information is not added in the mp4 video.
MP4Box -add video_tiled.hvc:split_tiles -new video_tiled.mp4

Do I need to follow some other steps which are not mentioned in the guide during the packaging of the video?

**Comment by jeanlf** [comment]
> But codec information is missing in the metadata.

Which meta-data are you refering to ?

If by codec info you mean parameter sets, they are only present on the tile base track, not the tile tracks.

**Comment by chitragupt** [comment]
Codec info is missing for tile base track.

**Comment by jeanlf** [comment]
could you upload your source file and detailed command lines used ?

**Comment by chitragupt** [comment]
Sequence of commands

1.  kvazaar -i input.yuv --input-res 3840x2160 -o output.hvc --tiles 3x3 --slices tiles --mv-constraint frametilemargin --bitrate 128000 --period 30 --input-fps 30
2. MP4Box -add high.hvc:split_tiles -fps 30 -new high_tiled.mp4
3. MP4Box -dash 1000 -profile live -out dash_tiled.mpd high_tiled.mp4

Here's the link for files

https://drive.google.com/file/d/1cnMbOu-So850rnER7vrJkyk8PKMhK9Lv/view?usp=sharing

**Comment by jeanlf** [comment]
`MP4Box -disox high_tiled_dash_track1_init.mp4 -std | grep Param`

shows PPS, SPS and VPS, and `hvcC`is present .

How did you check the 'missing codec info' ?

**Comment by chitragupt** [comment]
I created a output video by concatenating the tracks and segments.
Outtput video is getting  properly in MP4Client.

When I'm trying to calculate psnr value of new video it's showing the following error.

**Decoder (codec none) not found for input stream #0:0**

![decoder not found](https://user-images.githubusercontent.com/20301133/105974717-3127be00-60b4-11eb-9ebd-551c9f640856.png)

command used -> `ffmpeg -i output.mp4 -i sample20.mp4 -filter_complex "psnr" -f null /dev/null`

So I checked the properties of both the videos on /www.metadata2go.com

Original Video Properties 

![sample_video](https://user-images.githubusercontent.com/20301133/105974524-ffaef280-60b3-11eb-90f2-b660a3208c7f.png)

Output Video Properties

![output_video](https://user-images.githubusercontent.com/20301133/105974636-1c4b2a80-60b4-11eb-852b-653742374e45.png)


So if we can observe codec info is missing in the output video.
What might be the reason for this ?

**Comment by jeanlf** [comment]
Codec info is present (check `MP4Box -diso` dump), but I doubt ffmpeg supports HEVC tile tracks and/or hvc2/hev2 packaging.

If you want to calculate the PSNR using ffmpeg, I would suggest to not split the tiles when importing and compute PSNR on the imported result, not the dahsed one.

**Comment by rbouqueau** [comment]
Note that you could compute the PSNR using libavfilter on top of GPAC (given that your GPAC build can decode the stream e.g. ```gpac -play file```):
```gpac -i file1:#ffid=dist:FID=V1 -i file2:#ffid=ref:FID=V2 ffavf:SID=V1,V2::f=[dist][ref]psnr=f=psnr.log @ -o null```

**Comment by chitragupt** [comment]
Hello @rbouqueau  thank you for your suggestion.
I tried that solution but I'm having following error & after that error systems gets stuck and even ctrl + c is not able to terminate the process.

Error
"No filter chain found for PID V1 in filter ffavf to any loaded filters - NOT CONNECTED"

**Comment by rbouqueau** [comment]
@chitragupt Could you share with me your command-line and content (same as above?) so that I can have a look?

**Comment by chitragupt** [comment]
Content is same as above.
And this is the error.

![no filter chain](https://user-images.githubusercontent.com/20301133/106713977-34c1c480-6621-11eb-91c8-7f35d42d5da1.png)

**Comment by rbouqueau** [comment]
What is your command-line for getting these errors?

**Comment by chitragupt** [comment]
The one you suggested me to calculate psnr value 

> gpac -i file1:#ffid=dist:FID=V1 -i file2:#ffid=ref:FID=V2 ffavf:SID=V1,V2::f=[dist][ref]psnr=f=psnr.log @ -o null

**Comment by jeanlf** [comment]
We have a bug in the linker when using FID/SID and the tileagg in this specific setup, I'm investigating it.

Luckily, you don't really need the FID/SID here, so:
```
gpac -i file1:#ffid=dist -i file2:#ffid=ref ffavf::f=[dist][ref]psnr=f=psnr.log @ -o null
```

should work. Make sure your files have the same timescale otherwise psnr filter might not work properly.

**Comment by chitragupt** [comment]
I followed the same steps mentioned in the guide but timebase of the original and new video is different.
Do we have to specify some option during encoding ?

**Comment by jeanlf** [comment]
I'll have a look at automatic rescaling inputs to libavfilter graphs. Meanwhile you can change the timescale:
 - using latest master, in-place rewrite:
 ```MP4Box -add self:rescale=25000 src.mp4```

 - or at import time
 ```MP4Box -add $SRC:rescale=25000 src2.mp4```

**Comment by chitragupt** [comment]
Thank you for your help,it helped a lot.
Also is there a filter in gpac to calculate vmaf ?

**Comment by jeanlf** [comment]
no dedicated filter, but you can use libvmaf in avfilter if your ffmpeg build has vmaf support (check `gpac -h ffavf:libvmaf` exists)

**Comment by chitragupt** [comment]
Hello ,I built my ffmpeg with libvmaf support.I checked `gpac -h ffavf:libvmaf` but it says `No such filter "ffavf:libvmaf"`.

**Comment by rbouqueau** [comment]
@chitragupt Does ```gpac -h ffavf:*``` list VMAF?

PS: doc at https://github.com/gpac/gpac/wiki/ffavf

**Comment by rbouqueau** [comment]
For libvmaf and vmafmotion, see the FFmpeg doc: http://ffmpeg.org/ffmpeg-all.html#toc-vmafmotion

**Comment by chitragupt** [comment]
> @chitragupt Does `gpac -h ffavf:*` list VMAF?
> 
No. It only lists vmafmotion.
I'm using GPAC version 1.0.0-rev188-g2aa266d-master.

**Comment by rbouqueau** [comment]
1) Were you able to use it with your FFmpeg build?
2) Are you sure gpac uses this build (e.g. if you have FFmpeg installed on your system you may want to use LD_LIBRARY_PATH=my_ffmpeg_library_path)

**Comment by chitragupt** [comment]
I tried calculating vmaf with FFmpeg build it's showing the same error as above `codec not found`.

**Comment by rbouqueau** [comment]
What does this give?

```
sudo updatedb
locate libavcodec | fgrep .so
```

**Comment by chitragupt** [comment]
Earlier I used this command to calculate vmaf score of a 360 video
`ffmpeg -i distorted.mp4 -i original.mp4 -filter_complex libvmaf -f null -`

This gave error
`Decoder (codec none) not found for input stream #0:0`

distorted.mp4 is the same output.mp4 file discussed earlier in the discussion(Encoded with h265,Tiled,DASHed).

Earlier I was having same issue while calculating psnr which was resolved using `ffavf`

> What does this give?
> 
> ```
> sudo updatedb
> locate libavcodec | fgrep .so
> ```

This listed bunch of files with .so extension.

**Comment by rbouqueau** [comment]
> This listed bunch of files with .so extension.

I know. I wanted the list ;)

Give me this list instead, it'll go faster to help you:
```
locate libavfilter | fgrep .so | xargs grep libvmaf
```

**Comment by chitragupt** [comment]
![Screenshot from 2021-03-17 14-08-02](https://user-images.githubusercontent.com/20301133/111438661-86826200-872a-11eb-8c00-81b22d6f95fa.png)

**Comment by rbouqueau** [comment]
LD_LIBRARY_PATH=/home/linuxbrew/.linuxbrew/Cellar/ffmpeg/4.3.2-with-options.reinstall/lib/ gpac -h ffavf:*

**Comment by chitragupt** [comment]
Yes it does.

**Comment by rbouqueau** [comment]
Yes

**Comment by rbouqueau** [comment]
Can we close?

**Comment by Saurabh-Dange** [comment]
Yes thank you for your help.This issue is solved.
