### ISSUE TITLE
Problem when creating an MPEG-TS file from a VVC content

### ISSUE THREAD

**Issue by GentleGiant-82** [gpac/gpac#1684]
When trying to encapsulate H.266/VVC content into an MPEG-TS file, there seems to be 2 problems with the output:
1) Access unit delimiter appears without the stop bit (00 00 00 01 00 a1 **a0**), This appears throughout the stream (Gpac adds aud units to every frame)
2) Stream type seems to be off, according to "ISO/IEC 13818-1:2019 DAM 2 Carriage of VVC in MPEG-2 TS", it should be 0x32, whereas GPAC creates 0x33 (And from looking at the source code, it can choose between 0x33 or 0x34)

*) GPAC version used:  1.1.0-DEV-rev499-g3c03581d-master

Steps to reproduce:
1) Download a YUV file
2) Encode several frames by using a reference encoder (verified with VQ analyzer)
3) Pack to .ts file by using:  gpac -i suzie_16_frames.266 m2tsmx:pes_pack=none:first_pts=1000000 @ -o suzie_16_frames_new.ts
4) Observe faulty stream type and access unit delimiter lacking stop bit by viewing hex dump / ts analyzer

Snippet from notepad++:

![image](https://user-images.githubusercontent.com/54882656/107615834-91dafd00-6c55-11eb-84e8-2fd988cb972f.png)

The aud should end with 0xa8, according to the standard. Once this value is manually changed, the analyzer can open the bitstream (Once it's stripped back from .ts to .266, maintaining the aud units)

**Comment by jeanlf** [comment]
Stream type 0x32 is JPEGXS, the DAM text for VVC carriage was wrong and has been fixed in its final stage with VVC stream type is 0x33, VVC temporal sublayer streamtype is 0x34 (as implemented in GPAC).

I will have a look asap at the AUD issue, thanks for reporting it.

**Comment by jeanlf** [comment]
trailing bits for AU delim in VVC and HEVC now fixed, thanks for the report
