### ISSUE TITLE
[NOT A BUG] Prebuilt Android .so libraries

### ISSUE THREAD

**Issue by Duna** [gpac/gpac#1687]
This is not a bug, I just tried to compile on Big Sur using latest NSK21 and NDK12 and got issues like below:
`/Users/duna/Downloads/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lft2`

Can anyone share a link with precompiled mp4box libraries in order to include them in an mp4box_android sample project jni?

**Comment by Duna** [comment]
Or at least tell me what version of NDK is needed to compile them?

**Comment by aureliendavid** [comment]
you can try following this guide https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Android

it uses ndk13b, it should work with other versions but I'm not certain which ones

**Comment by Duna** [comment]
I followed the tutorial  and got into another issue: #1688

**Comment by Duna** [comment]
Just for lazy ones [here](https://mega.nz/file/NR00WKjA#t5D7eqUWF5u37NoUhab28MTfrrzvJVdY8exugK8onM4) there are the android precompiled so files and apk
