### ISSUE TITLE
Android studio 4.1 support and libraries compatibility with Android 10 [text relocations]

### ISSUE THREAD

**Issue by Duna** [gpac/gpac#1689]
The Android project is 10 years old, sadly. The main issue is here: gpac/applications/mp4box_android/jni/ - Android Studio does not recognise this type of project. We need an updated project compatible with latest Android Studio: 4.1 
I managed to compile android libraries folowing the android tutorial on ubuntu 18. This is the list of so files:

```
libeditline.so  libgpac.so   	libjs_osmo.so   libpng.so
libft2.so   	libjpegdroid.so  libopenjpeg.so  libz.so
```

The other issue is the libraries cannot be loaded due to text relocations

**Comment by jeanlf** [comment]
indeed - can you check with the list used for osmo4:
https://github.com/gpac/gpac/blob/master/applications/osmo4_android_studio/app/src/main/java/com/gpac/Osmo4/GPACInstance.java#L66

**Comment by Duna** [comment]
I have created a brand new Android Studio project, with all .so files inside the jniLibs folder, but when do `System.loadLibrary(s)` I got an error:
`dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.enst.mp4box-GEk6uJKmNyOTSkDBbbGtPg==/base.apk"],nativeLibraryDirectories=[/data/app/com.enst.mp4box-GEk6uJKmNyOTSkDBbbGtPg==/lib/x86, /data/app/com.enst.mp4box-GEk6uJKmNyOTSkDBbbGtPg==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "liblibavcodec.so"`
The project can be found [here](https://drive.google.com/file/d/1XMPeDv98ebkHhTEFABF4kc1Oi8Rnc622/view?usp=sharing).

I have replaced the libraries list with:
```
        final String[] toLoad = {"libavcodec", "libavdevice", "libavfilter",
                "libavformat", "libavutil",
                "libeditline", "libfaad", "libft2",
                "libjpegdroid", "libjs_osmo", "libmad", "libopenjpeg",
                "libpng", "libstlport_shared", "libswresample",
                "libswscale", "libz"};
```

**Comment by jeanlf** [comment]
as shown in the quoted example, do not put "lib" prefix in your libs, i.e. use "avcodec" and not "libavcodec"

**Comment by Duna** [comment]
```
        final String[] toLoad = {"avcodec", "avdevice", "avfilter",
                "avformat", "avutil",
                "editline", "faad", "ft2",
                "jpegdroid", "js_osmo", "mad", "openjpeg",
                "png", "stlport_shared", "swresample",
                "swscale", "z"};
``` - I have modified, but swresample does not load

**Comment by Duna** [comment]
It seems libgpac.so is missing for x86, it gets generated only for arm and arm_v7

**Comment by Duna** [comment]
Also this: System.out: Loading library libgpac...
2021-02-25 13:43:45.907 26423-26423/com.enst.mp4box E/linker: "/data/app/~~BXk9ztSoipkJMdbtaI3cfw==/com.enst.mp4box-SvfB-NjbdSVdQ1kn6aJM8A==/lib/x86/libgpac.so" has text ([ relocations](https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23))

**Comment by Duna** [comment]
I am able to compile it, but without x86 architecture because of text relocation issues 
Opened another issue #1691
