### ISSUE TITLE
Running mp4client with a modified openHevc code 

### ISSUE THREAD

**Issue by kjerbi** [gpac/gpac#169]
Hi !
I'm trying to use Gpac on windows with some modifications on the openhevc decoder.
Since there are problems compiling openHevc on windows, I used Linux (ubuntu 14.04 64bits) to compile openHevc with my modifications. Since the compilation generates a .so library I used the scripts from "https://github.com/OpenHEVC/HevcCompilationScripts" to cross-compile and generate libOpenHevcWrapper.dll.

When I moved to windows, I installed win64 Gpac nightly build and I susbstituted the libOpenHevcWrapper.dll by the cross compiled one and I got the following error:
"the program cannot start because libwinpthread-1.dll is missing from your computer. Try reinstalling the program to fix the problem"

1- I my approach to use cross compilation correct? If yes how can I avoid problems related to pthread?
2- If the approach is wrong what can you advice me what to do to have Gpac running with the new openHevc code?

Thank you !

**Comment by rbouqueau** [comment]
I don't know if it helps, but the OpenHEVC team also maintains a FFmpeg repo: https://github.com/OpenHEVC/FFmpeg . It is easier to build from windows directly.

For winpthread, it is a usual issue. Look at the flags we have in our script builder: https://github.com/gpac/zenbuild/blob/master/zen-ffmpeg.sh and https://github.com/gpac/zenbuild/blob/master/zen-libpthread.sh

**Comment by kjerbi** [comment]
Thank you so much for your answer!
Running the ffmpeg projet on windows requires a correct installation of mingw on the machine which is a complicated task that I would like to avoid in a first step. 
Focusing on your scripts, should I understand that I should compile gpac sources on my machine and then enable/disable flags in the scripts?
I compiled the extralibs and I used gpac/trunk/build/msvc11/gpac.sln. I set mp4client as start project and I got several errors (for example: Error	3	error LNK2019: unresolved external symbol _OPENSSL_add_all_algorithms_noconf referenced in function _init_ssl_lib	C:\Users\jerbik\work\GPAC\trunk\build\msvc11\libgpac_static.lib(downloader.obj)	libgpac_dll)

Was it the right way to compile gpac correctly? is there a link to follow (I cannot access the sourceForge link seems to be removed) ?

Thank you so much !

**Comment by rbouqueau** [comment]
Build instructions for windows: http://gpac.io/2011/04/18/command-line-gpac-compiling-on-windows-x86-using-free-microsoft-visual-c/

Actually you don't need to build the full GPAC, just the FFmpeg or libopehevc modules.

> Running the ffmpeg projet on windows requires a correct installation of mingw on the machine which is a complicated task that I would like to avoid in a first step. 

Install MSYS2. It is a shell with a package manager. It is easy.

**Comment by kjerbi** [comment]
Hi and thank you again for your answers!
The build instructions for windows are exactly what I used when I tried to compile Gpac. The compilation errors I got may be the result of several changes in the source code because the link of instructions and the msvc build projects were not updated since 2 years.
Concerning the compilation of ffmpeg with msys2, I installed the tool and I added the mingw64/bin and msys64/usr/bin to my path but when I use the ./configure I got the following error:
"cl is unable to create an executable file.If cl is a cross-compiler, use the --enable-cross-compile option. Only do this if you know what cross compiling means.C compiler test failed."
Is there other thing to do to correctly configure msys for a successful compilation?

trying to use gpac on ubuntu 14.04, I found the following specification in the nightly builds "For Ubuntu >= 11.04 users : the libavutil49 package has been removed, please download it " but the link returns error. 
So currently, I connot build ffmpeg and gpac on windows neither on linux!

**Comment by rbouqueau** [comment]
Could you point where the Windows build fails so that we update the build instructions? Thanks.

For Ubunu 14.04, are you saying that this section is incorrect? http://gpac.io/2011/04/20/compiling-gpac-on-ubuntu/#Ubuntu 14.04

I'd be happy to fix them all if they are incorrect. Also we plan to provide a package script to build the dependencies from scratch in a friendly manner.

**Comment by kjerbi** [comment]
Hi again!
"For Ubunu 14.04, are you saying that this section is incorrect? http://gpac.io/2011/04/20/compiling-gpac-on-ubuntu/#Ubuntu 14.04" => I resolved the problems on my machine. You ca

**Comment by kjerbi** [comment]
Hi again!
"For Ubunu 14.04, are you saying that this section is incorrect? http://gpac.io/2011/04/20/compiling-gpac-on-ubuntu/#Ubuntu 14.04" => I resolved the problems on my machine. The installation of libjack0 is not automatic, you can add the instruction "sudo apt-get install libjack0" before the instruction to install dependencies. Once the dependencies installed, there are some functions to remove from the ffmpeg_demux.c (av_find_stream_info, av_close_input_file, av_open_input_stream) and the compilation is OK.
now back to my initial request, I have some changes applied on the hevc.c file in the openhevc project and I want gpac to take them in consideration. Can you please give instructions to update gm_openhevc_dec.so and gm_ffmpeg_in.so with these changes?


"Could you point where the Windows build fails so that we update the build instructions? Thanks." I'll give you a feedback with detailed report of the errors I got on windows"

Thank you again for all your answers !

**Comment by mraulet** [comment]
you need to install openhevc then gpac configure should detect it automatically.

**Comment by kjerbi** [comment]
oh nice it works (at least in linux)
thank you all guys !
