### ISSUE TITLE
Failed to get libmp4box.so compiled for Android

### ISSUE THREAD

**Issue by Duna** [gpac/gpac#1690]
I have followed the tutorial from:
https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Android
I have successfully built for NDK:
`<GPAC_ROOT_DIR>/deps_android/build/android$ ./gpac_build_all_extra_libs /opt/android-ndk` having the following .so libs compiled:
```
duna@duna-VirtualBox:~/gpac_public/extra_lib/lib/android/armeabi$ ls
libavcodec.so   libavformat.so  libfaad.so   	libjs_osmo.so   libpng.so         	libswscale.so
libavdevice.so  libavutil.so	libft2.so    	libmad.so   	libstlport_shared.so  libz.so
libavfilter.so  libeditline.so  libjpegdroid.so  libopenjpeg.so  libswresample.so
```

The main issue is I do not manage to get libmp4box.so compiled file on Android. 
I executed the command line:
`<GPAC_ROOT_DIR>/gpac_public/build/android/jni$ ./gpac_build_android -ndk=/opt/android-ndk -sdk=/opt/android-sdk -jdk=/usr/lib/jvm/java-8-openjdk-amd64 -force_rebuild`

Built the library for armeabi but the output is:
```
duna@duna-VirtualBox:~/gpac_public/applications/mp4box_android/libs/armeabi$ ls
libeditline.so  libgpac.so   	libjs_osmo.so   libpng.so
libft2.so   	libjpegdroid.so  libopenjpeg.so  libz.so
```

**Comment by Duna** [comment]
How can I get the libmp4box.so compiled for Android?

**Comment by aureliendavid** [comment]
libmp4box doesn't exist, the main library is libgpac

mp4box and osmo4 are programs that both use libgpac to do different things
