### ISSUE TITLE
Audio track name change did not apply

### ISSUE THREAD

**Issue by Cyb3rd3crypti0n** [gpac/gpac#1694]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hello everybody,

I tried to change the language and name of audio tracks using mp4box (–lang 2=Eng -name 2="Surround 5.1").
The tool does indeed set the language but the track name stays the same (title0). Did I do something wrong, is it the tools fault or is it simply not possible to change names in mp4box. 

Edit: For my desired use case I can't use ffmpeg (or at least it won't work with the video codec)...

**Comment by jeanlf** [comment]
`-name` / `:name` modifies the handler name of the track, but this does not mean the tool you use to inspect uses this handle name. You can check this was properly set using `MP4Box -info 1 file.mp4` to print the track handler.

There is no official way to name a track in isobmff, it is usually up to specs using the format to define this...

You can try to tag the file, but the tag info is at the moov level, not per track.
