### ISSUE TITLE
Create DASH with multiple renditions from single mp4 file

### ISSUE THREAD

**Issue by psytechno604** [gpac/gpac#1696]
I need to create DASH with multiple renditions. As a source I have some (mostly random) video files. The algorithm is as follows:

1) Create MP4 file from source:
`ffmpeg -y -i r207997.mov -movflags +faststart -force_key_frames expr:gte(t,n_forced*0.96) -map 0:v:0 -c:v:0 libx264 -preset:v:0 ultrafast -r:v:0 25.000 -s:v:0 960x540 -level:v:0 3.0 -b:v:0 1800000 -minrate:v:0 1440000 -maxrate:v:0 2160000 -bufsize:v:0 3240000 -profile:v:0 main -bf:v:0 1 -b_strategy:v:0 0 -sc_threshold:v:0 0 -pix_fmt:v:0 yuv420p -map 0:v:0 -c:v:1 libx264 -preset:v:1 ultrafast -r:v:1 25.000 -s:v:1 1280x720 -level:v:1 4.0 -b:v:1 3584000 -minrate:v:1 2867200 -maxrate:v:1 4300800 -bufsize:v:1 6451200 -profile:v:1 high -bf:v:1 1 -b_strategy:v:1 0 -sc_threshold:v:1 0 -pix_fmt:v:1 yuv420p -map 0:v:0 -c:v:2 libx264 -preset:v:2 ultrafast -r:v:2 25.000 -s:v:2 1920x1080 -level:v:2 4.0 -b:v:2 8000000 -minrate:v:2 6400000 -maxrate:v:2 9600000 -bufsize:v:2 14400000 -profile:v:2 high -bf:v:2 1 -b_strategy:v:2 0 -sc_threshold:v:2 0 -pix_fmt:v:2 yuv420p intermediate-video.mp4`

`ffmpeg -y -i r207997.mov -map 0:a:0 -c:a:0 libfdk_aac -profile:a:0 aac_he -b:a:0 128000 /mnt/nemo-ssai-shared/r207997.mov/intermediate-audio.mp4`

(I need separate audio and video for some other reasons)

2) Package to DASH:
`MP4Box -dash 1920 -frag 1920 -rap -bs-switching no intermediate-video.mp4#trackID=1 intermediate-video-1.mp4#trackID=2 intermediate-video-2.mp4#trackID=3 intermediate-audio.mp4#trackID=1 -single-file -single-segment -out output/manifest.mpd`

you see there - intermediate-video-1.mp4, intermediate-video-2.mp4 - they should be either symlinks or copies of intermediate-video.mp4 - otherwise it just doesn't work and the result contains only 1 rendition. I just cannot use the same file! It was not a problem with symlinks, but now we moved to the NFS storage and they are not an option anymore. Copying the file is too slow.

Is there a way to use one source mp4 file to get multiple renditions in the manifest?

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ v ] I looked for a similar issue and couldn't find any.
- [ v ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ v ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
If you mean use different adaptation sets for your files, specify `:asID`, eg

`MP4Box -dash 1000 src.mp4:asID=1 src.mp4:asID=2 -profile live -out dash/live.mpd`

**Comment by Murmur** [comment]
Use v1.mp4 two times, writes separate `<AdaptationSet>` elements for video tracks. This is fine.
```
MP4Box \
  -dash 384000 -frag 384000 -dash-scale 48000 -closest -mem-frags -rap \
  -profile "dashif.ll" -profile-ext "urn:hbbtv:dash:profile:isoff-live:2012" \
  -bs-switching no \
  -sample-groups-traf -single-traf --tfdt64 --tfdt_traf --noroll=yes -subsegs-per-sidx 0 \
  -segment-name "$RepresentationID$/$Number$$Init=i$" -out "manifest.mpd" \
  "temp-v1.mp4#trackID=1:id=v1:period=p0:asID=1:dur=32" \
  "temp-v1.mp4#trackID=1:id=v2:period=p0:asID=2:dur=32" \
  "temp-a1.mp4#trackID=1:id=a1:period=p0:asID=11:dur=32"
```

Use v1.mp4 two times, writes one `<AdaptationSet>` with multiple `<Representation>` elements for video tracks. This is fine.
```
MP4Box \
  -dash 384000 -frag 384000 -dash-scale 48000 -closest -mem-frags -rap \
  -profile "dashif.ll" -profile-ext "urn:hbbtv:dash:profile:isoff-live:2012" \
  -bs-switching no \
  -sample-groups-traf -single-traf --tfdt64 --tfdt_traf --noroll=yes -subsegs-per-sidx 0 \
  -segment-name "$RepresentationID$/$Number$$Init=i$" -out "manifest.mpd" \
  "temp-v1.mp4#trackID=1:id=v1:period=p0:asID=1:dur=32" \
  "temp-v1.mp4#trackID=1:id=v2:period=p0:asID=1:dur=32" \
  "temp-a1.mp4#trackID=1:id=a1:period=p0:asID=11:dur=32"
```

ps: you may ignore `dur=32` timelimit argument and other not always mandatory flags.

**Comment by psytechno604** [comment]
> Use v1.mp4 two times, writes one `<AdaptationSet>` with multiple `<Representation>` elements for video tracks. This should work ok.
> 
> ```
> MP4Box \
>   -dash 384000 -frag 384000 -dash-scale 48000 -closest -mem-frags -rap \
>   -profile "dashif.ll" -profile-ext "urn:hbbtv:dash:profile:isoff-live:2012" \
>   -bs-switching no \
>   -sample-groups-traf -single-traf --tfdt64 --tfdt_traf --noroll=yes -subsegs-per-sidx 0 \
>   -segment-name "$RepresentationID$/$Number$$Init=i$" -out "manifest.mpd" \
>   "temp-v1.mp4#trackID=1:id=v1:period=p0:asID=1:dur=32" \
>   "temp-v1.mp4#trackID=1:id=v2:period=p0:asID=1:dur=32" \
>   "temp-a1.mp4#trackID=1:id=a1:period=p0:asID=11:dur=32"
> ```
> 
> ps: you may ignore `dur=32` timelimit argument and other not always mandatory flags.

yes, description is like what I need, but in the end manifest is invalid (at least I don't see necessary renditions there):

`<?xml version="1.0"?>

<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H0M15.105S" maxSubsegmentDuration="PT0H0M1.920S" profiles="urn:mpeg:dash:profile:full:2011">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>manifest.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period id="p0" duration="PT0H0M15.105S">
  <AdaptationSet id="1" segmentAlignment="true" maxWidth="1920" maxHeight="1080" maxFrameRate="25" par="16:9" lang="eng" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
   <ContentComponent id="1" contentType="video"/>
   <ContentComponent id="3" contentType="video"/>
   <ContentComponent id="2" contentType="video"/>
   <Representation id="v1" mimeType="video/mp4" codecs="avc1.4D401E,avc1.4D4028" width="960" height="540" frameRate="25" sar="1:1" bandwidth="1770649">
    <BaseURL>all-in-one_track2__dashinit.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="2187-2326">
     <Initialization range="0-2170"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
  <AdaptationSet id="11" segmentAlignment="true" lang="pol" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
   <Representation id="a1" mimeType="audio/mp4" codecs="mp4a.40.5" audioSamplingRate="48000" bandwidth="128350">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <BaseURL>all-in-one_track4__dashinit.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="929-1068">
     <Initialization range="0-912"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>`


and what I want to achieve is:
`<?xml version="1.0"?>

<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H0M15.105S" maxSegmentDuration="PT0H0M0.960S" profiles="urn:hbbtv:dash:profile:isoff-live:2012,urn:dvb:dash:profile:dvb-dash:2014,urn:dvb:dash:profile:dvb-dash:isoff-ext-on-demand:2014">
    <ProgramInformation moreInformationURL="http://gpac.io">
        <Title>manifest.mpd generated by GPAC</Title>
    </ProgramInformation>
    <Period duration="PT0H0M15.105S">
        <AdaptationSet segmentAlignment="true" maxWidth="1920" maxHeight="1080" maxFrameRate="25" par="16:9" lang="eng" bitstreamSwitching="true" startWithSAP="1">
            <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
            <SegmentTemplate initialization="intermediate-video_dash.mp4">
                <SegmentTimeline>
                    <S t="0" d="46080" r="14"/>
                    <S d="28800"/>
                </SegmentTimeline>
            </SegmentTemplate>
            <Representation id="1" mimeType="video/mp4" codecs="avc1.4D401E" width="960" height="540" frameRate="25" sar="1:1" scanType="progressive" bandwidth="1770445">
                <SegmentTemplate media="intermediate-video_dash$Time$.m4s" timescale="48000" startNumber="1" duration="1920"/>
            </Representation>
            <Representation id="2" mimeType="video/mp4" codecs="avc1.4D4028" width="1280" height="720" frameRate="25" sar="1:1" scanType="progressive" bandwidth="3497007">
                <SegmentTemplate media="___duration_issue___1-intermediate-video-1_dash$Time$.m4s" timescale="48000" startNumber="1" duration="1920"/>
            </Representation>
            <Representation id="3" mimeType="video/mp4" codecs="avc1.4D4028" width="1920" height="1080" frameRate="25" sar="1:1" scanType="progressive" bandwidth="7835424">
                <SegmentTemplate media="___duration_issue___1-intermediate-video-2_dash$Time$.m4s" timescale="48000" startNumber="1" duration="1920"/>
            </Representation>
        </AdaptationSet>
        <AdaptationSet segmentAlignment="true" lang="pol" startWithSAP="1">
            <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
            <SegmentTemplate media="intermediate-audio_dash$Time$.m4s" initialization="intermediate-audio_dashinit.mp4" timescale="48000" startNumber="1">
                <SegmentTimeline>
                    <S t="0" d="2048" r="352"/>
                    <S d="2114"/>
                </SegmentTimeline>
            </SegmentTemplate>
            <Representation id="4" mimeType="audio/mp4" codecs="mp4a.40.5" audioSamplingRate="48000" scanType="progressive" bandwidth="128350">
                <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
            </Representation>
        </AdaptationSet>
    </Period>
</MPD>`

- the only way to do it is to use symlinks (as for now). So, you may count this as a feature request...

**Comment by jeanlf** [comment]
I think your command line is wrong, could you post it ?

Using master and:

`MP4Box -dash 1000 -frag 1000 -profile onDemand temp-v1.mp4#trackID=1:id=v1 temp-v1.mp4#trackID=1:id=v2 temp-v1.mp4#trackID=1:id=v3 temp-a1.mp4#trackID=1:id=a1 -segment-name "\$RepresentationID\$/\$Init=i\$" -out result/manifest.mpd`

the manifest looks like:
```
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 1.1.0-DEV-rev652-gd06c6e3b5-master at 2021-03-31T13:23:10.776Z -->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H0M30.000S" maxSubsegmentDuration="PT0H0M1.022S" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>manifest.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H0M30.000S">
  <AdaptationSet segmentAlignment="true" maxWidth="1280" maxHeight="720" maxFrameRate="25" par="16:9" lang="und" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
   <Representation id="v1" mimeType="video/mp4" codecs="avc1.64001F" width="1280" height="720" frameRate="25" sar="1:1" bandwidth="445328">
    <BaseURL>v1/i.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="927-1318">
     <Initialization range="0-862"/>
    </SegmentBase>
   </Representation>
   <Representation id="v2" mimeType="video/mp4" codecs="avc1.64001F" width="1280" height="720" frameRate="25" sar="1:1" bandwidth="445328">
    <BaseURL>v2/i.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="927-1318">
     <Initialization range="0-862"/>
    </SegmentBase>
   </Representation>
   <Representation id="v3" mimeType="video/mp4" codecs="avc1.64001F" width="1280" height="720" frameRate="25" sar="1:1" bandwidth="445328">
    <BaseURL>v3/i.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="927-1318">
     <Initialization range="0-862"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" lang="und" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
   <Representation id="a1" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="44100" bandwidth="64008">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="1"/>
    <BaseURL>a1/i.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="786-1177">
     <Initialization range="0-721"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```

**Comment by psytechno604** [comment]
yes, found a mistake - was "v1" everywhere without "v2" "v3" etc.
now the next "problem" (or it is not a problem?) is that value in <Initialization range="0-978"/> is different for each representation, whereas the source file has exact the same lengths of audio and video tracks:

```xml
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 1.1.0-DEV-rev458-g8d9aeb5fc-master at 2021-03-31T13:26:40.241Z -->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H0M15.105S" maxSubsegmentDuration="PT0H0M1.920S" profiles="urn:mpeg:dash:profile:full:2011">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>manifest.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period id="p0" duration="PT0H0M15.105S">
  <AdaptationSet id="1" segmentAlignment="true" maxWidth="1920" maxHeight="1080" maxFrameRate="25" par="16:9" lang="eng" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
   <Representation id="v1" mimeType="video/mp4" codecs="avc1.4D401E" width="960" height="540" frameRate="25" sar="1:1" bandwidth="1770649">
    <BaseURL>all-in-one_track3__dash_rep1init.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="996-1135">
     <Initialization range="0-979"/>
    </SegmentBase>
   </Representation>
   <Representation id="v2" mimeType="video/mp4" codecs="avc1.4D4028" width="1280" height="720" frameRate="25" sar="1:1" bandwidth="3497007">
    <BaseURL>all-in-one_track3__dash_rep2init.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="994-1133">
     <Initialization range="0-977"/>
    </SegmentBase>
   </Representation>
   <Representation id="v3" mimeType="video/mp4" codecs="avc1.4D4028" width="1920" height="1080" frameRate="25" sar="1:1" bandwidth="7833026">
    <BaseURL>all-in-one_track3__dash_rep3init.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="995-1134">
     <Initialization range="0-978"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
  <AdaptationSet id="11" segmentAlignment="true" lang="pol" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
   <Representation id="a1" mimeType="audio/mp4" codecs="mp4a.40.5" audioSamplingRate="48000" bandwidth="128350">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <BaseURL>all-in-one_track4__dashinit.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="929-1068">
     <Initialization range="0-912"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```

**Comment by jeanlf** [comment]
It's not a problem, it just means the ftyp+moov size are different, either because the sources are different or because of some parameters in your command line.

**Comment by psytechno604** [comment]
the source: https://r.dcs.redcdn.pl/file/o2/TVN-Adserver/ATV_ingestion/r215688.mov


intermediate mp4 file: https://httpinterediate.blob.core.windows.net/source/all-in-one.mp4

**Comment by psytechno604** [comment]
Also... mediaPresentationDuration="PT0H0M15.105S" - but in the intermediate file all the streams have exactly the same duration - 15 sec, not 15.1 sec. This means that if I want to combine the periods to the multiperiod DASH - it will stop playing after first period.

**Comment by jeanlf** [comment]
For DVB you need to set the profiles (eg `-profile-ext urn:dvb:dash:profile:dvb-dash:2014`)and role for audio (eg `:id=a1:period=p0:asID=1:role=main`). We still have an open issue on DVB signaling (#635), feel free to contribute there.

The mismatch in period duration was due to presence of edit lists in audio tracks, now patched - thanks for the report/files.

**Comment by psytechno604** [comment]
so I need to update to fix the duration, right?

**Comment by jeanlf** [comment]
yes, or patch the MPD

**Comment by psytechno604** [comment]
thank you very much!

**Comment by psytechno604** [comment]
@jeanlf I have upgraded from 1.1.0-DEV-rev489-g8f22c66e0-master to 1.1.0-DEV-rev661-gf740a0efb-master and it seems that it cannot produce playable dash in some cases.

this is the source file - https://httpinterediate.blob.core.windows.net/source/intermediate-singleDASH.mp4

```
MP4Box -dash 1920 -frag 1920 -rap -bs-switching no \
/mnt/nemo-ssai-shared/93d6ba20-0aa0-5c89-a2fb-e3b60ce7430a/intermediate.mp4#trackID=1:id=v1:period=p0:asID=1 \
/mnt/nemo-ssai-shared/93d6ba20-0aa0-5c89-a2fb-e3b60ce7430a/intermediate.mp4#trackID=2:id=v2:period=p0:asID=1 \
/mnt/nemo-ssai-shared/93d6ba20-0aa0-5c89-a2fb-e3b60ce7430a/intermediate.mp4#trackID=3:id=v3:period=p0:asID=1 \
/mnt/nemo-ssai-shared/93d6ba20-0aa0-5c89-a2fb-e3b60ce7430a/intermediate.mp4#trackID=4:id=a1:period=p0:asID=2:role=main \
-single-file -single-segment -out /mnt/nemo-ssai-shared/93d6ba20-0aa0-5c89-a2fb-e3b60ce7430a/output/manifest.mpd
```

rev.661 output: https://r.dcs.redcdn.pl/file/o2/TVN-Adserver/Nowtilus_ingestion/dashttest/output661/manifest.mpd (does not play)

rev.489 output: https://r.dcs.redcdn.pl/file/o2/TVN-Adserver/Nowtilus_ingestion/dashttest/output489/manifest.mpd (playback ok)
