### ISSUE TITLE
DASHer: compute average bitrate when no bitrate pid property

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#1698]
In case the 'btrt' (or equivalent) is missing, GPAC emits this warning:
```
[Dasher] No bitrate property assigned to PID output.mp4, defaulting to 1Mbps
        Try specifying bitrate property after your source, e.g. -i source.raw:#Bitrate=VAL
```

Since most contents don't contain this information, this is a regression for most users. I propose we recompute a bitrate when missing. @jeanlf proposes to add this in the isobmff demuxer.

The bitrate cannot be reliably estimated until a sufficient amount of data is available. This could be an issue with low latency: in this case the manifest is written once one packet for input stream was received.

**Comment by jeanlf** [comment]
Bitrate is computed for ISOBMFF inputs even when no `btrt` box.

The issue however applies to sources not exposing a bitrate (raw sources not transcoded, M2TS), will patch ASAP.
