### ISSUE TITLE
Remove SEI messages in-place?

### ISSUE THREAD

**Issue by Android-X13** [gpac/gpac#1699]
Hello,

- I can remove SEI messages in a H264 bitstream upon extracting it:

    `gpac -i input.mp4#video rfnalu:nosei @ -o raw.264`

- I can also remove SEI messages upon importing a raw stream directly:

    `mp4box -add raw.264:nosei -new output.mp4`

- I can't remove SEI messages upon importing a stream from an existing .mp4 container, with mp4box (I get no errors but `nosei` option is ignored):
    ```
    mp4box -add input.mp4:nosei -new output.mp4
    mp4box -add input.mp4#video:nosei -new output.mp4
    ```

- I can't remove SEI units in-place by using the "self" mode with mp4box (`nosei `option is not marked with an "S" in the [documentation](https://github.com/gpac/gpac/wiki/mp4box-import-opts), which if I understand correctly means it cannot be used in this mode, but as a side note I can't use "self" mode with any option at all, even with the example in the docs, I always get `[Importer] Cannot load filter for input file "self"`)

    `mp4box -add self:nosei src.mp4`

- I can however remove the SEI upon importing a stream from an existing .mp4 container with gpac:

    `gpac -i input.mp4#video rfnalu:nosei @ -o output.mp4`

How can I remove SEI messages in-place (if even possible)?

In the last command how can I apply the rfnalu filter to a video stream but also passthrough/stream-copy all other tracks to the output file? The above only adds the video stream to output.mp4.

**Comment by jeanlf** [comment]
The simplest way is to use the [bsrw](https://github.com/gpac/gpac/wiki/bsrw) filter.

```gpac -i source.mp4 bsrw:rmsei @ -o nosei.mp4```

or

```MP4Box -add source.mp4:@bsrw:rmsei -new nosei.mp4```

I just fixed the `bsrw` filter to work in pass-through for non-handled codecs to avoid writing complex chains to keep all media, make sure you use the latest master.

A lot of import options (inc. `nosei`) are not used when importing a ISOBMFF but only when importing the raw bitstream, I'll try to update the doc / console feedback to warn users.

**Comment by Android-X13** [comment]
Thank you @jeanlf. I wasn't aware of bsrw filter

**Comment by jeanlf** [comment]
FYI I just patched the code to throw warnings for import options not support in case of isobmf source
