### ISSUE TITLE
[MP4Box] Import options are not working in Self mode

### ISSUE THREAD

**Issue by Android-X13** [gpac/gpac#1700]
I can't use any import option in Self mode with mp4box. I've tried several options that are marked with an `S` in the [documentation](https://github.com/gpac/gpac/wiki/mp4box-import-opts)

Example from the docs:

`MP4Box -add self:moovts=-1:noedit src.mp4`

Gives me the following:

`[Importer] Cannot load filter for input file "self"`

Is this faulty behavior or am I doing something wrong?

**Comment by jeanlf** [comment]
Are you sure of your version of MP4Box ? The output here gives:

>Option noedit not available for self-reference import
>Error importing self:moovts=-1:noedit: Bad Parameter

(I'll add noedit as a `self` option btw)

**Comment by Android-X13** [comment]
I'm trying this on a Windows machine right now using a pre-compiled binary from GPAC website

`MP4Box - GPAC version 1.0.1-rev0-gd8538e8a-master`

No import option that's marked with an `S` works for me:

`MP4Box -add self#1:name=test src.mp4`

`[Importer] Cannot load filter for input file "self"`

**Comment by jeanlf** [comment]
you need 1.1-dev version (get a nightly build), `self` has been added just recently.

**Comment by Android-X13** [comment]
> `self` has been added just recently.

Sorry didn't know that, OK.

**Comment by Android-X13** [comment]
Self mode importing works in nightly build
