### ISSUE TITLE
DEV: Error demuxing audio with mp4box, dev1.1.0 since rev506, Windows x64

### ISSUE THREAD

**Issue by 44vince44** [gpac/gpac#1707]
Hello all GPAC Coders and Contributors,

Platform: Win10 x64
Release of GPAC where the bug has been observed : since at least dev1.1.0 rev506. tested also 587 and 588 (latest today)
Release known to be working: dev1.1.0 rev447

## Description of the bug
A certain file that can be demuxed with previous versions of Mp4box can not be demuxed anymore, with an error (see below).

## link to the file 
https://www.mediafire.com/file/w4589c5dhn4nivl/DJI_0136.rar/file

## Command line used
"C:\Program Files\StaxRip\Apps\Support\MP4Box\MP4Box.exe" -single 2 -out "C:\Temp\_StaxRip\DJI_0136_temp\ID1 English {DJI.AAC}.m4a" "D:\Downloads\_IDM Downloads\DJI_0136.MP4"

## Error description
[isom] invalid tag size in Xtra !
[isom] not enough bytes in box Xtra: 177 left, reading 536576 (file ..\..\src\isomedia\box_code_base.c, line 12440)
[iso file] Read Box "Xtra" (start 90900445) failed (Invalid IsoMedia File) - skipping
[iso file] Read Box "udta" (start 90900043) failed (Invalid IsoMedia File) - skipping
[iso file] Read Box "moov" (start 90899927) failed (Invalid IsoMedia File) - skipping
Error opening file D:\Downloads\_IDM Downloads\DJI_0136.MP4: Invalid IsoMedia File

**Comment by jeanlf** [comment]
you're right, `Xtra` parsing is not fully tested yet. Thanks for the file, code is now patched to avoid aborting if `Xtra` fails, will look into why this fails later.

**Comment by Patman86** [comment]
Thx for the fast support 😁

**Comment by 44vince44** [comment]
yes, many,many thanks!! 👍🏼
