### ISSUE TITLE
QA of HEVC encoded 360 video | VMAF | PSNR

### ISSUE THREAD

**Issue by chitragupt** [gpac/gpac#1713]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
-  #[X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I'm working on 360 videos using MPEG-DASH-SRD.
Details about my work are discussed in issue #1683.

I'm trying to compute VMAF and PSNR for 360 videos. For which I used avfilter with libvmaf. 
When I calculated vmaf I got 0 vmaf score for most of the frames.I have attached the log for the same.
I'm not sure if there's some issue with my video or I'm calculating vmaf in wrong way.

I used following command.
`gpac -i original.mp4:#ffid=dist -i distorted.mp4:#ffid=ref ffavf::f=[dist][ref]libvmaf=log_path=libvmaf.log @ -o null`

vmaf score 
[libvmaf.log](https://github.com/gpac/gpac/files/6181668/libvmaf.log)

https://user-images.githubusercontent.com/20301133/111981307-81a81e80-8b2d-11eb-84ff-7aad54f850a3.mp4

https://user-images.githubusercontent.com/20301133/111981319-85d43c00-8b2d-11eb-9654-a9d55efcb81a.mp4

This second video (distorted.mp4) can be played with only mp4client,if there's a way to make it compatible with every other video player please let me know.

Also I wanted to calculate psnr and ssim score along with the vmaf for which I used following command but I just got the vmaf score.
`gpac -i original.mp4:#ffid=dist -i distorted.mp4:#ffid=ref  ffavf::f=[dist][ref]libvmaf=log_path=libvmaf.log::psnr=true=log_path=psnr.log @ -o null`

**Comment by rbouqueau** [comment]
> gpac -i original.mp4:#ffid=dist -i distorted.mp4:#ffid=ref ffavf::f=[dist][ref]libvmaf=log_path=libvmaf.log @ -o null

I think that's the first time someone's doing this with GPAC filters. In order to make it work, could you tell us what the equivalent ffmpeg command-line does?

> but I just got the vmaf score

As well as a gpac warning I guess. You need to instantiate two ffavf filters e.g. ```gpac -i original.mp4:#ffid=dist -i distorted.mp4:#ffid=ref ffavf::f=[dist][ref]libvmaf=log_path=libvmaf.log ffavf::psnr=true=log_path=psnr.log @ -o null @2 -o null```.

**Comment by jeanlf** [comment]
## Tile track HEVC to single track

```
% gpac -i distorted.mp4 tileagg @ -o distorted_st.mp4
% MP4Box -tracks distorted_st.mp4
1
```


## Using libvmaf

Using latest git from libvmaf and ffmpeg - first try here, I may be missing a few things. 
Rebuild everything (libvmaf, ffmpeg and gpac), after build check

```
% gpac -hx ffavf:* | grep libvmaf 
ffavf:libvmaf
```

Basic ffmpeg test:

```ffmpeg -i distorted_st.mp4 -i original.mp4 -filter_complex "[0][1]libvmaf=log_fmt=xml:log_path=/dev/stdout:model_path=$PATH_TO_MODELS/vmaf_v0.6.1.json" -f null -```

GPAC equivalent:

```gpac -i distorted_st.mp4:#ffid=dist -i original.mp4:#ffid=ref "ffavf::f=[dist][ref]libvmaf=log_fmt=xml:log_path=/dev/stdout:model_path=/usr/local/share/model/vmaf_v0.6.1.json" @ -o null```

And using directly the tiled track version (using `-graph` to make sure the connections are as expected):


```gpac -i distorted.mp4:#ffid=dist -i original.mp4:#ffid=ref "ffavf::f=[dist][ref]libvmaf=log_fmt=xml:log_path=/dev/stdout:model_path=/usr/local/share/model/vmaf_v0.6.1.json" @ -o null -graph```

The graph will show that `tileagg`filter is used, and its only output is connected to `ffavf`, along with the original video:

```
Filters connected:
fin (src=distorted.mp4:#ffid=dist) (ptr=0x7feee440cc60)
-(PID distorted.mp4) mp4dmx (ptr=0x7feee6005240)
--(PID V1) tileagg (ptr=0x7feee6049600)
---(PID V1) vtbdec "VTB:Hardware:HEVC" (ptr=0x7feee6049d80)
----(PID V1) ffavf (:f=[dist][ref]libvmaf=log_fmt=xml:log_path=/dev/stdout:model_path=/usr/local/share/model/vmaf_v0.6.1.json) (ID=_0x7feee4416960_)
-----(PID V1) fout (dst=null) (ptr=0x7feee60041f0)
--(PID V2) tileagg (ptr=0x7feee6049600)
--(PID V3) tileagg (ptr=0x7feee6049600)
--(PID V4) tileagg (ptr=0x7feee6049600)
--(PID V5) tileagg (ptr=0x7feee6049600)
--(PID V6) tileagg (ptr=0x7feee6049600)
--(PID V7) tileagg (ptr=0x7feee6049600)
--(PID V8) tileagg (ptr=0x7feee6049600)
--(PID V9) tileagg (ptr=0x7feee6049600)
--(PID V10) tileagg (ptr=0x7feee6049600)
--(PID V11) tileagg (ptr=0x7feee6049600)
--(PID V12) tileagg (ptr=0x7feee6049600)
--(PID V13) tileagg (ptr=0x7feee6049600)
--(PID V14) tileagg (ptr=0x7feee6049600)
--(PID V15) tileagg (ptr=0x7feee6049600)
--(PID V16) tileagg (ptr=0x7feee6049600)
--(PID V17) tileagg (ptr=0x7feee6049600)
--(PID V18) tileagg (ptr=0x7feee6049600)
--(PID V19) tileagg (ptr=0x7feee6049600)
--(PID V20) tileagg (ptr=0x7feee6049600)
--(PID V21) tileagg (ptr=0x7feee6049600)
--(PID V22) tileagg (ptr=0x7feee6049600)
--(PID V23) tileagg (ptr=0x7feee6049600)
--(PID V24) tileagg (ptr=0x7feee6049600)
--(PID V25) tileagg (ptr=0x7feee6049600)
--(PID V26) tileagg (ptr=0x7feee6049600)
fin (src=original.mp4:#ffid=ref) (ptr=0x7feee4416620)
-(PID original.mp4) mp4dmx (ptr=0x7feee6006260)
--(PID V1) vtbdec "VTB:Hardware:AVC|H264" (ptr=0x7feee6050220)
---(PID V1) ffavf (:f=[dist][ref]libvmaf=log_fmt=xml:log_path=/dev/stdout:model_path=/usr/local/share/model/vmaf_v0.6.1.json) (ID=_0x7feee4416960_)

```


Hope this helps!

**Comment by Saurabh-Dange** [comment]
Hello Thank You for your detailed solution.
I tried these steps and I'm having following error.
![vmaf_error](https://user-images.githubusercontent.com/20301133/112717733-88aba400-8f14-11eb-92d0-d68ae2bbf8a4.png)

I checked for model path and there is no json file there.That folder only have .pkl and .model files.
![vmaf_model_dir](https://user-images.githubusercontent.com/20301133/112717791-d0cac680-8f14-11eb-9375-9942c2d077cd.png)

**Comment by rbouqueau** [comment]
The error message says to "check logs for details". What do log say?

Please post answers as text whenever possible.

**Comment by Saurabh-Dange** [comment]
Hello,
log output was set to /dev/stdout/
So I got the following error
`[FFAVF] Fail to pull frame from filtergaph: Invalid argument`

I updated the model path to 
`/usr/local/share/model/vmaf_v0.6.1.pkl`

I got the vmaf score output as follows

`<fyi numOfFrames="999" aggregateVMAF="0.656749" execFps="32.8719" timeTaken="30.3907" />`

But in this case I have 30 fps video of 20 seconds so I just have 600 frames,but for some reason vmaf is getting calulated for 999 frames.

Also for most of the frames vmaf score is 0 ,I'm not able to figure out why this is happening .

I appreciate the help.
