### ISSUE TITLE
Coredump: free(): double free detected in tcache 2

### ISSUE THREAD

**Issue by doublex** [gpac/gpac#1714]
Tested with GPAC 1.0.1 (Centos7) and GPAC git (Ubuntu 20.04)

Steps to reproduce (filesize ~4GB):
````
cd /tmp
wget http://doppelbauer.name/coredump.mp4
MP4Box -inter 500 -tmp /tmp/test -add /tmp/coredump.mp4 -new /tmp/ignore.mp4
````

Console:
```
free(): double free detected in tcache 2
aborted (core dumped)
```

**Comment by jeanlf** [comment]
Thanks for the file.
I cannot reproduce the core dump here (osx & ubuntu 20.04), did you try with latest git?

I however found an issue duplicating the co64 box in the output file, now fixed.

**Comment by doublex** [comment]
You are right. It does not happen with current git. My mistake. 
Thanks for this great code!
