### ISSUE TITLE
Force SIDX version=1 earliestPresentationTime=64bit value?

### ISSUE THREAD

**Issue by Murmur** [gpac/gpac#1716]
[See this topic #1704](https://github.com/gpac/gpac/issues/1704) about the `--tfdt64` flag to force TFDT.version1(64bit baseMediaDecodeTime) version. 

Similar flag to force `--sidx64` SIDX.version1(64bit earliestPresentationTime) field?

This would help to create segments compatible to a vod-to-live conversion simulator.

**Comment by jeanlf** [comment]
good idea, I'll use the `--tfdt64` flag to trigger 64 bit timestamps in sidx as well

**Comment by jeanlf** [comment]
now in master

**Comment by Murmur** [comment]
I compiled a fresh mp4box but SIDX is using a version=0, doubled checked the source files and changes listed in a commit objects are available.
```
MP4Box -dash 384000 -frag 384000 -dash-scale 48000 -closest -mem-frags -rap \
  -profile dashavc264:live -profile-ext urn:hbbtv:dash:profile:isoff-live:2012 -min-buffer 4000 \
  -bs-switching no -sample-groups-traf -single-traf --tfdt64 --tfdt_traf --noroll=yes -subsegs-per-sidx 0 \
  -segment-name "$RepresentationID$/$Number$$Init=i$" -out "manifest.mpd" \
  "temp-v1.mp4#trackID=1:id=v1:period=p0:dur=32" \
  "temp-a1.mp4#trackID=1:id=a1:period=p0:dur=32"
  
a1/1.m4s audio seg SIDX box, same applies to a video SIDX version=0
00 00 00 2C 73 69 64 78 00 00 00 00 00 00 00 01 ; ...,sidx........
00 00 BB 80 00 00 00 00 00 00 00 00 00 00 00 01 ; ...............
00 01 C5 9F 00 05 DC 00 90 00 00 00             ; ............  
```

**Comment by jeanlf** [comment]
hmm yes it's only activated for onDemand profile, I'll fix asap

**Comment by jeanlf** [comment]
now fixed in master for all profiles, thanks for the cross-check !

**Comment by Murmur** [comment]
@jeanlf Thanks for the quick response, tested and both SIDX+TFDT boxes use version=1(64bit timestamp field) format.
