### ISSUE TITLE
A Integer Overflow in function gf_avc_read_pps_bs_internal

### ISSUE THREAD

**Issue by treebacker** [gpac/gpac#1720]
There is a integer overflow in `media_tools/av_parsers.c:5349`, function `gf_avc_read_pps_bs_internal`.
Below code:
`pps_id = gf_bs_read_ue_log(bs, "pps_id");
	if (pps_id >= 255) {
		return -1;
	}
pps = &avc->pps[pps_id];
	pps->id = pps_id;
`
pps_id may be a negative number, so will not return.
However, avc->pps only has 255 unit, so overflow, which results a crash .

More than, because of the `pps->id = pps_id`, the vuln may lead to an any addr write.

In command Line:
gpac -info bug3
![bug3_cmd](https://user-images.githubusercontent.com/44844446/112791109-61c7ac00-9093-11eb-8fca-cd4c258dd6aa.png)

In gdb:
![bug3](https://user-images.githubusercontent.com/44844446/112791114-642a0600-9093-11eb-86ea-65536bd0eabc.png)

The crafted file is in the attached zip:
[bug3.zip](https://github.com/gpac/gpac/files/6219500/bug3.zip)

**Comment by jeanlf** [comment]
could not reproduce crash with latest master, but added safety checks. Thanks for the report
