### ISSUE TITLE
Font scan issue

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#1725]
Since late last week, the following error appears regularly:
```
$ gpac -i avgen:dur=4 reframer -o null
[avgen] Error initializing filter
[avgen] Error: Font SANS not found and no default font available!
Check your GPAC configuration, or use `-rescan-fonts` to refresh font directory.

    at put_image (/home/rbouqueau/works/gpac/gpac/share/scripts/jsf/avgen/init.js:355)
    at <anonymous> (/home/rbouqueau/works/gpac/gpac/share/scripts/jsf/avgen/init.js:245)

Error Bad Parameter while instantiating filter jsf
Failed to load filter for "avgen:dur=4": Bad Parameter

```

```gpac -rescan-fonts``` doesn't work but ```rm -rf ~/.gpac``` does. However the errors comes back again regularly.

I am on Debian. @nlsdvl also had the issue on Ubuntu.

**Comment by jeanlf** [comment]
should now be fixed - if you encounter the issue again (hopefully not) please post the [FontCache] section of GPAC.cfg

**Comment by synologic** [comment]
This shows in gpac_1.1.0-DEV-rev771 running on debian 18.04

[FontCache]
DejaVu Sans Mono Bold=/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf
DejaVu Sans Bold=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf
DejaVu Serif Book=/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf
DejaVu Sans Book=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
DejaVu Serif Bold=/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf
DejaVu Sans Mono Book=/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf
FontFixed=DejaVu Sans Mono
FontSerif=DejaVu Sans Mono
FontSans=DejaVu Sans Mono


What would be the issue, it even shows when doing gpac -h filters

Thanks

**Comment by synologic** [comment]
Removing /usr/share/gpac/scripts/jsf/avgen stops the error, guess it's an error in that jsf plugin ?

**Comment by jeanlf** [comment]
the error comes from initializing the font engine, used by avgen script. I'll look into that asap

**Comment by jeanlf** [comment]
Hmm I cannot reproduce (OSX or ubuntu 20.04), all I have is a warning message:
`[FreeType] Default fonts not valid, rescanning font directories`

What is the output you get ?

**Comment by synologic** [comment]
There you go:

```
root@gpac-test:~# gpac -h filters
Listing 110 supported filters:
inspect: Inspect packets
probe: Probe source
........
dtout: DekTec SDIOut
ohevcdec: OpenHEVC decoder
[FreeType] Default fonts not valid, rescanning font directories
[avgen] Error initializing filter
[avgen] Error: Font SANS not found and no default font available!
Check your GPAC configuration, or use `-rescan-fonts` to refresh font directory.

    at put_image (/usr/share/gpac/scripts/jsf/avgen/init.js:355)
    at <anonymous> (/usr/share/gpac/scripts/jsf/avgen/init.js:245)

Error Bad Parameter while instantiating filter jsf

```

**Comment by jeanlf** [comment]
I think this should now be fixed but I'm having a hard time reproducing the bug - could you cross-check ?
