### ISSUE TITLE
MP4Box: Wrong indices from Movie Fragments to Sample Description Box entry

### ISSUE THREAD

**Issue by mprobst-irt** [gpac/gpac#173]
When encoding mpeg dash streams with multiple representations we encounter a wrong index for the first representation. The sampleDescriptionIndex in the Track Fragment Header box of the first representation is 0. For the next representations it continues with 2, 3 and so on ...

Looking into MPEG4 part 12 indices usually start with 1. Unfortunately for this box it is not defined, but I found another place in that spec where a sampleDescriptionIndex runs from 1 to number of samples.

The init segment for the video contains three avc1 boxes which is fine (-bs-switching and profile)
The indices I found are 0, 2, and 3

Here is the call to mp4box

MP4Box - GPAC version 0.5.2-DEV-rev499-ga222f5f-master

"C:\Program Files\GPAC\mp4box.exe" -profile hbbtv1.5:live -bs-switching multi -dash 4000 -segment-ext m4s -url-template -out ..\dash\onDemand\manifest.mpd ..\source\NickAndTheRoundabouts_1920x1080_10M_640x720_1.5M.mp4 ..\source\NickAndTheRoundabouts_1920x1080_10M_960x720_2.5M.mp4 ..\source\NickAndTheRoundabouts_1920x1080_10M_1280x720_5M.mp4 ..\source\NickAndTheRoundabouts_audio_192k.mp4 ..\source\NickAndTheRoundabouts_ttml_5min.mp4:role=subtitle

Can I attach some samples to this issue? This is my first bug report here, so some guidance how I can support fixing the issue is much appreciated.

**Comment by rbouqueau** [comment]
Hi, thanks for the description.

I found the reference in the standard (5th edition draft, 8.7.4.3):
```
sample_description_index is an integer that gives the index of the sample entry that describes the samples in this chunk. The index ranges from 1 to the number of sample entries in the Sample Description Box
```

It may explain some of the artifacts I saw at playback.

CC @jeanlf

**Comment by rbouqueau** [comment]
```The init segment for the video contains three avc1 boxes which is fine (-bs-switching and profile)
The indices I found are 0, 2, and 3```

Mmm I see 1, 2 and 3. Where do you see the '0'?

```Can I attach some samples to this issue? This is my first bug report here, so some guidance how I can support fixing the issue is much appreciated.```

Yes. Thanks for the effort of posting. You can use www.wetransfer.com for example to upload some samples.

**Comment by mprobst-irt** [comment]
Thanks for your response. I was misinterpreting the tools I was using. The fragments in the first representation are using the default_sample_description_index which is defined in the trex box.

The actual segments of the first representation contain no reference at all, which means the default is used. The 2 tools I was using just put a 0 there, i.e. I was misinterpreting the output.

I am sorry for the wrong notice

**Comment by rbouqueau** [comment]
No problem. We're all trying to make this work :)
