### ISSUE TITLE
Trying to split live 360 video to tiles and play it

### ISSUE THREAD

**Issue by jakc-1** [gpac/gpac#1731]
I'm trying to split live stream video from rtmp link to MxN tiles, encode each tile to different qualities and then play it. Is this possible with gpac and how, do I need linux for it? I'm new to this so I would appreciate any kind of help. 

Thanks

**Comment by rbouqueau** [comment]
Hello,

Here are some useful links:

- https://github.com/gpac/gpac/wiki/HEVC-Tile-based-adaptation-guide
- https://github.com/gpac/gpac/wiki/Tiled-Streaming

Please let us what you think. We are interested in improving our doc whenever possible.

**Comment by jeanlf** [comment]
You will need a GPAC build with ffmpeg support, ffmpeg compiled with kvazaar support (--enable-libkvazaar) (our nightly installers do NOT provide kvazaar support in  ffmpeg, you will have to rebuild everything).

 RTMP sources are declared as usual, e.g.  `-i rtmp://URL/path`

then follow the [tile adaptation guide](https://github.com/gpac/gpac/wiki/HEVC-Tile-based-adaptation-guide#kvazaar-as-a-gpac-filter)

**Comment by jakc-1** [comment]
Hi,
just out of interest, do you know how to compile ffmpeg with kvazaar support on windows 10? I've been trying some guides but am unable to achieve it, so something like a step by step guide would be very helpful.
