### ISSUE TITLE
Cannot decrypt CENC file

### ISSUE THREAD

**Issue by mc0re** [gpac/gpac#1740]
I had an encrypt-decrypt pair of batch files, they worked okay about 1 year ago. I updated GPAC to the latest source and recompiled, then tried to decrypt the file encrypted a year ago. It came out with no sound. If I encrypt with the newest GPAC, then the decryption goes fine. The problem is that I have a bunch of files encrypted back then, which I can't decrypt now. Can I change some parameters to make it work?

### XML file
That file `gp.xml` wasn't changed.
```
<GPACDRM type="cenc">
  <DRMInfo type="pssh" version="0" cypherMode="no">
    <BS ID128="9A04F07998404286AB92E65BE0885F95" />
    <BS data64="rgIAAAEAAQCkAjwAVwBSAE0ASABFAEEARABFAFIAIAB4AG0AbABuAHMAPQAiAGgAdAB0AHAAOgAvAC8AcwBjAGgAZQBtAGEAcwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBEAFIATQAvADIAMAAwADcALwAwADMALwBQAGwAYQB5AFIAZQBhAGQAeQBIAGUAYQBkAGUAcgAiACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADAALgAwAC4AMAAiAD4APABEAEEAVABBAD4APABQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsARQBZAEwARQBOAD4AMQA2ADwALwBLAEUAWQBMAEUATgA+ADwAQQBMAEcASQBEAD4AQQBFAFMAQwBUAFIAPAAvAEEATABHAEkARAA+ADwALwBQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsASQBEAD4AdABsAFEAaQA3ADAAYwA3AFMARQBXADcANwBjAGcAUgB0AHcAcwB0AEcAZwA9AD0APAAvAEsASQBEAD4APABDAEgARQBDAEsAUwBVAE0APgB0AG0AUwB4AGkANwBuAEkAQgBaAE0APQA8AC8AQwBIAEUAQwBLAFMAVQBNAD4APABMAEEAXwBVAFIATAA+AGgAdAB0AHAAcwA6AC8ALwBuAGMAcABzAG0AZQBkAGkAYQAuAGsAZQB5AGQAZQBsAGkAdgBlAHIAeQAuAHcAZQBzAHQAZQB1AHIAbwBwAGUALgBtAGUAZABpAGEALgBhAHoAdQByAGUALgBuAGUAdAAvAFAAbABhAHkAUgBlAGEAZAB5AC8APAAvAEwAQQBfAFUAUgBMAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA=" />
  </DRMInfo>
  <CrypTrack first_IV="0x0000000000000001" saiSavedBox="uuid_psec">
    <key KID="0xef2254b63b474548bbedc811b70b2d1a" value="0x04030201060508070102030405060708" />
  </CrypTrack>
</GPACDRM>
```

### Commands
Encrypt:
```
"C:\Projects\gpac\bin\Win32\Debug - MP4Box_only\mp4box.exe" -crypt gp.xml -ab piff Dji.mp4 -out Dji.cenc.mp4
```
Decrypt:
```
"C:\Projects\gpac\bin\Win32\Debug - MP4Box_only\mp4box.exe" -decrypt gp.xml Dji.cenc.mp4 -out Dji.decrypt.mp4
```
The (old) encrypted file is here: http://nikitins.dk/exchange/Dji.cenc.mp4
Unencrypted file: http://nikitins.dk/exchange/Dji.mp4

**Comment by jeanlf** [comment]
can you give the version info of the old mp4box used to encrypt ?

**Comment by mc0re** [comment]
I can't tell you the exact version, but it was related to this issue: https://github.com/gpac/gpac/issues/1452 and this pull request: https://github.com/gpac/gpac/pull/1458

**Comment by jeanlf** [comment]
OK got it, we had a bug writing PIFF PSEC (but not senc) for some time in the new arch, this was fixed with 48ea22fea.
Unfortunately detecting such files is not possible, you need to pass manually the patch option `-piff-force-subsamples`. 

I'd strongly suggest rewriting your files ...

**Comment by jeanlf** [comment]
One side note: you don't have to re-encrypt, just re-import the file,  ie:

`MP4Box -add Dji.cenc.mp4 -new Dji.cenc.patched.mp4 -piff-force-subsamples`

**Comment by mc0re** [comment]
Thanks, it worked :-)
