### ISSUE TITLE
How to generate both DASH & HLS for multiple representation files? [Help wanted]

### ISSUE THREAD

**Issue by Dave-B** [gpac/gpac#1743]
I'd like to generate a HLS .m3u8 at the same time as the DASH .mpd, but - as I'm new to streaming tech - have been overwhelmed by all the options available.

Having read about the gpac 0.9.0 rearchitecture I gather this is possible, and have been exploring 1.0.1 on Debian testing - but can't see how to manage it.

I've successfully used FFMPEG to create multiple scaled represenatations of a video (and a single separate audio file), and then MP4Box to create an .mpd file and adjust the video container information as needed - resulting in a working stream with single files for each representation (serving byte-ranges via Apache).

I'm currently using gpac 0.5.2 on Debian 10 this with command:
```MP4Box -dash 5000 -frag 5000 -rap -profile onDemand -out film.mpd film_360.mp4 film_540.mp4 film_720.mp4 film_1080.mp4 film_audio.mp4```

It seems that, to get the .m3u8, I need to specify the *dasher* filter with the *dual* option, but haven't wrapped my head around how to do this.

Any suggestions or examples?

**Comment by jeanlf** [comment]
You will need GPAC 1.0 or more. 

Dual MPD+HLS generation can be done using:
`-out film.mpd:dual`
or
`-out film.m3u8:dual`
or adding
`--dual`

See:
- [this howto](https://github.com/gpac/gpac/wiki/hls#dual-dash--hls-generation)
- [this test script](https://github.com/gpac/testsuite/blob/master/scripts/hls-gen.sh) for example
- help on [arguments inheriting](https://github.com/gpac/gpac/wiki/filters_general#arguments-inheriting), the dasher filter inheriting options from the destination (here the fout filter handling `film.mpd` ), as you can see in the filter graph using `-fgraph` for MP4Box
- help on [global filter options](https://github.com/gpac/gpac/wiki/core_config#global-filter-options) if you use `--dual`

**Comment by Dave-B** [comment]
Brillant, thanks!
