### ISSUE TITLE
ffavin filter documentation // How to use it

### ISSUE THREAD

**Issue by pierrextardif** [gpac/gpac#1745]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hi,

After reading the 
documentation, I've tried to use ffavin to load a stream through [NDI](https://www.ndi.tv/sdk/).
[EDIT]
To reproduce :
ffmpeg compilation:

```sh
sudo cp -av /NDI_Folder_Location_for_linux/lib/x86_64-linux-gnu/libndi.so* /usr/lib/
#compile ffmpeg
#configure 
wget -O ffmpeg-snapshot.tar.bz2 https://ffmpeg.org/releases/ffmpeg-4.1.3.tar.bz2 && tar xjf ffmpeg-snapshot.tar.bz2 && sudo rm ffmpeg-snapshot.tar.bz2
cd ffmpeg-4.1.3

./configure \
    --extra-cflags="-I/NDI_Folder_Location_for_linux/include" \
    --extra-ldflags="-L/usr/lib/" \
    --extra-libs="-lpthread -lm" \
    --pkg-config=pkg-config \
    --enable-libndi_newtek
#make
make -j$(nproc)
sudo make install
#quick test log
ffmpeg -h demuxer=libndi_newtek
```

Gpac compilation:

```sh

make config.mak
make -j$(nproc)
```

I've compiled ffmpeg with NDI support - 4.1.3 -, and gpac with my local version of ffmpeg: when running :
`./gpac -hx ffavin:libndi_newtek`
i get : 
``` sh
ffavin:libndi_newtek

Description: Network Device Interface (NDI) input using NewTek library
Version: Lavd58.5.100
Max Input PIDs: 1
Flags: URLMimeProber
Priority 0

Options (expert):

find_sources (bool, default: false): Find available sources
wait_sources (uint):           Time to wait until the number of online sources have changed
allow_video_fields (bool, default: true): When this flag is FALSE, all video that you receive will be progressive
extra_ips (str):               List of comma separated ip addresses to scan for remote sources

```

all good so far.

But when trying to specify my input I don't get the right command..
<br>
With ffmpeg i do:
```sh
ffmpeg -f libndi_newtek -i "PIERRE-ALL-SERIES (NDI_TEST)" -frames:v 100 output.mp4
```

<br>

I have assumed this would work:
```sh
./gpac -i libndi_newtek:i="PIERRE-ALL-SERIES (NDI_TEST)" compositor vout
```
but i get : `Failed to load filter for "libndi_newtek:i=PIERRE-ALL-SERIES (NDI_TEST)": Requested URL is not valid or cannot be found`

Any pointers?

Thanks for your great work and support, :).

Best,

P

**Comment by rbouqueau** [comment]
You can find additional information:
- https://github.com/gpac/gpac/wiki/filters_general#source-and-sink-filters
- https://github.com/gpac/gpac/wiki/ffavin

Also please make sure you fill all the information before checking the case. We miss information to replicate your setup/issue.

**Comment by jeanlf** [comment]
I think (haven't tried it) that the syntax should be:
`video://:fmt=libndi_newtek:dev="PIERRE-ALL-SERIES (NDI_TEST)"`

(or `audio://` or `av://`)

`ffavin:fmt` maps to ffmpeg `-f`, `ffavin:dev` maps to input URL (i.e. `-i`) in ffmpeg, I'll update the doc of ffavin to be a bit more explicit ...

Let us know if that works

**Comment by pierrextardif** [comment]
Oui, perfect.

Thanks @jeanlf & @rbouqueau , it's working!

```sh
./gpac -i video://:fmt=libndi_newtek:dev="PIERRE-ALL-SERIES (NDI_TEST)" compositor vout
```
did the trick.

Best,

P
