### ISSUE TITLE
Compositor isn't able to display BMP files with GPAC_DISABLE_3D enable

### ISSUE THREAD

**Issue by gorinje** [gpac/gpac#1749]
Although the compositor handles well jpeg/png/etc. images from rfimg and imgdec filter chain, when it comes to bmp  (so only with rfimg) the compositor display only a red images with GPAC_DISABLE_3D flag.

**Comment by jeanlf** [comment]
Indeed, this should now be fixed, thanks for the report !

Note that the `drv` option of compositor can now be used in player mode to disable OpenGL.
