### ISSUE TITLE
mp4box - named pipe input

### ISSUE THREAD

**Issue by modmanx** [gpac/gpac#175]
This is a feature request - I have a video device that outputs mpeg4 / h264 encoded stream to named pipe. I would like to use MP4Box to create DASH-mpd file for this named pipe input stream. Application is used on Windows OS.
In case this already exists, please point me to the documentation.

**Comment by cconcolato** [comment]
This is not yet supported. I've flagged it as a feature-request. We'll try to see what we can do but it might take some time.

**Comment by byumark** [comment]
I would also love to see this, as well as pipe output.  Thanks!

**Comment by timdp** [comment]
Same here.

**Comment by egridley** [comment]
Me too.

**Comment by carlilelance** [comment]
this would be awesome

**Comment by jeanlf** [comment]
not yet but there will be news regarding this soon

**Comment by Brainiarc7** [comment]
Thanks

**Comment by vinnitu** [comment]
Hello,

Is this implemented in the current state?

**Comment by evrenbingol** [comment]
This would be amazing.

**Comment by q-rom1** [comment]
Hello,
Any news on this ?

**Comment by jeanlf** [comment]
now in GPAC 0.9.0 DEV, see https://github.com/gpac/gpac/wiki/pipes
