### ISSUE TITLE
How to obtain the frame data?

### ISSUE THREAD

**Issue by wzl281158150** [gpac/gpac#1751]
Hello, everyone. Is there any method to obtain the frame data of the hevc tiled video?
When i use MP4Box to produce DASH video from a single MP4 file, I can simply concatenate the init.mp4 and the .m4s files like this:
```
cat init.mp4 1.m4s 2.m4s 3.m4s > target.mp4
```
Then i can use other tools to obtain the frame data of the video.
However, if i produce a tiled DASH video according to the wiki "HEVC Tile based adaptation guide", i find that the method i used no longer works. 
When i want to concatenate the DASH files of one of the tracks (3x3+1 in wiki), the output can not be played seperately which means i can not obtain the frame data with other video processing tools(like ffmpeg).
Is there any helpful method in GPAC that can achieve this?

**Comment by jeanlf** [comment]
First make sure you concatenate files in order, eg `init_seg + (base_tile_segN + tile_track1_segN +  ...  + tile_track9_segN)`.
Check the results using `MP4Box -info concat.mp4`
Then merge the result back into a single video:
`gpac -i concat.mp4 tileagg @ -o single.mp4`


(using tileagg filter with mp4box is not currently working, I'll investigate)

**Comment by jeanlf** [comment]
Usage of tileagg with MP4Box now patched:
`MP4Box -add concat.mp4:@tileagg -new single.mp4`

**Comment by wzl281158150** [comment]
Thanks for the reply!
I have tried the command that you suggested and I get a single mp4 file that can be played successfully.
