### ISSUE TITLE
Unexpected thread_info() call return (ipc/send) invalid destination port

### ISSUE THREAD

**Issue by jcfrk101** [gpac/gpac#1752]
I'm running GPAC on a mac mini with apple silicon, I am getting the following warning when running. 
"Unexpected thread_info() call return (ipc/send) invalid destination port". I am running the following command
./gpac -i ~/Downloads/meta_n2.mp4  reframer:rt=on @ -o live.m3u8:segdur=10:cdur=0.1:llhls=br:cmaf=cmf2:dmode=static

**Comment by jeanlf** [comment]
This seems specific to M1 but I don't have a test device yet. The message is only triggered by the collecting of CPU stats and should not impact GPAC in any way. Can you confirm that the command runs as expected, apart from the warning messages ? If so I'll move the log message as debug info until I find a proper workaround.

**Comment by jcfrk101** [comment]
Everything runs as expected.
