### ISSUE TITLE
Question? Add inband timed metadata to mpeg4 fragments?

### ISSUE THREAD

**Issue by jcfrk101** [gpac/gpac#1755]
Is there a way to add inband timed metadata to mpeg fragments? I know it's possible to add them to mpeg-ts fragments, but I am trying to make the switch to mpeg4 fragments and need some help figuring out how to add the metadata.

**Comment by jeanlf** [comment]
This is a bit vague, but the answer is yes. You can have various kinds of meta-data tracks in ISOBMFF, this really depends on your use case.
As far as DASH/CMAF/fragmentation goes, any track can be fragmented. 
In CMAF however, meta-data tracks are not multiplexed with video or audio tracks, they are in dedicated "CMAF tracks", one per meta-data track.

Closing but feel free to keep on the discussion on more specific needs.
