### ISSUE TITLE
MPEG 4 3D not playing in android

### ISSUE THREAD

**Issue by ekamsoftwares-india** [gpac/gpac#1758]
Hi, I am trying to play 3D music file in the Osmo4 player, but the app stops responding. Here is the audio file to test with: https://drive.google.com/file/d/1dOGFi1OplTyef4FhCOo7zrKKuI3AZ3CL/view?usp=sharing

Kindly help.

**Comment by jeanlf** [comment]
We don't have any MPEG-H audio decoder publicly available, and we currently don't interface with the device codecs for audio (cf #1503).
