### ISSUE TITLE
How to change resolution smoothly and process a frame in python DASH client example

### ISSUE THREAD

**Issue by blxzfb307** [gpac/gpac#1761]
Hi, I have tried the python DASH client and it is amazing. The example works in the beginning but the windows will freeze with some blurred block as the figure shows when the resolution is changed but the terminal prints logs as normal.  I wonder to know how to fix it.  The libgpac version is `gpac-1.1.0-DEV-rev770-gc8edcaff-master-x64` and the OS is windows 10.

![figure2](https://user-images.githubusercontent.com/15121801/116203984-dbc08300-a76e-11eb-90f4-c157fdd626d9.PNG)

The second question is I want to do some processes of the frames such as scaling the frame or draw a rectangle in the frame after decoding the video and get the numpy array while disabling the playing window. After reading the document in the wiki, it seems that I need a custom filter but I can not run the example in the wiki and determine the position of the filter in the workflow. Would you mind providing an example more detailedly?

Thanks for your help.

**Comment by jeanlf** [comment]
1.
Hmm I cannot reproduce the freeze, I just tested with the [dash_bind.py](https://github.com/gpac/testsuite/blob/65498a2b8f569b37c1be4bfdc34b95ba9011a9ff/media/python/dash_bind.py) with auto-increment of quality.
Are you using the example python script or a custom one ? Do you pass specific options to libgpac ?

2.
You will need a custom filter (see [custom_forward.py](https://github.com/gpac/testsuite/blob/65498a2b8f569b37c1be4bfdc34b95ba9011a9ff/media/python/custom_forward.py) ), and indicate raw codecid capability:
`self.push_cap("CodecID", "Raw", gpac.GF_CAPS_INPUT_OUTPUT)`

You can then link your dash input to this custom filter as usual:
```
#load a custom filter
my_filter = MyFilter(fs)

#load a source
dmx = fs.load_src(DASH_URL)
my_filter.set_source(dmx)

#load a sink
vout = fs.load_src("vout")
vout.set_source(my_filter)

```

For the time being, you're on your own for drawing on the video frame in Python, the EVG or WebGL APIs are only available for JavaScript (as shown [here](https://github.com/gpac/gpac/wiki/evg) ).

Note that you can still use a JS filter for that (instead of a custom Python filter) and run the session in Python.

**Comment by blxzfb307** [comment]
1. I run the code in the [wiki dash-client](https://github.com/gpac/gpac/wiki/python#dash-client without any modification. It first will showing the highest quality and then change to the lowest one and freeze. 
2. If I change the capability as suggested, does it mean that I just need to modify the raw frame data in `pck = pid.get_packet()` and then send a new pacakge?

**Comment by jeanlf** [comment]
1. I'll check on windows, cannot reproduce on OSX
2. yes (I'll try to update the wiki with an example).

**Comment by blxzfb307** [comment]
Thanks for your patience and help.
 I tried to conbime the dash and custom filter to resize the frames but it fails to run according the suggestion. The output is `Exception: Failed to load source filter vout: Requested URL is not valid or cannot be found`, but the URL should be a valid which can access by the browser. I wonder to know what wrong with the python script. Here is the [python script](https://gist.github.com/blxzfb307/7073e617f93e3a22953e6664196c4ca2) in github gist.

**Comment by jeanlf** [comment]
Just tried on win10 with the code from the wiki (updated to cycle through each quality), no issue.
- can you try the wiki code with the same source (our dash conformance sequences) ?
- Are you sure the source is ok ? You can check using `gpac -play URL`


For your example:
- your are loading a source called 'vout' which does not exist, what you want is load the vout filter: `fs.load("vout")`
- the packet data will likely be YUV, you will need to fiddle around before passing the associated numpy array to img_show

**Comment by blxzfb307** [comment]
I tried the updated code in the wiki which using the original source and capture a short video but it has the same problem.
https://user-images.githubusercontent.com/15121801/116406991-d98c2080-a863-11eb-97de-62a15f6065b3.mp4

After using `fs.load("vout")` instead of `vout = fs.load_src("vout")` and remove the `cv2.resize(data, (540, 960))`, the output is in below. Besides, I use `cv2.cvtColor(data, cv2.COLOR_YUV2BGR_YV12)` to convert yuv to rgb and show the frame but it still have the same output. The example code is updated in [gist](https://gist.github.com/blxzfb307/7073e617f93e3a22953e6664196c4ca2).
```
new filter PYnspect
new filter httpin
new filter vout
del filter httpin
new filter ffdmx
done
No filter chain found for PID video1 in filter ffdmx to any loaded filters - NOT CONNECTED
No filter chain found for PID video2 in filter ffdmx to any loaded filters - NOT CONNECTED
No filter chain found for PID video3 in filter ffdmx to any loaded filters - NOT CONNECTED
No filter chain found for PID video4 in filter ffdmx to any loaded filters - NOT CONNECTED
No filter chain found for PID audio1 in filter ffdmx to any loaded filters - NOT CONNECTED
No filter chain found for PID audio2 in filter ffdmx to any loaded filters - NOT CONNECTED
del filter vout
del filter ffdmx
del filter PYnspect
[dash @ 0000029865622e80] Could not read complete fragment.
[dash @ 0000029865622e80] Could not read complete fragment.
[dash @ 0000029865622e80] Could not read complete fragment.
[dash @ 0000029865622e80] Could not read complete fragment.
[dash @ 0000029865622e80] Could not read complete fragment.
[dash @ 0000029865622e80] Could not read complete fragment.
```

**Comment by jeanlf** [comment]
can you post the filter graph used (`gpac -play URL -graph`) ? Also maybe run with debug logs for video output (`-logs=mmio@debug`) and post the logs



Your custom filter is missing the media type in its capability:
` self.push_cap("StreamType", "Visual", gpac.GF_CAPS_INPUT_OUTPUT)`

Also, depending on input streams and decoder used
- the pixel format of the decoded video may not always be YUV420 -> check the video pid property `PixelFormat`.
- there could be padding in the color planes -> check video pid properties `Stride`and `StrideUV` (if last one is not defined, it means u/v stride is Stride/2 for YUV420 and 422, otherwise Stride)

**Comment by blxzfb307** [comment]
I ran the command `gpac -play https://download.tsi.telecom-paristech.fr/gpac/DASH_CONFORMANCE/TelecomParisTech/mp4-live-1s/mp4-live-1s-mpd-AV-BS.mpd -graph -logs=mmio@debug` in powershell for about 30s and here is the [logs.txt](https://github.com/gpac/gpac/files/6392665/logs.txt).

I added `self.push_cap("StreamType", "Visual", gpac.GF_CAPS_INPUT_OUTPUT)` in the` __init__` function of the custon filter and here is the output. The example also is updated in [gist](https://gist.github.com/blxzfb307/7073e617f93e3a22953e6664196c4ca2).

```
Welcome to GPAC Python !
Version: 1.1.0-DEV-rev770-gc8edcaff-master
(c) 2000-2021 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io

Please cite our work in your research:
	GPAC Filters: https://doi.org/10.1145/3339825.3394929
	GPAC: https://doi.org/10.1145/1291233.1291452

new filter PYnspect
new filter httpin
new filter vout
new filter dashin
period reset type 0
period reset type 1
new filter httpin
new group 0 qualities 4 codec avc1.42c00d
new filter httpin
new group 1 qualities 2 codec mp4a.40.2
new filter mp4dmx
new filter mp4dmx
new filter nvdec
new filter ffenc
No filter chain found for PID AS_2 in filter dashin to any loaded filters - NOT CONNECTED
[FFEnc] No codecid specified
Failed to connect filter nvdec PID AS_1 to filter ffenc: Bad Parameter
done
period reset type 0
del filter ffenc
del filter nvdec
del filter mp4dmx
del filter mp4dmx
del filter httpin
del filter httpin
del filter dashin
del filter vout
del filter httpin
del filter PYnspect
```

**Comment by jeanlf** [comment]
The log file link is dead...

For your code my bad I forgot codec parsing was case-sensitive, name should have been 'raw' not 'Raw' (now fixed on git)

You cannot access pid properties (nor packet extension properties) as direct fields, you must use pid.get_prop(`PixelFormat`)  - I'll try to fix that one of these days

**Comment by blxzfb307** [comment]
Sorry for the dead link. Here is the new [logs.txt](https://github.com/gpac/gpac/files/6395635/logs.txt).

If I use 'raw' instead of 'Raw', the `data` is None. The example also is updated in [gist](https://gist.github.com/blxzfb307/7073e617f93e3a22953e6664196c4ca2).

**Comment by jeanlf** [comment]
Logs do not show anything strange. Can you post the filter graph used (`gpac -play URL -graph`) ?

It seems that you have a hardware decoder filter involved, which explains data being `None`. I updated the howto page to illustrate how to deal with these cases.

**Comment by blxzfb307** [comment]
I ran `gpac -play https://download.tsi.telecom-paristech.fr/gpac/DASH_CONFORMANCE/TelecomParisTech/mp4-live-1s/mp4-live-1s-mpd-AV-BS.mpd -graph` and here is the filter graph.
```
Type 'h' in window for command list
[DASH] Max buffer 100 less than max playout buffer 1000, overwriting max playout buffer
[DASH] Max buffer 100 less than max playout buffer 1000, overwriting max playout buffer
catched SIGINT - flush session before exit ? (Y/n):


Filters connected:
httpin (src=https://download.tsi.telecom-paristech.fr/gpac/DASH_CONFORMANCE/TelecomParisTech/mp4-live-1s/mp4-live-1s-mpd-AV-BS.mpd) (ptr=0000021FD1CDAE60)
-(PID mp4-live-1s-mpd-AV-BS.mpd) dashin (ptr=0000021FDD6BAEC0)
--(PID AS_1) nvdec "NVidia HWGL AVC|H264" (ptr=0000021FDD6C1640)
---(PID AS_1) vout (ptr=0000021FD1D2EBB0)
--(PID AS_2) ffdec "ffdec:aac" (ptr=0000021FDD6C1990)
---(PID AS_2) resample (ptr=0000021FDDE2C830)
----(PID AS_2) aout (ptr=0000021FD1CD0A00)
httpin (src=https://download.tsi.telecom-paristech.fr:443/gpac/DASH_CONFORMANCE/TelecomParisTech/mp4-live-1s/mp4-live-1s-mpd-AV-BS_set1_init.mp4:gpac:cache=mem_keep) (ptr=0000021FDD6E46F0)
-(PID mp4-live-1s-h264bl_mid-41.m4s) mp4dmx (ptr=0000021FDD6DC120)
--(PID mp4-live-1s-mpd-AV-BS_set1_init.mp4) dashin (ptr=0000021FDD6BAEC0)
httpin (src=https://download.tsi.telecom-paristech.fr:443/gpac/DASH_CONFORMANCE/TelecomParisTech/mp4-live-1s/mp4-live-1s-mpd-AV-BS_set2_init.mp4:gpac:cache=mem_keep) (ptr=0000021FDD722B40)
-(PID mp4-live-1s-aaclc_high-42.m4s) mp4dmx (ptr=0000021FDD6C0EF0)
--(PID mp4-live-1s-mpd-AV-BS_set2_init.mp4) dashin (ptr=0000021FDD6BAEC0)
```


I used the updated example in wiki but the `pck.data` is still none, here is the logs.
```
Exception ignored on calling ctypes callback function: <function filter_cbk_process at 0x000002344EEFBDC0>
Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\xxx\libgpac.py", line 2602, in filter_cbk_process
    return filter.process()
  File "C:\Users\xxx\Desktop\xxx\gpac_custom.py", line 72, in process
    tmp_pck = pid.opid.new_pck_clone(pck)
  File "C:\Users\xxx\Desktop\xxx\libgpac.py", line 3442, in new_pck_clone
    _pck = _libgpac.gf_filter_pck_new_clone(self._pid, ipck._pck, None)
OSError: exception: access violation reading 0x0000000000000000
```

**Comment by jeanlf** [comment]
1. If you play `gapc -play URL -backlist=nvdec`, do you still have the freeze at resolution change ?
2. I forgot to tell you, you must pull/recompile latest git, I fixed a bug in gf_filter_pck_new_clone

**Comment by blxzfb307** [comment]
1. It works perfect if I add `-blacklist=nvdec`, but how can I add this argument in python?
2. Can I download the laters version in [GPAC Nightly Builds](https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/)?

**Comment by jeanlf** [comment]
1. use `fs = MyFilterSession(0, "nvdec")`
2. not sure what you mean. I would convert data to RGB24, create a new packet with the right size and copy converted data to this packet. Don't forget that you will have to modify properties `Width`, `Height`, `Stride` and `StrideUV`of the output pid during the pid configure process - you can set `Stride` and `StrideUV` to None (will remove property) if no padding in the rescaled image.

I'll look at the resize issue with nvdec as soon as I get my hands back on a machine with nvdec support.

**Comment by blxzfb307** [comment]
1. If I use `fs = MyFilterSession(0, "nvdec")`, the data will be read-only in the exapmle. Can I edit the data in this case?
2. I try to convet the yuv data to rgb data and resize the frame but the result is unexpected. It seems that we can not pass the rgb data directly and I pring the fixfmt whose value is `1314271538`. Then I try to convert the rgb to yuv and then the size is right but the color is wrong. Here is the [example code](https://gist.github.com/blxzfb307/7073e617f93e3a22953e6664196c4ca2).

**Comment by jeanlf** [comment]
1. no, the data is read-only for nvdec case, using `fs = MyFilterSession(0, "nvdec")` will blacklist nvdec (so not use it), making packet data in system memory and convertible to writable mem using new_pck_clone. 

2. If I try your code without resizing (yuv/nv12 -> RGB -> YUV) , or resizing to same size, the output is correct, something is wrong with cv2.resize here, don't know why.  You can also try RGB output by setting `opid.set_prop('PixelFormat', 'rgb')`

3.  I fixed the handling of PixelFormat which was not properly handled indeed (int instead of string as for other constants) - it's a python only patch no need to update libgpac. 

4. Also in your code, it is better to not modify output pid props at each packet, only when the properties change (typically done in configure)

**Comment by blxzfb307** [comment]
1. Howerver when I using `fs = MyFilterSession(0, "nvdec")`, the `pck.is_frame_ifce()` will return False which means that `data` is read-only in the example.
2. It it correct if I using `fs = MyFilterSession(0, "nvdec")` and convert the `data` (I420 -> RGB -> I420). Maybe there is something wrong in opencv when the procession is NV12 -> RGB -> YV12. Therefores, I tried to using `opid.set_prop('PixelFormat', 'rgb')` and here is the logs. 
```
Exception ignored on calling ctypes callback function: <function filter_cbk_process at 0x0000025E10676D30>
Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\untitled\libgpac.py", line 2602, in filter_cbk_process
    return filter.process()
  File "C:\Users\xxx\Desktop\untitled\gpac_custom.py", line 137, in process
    pid.opid.set_prop('PixelFormat', 'rgb')
  File "C:\Users\xxx\Desktop\untitled\libgpac.py", line 3186, in set_prop
    prop_val = _make_prop(prop_4cc, pcode, prop, custom_type)
  File "C:\Users\xxx\Desktop\untitled\libgpac.py", line 2547, in _make_prop
    elif _lingpac.gf_props_type_is_enum(type):
NameError: name '_lingpac' is not defined
```
If I use the lastest build, the error is below.
```
Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\untitled\gpac_custom.py", line 3, in <module>
    import libgpac as gpac
  File "C:\Users\xxx\Desktop\untitled\libgpac.py", line 1320, in <module>
    _libgpac.gf_pixel_fmt_sname.argtypes = [c_uint]
  File "C:\Users\xxx\Python\Python39\lib\ctypes\__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\xxx\Python\Python39\lib\ctypes\__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'gf_pixel_fmt_sname' not found
```

3. I tried the latest master build and the error is same as above.

4. I only want to modify output pid props after resize the frame. How can I fixed it?

**Comment by jeanlf** [comment]
> the pck.is_frame_ifce() will return False which means that data is read-only in the example.

No, it means the data is available for read (previously you had no data, just None).
In either case (whether frame interface or not), you make the data writable by cloning the packet. Not that in your case you only need read access to the frame

> NameError: name '_lingpac' is not defined

You did not update your libgpac.py , cf [last commit](https://github.com/gpac/gpac/commit/1fd9cf2d84752faeaecbf03e93e331203f8fe0a1#diff-8ebe4d38cd29ed0d9b415f89b9bb464de9f99cd562e6a0316a200218ed7068eeR2555) linked to issue

> I only want to modify output pid props after resize the frame. How can I fix it?

The filter session tracks changes of PID configuration, so you can prepare ahead of time your output pid setup. In configure, do 

```
pid.opid.copy_props(pid)
self.width = pid.get_prop('Width')
self.height = pid.get_prop('Height')
self.pixfmt = pid.get_prop('PixelFormat')
self.stride = pid.get_prop('Stride')
self.stride_uv = pid.get_prop('StrideUV')
self.out_width = self.width//2
self.out_height = self.height//2
pid.opid.set_prop('Width', self.out_width)
pid.opid.set_prop('Height', self.out_height)
pid.opid.set_prop('PixelFormat', 'yuv') # or 'rgb'
pid.opid.set_prop('Stride', None)
pid.opid.set_prop('StrideUV', None)

```

and then in process:

```
pck = pid.get_packet()
data = pck.data
size = pck.size

yuv = data.reshape((self.width*3//2, self.height))
if self.pixfmt == 'nv12':
  rgb = cv2.cvtColor(yuv, cv2.COLOR_YUV2BGR_NV12)
else:
  rgb = cv2.cvtColor(yuv, cv2.COLOR_YUV2BGR_I420)

rgb_s = cv2.resize(rgb, (self.oh, self.ow), cv2.INTER_LINEAR)
# if outputing to rgb, directly do data = rgb_s.reshape(-1)
yuv_s = cv2.cvtColor(rgb_s, cv2.COLOR_BGR2YUV_I420)
data = yuv_s.reshape(-1)
size = len(data)

opck = pid.opid.new_pck(size)
if opck == None:
  raise Exception("Packet alloc failed")
opck.copy_props(pck)
odata = opck.data
numpy.copyto(odata, data)

opck.send()
pid.drop_packet()

```

**Comment by blxzfb307** [comment]
Doed it means that I don't need to care the result of `pck.is_frame_ifce()`?

I use the code of last commit and build, the error become
```
Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\untitled\gpac_custom.py", line 3, in <module>
    import libgpac as gpac
  File "C:\Users\xxx\Desktop\untitled\libgpac.py", line 1320, in <module>
    _libgpac.gf_pixel_fmt_sname.argtypes = [c_uint]
  File "C:\Users\xxx\Python\Python39\lib\ctypes\__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\xxx\Python\Python39\lib\ctypes\__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'gf_pixel_fmt_sname' not found
```

**Comment by jeanlf** [comment]
> Doed it means that I don't need to care the result of pck.is_frame_ifce()?

You do care since you want read access to the data - cf wiki code, we don't check pck.is_frame_ifce only for the case of inplace data procesing, where we create a write packet containg clone or pointer to source data.

> AttributeError: function 'gf_pixel_fmt_sname' not found
My bad, the export was missing on windows, the installers should be online soon

**Comment by blxzfb307** [comment]
Does inpace data processing mean that we don't modify the `props` of `pid`? In the example, we always clone a new package and send it. The `pck.is_frame_ifce()` is used for determining which package's data is None.

Thank you for being patient with me.  It works perfect in windows 10 and ubuntu 18.04 now. 
Is there any way to use it in ubuntu 20.04 except building fron source?

**Comment by jeanlf** [comment]
> Does inpace data processing mean that we don't modify the props of pid? In the example, we always clone a new package and send it. The pck.is_frame_ifce() is used for determining which package's data is None.

That's for this example, but you could change the output pid properties depending on what the filter does (for ex, the CENC encryptor/decryptor filters use inplace processing but modify both output pid properties and output packets properties). In-place processing only means that output packet data size is the same as input packet data, and (in most cases) input packet data is directly transferred to output packet through pck_clone(), avoiding memory copy.

> Thank you for being patient with me. It works perfect in windows 10 and ubuntu 18.04 now.

No problem - did you figure out the cv resize issue ?

> Is there any way to use it in ubuntu 20.04 except building fron source?

We currently don't build installers for ubuntu 20.04 so you must rebuild from source. That's on our very short term roadmap

**Comment by blxzfb307** [comment]
If I use the example without `dst = fs.load("vout")`, there is an error said `No filter chain found for PID AS_1 in filter PYRawVid to any loaded filters - NOT CONNECTED`. I want to use opencv to process and show the frames so I don't want to play the video with `vout`. Is there other `dst` to do that?

**Comment by jeanlf** [comment]
I would suggest that you setup your filter as a sink, so:
-  change `GF_CAPS_INPUT_OUTPUT` to `GF_CAPS_INPUT`
- do not create a new output pid in your configure
- do not create output packets

**Comment by blxzfb307** [comment]
I change the code as suggested but I can not get any frame in the queen and the size of the frame is 0. Here is the [code](https://gist.github.com/blxzfb307/7073e617f93e3a22953e6664196c4ca2).

**Comment by blxzfb307** [comment]
I figured out the sink filter by reading the wiki but I still can not set the default quality of the first segment. The `on_rate_adaptation` may not be executed in the beginning. The code is updated [here](https://gist.github.com/blxzfb307/7073e617f93e3a22953e6664196c4ca2).

**Comment by jeanlf** [comment]
> I figured out the sink filter by reading the wiki

Great! In your example, you don't need `pck.ref()` / `pck.unref()`, the packet you get from `pid.get_packet()` is valid until ` pid.drop_packet()` is called.

> I still can not set the default quality of the first segment

This is defined by the option [start_with](https://github.com/gpac/gpac/wiki/dashin#start_with) of the dashin filter. To force starting with min bandwidth, use:

```
  src = fs.load_src("http://127.0.0.1:8080/1080p_dash.mpd:gpac:start_with=min_bw")
```

or use `gpac.set_args(["--start_with=min_bw"])` before creating your session, cf [howto](https://github.com/gpac/gpac/wiki/python#tuning-up-gpac).

**Comment by blxzfb307** [comment]
Thanks a lot, using `gpac.set_args(["--start_with=min_bw"])` does not work for me but 
`src = fs.load_src("http://127.0.0.1:8080/1080p_dash.mpd:gpac:start_with=min_bw")` works perfectly.

**Comment by blxzfb307** [comment]
I found a strange error when I add a 1/24 second sleep in the `process` function to emulate comment playback. The data size will mismatch the `self.width` and `self.height` when switching a high-resolution chunk to a low-resolution chuck. The error can be solved by removing the sleep, but the rate in `on_rate_adaptation` will become very large. How to solve this problem?

**Comment by jeanlf** [comment]
could you post your code ?

**Comment by blxzfb307** [comment]
Here is the [code](https://gist.github.com/blxzfb307/7073e617f93e3a22953e6664196c4ca2). The dash video is produced as below and the source video is 24 fps. 
```
ffmpeg -i source.mp4 -c:v h264 -an -preset slow -s 960x540 -sws_flags bicubic -g 94 -keyint_min 94 -sc_threshold 0 540p.mp4
MP4Box -dash 4000 -rap -profile dashavc264.live -bs-switching no -segment-name $RepresentationID$/segment_$Number$$Init=init$ -out dash.mpd 1080p.mp4 720p.mp4 540p.mp4 360p.mp4
```
It may be related to encoding parameters because it can work with other encoding parameters.
```
ffmpeg -i source.mp4 -c:v hevc -an -preset slow -s 960x540 -x265-params keyint=94:no-open-gop=1 -sws_flags bicubic 540p.mp4
MP4Box -dash 4000 -rap -profile live -bs-switching no -segment-name $RepresentationID$/segment_$Number$$Init=init$ -out dash.mpd 1080p.mp4 720p.mp4 540p.mp4 360p.mp4
```
I don't know what encoding parameters are the best practice to produce the dash video.

Besides, where can I find the help information about the status information in `on_rate_adaptation`? For example, what is the meaning of max_speed, and what is the unit of number?
`active_quality_idx 3 rate 3483344 speed 1.0 max_speed 0.7179041166076063 display_width 0 display_height 0 buffer_min 0 buffer_max 1000 buffer 1041`

**Comment by jeanlf** [comment]
Thanks for the files, there was indeed an issue in the dash demuxer triggering reconfiguration in an async way. Could you try with latest git ?

Also in your process code, you don't need to check `width = pid.get_prop('Width')`, this value is already in  `self.width` : property values are guaranteed to be the same until `configure_pid` is called again

> Besides, where can I find the help information about the status information in on_rate_adaptation?

doc is in gpac doxygen: https://doxygen.gpac.io/group__pydash__grp.html

**Comment by blxzfb307** [comment]
Thanks for your help. It works perfectly now. I also want to know what is the best practice to produce the dash video?

**Comment by blxzfb307** [comment]
I also want to know how I can set the buffer time in python? There is a function called `gf_dash_group_set_buffer_levels` in the document but I can not find a python version. Would you mind telling me how to use this function in python?

**Comment by jeanlf** [comment]
Buffer levels are assigned through events typically sent by sink filters. In you case, before sending the GF_FEVT_PLAY event, do:
```
            evt = gpac.FilterEvent(gpac.GF_FEVT_BUFFER_REQ)
            # maximum buffer level in microseconds, here 30 seconds
            evt.buffer_req.max_buffer_us = 30000000
            pid.send_event(evt)

```

**Comment by blxzfb307** [comment]
Thanks for your help. I have another question, how can I get the rebuffer time in python? I want to know the stalled time in the video playback.

**Comment by jeanlf** [comment]
same thing, it is up to the sink to decide what to do in case of buffer underflow. You can check how this is done for [vout](https://github.com/gpac/gpac/blob/master/src/filters/out_video.c) filter, check for rebuffer variable. Basically:

- start in buffering mode
- while [pid.buffer](https://doxygen.gpac.io/classlibgpac_1_1_filter_pid.html#a52c99f7f9e809377d7a749ffe264146e) is less than your target initial playout buffer level, do nothing (do not consume packets)
- move to playback mode (consume packets)
- if no packet or pid.buffer is less than your target rebuffering level, move to buffering mode

**Comment by blxzfb307** [comment]
After a quick reading of vout filter source code, it seems that I should  use `pid.buffer` to determine the mode and calculate the `rebuf_time` in the sink. In buffer mode, I just return 0 in the `process` function and consume packets which mean calls `pid.get_packet()` and `pid.get_packet()` in playback mode. 

Can I get the rebuffer time in `DASHCustomAlgorithm` by using [DASHGroupStatistics ](https://doxygen.gpac.io/classlibgpac_1_1_d_a_s_h_group_statistics.html) or [DASHGroupDownloadStatistics](https://doxygen.gpac.io/classlibgpac_1_1_d_a_s_h_group_download_statistics.html)? There are `buffer` and `buffer_min` in `DASHGroupStatistics` and can I use the `download_rate` and `files_ize` to calculate the rebuffer time?

**Comment by jeanlf** [comment]
For the time being there is no signaling of re-buffering decisions made by the sink, it's in my todo but I don't know when it will be done.
Until then, you have to compute the re-buffer time in your sink (eg using gpac.sys_clock or gpac.sys_clock_high_res at start and end of re-buffering period)  and expose it to your dash custom algo code.

**Comment by blxzfb307** [comment]
I understand. I am going to use `pid.buffer` to determine the mode. Dose consuming packets mean that calling `pid.get_packet()` and `pid.get_packet()` while directly `return 0` means do not consume packets in `process` funtion? Besides, is there any different between  `pid.buffer` and `buffer` of `DASHGroupStatistics`?

**Comment by jeanlf** [comment]
> Dose consuming packets mean that calling pid.get_packet() and pid.get_packet() while directly return 0 means do not consume packets in process funtion?

Yes - until you call pid.drop_packet(), the packet is kept, so simply returning from process without calling pid.drop_packet() is what you need when rebuffering

> Besides, is there any different between pid.buffer and buffer of DASHGroupStatistics?

Almost, the difference is that pid.buffer gathers all buffers until sink, including decoded frames (by default 4 frames for video, 20 for audio), while DASHGroupStatistics.buffer gathers all buffer until decoder but does not include decoded frames (I may patch this to align the two one of these days).

**Comment by a23232390** [comment]
@blxzfb307  

how to you fix this problem in python ?
i have same problem

new filter httpin
new filter PYRawVid
new filter dashin
period reset type 0
period reset type 1
new filter httpin
new group 0 qualities 4 codec hvc2.1.6.L186.80
new group 1 qualities 4 codec hvt1.1.6.L186.80
new group 2 qualities 4 codec hvt1.1.6.L186.80
new group 3 qualities 4 codec hvt1.1.6.L186.80
new group 4 qualities 4 codec hvt1.1.6.L186.80
new group 5 qualities 4 codec hvt1.1.6.L186.80
new group 6 qualities 4 codec hvt1.1.6.L186.80
new group 7 qualities 4 codec hvt1.1.6.L186.80
new group 8 qualities 4 codec hvt1.1.6.L186.80
new group 9 qualities 4 codec hvt1.1.6.L186.80
new group 10 qualities 4 codec hvt1.1.6.L186.80
new group 11 qualities 4 codec hvt1.1.6.L186.80
new group 12 qualities 4 codec hvt1.1.6.L186.80
new group 13 qualities 4 codec hvt1.1.6.L186.80
new group 14 qualities 4 codec hvt1.1.6.L186.80
new group 15 qualities 4 codec hvt1.1.6.L186.80
new group 16 qualities 4 codec hvt1.1.6.L186.80
new group 17 qualities 4 codec hvt1.1.6.L186.80
new group 18 qualities 4 codec hvt1.1.6.L186.80
new group 19 qualities 4 codec hvt1.1.6.L186.80
new group 20 qualities 4 codec hvt1.1.6.L186.80
new group 21 qualities 4 codec hvt1.1.6.L186.80
new group 22 qualities 4 codec hvt1.1.6.L186.80
new group 23 qualities 4 codec hvt1.1.6.L186.80
new group 24 qualities 4 codec hvt1.1.6.L186.80
new group 25 qualities 4 codec hvt1.1.6.L186.80
new filter mp4dmx
new filter tileagg
new filter ffdec
new filter ffenc
[FFEnc] No codecid specified
Failed to connect filter ffdec:hevc PID V1 to filter ffenc: Bad Parameter
