### ISSUE TITLE
Multicast input howto ?

### ISSUE THREAD

**Issue by synologic** [gpac/gpac#1762]
Is it possible to receive mpeg-ts multicast with gpac ?

Going over the documentation and scratching my head to figure out how, would like to use gpac to dash live streams, i just cannot figure out how.

Some guidance would be appreciated if this is possible.

**Comment by rbouqueau** [comment]
> Is it possible to receive mpeg-ts multicast with gpac ?

Yes!

> Some guidance would be appreciated if this is possible.

There is quite some information on the wiki. See https://github.com/gpac/gpac/wiki/sockin or https://github.com/gpac/gpac/search?p=3&q=multicast&type=wikis.

Let us know more about your use-case and setup if you need more guidance.

**Comment by jeanlf** [comment]
yes, cf [sockin](https://github.com/gpac/gpac/wiki/sockin) filter:
`gpac -i udp://SRC_MCAST_IP:PORT `

You may have to specify the IP interface to use if you have multiple ones, using [-ifce](https://github.com/gpac/gpac/wiki/core_options#ifce)

**Comment by synologic** [comment]
Thank you, it is however not very helpful not to follow the kernel's routing table.
In multihomed setups, routing tables can change according to network failures, etc.
Forcing the IP address and not following the routing table kind of breaks failover scenarios ...

**Comment by rbouqueau** [comment]
My understanding is that if you don't specify ```ifce``` then GPAC follows the kernel routing tables. Could you explicit your use-case so that we have a look?

**Comment by synologic** [comment]
In fact it does not, if i don't specify the ifce parameter, it tries to join on lo:
gpac -r -i udp://239.250.10.197:1234 -o test.mp4

root@gpac-test:~# netstat -gn
IPv6/IPv4 Group Memberships
Interface       RefCnt Group
--------------- ------ ---------------------
lo              1      239.250.10.197
lo              1      224.0.0.1
eth0            1      224.0.0.1
eth1            1      224.0.0.1
lo              1      ff02::1
lo              1      ff01::1
eth0            1      ff02::1:ffdb:5ea4
eth0            2      ff02::1
eth0            1      ff01::1
eth1            1      ff02::1:ffdc:40cc
eth1            2      ff02::1
eth1            1      ff01::1

gpac -r -i udp://239.250.10.197:1234/:ifce=10.223.0.102 -o test.mp4
root@gpac-test:~# netstat -gn
IPv6/IPv4 Group Memberships
Interface       RefCnt Group
--------------- ------ ---------------------
lo              1      224.0.0.1
eth0            1      224.0.0.1
eth1            1      239.250.10.197
eth1            1      224.0.0.1
lo              1      ff02::1
lo              1      ff01::1
eth0            1      ff02::1:ffdb:5ea4
eth0            2      ff02::1
eth0            1      ff01::1
eth1            1      ff02::1:ffdc:40cc
eth1            2      ff02::1
eth1            1      ff01::1

The routing table:
root@gpac-test:~# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.16.44.1     0.0.0.0         UG    0      0        0 eth0
10.223.0.0      0.0.0.0         255.255.255.0   U     0      0        0 eth1
172.16.44.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0
224.0.0.0       0.0.0.0         240.0.0.0       U     0      0        0 eth1


The usecase, aside from the convenience part, would be that if i have a multihomed system with two multicast interfaces, for redundancy, if one goes down, or i use dynamic routing to inject multicast routes on one interface or the other, or even if i have the same route with different metrics, when gpac loses the input and will exit, then restarted by some sort of watchdog process, it would pick up the new kernel route and join the multicast on the (best) route currently present in the kernel table.

Having to specify the IP would also make it harder to use gpac in systems that can be automatically deployed/configured etc. Of course, it's easy to determine the ip address via a script and run gpac accrodingly, i'm just saying is not elegant to do so :)

**Comment by jeanlf** [comment]
indeed we were defaulting the ifce to 127.0.0.1 when none was set, rather than NULL (INADDR_ANY) - could you cross-check ?
