### ISSUE TITLE
Segment-timeline is broken with multiple representations

### ISSUE THREAD

**Issue by delbinwen** [gpac/gpac#177]
Hi,

I'm testing segment-timeline but I found some segment names are incorrect. Here is the result segment template;

``` xml
<SegmentTemplate initialization="$RepresentationID$/init.mp4" media="$RepresentationID$/$Time$.m4s" startNumber="1" timescale="1000">
    <SegmentTimeline>
     <S d="4992" r="3" t="0"/>
     <S d="4993"/>
     <S d="4992" r="1"/>
     <S d="4993"/>
     <S d="4992"/>
     <S d="4842"/>
    </SegmentTimeline>
   </SegmentTemplate>
```

And two sets of segments are created;
RepresentationID=1: init.mp4 0.m4s 4992.m4s 9984.m4s 14976.m4s 19968.m4s 24961.m4s 29953.m4s 34945.m4s 39938.m4s 44930.m4s
RepresentationID=2: init.mp4 0.m4s 4992.m4s 9984.m4s 14976.m4s 19968.m4s 24960.m4s 29952.m4s 34944.m4s 39936.m4s 44928.m4s
The segment names for RepresentationID=2 are incorrect. If you follow the segment timeline, the 6th segment should be 24961 not 24960. Following names are also incorrect.

I noticed dash_segmenter.c will calculate drift and adjust period_duration by adding tick. But following files do not follow segment timeline.

**Comment by aureliendavid** [comment]
this should be fixed with the above commit - I think it came from rounding issues when computing timestamps and durations
