### ISSUE TITLE
Question output single m3u8 playlist for multi track input

### ISSUE THREAD

**Issue by jcfrk101** [gpac/gpac#1775]
Hello, I have a question, is it possible to use the gpac tool to output a single m3u8 media playlist for a multi track input file? I have an input mp4 file with audio and video, and when I pass it into gpac with the command below, I get a master playlist with 2 media playlist with 2 init files. But I want a single media playlist with a single init file, is this possible with gpac? What would I have to change in my command to make it work?

This is the command that I am using
gpac -i inputfile.mp4  reframer:rt=on @ -o live.m3u8:segdur=10:cdur=0.2:llhls=br:dmode=static

**Comment by jeanlf** [comment]
The default behavior of gpac when dashing is to consider all input streams independently, producing non-multiplexed output for each stream - this differs from MP4Box behavior which considers all streams from a given source as part of the same target multiplexed output).

So you need to indicate the "Representation" property (see [`gpac -h props`](https://github.com/gpac/gpac/wiki/filters_properties#built-in-properties-for-pids-and-packets-pixel-formats-and-audio-formats) ) of the source stream(s) to bundle them in the same Representation (in DASH terminology):

`gpac -i inputfile.mp4:#Representation=r1 reframer:rt=on @ -o live.m3u8:segdur=10:cdur=0.2:llhls=br:dmode=static`

Same if your input streams are not multiplexed:

`gpac -i audio.mp4:#Representation=r1 -i video.mp4:#Representation=r1 reframer:rt=on @ -o live.m3u8:segdur=10:cdur=0.2:llhls=br:dmode=static`

**Comment by jcfrk101** [comment]
I try adding the "Representation" prop as you suggested, it is still fragmenting the input into separate streams.

**Comment by jcfrk101** [comment]
I removed ":cmaf=cmf2" from my command, I had added it to make llhls play on iOS devices. After removing that portion of the command, gpac now creates a multiplexed stream, but it doesn't play on iOS devices.

**Comment by jeanlf** [comment]
CMAF requires unmultiplexed files, so "Representation" is ignored when `cmaf` is set.

You can try one or more of the following switches on your destination - cf [`gpac -hx mp4mx`](https://github.com/gpac/gpac/wiki/mp4mx):
`:mvex:straf:tfdt_traf:truns_first:strun:nofragdef`
