### ISSUE TITLE
 avcc_box_read : Invalid parsing of SPS from AVCC atom for H264 High Profile? 

### ISSUE THREAD

**Issue by lotharkript** [gpac/gpac#1787]
generating a sample Mp4 file using ffmpeg and encoding it to 264 high profile

`ffmpeg -f lavfi -i testsrc=size=1920x1080:duration=0.5 -c:v libx264 -profile:v high -level:v 4.0 -pix_fmt yuv420p -y /tmp/main.mp4`

the function [avcc_box_read](https://github.com/gpac/gpac/blob/master/src/isomedia/avc_ext.c#L2675) extract the SPS/PPS from the AVCC atom.
The first byte of the sequenceParameterSets buffer will contain the nal_hdr.

Then, there is a [test](https://github.com/gpac/gpac/blob/master/src/isomedia/avc_ext.c#L2731)  checking for the profile and if the profile is 100, the code will be calling [gf_avc_read_sps](https://github.com/gpac/gpac/blob/master/src/isomedia/avc_ext.c#L2737) while removing the 1st byte of the sequenceParameterSets buffer.
`idx = sl ? gf_avc_read_sps(sl->data+1, sl->size-1, &avc, 0, NULL) : -1;`

This function will then call [gf_avc_read_sps_bs](https://github.com/gpac/gpac/blob/master/src/media_tools/av_parsers.c#L5402) which will call [gf_avc_read_sps_bs_internal](https://github.com/gpac/gpac/blob/master/src/media_tools/av_parsers.c#L5091) with nal_hdr being set to 0.
`return gf_avc_read_sps_bs_internal(bs, avc, subseq_sps, vui_flag_pos, 0);`

Which then in the [code](https://github.com/gpac/gpac/blob/master/src/media_tools/av_parsers.c#L5106), will try to parse the 1st byte of the bitstream as nal_hdr. However, it seems we did remove the byte in avcc_box_read and instead of parsing the nal_hdr, we will be parsing the profile_idc

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
indeed, now fixed (and added warning the file is not conformant) - thanks for the report
