### ISSUE TITLE
Error when building GPAC dependencies on windows 10

### ISSUE THREAD

**Issue by kamal-pp** [gpac/gpac#1788]
I am trying to build gpac by following the instructions on below page.
https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Windows
I tried to search this in existing list of issues but couldn't find it. So posting here.
I am using Visual Studio 2019 and building for Windows 10 x64.

In the step of [building dependencies](https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Windows#building-dependencies) I am seeing this error.
![image](https://user-images.githubusercontent.com/84123371/118097561-7a481780-b3f0-11eb-9132-c31556e0a5c2.png)

Here is the command I am using for build.
`msbuild.exe BuildAll_vc10.sln /maxcpucount /t:Build /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v142 /p:WindowsTargetPlatformVersion=10`

And this is the directory structure as mentioned in [this](https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Windows#get-the-code).
![image](https://user-images.githubusercontent.com/84123371/118097792-c2ffd080-b3f0-11eb-9e9b-3ad2d069d37e.png)

**Comment by jeanlf** [comment]
libxvidcore requires [nasm](https://nasm.us/), I'll update the wiki.

**Comment by aureliendavid** [comment]
You are probably missing [nasm](https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/) (must be accessible in your PATH) for libxvidcore. 

I forgot to mention it on the wiki page.

**Comment by kamal-pp** [comment]
@jeanlf  @aureliendavid Thanks I am able proceed with build after installing NASM and adding it to PATH env variable

**Comment by kamal-pp** [comment]
@jeanlf Do I need to create another issue for above mentioned error ?

**Comment by jeanlf** [comment]
sorry, I closed before your edit, reopening.
I just removed deps to afxres.h could you give it a try (only gpac master impacted, not gpac_deps) ?

**Comment by kamal-pp** [comment]
I am able to build now. @jeanlf 
closing this issue
