### ISSUE TITLE
Null pointer dereference in gf_isom_get_sample_rap_roll_info

### ISSUE THREAD

**Issue by hifoolno** [gpac/gpac#1794]
https://github.com/gpac/gpac/blob/c2086a8cb7eb564f402c58710de26317aa4aa857/src/isomedia/isom_read.c#L4553-L4554

Hello~ There are several calls to the function `gf_list_get` in `gf_isom_get_sample_rap_roll_info`, but the return values of `gf_list_get` are not checked before they are referenced.

**Comment by jeanlf** [comment]
the return value is never null
