### ISSUE TITLE
Need help playing audio using gpac

### ISSUE THREAD

**Issue by peal-k1** [gpac/gpac#1795]
I am just starting with gpac. So not sure how to use it and I couldn't find any other place to post a help.
How can I play any encoded or wav pcm audio using gpac ?

[This](https://gpac.wp.imt.fr/player/features#hardware)  documentation page mentions Microsoft directsound audio output. Is there any such filter for playing audio ?

**Comment by jeanlf** [comment]
The audio output filter is [aout](https://github.com/gpac/gpac/wiki/aout) and is the same across all platform, the underlying audio output device used will depend on the platform (see `gpac -h modules`)

- To play a wav or any non-raw file , `gpac -i file aout` or `gpac -play file`
- to play some raw PCM, check the [howto](https://github.com/gpac/gpac/wiki/raw-formats#raw-audio)

**Comment by peal-k1** [comment]
@jeanlf thanks this helped. I shall check wiki for further doubts
