### ISSUE TITLE
How can I print custom logs in existing filter ?

### ISSUE THREAD

**Issue by kamal-pp** [gpac/gpac#1796]
All the logs I am seeing when running the filter are per-existent logs. Not seeing any logs that I have added. 
I have added logs in FAAD filter using following statement.
`GF_LOG(GF_LOG_DEBUG, GF_LOG_CODEC, ("[FAAD]: FAAD decode process 1"));`

and checking log with command
`gpac.exe -logs=codec:parser:media@debug:ncl -i aac-test.aac @ rfadts @ faad @ aout`

**Comment by jeanlf** [comment]
If you use log tool `GF_LOG_CODEC`, you must use "codec@debug" as log tools.

The matching is defined [here](https://github.com/gpac/gpac/blob/master/src/utils/error.c#L165).

**Comment by kamal-pp** [comment]
@jeanlf  I am using codec@debug in the gpac command. I am getting the logs from the FAAD decoder but the only one which were already present there. Not the new logs that I have added. Do I need to move the compiled filter library to some other place ?

**Comment by jeanlf** [comment]
If you made a system installation of gpac on linux/osx, you will have to re-run `make install` yes

**Comment by kamal-pp** [comment]
@jeanlf Sorry I forgot to mention. I am using gpac on windows 10 and I have not done system installation and I am using it from build directory.  D:\GPAC\gpac_public\bin\x64\release\gpac.exe
