### ISSUE TITLE
regression: [FFDmx] Fail to open avgen - error No such file or directory

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#1798]
```gpac -i avgen:dur=30:sr=48000:ch=2:#ClampDur=9.6:#PStart=0.0:#m=m1 @ ffenc:c=aac @1 ffenc:c=avc:fintra=1.920 @ @1 reframer:xs=0.0:FID=P0 -i avgen:dur=30:sr=48000:ch=2:#ClampDur=9.6:#PStart=9.6:#m=m2:#BUrl=batch3/counter/b/ @ ffenc:c=aac @1 ffenc:c=avc:fintra=1.920 @ @1 reframer:xs=9.6:FID=P1 -i avgen:dur=30:sr=48000:ch=2:#ClampDur=9.6:#PStart=19.2:#m=m3 @ ffenc:c=aac @1 ffenc:c=avc:fintra=1.920 @ @1 reframer:xs=19.2:FID=P2 -o batch3/counter/b/dash.mpd:segdur=1.920:stl:cmaf=cmf2:SID=P0,P1,P2 --template='$m$_$Type$_$Number$'```

**Comment by jeanlf** [comment]
works fine here (osx), you're sure your install is OK ?

**Comment by rbouqueau** [comment]
Ok you're right, I stripped the command-line and it made the issue go away. The issue is with the #BUrl, see example below. It seems like the parsing is somehow not ok but I couldn't escape it. How should I do?

```
$ gpac -logs=all@info,filter@debug -i avgen:dur=30:sr=48000:ch=2:#ClampDur=9.6:#PStart=0.0:#m=m1 @ ffenc:c=aac @1 ffenc:c=avc:fintra=1.920 @ @1 reframer:xs=0.0:FID=P0 -i avgen:dur=30:sr=48000:ch=2:#ClampDur=9.6:#PStart=9.6:#m=m2:#BUrl=https://dash @ ffenc:c=aac @1 ffenc:c=avc:fintra=1.920 @ @1 reframer:xs=9.6:FID=P1 -i avgen:dur=30:sr=48000:ch=2:#ClampDur=9.6:#PStart=19.2:#m=m3 @ ffenc:c=aac @1 ffenc:c=avc:fintra=1.920 @ @1 reframer:xs=19.2:FID=P2 -o batch3/counter/b/dash.mpd:segdur=1.920:stl:cmaf=cmf2:SID=P0,P1,P2 --template='$m$_$Type$_$Number$'
```

**Comment by jeanlf** [comment]
now fixed, thanks for the command line.
