### ISSUE TITLE
gpac -threads=-1 never exits

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#1799]
```gpac -threads=-1 -i avgen:dur=30:sr=48000:ch=2 @ enc:c=aac:FID=GEN1A @1 enc:c=avc:fintra=1.920:FID=GEN1V reframer:#ClampDur=9.6:FID=RF1:SID=GEN1A,GEN1V:xs=0,9.6::props=#PStart=0:#m=m1,#PStart=19.2:#m=m3 -i avgen:dur=30:sr=48000:ch=2 @ enc:c=aac:FID=GEN2A @1 enc:c=avc:fintra=1.920:FID=GEN2V reframer:#ClampDur=9.6:FID=RF2:SID=GEN2A,GEN2V:xs=9.6:#PStart=9.6:#m=m2:#BUrl=batch3/real/a -o batch3/counter/a/dash.mpd:segdur=1.920:stl:cmaf=cmf2:SID=RF1,RF2 --template='$m$_$Type$_$Number$'```

**Comment by jeanlf** [comment]
This should now be fixed, can you cross-check ?

**Comment by rbouqueau** [comment]
It works, thanks!
