### ISSUE TITLE
question on multiple props lists propagation

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#1800]
I think I am confused by the way the list of props are propagated, in particular ```#Period``` (but the code shows nothing particular compared to ```#PStart``` so I assume the error comes from me).

If I execute (one props but then what is the separator? ':'?) ```gpac -i avgen:dur=30:sr=48000:ch=2 @ enc:c=aac:FID=GEN1A @1 enc:c=avc:fintra=1.920:FID=GEN1V reframer:#ClampDur=9.6:FID=RF1:SID=GEN1A,GEN1V:xs=0,9.6:props=#PStart=0,#PStart=19.2:#Period=P1,#Period=P3:#m=m1,#m=m3 -i avgen:dur=30:sr=48000:ch=2 @ enc:c=aac:FID=GEN2A @1 enc:c=avc:fintra=1.920:FID=GEN2V reframer:#ClampDur=9.6:FID=RF2:SID=GEN2A,GEN2V:xs=9.6:#PStart=9.6:#Period=P2:#m=m2:#BUrl=batch3/real/a -o tmp/dash.mpd:segdur=1.920:stl:cmaf=cmf2:SID=RF1,RF2 --template='$m$_$Type$_$Number$'```, I get (Period ID is ```P1,#Period=P3```):
```
 <Period id="P1,#Period=P3" duration="PT0H0M9.600S">
...
 </Period>
 <Period id="P2" start="PT0H0M9.600S" duration="PT0H0M9.600S">
...
 </Period>
 <Period id="P1,#Period=P3" start="PT0H0M19.200S" duration="PT0H0M9.600S">
...
 </Period>
</MPD>
```

If I execute (props splitted): ```gpac -i avgen:dur=30:sr=48000:ch=2 @ enc:c=aac:FID=GEN1A @1 enc:c=avc:fintra=1.920:FID=GEN1V reframer:#ClampDur=9.6:FID=RF1:SID=GEN1A,GEN1V:xs=0,9.6:props=#PStart=0,#PStart=19.2:props=#Period=P1,#Period=P3:props=#m=m1,#m=m3 -i avgen:dur=30:sr=48000:ch=2 @ enc:c=aac:FID=GEN2A @1 enc:c=avc:fintra=1.920:FID=GEN2V reframer:#ClampDur=9.6:FID=RF2:SID=GEN2A,GEN2V:xs=9.6:#PStart=9.6:#Period=P2:#m=m2:#BUrl=batch3/real/a -o tmp/dash.mpd:segdur=1.920:stl:cmaf=cmf2:SIDID=RF1,RF2 --template='$m$_$Type$_$Number$'```, I get (period 3 has disappeared):
```
<Period id="P1" duration="PT0H0M9.600S">
...
 </Period>
 <Period id="P2" start="PT0H0M9.600S" duration="PT0H0M9.600S">
...
 </Period>
</MPD>
```

what do I miss?

**Comment by jeanlf** [comment]
The doc was not clear on that, I updated it: you must escape the `props` option since it contains PID properties, otherwise these properties (except the first one) will be assigned as output PID props for all ranges:

> reframer:xs=0,9.6:props=#PStart=0,#PStart=19.2:#Period=P1,#Period=P3:#m=m1,#m=m3 

This will assign [`#PStart=0`, `#PStart=19.2`] to props, but will assign `#Period=P1,#Period=P3` and `#m=m1,#m=m3` to the output PID(s)

> reframer:xs=0,9.6::props=#PStart=0,#PStart=19.2:#Period=P1,#Period=P3:#m=m1,#m=m3 

This will assign [`#PStart=0`, `#PStart=19.2:#Period=P1`,`#Period=P3:#m=m1`,`#m=m3`] to props

**Comment by rbouqueau** [comment]
Ok. What was unclear to me was the separators. The list is comma-separated.

Thanks!
