### ISSUE TITLE
Invalid type-casting with udta boxes

### ISSUE THREAD

**Issue by cconcolato** [gpac/gpac#181]
Trying to solve issue #159 based on the response to #33. 
The problem is that the "chpl" box is cast into an GF_UnknownBox, leading to invalid ptr->data and ptr->dataSize (see https://github.com/gpac/gpac/blob/master/src/isomedia/isom_read.c#L2034)

**Comment by rbouqueau** [comment]
Is this still relevant?

**Comment by saurabhshri** [comment]
@rbouqueau #159 is.

**Comment by aureliendavid** [comment]
should be fixed as of https://github.com/gpac/gpac/commit/90c430ee552277a7b92543813a3620560953454e
