### ISSUE TITLE
.m4s not playing correctly

### ISSUE THREAD

**Issue by pikachu28** [gpac/gpac#1816]
I run the following commands:
```
kvazaar -i output_1280x720p.yuv --input-res 1280x720 -o output.hvc --tiles 2x2 --slices tiles --mv-constraint frametilemargin --bitrate 128000 --period 30 --input-fps 30

MP4Box -add output.hvc:split_tiles -fps 30 -new video_tiled.mp4

MP4Box -dash 1000 -rap -frag-rap -profile live -out dash_tiled.mpd video_tiled.mp4

```
After running I got the last command , I got .m4s file track ID wise as expected but I am not able to play them on gpac (it says Filter not found for desired type).

Also I want to combine to combine .m4s trackid wise to a tile_x.mp4 file for object detection , so I run the following command

```
cat video_tiled_dash_track2_init.mp4 $(ls -vx video_tiled_dash_track2_*.m4s) > source_2.mp4

```

So, I got source_2.mp4 which was suppose to contain to  track ID 2 but the there is no output of source_2.pm4 with gpac

Can anybody explain why this is happening and help me resolve this?

Thanks in advance!

Please let me know if more details are required

**Comment by jeanlf** [comment]
> but I am not able to play them on gpac (it says Filter not found for desired type).

Are you using `gpac -play dash_tiled.mpd `? 

> cat video_tiled_dash_track2_init.mp4 $(ls -vx video_tiled_dash_track2_*.m4s) > source_2.mp4

This will create a file with a moov declaring all tracks but data only for tile track 2 (no base tile track) which is not playable.

If you need to extract a single tile as a standalone regular HEVC video, you must use the [hevcsplit](https://github.com/gpac/gpac/wiki/hevcsplit) filter

**Comment by pikachu28** [comment]
> > but I am not able to play them on gpac (it says Filter not found for desired type).
> @jeanlf Yes, I am getting the same error 
> Are you using `gpac -play dash_tiled.mpd `?
> No, I played it on installed gpac on Mac
> > cat video_tiled_dash_track2_init.mp4 $(ls -vx video_tiled_dash_track2_*.m4s) > source_2.mp4
> 
> This will create a file with a moov declaring all tracks but data only for tile track 2 (no base tile track) which is not playable.
> Yes, it is not playable
> If you need to extract a single tile as a standalone regular HEVC video, you must use the [hevcsplit](https://github.com/gpac/gpac/wiki/hevcsplit) filter
This file doesn't contain the commands. Can share how exactly I should use this filter

**Comment by jeanlf** [comment]
what is your GPAC version ?

> Yes, it is not playable. Shouldn't it be?

No, it's only a single tile track ('hvt1' track type) and cannot be played by itself, it needs the tile base track ('hev2' / 'hvc2' track type)

> This file doesn't contain the commands. Can share how exactly I should use this filter

See [these tests](https://github.com/gpac/testsuite/blob/master/scripts/hevcsplit.sh)

**Comment by pikachu28** [comment]
I am using 1.1.0 DEV version of GPAC

How can I play it with tile base track ?
