### ISSUE TITLE
Need help implementing a custom filter

### ISSUE THREAD

**Issue by kamal-pp** [gpac/gpac#1817]
I want to create a custom GPAC filter which is going to be a decoder at later stage.
From [this](https://github.com/gpac/gpac/wiki/filters_general#external-filters) document, it says we can load external filters from default module folder.

So I have created a folder "test_filter" in the gpac_public\modules folder and added a makefile and gf_test_filter.c source file in it.
Also I have added `PLUGDIRS+=test_filter` in the makefile of modules folder to enable build of test_filter.

But in the build log I am not seeing this file getting compiled anywhere and I am not able to use this filter with the gpac command.
It gives following error 
```
Failed to find filter "testfilter"
Closest filter names:
- flist
```

**Comment by jeanlf** [comment]
If the file is not compiled your have a problem with modules/Makefile, or because you disabled things at configure.
- What is your configure command line ?
- where in modules/Makefile did you add PLUGDIRS+=test_filter ?

 
Once compiled, your filter should be in bin/gcc/gf_test_filter.so (or whatever name used in the makefile, and .dll / .dylib depending on platform), and you should see it when typing `gpac -h modules`

**Comment by kamal-pp** [comment]
- I am using windows 10.
- What is the configure command line ? Did not see anything about it in build wiki.
- I have added PLUGDIRS+=test_filter on line 75 of makefile without any condition.

```
#other linux
ifeq ($(CONFIG_LINUX),yes)
endif

PLUGDIRS+=test_filter

#if static modules are used, disable all previous modules (built-in in libgpac)
ifeq ($(STATIC_MODULES),yes)
PLUGDIRS=
endif
```

Below is my makefile inside gpac_public\modules\testfilter\
```
include ../../config.mak

vpath %.c $(SRC_PATH)/modules/test_filter

CFLAGS=-I"$(SRC_PATH)/include" $(OPTFLAGS) -DDISABLE_WAVE_EX

ifeq ($(DEBUGBUILD),yes)
CFLAGS+=-g
LDFLAGS+=-g
endif

ifeq ($(GPROFBUILD),yes)
CFLAGS+=-pg
LDFLAGS+=-pg
endif

#common obj
OBJS=gf_test_filter.o


SRCS := $(OBJS:.o=.c) 

LIB=gf_test_filter$(DYN_LIB_SUFFIX)

all: $(LIB)


$(LIB): $(OBJS)
	$(CC) $(SHFLAGS) -o ../../bin/gcc/$@ $(OBJS) -L../../bin/gcc -lgpac $(EXTRALIBS)  $(LDFLAGS)

clean: 
	rm -f $(OBJS) ../../bin/gcc/$(LIB)

dep: depend

depend:
	rm -f .depend	
	$(CC) -MM $(CFLAGS) $(SRCS) 1>.depend

distclean: clean
	rm -f Makefile.bak .depend

-include .depend
```

**Comment by jeanlf** [comment]
are you building using visual studio ?

**Comment by kamal-pp** [comment]
yes Visual studio 2019

**Comment by jeanlf** [comment]
then you need to create a project for your filter, I suggest you use the [openhevc module project](https://github.com/gpac/gpac/blob/master/build/msvc14/dec_openhevc.vcxproj) as an example:
- copy file
- change ProjectGuid
- rename occurences of dec_openhevc to your own project name
- remove openhevc.lib from AdditionalDependencies
-  add project to gpac workspace

**Comment by kamal-pp** [comment]
adding project to gpac workspace means need to add it to gpac.sln like below ?
```
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "ohevcdec", "dec_openhevc.vcxproj", "{042D3628-67F3-4B6C-8CC0-CD9AFA416974}"
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "test_filter", "test_filter.vcxproj", "{3cd6dfce-b17b-4783-809a-42514cefe430}"
EndProject
```

**Comment by jeanlf** [comment]
yes, or add project to GPAC workspace through MSVC GUI

**Comment by kamal-pp** [comment]
Now I can see testFilter getting compiled and there is a gf_testFilter.dll in gpac_public\bin\x64\release\ but I am not able to use that filter in filter chain with GPAC command. It is not able to find the filter

**Comment by jeanlf** [comment]
hmm something is wrong in your project, I think you're missing the export file so `RegisterFilter`function is not exported.
To re-run again gpac remove `gf_testFilter.dll ` from the build directory.
Not sure why it is crashing though, I'll investigate - could you post the MSVC project file of your filter somwhere ?

**Comment by jeanlf** [comment]
I cannot reproduce your crash - I added a test sink filter [here](https://github.com/gpac/gpac/tree/master/modules/test_filter), but I will need at least your project file to reproduce your crash

**Comment by kamal-pp** [comment]
This contains the test_filter.vcxproj and updated gpac.sln
[msvc14.zip](https://github.com/gpac/gpac/files/6582563/msvc14.zip)

**Comment by jeanlf** [comment]
using your project file I can see a gf_testFilter.dll in build directory and it is listed in `gpac -h modules`. Is this not your case ?

**Comment by kamal-pp** [comment]
Yes I am seeing it listed in gpac -h modules. But for any other gpac command, like `gpac.exe` or `gpac.exe` -h filters it is crashing. Are you seeing this behavior ?

**Comment by jeanlf** [comment]
no I don't see that, I suppose this comes from the filter code itself, could you post it ?

**Comment by kamal-pp** [comment]
Yes. Here is test_filter.c file.
I have one more doubt. Why I am seeing it as a module and not filter? Will it work fine fine as other default filters do ?
[test_filter.zip](https://github.com/gpac/gpac/files/6595807/test_filter.zip)

**Comment by kamal-pp** [comment]
@jeanlf can you check this file and see if the crash is coming from this ?

**Comment by jeanlf** [comment]
this should now be fixed, we had a bad assignment making gpac crash if the registry was declared as const. Can you retry ?

**Comment by kamal-pp** [comment]
Yes it is working now. Is there any document for filter capabilities and how to define them or what capabilities I should use ?

**Comment by jeanlf** [comment]
Not yet, we need to update the doc to give a bit more details on that. Meanwhile you can check the various filters in gpac, 
- native ones (in [src/filters](https://github.com/gpac/gpac/tree/master/src/filters) ) 
- JavaScript  [howto](https://github.com/gpac/gpac/wiki/jsfilter) and [testsuite](https://github.com/gpac/testsuite/tree/master/media/jsf) examples
- Python [howto](https://github.com/gpac/gpac/wiki/python) and [testsuite](https://github.com/gpac/testsuite/tree/master/media/python)  examples.

You can check your capabilities as seen by the graph resolver  using `gpac -h links test_filter`.
