### ISSUE TITLE
MP4Client failed to playback 8x8 hevc-tiled dash contents

### ISSUE THREAD

**Issue by kjtseng** [gpac/gpac#1819]
Hello, I can play  tiles : 3x3 ~ 7x7 hevc-tiled dash contents.
But I can not play over 8x8 tiles.
Is it possible to play over 8x8 tiles?
Please help me, thank you guys.

**Comment by jeanlf** [comment]
Can you post the MP4Client output ?

Can you also try with:
- `gpac -play manifest.mpd`
- `gpac -play manifest.mpd -threads=1`
- `gpac -play manifest.mpd -threads=2`

**Comment by kjtseng** [comment]
Hello,
The MP4Client shows
ILoading GPAC Terminal
Terminal Loaded in 61 ms
Opening URL .\dash_tiled.mpd
Service Connected
Corrupted buffer level in PID instance V29 (mp4dmx -> dashin), dropping packet duration 33333 us greater than buffer duration 0 us
[TileAgg] Something is wrong in demuxer, received segment flush event but previous segment is not yet flushed !
[TileAgg] Something is wrong in demuxer, received segment flush event but previous segment is not yet flushed !
[TileAgg] Something is wrong in demuxer, received segment flush event but previous segment is not yet flushed !
[TileAgg] Something is wrong in demuxer, received segment flush event but previous segment is not yet flushed !
[TileAgg] Something is wrong in demuxer, received segment flush event but previous segment is not yet flushed !
[TileAgg] Something is wrong in demuxer, received segment flush event but previous segment is not yet flushed !
[TileAgg] Something is wrong in demuxer, received segment flush event but previous segment is not yet flushed !
...

It can play with 
gpac -play manifest.mpd
gpac -play manifest.mpd -threads=1
gpac -play manifest.mpd -threads=2
But the quality is the lowest , can I change it ?
Thanks for your reply.

**Comment by jeanlf** [comment]
This should now be fixed, tested with 10x10 tiling.

For local playback, quality will not change unless auto_switch is set or an HTTP download rate is simulated using `-maxrate` (I'll update the dashin doc on that)
