### ISSUE TITLE
MP4Client with gui command failed to playback 8x8 hevc-tiled dash contents 

### ISSUE THREAD

**Issue by kjtseng** [gpac/gpac#1820]
Thanks for the fix for my problems before.

Now I want to use the - gui command with MP4Client for 10x10 hevc-tiled dash contents.  
My command is
Mp4client .\dash_tiled.mpd -logs=all@info:dash@debug -gui
But it will stop after the following messags.
 
![image](https://user-images.githubusercontent.com/18127960/120890610-8792a380-c636-11eb-9103-ebe139ecde7a.png)

By the way, how much tiles of the column and row can I use in hevc-tiled dash contents? 
I need a lot of tiles for my research. Thanks.

**Comment by jeanlf** [comment]
You may have hit a limit of tiles supported by your decoder - looks like you use nvdec , try disabling it to use ffdec (add `-blcklist=vtbdec`).

> By the way, how much tiles of the column and row can I use in hevc-tiled dash contents?

HEVC Annex A.4.1 gives per level the following limits (rows x columns):
- 22x20 for level 6*
- 11x10 for level 5* 
- 5x5 for level 4*
- 3x3 for level 3.1
- 2x2 for level 3
- no tiles support for levels 1 and 2

Note that libavcodec doesn't seem to care much about the number of tiles (tried your 30x15 config without issue), but this will likely not be the case for other implementations (videotoolbox on big sur doesn't accept 30x15) 

> I need a lot of tiles for my research.

don't forget that the more tiles you add, the more files you get so the number of http request will get crazy, and the stress on the implementation quite high (I did a few optimisations in the filter session to reduce configuration CPU times for such extreme cases).
