### ISSUE TITLE
Failed to playback 30x15 hevc-tiled MP4 and can not create dash contents

### ISSUE THREAD

**Issue by kjtseng** [gpac/gpac#1821]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

* [x] I looked for a similar issue and couldn't find any.
* [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
* [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). 

Hi,
The resolution of my video is 3840x1920.
I divided the video frame by the tile size 128x128 pixels to created a hevc-tiled MP4.
If I play the video by the command MP4Client 5000bps.hvc
it will stuck on black screen and shows  
![image](https://user-images.githubusercontent.com/18127960/120848395-5323d680-c5a7-11eb-9a7e-a1cd1c46eb40.png)

If I want to create dash contents, it also can not work. 
I need the small tile size for my research, it is very important for me.
Please help me.
Thank you guys.

The following are my commands for creating the mp4 and MPD.
 
.\kvazaar.exe  -i 4K.yuv --input-res 3840x1920 -o 5000bps.hvc --tiles 30x15 --slices tiles  -q 40 --mv-constraint frametilemargin  --bitrate 5000 --period 30 --input-fps 30 

Mp4box.exe -add 5000bps.hvc:split_tiles -new 5000bps.mp4
MP4Box -dash 1000 -rap -frag-rap -profile live -out dash_tiled.mpd 5000bps.mp4

**Comment by jeanlf** [comment]
I did a few optimizations to handle loading such heavy configurations (also see #1820).

A few remarks here:

- by default MP4Box consider all tracks of a source file to be part of the same muxed quality, so in your case each output segment contains all tile tracks for the given duration (this was causing a crash in stats reporting of mp4mx filter). use `5000bps.mp4:id=NULL` to prevent this.

- kvazaar will likely generate open-gop only so the resulting dash will not be compliant to any common profile. To avoid that you need to do the encoding using gpac, forcing IDRs at your given period, for example:
```
gpac -+kvazaar-params=tiles=3x3,slices=tiles,mv-constraint=frametilemargin,rc-algorithm=lambda \
 -i src.mp4 enc:c=libkvazaar:b=2M:fintra=1:rc @ -o tiled.mp4
```
