### ISSUE TITLE
Reframer cuts in compressed mode leads to incorrect DASH content (raw is ok)

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#1823]
Source files:
*  https://www.gpac-licensing.com/downloads/tmp/tos.mp4

Doesn't work (the DASH second period is not at the right time (PTO value is not 9.6s) and A/V is desync):
```
gpac -i tos.mp4:FID=GEN1 \
    resample:osr=48k:SID=GEN1 @ enc:c=aac:FID=GEN1A \
    ffsws:osize=960x426:SID=GEN1 @ enc:c=avc:fintra=1.920:FID=GEN1V \
    reframer:#ClampDur=9.6:FID=RF1:SID=GEN1A,GEN1V:xs=19.6,29.2::props=#PStart=0:#m=m1,#PStart=9.6:#m=m2 \
  -o broken/dash.mpd:segdur=1.920:stl:cmaf=cmf2:SID=RF1 --template=\$m\$_\$Type\$_\$Number\$"
```

Works:
```
gpac -i tos.mp4 \
    @ resample:osr=48k @1 ffsws:osize=960x426 \
    @ @1 reframer:#ClampDur=9.6:xs=19.6,29.2::props=#PStart=0:#m=m1,#PStart=9.6:#m=m2 \
    @ enc:c=aac:FID=GEN1A  @1 enc:c=avc:fintra=1.920:FID=GEN1V \
  -o works/dash.mpd:segdur=1.920:stl:cmaf=cmf2:SID=GEN1A,GEN1V --template=\$m\$_\$Type\$_\$Number\$"
```

**Comment by jeanlf** [comment]
This should now be fixed, but there is no guarantee this will always work: the first command splits the input at non-IDR boundary, and the dasher was silently trashing non-sap packet before initializing without remembering the initial TS, now fixed.
However if the IDR frequency chosen is too low, spliting at non-IDR may result in empty segments which is not supported atm.
