### ISSUE TITLE
[Help wanted] Linkage with internal functions in custom filter

### ISSUE THREAD

**Issue by pierrextardif** [gpac/gpac#1828]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hi,

I'd like some helpm on linking a file which i am calling form a cusotm filter I'm trying to build:

I managed to call a `.o` from my filter by adding some flags to the compiler, but upon pulling changes I erased it and can't find how to get a shared `.o` to work witjh my custom filter, :(.

I'm using `ubuntu 20.04`, `gcc 8.4.0` and gpac up tp date with the master branch - so this [commit](https://github.com/gpac/gpac/commit/206ad0907cc1f56ef031b5e3b1e30136e721ba9f) -.

I've got my Makefile which is heavily inspired by the [dec_openhevc](https://github.com/gpac/gpac/blob/master/modules/dec_openhevc/Makefile), as it is module a filter.

My command to compile my filter into a library file is :
```sh
COMMAND = @gcc  -shared -o ../../bin/gcc/gf_libTest.so ../../src/filters/ff_common.o read_test.o  -lm -L/usr/local/lib -L/usr/local/lib -lavcodec -lavformat -lavutil -lavdevice -lswscale -lswresample -lavfilter -fsanitize=address -Wl,-z,defs -dynamiclib -L../../bin/gcc -lgpac -ldl  -fsanitize=address -Wl,-z,defs -dynamiclib 
```
which gives me an error :
```sh
/usr/bin/ld: ../../src/filters/ff_common.o: in function `ffmpeg_register_free':
ff_common.c:(.text+0xe7): undefined reference to `gf_fs_remove_filter_register'
/usr/bin/ld: ../../src/filters/ff_common.o: in function `ffmpeg_build_register':
ff_common.c:(.text+0x18a3): undefined reference to `gf_fs_add_filter_register'
/usr/bin/ld: ff_common.c:(.text+0x1a92): undefined reference to `gf_fs_add_filter_register'
/usr/bin/ld: ../../src/filters/ff_common.o: in function `ffmpeg_report_options':
ff_common.c:(.text+0x23ea): undefined reference to `gf_filter_report_meta_option'
collect2: error: ld returned 1 exit status
```

Any pointer?

Thks,

P

**Comment by pierrextardif** [comment]
So [here](https://drive.google.com/file/d/1iOLYs2kNpAOuc9Cp3WKMI3IjfPQLA2Vq/view?usp=sharing) is my module structure, although i felt like the previous post encapsulated the error.

If there is a faster way to approach this (Cmake recipie / autogen ), i'll take it, :).

The folder has to be placed in the module of gpac, and compile using gcc.
I used `make dep` to generate the .dep file just like in the other modules, but it's not enough.
Not sure how to link `ff_common.o` .

**Comment by aureliendavid** [comment]
Your setup seems to be working for me. 

Here's what I did: 
* ran a `make clean && ./configure && make` on gpac master
* extracted your zip and put `libTest` in `modules/`
* removed `.depend` and `read_test.o` in `libTest/`
* edited `modules/Makefile` to add `PLUGDIRS+=libTest`
* ran `make` in gpac dir 

I do get a `bin/gcc/gf_libTest.so` and I can run: 

```
$ gpac -p=0 -hh filters | grep -i readTest
readTest: reader Test This is a very simple excquiisit descripotion with some typois
```

(on ubuntu 20) 

do you get something different if you follow the same steps?

**Comment by pierrextardif** [comment]
my one is not working, :(.
Also i configure it using my local ffmpeg + fpic flag:
```
CC=gcc CXX=g++ CFLAGS="-fsanitize=address" CXXFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address"  ./configure --use-ffmpeg=local --enable-pic
```


also lin 107 has to be  uncommented (OUPS) :-1: 
`
    u32 pix_fmt = ffmpeg_pixfmt_to_gpac(AV_PIX_FMT_YUV420P);
`

And yes, if i follow your steps, with my code it is working, but if line 107 isn't commented, i belive it's failing?

Let me know if you can help to sort this out, :).

**Comment by aureliendavid** [comment]
> And yes, if i follow your steps, with my code it is working, but if line 107 isn't commented, i belive it's failing?

ah I see, you're trying to use a function defined in `ff_common` but it's not exported in `libgpac` so it fails

you can make it work by adding `GF_EXPORT` to the functions you want to use in `ff_common.c`, i.e.:

change 

https://github.com/gpac/gpac/blob/206ad0907cc1f56ef031b5e3b1e30136e721ba9f/src/filters/ff_common.c#L122

to 

```c
GF_EXPORT
u32 ffmpeg_pixfmt_to_gpac(u32 pfmt)
```

Another solution would be to change the default behavior to "export everything" by removing the `-fvisibility="hidden"` cflag, for example by commenting out this block: 

https://github.com/gpac/gpac/blob/206ad0907cc1f56ef031b5e3b1e30136e721ba9f/configure#L2852-L2854

However exporting everything might cause a mess, I'm not sure. 


We should probably officially export these functions in libgpac proper, that's to be discussed. 


(btw if you want to use asan you can you the `--enable-sanitizer` option in gpac `./configure`)

**Comment by pierrextardif** [comment]
ok perfect, the `GF_EXPORT` did marvels.
Ok will use `enable-sanitizer` .
Thansks for the support.
