### ISSUE TITLE
How can I increase the size of the buffer for MPEG-DASH playback?

### ISSUE THREAD

**Issue by kjtseng** [gpac/gpac#1829]
It shows a lot of buffering.

Buffer : |======              | (33/100)

How can I increase the size of the buffer?

**Comment by jeanlf** [comment]
Default buffer levels depends on the video sink used:

When using vout directly (  `gpac -play URL` or `gpac -i URL vout`), the [default buffer](https://github.com/gpac/gpac/wiki/vout#buffer) is 100ms.

When using the compositor filter (`MP4Client URL` or `gpac -gui URL`),  the [default buffer](https://github.com/gpac/gpac/wiki/compositor#buffer) is 3s.


Note that GPAC uses 3 values to control buffering, `buffer` for playout buffer, `rbuffer` for rebuffering events and `mbuffer` for max buffer allowed, typically used by DASH/HLS. 

Both vout and compositor use the same buffer option syntax, so you can control this using `--buffer=N` `--mbuffer=M`  regardless of which sink is used.
