### ISSUE TITLE
mp4box - cannot store correct "audioProfileLevelIndication" value for 7.1ch AAC audio

### ISSUE THREAD

**Issue by mayamo** [gpac/gpac#183]
I am working with MP4/AAC 7.1ch file which is based on "ISO/IEC 14496-3:2009/Amd.4:2013".
When remuxing a 7.1ch MP4 file which have correct "audioProfileLevelIndication" value,
the remuxed MP4 file always have 0x2A for audioProfileLevelIndication (which means 5.1ch).

e.g.
mp4box -add original_7.1ch.mp4#audio -new remuxed_7.1ch.mp4

original_7.1ch.mp4: audioProfileLevelIndication=0x50
remuxed_7.1ch.mp4: audioProfileLevelIndication=0x2A

Thanx for your help, and this tool.

**Comment by rbouqueau** [comment]
Would it be possible to provide a sample file?

**Comment by mayamo** [comment]
Sure!

Please download "71ch_sample_files.zip" from the following.
https://mega.co.nz/#!P8AVUbgL!RK1SYgnFFrLe9Xc6gb9RppuBIJh4k2LNDOMixeqbZwk

and try to run the following command.
> mp4box -add VIDEO_AUDIO_71ch_48kHz.mp4#audio -new test1.mp4
> mp4box -add VIDEO_AUDIO_71ch_96kHz.mp4#audio -new test2.mp4
> mp4box -add VIDEO_AUDIO_71ch_48kHz.mp4#video -add  AUDIO_71ch_48kHz.m4a#audio -new test3.mp4

Thank you.

**Comment by jeanlf** [comment]
thanks for the files - this should now be fixed on git, please confirm and close

jean

**Comment by mayamo** [comment]
Thank you very much for your quick support!

I have confirmed with the following binary.
- gpac-0.5.2-DEV-rev527-gb8912ce-master-x64.exe

It seems that the following two cases are fixed and correctly working.

> mp4box -add VIDEO_AUDIO_71ch_48kHz.mp4#audio -new test1.mp4
> mp4box -add VIDEO_AUDIO_71ch_96kHz.mp4#audio -new test2.mp4

but the following case is not working correctly yet.

> mp4box -add VIDEO_AUDIO_71ch_48kHz.mp4#video -add AUDIO_71ch_48kHz.m4a#audio -new test3.mp4

(When playing the "AUDIO_71ch_48kHz.m4a" in the quicktime player, you can confirm that this file is correct 7.1ch aac file. Quicktime player recognizes this file as 7.1ch)

Thank you.

**Comment by mayamo** [comment]
As for "AUDIO_71ch_48kHz.m4a", I have investigated the file.

It seems that if 7.1ch aac mp4 file have the following condition,
---
track->media->minf->stbl->stsd->mp4a->esds->ES_Descriptor
->DecoderConfigDescriptor->DecoderSpecificInfo->channelconfiguration = 0
and
actual audio channel layout is described by DecoderSpecificInfo->PCE(program_config_element)
---
mp4box recognize the 7.1ch audio as 5ch.

Is there a way to avoid this issue?

Thank you.

**Comment by jeanlf** [comment]
the audio is recognized as 5 ch because this is what is indicated in the program_config_element. Have you tried probing this file with other softwares ?

**Comment by mayamo** [comment]
I tried "AUDIO_71ch_48kHz.m4a" file on quicktime player(Win/Mac) and some of encoder application (e.g. TMPG Video Encoder),and it worked.

This file was generated by qaac.
(qaac is a command line AAC/ALAC encoder frontend based on Apple/QucikTime encoder)

And I think the file is correct from the aac media format aspects.

**Comment by rbouqueau** [comment]
I confirm that MediaInfo detects 8 channels.

**Comment by mayamo** [comment]
Let me summarize current situation.
Regarding "AUDIO_71ch_48kHz.m4a" file, 
- This file have 8ch audio, and it is indicated in the program_config_element
  (and this file is correct file from media format point of view)
- Mediainfo and other applications are able to recognize this file as 8ch audio file
- mp4box cannot recognize this file as 8ch audio file

**Comment by kit90** [comment]
Hi @mayamo , is the 7.1-channel file (AUDIO_71ch_48kHz.m4a) created by qaac compliant with ISO/IEC 14496-3:2009/Amd.4:2013? The reason I've asked is that according to the standard, it should conform to AAC Profile Level 6 (audioProfileLevelIndication = 0x50) and have channelConfiguration = 12 (7.1 with Back speakers).  But your previous post says that it has channelConfiguration = 0.

**Comment by rbouqueau** [comment]
Latest GPAC version seems to have this fixed:
```
$ MP4Box -info VIDEO_AUDIO_71ch_48kHz.mp4
* Movie Info *
        Timescale 90000 - 2 tracks
        Computed Duration 00:00:30.058 - Indicated Duration 00:00:30.058
        Fragmented File: no
        File suitable for progressive download (moov before mdat)
        File Brand mp42 - version 0
        Created: GMT Mon Jul 06 04:30:51 2015
        Modified: GMT Mon Jul 06 04:30:51 2015

File has root IOD (56 bytes)
Scene PL 0xff - Graphics PL 0xff - OD PL 0xff
Visual PL: AVC/H264 Profile (0x7f)
Audio PL: AAC Profile @ Level 6 (0x50)

Track # 1 Info - TrackID 1 - TimeScale 30000
Media Duration 00:00:30.030 - Indicated Duration 00:00:30.030
Track has 1 edit lists: track duration is 00:00:30.030
Media Info: Language "English (eng)" - Type "vide:avc1" - 900 samples
Visual Track layout: x=0 y=0 width=1280 height=720
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x21
AVC/H264 Video - Visual Size 1280 x 720
        AVC Info: 1 SPS - 1 PPS - Profile Main @ Level 4
        NAL Unit length bits: 32
        Pixel Aspect Ratio 1:1 - Indicated track size 1280 x 720
        Chroma format YUV 4:2:0 - Luma bit depth 8 - chroma bit depth 8
        SPS#1 hash: 2D14C496E7C821B20C4C017537283D80116AB317
        PPS#1 hash: 3514895F0054D61C36E72E168C6EEA4C803D7C1F
Synchronized on stream 2
        RFC6381 Codec Parameters: avc1.4d4028
        Average GOP length: 33 samples

Track # 2 Info - TrackID 2 - TimeScale 48000
Media Duration 00:00:30.058 - Indicated Duration 00:00:30.058
Track has 1 edit lists: track duration is 00:00:30.058
Track is present in Root OD
Media Info: Language "English (eng)" - Type "soun:mp4a" - 1409 samples
MPEG-4 Config: Audio Stream - ObjectTypeIndication 0x40
MPEG-4 Audio AAC LC - 8 Channel(s) - SampleRate 48000
Self-synchronized
        RFC6381 Codec Parameters: mp4a.40.2
        All samples are sync
```
