### ISSUE TITLE
An error occurred while compiling the file

### ISSUE THREAD

**Issue by dhbbb** [gpac/gpac#1832]
Hello，when I got the gpac source code and tried to compile them(./configure && make), the following error appeared.

System info：
Ubuntu 20.04 : clang 10.0.0 , gcc 9.3.0

./configure: 2470: source: not found

** System Configuration
Install prefix: /usr/local
Source path: /home/dh/Desktop/gpac-master/gpac-master
C   compiler: gcc
C++ compiler: g++
make: make
CPU: x86_64
Big Endian: no

** GPAC 1.1.0-DEV rev Core Configuration **
Static Modules: no
debug version: no
GProf enabled: no
Memory tracking enabled: no
Sanitizer enabled: no
Fixed-Point Version: no
IPV6 Support: yes
QuickJS Support: yes (qjslibc yes)

** Detected libraries **
zlib: system
OpenGL support: no
TinyGL support: no
OpenSSL support: yes
OSS Audio: yes
ALSA Audio: no
Jack Audio: no
Pulse Audio: no
DirectFB: no
SDL: no
DVB for Linux: yes
FreeType: system
JPEG: no
OpenJPEG: no
PNG: system
MAD: no
FAAD: no
XVID: no
FFMPEG: no
LZMA: no
Xiph OGG: no
Platinum UPnP: no
A52 (AC3): no
OpenSVCDecoder: no
OpenHEVCDecoder: no
Freenect: no
nghttp2: no

Creating config.mak
Check config.log for detection failures
Done - type 'make help' for make info, 'make' to build

...

  CC utils/os_divers.c
utils/os_divers.c:80:10: fatal error: gpac/revision.h: No such file or directory
   80 | #include <gpac/revision.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [../config.mak:144: utils/os_divers.o] Error 1
make[1]: Leaving directory '/home/dh/Desktop/gpac-master/gpac-master/src'
make: *** [Makefile:13: all] Error 2

How to solve this problem？

**Comment by jeanlf** [comment]
how did you get the source ?

**Comment by dhbbb** [comment]
> how did you get the source ?

from https://github.com/gpac/gpac

**Comment by jeanlf** [comment]
using git clone or an archive ?

**Comment by dhbbb** [comment]
> using git clone or an archive ?

archive

**Comment by jeanlf** [comment]
I just tried with 1.0.1 archive, no issue - which archive did you use ?

**Comment by dhbbb** [comment]
> I just tried with 1.0.1 archive, no issue - which archive did you use ?

Thanks for your reply, I downloaded the source code again, compiled it, and it passed.
