### ISSUE TITLE
mp4box split function location | to generate cgo bindings for calling programmatically

### ISSUE THREAD

**Issue by rhobro** [gpac/gpac#1833]
Platform: macOS/linux
Compiler: gcc / go

Hi there. I need to be able to programmatically split an mp4 file into equally sized (not duration) chunks. I found that the mp4box -splits command was the way to go for this. Please could you point me in the direction of the function which does this? I would like to wrap it using CGo so that I can call the function from a Go program instead of calling the executable from the command line. This way, the mp4box splits command will be compiled and packaged with the binary.

Where is the specific function located?

**Comment by jeanlf** [comment]
The split code is [split_isomedia_file](https://github.com/gpac/gpac/blob/master/applications/mp4box/fileimport.c#L1784). It is just a wrapper around a filter session but using a loaded ISO file as input which I doubt you'll need in go.

It is equivalent to the following filter chain:
```src=IN.mp4 reframer:splitrange:xs=SizeInBytes @ dst=IN_$num%03d$.mp4```

The simplest way to achieve what you want would be to provide bindings in your cgo code for:
- gf_sys_init, gf_sys_close
- gf_sys_set_args if you want to pass options to libgpac or global filter options
- gf_fs_new_defaults / gf_fs_new, gf_fs_del
- gf_fs_load_source, gf_fs_load_destination, gf_fs_load_filter
- gf_filter_set_source
- gf_fs_run
- gf_fs_run_step and gf_fs_is_last_task if you plan on using non-blocking filter session
- and the debug helpers gf_fs_print_non_connected, gf_fs_print_stats, gf_fs_print_connections

These are straightforward bindings, using only C strings, integers and opaque pointers for filters and filter session.
With these bindings, you will be able to call most of the filter graphs you can think of.

For advanced processing, such as defining your own filters in go,  you will need to handle slightly more complex things in the bindings (structures, pointer to functions, callbacks). I suggest you take a look at GPAC's  [python bindings](https://github.com/gpac/gpac/blob/master/share/python/libgpac.py).
 

Closing as this is not a GPAC issue, but don't hesitate to keep on discussing this here.

**Comment by jeanlf** [comment]
all headers are in gpac/include/gpac/

**Comment by rhobro** [comment]
Would it be possible to just call mp4boxMain() from the applications/mp4box/main.c file from CGo?

**Comment by rhobro** [comment]
Whenever I try to make bindings, the compiler states that they cannot find the files in include.

**Comment by rhobro** [comment]
Hi, because of include directories and dependencies, it has been challenging to make CGo bindings for all these functions. Would it be possible to add a go package to the repo with bindings for the split functionality or full go bindings?
