### ISSUE TITLE
There is a delay of 5 seconds when switching the bit rate of dash

### ISSUE THREAD

**Issue by xuqiqiang** [gpac/gpac#1851]
We need to switch the bit rate of dash by calling gf_dash_switch_quality method, but there is a delay of 5 seconds. How can I solve it?

**Comment by rbouqueau** [comment]
Please stop cross-posting and be patient.

In addition you need to provide enough information for contributors to reproduce e.g:
> Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by rbouqueau** [comment]
Again: stop cross-posting. I'm closing this one in favour of the better documenter #1852 .
