### ISSUE TITLE
How to specifie the length of the decoding buffer in the New Architecture Configuration

### ISSUE THREAD

**Issue by shiyuyu5** [gpac/gpac#1858]
In the old architecture configuration, i can change the bufferLength in the GPAC.cfg.
But, I cannot find how to specifie the bufferLength in the new architecture configuration?
By the way , where to obtain the old version gpac?
Can you help me?
Thank you for your attention.

**Comment by jeanlf** [comment]
for buffers, please see [here](https://github.com/gpac/gpac/issues/1852#issuecomment-879638661)

Pre-0.9 GPAC builds are still available [here](https://gpac.wp.imt.fr/downloads/gpac-legacy-builds/)
