### ISSUE TITLE
Encrypted multichannel AC-3 audio declared as stereo after dashing

### ISSUE THREAD

**Issue by BucherTomas** [gpac/gpac#1859]
- [x] I looked for a similar issue
- [x] I tried with the latest version of GPAC
- [x] I give enough information for contributors to reproduce my issue

There used to be an issue with encrypted 5.1 audio reported here https://github.com/gpac/gpac/issues/1274. Now it works great for 5.1 encrypted audio in AAC codec, however, it appears that there still needs to be an extra adjustment for AC-3/EC-3 codecs under the same scenario as it reports just 2 channels instead of 6 in the generated mpd even in the latest nightly 1.1.0 GPAC version.

The unencrypted 5.1 audio in AC-3/EC-3 codecs is correctly reported as 6 channels, the hex value in AudioChannelConfiguration is `F801`, which corresponds to the FL, C, FR, LS, RS, LFE mapping. But encrypted audio reports `A000`, which to my knowledge is just basic stereo in 16-bit representation, the result is:
`<Representation id="2" mimeType="audio/mp4" codecs="ac-3" audioSamplingRate="48000" bandwidth="640000">
    <AudioChannelConfiguration schemeIdUri="tag:dolby.com,2014:dash:audio_channel_configuration:2011" value="A000"/>
</Representation>`

The result can be verified with this sample content https://devs.origin.cdn.cra.cz/log/ac3.mp4 in unencrypted form and https://devs.origin.cdn.cra.cz/log/ac3enc.mp4 as encrypted.

Also when dashing the encrypted version, log reports the following notification `[iso file] Unknown box type dac3 in parent enca`.  Interesting thing is that when encrypting EC-3 codec, the message still mentions `dac3` even though the box is actually `dec3`. The file was encrypted by mp4box. and both AC-3 and EC-3 should be supported in ISO format normally I believe.

**Comment by jeanlf** [comment]
The culprit was `dac3`not being allowed in `enca`, now fixed.
The log message for `dec3`was coming from this, `dec3` being internally handled as `dac3` with box type changed to `dec3` only at serialization time, hence this somehow confusing log message...
