### ISSUE TITLE
DashCast and live mpegts udp stream on Windows failed

### ISSUE THREAD

**Issue by fredx21** [gpac/gpac#186]
I'm new to dash and trying to use DashCast to transcode a local live mpegts udp stream. When trying the following command:

```
dashcast -av udp://@127.0.0.1:9998?fifo_size=100000 -live-media
```

I get the following log:

```
Options:
    video source: udp://@127.0.0.1:9998?fifo_size=10000000
    video crop: 0x0
    audio source: udp://@127.0.0.1:9998?fifo_size=10000000
Configurations:
    id:v1       res:640x480     vbr:1000000
    id:a1       abr:192000
[udp @ 00807780] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
[h264 @ 0080aa60] non-existing PPS 0 referenced
[h264 @ 0080aa60] non-existing PPS 0 referenced
[h264 @ 0080aa60] decode_slice_header error
[h264 @ 0080aa60] no frame!
... lots more errors ...
[h264 @ 0080aa60] mmco: unref short failure
[h264 @ 0080aa60] number of reference frames (0+6) exceeds max (5; probably corrupt input), discarding one
[h264 @ 0080aa60] concealing 1210 DC, 1210 AC, 1210 MV errors in I frame
Input #0, mpegts, from 'udp://@127.0.0.1:9998?fifo_size=10000000':
  Duration: N/A, start: 45049.597322, bitrate: 384 kb/s
  Program 3
    Stream #0:0[0x1ff]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 59.94 tbr, 90k tbn, 119.88 tbc
    Stream #0:1[0x140]: Audio: ac3 ([129][0][0][0] / 0x0081), 48000 Hz, 5.1(side), fltp, 384 kb/s
Invalid input framerate 0 (AVCTX timebase is 1001/120000).
Cannot open input video.
```
1. The **circular_buffer_size** error requires a pthread-enabled ffmpeg library. Is that something that can be fixed? Does that mean that udp input cannot be used on Windows?
2. Any idea why it **cannot open input video**? It looks like it did find the video (Stream #0:0[0x1ff] from Program 3)

Regards,
Fred

**Comment by JamesXu20150314** [comment]
Hi, I also develop some project on Windows 7 X64bit with the dashcast. But I don't know how to connect to the video with vfwcap option. Such as:
DashCast -vf vfwcap -vres 1280x720 -vfr 24 -v 0 -live
But I recieve the rusult is : 

C:\Users\Administrator\Desktop\test1>DashCast -vf vfwcap -vres 1280x720 -vfr 24 -v 0 -live
MPD refresh time not set in live - defaulting to segment duration
[34m[1mOptions:
    video source: 0
    video format: vfwcap
    video framerate: 24
    video resolution: 1280x720
    video crop: 0x0
    audio source:
[0m[34m[1mConfigurations:
    id:v1       res:640x480     vbr:400000
    id:a1       abr:192000
[0m[vfwcap @ 0000000000689620] Could not connect to device.
Error -19 opening input - retrying without options
[vfwcap @ 0000000000689480] Could not connect to device.
Cannot open file 0
Cannot open input video.

Can you help me? Thank you very much.
Cannot open input video.

**Comment by cconcolato** [comment]
@JamesXu20150314 please don't cross post.

**Comment by cconcolato** [comment]
@fredx21 I have the same issue as you regarding the pthread part. Will investigate.

**Comment by jeanlf** [comment]
What you describe is now feasible using GPAC 0.9.0 (use gpac, Dashcast is deprecated)
