### ISSUE TITLE
Quicktime doesn't recognise subtitles and other noob related trouble with tagging tracks.

### ISSUE THREAD

**Issue by finnhughes** [gpac/gpac#1861]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [y] I looked for a similar issue and couldn't find any.
- [y] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [y] I give enough information for contributors to reproduce my issue

When I pack srt subs into an mp4, Quicktime isn't recognising the subtitles, e.g. fairly minimal commands:
`gpac -i TOS.264 -i TOS-en.aac:#Language=en -i TOS-it.aac:#Language=it -i TOS-en.srt:#Language=en -i TOS-da.srt:#Language=da -o test.mp4`
`MP4Box -group-add trackID=2:trackID=3 test.mp4`
`MP4Box -group-add trackID=4:trackID=5 test.mp4`
`MP4Box -disable 3 -disable 5 test.mp4`

Side note, I couldn't see how to create the variant groups and disable selected tracks in the gpac command?
I think the problem is that the subtitles are `text:tx3g` not `sbtl:tx3g` but I couldn't see how to change that?

I'm trying to make a more complete test file with UDTA signaling for closed captions and descriptive audio.
I couldn't see how to specify UDTA tags with a string using gpac so instead used MP4Box (from example here https://github.com/gpac/gpac/issues/1606#issuecomment-706069929), but again I couldn't see how to specify both name and tagc in one pass so instead e.g.
`MP4Box -udta 1:type=tagc:str="public.accessibility.describes-video" -lang en TOS_enAD.m4a`
`MP4Box -udta 1:type=name:str="English (describes video)" TOS_enAD.m4a`

I uploaded my 12s tears of steel files here https://www.mediafire.com/file/ll2t0mu25ypaqoo/TOS_quicktime_track_signaling.zip/file
I uploaded a similar file created with ffmpeg where Quicktime recognises the subs here https://www.mediafire.com/file/skd69qm19vjscn4/testffmpeg.mp4/file

**Comment by jeanlf** [comment]
You need to change the QT handler name to `stbl`, using
`MP4Box -i SRC:hdlr=sbtl ... `

It looks like you indeed need the alternate group to be set if multiple subs are present.

> I couldn't see how to specify both name and tagc

simply by specifying multiple times `-udta`

> Side note, I couldn't see how to create the variant groups and disable selected tracks in the gpac command

This was indeed not implemented, now done, along with udta assigning. You can now do:

```
gpac -i test/TOS.264 \
   -i test/TOS-en.aac:#udta_tagc="public.accessibility.describes-video":#udta_name="English (describes video)":#Language=en \
   -i test/TOS-fr.srt:#Language=fr:#AltGroup=2:#StreamSubtype=sbtl:#Disable \
   -i test/TOS-en.srt:#Language=en:#AltGroup=2:#StreamSubtype=sbtl \
  -o result.mp4

```
