### ISSUE TITLE
How to DASH a mp4 video to regular DASH+SRD mode

### ISSUE THREAD

**Issue by xuqiqiang** [gpac/gpac#1865]
How to DASH a mp4 video to regular DASH+SRD mode. Like this:

[http://download.tsi.telecom-paristech.fr/gpac/SRD/360/srd_360.mpd](http://download.tsi.telecom-paristech.fr/gpac/SRD/360/srd_360.mpd)

**Comment by rbouqueau** [comment]
We have some documentation https://github.com/gpac/gpac/wiki/MPEG-DASH-SRD-and-HEVC-tiling-for-VR-videos, have you tried it? There are some other references as well, I let you dig into it.

**Comment by jeanlf** [comment]
If you're not looking for HEVC tiling but simply laying out existing video, use `CropOrigin`or `SRD`+ `SRDRef`properties on input sources - cf [dasher help](https://github.com/gpac/gpac/wiki/dasher#pid-assignment-and-configuration).
