### ISSUE TITLE
Hls playlist byte range offset doesn't seems right

### ISSUE THREAD

**Issue by romainapivideo** [gpac/gpac#1869]
Hello,

I have a problem with hls playlists,I don't know if this is a bug, or if I am missing an option somewhere.

I tested with 1.0.1, and the last master version.

I tested this command
```bash 
MP4Box -dash 4000 \
-profile onDemand \
transcoded_720.mp4#video \
transcoded_720.mp4#audio \
-out manifest.m3u8
```
I tried with the gpac tool directly too.

The resulting playlist is playable with vlc and ffplay for example.
But it fails with videojs or hls.js, only the first segment is played.

Here is the resulting playlist for the video track:
```
#EXTM3U
#EXT-X-TARGETDURATION:4
#EXT-X-VERSION:6
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MAP:URI="transcoded_720_track1__dashinit.mp4",BYTERANGE="960@0"
#EXTINF:4
#EXT-X-BYTERANGE:930114@960
transcoded_720_track1__dashinit.mp4
#EXTINF:4
#EXT-X-BYTERANGE:743971@931074
transcoded_720_track1__dashinit.mp4
#EXTINF:4
#EXT-X-BYTERANGE:314098@1675045
transcoded_720_track1__dashinit.mp4
#EXTINF:4
#EXT-X-BYTERANGE:344031@1989143
transcoded_720_track1__dashinit.mp4
#EXTINF:4
#EXT-X-BYTERANGE:624362@2333174
transcoded_720_track1__dashinit.mp4
#EXTINF:4
#EXT-X-BYTERANGE:531460@2957536
transcoded_720_track1__dashinit.mp4
#EXTINF:4
#EXT-X-BYTERANGE:659193@3488996
transcoded_720_track1__dashinit.mp4
#EXTINF:4
#EXT-X-BYTERANGE:1333882@4148189
transcoded_720_track1__dashinit.mp4
#EXTINF:4
#EXT-X-BYTERANGE:711408@5482071
transcoded_720_track1__dashinit.mp4
#EXTINF:4
#EXT-X-BYTERANGE:293016@6193479
transcoded_720_track1__dashinit.mp4
#EXTINF:4
#EXT-X-BYTERANGE:447909@6486495
transcoded_720_track1__dashinit.mp4
#EXTINF:4
#EXT-X-BYTERANGE:246451@6934404
transcoded_720_track1__dashinit.mp4
#EXTINF:4
#EXT-X-BYTERANGE:314745@7180855
transcoded_720_track1__dashinit.mp4
#EXTINF:4
#EXT-X-BYTERANGE:544987@7495600
transcoded_720_track1__dashinit.mp4
#EXTINF:4
#EXT-X-BYTERANGE:514508@8040587
transcoded_720_track1__dashinit.mp4
#EXTINF:2.28
#EXT-X-BYTERANGE:258588@8555095
transcoded_720_track1__dashinit.mp4

#EXT-X-ENDLIST
```

If I analyze the file with your tool at https://gpac.github.io/mp4box.js/test/filereader.html,
In the segment view I get:

| Segment | referenced_size | segment offset |
|---------|-----------------|---------------|
| 0	 |  930114 |   1836    |
| 1	 |  743971 |   931950  |
| 2	 |  314098 |   1675921 |
| 3	 |  344031 |   1990019 |
| 4	 |  624362 |   2334050 |
| 5	 |  531460 |   2958412 |
| 6	 |  659193 |   3489872 |
| 7	 |  1333882 |   4149065 |
| 8	 |  711408 |   5482947 |
| 9	 |  293016 |   6194355 |
| 10 |  447909 |	 6487371 |
| 11 |  246451 |	 6935280 |
| 12 |  314745 |	 7181731 |
| 13 |  544987 |	 7496476 |
| 14 |  514508 |	 8041463 |
| 15 |  258588 |	 8555971 |

From what I see the segment offset from the online tool doesn't match with the byte range offsets in the playlist.
It seems to be missing 876 bytes for each range in the playlist.
If I replace the byte range starting offsets in the playlist with the ones reported by the online tool it works again 
with videojs and hls.js.

Here is the xml mp4 box dump of the file:
[gpac.md](https://github.com/gpac/gpac/files/6915816/gpac.md)

Is it intended to be like that, or is there a specific option to make it work ?

Regards,
Romain

**Comment by rbouqueau** [comment]
Hi, thanks for the detailed report. This definitely looks like a bug. Let me have a look when I find time (most people are on holidays).

**Comment by jeanlf** [comment]
indeed the sidx/ssix size(s) were not forwarded back to the dasher, resulting in wrong offsets. Could you cross-check with latest HEAD ?

**Comment by romainapivideo** [comment]
Working fine with the last master in videojs and hls.js.

Thank you for the quick fix.

**Comment by romainapivideo** [comment]
I allow myself to re-open the issue.

I think i found an other issue related to hls byte range offsets.

Tested on the last master branch.

This time with this command in manifest only mode
```bash 
MP4Box -dash 4000 \
-profile onDemand \
transcoded_cmaf_video_720.mp4 \
transcoded_cmaf_audio.mp4 \
--dual \
--sigfrag \
-out master.mpd
```

This time the resulting hls playlists are playable with videojs and hlsjs. 
I don't know for other players. Maybe it could impact some hls players.

This time only the first segment is impacted. The other ranges are fine.

Here is the playlist for the video:
```
#EXTM3U
#EXT-X-TARGETDURATION:4
#EXT-X-VERSION:6
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MAP:URI="transcoded_cmaf_video_720.mp4",BYTERANGE="784@0"
#EXTINF:4
#EXT-X-BYTERANGE:930366@784
transcoded_cmaf_video_720.mp4
#EXTINF:4
#EXT-X-BYTERANGE:743991@931150
transcoded_cmaf_video_720.mp4
#EXTINF:4
#EXT-X-BYTERANGE:314118@1675141
transcoded_cmaf_video_720.mp4
... other ranges are fine
#EXT-X-ENDLIST
```

In the segment view from your online tool I get:

| Segment | referenced_size | segment offset |
|---------|-----------------|----------------|
0	| 930134 | 1016	|
1	| 743991 | 931150 |	
2	| 314118 | 1675141 |

For the first segment the starting byte and size doesn't match.
The size of the sidx box is 232, and seems to be the missing offset for the first segment.

Here is the mp4 source file dump:
[gpac.md](https://github.com/gpac/gpac/files/6932172/gpac.md)

Regards

**Comment by jeanlf** [comment]
Indeed, the sidx range was included in the first segment in manifest-only mode. I don't think that's problematic for HLS players, but in doubt I removed it. Thanks for the report!
