### ISSUE TITLE
AAC CBR vs CBR

### ISSUE THREAD

**Issue by ghost** [gpac/gpac#187]
...

**Comment by rbouqueau** [comment]
Hi, thanks for the feedback.

3 remarks:
1) Can you update your MP4Box to the latest version and retry? https://gpac.io/downloads/gpac-nightly-builds/
2) Case 3: could you tell how you extract the aac? If you extract the .aac (with ```-raw```) it is not comparable with case 1) (where you should use ```-raw``` also). Can you precise? Also how does winamp finds that it is CBR or VBR? Changing this at the AU level would indeed be a bug of MP4Box.
3) Case 6: CBR doesn't mean that all AU have the exact same size. So one may still compute a minimum/average/maximi bitrate (how was this information obtained? ```MP4Box -info```?).

Generally speaking, these are informational values. Do they have an impact on following steps of your workflow, or do you write here to inform us of MP4Box behaviour (that can certainly be improved)?

```
-Why mp4box changes "Overall bit rate mode: Constant" and "Bit rate mode: Constant" to "Variable" when creating new .mp4 (vid + audio) when using aac file.
```

I don't know. I think sharing the files would indeed help :)

I would also appreciate if you could retry with the latest MP4Box and let us know about the results.

**Comment by codexredestemp** [comment]
Hi again.
I uploaded test files here: http://www.megafileupload.com/8XxI/test.zip

1) I installed latest mp4box rev529 and I obtained same results in all cases.
2) I extracted aac audio from CASE1 or CASE2 with -raw trackid command.
I added a capture of winamp playing this extracted aac track.
3) Mediainfo and Kmplayer shows "-Maximum bit rate" entry after "Bit rate" entry after creating mp4 CASE 6. I dont know if mp4box activates or creates something inside because these programs does not show "-Maximum bit rate" if I play mp3 CASE 5. I dont know if this is normal.

I like mp4box and I use it since two years ago for my vids. I didnt pay much attention to "-Maximum bit rate" when using mp3. Now I see this "behaivour" with aac files and I dont know if mp4box affects files by some way. I read mp4box cant read some info of aac files and I dont know if this is the case or no. 

Thanks for your help

**Comment by rbouqueau** [comment]
Thanks for files and tests. I'll be back when I have more info.

**Comment by rbouqueau** [comment]
Do you have the source for testaacaud.mp4? (e.g. testaacaud.aac)

MediaInfo detects that everything is VBR in your test files.

**Comment by codexredestemp** [comment]
Are you sure? I have MediaInfo 0.7.75 and it says testaacaud.mp4 (without extracting aac track) is constant and testmp3aud.mp3 is constant (I dont choose vbr mode in Sony Vegas. Even if I mux and then demux still says constant)

The audio source is Fraps audio ( PCM Constant 1411.2 Kbps)

I use Kmplayer 3.6.0.87 and shows same info as Mediainfo.

About testaacaud.mp4: this file is a mp4 rendered without video (CASE 1). Maybe the audio is rendered as variable but Sony Vegas flags it as constant and Mediainfo and other programs detect as constant? In this case, why winamp show its cbr when the file is extracted with -raw command? thats weird :/

**Comment by rbouqueau** [comment]
> Are you sure? I have MediaInfo 0.7.75 and it says testaacaud.mp4 (without extracting aac track)

I was talking about the extracted track. We are aligned for the mp4 interpretation :)

I don't know how these software figure out if an AAC (un-muxed or mp4-muxed) is CBR or VBR (e.g. the info is not in ADTS).

@jeanlf do you know?

**Comment by codexredestemp** [comment]
According to all information I read these days (wikis,forums...) and as you said, cbr does not mean 100% all time. For example I dint know about "bit reservoir" thing in mp3 files :-p

I have done another test. This time with NeroAACenc and this command:

       neroaacenc -cbr 192000 -if inputfile.wav -of outputfile.mp4 (constant)
       neroaacenc -br 192000 -if inputfile.wav -of outputfile.mp4 (target bitrate)
       neroaacenc -q 0.55 -if inputfile.wav -of outputfile.mp4 (q or vbr)

Then I extract the audio track and in all these (nero) cases, Winamp shows its cbr like the capture I uploaded. Even if I choose -q (vbr) option. This means that Winamp must not be trusted in these operations or its a bug.
Mediainfo shows it is variable in all cases (with or without extracting audio).

So the thing is how Sony Vegas creates mp4 when you render with Mainconcept/AVC/AAC option.
Or something is lost when doing an operation (mux or extract) or Sony Vegas does not render at constant mode really.

**Comment by codexredestemp** [comment]
This is Mediainfo code where it tells if an aac is cbr or vbr:

  160 void File_Aac::Streams_Finish()
  ...
  169     if (FrameSize_Min!=(int32u)-1 && FrameSize_Max)
  170     {
  171         if (FrameSize_Max>FrameSize_Min*1.02)
  172         {
  173             Fill(Stream_Audio, 0, Audio_BitRate_Mode, "VBR", Unlimited, true, true);
  174             if (Config->ParseSpeed>=1.0)
  175             {
  176                 Fill(Stream_Audio, 0, Audio_BitRate_Minimum ((float64)FrameSize_Min)/1024*48000*8, 0);
  177                 Fill(Stream_Audio, 0, Audio_BitRate_Maximum, ((float64)FrameSize_Max)/1024*48000*8, 0);
  178             }
  179         }
  180         else if (Config->ParseSpeed>=1.0)
  181         {
  182             Fill(Stream_Audio, 0, Audio_BitRate_Mode, "CBR");
  183         }
  184     }
  185 }

If this is correct, then the aac track from Sony Vegas is constant and mp4box does something or does a different interpretation of the info.

**Comment by codexredestemp** [comment]
Did another test. :P 
Mux with ffmpeg and it keeps audio as constant.
Bye.

**Comment by rbouqueau** [comment]
FYI I still have the files for this issue.

**Comment by jeanlf** [comment]
AFAIK there is no CBR vs VBR signaling of AAC in MP4 files, so I don't know how these software derive this info...

**Comment by rbouqueau** [comment]
We lost on the user description on this one... closing.
