### ISSUE TITLE
Streaming 360 video content

### ISSUE THREAD

**Issue by jakc-1** [gpac/gpac#1870]
Hi, 
I am trying to stream 360 tiled video content. I am streaming video from 360 camera with rtmp to nginx server and generating video content with this:

gpac  -i rtmp://localhost/live ffsws:FID=S -+kvazaar-params=tiles=3x3,slices=tiles,mv-constraint=frametilemargin,rc-algorithm=lambda enc:SID=S:c=libkvazaar:b=1m:fintra=1:rc @ tilesplit:FID=1 enc:SID=S:c=libkvazaar:b=200k:fintra=1:rc @ tilesplit:FID=2 -o live.mpd:SID=1,2:dmode=dynamic

so this produces mpd file and a lot of m4s files. I would like to understand the background of this command (what are the proccesses between input file and mpd output) and I wasn't been able to find some documentation, so I am wondering if you could provide me some information or documentation file. 

Secondly I would like to stream generated mpd file and play it in mp4client. I found this: https://github.com/gpac/gpac/wiki/Tiled-Streaming#how-to-stream-360-video-content, so if I understand correctly, all I should do is 

m4pclient http://localhost/live.mpd#360LIVE 

and this produces hls stream? So on the client side I would select an input http://localhost/live.mpd and it should play?

Thanks for all the information

**Comment by rbouqueau** [comment]
> so this produces mpd file and a lot of m4s files. I would like to understand the background of this command (what are the proccesses between input file and mpd output)

The documentation is here: https://github.com/gpac/gpac/wiki/DASH-basics

> and this produces hls stream?

No it will play it as a media player, like playing any video on your Web browser or VLC (but here the application is MP4Client).

> So on the client side I would select an input http://localhost/live.mpd and it should play?

That's correct: any DASH player that supports 360 tiled video content should be able to play it. Aside from GPAC I'm not aware of other open-source players able to play it.

**Comment by jakc-1** [comment]
Thank you for the documentation link.
So m4pclient http://localhost/live.mpd#360LIVE and selecting http://localhost/live.mpd as an input is basically the same? Do I have to do something else if I want to do: preparing video on server side, playing stored file on laptop in the same network?

**Comment by rbouqueau** [comment]
> m4pclient

MP4Client

> http://localhost/live.mpd#360LIVE 

There was an issue in some occurrences in the documentation. That's ```#LIVE360```, not ```#360LIVE```
http://localhost/live.mpd#360LIVE 

> So m4pclient http://localhost/live.mpd#360LIVE and selecting http://localhost/live.mpd as an input is basically the same?

Both play the content. The #LIVE360 version displays it in VR mode.

> Do I have to do something else if I want to do: preparing video on server side, playing stored file on laptop in the same network?

No, given that you have a way to remote-access the files (e.g. HTTP server ono the "laptop in the same network").

**Comment by jeanlf** [comment]
Also, note that `#360LIVE` will likely be deprecated soon, the preferred way is to use `#VR` as a fragment.
Closing, reopen if you need more help.
