### ISSUE TITLE
GPAC in Python usage steps

### ISSUE THREAD

**Issue by pierrextardif** [gpac/gpac#1871]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hi,

I'm trying to use GPAC with python.
The process is a little tidious as the `libasan.so.5` has to be preloaded, even though I'm using the sanitizer option upon configurating it:

### Configuration //  Compilation
I'm doing :
```sh
./configure --use-ffmpeg=local --enable-debug --prefix=/folder --bindir=/folder/bin --extra-cflags=-I/usr/local/cuda/include -I/folder/include --extra-ldflags=-L/usr/lib -L/usr/local/cuda/lib64 -L/folder/lib --enable-sanitizer
#compile
make -j$(nproc)
sudo make install
```

### Usage
1) Edit `/etc/ld.so.conf` and add `/folder/lib` , then `sudo ldconfig`
2.1) Find libasan : 
```sh
echo 'void foo() {}' | gcc -x c -fPIC -shared -fsanitize=address -
ldd a.out | grep libasan.so | awk '{print $3}'
```
gives me : `/lib/x86_64-linux-gnu/libasan.so.5`

2.2) Preload it :
```sh
LD_PRELOAD="/lib/x86_64-linux-gnu/libasan.so.5" python3 test.py
```

test.py :
```python
import sys
sys.path.append("/folder/share/gpac/python")
import libgpac as gpac

gpac.init()
fs = gpac.FilterSession()
f1 = fs.load_src("/home/pierre/Documents/test.mp4")
f2 = fs.load("vout")
f3 = fs.load("aout")
fs.run()

```
I'm on ubuntu 20.04, running GPAC `1.1.0-DEV-rev1165-gccba035a1-master` .
This seems rather convoluted to get it to work no?
If I'm removing the flag `--enable-sanitizer` then gpac throws the error about the sanitizer:
```sh
==20499==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
```
If I don't add 2), then the python command throws that same error, :/ .

Or am I missing something in my config?

Best, 

P

**Comment by aureliendavid** [comment]
Are you trying to use gpac+python specifically with the sanitizer enabled; or do you just encounter an error when you try not enabling it?

If it's the later then it's probably a misconfiguration from a previous build, you can try running `make distclean` before the `./configure` or try on a clean clone.

**Comment by aureliendavid** [comment]
is `python` alone working fine? is `gpac` alone working?

**Comment by aureliendavid** [comment]
ok so it's not a problem with gpac+python but just an improper gpac build

you are probably loading a libgpac.so from a previous build with asan enabled (from a `make install` maybe?)

try checking `which libgpac.so`, `ldd /path/to/gpac` and `ldd /path/to/libgpac.so`

**Comment by pierrextardif** [comment]
ah yeah.

I always do `sudo make install` as I'm using `-prefix=/folder --bindir=/folder/bin` in the config, therefore I have my `libgpac.so` files copied to `/folder/lib`.
 ldd /folder/bin/gpac 
	linux-vdso.so.1 (0x00007ffe96f08000)
	libasan.so.5 => /lib/x86_64-linux-gnu/libasan.so.5 (0x00007fb706c4e000)
[...]
```


Do you mean I should use `--enable-sanitizer` or not then? because from a fresh install now it seems to be working. Supe weird, but I guess this is resolved, :). I think that `make dist-clean` is sorting it.
Also `which libgpac.so` return nothing (?).

**Comment by aureliendavid** [comment]
> Do you mean I should use `--enable-sanitizer` or not then? because from a fresh install now it seems to be working. Supe weird, but I guess this is resolved, :). I think that `make dist-clean` is sorting it.

you shouldn't enable it 

(unless you explicitly want to do some memory corruption testing on gpac or stuff like that but it doesn't look like that's what you want)

so if your libgpac has a link to libasan in ldd then it's a problem (and probably comes from a previous build where it was enabled)

> Also `which libgpac.so` return nothing (?).

that's ok actually, it was a bad example on my part

glad it's working now

**Comment by pierrextardif** [comment]
ah ok great.
Thanks for your help.
`ldd /folder/bin/gpac` doesn't link to `libasan.so` anymore. In the past i was only using it because the compilation seemed to not work without it, :(; but now it's fine.
