### ISSUE TITLE
How to DASH to this video

### ISSUE THREAD

**Issue by xuqiqiang** [gpac/gpac#1872]
How to DASH a mp4 video to HEVC tile-based dash Like this video:

[http://download.tsi.telecom-paristech.fr/gpac/SRD/srd_hevc/multi_rate_p60/](http://download.tsi.telecom-paristech.fr/gpac/SRD/srd_hevc/multi_rate_p60/)

The video we converted is different from this video. We need to stay the same with it absolutely, please tell me the command with the specific parameters, Thanks!

**Comment by rbouqueau** [comment]
Please read the documentation: https://github.com/gpac/gpac/wiki/MPEG-DASH-SRD-and-HEVC-tiling-for-VR-videos#hevc-motion-constrained-tile-based-adaptation

Let us know if there is anything we can improve.
