### ISSUE TITLE
Choppy playback with live tiled DASH 

### ISSUE THREAD

**Issue by RodolpheFouquet** [gpac/gpac#1873]
### Files

Archive of the files used for this issue: https://www.mediafire.com/file/laq9u10c8jdgecx/tiled_playback_error.zip/file

It contains:
- cnpp.mp4, the video file used as input
- the logs of the player and the encoder sessions

### How to reproduce

Server Side:

```
gpac \
-+kvazaar-params=input-res=256x128,preset=ultrafast,tiles=2x2,slices=tiles,mv-constraint=frametilemargin,\
input-format=P420,qp=16,rc-algorithm=lambda,input-fps=30,gop=0\
erp-aqp=true \
-i cnpp.mp4:FID=I reframer:rt=on:SID=I:FID=R \
ffsws:SID=R:FID=Y:osize=256x128:ofmt=yuv420 \
enc:SID=Y:FID=K1:c=libkvazaar:b=20M:size=256x128:fintra=1:rc \
tilesplit:SID=K1:FID=1 \
-o http://localhost:8080/live.mpd:gpac:dmode\=dynamic:segdur\=4:cdur\=2:asto\=2:llhls\=br:profile\=live:sbound\="closest":rdirs\=outdir:template\=seg_live_:SID\=1 \
-graph -lu -stats  -logs=all@info -log-file=file_to_tiles_server.log
```

Client Side:

`gpac -i http://localhost:8080/live.mpd dashin:tile_mode=center tileagg ohevcdec vout -graph -logs=all@info -lu --skip_lqt -log-file=file_to_tiles_player.log`

### Observed behaviour

The playback is choppy. Every N seconds, the playback stops, I see the segments being downloaded in the terminal, and starts again. This behaviour is only observed in tiled mode, when the tiling parameters are removed from the encoder (tilesplit acting then as a pass-through) and from the client, everything plays smoothly.

The encoder seems to run perfectly, however it displays warnings like this:

```
UTC 2021-08-08T19:15:12Z (TS 1628450112654) - [Dasher] AS-1 Rep 1 segment 3 done TOO LATE by 1000 ms
UTC 2021-08-08T19:15:12Z (TS 1628450112654) - [Dasher] AS-1 Rep 2 segment 3 done TOO LATE by 1000 ms
UTC 2021-08-08T19:15:12Z (TS 1628450112654) - [Dasher] AS-1 Rep 3 segment 3 done TOO LATE by 1000 ms
UTC 2021-08-08T19:15:12Z (TS 1628450112654) - [Dasher] AS-1 Rep 4 segment 3 done TOO LATE by 1000 ms
UTC 2021-08-08T19:15:12Z (TS 1628450112654) - [Dasher] AS-1 Rep 5 segment 3 done TOO LATE by 1000 ms
```
When the same configuration is ran with tiling disabled, the same warning appears (though only once since there is only one representation), though it seems to have no impact on the playback.

I have tried also by disabling the lowlatency mode on the player and encoder side, the playback is still choppy.

### Configuration

OS: Ubuntu 20.04
Version: f42841f7105433023fcbdace975713873474ac95 compiled in release 

---
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by RodolpheUnicowd** [comment]
Side Note:

I should also precise that playing with the values of cdur and asto did not change anything. Even with a segdur of 8 seconds, and asto of 4, and a cdur of 4 did not change a thing.

**Comment by RodolpheFouquet** [comment]
Hello, could you reproduce this issue?

**Comment by jeanlf** [comment]
A few issues here:

- using `sbound=closest` will force the dasher to buffer until the next sap to take a decision, which in your case will flush the segment 1s (eg 1 intra period) too late, hence the log message
- the DASH client doesn't support low latency for tiling or scalable, dependent segments are downloaded sequentially
- we had some bugs upon 404 resulting in unalignment of tile tracks' sequence numbers. 

Could you try with latest master?

**Comment by RodolpheFouquet** [comment]
Version: version 1.1.0-DEV-rev1218-g60db13838-master

Encoder command

```
gpac \
-+kvazaar-params=input-res=256x128,preset=ultrafast,tiles=2x2,slices=tiles,mv-constraint=frametilemargin,\
input-format=P420,qp=16,rc-algorithm=lambda,input-fps=30,gop=0\
erp-aqp=true \
-i cnpp.mp4:FID=I reframer:rt=on:SID=I:FID=R \
ffsws:SID=R:FID=Y:osize=256x128:ofmt=yuv420 \
enc:SID=Y:FID=K1:c=libkvazaar:b=2M:size=256x128:fintra=1:rc \
tilesplit:SID=K1:FID=1 \
-o http://localhost:8080/live.mpd:gpac:dmode\=dynamic:segdur\=4:cdur\=2:asto\=2:llhls\=off:profile\=live:rdirs\=outdir:template\=seg_live_:SID\=1 \
-graph -lu -stats   -logs=all@info -log-file=file_to_tiles_server.log
```


Player command:

` gpac -i http://localhost:8080/live.mpd dashin:tile_mode=center:lowlat=no tileagg ohevcdec vout -graph -logs=all@info -lu -log-file=file_to_tiles_player.log`

I am still experiencing the same behaviour.

[Encoding logs](https://www.mediafire.com/file/p24hpmihwlaqitg/file_to_tiles_server.log/file)
[Playback logs](https://www.mediafire.com/file/18o3rgo3ugu76ro/file_to_tiles_player.log/file)

**Comment by jeanlf** [comment]
As I said, the dash demuxer does not support low latency for tiled tracks or scalable content, which means your content is played as a regular session, 4s (one segment) after the other. You need to adjust the playback buffer to be at least one segment duration in this case (eg, `vout:buffer=4000`), otherwise you will experience buffer underflows (press `i` in window when using vout to see the stats/graph).

I will try to add automatic buffer notification for this case, however enabling low-latency tiling is not on our roadmap.

**Comment by RodolpheFouquet** [comment]
Hi, indeed, issue fixed.

I thought that disabling the lowlat flag on the dashin + disabling it on the dasher would automatically turn on buffering.

**Comment by jeanlf** [comment]
> I thought that disabling the lowlat flag on the dashin + disabling it on the dasher would automatically turn on buffering.

not yet, patching this right now...
