### ISSUE TITLE
There is a issue when playing this video

### ISSUE THREAD

**Issue by xuqiqiang** [gpac/gpac#1874]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

We played the following video with GPAC Android official APK, and found some issue.
[https://drive.google.com/file/d/1tprzU_k0bMbkPfum7SkPsSaddnTlm1sp/view?usp=sharing](https://drive.google.com/file/d/1tprzU_k0bMbkPfum7SkPsSaddnTlm1sp/view?usp=sharing)

The video would get stuck at about 15s. But it worked fine with Windows exe.

**Comment by jeanlf** [comment]
could you try to play the reaggregated file ? 

To produce it:
`gpac -i dance_3840/tiled.mpd tileagg @ @@#audio -o dance_reagg.mp4`

**Comment by jeanlf** [comment]
no follow-up, closing
