### ISSUE TITLE
Live streaming with kvazaar - Low quality

### ISSUE THREAD

**Issue by laidactienbn** [gpac/gpac#1875]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hello, I am using gpac with kvazaar to live stream. Although it seems like a problem from kvazaar. However, I would like to seek for support from you. I hope that you guys can collaborate.

https://github.com/ultravideo/kvazaar/issues/307#issue-970080319

Thank you very much.

**Comment by jeanlf** [comment]
I see you closed the issue on kvazaar - is the only change you did related to 'input-fps' ?

**Comment by laidactienbn** [comment]
> I see you closed the issue on kvazaar - is the only change you did related to 'input-fps' ?

Hello jeanlf,
Yes, the only thing that I did is to change -input-fps from `enc:` to `kvazaar-params:`

**Comment by jeanlf** [comment]
weill `input-fps` is not a parameter for ffenc so no wonder you had to put it in `kvazaar-params`.
I think the issue is that the grabber filter (ffavin) doesn't forward the FPS , so it's not remapped to libkvazaar... 

Could you try removing `input-fps` and use ` -i video://:fmt=avfoundation:dev="0":#FPS=25` as a source (this will force the video pid FPS property) ? If working, I'll look into patching the grabber.

**Comment by laidactienbn** [comment]
> weill `input-fps` is not a parameter for ffenc so no wonder you had to put it in `kvazaar-params`.
> I think the issue is that the grabber filter (ffavin) doesn't forward the FPS , so it's not remapped to libkvazaar...
> 
> Could you try removing `input-fps` and use ` -i video://:fmt=avfoundation:dev="0":#FPS=25` as a source (this will force the video pid FPS property) ? If working, I'll look into patching the grabber.

I tried it and it worked

**Comment by jeanlf** [comment]
great, I'll patch asap

**Comment by jeanlf** [comment]
I think I got it - could you try with latest master, not setting frame rate at all ?

**Comment by laidactienbn** [comment]
> I think I got it - could you try with latest master, not setting frame rate at all ?

I tried with no frame rate setting and it shows the low-quality video like the problem at first.

**Comment by jeanlf** [comment]
Hmm that's weird. Could you check that you have a `FPS` property listed in the output of
`gpac -i video://:fmt=avfoundation:dev="0" inspect`

**Comment by laidactienbn** [comment]
![image](https://user-images.githubusercontent.com/74363562/132084689-07637618-194a-4fdc-be75-5c74fc02a171.png)

I don't see FPS property

> Hmm that's weird. Could you check that you have a `FPS` property listed in the output of
> `gpac -i video://:fmt=avfoundation:dev="0" inspect`

![image](https://user-images.githubusercontent.com/74363562/132084701-106696ea-5c1c-4b02-a531-3cf09e0486d7.png)

I don't see FPS property listed.

**Comment by jeanlf** [comment]
Hmm looks like you're still using an old version of GPAC, because the `FPS` property is now always set by ffdmx/ffavin. Could you double check you version ?

**Comment by laidactienbn** [comment]
![image](https://user-images.githubusercontent.com/74363562/132373953-b891cb0f-45e6-47c0-9206-0bfd9db58302.png)
I think it is the latest version


> Hmm looks like you're still using an old version of GPAC, because the `FPS` property is now always set by ffdmx/ffavin. Could you double check you version ?

**Comment by jeanlf** [comment]
no, `revUNKNOWN` means you are not on git master HEAD - how did you install ?

**Comment by laidactienbn** [comment]
> no, `revUNKNOWN` means you are not on git master HEAD - how did you install ?

I follow the instruction in this link: https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-OSX
I changed the clone line to:
`https://github.com/gpac/gpac.git` instead of `https://github.com/gpac/gpac.git/gpac_public` because if I cloned gpac_public, there would be no `libkvazaar`

**Comment by jeanlf** [comment]
using this method you should have a proper revision in `[build_dir]/include/gpac/revision.h`, not `revUNKNOWN` - what does it say ?
Also make sure you uninstall / reinstall.

**Comment by laidactienbn** [comment]
> using this method you should have a proper revision in `[build_dir]/include/gpac/revision.h`, not `revUNKNOWN` - what does it say ?
> Also make sure you uninstall / reinstall.

![image](https://user-images.githubusercontent.com/74363562/132726401-c39af93c-b404-4e41-b1b4-2758cb2590df.png)

Here is the `revision.h` file. Should I uninstall and reinstall now?

**Comment by laidactienbn** [comment]
![image](https://user-images.githubusercontent.com/74363562/132731715-6f73555a-6acf-45ac-b21a-eef0e711495e.png)
I reinstalled gpac. This is the new one.

I tried remove FPS option and it runned smoothly. Thank you for supporting.


However, I encountered some error while building gpac.
Specifically, when runnning `deps_unix$ ./build_all.sh osx`, it returned some errors like no `abs` in `/Users/tienld/gpac/deps_unix/opensvc/svcsvn/SVC/lib_svc/Fill_caches_svc.c` and some other files. I solved by adding `#include <stdlib.h>` in each file but it took quite a long time to fix. Could you please recheck the build?

**Comment by jeanlf** [comment]
indeed opensvc no longer compiles with latest toolchain. @aureliendavid could we patch [type.h](https://github.com/gpac-buildbot/opensvc/blob/69ec06db4ca0697b27be61191959e26f5b181d19/svcsvn/AVC/h264_baseline_decoder/lib_baseline/type.h) to add include for stdlib.h ?

**Comment by aureliendavid** [comment]
Hi, 

Can you tell me which versions of macos, xcode, etc. you have to get this issue? 

I can't seem to reproduce it on the machine I have set up with:

- macos 11.5.2
- xcode 11.3.1
- cmake 3.21.2
- homebrew 3.2.11

Also if you have a opensvc/svcsvn/CMakeCache.txt file from a previous build, you may need to remove it.

**Comment by aureliendavid** [comment]
ok I can reproduce it with xcode 12.5, will fix

**Comment by aureliendavid** [comment]
ok if you `git pull && git submodule update` (or equivalent) on the `deps_unix` repo it should now build on the latest macos setup

**Comment by laidactienbn** [comment]
> ok if you `git pull && git submodule update` (or equivalent) on the `deps_unix` repo it should now build on the latest macos setup

Thank you
