### ISSUE TITLE
MPEG-DASH lost final part when run with HTML5

### ISSUE THREAD

**Issue by thanhnv1986** [gpac/gpac#188]
I use this command
```
MP4Box -dash 11000 -rap -segment-name "%s_" input_video.mp4:bandwidth=105000 input_audio.mp4:bandwidth=57000
```
Case 1: MP4Box - GPAC version 0.5.1-DEV-rev5619
it working with HTML5 but it error in DASH player with flash (link player https://github.com/castlabs/dashas)

Case2: MP4Box - GPAC version 0.5.2-DEV-rev528-gd0ba24c-master
it working with DASH player but it lost final part when i run with HTML5.

Please help me. Thank you.

**Comment by rbouqueau** [comment]
Why is the title name ''lost final part"? Does your issue only concern the final part of your content playback?

**Comment by thanhnv1986** [comment]
In beginning I did not use parameter -profile dashavc264:live, when playing video on Android, the player cannot play last segement.

After I add -profile dashavc264:live, when I forward video long range, the Dash.js player frozen.

On Windows Phone with  -profile dashavc264:live, short video less than 5 minutes, the Dash.js player can play well,

If video is longer than 10 minutes, the Dash.js player has only black screen, and play audio only.

On Desktop, everything runs perfectly.

Do you think problem come from Dash.js player when it plays on Android and Windows Phone?

**Comment by rbouqueau** [comment]
Does the content pass the conformance test from http://www.dashif.org/conformance.html ?

**Comment by thanhnv1986** [comment]
We passed it
![screen shot 2015-07-10 at 6 35 51 pm](https://cloud.githubusercontent.com/assets/3871494/8617885/87a793e8-2732-11e5-993e-634075f8e8a7.png)

Can you check my resource?
https://www.mediafire.com/?3yy30quhoykl03u
Thank you.

**Comment by rbouqueau** [comment]
At this point I would advise you to contact the support from the players and tell them the content seems ok according to the conformance checker.

**Comment by cconcolato** [comment]
FYI, it is working well with MP4Client.

**Comment by thanhnv1986** [comment]
I will check it, thank everyone
