### ISSUE TITLE
GPAC hevc-tiling live streaming setup not support 4K or above

### ISSUE THREAD

**Issue by Lisuibiao** [gpac/gpac#1880]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hi GPAC Devs,

I followed the official wiki guidance and setup a hevc tiling live streaming on a linux server, building latest gpac main branch code and ffmpeg with libkvazaar.  

Everything works fine when the input stream res is 1920x960. But when I change the stream res to 3840x1920, I can not get the output dash stream to play. The gpac player (windows based) continues to pop error infos like this: 
**[DASH] Error in downloading new segment http://192.168.1.213:8070/stream/liveTest4K/live_dash_track1_20.m4s: Requested URL is not valid or cannot be found**.

Would you guys kindly help me out of this?
Thank you very much.

**Hardware env:** 
On-line CPU(s) list:   0-63
Intel Core Processor (Broadwell, no TSX, IBRS)
CPU MHz：             2095.076
BogoMIPS：            4190.15
KiB Mem :                65798908 total

**Command lines:** 
gpac -i 'rtmp://192.168.1.171/live'  \
ffsws:FID=S  \
-+kvazaar-params=tiles=8x4,slices=tiles,preset=ultrafast,bipred=0,mv-constraint=frametilemargin,rc-algorithm=lambda  \
enc:SID=S:c=libkvazaar:b=10m:rc @ tilesplit:FID=1  \
enc:SID=S:c=libkvazaar:b=1m:rc @ tilesplit:FID=2  \
-o /home/web/data/stream/liveTest4K/live.mpd:SID=1,2:dmode=dynamic

**And the output:**
No filter chain found for PID audio1 in filter ffdmx to any loaded filters - NOT CONNECTED
Disabling TMVP because tiles are used.
Disabling WPP because tiles were enabled.
Using preset ultrafast: --rd=0 --pu-depth-intra=2-3 --pu-depth-inter=1-2 --me=hexbs --gop=8 --ref=1 --bipred=1 --deblock=0:0 --signhide=0 --subme=0 --sao=off --rdoq=0 --rdoq-skip=0 --transform-skip=0 --mv-rdo=0 --full-intra-search=0 --smp=0 --amp=0 --cu-split-termination=zero --me-early-termination=sensitive --intra-rdo-et=0 --early-skip=1 --fast-residual-cost=28 --max-merge=5
Compiled: INTEL, flags: MMX SSE SSE2
Detected: INTEL, flags: MMX SSE SSE2 SSE3 SSSE3 SSE41 SSE42 AVX AVX2
Available: avx(11) avx2(54) sse2(2) sse41(4)
In use: avx(1) avx2(54)
--owf=auto value set to 2.
--threads=auto value set to 32.
Disabling TMVP because tiles are used.
Disabling WPP because tiles were enabled.
Using preset ultrafast: --rd=0 --pu-depth-intra=2-3 --pu-depth-inter=1-2 --me=hexbs --gop=8 --ref=1 --bipred=1 --deblock=0:0 --signhide=0 --subme=0 --sao=off --rdoq=0 --rdoq-skip=0 --transform-skip=0 --mv-rdo=0 --full-intra-search=0 --smp=0 --amp=0 --cu-split-termination=zero --me-early-termination=sensitive --intra-rdo-et=0 --early-skip=1 --fast-residual-cost=28 --max-merge=5
Compiled: INTEL, flags: MMX SSE SSE2
Detected: INTEL, flags: MMX SSE SSE2 SSE3 SSSE3 SSE41 SSE42 AVX AVX2
Available: avx(22) avx2(108) sse2(4) sse41(8)
In use: avx(2) avx2(108)
--owf=auto value set to 2.
--threads=auto value set to 32.
Disabling TMVP because tiles are used.
Disabling WPP because tiles were enabled.
Using preset ultrafast: --rd=0 --pu-depth-intra=2-3 --pu-depth-inter=1-2 --me=hexbs --gop=8 --ref=1 --bipred=1 --deblock=0:0 --signhide=0 --subme=0 --sao=off --rdoq=0 --rdoq-skip=0 --transform-skip=0 --mv-rdo=0 --full-intra-search=0 --smp=0 --amp=0 --cu-split-termination=zero --me-early-termination=sensitive --intra-rdo-et=0 --early-skip=1 --fast-residual-cost=28 --max-merge=5
Compiled: INTEL, flags: MMX SSE SSE2
Detected: INTEL, flags: MMX SSE SSE2 SSE3 SSSE3 SSE41 SSE42 AVX AVX2
Available: avx(33) avx2(162) sse2(6) sse41(12)
In use: avx(3) avx2(162)
--owf=auto value set to 2.
--threads=auto value set to 32.
Disabling TMVP because tiles are used.
Disabling WPP because tiles were enabled.
Using preset ultrafast: --rd=0 --pu-depth-intra=2-3 --pu-depth-inter=1-2 --me=hexbs --gop=8 --ref=1 --bipred=1 --deblock=0:0 --signhide=0 --subme=0 --sao=off --rdoq=0 --rdoq-skip=0 --transform-skip=0 --mv-rdo=0 --full-intra-search=0 --smp=0 --amp=0 --cu-split-termination=zero --me-early-termination=sensitive --intra-rdo-et=0 --early-skip=1 --fast-residual-cost=28 --max-merge=5
Compiled: INTEL, flags: MMX SSE SSE2
Detected: INTEL, flags: MMX SSE SSE2 SSE3 SSSE3 SSE41 SSE42 AVX AVX2
Available: avx(44) avx2(216) sse2(8) sse41(16)
In use: avx(4) avx2(216)
--owf=auto value set to 2.
--threads=auto value set to 32.
[Dasher] AS-1 Rep 1 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 3 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 35 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 4 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 36 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 5 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 37 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 6 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 38 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 7 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 39 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 8 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 40 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 9 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 41 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 10 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 42 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 11 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 43 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 12 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 44 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 13 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 45 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 14 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 46 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 15 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 47 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 16 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 48 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 17 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 49 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 18 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 50 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 19 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 51 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 20 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 52 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 21 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 53 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 22 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 54 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 23 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 55 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 24 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 56 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 25 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 57 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 26 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 58 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 27 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 59 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 28 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 60 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 29 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 61 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 30 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 62 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 31 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 63 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 32 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 64 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 33 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 65 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 34 segment 1 done TOO LATE by 907 ms
[Dasher] AS-1 Rep 66 segment 1 done TOO LATE by 907 ms
[MP4Mux] PID video1_tile1 ID 3 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile2 ID 4 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile3 ID 5 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile4 ID 6 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile5 ID 7 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile6 ID 8 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile7 ID 9 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile8 ID 10 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile9 ID 11 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile10 ID 12 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile11 ID 13 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile12 ID 14 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile13 ID 15 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile14 ID 16 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile15 ID 17 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile16 ID 18 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile17 ID 19 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile18 ID 20 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile19 ID 21 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile20 ID 22 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile21 ID 23 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile22 ID 24 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile23 ID 25 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile24 ID 26 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile25 ID 27 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile26 ID 28 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile27 ID 29 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile28 ID 30 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile29 ID 31 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile30 ID 32 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile31 ID 33 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile32 ID 34 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1 ID 2 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile1 ID 3 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile2 ID 4 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile3 ID 5 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile4 ID 6 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile5 ID 7 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile6 ID 8 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile7 ID 9 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile8 ID 10 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile9 ID 11 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile10 ID 12 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile11 ID 13 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile12 ID 14 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile13 ID 15 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile14 ID 16 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile15 ID 17 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile16 ID 18 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile17 ID 19 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile18 ID 20 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile19 ID 21 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile20 ID 22 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile21 ID 23 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile22 ID 24 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile23 ID 25 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile24 ID 26 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile25 ID 27 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile26 ID 28 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile27 ID 29 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile28 ID 30 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile29 ID 31 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile30 ID 32 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile31 ID 33 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration
[MP4Mux] PID video1_tile32 ID 34 Sample 31 with DTS 1000 less than previous sample DTS 1000, adjusting prev sample duration

**Comment by jeanlf** [comment]
can you run the same setup but not live and play the result ?

**Comment by jeanlf** [comment]
also can you try without any preset for kvazaar ?

**Comment by jeanlf** [comment]
The MP4Mux warning was due to a bug in kvazaar fixed some time ago. 
Closing - feel free to add further report.
