### ISSUE TITLE
MP4Box Split video formatted output

### ISSUE THREAD

**Issue by jw-star** [gpac/gpac#1882]
```
MP4Box -splits 20176 aa.mp4
```
aa_001.mp4
aa_002.mp4

how to output

aa001.mp4
aa002.mp4

**Comment by jeanlf** [comment]
I updated the [documentation](https://github.com/gpac/gpac/wiki/mp4box-dump-opts#file-splitting), you need to do:
`MP4Box -splits 20176 aa.mp4 -out aa$num%03d$.mp4`

**Comment by jw-star** [comment]
When I execute the use case in the document, it fails
```
root@vultr:~/gpac_public/bin/gcc# ./MP4Box -splits 20176 aa.mp4 -out aa$num%04d$.mp4
splitting: file 1 done
splitting: file 2 done
[FileOut] re-opening in write mode output file aa%04d$.mp4, content overwrite (use `cat` option to enable append)

```

**Comment by jw-star** [comment]
> I updated the [documentation](https://github.com/gpac/gpac/wiki/mp4box-dump-opts#file-splitting), you need to do:
> `MP4Box -splits 20176 aa.mp4 -out aa$num%03d$.mp4`

**Comment by jeanlf** [comment]
you llikely need to quote or escape the `$` for your prompt:

`-out 'aa$num%04d$.mp4'`

or

`-out aa\$num%04d\$.mp4`

**Comment by jw-star** [comment]
> you llikely need to quote or escape the `$` for your prompt:
> 
> `-out 'aa$num%04d$.mp4'`
> 
> or
> 
> `-out aa\$num%04d\$.mp4`

It's okay, thank you very much for the author's patient answer
