### ISSUE TITLE
MP4Box DASH: :baseURL should be relative to '-out', not the local folder

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#189]

**Comment by blacktrash** [comment]
@rbouqueau - thanks for fixing this. I had opened a bug on sourceforge, currently down: https://sourceforge.net/p/gpac/bugs/351 - as I can confirm that the fix works, you can close it there, once sf is up again.

**Comment by blacktrash** [comment]
@rbouqueau - spoke to soon (wishful thinking): the baseUrl still is duplicated in the mpd, and if I don't add it to `--segment-name`, then all segments are created in the current directory.

**Comment by rbouqueau** [comment]
I'm going to reopen. I'll take time to test all the use cases later.

Take care that the buildbot seems to be stopped. So you need to compile MP4Box by your own means (writing a blog article on this btw, should be online before this Friday - feedbacks welcome)

**Comment by rbouqueau** [comment]
And thanks for your messages, it helps imrpving the software.

**Comment by blacktrash** [comment]
> I'm going to reopen. I'll take time to test all the use cases later.

No prob. I can manage with a little sed script.

> Take care that the buildbot seems to be stopped. So you need to compile MP4Box by your own means

I rolled git HEAD on my own for testing. I'm certain that your changes were in - famous loast words ;-)

**Comment by blacktrash** [comment]
@rbouqueau - https://github.com/gpac/gpac/issues/219
Sorry, forgot about this one. It's still happening with MP4Box - GPAC version 0.5.2-DEV-rev623-g1ede7f5-master

**Comment by jeanlf** [comment]
please check #219
