### ISSUE TITLE
Muxing av1 in .ivf format to .mp4 adds more sample descriptions than necessary

### ISSUE THREAD

**Issue by dimitry-unified-streaming** [gpac/gpac#1907]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

This is with gpac master 8d9ccb02e (`GPAC1.1.0-DEV-rev1210-g8d9ccb02e-master`). The issue is not dependent on the host operating system, but for your information, I am using Ubuntu Linux 20.04 LTS here.

As input we have a AV1 elementary stream, provided as a [input.ivf](https://live.unified-streaming.com/dimitry/gpac-av1-mux/input.ivf) file (~347 MiB). We then create a progressive MP4 file using MP4Box, e.g.:

```
MP4Box -add input.ivf output.mp4
```

The resulting MP4 file has more sample descriptions than necessary, because it repeats the first sample description, but leaves out the Sequence Header OBU. E.g., the first sample description contains the Sequence Header OBU, followed by two metadata OBUs (HDR_MDCV and HDR_CLL), while the second sample description contains *only* the same two identical metadata OBUs:

```xml
<SampleTableBox Size="30487" Type="stbl" Specification="p12" Container="minf">
  <SampleDescriptionBox Size="359" Type="stsd" Version="0" Flags="0" Specification="p12" Container="stbl">
    <AV1SampleEntryBox Size="190" Type="av01" Specification="av1" Container="stsd" DataReferenceIndex="1" Width="3840" Height="2160" XDPI="4718592" YDPI="4718592" BitDepth="24">
      <AV1ConfigurationBox>
        <AV1Config version="1" profile="0" level_idx0="12" tier="0" high_bitdepth="1" twelve_bit="0" monochrome="0" chroma_subsampling_x="1" chroma_subsampling_y="1" chroma_sample_position="0" initial_presentation_delay="1" OBUs_count="3">
          <OBU type="1" name="seq_header" size="17" content="data:application/octet-string,0A0F00000062EFBFE1BDDBF9D091009140"/>
          <OBU type="5" name="metadata" size="28" content="data:application/octet-string,2A1A02AE1451EC43D0B0A426660F5C500D54390003E8000000000280"/>
          <OBU type="5" name="metadata" size="8" content="data:application/octet-string,2A060102DF011880"/>
        </AV1Config>
      </AV1ConfigurationBox>
      <ColourInformationBox Size="19" Type="colr" Specification="iff" Container="video_sample_entry ipco encv resv" colour_type="nclx" colour_primaries="9" transfer_characteristics="16" matrix_coefficients="9" full_range_flag="0">
</ColourInformationBox>
      <BitRateBox Size="20" Type="btrt" Specification="p12" Container="sample_entry" BufferSizeDB="1690167" avgBitRate="11054528" maxBitRate="48834496">
</BitRateBox>
    </AV1SampleEntryBox>
    <AV1SampleEntryBox Size="153" Type="av01" Specification="av1" Container="stsd" DataReferenceIndex="1" Width="3840" Height="2160" XDPI="4718592" YDPI="4718592" BitDepth="24">
      <AV1ConfigurationBox>
        <AV1Config version="1" profile="0" level_idx0="12" tier="0" high_bitdepth="1" twelve_bit="0" monochrome="0" chroma_subsampling_x="1" chroma_subsampling_y="1" chroma_sample_position="0" initial_presentation_delay="1" OBUs_count="2">
          <OBU type="5" name="metadata" size="28" content="data:application/octet-string,2A1A02AE1451EC43D0B0A426660F5C500D54390003E8000000000280"/>
          <OBU type="5" name="metadata" size="8" content="data:application/octet-string,2A060102DF011880"/>
        </AV1Config>
      </AV1ConfigurationBox>
      <ColourInformationBox Size="19" Type="colr" Specification="iff" Container="video_sample_entry ipco encv resv" colour_type="nclx" colour_primaries="9" transfer_characteristics="16" matrix_coefficients="9" full_range_flag="0">
</ColourInformationBox>
    </AV1SampleEntryBox>
  </SampleDescriptionBox>
```

In the `SampleToChunkBox` you can see that it flips between these two sample descriptions:

```xml
<SampleToChunkBox Size="2176" Type="stsc" Version="0" Flags="0" Specification="p12" Container="stbl" EntryCount="180">
  <SampleToChunkEntry FirstChunk="1" SamplesPerChunk="1" SampleDescriptionIndex="1"/>
  <SampleToChunkEntry FirstChunk="2" SamplesPerChunk="11" SampleDescriptionIndex="2"/>
  <SampleToChunkEntry FirstChunk="3" SamplesPerChunk="12" SampleDescriptionIndex="2"/>
  <SampleToChunkEntry FirstChunk="12" SamplesPerChunk="1" SampleDescriptionIndex="1"/>
  <SampleToChunkEntry FirstChunk="13" SamplesPerChunk="11" SampleDescriptionIndex="2"/>
  <SampleToChunkEntry FirstChunk="14" SamplesPerChunk="12" SampleDescriptionIndex="2"/>
  <SampleToChunkEntry FirstChunk="23" SamplesPerChunk="1" SampleDescriptionIndex="1"/>
  <SampleToChunkEntry FirstChunk="24" SamplesPerChunk="11" SampleDescriptionIndex="2"/>
...
  <SampleToChunkEntry FirstChunk="577" SamplesPerChunk="1" SampleDescriptionIndex="1"/>
  <SampleToChunkEntry FirstChunk="578" SamplesPerChunk="7" SampleDescriptionIndex="2"/>
  <SampleToChunkEntry FirstChunk="579" SamplesPerChunk="12" SampleDescriptionIndex="2"/>
  <SampleToChunkEntry FirstChunk="588" SamplesPerChunk="4" SampleDescriptionIndex="2"/>
  <SampleToChunkEntry FirstChunk="589" SamplesPerChunk="1" SampleDescriptionIndex="1"/>
  <SampleToChunkEntry FirstChunk="590" SamplesPerChunk="7" SampleDescriptionIndex="2"/>
  <SampleToChunkEntry FirstChunk="591" SamplesPerChunk="12" SampleDescriptionIndex="2"/>
  <SampleToChunkEntry FirstChunk="600" SamplesPerChunk="2" SampleDescriptionIndex="2"/>
  <!-- counted 6314 samples in STSC entries (could be less than sample count) -->
</SampleToChunkBox>
```

But it seems that having more than one sample description is not needed at all. You could have just the first sample description, and point all the samples to that first one, since the Metadata OBUs are exactly the same, and any valid sample description should really contain a Sequence Header OBU. At least, this is how I would interpret the [AV1 Codec ISO Media File Format Binding](https://cdn.rawgit.com/AOMediaCodec/av1-isobmff/v1.1.0/).

I did some debugging of the logic in `src/filters/mux_isom.c` and `src/filters/reframe_av1.c`, and it turns out that the `mp4_mux_setup_pid()` function (in `src/filters/mux_isom.c`) concludes every few samples that the decoder config changed. I.e. `needs_sample_entry` gets set to nonzero, because the CRC of the `GF_PROP_PID_DECODER_CONFIG` property changed. However, this change is only because `av1dmx_check_pid()` (in `src/filters/reframe_av1.c`) always throws away *all* OBUs and starts from scratch:

```c
        } else if (ctx->is_av1) {
                //first or config changed, compute dsi
                while (gf_list_count(ctx->state.config->obu_array)) {
                        GF_AV1_OBUArrayEntry *a = (GF_AV1_OBUArrayEntry*) gf_list_pop_back(ctx->state.config->obu_array);
                        if (a->obu) gf_free(a->obu);
                        gf_free(a);
                }
                dsi = NULL;
                dsi_size = 0;
                while (gf_list_count(ctx->state.frame_state.header_obus)) {
                        GF_AV1_OBUArrayEntry *a = (GF_AV1_OBUArrayEntry*) gf_list_get(ctx->state.frame_state.header_obus, 0);
                        gf_list_add(ctx->state.config->obu_array, a);
                        gf_list_rem(ctx->state.frame_state.header_obus, 0);
                }
                gf_odf_av1_cfg_write(ctx->state.config, &dsi, &dsi_size);

                if ((!ctx->fps.num || !ctx->fps.den) && ctx->state.tb_num && ctx->state.tb_den && ! ( (ctx->state.tb_num<=1) && (ctx->state.tb_den<=1) ) ) {
                        ctx->cur_fps.num = ctx->state.tb_num;
                        ctx->cur_fps.den = ctx->state.tb_den;
                }

        }
```

I think it should always keep at the last encountered Sequence Header OBU, and not throw it away. For example, in the first loop where it pops all the list items from `ctx->state.config->obu_array`, save the Sequence Header OBU separately, and if `ctx->state.frame_state.header_obus` does *not* start with a Sequence Header OBU, insert it again. But this could be done in several different ways.

In any case, if the resulting `ctx->state.config->obu_array` will then start with the same Sequence Header OBU, the decoder configuration (`dsi`) will come out as bit-identical, so its CRC won't change and the same sample description can be re-used for all samples in the stream.

**Comment by rbouqueau** [comment]
Hi, thanks for the detailed report. I can't download the input file, could you please check the link?

**Comment by jeanlf** [comment]
+1, could you re-upload the file ?

**Comment by dirk-unified** [comment]
Adding a very small sample file (as the previously uploaded could not be shared
[apv_test_hdr10.ivf.zip](https://github.com/gpac/gpac/files/7121039/apv_test_hdr10.ivf.zip)
)

**Comment by jeanlf** [comment]
indeed, now fixed. Thanks for the report and the file !
