### ISSUE TITLE
DashCast: transcoding mp4: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by osztrovszky** [gpac/gpac#191]
Hello Guys!
I've just installed GPAC on my Ubuntu. I've tried DashCast with the sample code you provided: DashCast -av test.mp4 -seg-dur 1000 -frag-dur 200
It starts working frame by frame, but after a while it stops and says:
Segmentation fault (core dumpled)
Can you help me with this error?
Thanks, 
Zsolt

**Comment by jeanlf** [comment]
could you post your test file somewhere, so that we can have a look at the problem ?

**Comment by jeanlf** [comment]
dashcast is now deprecated, use GPAC 0.9.0
