### ISSUE TITLE
Playing with back tiled video in VR with compositor crashes

### ISSUE THREAD

**Issue by RodolpheFouquet** [gpac/gpac#1919]
Hi,

I am encountering frequent crashes while playing back tiled VR content using the compositor, you can find the way to reproduce it below.

Encoder command:

```
 gpac\
 -i test_30fps.mp4:FID=I reframer:rt=on:SID=I:FID=REGULATED\
 ffsws:SID=REGULATED:FID=Y:osize=1024x512:ofmt=yuv420\
 -+kvazaar-params=preset=ultrafast,tiles=4x4,slices=tiles,mv-constraint=frametilemargin,input-format=P420,qp=16,rc-algorithm=lambda\
 ffenc:SID=Y:FID=K1:c=libkvazaar:b=10M:size=$SIZE:fintra=4:rc\
 tilesplit:SID=K1:FID=1 -o http://localhost:8080/live.mpd:gpac:dmode\=dynamic:segdur\=4:cdur\=2:asto\=2:llhls\=off:profile\=live:rdirs\=outdir:template\=seg_live_:SID\=1  -stats  -logs=all@info -log-file=file_to_tiles_server.log
```

Player command

``` 
gpac compositor:src=http://localhost:8080/live.mpd#VR vout:buffer=8000 -graph -logs=all@info -log-file=compositor_crash.log 
```

[Link containing](https://www.mediafire.com/file/991b9w4ilkyo9ac/compositor_crash1.zip/file):

- player log
- encoder log
- screenshot of the stacktrace
The video file used https://github.com/gpac/gpac/issues/1849

OS: ubuntu 21.04 
GPAC: version 1.1.0-DEV-rev1283-gc51f07f11-master
Compiled in debug
Ran using` _NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia` to make use of the nvidia GPU 

-------
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
I think the problem comes from nvdec reconfigure in gl mode, I'll have a look at that as soon as I get my hands on a machine with nvdec support.
Could you try forcing nvdec output to copy (`--fmode=copy`) and see if the crash still happens?

**Comment by RodolpheFouquet** [comment]
I tried with the option, and, indeed, it is not crashing anymore, but the playback is choppy.

I tried in two configurations:

One with` --fmode=copy`

```
gpac --fmode=copy compositor:src=http://localhost:8080/live.mpd#VR vout -graph -logs=all@info -log-file=compositor_fmode_copy.log
```

One with nvdec blacklisted


```
gpac  -blacklist=nvdec compositor:src=http://localhost:8080/live.mpd#VR vout -graph -logs=all@info -log-file=compositor_nvdec_blacklisted.log
```

https://www.mediafire.com/file/ufc9ik7hqebevzf/choppy_compositor.zip/file you can find the logs enclosed.

As bonus, with nvdec blacklisted, after a few seconds, the video seems to have colour conversion issues as shown below.

![Screenshot from 2021-09-28 03-02-31](https://user-images.githubusercontent.com/3400735/135010562-ab7aebfa-c90d-4010-a285-73e3e6fdcec7.png)

**Comment by RodolpheFouquet** [comment]
Hi, so I retested by updating and using this commit a96df00059a0f4198790249cce13f308435e351a, here is the situation:

- The colour conversion bug is now gone.
- both (blacklist and fmode) are choppy whilst using the command line I provided
- `-blacklist=nvdec` becomes smoother when buffer=8000 used, albeit some hiccups are still present at the beginning of the stream
- `--fmode=copy` stays choppy regardless of the offer used

**Comment by RodolpheFouquet** [comment]
Update: 

So, it looks like that when using a video as input, the last command given do not seem to result in a choppy playback.

However, when using a 30fps ffavin input, the playback gets choppy.

I suspect [this](https://github.com/gpac/gpac/issues/1928) might be the cause.

**Comment by jeanlf** [comment]
> First, Is it possible to construct a command line which feeds the output of a decoded DASH stream into the compositor without needing to specify the "src" parameter?

Something like
`gpac -i DASH_URL @ compositor @ vout @1 aout`

should work for playback, replace aout / vout with encoding filters or other.

There's also an issue using presets with bipredicition in kvazaar, the timing is somehow wrong - cf [here](https://github.com/ultravideo/kvazaar/issues/310)

I would suggest:
- use kvazaar without presets
- force your input fps to 30 (e.g.`-i video://:#FPS=30`) if you get the `[FFAVIn] Unknown frame rate, will use 25 fps [...]` message

and check if the playback is better.

**Comment by RodolpheFouquet** [comment]
Hi sorry for the long delay.

It works!
