### ISSUE TITLE
Errors when probing/muxing dav1 video file

### ISSUE THREAD

**Issue by quietvoid** [gpac/gpac#1925]
Hello,

I'm playing around with some sample files I found in Google's `CtsMediaTestCases`, but some of them seem to be unrecognized by GPAC.

I've uploaded the mp4 here: https://www.mediafire.com/file/wsyt42zw7mf5fxs/video_dovi_3840x2160_30fps_dav1_10.mp4/file
And a demuxed OBU file here: https://www.mediafire.com/file/ee16i6lsoaeug09/dav1_10.obu/file
(According to the template, that's how it should be done..)

The demuxed video was obtained with Dolby's tool: https://github.com/DolbyLaboratories/dlb_mp4demux

When probing with `gpac` I get this:
```
gpac probe -i video_dovi_3840x2160_30fps_dav1_10.mp4
[iso file] Read Box "sgpd" (start 1460337) failed (Invalid IsoMedia File) - skipping
[iso file] Read Box "stbl" (start 1458670) failed (Invalid IsoMedia File) - skipping
[iso file] Read Box "minf" (start 1458606) failed (Invalid IsoMedia File) - skipping
[iso file] Read Box "mdia" (start 1458521) failed (Invalid IsoMedia File) - skipping
[iso file] Read Box "trak" (start 1458385) failed (Invalid IsoMedia File) - skipping
[iso file] Read Box "moov" (start 1458269) failed (Invalid IsoMedia File) - skipping
[IsoMedia] error while opening video_dovi_3840x2160_30fps_dav1_10.mp4, error=Invalid IsoMedia File
Failed to connect filter fin PID video_dovi_3840x2160_30fps_dav1_10.mp4 to filter mp4dmx: Invalid IsoMedia File
Blacklisting mp4dmx as output from fin and retrying connections
session last connect error Filter not found for the desired type
```

And when trying to remux:
```
MP4Box -add dav1_10.obu -new test.mp4
[AV1] parsing for metadata is not implemented. Forwarding.
[Importer] Error probing dav1_10.obu
Error importing dav1_10.obu: Bad Buffer size (too small)
```

Now I think this might be an experimental file, but I'm not sure at all.
The OBU file parses correctly using https://github.com/yohhoy/av1parser
But `aomdec` does say the frames are corrupted.

The file also does not seem to follow AV1's ITU-T T.35 specification for the Dolby Vision metadata, so it might just be bogus.

I am using GPAC on Arch Linux, 64 bits.
`gpac - GPAC command line filter engine - version 1.0.1-rev0-gd8538e8ae-makepkg`

**Comment by jeanlf** [comment]
Thanks for the file

- The extracted OBU is not conformant, it is missing temporal delimiters. This was causing the buffer too small error, patched

- the MP4 file is broken, the culprit is the sample group `av1m`. Patching the 4 bytes after `av1m` to 0 with an hex editor fixes the file

I did a cleanup on dolby vision code points for AVC, HEVC and added the AV1 signaling, you can try with the patched file:
```
#get info, now displaying DOVI info
MP4Box -info video_dovi_3840x2160_30fps_dav1_10.mp4

#extract obu, properly formated
MP4Box -raw 1 video_dovi_3840x2160_30fps_dav1_10.mp4

#play the file
gpac -play video_dovi_3840x2160_30fps_dav1_10.mp4
```

**Comment by quietvoid** [comment]
Thank you!

**Comment by cconcolato** [comment]
> I'm playing around with some sample files I found in Google's `CtsMediaTestCases`

@quietvoid can you provide a link to where these CtsMediaTestCases files are?

**Comment by quietvoid** [comment]
There's a download link here: https://source.android.com/compatibility/cts/run-locally

**Comment by podborski** [comment]
@quietvoid, @jeanlf  just saw this issue. Question, why `av1m` and not `av1M`? According to AV1 isobmff spec the second one [is used for samples with metadata OBUs](https://aomediacodec.github.io/av1-isobmff/#metadatasamplegroupentry), while the first one is used for multi frame. The file provided above has `av1m` sample group which I believe is wrong.

**Comment by jeanlf** [comment]
Probably, but the sample group description bx is wrong either way:
- version: 0x00
- flags: 0x00000C
- entry_count: 0x04B5003B 

looks like this could indeed be a `av1M` for meta data METADATA_TYPE_ITUT_T35 (0x04), but with a missing entry_count field ...
