### ISSUE TITLE
MP4Box creating corrupted MPD (incorrect XML syntax) 

### ISSUE THREAD

**Issue by tsinghal18** [gpac/gpac#193]
Hi Team,

I am executing Mp4Box as part of my C# application. 
In some random execution it creates wrong XML syntax of MPD. Please find attached screenshot of one of the invalid MPD. Seems to be there is a bug when it tried to write the final MPD.

MP4Box Command (sample): mp4box -rap -url-template -frag 2000 -dash 5000 -segment-name wild_%s -bs-switching merge 1000000037_2464.m4v 1000000037_1264_enc.m4v 1000000037_864_enc.m4v 1000000037_264_enc.m4v audio_enc.m4a

Please let me know what could be the reason of this. I am using following code to invoke the process.
    Dim standardOutput As New System.Text.StringBuilder
    Dim standardError As New System.Text.StringBuilder
    myProcess = New System.Diagnostics.Process()
    myProcess.StartInfo.FileName = Command
    myProcess.StartInfo.Arguments = Params
    myProcess.StartInfo.WindowStyle = System.Diagnostics.ProcessWindowStyle.Normal
    myProcess.StartInfo.UseShellExecute = True
    myProcess.StartInfo.RedirectStandardOutput = False
    myProcess.StartInfo.RedirectStandardError = False
    'myProcess.StartInfo.StandardErrorEncoding = System.Text.Encoding.ASCII
    myProcess.StartInfo.ErrorDialog = False
    myProcess.StartInfo.CreateNoWindow = True
    myProcess.StartInfo.WorkingDirectory = WorkingDirectory

    standardOutput.AppendLine("Standard Output Begin")
    standardError.AppendLine("Standard Error Begin")

    Try
        myProcess.Start()
    Catch ex As Exception

    End Try
    Try

        If Not myProcess.Start() Then

        End If
        myProcess.WaitForExit(Timeout * 1000)
        If Not myProcess.HasExited Then
            myProcess.Kill()
            success = False
        End If
![wrong_mpd](https://cloud.githubusercontent.com/assets/13536181/8927946/bfaf6086-3538-11e5-99ca-08040016f235.PNG)

**Comment by jeanlf** [comment]
strange indeed. Can you reproduce this with other files ? Can you reproduce this with a single input media ?

**Comment by rbouqueau** [comment]
no news for more than a year => closing
