### ISSUE TITLE
endless loop using ac3 audio file

### ISSUE THREAD

**Issue by martinr92** [gpac/gpac#194]
I've currently the issue that when adding an AC3 audio track to a mp4, it runs endless until my disk is full!
Please download the test material and try to bring both tracks (one h264 video and the ac3 audio) together (https://www.dropbox.com/sh/2m4nxqyw6fcjok9/AAA3CGhqUlCTAESzcbOvR2_Ea?dl=0). For this I'm executing the following command:
```
./MP4Box -add American_Beauty_15.07.25_23-55_orf1_110_TVOON_DE.mpg.HD_video.h264 -add American_Beauty_15.07.25_23-55_orf1_110_TVOON_DE.mpg.HD.ac3 -inter 500 -new out.mp4
```
I was also successfully using an mp3 audio track.
The really bad thing is that it runs endless until no more free disk space is available!

**Comment by jeanlf** [comment]
now fixed, thanks for the report

**Comment by martinr92** [comment]
@jeanlf and @nguyen-viet-thanh-trung Thanks for the bugfix.
