### ISSUE TITLE
ISOBMFF conformance suite issues

### ISSUE THREAD

**Issue by podborski** [gpac/gpac#1940]
While running `MP4Box -diso ...` xml dump on files in the ISOBMFF conformance suite, I noticed that MP4Box has issues with some of the files:

1. Two files produce invalid xml files ([09_text.mp4](https://conformance.mpeg.expert/ISOBMFF/published/isobmff/09_text.mp4), [22_tx3g.mp4](https://conformance.mpeg.expert/ISOBMFF/published/isobmff/22_tx3g.mp4))
The issue seems to come from the dump of the `DefaultBox` where the closing xml tag is missing. 
It looks like `gf_isom_box_dump_done` call is missing  in https://github.com/gpac/gpac/blob/54bce6b07332fabb016cf9a4ae9b80aa33bca3cd/src/isomedia/box_dump.c#L1929

2. Three files can not be opened at all.
    - [compact-no-code-fec-1.iso3](https://conformance.mpeg.expert/ISOBMFF/published/isobmff/compact-no-code-fec-1.iso3)
    - [compact-no-code-fec-2.iso3](https://conformance.mpeg.expert/ISOBMFF/published/isobmff/compact-no-code-fec-2.iso3)
    - [mbms-fec.iso3](https://conformance.mpeg.expert/ISOBMFF/published/isobmff/mbms-fec.iso3)

```shell
MP4Box -diso compact-no-code-fec-1.iso3
[iso file] Media header timescale is 0 - defaulting to 90000
[iso file] Read Box "stbl" (start 381) failed (Invalid IsoMedia File) - skipping
[iso file] Read Box "minf" (start 309) failed (Invalid IsoMedia File) - skipping
[iso file] Read Box "mdia" (start 236) failed (Invalid IsoMedia File) - skipping
[iso file] Read Box "trak" (start 136) failed (Invalid IsoMedia File) - skipping
[iso file] Read Box "moov" (start 20) failed (Invalid IsoMedia File) - skipping
Error opening file compact-no-code-fec-1.iso3: Invalid IsoMedia File
```

**Comment by jeanlf** [comment]
Thanks for the report, dumping of tx3g now fixed.

For the fec files, they are not compliant (missing stts). I added a warning in the code to be more explicit.

You can still use `-no-check` to ignore these errors (might crash), for `-diso` on these files  it works properly.
