### ISSUE TITLE
Mp4Box Split has audio issues

### ISSUE THREAD

**Issue by pankajsoni19** [gpac/gpac#1941]
ubuntu `18.04.6 LTS`

by default installs
MP4Box - GPAC version 0.5.2-DEV-revVersion: 0.5.2-426-gc5ad4e4+dfsg5-3ubuntu0.1

MP4Box -splitx has audio drop issues

then I upgrade to Debian:bullseye
by default installs
`MP4Box - GPAC version 1.0.1-revrelease`

MP4Box -splitx & splitz has audio drop issues

`-splitg` option not available though document mentions it.

then I upgrade to nightly build 

`gpac_1.1.0-DEV-latest-master_amd64.deb`

```
> MP4Box -splitz 1638:5311 1635881002.mp4 -out splitz.mp4
AVCC: invalid syntax for REXT profile, patching.
[MP4Mux] Error creating new tx3g sample description: Bad Parameter
Failed to connect filter reframer PID T3 to filter mp4mx: Bad Parameter
splitting: file 1 done
Split failed: Bad Parameter
```

while the file is correctly split as using `splitg` the output says that split failed. Why the error?

Also https://github.com/gpac/gpac/wiki/mp4box-dump-opts
mentions

`-splitz (string): extract the specified time range so that ranges A:B and B:C share exactly the same boundary B:`
it only takes `start_second:end_seconds`, why does document mention 3 points?

**Comment by pankajsoni19** [comment]
on Mac 

`brew install gpac` -> ` 1.0.1-revrelease`

```
gpac src=1635881002.mp4 reframer:xs=1638:xe=5311  -o dest.mp4 
```

does not split

**Comment by jeanlf** [comment]
I suspect the issue comes from the input file, could you upload a sample test file?

Documented options are from latest dev version, splitg was introduced recently.

> it only takes start_second:end_seconds, why does document mention 3 points?

You don't, what this means is that executing `MP4Box -splitz A:B src.mp4` and `MP4Box -splitz B:C src.mp4` will perform the same adjustments for time `B`. Other split options do not guarantee that.

**Comment by pankajsoni19** [comment]
1.0.1-revrelease

gpac split works well for same file. I ended up using it. there may be some issue in mp4box.

```
gpac -i input.mp4 -reframer:xs=T00:01:00:xe=T00:02:00 @ -o output.mp4
```

**Comment by jeanlf** [comment]
That's strange, `-split` options are just wrappers around this command.

I tried -splitx with a file containing audio, video and subs, no issues. 
If you want further investigations on that, please upload a sample test file.

**Comment by pankajsoni19** [comment]
files that I split by gpac where being joined using mp4box

gpac split
```
gpac -i 1636946501.mp4 reframer:xs=T00:04:26:xe=T00:04:43 @ -o part_0.mp4
[IsoMedia] Track 3 is disabled, ignoring track - you may retry by specifying alltk option
```

```
gpac -i 1636946501.mp4 reframer:xs=T00:07:46:xe=T01:31:09 @ -o part_1.mp4
[IsoMedia] Track 3 is disabled, ignoring track - you may retry by specifying alltk option
[MP4Mux] PID V2 Sample 1 with DTS 0 less than previous sample DTS 0, adjusting prev sample duration
.... same line repeats
```

```
gpac -i 1636946501.mp4 reframer:xs=T01:31:37:xe=T01:33:02 @ -o part_3.mp4
[IsoMedia] Track 3 is disabled, ignoring track - you may retry by specifying alltk option
```

Mp4Box join
```
MP4Box -noprog -add part_0.mp4 -cat part_1.mp4 -cat part_3.mp4  -new output.mp4
```

above gives error

```
IsoMedia import part_0.mp4 - track ID 1 - Audio (SR 32000 - 1 channels)
IsoMedia import part_0.mp4 - track ID 2 - Video (size 640 x 360)
[iso file] Found stts entry with sample_delta=0 - forbidden ! Fixing to 1
Appending file part_1.mp4
Error appending part_1.mp4: Bad Parameter
.... above line repeats
```

however this works

```
gpac -i part_0.mp4 -i part_1.mp4 -i part_3.mp4 reframer @ -o output.mp4
```

is the above gpac command the correct way to concat files?

**Comment by nerdCopter** [comment]
I'm stumped at this as well
i.e. It used to work, but dont know the version.

```
$ gpac --version
Nothing to do, check usage "gpac -h"
gpac - GPAC command line filter engine - version 1.0.1-rev1.0.1+dfsg1-4+deb11u1
(c) 2000-2020 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io
```

```
MP4Box -splitx 21:79 ./GOPro_INPUT.mp4 -out Output.mp4
[iso file] Box "tmcd" (start 697654724) has 2 extra bytes
[IsoMedia] Track 3 is disabled, ignoring track - you may retry by specifying alltk option
```
Resulted without audio.
However,
```
$ gpac -i ./GOPro_INPUT.mp4 reframer:xs=T00:00:21:xe=T00:01:19 @ -o Output.mp4
[iso file] Box "tmcd" (start 697654724) has 2 extra bytes
[IsoMedia] Track 3 is disabled, ignoring track - you may retry by specifying alltk option
```
Resulted with audio.

**Comment by jeanlf** [comment]
Thanks for the file.

However I cannot reproduce with latest master, both commands give files with audio and working in my various tests players. 
Please retry with master and reopen if needed.

**Comment by nerdCopter** [comment]
> Thanks for the file.
> 
> However I cannot reproduce with latest master, both commands give files with audio and working in my various tests players. Please retry with master and reopen if needed.

confirmed success with `master`. Debian supplied package is out of date. Thank you!
