### ISSUE TITLE
Unknown input file type; Special chars in file name

### ISSUE THREAD

**Issue by spinner-b** [gpac/gpac#1942]
**Info:**
MP4Box - GPAC version 0.5.2
Ubuntu 20.04

**Problem:**
I have .h264 video files which i need to convert to .mp4.
This works perfectly fine on test files that have no special characters in their names.
Working command: `MP4Box -add ./static/video/myfile.h264 ./static/video/test.mp4`

Now my production files have a different file name which contains the date and time of creation
separated by "-" "@" ":" and "/" characters. MP4Box can't work with them i guess because of the file name.

The files are fully intact and not corrupted or anything. If i change file name to something without the 
special characters it works fine.

The following command does not work: 
`MP4Box -add ./static/video/2021-05-10_11:20:03.h264  ./static/video/2021-05-10_11:20:03.mp4`
```
[Importer] Unknown input file type for "./static/video/2021-05-10_11:20"
Error importing ./static/video/2021-05-10_11:20:03.h264: Requested URL is not valid or cannot be found
```

I can tell that in the first line of the error message the file name gets cut off. I don't know if this could give a hint to the solution of the problem.

Using the same file names works perfectly with tools like FFmpeg etc. I can't really tell if my file names are too long for MP4Box or if MP4Box doesn't like special chars in file names.

Thanks

**Comment by spinner-b** [comment]
I played around with the file names a bit. It seems like the ":" is the problem here.

**Comment by rbouqueau** [comment]
The default internal separators in GPAC are ```:=#,@```. The ```gpac``` can overwrite them using ```-seps``` while is is not implemented in ```MP4Box```.

We usually introduce ```:gpac:```to avoir escapings URLs. However I checked the code and it only happens when we detect ```://```.

**Comment by spinner-b** [comment]
Alright thank you for the explanation. To continue my work i was able to make a change in the file names and avoid using ":".
So i basically have my workaround. From my perspective you/i can close this issue.

**Comment by rbouqueau** [comment]
Thanks. Seeing with @jeanlf if we can't make things clearer for users.

**Comment by jeanlf** [comment]
0.5.2 is quite old, we've had a lot of patches in the option parser of mp4box to only check ':' after the file extension, if any.
I'd suggest you try with a more recent version.

**Comment by jeanlf** [comment]
I just did a cleanup pass, using filename with ':' should now work properly with both MP4Box and gpac.

**Comment by spinner-b** [comment]
@jeanlf Thanks for your time, i appreciate it.
