### ISSUE TITLE
gpac reporting unknown argument but unable to find match

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#1944]
```
$ gpac -i input.mp4 @ -o output.mp4:frag
Unknown argument ":frag" set but not used by any filter - possible matches
- range in filters httpin fin
```

Here it proposes ```range``` but not ```frag``` which is available in ```mp4mx```.

**Comment by jeanlf** [comment]
the problem comes from the fact that 'frag' is not an option of mp4mx, it's a value of the "store" option...
I patched so that enum values are also reported
