### ISSUE TITLE
MKV to MP4 Using MP4Box

### ISSUE THREAD

**Issue by dojima** [gpac/gpac#1947]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Sorry for the question, but I just wanted to confirm something.

I'm trying to move an H.265 video from an MKV container to an MP4 container.  When doing this with FFmpeg, it mangles the framerate (changing what was constant to a variable framerate).  For integer framerates, I am able to use `-video_track_timescale 60` to work around this issue with FFmpeg, but it doesn't work with framerates like 59.94.

I am able to successfully do what I need with MP4Box after extracting the video with mkvextract, but, as I often work with files in the hundreds of gigabytes, I wonder if this is possible with one step.  `:fps=x` works fine with the extracted H.265 file, but not with the original MKV.  Just wanted to make sure I wasn't overlooking anything and that extracting the file first with mkvextract is my only option here.

Thanks.

**Comment by jeanlf** [comment]
If the source is indeed CFR with no lost frame, you can patch the sample duration:
`MP4Box -add self#video:sampdur=1001/30000 file.mp4`

You can also try importing the mkv directly:
`MP4Box -add file.mkv -new file.mp4`

Note that the importer uses libavformat, so it's possible you will get the same fps issue.

To reimport the video and its timing in one pass (using latest master), you need to add filters for that:

```
MP4Box -add source.mkv:@rfnalu:notime:fps=30000/1001::SID=#video@@reframer:SID=#!video -new reimport.mp4
```
 (the reframer is only needed here to carry the source ID info).

Using gpac:
```
gpac -i source.mkv rfnalu:notime:fps=30000/1001:SID=#video @ @@#!video -o reimport.mp4
```

Note that `:fps=30000/1001` is needed only if you want to overwrite the default frame rate, or if no timing info is present in the video bitstream.
