### ISSUE TITLE
Dsah use onDemand profile segment duration is random

### ISSUE THREAD

**Issue by kurodaak1ra** [gpac/gpac#1948]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I used command: MP4Box -dash 10000 -profile onDemand video.mp4

But the result sidx subsegment_duration is random, not same value, how can i set subsegment_duration in same value, like example pic

Thakns!

<img width="1440" alt="スクリーンショット 2021-11-25 23 25 00" src="https://user-images.githubusercontent.com/38561128/143467732-0367c8ca-e983-49dd-b48c-e5d339a2d3ed.png">

<img width="1227" alt="スクリーンショット 2021-11-25 23 24 13" src="https://user-images.githubusercontent.com/38561128/143467599-97e659cb-68ee-44eb-8749-e2483da7fcd8.png">

### example pic
<img width="1241" alt="スクリーンショット 2021-11-26 1 06 20" src="https://user-images.githubusercontent.com/38561128/143480660-105830c8-b203-41d3-be49-1f9207ae6d42.png">

**Comment by rbouqueau** [comment]
What is the log of GPAC when processing these?

My first clue would be that your video encoding is not made with regular RAPs. How did you encode it?

**Comment by jeanlf** [comment]
These are not random values, these are the duration between RAP frames in the source media, you can cross check the RAP frame timings using:
`gpac -i source.mp4 reframer:saps=1 @ inspect:deep`

You will need to re-encode your media if you want segments of this desired duration.
