### ISSUE TITLE
Build on fedora 35 fails

### ISSUE THREAD

**Issue by jb-alvarado** [gpac/gpac#1949]
Hello,\
I try to compile MP4Box under fedora 35. In the past I was able to compile it, but now I have this problem:
- Compiling with: `./configure --prefix="$LOCALDESTDIR" --static-bin --static-build --static-modules && make -j6` runs smoothly, but only when I install **glibc-static**.
- Stripping from MP4Box binary shows: `strip: bin/MP4Box[.gnu.build.attributes__libc_freeres_fn]: Warning: version note missing - assuming version 3`
- running `/usr/local/bin/MP4Box -h` show:  `[1]    120297 segmentation fault (core dumped)  /usr/local/bin/MP4Box -h`

But interestingly I can run inside the source code folder: `bin/gcc/MP4Box -h`.

**Comment by jeanlf** [comment]
Hmm can't reproduce, got a fresh fedora 35, installed git gcc glibc-static and zlib-static, used `./configure  --static-bin --static-build --static-modules && make -j`,  strip and make install, works fine

Could you run this through gdb on your machine ?

**Comment by jb-alvarado** [comment]
Interesting. Can you also run: `MP4Box input.mp4 -brand mp42 -inter 500 -out output.mp4`?

You mean running `gdb MP4Box`? That gives: `No debugging symbols found in /usr/local/bin/MP4Box`

**Comment by jeanlf** [comment]
> `MP4Box input.mp4 -brand mp42 -inter 500 -out output.mp4`

works

In gdb, once crashed, type 'bt' to see the call stack. You will likely need to enable debug build for gpac, add `--enable-debug`to your configure, then `make clean && make -j && make install`

**Comment by jb-alvarado** [comment]
Ok, I think I know the problem now. Here is the output:

```
Starting program: /usr/local/bin/MP4Box /home/jonathan/Videos/ADtv.Gesund-aber-wie.2017.mp4 -brand mp42 -inter 500 -out /home/jonathan/Videos/ADtv.Gesund-aber-wie.2017_test.mp4
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000000000cb1dd1 in __strcpy_avx2 ()
(gdb) bt
#0  0x0000000000cb1dd1 in __strcpy_avx2 ()
#1  0x0000000000455d9e in get_default_install_path (file_path=0x7fffffff8450 "/usr/local/share/gpac", path_type=4) at utils/os_config_init.c:429
#2  0x000000000045635f in get_default_install_path (file_path=0x7fffffff9480 " \234\377\377\377\177", path_type=2) at utils/os_config_init.c:495
#3  0x00000000004579c7 in gf_cfg_load_restrict () at utils/os_config_init.c:1034
#4  0x000000000043ba79 in gf_sys_set_args (argc=8, argv=0x7fffffffdf68) at utils/os_divers.c:1005
#5  0x0000000000412e05 in mp4boxMain (argc=8, argv=0x7fffffffdf68) at main.c:5697
#6  0x0000000000415dfd in main (argc=8, argv=0x7fffffffdf68) at main.c:6483
```

The thing is, that I install the program to a different build location in my home folder and later I copy the program bin to **/usr/local/bin**. And after that point mp4box is not working anymore. I think this should not be happen, because it is a static build, but how can I fix that?

**Comment by jeanlf** [comment]
Thanks for the analysis, this should now be fixed, can you cross-check ?

**Comment by jb-alvarado** [comment]
Yes I can confirm that it is fixed. Thank you for your fast helping!
