### ISSUE TITLE
Dasher - Add multiple subtitle, then do not create manifest file.

### ISSUE THREAD

**Issue by fingul** [gpac/gpac#1951]
Dasher - Add multiple subtitles, then do not create manifest file. - thank you!

- [*] I looked for a similar issue and couldn't find any.
- [*] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/

> gpac -i video.mp4 -i subtitle1.vtt  -o out.mpd

--> create manifest file.

> gpac -i video.mp4 -i subtitle1.vtt -i subtitle1.vtt  -o out.mpd

--> DO NOT create manifest file.

**Comment by fingul** [comment]
@ 1.0.1 version 1.0.1-rev0-gd8538e8ae

**Comment by jeanlf** [comment]
yes I can reproduce, will fix asap

**Comment by jeanlf** [comment]
now fixed, can you cross-check ?

**Comment by fingul** [comment]
Cross-checked! Thank you! Have a nice day!
