### ISSUE TITLE
--dual  -profile onDemand      will get stuck in safari

### ISSUE THREAD

**Issue by fastfading** [gpac/gpac#1952]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ yes] I looked for a similar issue and couldn't find any.
- [ yes] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ yes] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

issue:  
when we generate m3u8 and mpd with following command,  m3u8 plays well in safari 
------------
MP4Box -dash 1000 file.mp4 -out live.mpd --dual

if I add  " -profile onDemand ",  m3u8 will stuck in safari  when you try seeking several times
------------
MP4Box -dash 1000 file.mp4 -profile onDemand -out live.mpd --dual

**Comment by jeanlf** [comment]
what is your GPAC version (type `MP4Box`) ?

**Comment by fastfading** [comment]
MP4Box - GPAC version 1.0.1-revrelease

**Comment by jeanlf** [comment]
Could you try with latest master ? I think this was fixed some time ago (cf #1869)

**Comment by fastfading** [comment]
yes， it is fixed。  thanks
