### ISSUE TITLE
TTML import does not support the absence of the default TTML namespace

### ISSUE THREAD

**Issue by SoleneBuet** [gpac/gpac#197]
It seems mp4box requires the default namespace for TTML to be set:
````
XML (Subtitle, Metadata or Text) SampleEntry: namespace is mandatory. Abort.
````
It seems mp4box expects xmlns="http://www.w3.org/ns/ttml" to be set, although it is also valid to use prefixes on the elements e.g.:
xmlns:tt="http://www.w3.org/ns/ttml" and <tt:styling> throws up an error. 

It should not be the case as from XML specification.

**Comment by nigelmegitt** [comment]
That's correct. I'd suggest changing the test to:

| root element name resolves to `tt` in the `http://www.w3.org/ns/ttml` namespace

**Comment by rbouqueau** [comment]
Please feel free to provide us with test files that we would add to the regression folder: https://github.com/gpac/gpac/tree/master/regression_tests/ttml
Thanks!

**Comment by rbouqueau** [comment]
Added by 7d5a0bc5cbb6148d78f87f51f8dc78d32125b643 . Feedback and tests welcome :)
