### ISSUE TITLE
DashCast: Can it be using for audio only?

### ISSUE THREAD

**Issue by jeprojects** [gpac/gpac#198]
Can DashCast be used to take an audio feed only (no video) from LINE IN from the soundcard and produce a MPEG-DASH compatible audio only live stream?

**Comment by jeanlf** [comment]
DashCast uses ffmpeg or libav for media capture, if these support recording from line in on your system then this should work, but it has not been tested yet

**Comment by alexander-kudinov** [comment]
I cannot get it work. The problem with avresampler. The layout (channel_layout) for input stream is zerro.

**Comment by jeprojects** [comment]
@jeanlf Alexander is the developer working on this.

He can use ffmpeg to take the live audio feed in and output to a file just fine. So that should mean it supports recording from the line on his system.

But when trying to run the following with DashCast:

LD_LIBRARY_PATH=pwd ./DashCast -af alsa -a plughw:1,0 -conf dashcast.conf -seg-dur 3000 -frag-dur 3000 -live
MPD refresh time not set in live - defaulting to segment duration
Options:
video source: 
video crop: 0x0
audio source: plughw:1,0
audio format: alsa
Configurations:
id:a1	abr:32000
id:a2	abr:64000
id:a3	abr:96000
id:a4	abr:128000
Input #0, alsa, from 'plughw:1,0':
Duration: N/A, start: 1438787319.417999, bitrate: 1536 kb/s
Stream #0:0: Audio: pcm_s16le, 48000 Hz, 2 channels, s16, 1536 kb/s
Press q or Q to exit...
[AVAudioResampleContext @ 0x7ff368008b60] Invalid input channel layout: 0
Could not open the audio resampler. Aborting.
An error occurred while reading audio frame.
Generating MPD at 1900-01-01T00:00:00.000Z
StartTime: 1900-01-01T00:00:00.000Z - startNumber 1 - last number 1

So the error message is:
[AVAudioResampleContext @ 0x7ff368008b60] Invalid input channel layout: 0
