### ISSUE TITLE
MP4Box rev4065 behaviour different on OSX vs Ubuntu (ubuntu produces unplayable file)

### ISSUE THREAD

**Issue by milkisevil** [gpac/gpac#199]
@grudelsud and I are using MP4Box `0.5.1-DEV-rev4065` in two environments: OSX 10.10.4 and Ubuntu 14.04.3 LTS. When DASHing the same input file using the same command, the DASHed output on OSX works in [this Shaka Player demo](https://shaka-player-demo.appspot.com/) but the file DASHed on Ubuntu fails in the same Shaka Player demo. (Tested in Chrome 44 OSX).

Command:

    MP4Box -dash 4000 -rap -frag 4000 -frag-rap -profile onDemand -out "kitty-step3-mp4box.mpd" "kitty-step2-ffmpeg.mp4"

## OSX
This [MPD file and it's MP4](https://responsive-tv-shared.s3.amazonaws.com/shaka-test/local/kitty-step3-mp4box.mpd) plays successfully in [Shaka Player](https://shaka-player-demo.appspot.com/):
```
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.5.1-DEV-rev4065  on 2015-08-05T15:28:53Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500000S" type="static" mediaPresentationDuration="PT0H1M15.00S" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>kitty-step3-mp4box.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H1M15.00S">
  <AdaptationSet segmentAlignment="true" maxWidth="1280" maxHeight="720" maxFrameRate="25" par="16:9" lang="und" subsegmentStartsWithSAP="1">
   <ContentComponent id="1" contentType="video" />
   <ContentComponent id="2" contentType="audio" />
   <Representation id="1" mimeType="video/mp4" codecs="avc1.4d401f,mp4a.40.2" width="1280" height="720" frameRate="25" sar="1:1" audioSamplingRate="48000" startWithSAP="1" bandwidth="2707746">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <BaseURL>kitty-step2-ffmpeg_dashinit.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="1396-1655">
      <Initialization range="0-1395"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```

## Ubuntu
This [MPD file and it's MP4](https://responsive-tv-shared.s3.amazonaws.com/shaka-test/local-ffmpeg/kitty-step3-mp4box.mpd) does not play, throwing an error visible in the console of [Shaka Player](https://shaka-player-demo.appspot.com/):
```
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.5.1-DEV-rev4065 -->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500000S" type="static" mediaPresentationDuration="PT0H1M15.00S" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>kitty-step3-mp4box.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period id="" duration="PT0H1M15.00S">
  <AdaptationSet segmentAlignment="true" maxWidth="1280" maxHeight="720" maxFrameRate="25" par="16:9" subsegmentStartsWithSAP="1">
   <ContentComponent id="1" contentType="video"  lang="und"/>
   <ContentComponent id="2" contentType="audio"  lang="und"/>
   <Representation id="1" mimeType="video/mp4" codecs="avc1.4d401f,mp4a.40.02" width="1280" height="720" frameRate="25" sar="1:1" audioSamplingRate="48000" startWithSAP="1" bandwidth="2707676">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <BaseURL>kitty-step2-ffmpeg_dashinit.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="1288-1547"/>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```

If you diff the MPDs, you'll see that they claim to be from the same version of MP4Box, but there are obvious differences between the two (most notably the `indexRange`).

Please let us know if we can provide you with any further info, and of course any advice would be much appreciated!

**Comment by milkisevil** [comment]
This no longer seems to be a problem in 0.5.2 nightly build.

**Comment by grudelsud** [comment]
worth mentioning that ubuntu 14.04 ships a broken gpac version. installing the nightly build will complain about wrong library version numbers, but MP4Box will work anyways, provided the following standard ubuntu libraries are installed:

  ii  libavcodec54:amd64               6:9.18-0ubuntu0.14.04.1+fdkaac       amd64        Libav codec library
  ii  libavdevice53:amd64              6:9.18-0ubuntu0.14.04.1+fdkaac       amd64        Libav device handling library
  ii  libavformat54:amd64              6:9.18-0ubuntu0.14.04.1+fdkaac       amd64        Libav file format library
  ii  libavutil52:amd64                6:9.18-0ubuntu0.14.04.1+fdkaac       amd64        Libav utility library
