### ISSUE TITLE
[bug] generated m3u8 file can not be played in safari 

### ISSUE THREAD

**Issue by fastfading** [gpac/gpac#1992]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ yes] I looked for a similar issue and couldn't find any.
- [yes master branch ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ yes] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

/opt/git/gpac/bin/gcc/MP4Box  -dash 30000 output.mp4  -profile onDemand -out arch.mpd --dual 
will generate a  arch.m3u8 file 

```
#EXTM3U
#EXT-X-VERSION: 6
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:BANDWIDTH=1563831,CODECS="avc1.640033,mp4a.40.2",RESOLUTION=3840x2160,FRAME-RATE="25"
arch_1.m3u8
```

this m3u8 file works well in hls.js and video.js  
but it is not well supported in   safari natively  , we found the root cause is  
FRAME-RATE="25"   should not contain   "  
change   FRAME-RATE="25"   to   FRAME-RATE=25  ,  it will perfectly  
pls fix this bug

**Comment by jeanlf** [comment]
done thanks for the report
