### ISSUE TITLE
improve help about options

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#1993]
Example:

Ok with -h (although there could be more context of what the option belongs to):
```
$ MP4Box -h dv-profile
:dv-profile (int):             S set the Dolby Vision profile
```

Broken with -hx:
```
$ MP4Box -hx dv-profile
Possible options mentionning `dv-profile`:
```

```gpac``` broken with -h:
```
$ gpac -h dv-profile
Failed to load filter dv-profile: no such filter registry
No such filter "dv-profile"
Closest filter names: 
- vflip
```

```gpac``` broken with -hx:
```
$ gpac -hx dv-profile
Failed to load filter dv-profile: no such filter registry
No such filter "dv-profile"
Closest filter names: 
- vflip
```

**Comment by rbouqueau** [comment]
@jeanlf mentions that ```-h``` look into option names while ha, hh, and hx don't ATM.

**Comment by jeanlf** [comment]
I did a cleanup pass so that -hx also logs options with matching name

Note however that `gpac -h dv-profile` won't find anything, since this is an MP4Box option, not a gpac/libgpac/filter option.
