### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [gpac/gpac#1997]
Hey there!

I belong to an open source security research community, and a member (@aidaip) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by rbouqueau** [comment]
Hi @JamieSlome, thank you.

If you plan to report issues found by a fuzzer, our preference is that you open a public issue. Otherwise feel free to send us an email at security@gpac.io.

We'll discuss among maintainers about adding the SECURITY.md file. Github recommendations seem more complete than last time I checked, thanks for the link.

**Comment by aureliendavid** [comment]
added SECURITY.md with basic info

**Comment by rbouqueau** [comment]
Hello @JamieSlome Happy new year!

Can the magic links you sent us by email made public if we'd like to?

**Comment by JamieSlome** [comment]
@rbouqueau - a happy new year to you too! 🎉 

The magic links are not to be shared, as they provide maintainer controls which should only be used by maintainers or contributors with write permissions.

If you would like the reports to be public, we can arrange this for you. LMK ❤️

**Comment by rbouqueau** [comment]
On our wishlist it would ideal if we could change the visibility of the report once we have internally reviewed it. Even better: once we change the visibility to public, it becomes a github public issue!

Thanks again!

**Comment by JamieSlome** [comment]
@rbouqueau - awesome ideas and we would love to keep them tracked!

I'd love to invite you to create an issue on our GitHub repo: https://github.com/418sec/huntr/issues/new

Tell us about your feature request and a member from our team will get round to responding!

Just to confirm, would you like me to make the reports publicly visible now? 🤝

**Comment by rbouqueau** [comment]
Done. Thank you so much!

**Comment by JamieSlome** [comment]
@rbouqueau - looks like the e-mails went out but they soft-bounced.

Can you confirm if you have received the magic URLs?

**Comment by aureliendavid** [comment]
we've received the emails but some addresses on our list are misconfigured so might bounced 

it is being fixed atm

**Comment by rbouqueau** [comment]
@JamieSlome Thanks for touching base. This just confirms that dealing with emails for an entity like us is not efficient. I think the text in the security.md makes it clear.

I hope your organization will be able to implement https://github.com/418sec/huntr/issues/2188! FYI see #2050 #2051 and #2052 for the issue that your community raised.

**Comment by JamieSlome** [comment]
@rbouqueau - thanks for the update. Will just (cc) @psmoros into this conversation for tracking purposes of the demand for the feature request.

**Comment by aureliendavid** [comment]
I've marked issues as confirmed and fixed on huntr.dev using the magic links

**Comment by JamieSlome** [comment]
@aureliendavid thanks 👋 

That is all now!
