### ISSUE TITLE
Issue when playing DashCast live stream

### ISSUE THREAD

**Issue by vitortmdiniz** [gpac/gpac#200]
I'm trying to capture desktop and stream it live in an Apache server using DashCast. It captures and plays correctly when I do it on demand, however when I do it live and then play with MP4Client it shows only a black screen, not even getting any error message while capturing it. The commands I’m using are:

DashCast -vf x11grab -vres 1280x720 -v :0.0 -npts -live -out /public_html/

And then I play with:

MP4Client http://localhost/vitor/dashcast.mpd

Which results in the following output:

MP4Client http://localhost/vitor/dashcast/dashcast.mpd
Using config file in /home/vitor directory
System info: 11948 MB RAM - 8 cores
Modules Found : 36 
Loading GPAC Terminal
[Thread MediaManager] Couldn't set priority(2) for thread ID 0x9b55a700
[Thread MediaManager] Couldn't set priority(2) for thread ID 0x9b55a700
Terminal Loaded in 35 ms
Opening URL http://localhost/vitor/dashcast/dashcast.mpd
[DASH] Slight drift in UTC clock at time 2015-08-05T12:38:45Z: diff AST - now 3563501 ms
Service Connected

So what am I doing wrong? The client apparently connects correctly to the server, open the player but then it doesn't show anything on screen. I'm using Ubuntu 14.04 with GPAC version 0.5.0.

**Comment by JamesXu20150314** [comment]
All right, do you have tried the camera, what problems will happen.

**Comment by cconcolato** [comment]
Can you try to rerun with -logs dash@debug and post the log here?

**Comment by jeanlf** [comment]
dashcast is now deprecated, use GPAC 0.9.0
