### ISSUE TITLE
-diso command crashes on CP free iTunes m4vs

### ISSUE THREAD

**Issue by ndjamena** [gpac/gpac#201]
All the m4v files I've tried so far crash on the -diso command using both the latest 32 version and an older 64 bit version...  for some reason I can't install a newer 64 bit version, it always says the download is corrupted.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	mp4box.exe
  Application Version:	0.0.0.0
  Application Timestamp:	551ee7e1
  Fault Module Name:	libgpac.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	551ee7b0
  Exception Code:	c0000005
  Exception Offset:	00000000000accf6
  OS Version:	6.3.9600.2.0.0.256.103
  Locale ID:	3081
  Additional Information 1:	1bf7
  Additional Information 2:	1bf7526cd8a74c6608dbbcb90d3dfb22
  Additional Information 3:	1a7f
  Additional Information 4:	1a7f73b189c21f124613ccd6806fd818

**Comment by nguyen-viet-thanh-trung** [comment]
Could you sharing some m4v files, we will check it. 
FYI, 64-bits version is now available !

**Comment by ndjamena** [comment]
Umm, definitely not directly through github.  They're iTunes files and I'm REALLY not comfortable distributing them AT ALL.  I don't want my iTunes account cancelled, I'd have to make a new one.  If I send the file to anyone, it will have to be someone specific and they'll have to delete the file when they're done.

I've tried making a smaller mp4 file but the same problem doesn't happen to it... so what do we do?

64 bit works now, and the crash happens there too.

**Comment by ndjamena** [comment]
These are the last few line in the Log:

...
[iso file] Read Box type ---- size 536 start 917761
[iso file] Read Box type covr size 62763 start 918297
[iso file] Read Box type data size 62755 start 918305
[iso file] Current top box start before parsing 981060
[iso file] Read Box type free size 981070 start 981060
[iso file] Current top box start before parsing 1962130
[iso file] Read Box type mdat size 860731127 start 1962130

**Comment by rbouqueau** [comment]
@ndjamena Had you been able to send the file directly to Viet? We won't share any file that you provide to a contributor for debug.

**Comment by ndjamena** [comment]
How exactly, is there a messaging system here or do I use the email address on his profile?

**Comment by nguyen-viet-thanh-trung** [comment]
@ndjamena : Please send to my email: viet-thanh-trung.nguyen@telecom-paristech.fr

**Comment by ndjamena** [comment]
Sent.

Hopefully it crashes for you too.

**Comment by nguyen-viet-thanh-trung** [comment]
Should be fixed now
