### ISSUE TITLE
[bug]gpac generated ll-hls  could not be played in safari

### ISSUE THREAD

**Issue by fastfading** [gpac/gpac#2010]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ yes] I looked for a similar issue and couldn't find any.
- [ yest, master release] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ yes] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I use master release of gpac  and try to do some ll hls
./gpac -i /opt/Downloads/dash/output.mp4 reframer:rt=on @ -o live.m3u8:segdur=2:cdur=0.2:llhls=sf:dmode=dynamic
this output is play well in  https://www.theoplayer.com/ll-hls-test-page 
but could not be play in safari 15.1  mac
This ll hls is apple standard, this is an apple example  https://ll-hls-test.apple.com/llhls1/multi.m3u8  .
it can be play well in both theoplayer and safari. 
pls follow apple example and  let it could be played  in safari

**Comment by DavidYou** [comment]
Refer to rfc8216 (https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-4.4.3.8) , Safari could start playback with the right #EXT-X-SERVER-CONTROL: CAN-SKIP-UNTIL=XX,PART-HOLD-BACK=XX

Also PART-TARGET should be a litter larger than hls_ll_frag_dur.

**Comment by jeanlf** [comment]
I fixed a few things in LL HLS signaling (added PART-HOLD-BACK and make sure PART-TARGET is not less than any parts in the manifest), works on my mac (safari 14.1). Could you give it another try with latest master ?

**Comment by fastfading** [comment]
it can be play on both safari and theoplayer  ,  but it will get stuck sometimes.  
I am using  obs to push a rtmp stream .  gop  6s   30fps

**Comment by jeanlf** [comment]
OK good. I think the getting stuck part is same as #2034, so I'm closing here and we'll investigate the stability asap.
