### ISSUE TITLE
fail to import raw h264 file into 3gp file

### ISSUE THREAD

**Issue by andrewmabc** [gpac/gpac#202]
I run the follow command, and find video sample is not imported into ouput file:

MP4Box -quiet -add input.h264 -fps 10 output.3gp

where 'input.h264' consists of only sps, pps, and one idr nal units.

The MP4Box version to test is shown as below:

    commit 35b16b3f3364c192b70a7757f273a1574d6c3c69
    Author: jeanlf <jeanlf@users.sourceforge.net>
    Date:   Wed Apr 22 17:08:25 2015 +0200
    fixed timeshift estimation bug'

Test h264 file can be downloaded via 'http://sharesend.com/8x182bvw', or via 'http://mail.sina.com.cn/netdisk/download.php?id=093d288249aca362cd2769e01907441782'

**Comment by nguyen-viet-thanh-trung** [comment]
Could you please send us your input file ?

**Comment by andrewmabc** [comment]
how to upload file on this forum?

**Comment by nguyen-viet-thanh-trung** [comment]
You can upload file to a file sharing site (dropbox or mediafire for example) and add the link here.

**Comment by andrewmabc** [comment]
how long will it take to fix the bug?

**Comment by nguyen-viet-thanh-trung** [comment]
I could not download your file at all; Firefox and Chrome said that: "Blocked: May contain a virus or spyware"

**Comment by andrewmabc** [comment]
I have added another url link for downloading sample file. Please try.

**Comment by nguyen-viet-thanh-trung** [comment]
It assumes that your track with only one sample is an image track and remove it:
>if (gf_isom_get_sample_count(mp4file, i+1)<=1) {
				GF_LOG(GF_LOG_INFO, GF_LOG_AUTHOR, ("[3GPP convert] Visual track ID %d: only one sample found, assuming image and removing track\n", gf_isom_get_track_id(mp4file, i+1) ));
				goto remove_track;
			}

**Comment by andrewmabc** [comment]
I think it is rare that clips only have one video sample. But those clips don't violate mpeg4 standard. 

Why not remove the if condition and decide the track with only one video sample is correct video track?

Why does gpac think the track with only one video sample is always image track? H264 is a video standard, and not used for image coding/decoding. I think gpac should the track is video track if only one h264 sample is in that track.

**Comment by andrewmabc** [comment]
Is the assumption a bug?

**Comment by andrewmabc** [comment]
Is the assumption a bug?

If the only one sample is coded as h264 format, the track with the sample can't be seen as image track.

**Comment by andrewmabc** [comment]
Is the assumption a bug?

If the only one sample is coded as h264 format, the track with the sample can't be seen as image track. Because h264 is a video coding standard but not image standard

**Comment by andrewmabc** [comment]
Is it possible to change the assumption logic in gpac, and commit the change to git repository?

**Comment by nguyen-viet-thanh-trung** [comment]
now fixed ! please checkout the latest version.
