### ISSUE TITLE
MP4Box itags integer values wrongly recorded

### ISSUE THREAD

**Issue by MartiCode** [gpac/gpac#2029]
How to reproduce:

MP4box -itags media=9 test.mp4

MP4box -info test.mp4 shows tag "media" has value 57

This seems to happen to all integer types (also hdvd or rating) and basically adds 48 to every value (ie writing value 1 records 49)

**Comment by jeanlf** [comment]
Indeed, 8-bit tag types where not correctly implemented. This is now fixed, thanks for the report
