### ISSUE TITLE
Dash content generation for multiple resolution

### ISSUE THREAD

**Issue by niteeshbhat** [gpac/gpac#203]
Hello,

I am generating dash content for HEVC live service using MP4Box. The input video representations has different resolutions, but only one initialization segment has been generated. This shouldn't be the case since init segment contains video width and height parameters, which should be different for each of these representations.

The different representations are created using ffmpeg, example:

ffmpeg -i ~\ContentSources\big_buck_bunny_1080p_surround.avi -f mp4 -vcodec libx265 -s 512x288 -aspect 16:9 -b:v 500k -an -maxrate 504k -bufsize 1004k -threads 0 -x265-params no-open-gop=1:min-keyint=48:scenecut=0:keyint=48 -y ~\ContentSources\bbb_288p_500k_H265.mp4 

Then dash content creation using MP4Box,
MP4Box -dash 2000 -profile live -rap -frag-rap -url-template -out ~\Dashcontent\BBB_MultiRes_Multirate_HEVC_Live.mpd -segment-name %s_ -segment-ext mp4 ~\ContentSources\bbb_288p_500k_H265.mp4 ~\ContentSources\bbb_432p_1000k_H265.mp4 ~\ContentSources\bbb_720p_2000k_H265.mp4 ~\ContentSources\bbb_64k_audio.mp4

The common init segment shows size parameters as 512x288.
Also I am using Ubuntu 12.04.5 LTS, 
ffmpeg version N-74299-g8db0f71 built with gcc 4.6 (Ubuntu/Linaro 4.6.3-1ubuntu5)
MP4Box - GPAC version 0.5.2-DEV-rev552-g5a1b427-master

**Comment by Murmur** [comment]
Try this parameter `-bs-switching no` if makes a difference. See documentation for detailed information.
https://gpac.wp.mines-telecom.fr/mp4box/dash/

**Comment by niteeshbhat** [comment]
Its working fine now.. Thank you
