### ISSUE TITLE
Deleting itags doesn't seem to work

### ISSUE THREAD

**Issue by MartiCode** [gpac/gpac#2030]
Documentation says "Setting a tag with no value or value NULL removes the tag."

However all these fail with "Error assigning tag comment=: Bad Parameter":

MP4box -itags comment= test.mp4
MP4box -itags comment=NULL test.mp4
MP4box -itags comment="" test.mp4

But setting a comment with MP4box -itags comment="Test" test.mp4 does work.

**Comment by jeanlf** [comment]
indeed, now fixed thanks for the report!
