### ISSUE TITLE
MP4Box itags string parsing issue with @tag

### ISSUE THREAD

**Issue by MartiCode** [gpac/gpac#2031]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

How to reproduce:

MP4Box -itags title="Some title":gen=Genre test.mp4
MP4Box -info test.mp4

Shows tag title has value **Some title:gen=Genre**
Issue is the same omitting quotes (ie MP4Box -itags title=Sometitle:gen=Genre test.mp4 has the same problem)

However MP4Box -itags gen=Genre:title="Some title" test.mp4 works fine.

**Comment by jeanlf** [comment]
Indeed, this was working for 4CC tags only, not 3CC. Now fixed, thanks for the report

Note that passing `-itags title="Some title":genve=Genre` will still result in a single tag with type title and  value `Some title:genve=Genre`
