### ISSUE TITLE
Regulation issue with live HLS/DASH output

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#2034]
To reproduce:
```gpac avgen @ reframer:rt=on @ enc:c=aac @1 enc:c=avc @ @1 -o http://127.0.0.1:8889/live.m3u8:gpac:muxtype=ts:dmode=dynamic:segdur=2:rdirs=/tmp/gpac```

Idem with:
```gpac -i https://akamaibroadcasteruseast.akamaized.net/cmaf/live/657078/akasource/out.mpd -o http://127.0.0.1:8889/live.m3u8:gpac:muxtype=ts:dmode=dynamic:segdur=2:rdirs=/tmp/gpac```

For HLS you can try with https://hls-js.netlify.app/demo/

**Comment by jeanlf** [comment]
This should now work properly, could you cross-check ?

**Comment by rbouqueau** [comment]
It works, thanks!
