### ISSUE TITLE
can gpac convert RTMP to ll-hls?

### ISSUE THREAD

**Issue by GlassyYang** [gpac/gpac#2037]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I need to push living stream by `obs`, and cut living stream into ll-hls segment files. I read `wiki` and using next command to realize this mission:
```shell
gpac -i rtmp://localhost/live reframer:rt=on @ -o res/live.m3u8:segdur=10:cdur=1:profile=live:dmode=dynamic:llhls=sf
``` 
but `gpac`  output next message:
```shell
[FFDmx] Fail to open rtmp://localhost/live - error Input/output error
Failed to load filter for "rtmp://localhost/live": Feature Not Supported
```
I want to know where there is a way to create living stream by `obs` and generate ll-hls segment files? I read wiki and it's just using file as input, which is not true live stream and not people always wanto to do.

**Comment by rbouqueau** [comment]
Can you plan ```rtmp://localhost/live```with any player (e.g; VLC)? I suspect that you are missing the steam name in your URL.

**Comment by fastfading** [comment]
@GlassyYang   you should build gpac  with  ffmpeg

**Comment by jeanlf** [comment]
test your install gpac+ffmpeg:

server:
`gpac -i src.mp4 -o rtmp://127.0.0.1:8888/live:gpac:ffmt=flv:rtmp_listen=1`
 
client:

`gpac -play rtmp://127.0.0.1:8888/live`
