### ISSUE TITLE
Key rotation with ROOT/LEAF keys instead of new <Period> on each new keyID

### ISSUE THREAD

**Issue by Murmur** [gpac/gpac#2043]
Is this kind of key rotation considered in gpac drm packaging?
Segment files may have PSSH(playready pro object, els key object) table.

**Key rotation with ROOT/LEAF keys** 
_Changing the encryption keys frequently—scalable key rotation_ 
https://docs.microsoft.com/en-us/playready/packaging/content-packaging-and-delivery
https://github.com/MicrosoftDocs/PlayReady/blob/main/Docs/Packaging/how-to-package-mp4-based.md

> 
> There is an advanced mechanism in PlayReady called scalable key rotation (as opposed to license rotation). This method stores an Embedded License Store (ELS) in the stream of the actual content. In this mechanism, the key used to encrypt the A2 segment itself is called the leaf key {kidA2, ckA2}, and is delivered in the ELS of the segment A2, being itself encrypted with a separate key that is the same for all the segments of track A, called the root key {kidRA, ckRA}. 
> 
> Let's say this asset is live linear TV. When the client attempts playback, it finds kidRA in the PlayReady Header of the stream manifest, and requests a license for kidRA. The License Server returns a root license for the root key {kidRA, ckRA}. Then the client parses segment A1 and discovers the ELS in the header of the segment. Parsing this ELS, it finds the leaf license {kidA1, ckA1} in this ELS. Using the root key {kidRA, ckRA} and the leaf license {kidA1, ckA1}, it can get the value of ckA1, and decrypt and render the segment A1.

**Comment by jeanlf** [comment]
Interesting but not considered yet.

The main problem comes with storing the leaf license in regular (non-fragmented) mode, maybe a custom sample group would do the trick.

If doing directly encryption to dash or plain fmp4 (that would require gpac not mp4box), this should not be too hard but we need to patch the encryptor to produce the leaf pssh at each key roll, probably using a template pssh in the DRM config file...

Do you have any test files for this method ?

**Comment by Murmur** [comment]
Sorry no test files existing yet and do any of the players support it anyway, other than maybe some microsoft provider player :-)

**Comment by jeanlf** [comment]
That was fun ;) see a6b64082 and [related test](https://github.com/gpac/testsuite/blob/master/scripts/encryption_exotic.sh#L101) 

There is also with that commit:
- ability to generate random keys and KIDs in the DRM config file
- ability to embed in base64 some [binary XML](XML-Binary) elements

Documentation for pssh templating is [here](Common-Encryption#drminfotemplate-element-semantics).

**Comment by Murmur** [comment]
@jeanlf Thanks, Links `Binary XML | templating is here` goes to a blank page?

Is this tpl_roll.xml example for a rootKey-leafKey configuration?
https://github.com/gpac/testsuite/blob/master/media/encryption/tpl_roll.xml

- master KeyID pssh in init.mp4 goes in `<DRMInfo..>` as usual. This KeyID is requsted in LaUrl request call.
- four different KeyID+encryption pairs in `<CryptTrack ... keyRoll="rap">`, a key changed on RAP(gop) boundary such as every 2-8 seconds, keys are looped, given segment is encrypted using the active leaf key step.
- I have not seen `<DRMInfoTemplate..>` before, is this data written to segments seg123.m4s/pssh box? This could provide a syntax writing playready root-leaf child pssh table format?
- manifest.mpd is not using a multi `<period>` ? Traditional multikey is writing a new period each time a new init.mp4/pssh table is written.
 
Is it possible to configure segment's leaf pssh be updated on every XX seconds such as every 120 seconds? 

Crazy bonus question: possible to use a gpacdrm.xml format where master KeyID is changed every 30min (=multiperiod boundary in mpd) and segment's leaf key pssh changed every 120 seconds (=no period boundary in mpd)?

**Comment by jeanlf** [comment]
links fixed, sorry about that.

Yes the tpl_roll.xml example is for a master/leaf key config 

> Is it possible to configure segment's leaf pssh be updated on every XX seconds such as every 120 seconds?

yes, using `keyRoll="roll=N"` with N the number of samples (we don't have a syntax using duration ATM).

> Crazy bonus question: possible to use a gpacdrm.xml format where master KeyID is changed every 30min (=multiperiod boundary in mpd) and segment's leaf key pssh changed every 120 seconds (=no period boundary in mpd)?

if using separate inputs for each period that's fairly simple (one DRM file per input/period).

For live setup it's trickier (and independent of pssh template being used), as you need to trigger reconfig of the crypto filter, typically by providing a new DRM config. One way of doing that would be to use the [flist](http://wiki.gpac.io/flist) in splice mode using `mark` directives, and changing the DRM config (`CryptInfo` pid property) at each splice point.

This needs further thinking I believe, as various use cases may have different needs ... We might want to further expand the flist syntax (or use a different filter ...) to only propagate property changes rather than operating splice points.   

> We must use a new gpac.exe binary for drm crypting, traditional mp4box.exe is fine for segmenting?

either gpac or MP4Box will work for encryption and segmentation (I have a howto planned on that topic...)
