### ISSUE TITLE
osmo4 not working android 4.2

### ISSUE THREAD

**Issue by knightrider-kit** [gpac/gpac#2047]
I have installed latest version. Read about some other issues with older android due to symbols but couldn't find anything specific to this. Issue is that libraries will not load because libmediandk.so is not found. App is supposed to work with my version of android (17) but research suggests that libmediandk is only available in android 21+. Is jellybean supported or not?
![Screenshot_2022-01-16-11-10-07](https://user-images.githubusercontent.com/59257536/149669442-8e5c199c-f5cb-4bcb-b9e2-5add6faa7e4e.png)
![Screenshot_2022-01-16-11-09-47](https://user-images.githubusercontent.com/59257536/149669466-a57052a8-77b2-44f8-867d-5f829f140163.png)
![Screenshot_2022-01-16-09-50-24](https://user-images.githubusercontent.com/59257536/149669490-4e2a270e-9c51-49c4-8e21-8d3a851fdad3.png)
![Screenshot_2022-01-16-09-50-13](https://user-images.githubusercontent.com/59257536/149669517-9d2061b2-88f4-429a-b3fa-4b535cc8912f.png)

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ x ] I looked for a similar issue and couldn't find any.
- [ x ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ x ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
We no longer produce binaries for such versions, you will have to recompile yourself:

- follow instructions [here](https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Android)
- before building gpac;
  - comment GPAC_HAS_MEDIACODEC in build/android/jni/libgpac/config.h
  - remove `-llog -lOpenMAXAL -lmediandk -landroid` from build/android/jni/libgpac/Android.mk
