### ISSUE TITLE
who is the idiot that added the clean.bat file in the release code source?!

### ISSUE THREAD

**Issue by allaze-eroler** [gpac/gpac#2048]
seriously dude! that file is PLAIN dangerous..... it DOES deleted almost all my C:// hard drive disk.... thankfully, i only lost 20gb of data... mostly software and windows 10 system... pfff -_-

**Comment by jeanlf** [comment]
- be polite
- don't click on batch file without looking at what they do
- if the problem persist, open a proper issue describing the context (where was your gpac root tree located, did you try to build before cleaning, did you move the batch file out of the tree etc ...)

**Comment by aureliendavid** [comment]
sorry you lost data but there's no need to be insulting

I've removed the script to prevent accidental use
