### ISSUE TITLE
ISOBMFF conformance suite issue

### ISSUE THREAD

**Issue by podborski** [gpac/gpac#2053]
This one is similar to https://github.com/gpac/gpac/issues/1940 

I noticed that the xml dump of file with a `CompactSampleGroupBox` results in invalid xml where `Pattern` tags are never closed.

How to reproduce:

```shell
curl https://conformance.mpeg.expert/ISOBMFF/under_consideration/compact_sample_groups/samplegroups_defrag_compact.mp4 -O
MP4Box -diso samplegroups_defrag_compact.mp4
```

run xml validator on `samplegroups_defrag_compact_info.xml`

Used MP4Box - GPAC version 1.1.0-DEV-rev1632-gf2fddd04-master

btw. is there a way to automate xml validation checks? Could be useful to identify those types of issues when dumping the xml.

**Comment by jeanlf** [comment]
> btw. is there a way to automate xml validation checks? Could be useful to identify those types of issues when dumping the xml

Good idea, now possible using:

`MP4Box -check-xml -diso source`

Works for diso, dnal and dxml, the command will fail if XML parsing fails.
