### ISSUE TITLE
Importing 2nd audio track from mp4 file messes up track ID order in final output file

### ISSUE THREAD

**Issue by jlw4049** [gpac/gpac#2054]
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

`
"C:\Users\jlw_4\Desktop\mp4box.exe" -add "videosource.h264#video:lang=und:fps=23.976" -add "source.mp4#trackID=3#audio:name=AC-3 2.0:delay=0:lang=eng" -set-track-id 3:2 -add "source.srt:lang=und" -add "chapter.txt:fps=23.976" -new "C:\Users\jlw_4\Desktop\working.mp4"`

source.mp4 has TWO audio tracks
I'm trying to get the track #2 from source.mp4 and input it into my working.mp4 output

I can get it to actually get this done, however, it sets all of the track ID's out of order. Instead of them being **Video 1, Audio 2, SRT 3**, it becomes **Video 1, audio 3, srt 4**

If I swap Audio from 3 to 2 with -set-track-id 3:2 then srt will still be 4.

Is there a better way of doing this? I can't seem to find a work around that is accurate. 

I simply would like to be able to import video file, import audio (select which track I want out of the audio, in this case there is 1 video track and two audio tracks, I just want to get audio track 2, which would be ID 3), import srt, import chapters and them output in the correct format 1, 2, 3, etc...

I feel like I'm using the CLI wrong in some way. Thank you!

**Comment by jlw4049** [comment]
After spending hours reading the documents. It seems like there is no way to import a media file with TrackID=3 and it not retain the TrackID=3 information?

**Comment by jeanlf** [comment]
FYI there is no "correct" format here for trackIDs, as long as track dependencies are properly set.

But indeed, one could only do that track by track using -set-track-id or -swap-track-id, which is not very convenient.

Using latest master:

```
MP4Box -add src.mp4#video:ID=-1 -add src.mp4#3:ID=-1 -add subtitle.srt -new test.mp4
```


You can also try to assign the track IDs directly


```
MP4Box -add src.mp4#video:ID=10 -add src.mp4#3:ID=12 -add subtitle.srt:ID=11 -new test.mp4
```

Thanks for reporting that.

**Comment by jlw4049** [comment]
The new commands work perfectly! I am able to do what I wanted now. I appreciate the information and I appreciate the quick work you did!
