### ISSUE TITLE
Getting size of individual fragments(chunks) after segmenting using MP4Box

### ISSUE THREAD

**Issue by AdithyaRaman** [gpac/gpac#2056]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I am using a video for ABR development with segment size as 1000ms and chunk(or frag) size as 200ms.
I need to get size (in bytes) for individual chunks and my idea was to use MP4Box to segment my video and use the file size of the **.m4s** files that would be generated.

The cmd I used below however only generates a file for each segment and not for each chunk. Additionally the mpd file generated has no mention of the frag size I specified which makes me wonder if the current version of MP4Box has support for frags.

`MP4Box -dash 1000 -frag 200 -profile live -out bbb_300/bbb_300.mpd bbb_300.mp4`

Would there be another route that I could take to get the size of individual chunks for the video ?

**Comment by jeanlf** [comment]
When doing LL the fragment size within the segment is usually not exposed to the outside world:
- in DASH you don't see it in the MPD
- in LL-HLS you only have access to the fragments ("parts") of the 2 or 3 segments at live edge in the M3U8


You can do an XML dump of the segment (`MP4Box -diso segment.m4s`) to check moof and mdat sizes.

Using latest master, `MP4Box -info segment.m4s` will now dump size of segment as well.

**Comment by AdithyaRaman** [comment]
Thanks, This seems to do the job.
But one curious observation.
I am segmenting my video with 1 sec segments and 200ms fragments (Like below)
```

(base) adithya@amaramindu:~/ub/ub/research/simulators/video_files$ MP4Box -dash 1000 -frag 200 -profile live -out bbb_300/bbb_300.mpd bbb_300_new.mp4
[DASH]: WARNING! DASH Live profile requested but no -segment-name
	using "%s_dash" by default

DASH-ing file: 1.00s segments 0.20s fragments single sidx per segment
Splitting segments at GOP boundaries
DASHing file bbb_300_new.mp4
[DASH] Generating MPD at time 2022-01-21T11:21:26.459Z 
```

So ideally there should be 5 chunks per segments (1000/200 = 5).

However only the first segment seems to have 5 fragments while the rest have 4 fragments.
```
(base) adithya@amaramindu:~/ub/ub/research/simulators/video_files/bbb_300$ MP4Box -info bbb_300_new_dash1.m4s 
File is a segment - 5 movie fragments - Brand msdh (version 0):
	Fragment #1 Track ID 1 - TFDT 0
	Fragment #2 Track ID 1 - TFDT 1536
	Fragment #3 Track ID 1 - TFDT 3072
	Fragment #4 Track ID 1 - TFDT 6144
	Fragment #5 Track ID 1 - TFDT 9216
(base) adithya@amaramindu:~/ub/ub/research/simulators/video_files/bbb_300$ MP4Box -info bbb_300_new_dash2.m4s 
File is a segment - 4 movie fragments - Brand msdh (version 0):
	Fragment #1 Track ID 1 - TFDT 9728
	Fragment #2 Track ID 1 - TFDT 12800
	Fragment #3 Track ID 1 - TFDT 15872
	Fragment #4 Track ID 1 - TFDT 18944

```

**Comment by jeanlf** [comment]
that's likely due to the input key frames not being exactly every second, you can check that using:

`MP4Box -diso  bbb_300_new.mp4` and check the SyncSampleBox (assuming the source file is not fragmented)

or

`gpac -i bbb_300_new.mp4 reframer:saps=1 @ inspect:deep`

or using segment timeline in your dash command (`--stl`) look at the `SegmentTimeline` element in the MPD.

**Comment by AdithyaRaman** [comment]
Judging from what I am seeing in the SyncSampleBox from the mpd file generated from the source  bbb_300_new.mp4 video, I feel that my IDR frames are not at regular positions ( Similar to what you had pointed out). 


```
<SyncSampleBox Size="1876" Type="stss" Version="0" Flags="0" Specification="p12" Container="stbl" EntryCount="465">
<SyncSampleEntry sampleNumber="1"/>
<SyncSampleEntry sampleNumber="13"/>
<SyncSampleEntry sampleNumber="25"/>
<SyncSampleEntry sampleNumber="37"/>
<SyncSampleEntry sampleNumber="49"/>
<SyncSampleEntry sampleNumber="61"/>
.
.
.
</SyncSampleBox>
```


The other observation I made was when I used MP4Box to segment my 3 min video to 1 second segments with 200 ms chunks, I expected to see ~180 m4s files. But instead 224 files were generated.

I am guessing my next step would be to use ffmpeg to ensure my IDR frames are at regular 1 second intervals so segmentation would produce equal size segments

**Comment by AdithyaRaman** [comment]
Encoding the video to force IDR frames at regular 1 sec intervals with ffmpeg seemed to do the trick. I used the below cmd

`ffmpeg -i bbb.mp4 -g 30 -keyint_min 30 -force_key_frames "expr:gte(t,n_forced*1)" output.mp4`

Now I see perfect segmentation when I use MP4Box
Appreciate the help.

**Comment by jeanlf** [comment]
you can also do this in one pass with gpac:

`gpac -i bbb.mp4 enc:c=avc:b=1m @ -o dash/live.mpd`

The dasher filter will signal the target segment duration (default `segdur=1`) to the filters down the chain, and ffenc will use this to configure closed-gop intra frame injection every segdur.
