### ISSUE TITLE
DashCast capture webcam error with AVFrame.format is not set

### ISSUE THREAD

**Issue by davidlou** [gpac/gpac#206]
I am new to the DashCast. I want to use DashCast to stream live video from a webcam. After installation with the instructions from https://gpac.wp.mines-telecom.fr/dashcast/, I tried with the first example

DashCast -vf video4linux2 -v4l2f mjpeg -vfr 30 -vres 1280x720 -v /dev/video0 -conf dashcast.conf -live

But it failed with the following message:
[libx264@0x7f52380000920] AVFrame.format is not set
[libx264@0x7f52380000920] AVFrame.width or height is not set
[libx264@0x7f52380000920] AVFrame.format is not set
[libx264@0x7f52380000920] AVFrame.width or height is not set
.......

I have tried to tune some parameters, e.g. codec from mjpeg to yuyv422, resolution from 1280x720 to 960x540, etc. Neither works around. Can anyone help me there? Is there more online documentation about DashCast?

Many thanks in advance
David

**Comment by davidlou** [comment]
BTW, I installed DashCast on a ubuntu 14.04, 64-bit.

**Comment by JamesXu20150314** [comment]
Can you show the context of your dashcast.conf

**Comment by JamesXu20150314** [comment]
I also have this problem. But I cannot connect to the video, the program will be blocked.

**Comment by davidlou** [comment]
my dashcast.conf is a very simple one.
[v1]
type=video
bitrate=1200000
width=960
height=540

**Comment by JamesXu20150314** [comment]
Thank you very much. Can you help me with my errors:
zhiminxu@zhiminxu-virtual-machine:~/coder/test$ DashCast -vf video4linux2 -vres 640x480 -vfr 30 -v4l2f yuyv422 -v /dev/video0 -live
Options:
    video source: /dev/video0
    video format: video4linux2
    v4l2 format: yuyv422
    video framerate: 30
    video resolution: 640x480
    video crop: 0x0
    audio source: 
Configurations:
    id:v1       res:640x480     vbr:147456
[video4linux2,v4l2 @ 0x9fd1fc0] Dequeued v4l2 buffer contains 2360 bytes, but 614400 were expected. Flags: 0x00002005.
Input #0, video4linux2,v4l2, from '/dev/video0':
  Duration: N/A, bitrate: 147456 kb/s
    Stream #0:0: Video: rawvideo (YUY2 / 0x32595559), yuyv422, 640x480, 147456 kb/s, 30 fps, 30 tbr, 1000k tbn, 1000k tbc
Press q or Q to exit...
[video4linux2,v4l2 @ 0x9fd1fc0] Dequeued v4l2 buffer contains 268800 bytes, but 614400 were expected. Flags: 0x00002005.
Cannot read video frame.
[video4linux2,v4l2 @ 0x9fd1fc0] Dequeued v4l2 buffer contains 251492 bytes, but 614400 were expected. Flags: 0x00002005.
Cannot read video frame.
[video4linux2,v4l2 @ 0x9fd1fc0] Dequeued v4l2 buffer contains 230402 bytes, but 614400 were expected. Flags: 0x00002005.


Thank you very much.

**Comment by JamesXu20150314** [comment]
This is my dashcast.conf:
[v1]
type=video
bitrate=147456
width=640
height=480

**Comment by jeanlf** [comment]
dashcast is now deprecated, use GPAC 0.9.0
