### ISSUE TITLE
wanted create and MPD file for 360 degree video using SRD?

### ISSUE THREAD

**Issue by Faiz786-Hp-rgb** [gpac/gpac#2063]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by Faiz786-Hp-rgb** [comment]
https://github.com/Faiz786-Hp-rgb kindly reply to me at this, please.

**Comment by rbouqueau** [comment]
We have some documentation: https://github.com/gpac/gpac/wiki/MPEG-DASH-SRD-and-HEVC-tiling-for-VR-videos. Please read and let us know if you have any problem.

**Comment by jeanlf** [comment]
also [here](HEVC-Tile-based-adaptation-guide), and some [tests here](https://github.com/gpac/testsuite/blob/master/scripts/dash-srd-hevc.sh)
