### ISSUE TITLE
Mac Crash Attempting to Open Multicast TS

### ISSUE THREAD

**Issue by bwalls** [gpac/gpac#207]
I am attempting to play an MPEG-2 TS multicast stream with the Mac OSMO4 player. I enter the URL (udp://233.3.3.197:30120) on the playlist. As soon as I select it from the playlist, OSMO4 crashes. 

Running OS X 10.10.5, have tried  the two most recent dailies:
gpac-0.5.2-DEV-rev552-g5a1b427-master
gpac-0.5.2-DEV-rev553-gfb86514-master

I also tried on 10.8.5, but there OSMO4 crashes on launch. 

The stream I'm testing with is a well known MPEG-2 TS with H.264/AAC payload. It plays fine in VLC. Ultimately, I'm needed to receive a 4K HEVC TS, but small steps first...

**Comment by bwalls** [comment]
Same result in gpac-0.5.2-DEV-rev563-ge3b29f0-master.dmg

**Comment by rbouqueau** [comment]
Is this still relevant? Is there a way to get acces to a file or capture or command-line to reproduce the issue?

**Comment by jeanlf** [comment]
closing, try with latest master or filters branch
