### ISSUE TITLE
Video MP4 file with Dolby Vision Profile 8.1, created using MP4Box, is not determined by the built-in Sony TV player as video with Dolby Vision

### ISSUE THREAD

**Issue by Juca1107** [gpac/gpac#2076]
Other Android TV players (such as JustPlayer) recognize in the Dolby Vision file.
With this video file, the file collected by the MP4MUXER program (DLB_MP4BASE \ MP4MUXER) from the same components (H265 and AC3) is determined on the built-in Sony TV player as a full Dolby Vision.
Comparison Output MP4Info (Bento4 \ Mp4Info) on the problematic and normal files showed that the difference in them is only that the file made using MP4Box does not have the "in-movie" and "in-preview" flags in contrast to the file, Made using MP4MUXER.

Conclusion for MP4Box:
Found 2 Tracks.
Track 1:
  Flags: 1 Enabled
  ID: 1.
  Type: Video.

Conclusion for MP4MUXER:
Found 2 Tracks.
Track 1:
  Flags: 15 Enabled In-Movie In-Preview
  ID: 1.
  Type: Video.

Is it possible to add to the MP4BOX program to add the options "in-movie" and "in-preview" for the import of video and audio components?

**Comment by Juca1107** [comment]
Command to create a file:
"C:\Program Files\GPAC\mp4box.exe" -tmp D:\bj\ -add D:\bj\bj-sample.h265:dv-profile=8.hdr10:xps_inband:hdr=none -add D:\bj\bj-sample.ac3 -brand mp42:1 -ab dby1 -ab isom -no-iod -new D:\bj\bj-8-new1.mp4

**Comment by Juca1107** [comment]
MP4Box - GPAC version 1.1.0-DEV-rev1665-ga6b64082-master

**Comment by jeanlf** [comment]
can you try setting the flags at import:
`MP4Box -add source:tkhd=0x7 -new dst.mp4`

The default behavior does not set any flags other than the track_enabled flag as these other flags were historically reserved (qt-use only). We'll need to change that behavior (at least to set the track_in_movie flag) one of these days, but that might be problematic for systems relying on muxed file hashes to check for regressions (including our own test system ...)

**Comment by jeanlf** [comment]
now set by default

**Comment by jeanlf** [comment]
could you upload the working file ? If not, do `MP4Box -diso` on both files and post the results

**Comment by Juca1107** [comment]
Could you give a full command?

**Comment by Juca1107** [comment]
Output from mp4box created file:
[bj-8-new1671-tkhd0x7_info.xml.txt](https://github.com/gpac/gpac/files/7951852/bj-8-new1671-tkhd0x7_info.xml.txt)

**Comment by Juca1107** [comment]
Output from mp4muxer created file (worked
[bj-sample-mp4muxer_info.xml.txt](https://github.com/gpac/gpac/files/7951858/bj-sample-mp4muxer_info.xml.txt)
):

**Comment by Juca1107** [comment]
Files renamed to txt

**Comment by jeanlf** [comment]
the main difference in the video tracks:
- presence of colr and pasp box in mp4box mux
- presence of 'rap ' sample group description and sample group in mp4box mux
- flags set to 7 in mp4box mux while they are set to 15 in dlby mux

you can try muxing the video track using `-add sample.h265:dv-profile=8.hdr10:xps_inband:hdr=none:colr=none` to remove the colr box info and see if that works

**Comment by Juca1107** [comment]
As a result, the tests found the following when creating MP4 files using MP4BOX (video stream only):
The MP4 file is functioning normally if its duration <= 69 seconds
MP4 file does not play if its duration >= 70 seconds
The source file H265 is the same (parameter is used :dur=69 or :dur=70)
Any ideas?

**Comment by Juca1107** [comment]
[bj.zip](https://github.com/gpac/gpac/files/7953565/bj.zip)
bj70-mp4box.mp4 (duration 70seconds) - not playing
bj70-mp4muxer.mp4 (duration 70seconds) - playing
bj69-mp4box.mp4 (duration 69seconds) - playing

**Comment by jeanlf** [comment]
The only important difference I can see is the presence of 'rap ' sample group. Using latest master, can you try adding `--norap` to your mp4box mux command line to disable this sample group ?

**Comment by Juca1107** [comment]
What build number should be the last master?
In Build 1678 output: Arg norap set but not used

**Comment by jeanlf** [comment]
rev1681 - if you use the binaries you'll need to wait a bit...

**Comment by Juca1107** [comment]
There is a new idea.
The reason may be the presence of the Maximum Bit Rate field generated by the MAXIMUM BIT RATE (MAXBITRATE).
In problem files, this field has gigantic values.
In good files, this value does not exceed 51.0 MB / S
In the files made using MP4MUXER, this field is missing.
Maxbitrate is not clearly calculated correctly.
Is it possible to disable the generation of this field or make the calculation more correct.
In the previously attached files, the Maxbitrate values ​​are visible.

**Comment by jeanlf** [comment]
> Is it possible to disable the generation of this field or make the calculation more correct.

yes, add `--btrt=0` to your mux command line - cf [mp4mx](https://github.com/gpac/gpac/wiki/mp4mx#btrt)

**Comment by Juca1107** [comment]
Adding the key "--btrt=0" solved the problem. Files made using this key are played correctly regardless of duration and size.
Thank you very much!
