### ISSUE TITLE
MP4Box scales edit duration incorrectly when mediaTime is a float

### ISSUE THREAD

**Issue by m-i-dyer** [gpac/gpac#2082]
For example using Big Buck Bunny:

'MP4Box bbb_sunflower_1080p_30fps_normal.mp4 -edits 1=re0.1-5,0.1 -out tmp.mp4'

Gives the following results in 'MP4Box -disox':

```
<MovieHeaderBox Size="108" Type="mvhd" Version="0" Flags="0" Specification="p12" Container="moov" CreationTime="3470060679" ModificationTime="3470060679" TimeScale="600" Duration="380520" NextTrackID="4">

...

<MediaHeaderBox Size="32" Type="mdhd" Version="0" Flags="0" Specification="p12" Container="mdia" CreationTime="3470060679" ModificationTime="3470060682" TimeScale="30000" Duration="19036000" LanguageCode="und">

...

<EditBox Size="48" Type="edts" Specification="p12" Container="trak" >
<EditListBox Size="40" Type="elst" Version="0" Flags="0" Specification="p12" Container="edts" EntryCount="2">
<EditListEntry Duration="60" MediaTime="-1" MediaRate="1"/>
<EditListEntry Duration="300" MediaTime="3000" MediaRate="1"/>
</EditListBox>
</EditBox>
```

The 2nd EditListEntry duration is not 5 seconds, but 0.5 seconds.  MediaTime is correct.

I think this is due to an extra scaling operation [here](https://github.com/gpac/gpac/blob/6b5bdbc7f88eb11aa65657ebb97269c11a07711a/applications/mp4box/fileimport.c#L544) where the duration is scaled by ```movie_time.den```

**Comment by jeanlf** [comment]
correct now fixed, thanks for the report
