### ISSUE TITLE
DashCast cannot connect the video in Windows using vfwcap.

### ISSUE THREAD

**Issue by JamesXu20150314** [gpac/gpac#209]
Hi, I also develop some project on Windows 7 X64bit with the dashcast. But I don't know how to connect to the video with vfwcap option. Such as:
DashCast -vf vfwcap -vres 1280x720 -vfr 24 -v 0 -live
But I recieve the rusult is :

C:\Users\Administrator\Desktop\test1>DashCast -vf vfwcap -vres 1280x720 -vfr 24 -v 0 -live
MPD refresh time not set in live - defaulting to segment duration
�[34m�[1mOptions:
video source: 0
video format: vfwcap
video framerate: 24
video resolution: 1280x720
video crop: 0x0
audio source:
�[0m�[34m�[1mConfigurations:
id:v1 res:640x480 vbr:400000
id:a1 abr:192000
�[0m[vfwcap @ 0000000000689620] Could not connect to device.
Error -19 opening input - retrying without options
[vfwcap @ 0000000000689480] Could not connect to device.
Cannot open file 0
Cannot open input video.

Can you help me? Thank you very much.
Cannot open input video.

**Comment by cconcolato** [comment]
I have the same problem. Will try to look at it.

**Comment by cconcolato** [comment]
Have you tried with DirectShow? 
```
DashCast -vf dshow  -vres 1280x720 -vfr 24 -v video="YOUR-WEBCAM" -pixf yuv420p -live
```

**Comment by JamesXu20150314** [comment]
I have try it. But I don't know how to insert the value to repalce the "YOUR-WEBCAM".
Such as:
C:\Users\Administrator\Desktop\test1>DashCast -vf dshow  -vres 1280x720 -vfr 24 -v video="0" -pixf yuv420p -live
MPD refresh time not set in live - defaulting to segment duration
[34m[1mOptions:
    video source: video=0
    video format: dshow
    video framerate: 24
    video resolution: 1280x720
    video crop: 0x0
    audio source:
[0m[34m[1mConfigurations:
    id:v1       res:640x480     vbr:400000
    id:a1       abr:192000
[0m[dshow @ 00000000006d96c0] Could not find video device.
Error -5 opening input - retrying without options
[dshow @ 00000000006d9480] Could not find video device.
Cannot open file video=0
Cannot open input video.

C:\Users\Administrator\Desktop\test1>DashCast -vf dshow  -vres 1280x720 -vfr 24 -v video="winvideo" -pixf yuv420p -live
MPD refresh time not set in live - defaulting to segment duration
[34m[1mOptions:
    video source: video=winvideo
    video format: dshow
    video framerate: 24
    video resolution: 1280x720
    video crop: 0x0
    audio source:
[0m[34m[1mConfigurations:
    id:v1       res:640x480     vbr:400000
    id:a1       abr:192000
[0m[dshow @ 00000000008596c0] Could not find video device.
Error -5 opening input - retrying without options
[dshow @ 0000000000859480] Could not find video device.
Cannot open file video=winvideo
Cannot open input video.

C:\Users\Administrator\Desktop\test1>DashCast -vf dshow  -vres 1280x720 -vfr 24 -v video="virtual-camera-show" -pixf yuv420p -live
MPD refresh time not set in live - defaulting to segment duration
[34m[1mOptions:
    video source: video=virtual-camera-show
    video format: dshow
    video framerate: 24
    video resolution: 1280x720
    video crop: 0x0
    audio source:
[0m[34m[1mConfigurations:
    id:v1       res:640x480     vbr:400000
    id:a1       abr:192000
[0m[dshow @ 00000000007896c0] Could not find video device.
Error -5 opening input - retrying without options
[dshow @ 000000000078f7c0] Could not find video device.
Cannot open file video=virtual-camera-show
Cannot open input video.

I am so glad to discuss with you. I hope that we can help each other.

**Comment by cconcolato** [comment]
Apparently support in ffmpeg for vfwcap is not so good: see
[http://stackoverflow.com/questions/8783781/why-does-recoding-video-with-ffmpeg-on-windows-always-give-an-error](this post) 
or [https://groups.google.com/forum/#!topic/xuggler-users/2OKNGutfypo](this other post). 
We should remove it from the command line examples and only recommend dshow.

Now to know the exact name of your device with DirectShow you need to use ffmpeg:
```
ffmpeg -list_devices true -f dshow -i dummy 
```
See [https://trac.ffmpeg.org/wiki/DirectShow](ffmpeg's documentation) for more info.

**Comment by JamesXu20150314** [comment]
Oh, thank you  very much. That means I need to install ffmpeg in my windows.

I am so happy you can give me this infomation. 

Now I have a new problem in Linux:

zhiminxu@zhiminxu-virtual-machine:~/coder/test$ DashCast -vf video4linux2 -vres 100x50 -vfr 30 -v /dev/video0 -live
Options:
    video source: /dev/video0
    video format: video4linux2
    video framerate: 30
    video resolution: 100x50
    video crop: 0x0
    audio source: 
Configurations:
    id:v1       res:640x480     vbr:4000
[video4linux2,v4l2 @ 0x86f1f80] The V4L2 driver changed the video from 100x50 to 320x240
[video4linux2,v4l2 @ 0x86f1f80] Dequeued v4l2 buffer contains 75060 bytes, but 153600 were expected. Flags: 0x00002005.
Input #0, video4linux2,v4l2, from '/dev/video0':
  Duration: N/A, bitrate: 36864 kb/s
    Stream #0:0: Video: rawvideo (YUY2 / 0x32595559), yuyv422, 320x240, 36864 kb/s, 30 fps, 30 tbr, 1000k tbn, 1000k tbc
Press q or Q to exit...
[video4linux2,v4l2 @ 0x86f1f80] Dequeued v4l2 buffer contains 60800 bytes, but 153600 were expected. Flags: 0x00002005.
Cannot read video frame.
[video4linux2,v4l2 @ 0x86f1f80] Dequeued v4l2 buffer contains 57600 bytes, but 153600 were expected. Flags: 0x00002005.
Cannot read video frame.
[video4linux2,v4l2 @ 0x86f1f80] Dequeued v4l2 buffer contains 75068 bytes, but 153600 were expected. Flags: 0x00002005.
Cannot read video frame.
[video4linux2,v4l2 @ 0x86f1f80] Dequeued v4l2 buffer contains 60800 bytes, but 153600 were expected. Flags: 0x00002005.
Cannot read video frame.
[video4linux2,v4l2 @ 0x86f1f80] Dequeued v4l2 buffer contains 60800 bytes, but 153600 were expected. Flags: 0x00002005.
Cannot read video frame.
[video4linux2,v4l2 @ 0x86f1f80] Dequeued v4l2 buffer contains 76800 bytes, but 153600 were expected. Flags: 0x00002005.
Cannot read video frame.
[video4linux2,v4l2 @ 0x86f1f80] Dequeued v4l2 buffer contains 58242 bytes, but 153600 were expected. Flags: 0x00002005.
Cannot read video frame.
......

Can you help me.

**Comment by cconcolato** [comment]
Please open a new issue so that we can track them properly. For ffmpeg on windows, see http://ffmpeg.zeranoe.com/builds/

**Comment by JamesXu20150314** [comment]
OK, Thank you very much.
