### ISSUE TITLE
A strange erros in the Unbuntu 14.04 LTS about DashCast.

### ISSUE THREAD

**Issue by JamesXu20150314** [gpac/gpac#210]
I find a strange problem in my use of dashcast:
As follow:

roots@roots-virtual-machine:~/coder/test$ DashCast -vf video4linux2 -vres 640x480 -vfr 30 -v4l2f yuyv422 -v /dev/video0 -live
Options:
    video source: /dev/video0
    video format: video4linux2
    v4l2 format: yuyv422
    video framerate: 30
    video resolution: 640x480
    video crop: 0x0
    audio source: 
Configurations:
    id:v1       res:640x480     vbr:147456
[video4linux2,v4l2 @ 0x8d94fc0] Dequeued v4l2 buffer contains 962 bytes, but 614400 were expected. Flags: 0x00002005.
Input #0, video4linux2,v4l2, from '/dev/video0':
  Duration: N/A, bitrate: 147456 kb/s
    Stream #0:0: Video: rawvideo (YUY2 / 0x32595559), yuyv422, 640x480, 147456 kb/s, 30 fps, 30 tbr, 1000k tbn, 1000k tbc
Press q or Q to exit...
[video4linux2,v4l2 @ 0x8d94fc0] Dequeued v4l2 buffer contains 230402 bytes, but 614400 were expected. Flags: 0x00002005.
Cannot read video frame.
[video4linux2,v4l2 @ 0x8d94fc0] Dequeued v4l2 buffer contains 242858 bytes, but 614400 were expected. Flags: 0x00002005.
Cannot read video frame.
[video4linux2,v4l2 @ 0x8d94fc0] Dequeued v4l2 buffer contains 281274 bytes, but 614400 were expected. Flags: 0x00002005.
Cannot read video frame.
[video4linux2,v4l2 @ 0x8d94fc0] Dequeued v4l2 buffer contains 242878 bytes, but 614400 were expected. Flags: 0x00002005.
Cannot read video frame.
[video4linux2,v4l2 @ 0x8d94fc0] Dequeued v4l2 buffer contains 230400 bytes, but 614400 were expected. Flags: 0x00002005.
Cannot read video frame.

I hope anyone can help me.Thanks so much.

**Comment by cconcolato** [comment]
This seems to be an ffmpeg bug see https://trac.ffmpeg.org/ticket/4030. You need to apply the proposed patch to ffmpeg and then recompile.

**Comment by JamesXu20150314** [comment]
Thank you very much. I will take a look at that website.
