### ISSUE TITLE
MP4Box copyright itag doesn't work

### ISSUE THREAD

**Issue by MartiCode** [gpac/gpac#2117]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). 

Using the test command:
mp4box -itags copyright=TestString test.mp4

Then:
mp4box -info test.mp4

Shows existing but empty coypright tag. ffprobe can't see any copyright tag at all.

Trying to set the copyright tag again results in error message:
[iso file] Read Box type C-0000 (0x432D0000) at position 270566371 has size 0 but is not at root/file level !
[iso file] Box "cprt" (start 270566363) has 28 extra bytes

**Comment by jeanlf** [comment]
indeed there was a mixup with regular cprt box from qt/isobmff, now fixed
