### ISSUE TITLE
gpac generated ll-hls files cannot play normally

### ISSUE THREAD

**Issue by GlassyYang** [gpac/gpac#2119]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I use gpac to cut a mp4 file into ll-hls files and use nginx to serve them. gpac command I used is:
```shell
gpac -i ~/Videos/436256398-1-208.mp4  -o res/playlist.m3u8:gpac:segdur=6:cdur=1:profile=live:dmode=dynamic:rdirs=outdir:llhls=sf
```
I use https://www.theoplayer.com/ll-hls-test-page to verify ll-hls and find that the video is playing for 2~3s then it starts buffering infinitly. I use sample ll-hls test url and it can play normally and I believe that bandwidth is not bottleneck because I run nginx on  `localhost`.
I try to build `gpac` by myself, also try to use latest nightly prebuilded version of `gpac`  on [gpac official site](gpac.io) on Ubuntu 18.04, but this question still happpen. I want to know why and how to fix this question.

**Comment by jeanlf** [comment]
Did you also try in regular mode (no LL-HLS) ?

This command line will not transcode the video, did you make sure that you indeed have an I-frame every 6 seconds ? You can check using

```
gpac -i ~/Videos/436256398-1-208.mp4  reframer:saps=1 inspect:deep
```

**Comment by GlassyYang** [comment]
I'm sure this video file can be played normally but I don't know key frame interval of that video. Can you tell me how to reformat video so that it can satiafy requirements of ll-hls under above gpac parameters?

**Comment by jeanlf** [comment]
> but I don't know key frame interval of that video
That's the command I gave you.


To run your HLS with video transcoding (1mbps, adjust your encoder params as needed):

```
gpac -i ~/Videos/436256398-1-208.mp4  c=avc:b=1m -o res/playlist.m3u8:gpac:segdur=6:cdur=1:profile=live:dmode=dynamic:llhls=sf
```

If you want to transcode separately from dashing, you must set the`fintra`option to match your desired segmentation boundaries:

```
gpac -i ~/Videos/436256398-1-208.mp4  c=avc:b=1m:fintra=6 -o transcoded.mp4
gpac -i transcoded.mp4 res/playlist.m3u8:gpac:segdur=6:cdur=1:profile=live:dmode=dynamic:llhls=sf
```

**Comment by GlassyYang** [comment]
I try following command and it's playing well:
```shell
gpac avgen @ reframer:rt=on @ enc:c=aac @1 enc:c=avc @ @1 -o http://127.0.0.1:8889/live.m3u8:gpac:segdur=10:cdur=1:profile=live:dmode=dynamic:llhls=sf:rdirs=/tmp/gpac
```
so I try to use obs and following command, it's also playing well:
```shell
gpac -i 'rtmp://:1935/live/test:gpac:rtmp_listen=1' reframer:rt=on  -o http://127.0.0.1:8889/live.m3u8:gpac:segdur=10:cdur=1:profile=live:dmode=dynamic:llhls=sf:rdirs=/tmp/gpac
```
I try to write a HTTP server, and use following command pushing hls files into my HTTP server:
```
gpac -i 'rtmp://:1935/live/test:gpac:rtmp_listen=1' reframer:rt=on  -o http://127.0.0.1:8080/ll-hls/live.m3u8:gpac:segdur=4:cdur=1:profile=live:dmode=dynamic:llhls=sf:hmode=push
```
The question is that I find that `gpac` just push  segment files and manifest files, even if `llhls=sf` is used. Initially, I think that `gpac` use HTTP 1.1 chunked encoding, each chunk in HTTP request is a ll hls chunk, Finally find that the number of chunks in `gpac`'s PUT method isn't equals to number of ll-hls chunks a segment file should have when `gpac` pushes a segment file into my HTTP server. If `gpac` don't push chunk file, How do I serve ll-hls chunk to other file? Is there a way I can cut  ll-hls segment  into ll-hls chunks?

**Comment by GlassyYang** [comment]
ll-hls chunks was pushed to my http server and the server can serve ll-hls normally.
