### ISSUE TITLE
EMSG boxes are lost in fMP4 after MP4Box processing

### ISSUE THREAD

**Issue by katietian** [gpac/gpac#2121]
Hi,

Thanks in advance for any help. Please let me know if I should send more information privately.

**Summary**
I had a `sample.mp4` file which has embedded EMSG boxes carrying custom metadata. To serve it via DASH, I used MP4Box to generate the mpd manifest file, and MP4Box generates two files for me

- `sample_dash.mpd`
- `sample_dashinit.mp4`

**Expected Result**
The EMSG boxes in the original fMP4 is preserved in `sample_dashinit.mp4` and served via `sample_dash.mpd`

**Actual Result**
The generated sample_dashinit.mp4 no longer have EMSG boxes.

**Repro Steps**

1. Take any fragmented MP4 file with EMSG boxes
2. run `MP4Box -dash 100000 sample.mp4`
3. Load the generated `sample_dashinit.mp4` using https://gpac.github.io/mp4box.js/test/filereader.html, and no EMSG boxes are in BoxView > TreeView

I might have missed any usage to preserve the EMSG boxes - can someone help advice any proper usage of MP4Box or any workaround in this case? Thanks.

Also copying the generated mpd file
```
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 1.1.0-DEV-rev1759-geb2d1e6dd-master at 2022-02-17T06:23:14.473Z -->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H0M23.992S" maxSegmentDuration="PT0H0M23.993S" profiles="urn:mpeg:dash:profile:full:2011">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>sample_dash.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H0M23.992S">
  <AdaptationSet segmentAlignment="true" maxWidth="1920" maxHeight="1080" maxFrameRate="96000/3199" par="16:9" lang="und" startWithSAP="1">
   <InbandEventStream schemeIdUri="urn:mpeg:dash:event:2012" value="1"/>
   <Representation id="1" mimeType="video/mp4" codecs="hev1.1.6.L150.0" width="1920" height="1080" frameRate="96000/3199" sar="1:1" bandwidth="3030916">
    <BaseURL>sample_dashinit.mp4</BaseURL>
    <SegmentList timescale="96000" duration="9600000">
     <Initialization range="0-847"/>
     <SegmentURL mediaRange="848-9097166" indexRange="848-891"/>
    </SegmentList>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```

**Environment Info**
```
MP4Box -version                     
MP4Box - GPAC version 1.1.0-DEV-rev1759-geb2d1e6dd-master
(c) 2000-2022 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io
	MINI build (encoders, decoders, audio and video output disabled)

Please cite our work in your research:
	GPAC Filters: https://doi.org/10.1145/3339825.3394929
	GPAC: https://doi.org/10.1145/1291233.1291452

GPAC Configuration: --static-mp4box
Features: GPAC_CONFIG_LINUX GPAC_64_BITS GPAC_HAS_SOCK_UN GPAC_MINIMAL_ODF GPAC_HAS_QJS GPAC_HAS_JPEG GPAC_HAS_PNG  GPAC_DISABLE_3D 
```

**Comment by jeanlf** [comment]
There is no support for emsg box other than dumping at the current time. If you can upload a sample file I can have a look at that

**Comment by jeanlf** [comment]
there should now be some support for that in master, could you cross-check ?

**Comment by katietian** [comment]
Thank you @jeanlf! I just verified that EMSG boxes are succesfully preserved with your change. Thanks for the quick turnaround.

**Comment by katietian** [comment]
Hi @jeanlf , sorry for circling back. On a second look, I noticed below unexpected changes to the EMSG boxes in the fMP4 (`original.mp4` -> `original_dashinit.mp4`):

When viewing from [MP4Box.js](https://gpac.github.io/mp4box.js/test/filereader.html) tool,
1. The structure of the boxes changes. The original video has one EMSG box before each MOOF box, while the `_dashinit.mp4` file after processing has EMSG boxes all clustered before the generated sidx box and the 1st moof box
2. The `start` property in EMSG boxes has changed. E.g., the EMSG boxes of the original video has start time of 646, 202693, 312324, 442975, ... and the file after processing shows 872, 951, 1030, 1109, ... which seems to be at a totally different scale. The `start` properties are also changed in other boxes as well

I've attached the original file and the generated file (generated by running `MP4Box -dash 1000000 sample.mp4`). Can you help take a look? My questions are mainly -
1. Can we keep the original structure of emsg boxes (one emsg box before each moof box) in the processed .mp4?
2. Is `start` property change intended (e.g., some calculation is done during segmentation)? This sample video is mainly used to test timed metadata, and I noticed that after the `start` change, emsg boxes are all loaded at the beginning of the video in a player, while we expect them to be output evenly through the video playback.

https://user-images.githubusercontent.com/65938624/154711557-6a8c4044-0b66-4953-9e0b-3385126633f1.mp4

https://user-images.githubusercontent.com/65938624/154712073-f3e13a8c-9569-4974-ad10-67ff3efbbaef.mp4

**Comment by jeanlf** [comment]
indeed this was not properly working for ondemand profiles, only live. Should now be fixed, could you cross-check ?

**Comment by jeanlf** [comment]
also regarding 2 (emsg@start),  I'm not sure I get the issue, there is no start property in `emsg`, and the current code only copies over the the `emsg` boxes. Where is this `start`info coming from ?

**Comment by katietian** [comment]
Hi @jeanlf , thanks for the reply. I tried out the latest version and seems the emsg boxes are still clustered. I'm marking what I meant for 1 (structure) and 2 (value of start property) in the below before-and-after screenshots and hope it helps:

**Original video box structure:**

![original](https://user-images.githubusercontent.com/65938624/154897719-206df700-8aa9-47b3-98c9-ad4e9c9c7ebb.png)

**Processed video box structure:**
![processed(_dashinit)](https://user-images.githubusercontent.com/65938624/154897810-62e1cf34-1e4c-4105-921d-9fa99f697d95.png)

Essentially I notice that my mobile player is reading emsg boxes all at the beginning of the video, and I suspect that it's due to either the restructure or the start time change. Thank you in advance for your help!

**Comment by jeanlf** [comment]
Are you sure you're up to date ? Using latest master and `MP4Box -dash 1000000 sample.mp4` on your provided file gives me one emsg before each moof, and non before the sidx.

**Comment by jeanlf** [comment]
Also, the `@start` property has nothing to do with `emsg`, it is the position of first byte of the box header in the file.

**Comment by katietian** [comment]
Thanks @jeanlf . Yeah I forgot to reinstall the new binary. With your change above the structure seems to be right now. And the `@start` property also seems to be in the same scale as the original (which can be inferred given it's the first byte of the box header in the file, and the structure remains after processing).

Thanks a lot for your quick help!
