### ISSUE TITLE
#2122 - At live mode "muxtype=ts" output file will not remove.  - NOT FIXED

### ISSUE THREAD

**Issue by fingul** [gpac/gpac#2123]
Hi!

At latest version 1.1.0-DEV-rev1769-g1d936f89d-master. 

I tested, but not fixed.

When running #2122 - case-2, number of files grown infinitely.

#2122 - At live mode "muxtype=ts" output file will not remove.  - NOT FIXED

Thanks.

-----------------------

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [*] I looked for a similar issue and couldn't find any.
- [*] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [*] I give enough information for contributors to reproduce my issue

**Comment by jeanlf** [comment]
please don't create new issue for this, post comment in existing issue
