### ISSUE TITLE
OpenXR Implementation for VR Mode (360Videos)

### ISSUE THREAD

**Issue by Deltajom** [gpac/gpac#2126]
Hello, this is less of an issue and more of a request for some information/assistance. I'd like to see if I can get the OpenXR loader working inside of GPAC's video player to allow a majority of the current VR runtimes (SteamVR, Monado, etc.) to work with GPAC so that non-mobile headsets can be used to watch 360 videos as well. There is also some coming support for standalone headsets such as the Quest 2, so it could also be a possible solution for this issue #1937. 

What I've done so far - 
Explored OpenXR Loader Structure
Explored GPAC source looking for render/frame update sections
Realized that I need to get the viewport frame(s) / frame buffer(s) instead of the full frame buffer(s)

My questions - 
1. Where are the buffers and frame update functions for the viewport in VR mode? (I've been looking in camera.c, visual_manager.c, visual_manager_3d.c, but haven't found anything specifically viewport, might just be missing them)
2. Is there an implementation somewhere for Z-axis rotation of the camera in VR mode? (I knew there is one for X and Y because the current 360 player exists, but tilting the viewport was something I wasn't able to find in camera.c or navigate.c)
3. I remember there was a section on viewport resizing, but is there anything dedicated to FOV based viewport size or is it resolution based only?

An answer to these three questions would be a great help thank you for your time!
 

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by hpwang22** [comment]
> 

Hello, does osmo4 player work on quest 2?

**Comment by Deltajom** [comment]
The best I can make of it is you might try side-loading onto quest 2 with a .apk file. There are some guides out there for creating one from an android app, but this may still not work. I'm still trying to work through the OpenXR stuff for now, as it should allow for most of the PC VR headsets to run MP4Client at the least. Though as I mentioned the Quest 2 is gaining better and better OpenXR support, but it's not 100% there yet for a development side. 

Don't have a quest 2 to try with, but if I find something I'll post it here.

**Comment by Gabrielgca** [comment]
Hello @Deltajom ,

Did you have progress on this issue? I'm trying to make GPAC run on HMDs such as Oculus Quest 2. However, If there was a way to used only on mobile to watch 360 videos it's a good start!

**Comment by Deltajom** [comment]
> Hello @Deltajom ,
> 
> Did you have progress on this issue? I'm trying to make GPAC run on HMDs such as Oculus Quest 2. However, If there was a way to used only on mobile to watch 360 videos it's a good start!

Haven't made any meaningful progress on the OpenXR side, ended up reading a lot about rendering libraries OpenGL, DX11, etc. and found that implementation of even one would be a multi-month job for me as I've not had experience with such low-level rendering libraries.

Short term solution for NON-TILED videos is with javascript in aframe with webxr and Dash.js. 

Is modifying gpac's player still possible? Yes, but for me I needed something a bit faster to put together. I still am keeping modifying the player as an idea in my head and have been working on it every once in a while, but don't have anything working yet.

**Comment by jeanlf** [comment]
@Deltajom  sorry for the late follow-up. 

> Where are the buffers and frame update functions for the viewport in VR mode? (I've been looking in camera.c, visual_manager.c, visual_manager_3d.c, but haven't found anything specifically viewport, might just be missing them)

Not sure what you mean here - the VR viewpoint is updated in navigate.c and only impacts the camera matrix. The rest of the rendering is independent from the navigation. The result is usually drawn on the main framebuffer, but can be rendered on FBOs if needed, using [-glfbo-txid](https://github.com/gpac/gpac/wiki/core_options#glfbo-txid). Note that currently we only support a single FBO as output, so stereo layout must be drawn side-by-side or top-bottom on that fbo...

> Is there an implementation somewhere for Z-axis rotation of the camera in VR mode? (I knew there is one for X and Y because the current 360 player exists, but tilting the viewport was something I wasn't able to find in camera.c or navigate.c)

yes, it's dealt through the GF_EVENT_SENSOR_ORIENTATION in navigate.c, where we handle yaw pitch and roll


> I remember there was a section on viewport resizing, but is there anything dedicated to FOV based viewport size or is it resolution based only?

Viewport resizing is only meant to deal with output resolution changes. There are a few places where we compute the FOV viewport to trigger downstream events, typically for DASH SRD, to lower the quality of hidden tiles, if that's what you are looking for.


 
We're not planning on supporting OpenXR or dedicated headsets in the near future, so I'm closing this, but do not hesitate to continue this discussion here.
