### ISSUE TITLE
How do I modify the value of PART-HOLD-BACK ?

### ISSUE THREAD

**Issue by GlassyYang** [gpac/gpac#2128]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I want to modify the value of `PART-HOLD-BACK` in tag `#EXT-X-SERVER-CONTROL` and I don't find any use message in documentation. is There a configuration so I can modify this value use `gpac`?

**Comment by GlassyYang** [comment]
I have modified manifest file by myself.

**Comment by jeanlf** [comment]
now in master (dasher:ll_part_hb option)
