### ISSUE TITLE
Incorrect/inconsistent results produced by `MP4Box -bt`

### ISSUE THREAD

**Issue by shao-hua-li** [gpac/gpac#2130]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Hi,

I built `gpac` twice with `gcc-11 -O0` and `gcc-11 -O3` separately. For the provided input, `MP4Box -bt` would produce different outputs/warnings. Reproduce as follows:
- Compile  `gpac` twice with `gcc-11 -O0` and `gcc-11 -O3` to obtain two versions MP4Box: `MP4Box-O0` and `MP4Box-O3`
- Run `MP4Box-O0 -bt $issue-2130 -std > out-O0.txt 2>&1` and `MP4Box-O3 -bt $issue-2130 -std > out-O3.txt 2>&1`
- Compare with `diff -y out-O0.txt out-O3.txt` and you'll see these two files differ (`out-O3.txt` shown on the right has two more lines than `out-O1.txt`) 
[issue-2130.tar.gz](https://github.com/gpac/gpac/files/8171226/issue-2130.tar.gz)

```
[33m[ISO file] dataReferenceIndex set to 0 in sample entry, o	[33m[ISO file] dataReferenceIndex set to 0 in sample entry, o
[isom/avcc] Missing REXT profile signaling, patching.	[isom/avcc] Missing REXT profile signaling, patching.
[iso file] Missing DataInformationBox			[iso file] Missing DataInformationBox
[iso file] Box "saiz" (start 1128) has 8 extra bytes	[iso file] Box "saiz" (start 1128) has 8 extra bytes
[iso file] Warning: trackID of MOOF/TRAF(2) is not the	[iso file] Warning: trackID of MOOF/TRAF(2) is not the
							      >	[iso file] saiz box without flags nor aux info type an
[iso file] senc box without tenc, assuming MS smooth+p	[iso file] senc box without tenc, assuming MS smooth+p
[isobmf] cannot parse senc, missing IV/crypto state	[isobmf] cannot parse senc, missing IV/crypto state
[iso file] Unknown top-level box type D2E498FF		[iso file] Unknown top-level box type D2E498FF
[iso file] Incomplete box D2E498FF - start 1965 size 1	[iso file] Incomplete box D2E498FF - start 1965 size 1
[iso file] Incomplete file while reading for dump - ab	[iso file] Incomplete file while reading for dump - ab
[ISO file] dataReferenceIndex set to 0 in sample entry	[ISO file] dataReferenceIndex set to 0 in sample entry
[isom/avcc] Missing REXT profile signaling, patching.	[isom/avcc] Missing REXT profile signaling, patching.
[iso file] Missing DataInformationBox			[iso file] Missing DataInformationBox
[iso file] Box "saiz" (start 1128) has 8 extra bytes	[iso file] Box "saiz" (start 1128) has 8 extra bytes
[iso file] Warning: trackID of MOOF/TRAF(2) is not the	[iso file] Warning: trackID of MOOF/TRAF(2) is not the
							      >	[iso file] saiz box without flags nor aux info type an
[iso file] senc box without tenc, assuming MS smooth+p	[iso file] senc box without tenc, assuming MS smooth+p
[isobmf] cannot parse senc, missing IV/crypto state	[isobmf] cannot parse senc, missing IV/crypto state
[iso file] Unknown top-level box type D2E498FF		[iso file] Unknown top-level box type D2E498FF
[iso file] Incomplete box D2E498FF - start 1965 size 1	[iso file] Incomplete box D2E498FF - start 1965 size 1
[iso file] Incomplete file while reading for dump - ab	[iso file] Incomplete file while reading for dump - ab
Scene loaded - dumping root scene				Scene loaded - dumping root scene
```

**Comment by aureliendavid** [comment]
nice catch

it came from an undefined behavior from an uninitialized variable (assumed to be 0 in case of error but wasn't explicitly set) 

(interestingly it's the higher optim level (-O3) which had the variable forced to 0 whereas -O0 had a random value from memory, but since it's undefined behavior I don't know that this is deterministic)

should be fixed now, thanks for the report, feel free to reopen the issue if the problem persists

**Comment by shao-hua-li** [comment]
Thanks for the analysis. Interestingly, I originally thought it was related to uninitialized variables, so I built gpac with clang's MemorySanitizer, which didn't complain on this input. I'm thinking this might be a false negative of the sanitizer.
