### ISSUE TITLE
a/v sync issue in mp4box converted fragment mp4 

### ISSUE THREAD

**Issue by fastfading** [gpac/gpac#2135]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ yes] I looked for a similar issue and couldn't find any.
- [yes ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [yes ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

we found an a/v sync issue in mp4box converted fragment mp4 
check below command
mp4box is from gpac https://github.com/gpac/gpac/wiki/MP4Box
mp4fragment is from bento4  https://www.bento4.com/

input: normal.mp4    
mp4fragment normal.mp4 mp4frag.mp4
output: mp4frag.mp4
mp4box -dash 20000 -profile onDemand -out output.mpd normal.mp4
output: output.mpd  normal_dashinit.mp4

 files are here .   https://mega.nz/file/PagnkAzJ#-OYNK78tw9XJsyAzh42Tv4FSPisN2pl6-X7tLKfxisw

normal.mp4 and mp4frag.mp4 can be played well in mac quicktime player Version 10.5 (1086.4.2)
output.mpd and normal_dashinit.mp4 can be played well in all browser player
However mp4box output normal_dashinit.mp4 could a trigger a a/v sync issue while seeking in quicktime player
try to seek to the middle position of the mp4,  you will found the count down a/v is not sync.
and normal_dashinit.mp4 has no audio for some time in latest version VLC player(Version 3.0.16 Vetinari (Intel 64bit) )

mp4frag.mp4  and normal_dashinit.mp4 are all fragment mp4 ,  although the format is a little different.
I guess there must be some timestamps wrong in the mp4 header , it caused this av sync issue

may be related to this issue,  I am not sure.
https://stackoverflow.com/questions/63262104/fragmented-mp4-not-playing-in-ffplay-quicktime-safari-but-in-vlc

**Comment by fastfading** [comment]
if you play normal_dashinit.mp4 in quicktime player from start to end ,  there is no av sync issue. 
however if you do seek in the progress bar,  it will trigger a/v sync issue.

**Comment by jeanlf** [comment]
The source file is broken, it indicates one AAC sample with duration 1504 and another with duration 992 (both in the middle of the stream).

I think this causes unpredictable behavior in QT and in VLC (plays/seeks fine in ffplay, gpac, firefox and chrome though).

Patching the source aac track with `MP4Box -add self#2:sampdur=1024/32000 normal.mp4` and then dashing plays fine in QT/VLC.

As far as I can tell there's no issue with the fragmentation on the GPAC side here and not much we can do, so I'm closing but feel free to add any further clarification.

**Comment by fastfading** [comment]
@jeanlf   Thank you very much.
will this cmd fix the normal.mp4  without consquence?  
MP4Box -add self#2:sampdur=1024/32000 normal.mp4  

will this change bring a time shift in audio ?

**Comment by fastfading** [comment]
Patching the source aac track with MP4Box -add self#2:sampdur=1024/32000 normal.mp4 and then dashing plays fine in QT/VLC.
------------------------------
after this command 
MP4Box -add self#2:sampdur=1024/32000 normal.mp4
then 
mp4box -dash 20000 -profile onDemand -out output.mpd normal.mp4
normal_dashinit.mp4  plays well in QT ，  
play well in vlc  sometimes，   somtimes  a/v still not sync.   
try to seek several times ,  you will find the unsync issue happen again.  
How to solve that ?

**Comment by fastfading** [comment]
by the way which tool are you using to  identify this

_The source file is broken, it indicates one AAC sample with duration 1504 and another with duration 992 (both in the middle of the stream)._

**Comment by jeanlf** [comment]
>by the way which tool are you using to identify this

any tool able to inspect ISOBMF files (mp4box, mp4box.js, ffprobe) will do. In this case, I just checked the box structure using `MP4Box -diso source`

**Comment by fastfading** [comment]
normal.mp4 plays well in both QT and VLC

after this command 
MP4Box -add self#2:sampdur=1024/32000 normal.mp4
then 
mp4box -dash 20000 -profile onDemand -out output.mpd normal.mp4
normal_dashinit.mp4  plays well in QT ，  
but  a/v still not sync in VLC when seeking

I try other mp4 download from youtube or other platform .  
then mp4box -dash 20000 -profile onDemand -out youtube.mpd youtube.mp4
youtube_dashinit.mp4 don't have this av sync issue.

I check the 2 mp4 with mp4box.js,  found they are all the same .  I don't know why. 

since normal.mp4 could play well in QT VLC, I guess there is no codec error. Looks like a container error
