### ISSUE TITLE
GPAC + kvazaar RTMP input works but UDP does not.

### ISSUE THREAD

**Issue by ionProjects** [gpac/gpac#2136]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
please give the details of your command lines...

**Comment by ionProjects** [comment]
Hello there, I'm using a GPAC version compiled with ffmpeg and libkvazaar to try and generate the MPD and segmets from a live feed. I can only make it work with a live feed generated from an android App, that uses the mobile camera to generate a RTMP server.  [Android App](https://play.google.com/store/apps/details?id=veg.mediacapture.sdk.test.server&hl=es&gl=US) 


**Software used.**
MSYS2 MinGW x64
Gpac - version 2.1-DEV-rev3-gfc9158820-master **with local ffmpeg** 
ffmpeg - configuration: --enable-shared --disable-static --enable-pic --enable-libx264 --enable-gpl --enable-opengl --enable-libkvazaar

**scenario that works.** 
RTMP generated with Android App.

`gpac -i rtmp://54.173.34.172:1937/publish_demo:gpac:FID=S -+kvazaar-params=tiles=3x3,slices=tiles,mv-constraint=frametilemargin,rc-algorithm=lambda enc:SID=S:c=libkvazaar:b=1m:fintra=1:rc @ tilesplit:FID=1 -o live.mpd:SID=1:dmode=dynamic`

This generates the files, that I'm able to play with MP4Client during the process.

**scenario that isn't working.** 

Using ffmpeg and webcam

`ffmpeg -f dshow -i video="USB2.0 HD UVC WebCam" -c:v libx264 -b:v 100k -f mpegts udp://LOCALIP:1234`

And using this [wiki](https://github.com/gpac/gpac/wiki/sockets) to test it.

`gpac -i udp://127.0.0.1:1234/:ext=avc -o test.mp4`

Result: 

`$ gpac -i udp://192.168.1.136:1234/:ext=avc -o test.mp4
Filters not connected:
fout (dst=test.mp4) (idx=2)
`

**Comment by ionProjects** [comment]
> please give the details of your command lines...

Sorry, i was writing the post.

**Comment by jeanlf** [comment]
> gpac -i udp://127.0.0.1:1234/:ext=avc -o test.mp4

If your input is TS why force raw annexB AVC ? This should be:
`gpac -i udp://127.0.0.1:1234/:ext=ts -o test.mp4`

Also as said in the [filter help](https://wiki.gpac.io/sockin), probing of MPEG-2 TS over UDP/RTP is enabled by default, so simply use:
`gpac -i udp://127.0.0.1:1234/ -o test.mp4`

**Comment by jeanlf** [comment]
is [inspect](https://wiki.gpac.io/inspect) working on the source ?

`gpac -i udp://localhost:1234/ inspect:deep`

You can try turning on network logs (used `debug` instead of `info` for complete log):

`gpac -i udp://localhost:1234/ inspect:deep -logs=network@info` 

On my OSX machine, using as server:
`ffmpeg -f avfoundation -r 30 -i "0" -c:v libx264 -b:v 100k -f mpegts udp://127.0.0.1:1234/`

both `ffplay udp://127.0.0.1:1234/ ` and `gpac -i  udp://127.0.0.1:1234/ vout` (or recording to file) work.

**Comment by ionProjects** [comment]
There are the 3 different results I got.

`gpac -i udp://localhost:1234/ inspect:deep
[socket] error reading: Unknown error
PID 256 video service 1 timescale 90000 codec AVC|H264
`
`gpac -i udp://localhost:1234/ inspect:deep -logs=network@info
[socket] socket bound to 00000000 - port 1234 - remote peer: localhost:1234
[Sock_IPV4] Solving localhost address
[Sock_IPV4] Host localhost found
[Sock_IPV4] Connecting to localhost:1234
[Sock_IPV4] Connected to localhost:1234
[SockIn] opening udp://localhost:1234/
Filters not connected:
inspect (deep) (idx=2)
`
`gpac -i udp://localhost:1234/ vout
[VideoOut] No output modules found, cannot load video output
Failed to load filter "vout": I/O Error
[socket] error reading: Unknown error
No filter chain found for PID  in filter sockin to any loaded filters - NOT CONNECTED
`

**Comment by jeanlf** [comment]
can you try with '127.0.0.1' instead of localhost ?

**Comment by ionProjects** [comment]
The only cmd that changed is this one. **Also changed the ffpemg cmd to 127.0.0.1**

`gpac -i udp://127.0.0.1:1234/ vout
[VideoOut] No output modules found, cannot load video output
Failed to load filter "vout": I/O Error
`

ffplay works proprely.

**Comment by jeanlf** [comment]
we had a bug with mingw build and udp, should now be fixed - can you cross-check ?

**Comment by ionProjects** [comment]
Hello,

First of all, thanks for your fast response.


This works just fine now, there are no errors at all.
`gpac -i udp://127.0.0.1:1234/ -o out.mp4`

But when I try with my original command this happens.

`gpac -i udp://127.0.0.1:1234/:gpac:FID=S -+kvazaar-params=tiles=3x3,slices=tiles,mv-constraint=frametilemargin,rc-algorithm=lambda enc:SID=S:c=libkvazaar:b=1m:fintra=1:rc @ tilesplit:FID=1 -o resources/dashout/live.mpd:SID=1:dmode=dynamic
Failed to load a video output for OpenGL context support !
[NVDec] failed to request an OpenGL provider (error I/O Error), will not use OpenGL output
[FFEnc] encoder reconfiguration failed, aborting stream
[FFEnc] encoder reconfiguration failed, aborting stream
`

**Comment by jeanlf** [comment]
can you try blacklisting the nvdec decoder (`-blacklist=nvdec`) ?

**Comment by ionProjects** [comment]
This is the new result.

`gpac -blacklist=nvdec -i udp://127.0.0.1:1234/:gpac:FID=S:FPS=30 -+kvazaar-params=tiles=3x3,slices=tiles,mv-constraint=frametilemargin,rc-algorithm=lambda enc:SID=S:c=libkvazaar:b=1m:fintra=1:rc @ tilesplit:FID=1 -o resources/dashout/live.mpd:SID=1:dmode=dynamic    [FFEnc] Unknown frame rate for PID P1V2, will use 25 fps - use `:#FPS=VAL` on input to force frame rate
[libkvazaar] dimensions not set
[FFEnc] PID P1V2 failed to open codec context: Invalid argument
Failed to connect filter ffdec:h264 PID P1V2 to filter ffenc:libkvazaar: Bad Parameter
`

Not sure if I used  FPS=VAL correctly. It hangs there until I manually stop the stream, then it prints this.

`session last connect error Bad Parameter
Argument "-+kvazaar-params" was set but not used by any filter
Unknown argument ":dmode" set but not used by any filter - possible matches
- dv_mode in filters rfnalu
Filters not connected:
tilesplit (FID=1) (idx=3)
fout (dst=resources/dashout/live.mpd:SID=1:dmode=dynamic) (idx=4)
Segmentation fault
`

**Comment by jeanlf** [comment]
The correct syntax to override the FPS prop is 
`-i udp://127.0.0.1:1234/:gpac:FID=S:#FPS=30`

There was a bug in ffenc initialization for this particular setup , should now be fixed. Can you cross-check ?

**Comment by ionProjects** [comment]
This cmd does not crash fail now, and the files are generated, but I got some warnings. 

**Warnings**
`[Dasher] AS-1 Rep 1 segment 23 done TOO LATE by 2384 ms
[Dasher] AS-1 Rep 2 segment 23 done TOO LATE by 2384 ms
[Dasher] AS-1 Rep 3 segment 23 done TOO LATE by 2384 ms
[Dasher] AS-1 Rep 4 segment 23 done TOO LATE by 2384 ms
[Dasher] AS-1 Rep 5 segment 23 done TOO LATE by 2384 ms
[Dasher] AS-1 Rep 6 segment 23 done TOO LATE by 2384 ms
[Dasher] AS-1 Rep 7 segment 23 done TOO LATE by 2384 ms
[Dasher] AS-1 Rep 8 segment 23 done TOO LATE by 2384 ms
[Dasher] AS-1 Rep 9 segment 23 done TOO LATE by 2384 ms
[Dasher] AS-1 Rep 10 segment 23 done TOO LATE by 2384 ms
[swscaler] deprecated pixel format used, make sure you did set range correctly
[swscaler] deprecated pixel format used, make sure you did set range correctly
[swscaler] deprecated pixel format used, make sure you did set range correctly
[swscaler] deprecated pixel format used, make sure you did set range correctly
[swscaler] deprecated pixel format used, make sure you did set range correctly
[swscaler] deprecated pixel format used, make sure you did set range correctly
[Win32] temporary file "C:\msys64\tmp\gpac_18200_00007d8f_21" won't be deleted - contact the GPAC team
`

**MP4Client Playback**
`[DASH] Error in downloading new segment ./_dash_track256_87.m4s: Requested URL is not valid or cannot be found - waited 1569 ms but segment still not available, checking next one ...
[DASH] Error in downloading new segment ./_dash_track256_87.m4s: Requested URL is not valid or cannot be found
[DASH] File ./_dash_track256_88.m4s not found on disk
[DASH] Error in downloading new segment ./_dash_track256_88.m4s: Requested URL is not valid or cannot be found
[DASH] File ./_dash_track256_89.m4s not found on disk
[DASH] Error in downloading new segment ./_dash_track256_89.m4s: Requested URL is not valid or cannot be found
[DASH] File ./_dash_track256_90.m4s not found on disk
[DASH] Error in downloading new segment ./_dash_track256_90.m4s: Requested URL is not valid or cannot be found
[DASH] File ./_dash_track256_91.m4s not found on disk
[DASH] Error in downloading new segment ./_dash_track256_91.m4s: Requested URL is not valid or cannot be found
[DASH] File ./_dash_track256_92.m4s not found on disk
[DASH] Error in downloading new segment ./_dash_track256_92.m4s: Requested URL is not valid or cannot be found
[DASH] File ./_dash_track256_93.m4s not found on disk
[DASH] Error in downloading new segment ./_dash_track256_93.m4s: Requested URL is not valid or cannot be found
[DASH] File ./_dash_track256_94.m4s not found on disk
[DASH] Error in downloading new segment ./_dash_track256_94.m4s: Requested URL is not valid or cannot be found
[DASH] File ./_dash_track256_95.m4s not found on disk
[DASH] Error in downloading new segment ./_dash_track256_95.m4s: Requested URL is not valid or cannot be found
[DASH] File ./_dash_track256_96.m4s not found on disk
[DASH] Too many consecutive segments not found (broken source, sync or signal lost...) - entering end of stream detection mode`

**Comment by ionProjects** [comment]
I recorded a video firts, then used that video as source for the UDP stream and it worked flawlessly. I'll try to stream a valid UDP stream from a live video feed encoded fast enough. I think this is fixed now.

Thanks!

**Comment by jeanlf** [comment]
Great, thanks for the cross-check!

**Comment by a23232390** [comment]
@ionProjects 
Excuse me,  recorded a video first like this one(ffmpeg -y -i input.mp4 -c copy -t 4  output.mp4)
or Is there any other can tell me
