### ISSUE TITLE
how to use osmo4 to play a video?

### ISSUE THREAD

**Issue by whp22** [gpac/gpac#2142]
I have installed the gpac with exe file from https://gpac.wp.imt.fr/downloads/, and i can find osmo4 player in my computer. now I want play the demo in http://download.tsi.telecom-paristech.fr/gpac/SRD/srd_hevc/multi_rate_p60/ using osmo4. But I can not open or add the file with osmo4 gui. Any idea? thanks a lot.

**Comment by rbouqueau** [comment]
I tried with the latest installer in a VM. When I press the "Windows" keyboard key and type 'osmo' I can see Osmo4.

When I open it, it closes after a few seconds of displaying a grey window. When opening with a console I see ```[Compositor] OpenGL shaders not supported```.

**Comment by aureliendavid** [comment]
> Side note from maintainer:
> 
> I tried with the latest installer in a VM. When I press the "Windows" keyboard key and type 'osmo' I can see Osmo4.
> 
> When I open it, it closes after a few seconds of displaying a grey window. When opening with a console I see `[Compositor] OpenGL shaders not supported`.
> 
> That prevents me from helping here.

hm I'm not seeing this on a fresh win10 x64 machine

if you've had a previous version of gpac installed before you may have to delete the %appdata%\GPAC dir?

**Comment by aureliendavid** [comment]
> I have installed the gpac with exe file from https://gpac.wp.imt.fr/downloads/, and i can find osmo4 player in my computer. now I want play the demo in http://download.tsi.telecom-paristech.fr/gpac/SRD/srd_hevc/multi_rate_p60/ using osmo4. But I can not open or add the file with osmo4 gui. Any idea? thanks a lot.

to play a file with the gui you can click the second button (open) then either select a local file, or click the little planet icon on top to enter a url (you can launch osmo4 with the "osmo4 (with console) shortcut to see more debug messages if something goes wrong)

you can also play a file from the commande line (win+r > `cmd`) and type `mp4client -gui [path or url of the file]`

(mp4client is the newer name of the osmo4 player)

**Comment by whp22** [comment]
> > I have installed the gpac with exe file from https://gpac.wp.imt.fr/downloads/, and i can find osmo4 player in my computer. now I want play the demo in http://download.tsi.telecom-paristech.fr/gpac/SRD/srd_hevc/multi_rate_p60/ using osmo4. But I can not open or add the file with osmo4 gui. Any idea? thanks a lot.
> 
> to play a file with the gui you can click the second button (open) then either select a local file, or click the little planet icon on top to enter a url (you can launch osmo4 with the "osmo4 (with console) shortcut to see more debug messages if something goes wrong)
> 
> you can also play a file from the commande line (win+r > `cmd`) and type `mp4client -gui [path or url of the file]`
> 
> (mp4client is the newer name of the osmo4 player)

I have tried gui and command line, and both did not work. When I click the open button of  gui, nothing is show

**Comment by whp22** [comment]
I just found I got this error when i click open button
![Screenshot 2022-03-16 130127](https://user-images.githubusercontent.com/79181675/158646507-7584e847-5121-48d0-aa12-13549a00bcc1.png)
n

**Comment by whp22** [comment]
I reinstall the exe with default path and fixed the error
