### ISSUE TITLE
bad mpd generated by MP4Box

### ISSUE THREAD

**Issue by burstmarcom** [gpac/gpac#215]
Hi We used MP4Box to genreate mpd and segment-ed dash files
Command used was:
MP4Box -dash 2000 -rap -frag-rap -profile onDemand -out /eph/974792159628123000/a/613992915/v/752033447846770000_100/dash.mpd /eph/974792159628123000/a/613992915/v/752033447846770000_100/xq.mp4#video /eph/974792159628123000/a/613992915/v/752033447846770000_100/xq.mp4#audio /eph/974792159628123000/a/613992915/v/752033447846770000_100/hq.mp4#video /eph/974792159628123000/a/613992915/v/752033447846770000_100/mq.mp4#video /eph/974792159628123000/a/613992915/v/752033447846770000_100/lq.mp4#video

When we play the mpd in the GPAC sample player (and even in our own own implementation in flowplayer 6.0.3)

It results in buffer stalling between 7/ 13 seconds (it varies).

The mpd url is:- https://s3.amazonaws.com/dev.media.burst.it/a/613992915/v/752033447846770000_100/dash.mpd

Tried it in this sample player:-  http://dashif.org/reference/players/javascript/1.4.0/samples/dash-if-reference-player/index.html

Also tried it in our own player here-
https://dev.burst.com/test/videoplayback/inbuilt.html

In both case we  it results in same results.

Note to see the issue use chrome and if the entire video plays perhaps reload browser and retry.

Can someone tell me what is wrong? From the flowplayer developers they said the mpd is incorrect.
However we are using MP4Box so how can it be incorrect unless there is a bug.

MP4Box is fairly recent and compiled from github
See below-
MP4Box - GPAC version 0.5.2-DEV-rev563-ge3b29f0-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: 
Features: GPAC_64_BITS GPAC_HAS_SSL GPAC_HAS_JPEG GPAC_HAS_PNG

**Comment by burstmarcom** [comment]
Note per this chrome bug (https://code.google.com/p/chromium/issues/detail?id=511128) 
I also got the latest canary build 47. and the same issue occurs in that as well on the GPAC playe and our own player.

**Comment by burstmarcom** [comment]
also reported this to chrome
https://code.google.com/p/chromium/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=&id=511128

**Comment by rbouqueau** [comment]
In Chrome 44, it seems to play at least the first 30 seconds. MP4Client does complain. Could you share the input MP4s with us so that we investigate?

**Comment by burstmarcom** [comment]
Hi -
You can download 4 input files ref above from 
	
https://s3.amazonaws.com/dev.media.burst.it/a/613992915/v/752033447846770000_100/xq.mp4
	
https://s3.amazonaws.com/dev.media.burst.it/a/613992915/v/752033447846770000_100/hq.mp4
	
https://s3.amazonaws.com/dev.media.burst.it/a/613992915/v/752033447846770000_100/mq.mp4
	
https://s3.amazonaws.com/dev.media.burst.it/a/613992915/v/752033447846770000_100/lq.mp4


They were created from ffmpeg

**Comment by rbouqueau** [comment]
Your content is not encoded appropriately because the RAPs are not aligned:
```
$ MP4Box -std -diso xq.mp4 2>&1 | grep SyncSampleEntry
<SyncSampleEntry sampleNumber="1"/>
<SyncSampleEntry sampleNumber="60"/>
<SyncSampleEntry sampleNumber="119"/>
...

$ MP4Box -std -diso mq.mp4 2>&1 | grep SyncSampleEntry
<SyncSampleEntry sampleNumber="1"/>
<SyncSampleEntry sampleNumber="25"/>
<SyncSampleEntry sampleNumber="49"/>
...

$ MP4Box -std -diso hq.mp4 2>&1 | grep SyncSampleEntry
<SyncSampleEntry sampleNumber="1"/>
<SyncSampleEntry sampleNumber="25"/>
<SyncSampleEntry sampleNumber="49"/>
...

$ MP4Box -std -diso lq.mp4 2>&1 | grep SyncSampleEntry
<SyncSampleEntry sampleNumber="1"/>
<SyncSampleEntry sampleNumber="16"/>
<SyncSampleEntry sampleNumber="31"/>
...
```

You need to re-encode it following this tutorial: http://blog.streamroot.io/encode-multi-bitrate-videos-mpeg-dash-mse-based-media-players/

We have a draft blog article to help people check their RAP alignments.

**Comment by burstmarcom** [comment]
Hi Based on your comment we changed our inputs so the RAP alignment are correct on all 4 inputs. (see below) However the exact same issue still is occurring.
Using the proper input files we again tried MP4Box command and tried to play in chrome latest version (as stated above) and same exact results ("It results in buffer stalling between 7/ 13 seconds (it varies).
").

Please help.

MP4Box -dash 2000 -rap -frag-rap -profile onDemand -out /eph/307228274177760000/a/522809591/v/250542378175534_100/dash.mpd /eph/307228274177760000/a/522809591/v/250542378175534_100/xq.mp4#video /eph/307228274177760000/a/522809591/v/250542378175534_100/xq.mp4#audio /eph/307228274177760000/a/522809591/v/250542378175534_100/hq.mp4#video /eph/307228274177760000/a/522809591/v/250542378175534_100/mq.mp4#video /eph/307228274177760000/a/522809591/v/250542378175534_100/lq.mp4#video




The mpd url is:- https://s3.amazonaws.com/dev.media.burst.it/a/522809591/v/250542378175534_100/dash.mpd



You can download 4 input files ref above from

https://s3.amazonaws.com/dev.media.burst.it/a/522809591/v/250542378175534_100/xq.mp4

https://s3.amazonaws.com/dev.media.burst.it/a/522809591/v/250542378175534_100/hq.mp4

https://s3.amazonaws.com/dev.media.burst.it/a/522809591/v/250542378175534_100/mq.mp4

https://s3.amazonaws.com/dev.media.burst.it/a/522809591/v/250542378175534_100/lq.mp4 



Also as you can see the RAP alignment is correct this time.

[root@ip-10-0-1-137 250542378175534_100]# MP4Box -std -diso hq.mp4 2>&1 | grep SyncSampleEntry
<SyncSampleEntry sampleNumber="1"/>
<SyncSampleEntry sampleNumber="25"/>
<SyncSampleEntry sampleNumber="49"/>
<SyncSampleEntry sampleNumber="73"/>
<SyncSampleEntry sampleNumber="97"/>
<SyncSampleEntry sampleNumber="121"/>
<SyncSampleEntry sampleNumber="145"/>
<SyncSampleEntry sampleNumber="169"/>
<SyncSampleEntry sampleNumber="193"/>
<SyncSampleEntry sampleNumber="217"/>
<SyncSampleEntry sampleNumber="241"/>
<SyncSampleEntry sampleNumber="265"/>
<SyncSampleEntry sampleNumber="289"/>
<SyncSampleEntry sampleNumber="313"/>
<SyncSampleEntry sampleNumber="337"/>
<SyncSampleEntry sampleNumber="361"/>
<SyncSampleEntry sampleNumber="385"/>
<SyncSampleEntry sampleNumber="409"/>
<SyncSampleEntry sampleNumber="433"/>
<SyncSampleEntry sampleNumber="457"/>
<SyncSampleEntry sampleNumber="481"/>
<SyncSampleEntry sampleNumber="505"/>
<SyncSampleEntry sampleNumber="529"/>
<SyncSampleEntry sampleNumber="553"/>
<SyncSampleEntry sampleNumber="577"/>
<SyncSampleEntry sampleNumber="601"/>
<SyncSampleEntry sampleNumber="625"/>
<SyncSampleEntry sampleNumber="649"/>
<SyncSampleEntry sampleNumber="673"/>
<SyncSampleEntry sampleNumber="697"/>
<SyncSampleEntry sampleNumber="721"/>
<SyncSampleEntry sampleNumber="745"/>
<SyncSampleEntry sampleNumber="769"/>
<SyncSampleEntry sampleNumber="793"/>
<SyncSampleEntry sampleNumber="817"/>
<SyncSampleEntry sampleNumber="841"/>
<SyncSampleEntry sampleNumber="865"/>
<SyncSampleEntry sampleNumber="889"/>
<SyncSampleEntry sampleNumber="913"/>
<SyncSampleEntry sampleNumber="937"/>
<SyncSampleEntry sampleNumber="961"/>
<SyncSampleEntry sampleNumber="985"/>
<SyncSampleEntry sampleNumber="1009"/>
<SyncSampleEntry sampleNumber="1033"/>
<SyncSampleEntry sampleNumber="1057"/>
<SyncSampleEntry sampleNumber="1081"/>
<SyncSampleEntry sampleNumber="1105"/>
<SyncSampleEntry sampleNumber="1129"/>
<SyncSampleEntry sampleNumber="1153"/>
<SyncSampleEntry sampleNumber="1177"/>
<SyncSampleEntry sampleNumber="1201"/>
<SyncSampleEntry sampleNumber="1225"/>
<SyncSampleEntry sampleNumber="1249"/>
<SyncSampleEntry sampleNumber="1273"/>
<SyncSampleEntry sampleNumber="1297"/>
<SyncSampleEntry sampleNumber="1321"/>
<SyncSampleEntry sampleNumber="1345"/>
<SyncSampleEntry sampleNumber="1369"/>
<SyncSampleEntry sampleNumber="1393"/>
<SyncSampleEntry sampleNumber="1417"/>
<SyncSampleEntry sampleNumber="1441"/>
<SyncSampleEntry sampleNumber="1465"/>
<SyncSampleEntry sampleNumber="1489"/>
<SyncSampleEntry sampleNumber="1513"/>
<SyncSampleEntry sampleNumber="1537"/>
<SyncSampleEntry sampleNumber="1561"/>
<SyncSampleEntry sampleNumber="1585"/>
<SyncSampleEntry sampleNumber="1609"/>
<SyncSampleEntry sampleNumber="1633"/>
<SyncSampleEntry sampleNumber="1657"/>
<SyncSampleEntry sampleNumber="1681"/>
<SyncSampleEntry sampleNumber="1705"/>
<SyncSampleEntry sampleNumber="1729"/>
<SyncSampleEntry sampleNumber="1753"/>
<SyncSampleEntry sampleNumber="1777"/>
<SyncSampleEntry sampleNumber="1801"/>
<SyncSampleEntry sampleNumber="1825"/>
<SyncSampleEntry sampleNumber="1849"/>
<SyncSampleEntry sampleNumber="1873"/>
<SyncSampleEntry sampleNumber="1897"/>
<SyncSampleEntry sampleNumber="1921"/>
<SyncSampleEntry sampleNumber="1945"/>
<SyncSampleEntry sampleNumber="1969"/>
<SyncSampleEntry sampleNumber="1993"/>
<SyncSampleEntry sampleNumber="2017"/>
[root@ip-10-0-1-137 250542378175534_100]# MP4Box -std -diso lq.mp4 2>&1 | grep SyncSampleEntry
<SyncSampleEntry sampleNumber="1"/>
<SyncSampleEntry sampleNumber="25"/>
<SyncSampleEntry sampleNumber="49"/>
<SyncSampleEntry sampleNumber="73"/>
<SyncSampleEntry sampleNumber="97"/>
<SyncSampleEntry sampleNumber="121"/>
<SyncSampleEntry sampleNumber="145"/>
<SyncSampleEntry sampleNumber="169"/>
<SyncSampleEntry sampleNumber="193"/>
<SyncSampleEntry sampleNumber="217"/>
<SyncSampleEntry sampleNumber="241"/>
<SyncSampleEntry sampleNumber="265"/>
<SyncSampleEntry sampleNumber="289"/>
<SyncSampleEntry sampleNumber="313"/>
<SyncSampleEntry sampleNumber="337"/>
<SyncSampleEntry sampleNumber="361"/>
<SyncSampleEntry sampleNumber="385"/>
<SyncSampleEntry sampleNumber="409"/>
<SyncSampleEntry sampleNumber="433"/>
<SyncSampleEntry sampleNumber="457"/>
<SyncSampleEntry sampleNumber="481"/>
<SyncSampleEntry sampleNumber="505"/>
<SyncSampleEntry sampleNumber="529"/>
<SyncSampleEntry sampleNumber="553"/>
<SyncSampleEntry sampleNumber="577"/>
<SyncSampleEntry sampleNumber="601"/>
<SyncSampleEntry sampleNumber="625"/>
<SyncSampleEntry sampleNumber="649"/>
<SyncSampleEntry sampleNumber="673"/>
<SyncSampleEntry sampleNumber="697"/>
<SyncSampleEntry sampleNumber="721"/>
<SyncSampleEntry sampleNumber="745"/>
<SyncSampleEntry sampleNumber="769"/>
<SyncSampleEntry sampleNumber="793"/>
<SyncSampleEntry sampleNumber="817"/>
<SyncSampleEntry sampleNumber="841"/>
<SyncSampleEntry sampleNumber="865"/>
<SyncSampleEntry sampleNumber="889"/>
<SyncSampleEntry sampleNumber="913"/>
<SyncSampleEntry sampleNumber="937"/>
<SyncSampleEntry sampleNumber="961"/>
<SyncSampleEntry sampleNumber="985"/>
<SyncSampleEntry sampleNumber="1009"/>
<SyncSampleEntry sampleNumber="1033"/>
<SyncSampleEntry sampleNumber="1057"/>
<SyncSampleEntry sampleNumber="1081"/>
<SyncSampleEntry sampleNumber="1105"/>
<SyncSampleEntry sampleNumber="1129"/>
<SyncSampleEntry sampleNumber="1153"/>
<SyncSampleEntry sampleNumber="1177"/>
<SyncSampleEntry sampleNumber="1201"/>
<SyncSampleEntry sampleNumber="1225"/>
<SyncSampleEntry sampleNumber="1249"/>
<SyncSampleEntry sampleNumber="1273"/>
<SyncSampleEntry sampleNumber="1297"/>
<SyncSampleEntry sampleNumber="1321"/>
<SyncSampleEntry sampleNumber="1345"/>
<SyncSampleEntry sampleNumber="1369"/>
<SyncSampleEntry sampleNumber="1393"/>
<SyncSampleEntry sampleNumber="1417"/>
<SyncSampleEntry sampleNumber="1441"/>
<SyncSampleEntry sampleNumber="1465"/>
<SyncSampleEntry sampleNumber="1489"/>
<SyncSampleEntry sampleNumber="1513"/>
<SyncSampleEntry sampleNumber="1537"/>
<SyncSampleEntry sampleNumber="1561"/>
<SyncSampleEntry sampleNumber="1585"/>
<SyncSampleEntry sampleNumber="1609"/>
<SyncSampleEntry sampleNumber="1633"/>
<SyncSampleEntry sampleNumber="1657"/>
<SyncSampleEntry sampleNumber="1681"/>
<SyncSampleEntry sampleNumber="1705"/>
<SyncSampleEntry sampleNumber="1729"/>
<SyncSampleEntry sampleNumber="1753"/>
<SyncSampleEntry sampleNumber="1777"/>
<SyncSampleEntry sampleNumber="1801"/>
<SyncSampleEntry sampleNumber="1825"/>
<SyncSampleEntry sampleNumber="1849"/>
<SyncSampleEntry sampleNumber="1873"/>
<SyncSampleEntry sampleNumber="1897"/>
<SyncSampleEntry sampleNumber="1921"/>
<SyncSampleEntry sampleNumber="1945"/>
<SyncSampleEntry sampleNumber="1969"/>
<SyncSampleEntry sampleNumber="1993"/>
<SyncSampleEntry sampleNumber="2017"/>
[root@ip-10-0-1-137 250542378175534_100]# MP4Box -std -diso hq.mp4 2>&1 | grep SyncSampleEntry
<SyncSampleEntry sampleNumber="1"/>
<SyncSampleEntry sampleNumber="25"/>
<SyncSampleEntry sampleNumber="49"/>
<SyncSampleEntry sampleNumber="73"/>
<SyncSampleEntry sampleNumber="97"/>
<SyncSampleEntry sampleNumber="121"/>
<SyncSampleEntry sampleNumber="145"/>
<SyncSampleEntry sampleNumber="169"/>
<SyncSampleEntry sampleNumber="193"/>
<SyncSampleEntry sampleNumber="217"/>
<SyncSampleEntry sampleNumber="241"/>
<SyncSampleEntry sampleNumber="265"/>
<SyncSampleEntry sampleNumber="289"/>
<SyncSampleEntry sampleNumber="313"/>
<SyncSampleEntry sampleNumber="337"/>
<SyncSampleEntry sampleNumber="361"/>
<SyncSampleEntry sampleNumber="385"/>
<SyncSampleEntry sampleNumber="409"/>
<SyncSampleEntry sampleNumber="433"/>
<SyncSampleEntry sampleNumber="457"/>
<SyncSampleEntry sampleNumber="481"/>
<SyncSampleEntry sampleNumber="505"/>
<SyncSampleEntry sampleNumber="529"/>
<SyncSampleEntry sampleNumber="553"/>
<SyncSampleEntry sampleNumber="577"/>
<SyncSampleEntry sampleNumber="601"/>
<SyncSampleEntry sampleNumber="625"/>
<SyncSampleEntry sampleNumber="649"/>
<SyncSampleEntry sampleNumber="673"/>
<SyncSampleEntry sampleNumber="697"/>
<SyncSampleEntry sampleNumber="721"/>
<SyncSampleEntry sampleNumber="745"/>
<SyncSampleEntry sampleNumber="769"/>
<SyncSampleEntry sampleNumber="793"/>
<SyncSampleEntry sampleNumber="817"/>
<SyncSampleEntry sampleNumber="841"/>
<SyncSampleEntry sampleNumber="865"/>
<SyncSampleEntry sampleNumber="889"/>
<SyncSampleEntry sampleNumber="913"/>
<SyncSampleEntry sampleNumber="937"/>
<SyncSampleEntry sampleNumber="961"/>
<SyncSampleEntry sampleNumber="985"/>
<SyncSampleEntry sampleNumber="1009"/>
<SyncSampleEntry sampleNumber="1033"/>
<SyncSampleEntry sampleNumber="1057"/>
<SyncSampleEntry sampleNumber="1081"/>
<SyncSampleEntry sampleNumber="1105"/>
<SyncSampleEntry sampleNumber="1129"/>
<SyncSampleEntry sampleNumber="1153"/>
<SyncSampleEntry sampleNumber="1177"/>
<SyncSampleEntry sampleNumber="1201"/>
<SyncSampleEntry sampleNumber="1225"/>
<SyncSampleEntry sampleNumber="1249"/>
<SyncSampleEntry sampleNumber="1273"/>
<SyncSampleEntry sampleNumber="1297"/>
<SyncSampleEntry sampleNumber="1321"/>
<SyncSampleEntry sampleNumber="1345"/>
<SyncSampleEntry sampleNumber="1369"/>
<SyncSampleEntry sampleNumber="1393"/>
<SyncSampleEntry sampleNumber="1417"/>
<SyncSampleEntry sampleNumber="1441"/>
<SyncSampleEntry sampleNumber="1465"/>
<SyncSampleEntry sampleNumber="1489"/>
<SyncSampleEntry sampleNumber="1513"/>
<SyncSampleEntry sampleNumber="1537"/>
<SyncSampleEntry sampleNumber="1561"/>
<SyncSampleEntry sampleNumber="1585"/>
<SyncSampleEntry sampleNumber="1609"/>
<SyncSampleEntry sampleNumber="1633"/>
<SyncSampleEntry sampleNumber="1657"/>
<SyncSampleEntry sampleNumber="1681"/>
<SyncSampleEntry sampleNumber="1705"/>
<SyncSampleEntry sampleNumber="1729"/>
<SyncSampleEntry sampleNumber="1753"/>
<SyncSampleEntry sampleNumber="1777"/>
<SyncSampleEntry sampleNumber="1801"/>
<SyncSampleEntry sampleNumber="1825"/>
<SyncSampleEntry sampleNumber="1849"/>
<SyncSampleEntry sampleNumber="1873"/>
<SyncSampleEntry sampleNumber="1897"/>
<SyncSampleEntry sampleNumber="1921"/>
<SyncSampleEntry sampleNumber="1945"/>
<SyncSampleEntry sampleNumber="1969"/>
<SyncSampleEntry sampleNumber="1993"/>
<SyncSampleEntry sampleNumber="2017"/>

**Comment by rbouqueau** [comment]
Yes but no ;)

Please re-encode your content with the following command-line option to force the RAPs each second (or two seconds if that's acceptable for you). You are currently asking for 2s segments and RAP-alignment while your RAPs are not on segment boundaries:
```-x264opts "keyint=$FRAMERATE:min-keyint=$FRAMERATE:no-scenecut"```

I am going to ask the tutorial people to fix their article since it is not the first time it generates some wrong content.

**Comment by burstmarcom** [comment]
initial tests seems to show it is working.  Thanks. We will test more.
fyi this is the snippet of my ffmpeg command.
-vcodec libx264 -pix_fmt yuv420p -vprofile baseline -preset veryfast -crf 22 -r 24 -g 24 -x264opts 'keyint=24:min-keyint=24:no-scenecut' -s 320x180 -acodec libfdk_aac -ab 40000 -ar 48000 /eph/141669720876962000/a/522809591/v/24951461372548_100/lq.mp4 -map '[vo3]' -map '[ao3]' -map '[ao4]' -vcodec libx264 -pix_fmt yuv420p -vprofile baseline -preset veryfast -crf 22 -r 24 -g 24 -f hls -hls_time 5 -hls_list_size 0 -hls_flags single_file -s 320x180 -acodec libfdk_aac -
.....

-HR

**Comment by rbouqueau** [comment]
Thanks for sharing. I close the issue, re-open if needed.

**Comment by burstmarcom** [comment]
Hey-
This needs to be reopned. The same issue is still occuring :(
Our guess is something maybe wrong with the xq.mp4 input but unsure
After all changes etc the inputs and outputs are below-

The mpd url is:- https://s3.amazonaws.com/dev.media.burst.it/a/522809591/v/24951461372548_100/dash.mpd

You can download 4 input files ref above from

https://s3.amazonaws.com/dev.media.burst.it/a/522809591/v/24951461372548_100/xq.mp4

https://s3.amazonaws.com/dev.media.burst.it/a/522809591/v/24951461372548_100/hq.mp4

https://s3.amazonaws.com/dev.media.burst.it/a/522809591/v/24951461372548_100/mq.mp4

https://s3.amazonaws.com/dev.media.burst.it/a/522809591/v/24951461372548_100/lq.mp4

**Comment by burstmarcom** [comment]
I feel like when the dash if player switches to use the xq_dashinit.mp4 is when this issue occurs.
Also point to note is that the XQ file is the only file which has a frame rate of  59.94. others are 24

**Comment by cconcolato** [comment]
Just tried out your latest version and it works without problem in MP4Client (from file) and with DASHIF 1.5.1 dev (from localhost). Can you clarify what your issue is? I'm not sure GPAC has an issue here. It may be an issue with the player you are using.

**Comment by burstmarcom** [comment]
Hey,
It is occurring for me on dashif, but not always. I have narrowed down it down to that when my bandwidth is real good and the time when the dash player switches to the highest quality (xq_dashinit.mp4) it happens where the buffer stops buffering and then everything stops.

**Comment by burstmarcom** [comment]
Also note that per the conformance test on dashif it shows error for the 4 representation..

For ex:
Error: Number of leafs 53 for track 1 for representation id "1" not equal to the number of leafs 43 for track 1 for representation id "3"
Error: Number of leafs 53 for track 1 for representation id "1" not equal to the number of leafs 43 for track 1 for representation id "4"
Error: Number of leafs 53 for track 1 for representation id "1" not equal to the number of leafs 43 for track 1 for representation id "5"

**Comment by jeanlf** [comment]
any idea what this message could mean ?

**Comment by burstmarcom** [comment]
no idea what the leaf means.
Anycase I think I took a shot in the dark. of the 4 representation for video I had in my mpd the highest quality had a different frame rate (59.94) but my gop and keyframe was set to 24 Changing it to 59 fo it seems to work. However more testing needed. Somehow the frame rate need to be a mutliple of the keyframe interval? Can oneone comment?

**Comment by jeanlf** [comment]
using 24 gop interval for 59.94 fps video makes switching point at different position than 24 gop for 24 fps (every second), which result in non-aligned swiching points. MP4Box assumes that I-frames are aligned across representation, and currently doesn't throw any message if that is not the case which indeed is a limitation ...

hope this helps 

PS: Is the DASH-IF validator now happy with your sequences ?

**Comment by burstmarcom** [comment]
No dash validator is never happy.
this time it showing diff errors for all my 4 rep. 
something along the lines

### SAP found with presentation time 10.003337 lesser than the declared SAP time 10.040934 (SAP_delta_time 0.000000), for sidx number 1 at reference count 5; first SAP shall be signaled as per Section 8.16.3.3 of ISO/IEC 14496-12 4th edition
