### ISSUE TITLE
Tagging of AAC files with MP4Box -itags fails for record_company (A9mak), publisher (A9pub) and a few other tags

### ISSUE THREAD

**Issue by otodoran-g** [gpac/gpac#2151]
I'm trying to use MP4Box to tag some AAC audio files (using the **-itags option**) and I'm getting an unexpected error when trying to add these two tags:
- record_company (A9mak)
- publisher (A9pub) 

MP4Box reports an error for them as:
`[iso file] Unknown box type A9mak`  respectively 
`[iso file] Unknown box type A9pub`

Dumping the tags with MP4Box -disox shows that the tags are added in the file, but with a **Container=unknown** and the value as **data:application/octet-string** (vs expected text).
Here's how the metadata read back **is shown**:
`<UnknownBox Size="35" Type="A9mak" Specification="unknown" Container="unknown"  value="data:application/octet-string,41396D616B2D544553540D" >`
`<data Size="27" Type="data" Version="0" Flags="1" Specification="apple" Container="ilst *" >`
`</data></UnknownBox>`

And here's what I **expected**:
`<record_company Size="10" Type="A9mak" Specification="apple" Container="ilst data"  value="A9mak-TEST" >`
`<data Size="26" Type="data" Version="0" Flags="1" Specification="apple" Container="ilst *" >`
`</data></record_company>`

The tags are set per MP4Box documentation: https://github.com/gpac/gpac/wiki/mp4box-other-opts#tagging-support 
Here's **how to repro** (files available at: https://www.dropbox.com/sh/tnmhfy5cx2apxju/AABVZV1ssiGWwA9_42p8H-Pta):
`copy /y Test-ORIG.m4a Test.m4a`
`mp4box.exe -itags mp4_metadata-full-set.txt  Test.m4a`
`mp4box.exe -disox Test.m4a -std > Test.m4a.xml`

The error is **not file dependent** (I've seen it reproduced on all files I tried) and it's **reproducible on latest GPAC** (MP4Box - GPAC version 2.1-DEV-rev74-gfa127347-master).
I am not able to find any other reports of such errors.

I have done a test with all the tagging elements that  are supported by MP4Box and discovered there are a few more that exhibit the same issue. Here's the full list of tags that fail:
- Unknown box type A9ard
- Unknown box type A9arg
- Unknown box type A9aut
- Unknown box type A9cak
- Unknown box type A9des
- Unknown box type A9dir
- Unknown box type A9equ
- Unknown box type A9lnt
- Unknown box type A9mak
- Unknown box type A9ope
- Unknown box type A9phg
- Unknown box type A9prd
- Unknown box type A9prf
- Unknown box type A9pub
- Unknown box type A9sne
- Unknown box type A9sol
- Unknown box type A9src
- Unknown box type A9thx
- Unknown box type A9url
- Unknown box type A9xpd

**Environment:**
* Windows64
* GPAC version - latest nightly build: version 2.1-DEV-rev74-gfa127347-master

**Comment by jeanlf** [comment]
Thanks for the detailed report and analysis, should now be fixed. I added your test tagfile to the testsuite.
