### ISSUE TITLE
Missing directory in HLS playlist generated from existing MPD

### ISSUE THREAD

**Issue by akkermansadriaan** [gpac/gpac#2152]
**Description**
I'm using GPAC to recreate DASH mpd's and HLS playlists. That's to simulate an event from a static asset, or creating a new playlist from 2 individual static assets.

```
gpac --forward=segb -i asset/manifest.mpd -i asset2/manifest.mpd -o merged.mpd:sigfrag:dual
```
```
gpac --forward=segb -i asset/manifest.mpd reframer:rt=on @ -o live.mpd:sigfrag:dynamic:tsb=-1:dual
```
**Expected**
The HLS playlist also contains the directory in the list of individual fragments.

**Actual**
In both cases the resulting HLS playlist for the chunks doesn't contain the `asset` or `asset2` prefix for the individual fragments. It does contain it for the init fragment however.

**Environment**
- macOS Monterey 12.3
- GPAC version 2.0-rev0-g418db414-master

**Comment by jeanlf** [comment]
Indeed this was not really working, thanks for the report. Should now be fixed with latest master, can you cross-check ?

**Comment by akkermansadriaan** [comment]
Checked and it's working! Thanks
