### ISSUE TITLE
Add Support to SCTE - 35

### ISSUE THREAD

**Issue by JuanMorenoS** [gpac/gpac#2158]
Hi,
Do you have in your roadmap add support to SCTE-35?
If not.... I can do it, but maybe I need help to know the project structure.

Thanks and awesome project!

**Comment by rbouqueau** [comment]
I have on my plate to extract the SCTE-35 markers from MPEG-TS and forward them to the DASH/HLS muxer.

Which use-cases do you want to cover?

**Comment by JuanMorenoS** [comment]
Exactly that one!

**Comment by JuanMorenoS** [comment]
Exactly that one! also I start to code that!

**Comment by JuanMorenoS** [comment]
But i have a lot of problems regarding the arch of the project

**Comment by jeanlf** [comment]
The first step is to demux the messages. You'll need to modify a bit the [M2TS demuxer code](https://github.com/gpac/gpac/blob/master/src/media_tools/mpegts.c) :

- add SCTE35 PID in [gf_m2ts_process_pmt](https://github.com/gpac/gpac/blob/master/src/media_tools/mpegts.c#L1132) 
- add a new section handler for these streams - check how this is done for e.g. [MPEG4 sections](https://github.com/gpac/gpac/blob/master/src/media_tools/mpegts.c#L1395)

Once you have a new SCTE35 message extracted, you will need to forward it to the user (here the m2ts demux filter) through a new event type passing the parsed info, as done for [TEMI](https://github.com/gpac/gpac/blob/master/src/media_tools/mpegts.c#L2419).

We can then map this info to a packet property

Not sure we need to parse the entire set of SCTE35 descriptors, maybe a subset will do.

It would be nice to have one or two _public_ reference TS with SCTE35 descriptors that we could include in the testsuite, would you have any ?

**Comment by JuanMorenoS** [comment]
I found this in a FFMPEG question but I don't know if is legal https://www.mediafire.com/folder/zv20csqeo1ixt/

**Comment by JuanMorenoS** [comment]
Hello @jeanlf @rbouqueau 
Thank you very much for your help! I am successfully reading the SCTRE-35 data but I have some problems/questions. 
1. I have created the event in the switch of `dmx_m2ts.c` very similar to [TEMI](https://github.com/gpac/gpac/blob/master/src/filters/dmx_m2ts.c#L890) but i am not sure if i have to save the data in the same place `gf_list_add(en->props, data);`or how to map the info in some packet like you said in the previous comment
2. how can I receive the data in the dasher filter? it's required a new config in that filter? and finally ... how can I put the labels in manifests? 

once again thank you for your help

**Comment by jeanlf** [comment]
> I have created the event in the switch of dmx_m2ts.c very similar to [TEMI](https://github.com/gpac/gpac/blob/master/src/filters/dmx_m2ts.c#L890) but i am not sure if i have to save the data in the same place gf_list_add(en->props, data);or how to map the info in some packet like you said in the previous comment

I think that's a good approach yes. You may want to extend the GF_TEMIInfo structure to differentiate between TEMI and SCTE35 messages and change packet prop name in [m2tsdmx_merge_temi](https://github.com/gpac/gpac/blob/master/src/filters/dmx_m2ts.c#L516).

> how can I receive the data in the dasher filter? it's required a new config in that filter?

Nothing specific to do, the data will be passed along as packet properties, so all you need to do is check for the desired properties when processing a packet in the dasher

> how can I put the labels in manifests?

What I would do (at least initially) is format the EXT-X-DATERANGE tag in the dasher, and add that info to the [segment state](https://github.com/gpac/gpac/blob/master/include/gpac/mpd.h#L574), then serialize it after or before the segment [crypt info](https://github.com/gpac/gpac/blob/master/src/media_tools/mpd.c#L3578)

**Comment by rbouqueau** [comment]
@JuanMorenoS Is there any progress or questions here?

**Comment by rbouqueau** [comment]
@JuanMorenoS Is there any progress or questions here?

**Comment by rbouqueau** [comment]
For those reading: WiP in #2748

**Comment by rbouqueau** [comment]
https://github.com/gpac/gpac/pull/2748 merged. Closing.
