### ISSUE TITLE
Syntax not valid issue.

### ISSUE THREAD

**Issue by Faiz786-Hp-rgb** [gpac/gpac#2160]
I am trying to do tiling using this command.

MP4Box -dash 1000 [other dash params]  source.mp4:desc_as=<SupplementalProperty schemeIdUri=\"urn:mpeg:dash:srd:2014\" value=\"0,0,1,1,1,2,2\"/>

but this is showing a syntax error every time I implement this. Different other params were also tried but every time the same issue persist. I have also attached my version of the GPAC.  version 2.0. if some help can be provided that would be really appreciated.

<img width="671" alt="image" src="https://user-images.githubusercontent.com/74789273/161098498-4e1dc736-4636-4989-b7ae-80254fb9ba62.png">

<img width="415" alt="image" src="https://user-images.githubusercontent.com/74789273/161098858-5bef2f05-aa5f-4542-9434-6284f0608fa3.png">

**Comment by rbouqueau** [comment]
That's because you need to escape special characters, see https://stackoverflow.com/questions/10296162/escaping-special-characters-in-cmd. The simplest in your case would be to use some single quote around the ```desc_as=``` value.

**Comment by Faiz786-Hp-rgb** [comment]
I did try to escape the special characters but it is not making the tiling it just creates a dash file and a nonplayable MPD file.
 while executing it gives that certain arguments are not defined which are not understandable to me.

<img width="666" alt="image" src="https://user-images.githubusercontent.com/74789273/162235945-57c34ccd-819e-46cc-9687-fd269aef1ee6.png">

**Comment by rbouqueau** [comment]
I think the error message is pretty clear. Try this instead (to fix the escaping):
```
MP4Box -dash 1000 [other dash params] source.mp4:desc_as='<SupplementalProperty schemeIdUri="urn:mpeg:dash:srd:2014" value="0,0,1,1,1,2,2"/>'
```

**Comment by jeanlf** [comment]
Indeed, the presence of ':' in the XML was not properly checked. Now fixed, thanks for the report
