### ISSUE TITLE
Python APIs where is it

### ISSUE THREAD

**Issue by a23232390** [gpac/gpac#2167]
![image](https://user-images.githubusercontent.com/68137277/162574969-15076696-7fcc-48e1-80bd-d61bbbeaf6a8.png)
I want to make my own mpeg dash ABS
I want to know the user environment bandwidth and total use Bandwidth for playing HEVC TILE video

**Comment by rbouqueau** [comment]
Thank you, we'll improve this. Does https://github.com/gpac/gpac/wiki/python answer your questions?

**Comment by a23232390** [comment]
Thank you for your answer
I am a newbie can you tell me the
environment bandwidth the python api
total use Bandwidth for playing HEVC TILE video the python api

**Comment by rbouqueau** [comment]
Yes, read this section of the link above: https://github.com/gpac/gpac/wiki/python#dash-client. I checked and there is no example for this ; please do not hesitate to share your findings with us!

**Comment by a23232390** [comment]
i watch but Less Python APIs, no way to look up the required API

**Comment by rbouqueau** [comment]
I see it in the code: https://raw.githubusercontent.com/gpac/gpac/master/share/python/libgpac/libgpac.py

It seem similar to the JS binding: https://doxygen.gpac.io/group__dash__grp.html. And there is a basic Ptyhon example at https://github.com/gpac/gpac/wiki/python#dash-client.

I see some comments in the Python code related to doxygen. However, as you mentioned, the doxygen is broken. That's your primary issue. Have you considered trying to fix it?

**Comment by rbouqueau** [comment]
@a23232390 I've fixed the doc. Wait for a few minutes for it to e updated online.

@jeanlf There is a broken link [here](https://github.com/gpac/gpac/wiki/python#dash-client): search for ["the documentation"](https://doxygen.gpac.io/classlibgpac_1_1_filter.html#a05de5bc6b3cb9a3573e00d9f4ccfc056). Do you remember where it should point to?

**Comment by jeanlf** [comment]
doc and wiki updated
