### ISSUE TITLE
Colour convertion bug playing tiled video in VR using HEVC and DASH SRD

### ISSUE THREAD

**Issue by Gabrielgca** [gpac/gpac#2168]
Hello,

I'm trying to play a video in VR mode using HEVC and DASH SRD as follows:

`gpac -i DoiSuthep_dash_22_50.mpd#VR @ compositor @ vout`

But after a few seconds the video seems to have colour conversion issues as shown below:

![image](https://user-images.githubusercontent.com/65353733/162592166-0881fab0-606d-4552-89eb-5083265a0dd5.png)

The manifest was made following  [this](https://github.com/gpac/gpac/wiki/HEVC-Tile-based-adaptation-guide) tutorial. It has two qualities and it seems that the problem happens when it has a quality change, but I am not quite sure.

I have found a similar issue #1919, but his solution did not work for me.

Any help will be very appreciate it.

OS: Windows 10
GPAC: version  2.1-DEV-rev90-g1dc48009a-master

<hr>

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
Are you using nvdec decoder (check by adding -graph) ?
If so could you try without nvdec (-blacklist=nvdec) ?

**Comment by Gabrielgca** [comment]
Thanks for the reply!

I was not using nvdec decoder and I also tried with the  `-blacklist=nvdec`.

Following your step, it turned out that using `-blacklist=ffdec` worked for me. Now the decoder that gpac choose is the `ohevcdec` OpenHEVC-V3.0

**Comment by jeanlf** [comment]
Hmm that's strange, ffdec should be able to decode such a stream. Could you share part of your sequence (either the dash or the source+cmd line) ?

**Comment by Gabrielgca** [comment]
Sure,

Here que the [https://drive.google.com/file/d/1X7uK3GYWXEu8HV2MJevWblxCYIRtj-mD/view?usp=sharing](link) of the dash. Now I'm wondering if I did something wrong encoding the video.
