### ISSUE TITLE
RTMP input cannot encode in multi-qualitis by using given example

### ISSUE THREAD

**Issue by GlassyYang** [gpac/gpac#2171]
It seems like example in [dash-low-latency-live-encoding](https://github.com/gpac/gpac/wiki/dash_low_latency#dash-low-latency-live-encoding) cannot work correctly when simply change input to RTMP. The command I use is:
```
gpac \
        -i rtmp://127.0.0.1:1935/live/test:gpac:rtmp_listen=1:FID=1 \
        ffsws:osize=1920x1080:SID=1 @ enc:c=avc:fintra=1:FID=EV1:b=6m \
        ffsws:osize=1280x720:SID=1 @ enc:c=avc:fintra=1:FID=EV2:b=3m \
        enc:ffc=aac:SID=1:FID=EA:b=128k \
        -o http://127.0.0.1:8080/live.mpd:gpac:SID\=EV1,EV2,EA \
         --hmode=push --profile=live --segdur=1 --cdur=0.1 --asto=0.9
```
`gpac` printed following outputs:
```
[Eval] Undefined constant or missing '(' in 'live'
[aac] Unable to parse option value "live"
[aac] Error setting option profile to value live.
[FFDec] PID audio1 failed to open codec context: Invalid argument
Failed to connect filter ffdmx PID audio1 to filter ffdec: BitStream Not Compliant
Blacklisting ffdec as output from ffdmx and retrying connections
[Eval] Undefined constant or missing '(' in 'live'
[h264] Unable to parse option value "live"
[h264] Error setting option profile to value live.
[FFDec] PID video1 failed to open codec context: Invalid argument
Failed to connect filter ffdmx PID video1 to filter ffdec: BitStream Not Compliant
Blacklisting ffdec as output from ffdmx and retrying connections
[FFEnc] No codecid specified
Failed to connect filter dec_faad:FAAD2 PID audio1 to filter ffenc: Bad Parameter
x264 [error]: invalid profile: live
[libx264] Error setting profile live.
[FFEnc] PID video1 failed to open codec context: Invalid argument
Failed to connect filter ffsws PID video1 to filter ffenc:libx264: Bad Parameter
x264 [error]: invalid profile: live
[libx264] Error setting profile live.
[FFEnc] PID video1 failed to open codec context: Invalid argument
Failed to connect filter ffsws PID video1 to filter ffenc:libx264: Bad Parameter
session last connect error Bad Parameter
Unknown argument "--profile" set but not used by any filter - no matching argument found
Argument "--segdur" was set but not used by any filter
Argument "--cdur" was set but not used by any filter
Argument "--asto" was set but not used by any filter
Filters not connected:
httpout (dst=http://127.0.0.1:8080/live.mpd:gpac:SID=EV1,EV2,EA) (idx=7)
```
I found that this error is wrong parameters was given to `gpac`. I want to know how can I do the same thing by correct command? I have tried many commands. Thank you very much

**Comment by rbouqueau** [comment]
First in ```SID\=EV1,EV2,EA```, the ```\``` is incorrect.

Second in ```enc:ffc=aac```, I don't know what ```ffc``` is. Put ```enc:c=aac``` instead. @jeanlf That's legacy, correct?

Then ```--profile=live``` seems to emit some misleading errors. Put the option locally: ```http://127.0.0.1:8080/live.mpd:gpac:SID\=EV1,EV2,EA:profile=live```. @jeanlf Do you know why this global option causes so many issues?

**Comment by GlassyYang** [comment]
Thank you very much. After your advice, I have corrected my command and it now works well.

**Comment by rbouqueau** [comment]
@jeanlf Could you have a look at the two mentions for you above before we close. Thanks

**Comment by jeanlf** [comment]
> enc:ffc=aac

`ffc` is an ffenc option used to select the underlying codec if several are available for the coding type. It is not parsed by the `enc` alias, so `enc:ffc=aac` cannot detect the coding type (note that `ffenc:ffc=aac` does not work either it still needs `c=aac`, I'll patch that).
 

> `--profile=live` 

That's trickier, some meta filters (in this case ffenc:libx264) have options using the same name as other filters (here dasher). There is no way to detect that, unfortunately. To be safe, either use the option locally (eg `:profile=live`) or set the filter name in the global option (eg `--dasher:profile=live`)

**Comment by jeanlf** [comment]
errata: `ffc` has been removed in 2.0 , I forgot about that....

**Comment by jeanlf** [comment]
wiki updated
