### ISSUE TITLE
"mp4box -udta ..." naming track IDs works YET outputs ~>[isom/avcc] Missing REXT profile signaling, patching.

### ISSUE THREAD

**Issue by tweed** [gpac/gpac#2176]
[INSTALLED: windows latest mid-april 2022 GPAC dev versions]

OBJECTIVE:  To find out the meaning of output message ~>>  "[isom/avcc] Missing REXT profile signaling, patching."

I RUN:
mp4box -udta 1:type=name:str=homevid001  -udta  2:type=name:str=homeaud001   home001.mp4

In-place editing works brilliantly YET shows this:   

" [isom/avcc] Missing REXT profile signaling, patching. "

May I ask if this is expected and normal... ??

HERE APPEARS TO BE THE SOURCE CODE WITH ENTIRE  "Missing REXT..."  MESSAGE IN IT - and more!-)
https://github.com/gpac/gpac/blob/275394b43a0a4516b88fc42cca2b9299004b50f8/src/isomedia/avc_ext.c

I wonder, why this gets output, and, can i ignore this?
~>  " [isom/avcc] Missing REXT profile signaling, patching. "

Perplexed-) enough to stop until i know the answer.  Comments asked for please and thanks.
I looked at the hexidecimal differences while trying several naming and renaming experiments.
Fascinating, yet there were enough changes that even study and searches couldn't help me understand.

THANK YOU for the read/think in absolutely any event. -)

**Comment by jeanlf** [comment]
The message is trigger for AVC|H264 tracks missing the end of the decoder config record, this happens a lot with files produced according to older versions of ISO/IEC 14496-15.

The message is a warning indicating GPAC is recomputing the values from the bitstream and can be ignored.

**Comment by tweed** [comment]
SUPERBLY HELPFUL - cannot thank you enough!
Keen not to even slightly mangle my seasons long digital archiving project.~}

Happy to have this question answered, and hoping to find a forum where 
the inexperienced can ask basic yet potentially obscure questions. 
Doesn't feel quite right to ask simpler questions here.  And... happy to be here!

Earlier today I read about other features and options that are amazingly interesting. 
GREAT WIKI
GPAC/MP4BOX discovery absolutely fabulous!
