### ISSUE TITLE
MP4Box input file from server

### ISSUE THREAD

**Issue by shravandoda** [gpac/gpac#2178]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

How can I use a file present on a server as the input file for MP4Box command? I have the source url (something like `https://abcd.com/video/testing.mp4`. I want to use `dash` operation on this.

**Comment by shravandoda** [comment]
@jeanlf kindly guide

**Comment by shravandoda** [comment]
Tried this. Doesn't work.
```
>> MP4Box -dash 2000 $URL                                                                                                
[SSL] Cannot connect, error -1
[HTTP] Error sending request Network Unreachable
Error DASHing file: Network Unreachable
```

**Comment by rbouqueau** [comment]
Can you share a $URL that fails with us?

**Comment by shravandoda** [comment]
`http://s-cdn.qoohoo.in/video/009d7f6702194bcfa798b1b6273bacfd.mp4`

**Comment by shravandoda** [comment]
> Can you share a $URL that fails with us?

http://s-cdn.qoohoo.in/video/009d7f6702194bcfa798b1b6273bacfd.mp4

**Comment by rbouqueau** [comment]
It works (except that the mp4 file itself is broekn, which I confirmed by downloading it locally with wget):
```
$ MP4Box -dash 2000 009d7f6702194bcfa798b1b6273bacfd.mp4
[iso file] Box 00000000 size 1751411826 is larger than remaining parent size 225
[Dasher] No template assigned, using $File$_dash$FS$$Number$
[MPD] Generating MPD at time 2022-04-20T13:14:37.071Z.56s 99 %
[Dasher] End of Period 
[Dasher] End of MPD (no more active streams)
```

What do you get on your side? Which version of GPAC are you using?

**Comment by shravandoda** [comment]
> It works (except that the mp4 file itself is broken, which I confirmed by downloading it locally with wget):
> 
> ```
> $ MP4Box -dash 2000 009d7f6702194bcfa798b1b6273bacfd.mp4
> [iso file] Box 00000000 size 1751411826 is larger than remaining parent size 225
> [Dasher] No template assigned, using $File$_dash$FS$$Number$
> [MPD] Generating MPD at time 2022-04-20T13:14:37.071Z.56s 99 %
> [Dasher] End of Period 
> [Dasher] End of MPD (no more active streams)
> ```
> 
> What do you get on your side? Which version of GPAC are you using?

`gpac - GPAC command line filter engine - version 1.0.1-revrelease`

**Comment by rbouqueau** [comment]
Can you update to the latest nightly build and retry?

**Comment by shravandoda** [comment]
> Can you update to the latest nightly build and retry?

Sure

**Comment by shravandoda** [comment]
Working with latest release

**Comment by shravandoda** [comment]
@rbouqueau when built from source, I get the error. Am I doing something wrong while building?
```
❯ ./MP4Box -dash 2000 -out "output.mpd" $URL#video $URL#audio
Static GPAC build has no DNS support, cannot resolve host s-cdn.qoohoo.in !
Static GPAC build has no DNS support, cannot resolve host s-cdn.qoohoo.in !
Filters not connected:
fout (dst=output.mpd:gpac:segdur=2000/1000:bs_switch=off:profile=onDemand:buf=1500:!check_dur:pssh=v:subs_sidx=0:sfrag) (idx=1)
Arg segdur set but not used
Arg bs_switch set but not used
Arg profile set but not used
Arg buf set but not used
Arg !check_dur set but not used
Arg pssh set but not used
Arg subs_sidx set but not used
Arg sfrag set but not used
Arg tkid set but not used
Error DASHing file: Network Unreachable

```

**Comment by rbouqueau** [comment]
> ```Static GPAC build has no DNS support, cannot resolve host s-cdn.qoohoo.in !```

As written, don't use a static build if you need DNS support.

**Comment by shravandoda** [comment]
Needed a static build to be run on AWS Lambda. Any way around this?

**Comment by shravandoda** [comment]
> Needed a static build to be run on AWS Lambda. Any way around this?

@rbouqueau lmk if there's any way around this

**Comment by jeanlf** [comment]
see discussion in #1685 - the only workaround for now is to pass resolved IP to MP4Box / gpac.
