### ISSUE TITLE
i want to ask RTMP to hevc tile some question

### ISSUE THREAD

**Issue by a23232390** [gpac/gpac#2180]
Hello there, I'm using a GPAC version compiled with ffmpeg and libkvazaar to try and generate the MPD and segmets from a live feed.
when i hit this 

gpac   -i ./1.mp4  ffsws:FID=S -+kvazaar-params=tiles=3x3,slices=tiles,mv-constraint=frametilemargin,rc-algorithm=lambda enc:SID=S:c=libkvazaar:b=1m:fintra=1:rc @ tilesplit:FID=1 enc:SID=S:c=libkvazaar:b=200k:fintra=1:rc @ tilesplit:FID=2 -o ./dash/live.mpd:SID=1,2:dmode=dynamic

I have this problem is the encoding not fast enough?
Still can adjust those parameters to improve this problem

Disabling TMVP because tiles are used.
Disabling WPP because tiles were enabled.
Compiled: INTEL, flags: MMX SSE SSE2
Detected: INTEL, flags: MMX SSE SSE2 SSE3 SSSE3 SSE41 SSE42 AVX AVX2
Available: avx(1749) avx2(8586) sse2(318) sse41(636) 
In use: avx(159) avx2(8586) 
--owf=auto value set to 2.
--threads=auto value set to 2.
Disabling TMVP because tiles are used.
Disabling WPP because tiles were enabled.
Compiled: INTEL, flags: MMX SSE SSE2
Detected: INTEL, flags: MMX SSE SSE2 SSE3 SSSE3 SSE41 SSE42 AVX AVX2
Available: avx(1760) avx2(8640) sse2(320) sse41(640) 
In use: avx(160) avx2(8640) 
--owf=auto value set to 2.
--threads=auto value set to 2.
[Dasher] AS-1 Rep 1 segment 79 done TOO LATE by 77651 ms
[Dasher] AS-1 Rep 3 segment 79 done TOO LATE by 77777 ms
[Dasher] AS-1 Rep 12 segment 79 done TOO LATE by 77778 ms
[Dasher] AS-1 Rep 4 segment 79 done TOO LATE by 77778 ms
[Dasher] AS-1 Rep 13 segment 79 done TOO LATE by 77778 ms
[Dasher] AS-1 Rep 5 segment 79 done TOO LATE by 77778 ms
[Dasher] AS-1 Rep 14 segment 79 done TOO LATE by 77778 ms
[Dasher] AS-1 Rep 6 segment 79 done TOO LATE by 77778 ms
[Dasher] AS-1 Rep 15 segment 79 done TOO LATE by 77778 ms
[Dasher] AS-1 Rep 7 segment 79 done TOO LATE by 77778 ms
[Dasher] AS-1 Rep 16 segment 79 done TOO LATE by 77778 ms
[Dasher] AS-1 Rep 8 segment 79 done TOO LATE by 77778 ms
[Dasher] AS-1 Rep 17 segment 79 done TOO LATE by 77778 ms
[Dasher] AS-1 Rep 9 segment 79 done TOO LATE by 77778 ms
[Dasher] AS-1 Rep 18 segment 79 done TOO LATE by 77778 ms
[Dasher] AS-1 Rep 10 segment 79 done TOO LATE by 77779 ms
[Dasher] AS-1 Rep 19 segment 79 done TOO LATE by 77779 ms
[Dasher] AS-1 Rep 11 segment 79 done TOO LATE by 77779 ms
[Dasher] AS-1 Rep 20 segment 79 done TOO LATE by 77779 ms

this is computer setup
![image](https://user-images.githubusercontent.com/68137277/165679427-ad3a5a80-2bfa-4559-8a00-97185ec911d7.png)

1.mp4 setup
 Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 36 kb/s, 23.98 fps, 23.98 tbr, 24k tbn (default)
  
ffmpeg version
ffmpeg version 4.4.git Copyright (c) 2000-2022 the FFmpeg developers
gpac version 
gpac - GPAC command line filter engine - version 2.1-DEV-rev116-g3dbe11b37-master
(c) 2000-2022 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io

**Comment by rbouqueau** [comment]
If you think the encoding is too slow, try with a local file. See https://github.com/gpac/gpac/issues/2136#issuecomment-1065294353

**Comment by jeanlf** [comment]
could you share your sample input file ?

**Comment by a23232390** [comment]
@pclouds  i use local file same problem
@jeanlf this is the input file 
https://drive.google.com/drive/folders/1kLzGoL8xH0ozKj44-jh84pKD0THS5p5y?usp=sharing

**Comment by a23232390** [comment]
i know just CPU is not powerful enough
