### ISSUE TITLE
Can I use MP4Box to combine audio and video with some delay into one video file?

### ISSUE THREAD

**Issue by zydjohnHotmail** [gpac/gpac#2184]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hello:
I have one audio file (aac format) named: 1.aac, and one video file (mp4 format) named: 1.mp4, the video file has no audio, and its duration is 5 seconds longer than the audio file.
Let’s say that: 1.aac file has duration of 55 seconds, and 1.mp4 file has duration of 1 minute.
I want to make one video file: merge.mp4 with audio from 1.aac, and video from 1.mp4.
But with one requirement that the audio start from the 5th second, therefore, the audio and video will end at the same time at the end of merge.mp4.
I can’t find any example on how to do this using MP4Box, however, FFMPEG has such parameter, but I prefer to use MP4Box, as it is faster and better.
I am using MP4Box version 2.0 on Windows 10.
Please advise,
Thanks,

**Comment by rbouqueau** [comment]
Look at the ```-delay```with a negative value at https://github.com/gpac/gpac/wiki/mp4box-gen-opts. Would it help?

**Comment by zydjohnHotmail** [comment]
Hello:
I got lost, can you please provide an example?

**Comment by aureliendavid** [comment]
You can use something like this: 

```
MP4Box -add vid.mp4 -add audio.mp4:delay=5000 -new merged.mp4
```

**Comment by zydjohnHotmail** [comment]
It works,
Thanks!
