### ISSUE TITLE
How to extract audio from video file without knowing the audio track ID?

### ISSUE THREAD

**Issue by zydjohnHotmail** [gpac/gpac#2187]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hello:
I have one video file: 1.mp4, it contains only one video track and only one audio track.  I want to extract the only audio from it, but I don't know the audio track ID, sometimes, it is 2, but most of the times (90%+), the audio track ID will be a high number, like 256, 257 or 1001, there is no way to know the track ID without using mp4box -info.
However, I know that the MP4 file has only one audio track.
Can I run mp4box to extract the audio track without knowing its audio track ID?
ffmpeg can do this, but I prefer to use mp4box.
Please advise!

**Comment by rbouqueau** [comment]
```MP4Box -add file.mp4#audio audio.mp4```

**Comment by zydjohnHotmail** [comment]
It works!
Thanks!
