### ISSUE TITLE
Can I use MP4Box to virtually create a 24 hour video with several video clips.

### ISSUE THREAD

**Issue by chokosticks** [gpac/gpac#2188]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ x] I looked for a similar issue and couldn't find any.
- [x ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hello,

I am working with a task of be able to view clips of video that happened during the day, triggered by motion detection from a camera. And be able to stream these video in a single player, for example shaka player.

I've thought of creating a virtual 24 hours video of, for example, 10 clips of different duration, and make a viable manifest file which kan display this video and information on a 24 hour timeline?

Or is it some other way I can create a manifest which will use all of these small videos?

Thanks in advance.

**Comment by chokosticks** [comment]
Hi, thanks for a quick response!

Yes I will be able to re-encode the video.

I will take a look at what you've mentioned. 

End goal for me is to be able to stream this "24 hours" video on the web, beeing able to make a mark  where the different videoclips happened during the day on the 24 hour timeline, and be able to switch in between the videos where motion were detected.

My videos are stored at granularity of a day. i.e. one folder per day with videos from one camera. So one manifest per day I presume.

Thanks!

**Comment by rbouqueau** [comment]
Ok. If I were you, I would prepare a black content. You could pre-encode the back and the clips to avoid re-encoding 24h of video. Then I would build a 24h playlist with some "multi-period session" (look for that [here](https://github.com/gpac/gpac/wiki/playlist)) (The "Period" is the highest-level time element of the DASH manifest/playlist).

PS: the [flist regression tests](https://github.com/gpac/testsuite/search?q=flist) may serve as examples

**Comment by chokosticks** [comment]
Hi,

I'll give it a try, thanks for the input!

**Comment by rbouqueau** [comment]
Hi, could you please indicate why the issue was closed. If you found a way, that may be of interest for other users. Thanks

**Comment by chokosticks** [comment]
Hi,

I tried it out a little, but because of lack of time right now, I'll give it more attention at a later stage.

I'll reopen the issue if and when I'll make it work.

Thanks for the tips!
