### ISSUE TITLE
Issue with streaming manifest file on Exoplayer

### ISSUE THREAD

**Issue by bhattaBB** [gpac/gpac#2189]
Hello,
I have used Kvazaar to split a 360-degree video (YUV format) into 3x3 tiles and make a .hvc file. I then used the .hvc file to package within a container via MP4Box `$ MP4Box -add video_tiled.hvc:split_tiles -fps 30 -new video_tiled.mp4`
Later I used the generated file to create an MPD file using the following command `$ MP4Box -dash 1000 -rap -frag-rap -profile live -out dash_tiled.mpd video_tiled.mp4`
Although the manifest file is playing on Osmo4, the tiles have been split and I can observe the splitting in the video, but it seems to be still in YUV format. Also, I am not able to play the video on my Exoplayer application. The lines in the manifest file seem to be okay. (Attaching it here for reference). Can someone point out what am I missing?
![image](https://user-images.githubusercontent.com/73991812/167699440-ecb9c35c-e114-44aa-a33e-e97e361decc0.png)
[dash_tiled.txt](https://github.com/gpac/gpac/files/8664164/dash_tiled.txt)

**Comment by jeanlf** [comment]
What is the decoder used (try `gpac -i file.mpd vout -graph`) ? Could you upload your transcoded tile HEVC file (not the dash) ?

I don't think exoplayer supports tiled VR + DASH

**Comment by Faiz786-Hp-rgb** [comment]
this is the transcoded HVC file. 

[output.zip](https://github.com/gpac/gpac/files/8883701/output.zip)

**Comment by jeanlf** [comment]
the file is ok and tile dashing / playback works fine.

Like I said:
> I don't think exoplayer supports tiled VR + DASH
