### ISSUE TITLE
MP4Box -base-url has no effect on file creation

### ISSUE THREAD

**Issue by blacktrash** [gpac/gpac#219]
Issue migrated from [here](http://sourceforge.net/p/gpac/bugs/351/).
- Files are not created under base url, but in current directory:

``` sh
$ mkdir base
$ MP4Box -dash 10000 -base-url 'base/' -segment-name '$RepresentationID$-$Number$' -url-template -out test.mpd test.mp4#audio test.mp4#video
$ ls -1 base
$ ls -1 | wc -l
     125
```
- prefixing segment name with base url result in files created in correct directory, but base url must then be removed from the `media` and `initialization` attributes of the SegmentTemplate tag:

``` sh
$ MP4Box -dash 10000 -base-url 'base/' -segment-name 'base/$RepresentationID$-$Number$' -url-template -out
test.mpd test.mp4#audio test.mp4#video
$ ls -1 base | wc -l
     122
$ ls -1
base
test.mp4
test.mpd
$ fgrep RepresentationID test.mpd
   <SegmentTemplate timescale="44100" media="base/$RepresentationID$-$Number$.m4s" startNumber="1" duration="440294" initialization="base/$RepresentationID$-.mp4"/>
   <SegmentTemplate timescale="19200" media="base/$RepresentationID$-$Number$.m4s" startNumber="1" duration="192000" initialization="base/$RepresentationID$-.mp4"/>
```

With more than one video input, the set init file is still created in the current directory and must be moved into the base url directory.

**Comment by blacktrash** [comment]
In short: The base url should not be repeated in the SegmentTemplate.

**Comment by blacktrash** [comment]
With default inband bs switching the video init files are erroneously created in the current directory even when I give a segment name prefixed with base-url to have the segments in the base-url directory:
```sh
$ MP4Box -dash 10000 -base-url base/ \
-segment-name "base/\$RepresentationID\$-\$Number\$" \
-url-template -out test.mpd \
test-300.mp4#audio \
test-300.mp4#video \
test-600.mp4#video
$ ls -1
base
out_test-300.mp4
out_test-600.mp4
test-300.mp4
test-600.mp4
test.mpd
test_set2_init.mp4
```

**Comment by blacktrash** [comment]
The same happens without `-url-template`. In that case the base url in the values of the `media` attributes in the `SegmentURL` tags and the `sourceURL` attributes of the `Initialization` tags must be removed after running MP4Box.

**Comment by rbouqueau** [comment]
Thank you for your patience. I have not forgotten about this issue. Just lack of time and resources yet.

**Comment by blacktrash** [comment]
Sure, no prob.

**Comment by jeanlf** [comment]
baseurl is not design to alter creation path, it only inserts baseURL elements in the MPD.
To do what you want, you will need to set the base url and also modify the segment template as follows:
```
MP4Box [...] -base-url foo/ -segment-name $Path=foo/$file-$Number$ [...]
```
This will create the files in foo/ but will keep the mpd template as "file-$Number$"

**Comment by alexkozhemyakin** [comment]
I solve the issue with "-out".
MP4Box [...] -segment-name required_segment_name  -out ./foo/index.mpd [...]

This will create the all files in foo/ directory(index.mpd + all segment files)

**Comment by blacktrash** [comment]
@jeanlf - thanks, I was either missing `$Path=...$` or it did not exist at the time I filed the issue.
