### ISSUE TITLE
How to force audio sampling rate w/ mp4box

### ISSUE THREAD

**Issue by Kurtnoise29** [gpac/gpac#2191]
Hi,

I would like to know if it's doable to force the sampling rate during audio stream import within MP4Box...because I would like to mux h264 video and opus audio streams but sometimes my audio streams have sampling rate @ 44.100 KHz. 

Import opus streams to mp4 forces the sampling rate @ 48000 Hz. So, my question is : is it possible to put the sampling rate @ 44.100 KHz for such streams within MP4Box ?

Thanks in advance.

**Comment by Kurtnoise29** [comment]
Hi Romain,

[here is a sample](https://www.mediafire.com/file/n6959vv2ujdezqp/output.opus/file). Just generated using opusenc from https://github.com/xiph/opus.

After muxing w/ MP4Box, I get this :

`# Movie Info - 1 track - TimeScale 600
Duration 00:00:06.115
Fragmented: no
Progressive (moov before mdat)
Major Brand isom - version 1 - compatible brands: isom
Created: GMT Fri May 13 07:09:51 2022

File has root IOD (9 bytes)
Scene PL 0xff - Graphics PL 0xff - OD PL 0xff
Visual PL: No visual capability required (0xff)
Audio PL: Not part of MPEG-4 audio profiles (0xfe)
No streams included in root OD

iTunes Info:
        tool: libopus 1.3.1-103-gc6f98577, libopusenc 0.2.1-14-gf51c3aa
        encoder: opusenc from opus-tools 0.2-28-g5d0ac20

# Track 1 Info - ID 1 - TimeScale 48000
Media Duration 00:00:06.120
Track has 1 edits: track duration is 00:00:06.115
Track flags: Enabled In Movie In Preview
Media Info: Language "Undetermined (und)" - Type "soun:Opus" - 306 samples
        Opus Audio - Sample Rate 48000 ch 2
        RFC6381 Codec Parameters: Opus
        All samples are sync
        Max sample duration: 960 / 48000`

**Comment by phloxic** [comment]
I guess this is because opus sample rate is 'always 48000' so to speak. See the section 'Input sample rate' at https://wiki.xiph.org/OggOpus#ID_Header
And 44100 Hz is not in the list of decoding rates.
