### ISSUE TITLE
MP4Box dash can't use input modifiers when opening a TS file

### ISSUE THREAD

**Issue by gtow** [gpac/gpac#2192]
Hi,
I'm trying to use DASH segmentation to remux a TS video into a DASH.
But I can't get sepparated streams (video/audio).
When I use one of the input modifiers (#audio, #video or #trackID), for example:
MP4Box -dash 1000 -profile live -segment-name file_ input.ts#audio -out output.mpd
those modifiers are ignored, and the output alerts with the message:
**Arg tkid set but not used**
Always i get all the streams muxed in the same segment.m4s
It works ok if my input is encapsulated in a mp4.
I've tried with the version
GPAC version 1.1.0
and the last 
GPAC version 2.0-revrelease
with same result.

It's possible to use the modifiers when opening a TS file?

Thank you very much

**Comment by jeanlf** [comment]
This is now supported in master.

Note that you can achieve the same result with gpac (slightly more efficiently since only one source will be opened) using:

```
gpac -i input.ts -o output.mpd
```

For single track filtering:
```
gpac -i input.ts @#audio -o output.mpd
```

**Comment by gtow** [comment]
Thank you very much
