### ISSUE TITLE
How to properly use :asID=VALUE with MP4Box

### ISSUE THREAD

**Issue by Eelisland** [gpac/gpac#2196]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

From my understanding :asID=VALUE add an ID to the AdaptationSet parent of the Representation.

Using this command line:
```
MP4Box -dash 10000 -profile dashavc264:onDemand test.mp4#trackID=1:id=video test.mp4#trackID=2:id=fre test.mp4#trackID=3:id=eng test.mp4#trackID=6:id=fr_forced:asID=fr_forced:role=forced-subtitle test.mp4#trackID=7:id=fr_full:asID=fr_full:role=subtitle -out index.mpd
```
I was expecting this result (truncated):
```
  <AdaptationSet id="fr_forced" segmentAlignment="true" lang="fra" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
   <Role schemeIdUri="urn:mpeg:dash:role:2011" value="forced-subtitle"/>
   <Representation id="fr_forced" mimeType="application/mp4" codecs="wvtt" bandwidth="25">
    <BaseURL>test_dash_track6_init.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="965-8904">
     <Initialization range="0-804"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
```
But **id="fr_forced"** is not added to the AdaptationSet

**Comment by jeanlf** [comment]
AdaptationSet IDs are unsigned integers only, I added log messages to check wrong argument types

**Comment by Eelisland** [comment]
@jeanlf hello,
Thank you, using unsigned integer add id to AdapationSet.
