### ISSUE TITLE
Feature request: possibility to add a file.vtt to MPD from command line

### ISSUE THREAD

**Issue by Eelisland** [gpac/gpac#2197]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Actually i'm editing MPD file after creation to add file.vtt to load it with dash.js:
```
    <AdaptationSet id="3" contentType="text" mimeType="text/vtt" lang="fre" startWithSAP="1">
      <Label>Français forcés</Label>
      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="forced-subtitle"/>
      <Representation id="3" bandwidth="256">
        <BaseURL>3_fre.vtt</BaseURL>
      </Representation>
    </AdaptationSet>
```
I was hopping MP4Box can do it from command line, for example:

```
MP4Box -dash 4000 -frag 4000 -rap -fps 24 \
test.mp4#trackID=1:id=video \
test.mp4#trackID=2:id=fre \
/path/to/3_fre.vtt#subtitle:id=3:asID=3:role=forced-subtitle:desc_as='<Label>Français forcés</Label>' \
-out index.mpd
```
Thank you.

**Comment by jeanlf** [comment]
Using latest master:

```
 MP4Box -dash 2000 av2.mp4#video subs.vtt:role=forced-subtitle:desc_as='<Label>Français forcés</Label>'  -profile onDemand -out dash/test.mpd
```

gives in test.mpd:

```
 <AdaptationSet segmentAlignment="true" lang="und" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
    <Label>Français forcés</Label>
   <Role schemeIdUri="urn:mpeg:dash:role:2011" value="forced-subtitle"/>
   <Representation id="2" mimeType="application/mp4" codecs="wvtt" bandwidth="421">
    <BaseURL>subs_dashinit.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="797-924">
     <Initialization range="0-796"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
```

This uses vtt in mp4 (default mode for dasher). If you want the raw format, use [--rawsub](http://wiki.gpac.io/dasher#rawsub) option:


```
MP4Box -dash 2000 av2.mp4#video subs.vtt:role=forced-subtitle:desc_as='<Label>Français forcés</Label>'  -profile onDemand -out dash2/test.mpd --rawsub
```

gives in test.mpd

```
<AdaptationSet segmentAlignment="true" lang="und" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
    <Label>Français forcés</Label>
   <Role schemeIdUri="urn:mpeg:dash:role:2011" value="forced-subtitle"/>
   <Representation id="2" mimeType="application/mp4" codecs="wvtt" bandwidth="421">
    <BaseURL>subs_dashinit.vtt</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="0-0">
    </SegmentBase>
   </Representation>
  </AdaptationSet>
```


Appart from the mime type which is not quite right (I'm looking into that), it works as expected. Can you reproduce ?

**Comment by jeanlf** [comment]
mime type should now be correct.
