### ISSUE TITLE
VVC does not read profile high by MP4BOX after vvc encoding

### ISSUE THREAD

**Issue by MartinEesmaa** [gpac/gpac#2200]
@jeanlf,

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

MP4BOX/GPAC version: MP4Box - GPAC version 2.1-DEV-rev173-g82dd6d2b-master

vvencapp version: 1.4.0

OS: Windows 11

My github action & encoded .266 file: https://github.com/MartinEesmaa/fixmyissueofGPAC/actions/runs/2351776705

Run log: https://github.com/MartinEesmaa/fixmyissueofGPAC/runs/6506624031?check_suite_focus=true

Steps reproduced:
1: I converted from mp4 to yuv
2: Converted from YUV 8-bit to VVC 10-bit using code: `vvencapp -i bbbbeforenw.yuv -s 1280x720 -r 24 --preset fast --qp 35 --tier high -o gpactestvvc.266`
3: After converting, I checked .266 file in mp4box and I got an error:
```
mp4box -info gpactestvvc.266.266
Import probing results for gpactestvvc.266.266:
File has no selectable tracks
```

**Comment by jeanlf** [comment]
indeed the prober was looking for a vps which is not mandatory in vvc, now fixed thanks for the file.

FYI, you can disable bitstream probing using `-no-probe`, this will rely on file extension for media identification
