### ISSUE TITLE
Producing MISB ST1910 CMAF from MPEGTS

### ISSUE THREAD

**Issue by jwstover** [gpac/gpac#2204]
Hello, I apologize if this is not the right place, but I was hoping for some guidance on how I could best approach this problem and if GPAC/MP4Box is the right tool for the job. 

What I would like to do is convert an mpegts file that contains a single video stream and a single KLV data stream to CMAF according to [MISB ST1910](https://nsgreg.nga.mil/doc/view?i=5097). What I'm most interested in is mapping the KLV metadata packets into EMSG boxes in the output CMAF. There is a demo [DASH manifest](https://www.mistandards.org/demo/cmaf/data/ST1910.1/H264/cmafsample.mpd) that looks like it was created with GPAC that gives me some hope, but I'm not really sure where to start.

**Comment by rbouqueau** [comment]
The only reference I see in the GPAC repository is in #736. Maybe that was the original contributors?

Have you tried to write to the MASB chair to ask how they generated the streams?

**Comment by rbouqueau** [comment]
Any news here?

**Comment by rbouqueau** [comment]
Still no news here?

**Comment by jwstover** [comment]
Hi, apologies for the long delay. I reached out to one of the people that worked on the demo that I linked in my original question. The manifest and CMAF chunks were made using a collection of custom python scripts that are entirely unrelated to GPAC. As far as I am aware there isn't a tool that provides the capability that I was looking for.

**Comment by rbouqueau** [comment]
Ok, closing for now. Please re-open if there is news.
