### ISSUE TITLE
GPAC full form

### ISSUE THREAD

**Issue by bhattaBB** [gpac/gpac#2205]
This may come off as a dumb question to ask but I need to include it in my project report. I did not find what GPAC stands for on the internet so maybe the contributors may help. On Wikipedia it says GPAC is a recursive acronym.
Can someone tell me what GPAC stands for?

**Comment by aureliendavid** [comment]
as wikipedia states, gpac is a [recursive acronym](https://en.wikipedia.org/wiki/Recursive_acronym) meaning the g in gpac actually stands for gpac in the same way gnu stands for gnu's not unix, so _GPAC = GPAC Project on Advanced Content_
