### ISSUE TITLE
mp4box split option doesn't handle chapter data

### ISSUE THREAD

**Issue by HellmannM** [gpac/gpac#2209]
Issue:
Calling `mp4box -splits` doesn't distribute chapter marks onto the split files.

Example:
10min mp4 video with a chapter that starts at 9 minutes. After splitting, the first part contains the chapter mark even though that mark points to a section that is in another split file.

Command used:
`mp4box v.mp4 -splits 1024 -out v_$num%03d$.mp4`

Explanation:
While trying to split mp4 files by size (-splits option) I noticed, that chapter information is simply copied to ~~the first split while all other splits don't contain any chapter information at all~~ all splits without rebasing. This results in broken chapters, since chapters may point to times after the first split file.

Expected behaviour:
Chapter marks are distributed to the according split files (and rebased since every split video starts at 0 time again).

System info:
MP4Box - GPAC version 2.1-DEV-rev193-g7370ab0b-master
Windows 10 Pro 20H2

**Comment by jeanlf** [comment]
How are the chapters indicated, as a text track or as user data box ? 
Could you upload a sample ?

**Comment by HellmannM** [comment]
The chapters were inserted into the video with mp4box and a text file formatted like this:
```
CHAPTER0001=0:00:17:448
CHAPTER0001NAME=Chapter 1
CHAPTER0002=0:00:45:303
CHAPTER0002NAME=Chapter 2
[...]
```

**Comment by HellmannM** [comment]
While trying to re-create a sample, I noticed that the chapter marks are actually copied to all splits and not only the first one as stated in my initial post. I edited the post to reflect current behaviour. Here are sample files I used this time:

Commands used:
```
mp4box vid.mp4 -chap chap.txt -out vid_with_chaps.mp4
mp4box vid_with_chaps.mp4 -splits 5000 -out vid_with_chaps_$num%03d$.mp4
```

[chap.txt](https://github.com/gpac/gpac/files/8989832/chap.txt)

https://user-images.githubusercontent.com/22742274/175891189-4d7e2fde-fbea-42b8-8efd-63de75f8b01f.mp4

**Comment by jeanlf** [comment]
Yes, chapters stored in udta are not yet split by the reframer filter, only chapters stored as qt text tracks are. I'll see if I can come up with a quick patch

**Comment by jeanlf** [comment]
Now available on master. [File concatenator](https://github.com/gpac/gpac/wiki/flist) filter can also be used to inject chapters using `#chap=Name` in playlist instructions.
