### ISSUE TITLE
"Video Element Error: MEDIA_ERR_SRC_NOT_SUPPORTED" in dash.js player

### ISSUE THREAD

**Issue by JamesXu20150314** [gpac/gpac#221]
Hi,
everyone.

I have used dashcast(GPAC) to create my dash content. MP4Client plays them fine.

I am trying to play them using the dash.js reference player. But I recieved this result:

![image](https://cloud.githubusercontent.com/assets/11470231/9575152/c03e1a7e-4fff-11e5-8d7f-f9c272e017c1.png)

I use the command
dashcast -av test.mp4 -seg-dur 10000 -time-shift -1 -vcodec "h264" -acodec "acc" -gop 30
![Uploading QQ图片20150831173142.jpg…]()

And my dash content is

image
![image](https://cloud.githubusercontent.com/assets/11470231/9575154/c8e39b40-4fff-11e5-8db7-78794aa09dad.png)

image
![image](https://cloud.githubusercontent.com/assets/11470231/9575158/d1ea15e8-4fff-11e5-99cc-7015234dcecb.png)

I'll be thankful for some help.

**Comment by JamesXu20150314** [comment]
Is that means the DashCast has a very serious bug?

**Comment by cconcolato** [comment]
You may have configured DashCast with incompatible parameters for dash.js. Please provide the version of dash.js, of DashCast, of Chrome and if possible your test content.

**Comment by JamesXu20150314** [comment]
I am so glad that you can help me.
The version of my Chrome is 45.0.2454.85 m (64-bit).
The version of my DashCast is gpac-0.5.2-DEV-rev625-g1f8466a-master-x64.exe
The dash.js is the file from there: https://github.com/Dash-Industry-Forum/dash.js/tree/development/dist
The dash.all.js run in Apache.

Could you tell me how can I exactly configure the DashCat for this dash.all.js.

**Comment by JamesXu20150314** [comment]
I need your help. I am so interest in the function of your DashCast.

**Comment by cconcolato** [comment]
Using the following command line works for me:
```
dashcast -v test.mp4 -seg-dur 10000 -time-shift -1 -npts -low-delay
```
It is video only as I have some issues with the audio for now. I'm still investigating. I had to add two options:
  - `-npts` because the timestamp that ffmpeg was generating were completely crazy. This option tells dashcast to ignore those timestamps and to simply count the number of frames and increment the timestamp by the duration of the frame in the given timescale. 
  - `-low-delay`because it seems that we have an issue when encoding video with B-frames, the first segment uses lots of sync sample (at least when encoding the counter video) but does not align the sync sample with the start of segments. This creates an issue for Chrome. You can view the error in the `chrome://media-internals` tab, it says:
```
Media segment did not begin with key frame. Support for such segments will be available in a future version. Please see https://crbug.com/229412
```

**Comment by JamesXu20150314** [comment]
I am long for a more better dashcast. I think DashCast is a very nice tools for streaming. I believe you will quickly fix these errors in this tools. I will also search some other solution.

**Comment by JamesXu20150314** [comment]
I have tried your command. 

D:\wamp\www>dashcast -v test.mp4 -seg-dur 10000 -time-shift -1 -npts -low-delay

But I also will recieved this error by dash.all.js.

Uncaught TypeError: Cannot read property 'start' of undefined
 Video Element Error: MEDIA_ERR_DECODE

There is my MPD file that fixed by hand.

<?xml version="1.0"?>
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" mediaPresentationDuration="PT00H30M00.000S" minBufferTime="PT1.000000S"  type="static" profiles="urn:mpeg:dash:profile:full:2011">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>dashcast.mpd</Title>
 </ProgramInformation>
 <Period start="PT0H0M0.000S" id="P1">
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="false">
   <SegmentTemplate timescale="30" duration="300" media="$RepresentationID$_$Number$_gpac.m4s" startNumber="1" initialization="$RepresentationID$_init_gpac.mp4"/>
   <Representation id="v1" mimeType="video/mp4" codecs="avc1.64000d" width="320" height="240" frameRate="30" sar="1:1" startWithSAP="1" bandwidth="400000">
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>



 I also want to know what kind of MP4 file should I input. Could you give me some guideline.

**Comment by JamesXu20150314** [comment]
<?xml version="1.0"?>
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" mediaPresentationDuration="PT00H30M00.000S" minBufferTime="PT1.000000S"  type="static" profiles="urn:mpeg:dash:profile:full:2011">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>dashcast.mpd</Title>
 </ProgramInformation>
 <Period start="PT0H0M0.000S" id="P1">
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="false">
   <SegmentTemplate timescale="30" duration="300" media="$RepresentationID$_$Number$_gpac.m4s" startNumber="1" initialization="$RepresentationID$_init_gpac.mp4"/>
   <Representation id="v1" mimeType="video/mp4" codecs="avc1.64000d" width="320" height="240" frameRate="30" sar="1:1" startWithSAP="1" bandwidth="400000">
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>

**Comment by JamesXu20150314** [comment]
<?xml version="1.0"?>
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" mediaPresentationDuration="PT00H30M00.000S" 
minBufferTime="PT1.000000S"  type="static" profiles="urn:mpeg:dash:profile:full:2011">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>dashcast.mpd</Title>
 </ProgramInformation>
 <Period start="PT0H0M0.000S" id="P1">
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="false">
   <SegmentTemplate timescale="30" duration="300" 
media="$RepresentationID$_$Number$_gpac.m4s" startNumber="1"
 initialization="$RepresentationID$_init_gpac.mp4"/>
   <Representation id="v1" mimeType="video/mp4" codecs="avc1.64000d" width="320" height="240" 
frameRate="30" sar="1:1" startWithSAP="1" bandwidth="400000">
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>

**Comment by cconcolato** [comment]
When the error is `MEDIA_ERR_DECODE`, it means the error is not in the MPD, but in the media data. You should report what `chrome://media-internals` says.

**Comment by cconcolato** [comment]
If you try this [Sintel file](https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4), with the following command line, it should work:
```
dashcast -av ../sintel_trailer-480p.mp4 -seg-dur 10000 -time-shift -1 -npts -gop 25 -low-delay
```
The only issue is an audio resampling problem, pending resolution of #249.

As a recommendation, the input audio should be stereo@44100Hz for the moment. For the video, there should be no restriction (that I know of ...).

**Comment by JamesXu20150314** [comment]
ok. Thank you very much.
Could you give me some tips for configuring DashCast in windows7 64bit.
Whether I only need run the gpac-0.5.2-DEV-rev625-g1f8466a-master-x64.exe,.but if I do this, is that means the configure is automatic.

JamesXu

**Comment by cconcolato** [comment]
I don't understand the question. On Windows, DashCast is installed correctly with the installer. But, you have to configure DashCast every time you use it depending on your inputs and outputs. See the documentation [here](https://gpac.wp.mines-telecom.fr/dashcast/).

**Comment by JamesXu20150314** [comment]
Because I use the command
 dashcast -av sintel_trailer-480p.mp4 -seg-dur 10000 -time-shift -1 -npts -gop 25 -low-delay

But I also recieved the error report from dash.all.js 

Uncaught TypeError: Cannot read property 'start' of undefined
 Video Element Error: MEDIA_ERR_DECODE

Could you tell me the configuration of your windows. Are you use the Apache as a server, and add the dash.all.js as the src. The dash.all.js is the lastest version from Github. Can I use the 
dash.debug.js. (https://github.com/Dash-Industry-Forum/dash.js/tree/development/dist)

Here is my index.html
<!doctype html>
<html>
    <head>
        <title>Dash.js Rocks</title>
    </head>
    <body>
        <div>
            <video id="videoPlayer" controls="true"></video>
        </div>
        <script src="dash.all.js"></script>
        <script>
            (function(){
                var url = "http://localhost/output/dashcast.mpd";
                var context = new Dash.di.DashContext();
                var player = new MediaPlayer(context);
                player.startup();
                player.attachView(document.querySelector("#videoPlayer"));
                player.attachSource(url);
            })();
        </script>
    </body>
</html>

**Comment by JamesXu20150314** [comment]
My index.html like the guidline from https://github.com/Dash-Industry-Forum/dash.js

**Comment by JamesXu20150314** [comment]
Look forward to your answer.

JamesXu

**Comment by JamesXu20150314** [comment]
Looking forward to your answer.

JamesXu

**Comment by JamesXu20150314** [comment]
Thank you very much. I know that I must remove the dashcast.conf.
I am so happy that you can help me.

**Comment by JamesXu20150314** [comment]
Could you try to the option of '-live', I can't get right number of the segment.
My command is 

D:\wamp\www>DashCast -vf dshow  -vres 1280x720 -vfr 24 -v video="screen-capture-recorder" -live -npts  -low-delay -mpd-refresh 2

Here is a strange error.

**Comment by cconcolato** [comment]
Please report issues more precisely. Also, if the error is with dash.js, please file issues there. I'm closing this issue as the provided command line with the example works with dash.js.
