### ISSUE TITLE
How to burn subtitle in simplified Chinese into a video?

### ISSUE THREAD

**Issue by zydjohnHotmail** [gpac/gpac#2215]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hello:
I have one video without subtitle, its name: 13864_en.mp4; I have one English subtitle in SRT format: 13864_en.srt; I have yet another Chinese subtitle in SRT format: 13864_cn.srt.
I can make a video with English subtitle with the following simple command:
mp4box -add 13864_en.srt:hdlr=sbtl:lang=eng 13864_en.mp4 -out 13864_English.mp4
But when I tried to make a video with Chinese subtitle, none of my commands works.
The following is the log:

D:\Videos\Youtube>mp4box -for-test -add 13864_en.mp4#video -add '13864_cn.srt:lang=zh-Hans:name=Mandarin (Simplified)' -out 13864Chinese.mp4
IsoMedia import 13864_en.mp4 - track ID 1 - Video (size 1280 x 720)
[Importer] Cannot load filter for input file "'13864_cn.srt"
Failure while importing media: Requested URL is not valid or cannot be found
Error importing '13864_cn.srt:lang=zh-Hans:name=Mandarin: Requested URL is not valid or cannot be found

D:\Videos\Youtube>mp4box -for-test -add 13864_en.mp4#video -add '13864_cn.srt:lang=zh-Hans' -out 13864Chinese.mp4
Broken argument specifier or file name missing - check usage with -h

D:\Videos\Youtube>mp4box -for-test -add 13864_en.mp4#video -add '13864_cn.srt:lang=zh-CN' -out 13864Chinese.mp4
Broken argument specifier or file name missing - check usage with -h

D:\Videos\Youtube>mp4box -for-test -add 13864_en.mp4#video -add '13864_cn.srt:lang=zh-TW' -out 13864Chinese.mp4
Broken argument specifier or file name missing - check usage with -h

D:\Videos\Youtube>dir 13864*
 Volume in drive D is SATABackup
 Volume Serial Number is 4425-E62C

 Directory of D:\Videos\Youtube

07/02/2022  01:52 PM         8,204,487 13864Chinese.mp4
07/02/2022  01:32 PM         8,204,323 13864EN720P.mp4
07/02/2022  10:32 AM               122 13864_cn.srt
06/30/2022  01:45 PM         8,219,623 13864_en.mp4
06/30/2022  01:55 PM               136 13864_en.srt
               5 File(s)     24,628,691 bytes
               0 Dir(s)  449,866,760,192 bytes free

D:\Videos\Youtube>type 13864_en.srt
1
0:00:00,00 --> 0:00:30,233
Zelensky published a video of a Russian cruise missile hitting the AMSTOR shopping center in Kremenchug

D:\Videos\Youtube>type 13864_cn.srt
1
0:00:00 --> 0:00:29
µ│¢Þ┐×µû»Õƒ║ÕÅæÕ©âõ║åõ©Çµ«Áõ┐äþ¢ùµû»ÕÀíÞê¬Õ»╝Õ╝╣Õç╗õ©¡ÕàïÕêùÚù¿õ©ÿµá╝ AMSTOR Þ┤¡þë®õ©¡Õ┐âþÜäÞºåÚóæ
D:\Videos\Youtube>mp4box -add 13864_en.srt:hdlr=sbtl:lang=eng 13864_en.mp4 -out 13864_English.mp4
Track Importing Timed Text - Text track 1280 x 720 font Serif (size 18) layer 0
0.500 secs Interleaving

D:\Videos\Youtube>dir 13864_English.mp4
 Volume in drive D is SATABackup
 Volume Serial Number is 4425-E62C

 Directory of D:\Videos\Youtube

07/02/2022  02:09 PM         8,204,342 13864_English.mp4
               1 File(s)      8,204,342 bytes
               0 Dir(s)  449,858,551,808 bytes free

D:\Videos\Youtube>mp4box -add 13864_cn.srt:hdlr=sbtl:lang=zh-CN 13864_en.mp4 -out 13864_Chinese.mp4
Track Importing Timed Text - Text track 1280 x 720 font Serif (size 18) layer 0
[TXTIn] Error scanning SRT frame 1 timing
[TXTIn] Bad SRT formatting - expecting number got "µ│¢Þ┐×µû»Õƒ║ÕÅæÕ©âõ║åõ©Çµ«Áõ┐äþ¢ùµû»ÕÀíÞê¬Õ»╝Õ╝╣Õç╗õ©¡ÕàïÕêùÚù¿õ©ÿµá╝ AMSTOR Þ┤¡þë®õ©¡Õ┐âþÜäÞºåÚóæ"
0.500 secs Interleaving

D:\Videos\Youtube>mp4box -version
MP4Box - GPAC version 2.1-DEV-rev232-gfcaa01eb-master
(c) 2000-2022 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io

Please cite our work in your research:
        GPAC Filters: https://doi.org/10.1145/3339825.3394929
        GPAC: https://doi.org/10.1145/1291233.1291452

GPAC Configuration: (static configuration file)
Features: GPAC_CONFIG_WIN32 GPAC_64_BITS GPAC_MEMORY_TRACKING GPAC_HAS_SSL GPAC_MINIMAL_ODF GPAC_HAS_QJS GPAC_HAS_FAAD GPAC_HAS_MAD GPAC_HAS_LIBA52 GPAC_HAS_JPEG GPAC_HAS_PNG GPAC_HAS_FFMPEG GPAC_HAS_OPENSVC GPAC_HAS_JP2 GPAC_HAS_OPENHEVC GPAC_HAS_THEORA GPAC_HAS_VORBIS GPAC_HAS_XVID GPAC_HAS_GLU

D:\Videos\Youtube>

Please advise on how to make burn Chinese subtitle into a .MP4 format video. I am using Windows 10 version 21H2, MP4box latest version: version 2.1-DEV-rev232-gfcaa01eb-master
Thanks,

**Comment by jeanlf** [comment]
could you upload your sample SRT files ?

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply, I did some testing, your code works.  I think the error was made by some script which didn't produce SRT file with correct time format.
However, there is another issue for using the above command, the command generate a video with default Chinese font, which I don't know what font it is, since I am using English version of Windows 10.
I have installed one Chinese font in Windows, its font name is: LiSu, use ffmpeg, I can burn video with Chinese subtitle using specific font and style, like the following:
ffmpeg -i vid.mp4 -filter_complex "subtitles=subs_ch.srt:force_style='Fontname=Lisu,Fontsize=12'" -c:a copy vid_Chinese.mp4

Let me know if I can use mp4box to set specific Chinese font name and size just like ffmpeg to burn subtitle into one mp4 file.
Thanks,

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply, but setting font seems not working.
You can see the following pictures: the first one is the video with SRT generated by FFMEPG,  the second one was generated by MP4Box command like:
mp4box -add video_cn.srt:lang=zh-CN:font=LiSu video.mp4 -out mp4box.mp4 

But look carefully you can see the fonts are different, if you see font difference like TimesNewRoman and Franklin Gothic, then you will understand that Chinese fonts look totally different in the two pictures.
![FFMPEGLisuSRT](https://user-images.githubusercontent.com/45263518/179817649-5093ff98-1230-466b-bd30-0298074433ea.png)
![MP4BoxLisuSRT](https://user-images.githubusercontent.com/45263518/179817680-aba4092f-f7fc-4414-8147-8213eb678258.png)

**Comment by jeanlf** [comment]
you are correct, :font and :size are currently broken in mp4box, you need to use global options of the [txtin](https://github.com/gpac/gpac/wiki/txtin) filter, i.e. `--fontname=Lisu`

I'll patch this asap

**Comment by zydjohnHotmail** [comment]
Thanks, let me know when done!

**Comment by zydjohnHotmail** [comment]
Hello:
If you fix the issue, let me know how I can get the update?
