### ISSUE TITLE
DD+ Atmos not working on Apple TV

### ISSUE THREAD

**Issue by wezen-dev** [gpac/gpac#2217]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Dolby vision profile 5 is working great on Apple TV but Dolby Atmos is recognized as DD+ only. If I use mp4muxer Dolby Atmos works. This can be reproduced demuxing any mkv with FFMPEG and muxing it with mp4box.

**Comment by jeanlf** [comment]
could you please upload a sample file (working and not working) so that we can have a look at the issue?

**Comment by wezen-dev** [comment]
Of course! Here is the link with the original mkv, the mp4muxer and mp4box mux and the Apple TV screenshoots.
https://www.dropbox.com/sh/vbqsj3ntgnguqyp/AABtRmjcwBT-ERgi-66lZ2eca?dl=0

**Comment by jeanlf** [comment]
We don't support EC3+Atmos yet. Before looking into that in more details, could you do the following test: with an hex editor, insert `0110` (as hex) at the end of the `dec3` box (for your test file, that means inserting after the bytes `1800200F00` located after `dec3`), and check if the file is recognized as atmos ?

**Comment by akash329d** [comment]
@jeanlf Inserting bytes with a hex editor seems to break the file but that should be all thats needed to accomplish this. More details on how subler did it here as well: https://bitbucket.org/galad87/subler/issues/451/support-for-new-tags-hdr-4k-dolby-vision

**Comment by sw5163** [comment]
If this can help, 
`Complexity index : 16` in media info can be recognized by Apple as atmos
`Complexity index : Not present / 16` can't

`mp4muxer -i atmos.ec3 -o atmos.mp4` will fix/restore that `Complexity index` field.
`ffmpeg -i atmos.mp4 -c copy` will break it.
`mp4box -add atmos.mp4` will break it.

**Comment by jeanlf** [comment]
Thanks for the files and links. This should now be supported:
- remux/dashing
- eac3+atmos import

Could you cross-check ?

**Comment by akash329d** [comment]
@jeanlf Just cross-checked, and confirmed working on my Macbook, thanks! (Tested demuxing the mkv and creating an mp4 using mp4box and atmos is successfully detected). Is there an easier way to convert from mkv -> mp4 without demuxing with ffmpeg first? When running `mp4box -info sample.mkv` I get no tracks.

**Comment by jeanlf** [comment]
> Is there an easier way to convert from mkv -> mp4 without demuxing with ffmpeg first?

If you have a gpac build with ffmpeg support, you can import mkv files as usual (`-add src.mkv`).

I also added an option in MP4Box to update/force/remove the atmos extension signaling.
To drop it
`MP4Box -add self#audio:dlba=no file.mp4`

To rescan from first sample
`MP4Box -add self#audio:dlba=auto file.mp4`

To force it with a complexity type level of 10
`MP4Box -add self#audio:dlba=10 file.mp4`

Option can also be used when importing (e.g. `-add audio.ec3:dlba=10 ...`)

**Comment by sw5163** [comment]
Sorry to bother, I've tried the `MP4Box - GPAC version 2.1-DEV-rev314-g360b380b-master` build,
5.1 atmos eac3 file remuxing is perfectly fine, it's a great work!

However, it fails to remux the 7.1 atmos eac3 within [00003.m2ts](https://drive.google.com/drive/folders/1E4Go5zLiR4LlMiT8GQTJxxF22-4q1qTe?usp=sharing)
My above post is using the 2.0 main release and it results in a playable yet no atmos file.

When using the latest build, it gives a lot of error:
`ffmpeg -i 00003.m2ts -map 0:4 -c copy atmos.eac3`
`mp4box -add atmos.eac3 -new test.mp4`
![image](https://user-images.githubusercontent.com/108165384/191326799-f619cdba-1f13-47f4-addf-4492ac80e514.png)
But it's not a big deal since there isn't really any 7.1 atmos eac3 release.

**Comment by jeanlf** [comment]
Thanks for the TS, quite useful ! This should now be fixed, including TS import for EAC3 and TrueHD

**Comment by sw5163** [comment]
It helps a lot that the latest mp4box can import from m2ts now!
The 7.1 atmos eac3 is also showing proper 8 channel in windows player!
Many thanks for the great project!

**Comment by mpeleshenko** [comment]
> If you have a gpac build with ffmpeg support

@jeanlf Is there anywhere I can get such a build for Windows 10/Server 2019?

Or are there any steps to include it in a build? https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Windows doesn't seem to cover ffmpeg. It sure would simplify thing to directly add .mkv in mp4box without needing explicit ffmpeg extracts of video, audio, subs.

**Comment by jeanlf** [comment]
> Is there anywhere I can get such a build for Windows 10/Server 2019?

check https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/

The windows guide includes the full setup (including libav* support), see https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Windows#full-gpac-build

However you need the full build for mkv support, mp4box-mini builds do not include ffmpeg support and we rely on libavformat for mkv.

**Comment by mpeleshenko** [comment]
> > Is there anywhere I can get such a build for Windows 10/Server 2019?
> 
> check https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/
> 
> The windows guide includes the full setup (including libav* support), see https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Windows#full-gpac-build
> 
> However you need the full build for mkv support, mp4box-mini builds do not include ffmpeg support and we rely on libavformat for mkv.

Ahh, it seems I'm running into a crash when trying mp4box -info sample.mkv:
```
Faulting application name: mp4box.exe, version: 0.0.0.0, time stamp: 0x632c6f60
Faulting module name: avutil-57.dll, version: 57.17.100.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x000000000000d797
Faulting process id: 0x5354
Faulting application start time: 0x01d8d1cd6e812f8e
Faulting application path: C:\Program Files\GPAC\mp4box.exe
Faulting module path: C:\Program Files\GPAC\avutil-57.dll
```
I'll try to open a separate issue in some time once I cut a sample file out.
