### ISSUE TITLE
Long path name error with newer versions (MP4Box)

### ISSUE THREAD

**Issue by jlw4049** [gpac/gpac#2226]
Old build that works correctly
`MP4Box - GPAC version 1.1.0-DEV-rev1161-g2dfbf0c7a-master`

Newest build I've tried
`MP4Box - GPAC version 2.1-DEV-rev243-gf87b12b32-master`

Example long file path/name
`"\\?\E:\Downloads\Rocky.Horror.Picture.Show.The.1975.BluRay.1080p.DTS-HD.MA.7.1.AVC.REMUX-xxxxxxx\Rocky.Horror.Picture.Show.The.1975.BluRay.1080p.DTS-HD.MA.7.1.AVC.REMUX-xxxxxxLONGER123_temp\Rocky.Horror.Picture.Show.The.1975.BluRay.1080p.DTS-HD.MA.7.1.AVC.REMUX-xxxxxxLONGER123_chapters.txt"`

**Error:**
When muxing long filenames on newer versions of mp4box, it displays an error such as this during muxing
`Track Importing MPEG-4 AVC - Width 1792 Height 1080 FPS 96000/4004 Error: Requested URL is not valid or cannot be found`

I do understand the pathname is very long. However, I figured since the older versions had no issues with this, maybe it's something you could look into?

Thanks!!

**Comment by jeanlf** [comment]
strange, works here on my win10 VM.
Do you have [long paths enabled](https://www.thewindowsclub.com/how-to-enable-or-disable-win32-long-paths-in-windows-11-10) on your machine ?

**Comment by jeanlf** [comment]
could you share your windows version info ?

**Comment by jeanlf** [comment]
also your faulty command line ?

**Comment by jlw4049** [comment]
> could you share your windows version info ?

Windows 10 Pro 10.0.19044 Build 19044

**Comment by jlw4049** [comment]
> also your faulty command line ?

`"Apps\mp4box\MP4Box.exe" -add "E:/Downloads/Lemony.Snickets.A.Series.of.Unfortunate.Events.2004.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR/Lemony.Snickets.A.Series.of.Unfortunate.Events.2004.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR_temp/Lemony.Snickets.A.Series.of.Unfortunate.Events.2004.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR_new_out.h264#1:lang=und:fps=23.976:ID=1" -add "E:/Downloads/Lemony.Snickets.A.Series.of.Unfortunate.Events.2004.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR/Lemony.Snickets.A.Series.of.Unfortunate.Events.2004.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR_temp/Lemony.Snickets.A.Series.of.Unfortunate.Events.2004.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR_chapters.txt:fps=23.976" -new "E:\Downloads\Lemony.Snickets.A.Series.of.Unfortunate.Events.2004.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR\Lemony.Snickets.A.Series.of.Unfortunate.Events.2004.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR_temp\Lemony.Snickets.A.Series.of.Unfortunate.Events.2004.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR_new_out.muxed_output.mp4"`

**Comment by jlw4049** [comment]
![image](https://user-images.githubusercontent.com/48299282/180001522-e03614ce-4237-45d4-b9a0-350015109d5c.png)

**Comment by jeanlf** [comment]
with latest master (nothing changed except some potential bug with UNC path), simple h264 and srt streams in cmd.exe:

```
MP4Box -add X:/Downloads/Lemony.Snickets.A.Series.of.Unfortunate.Events.2004.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR/Lemony.Snickets.A.Series.of.Unfortunate.Events.2004.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR_temp/Lemony.Snickets.A.Series.of.Unfortunate.Events.2004.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR_new_out.h264#1:lang=und:fps=23.976:ID=1 

-add X:/Downloads/Lemony.Snickets.A.Series.of.Unfortunate.Events.2004.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR/Lemony.Snickets.A.Series.of.Unfortunate.Events.2004.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR_temp/Lemony.Snickets.A.Series.of.Unfortunate.Events.2004.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR_chapters.srt:fps=23.976

-new X:\Downloads\Lemony.Snickets.A.Series.of.Unfortunate.Events.2004.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR\Lemony.Snickets.A.Series.of.Unfortunate.Events.2004.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR_temp\Lemony.Snickets.A.Series.of.Unfortunate.Events.2004.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR_new_out.muxed_output.mp4

[AVC|H264] Possible Variable Frame Rate: VUI "fixed_frame_rate_flag" absent
Track Importing MPEG-4 AVC - Width 120 Height 96 FPS 23976/1000 SAR 1/1
OpenGOP detected - adjusting file brand
AVC|H264 Import results: 250 samples (281 NALUs) - Slices: 11 I 70 P 170 B - 10 SEI - 1 IDR - 0 CRA
AVC|H264 Stream uses forward prediction - stream CTS offset: 3 frames
AVC|H264 Max NALU size is 1568 - stream could be optimized by setting nal_length=2
Track Importing Timed Text - Text track 120 x 96 font Serif (size 18) layer 0
Saving X:\Downloads\Lemony.Snickets.A.Series.of.Unfortunate.Events.2004.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR\Lemony.Snickets.A.Series.of.Unfortunate.Events.2004.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR_temp\Lemony.Snickets.A.Series.of.Unfortunate.Events.2004.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR_new_out.muxed_output.mp4: 0.500 secs Interleaving
```

no problem, I even tried switching `\`and `/` same result.

you confirm your command runs fine if shorter path ?

**Comment by jlw4049** [comment]
I rebuilt with the latest git master. Can confirm it doesn't work with the long path name.

**Comment by aureliendavid** [comment]
ok we've had a similar discussion at the time when we implemented long path support in mp4box (with patman and stax76): https://github.com/gpac/gpac/issues/1589 

one issue is that our official builds are made with visual studio, and these builds have long path support activated (using an xml manifest)

then we added the feature for custom mingw builds https://github.com/gpac/gpac/commit/39a078f7ff8e27b3dfec86b78f139258251c519b

but there are no standard mingw build so it will probably depend on how you build it

I don't have much information about @patman86 builds, except that his configure is "--static-mp4box --use-zlib=no" and he uses mingw, but I don't think he made actual changes to the code for it to work 

can you provide more detail on how you build the latest master? (which os, compiler, command line and all that?)

**Comment by jlw4049** [comment]
Currently I follow this guide here for windows

https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Windows

I then run this command 
`msbuild.exe gpac.sln /maxcpucount /t:Rebuild /p:Configuration="Release - MP4Box_only" /p:Platform=x64 /p:PlatformToolset=v142 /p:WindowsTargetPlatformVersion=10.0.18362.0`

via `Visual Studio 2019 Developer Command Prompt v16.7.5`

**Comment by aureliendavid** [comment]
well you are actually correct, it is not activated on the mini-build (mp4box only) in visual studio, I don't know how that happened

I'm doing some tests and I'll push a fix after that, but thanks for catching that

**Comment by aureliendavid** [comment]
@jlw4049 : can you retry with latest master? I think it should be ok now

in any case thanks for the report

**Comment by jlw4049** [comment]
Problem is solved in the latest master! Thanks very much!
