### ISSUE TITLE
how to call python api(session.http_bitrate )

### ISSUE THREAD

**Issue by a23232390** [gpac/gpac#2227]
Excuse me, I want to ask how to call [session.http_bitrate](https://doxygen.gpac.io/classpython_1_1libgpac_1_1libgpac_1_1_filter_session.html#a31223012cba8ee5207e7556a60dce1cc) on python code
I am referring Advanced example (https://github.com/gpac/gpac/wiki/python#advanced-example)

**Comment by jeanlf** [comment]
it's a property of the filter session you created. Possible usage using async run:

```
fs = gpac.FilterSession(gpac.GF_FS_FLAG_NON_BLOCKING)
f1 = fs.load_src(URL)
f2 = fs.load("vout")
while True:
	#call session
	fs.run()

	#print current rate
	print('Current http rate ' + str(fs.http_bitrate) )

	#if last task, GPAC session is done
	if fs.last_task:
		break
```
