### ISSUE TITLE
Should i change first_IV with clearkey encryption ?

### ISSUE THREAD

**Issue by Eelisland** [gpac/gpac#2228]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I'm able to encrypt successfully mp4 with this drm.xml file

```
<GPACDRM type="CENC AES-CTR">
  <DRMInfo type="pssh" version="1">
    <!-- ?? this indicates the PSSH SystemID ?? -->
    <BS ID128="1077efecc0b24d02ace33c1e52e2fb4b"/>
    <!-- ?? this indicates the PSSH number of keys (version 1), on 32 bits ?? -->
    <BS bits="32" value="1"/>
    <!-- KID -->
    <BS ID128="e76cacfd3ecda68a76f28dc5d41c0e19"/>
  </DRMInfo>
    <!--
    IV_size : is the size in bytes of the Initialization Vector. It should be 0 (if track is not encrypted i.e the IsEncrypted flag is 0x0), 8 or 16. When not set, guessed from the size of the first_IV attribute.
    first_IV : is the first Initialization Vector used for this track. If the scheme type uses constant IV and constant_IV -->
  <CrypTrack IV_size="8" first_IV="0x603f39bfdb3d9799" isEncrypted="1" saiSavedBox="senc" trackID="1">
    <!-- KID with 0x before -->                         <!-- KEY with 0x before -->
    <key KID="0xe76cacfd3ecda68a76f28dc5d41c0e19" value="0x034482e9652d9510d6b91e1b60e601b2"/>
  </CrypTrack>
</GPACDRM>
```
I don't understand what first_IV is for and if i should edit this value ?
Also can anyone confirm if my comments with ?? are right ?

Thanks. 

note: this two pages helped me to generate keys
[Link 1](https://github.com/Dash-Industry-Forum/dash.js/wiki/Generate-MPEG-DASH-content-encrypted-with-MPEG-CENC-ClearKey)
[Link 2](https://ahelpme.com/software/drm/mpeg-dash-and-clearkey-cenc-drm-encryption-with-nginx-bento4-and-dashjs-under-centos-8/)

**Comment by rbouqueau** [comment]
This is the AES initialization vector (IV). This is usually an external parameter (e.g. used by the key provider to sign requests or simply tell you about the AES context).

**Comment by jeanlf** [comment]
The first IV is supposed to be a random number, so yes you can change it. For more info, check CBC and CTR modes for AES (https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation)


For more details on the XML syntax, especially the formatting of the PSSH box, check https://github.com/gpac/gpac/wiki/Common-Encryption
