### ISSUE TITLE
Website: Nightly Builds are not "compatible with OS X version 10.7" (and some above) anymore

### ISSUE THREAD

**Issue by the-real-tokai** [gpac/gpac#2229]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my iss…[cut]

**Issue**

When downloading a nightly build of GPAC from this link https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/ it states on that very site that the versions for OS X (or macOS how they call it now) are compatible "with 10.7 and above". This no longer seems to be a case. 

Downloading the latest version and installing it on Mac OS X 10.10.5 (Yosemite) results in an application bundle that's blocked out in Finder (with a stop symbol across the icon) and running the contained binaries directly from Terminal results in following issue:

```
$ /Applications/GPAC.app/Contents/MacOS/gpac --help
dyld: Library not loaded: /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
  Referenced from: /Applications/GPAC.app/Contents/MacOS/./lib/libavdevice.58.dylib
  Reason: image not found
Trace/BPT trap: 5
```

With how badly the OS X ecosystem works regarding backwards compatibility you're probably no longer be able to fix the package for older systems (albeit this would be appreciated), so an update of the information of the website seems to be reasonable as a fix.

**Comment by jeanlf** [comment]
Thanks for the report. @aureliendavid I think we could try to make an "alt" OSX build with a basic ffmpeg support (no avdevice, and maybe without codecs using videotoolbox), what do you think ?

**Comment by the-real-tokai** [comment]
@aureliendavid I tried a very basic build of the latest release version (I'm afraid setting up all the dependencies would take me a week otherwise doing it all manually, lib after lib. Albeit I have a lot of them, but not in a standard path. I'm not sure how to tweak the particular configure script/ setup to look for things there. :D ). I only encountered a single breaking issue:

```
…
  CC quickjs/quickjs-libc.c
quickjs/quickjs-libc.c:2058:5: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]
    clock_gettime(CLOCK_MONOTONIC, &ts);
    ^
quickjs/quickjs-libc.c:2058:19: error: use of undeclared identifier 'CLOCK_MONOTONIC'
    clock_gettime(CLOCK_MONOTONIC, &ts);
                  ^
1 warning and 1 error generated.
make[1]: *** [quickjs/quickjs-libc.o] Error 1
make: *** [all] Error 2
```

It seems that `clock_gettime()` is only available starting with 10.12 (Sierra), at least according to information here: https://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x .

I uncommented the `defined(__APPLE__)` in line 2054 of quickjs-libc.c like this: `#if defined(__linux__) /* || defined(__APPLE__) */` so it would use the generic fallback case and the build went fine afterwards. I guess `defined(__APPLE__)` could be extended with an extra version check.

```
$ ./configure --static-mp4box
--static-mp4box deprecated, use --static-bin instead

** System Configuration
Install prefix: /usr/local
Source path: /Volumes/Temporary/Downloads/gpac-2.0.0
C   compiler: gcc
C++ compiler: g++
make: make
CPU: x86_64
Big Endian: no

** GPAC 2.0 rev Core Configuration **
Static binaries enabled
debug version: no
GProf enabled: no
Memory tracking enabled: no
Sanitizer enabled: no
Fixed-Point Version: no
IPV6 Support: no
QuickJS Support: yes (qjslibc yes)

** Detected libraries **
zlib: system
OpenGL support: no
TinyGL support: no
OpenSSL support: no
OSS Audio: no
ALSA Audio: no
Jack Audio: no
Pulse Audio: no
DirectFB: no
SDL: no
FreeType: system
JPEG: system
OpenJPEG: no
PNG: system
MAD: local
FAAD: no
XVID: system
FFMPEG: no
LZMA: no
Xiph OGG: no
Platinum UPnP: no
A52 (AC3): no
OpenSVCDecoder: no
OpenHEVCDecoder: no
Freenect: no
nghttp2: system

Creating config.mak
Check config.log for detection failures

Warning: static binaries on OSX cannot remove all dependendencies to system libraries

Done - type 'make help' for make info, 'make' to build

$ make
…

$ otool -L ./bin/gcc/MP4Box 
./bin/gcc/MP4Box:
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/local/lib/libjpeg.8.dylib (compatibility version 13.0.0, current version 13.0.0)
	/usr/local/opt/libpng/lib/libpng16.16.dylib (compatibility version 42.0.0, current version 42.0.0)
	/usr/local/opt/freetype/lib/libfreetype.6.dylib (compatibility version 19.0.0, current version 19.6.0)
	/usr/local/lib/libmad.0.dylib (compatibility version 3.0.0, current version 3.1.0)
	/usr/local/lib/libnghttp2.14.dylib (compatibility version 34.0.0, current version 34.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

$ ./bin/gcc/MP4Box -version
MP4Box - GPAC version 2.0-revrelease
(c) 2000-2022 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io
	MINI build (encoders, decoders, audio and video output disabled)

Please cite our work in your research:
	GPAC Filters: https://doi.org/10.1145/3339825.3394929
	GPAC: https://doi.org/10.1145/1291233.1291452

GPAC Configuration: --static-mp4box
Features: GPAC_CONFIG_DARWIN GPAC_64_BITS GPAC_HAS_SOCK_UN GPAC_MINIMAL_ODF GPAC_HAS_QJS GPAC_HAS_FREETYPE GPAC_HAS_MAD GPAC_HAS_JPEG GPAC_HAS_PNG GPAC_HAS_XVID  GPAC_DISABLE_3D 
```

That's what I ended up with. Not sure how useful it is like that (I do not know anything about gpac/ MP4box yet. :) )

**Note:** the linked build guide probably should be updated to show `--static-bin` instead `--static-mp4box` to avoid the deprecation warning.

**Comment by aureliendavid** [comment]
Hi, 

Thanks for your investigations, it's very helpful. 

I finally managed to set up a yosemite machine. 

For the basic build, I patched quickjs on the issue you found (by checking if `CLOCK_MONOTONIC` is defined as a clue about the availability of `clock_gettime()`). 

I also needed a patch to be able to build on systems without `pkg-config` (done in 3e04caf2bf968)

Now for the full build with all the dependencies, I can't install homebrew on a system this old. However macports has all the necessary packages for the gpac build. 

I updated the docs with macports instructions at https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-OSX#set-up

(I also changed --static-mp4box to --static-bin as you mentioned)

**Comment by aureliendavid** [comment]
I'm closing this, as of now: 
 - the download page on gpac.io mentions that installers are for 10.11 and up
 - following the build guide on the wiki will now work at least down to 10.7 

If we see a real demand for old macos installers we might revisit extending the compatibility of our builds, but for now I think it's sensible for keep it that way.

**Comment by the-real-tokai** [comment]
@aureliendavid Works well enough for me. 👍 Thank you very much for the support!
