### ISSUE TITLE
Problems building on fedora with --static-bin

### ISSUE THREAD

**Issue by adaviding** [gpac/gpac#2234]
Your build scripts are a bit complicated and I am hoping for some guidance.  Here is a Dockerfile which shows exactly how I am building gpac:

```Dockerfile
FROM fedora:29

RUN dnf group install -y "C Development Tools and Libraries" "Development Tools"
RUN dnf install -y zlib-devel

RUN mkdir -p /var/repo
WORKDIR /var/repo
RUN git clone https://github.com/gpac/gpac.git -b v2.0.0

WORKDIR /var/repo/gpac
RUN ./configure --static-bin
RUN make
```

Basically I cannot get past this error.

```
make[2]: Entering directory '/var/repo/gpac/applications/gpac'
  CC gpac.c
  CC compositor_tools.c
  CC gpac_help.c
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
```

I am **guessing** that it is trying to static link with some `glibc` libraries which is generally discouraged (for good reasons).  You probably want to be linking dynamically to all of `glibc`, then statically to everything else.  I wrestled with your build scripts for a couple hours and I couldn't figure it out.

Extra info:
* The fedora build succeeds when I remove `--static-bin`
* I tried 2 other branches of gpac:
  * `master` also has the error
  * `v1.0.1` does not have the error

**Comment by aureliendavid** [comment]
Hi, 

Thanks for the providing the dockerfile, it makes it way easier to reproduce the issues. 

I agree that the configure script can be a bit confusing, and my answer won't disprove that :)

The `--static-bin` option was created around v2.0 and this issue: https://github.com/gpac/gpac/issues/1685. It replaces the old `--static-mp4box` and builds both `gpac` and `mp4box` as **fully static binaries** (using the `-static` option of gcc - added here https://github.com/gpac/gpac/commit/75b879fc4e63ba26e76efddf1f74e029de94c9e1#diff-90d08e583c4c9c6f391b2ae90f819f600a6326928ea9512c9e0c6d98e9f29ac2R474). 

As such, they wil need the static glibc.  I get that static binaries are out of fashion and linking against static glibc is frowned upon, but some users want it so it exists. 

Now what you're describing is basically linking statically against `libgpac` only and allowing dynamic linking for system libs like libc, libm, etc.. Good news is, this option exists and is called `--static-build` (I know, name is not very clear).

From the `configure` help: 

```
  --static-build           link statically against libgpac but still allow dependencies to shared libraries (enable --static-modules)
  --static-bin             enable static linking of MP4Box and gpac only (enable --static-build), disable all libraries not linkable statically.
```

<hr> 

From there you have to options:

1. add `dnf install -y glibc-static zlib-static` to your Dockerfile and use `--static-bin`, it will produce fully static binaires: 

```
$ ldd bin/gcc/MP4Box
        not a dynamic executable
$ file bin/gcc/MP4Box
bin/gcc/MP4Box: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=51a689a72b5b7b70f96d12194960f93d6e304af5, for GNU/Linux 3.2.0, with debug_info, not stripped
```

2. replace `--static-bin` with `--static-build` and it will link statically with libgpac and dynamically with the rest: 

```
# ldd bin/gcc/MP4Box 
        linux-vdso.so.1 (0x00007ffd01d3b000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f8a1d595000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f8a1d57b000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f8a1d55a000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f8a1d554000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f8a1d38e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8a1d721000)
# file bin/gcc/MP4Box 
bin/gcc/MP4Box: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=95fee2884ae9a6aab7f45eefed8a3553d0afa87a, not stripped
```

**Comment by adaviding** [comment]
Thanks for your help.  I will close the issue because this unblocks me.
