### ISSUE TITLE
[Question] How to insert my website url to M3U8 and MPD files ?

### ISSUE THREAD

**Issue by AhmedAbouelkher** [gpac/gpac#2235]
This is not an issue, just a quick question.
I have local videos which are considered different qualities for the same video, and I want to package them in HLS and Dash.
I was able to successfully generate both of them but without any URL to host from.

I read your wiki and tried to do so, but I encountered issues and the m3u8 did not have the host URL

I saw
[DASH Low Latency](https://github.com/gpac/gpac/wiki/dash_low_latency)
[HLS Low Latency](https://github.com/gpac/gpac/wiki/llhls)

I suspect that the commands used in for example (DASH Low Latency) are for live video encoding

**Comment by rbouqueau** [comment]
By default the media content is accessed relatively to the MPD location. If you want to force an absolute URL, look for ```BaseURL```.

So if you can play your content locally, you will equally be able to play it from your own Web (http) server.

Please note that in some the examples GPAC embeds its own HTTP server: that's convenient for testing but indeed not suitable for production.

Do that answer your question?

**Comment by AhmedAbouelkher** [comment]
Thanks for your quick reply.

If you have any example for `BaseURL`, it will be amazing

**Comment by rbouqueau** [comment]
You can use github search capabilities. There is an example on [this page](https://github.com/gpac/gpac/wiki/dasher).

If this is still not clear, please let us know so that we can improve the documentation.

**Comment by AhmedAbouelkher** [comment]
> You can use github search capabilities. There is an example on [this page](https://github.com/gpac/gpac/wiki/dasher).
> 
> If this is still not clear, please let us know so that we can improve the documentation.

I tried to search and found this issue [#219](https://github.com/gpac/gpac/issues/219), But I can see that `baseUrl` doesn't work for `m3u8`

There are no clear implementation in the docs on how to add a `base URL` for both `dash` and `hls`

**Comment by jeanlf** [comment]
BaseURL is a DASH-specific construct typically used to provide alternate download URLs, there's no such thing in HLS (one would need to create as many variants as there are base URLs to mimic that)

Could you please give a detailed example of what your are trying to do ?

**Comment by AhmedAbouelkher** [comment]
> BaseURL is a DASH-specific construct typically used to provide alternate download URLs, there's no such thing in HLS (one would need to create as many variants as there are base URLs to mimic that)
> 
> Could you please give a detailed example of what you are trying to do?

I'm trying to build a VOD service that converts mp4 into (DASH and HLS) to be used with my mobile application video player.
I have a single quality video, say 1080p 100mp video, converted to multiple qualities and packaged using gpac to use.

I'm trying to stream the video quality segments which need a base URL to fetch from the server.

Still looking for the optimal way to stream my local HLS or DASH video from my server.

**Comment by jeanlf** [comment]
> I'm trying to stream the video quality segments which need a base URL to fetch from the server.

I don't inderstand why you need a dash baseURL for that, nor how you would use it. Why can't you host the produced m3u8/mpd on any http server (apache/node/gpac/...) ?

**Comment by AhmedAbouelkher** [comment]
> > I'm trying to stream the video quality segments which need a base URL to fetch from the server.
> 
> I don't inderstand why you need a dash baseURL for that, nor how you would use it. Why can't you host the produced m3u8/mpd on any http server (apache/node/gpac/...) ?

I'm still researching.

The issue I have currently is how to stream videos from the storage service to the serving service because the video files themselves do not live in the serving service.

**Comment by jeanlf** [comment]
That's a web server configuration question, not related to GPAC.
