### ISSUE TITLE
Below is my requirement:If I change my 360 degree view to any direction(right/left/up/down) while navigating, then is it possible to find out from the log files that there is a change in field of view(FoV)? If possible, then can you please guide me on how to extract the statements from the log which says that there is change in "field of view".

### ISSUE THREAD

**Issue by VinitaKasbeUcc** [gpac/gpac#2236]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
there is currently no logs for that, but the change of active areas for 360 is tracked/notified in compositor through the functions [gf_mo_hint_quality_degradation](https://github.com/gpac/gpac/blob/master/src/compositor/media_object.c#L1686) ,  [gf_mo_hint_visible_rect](gf_mo_hint_visible_rect) and [gf_mo_hint_gaze](https://github.com/gpac/gpac/blob/master/src/compositor/media_object.c#L1724)

The 3D camera updates are notified in [camera_changed](https://github.com/gpac/gpac/blob/master/src/compositor/navigate.c#L32) if you need to directly monitor the camera
