### ISSUE TITLE
Trimming with mp4box splitz moves forward instead of back at end point for low frame rate

### ISSUE THREAD

**Issue by msrdanov** [gpac/gpac#224]
I'm using the "splitz" option of mp4box to trim mp4 files.  From what I've seen so far, and how I interpret the documentation, the expected behavior is to adjust the end time backwards if needed.  I have files at varying frame rates, namely 30000/1001 (29.970fps), 15000/1001 (14.985fps) and 10000/1001 (9.990fps).  Whenever I specify an endpoint of "87", the files at 14.985fps and 29.97fps adjust correctly back to the previous point at 84.08 sec, however the file at 9.990fps moves forward to 87.09 sec.

The following example using big buck bunny encoded at the rates listed above illustrates the issue:

```
$ mp4box -splitz 15:87 in/bbb_9.990fps.mp4 -out out/bbb_9.990fps_splitz_15_87.mp4
Adjusting chunk start time to previous random access at 12.01 sec
Adjusting chunk end time to previous random access at 87.09 sec
Extracting chunk out/bbb_9.990fps_splitz_15_87.mp4 - duration 75.08s (12.01s->87.00s)
Warning: Edit list doesn't look like a track delay scheme - ignoring

$ mp4box -splitz 15:87 in/bbb_14.985fps.mp4 -out out/bbb_14.985fps_splitz_15_87.mp4
Adjusting chunk start time to previous random access at 12.01 sec
Adjusting chunk end time to previous random access at 84.08 sec
Extracting chunk out/bbb_14.985fps_splitz_15_87.mp4 - duration 72.07s (12.01s->87.00s)
Warning: Edit list doesn't look like a track delay scheme - ignoring

$ mp4box -splitz 15:87 in/bbb_29.970fps.mp4 -out out/bbb_29.970fps_splitz_15_87.mp4
Adjusting chunk start time to previous random access at 12.01 sec
Adjusting chunk end time to previous random access at 84.08 sec
Extracting chunk out/bbb_29.970fps_splitz_15_87.mp4 - duration 72.07s (12.01s->87.00s)
Warning: Edit list doesn't look like a track delay scheme - ignoring
```

Using an endpoint of 86 (or 88) moves backwards properly as do many other values.

Source and output files used in this example can be found at https://www.dropbox.com/s/4yj6iu19yeh3xei/mp4box-splitz-issue.zip?dl=0

I'm using the following version of mp4box under 64 bit windows 7 - MP4Box - GPAC version 0.5.2-DEV-rev575-geedd2f0-master

Please let me know if I can provide any additional information.  Thanks!

**Comment by rbouqueau** [comment]
@jeanlf I confirm that 'splitx' gives inconsistent results with edit lists in files. You cannot extract 0:10, then 10:20, then 20:30 (with RAPs on the according frames) and then stitch them again.

**Comment by jeanlf** [comment]
this should now be properly handled in latest git, thanks for the report
