### ISSUE TITLE
how to call python api(session.http_max_rate=VALUE )

### ISSUE THREAD

**Issue by a23232390** [gpac/gpac#2241]
Excuse me, I want to ask how to call [session.http_max_rate]on python code
I am referring Advanced example (https://github.com/gpac/gpac/wiki/python#advanced-example)
I want to test my ABS by changing the internet speed indefinitely

**Comment by jeanlf** [comment]
In that example, use `fs.http_max_rate = 1000000` to limit global http download rate to 1 mbits per second
