### ISSUE TITLE
new bitrate selection algorithm for 360-degree videos

### ISSUE THREAD

**Issue by binbinzhm** [gpac/gpac#2247]
Hello,
I am a researcher looking into 360 TILED videos and was looking for a good open source DASH implementation for my studies.
I want to set up new bandwidth prediction algorithm, viewpoint prediction algorithm, and bitrate selection algorithm for tiles. Do I need to modify the source code, or can it be done through JS?

**Comment by binbinzhm** [comment]
`import { Sys as sys } from 'gpaccore'

print("Hello GPAC !");

let all_filters = [];

//custom rate adaptation object
let dashin = {};
dashin.groups = [];

session.set_new_filter_fun( (f) => {
		print("new filter " + f.name);
		
		f.iname = "JS"+f.name;
		all_filters.push(f);

		//bind our custom rate adaptation !
		if (f.name == "dashin") {
			f.bind(dashin);
		}
} ); 

session.set_del_filter_fun( (f) => {
	print("delete filter " + f.iname);
	//print(JSON.stringify(f));
	let idx = all_filters.indexOf(f);
	if (idx>=0)
		all_filters.splice (idx, 1);
}); 

dashin.rate_adaptation = function (group, base_group, force_lower_complexity, stats)
{
	//print(`Getting called in custom algo ! group ${group} base_group ${base_group} force_lower_complexity ${force_lower_complexity}`);
	//print(group +  " " + base_group + " "+ 'Stats.buffer: ' + JSON.stringify(stats.buffer) + " " + stats.buffer_max);

    //print(JSON.stringify(this.groups[group].SRD))

	//always use lowest quality
	

	return 0;
}

dashin.new_group = function (group)
{
	//print("New group: " + JSON.stringify(group));
	//remember the group (adaptation set in dash)
	this.groups.push(group);
}

dashin.period_reset = function (type)
{
	print("Period reset type " + type);
	if (!type)
		this.groups = [];
}

dashin.download_monitor = function (group_idx, stats)
{
	return -1;
}

let f = session.add_filter("src=http://download.tsi.telecom-paristech.fr/gpac/SRD/tears_of_steal/tos_srd_hd.mpd");
session.add_filter("compositor");
let v_f = session.add_filter("vout");`

I want to modify dashin.rate_adaptation, but it can only return the bit rate of a certain tile.I want to decide for myself when and where to download the bitrate of the tile
and I want to implement bandwidth prediction algorithm

**Comment by binbinzhm** [comment]
maybe I need to modify this?
![image](https://user-images.githubusercontent.com/38529221/187337154-4f438d80-5d72-473e-bacc-fe3378fac836.png)

**Comment by jeanlf** [comment]
> I want to modify dashin.rate_adaptation, but it can only return the bit rate of a certain tile.I want to decide for myself when and where to download the bitrate of the tile

You cannot decide when/where to download a tile, the group (hence segment) scheduling is not configurable.

The rate adaptation callback is performed once all dependent groups are done, i.e. once all tiles are fetched for a given time. So you need to select the quality you want in dashin.rate_adaptation based on your desired goal and the global stats (typically total_rate on stats object passed in this callback)

**Comment by binbinzhm** [comment]
So the given time is the segment duration?

**Comment by binbinzhm** [comment]
thank you for your answer

**Comment by alstj908** [comment]
Hello, if you succeeded in implementing it, can I know the code? I beg you :)
