### ISSUE TITLE
[mp4box][cover tag] Failure while importing media

### ISSUE THREAD

**Issue by RobertoHN** [gpac/gpac#2249]
Hi! My name is Roberto.
I have installed this version that I got from [https://gpac.wp.imt.fr/downloads/](url)
```
MP4Box - GPAC version 2.0-rev0-g418db414-master
(c) 2000-2022 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io
```
OS: Windows 10 Home x64

I'm trying to add cover to mp4 files, so I am using the code in cmd as it fallows:
`mp4box -add cover=myfile.jpg "my_video.mp4"`

And I get this error:
> Failure while importing media: Requested URL is not valid or cannot be found
> Error importing cover=myfile.jpg: Requested URL is not valid or cannot be found

This jpg files is 409*545 px

Like a week ago, I did add cover to some video files with a older version of gpc, and it worked.
Today, I'm getting this issue, so I installed latest gpac version, but  same "Requested URL is not valid or cannot be found" error.

I will appreciate if someone help me out.

Roberto.

**Comment by aureliendavid** [comment]
hi, 

if i'm not mistaken the syntax to add a cover is 

```bash
MP4Box -itags cover=cover.jpg video.mp4

# or

MP4Box -add video.mp4 -itags cover=cover.jpg -new newvideo.mp4
```

**Comment by RobertoHN** [comment]
> hi,
> 
> if i'm not mistaken the syntax to add a cover is
> 
> ```shell
> MP4Box -itags cover=cover.jpg video.mp4
> 
> # or
> 
> MP4Box -add video.mp4 -itags cover=cover.jpg -new newvideo.mp4
> ```

I feel so dumb.
I have done this so many times and in a couple of days I forgot how to do it.
Thank you.
-itags is the answer.
