### ISSUE TITLE
gpac has problems reading from stdin

### ISSUE THREAD

**Issue by jnnks** [gpac/gpac#2256]
When using `cat input.ivf | gpac -i - vout` I get the following errors:
```
[IVF] Wrong frame size 1653761469
[IVF] Wrong frame size 1201015313
[IVF] Wrong frame size 694008384
[IVF] Wrong frame size 2555895191
[IVF] Wrong frame size 3525515593
[IVF] Wrong frame size 4081952536
[IVF] Wrong frame size 4244438912
[IVF] Wrong frame size 1216447311
[IVF] Wrong frame size 2265514515
session last process error BitStream Not Compliant
```

`gpac -i input.ivf vout` on the other hand works fine.
What can I do here?

____
Background: I want to repackage ivf frames coming from a tcp port and forward them to another tcp port as mp4.
This is one step on the way. If I am doing something completely wrong, please tell me :)

**Comment by jeanlf** [comment]
This was not working with ivf or av1, should now be fixed. Thanks for the report.
