### ISSUE TITLE
How to set the size of playback buffer?

### ISSUE THREAD

**Issue by phananh1010** [gpac/gpac#2260]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hello,

I am trying to set the buffer of the playback to 2 seconds using this command:
```
gpac httpin:src=http://localhost/dash/coaster2/coaster2_6x3.mpd dashin tileagg ffdec  inspect:buffer=2000:dur=5 -graph
```
However, it seems the playback buffer is overwritten by some configuration. The streaming session also hang. Here is the error: 

![image](https://user-images.githubusercontent.com/10344401/190489584-59901609-0884-4eb4-9f86-36e7fd5f29b6.png)

Setting buffer less than 1000 will resume the playback again. Can you please let me know a way to set playback buffer for the inspect filter?.

**Comment by jeanlf** [comment]
Indeed there was a bug with buffer level setup when using inspect as a sink, now fixed. Thanks for the report
