### ISSUE TITLE
Any way to generate an accurate list of supported video/audio input formats? 

### ISSUE THREAD

**Issue by jlw4049** [gpac/gpac#2262]
Reading the documentation it seems like it's based on how it's built. 

However, it's really hard to make out proper formats/extension that are allowed to be imported via mp4box. 

I know this isn't a big issue, just wondering! Thanks!

**Comment by jeanlf** [comment]
yes it is possible

Print all supported codecs in build: `gpac -hx codecs`
Print all supported formats in build: `gpac -hx formats` (latest master, used to be `gpac -h exts` but new version is more readable)
Print all supported protocols in build: `gpac -hx protocols` (latest master)

Same command with `-h` omits meta-filters (ffmpeg and co)

See `gpac -h`

**Comment by jlw4049** [comment]
I apologize as I was not clear with the my issue. 

I was wondering if this is possible with mp4box?
