### ISSUE TITLE
MP4Box -time reports 1 day earlier after update

### ISSUE THREAD

**Issue by dunha** [gpac/gpac#2263]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x ] I looked for a similar issue and couldn't find any.

tool: GPAC-2.1-DEV-rev273-g02437a478-master

The Created tag of my files has been set by the camera where the date had not been set.
I'm attempting to set the tag to the first date/time reported from the GPS using the 
```-time [tkID=]DAY/MONTH/YEAR-H:M:S: set movie or track creation time``` format

```mp4box -time 03/05/2022-16:05:40 video.MP4```

but the result from ```mp4box -info video.MP4```  is ```Created: GMT Mon May  2 08:05:40 2022```

Admittedly, the input is local time (GMT+8), which accounts for the time difference, but not the day. 
The docs are not clear if there some trickery that adjusts it to GMT. Am I doing it correctly?

**Comment by jeanlf** [comment]
Indeed. Now fixed, thanks for the report.
