### ISSUE TITLE
Any way to generate an accurate list of supported video/audio input formats for MP4Box?

### ISSUE THREAD

**Issue by jlw4049** [gpac/gpac#2265]
I posted this question here https://github.com/gpac/gpac/issues/2262 but I wasn't very clear.

I wanted to know if there was anyway to get all of the input extensions/formats that is supported by **Mp4Box**? 

Thanks!

**Comment by jeanlf** [comment]
They are exactly the same as the ones supported by the `gpac` application. Does this help ?

**Comment by jlw4049** [comment]
This looks like it will suffice. Thanks!
