### ISSUE TITLE
CBCS encryption not working on Firefox but Edge+Chrome ok (dashjs player)

### ISSUE THREAD

**Issue by Murmur** [gpac/gpac#2268]
**edit:** Using cbcs `tenc.default_constant_IV, default_constant_IV_size` atom fields fixed Firefox(widevine) playback, see my additinal comment. New test content for CBCS_1:9 pattern here.
https://refapp.hbbtv.org/dash/test_dashjs_wv.html?video=springcbcs2wv

Win10 Firefox cbcs test fails, what is the secret of Firefox cbcs encryption scheme? I also asked the same in dashjs slack but no answers yet. Win10 Edge(playready, cbcs1:9, cbcs0:0)=ok, Win10 Chrome(widevine, cbcs1:9, cbcs0:0)=ok, Android Chrome(widevine, cbcs1:9, cbcs0:0)=ok.  

Do gpac talents know more about the Firefox issue?

**CBCS_1:9 pattern (10% encrypt, 90% nocrypt)**
https://refapp.hbbtv.org/dash/test_dashjs_wv.html?video=llamacbcswv
https://refapp.hbbtv.org/dash/test_dashjs_wv.html?video=llamacbcs

**CBCS_0:0 pattern**
https://refapp.hbbtv.org/dash/test_dashjs_wv.html?video=llamacbcs2wv
https://refapp.hbbtv.org/dash/test_dashjs_wv.html?video=llamacbcs2

See drmxml examples here for video and audio tracks, audio is using a default settings without `crypt_,skip_` arguments.

**CBCS_1:9 drm.xml**
http://refapp.hbbtv.org/videos/00_llama_1080p_cbcs_v1/temp-gpacdrmvideo.xml 
http://refapp.hbbtv.org/videos/00_llama_1080p_cbcs_v1/temp-gpacdrmaudio.xml 
```
<?xml version="1.0" encoding="UTF-8" ?>
<GPACDRM type="CENC AES-CBC Pattern">
 ...clip...
<CrypTrack trackID="1" IsEncrypted="1" IV_size="16" first_IV="0x22ee7d4745d3a26a0100000000000002" saiSavedBox="senc" crypt_byte_block="1" skip_byte_block="9" >
  <key KID="0x43215678123412341234123412341236" value="0x12341234123412341234123412341236"/>
</CrypTrack>
</GPACDRM>
```

**CBCS_0:0 drm.xml**
http://refapp.hbbtv.org/videos/00_llama_1080p_cbcs_v2/temp-gpacdrmvideo.xml
http://refapp.hbbtv.org/videos/00_llama_1080p_cbcs_v2/temp-gpacdrmaudio.xml
```
<?xml version="1.0" encoding="UTF-8" ?>
<GPACDRM type="CENC AES-CBC Pattern">
   ...clip...
<CrypTrack trackID="1" IsEncrypted="1" IV_size="16" first_IV="0x22ee7d4745d3a26a0100000000000002" saiSavedBox="senc" crypt_byte_block="0" skip_byte_block="0" >
  <key KID="0x43215678123412341234123412341236" value="0x12341234123412341234123412341236"/>
</CrypTrack>
</GPACDRM>
```

This is mp4box cmdlines, `tfdt64bit, cmf2, noroll, segdur=8sec` flags. 
```
MP4Box -crypt "temp-gpacdrmvideo.xml" temp-v1.mp4 -out "drm/temp-v1.mp4"
MP4Box -crypt "temp-gpacdrmaudio.xml" temp-a1.mp4 -out "drm/temp-a1.mp4"

MP4Box -dash 384000 -frag 384000 -dash-scale 48000 -mem-frags -rap -profile dashavc264:live ^
  -profile-ext "urn:hbbtv:dash:profile:isoff-live:2012" -min-buffer 4000 ^
  -bs-switching no -sample-groups-traf -single-traf --tfdt64 --tfdt_traf --noroll=yes --cmaf=cmf2 ^
  -subsegs-per-sidx 0 ^
  -segment-name "$RepresentationID$/$Number$$Init=i$" -out manifest.mpd ^
  "temp-v1.mp4#trackID=1:id=v1:period=p0:dur=30" ^
  "temp-a1.mp4#trackID=1:id=a1:period=p0:dur=30"
```

**Comment by rbouqueau** [comment]
I haven't tested on Windows, but on Linux none of these play in both Firefox and Chromium. Could it be an EME or DRM issue more than a browser issue? What is the difference in the log between success and failure?

**Comment by jeanlf** [comment]
Are there any working example of cbcs for firefox available somewhere?

**Comment by Murmur** [comment]
@rbouqueau @jeanlf Googling found this mozilla bug report. I put links to my `cbcs1:9/cbcs0:0/cenc` test pages for reference. Maybe I and mp4box are not doing anything wrong about cbcs encryption. After all Chrome+Edge(win10,macos,android) is playing both cbcs tests fine.

No idea how active this ticket is as the original assignee developer is no longer working at Mozilla.
https://bugzilla.mozilla.org/show_bug.cgi?id=1759936
https://bugzilla.mozilla.org/show_bug.cgi?id=1492377

**Comment by Murmur** [comment]
@jeanlf  @rbouqueau I had to change gpacdrm.xml `first_IV -> constant_IV` and Firefox browser works. [Gpac drm ](https://github.com/gpac/gpac/wiki/Common-Encryption) do mention about the constantIv-firstIv but it does an automatic selection for HLS_SAES mode only?

I was given this comment in dashjs slack channel, `(@disneystreaming) Pretty sure the 'tenc' box is not setup correctly for cbcs -- you should be setting up the default_constant_iv, not the per_sample_iv`

https://refapp.hbbtv.org/dash/test_dashjs_wv.html?video=springcbcs2wv

**New, works "everywhere" also in Firefox browser**
```
<GPACDRM type="CENC AES-CBC Pattern">
...clip...
<CrypTrack trackID="1" IsEncrypted="1" constant_IV_size="16" constant_IV="0x22ee7d4745d3a26a0100000000000002" saiSavedBox="senc"   >
  <key KID="0x43215678123412341234123412341236" value="0x12341234123412341234123412341236"/>
</CrypTrack>
...clip...
</GPACDRM>
```

**Old, works "everywhere" but not in Firefox browser**, this is what is used for the traditional CENC-CTR mode.
```
<GPACDRM type="CENC AES-CBC Pattern">
...clip...
<CrypTrack trackID="1" IsEncrypted="1" IV_size="16" first_IV="0x22ee7d4745d3a26a0100000000000002" saiSavedBox="senc"   >
  <key KID="0x43215678123412341234123412341236" value="0x12341234123412341234123412341236"/>
</CrypTrack>
...clip...
</GPACDRM>
```

**Comment by jeanlf** [comment]
Indeed, we were allowing aes-cbc+pattern+per-sample IV for such a config, but given that there are no code points for this in CENC I just disabled that. Using "first_IV" or "constant_IV" is now the same for cbcs mode (doc updated).

Thanks for the analysis!
