### ISSUE TITLE
Latest Win32 build link doesn't install

### ISSUE THREAD

**Issue by Tobus2** [gpac/gpac#227]
The latest Win32 binary link on the webite: http://download.tsi.telecom-paristech.fr/gpac/latest_builds/win32/gpac-0.5.2-DEV-rev612-gb1a150e-master-win32.exe  is returning a 200kb file that says "NSIS error", "Installer integrity check failed...." when you run it. Downloaded with FF 40.0.3 on XPSP2.

**Comment by rbouqueau** [comment]
Thanks for reporting. Unfortunately it happens. Something may fail during the upload from the buildbot to the website.

@nguyen-viet-thanh-trung @jeanlf Could you have a look please?

**Comment by nguyen-viet-thanh-trung** [comment]
@Tobus2 It should work well now. Thank you for your reporting.
