### ISSUE TITLE
How can I invoke parsing when needed?

### ISSUE THREAD

**Issue by sasmaster** [gpac/gpac#2273]
Hi,
Is there an option to advance parsing manually.Currently I see that start() function runs the parsing from the beginning till the end of the container automatically. But I am looking for a way to invoke the parsing routine manually.
Thanks.

**Comment by jeanlf** [comment]
This doesn't look like a question for gpac, maybe for mp4box.js ? Closing, feel free to add more details

**Comment by sasmaster** [comment]
Oops, my bad. I thought it was mp4box.js
