### ISSUE TITLE
Extract frames from tiled videos

### ISSUE THREAD

**Issue by pratikbendre47** [gpac/gpac#2274]
I have been working on a project which needs to examine the frames of a streamed video. I have followed the steps provided at https://github.com/gpac/gpac/wiki/HEVC-Tile-based-adaptation-guide to create a tiled video and used the same reference to create a mpd file. 
I setup my DASH server and started streaming the video, but its only playable on GPAC and not on any other media player (i.e VLC). Is there a way to save the frames of this streamed video using gpac?

**Comment by jeanlf** [comment]
to save the reaggregated stream: `gpac -i MPD_URL tileagg -o remux.mp4`

for regular sessions without tiling: `gpac -i MPD_URL -o remux.mp4`
