### ISSUE TITLE
How to add metadata to an MP4 file?

### ISSUE THREAD

**Issue by birdie-github** [gpac/gpac#2275]
I've perused the man page, Google and closed issues, I cannot find anything.

My source video contains this:
```
ffprobe 1.mp4 
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '1.mp4':
  Metadata:
    creation_time   : 2019-04-09T06:01:42.000000Z
    location        : +12.3456+078.9012/
    location-eng    : +12.3456+078.9012/
    com.android.version: 11
    com.android.capture.fps: 60.000000
```

I've tried:
`MP4Box -udta com.android.version:type=name:str=9 newfile.mp4` - doesn't work.
`MP4Box -itags com.android.version:9 newfile.mp4` - doesn't work.

So, how can I add metadata to an MP4 file?

**Comment by birdie-github** [comment]
[Sample video](https://mega.nz/file/L4M1FKxS#70aqE3x5ZvYxWmMlm_2WRF7PJ6GBZQ3BINm12Dav7X8).

> For udta tagging, you need to pass the box payload (or string) but that shouldn't be needed for simple tagging.

This sounds a bit complicated. How does it work?

I've noticed that for mp4 files tags can exist for the file itself and for each of its streams.

I need to add tags to the file itself (not individual video/audio streams).

**Comment by birdie-github** [comment]
> your test file doesn't show any 'com.android.version' metadata, only regular tags

It's the file I'm trying to add headers/tags/whatever they are called to.

The [source file](https://mega.nz/file/noExjQCC#-rRCvpfi02xIn7vHc2Ffpm5q8m4qoCydfcn28EqaTlE) which contains the headers.

**Comment by jeanlf** [comment]
This kind of metadata is from QT and was not supported, now available on master:
- you should see these metadata with `MP4Box -info`
- you can add them using `MP4Box -tags com.android.version=9 file.mp4`

I have some doubts about usage of `@xyz` tag in your source file, it should either be a tag of ilst (itunes-like) or a `com.apple.quicktime.location.ISO6709` QT tag.

**Comment by birdie-github** [comment]
> I have some doubts about usage of `@xyz` tag in your source file, it should either be a tag of ilst (itunes-like) or a `com.apple.quicktime.location.ISO6709` QT tag.

This is what OnePlus camera app writes/adds by default. I've no control over that.
