### ISSUE TITLE
Some problems with opening the encoded videos

### ISSUE THREAD

**Issue by chutoutian** [gpac/gpac#2286]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

HI， I want to do tile streaming and follow the instruction in https://github.com/gpac/gpac/wiki/HEVC-Tile-based-adaptation-guide

However, after I package the video and ran the following code:

MP4Box -add video_tiled.hvc:split_tiles -new video_tiled.mp4
MP4Box -rem 3 video_tiled.mp4 -out test_tile_lost.mp4

I had some problems opening the output video (video_tiled.mp4 test_tile_lost.mp4). I tried several ways to open but all failed:

1） gpac -i video_tiled.mp4 
No filter chain found for PID video_tiled.mp4 in filter fin to any loaded filters - NOT CONNECTED

2）ffplay video_tiled.mp4
No decoder could be found for codec none
Failed to open file 'video_tiled.mp4' or configure filtergraph

3） I open the mp4 file with the some players and it turns out that  hvt1 and hvc2 decoder are required.

Besides, I also found some problems with the gpac, like when I ran:

gpac -gui
[Compositor] Failed to load a video output module.
Failed to load filter "compositor:player=gui": I/O Error

I am new to this and I have looked the issues and cannot find the solutions.  I think I have the same issue with https://github.com/gpac/gpac/issues/1550#issue-665001400  , but it is closed.

Thanks a lot if you could give some suggestions !

**Comment by jeanlf** [comment]
> gpac -i video_tiled.mp4

this does nothing, only specifies an input - use `gpac -i SRC vout`, `gpac -play SRC` , `gpac -gui SRC` ... cf [wiki](https://github.com/gpac/gpac/wiki/Player)

I don't think other players support hvt1/hvt2 tracks

> [Compositor] Failed to load a video output module.

Are you using a mini-build ? You can check support for video output using `gpac -h modules`
