### ISSUE TITLE
Why is video playing green？

### ISSUE THREAD

**Issue by binbinzhm** [gpac/gpac#2287]
![image](https://user-images.githubusercontent.com/38529221/195586498-ab7bd2f7-95c6-4b98-b801-3f79521aad76.png)
![image](https://user-images.githubusercontent.com/38529221/195586576-00d678ae-a47a-4a46-9077-5417cce935ba.png)

**Comment by jeanlf** [comment]
what is the video decoder being used ? (either click on the `i` icon or use `-graph` in command line)

**Comment by binbinzhm** [comment]
![image](https://user-images.githubusercontent.com/38529221/195590063-e24e5b6d-bebd-4873-94e0-c939c4d2a63f.png)

**Comment by jeanlf** [comment]
is the video playing normally before tiles spliting ?

**Comment by binbinzhm** [comment]
When I select the highest bit rate, it can play normally，

**Comment by binbinzhm** [comment]
But when I choose a low bit rate, it will play in green.

**Comment by binbinzhm** [comment]
![image](https://user-images.githubusercontent.com/38529221/195590646-f9595a43-1087-4041-87be-d48b8ada8a70.png)

**Comment by binbinzhm** [comment]
![image](https://user-images.githubusercontent.com/38529221/195590937-bedc7116-4d03-4121-9d85-ed54cd6a57d8.png)

**Comment by binbinzhm** [comment]
![image](https://user-images.githubusercontent.com/38529221/195591098-2216b6c4-425a-4cf7-bbe4-fae30ee3794d.png)

**Comment by binbinzhm** [comment]
![image](https://user-images.githubusercontent.com/38529221/195591248-9e160c53-b175-4038-82a4-31aa79c98821.png)

**Comment by binbinzhm** [comment]
![Uploading image.png…]()

**Comment by binbinzhm** [comment]
One renturn 0 and one return 2

**Comment by binbinzhm** [comment]
Another question is why 3x3 tiles have 10 tracks

**Comment by binbinzhm** [comment]
thank you

**Comment by jeanlf** [comment]
> Another question is why 3x3 tiles have 10 tracks

one for tile base track and one track per tile

> But when I choose a low bit rate, it will play in green.

I think you have a mismatch in the encoding settings of the two versions, could you share your files ?

**Comment by binbinzhm** [comment]
of course

**Comment by binbinzhm** [comment]
# step1

original.mp4 >> original.yuv

`ffmpeg -i original.mp4 original.yuv` 

# step2

original.yuv >> video-16Mb.hvc
original.yuv >> video-32Mb.hvc
original.yuv >> video-64Mb.hvc

`kvazaar -i original.yuv --input-res 76800x3840 -o video-16Mb.hvc --tiles 3x3 --slices tiles --mv-constraint frametilemargin --bitrate 16000000`

# step3

video-16Mb.hvc >> video-16Mb.mp4
video-32Mb.hvc >> video-32Mb.mp4
video-64Mb.hvc >> video-64Mb.mp4

`MP4Box -add video-16Mb.hvc:split_tiles -new video-16Mb.mp4`

# step4

video-16Mb.mp4 + video-32Mb.mp4 + video-64Mb.mp4 >> video16-32-64/*

`MP4box -dash 1000 -rap -frag-rap -profile live -out video16-32-64Mb.mpd video-16Mb.mp4 video-32Mb.mp4 video-64Mb.mp4`

**Comment by binbinzhm** [comment]
this is my  operation

**Comment by binbinzhm** [comment]
but the file is to big.so which one do you like？
<img width="880" alt="image" src="https://user-images.githubusercontent.com/38529221/195654966-81f261fb-cbe1-4d2a-9580-b455ca156413.png">

**Comment by binbinzhm** [comment]
<img width="819" alt="image" src="https://user-images.githubusercontent.com/38529221/195655257-493352db-7128-4a64-96a6-f7db813b024b.png">

**Comment by binbinzhm** [comment]
> one for tile base track and one track per tile
What is the role of tile base track？

Thanks for your help！

**Comment by binbinzhm** [comment]
I am very late here, maybe I will go to bed soon, so my reply may not be very timely

**Comment by binbinzhm** [comment]
[video](https://drive.google.com/drive/folders/1ZBtuSItsaANIurJwHdYLbhBM4QVhJNjT?usp=sharing)
I will upload the original video and step 3 video

**Comment by binbinzhm** [comment]
Another problem is that I cannot play in VR mode
<img width="693" alt="image" src="https://user-images.githubusercontent.com/38529221/195778831-6571557a-d208-4ac5-8ae0-77c64ac29824.png">
<img width="990" alt="image" src="https://user-images.githubusercontent.com/38529221/195778106-cf58faac-fa44-4515-98e1-2096c2bd5186.png">

this is normal mode.
<img width="686" alt="image" src="https://user-images.githubusercontent.com/38529221/195779246-f9500117-dfcd-4d08-af75-0915ff1db00d.png">

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/38529221/195778951-72d5d006-5eec-46f8-b756-7cdc15e7f1b5.png">

**Comment by binbinzhm** [comment]
I follow the [GPAC Build Guide for Linux](https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux)
<img width="701" alt="image" src="https://user-images.githubusercontent.com/38529221/195779609-d5ec47ae-1615-434d-8bb2-83bbb7b49d53.png">

**Comment by binbinzhm** [comment]
The problem playing green was solved.when I reinstalled GPAC

**Comment by binbinzhm** [comment]
Now I have two problem.

1. What is the role of tile base track？
2. Another problem is that I cannot play in VR mode(Linux)

**Comment by jeanlf** [comment]
> What is the role of tile base track？

it carries base non-VCL nal units (SEIs, parameter sets) that may happen in-band and also gives the tile reaggregation order.

 > Another problem is that I cannot play in VR mode(Linux)

Do you have the same issue with any file , eg `gpac -gui source.mp4#VR` ? If still not working, open new issue.
