### ISSUE TITLE
Wiki suggestion 

### ISSUE THREAD

**Issue by vt-idiot** [gpac/gpac#2288]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ X ] I looked for a similar issue and couldn't find any.
- [ N/A ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ X ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

The [Wiki page for import opts](https://github.com/gpac/gpac/wiki/mp4box-import-opts/) recommends "(see ISO/IEC 23001-8)" under the **colr** option. [That standard has been revised and replaced by three, new, separate standards,](https://www.iso.org/standard/69661.html) because _of course_ ISO would like you to pay for three, separate standards...

Tools like mkvtoolnix, x264, etc. include the codepoints in their documentation.

If directing end-users to the appropriate external document or standard is the desired look in the gpac/mp4box documentation, then perhaps point them to something easily and freely available, preferably directly, like a link to [ITU H.273](https://www.itu.int/rec/T-REC-H.273/en) which I believe the ISO standards are just referencing anyways.

**Comment by jeanlf** [comment]
updated doc to point out to text/int values (`MP4Box -h cicp` which was already there). Thanks for the feedback
