### ISSUE TITLE
Apple Device Dolby Vision Perfect Mixed Stream Sharing Posts

### ISSUE THREAD

**Issue by dfvips** [gpac/gpac#2289]
The Audio requires raw streaming instead of mp4 or m4a,and the Dolby Vision MP4 file generated by the above process is tested to be perfectly compatible with Apple devices.
### 
**For Mac or Linux:**

```
> ffmpeg -i $1 -c copy -vbsf hevc_mp4toannexb -f hevc -y -an video.tmp.hevc;
> ffmpeg -i $1 -c copy -y -vn audio.tmp.aac; #Can not be omitted
> mp4muxer -i video.tmp.hevc -o $2.tmp.mp4 --dvh1flag 0 --dv-profile 5 --mpeg4-comp-brand mp42,iso6,isom,msdh,dby1 --overwrite;
> mp4box -add "$2.tmp.mp4#video" -add "audio.tmp.aac" -new $2.mp4;
```

**For Windows:**
```
@echo off
for %%i in (%*) do (
ffmpeg -y -i %%i.ts -map 0:a -c copy %%i.aac && ffmpeg -y -i %%i.ts -c copy -vbsf hevc_mp4toannexb -f hevc %%i.hevc && mp4muxer -i %%i.hevc -o %%i.hevc.mp4 --dvh1flag 0 --dv-profile 5 --mpeg4-comp-brand mp42,iso6,isom,msdh,dby1 --overwrite  && mp4box -inter 500 -noprog -add %%i.hevc.mp4#1:name= -add %%i.aac#1:name=:lang=chi -brand mp42isom -ab iso6 -ab msdh -ab dby1 -new MUX_%%i.mp4
)
pause.
```
**Requirements**

-   [ffmpeg](https://ffmpeg.org/download.html) (>=5.0)
    Read track info, extract stream
-   [mp4box](https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/) (>=2.1)
    Mux video, audio, subtitle together
-   [mp4muxer](https://github.com/DolbyLaboratories/dlb_mp4base/tree/master/bin)
    Mux ES to DoVi mp4

 Please ensure the version of these software, or the output may not be correct!

**Comment by sw5163** [comment]
大佬能解释一下 `$1`, `-vbsf hevc_mp4toannexb`, `-y -an`分别是什么意思
以及 mp4box 多出来的那些指令和
https://www.avsforum.com/threads/apple-dolby-vision.3252865/
这个里面`mp4box -add dv.hevc:dv-profile=5`有什么区别吗
非常感谢！

**Comment by dfvips** [comment]
$1指的是视频文件，循环里面用$代表传入的参数，-vbsf hevc_mp4toannexb视频流过滤，-y确认覆盖，-an表示只要视频流。建议熟悉ffmpeg文档。mp4box -add dv.hevc:dv-profile=5是添加dvhe的流，Apple是无法支持的，Apple只支持识别dvh1和hvc1。此外，建议使用[](https://github.com/nilaoda/DoViMuxer)，可以更方便快捷封装。
使用方法：
> DoViMuxer -i xxx.mkv xxx.mp4
原理和上面的命令一致，都是将不支持苹果的dvhe和hevc封装成dvh1和hvc1。

**Comment by dfvips** [comment]
> 大佬能解释一下 `$1`, `-vbsf hevc_mp4toannexb`, `-y -an`分别是什么意思 以及 mp4box 多出来的那些指令和 https://www.avsforum.com/threads/apple-dolby-vision.3252865/ 这个里面`mp4box -add dv.hevc:dv-profile=5`有什么区别吗 非常感谢！

看上面的回复。

**Comment by dfvips** [comment]
Communication here <a href="https://github.com/gpac/gpac/issues/1991">https://github.com/gpac/gpac/issues/1991</a>

**Comment by sw5163** [comment]
ok thx

**Comment by sw5163** [comment]
呃 @nilaoda 的那个也是调用的 MP4box 吧？
好像还是 `mp4box -add dv.hevc:dv-profile=5` 简单一点 :)
