### ISSUE TITLE
Will the dashcast no longer be maintained?

### ISSUE THREAD

**Issue by JamesXu20150314** [gpac/gpac#229]
Hi,
Why I can not get a right segment with dashcast.
I have tried many machines, such as windows 7 64 bit, ubuntu 14.04.
Now, I can not get a right segment which can be played by dash.js.
I want know will the tool no longer be maintained?

JamesXu

**Comment by cconcolato** [comment]
DashCast is maintained, maybe not at the same frequency as other applications, depending on our priorities. If you have specific bugs or needs, open issues (as you have for some), we will try to fix them  when we can. Please refrain from opening issues like this one as it does not help. Remember that GPAC is an open source project and we are not 100 developers working on it. We welcome your contribution: code, patches, documentation, bug reports as precise as possible ...
