### ISSUE TITLE
inspect filter, 'speed' parameter does not work

### ISSUE THREAD

**Issue by phananh1010** [gpac/gpac#2290]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Hello, I tried to change the value of `speed` [parameter](https://github.com/gpac/gpac/wiki/inspect), but the play back speed does not change. Can you please let me know how to change playback speed when `inspect` filter is used as a sink?

Here is the code I tested, I used the newest code in master.
```
import libgpac as gpac
import time

fs = gpac.FilterSession(0)
f1 = fs.load_src(f"http://localhost/dash/coaster2/coaster2_10x5.mpd")
f2 = fs.load("dashin")
f3 = fs.load("tileagg")
f4 = fs.load("inspect:interleave=true:deep=true:dur=15:buffer=3000:speed=0.02")


f2.set_source(f1)
f3.set_source(f2)
f4.set_source(f3)

btime = time.time()
fs.run()
print(f'\n\nDone, executing time: {time.time() - btime}')
fs.print_graph()
fs.delete()
gpac.close()
```

I changed `speed` to different values, from 0.02 to 100, but the reported executing time is always about 2.4 seconds. If I set `dur` to 15 and `speed` to 1.0, should the total time report be around 15 seconds too?

**Comment by jeanlf** [comment]
inspect.speed does not impact real-time delivery (I just updated the doc on that), it is just here to forward speed to source filter chain, to test dash adaptation for example.  
You need to insert a real-time reframer (use latest master):

```
gpac -i SRC_URL reframer:rt=on inspect:deep:speed=2
```

The speed param will be used by default by the reframer to do the regulation.

I also aligned inspect buffering options to vout/aout/compositor so you can set playout buffer, max buffer and rebuffering options.
