### ISSUE TITLE
Tiled Streaming . Delete a tiled track from the file(video_tiled.mp4). I can't see a video with a clean cut, green area in place of the removed tile.My results are shown below.My process is shown in the issue file.

### ISSUE THREAD

**Issue by xd-YuDeng** [gpac/gpac#2303]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/
[issue.md](https://github.com/gpac/gpac/files/9943986/issue.md)
![eef24f37c16cee629848518c2f43d89](https://user-images.githubusercontent.com/106050771/200123893-491a29ca-cba7-4f58-b624-64c35bf07c10.jpg)

**Comment by jeanlf** [comment]
how a decoder deals with missing slices (or tiles) is implementation specific, some decoders will output a black area (-> green in yuv), some will complain/fail, some will output data from previously reconstructed pictures...

**Comment by xd-YuDeng** [comment]
> how a decoder deals with missing slices (or tiles) is implementation specific, some decoders will output a black area (-> green in yuv), some will complain/fail, some will output data from previously reconstructed pictures..

May I ask how to delete the specified tile? I use this link to guide operation failed (https://github.com/gpac/gpac/wiki/HEVC-Tile-based-adaptation-guide)
