### ISSUE TITLE
What command should I use to build a nightly build rather than a stable build?

### ISSUE THREAD

**Issue by bluewidy** [gpac/gpac#2305]
https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux

What command should I use to build a nightly build rather than a stable build?
https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/

**Comment by jeanlf** [comment]
nightly builds are built using the instructions in the wiki with all dependencies compiled, see:
- https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux#full-gpac-build-advanced-users
- https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Windows#full-gpac-build
- https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-OSX#full-build
