### ISSUE TITLE
mkv to mp4 remux not working in MP4Box on Linux.

### ISSUE THREAD

**Issue by bluewidy** [gpac/gpac#2306]
<img width="663" alt="Windows MP4Box" src="https://user-images.githubusercontent.com/40682277/200276320-161eb6bc-4485-4abf-9982-6b493270273d.png">
<img width="509" alt="Linux MP4Box" src="https://user-images.githubusercontent.com/40682277/200276336-0714bebf-e3bd-42a1-ac41-0256c1e1e8ea.png">

As you can see from the screenshot, it works fine on Windows, but not on Linux.

**Comment by jeanlf** [comment]
check your support for ffmpeg:
`gpac -h filters:@ | grep matro`

**Comment by bluewidy** [comment]
<img width="317" alt="hmm" src="https://user-images.githubusercontent.com/40682277/200295400-07abe64a-1d6f-414d-9ccf-b245c5b13d61.png">

**Comment by rbouqueau** [comment]
Do ```./gpac``` as you did for MP4Box.

You don't need sudo priviledges to do ```sudo make install```. When executing the ```configure```script you can specify a prefix (which is where GPAC will be installed).

**Comment by bluewidy** [comment]
<img width="481" alt="Thank you" src="https://user-images.githubusercontent.com/40682277/200297249-117872a0-f3b0-4090-a656-ebc0cca43d29.png">
Thank you! Something happened!

**Comment by bluewidy** [comment]
<img width="503" alt="result" src="https://user-images.githubusercontent.com/40682277/200297575-3f84aba4-4df4-42a0-97a7-08c47f32b527.png">
However, the problem still occurs after executing the command.

**Comment by bluewidy** [comment]
> Make sure you compile with a recent ffmpeg

Thanks for the solution. But honestly, I don't understand what you're talking about. Does that mean I need to install ffmpeg on my OS?

**Comment by aureliendavid** [comment]
(re-reading the build guide I agree that the sections are confusing, I'll rework them, but the short answer is you need to follow the steps in https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux#gpac-easy-build-recommended-for-most-users and then in https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux#building-gpac )

longer answer: 

mkv support in gpac in done by using libavformat (which is part of the ffmpeg set of libraries)

if you used an official installer for gpac on windows, all the libraries are included

but on linux it's up to you to install the system libraries you want depending on the features you need

if you look at https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux#gpac-easy-build-recommended-for-most-users it does mention to install `libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavdevice-dev` (which are the ffmpeg libraries)

when you build gpac, you can see which features are activated during the `./configure` step ; for example if the ffmpeg libraries are properly installed and activated you should see: 

```
...
FFMPEG: system (pkgconfig)
...
```

in the ./configure output (otherwise you'll see `FFMPEG: no`)

**Comment by bluewidy** [comment]
Oops... Should I use the `sudo` command I fear? Is there any way to install a library without using `sudo`?

**Comment by aureliendavid** [comment]
> The good news is that already have ffmpeg installed on cloud computer!

that is good

what does the gpac  `./configure` script says when you run it (without --static-bin)?

**Comment by bluewidy** [comment]
```
bluewindy@nova:~/bin/gpac_public$ ./configure

** System Configuration
Install prefix: /usr/local
Source path: /home/bluewindy/bin/gpac_public
C   compiler: gcc
C++ compiler: g++
make: make
CPU: x86_64
Big Endian: no

** GPAC 2.1-DEV rev463-g2191e66aa-master Core Configuration **
Static Modules: no
debug version: no
GProf enabled: no
Memory tracking enabled: no
Sanitizer enabled: no
Fixed-Point Version: no
IPV6 Support: yes
QuickJS Support: yes (with qjs-libc)

** Detected libraries **
zlib: system (pkgconfig)
OpenGL support: yes
OpenSSL support: system (pkgconfig)
nghttp2: no
OSS Audio: yes
ALSA Audio: no
Jack Audio: no
Pulse Audio: no
DirectFB: no
X11: yes (path: /usr/X11R6)
X11 Shared Memory support: yes
X11 XVideo support: no
SDL: no
DVB for Linux: yes
FreeType: system (pkgconfig)
JPEG: no
OpenJPEG: no
PNG: system (pkgconfig)
MAD: no
FAAD: no
XVID: no
FFMPEG: no
LZMA: yes
Xiph OGG: no
Platinum UPnP: no
A52 (AC3): no
OpenSVCDecoder: local
OpenHEVCDecoder: no
Freenect: no

Creating config.mak
config.h is unchanged
Check config.log for detection failures
Done - type 'make help' for make info, 'make' to build
bluewindy@nova:~/bin/gpac_public$
```

**Comment by aureliendavid** [comment]
ok, can you join the config.log file as well ?

**Comment by bluewidy** [comment]
<img width="806" alt="blank" src="https://user-images.githubusercontent.com/40682277/200328227-c6b0ab05-c346-4d24-9d21-5bd5aaf1de24.png">

**Comment by bluewidy** [comment]
[config.log](https://github.com/gpac/gpac/files/9952295/config.log)

**Comment by aureliendavid** [comment]
can you run the 3 following commands:

```
dpkg -l | grep libav
ls -l /usr/lib/x86_64-linux-gnu/libavcodec.so  /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h
ld --verbose | grep SEARCH_DIR | tr -s ' ;' \\012
```

**Comment by bluewidy** [comment]
`bluewindy@nova:~/bin/gpac_public$ dpkg -l | grep libav
ii  libavahi-client3:amd64                                      0.7-4+deb10u1                                                                                                                                                                                   amd64        Avahi client library
ii  libavahi-common-data:amd64                                  0.7-4+deb10u1                                                                                                                                                                                   amd64        Avahi common data file                                                                                                                                   s
ii  libavahi-common3:amd64                                      0.7-4+deb10u1                                                                                                                                                                                   amd64        Avahi common library
ii  libavc1394-0:amd64                                          0.5.4-5                                                                                                                                                                                         amd64        control IEEE 1394 audi                                                                                                                                   o/video devices
ii  libavcodec57:amd64                                          7:3.2.15-0+deb9u                                                                                                                                   2                                            amd64        FFmpeg library with de                                                                                                                                   /encoders for audio/video codecs - runtime files
ii  libavcodec58:amd64                                          7:4.1.9-0+deb10u                                                                                                                                   1                                            amd64        FFmpeg library with de                                                                                                                                   /encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                                         7:4.1.9-0+deb10u                                                                                                                                   1                                            amd64        FFmpeg library for han                                                                                                                                   dling input and output devices - runtime files
ii  libavfilter7:amd64                                          7:4.1.9-0+deb10u                                                                                                                                   1                                            amd64        FFmpeg library contain                                                                                                                                   ing media filters - runtime files
ii  libavformat58:amd64                                         7:4.1.9-0+deb10u                                                                                                                                   1                                            amd64        FFmpeg library with (d                                                                                                                                   e)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                                        7:4.1.9-0+deb10u                                                                                                                                   1                                            amd64        FFmpeg compatibility l                                                                                                                                   ibrary for resampling - runtime files
ii  libavutil55:amd64                                           7:3.2.15-0+deb9u                                                                                                                                   2                                            amd64        FFmpeg library with fu                                                                                                                                   nctions for simplifying programming - runtime files
ii  libavutil56:amd64                                           7:4.1.9-0+deb10u                                                                                                                                   1                                            amd64        FFmpeg library with fu                                                                                                                                   nctions for simplifying programming - runtime files
bluewindy@nova:~/bin/gpac_public$ ls -l /usr/lib/x86_64-linux-gnu/libavcodec.so                                                                                                                                     /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h
ls: cannot access '/usr/lib/x86_64-linux-gnu/libavcodec.so': No such file or dir                                                                                                                                   ectory
ls: cannot access '/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h': No such                                                                                                                                    file or directory
bluewindy@nova:~/bin/gpac_public$`

**Comment by bluewidy** [comment]
```
bluewindy@nova:~/bin/gpac_public/bin/gcc$ gpac -h filters:@ | grep matro
ffdmx:matroska,webm: Matroska / WebM
ffmx:matroska: Matroska
ffmx:matroska: Matroska Audio
bluewindy@nova:~/bin/gpac_public/bin/gcc$ ./MP4Box -add Unfold.mkv -new Unfold.mp4
Track Importing MPEG-4 AVC - Width 1920 Height 1080 FPS 24/1 SAR 1/1
Track Importing FLAC - SampleRate 48000 Num Channels 2
Track Importing EAC-3 - SampleRate 48000 Num Channels 8
[MP4Mux] PID video1 ID 1 Sample 2 with DTS 0 less than previous sample DTS 0, adjusting prev sample duration
[NULL] invalid sync code
Saving Unfold.mp4: 0.500 secs Interleaving
bluewindy@nova:~/bin/gpac_public/bin/gcc$
```

Thank you, thank you so much!  Now I'm so happy that the output is the same as what I saw on Windows!  You have given me a significant amount of time to help me invaluable.  Thank you very much for your devoted heart. 

and as you mentioned, ffmpeg allows me to remux MKV to MP4, but it has [bug](https://trac.ffmpeg.org/ticket/9996#comment:1), so I used MP4Box, and it produced the results I was expecting!
![Mission accomplished!](https://user-images.githubusercontent.com/40682277/200359011-c300d824-82cf-4a87-83e0-8cb54a0e4e7a.jpg)
