### ISSUE TITLE
 How to remove a Tile?When I delete a tile, none of the subsequent tiles will play.In the guide you gave, what player is used after removing a tile??

### ISSUE THREAD

**Issue by xd-YuDeng** [gpac/gpac#2308]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

![c09b4b7d6b79904cbd5f56041f0ba17](https://user-images.githubusercontent.com/106050771/200327069-f11c67cc-ff2c-4b8a-b758-8a0811a00a62.jpg)

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
please provide detail information: how do you "delete" a tile (track removal, MPD representation removal, removal through custom DASH logic, etc ...) so that we can verify if there is a bug or not. Upload your content if needed.

**Comment by xd-YuDeng** [comment]
> please provide detail information: how do you "delete" a tile (track removal, MPD representation removal, removal through custom DASH logic, etc ...) so that we can verify if there is a bug or not. Upload your content if needed.

Hello, the process of my tile deletion is as follows：

1、kvazaar -i fam_1920x1080.yuv --input-res 1920x1080 -o fam_1920x1080.hvc --tiles 3x3 --slices tiles --mv-constraint frametilemargin --bitrate 12800000 --period 30 --input-fps 30

2、MP4Box.exe -add fam_1920x1080.hvc:split_tiles -fps 30 -new video_tiled.mp4

3、MP4Box -rem 6 video_tiled.mp4 -out test_tile_lost.mp4

4、MP4Box -dash 1000 -rap -frag-rap -profile live -out dash_tiled.mpd test_tile_lost.mp4

5、gpac -gui dash_tiled.mpd

The final result is as follows.

![QQ图片20221109112438](https://user-images.githubusercontent.com/106050771/200733179-89b57a3f-cd5f-4164-b494-f39963b4533b.png)

**Comment by jeanlf** [comment]
I can't reproduce here using [this file](http://download.tsi.telecom-paristech.fr/gpac/gpac_test_suite/resources/media/counter/counter_1280_720_I_25_tiled_1mb.hevc), could you post your source (no split) somewhere ?

Also do you see the same results when you play the split mp4 using gpac ?

**Comment by xd-YuDeng** [comment]
> 
Hello, I directly use the command line to code, that is my command line operations.
I saw the same result when playing test_tile_lost.mp4 using gpac.
![e6c74153c91f7ba0d9e48ac4f656c70](https://user-images.githubusercontent.com/106050771/201906726-eb298c58-00da-4764-817c-ee56680f4b1c.jpg)
