### ISSUE TITLE
MP4 audio to AudioBuffer

### ISSUE THREAD

**Issue by bengfarrell** [gpac/gpac#2310]
Hi all, 
Does anyone have any examples of reading and maybe queueing samples from MP4Box and creating an AudioBuffer from these?
Currently I have something that creates EncodedAudioChunks and it works great, but I'm having trouble using Web Codecs on the audio side to work well with AudioBuffers from elsewhere, so I'm thinking that I'd like to avoid using Web Codecs on the audio side.  Unfortunately I fell short trying to process these samples without making the EncodedAudioChunks (other than decoding them all with Web Codecs)
Thanks!

**Comment by jeanlf** [comment]
This issue concerns mp4box.js, please open it [here](https://github.com/gpac/mp4box.js/issues/).

**Comment by bengfarrell** [comment]
Oh, my apologies! I think I've been bouncing between the two repos too much
