### ISSUE TITLE
Muxing Raw ALAC Stream into M4A

### ISSUE THREAD

**Issue by microtechton** [gpac/gpac#2314]
Hello,

I've been pounding my head with this issue and cannot find an appropriate resolution.

I have a file (called filename.alac) which contains the raw ALAC stream, specifically the mdat payload. (Equivalent to the output from ` mp4box -raw filename.m4a` where filename.m4a contains an alac stream)

I am trying to mux this raw stream into an m4a (M4A /mp42/isom) container. Is this possible with MP4Box? 

I have tried the following command:
`mp4box -add filename.alac#audio filename_new.m4a`

But I received the following output:
```
[Importer] Cannot load filter for input file "filename.alac"
Failure while importing import: Requested URL is not valid or cannot be found
Error importing filename.alac#audio: Requested URL is not valid or cannot be found
```

**Comment by jeanlf** [comment]
We currently don't support raw ALAC. Just curious, what is the file layout you have (given there's no official format for raw ALAC)? Magic cookie encapsulated in alac box + optional chan + payload ?

**Comment by jeanlf** [comment]
I took a quick look at alac, from what I can see parsing the bitstream to reframe it is basically equivalent to decoding it, so we won't support this.
