### ISSUE TITLE
Check timescale when calling 'MP4Box -dashctx' again

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#232]
Because it could be called from a different file. A different timescale leads to an error. So we need to error.

I have test files.

**Comment by rbouqueau** [comment]
More should be checked actually.

**Comment by cconcolato** [comment]
I don't understand the issue. Can you describe a bit more?

**Comment by rbouqueau** [comment]
Yes, sorry for the short description. Actually, when using the context file, parameters are not checked for consistency (including the timescale - we were experimenting on ad-insertion when I reported this issue (for myself)).

Now we have the new dasher merged, we could have a function to test the ctx and the command-line params won't lead to inconsistencies.

**Comment by jeanlf** [comment]
with 0.9.0 the source is reloaded with the options from context, and we try to ensure a consistent result when options changed. We however don't forbid option changes (eg you could change the fragmentation duration, this would not break the result), hence don't check for these. I propose we close and if/when needed open more specific issues on which option changes break the dasher.
