### ISSUE TITLE
HEVC tiled video playback issues

### ISSUE THREAD

**Issue by anshuldevnani** [gpac/gpac#2321]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ x ] I looked for a similar issue and couldn't find any.
- [ x ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ x ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hi, seeing some weird behavior when playing my hevc encoded tiled video following the guide here https://github.com/gpac/gpac/wiki/HEVC-Tile-based-adaptation-guide. 

when running the following command

gpac -gui http://{ip}/path/to/mpd 

i get the following and my video plays as normal
 
![Screen Shot 2022-11-21 at 10 37 42 PM](https://user-images.githubusercontent.com/40804167/203242460-f1e9476a-9d22-43f1-b4f0-be2adf6ef435.png)

However, when running the following command " gpac -play http://{ip}/path/to/mpd"  or using the DASH Client python example i get the following.

![Screen Shot 2022-11-21 at 10 40 19 PM](https://user-images.githubusercontent.com/40804167/203242869-fd790a8d-5e52-4701-98d7-6225febb8597.png)

only the bottom 6th of the player is shown. Any ideas as to why this is happening or what im missing here. I would really like to use the DASH client python example as i would like to implement my own adaptation algorithm.

Appreciate any help thanks!

**Comment by jeanlf** [comment]
could you upload your sample file somewhere?

**Comment by anshuldevnani** [comment]
reinstalled gpac and it works now
