### ISSUE TITLE
Guidelines for dependencies

### ISSUE THREAD

**Issue by paulhiggs** [gpac/gpac#2323]
- [X] I looked for a similar issue and couldn't find any.
- [NA] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [NA] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

It would be useful for the Readme to include information on the various dependencies needed to build GPAC from source code. On Windows, I found that I had to obtain SDL and put it in `extra_lib\include\SDL` and `zlib.lib` into `extra_lib\lib\x64\Debug` and there is more to do with `libcryptoMDd.lib`.
Even better than guidance information would be a PowerShell of Command script that would `curl` and `unzip` the required items into the relevant locations.

**Comment by aureliendavid** [comment]
Hi, 

there is more information about dependencies in the wiki here: https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Windows#full-gpac-build

among other things it will point you to this repo: https://github.com/gpac/deps_windows which contains most dependencies and scripts to build and copy them to the right place

**Comment by aureliendavid** [comment]
the 8.1 in the wiki is because we want the widest retro-compatibility possible, but it should work with everything from visual studio 2015 and up (toolset v140+) and windows sdk 8.1 and up

**Comment by aureliendavid** [comment]
I meant you can use any toolset above v140 and any sdk above 8.1 (so VS2022 with sdk 10 or 11 is ok) 

if you use the command line you can change this part: 

```
/p:PlatformToolset=v140 /p:WindowsTargetPlatformVersion=8.1
```

to match your set up

If you use the visual studio gui you can change this parameter in the project settings page, or right click on the solution and use "retarget solution" to set up the whole thing according to what you have installed
