### ISSUE TITLE
MP4Box produces hundreds of lines when no space left on device error occurs

### ISSUE THREAD

**Issue by rafrafek** [gpac/gpac#2324]
I'm using MP4Box in a Python 3.11 docker container which means I'm using Debian bullseye.

MP4Box - GPAC version 1.0.1-rev1.0.1+dfsg1-4+deb11u1

When "no space left on device" error occurs MP4Box produces so many lines of errors that I cannot event log it into my db.

Is there any option to limit error message to 1 line? Is it fixed already in the latest version of gpac?

<img width="820" alt="image" src="https://user-images.githubusercontent.com/23004737/203570270-61f22e09-b4bc-41e4-987b-fdf4d1c36dc1.png">

My error logging issue:
<img width="785" alt="image" src="https://user-images.githubusercontent.com/23004737/203572312-857d0e62-6eda-4e1a-b7a9-aa8f8e01e42b.png">

**Comment by rafrafek** [comment]
```
➜  ~ docker logs xxx | grep "No space left on device" | wc -l
  163754
```

**Comment by rbouqueau** [comment]
Well, this message doesn't seem to originate from GPAC: https://github.com/gpac/gpac/search?q=%22No+space+left+on+device%22

I think GPAC actually tries to write at a location that has no space left. Have you tried the ```-tmp``` option as suggested in #445?

**Comment by rafrafek** [comment]
Yes, I'm using the -tmp option. It works well on Linux server but when I test big files on my local macbook inside a docker container it is limited to the docker volume and sometimes produces this error. It would be nice to have just one line in error output. Is there any way to debug this behavior?

**Comment by jeanlf** [comment]
@rbouqueau , the message indeed comes from gpac fwrite wrapper. 

@rafrafek , use `-strict-error` option  if you need to abort on first error.

Also, when you have limited storage space,  be careful of the storage mode you use for MP4Box/gpac, some modes will require twice the final file size...
