### ISSUE TITLE
When trying to mkv to mp4 remux on linux, dolby vision metadata is not maintained.

### ISSUE THREAD

**Issue by bluewidy** [gpac/gpac#2325]
This is the original mkv.
<img width="776" alt="mkv" src="https://user-images.githubusercontent.com/40682277/204077854-bf062da3-2060-4e1e-a234-c6d401b4f1d8.png">

This is the result of remuxing mkv to mp4 on Windows. As you can see the Dolby Vision metadata is preserved.
<img width="607" alt="mp4_windows" src="https://user-images.githubusercontent.com/40682277/204077870-76ebc93f-f341-4f58-b05e-66104f2c5c95.png">

This is what I tried on Linux. As you can see the Dolby Vision metadata is lost.
<img width="325" alt="mp4_rinux" src="https://user-images.githubusercontent.com/40682277/204077885-803af644-77b0-466d-a182-3ecb23734316.png">

Tried with nightly builds on both Windows and Linux.

**Comment by jeanlf** [comment]
This is likely due to an old version of ffmpeg in the linux build.

The latest master should fix this (cf 86ce5633).

Otherwise you can always force reparsing of the stream using
```
MP4Box -add src.mkf:@unframer -new res.mp4
or
gpac -i src.mkf unframer -o res.mp4

```

cf https://github.com/gpac/gpac/issues/1991#issuecomment-1303947232

**Comment by bluewidy** [comment]
> The latest master should fix this (cf [86ce563](https://github.com/gpac/gpac/commit/86ce563305f14828be604a7d69465adb02a7cd24)).

Wonderful! Thank you! https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/
If you have time, can you upload the master here so I can install that please?

**Comment by aureliendavid** [comment]
looks like we have an issue with the auto uploading of the builds, I'm looking into it

**Comment by bluewidy** [comment]
I see. Thank you.

**Comment by aureliendavid** [comment]
[86ce563](https://github.com/gpac/gpac/commit/86ce563305f14828be604a7d69465adb02a7cd24) installers should now be up

**Comment by bluewidy** [comment]
> The latest master should fix this (cf [86ce563](https://github.com/gpac/gpac/commit/86ce563305f14828be604a7d69465adb02a7cd24)).

Tried with the latest master, still doesn't retain Dolby Vision metadata.
<img width="374" alt="latest master" src="https://user-images.githubusercontent.com/40682277/204269830-a936f925-6a54-4231-8597-a288cfeea8bd.png">

> Otherwise you can always force reparsing of the stream using
> 
> ```
> MP4Box -add src.mkf:@unframer -new res.mp4
> or
> gpac -i src.mkf unframer -o res.mp4
> ```

On the other hand, the results of using the command you pointed out will retain the Dolby Vision metadata. However, it is not psychologically comfortable to see the tag "SMPTE ST 2086, HDR 10 compatible" appearing twice.
<img width="890" alt="Recommended command used" src="https://user-images.githubusercontent.com/40682277/204269945-38075f2f-af5e-4271-9169-90d81c6f7514.png">

**Comment by jeanlf** [comment]
> Tried with the latest master, still doesn't retain Dolby Vision metadata

what is your ffmpeg version ? Check  `gpac -hx ffdmx | grep Version` and `gpac -hx ffenc | grep Version` 

 > However, it is not psychologically comfortable to see the tag "SMPTE ST 2086, HDR 10 compatible" appearing twice.

this is a display issue from mediainfo due to the presence of clli and mdcv in the muxed mp4, you can try adding `:hdr=none` to the added source (`-add src.mkv:hdr=none:@unframer `)

**Comment by bluewidy** [comment]
<img width="373" alt="not work" src="https://user-images.githubusercontent.com/40682277/204302729-88d1230a-ad2d-487f-8348-bb7927103955.png">
