### ISSUE TITLE
32 bit issue

### ISSUE THREAD

**Issue by Noitarud** [gpac/gpac#2326]
I just obtained 32 bit from
https://gpac.wp.imt.fr/downloads/
To see if a bug has since been fixed. Mp4box seems to not be 32 bit.  Ffmpeg runs. Installer ran. Cannot locate previous version of installer to see if my bug is there.

As for the bug, frame rate specification is being ignored with one video specifically, it wants 29.08, I want 29.04 and 5fps test fails.
Using: -add AVfile -fps 5 AVoutfile
Also tried: …\mp4box" -add E:\copy.mp4#audio -add E:\copy.mp4#video:fps=5.0 C:\Recov\out.mp4
The first was tried on a short clip with success so shouldn't be command issue…

N.

**Comment by rbouqueau** [comment]
What's your OS?

You are saying that the 32 bits installer is not 32 bits, is that correct?

> As for the bug, frame rate specification is being ignored with one video specifically, it wants 29.08, I want 29.04 and 5fps test fails.
Using: -add AVfile -fps 5 AVoutfile
Also tried: …\mp4box" -add E:\copy.mp4#audio -add E:\copy.mp4#video:fps=5.0 C:\Recov\out.mp4
The first was tried on a short clip with success so shouldn't be command issue…

Could you share a sample with us? We have an anonymous dropbox [here](https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95), make sure to mention the issue number in your file names.

Please note that your command-line doesn't re-encode the video. It just changes the fps signalling. So your video keeps on being encoded at the original framerate. Make sure this is what you intended.

**Comment by Noitarud** [comment]
OS is XP, error is typical. My working version of GPAC is 0.5.1-DEV-Rev4867

The full file is over 1Gb, the fps problem I am having survives a FFMPEG reencode and limiting to 40kframes. By the end of the smaller file the sound offset is -1800ms. M4B did not give errors about inability to apply fps command (if you feel there should be, suggest next option). If the problem is associated with an internal stipulated (ie, variable) framerate please allow this to be scaled.

The file with problem was acquired as a .gvi, the DivX6 container is not required. Do I need to supply the URL?
https://www.mediafire.com/file/mceb9lncm15imqo/2326Shortto40k%2CnotCopy.mp4/file

**Comment by Noitarud** [comment]
OS is XP, error is typical. My working version of GPAC is 0.5.1-DEV-Rev4867

The full file is over 1Gb, the fps problem I am having survives a FFMPEG reencode and limiting to 40kframes. By the end of the smaller file the sound offset is -1800ms. M4B did not give errors about inability to apply fps command (if you feel there should be, suggest next option). If the problem is associated with an internal stipulated (ie, variable) framerate please allow this to be scaled.

The file with problem was acquired as a .gvi, the DivX6 container is not required. Do I need to supply the URL?
https://www.mediafire.com/file/mceb9lncm15imqo/2326Shortto40k%2CnotCopy.mp4/file

**Comment by Noitarud** [comment]
OS is XP, error is typical. My working version of GPAC is 0.5.1-DEV-Rev4867

The full file is over 1Gb, the fps problem I am having survives a FFMPEG reencode and limiting to 40kframes. By the end of the smaller file the sound offset is -1800ms. M4B did not give errors about inability to apply fps command (if you feel there should be, suggest next option). If the problem is associated with an internal stipulated (ie, variable) framerate please allow this to be scaled.

The file with problem was acquired as a .gvi, the DivX6 container is not required. Do I need to supply the URL?
https://www.mediafire.com/file/mceb9lncm15imqo/2326Shortto40k%2CnotCopy.mp4/file

**Comment by jeanlf** [comment]
we had a bug in the parsing of options resulting in not displaying the message ':fps option not allowed for ISOBMFF' ....

latsest master:
- bug fixed
- `:fps` option now allowed for isobmff sources, although`rescale` option  should be preferred ( provides finer control)

Could you cross-check ?

**Comment by Noitarud** [comment]
If you are asking me, I will need a version that will not give me the message "C:\Program Files\GPAC\mp4box.exe is not a valid Win32 application" I am stuck with an old version since the install site only offers the one download for my platform.

**Comment by aureliendavid** [comment]
windows xp is officially not supported anymore by gpac so the published installers won't work

it is however possible to build recent mp4box for xp using visual studio and the v140_xp toolset, there is some discussion about it here: https://github.com/gpac/gpac/pull/2257 ; but you'll have to do it yourself as we don't provide binaries for unsupported platforms

**Comment by Noitarud** [comment]
It does install

**Comment by aureliendavid** [comment]
yes it installs, but the message you're seeing when trying to run the actual program ("mp4box is not a valid Win32 application") means that the binary is not compatible with xp (it doesn't mean that it's not really 32 bits, it's just that xp can't run it)

**Comment by Noitarud** [comment]
Thanks Jean (i thought you had referenced an old fix, not fixing as a result of what i had subitted, thanks for your troubles).

**Comment by aureliendavid** [comment]
I see what you mean, but even standalone binaries with no dependencies on external libraries aren't "selfcontained". They depend on the OS to load the program (by reading the [PE](https://en.wikipedia.org/wiki/Portable_Executable) format), to call standard functions, etc.. And there can be compatibility issues in all of these. 

That's why when building a program you have to target a specific "toolset" which has its own range of compatible windows versions. Microsoft has dropped xp support from their standard toolsets for a long time now, that's why gpac isn't working on xp. 

But they do provide an xp compatible toolset with limited functionalities (v141_xp). This can be used to build a limited xp-compatible version of gpac (with mp4box only) for people who really want it. But we are not distributing official binary version of those. 

(maybe we should mention the xp incompatibility on the download pages)

hope this helps

**Comment by Noitarud** [comment]
@aureliendavid I thought about it, and went over what could be required (you're right), I thought making a converter to convert the compiled exe should be possible, the toolset (spelt out) could become a DLL or appended to the end. Probably will not run efficient, but publisher does not need to be involved.

**Comment by jeanlf** [comment]
I updated the download pages with links to wiki for xp - As stated earlier, we no longer support XP installers, build from source is required here.
