### ISSUE TITLE
tpl_roll: mp4box is putting default KID in the MPD

### ISSUE THREAD

**Issue by andyburras** [gpac/gpac#2329]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ /] I looked for a similar issue and couldn't find any.
- [ /] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [/ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Using the GPAC testsuite file tpl_roll.xml to generate and dash media:

```
mp4box.exe -crypt D:\git-repos\gpac\testsuite\media\encryption\tpl_roll.xml D:\test.mp4 -out tpl_roll.mp4

mp4box.exe -rap -dash 2000 -bs-switching no -profile live -pssh v -out .\tpl_roll\index.mpd -sample-groups-traf -no-frags-default -tfdt-traf --cmaf=cmfc -single-traf tpl_roll.mp4 -segment-name $Segment=seg_r$$Init=seg-init_r$$RepresentationID$-$Number$
```

The MPD contains:

`<ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cbcs" cenc:default_KID="27992649-6a7f-5d25-da69-f2b3b2799a7f"/>`

According to DASH-IF IOP-6 V5.0.0 sect 9.3 In-band key rotation signalling

> "For supporting this mechanism:
> • The MPD has no default_KID attribute in the ContentProtection element defined at the AdaptationSet level [...]"

so I think the cenc:default_KID should not be present?

**Comment by jeanlf** [comment]
It's actually a corner case, since this is a master+roll key, it could make sense to expose the default KID of the master key in the manifest. I'm not even sure why the restriction on no default_KID is needed in the DASH-IF IOPs ...

Anyway, I patched as follows master:
- if key roll is detected, try to follow DASH-IF guidelines
- added `dkid` option to dasher to control insertion of defualt_KID (e.g. to force it event if key roll is used)
- added modes to `mp4mx.psshs` to add pssh to both movie and movie fragments (again, not sure why DASH-IF IOP wants this as in vod+roll case it does not really make sense to force it...

Thanks for the report !

**Comment by andyburras** [comment]
Ah, Is tpl_roll approach specifically root/leaf roll? DASH-IF 9.3 is talking about in-band key rotation.
9.4 talks about root/leaf approach (In-band key hierarchy).

Does in-band key rotation require a different GPACDRM syntax?

**Comment by jeanlf** [comment]
> Is tpl_roll approach specifically root/leaf roll? 

Not really, apart from the fact that the rolled keys, when injected in pssh, are encrypted with the key announced in the pssh of the init segment

> Does in-band key rotation require a different GPACDRM syntax?

You can still use the template model but use `KID` instead of `KEYS` , ie inject only the clear KID in pssh:

```
<DRMInfoTemplate version="1" system="6770616363656E6364726D746F6F6C31" KEY="0x5344694d47473326622665665a396b30"> 
<BS ID128="KIDS"/>
</DRMInfoTemplate>

```

The `KEY`attribute is required but ignored, I'll try to patch this.

**Comment by andyburras** [comment]
Thanks for your efforts, that explanation makes it clearer.

**Comment by andyburras** [comment]
Looks like there's a subtlety here. In the root/leaf case (BS ID128="KEY") there is a version 1 PSSH added to the media segments that carries the KID, which seems correct.

In the in-band rotation case (BS ID128="KEY") there is a version 0 PSSH added to the media segments that carries the proprietary DRM-specific data, which again looks correct, e.g.:

```
<ProtectionSystemHeaderBox Size="648" Type="pssh" Version="0" Flags="0" Specification="cenc" Container="moov moof meta" SystemID="0x9A04F07998404286AB92E65BE0885F95">
 <PSSHData size="616" value="0x68020[...]00"/>
</ProtectionSystemHeaderBox>
```

However in the latter case, currently there is **also** a PSSH version 1 being added, e.g.:

```
<ProtectionSystemHeaderBox Size="68" Type="pssh" Version="1" Flags="0" Specification="cenc" Container="moov moof meta" SystemID="0x9A04F07998404286AB92E65BE0885F95">
 <PSSHKey KID="0xA9A6EA9FC0704F65A1A8AAF983A31116"/>
 <PSSHData size="16" value="0xA9A6EA9FC0704F65A1A8AAF983A31116"/>
</ProtectionSystemHeaderBox>
```

which I think may contrevene the DASH-IF 9.3 "_The media segments have one PSSH box per DRM_ [...]" ?

**Comment by jeanlf** [comment]
I cleaned up the tests for DRM template so that we have one for key roll and one for master/leaf schemes.

Using the new DRM [test file](https://github.com/gpac/testsuite/blob/master/media/encryption/tpl_roll.xml) for key roll and dashing the encrypted file, I see one pssh in the moov (signaling no KIDs) and one pssh per moof. Can you cross-check ?

**Comment by andyburras** [comment]
Here are my findings...
Using MP4Box - GPAC version 2.1-DEV-rev516-g2d5fbe1d-master with tpl_roll.xml:

```
<DRMInfoTemplate version="1" system="6770616363656E6364726D746F6F6C31" KEY="0x6770616363656E6364726D746F6F6C31">
<BS bits="8" string="CID=Test"/>
<BS ID128="KEY"/>
</DRMInfoTemplate>
```
  
init-seg:
```
<ProtectionSystemHeaderBox Size="32" Type="pssh" Version="0" Flags="0" Specification="cenc" Container="moov moof meta" SystemID="0x6770616363656E6364726D746F6F6C31">
</ProtectionSystemHeaderBox>
...
<TrackEncryptionBox Size="49" Type="tenc" Version="1" Flags="0" Specification="cenc" Container="schi" isEncrypted="1" constant_IV_size="16" constant_IV="0x0A610676CB88F302D10AC8BC66E039ED"  KID="0x279926496A7F5D25DA69F2B3B2799A7F" crypt_byte_block="1" skip_byte_block="9">
</TrackEncryptionBox>
```
SytemID looks odd, it's being set to the DRMInfoTemplate "KEY" value, shouldn't it be the "system" value?

segment 1:
```
<ProtectionSystemHeaderBox Size="77" Type="pssh" Version="1" Flags="0" Specification="cenc" Container="moov moof meta" SystemID="0x6770616363656E6364726D746F6F6C31">
 <PSSHKey KID="0x279926496A7F5D25DA69F2B3B2799A7F"/>
 <PSSHData size="25" value="0x084349443D5465737400B9516B23CA00E6D9B8F07B113C861E"/>
</ProtectionSystemHeaderBox>
```
Again, SytemID looks odd, it's being set to the DRMInfoTemplate "KEY" value, shouldn't it be the "system" value?

PSSH written to each media segment, and rotating through the leaf keys so looks good:
```
seg_r1-100_info.xml: <PSSHKey KID="0x32783E367C2E4D4D6B46467B3E6B5478"/>
seg_r1-101_info.xml: <PSSHKey KID="0x279926496A7F5D25DA69F2B3B2799A7F"/>
seg_r1-102_info.xml: <PSSHKey KID="0x597669572E55547E656B56586E2F6F68"/>
seg_r1-103_info.xml: <PSSHKey KID="0x205B2B293A342F3D3268293E6F6F4E29"/>
seg_r1-104_info.xml: <PSSHKey KID="0x32783E367C2E4D4D6B46467B3E6B5478"/>
```

sgpd is written to each media segment, but only segments with KIDs other than that in the tenc has a CENCSampleEncryptionGroupEntry, which seems reasonable as the tenc acts as the default:
```
seg_r1-100_info.xml:<CENCSampleEncryptionGroupEntry IsEncrypted="1" IV_size="0" KID="0x32783E367C2E4D4D6B46467B3E6B5478" constant_IV_size="16"  constant_IV="0x0A610676CB88F302D10AC8BC66E039ED"/>
seg_r1-102_info.xml:<CENCSampleEncryptionGroupEntry IsEncrypted="1" IV_size="0" KID="0x597669572E55547E656B56586E2F6F68" constant_IV_size="16"  constant_IV="0x0A610676CB88F302D10AC8BC66E039ED"/>
seg_r1-103_info.xml:<CENCSampleEncryptionGroupEntry IsEncrypted="1" IV_size="0" KID="0x205B2B293A342F3D3268293E6F6F4E29" constant_IV_size="16"  constant_IV="0x0A610676CB88F302D10AC8BC66E039ED"/>
seg_r1-104_info.xml:<CENCSampleEncryptionGroupEntry IsEncrypted="1" IV_size="0" KID="0x32783E367C2E4D4D6B46467B3E6B5478" constant_IV_size="16"  constant_IV="0x0A610676CB88F302D10AC8BC66E039ED"/>
seg_r1-106_info.xml:<CENCSampleEncryptionGroupEntry IsEncrypted="1" IV_size="0" KID="0x597669572E55547E656B56586E2F6F68" constant_IV_size="16"  constant_IV="0x0A610676CB88F302D10AC8BC66E039ED"/>
```

Changing the `<BS ID128="KEY"/>` to `<BS ID128="KID"/>`, i.e. switching from root/leaf to inband key rotation looks to give the same results from this level of examination, so I'm a bit unclear of the difference. In the former case are the leaf keys being encrypted by the root key and being added as the PSSHData element?, or are the requirements DRM-specific and out of scope for mp4box?

**Comment by jeanlf** [comment]
> [UPDATE]: Just realised that the system and key have been given the same value, which is where the confusion may be.

indeed - this is a GPAC DRM test file, so we crypt keys with a master key equal to the system ID  - cf [doc](https://github.com/gpac/gpac/wiki/Common-Encryption#gpac-drm-format)

> sgpd is written to each media segment, but only segments with KIDs other than that in the tenc has a CENCSampleEncryptionGroupEntry, which seems reasonable as the tenc acts as the default:

yes that's the default in gpac. We might want an option to simply ignore tenc and always inject the KID. This needs further testing with existing deployments I think...

> Changing the <BS ID128="KEY"/> to <BS ID128="KID"/>, i.e. switching from root/leaf to inband key rotation looks to give the same results from this level of examination, so I'm a bit unclear of the difference. 

No that's switching the mode, maybe I was not very clear ;)

-  To use master/leaf :  you need a DRMInfoTemplate in which you write the KID AND the key, encrypted using the DRMInfoTemplate@key attribute

```
<DRMInfoTemplate version="1" system="6770616363656E6364726D746F6F6C31" KEY="MYMASTERKEYHEX">
<!-- whatever your DRM system uses as PSSH formating of OPAQUE data (ie, after the KID array of PSSH -->
<!-- here we assume only the key value - the atribute value will be replaced by the key used then encrypted with MYMASTERKEYHEX before serialization of the PSSH -->
<BS ID128="KEY"/>
</DRMInfoTemplate>
```


- To use  key roll,  you need a DRMInfoTemplate in which you only list the kid, which is injected by default if DRMInfoTemplate@version is 1 (pssh.version==1).

```
<DRMInfoTemplate version="1" system="6770616363656E6364726D746F6F6C31" >
<!-- whatever your DRM system uses as PSSH formating of OPAQUE data (ie, after the KID array of PSSH -->
<!-- here we assume nothing (out of band fetch of the key) -->
</DRMInfoTemplate>
```

(obviously in both cases you want to use `keyRoll` attribute for your track).

**Comment by andyburras** [comment]
I think this is much closer now thanks.
My only query is that the PSSHData from the initialisation segment is also being repeated in the first (but only the 1st) media segment moof? I'd have expected there to just be the relevant KID in the moof's pssh?

**Comment by jeanlf** [comment]
strange - if I check the results of the `encryption-template-roll` test, I can see a pssh version 0 in the init segment and a single pssh with version 1 and KID in the media segment (1st or others).

What is the command line you use to have this behavior ?

**Comment by andyburras** [comment]
Encrypting with:
`mp4box.exe -crypt gpacdrm.xml mezzanine.mp4 -out mezzanine_encrypted.mp4`

DASH with:
`mp4box.exe -rap -dash 2000 -bs-switching no -profile hbbtv1.5.live -pssh v -out out/index.mpd -sample-groups-traf -no-frags-default -tfdt-traf --cmaf=cmfc -single-traf mezzanine_encrypted.mp4#video:period=Period1 stereo_encrypted.mp4#audio:period=Period1 -segment-name $Segment=seg_r$$Init=seg-init_r$$RepresentationID$-$Number$`

GPACDRM is:
```
<?xml version="1.0" encoding="UTF-8" ?>
    <GPACDRM type="CENC AES-CTR">
      <DRMInfo type="pssh" version="0">
        <BS ID128="9a04f07998404286ab92e65be0885f95" />
        <BS bits="32" endian="little" value="846" />
        <BS bits="16" endian="little" value="1" />
        <BS bits="16" endian="little" value="1" />
        <BS bits="16" endian="little" value="836" />
        <BS data64="PABXAFIATQBIAEUAQQBEAEUA[...]" />
      </DRMInfo>
      <DRMInfoTemplate version="1" system="9a04f07998404286ab92e65be0885f95" mode="ctr" KEY="0xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA">
    </DRMInfoTemplate>

      <CrypTrack IsEncrypted="1" IV_size="8" first_IV="0x7DF7C12E832F9726" saiSavedBox="senc" keyRoll="samp=100">
    <key KID="0x11111111111111111111111111111111" value="0xBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"/>
    <key KID="0x22222222222222222222222222222222" value="0xCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"/>
    <key KID="0x33333333333333333333333333333333" value="0xDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"/>
    </CrypTrack>
    </GPACDRM>

```


Initialisatiom segment:
```
<ProtectionSystemHeaderBox Size="878" Type="pssh" Version="0" Flags="0" Specification="cenc" Container="moov moof meta" SystemID="0x9A04F07998404286AB92E65BE0885F95">
 <PSSHData size="846" value="0x4E0300000100010044[...]"/>
</ProtectionSystemHeaderBox>

```

But first media segment has:

```
<ProtectionSystemHeaderBox Size="898" Type="pssh" Version="1" Flags="0" Specification="cenc" Container="moov moof meta" SystemID="0x9A04F07998404286AB92E65BE0885F95">
 <PSSHKey KID="0x11111111111111111111111111111111"/>
 <PSSHData size="846" value="0x4E0300000100010044[...]"/>
</ProtectionSystemHeaderBox>

```
Subsequent media segments have e.g.:
```
<ProtectionSystemHeaderBox Size="52" Type="pssh" Version="1" Flags="0" Specification="cenc" Container="moov moof meta" SystemID="0x9A04F07998404286AB92E65BE0885F95">
 <PSSHKey KID="0x22222222222222222222222222222222"/>
</ProtectionSystemHeaderBox>

```


I wouldn't have expected the PSSHData to be in the first media segment at all, only the PSSHKey?

**Comment by jeanlf** [comment]
sorry for late follow-up - indeed the PSSH in first seg was injecting the data which was not correct. Now fixed on master
