### ISSUE TITLE
-r framerate calculation length mismatch (super low values)

### ISSUE THREAD

**Issue by Noitarud** [gpac/gpac#2330]
This may be deemed insignificant to bother with - unless you are fastidious.
Ffmpeg -r causes media length to extend and is prominent if value is very low. The audio runs out before video concludes.

Original length is 4m53. At 0.1 FPS the length is 5m20; at 0.2 FPS the length is 5m10.
Original length is 4m15. At 0.1 FPS the length is 4m50; at 0.2 FPS the length is 4m30.
The images in the 0.1 and 0.2 files update at the correct periodicy, but will become faster if I fix the length.

I also notice Ffdshow OSD reports half the frames by end of file that ffmpeg says is present after encoding (27 to 54 for 0.2; 29 to 14 for 0.1 on the second file).

Please be aware media players can become buggy at low FPS.
This is using FFMPEG in recent release.

**Comment by jeanlf** [comment]
this doesn't look like a gpac issue but an ffmpeg one right ?

**Comment by jeanlf** [comment]
closing as this is not related to gpac

**Comment by Noitarud** [comment]
I instaled gpac and ffmpeg.exe is in the subdirectory-!

**Comment by jeanlf** [comment]
I guess your installer is not an official gpac one, we don't distribute ffmpeg.exe in ours.
