### ISSUE TITLE
Chapter titles, character selection

### ISSUE THREAD

**Issue by Noitarud** [gpac/gpac#2332]
I have had some issues with adding in chapters, I will lump them here, I notice no github issues in past cover people's experiences, I presume you could be ignorant.

1. Yes you have to escape some characters (#;), but I attempted adding some and they were omitted even with escaping. Here is a sampling of my disappointments: …’“”/¹²³¼½¾§ (quotes are the slanted types) some seem to be rather elementary (not needing Unicode). The player should be able to show it.
2. I notice limit is 128 long. If this cannot be expanded, perhaps you can look at the bug on the 128th character, though I was using MPC-HC 2013, when you add the last character extra symbols are displayed, I think they differ between files, but are same between chapters. Added characters can be Asian. Maybe a bug in player?
3. The 128 character limit may be reduced to a smaller limit with many(60+) chapters but I couldn't be bothered exploring this, that was for a 339mb audio that is super long. I can submit what I did if you must have it, extract and extend whats there already.
4. I thought I had troubles updating when I tried to use one I applied chapters already, so give that a go if you attempt the above.
5. To save on lines can you allow a global timebase entry. I omit since not convenient as is.

Here is some stuff to get you going. Command:
"C:\Program Files\GPAC\ffmpeg" -i infile -i D:\ADD.txt -map_metadata 1 -codec copy outfile

My generator is a spreadsheet (I paste delimited data from elsewhere), I use Npp to convert tabs to carriage returns. Title length is capped here at a low figure because limit seemed to be less. Material to paste at A3:
`[CHAPTER]	="START="&M3	="END="&M4-1	=LEFT("TITLE="&G3,98)	x	x	Title	x	x	x	x	x	=N3*1000000000	=Q3+P3*60+O3*60*60	0	0	0` GitHub not showing tabs x is blank cell. copy first four columns to Npp.

Here is example add.txt:

;FFMETADATA1
TITLE=Sample
ARTIST=Sample
[CHAPTER]
START=0
END=92999999999
TITLE=ONE
[CHAPTER]
START=93000000000
END=242999999999
TITLE=TWO
[CHAPTER]
START=243000000000
END=444999999999
TITLE=THREE
[CHAPTER]
START=445000000000
END=548999999999
TITLE=FOUR
[CHAPTER]
START=549000000000
END=848999999999
TITLE=FIVE
[CHAPTER]
START=849000000000
END=1272999999999
TITLE=SIX
[CHAPTER]
START=1273000000000
END=1477999999999
TITLE=SEVEN
[CHAPTER]
START=1478000000000
END=1735999999999
TITLE=EIGHT
[CHAPTER]
START=1736000000000
END=2025999999999
TITLE=NINE
[CHAPTER]
START=2026000000000
END=2270499999999
TITLE=TEN

**Comment by jeanlf** [comment]
could you please upload faulty chapter files and the command line used to add them (no need for the media files) ?

**Comment by jeanlf** [comment]
looking at this in details, this look like a ffmpeg issue not a gpac one- we don't have a 128 byte limit for chapter names, and the format you use here is not supported by gpac.
