### ISSUE TITLE
bug report : segmentation fault (core dumped)

### ISSUE THREAD

**Issue by bluewidy** [gpac/gpac#2334]
<img width="465" alt="mediainfo" src="https://user-images.githubusercontent.com/40682277/205034819-d4c0ef9d-12d6-4b67-b13d-60df67ac459b.png">

I tried to remux this mkv to mp4 using the following command `MP4Box -add input.mkv -new output.mp4`
 and it gave me `segmentation fault (core dumped)`

My environment is Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-53-generic x86_64).
And the build I tried was gpac_2.1-DEV-rev523-g4112fc35-master_amd64

**Comment by rbouqueau** [comment]
Am I missing the sample file? You can either upload files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by bluewidy** [comment]
Can you permanently destroy it immediately after confirming it? Because this is copyrighted.

**Comment by rbouqueau** [comment]
Sure.

**Comment by bluewidy** [comment]
Upload complete.

**Comment by bluewidy** [comment]
Sorry but the upload is stuck at 1.06 GB and won't go any further.

**Comment by bluewidy** [comment]
Sorry but the upload is stuck at 1.06 GB and won't go any further.

**Comment by bluewidy** [comment]
https://file.kiwi/qzTzhXZR#dStMpyaMR-q74P9B4r1lVg

The error persists in the v2.3 nightly build. and I tried to attach a file through the link you gave, but an error message appeared saying that the file size limit is exceed. So I am attaching the file through the link above. The file attachment is successful and the error persists to this day, so reopening the issue.

**Comment by aureliendavid** [comment]
Hi, 

I looked into this a bit and I got it to crash on all files that have more than 16 tracks, which was puzzling.

Turns out when we call when calling `avformat_find_stream_info()`  the second argument needs to be an array of `AVDictionnary*` as long as the number of tracks in the file, and instead we pass a pointer to a single `AVDictionnary*` (see http://ffmpeg.org/doxygen/5.0/group__lavf__decoding.html#gad42172e27cddafb81096939783b157bb)

I think the reason it doesn't crash with less than 16 tracks is that, coincidentally, the wrong variable we pass was allocated to 16 times the size of an `AVDictionnary*` so it's ok up to 16 tracks. 

Anyway I'm testing a patch in https://github.com/gpac/gpac/commit/88a70c848231b47530e28cf084f7cccec8d31415 that just creates an array and copies the options we have to all of the elements, I'm not sure it's the right solution (do we want to change the options for different tracks for example?) but it seems to work (it also works with null but I think we want to keep the options?).

<hr >

Other than that we also have a problem with displaying the progress bar when demuxing big files (it goes into an infinite loop). I haven't looked at it much yet but a workaround for now is to use `MP4Box -noprog` to prevent displaying the progress. 

Will update with further tests.

**Comment by aureliendavid** [comment]
@bluewidy > the latest master should fix your import issue, but you may have to add the `-noprog` option for now

can you test it and report back?

a patch for the progress bar is coming

**Comment by bluewidy** [comment]
```
bluewindy@bluewindy:~$ MP4Box -add DV_input.mkv -new DV_input.mkv -noprog
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing Timed Text - Text track 400 x 60 font Serif (size 18) layer 0
Track Importing HEVC - Width 3840 Height 2160 FPS 24/1 SAR 1/1
Track Importing EAC-3 - SampleRate 48000 Num Channels 6
Segmentation fault (core dumped)
bluewindy@bluewindy:~$
```
I followed the guide and upgraded the version using 3 commands: `git pull`, `make`, `make install`. So I tried with the following version `MP4Box - GPAC version 2.3-DEV-rev16-g4ab599224-master`
 And the result is as above. Still getting an error.

**Comment by bluewidy** [comment]
[minisample.zip](https://github.com/gpac/gpac/files/10353795/minisample.zip)
Clips created for easy download.

**Comment by aureliendavid** [comment]
thanks for the test and the samples

I think I see the issue now, a fix is upcoming 

(I only tested on windows before, now fixing on linux too)

**Comment by aureliendavid** [comment]
hi @bluewidy 

the latest master version should now be ok on both windows and linux

it fixes the progress bar issue so the `-noprog` option shouldn't be necessary anymore

can you retest and confirm?

thanks

**Comment by bluewidy** [comment]
Now the error does not occur on Windows and Linux! Thank you very much!

https://user-images.githubusercontent.com/40682277/211318713-76f4a046-96b9-47f3-b1d8-6d79d7539ba0.mp4

By the way, is this the progress bar issue you are referring to? I haven't observed this on Linux. However, it is observed on windows. I downloaded and installed the latest nightly build from this link(https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/), maybe it's because your update is not reflected in this link?

**Comment by aureliendavid** [comment]
yes that is the progress bar issue I mentioned

the windows installers for the new version weren't up yet when I posted earlier, but they are now (rev20 and up, might need to ctrl+f5 the page to see the new ones)
