### ISSUE TITLE
Improve mp4box concatenation

### ISSUE THREAD

**Issue by cconcolato** [gpac/gpac#235]
Current file concatenation with MP4Box has limitations, see:
http://superuser.com/questions/623460/mp4box-and-concatenating-files-with-different-aspect-ratio
http://superuser.com/questions/670541/ffmpeg-concatenating-two-mp4-files-results-in-bad-output-file
http://superuser.com/questions/563063/mp4box-h264-merge-video-files

We should allow for multiple sample description entries or for inband xPS for AVC/HEVC.

**Comment by rbouqueau** [comment]
I need to find the reference, but FFmpeg was "randomly" (i.e. from our perspective) inserting AR information in the SPS on similar streams. So we had added a SPS comparison (xPS hash displayed by 'MP4Box -info').

**Comment by rbouqueau** [comment]
This issue is a duplicate of #13
