### ISSUE TITLE
cmaf video track compliance tkhd/stss

### ISSUE THREAD

**Issue by RufaelDev** [gpac/gpac#2351]
Hi, when packaging a cmaf video track e.g. mp4Box -dash 1000 -out out.mpd --cmaf=cmfc vvc_8b_bt709-ClosedGOP-3840x2160-24fps-60s-4Mbps.mp4 the mp4 file written is not fullly cmaf compliant namely: 

the stss box absent (cmaf mention this shall be present if not all samples are sync samples which is not the case for this video track) 
tkhd flags shall be 0x000007  (23000-19 9.2) for video tracks , it is set to 3 in my test file.

It would be great if these can be fixed to improve the CMAF compliance, thank you

**Comment by jeanlf** [comment]
could you please upload a test file reproducing the issue ?

**Comment by cconcolato** [comment]
I just tested a build from tip of tree. I tried the enst_video.264 from the testsuite. I also tried with an AV1 file. I confirm that the `stss` box is absent but the flags is correctly set to 7.

**Comment by jeanlf** [comment]
flags were fixed some time ago - added stss when cmaf option is set, thanks for the report.

**Comment by RufaelDev** [comment]
@jeanlf and @cconcolato thanks for the quick handling of this!
