### ISSUE TITLE
Segmentation fault when using MP4Box to generate MPD with key-frames encrypted MP4s

### ISSUE THREAD

**Issue by delbinwen** [gpac/gpac#236]
Hi,

We use MP4Box to encrypt MP4 files and then use MP4Box to generate MPD. It worked very well. We recently met an performance issue on one device when playing encrypted MPEG-DASH stream. So we would like to try to encrypt key frames (RAP) only instead of all samples.

According to the [documentation] (https://gpac.wp.mines-telecom.fr/mp4box/encryption/common-encryption/), we add selectiveType and set it to "RAP". There is no error when calling MP4Box -crypt, but segmentation fault occurred when calling MP4Box -dash.

Could someone help this?

Thanks,
Wesley

**Comment by cconcolato** [comment]
I cannot reproduce the problem using the drm_file_rap.xml from https://gpac.wp.mines-telecom.fr/mp4box/encryption/common-encryption/. Can you provide an example of encrypted file ?

**Comment by rbouqueau** [comment]
Can we close?
