### ISSUE TITLE
Website: Downloads pages need revisions

### ISSUE THREAD

**Issue by facorread** [gpac/gpac#2362]
Hi all,

As you continue working towards publishing version 2.2 to the GPAC website, please take a moment to review your code for the Legacy builds page; the Markdown tag `textimport` was not interpreted by your platform. Check out the screenshot:

https://gpac.wp.imt.fr/downloads/gpac-legacy-builds/

![image](https://user-images.githubusercontent.com/127711/208478793-b83f8e03-2283-4d22-a90d-c6920fa01090.png)

Just as a side note, the Downloads page is still showing v2.0, even though the 2.2 announcement is already published on the website. I am not sure if you are still building the v2.2 downloads page somehow.

https://gpac.wp.imt.fr/2022/12/19/gpac-2-2/
https://gpac.wp.imt.fr/downloads/

![image](https://user-images.githubusercontent.com/127711/208479375-c1c7c8c0-a0ef-4be0-9283-ee8b754a109c.png)

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...).

**Comment by jeanlf** [comment]
be patient :)

build is in progress on 2.2 - cf https://buildbot.gpac.io/#/grid

Installers will be up within the hour.

**Comment by aureliendavid** [comment]
the legacy downloads page was indeed broken, it should now be ok 

the 2.2 links will be up asap

**Comment by aureliendavid** [comment]
links are up
