### ISSUE TITLE
mp4Box incorrect sap type in segment index box and mpd

### ISSUE THREAD

**Issue by RufaelDev** [gpac/gpac#2370]
when trying to create a file with video that has negative composition time offsets:

mp4Box -dash 1000 -out out.mpd -dash-profile onDemand --cmaf=cmfc vvc_uhd2_hdr-ClosedGOP-7680x4320_50fps-HLG10-30s-12Mbps.mp4  

the segment index box signals SAP_type=1 and the mpd signal subsegmentStartsWithSAP="1" 

This should for this specific file be 2, as the first decoded sample is not the first one displayed.

also it may be easier to always signal 2 for dash as sap type 1 is a subset of sap type 1. 

My suggestion is to put the correct SapType in the mpd and segment index or always put 2

**Comment by RufaelDev** [comment]
hello @jeanlf i uploaded both files:

https://www.mediafire.com/file/hce9ia538hljbvq/vvc_8b_bt709-ClosedGOP-3840x2160-24fps-60s-4Mbps_dashinit.mp4/file
https://www.mediafire.com/file/zbhp196stiklh0y/out.mpd/file 

Also i noticed (I am helping with the creation of test files for DVB), that timing of sidx is also not correct corresponding with mp4 fragment timing, e.g.

subsegment_duration=0 (which is incorrect in the sample files), I have also seen other files where sidx timing is off, i can create a separate issue if needed.

**Comment by jeanlf** [comment]
hmm link for the media file is showing "upload still in progress" after 12+ hours, could you cross-check the link ?

**Comment by RufaelDev** [comment]
could not get it to work please see it here: 

https://drive.google.com/file/d/1WwIADkFBKEjvGvYoHaoD7kFJ-tgTGd8R/view?usp=sharing

**Comment by jeanlf** [comment]
@RufaelDev thanks for the file - this should now be fixed on master, could you cross-check ?

Also if you find problems on sap_delta_time signaling in sidx, could you please open a new issue (and post test files) ?

**Comment by RufaelDev** [comment]
@jeanlf thank you i will check it, in mean time i created an issue:
https://github.com/gpac/gpac/issues/2377 for the sidx timing inconsistency.

**Comment by jeanlf** [comment]
closing this as fixed in master, reopen if still broken with other streams.
