### ISSUE TITLE
How to install gpac on Docker container?

### ISSUE THREAD

**Issue by AhmedAbouelkher** [gpac/gpac#2372]
Hi,
I'm using docker to scale my service and I need `gpac` as a dependency just like `FFmpeg`, but I couldn't install the latest [gpac](https://gpac.wp.imt.fr/downloads/) on my docker container.

I'm using `amd64/debian:11` from [here](https://hub.docker.com/r/amd64/debian/) and installing the dependencies mentioned in your [GPAC Build Guide for Linux](https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux) guide here, to make sure that I have all the required dependencies.

```dockerfile
FROM amd64/debian:11

WORKDIR /app

# Install dependencies
RUN apt-get update
RUN apt-get install gdebi zlib1g-dev libfreetype6-dev libjpeg62-turbo-dev libpng-dev libmad0-dev libfaad-dev libogg-dev libvorbis-dev libtheora-dev liba52-0.7.4-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavdevice-dev libxv-dev x11proto-video-dev libgl1-mesa-dev x11proto-gl-dev libxvidcore-dev libssl-dev libjack-dev libasound2-dev libpulse-dev libsdl2-dev mesa-utils -y

COPY ./gpac_2.0.0.deb ./gpac.deb
RUN apt-get update && \
  apt-get install ./gpac.deb

CMD ["pwd"]
```
When building the image, All the dependencies are installed successfully, but it fails to install `gpac` due to _missing dependencies_. 
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gpac : Depends: libavcodec57 (>= 7:3.4.8) but it is not installable or
                 libavcodec-extra57 (>= 7:3.4.8) but it is not installable
        Depends: libavdevice57 (>= 7:3.4.8) but it is not installable
        Depends: libavfilter6 (>= 7:3.4.8) but it is not installable or
                 libavfilter-extra6 (>= 7:3.4.8) but it is not installable
        Depends: libavformat57 (>= 7:3.4.8) but it is not installable
        Depends: libavutil55 (>= 7:3.4.8) but it is not installable
        Depends: libswscale4 (>= 7:3.4.8) but it is not installable
```

I created a new Linode `Debian 11` VM to test this issue and tried to install [gpac](https://gpac.wp.imt.fr/downloads/) directly without any dockerization, it worked without any issue!

I really want this fixed, Any help will be appreciated.

_Note_
```bash
apt-get install gpac -y
```
Using `apt` to install gpac is what I used to have, but I need the latest release of gpac to fix some issues and avoid deprecated APIs.

**Comment by rbouqueau** [comment]
@aureliendavid Wouldn't it be simpler for the users to regenerate their own .deb in this case?

**Comment by AhmedAbouelkher** [comment]
> @aureliendavid Wouldn't it be simpler for the users to regenerate their own .deb in this case?

I believe you are correct and that's what I will work on, but for not I found a possible working solution.
```dockerfile
FROM amd64/debian:11

WORKDIR /usr/src/app

# Install dependencies
RUN apt-get update && \
  apt-get install -y libnghttp2-14 dpkg wget && \
  apt-get install -y zlib1g-dev libfreetype6-dev libjpeg62-turbo-dev libpng-dev libmad0-dev libfaad-dev libogg-dev libvorbis-dev libtheora-dev liba52-0.7.4-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavdevice-dev libxv-dev x11proto-video-dev libgl1-mesa-dev x11proto-gl-dev libxvidcore-dev libssl-dev libjack-dev libasound2-dev libpulse-dev libsdl2-dev dvb-apps mesa-utils && \
  wget -O gpac.deb https://download.tsi.telecom-paristech.fr/gpac/release/2.2/gpac_2.2-rev0-gab012bbf-master_amd64.deb && \
  dpkg -i ./gpac.deb && \
  apt-get install -f

CMD [ "pwd" ]
```

This solution did work without any issues. I will comment the Dockerfile configs for building the binary from scratch as soon as I finish it.
