### ISSUE TITLE
Multiplexing Dolby Vision Profile 5

### ISSUE THREAD

**Issue by arxivariys** [gpac/gpac#2373]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [v] I looked for a similar issue and couldn't find any.
- [v] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [v] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox

Problem 1:
When multiplexing Dolby Vision profile 5 with netflix, I encountered a problem that mp4box does not multiplex the video file correctly
Command:
- mp4box -brand mp42isom -ab dby1 -no-iod --xps_inband=all -add G:\dv.hevc -add G:\1.eac3:lang=en:name=Original -add G:\eng1.srt:disable:lang=en:name=full -add G:\eng2.srt:disable:lang=en:name=SDH -new G:\dv5full.mp4

Original file:
- Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5@Main
HDR format                               : Dolby Vision, Version 1.0, dvhe.05.06, BL+RPU
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 2 h 21 min
Bit rate                                 : 18.6 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 24.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.094
Stream size                              : 18.4 GiB (96%)
Default                                  : Yes
Forced                                   : No
Color range                              : Full

Received file:
- Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5@Main
HDR format                               : Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, SDR compatible
Codec ID                                 : hev1
Codec ID/Info                            : High Efficiency Video Coding
Duration                                 : 2 h 21 min
Bit rate                                 : 18.6 Mb/s
Maximum bit rate                         : 41.8 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 24.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.094
Stream size                              : 18.4 GiB (96%)
Title                                    : hevc@GPAC2.3-DEV-rev23-g5a733aec-master
Encoded date                             : UTC 2023-01-14 20:52:52
Tagged date                              : UTC 2023-01-14 20:56:21
Color range                              : Limited
colour_range_Original                    : Full
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
mdhd_Duration                            : 8461125
Codec configuration box                  : hvcC+dvvC

Problem 2:
Since when multiplexing, an incorrect file is immediately obtained, according to the info file, I initially use mp4muxer https://github.com/DolbyLaboratories/dlb_mp4base
Command:
mp4muxer -i G:\dv.hevc --media-lang eng -o G:\dv5.mp4 --dv-profile 5
mp4box -brand mp42isom -ab dby1 -no-iod --xps_inband=all -add G:\dv5.mp4 -add G:\1.eac3:lang=en:name=Original -add G:\eng1.srt:disable:lang=en:name=full -add G:\eng2.srt:disable:lang=en:name=SDH -new G:\dv5full.mp4,
Info file of received file:
General
Complete name                            : G:\dv5full.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (isom/mp42/dby1)
File size                                : 19.1 GiB
Duration                                 : 2 h 21 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 19.4 Mb/s
Encoded date                             : UTC 2023-01-14 22:10:56
Tagged date                              : UTC 2023-01-14 22:10:56
Writing application                      : GPAC-2.3-DEV-rev23-g5a733aec-master

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5@Main
HDR format                               : Dolby Vision, Version 1.0, dvhe.05.06, BL+RPU
Codec ID                                 : dvhe
Codec ID/Info                            : High Efficiency Video Coding with Dolby Vision
Duration                                 : 2 h 21 min
Bit rate                                 : 18.6 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 24.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.094
Stream size                              : 18.4 GiB (96%)
Language                                 : English
Default                                  : Yes
Alternate group                          : 1
Encoded date                             : UTC 2023-01-14 21:37:51
Tagged date                              : UTC 2023-01-14 22:15:20
Color range                              : Full
mdhd_Duration                            : 8461125
Codec configuration box                  : hvcC+dvcC

Audio
ID                                       : 2
Format                                   : E-AC-3 JOC
Format/Info                              : Enhanced AC-3 with Joint Object Coding
Commercial name                          : Dolby Digital Plus with Dolby Atmos
Codec ID                                 : ec-3
Duration                                 : 2 h 21 min
Bit rate mode                            : Constant
Bit rate                                 : 768 kb/s
Maximum bit rate                         : 811 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 775 MiB (4%)
Title                                    : Original
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Alternate group                          : 1
Encoded date                             : UTC 2023-01-14 22:15:12
Tagged date                              : UTC 2023-01-14 22:15:20
Complexity index                         : 16
Number of dynamic objects                : 15
Bed channel count                        : 1 channel
Bed channel configuration                : LFE

Text #1
ID                                       : 3
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 2 h 10 min
Bit rate mode                            : Variable
Bit rate                                 : 87 b/s
Frame rate                               : 0.524 FPS
Stream size                              : 83.3 KiB (0%)
Title                                    : full
Language                                 : English
Default                                  : No
Forced                                   : No
Encoded date                             : UTC 2023-01-14 22:15:20
Tagged date                              : UTC 2023-01-14 22:15:20

Text #2
ID                                       : 4
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 2 h 13 min
Bit rate mode                            : Variable
Bit rate                                 : 98 b/s
Frame rate                               : 0.584 FPS
Stream size                              : 95.5 KiB (0%)
Title                                    : SDH
Language                                 : English
Default                                  : No
Forced                                   : No
Encoded date                             : UTC 2023-01-14 22:15:20
Tagged date                              : UTC 2023-01-14 22:15:20

If you play the received file using Plex or from a NAS via DLNA, then sound problems begin from 5-6 minutes (the sound starts to stutter). With other videos from other streaming services, I did not notice such a problem.

**Comment by jeanlf** [comment]
could you upload a fault dv profile 5 file ?

**Comment by arxivariys** [comment]
> could you upload a fault dv profile 5 file ?

Of course
mkv - https://disk.yandex.ru/i/gVsVuFNMU5ayCA
mp4box - https://disk.yandex.ru/i/FHwPAnS2ZXNPUA
mp4muxer + mp4box - https://disk.yandex.ru/d/s1h3tYQ9cF9jPw

**Comment by jeanlf** [comment]
ok that's what I thought: the file uses dv5 except for the last minute or so (translator credits) where it moves to dv8. This results in overwriting the profile from 5 to 8...

I added a flag (`--dvsingle`) to skip this last profile change, might need further rework though...
