### ISSUE TITLE
I am using gpac python as the DASH client. Is there a way I can know the frame arrival rate or the timestamp for receiving each frame? 

### ISSUE THREAD

**Issue by ushasigh** [gpac/gpac#2376]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
timestamps are available as dts and cts properties of received packets in your custom filter, cf python inspector - https://github.com/gpac/gpac/wiki/python#custom-sink-example

on non-custom filters, you can query filter stats using get_statistics() and check the last_ts_sent and last_ts_drop in the returned statistics object - note that these stats are not yet available in ipid_stats() or opid_stats() , I'll add that asap.
