### ISSUE TITLE
Filter to aggregate with respect to segments

### ISSUE THREAD

**Issue by pratikbendre86** [gpac/gpac#2379]
Currently I have been using tileagg to aggregate the input Tiled DASH stream into a single video output. I further need to carry on some processing on each of the frame observed. However i need to do this segment wise. So is there a way to aggregate each segment of the incoming DASH stream separately? Say an .mpd file with 3 segments of 2s should produce 3 HEVC streams instead of one 6 sec stream.

**Comment by rbouqueau** [comment]
I don't think you can. But you can generate an independent file for each segment. Either:
 - concatenate the init segment with any segment (i.e. ```cat init.mp4 seg_x.m4s > file_x.mp4```); or
 - use the ```-init-seg``` option of MP4Box.

**Comment by jeanlf** [comment]
additionally:
- use initseg of [mp4dmx](https://github.com/gpac/gpac/wiki/mp4dmx#initseg) to parse each segment:
```gpac -i segment.m4s --initseg=seg_init.mp4 ...```

- to store segments directly as dedicated files, use segment boundary signaling from the dash demuxer together with output file templating (independent of muxing format, so would work for raw stream extract as well):
```gpac -i DASH_URL --forward=segb -o res/file_$num$.mp4```

-  within the filter chain (if you need your processing to happen on the fly in a custom filter), provided you used  `--forward=segb`as above, you can monitor the segment bounds by querying the property `FileNumber` on input packets: when present, this marks the start of a segment.

See [segment bounds forwarding](https://github.com/gpac/gpac/wiki/dashin#segment-bound-modes) on wiki
