### ISSUE TITLE
Allow audio track selection from the player GUI 

### ISSUE THREAD

**Issue by cconcolato** [gpac/gpac#238]
It should be possible in the GUI of MP4Client to select which audio track to play when there are multiple tracks. Ideally information such as language (from the track header and the extended language box), kind (from the kind box), and other metadata should be exposed to make the choice. An example file is : http://perso.telecom-paristech.fr/~concolat/html5_tests/count_audio.mp4

**Comment by jeanlf** [comment]
this was added a while ago
