### ISSUE TITLE
When remuxing mkv to mp4, the Dolby Vision metadata is stripped and the video and audio metadata are mixed together.

### ISSUE THREAD

**Issue by bluewidy** [gpac/gpac#2380]
This phenomenon is bizarre.  If you look directly at the attachment you will know what I am talking about. I used the latest nightly build `MP4Box - GPAC version 2.3-DEV-rev31-g9971fb125-master` , and this is the footage I used for testing.
[minisample.zip](https://github.com/gpac/gpac/files/10442010/minisample.zip)

And this is information output through the MediaInfo tool.
[minisample_MediaInfo.zip](https://github.com/gpac/gpac/files/10442045/minisample_MediaInfo.zip)

As you can see, the bitrate descriptions for video and audio seem to be interchanged. And the Dolby Vision metadata is also gone.

**Comment by jeanlf** [comment]
I think that's a pb of your mediainfo tool, using mediainfo on osx (MediaInfoLib - v22.09) does not show this.
