### ISSUE TITLE
Track duration changes when remuxing from mkv to mp4

### ISSUE THREAD

**Issue by mohd-akram** [gpac/gpac#2381]
The audio duration seems to change when remuxing an MKV file to MP4.

[Sample](https://github.com/gpac/gpac/files/10442010/minisample.zip) (borrowed from gpac/gpac#2380).
Tested with gpac bbca869177585aaca8eb66d8541079e6f364798e on macOS 12.6.2

Command: `MP4Box -new -brand mp42 -ab dby1 -add minisample.mkv minisample.mp4`

MKV MediaInfo (audio):

```
Audio
ID                                       : 2
Format                                   : E-AC-3 JOC
Format/Info                              : Enhanced AC-3 with Joint Object Coding
Commercial name                          : Dolby Digital Plus with Dolby Atmos
Codec ID                                 : A_EAC3
Duration                                 : 9 s 120 ms
Bit rate mode                            : Constant
Bit rate                                 : 768 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Delay relative to video                  : 16 ms
Stream size                              : 855 KiB (5%)
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No
Complexity index                         : 16
Number of dynamic objects                : 15
Bed channel count                        : 1 channel
Bed channel configuration                : LFE
```

MP4 Mediainfo (audio):

```
Audio
ID                                       : 2
Format                                   : E-AC-3 JOC
Format/Info                              : Enhanced AC-3 with Joint Object Coding
Commercial name                          : Dolby Digital Plus with Dolby Atmos
Codec ID                                 : ec-3
Duration                                 : 10 s 607 ms
Source duration                          : 10 s 592 ms
Source_Duration_LastFrame                : 1 s 504 ms
Bit rate mode                            : Constant
Bit rate                                 : 768 kb/s
Maximum bit rate                         : 811 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 993 KiB (6%)
Source stream size                       : 852 KiB (5%)
Title                                    : mkv@GPAC2.3-DEV-rev35-gbbca86917-master
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Alternate group                          : 1
Encoded date                             : UTC 2023-01-20 11:34:32
Tagged date                              : UTC 2023-01-20 11:34:32
Complexity index                         : 16
Number of dynamic objects                : 15
Bed channel count                        : 1 channel
Bed channel configuration                : LFE
```

There's also a slight change in the video duration:

MKV Mediainfo (video):

```
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5@Main
HDR format                               : Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2086, HDR10 compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 9 s 125 ms
Bit rate                                 : 14.2 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 24.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.071
Stream size                              : 15.4 MiB (95%)
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0001 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 756 cd/m2
Maximum Frame-Average Light Level        : 115 cd/m2
```

MP4 Mediainfo (video):

```
Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5@Main
HDR format                               : Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2086, HDR10 compatible
Codec ID                                 : hvc1
Codec ID/Info                            : High Efficiency Video Coding
Duration                                 : 9 s 123 ms
Source duration                          : 9 s 121 ms
Bit rate                                 : 14.2 Mb/s
Maximum bit rate                         : 19.6 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 24.000 FPS
Minimum frame rate                       : 23.810 FPS
Maximum frame rate                       : 24.390 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.071
Stream size                              : 15.4 MiB (95%)
Source stream size                       : 15.4 MiB (95%)
Title                                    : mkv@GPAC2.3-DEV-rev35-gbbca86917-master
Language                                 : English
Encoded date                             : UTC 2023-01-20 11:34:32
Tagged date                              : UTC 2023-01-20 11:34:32
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0001 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 756 cd/m2
Maximum Frame-Average Light Level        : 115 cd/m2
mdhd_Duration                            : 9205
Codec configuration box                  : hvcC+dvvC
```

**Comment by bluewidy** [comment]
and don't the colors look weird when you look at the output mp4 video?

**Comment by bluewidy** [comment]
I used a Samsung Galaxy Note 20 Ultra. This is a display that supports HDR10 and HDR10+.

**Comment by jeanlf** [comment]
have you tried the resulting mp4 file on another display ?

also have you tried forcing DV sample entry codes (add `--force_dv`) so that the video type is `vide:dvh1' ?

**Comment by bluewidy** [comment]
> also have you tried forcing DV sample entry codes (add `--force_dv`) so that the video type is `vide:dvh1' ?
When I do that it repeats the hdr format metadata
[minisample.mp4.txt](https://github.com/gpac/gpac/files/10922381/minisample.mp4.txt)
.

**Comment by bluewidy** [comment]
A minisample is a 9-second cutout of the original video. 
I tried this on the original video and the HDR metadata is abnormally reconstructed.

**Comment by jeanlf** [comment]
the repeated format is just a mediainfo thing

> I tried this on the original video and the HDR format metadata is abnormally reconstructed.

could you share a longer sample showing the issue ?

**Comment by bluewidy** [comment]
https://bluewindy.kro.kr/filebrowser/share/-c7AYH9P
Okay. This is original. Downloads are only available for 24 hours from now.

**Comment by jeanlf** [comment]
I cannot access the link ...

**Comment by bluewidy** [comment]
Oops... okay, I upload it again
https://bluewindy.kro.kr/filebrowser/share/7rvNFWcT

**Comment by jeanlf** [comment]
hmm, here (gpac latest 2.3-DEV-rev52-g1f3f992d8-master, MediaInfoLib - v22.09) , doing:

```
MP4Box -new -brand mp42 -ab dby1 -add Fullsample.mkv -new rmx.mp4 --force_dv
```

gives

```
% mediainfo rmx.mp4
[...]
Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5@Main
HDR format                               : Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2086, HDR10 compatible
Codec ID                                 : dvh1
Duration                                 : 58 min 21 s
Bit rate                                 : 9 242 kb/s
Maximum bit rate                         : 47.3 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 24.000 FPS
Minimum frame rate                       : 23.810 FPS
Maximum frame rate                       : 24.390 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.046
Stream size                              : 3.77 GiB (92%)
Title                                    : mkv@GPAC2.3-DEV-rev52-g1f3f992d8-master
Language                                 : English
Encoded date                             : UTC 2023-03-10 17:19:15
Tagged date                              : UTC 2023-03-10 17:19:31
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0001 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 756 cd/m2
Maximum Frame-Average Light Level        : 97 cd/m2
mdhd_Duration                            : 3502163
Codec configuration box                  : hvcC+dvvC
[...]
```

I can't see any repeated info as in your sample... Could you upload the result of `MP4Box -disox REMUX.mp4` ?

**Comment by bluewidy** [comment]
I want to try using rev52 .  Can you provide rev52 please?
![Screenshot_20230311_122931_Chrome](https://user-images.githubusercontent.com/40682277/224462671-0ab39347-0f8e-41a5-9f02-57775b99e60b.jpg)

**Comment by aureliendavid** [comment]
> I want to try using rev52 . Can you provide rev52 please?

Hi, 

There was an issue uploading the latest releases, it's now fixed, you can find rev52+ at the usual location, thanks for the report.

**Comment by jeanlf** [comment]
I was able to reproduce the duplication using the test file in #2373, now fixed on master.

**Comment by bluewidy** [comment]
It still loops in my Fullsample.mkv. I tried rev 58.
Here is my result.
https://bluewindy.kro.kr/filebrowser/share/sAAj8BVL

**Comment by bluewidy** [comment]
duplication

**Comment by jeanlf** [comment]
using latest master and 
```
-new -brand mp42 -ab dby1 -add Fullsample.mkv rmx.mp4
```
 
gives

```
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5@Main
HDR format                               : Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2086, HDR10 compatible
Codec ID                                 : hvc1

```
(no repeat)

same when using `--force_dv` option.

Have you changed your command line ?

**Comment by bluewidy** [comment]
I tried using your command line and the metadata still repeats. I used 2.3-DEV-rev58-gedaca299-master. Isn't this the latest?
and your environment is Mac, right?  I'm on Ubuntu 22.04.2 LTS. and my ffmpeg version is 5.1.1-static https://johnvansickle.com/ffmpeg/

**Comment by bluewidy** [comment]
https://user-images.githubusercontent.com/40682277/224921245-7075b852-98fb-499f-bc2a-513683458901.mp4

I tried to uninstall ffmpeg but something is wrong.  ffmpeg could not be found on the system.

**Comment by rbouqueau** [comment]
Type ```which ffmpeg``` in your terminal to know where it is located.

**Comment by bluewidy** [comment]
Found it. Thank you!

**Comment by jeanlf** [comment]
I finally got to the bottom of this: mkv+dovi support depends on ffmpeg versions:
- old ffmpeg: no dovi from mkv, we trigger a full reparse of the video stream, resulting in 6 different sample descritpion entries (6 different PPS are used in your stream)
- new ffmpeg: we trust (and maybe shouldn't) the mkv and use its dovi config, resulting in a single entry but some samples end up with PPS which is not really compliant.

Forcing a clean reparse of mkv (`-add src.mkv --reparse`) produces the same "duplication". Note that the file is legit, it's just that mediainfo reports one dovi config for each sample description.

One way to avoid this is to move to inband param sets (`--xps_inband=all` or `--xps_inband=both`) but some players/devices might bug on inband params (note that some others might bug on multiple sample descriptions...)

**Comment by bluewidy** [comment]
So it's an ffmpeg problem, right?  Which ffmpeg do you recommend?

**Comment by jeanlf** [comment]
> So it's an ffmpeg problem, right? Which ffmpeg do you recommend?

I would recommend that , independently of ffmpeg's version, you do a full reparse of the media (`-add src.mkv --reparse`) if you don't use inband param sets - the file may have multiple sample descriptions for the video track, but that is to be expected (and mediainfo will print multiple times the DV info).

If you use inband parameter set, you can skip the reparsing of the media.

**Comment by bluewidy** [comment]
One thing that puzzled me is that mp4box is executable after removing ffmpeg. What happens when mp4box doesn't reference the system's ffmpeg? And after installing ffmpeg, what do I need to do to make it reference ffmpeg on my system?

**Comment by jeanlf** [comment]
> mp4box is still executable after removing ffmpeg

this means mp4box was linked against a static ffmpeg build. If it were linked against a shared build of ffmpeg, removing ffmpeg will break mp4box (and installing a new ffmpeg will also likely break...)

**Comment by rbouqueau** [comment]
You can do ```ldd `which MP4Box``` and see if the libav*.so dynamic libraries are still resolved.

**Comment by bluewidy** [comment]
yes you are right. The dynamic library is still running. Thanks!
> --xps_inband=all
I used the parameters you mentioned and no more repetitions. Thank you for your help in resolving the issue.

**Comment by bluewidy** [comment]
![Screenshot_20230315_000924_MediaInfo](https://user-images.githubusercontent.com/40682277/225046159-41315223-88fb-40b0-9777-be69f1c5c57b.jpg)

Can I report one more thing? I never assigned a title.  However, the title is always forced to the GPAC version.

**Comment by jeanlf** [comment]
this is the default behaviour yes. Use `-add SRC:name="My Name"` to change that

**Comment by bluewidy** [comment]
But what I want is the title to be undefined. I.e, is it possible to prevent mediainfo from detecting the title?

**Comment by jeanlf** [comment]
use an empty string at import, e.g. `-add SRC:name="" `

**Comment by bluewidy** [comment]
Thank you 😊
