### ISSUE TITLE
Potential memory leak in src/filters/ff_mx.c

### ISSUE THREAD

**Issue by icy17** [gpac/gpac#2383]
Potential memory leak in [ff_mx.c](https://github.com/gpac/gpac/blob/master/src/filters/ff_mx.c#L373) line 373. Calling av_dict_copy() without calling av_dict_free() to free the memory will cause a memory leak.[Doc](https://ffmpeg.org/doxygen/trunk/group__lavu__dict.html#ga1bafd682b1fbb90e48a4cc3814b820f7) says "av_dict_free() Free all the memory allocated for an [AVDictionary](https://ffmpeg.org/doxygen/trunk/structAVDictionary.html) struct and all keys and values."
![image](https://user-images.githubusercontent.com/39425646/214762607-08c18e82-4fa0-4992-81ac-93b238b67736.png)

**Comment by aureliendavid** [comment]
you're right, although ironically this can only happen if we're already out of memory (at which point the program will exit anyway), but still

will fix it next week when i'm back from vacation, thanks for reporting
