### ISSUE TITLE
Implement the W3C Clear Key DRM System

### ISSUE THREAD

**Issue by cconcolato** [gpac/gpac#239]
The player should support the [ClearKey DRM system](https://w3c.github.io/encrypted-media/#clear-key) as defined by the W3C EME Spec. Some documentation is available by Cable Labs [here](https://html5.cablelabs.com/mse-eme/doc/creation.html#encryption) and a tool to generate the ClearKey crypt file is [here](https://github.com/cablelabs/mse-eme).

**Comment by lenny0702** [comment]
Is there any progress here? Or could someone give some alternatives to let me encrypt video by using ClearKey DRM system? 
Because all the page link in the question are already 404. I am really stuck in here. Really appreciate if someone can help me.

**Comment by cconcolato** [comment]
You might want to check https://nougat.cablelabs.com/Innovation/mse-eme

**Comment by jeanlf** [comment]
key fetching is outside the scope of the player (but can be done through JS), we will not add this support.
