### ISSUE TITLE
Generating HEIC from still video sequence frame and depth buffer ?

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [gpac/gpac#2392]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [* ] I looked for a similar issue and couldn't find any.
- [**X** ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/

**Sorry people. My bad. I thought I had latest copy using “brew”. Have now found your nightly and am retesting. Apologies.**

- [* ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

—

Hi. This is on latest macOS (Ventura) with gpac/mp4box installed via home-brew.

I’m needing to create HEIC images from source animation frames and depth buffer produced by Mandelbulber (see attached images) for Apple Object Capture.

For my initial testing I converted the png’s to HEIC using macOS Quick Action —> Convert.

I’m using. …

`mp4box -add-image frame_0000000.heic:primary -add-image frame_0000000_zbuffer.heic:depth:ref=auxl:1 -ab heic -new img.heic`

But get error …

```
No sample found for requested time

	Error: Bad Parameter
```

I’m aware that I could make a lossless HEVC video from my source animation frames, one for the colour images and another with the depth buffer frame (just trying to avoid that step to keep things simple).I’m not familiar with HEVC. Would I be able to make lossless video that would retain all the source image data ? Otherwise is it possible to define the use of a still image frame file for mp4box ?

![frame_0000000_zbuffer](https://user-images.githubusercontent.com/951566/216994371-cec2dca1-f337-4506-a374-5ca878bb176a.png)
![frame_0000000](https://user-images.githubusercontent.com/951566/216994403-2b3e8091-cda8-4f36-a636-39463fd63e4a.png)

**Comment by Michael-Z-Freeman** [comment]
Hi. I now realise that the input needed to be in x265/HEVC format. So I created primary and depth input using Apple Compressor. I now use …

```
michaelzfreeman@Michaels-MacBook-Air.local
~/Temp/test
$ mp4box -add-image frame.m4v:primary -add-image depth.m4v:ref=auxl:depth -brand heic -new img.heic
IsoMedia import frame.m4v - track ID 1 - Video (size 1920 x 1080)
Adding sample at time 0.000 as item 1                     
Adding sample at time 0.000 as item 2
Saving img.heic: 0.500 secs Interleaving
```

However a test shows …

```
michaelzfreeman@Michaels-MacBook-Air.local
~/Temp/test
$ heif-info img.heic 
MIME type: image/heic
main brand: heic
compatible brands: mif1, heic

Could not read HEIF/AVIF file: Invalid input: Non-existing item ID referenced: Non-existing depth image referenced
```

Even though mp4box shows …

```
michaelzfreeman@Michaels-MacBook-Air.local
~/Temp/test
$ mp4box -info img.heic 
# File Meta type: "pict" - 3 resource item(s)
Primary Item - ID 1
Item #1: ID 1 type hvc1 size 1920x1080 SAR 1/1 3 channels (8 bpc)
Item #2: ID 2 type hvc1 size 1920x1080 SAR 1/1 1 channel (8 bpc)

File has no movie (moov) - static data container
```

It’s as if the second depth buffer image is never added. mp4box reports "IsoMedia import frame.m4v - track ID 1 - Video (size 1920 x 1080)” but never reports anything about “depth.m4v”.

https://files.michaelzfreeman.org/frame.m4v

https://files.michaelzfreeman.org/depth.m4v

**Comment by Michael-Z-Freeman** [comment]
OK, apologies for not having originally found the similar issue - "[Looking for a way to create an HEIC file with depth map, just like the ones saved by iOS api](https://github.com/gpac/gpac/issues/2022)”.

I am now able to replace the primary image and depth map using the test image provided in the issue above …

`MP4Box -add-image depth.m4v:ID=38:replace:keep_props=auxC IMG_0090.HEIC -out IMG_0090_new.HEIC`

`MP4Box -add-image frame.m4v:primary:ID=36:replace IMG_0090_new.HEIC -out IMG_0090_new-with-primary.HEIC`

I can then verify the images are in there by extracting with …

`heif-convert --with-aux IMG_0090_new-with-primary.HEIC IMG_0090_new-with-primary.jpg`

However the thumbnail for the HEIC file no longer shows in file manager GUI. Don’t need a thumbnail really. However do I need to rebuild the grid of images with mp4box ?

I also wonder why these commands don’t work on an image converted to HEIC using MacOS built in conversion tool ? I guess there is a shed load of extra stuff in the HEIC  produced by the iPhone camera that is not added when converting to HEIC in MacOS ? Reason I ask is that I can now see how to convert from my original series of frames to HEIC by modifying an HEIC test image from the iPhone itself using the above commands. However is there a simpler way ? Can I just add the missing HEIC data using mp4box to a fresh HEIC image ? Cheers.

**Comment by jeanlf** [comment]
> However the thumbnail for the HEIC file no longer shows in file manager GUI. Don’t need a thumbnail really. However do I need to rebuild the grid of images with mp4box ?

You are replacing a grid item with a native item, however the replace command keeps all item references in place. The resulting file is no longer compliant and does not show any thumbnail in finder. Removing item 1 to 35 fixes this.
If you want to use grid, then split your image according to the source grid, encode in hvc and replace all items in the grid but not the grid.

> I also wonder why these commands don’t work on an image converted to HEIC using MacOS built in conversion tool ?

Could you please upload a test file ?

> Can I just add the missing HEIC data using mp4box to a fresh HEIC image ?

You can, just add the meta-data (using add-meta and not add-item) and related images as you need, and set the right item references.

**Comment by jeanlf** [comment]
no follow-up, closing. Will reopen if you provide a test file for which the add-image commands don't work

**Comment by DY-TL** [comment]
Hi, I want to convert a png/jpeg image to a heif image with a grid size of 512x512. Currently, the possible solutions are as follows: 
1. Split the image into multiple 512x512 subimages using ffmpeg; 
2.  convert each subimage to a hevc stream using ffmpeg. 
3.  Finally, the mp4box tool was used to encapsulate the hevc bitstreams of all sub-images into heif images. 
I was wondering if there was a cleaner way to convert png/jpeg images to heif images. Or can we use the gpac tool instead of ffmpeg to split png/jpeg images into 512x512 subgraphs and transcode them into hevc bitstreams.
Thanks!
