### ISSUE TITLE
Question. Does mp4box support remux mp4 to mkv?

### ISSUE THREAD

**Issue by bluewidy** [gpac/gpac#2393]
This is just a question, not a bug report or feature request.
Since mp4box can remux mkv to mp4, so I wonder if it is also possible to remux mp4 to mkv.
I tried the following command, `mp4box -add input.mp4 -new output.mkv`
the extension is shown as mkv but actually outputted as mp4.

**Comment by rbouqueau** [comment]
I confirm mkv muxing works with ```gpac -graph -i beepbop.mp4 -o beepbop.mkv``` but not with MP4Box.

**Comment by bluewidy** [comment]
Thank you for the information.

**Comment by rbouqueau** [comment]
@jeanlf Is it expected?

**Comment by jeanlf** [comment]
you can use muxing with mp4box using `-mux` instead of `-out`:

```
MP4Box -mux dest.mkv file.mp4
```

This only work for input isobmf files, use gpac to mux from non-isobmf to non-isobmf .
