### ISSUE TITLE
Ensuring subtitles on iPods ("sbtl" vs. "gnrc")

### ISSUE THREAD

**Issue by forthrin** [gpac/gpac#2399]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC.
- [X] I give enough information for contributors to reproduce my issue _(Disclaimer: This is foremost a question.)_

I am experiencing some strange things when syncing video files ("Home Videos") from different Macs to an iPod Nano 3rd generation. Before syncing, the videos (on the Mac) have the following media information:

```
Media Type: sbtl:tx3g
	QT/3GPP subtitle
	Size 320 x 240 - Translation X=0 Y=0 - Layer 0
```

Curiously, after syncing from High Sierra (oldest macOS) and Ventura (newest macOS), the videos (on the iPod) have a modified media information. This causes the iPod not to display subtitles.

```
Media Type: gnrc:tx3g
	Subtitle/text 3GPP/Apple Stream
```

On Monterey (released between High Sierra and Ventura), media info is intact ("sbtl"), and subtitles are displayed.

My current workaround for High Sierra and Ventura is to stream copy the videos on the iPod, which reinstates `sbtl`.

Does anyone know what `gnrc` is, why it is applied by *some* macOS, and how to avoid this, in order to get subtitles? The `FOURCC` is elusive on the web and the gpac and FFmpeg sources. FFmpeg generates `sbtl` by default.

PS! Curiously, while "3GPP/Apple Stream" (associated with the obscure `gnrc`) occurs prominently in the MP4Box source, while "QT/3GPP" (associated with the more agreeable `sbtl`) is hardcoded.

https://github.com/gpac/gpac/blob/master/applications/mp4box/filedump.c#L3381

**Comment by rbouqueau** [comment]
'gnrc' seems to stand for "generic". Would you have samples to share so that I have a look?

**Comment by forthrin** [comment]
Thanks for getting back to me. Sounds logical. Of course I have sample files.

Now, with closer inspection it seems the only thing that's changed in iPod file is the FOURCC itself! Nothing else.

```
$ ffmpeg -t 9 -f lavfi -i color=c=black:s=320x240 -i sbtl.srt -c:s mov_text -profile:v baseline -level 3.0 -y sbtl.m4v
# sync file to iPod via iTunes 12.8.3.1 (or Finder in macOS 13.2)
$ cmp -l sbtl.m4v /Volumes/iPod/.../gnrc.m4v | gawk '{printf "%08x %c %c\n", $1, strtonum(0$2), strtonum(0$3)}'
000014bf s g
000014c0 b n
000014c1 t r
000014c2 l c
```

Anyway, as long as `gnrc` is inserted by the very proprietary iTunes (and later Finder), I assume there is nothing to do except make a program that in-place writes `sbtl` into the iPod files. At least a full stream copy will not be necessary.

Any further insight into the practice, and why it's changing between macOS versions, will be appreciated.

[sbtl.zip](https://github.com/gpac/gpac/files/10758249/sbtl.zip)

**Comment by rbouqueau** [comment]
PS: see also https://github.com/gpac/gpac/issues/1861#issuecomment-884160341

**Comment by forthrin** [comment]
Thanks for the reference. I just wrote an atom parser in Ruby that overwrites the incorrect values in-place (very fast). From the issue, it seems MP4Box can chang any metadata, but with an assumed overhead regenerating the output file.

I'll leave the question open for responses to the questions.

**Comment by jeanlf** [comment]
> Does MP4Box provide general functionality for manipulating the atom tree

Not a generic one - we have box patch tools for that - cf [doc](https://github.com/gpac/gpac/wiki/BoxPatch)

> Does the binary data say if a node (eg. moov) has subnodes, or must the parser know this from the format docs?

Not in the binary, this is known from the doc

> It's peculiar that MP4Box reports quite different -info when only the FOURCC is changed. Should this be fixed ?

Maybe - the info printed is based on the known types, so changing the main handler type indeed has some impact - you cannot guarantee that FOOX:tx3g is a text entry if FOOX is not `sbtl` or `text`...

> Why would Apple change (only!) these four bytes (on some macOS) and ruin subtitles? Any insight is appreciated

No clue... You can try changing the subtype to `sbtl:text` using `:stype` option and see if the file is still modified after syncing. 


You can also force the handler type using mp4box:
```
MP4Box -add :hdlr=sbtl text.mp4
```

These two ops will only rewrite the handler type and should be quite fast as they use in-place editing of the file.

**Comment by forthrin** [comment]
Thanks for your helpful and to the point assistance. The FFmpeg maintainers really have something to learn from you.

Can you show the full command line for the suggested `:stype` option? I couldn't find any examples how it's formatted.

**Comment by jeanlf** [comment]
> Can you show the full command line for the suggested :stype option? I couldn't find any examples how it's formatted.

Rewriting media type of track 3 from src.mp4 to `fooX`, in-place edit
```
MP4Box -add self#3:hdlr=fooX src.mp4
```

Rewriting media subtype (i.e. codec entry type) of track 3 from src.mp4 to `barX`, in-place edit
```
MP4Box -add self#3:stype=barX src.mp4
```
(you can combine the two in one command)

> Also, the "in-place editing" of MP4Box -add :hdlr=sbtl text.mp4 seems to rewrite the entire file (maintaining the inode I assume), as this took several seconds, while the Ruby script I wrote just changes the necessary 4 bytes in an instant

In some cases, in-place rewrite needs to shift the mdat position in the file, which can take some time. However for simple operations such as these, it should not be the case. Could you share the original file before edits ?

**Comment by forthrin** [comment]
Let me know if the attached verbose log doesn't give you the necessary insight.

[in-place.txt](https://github.com/gpac/gpac/files/11062949/in-place.txt)

**Comment by jeanlf** [comment]
Thanks. The ftyp is modified (larger) when saving the first file (MP4Box setting itunes tags for m4v extension) which will shift the mdat from position 40 to 48.

I'll try to disable automatic brand updates when in-place editing is possible to avoid this.

**Comment by jeanlf** [comment]
now on master - note that forcing -ipod or -ab will modify the ftyp box, hence will shift the mdat.

**Comment by forthrin** [comment]
It is beyond me how you guys run such a tight show compared to certain other video-related projects.

Maybe its specialized nature keeps it out of common reach. Whatever the reason, good on everyone.

I'll post back, but I have great confidence the fix will work.

**Comment by forthrin** [comment]
Some related questions:

1. Do any Apple video players adhere to the font, fontsize and layout settings? (And if yes for fonts, can you specify any installed font on the system, or is this restricted a narrow subset like the CSS fallback fonts, etc.?)

- QuickTime (modern macOS)
- QuickLook (modern macOS)
- Messages (modern macOS)
- iPod (legacy Nano 3, etc.)

$ MP4Box -add video.mp4 -add video.srt:hdlr=sbtl:font=Serif:size=20:layout=480x80x0x280 -new test.m4v

2. In particular, subtitles in inline video thumbs in Messages on macOS are very small to the point of being illegible. Is it possible to force them larger from the movie file metadata? Or even from global macOS settings?

**Comment by jeanlf** [comment]
> Do any Apple video players adhere to the font, fontsize and layout settings? 

No clue - from my tests on OSX 12.5, QT/QuickLook/Safari don't check font and size settings

>  Is it possible to force them larger from the movie file metadata?

you can try forcing the text track flags to 0xF (ie set the flag `track_size_is_aspect_ratio`) - cf `MP4Box -h tkhd` and see if this helps.
