### ISSUE TITLE
[DASH] Muxed media is not supported by DASH-AVC/264.

### ISSUE THREAD

**Issue by vladimir-kazakov** [gpac/gpac#24]
Hi!

I noticed that using MP4Box (GPAC rev 5572) it's possible to create muxed DASH media using DASH-AVC/264 profiles. But, as mentioned in the DASH-AVC/264 Interoperability Points v2.0, "only non-multiplexed Representations are supported, i.e. each Representation only contains a single media component" (see: Figure 7, page 16; 3.2.1, page 2, line 38).
.
I guess, at least a warning must be shown in this case.

Test media can be found here: http://1drv.ms/1xDwuTP

**Comment by jeanlf** [comment]
Thanks for reporting, this is now fixed in rev 5583
