### ISSUE TITLE
Can’t create auxiliary image subtype

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [gpac/gpac#2402]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [✓ ] I looked for a similar issue and couldn't find any.
- [✓ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ✓] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

===

Using latest nightly on MacOS.

The following command works …

`mp4box frame_0000003.heic -add-image frame_0000003_zbuffer.hvc:ID=50:auxt=urn:mpeg:hevc:2015:auxid:2`

However for my purposes the HEIC requires a Aux Subtype otherwise the depth channel is not seen.

In an Apple reference HEIC this looks like the following (using "_mp4box -diso_" XML dump) …

(from [https://files.michaelzfreeman.org/IMG_0019_A.HEIC](https://files.michaelzfreeman.org/IMG_0019_A.HEIC) )

```
<AuxiliaryTypePropertyBox Size="60" Type="auxC" Version="0" Flags="0" Specification="iff" Container="ipco" aux_type="urn:mpeg:hevc:2015:auxid:2" aux_subtype="0x000000110000000D4E01B109351F7B760103C7A020" >
</AuxiliaryTypePropertyBox>
```

Unless I’m missing a function can a way be added to allow the setting of “aux_subtype=“. Cheers.

**Comment by jeanlf** [comment]
you can use `auxt` and `auxd`, see doc [here](https://github.com/gpac/gpac/wiki/mp4box-meta-opts#add-image)
