### ISSUE TITLE
My video cannot view in gpac 

### ISSUE THREAD

**Issue by nisakadir** [gpac/gpac#2403]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x ] I looked for a similar issue and couldn't find any.
- [x ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hai, i got a issues regarding my gpac player. Why after i play the video it become blank?
![issues](https://user-images.githubusercontent.com/111970076/220865078-9868114b-9975-40ff-9509-3fd141575e89.PNG)

**Comment by rbouqueau** [comment]
> [x ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...).

I see nothing else than a sentence and a screen capture. Could you please ensure you provide us with the missing information?

**Comment by jeanlf** [comment]
Closing, will reopen if more info is provided for us to reproduce.
