### ISSUE TITLE
MP4Box 2 incompatible with Windows Explorer tags

### ISSUE THREAD

**Issue by Asterchades** [gpac/gpac#2404]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

The "Tags" (specifically the section simply called "Tags", as opposed to "Title", "Comments", etc) as applied by Windows Explorer appear to be  interfering with the correct functionality of MP4Box. Assigning a single "Tag" will result in no observable impact (MP4Box doesn't even acknowledge it exists), but as soon as a second "Tag" is assigned the file becomes completely incompatible. This persists should the second "Tag" be removed - it's only after all "Tags" have been removed that the file works as expected, at which point you can repeat the process.

The errors presented are as follows (consistent across all tested files):

> [isom] invalid tag size in Xtra !
[iso file] Read Box "Xtra" (start 4803875) failed (Invalid IsoMedia File) - skipping
[iso file] Read Box "udta" (start 4803867) failed (Invalid IsoMedia File) - skipping
[iso file] Read Box "moov" (start 36) failed (Invalid IsoMedia File) - skipping
Error opening file \\mediaserver\video\movies\Hero (CMN, ENG)(FHD).mp4: Invalid IsoMedia File

_There is also another error stating "[iso file] Broken text box detected, skiping parsing.", however this appears on files that otherwise work so I mention it only for the sake of completeness._

I'm unable to provide a demonstration file based on what I've used in my testing. They are both too large and only legal for personal use.

1.0 handled these tags without presenting an issue. It seemed unable to display them, but it at least acknowledged their existence and dealt with them accordingly. They present simply as a "tags" UDTA type, which is not detected in 2.x (files report four UDTA types in 1.0, but only three in 2.x).

**Comment by jeanlf** [comment]
Indeed, this should now be fixed on master. Thanks for the report
