### ISSUE TITLE
How to stitching NxM independently encoded HEVC video stream?

### ISSUE THREAD

**Issue by InkosiZhong** [gpac/gpac#2405]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I have seen https://github.com/gpac/gpac/wiki/HEVC-Tile-based-adaptation-guide and successfully used kvazaar and gpac to generate tiled videos.
However, I am looking for a method to stitch NxM independently encoded HEVC video stream into one mp4 file.
If I can control using the same video encoding parameters, is it possible to perform the stitching?
It should perform like `vstack` and `hstack` in ffmpeg.
Thank you so much.

**Comment by jeanlf** [comment]
if the same parameters are used and gop structures match, then yes it is possible using the [hevcmerge](https://github.com/gpac/gpac/wiki/hevcmerge) filter, see [this test](https://github.com/gpac/testsuite/blob/master/scripts/hevcsplit.sh).
