### ISSUE TITLE
Error DASHing file: Filter not found for the desired type

### ISSUE THREAD

**Issue by RfadnjdExt** [gpac/gpac#2409]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/
What was expected: A successful mux.
What was the result you obtained: As of [#1402](https://github.com/gpac/gpac/issues/1402) it says i can use mkv container as input file. But instead I got error.
```
Filter fin failed to setup: Filter not found for the desired type
Filter fin failed to setup: Filter not found for the desired type
Filters not connected:
fout (dst=/Users/naufalazharalmizan/Documents/Media/Kusonime.D.Conan - 03.mpd:gpac:segdur=3000/1000:muxtype=mkv:profile=onDemand:buf=1500:!check_dur:pssh=v:subs_sidx=0) (idx=1)
Arg segdur set but not used
Arg muxtype set but not used
Arg profile set but not used
Arg buf set but not used
Arg !check_dur set but not used
Arg pssh set but not used
Arg subs_sidx set but not used
Error DASHing file: Filter not found for the desired type
```
MP4Box: 
- Build:     I'm compiling myself & I try to use Nightly Builds same results.
- Version: 2.3-DEV-rev45-gb964fe422-master
Operating System: MacOS 10.15
Architecture: 64 bits
Commands:
```MP4Box -dash 3000 -out manifest.mpd:muxtype=mkv -profile onDemand video.mkv#video video.mkv#audio```
The problem happens all the time and a new problem.
Any required information can be requested. Thank you

**Comment by jeanlf** [comment]
Works fine on my mac and in the test suite - you likely don't have ffmpeg support in your build, check the output of

```
gpac -h ffmx
gpac -h ffdmx

```
