### ISSUE TITLE
Due to the loss of sound quality caused by ALAW, we plan to use pcm to directly encapsulate mp4. The following tests are carried out: Mp4Box-add src.pcm-add src.h265 output.mp4. We parsed the output file and found that the audio encoder is SOWT, which is also missing in version 2.2.0. How to choose?

### ISSUE THREAD

**Issue by fzcode** [gpac/gpac#2413]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
same place as in #2412, use GF_QT_SUBTYPE_SOWT
