### ISSUE TITLE
Cannot generate multiplexed LLHLS outputs

### ISSUE THREAD

**Issue by forbot161602** [gpac/gpac#2414]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

App: GPAC
OS: Mac OS X 12.6 64 Bits
Version: 2.3-DEV-fccf4a645-master-20230307
I built it from source by following this [instructions](https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-OSX).

I'm attempting to convert an mp4 file into a playlist and segment files using the LLHLS protocol as the primary format. Due to my work requirements, I need to output both multiplexed and non-multiplexed segment files separately (not necessarily simultaneously), but no matter how I adjust the command, I am unable to output multiplexed segment files. I have tried referring to a similar issue #1775 and several wiki explanations ([Dasher](https://github.com/gpac/gpac/wiki/dasher), [HLS](https://github.com/gpac/gpac/wiki/hls#hls-with-one-file-per-segment), [LLHLS](https://github.com/gpac/gpac/wiki/LL-HLS#hls-low-latency-setup), [Dash Transcoding](https://github.com/gpac/gpac/wiki/dash_transcoding#same-resolution), etc.), but still can't get it to work. What I want to achieve is an output in LLHLS protocol that includes only one variant m3u8 file, one init file, and segment and part files for a single audio and video stream (it's okay if a master m3u8 file is also generated). Is this a bug or is there a specific part of the command I need to adjust?

The command I used is:
```bash
gpac -i "input.mp4:#Representation=main" \
"reframer:rt=on" @ \
"ffsws:osize=640x360" @ \
"enc:c=avc:fintra=2" @2 \
"enc:c=aac:fintra=2:b=128k" @ @1 \
-o "index.m3u8:segdur=5:cdur=0.5:profile=live:dmode=dynamic:llhls=sf:tsb=-1:append" \
-graph
```

This command will generate these files in my output folder.
```
-rw-r--r--  1 owner group  283 Mar  9 21:27 index.m3u8
-rw-r--r--  1 owner group  12K Mar  9 21:27 index_1.m3u8
-rw-r--r--  1 owner group 7.6K Mar  9 21:27 index_2.m3u8
-rw-r--r--  1 owner group 680K Mar  9 21:27 input_dash_track1_1.m4s
-rw-r--r--  1 owner group 153K Mar  9 21:27 input_dash_track1_1.m4s.1
-rw-r--r--  1 owner group 134K Mar  9 21:27 input_dash_track1_1.m4s.2
-rw-r--r--  1 owner group  40K Mar  9 21:27 input_dash_track1_1.m4s.3
-rw-r--r--  1 owner group 1.2K Mar  9 21:27 input_dash_track1_init.mp4
-rw-r--r--  1 owner group  56K Mar  9 21:27 input_dash_track2_1.m4s
-rw-r--r--  1 owner group  353 Mar  9 21:27 input_dash_track2_1.m4s.1
-rw-r--r--  1 owner group 7.3K Mar  9 21:27 input_dash_track2_1.m4s.2
-rw-r--r--  1 owner group 8.6K Mar  9 21:27 input_dash_track2_1.m4s.3
-rw-r--r--  1 owner group 1022 Mar  9 21:27 input_dash_track2_init.mp4
```

I checked the gpac graph and it seems that all filters are connected properly. Here is the output from the terminal:
```
Filters connected:
fin (src=input.mp4:#Representation=main) (idx=1)
-(PID input.mp4) mp4dmx (dyn_idx=7)
--(PID V1)\
--(PID A2)-> reframer (rt=on) (idx=2)
---(PID V1) vtbdec "VTB:Hardware:AVC|H264" (dyn_idx=8)
----(PID V1) ffsws (osize=640x360) (idx=3)
-----(PID V1) ffenc "ffenc:libx264" (c=avc:fintra=2) (idx=4)
------(PID V1) rfnalu (dyn_idx=11)
-------(PID V1) dasher (dyn_idx=10)
--------(PID manifest_m3u8) fout (dst=index.m3u8:segdur=5:cdur=0.5:profile=live:dmode=dynamic:llhls=sf:tsb=-1:append) (idx=6)
--------(PID A2)            mp4mx (dyn_idx=14)
---------(PID A2) fout (dst=input_dash_track2_init.mp4:gfopt:segdur=5:cdur=0.5:profile=live:dmode=dynamic:llhls=sf:tsb=-1:append:frag:xps_inband=no:psshs=moov:mime=audio/mp4:cmaf=cmfc) (idx=12)
--------(PID V1)            mp4mx (dyn_idx=15)
---------(PID V1) fout (dst=input_dash_track1_init.mp4:gfopt:segdur=5:cdur=0.5:profile=live:dmode=dynamic:llhls=sf:tsb=-1:append:frag:xps_inband=no:psshs=moov:mime=video/mp4:cmaf=cmfc) (idx=13)
---(PID A2) ffdec "ffdec:aac" (dyn_idx=9)
----(PID A2) ffenc "ffenc:aac" (c=aac:fintra=2:b=128k) (idx=5)
-----(PID A2) dasher (dyn_idx=10)
```

It seems that two streams are being outputted at the (PID manifest_m3u8) fout location.

Here is the output of `gpac -i "input.mp4" inspect` command (I can upload the file to Dropbox if needed).
```
PID 1 video inMovie duration 23:40.128 timescale 24000 delay -2002 1920x1080 fps 24000/1001 SAR 1/1 3113 kbps 34049 frames codec AVC|H264 PL High@5 YUV 4:2:0 8 bpp
PID 2 audio inMovie duration 23:40.086 timescale 44100 44100 Hz 2 channels 130 kbps 61158 frames codec AAC LC (aot=2 implicit)
```

I have a basic understanding of audio and video concepts and streaming protocols, but I am extremely unfamiliar with transcoding. Please let me know if there are any errors or omissions in my understanding. Thank you.

**Comment by jeanlf** [comment]
Indeed, using LLHLS was triggering CMAF compatibility by default, enforcing unmultiplexed media. This is now fixed in master, thanks for the report.
