### ISSUE TITLE
mp4box does not process all PPS NALs in a stream

### ISSUE THREAD

**Issue by iain-waugh** [gpac/gpac#2417]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Platform:
Windows 10, mp4box version 2.2-rev0-gab012bbf-master

There are 2x PPS NAL units in a video encoding made by nVidia's NVEnc when weighted prediction is turned on.  One PPS is for normal operation and the other PPS contains the weighted prediction information.  When extracting the raw video stream with `mp4box -raw 1 <file>`, only the first (non-weighted prediction) PPS is extracted, leaving the weighted pred frames un-decodable.  A sample encoding has been [uploaded here](https://www.mediafire.com/file/5thmnhuor68f02y/DHBSPan_nVidia_A4000_VBR_POnly_QtrPass_60fGoP_WPred-short.mp4/file).

Also, when you inspect the file with `mp4box -info`, it gives these details for Track 1:
```Parameter Sets: 1 VPS 1 SPS 1 PPS```

It should say:
```Parameter Sets: 1 VPS 1 SPS 2 PPS```

The attached encoding has the first PPS at offset 0x089 and the second one at offset 0x094.

**Comment by jeanlf** [comment]
1. The file should not be hvc1 but hev1 since it uses inband parameter sets
2. we indeed had a bug in parsing of inband param sets fixed in 1659cd1a ((wrong ref in commit, sorry)
3. `MP4Box -info` only reports param sets in the config record, not the ones embedded in the stream hence 1 PPS shown and not 2.
 
Thanks for the report !
