### ISSUE TITLE
Cocatenate .mp4 videos using S3 presigned urls.

### ISSUE THREAD

**Issue by enagaraj89** [gpac/gpac#2419]
I am able to concatenate videos when the input files(.mp4) are on my machine. My use case is to merge multiple videos uploaded to S3 storage. I have to use presigned urls of input videos as input in concatenate command. 

When I tried concatenate operation using input video's presigned urls, I am getting "Unknown input file type" error.

MP4Box -add "presigned url for video1" -cat "presigned url for video2" output.mp4.

Can someone help to use presigned urls as input to MP4Box for concatenating videos?

**Comment by rbouqueau** [comment]
Can you share more information about your environment (shell/os) ? And also what does the presigned URL look like ?

**Comment by enagaraj89** [comment]
I am running MP4Box on windows10 machine. 

Presignrd url looks like "https://192.168.19.170:20021/media/0367d829-6ea6-4d3a-a396-d793bd24a80b/videos/Ch1_001_CH001_V.MP4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=GGTIZOFE1NYM1BF3WTCV%2F20230321%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230321T151742Z&X-Amz-Expires=604800&X-Amz-Security-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJHR1RJWk9GRTFOWU0xQkYzV1RDViIsImV4cCI6MTY3OTQxNTQxMiwicGFyZW50IjoiTmFnYXJhajE3IyJ9.9cHU_3skHDWeG5lFXP3rgi0LN98Ae8pTrQ-by4sf1rTZcfgE6WchZaf-ciG2JMeLNcrMw3AZYK1PYWByG4I4VA&X-Amz-SignedHeaders=host&versionId=null&X-Amz-Signature=eaa1bde067f572d84f76ad8eacfe9e552588d157e472e57d9de82d216ebfcb7a". We can access the video using presigned url.

**Comment by enagaraj89** [comment]
Yes, I am still having issue. I was able to merge videos using ffmpeg when I provide presigned url as input video, but MP4Box is not supporting presigned url as input. Below is the log.

C:\Users\user1\Documents\MP4Box>MP4Box -keepsys -flat -add "https://192.168.19.173:20019/media/1a84183d-15f0-4d16-bc28-7e8a5cccf256/videos/sample.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=9BFHOFCT4MGIUSAYM3OO%2F20230322%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230322T133321Z&X-Amz-Expires=604800&X-Amz-Security-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiI5QkZIT0ZDVDRNR0lVU0FZTTNPTyIsImV4cCI6MTY3OTQ5NTU3NCwicGFyZW50IjoiTmFnYXJhajE3IyJ9.GCQfaC8w4FRFjKhCNnK2x5zUSjJLvq5GYKWkoLt7Ay5xI9vkcZZIinEk6QL-HsL06Xk2eHFyFwQulvCJGEoS7A&X-Amz-SignedHeaders=host&versionId=null&X-Amz-Signature=ce1371d13b4b45f734150c454e8c68ddeb1efadd08dd9791441875052baca02e" -cat "https://192.168.19.173:20019/media/1a84183d-15f0-4d16-bc28-7e8a5cccf256/videos/sample.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=9BFHOFCT4MGIUSAYM3OO%2F20230322%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230322T133321Z&X-Amz-Expires=604800&X-Amz-Security-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiI5QkZIT0ZDVDRNR0lVU0FZTTNPTyIsImV4cCI6MTY3OTQ5NTU3NCwicGFyZW50IjoiTmFnYXJhajE3IyJ9.GCQfaC8w4FRFjKhCNnK2x5zUSjJLvq5GYKWkoLt7Ay5xI9vkcZZIinEk6QL-HsL06Xk2eHFyFwQulvCJGEoS7A&X-Amz-SignedHeaders=host&versionId=null&X-Amz-Signature=ce1371d13b4b45f734150c454e8c68ddeb1efadd08dd9791441875052baca02e" mergedvideo.mp4
Unknown input file type
Error importing https://192.168.19.173:20019/media/1a84183d-15f0-4d16-bc28-7e8a5cccf256/videos/sample.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=9BFHOFCT4MGIUSAYM3OO%2F20230322%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230322T133321Z&X-Amz-Expires=604800&X-Amz-Security-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiI5QkZIT0ZDVDRNR0lVU0FZTTNPTyIsImV4cCI6MTY3OTQ5NTU3NCwicGFyZW50IjoiTmFnYXJhajE3IyJ9.GCQfaC8w4FRFjKhCNnK2x5zUSjJLvq5GYKWkoLt7Ay5xI9vkcZZIinEk6QL-HsL06Xk2eHFyFwQulvCJGEoS7A&X-Amz-SignedHeaders=host&versionId=null&X-Amz-Signature=ce1371d13b4b45f734150c454e8c68ddeb1efadd08dd9791441875052baca02e: Requested URL is not valid or cannot be found

**Comment by enagaraj89** [comment]
![Mp4version](https://user-images.githubusercontent.com/26904258/226935456-085621ba-d12d-489b-89ba-aa5b0a82b830.PNG)

MP4Box - GPAC version 0.4.6-DEV-rev2735
Compilation Date: Mar  2 2011 - by Kurtnoise
GPAC Copyright: (c) Jean Le Feuvre 2000-2005
                (c) ENST 2005-200X
GPAC Configuration: (static configuration file)
Features: GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG

This is the version I am using. Looks like it's an old version. Could you please provide the latest version and the version you're using. Also, please provide the link to get latest version.

**Comment by rbouqueau** [comment]
You can update by using [installers from our website](http://gpac.io/downloads/gpac-nightly-builds/).

**Comment by enagaraj89** [comment]
Can we merge if a .mp4 file is in the form of a url using MP4Box?

**Comment by rbouqueau** [comment]
The input yes, the output I don't know. Which command-line would it be?

**Comment by enagaraj89** [comment]
For my scenario input videos are always going to be in the form of urls(https) and output I expect is memorystream or physical .mp4 file. I will be running this process with in a .net core application.

**Comment by jeanlf** [comment]
@enagaraj89 MP4Box import from URLs other than local files is only available starting from GPAC 1.0. Output file of MP4Box must be a local file - if you need to create a remote file you will need to use gpac.

Please check with latest version and let us know if we can close this.

**Comment by jeanlf** [comment]
now fixed on master, thanks for the report.
