### ISSUE TITLE
VC++ 2015 instead of VC++ 2010

### ISSUE THREAD

**Issue by stax76** [gpac/gpac#242]
Please support GUI authors and GUI users by building against VC++ 2015, authors and users of GUIs such as MeGUI or StaxRip would appreciate it.

Thanks

**Comment by rbouqueau** [comment]
Thanks for the feedback.

Just for my understanding before I take care of this: is this a pb of compiler or of standard library?

**Comment by stax76** [comment]
Thanks for taking care, it's about standard library, I do not bundle the runtime DLLs to keep the download size low, my bundle is currently around 60 MB, instead I show a warning in case the VC++ 2010 DLLs are not installed, my users have to download and install the VC++ 2010 DLLs manually in case it's not already installed by another software. My bundle is about 50 tools and plugins and MP4Box is the only one using such a old runtime.

**Comment by rbouqueau** [comment]
I am away and will be back only next week. I want to make sure I understand.

Right now the StaxRip does copy its binaries from the official installer, correct?

We could provide you with a much smaller build. Would you be interested?

For my information do you have the ability to build yourself?

**Comment by stax76** [comment]
I would be interested in a smaller build. Once I tried together with Selur (author of a GUI called Hybrid) to use a build created with the help of cygwin, it was very small but some things did not work, if I remember right then it was the -hint switch but I'm not sure.

**Comment by rbouqueau** [comment]
Thanks for the additional detail.

I remember the issue about 'hint' and it seems we solved it then: https://github.com/gpac/gpac/issues/139 . Let me know if you feel this is not ok.

**Comment by rbouqueau** [comment]
I put an example of such an .exe (around 3.5MB) at http://www.gpac-licensing.com/downloads/242/MP4Box.exe

Let me know if it works for you. It could be even smaller.

We could make such builds available as CI, see #118 (to any reader: any help welcome of course :))

**Comment by stax76** [comment]
Thanks, much appreciated. So far it works fine, what's the version and revision?

If such builds could be downloaded somewhere I think there would be some people interested.

**Comment by rbouqueau** [comment]
```
$> MP4Box -version
MP4Box - GPAC version 0.5.2-DEV-rev649-g361314a-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: --static-mp4box --use-zlib=no
Features: GPAC_64_BITS GPAC_DISABLE_3D GPAC_DISABLE_SWF_IMPORT
```

I'll close this issue when #118 is done. You can also subscribe to a specific issue on github to be updated then.

**Comment by rbouqueau** [comment]
You might be interested by #308. Now you can take the free version of MSVC (Community 2015) and build MP4Box with no deps in litterally 1 click. See also http://gpac.io/2015/07/29/gpac-build-mp4box-only-all-platforms/

**Comment by rbouqueau** [comment]
Can we close?

**Comment by stax76** [comment]
closing
