### ISSUE TITLE
RTP streaming with GPAC

### ISSUE THREAD

**Issue by ghost** [gpac/gpac#2433]
Hi,
Can someone let me know/ point me to the documentation for real time streaming applications with GPAC.

Thanks

**Comment by rbouqueau** [comment]
RTP works like any other source in GPAC.

At the moment our wiki is hosted on github, so you can find plenty of information by using github's search engine: https://github.com/search?q=repo%3Agpac%2Fgpac+rtp&type=wikis&p=1

Let us know more about your project if you are still confused. Any help on the document is also welcome.

**Comment by jeanlf** [comment]
no follow up, closing
