### ISSUE TITLE
Feature Request: Make mp4box accept + signs when naming tracks.

### ISSUE THREAD

**Issue by bluewidy** [gpac/gpac#2441]
Currently mp4box accepts - signs in track names, but not + signs. For example, mp4box allows: `mp4box -add audio.ec3:name=DD-Atmos`
but mp4box doesn't allow: `mp4box -add audio.ec3:name=DD+Atmos`
Yes... actually I would like to name the Dolby Digital Plus Atmos track to DD+Atmos :)

**Comment by jeanlf** [comment]
indeed, there was some issue in multiple add detection ( -add URL1+URL2) ... Now fixed, thanks for the report
