### ISSUE TITLE
MP4Box: `-splitx` causes `-new` file name to be different than specified

### ISSUE THREAD

**Issue by rafrafek** [gpac/gpac#2444]
Command:
`MP4Box -add video.ts:tc=50/1,11,09,59,07 -splitx 0.93:60.93 -new out.mp4`
instead of producing:
`out.mp4`
produces:
`out_0.93_60.93.mp4` (or `out_.mp4` with single underscore character suffix if error occurs).

How can I force MP4Box to name the output file `out.mp4`?

Currently it breaks my script which expects the name to be always `out.mp4`.

I can't get the name from the output, it doesn't say it:

```
IsoMedia import video.ts - track ID 33 - Video (size 1920 x 1080)
IsoMedia import video.ts - track ID 34 - Audio (SR 48000 - 2 channels)
splitting: file 1 done   
```

I don't see the name with a `-v` flag either.

I've tested it with the latest GPAC 2.2 and with the older 1.0.1-rev1.0.1+dfsg1-4+deb11u1, both versions create changed name.

Thanks!

**Comment by jeanlf** [comment]
This was indeed not supported, now on master. Thanks for the report.

**Comment by rafrafek** [comment]
Nice, thank you! 🙏
