### ISSUE TITLE
TTML generation fails for italic on 2 lines

### ISSUE THREAD

**Issue by akkermansadriaan** [gpac/gpac#2445]
### Description

I'm translating a vtt track in an mp4 file using `gpac -i test.mp4#text -o test.ttml`. This result in an error on screen.
```Attempt to write property on input PID in filter ufvtt - ignoring
[XML] Invalid TTML doc: Invalid node stack: closing node is p but span was expected - Line 10: </p
	XML text was:
<?xml version="1.0" encoding="UTF-8" ?>
<tt xmlns="http://www.w3.org/ns/ttml" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:ttp="http://www.w3.org/ns/ttml#parameter"  xml:lang="und">
 <head>
  <layout>
   <region xml:id="Default" tts:origin="5% 5%" tts:extent="90% 90%" tts:displayAlign="after" tts:overflow="visible" tts:textAlign="center" tts:fontSize="18px" tts:fontFamily="Serif"/>
  </layout>
 </head>
 <body>
  <div>
  <p begin="00:02:47.090" end="00:02:49.260"><span tts:fontStyle="italic">Text part 1.<br/><span tts:fontStyle="italic">- Text part 2.</span></p>
  </div>
 </body>
</tt>
```
I was able to trace it down to when there's a `<br/>` in the italic span, or when the end of the line is italic and the start of the next one as well.

**Comment by rbouqueau** [comment]
It seems like there is 2 ```span``` opens but only 1 closing. So the error message seems ok.

**Comment by akkermansadriaan** [comment]
The test.mp4 video contains a WebVTT track
```
gpac -i test.mp4 inspect
PID 1 video inMovie inPreview duration 54:36.120 timescale 25000 delay -2000 1920x1080 fps 25 SAR 1/1 4474 kbps 81903 frames codec avc1.640032 AVC|H264 PL High@5 YUV 4:2:0 8 bpp
PID 2 audio inMovie inPreview duration 54:36.181 timescale 48000 48000 Hz 2 channels 125 kbps 153571 frames codec mp4a.40.2 AAC LC (aot=2 implicit)
PID 3 text inMovie inPreview duration 14:53.720 timescale 1000 1920x1080 SAR 1/1 261 bps 280 frames codec wvtt WebVTT Text
```

When writing the WebVTT to a text file `gpac -i test.mp4#text -o test.vtt` it does give a strange error `Attempt to write property on input PID in filter ufvtt - ignoring` but it does result in a file and the specific subtitle that doesn't get translated to TTML as the original description is:
```
02:47.090 --> 02:49.260 line:90% size:100.00% position:50.00% region:cueRegion_anchor_0_90 align:center
<c.region-cueRegion_anchor_0_90><c.white><i>Text part 1.</i></c>
<c.white><i>- Text part 2.</i></c></c>
```
It seems like the original WebVTT track is correct, and the translation of the italic `span` with a break in between doesn't get translated correctly to TTML, correct?

**Comment by rbouqueau** [comment]
That's a possibility. Could you share the test.mp4 sample with us?

**Comment by jeanlf** [comment]
Indeed the span closing was buggy, now fixed on master. Thanks for the file.
