### ISSUE TITLE
uncvg filter errors out on row interleave with tiles

### ISSUE THREAD

**Issue by bradh** [gpac/gpac#2446]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...).

Running

`./bin/gcc/gpac uncvg:interleave=row:tiles=1x2:fps=0 -o uncompressed_row.heif` 

with current git HEAD (commit 586113942f9e1efdfa75eac1aae2b27b610bcb27) results in repeating error messages:

```
[uncvg] Error processing
[uncvg] Throw Internal error in tile padding: remain 24832 is greater than tile size 24576
```

followed by

```
[Filter] uncvg (idx 1) in error / not responding properly: 54 consecutive errors in 1018526 us with no packet discarded or sent
        discarding all inputs and notifying end of stream on all outputs
```

The problem does not appear with component or pixel interleave.

The problem does not appear if tiles are not used, or for `tiles=1x1`. It does appear for `tiles=2x1`, `tiles=2x2` and `tiles=1x2`.

**Comment by jeanlf** [comment]
Indeed, now fixed thanks for the report. I also fixed uncvdec which was broken for non-square tile grids.

**Comment by bradh** [comment]
Appreciate the work in general and particular thanks for the quick response on a busy week.
