### ISSUE TITLE
Dasher HLS doesn't play on client side

### ISSUE THREAD

**Issue by carminoplata** [gpac/gpac#2447]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hi,

I tried the following command in order to use HLS protocol for making onDemand streaming:

`gpac -r -graph -stats -i video.mp4 -o http://localhost:8000/live.m3u8:gpac:hmode=push:profile=onDemand -no-h2`

I implemented a node.js server for storing all segments in a particular folder, but VLC Player and several web player using hls.js are not able to play the video. It looks like that the fragments are not created correctly. 
You can see the error showed in [hls.js Demo]( https://hlsjs.video-dev.org/demo/) in the attached images.

![HlsDemoErrors](https://user-images.githubusercontent.com/40350337/234860778-fe9d43f0-2c44-41b3-98b8-171594febff4.png)

In addition, I observed that m3u8 file was wrong since it shows that there are Indpendent Segments although the command require onDemand profile. 
According to [Apple HLS Specification](https://developer.apple.com/documentation/http_live_streaming/example_playlists_for_http_live_streaming/video_on_demand_playlist_construction), the content of the m3u8 file should be:

`#EXTM3U

#EXT-X-PLAYLIST-TYPE:VOD

#EXT-X-TARGETDURATION:10

#EXT-X-VERSION:4

#EXT-X-MEDIA-SEQUENCE:0

#EXTINF:10.0,

http://example.com/movie1/fileSequenceA.ts
#EXTINF:10.0,

http://example.com/movie1/fileSequenceB.ts

#EXTINF:10.0,

http://example.com/movie1/fileSequenceC.ts

#EXTINF:9.0,

http://example.com/movie1/fileSequenceD.ts

#EXT-X-ENDLIST`

Instead the output generated by the command below is that one

`#EXTM3U
#EXT-X-VERSION:6
#EXT-X-INDEPENDENT-SEGMENTS

#EXT-X-STREAM-INF:BANDWIDTH=534662,CODECS="avc1.4D401F,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=25,AUDIO="audio2"
live_1.m3u8

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio2",NAME="2",LANGUAGE="eng",AUTOSELECT=YES,URI="live_2.m3u8",CHANNELS="2"`

Is there something wrong in the command?

Software and Used System:

- Ubuntu 20.04
- Gpac 2.2
- Firefox 112.0.1

**Comment by rbouqueau** [comment]
I think you are confusing several things.

The playlist you quote from GPAC is a "master playlist" (new name is "multivariant playlist") while the one from the HLS doc is a "variant playlist" (now called "media playlist"). The media playlist from GPAC is ```live_1.m3u8```. And probably ```live_2.m3u8``` as your report may be truncated.

You should ignore ```#EXT-X-INDEPENDENT-SEGMENTS``` for your understanding. 

A tutorial on HLS is available here: https://www.motionspell.com/2023/03/30/hls-posts-updated-rfc8216bis-rev12/

I acknowledge that we never write ```#EXT-X-PLAYLIST-TYPE:VOD```:
```
#EXTM3U
#EXT-X-TARGETDURATION:1
#EXT-X-VERSION:6
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MAP:URI="beepbop_track1__dashinit.mp4",BYTERANGE="869@0"
#EXTINF:0.998458
#EXT-X-BYTERANGE:2197@989
beepbop_track1__dashinit.mp4
#EXTINF:0.998458
#EXT-X-BYTERANGE:2311@3186
beepbop_track1__dashinit.mp4
#EXTINF:0.998458
#EXT-X-BYTERANGE:2341@5497
beepbop_track1__dashinit.mp4
#EXTINF:0.998458
#EXT-X-BYTERANGE:2393@7838
beepbop_track1__dashinit.mp4
#EXTINF:0.998458
#EXT-X-BYTERANGE:2479@10231
beepbop_track1__dashinit.mp4
#EXT-X-ENDLIST
```

I'll try to have a look later today with hls.js.

**Comment by carminoplata** [comment]
Hi Romain,

thanks a lot for your fast response. I agree with you regarding the two type of playlists and they should be fine. It looks like a server issue since if I copy all playlists and segments into the server (without performing a HTTP push requests), the player is able to play the streaming. The issue above appear when the segments are sent to server via HTTP push, so probably it's server's issue.

I'll let you know for confirmation. 

Just to understanding better, if I use profile onDemand and profile live for HLS, the playlists generated by gpac will be the same, won't they?

**Comment by rbouqueau** [comment]
> I use profile onDemand and profile live for HLS, the playlists generated by gpac will be the same, won't they?

onDemand profile will generate one big segment while live profile will generate several segments.

**Comment by jeanlf** [comment]
I see two issues with this approach:
- You are using static content generation (eg `dmode=static`). In this mode, the manifests (MPD or HLS master+variants) are only generated once the entire content is processed

- you are using onDemand profile, which implies creation of a root sidx which can only be finalized at the end of the session. If output is HTTP, this will result in a final PUT/POST with the overridden byte range - this might not be well supported by your server.

Playing in HLS.js once the session is done (everything pushed) works fine here. I'm closing this as I don't think there is any issue with GPAC here.

**Comment by carminoplata** [comment]
Hi, 

I confirm there was an issue on server side on how the files were stored. The only thing that I didn't understood very well, is how the playlist (master and variants) are generated in case of onDemand profile or live profile. 

Should master playlist contain `EXT-X-PLAYLIST-TYPE:VOD` in case of onDemand profile?
