### ISSUE TITLE
link to latest nightly build

### ISSUE THREAD

**Issue by grudelsud** [gpac/gpac#245]
hey

little feature request that could be helpful. 

I'm building a docker container with gpac (among other things) but I cannot find a link to the **latest nightly build**, e.g. from [this page](http://download.tsi.telecom-paristech.fr/gpac/latest_builds/linux64/gpac/) I can see the list of builds with commit hashes but no link to something like *gpac_0.5.2-DEV-latest.deb* that would be quite handy to implement CI on our side. 

would this be something reasonably easy for you to add? I think it would be useful!

thanks!
thomas

**Comment by rbouqueau** [comment]
Thanks for the feedback.

Is .deb the best format for you, or could we provide something else (like a container)?

**Comment by grudelsud** [comment]
we build our own containers by installing a set of tools we require and we normally base our images on ubuntu64, so for us .deb files are ideal. 

one thing I have to do in my Dockerfile is to retrospectively install gpac dependencies, ie. here's an extract of my Dockerfile:

    # gpac dependencies
    RUN apt-get install -y \
        libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev \
        libavcodec-extra-54 libavformat-extra-54 libavutil-extra-52 \
        liba52-0.7.4 libfaad2 libfreenect0.2 libglu1-mesa libmad0 libswscale2 \
        libjpeg62 libmozjs185-1.0

    # install gpac
    RUN wget http://download.tsi.telecom-paristech.fr/gpac/latest_builds/linux64/gpac/gpac_0.5.2-DEV-rev623-g1ede7f5-master_amd64.deb
    RUN dpkg -i gpac_0.5.2-DEV-rev623-g1ede7f5-master_amd64.deb

which I think it's totally fine. the only sticky point here is using a specific build rather than using a link to latest, as mentioned in my previous comment.

hope this helps

**Comment by nguyen-viet-thanh-trung** [comment]
Hi,
You should have now  a link to the latest build like that http://download.tsi.telecom-paristech.fr/gpac/latest_builds/linux64/gpac/gpac_0.5.2-DEV-latest-master_amd64.deb

Please try it and give us your feedback !

**Comment by grudelsud** [comment]
awesome, thanks!
