### ISSUE TITLE
Setting audio channel labels?

### ISSUE THREAD

**Issue by dprestegard** [gpac/gpac#2450]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I'm trying to build an MP4Box command to set the channel labels of a multi-track MOV where every audio track has just one channel.

The problem I'm facing is that for some reason FFmpeg labels the left surround / right surround tracks as "Bl / Br" when they should be "Ls / Rs", at least according to mediainfo. I want MP4Box to set these channel labels for me but don't see anything in the documentation about channel labels. Suggestions?

**Comment by jeanlf** [comment]
usually labels are set using the track's handler name, ie `-add src.mp4:name=foo`

**Comment by jeanlf** [comment]
any news on this ?

**Comment by jeanlf** [comment]
No follow-up, closing
