### ISSUE TITLE
MP4Box DASH live stream: .m4s files are being removed

### ISSUE THREAD

**Issue by anthnyprschka** [gpac/gpac#2452]
I am getting the same error as #1553 with GPAC release 2.2.1 when running MP4Box -dash 1000 -profile live -mpd-refresh 15 -dynamic "sample.mp4" -out live.mpd:

[Dasher] Segment 1 duration 5.26667 more than 3/2 DASH duration, consider reencoding or using segment timeline
[Dasher] AS-1 Rep 1 segment 1 done 5196 ms before UTC due time
[Dasher] updated period DID1 duration 5266 MPD time 52663s 34 %
[Dasher] First CTS 80896 in segment 2 drifting by 4.26667 (more than half a segment duration) from segment time, consider reencoding or using segment timeline
[Dasher] Segment 2 duration 5.06667 more than 3/2 DASH duration, consider reencoding or using segment timeline
[Dasher] AS-1 Rep 1 segment 2 done 10227 ms before UTC due time
**[Dasher] removing segment sample_dash1.m4s 68 %**
[Dasher] updated period DID1 duration 10333 MPD time 10333

It's removing the generated m4s files for some reason.

Streaming the file with MP4Box -dash 1000 -frag 1000 -rap -segment-name segment_ "sample.mp4" works fine but I wanna do it dynamic so I can push new mp4 files as they arrive at the server to the live stream (like this issue: https://github.com/gpac/gpac/issues/1252).

Any help would be very appreciated!

**Comment by jeanlf** [comment]
closing as not a GPAC bug, let us know if you need more help
