### ISSUE TITLE
I want to ask some questions about python api

### ISSUE THREAD

**Issue by a23232390** [gpac/gpac#2459]
The following are 16 TILEs
total_rate is 16 TILEs download_rate divided by time right?
How to calculate total_rate
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/a2323/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/a2323/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

stats.total_rate | download_rate | group.idx | filesize | group.qualities[stats.active_quality_idx].bandwidth)]
-- | -- | -- | -- | --
3243509 | 1672288 | 0 | 4904 | 10000
3243509 | 1459744 | 1 | 8362 | 534375
3243509 | 5440344 | 2 | 24266 | 534375
3243509 | 6882176 | 3 | 17122 | 534375
3243509 | 4461464 | 4 | 12114 | 534375
3243509 | 11095000 | 5 | 30962 | 534375
3243509 | 25044280 | 6 | 76983 | 534375
3243509 | 12390008 | 7 | 40441 | 534375
3243509 | 8389216 | 8 | 22610 | 534375
3243509 | 12150120 | 9 | 34599 | 534375
3243509 | 40744304 | 10 | 212889 | 534375
3243509 | 37406256 | 11 | 136603 | 534375
3243509 | 12582128 | 12 | 36441 | 534375
3243509 | 3430728 | 13 | 9540 | 534375
3243509 | 4199808 | 14 | 10047 | 534375
3243509 | 3425088 | 15 | 9279 | 534375
3243509 | 3313784 | 16 | 9960 | 534375

</body>

</html>

**Comment by jeanlf** [comment]
`total_rate` is computed as `sumOf(download_rate[i]/8*filesize[i]) / sumOf(filesize[i])` for each group `i`.

`total_rate` is in bytes per sec while `download_rate` is in bits per sec, I'll update the doc.
