### ISSUE TITLE
test file full paths prefixed with out_

### ISSUE THREAD

**Issue by blacktrash** [gpac/gpac#246]
Latest MP4Box -dash creates out_{intputfilename}.mp4 files. But the path creation is broken for instance when the input path is absolute:
`out_/full/path/to/input.mp4` for an input at `/full/path/to/input.mp4`

If only relative input paths are allowed, then this should be clearly documented, although I'd consider it a seriously lacking feature.

**Comment by blacktrash** [comment]
Actually it means that I have to run the command in the same directory as the input files ... or recreate even the relative path in a directory named `out_` ...

**Comment by jeanlf** [comment]
Could you give the command line used ? I tried to reproduce the bug but couldn't

**Comment by blacktrash** [comment]
```sh
$ MP4Box -dash 10000 -base-url base/ -segment-name 'base/$Representation-ID$-$Number$' \
-url-template -bs-switching merge -out test.mpd \
some/path/test-300.mp4#audio \
some/path/test-300.mp4#video \
some/path/test-600.mp4#video
[Core] system failure for file opening of out_some/path/test-300.mp4 in mode w+b: 2
[Core] system failure for file opening of out_some/path/test-300.mp4 in mode w+b: 2
[Core] system failure for file opening of out_some/path/test-600.mp4 in mode w+b: 2
```

**Comment by rbouqueau** [comment]
I definitely made a mistake in the commit adding relative path to the output files (```-base-url```). There are at least 3 issues on the same theme so I made end up marking them as duplicates. Thanks for your patience, it may take some time (unless you need it fast, let us know).

**Comment by blacktrash** [comment]
Thanks.
The above needs actually double quotes around the segment name to work 'properly', but then the m4s filenames are also munged.

I can make do for the moment with some weird combination of current directory jumping, file and directory moving and `sed` scripting ;-)
I would need it at some point though because we are planning to offer MPEG-DASH for Flowplayer Drive: https://flowplayer.org/features/#encoding in a couple of months.

**Comment by blacktrash** [comment]
Note that this issue is *not* related to `-base-url`, only to input paths:

```
$ MP4Box -dash 10000 -segment-name "$Representation-ID$-$Number$" \
-url-template -bs-switching merge -out test.mpd \
some/path/test-300.mp4#audio \
some/path/test-300.mp4#video \
some/path/test-600.mp4#video
[Core] system failure for file opening of out_some/path/test-300.mp4 in mode w+b: 2
[Core] system failure for file opening of out_some/path/test-300.mp4 in mode w+b: 2
[Core] system failure for file opening of out_some/path/test-600.mp4 in mode w+b: 2
$ ls -1
-IDhimBH$1.m4s
-IDhimBH$10.m4s
-IDhimBH$11.m4s
-IDhimBH$12.m4s
-IDhimBH$13.m4s
-IDhimBH$14.m4s
-IDhimBH$15.m4s
-IDhimBH$16.m4s
-IDhimBH$17.m4s
-IDhimBH$18.m4s
-IDhimBH$19.m4s
-IDhimBH$2.m4s
# [... etc ...]
some
test.mpd
```
It is a more recent regression.

**Comment by jeanlf** [comment]
this was fixed some time ago, reopen if needed
