### ISSUE TITLE
build apk error

### ISSUE THREAD

**Issue by llinshpd** [gpac/gpac#2461]
I built APK on the v0.9.0 review branch, referencing/home/liulin/Android/gpac/build/android/README, but reported the following error:

[armeabi] SharedLibrary  : libgpac.so
Reaping winning child 0x5637313df250 PID 18242 
Live child 0x5637313df250 (/home/liulin/Andorid/gpac/build/android/obj/local/armeabi/libgpac.so) PID 18243 
/home/liulin/Andorid/android-ndk-r13b-linux-x86_64/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lavdevice
/home/liulin/Andorid/gpac/build/android/jni/libgpac/../../../../src/filters/ff_common.c:632: error: undefined reference to 'avdevice_register_all'
/home/liulin/Andorid/gpac/build/android/jni/libgpac/../../../../src/filters/ff_common.c:732: error: undefined reference to 'av_filter_iterate'
/home/liulin/Andorid/gpac/build/android/jni/libgpac/../../../../src/filters/ff_dmx.c:762: error: undefined reference to 'avdevice_register_all'
/home/liulin/Andorid/gpac/build/android/jni/libgpac/../../../../src/filters/ff_mx.c:83: error: undefined reference to 'avformat_init_output'
/home/liulin/Andorid/gpac/build/android/jni/libgpac/../../../../src/filters/ff_mx.c:217: error: undefined reference to 'avcodec_parameters_copy'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
Reaping losing child 0x5637313df250 PID 18243 
make: *** [/home/liulin/Andorid/android-ndk-r13b-linux-x86_64/android-ndk-r13b/build/core/build-binary.mk:703: /home/liulin/Andorid/gpac/build/android/obj/local/armeabi/libgpac.so] Error 1
Removing child 0x5637313df250 PID 18243 from chain.

android ndk version is : ndk13b

**Comment by rbouqueau** [comment]
Would you consider upgrading your GPAC to the latest master? Your version is largely superseeded and we don't support it anymore.

Build instructions can be found [here](https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Android).

**Comment by llinshpd** [comment]
I just took over a project based on version 0.9, but it no longer runs, so I want to build an APK based on version 0.9 review.

I would like to know what versions of Android ndk, sdk, and jdk are used for version 0.9 preview?

Thanks!
