### ISSUE TITLE
FFplay warns on a file and chrome plays it much better after -c copy

### ISSUE THREAD

**Issue by ValZapod** [gpac/gpac#2462]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

If you remux Annex B 24/1.001 file with mp4box to https://slydiman.me/ffmpeg/hevc_mp4box_copy_valid.mp4 (mp4box uses latest 2.2 stable fixes GPAC, commit b34e3851) it will open very slow in chrome, ffplay warns on it:

[mov,mp4,m4a,3gp,3g2,mj2 @ 000001db95c67ec0] st: 0 edit list: 1 Missing key frame while searching for timestamp: 10010
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001db95c67ec0] st: 0 edit list 1 Cannot find an index entry before timestamp: 10010.

and after ffmpeg's -c copy it works perfectly in Chrome. Mpv also does not like it much, it plays with a pause in the middle, but after -c copy it is great.

File is also still wrongly vfr with ffmpeg -i file.mp4 -vf vfrdet -f null -

P.S. this issue is part of a bigger bug in ffmpeg about GOP for H265 recorded by SONY FX3
IIIIIIII-BBBBBBBB-BBBBBBBB-PPPPPPPP-BBBBBBBB-BBBBBBBB-PPPPPPPP-... (7 blocks): https://trac.ffmpeg.org/ticket/10348#comment:12

**Comment by ValZapod** [comment]
Annex B is here: http://slydiman.me/ffmpeg/b-frames.hevc

>The first chrome access to the file is slow indeed

But it is not slow after you -c copy https://slydiman.me/ffmpeg/hevc_mp4box_copy_valid.mp4

[ffmpegccopy.mp4.zip](https://github.com/gpac/gpac/files/11446592/ffmpegccopy.mp4.zip)


>No warnings from ffplay here.

Do you get warnings on original file? It is using a release from 2 weeks ago... mpv also is slow to open, only MPC-HC is good, Lavfilters...

**Comment by ValZapod** [comment]
>I tried with the latest version of GPAC. Installers available at

Okay, tried with latest nightly GPAC-2.3-DEV-rev246-gef9e1490-master, since you got this: https://github.com/gpac/gpac/issues/2456

I dunno what ffmpeg you are using, but if you use our official binaries: https://github.com/BtbN/FFmpeg-Builds it still prints 

```
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001c55e516700] st: 0 edit list: 1 Missing key frame while searching for timestamp: 10010
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001c55e516700] st: 0 edit list 1 Cannot find an index entry before timestamp: 10010.

```

It still has VFR, the main difference with -c copy is moov atom in the end for ffmpeg (since faststart is not active):

```
mp4box.exe -add b-frames.hevc csewcqa.mp4

ffmpeg -i csewcqa.mp4 -vf vfrdet -f null -

```

[Parsed_vfrdet_0 @ 0000022741cc1c00] VFR:0.019231 (1/51) min: 10010 max: 20020 avg: 20020

**Comment by jeanlf** [comment]
Some more digging here:  the stream starts with IDR with decodable leading pictures (sap type 2):
- first frame CTS 20020, DTS 0 (=> CTS offset 20020)
- second frame CTS 0, DTS 10010 (=> CTS offset -10010)
- third frame CTS 10010, DTS 20020 (=> CTS offset -10010)

When moving to positive cts offset, we end up with
- first frame CTS 30030, DTS 0 (=> CTS offset 30030)
- second frame CTS 10010, DTS 10010 (=> CTS offset 0)
- third frame CTS 20020, DTS 20020 (=> CTS offset 0)

and an edit list skipping 0->10010 , which I believe is correct.
The warning 'Cannot find an index entry before timestamp: 10010'  is likely a bug from ffmpeg.

On the other hand,  ffmpeg -c copy ends up with an edit list skipping 0->30030 which points to the IDR but ends up skipping presentation of frames 2 and 3 which I believe is wrong.


I uploaded [here](http://download.tsi.telecom-paristech.fr/gpac/tests/sap2/) the two files along with remuxed ctss v0 and v1 files with latest master, I see exactly the same behaviour on  chrome (osx, Version 113.0.5672.92 with clean cache )  on each of these files.

So I don't think there is any bug on GPAC's side here, the generated files are correct IMO. I'm closing this, but don't hesitate to further comment, I will reopen if needed.

**Comment by ValZapod** [comment]
>starts with IDR with decodable leading pictures

So that is like a thumbnail? Any simple way to remove it? Any simple way to make it CFR?

**Comment by jeanlf** [comment]
> So that is like a thumbnail?

No, it's the first keyframe but it is not presented first 

>  Any simple way to remove it?

that would just break the stream ...

> Any simple way to make it CFR?

it is, see `MP4Box -info src.mp4 2>&1 | grep CFR`

**Comment by ValZapod** [comment]
Yes, got it, we just do not support it, just as BLA, only CRA is supported for keygrames.

https://github.com/FFmpeg/FFmpeg/commit/ab77b878f1205225c6de1370fb0e998dbcc8bc69

**Comment by ValZapod** [comment]
https://github.com/gpac/gpac/blob/ef9e14907693c1bbf44a9af86acbb5c8b1a7c852/src/filters/reframe_nalu.c#L3925-L3926

Should that be updated to include BLA? What about RADL?

**Comment by rbouqueau** [comment]
At least for now ```gpac -i file.mp4 inspect:deep``` mentions SAP type = 2.

**Comment by jeanlf** [comment]
> Should that be updated to include BLA? What about RADL?

this is just a quick summary of the import, we don't show all variations of IDRs and BLA. As @rbouqueau  said, use inspect:deep filter for more details on the stream.

**Comment by ValZapod** [comment]
So why when gpac.exe -i b-frames.hevc inspect:deep

it says it is sap 1? Is it a bug?

**Comment by rbouqueau** [comment]
I confirm: mp4 mentions sap2 but raw mentions sap1.

**Comment by rbouqueau** [comment]
I pushed a fix. Thanks for the report!

**Comment by ValZapod** [comment]
> I pushed a fix. Thanks for the report!

Your commit also fixes http://slydiman.me/ffmpeg/b-frames-yuv422p10le.hevc that is also SAP 2. Nice. BTW, you do not use sdtp box? See https://github.com/FFmpeg/FFmpeg/commit/ab77b878f1205225c6de1370fb0e998dbcc8bc69

**Comment by ValZapod** [comment]
I imagine we have it already: https://trac.ffmpeg.org/ticket/7123
