### ISSUE TITLE
uncompressed YCbCr can't be decoded to a file

### ISSUE THREAD

**Issue by bradh** [gpac/gpac#2467]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

I have created a couple of test uncompressed files with Y Cb Cr components (no subsampling). Converting those to PNG, JPEG or YUV fails with unable to convert caps.

A simple way to reproduce this is:

```
#gpac uncvg:c=Y,U,V:fps=0 -o gpac_yuv.heif
$ ../../gpac/bin/gcc/gpac -i gpac_yuv.heif -o out.yuv
No suitable filter to adapt caps between pid gpac_yuv.heif in filter uncvdec to filter writegen, disconnecting pid!
session last connect error Filter not found for the desired type
```

In addition, trying with PNG will segfault:
```
$ ../../gpac/bin/gcc/gpac -i gpac_yuv.heif -o out.png
No suitable filter to adapt caps between pid gpac_yuv.heif in filter uncvdec to filter encpng:1.6.37, disconnecting pid!
Segmentation fault (core dumped)
```

This doesn't appear to happen with other components - mono, mono+alpha planar, RGB pixel interleave, RGBA pixel interleave, and RGB planar appear OK.

**Comment by ValZapod** [comment]
PNG does not support YCbCr, at least without very recent cICP spec allows to specify range, matrix https://github.com/FFmpeg/FFmpeg/commit/6f79f0971e8ccf6c7a2b8eb1dbc5b64fdd77ca0f and even with sBIT chunk to specify 10 bit or 12 bit, https://github.com/FFmpeg/FFmpeg/commit/84b454935fae2633a8a5dd075e22393f3e8f932f. All of those would be needed to support that, but why if AVIF already does?

**Comment by jeanlf** [comment]
> In addition, trying with PNG will segfault:

fixed in master thanks!

The rest is due to your build not having ffmpeg support, which is needed to convert the YUV444 to RGB (for .png output) or to YUV420 (for .yuv output).

I just added a [new filter](https://github.com/gpac/gpac/wiki/evgs) based on our soft rasterizer for that, so you should now be able to convert to PNG or YUV directly with ffmpeg-disabled builds.

**Comment by bradh** [comment]
Thanks. The new evgs filter functionality works well, and I no longer see the segfault.
