### ISSUE TITLE
Is it possible to combine a series of WebM files into a Dash MPD playlist?

### ISSUE THREAD

**Issue by diegoboston** [gpac/gpac#2478]
I have a tool that creates a series of 1 sec webm files (with Alpha information in the BlockAdditional element of each packet). Is it possible to create a Dash playlist, using MP4Box or gpac as follows?

- the segments are played in a sequence
- the video is not transcoded
- the alpha channel is preserved

I tried a variety of commands like:
```
MP4Box -dash 10000  /alpha/video_0000.webm:Period=0 /alpha/video_0001.webm:period=1 --muxtype=webm
```
This gets close, but it transcode to MP4. I also get an error saying:
```
Arg muxtype set but not used
```

I'm on Ubuntu 20. I installed gpac and mp4box with
```

 apt-get update && apt-get install -y --no-install-recommends libjpeg62 gpac 
 wget https://download.tsi.telecom-paristech.fr/gpac/release/2.2.1/gpac_2.2.1-rev0-gb34e3851-release-2.2_amd64.deb
 dpkg -i gpac_2.2.1-rev0-gb34e3851-release-2.2_amd64.deb 

```

Thanks for helping.

**Comment by jeanlf** [comment]
You need to generate the mpd in live profile for that

`MP4Box -dash 10000  /alpha/video_0000.webm:Period=0 -out dash/live.mpd -profile=live --muxtype=webm`

you should end up with the init and the segment.

It might be simpler to create a simple playlist with all your sources and do
 
`gpac -i pl.m3u:sigcues -o dash/live.mpd --muxtype=webm`

This way each segment will match your input files

Not sure however if the alpha would be preserved, could you upload some sample files  ?

**Comment by diegoboston** [comment]
Thanks for the prompt answer. Here are two files to combine. They have all the same duration (1 sec), but in general they may be different.

[video_0000.webm](https://github.com/gpac/gpac/assets/8549838/e3dc1469-27dc-4d52-834f-f8f3540c3774)
[video_0001.webm](https://github.com/gpac/gpac/assets/8549838/c01ebc32-6fb9-4267-848b-f12610b76426)

In the meantime, I had to tweak the command slightly as follows (no equal between profile and live
```
MP4Box -dash 10000  /alpha/video_0000.webm:Period=0  /alpha/video_0001.webm:Period=1 -out dash/live.mpd -profile live --muxtype=webm
```
but I get a warning:
```
Arg muxtype set but not used
```

**Comment by jeanlf** [comment]
> Arg muxtype set but not used

You need to use latest master, downloads are [here](https://gpac.wp.imt.fr/downloads/gpac-nightly)

Using latest master, the alpha_mode tag is preserved in the dashed webm files.
