### ISSUE TITLE
DashCast ignores command line parameters if a configuration file is present

### ISSUE THREAD

**Issue by cconcolato** [gpac/gpac#248]
Run dashcast once without -low-delay. This will create dashcast.conf with low-delay=no
Run dashcast again with -low-delay in the command line. The low-delay is ignored because the configuration file is used.
Command line parameters should override the configuration file, not the opposite.

**Comment by JamesXu20150314** [comment]
Could you try to the option of '-live', I can't get right number of the segment.
My command is

D:\wamp\www>DashCast -vf dshow -vres 1280x720 -vfr 24 -v video="screen-capture-recorder" -live -npts -low-delay -mpd-refresh 2

Here is a strange error.

JamesXu.

**Comment by JamesXu20150314** [comment]
This guideline is very useful.
Thank you very much.

**Comment by JamesXu20150314** [comment]
I want to get live stream from DashCast, and I will play by the dash.js.
Could you give me some guideline.

JamesXu

**Comment by cconcolato** [comment]
@JamesXu20150314 Please don't cross-post, don't duplicate your post and don't add comments to issues if they are not related to the issue. I've deleted such posts.

**Comment by jeanlf** [comment]
dashcast is now deprecated, use GPAC 0.9.0
