### ISSUE TITLE
Remove different tiles for each frame

### ISSUE THREAD

**Issue by pratikbendre47** [gpac/gpac#2481]
Is there a way to remove different tiles for each frame or segment? For example, if I have a 3x3 tiled video, can tile 3 from 1st frame and tile 4 from 2nd frame be removed?

**Comment by jeanlf** [comment]
you will likely break the decoding, unless all tiles are coded in intra.

That being said, you can use  reframer filers after each PID produced by the tilesplit filter, setting the `frames`option of the reframer to drop your frame.

Alternatively (and likely more flexible), write a JS filter doing the filtering job and set it after the tilesplit filter.
