### ISSUE TITLE
mp4box produces unplayable video at strange conditions

### ISSUE THREAD

**Issue by slydiman** [gpac/gpac#2486]
mp4box v2.3-DEV-rev301
I have faced very strange bug remuxing files from Canon C300.
```
mp4box -add video.h264 -add audio1.wav -new nofps_ok.mov
mp4box -add "video.h264:fps=25" -add audio1.wav -new fps25_ok.mp4
mp4box -add "video.h264:fps=25" -new fps25_noaudio_ok.mov
mp4box -add "video.h264:fps=25:dur=3" -add "audio1.wav:dur=3" -new fps25_3sec_ok.mov
mp4box -add "video.h264:fps=25" -add audio1.wav -new fps25_bad.mov
```
The file fps25_bad.mov is unplayable. 
It is stuck in MediaPlayerClassic (on Windows) at opening. It can be played (video and audio) after seeking to 1 sec.
VLC can playback audio only and 1 static frame.

mp4 with the same parameters is ok.
mov without audio is ok.
mov without fps is ok.
mov 1 sec shorten  is ok.
I have no idea what is wrong. Please investigate.

Samples:
http://slydiman.me/ffmpeg/unk/video.h264
http://slydiman.me/ffmpeg/unk/audio1.wav
http://slydiman.me/ffmpeg/unk/fps25_bad.mov

**Comment by jeanlf** [comment]
Indeed, now fixed in master thanks for the detailed report and files.
