### ISSUE TITLE
no audio sometimes in fragment mp4

### ISSUE THREAD

**Issue by fastfading** [gpac/gpac#2488]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x ] I looked for a similar issue and couldn't find any.
- [x ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

I found some mp4box converted file audio is missing  on some players such as vlc ,windows media player and adobe premier 2023
detail and files are here
https://code.videolan.org/videolan/vlc/-/issues/27328

convert cmd is 
MP4Box -dash 30000 -profile onDemand mp4box.mp4 -out dash.mpd --dual

**Comment by fastfading** [comment]
if I converted this fmp4 to normal.mp4 , audio play fine
ffmpeg -i fmp4.mp4 -c copy normal.mp4

**Comment by rbouqueau** [comment]
It plays with gpac and ffplay. Seems like a VLC issue.

Could you share details on how the file was generated?

**Comment by jeanlf** [comment]
Indeed, we had a drift issue due to aborting the audio rep before the video rep in muxed content with video duration much larger than requested dash duration - in your file, the first seg is 53 secs.

Thanks for the report!

**Comment by fastfading** [comment]
> Indeed, we had a drift issue due to aborting the audio rep before the video rep in muxed content with video duration much larger than requested dash duration - in your file, the first seg is 53 secs.
> 
> Thanks for the report!

Thank you ,  
Base on our testing.  most of the mp4 is fixed.  
however we found some cases ,   after 
MP4Box -dash 30000 -profile onDemand music_normal.mp4  -out music.mpd --dual

Windows media player still have some issues when play the last part of the mp4 
when seek to the last part of the video.  it is not playable and will jump back to the beggining . 
I guess there is some boundary conditions may not been taken into consideration.

sorry ，  I can not provide an example because it is customer data.  
But I notice that the last part of m3u8 looks like this. 

#EXTINF:30
#EXT-X-BYTERANGE:417918@80149025
timely_dashinit.mp4
#EXTINF:30
#EXT-X-BYTERANGE:431053@80566943
timely_dashinit.mp4
#EXTINF:16.96
#EXT-X-BYTERANGE:284118@80997996
timely_dashinit.mp4
#EXTINF:13.44
#EXT-X-BYTERANGE:123648@81282114
timely_dashinit.mp4


the file in this link https://code.videolan.org/videolan/vlc/-/issues/27328   may have the same issue 
#EXTINF:30
#EXT-X-BYTERANGE:2382085@11267984
music_normal_dashinit.mp4
#EXTINF:30
#EXT-X-BYTERANGE:2434397@13650069
music_normal_dashinit.mp4
#EXTINF:10.6
#EXT-X-BYTERANGE:237852@16084466
music_normal_dashinit.mp4
#EXTINF:0.08
#EXT-X-BYTERANGE:10272@16322318
music_normal_dashinit.mp4

but the last part is 0.08s ,  so it is not very obvious

**Comment by fastfading** [comment]
I am not quite sure about the split logic , looks the last 2 fmp4 should not be splited .

**Comment by jeanlf** [comment]
the split logic is governed by the `sbound` parameter of the dasher. The default mode is to cut at each sync frame at or after the target segment duration. In your test file, the first IDR is at 23s and the second is at 53s, resulting in the first segment being 53s long. This makes the dasher try to compensate the drift in the next segments, hence creating two shorter segments at the end (first one due to drift compensation, second one due to end of stream).

If you're not too worried about latency, you should try specifying `in` or `closest` mode for sbound, which should avoid this in most cases, by buffering until next sync frame before deciding on the segment boundary.

Note that this is dependent on the sync frame distribution, some distributions may cause these short splits.

**Comment by fastfading** [comment]
@jeanlf   
Base on our testing. most of the mp4 is fixed.
however we found some cases , after
MP4Box -dash 30000 -profile onDemand music_normal.mp4 -out music.mpd --dual

Windows media player still have some issues when play the last part of the mp4
when seek to the last part of the video. it is not playable and will jump back to the beggining .
I guess there is some boundary conditions may not been taken into consideration.

we got the customer's permission to share one of the example , 
but I want to share it to you in private rather than put it here publicly
could you  give me an email or something I can reach to you .

**Comment by rbouqueau** [comment]
If you use our uploading system, only the GPAC maintainers will see the link: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by fastfading** [comment]
> If you use our uploading system, only the GPAC maintainers will see the link: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

thanks 
I have upload this file  (timely_dashinit.mp4) to above link. 
the last 30s  can not been seen on windows media player. 
when seek to the last 30s of the video. it is not playable and will jump back to the beggining .

**Comment by fastfading** [comment]
please try use this link 
https://mega.nz/file/nLZz3ahL#Ew5SJMkAWYBu0_RCASmGeJXuiCnlqD5yziiyqkcjVLk
Windows media player still have some issues when play the last 30s of the mp4
when seek to the last 30s of the video. it is not playable and will jump back to the beggining .
I guess there is some boundary conditions may not been taken into consideration.

**Comment by fastfading** [comment]
for Issue https://github.com/gpac/gpac/issues/2488
please try use this link 
https://mega.nz/file/nLZz3ahL#Ew5SJMkAWYBu0_RCASmGeJXuiCnlqD5yziiyqkcjVLk
Windows media player still have some issues when play the last 30s of the mp4
when seek to the last 30s of the video. it is not playable and will jump back to the beggining .
I guess there is some boundary conditions may not been taken into consideration.

**Comment by jeanlf** [comment]
Here's what I checked:
- dashing using 15s segments instead of 30s: playback until end OK
- dashing video only with 30s segments: playback until end OK
- dashing audio only with 30s segments: playback until end OK

The segment durations in 30s Audio+Video and 30s VideoOnly are the same, and the last segments are correct. 

I think that's a WMP bug, there's not much we can do here.

**Comment by fastfading** [comment]
> Here's what I checked:
> 
> * dashing using 15s segments instead of 30s: playback until end OK
> * dashing video only with 30s segments: playback until end OK
> * dashing audio only with 30s segments: playback until end OK
> 
> The segment durations in 30s Audio+Video and 30s VideoOnly are the same, and the last segments are correct.
> 
> I think that's a WMP bug, there's not much we can do here.

thank you very much ,  I will check with wmp and update later
