### ISSUE TITLE
DashCast uses hardcoded audio configuration

### ISSUE THREAD

**Issue by cconcolato** [gpac/gpac#249]
Audio is hardcoded as stereo @ 44100 hz. The configuration of the input should be used instead.

**Comment by cconcolato** [comment]
The audio representation element also sets hard coded values:
https://github.com/gpac/gpac/blob/f85197f20cec31205a0797bbc54ac44161c309bc/applications/dashcast/controler.c#L214

**Comment by jeanlf** [comment]
dashcast is now deprecated, use GPAC 0.9.0
