### ISSUE TITLE
GPAC 2.0 caches input stream

### ISSUE THREAD

**Issue by shubhamchdhary** [gpac/gpac#2490]
Hi, 
I'm trying to encode a continuous HEVC byte stream from Kvazaar, but not sure why GPAC keeps the encoded output byte stream in its buffer. The whole stream is dumped into a file only when I break the pipeline.

I've looked into different issues and even checked the documentation to fix. I've tried all the options such as --no-cache, --no-block, --no-reservoir, --no-graph-cache, etc.

**Comment by rbouqueau** [comment]
> GPAC keeps the encoded output byte stream in its buffer.

How do you know that? When does it happen? What is your command-line?

**Comment by shubhamchdhary** [comment]
I'm using:

On terminal 1: kvazaar -i a.hevc --input-res 1280x720 --input-fps 30 --tiles 4x4 --slices tiles --mv-constraint frametilemargin --preset superfast -o named_pipe1  
On terminal 2: cat named_pipe1 | gpac -i - tilesplit @ -o /dev/fd/1

If I only run cat named_pipe1 on terminal 2, I can see the byte stream. But if the above command is run on terminal 2, then the bytes are dumped on only when the encoding ends or when I manually stop using Ctrl+C.

**Comment by rbouqueau** [comment]
Could you retry with the latest version? We've made recent change in pipe flushing.

**Comment by jeanlf** [comment]
You are not specifying an output format, which currently maps to mp4 (I'll check if we can improve logs here).  Since your are not writing in fragmented mode , the muxer will only output results once the file is built.
 Try changing output format or fragmented mode, eg `-o /dev/fd/1:ext=mp4:frag`

**Comment by shubhamchdhary** [comment]
Thanks a lot, using `:frag` worked. But, it is dumping the byte stream at certain time intervals. Can you pls tell me how can set this time period?

**Comment by jeanlf** [comment]
>  it is dumping the byte stream at certain time intervals
yes, data is dumped after each fragmented is completed. You can set the fragment duration using `:cdur` option (1s by default).

**Comment by shubhamchdhary** [comment]
Okay, can you pls tell me one more thing? How many frames is it dumping in each fragment? Does it depends on `:cdur`? . Like for 30fps `cdur` of 1s means 30 frames. Also, I tried `:flat` option also. But the dumped files are corrupted.

**Comment by jeanlf** [comment]
> Does it depends on :cdur? . Like for 30fps cdur of 1s means 30 frames

yes

> Also, I tried even :flat option. But the dumped files are corrupted

`flat` requires seeking support on output to update the mdat box size, so it is not compatible with pipe outputs. The command line should fail with message `[PipeOut] Block patching is not supported by pipe output`

**Comment by shubhamchdhary** [comment]
Okay, thanks a lot.
