### ISSUE TITLE
I want to ask some questions about python api(ABS)

### ISSUE THREAD

**Issue by a23232390** [gpac/gpac#2498]
1.I want to test my own Adaptive Bitrate Streaming (ABS). Is fs.http_max_bitrate used to limit the download rate? I set fs.http_max_bitrate=700000, but it did not reflect on stats.total_rate and stats.download_rate. What should I do?

2.For most cases, is the switching of video quality based on stats.total_rate?

**Comment by jeanlf** [comment]
> Is fs.http_max_bitrate used to limit the download rate?

yes

>  it did not reflect on stats.total_rate and stats.download_rate

It should, unless your files are small and downloaded faster than the http rate regulation. You can verify this using `-logs=http@info` or `-logs=http@debug` 

> For most cases, is the switching of video quality based on stats.total_rate?

If you define your own algorithm, the quality switching is only based on the return value of the `on_rate_adaptation` function.

For GPAC builtin alogos, it is algo-specific (some ignore the total rate, some use it)
