### ISSUE TITLE
DashCast sets the mediaPresentationDuration to 0 if mp4 input is fragmented

### ISSUE THREAD

**Issue by cconcolato** [gpac/gpac#250]
This is probably a problem with ffmpeg not reporting the correct duration.

**Comment by Clement-TS** [comment]
I got an error as well from dashjs, saying mediaPresentationDurant or minimumUpdatePeriod have to be set.
I'm using DashCast with the following command : 

```bash
DashCast -av udp://@239.1.1.1:8200?fifo_size=100000 -out /tmp/dash
```

My input stream is MPEG2-TS with h.264 encoding.

**Comment by jeanlf** [comment]
dashcast is now deprecated, use GPAC 0.9.0
