### ISSUE TITLE
Can I change metadata of an Atmos file, specifically the Complexity index. 

### ISSUE THREAD

**Issue by rkuli** [gpac/gpac#2500]
Hello, I am trying to configure some Atmos files so they can play properly on my iPhone. Figured out what was causing the issue was the Complexity Index in the Atmos mediainfo was labeled "Not Present/16" instead of just "16." Tested two different files with MP4Box and one file that didn't say "Not Present" was recognized as ATMOS while the other that listed it didn't. How can I change the complexity index to get rid of "Not Present?"

**Comment by jeanlf** [comment]
could you upload your two sample files ?

**Comment by rbouqueau** [comment]
@rkuli Could you share how your issue was solved? It may be useful to other users as well.

**Comment by rkuli** [comment]
> @rkuli Could you share how your issue was solved? It may be useful to other users as well.

Used ffmpeg to convert the M4A/MP4 to an MKV, used MKVToolNix to have both an audio and visual stream, then used MP4Box to merge both into an MP4

**Comment by rbouqueau** [comment]
If you share a sample with us, we'd be happy to fix the loss of metadata and tag.

**Comment by rkuli** [comment]
The file with the 10 is the original and the other file is the altered one I did to get rid of the “Not  Present” in the Complexity Index

**Comment by jeanlf** [comment]
for both, source is the original file (missing the atmos signaling)

**Comment by rkuli** [comment]
> 

Just tried it, works great, thank you so much, this makes it so much easier
