### ISSUE TITLE
I want to ask some questions about python api(tileagg ) 

### ISSUE THREAD

**Issue by a23232390** [gpac/gpac#2509]
processing time of the tileagg filter: you need to locate the filter in your session and call get_statistics on it - you will have a FilterStats object, check the time_process field

1.I'm sorry, could you please tell me how to call the get_statistics function?
You can use the following example
2. Always trigger [TileAgg] No frames on tile base pid V1 after 33977 ms, discarding all tiles WHY?

"Advanced example" in https://github.com/gpac/gpac/wiki/python

**Comment by jeanlf** [comment]
please do not reopen new issue, continue discussion in #2502
