### ISSUE TITLE
DashCast transcode a live stream in multiple qualities on windows7 64bit.

### ISSUE THREAD

**Issue by JamesXu20150314** [gpac/gpac#251]
When I play the live stream which product by the dashcast in dash.js player. I found that the dash.js player can not product right segment number. 

Such as the dashcast is producting the segement 10. But the dash.js are requesting the segment 97.

This means that the dash.js can not calculate right number of the segment according the MPD file.

Here is my command.

D:\wamp\www>DashCast -vf dshow -vres 1280x720 -vfr 24 -v video="screen-capture-recorder" -live -npts -low-delay -mpd-refresh 2

I hope that you can help me.

JamesXu

**Comment by rbouqueau** [comment]
What does the conformance checker says? http://dashif.org/conformance.html

**Comment by JamesXu20150314** [comment]
Thanks for your answer.
Could you tell me how can I play a live stream with the help of dashcast.

I use the dash.js player. I want to use the input mp4 file as a live stream.

JamesXu

**Comment by rbouqueau** [comment]
What does the conformance checker say? http://dashif.org/conformance.html

**Comment by JamesXu20150314** [comment]
Thank you.
I have answered this question in the  http://dashif.org/conformance.html.

I think the "availabilityStartTime" is wrong if I use the -live option.
Could you look at it.. 
And I want to know that is this "availabilityStartTime" is uniform in the world.

JamesXu

**Comment by JamesXu20150314** [comment]
By the way, I come from China.

**Comment by cconcolato** [comment]
@JamesXu20150314 If you want us to help, you have to provide the information we ask: 

> What does the conformance checker say? http://dashif.org/conformance.html

Provide the details of what the conformance checker reports!

**Comment by JamesXu20150314** [comment]
Thanks for your answer.
They have not answer me until now.
I means that when I use the -live option. The dashcast will drop some segment.

Such as the output, there lost the segment 15.
Generating MPD at 2015-09-19T10:24:52.559Z
StartTime: 2015-09-19T10:24:39.920Z - startNumber 1 - last number 13
[video_encoder] Rep v1 UTC diff 15198 bigger than segment duration 13 - some frame where probably lost. Adjusting
Generating MPD at 2015-09-19T10:24:53.850Z
StartTime: 2015-09-19T10:24:39.920Z - startNumber 1 - last number 14
Generating MPD at 2015-09-19T10:24:55.121Z
StartTime: 2015-09-19T10:24:39.920Z - startNumber 1 - last number 16
Generating MPD at 2015-09-19T10:24:55.157Z
Unable to delete the file output/v1_6_gpac.m4s
StartTime: 2015-09-19T10:24:39.920Z - startNumber 1 - last number 17
Generating MPD at 2015-09-19T10:24:56.405Z
StartTime: 2015-09-19T10:24:39.920Z - startNumber 1 - last number 18

My command is 
DashCast -vf dshow  -vres 1280x720 -vfr 24 -v video="screen-capture-recorder" -live -npts -low-delay

And when I play, dash.js will occur a stange error. Also it can not output right segment.

I think the segments' lost is a very serious problem. Could you help me with the lost of segment problem first. I think maybe this is the problem taht arouse these problem.

JamesXu

**Comment by JamesXu20150314** [comment]
More accurately, how to solve the problem of lost segment.

As the output information. It lost the segment 6.

Generating MPD at 2015-09-19T10:36:28.099Z
StartTime: 2015-09-19T10:36:04.192Z - startNumber 1 - last number 3
[video_encoder] Rep v1 UTC diff at segment close: 49206 is higher than cumulated segment duration 40000 (diff 9206) - frame rate is probably not corre
ct!
Generating MPD at 2015-09-19T10:36:40.741Z
StartTime: 2015-09-19T10:36:04.192Z - startNumber 1 - last number 4
[video_encoder] Rep v1 UTC diff 61816 bigger than segment duration 4 - some frame where probably lost. Adjusting
Generating MPD at 2015-09-19T10:36:53.401Z
StartTime: 2015-09-19T10:36:04.192Z - startNumber 1 - last number 5
[video_encoder] Rep v1 UTC diff at segment close: 61867 is lower than cumulated segment duration 70000 (diff -8133) - frame rate is probably not corre
ct or frames were lost!
Generating MPD at 2015-09-19T10:37:06.009Z
StartTime: 2015-09-19T10:36:04.192Z - startNumber 1 - last number 7

Thank you.

JamesXu.

**Comment by JamesXu20150314** [comment]
By the way, all my test is excute with the -live option, -npts option and -low-delay option in windows7 64bit system.

**Comment by jeanlf** [comment]
dashcast is now deprecated, use GPAC 0.9.0
