### ISSUE TITLE
Problem playing content stored on the server

### ISSUE THREAD

**Issue by Egea53** [gpac/gpac#2510]
Hi, I'm using kvazaar for a university project and I'm having a little problem. I would appreciate if someone help me to solve it. I am working with five different qualities of the same video (480p,720p,1080p,2k,4k)
I have generated the segments (for all the qualitis) and stored them on a server. I am working with WSL2 and I have the server in windows.
So to play the content, I use the following command gpac -gui http://192.168.1.221/TFG/dash_tiled.mpd#VR

The problem is that I get a black screen. I have captured the traffic with wireshark and I have obtained two different cases. Sometimes only the "init" files are requested and the segments are not requested. And in other cases everything seems to be fine. The client requests the "init" files and segments and the server provides them I have tried to reproduce the 5 mpds of the 5 qualities and they all work correctly. The problem is the mpd with more than one representation.

I attach the mpd and the wireshark captures that proves that sometimes the traffic is correct and  the client dosen't request the segments

![no segments](https://github.com/ultravideo/kvazaar/assets/106270238/6844c66c-7262-462c-bfa4-68070f1f1c92)
![segments](https://github.com/ultravideo/kvazaar/assets/106270238/e05ca2f9-4c01-4304-b1d6-c6f71688c359)
mpd: https://drive.google.com/file/d/1YcfiUMpgy-_0Iz6tGqd-vgUtmG_DsybQ/view?usp=sharing

I would appreciate if someone help me to solve it

**Comment by Egea53** [comment]
> Hi, I have generated the segments and stored them on a server. I am working with WSL2 and I have the server in windows. So to play the content, I use the following command gpac -gui http://192.168.1.221/TFG/dash_tiled.mpd#VR
> 
> The problem is that I get a black screen and after a few seconds in the console I get the message "No frames on tiled pid V2 after 212423 ms, reaggregating with lost tiles"
> 
> I would appreciate if someone help me to solve it

**Comment by jeanlf** [comment]
- please upload your content somewhere
- can you reproduce using a web server in the wsl2 environment ?

**Comment by Egea53** [comment]
For the project I need to have the server in the windows environment. 

I have created a different mpd for each of the five qualities and those work correctly. The problem occurs when I try to play the mpd that includes all 5 qualities

Here I leave a link with the folder that includes all the segments and the mpd. And also ordered by folders the segments of each quality with their respective mpd (which do work correctly) https://www.transfernow.net/dl/20230704gKMjpylo

**Comment by Egea53** [comment]
After some tests I managed to play the beginning of the video, stored in the "initi" file but I get the error "No filter chain found for PID vout in filter ffenc to any loaded filters - NOT CONNECTED"
I don't know what this could be

**Comment by rbouqueau** [comment]
The video encoder couldn't be setup.

What's your command-line? What's your GPAC build/version/os and how did you get it?

Note that if you use GPAC for tiling, your build must enable the ```kvazaar``` encoder, cf https://github.com/gpac/gpac/wiki/HEVC-Tile-based-adaptation-guide#kvazaar-as-a-gpac-filter.

**Comment by Egea53** [comment]
Sorry, I don't quite understand the instructions to enable the kvazaar encoder. When should I add that? Before creating the mpd or before playing it?

My command line is gpac -gui http://192.168.1.221/TFG/Playa/manifest.mpd#VR

I installed gpac following this https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux

**Comment by Egea53** [comment]
I have been trying this https://github.com/gpac/gpac/wiki/HEVC-Tile-based-adaptation-guide#kvazaar-as-a-gpac-filter. but I have not been able to apply it correctly and I get an error. Possibly these errors come because I don't know very well in which part of my process I should apply it.
The process that I have followed is the following
1. I have generated 5 different qualities of the video with ffmpeg
2. I have passed the videos to .yuv
3. I have created the tiles of each quality with the command kvazaar -i out720.yuv --input-res 1280x720 -o output720.hvc --tiles 3x3 --slices tiles --mv-constraint frametilemargin --bitrate 5000000 --period 3000 --input-fps 30
4. I use the command MP4Box -add output720.hvc:split_tiles -fps 30 -new video720_tiled.mp4
5. I use the command MP4Box -dash 1000 -rap -frag-rap -profile live -out dash_tiled.mpd video480_tiled.mp4 video720_tiled.mp4 video1080_tiled.mp4 video2_tiled.mp4 video4_tiled.mp4 to generate a mpd with the 5 qualities
6. Finally i use the command gpac -gui http://192.168.1.221/TFG/Playa/manifest.mpd#VR to reproduce the content

What I am doing wrong? Why do I get a black screen? 

Thank you very much for the help!

**Comment by Egea53** [comment]
https://www.transfernow.net/dl/20230710RsrL66hs

**Comment by jeanlf** [comment]
This should now be fixed on master, we were not supporting multiple instances of tileagg properly. Thanks for the report

**Comment by Egea53** [comment]
So I can't use a mpd with different qualities? or was it already fixed?

**Comment by Egea53** [comment]
i created the mpd again and i get this

![image](https://github.com/gpac/gpac/assets/106270238/f831bf77-62d6-4eb7-ad12-1a69ea61f003)

**Comment by jeanlf** [comment]
make sure to recompile master first.

You can use multiple resolutions in tiled mode as in your example, however rate adaptation in GPAC only works for representations of an adaptation set; so for tiled mode, this means only for tiles of same resolution but different bitrates. In your case, each resolution will appear as a different video stream in the GUI and you can select one in the set manually, but not automatically.

**Comment by Egea53** [comment]
Yes, I have recompiled the master. 

so there is no way to automatically play an mpd with different resolutions?

**Comment by jeanlf** [comment]
> so there is no way to automatically play an mpd with different resolutions?

if you mean automatically adjust rate across tiled multi-resolution files, then not in gpac. This requires reassembling tiles in a different grid (so complete rewrite of pps/sps and slice headers), which at the moment cannot be done automatically. You may want to look at the hevcmerge and hevcsplit filters which provide such tools, but this will require some coding to use that automatically with dash, and we're not planning on working on that in the near future.

**Comment by Egea53** [comment]
Okay, thx!

So I should use one resolution but different bitrates and then create an mpd that references all bitrates

**Comment by Egea53** [comment]
Please, can you give me an example of an mpd with multi representations that works correctly?

**Comment by rbouqueau** [comment]
```gpac avgen:sizes=1280x720,1920x1080:rates=2M,5M c=aac:FID=1 c=264:FID=2:clone -o live.mpd:SID=1,2``` to generate some multi representation content. Type ctrl-c then 'enter' to stop the generation (gpac will display some instructions).

**Comment by Egea53** [comment]
But in what part of the process should I do that? And how do I indicate which is the input video? 

I mean, I'm following this tutorial https://github.com/gpac/gpac/wiki/Tiled-Streaming, where should I enter the command you say?

**Comment by jeanlf** [comment]
cf test dash-srd-hevc-dual in https://github.com/gpac/testsuite/blob/master/scripts/dash-srd-hevc.sh

**Comment by Egea53** [comment]
I'm sorry but I don't quite understand what command I have to put, with "$MP4BOX -dash 1000 -profile live $TEMP_DIR/file1.mp4 $TEMP_DIR/file2.mp4 -out $TEMP_DIR/file.mpd" is the one I tried and didn't it worked
