### ISSUE TITLE
How to extract frames of tiled mp4 using Python API

### ISSUE THREAD

**Issue by shubhamchdhary** [gpac/gpac#2518]
Hi,
I want to extract the frame of a tiled mp4 using the Python API of GPAC, then process and render using OpenCV. Can you please tell me how to do it? I tried the custom_sink.py, but it throws errors. I also looked into this https://github.com/gpac/gpac/issues/1761 issue. 

When I ran the custom_sink.py on a tiled HEVC from Kvazaar, it ran and showed packets like this.
```
[  0   0   0  16   2   1 255  17 106  79 221  17 128 226 176 220   0   0
  15 120] (20,)
PCK Prop: 1280, 720

[  0   0   0  17   2   1  65 127  17 106  79 221  17 128 226 176 220   0
   0  15 120] (21,)
PCK Prop: 1280, 720

[  0   0   0  17   2   1  66 191  17 106  79 221  17 128 226 176 220   0
   0  15 120] (21,)
PCK Prop: 1280, 720

[  0   0   0  17   2   1  67 255  17 106  79 221  17 128 226 176 220   0
   0  15 120] (21,)
PCK Prop: 1280, 720

```
Can you tell me what these arrays imply? I guess these are frame data. But how can I make OpenCV read them?

But for tiled mp4 videos, it gives this error:
```
Exception ignored on calling ctypes callback function: <function filter_cbk_configure at 0x7f4f818325e0>
Traceback (most recent call last):
  File "/home/shubhamch/project/NetColab/env/lib/python3.8/site-packages/libgpac/libgpac.py", line 2725, in filter_cbk_configure
    filter = cast(obj, py_object).value
ValueError: PyObject is NULL
```

**Comment by jeanlf** [comment]
> Can you tell me what these arrays imply? I guess these are frame data. 

This depends on the code of your custom_sink.py, but yes it looks like the first bytes of the frame data

> But how can I make OpenCV read them?

you need to make sure you ask for uncompressed data - can you share your test python script ?

**Comment by shubhamchdhary** [comment]
I'm using the custom_sink.py provided by GPAC.

**Comment by shubhamchdhary** [comment]
Okay, I'll check. Thank you.
