### ISSUE TITLE
Install the gpac(3744) on ubuntun14.04

### ISSUE THREAD

**Issue by huyang113** [gpac/gpac#252]
I make gpac.
make -C src all
make[1]: Entering directory `/home/huyang/gpac/src'
gcc  -Wall -fno-strict-aliasing -Wno-pointer-sign -O3  -Wall -fno-strict-aliasing -Wno-pointer-sign -fPIC -DPIC -DGPAC_HAVE_CONFIG_H -I"/home/huyang/gpac" -I"/home/huyang/gpac/include" -I"/home/huyang/gpac/extra_lib/include/zlib"  -c -o media_tools/img.o media_tools/img.c 
In file included from /usr/include/png.h:536:0,
                 from media_tools/img.c:35:
/usr/include/zlib.h:86:5: error: unknown type name ‘z_const’
     z_const Bytef *next_in;     /* next input byte */
     ^
/usr/include/zlib.h:86:19: error: expected ‘:’, ‘,’, ‘;’, ‘}’ or ‘__attribute__’ before ‘*’ token
     z_const Bytef *next_in;     /* next input byte */
                   ^
In file included from /usr/include/zlib.h:34:0,
                 from /usr/include/png.h:536,
                 from media_tools/img.c:35:
/usr/include/zlib.h:1025:29: error: unknown type name ‘z_const’
 typedef unsigned (*in_func) OF((void FAR *,
                             ^
/usr/include/zlib.h:1029:33: error: unknown type name ‘in_func’
 ZEXTERN int ZEXPORT inflateBack OF((z_streamp strm,
                                 ^
In file included from /usr/include/png.h:536:0,
                 from media_tools/img.c:35:
/usr/include/zlib.h:1349:32: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Z_ARG’
 ZEXTERN int ZEXPORTVA gzprintf Z_ARG((gzFile file, const char *format, ...));
                                ^
/usr/include/zlib.h:1673:5: error: unknown type name ‘z_off64_t’
     z_off64_t pos;
     ^
/usr/include/zlib.h:1748:1: error: unknown type name ‘z_crc_t’
 ZEXTERN const z_crc_t FAR * ZEXPORT get_crc_table    OF((void));
 ^
/usr/include/zlib.h:1758:44: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Z_ARG’
 ZEXTERN int            ZEXPORTVA gzvprintf Z_ARG((gzFile file,
                                            ^
make[1]: *** [media_tools/img.o] Error 1
make[1]: Leaving directory `/home/huyang/gpac/src'
make: *** [all] Error 2
Could you tell me why?

**Comment by rbouqueau** [comment]
Revision 3744 is from 2011! Source: https://sourceforge.net/p/gpac/code/3744/

Would you consider updating? Or building:
- http://gpac.io/2011/04/20/compiling-gpac-on-ubuntu/
- http://gpac.io/2015/07/29/gpac-build-mp4box-only-all-platforms/

**Comment by rbouqueau** [comment]
PS: installers available at http://gpac.io/downloads/gpac-nightly-builds/
