### ISSUE TITLE
After removing a track "Next track ID" is set to excisting track ID

### ISSUE THREAD

**Issue by L2501** [gpac/gpac#2523]
before
```
mediainfo --Details=10 test.m4a | grep "k ID"                  
000008C   Next track ID:                        3 (0x00000003)
00000C1    Track ID:                            1 (0x00000001)
02A3DBA    Track ID:                            2 (0x00000002)
```
MP4Box -rem 2 test.m4a
```
000008C   Next track ID:                        1 (0x00000001)
00000C1    Track ID:                            1 (0x00000001)
```
importing the file again corrects it: 
MP4Box -add test.m4a -new test2.m4a
```
000008C   Next track ID:                        2 (0x00000002)
00000C1    Track ID:                            1 (0x00000001)
```

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
fixed in 609cba67 (wrong issue number in commit message, my bad)
