### ISSUE TITLE
mp4box option error

### ISSUE THREAD

**Issue by yunabee** [gpac/gpac#2528]
I'm trying to play tiled videos with mp4box.

Tiling low-definition images and high-definition videos with kvazaar, packaging them with mp4box, and then generating mpd and playing them live.

However, it takes too long for low-definition video to change to high-definition.
When I move the point of view, I want to change to high-definition tiles quickly.
So I tried to adjust the maximum buffer length to 4000ms using the mbuffer option, but the error "ARG mbuffer: 4000 set but not used" appears.
(used code: `mp4box -dash 2000 -rap --mbuffer 4000 -profile live -out mbuffer/dash_file.mpd lowvideo.mp4 highvideo.mp4`

This error also occurs when trying to utilize other options, and the option does not apply. 
How do I fix this?
I'm running this on Windows.

Also, I was wondering what options are there to help low-definition tiles quickly change to high-definition.

**Comment by jeanlf** [comment]
`mbuffer` is a playout option, not a content generating one, so use it in the player but not in the packaging step.

In GPAC's dash client, the lowest latency for switching is currently the segment, so you will need to:
- produce shorter segments (say 1s) while packaging
-  use a minimal buffer of less than one segment duration in the player
