### ISSUE TITLE
How to create separate output directories for multiple input sources?

### ISSUE THREAD

**Issue by AhmedAbouelkher** [gpac/gpac#2529]
Hello.
I have been using GPAC for over a year now and I find it amazing and easy to use, but there is one feature that I really want to use, and it is to be able to output to separate output directories for every source input I use.

I extract multiple resolutions from a video mp4 file to support variable bitrate for HLS and DASH video on demand. Then use GPAC to encode these mp4 files to [HLS and DASH](https://github.com/gpac/gpac/wiki/LL-HLS).

In the end, I get all encoded segments (.ts) in a single directory which is very confusing and not ergonomic. [Shaka Packager](https://shaka-project.github.io/shaka-packager/html/tutorials/hls.html#examples) has this feature and I want to use it with GPAC instead and don't know if it exists or not.

**Comment by rbouqueau** [comment]
Hi, thanks for the feedback.

Actually you can do the same as in the Shaka Packager link you gave: ```gpac -i input1:#Template='h264_480p/$File$_$Number$' -i input2:#Template='h264_720p/$File$_$Number$' ...```.

The template property will be propagated to the dasher.

The complete doc is [here](https://github.com/gpac/gpac/wiki/dasher#template-strings). Let us know if you have remarks regarding the doc too.

Is it sufficient or are you referring to something else?
