### ISSUE TITLE
routeout atsc setting major and minor channel numbers

### ISSUE THREAD

**Issue by EK701** [gpac/gpac#2530]
Does routeout atsc support setting major and minor channel numbers?  I looked through the code and it does not look like it, but I wanted to confirm, as I am not much of a coder. It looks like routeout just passes through any channel info it receivers from a DASH feed.

Any confirmation or pointers on how to do this is appreciated!

**Comment by rbouqueau** [comment]
This is not possible but could be added. What is the use-case?

**Comment by EK701** [comment]
Sending a DASH/ROUTE feed to an ATSC 3.0 exciter/modulator.

**Comment by jeanlf** [comment]
now on master using `RouteMajorNo` and `RouteMinorNo` pid properties

**Comment by EK701** [comment]
Wow, that was fast!  Thank you!

**Comment by EK701** [comment]
I compiled the updated release, but it does not appear to be working properly.  Here is what I am running:

`gpac/bin/gcc/gpac -i videos/testlist.m3u reframer:rt=on dasher:profile=live:#ShortServiceName=KXXXX-D:RouteMajorNo=16:RouteMinorNo=1 -o atsc://:ip=239.6.15.16:first_port=30000:carousel=200:bsid=1:llmode
`
When I exit from that command, I get the following:

`Unknown argument ":RouteMajorNo" set but not used by any filter - no matching argument found
Unknown argument ":RouteMinorNo" set but not used by any filter - no matching argument found
`
I'm probably doing something wrong.  Any help is appreciated!

**Comment by EK701** [comment]
I compiled the updated release and it appears to be working.

Thanks again!
