### ISSUE TITLE
Filter pngenc does not support GF_PIXEL_RGBA

### ISSUE THREAD

**Issue by gorinje** [gpac/gpac#2531]
Altough pixel in other formats (GF_PIXEL_RGB,  GF_PIXEL_BGR, etc.) all well supported, image data send with GF_PIXEL_RGBA format to the pngenc filter outputs an image with the correct size, but with no data from the image.

Command line for testing :
gpac -i 32bpp-320x240.bmp -o test.png

with the enclosed image:
[32bpp-320x240.bmp.zip](https://github.com/gpac/gpac/files/12122641/32bpp-320x240.bmp.zip)

**Comment by jeanlf** [comment]
this is not related to pngenc but to rfimg declaring 32bits BI_RGB as RGBA instead of RGBX, now fixed. Thanks for the file
