### ISSUE TITLE
Access player properties

### ISSUE THREAD

**Issue by Egea53** [gpac/gpac#2534]
Hello, I am doing a project at the Polytechnic University of Valencia (UPV) and for its realization, I need to access the GPAC player file and be able to access the properties that are shown in the player (such as the clock time shown in the attached image)
How could I do it?
![image](https://github.com/gpac/gpac/assets/106270238/4c2da7a4-b6ab-4b08-9fc2-6e56d80da769)

**Comment by jeanlf** [comment]
check the gui source code, especially the [stats.js](https://github.com/gpac/gpac/blob/master/share/gui/extensions/player/stats.js) file
