### ISSUE TITLE
uncvg error handling for invalid tile size

### ISSUE THREAD

**Issue by bradh** [gpac/gpac#2535]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). 

Using a current gpac (git 7c6cf9e9cafb4b34efcc30a578b62f453937abe9), with the uncvg plugin, 

```
 ./bin/gcc/gpac uncvg:vsize=20x10:c=Y8,U8,V8:tiles=5x2:interleave=comp:sampling=420:fps=0 -o error.heif
```

produces repeated (10000+) errors of the form:

```
[uncvg] Error processing
Internal error in tile padding: remainder 31 is greater than tile size 30 tile start 0
```

I believe it is because the tile height needs to be a power of 2 for 420 to make sense, and in this case it isn't, so its an operator error. It might be possible to detect this invalid input / configuration rather than generate the errors though.

**Comment by jeanlf** [comment]
indeed, thanks for the report
