### ISSUE TITLE
MP4Box err 256

### ISSUE THREAD

**Issue by lmitcham** [gpac/gpac#2538]
I am using MP4Box to convert h264 files to MP4 in Python on a Pi Zero 2W board.  MP4Box works great, for a while, then throws an error 256.  is there a master list of error codes? Or perhaps, help with this one would get me further along.

Thank you

**Comment by jeanlf** [comment]
this return code is not from MP4Box (error codes for MP4Box and gpac are 1: failure, 2: mem leak - I'll update the doc)
Could you try with a bit more logs, eg add `-logs=all@info` to your command line and see if you see something wrong ?

**Comment by jeanlf** [comment]
doc updated
