### ISSUE TITLE
uncompressed encode / decode with mix interleave and tiling has corrupted image

### ISSUE THREAD

**Issue by bradh** [gpac/gpac#2541]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...).

Generation of uncompressed YUV 422 or 420 image with mixed interleave and tiling appears to work OK:

```sh
$ ./bin/gcc/gpac uncvg:vsize=20x12:c=Y8,U8,V8:tiles=2x2:interleave=mix:sampling=422:fps=0 -o ./uncompressed_yuv422_mix_tiled.heif
$ ./bin/gcc/gpac uncvg:vsize=20x12:c=Y8,U8,V8:tiles=2x2:interleave=mix:sampling=420:fps=0 -o ./uncompressed_yuv420_mix_tiled.heif
```

However viewing those with `gpac -gui` produces corrupted images, for tiles after the first tile.

Example (422):

![image](https://github.com/gpac/gpac/assets/174642/6d4bd415-6279-4eaa-8ce5-d6cc5fb5e287)

I haven't done the work to determine whether the problem is on the encode or decode side, but a quick inspection of the generated file didn't identify any issue, so perhaps on the decode side.

**Comment by bradh** [comment]
I subsequently implemented the decode, and the file looks fine. So almost certainly on the gpac decode side.

**Comment by jeanlf** [comment]
This was indeed a bug in the decoder, now fixed. Thanks for the report
