### ISSUE TITLE
mkv to mp4 remux not working in MP4Box build with Media AutoBuild Suite

### ISSUE THREAD

**Issue by kenichi512** [gpac/gpac#2543]
Operating system: Windows 10 (64-bit)
MP4Box version: MP4Box - GPAC version 2.3-DEV-rev472-g2a2327c3b-ab-suite

I built static MP4Box with [Media AutoBuild Suite](https://github.com/m-ab-s/media-autobuild_suite) but when I use the bin for copy audio and videos streams from MKV container, I get this error.

`
[core] Creating default credential key in D:\Remux\MP4Box/creds.key, use -cred=PATH/TO_FILE to overwrite
Filter fin failed to setup: Filter not found for the desired type
[Importer] Error probing D:\Remux\input\001.mkv
Failure while importing import: Filter not found for the desired type
Error importing D:\Remux\input\input.mkv#1: Filter not found for the desired type
`

Shouldn't the static MP4Box work standalone without depending on other files unlike the GPAC installer package version?

**Comment by aureliendavid** [comment]
Hi, 

The static build has a limited feature set due to some external libraries not being easily statically linkable. 

Most notably the static build doesn't have ffmpeg support which mp4box rely on to handle mkv files. 

So if you want to convert mkvs you'll need to build or install a full version of gpac.

**Comment by rbouqueau** [comment]
I'd be happy to give it a try, not necessarily with m-ab-s (since I don't have a Windows machine at hand). A static build could be handy, and that's something some users reported to have used in the past.
