### ISSUE TITLE
Can I create fixed byte size moof?

### ISSUE THREAD

**Issue by shubhamchdhary** [gpac/gpac#2546]
Hi there,
I'm working on a video streaming application where I want to stream tile-encoded bitstream from a server. The problem is at the receiver to render, I need to wait for all the moof packets to come. The size of moof varies depending on the frame type and scene, right? 

Is there any way to fix the size of moof payloads so that fragments of the same size can be generated? By size, I mean the number of bytes in the fragment. I tried with `:cdur`, but it only fixes the time, not the size.

If this isn't possible, can I know the number of bytes dumped in each fragment when using `:frag`?

**Comment by jeanlf** [comment]
You cannot, fragmentation in GPAC is only time-based. Given the variety of media packaged, their fragmentation constraints and the short duration of the fragments, size-based fragmentation would not make a lot of sense.

you can do something like `MP4Box -diso test.mp4 -std | grep -E MovieFragmentBox\|MediaDataBox` to extract the size of the fragments

**Comment by shubhamchdhary** [comment]
Okay, thank you very much.
