### ISSUE TITLE
Protected DASH - Allow ContentProtection schemeIdUri attribute to be configuratable

### ISSUE THREAD

**Issue by holozip** [gpac/gpac#255]
Hi there,

At present, when dashing protected content with MP4Box, it uses the generic identifier "urn:mpeg:dash:mp4protection:2011" within the generated MPD playlist for element ContentProtection, attribute @schemeIdUri.

This value is currently hardcoded in the following function:
https://github.com/gpac/gpac/blob/master/src/media_tools/dash_segmenter.c#L630

Some vendors use different ContentProtection identifiers that are detailed here:
http://dashif.org/identifiers/protection/

In our case, we're using Widevine, and whilst the majority of clients and players are happy with the generic identifier, some clients such as Chromecast require it set to "edef8ba9-79d6-4ace-a3c8-27dcd51d21ed". 

I managed to work around this in our case by simply recompiling libgpac with the Widevine identifier, but it'd be awesome if there was a feature in mp4box to allow the schemeIdURI to be specified on the command line.

Hopefully this feature request would be useful for other users of gpac, and a nice addition to mp4box's repertoire.

Kind regards,
Gareth

**Comment by sandersaares** [comment]
I believe the general pattern here should be that you *add* any additional ContentProtection elements, rather than replace existing. For example, here is what I would use for Widevine+PlayReady support:

```
AdaptationSet segmentAlignment="true" maxWidth="3840" maxHeight="2160" maxFrameRate="24" par="16:9" lang="und">
			<ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="7d4413fb-a250-47bf-934b-a943dc8ef314" />
			<ContentProtection value="MSPR 2.0" schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95">
				<cenc:pssh>AAAB5HBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAAcTEAQAAAQABALoBPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgArAHgATgBFAGYAVgBDAGkAdgAwAGUAVABTADYAbABEADMASQA3AHoARgBBAD0APQA8AC8ASwBJAEQAPgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==</cenc:pssh>
				<pro xmlns="urn:microsoft:playready">xAEAAAEAAQC6ATwAVwBSAE0ASABFAEEARABFAFIAIAB4AG0AbABuAHMAPQAiAGgAdAB0AHAAOgAvAC8AcwBjAGgAZQBtAGEAcwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBEAFIATQAvADIAMAAwADcALwAwADMALwBQAGwAYQB5AFIAZQBhAGQAeQBIAGUAYQBkAGUAcgAiACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADAALgAwAC4AMAAiAD4APABEAEEAVABBAD4APABQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsARQBZAEwARQBOAD4AMQA2ADwALwBLAEUAWQBMAEUATgA+ADwAQQBMAEcASQBEAD4AQQBFAFMAQwBUAFIAPAAvAEEATABHAEkARAA+ADwALwBQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsASQBEAD4AKwB4AE4ARQBmAFYAQwBpAHYAMABlAFQAUwA2AGwARAAzAEkANwB6AEYAQQA9AD0APAAvAEsASQBEAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA=</pro>
			</ContentProtection>
			<ContentProtection value="Widevine" schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
				<cenc:pssh>AAAANHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABQIARIQfUQT+6JQR7+TS6lD3I7zFA==</cenc:pssh>
			</ContentProtection>
			<Representation id="1" mimeType="video/mp4" codecs="avc1.640015" width="512" height="288" frameRate="24" sar="1:1" startWithSAP="1" bandwidth="391340">
				<ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="7d4413fb-a250-47bf-934b-a943dc8ef314" />
				<SegmentTemplate timescale="24" media="sintel_en-288-400k_dash$Number$.m4s" startNumber="1" duration="96" initialization="sintel_en-288-400k_dashinit.mp4" />
			</Representation>
```

Right now, we just add this data manually after mp4box does its thing. Works well enough for us, really.

**Comment by jeanlf** [comment]
you can also try to insert the descriptor using :desc_as_c=<XML fragment/> on one of the source of your adaptation set, this should work
