### ISSUE TITLE
Problems using the HAS technique and the tiled streaming technique

### ISSUE THREAD

**Issue by Egea53** [gpac/gpac#2554]
For a university project I would like to use the HAS technique (obtaining different resolutions of the same video) and the tile-based streaming technique (dividing the video into different tiles, specifically using a 3x3 division).

I have generated the videos in different resolutions with the ffmpeg tool and later I have used this tutorial to perform the tiled streaming (https://github.com/gpac/gpac/wiki/Tiled-Streaming)
However, I have had problems with the reproduction of the content
I don't know if the problem is that both techniques cannot be used or if I should carry out another process.
I don't know if someone could help me solve this

**Comment by jeanlf** [comment]
multi-resolution HEVC tiled streaming is not yet supported in GPAC, as mentioned previously (#2510 - please don't open new issues for the same topic)
