### ISSUE TITLE
How to convert a png/jpeg image to a heif image with grid size 512x512

### ISSUE THREAD

**Issue by DY-TL** [gpac/gpac#2556]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hi, I want to convert a png/jpeg image to a heif image with a grid size of 512x512. Currently, the possible solutions are as follows: 
1. Split the image into multiple 512x512 subimages using ffmpeg; 
2.  convert each subimage to a hevc stream using ffmpeg. 
3.  Finally, the mp4box tool was used to encapsulate the hevc bitstreams of all sub-images into heif images. 
I was wondering if there was a cleaner way to convert png/jpeg images to heif images. Or can we use the gpac tool instead of ffmpeg to split png/jpeg images into 512x512 subgraphs and transcode them into hevc bitstreams.
Thanks!

**Comment by rbouqueau** [comment]
I couldn't make it work but here are my findings:
- Some features are coded in ```MP4Box``` only, not ```gpac```.
- MP4Box can transcode (to png/jpg) when exporting, but not when importing

If you have the command-lines from FFmpeg, we could port them to GPAC to minimize the number of processing steps.

**Comment by DY-TL** [comment]
Ok, thank you, I will look for a more convenient solution

**Comment by rbouqueau** [comment]
I had hoped someone would show up to help. That's August so most people are absent. Please keep us updated on your solution as it may help us to improve.
