### ISSUE TITLE
How to add name to video tracks in HLS?

### ISSUE THREAD

**Issue by JuanSalazar22** [gpac/gpac#2559]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Is posible to add the `NAME` property to the `#EXT-X-MEDIA` tag when using HLS  multivariant playlist?

I'm using the command 
```
gpac \
        -i udp://225.225.225.225:5000/:gpac:listen=true:tsprobe=true:#Representation=default \
        -i udp://225.225.225.225:5001/:gpac:listen=true:tsprobe=true:#Representation=player-stats \
        -i udp://225.225.225.225:5003/:gpac:listen=true:tsprobe=true:#Representation=nex-gen-stats \
        -i udp://225.225.225.225:5005/:gpac:listen=true:tsprobe=true:#Representation=audio \
        -o /tmp/workdir/content/playlist.m3u8:gpac:llhls=sf:hlsc=true:cmaf=cmf2:dmode=dynamic:pssh=mv:hmode=push:template=segment_hls_$$(openssl rand -hex 5) -broken-cert
```

But the playlist generated is:

```
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-INDEPENDENT-SEGMENTS

#EXT-X-STREAM-INF:BANDWIDTH=1650000,CODECS="avc1.42C028,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=30,AUDIO="audio2"
playlist_1.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=308000,CODECS="avc1.42C028,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=30,AUDIO="audio2"
playlist_2.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=330000,CODECS="avc1.42C028,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=30,AUDIO="audio2"
playlist_3.m3u8

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio2",NAME="audio",AUTOSELECT=YES,URI="playlist_4.m3u8",CHANNELS="2"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio2",NAME="audio",AUTOSELECT=YES,URI="playlist_5.m3u8",CHANNELS="2"
```

Is possible to get the NAME property in the #EXT-X-STREAM-INF tags that contains the variant playlist?
There are examples for multivariant commands?

I'm looking for a playlist similar to this
```
#EXTM3U
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="low",NAME="66", DEFAULT=YES,URI="bunny/playlist_1.m3u8"

#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="low",NAME="67",DEFAULT=NO,URI="cow/playlist_1.m3u8"


#EXT-X-STREAM-INF:BANDWIDTH=140800,RESOLUTION=1920x1080,CODECS="avc1.64002a,mp4a.40.2",VIDEO= "low"
bunny/playlist_1.m3u8
```

It is posible to manipulate the `#EXT-X-MEDIA` tag to use the video instead of the audio?

Thanks in advance

**Comment by rbouqueau** [comment]
That's the way it is done now. What would be the benefit of implementing your changes?

**Comment by rbouqueau** [comment]
HLS spec ref: https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-9.7

**Comment by jeanlf** [comment]
>Is possible to get the NAME property in the #EXT-X-STREAM-INF tags that contains the variant playlist?

NAME is a defined for EXT-X-MEDIA only, so no

> There are examples for multivariant commands?

I'll add some tests asap

> It is possible to manipulate the #EXT-X-MEDIA tag to use the video instead of the audio?

Now on master, using the dasher option `hls_ap` (for audio primary)

**Comment by jeanlf** [comment]
tests now in the [testsuite](https://github.com/gpac/testsuite/blob/master/scripts/hls.sh#L140)
