### ISSUE TITLE
Code Won't Build

### ISSUE THREAD

**Issue by ayuk23** [gpac/gpac#256]
After cloning the repository, running ./configure and make, the project won't build and the following error message comes up...

make[2]: *** [video_encoder.o] Error 1
make[2]: Leaving directory `/.../gpac/applications/dashcast'
make[1]: *** [apps] Error 2
make[1]: Leaving directory `/.../gpac/applications'
make: *** [all] Error 2

I've been following the instructions linked here for Ubuntu 14.04
https://gpac.wp.mines-telecom.fr/2011/04/20/compiling-gpac-on-ubuntu/

Any idea what could be happening?

**Comment by jeanlf** [comment]
Could you post the complete build log for dashcast? Which version of ubuntu are you using?

**Comment by jeanlf** [comment]
also try with ffmpeg instead of libav if possible
