### ISSUE TITLE
MP4Box change input framerate to 25 fps

### ISSUE THREAD

**Issue by wtuemura** [gpac/gpac#2562]
**Tested with**: `GPAC version 2.2.1-rev0-gb34e3851-release-2.2`, `GPAC version 2.3-DEV-rev478-g89285266-master`

**Sample**: https://anonymfile.com/560bg/video1440.7z

**x264 command to encode sample**: `x264-r3107-a8b68eb.exe --preset fast --output-csp i422 --sar 1:1 --bframes 2 --crf 17 --keyint 30 --no-interlaced --videoformat component --output VIDEO1440.h264 mame-1440.avs`

**ffprobe info**: `ffprobe -i VIDEO1440.h264 -hide_banner -probesize 10M`
**Output**:
```
Input #0, h264, from 'VIDEO1440.h264':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: h264 (High 4:2:2), yuv422p(tv, smpte170m/bt709/bt709, progressive), 1920x1440 [SAR 1:1 DAR 4:3], 59 fps, 59.19 tbr, 1200k tbn
```

**MP4Box mux command**: `mp4box -add "VIDEO1440.h264" -new "file.mp4"`
**Output**:
```
Track Importing MPEG-4 AVC - Width 1920 Height 1440 FPS 25000/1000 SAR 1/1
AVC|H264 Import results: 3552 samples (3791 NALUs) - Slices: 119 I 1226 P 2207 B - 1 SEI - 119 IDR - 0 CRA
AVC|H264 Stream uses forward prediction - stream CTS offset: 2 frames
```

**Comment by jeanlf** [comment]
test file is not working, could you reupload ? 

It looks like the input bitstream does not have any FPS info.
 
25 fps is the default framerate when importing content with no FPS info in the bitstream, use `-add SRC:fps=N/D` if needed.

Will reopen if you can upload faulty content

**Comment by wtuemura** [comment]
Hi @jeanlf thank for looking into it.

[Here](https://drive.google.com/file/d/1Z6sJBpedxcz0Wx5OCEMJUWe2ZWz7o4yd/view?usp=drive_link) is the file.

Thanks.

**Comment by wtuemura** [comment]
Hi @jeanlf
Google blocked the download for some reason, link fixed.
Thank you.

**Comment by jeanlf** [comment]
indeed this was due to a very large value in vui timescale, now fixed - thanks for the file!
