### ISSUE TITLE
Quick record example fail: Unknown argument ":frag" set but not used by any filter

### ISSUE THREAD

**Issue by leslie-wang** [gpac/gpac#2566]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I have a need to download one MP4 file and generate fragment MP4 file on the fly. I followed the example https://github.com/gpac/gpac/wiki/HAS-advanced#quick-record-examples, but got this failure. Can someone please help?
```
 % gpac -i http://localhost:8000/gear4.mp4 -o grab/record.mp4:frag
Unknown argument ":frag" set but not used by any filter - possible matches
- range in filters httpin fin
- store (inter|flat|fstart|tight|frag|sfrag) in filters mp4mx
```

**Comment by rbouqueau** [comment]
I can't reproduce. What is the output of ```gpac -version```?

**Comment by leslie-wang** [comment]
I use brew to install on my mac book pro, here is the version
```
% gpac -version
Nothing to do, check usage "gpac -h"
gpac - GPAC command line filter engine - version 2.2.1-revrelease
(c) 2000-2022 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io

Please cite our work in your research:
	GPAC Filters: https://doi.org/10.1145/3339825.3394929
	GPAC: https://doi.org/10.1145/1291233.1291452
```

**Comment by jeanlf** [comment]
could you try adding  `-graph` and post the results ?

**Comment by jeanlf** [comment]
this is the intended behaviour, cf discussion in https://github.com/gpac/gpac/wiki/filters_general#complex-links:
- local file input are remuxed by default
- other inputs are copied

The `nomux` option can be used to change this (I jiust fixed a bug not applying nomux=0 for remote files...)

Alternatively, just specify a reframer:
```
gpac -i HTTP_URL reframer rec.mp4:frag
```

**Comment by leslie-wang** [comment]
Here are outputs for your reference.
```
 % gpac -i http://localhost:8000/gear4.mp4 -graph -o grab/record.mp4:frag
[Cache] Cache size 331900977 exceeds max allowed 100000000, deleting entire cache
Unknown argument ":frag" set but not used by any filter - possible matches
- range in filters httpin fin
- store (inter|flat|fstart|tight|frag|sfrag) in filters mp4mx

Filters connected:
httpin (src=http://localhost:8000/gear4.mp4) (idx=1)
-(PID gear4.mp4) fout (dst=grab/record.mp4:frag) (idx=2)

% gpac -i http://localhost:8000/gear4.mp4 reframer -o grab/record.mp4:frag
[Cache] Cache size 331900977 exceeds max allowed 100000000, deleting entire cache
Unknown argument ":frag" set but not used by any filter - possible matches
- range in filters httpin fin
- store (inter|flat|fstart|tight|frag|sfrag) in filters mp4mx
- raw in filters flist reframer
- frames in filters reframer
Filters not connected:
reframer (idx=2)
```
