### ISSUE TITLE
Create single-init.mp4 from separate init-v1.mp4, init-v2.mp4 so on?

### ISSUE THREAD

**Issue by Murmur** [gpac/gpac#257]
Many dash streams meant to be run on PC or mobile devices use a separate init and segment files per each bitrate stream. It is easy to understand, transcodings may run clustered, easy to text edit manifest.mpd file to create new test case. Just add new or remove bitrate representations in a xml file.

HbbTV specification (unfortunately) chose to use a shared init.mp4 file where 1..n TRAK/MDIA/MINF/STBL/STSD/AVCx objects are embedded in a same file, thus introduce a dependency between each bitrate stream in a manifest file. This is bs-switching=multi in gpac documentation. https://gpac.wp.mines-telecom.fr/mp4box/dash/

Complicates a clustered transcoding use, no easy text edit to change bitrate representations. Changing number of representations require to create a new init.mp4 binary file.  I have this exact problem.

Source manifest has separate init-vX.mp4 per each bitrate representation. I could create a script to download multiple init segment files and run "merge init segments (video, audio)" action. Possible with mp4box without actual data payload video files?

Or is it each seg-v1_001.mp4, seg-v1_002.mp4, seg-v2_001.mp4, seg-v2_002.mp4 payload segments must sample_description_index(0..n) reference to an appropriate init.mp4 STSD/AVCx object array? If that is the case then no simple runtime script is possible.

**Comment by jeanlf** [comment]
you should be able to merge the differents init segments into a single file, as sample_description_index are per track and should be OK if you use -bs-switching=multi
