### ISSUE TITLE
FR: Allow setting default audio track with MP4Box

### ISSUE THREAD

**Issue by Ecksters** [gpac/gpac#2585]
MP4 file format appears to support a default flag on audio tracks as well as subtitle tracks, although not all MP4 players respect this setting, many simply pick the track with the highest ID.

To ensure maximum compatibility, it would be nice if MP4Box could allow setting this flag. FFMPEG currently allows it with the `-disposition:a:1 default` flag, so that may be a useful reference for how it's being done.

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
Use `tkhd` option for that.

Note that default track handling depend on target playback:
- ISOBMFF recommends using same alternateGroup on all tracks, have all track enabled and  only mark the default track as "in movie"

`MP4Box -add audio1:group=1:tkhd=3 -add audio1:group=1:tkhd=1 -new isobmf.mp4`

- QT recommends using the same alternateGroup on all tracks and have only the default track enabled

`MP4Box -add audio1:group=1:tkhd=1 -add audio1:group=1:tkhd=0 -new qt.mov`

The QT way of signaling might be problematic for some ISOBMFF readers, as the spec states "Tracks that are marked as not enabled (track_enabled set to 0) shall be ignored and treated as if not present."

**Comment by Ecksters** [comment]
@jeanlf Thank you for clearing that up, it might help people in the future if the tkhd option had more documentation on how to use it, thanks for letting me know though!
