### ISSUE TITLE
Potential negative value  displayed in Console

### ISSUE THREAD

**Issue by soheibthriber** [gpac/gpac#2588]
``` 13:38:34.273Z] GPAC Session Status: mem  18446744073700581 kb CPU  0 ```

Potential negative value  displayed : 

Command line:
gpac -i https://akamaibroadcasteruseast.akamaized.net/cmaf/live/657078/akasource/out.mpd dashin:forward=file -o route://225.1.1.0:6000 -r

**Comment by jeanlf** [comment]
indeed, should now be fixed on master
