### ISSUE TITLE
Issue to build GPAC on Fedora 21 due to JS functions

### ISSUE THREAD

**Issue by Aumontf** [gpac/gpac#259]
Hi,
Can GPAC be built on Fedora 21?
If yes, how to manage the mozilla js 185 dependency?

Fedora version: Fedora release 21 (Twenty One)
.configure:
./configure
/bin/svnversion
svn: E155036: The working copy at 'gpac'
is too old (format 10) to work with client version '1.8.11 (r1643975)' (expects format 31). You need to upgrade the working copy first.

** System Configuration
Install prefix: /usr/local
Source path: gpac
C compiler: gcc
C++ compiler: g++
make: make
CPU: x86_64
Big Endian: no

GPAC 0.5.1-DEV rev Core Configuration
debug version: yes
GProf enabled: no
Static build enabled: no
Memory tracking enabled: no
Use standard memory allocator: no
Fixed-Point Version: no
IPV6 Support: yes
Static Modules: no

Detected libraries
zlib: system
OSS Audio: yes
ALSA Audio: yes
Jack Audio: no
PulseAudio Audio: no
DirectFB support: no
X11 Shared Memory support: yes (path: /usr/X11R6)
X11 XVideo support: no
SDL Support: no
OpenGL support: yes
TinyGL support: no
OpenSSL support: yes
Mozilla XUL/GECKO support: no
DVB Support: yes
XMLRPC Support: no
wxWidgets support: no

Extra Libraries used
SpiderMonkey: local
FreeType: system
JPEG: system
OpenJPEG: system
PNG: system
MAD: system
FAAD: no
XVID: no
FFMPEG: no
Xiph OGG: system
Platinum UPnP: no
AVCap: no
Xiph Vorbis: system
Xiph Theora: no
A52 (AC3): no
OpenSVCDecoder: no
OpenHEVCDecoder: no
MMT: yes
Freenect: no

Creating config.mak
Done - type 'make help' for make info, 'make' to build

make:
CC mcrypt/ctr.c
CC mcrypt/des.c
CC mcrypt/ecb.c
CC mcrypt/g_crypt.c
CC mcrypt/ncfb.c
CC mcrypt/nofb.c
CC mcrypt/ofb.c
CC mcrypt/rijndael-128.c
CC mcrypt/rijndael-192.c
CC mcrypt/rijndael-256.c
CC mcrypt/stream.c
CC mcrypt/tripledes.c
OBJS utils/os_divers.o utils/list.o utils/bitstream.o utils/error.o utils/alloc.o utils/url.o utils/configfile.o utils/sha1.o utils/base_encoding.o utils/os_net.o utils/os_thread.o utils/os_config_init.o utils/cache.o utils/downloader.o utils/xml_parser.o utils/utf.o utils/token.o utils/color.o utils/os_module.o utils/math.o utils/path2d.o utils/path2d_stroker.o utils/module.o utils/uni_bidi.o utils/ringbuffer.o utils/unicode.o utils/map.o mcrypt/cbc.o mcrypt/cfb.o mcrypt/ctr.o mcrypt/des.o mcrypt/ecb.o mcrypt/g_crypt.o mcrypt/ncfb.o mcrypt/nofb.o mcrypt/ofb.o mcrypt/rijndael-128.o mcrypt/rijndael-192.o mcrypt/rijndael-256.o mcrypt/stream.o mcrypt/tripledes.o scenegraph/base_scenegraph.o scenegraph/mpeg4_animators.o scenegraph/commands.o scenegraph/mpeg4_nodes.o scenegraph/mpeg4_valuator.o scenegraph/vrml_interpolators.o scenegraph/vrml_proto.o scenegraph/vrml_route.o scenegraph/vrml_script.o scenegraph/vrml_smjs.o scenegraph/vrml_tools.o scenegraph/x3d_nodes.o scenegraph/svg_attributes.o scenegraph/svg_types.o scenegraph/svg_smjs.o scenegraph/smil_anim.o scenegraph/smil_timing.o scenegraph/svg_properties.o scenegraph/dom_events.o scenegraph/dom_smjs.o scenegraph/xbl_process.o scenegraph/xml_ns.o scenegraph/html5_media_smjs.o scenegraph/html5_mse_smjs.o scenegraph/webvtt_smjs.o ietf/rtcp.o ietf/rtp.o ietf/rtp_packetizer.o ietf/rtp_pck_3gpp.o ietf/rtp_pck_mpeg12.o ietf/rtp_pck_mpeg4.o ietf/rtsp_command.o ietf/rtsp_common.o ietf/rtsp_response.o ietf/rtsp_session.o ietf/sdp.o ietf/rtp_depacketizer.o ietf/rtp_streamer.o bifs/arith_decoder.o bifs/bifs_codec.o bifs/bifs_node_tables.o bifs/com_dec.o bifs/com_enc.o bifs/conditional.o bifs/field_decode.o bifs/field_encode.o bifs/memory_decoder.o bifs/predictive_mffield.o bifs/quantize.o bifs/script_dec.o bifs/script_enc.o bifs/unquantize.o isomedia/avc_ext.o isomedia/box_code_3gpp.o isomedia/box_code_apple.o isomedia/box_code_mmt.o isomedia/box_code_base.o isomedia/box_code_drm.o isomedia/box_code_meta.o isomedia/box_dump.o isomedia/box_funcs.o isomedia/data_map.o isomedia/drm_sample.o isomedia/isom_intern.o isomedia/isom_read.o isomedia/isom_store.o isomedia/isom_write.o isomedia/media.o isomedia/media_odf.o isomedia/meta.o isomedia/movie_fragments.o isomedia/sample_descs.o isomedia/stbl_read.o isomedia/stbl_write.o isomedia/track.o isomedia/tx3g.o isomedia/hint_track.o isomedia/hinting.o isomedia/box_code_adobe.o isomedia/ttml.o odf/desc_private.o odf/descriptors.o odf/odf_code.o odf/odf_codec.o odf/odf_command.o odf/qos.o odf/slc.o odf/ipmpx_code.o odf/oci_codec.o odf/ipmpx_dump.o odf/ipmpx_parse.o odf/odf_dump.o odf/odf_parse.o media_tools/isom_tools.o media_tools/dash_segmenter.o media_tools/av_parsers.o media_tools/img.o media_tools/media_import.o media_tools/mpegts.o media_tools/m3u8.o media_tools/mpd.o media_tools/dash_client.o media_tools/media_export.o media_tools/m2ts_mux.o media_tools/filestreamer.o media_tools/avilib.o media_tools/mpeg2_ps.o media_tools/gpac_ogg.o media_tools/ismacryp.o media_tools/isom_hinter.o media_tools/saf.o media_tools/vobsub.o media_tools/text_import.o media_tools/html5_media.o media_tools/html5_mse.o media_tools/webvtt.o scene_manager/scene_manager.o scene_manager/text_to_bifs.o scene_manager/loader_bt.o scene_manager/loader_xmt.o scene_manager/loader_isom.o scene_manager/loader_qt.o scene_manager/loader_svg.o scene_manager/swf_parse.o scene_manager/swf_bifs.o scene_manager/swf_svg.o scene_manager/scene_dump.o scene_manager/scene_stats.o scene_manager/scene_engine.o scene_manager/encode_isom.o terminal/channel.o terminal/clock.o terminal/decoder.o terminal/term_node_init.o terminal/input_sensor.o terminal/media_control.o terminal/media_manager.o terminal/media_memory.o terminal/media_object.o terminal/media_sensor.o terminal/mpeg4_inline.o terminal/network_service.o terminal/object_browser.o terminal/object_manager.o terminal/scene.o terminal/terminal.o terminal/svg_external.o compositor/audio_input.o compositor/audio_mixer.o compositor/audio_render.o compositor/bindable.o compositor/camera.o compositor/compositor.o compositor/compositor_2d.o compositor/compositor_3d.o compositor/compositor_node_init.o compositor/drawable.o compositor/events.o compositor/font_engine.o compositor/hc_flash_shape.o compositor/hardcoded_protos.o compositor/mesh.o compositor/mesh_collide.o compositor/mesh_tesselate.o compositor/mpeg4_animstream.o compositor/mpeg4_audio.o compositor/mpeg4_background.o compositor/mpeg4_background2d.o compositor/mpeg4_bitmap.o compositor/mpeg4_composite.o compositor/mpeg4_form.o compositor/mpeg4_geometry_2d.o compositor/mpeg4_geometry_3d.o compositor/mpeg4_geometry_ifs2d.o compositor/mpeg4_geometry_ils2d.o compositor/mpeg4_gradients.o compositor/mpeg4_grouping.o compositor/mpeg4_grouping_2d.o compositor/mpeg4_grouping_3d.o compositor/mpeg4_layer_2d.o compositor/mpeg4_layer_3d.o compositor/mpeg4_layout.o compositor/mpeg4_lighting.o compositor/mpeg4_path_layout.o compositor/mpeg4_sensors.o compositor/mpeg4_sound.o compositor/mpeg4_text.o compositor/mpeg4_textures.o compositor/mpeg4_timesensor.o compositor/mpeg4_viewport.o compositor/navigate.o compositor/offscreen_cache.o compositor/svg_base.o compositor/svg_filters.o compositor/svg_font.o compositor/svg_geometry.o compositor/svg_grouping.o compositor/svg_media.o compositor/svg_paint_servers.o compositor/svg_text.o compositor/texturing.o compositor/texturing_gl.o compositor/visual_manager.o compositor/visual_manager_2d.o compositor/visual_manager_2d_draw.o compositor/visual_manager_3d.o compositor/visual_manager_3d_gl.o compositor/x3d_geometry.o laser/lsr_enc.o laser/lsr_dec.o laser/lsr_tables.o
LIBS -lm -L/usr/local/lib -lGL -lGLU -lX11 -L../extra_lib/lib/gcc -lz -lssl -lcrypto -ljs -ljpeg -lpng -lpthread -ldl
scenegraph/vrml_smjs.o: In function gf_js_add_root': gpac/src/scenegraph/vrml_smjs.c:60: undefined reference toJS_AddRoot'
scenegraph/vrml_smjs.o: In function gf_js_add_named_root': gpac/src/scenegraph/vrml_smjs.c:83: undefined reference toJS_AddNamedRoot'
scenegraph/vrml_smjs.o: In function gf_js_remove_root': gpac/src/scenegraph/vrml_smjs.c:244: undefined reference toJS_RemoveRoot'
scenegraph/vrml_smjs.o: In function JSPrint': gpac/src/scenegraph/vrml_smjs.c:588: undefined reference toJS_GetStringBytes'
scenegraph/vrml_smjs.o: In function getCurrentSpeed': gpac/src/scenegraph/vrml_smjs.c:616: undefined reference toJS_NewDouble'
scenegraph/vrml_smjs.o: In function getCurrentFrameRate': gpac/src/scenegraph/vrml_smjs.c:625: undefined reference toJS_NewDouble'
scenegraph/vrml_smjs.o: In function loadScript': gpac/src/scenegraph/vrml_smjs.c:709: undefined reference toJS_GetStringBytes'
scenegraph/vrml_smjs.o: In function getElementById': gpac/src/scenegraph/vrml_smjs.c:771: undefined reference toJS_GetStringBytes'
scenegraph/vrml_smjs.o: In function addRoute': gpac/src/scenegraph/vrml_smjs.c:873: undefined reference toJS_GetStringBytes'
gpac/src/scenegraph/vrml_smjs.c:896: undefined reference to JS_GetStringBytes' gpac/src/scenegraph/vrml_smjs.c:929: undefined reference toJS_GetFunctionName'
scenegraph/vrml_smjs.o: In function deleteRoute': gpac/src/scenegraph/vrml_smjs.c:993: undefined reference toJS_GetStringBytes'
gpac/src/scenegraph/vrml_smjs.c:1017: undefined reference to JS_GetStringBytes' gpac/src/scenegraph/vrml_smjs.c:1018: undefined reference toJS_GetStringBytes'
scenegraph/vrml_smjs.o: In function loadURL': gpac/src/scenegraph/vrml_smjs.c:1071: undefined reference toJS_GetStringBytes'
gpac/src/scenegraph/vrml_smjs.c:1091: undefined reference to JS_GetStringBytes' scenegraph/vrml_smjs.o:gpac/src/scenegraph/vrml_smjs.c:1108: more undefined references toJS_GetStringBytes' follow
scenegraph/vrml_smjs.o: In function node_getProperty': gpac/src/scenegraph/vrml_smjs.c:1625: undefined reference toJS_NewDouble'
gpac/src/scenegraph/vrml_smjs.c:1626: undefined reference to JS_NewDouble' gpac/src/scenegraph/vrml_smjs.c:1627: undefined reference toJS_NewDouble'
gpac/src/scenegraph/vrml_smjs.c:1628: undefined reference to JS_NewDouble' scenegraph/vrml_smjs.o: In functionnode_setProperty':
gpac/src/scenegraph/vrml_smjs.c:1663: undefined reference to JS_GetStringBytes' scenegraph/vrml_smjs.o: In functionnode_getTime':
gpac/src/scenegraph/vrml_smjs.c:1739: undefined reference to JS_NewDouble' scenegraph/vrml_smjs.o: In functionvec2f_getProperty':
gpac/src/scenegraph/vrml_smjs.c:1928: undefined reference to JS_NewDouble' gpac/src/scenegraph/vrml_smjs.c:1931: undefined reference toJS_NewDouble'
scenegraph/vrml_smjs.o: In function vec2f_length': gpac/src/scenegraph/vrml_smjs.c:2065: undefined reference toJS_NewDouble'
scenegraph/vrml_smjs.o: In function vec2f_dot': gpac/src/scenegraph/vrml_smjs.c:2091: undefined reference toJS_NewDouble'
scenegraph/vrml_smjs.o:gpac/src/scenegraph/vrml_smjs.c:2128: more undefined references to JS_NewDouble' follow scenegraph/vrml_smjs.o: In functionarray_setElement':
gpac/src/scenegraph/vrml_smjs.c:2973: undefined reference to JS_GetStringBytes' gpac/src/scenegraph/vrml_smjs.c:2984: undefined reference toJS_GetStringBytes'
scenegraph/vrml_smjs.o: In function `array_setLength':
collect2: error: ld returned 1 exit status
Makefile:607: recipe for target '../bin/gcc/libgpac.so' failed
make[1]: * [../bin/gcc/libgpac.so] Error 1
make[1]: Leaving directory 'gpac/src'
Makefile:9: recipe for target 'all' failed
make: * [all] Error 2

**Comment by rbouqueau** [comment]
You are not using the lastest GPAC from github, correct?

**Comment by jeanlf** [comment]
did you compile JS 185 yourself ? we're using mozjs-185 on debian without any issue ...

**Comment by Aumontf** [comment]
I'm using the last version of GPAC.

**Comment by Aumontf** [comment]
Perharps I did someting wrong but I have built mozjs-185 myself to be aligned with the JS API that GPAC needs and i have this error when linking.

**Comment by Aumontf** [comment]
I got the RPM for mozjs185 and perhaps i not get the good one. Have you got a link you have already tested?

**Comment by Aumontf** [comment]
the uname -a of my working station is 3.17.4-301-fa21-x86_64

**Comment by jeanlf** [comment]
can you post your config.mak ? It seems like a wrong version of JS is detected (local headers are found instead of global ones).  You may want to change the JS include and link options in the config.mak to see if that is the issue

**Comment by jeanlf** [comment]
OK now fixed on git, thanks for the report.
