### ISSUE TITLE
How to use the filter ffavf of ffmpeg through mp4box?

### ISSUE THREAD

**Issue by DY-TL** [gpac/gpac#2591]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I would like to express my sincere gratitude for providing us with the exceptional open-source software, GPAC. Currently, I am utilizing MP4Box for image encapsulation.
Here are the steps I follow to process the images:

1. First, I use ffmpeg to pad the images to m512 x n512 dimensions. The command is as follows:

`ffmpeg  -i input.png -vf "pad=4096:3072:220:240"  pad.png`

2.Next, I utilize the kvazaar encoder to encode the resized images into HEVC bitstreams with a tile size of 512x512. Additionally, I encapsulate the bitstreams into HEIF format images. The command I am using is:

`MP4Box -add-image pad.png:@enc:c=libkvazaar::kvazaar-params=tiles=8x6,slices=tiles,mv-constraint=frametilemargin:@tilesplit -new pad.heic`

I have encountered a few issues during this process and would greatly appreciate your assistance. My first question is regarding the usage of MP4Box to execute ffmpeg commands, so that I can accomplish the image padding, transcoding, and HEIF encapsulation steps with a single MP4Box command, like follows:
       ` MP4Box -add-image input.png:@ffavf:f=pad=w=4096=h=3072:@enc:c=libkvazaar::kvazaar-params=tiles=8x6,slices=tiles,mv-constraint=frametilemargin:@tilesplit -new pad.heic
`
I tried the command mentioned above, but I didn't get any output.
![163977FC-6DA5-4976-B4CD-3CB2F335CC37_4_5005_c](https://github.com/gpac/gpac/assets/73345901/84804027-7b71-45ba-92f5-e6bbcf10c291)

![53CA546E-8753-43A5-9A40-7F86C4CDA018_4_5005_c](https://github.com/gpac/gpac/assets/73345901/c2e6b07f-120a-4a33-b334-c8131aadb73c)

**Comment by jeanlf** [comment]
There's a typo in the description of the ffavf ('=' instead of ':' for arg separator) filter and it should be escaped (double colon):

```
MP4Box -add-image input.png:@ffavf::f=pad=w=4096:h=3072::@enc:c=libkvazaar::kvazaar-params=tiles=8x6,slices=tiles,mv-constraint=frametilemargin:@tilesplit -new pad.heic
```

There was also a bug due to format reconfiguration when source was jpg or png, now fixed on master. Thanks for the report !
