### ISSUE TITLE
mp4box out of memory when convert normal mp4 to fmp4  

### ISSUE THREAD

**Issue by fastfading** [gpac/gpac#2593]
latest build   
MP4Box - GPAC version 2.3-DEV-rev531-g61f1cf39e-master
and   
MP4Box - GPAC version 2.3-DEV-rev314-gedc6d8aa9-master
all have this issue 

my command is 
mp4box -dash 30000 -profile onDemand big.mp4 -out dash.mpd --dual

big.mp4   is  18GB
my system memory is :
free -h
                    total        used        free      shared  buff/cache   available
Mem:            15G        2.1G         12G        5.3M        506M         13G
Swap:          3.0G        2.6G        400M

[11768127.914421] Out of memory: Kill process 16249 (mp4box) score 694 or sacrifice child 
[11768127.914794] Killed process 16249 (mp4box), UID 0, total-vm:13886608kB, anon-rss:13692940kB, file-rss:4kB, shmem-rss:0kB

only 5.5GB data has been converted
-rw-------. 1 root    root     18G Sep 11 06:17 big.mp4
-rw-------. 1 root    root    5.5G Sep 11 08:17 big_dashinit.mp4

is there a memory leak in this case ?
we can not provide you the big.mp4 since it is customer data

**Comment by fastfading** [comment]
similar issues  https://github.com/gpac/gpac/issues/2214

**Comment by fastfading** [comment]
[270128907601098408_info.xml.xz.zip](https://github.com/gpac/gpac/files/12583797/270128907601098408_info.xml.xz.zip)
this is the mp4box -diso big.mp4    dump
unzip 270128907601098408_info.xml.xz.zip
unxz 270128907601098408_info.xml.xz

**Comment by rbouqueau** [comment]
The media seem interleaved. Any idea?

**Comment by jeanlf** [comment]
could you upload a truncated file containing ftyp+moov only ? For your dumped file this means the first 75069184 bytes

**Comment by fastfading** [comment]
> could you upload a truncated file containing ftyp+moov only ? For your dumped file this means the first 75069184 bytes

SURE,  but how to get such file ？ 
could you send me the command line ?

**Comment by jeanlf** [comment]
On linux/osx something like 
```
truncate -s 75069184 file.mp4
```

**Comment by jeanlf** [comment]
also do `MP4Box -info` or `MP4Box -diso ` on the result to check it

**Comment by fastfading** [comment]
MP4Box -info big.mp4

# Movie Info - 2 tracks - TimeScale 1000
Duration 21:23:21.760
Fragmented: no
Progressive (moov before mdat)
Major Brand isom - version 512 - compatible brands: isom iso2 avc1 mp41
Created: UNKNOWN DATE

Meta-Data Tags:
	tool: Lavf59.16.100

# Track 1 Info - ID 1 - TimeScale 12800
Media Duration 21:23:21.680  (recomputed 21:23:21.720)
Track has 2 edits: track duration is 21:23:21.760
Track flags: Enabled In Movie
Media Samples: 1925042 - CFR 25/sec
Visual Track layout: x=0 y=0 width=1920 height=1080
Media Type: vide:avc1
	Visual Sample Entry Info: width=1920 height=1080 (depth=24 bits)
	AVC/H264 Video - Visual Size 1920 x 1080
	AVC Info: 1 SPS - 1 PPS - Profile High @ Level 4
	NAL Unit length bits: 32
	Pixel Aspect Ratio 1:1 - Indicated track size 1920 x 1080
	Chroma format YUV 4:2:0 - Luma bit depth 8 - chroma bit depth 8
	SPS#1 hash: C14339F4F5E5A6F963244886D2C89933922B2FD1
	PPS#1 hash: A3EE4CDCBCFE65012A7D3860B430E3AC70377532
	RFC6381 Codec Parameters: avc1.640028
	Average GOP length: 746 samples
	Max sample duration: 512 / 12800

# Track 2 Info - ID 2 - TimeScale 32000
Media Duration 21:23:21.604
Track has 2 edits: track duration is 21:23:21.652
Track flags: Enabled In Movie
Media Samples: 2406301
Alternate Group ID 1
Media Type: soun:mp4a
	MPEG-4 Audio AAC LC (AOT=2 implicit) - 1 Channel(s) - SampleRate 32000
	RFC6381 Codec Parameters: mp4a.40.2
	All samples are sync
	Max sample duration: 1024 / 32000

**Comment by fastfading** [comment]
truncate -s 75069184 big.mp4
MP4Box -diso big.mp4
result is using xz  and then  zip  to compress
[big_info.xml.xz.zip](https://github.com/gpac/gpac/files/12734821/big_info.xml.xz.zip)

**Comment by jeanlf** [comment]
Thanks for the file - this should now be fixed on master, could you cross-check ?

**Comment by fastfading** [comment]
@jeanlf   yes ,the memory issue has been fixed .  thanks a lot
