### ISSUE TITLE
Question regarding file size reduction and bitrate reduction when muxing video and audio using MP4Box

### ISSUE THREAD

**Issue by xanadu6291** [gpac/gpac#2597]
Question regarding file size reduction and bitrate reduction when muxing video and audio using MP4Box

I have got some jerky motion video only when play with QuickTime Player.  They can be fixed by demuxing and re-muxing using MP4Box.
Today, I got one video both file size and bitrate are reduced even though just demuxing and re-muxing using MP4Box. (File size was reduced to about 68% of original video, Bitrate was reduced to about 67% of original video)
After processing, I mean demuxing and re-muxing, the video seems to play without any problem.  I feel suspition about file size and bitrate are reduced such a big amount without re-encoding. Could you explain me such a thing is possible or not?

MP4Box Version:
MP4Box - GPAC version 2.3-DEV-rev537-gc9cad7b7d-master

Command to demux:
% MP4Box -raw 1 input.mp4 
Exporting MPEG-4 AVC|H264 Video - Size 1920x1080
% MP4Box -raw 2 input.mp4
Exporting MPEG-4 AAC Audio - SampleRate 48000 2 channels 16 bits per sample

Command to re-mux:
% MP4Box -add input_track1.264 -add input_track2.aac -new output.mp4
Track Importing MPEG-4 AVC - Width 1920 Height 1080 FPS 40000000/1334668 SAR 8001/8000
AVC|H264 Import results: 130118 samples (462919 NALUs) - Slices: 2808 I 35050 P 92261 B - 132926 SEI - 2807 IDR - 0 CRA
AVC|H264 Stream uses forward prediction - stream CTS offset: 3 frames
AVC|H264 Max NALU size is 62328 - stream could be optimized by setting nal_length=2
Track Importing AAC  - SampleRate 24000 Num Channels 2

File size for input/output:
% ls -l input* output*
-rw-r--r--@ 1 roushi  staff  1862113648  9 18 16:50 input.mp4
-rw-r--r--  1 roushi  staff  1822261637  9 18 21:28 input_track1.264
-rw-r--r--  1 roushi  staff    38909579  9 18 21:28 input_track2.aac
-rw-r--r--  1 roushi  staff  1265112993  9 18 21:31 output.mp4

Bitrate for input/output:
% mp4info input.mp4 
mp4info version 2.0.0
input.mp4:
Track	Type	Info
1	video	H264 High@4, 4341.608 secs, 3356 kbps, 1920x1080 @ 29.970002 fps
2	audio	MPEG-4 AAC LC, 4341.717 secs, 70 kbps, 48000 Hz
3	text
 Encoded with: Lavf58.20.100
 
 % mp4info output.mp4 
mp4info version 2.0.0
output.mp4:
Track	Type	Info
1	video	H264 High@4, 4341.675 secs, 2257 kbps, 1920x1080 @ 29.969539 fps
2	audio	MPEG-4 AAC LC, 4341.717 secs, 70 kbps, 24000 Hz
 Encoded with: GPAC-2.3-DEV-rev537-gc9cad7b7d-master

**Comment by rbouqueau** [comment]
If this is TV content, this could be explained by the removal of filler data. A third of the content size still seems a lot though.

Do you know what's the source of this content?

**Comment by xanadu6291** [comment]
I'm wondering that the console output "AVC|H264 Max NALU size is 62328 - stream could be optimized by setting nal_length=2" when re-muxing is related with the reduction of file size and reduction of bitrate. Since I don't see such a message with another video source...

**Comment by jeanlf** [comment]
try comparing `MP4Box -info 1 input.mp4` and `MP4Box -info 1 output.mp4` to cross-check that this is indeed due to filler data being removed. 

You can also dump some samples (`MP4Box -raws 1:N input.mp4` with N the sample number) and check with an hex editor if you have a bunch of 0 at the end.
 

> I'm wondering that the console output "AVC|H264 Max NALU size is 62328 - stream could be optimized by setting nal_length=2" when re-muxing is related with the reduction of file size

No, the flag is never set automatically by MP4Box, hence the message to suggest adding it.
