### ISSUE TITLE
[DASH] AdaptationSet@lang (audio) is missing while using DASH-AVC/264 profiles.

### ISSUE THREAD

**Issue by vladimir-kazakov** [gpac/gpac#26]
Hi!

While using MP4Box (GPAC rev 5572), I noticed that the AdaptationSet@lang attribute for audio streams is missing when the DASH-AVC/264 profiles are used, and a language of an audio stream is undefined. But, according to DASH-AVC/264 Interoperability Points v2.0, this attribute is mandatory - "For any Adaptation Sets with value of the @contentType="audio" the following attributes shall be present: @lang".

Test media can be found here: http://1drv.ms/1AxRlrg

There are 2 audio streams:
1) audio-240k.m4a - doesn't have the language "tag", so "mp4box.exe -info" reports "Media Info: Language "und (und)"".
2) audio-240k-en-US.m4a - has the language "tag" (en-US) (Media Info: Language "English (en-US)") (I used "mp4box.exe -lang en-US audio-240k-en-US.m4a" in order to set it).

So, if the language is not set (the "und" case), then AdaptationSet@lang is missing. But this is wrong - this attribute must always present, and its value, in the "und" case, must be set to "und", according to 4.1 (5) of the BCP-47 (http://www.rfc-editor.org/rfc/bcp/bcp47.txt).

**Comment by jeanlf** [comment]
Indeed now fixed on SVN rev 5582, thanks for the report
