### ISSUE TITLE
MP4Box META -add-xml towards END of File

### ISSUE THREAD

**Issue by jotzet79** [gpac/gpac#2603]
Hello gpac community,

In my workflow I need the META XML to be at the very beginning or very end of the MP4 container. Is there a way to influence this behaviour?

Thank you,
Joachim

**Comment by jeanlf** [comment]
No, and this is not on our todo:
- the xml set using `-set-xml` is contained within the meta box using an `xml `box, and cannot be at the end of the file (we always store meta before moov and mdat).

- the payload of items described in meta boxes are also written in mdat before the media sample.
