### ISSUE TITLE
DashCast transcode a live stream in multiple qualities on windows7 64bit，and played these stream in the DASH.js.

### ISSUE THREAD

**Issue by JamesXu20150314** [gpac/gpac#262]
Hello,

Who can give me a guideline about the title.

Because the segments that pruduct by Dashcast with the -live options, can not played by the dash.js player.
Thanks so much.

JamesXu

**Comment by rbouqueau** [comment]
Duplicate of #216 and/or #251. Please don't double post.

**Comment by adetheprince** [comment]
DashCast: command not found

**Comment by jeanlf** [comment]
which platform are you using? which version of the installer?

**Comment by adetheprince** [comment]
Hi there
I am using Ubuntu Server 14.04.3 LTS 

I also try to use the tutorial but lots of error and directory missing...
