### ISSUE TITLE
"par" attribute value calculation does not consider sample aspect ratio

### ISSUE THREAD

**Issue by sandersaares** [gpac/gpac#263]
I have multiple representations, not all with the same sample aspect ratio but all with display aspect ratio 16:9 (as verified by FFmpeg). I would thus expect that the `AdaptationSet@par` attribute generated by mp4box be `16:9`, since according to the DASH specification, it should take into account the sample aspect ratio.

However, the reality is that the value of this attribute is the picture aspect ratio from the last representation, without taking the sample aspect ratio into account.

FFmpeg output for this stream, showing example sar/par and picture size:

        Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv), 852x480 [SAR 640:639 DAR 16:9], 1157 kb/s, 23.98 fps, 23.98 tbr, 2997 tbn, 47.95 tbc (default)

Manifest contents:

	<AdaptationSet segmentAlignment="true" maxWidth="852" maxHeight="480" maxFrameRate="2997/125" par="852:480" lang="und">
		<Representation id="1" mimeType="video/mp4" codecs="avc1.640015" width="512" height="288" frameRate="2997/125" sar="1:1" startWithSAP="1" bandwidth="391676">
			<SegmentTemplate timescale="2997" media="Unbroken_Mismatching_Aspect_and_Resolution-288-400k_dash$Number$.m4s" startNumber="1" duration="11748" initialization="Unbroken_Mismatching_Aspect_and_Resolution-288-400k_dashinit.mp4" />
		</Representation>
		<Representation id="2" mimeType="video/mp4" codecs="avc1.64001e" width="640" height="360" frameRate="2997/125" sar="1:1" startWithSAP="1" bandwidth="775040">
			<SegmentTemplate timescale="2997" media="Unbroken_Mismatching_Aspect_and_Resolution-360-800k_dash$Number$.m4s" startNumber="1" duration="11748" initialization="Unbroken_Mismatching_Aspect_and_Resolution-360-800k_dashinit.mp4" />
		</Representation>
		<Representation id="3" mimeType="video/mp4" codecs="avc1.64001e" width="852" height="480" frameRate="2997/125" sar="640:639" startWithSAP="1" bandwidth="1159419">
			<SegmentTemplate timescale="2997" media="Unbroken_Mismatching_Aspect_and_Resolution-480-1200k_dash$Number$.m4s" startNumber="1" duration="11748" initialization="Unbroken_Mismatching_Aspect_and_Resolution-480-1200k_dashinit.mp4" />
		</Representation>
	</AdaptationSet>

Tested with mp4box rev550.

**Comment by rbouqueau** [comment]
DASH second edition, 5.3.3.2 Table-5:

``` @par ```

> When this attribute is present, and the attributes @width and @height for the set of Representations are also present, the picture aspect ratio as specified by this attribute shall be the same as indicated by the values of @width, @height, and @sar, i.e. it shall express the same ratio as (@width * sarx): (@height * sary), with sarx the first number in @sar and sary the second number.

So it is not the picture AR per-se. It seems consistent with the values in the manifest. What do you think?

**Comment by sandersaares** [comment]
I agree - `@par` is not in fact the picture aspect ratio but what most other things call the display aspect ratio. The naming used in DASH is quite confusing, indeed.

**Comment by sandersaares** [comment]
Wait, why did this get closed? The problem still exists. Please do not interpret my "I agree" as me saying there is no problem - I agree with your analysis of what the problem is.

**Comment by rbouqueau** [comment]
I think I don't get your issue. MP4Box seems to follow the spec, and your three representations are in the same AdaptationSet. Could you give me a pointer on what seems wrong?

**Comment by sandersaares** [comment]
Sure, I am happy to explain further.

The spec says that `@par` components must be calculated by `value*sar`. The issue is that the second factor in this calculation is missing - there is no multiplication with the SAR.

Let's take the specific manifest I listed and manually go through the steps needed to calculate the `@par` value.

Representation 1 and 2 have picture dimensions with 16:9 ratio and a SAR of 1:1 so, obviously, 16:9 is the expected result.

Representation 3 has picture dimensions with a different aspect ratio, 852:480 and a SAR of 640:639. The `@par` value for this would be: (852 * 640):(480 * 639) == 545280:306720 == 16:9.

Thus the correct `@par` value to use is 16:9. However, mp4box simply takes the width/height of the last representation, ignoring the SAR.

The DASH specification is confusing in this matter because normally what it calls `par` here is called `dar` elsewhere - picture aspect ratio is that of the original picture; after multiplying with SAR you get the DRAW (display aspect ratio). The DASH attribute should really be called `dar`, in my opinion. I imagine this is what caused the current implementation to be incorrect.

**Comment by rbouqueau** [comment]
Ok I get it. Would you be kind enough to drop me the files with the issue number at: 
https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Thank you.

**Comment by sandersaares** [comment]
It is done - I have uploaded the 3 video streams I used as input.

**Comment by jeanlf** [comment]
Indeed the PAR writing only uses max_width/max_height ( dash_segmenter.c line 4683), we need to pass the corresponding sar to fix this. We'll do this asap

**Comment by jeanlf** [comment]
This should now be fixed, thanks for the report
