### ISSUE TITLE
combining multiple small video files (iphone live photo clips) into one file - horizontal and vertical files

### ISSUE THREAD

**Issue by Vaim1** [gpac/gpac#2630]
Is there a way to command line combine multiple video files into one while keeping the file actually playable and adding black bars to vertical clips?

This functionality kind of works when using MP4Joiner, but it is fairly slow to add files and it crashes very often when trying to combine 100+ files or some files that are broken for whatever playback reason.
The output is also often choppy and video files become garbled at points and playback is not possible. (MPC HC but eventually planning to upload to youtube unlisted)
However the addition of black bars is excellent and from my task manager i can see many files are being re-encoded with ffmpeg while the process is going on.

When using MP4Box, the videos combine, but playback is not possible a lot of the time and vertical clips are streched to fit the first horizontal size.
My command is this - i've tried some variations and removal of bs-switching as well.

`$command = '"C:\Program Files (x86)\MP4Tools\bin\MP4Box" -bs-switching merge -force-cat' ; (Get-ChildItem *.mp4 | sort { [regex]::Replace($_.Name, '\d+', { $args[0].Value.PadLeft(20) }) } )  | foreach { $command += " -cat $_" } ; $command += " combined.mp4" ;$command ; cmd /c $command`
(i have also tried the newest GPAC mp4box.exe files)

With this i get a full list of mp4's and they are all -cat'ed into the command.

Here are some sample files and the mp4 that is created when i combine with the mp4box command.
https://www.dropbox.com/scl/fo/auvvmk03oeoq2k7w175qv/h?rlkey=387jb5ccu9b6vvdv3k55qd1c9&dl=0

In these test files the mp4joiner file is also quite broken after combining. But the mp4box combined file handles vertical even worse.

How could i re-encode these to make the files actually play? I cant find a way right now, but it would be awesome to be able to combine my live photo clips to a movie.

**Comment by aureliendavid** [comment]
Hi, 

I don't know if rencoding is an option for you but it's probably your best bet, as raw concatenation can often lead to playback issues (but I'll let others suggest a concat solution if there is one). 

In case you're open to rencoding, you should probably install a full version of gpac (https://download.tsi.telecom-paristech.fr/gpac/new_builds/gpac_latest_head_win64.exe) and checkout gpac's [playlist](https://github.com/gpac/gpac/wiki/playlist) feature and [encoding](https://github.com/gpac/gpac/wiki/encoding) principles.

For example with your sample files, I had good results with something like: 

```
gpac -r -stats flist:srcs=./2630/*.mp4  ffsws:osize=1440x1080:keepar=full:ofr=true ffenc:c=avc:fintra=1 -o combined.mp4 
```

hope this helps

**Comment by Vaim1** [comment]
> Hi,
> 
> I don't know if rencoding is an option for you but it's probably your best bet, as raw concatenation can often lead to playback issues (but I'll let others suggest a concat solution if there is one).
> 
> In case you're open to rencoding, you should probably install a full version of gpac (https://download.tsi.telecom-paristech.fr/gpac/new_builds/gpac_latest_head_win64.exe) and checkout gpac's [playlist](https://github.com/gpac/gpac/wiki/playlist) feature and [encoding](https://github.com/gpac/gpac/wiki/encoding) principles.
> 
> For example with your sample files, I had good results with something like:
> 
> ```
> gpac -r -stats flist:srcs=./2630/*.mp4  ffsws:osize=1440x1080:keepar=full:ofr=true ffenc:c=avc:fintra=1 -o combined.mp4 
> ```
> 
> hope this helps

Hey! This has actually worked really well in early testing.
Results seem very positive and this might actually be exactly what i was looking for! 

Thanks!



Now if only it could arrange input files by exif data created date :D
Using some fairly slow powershell module that converts all files one at a time.

**Comment by aureliendavid** [comment]
> Now if only it could arrange input files by exif data created date :D
> Using some fairly slow powershell module that converts all files one at a time.

The flist filter has a fsort parameter that can sort by name or file date. 

If you really need to sort by exif data my advice would be to write a small script (in python or whatever can read exif) that creates a properly sorted playlist that you can then use as input to gpac (gpac -i playlist.txt).
