### ISSUE TITLE
mp4box crashes during dashing

### ISSUE THREAD

**Issue by sandersaares** [gpac/gpac#264]
The crashes are not 100% reproducible even with the same data set - sometimes it actually finishes execution successfully. Most times, the Windows crash dialog pops up. Visual Studio informs me that the error is:

    Unhandled exception at 0x00007FF88401A28C (ntdll.dll) in mp4box.exe: 0xC0000374: A heap has been corrupted (parameters: 0x00007FF884072180).

Command: `mp4box -dash-strict 4000 -out out\Manifest.mpd -profile "dashavc264:live" -sample-groups-traf -bs-switching no sintel.mp4 sintel-288-400k.mp4`

My input files: https://mega.nz/#!EkB2HBQQ!v489_PESs0ITPQAszNBZvtC0x6XTDVvRNV6661kO0d0

Tested with MP4Box - GPAC version 0.5.2-DEV-rev679-g0fd69e0-master.

**Comment by rbouqueau** [comment]
Fixed. Thanks for reporting :)
