### ISSUE TITLE
Can I play back video encrypted with MP4box using the HTML5 <video> tag?

### ISSUE THREAD

**Issue by crg1955** [gpac/gpac#265]
I hope this is the right place to ask about this.

I'm trying to play a video that I've CENC-encrypted using MP4box with these options:

    MP4Box -crypt drm_file_gpac_clear.xml BigBuckBunny.mp4 -out BigBuckBunny_cenc.mp4

Where the XML file specifies clearKey encryption. It's taken from GPAC's website https://gpac.wp.mines-telecom.fr/mp4box/encryption/common-encryption/

      <?xml version="1.0" encoding="UTF-8"?>
      <GPACDRM type="CENC AES-CTR">
      
      <DRMInfo type="pssh" version="1" cypherOffset="9" cypherKey="0x6770616363656E6364726D746F6F6C31" cypherIV="0x00000000000000000000000000000001">
      <BS ID128="0x6770616363656E6364726D746F6F6C31"/>
      <BS value="2" bits="32"/>
      <BS ID128="0x279926496a7f5d25da69f2b3b2799a7f"/>
      <BS ID128="0x676cb88f302d10227992649885984045"/>
      <BS bits="8" string="CID=Toto"/>
      <BS ID128="0xccc0f2b3b279926496a7f5d25da692f6"/>
      <BS ID128="0xccc0f2b3b279926496a7f5d25da692d6"/>
      </DRMInfo>
      <CrypTrack trackID="1" IsEncrypted="1" IV_size="16" first_IV="0x0a610676cb88f302d10ac8bc66e039ed" saiSavedBox="senc">
      <key KID="0x279926496a7f5d25da69f2b3b2799a7f" value="0xccc0f2b3b279926496a7f5d25da692f6"/>
      </CrypTrack>
      </GPACDRM>

To play this back, I have an HTML file which includes a video tag that specifies the encrypted file:

      <video  autoplay id="video1" controls src="BigBuckBunny_cenc.mp4" type="video/mp4"></video>

And some attached JS:

      var KEY = new Uint8Array([
        0xcc, 0xc0, 0xf2, 0xb3, 0xb2, 0x79, 0x92, 0x64,   // this is key for MP4 file
        0x96, 0xa7, 0xf5, 0xd2, 0x5d, 0xa6, 0x92, 0xf6    // encrypted with drm_file_gpac_clear.xml
      ]);

      var config = [
        {
          initDataType: "cenc",
          videoType: "video/mp4",
        }
      ];

      var video = document.getElementById('video1');
      video.addEventListener('encrypted', handleEncrypted, false);

My problem is that the 'encrypted' event isn't fired.

This plays fine if I put an unencrypted file in place of the encrypted one, and it also plays fine if I substitute a WEBM file (from http://simpl.info/eme/clearkey/ ) and change the key and config accordingly ("view page source" on that URL for the details). So it will play back an encrypted file (in this case the 'encrypted' event is fired, of course), but not one I've encrypted with MP4box.

Also, when I play back the encrypted file, the unencrypted audio track plays OK; but the video is blank.

I've tried it in IE 11.0.9600.18036, Firefox 41.0, Chrome 45.0.2454.93 m and Chrome 47.0.2516.0 canary (64-bit).

I had a look at the MP4 file with MP4 Explorer, and it has the boxes I've been told to expect, such as encv, sinf and schm.

I've only been trying to learn about CENC during the last few weeks so this is all comparatively new, and I may have made some obvious mistake. If anyone can help, I'd be grateful for any advice.

Thanks!

**Comment by rbouqueau** [comment]
I don't have time right now to make a detailed answer but it can work. You should be able to find examples from other people here on github or on our previous sourceforge tracker/forums.

What is wrong in your case is the encryption scheme: you are using a GPAC specific one, whereas you probably mean to use ClearKey or Widevine/Playready depending on the platform you are targetting.

**Comment by crg1955** [comment]
Thank you very much! I will look for a ClearKey equivalent of the file "drm_file_gpac_clear.xml" (I thought that was using ClearKey, I was fooled by the comment "example for GPAC 'clear' DRM System").

**Comment by crg1955** [comment]
I have a follow-up query. I have now created a drm_file which I think is correct for clearKey.

    <DRMInfo type="pssh" version="1" flags="0">
    <BS ID128="0x1077EFECC0B24D02ACE33C1E52E2FB4B"/>  
    
    
    <BS value="2" bits="32"/>
    <BS ID128="0x279926496a7f5d25da69f2b3b2799a7f"/>
    <BS ID128="0x676cb88f302d10227992649885984045"/>
    <BS bits="8" string="CID=Toto"/>
    <BS ID128="0xccc0f2b3b279926496a7f5d25da692f6"/>
    <BS ID128="0xccc0f2b3b279926496a7f5d25da692d6"/>
    <BS value="0" bits="32"/> 
    </DRMInfo>
    <CrypTrack trackID="1" IsEncrypted="1" IV_size="16" first_IV="0x0a610676cb88f302d10ac8bc66e039ed" saiSavedBox="senc">
    <key KID="0x279926496a7f5d25da69f2b3b2799a7f" value="0xccc0f2b3b279926496a7f5d25da692f6"/>
    </CrypTrack>
    </GPACDRM>

If I dump this I get what looks like the correct contents

    00082ab0  66 35 32 2e 31 34 2e 30  00 00 00 71 70 73 73 68  |f52.14.0...qpssh|
    00082ac0  01 00 00 00 10 77 ef ec  c0 b2 4d 02 ac e3 3c 1e  |.....w....M...<.|
    00082ad0  52 e2 fb 4b 00 00 00 02  27 99 26 49 6a 7f 5d 25  |R..K....'.&Ij.]%|
    00082ae0  da 69 f2 b3 b2 79 9a 7f  67 6c b8 8f 30 2d 10 22  |.i...y..gl..0-."|
    00082af0  79 92 64 98 85 98 40 45  00 00 00 2d 08 43 49 44  |y.d...@E...-.CID|
    00082b00  3d 54 6f 74 6f cc c0 f2  b3 b2 79 92 64 96 a7 f5  |=Toto.....y.d...|
    00082b10  d2 5d a6 92 f6 cc c0 f2  b3 b2 79 92 64 96 a7 f5  |.]........y.d...|
    00082b20  d2 5d a6 92 d6 00 00 00  00 03 d5 55 e5 6d 64 61  |.].........U.mda|

However it doesn't play back (I get the error message "Source not as expected")

I've tried various versions of the above, only have one KID for example. (And I have no idea what the "CID=Toto" field is for, so perhaps that's the problem, or part of it.)

Again, any help would be much appreciated.

**Comment by nguyen-viet-thanh-trung** [comment]
Hello,
The "CID=toto" is an example of private data for a DRM.

**Comment by crg1955** [comment]
Thank you. (So presumably it isn't relevant in my case! I'm probably putting too much information in.)

**Comment by crg1955** [comment]
I'ev tried a minimalist approach with just the clearKey systemID plus a "data" field that is supposed to be zero, and is inserted by MP4Box - but I still get the same error, "source not as expected" in all the browsers I mentioned before.

The inserted pssh box is visible here. There is a length field (32), an FCC "pssh", a version/flags field set to 0, the ID (I believe!), a daat field set to 0, then an "mdat" box. I have no idea why this is "not as expected" - the error message isn't very helpful! 

      00082ab0  66 35 32 2e 31 34 2e 30  00 00 00 20 70 73 73 68  |f52.14.0... pssh|
      00082ac0  00 00 00 00 10 77 ef ec  c0 b2 4d 02 ac e3 3c 1e  |.....w....M...<.|
      00082ad0  52 e2 fb 4b 00 00 00 00  03 d5 55 e5 6d 64 61 74  |R..K......U.mdat|
      00082ae0  00 00 00 d1 65 40 1a 22  0e 10 6f db a1 81 23 c4  |....e@."..o...#.|

I'm now well and truly struck. If anyone can help, thanks in advance :)

**Comment by crg1955** [comment]
I've tried this with the box set to version 1 as well, by the way. I get the same result when I try to play it, but oddly the MP4 file ends up as about 4Gb in size, rather than 64Mb!

**Comment by rbouqueau** [comment]
> I've tried this with the box set to version 1 as well, by the way. I get the same result when I try to play it, but oddly the MP4 file ends up as about 4Gb in size, rather than 64Mb!

Could you solve your issue? I'd be highly interested in a sample + command-line to reproduce this issue.

Anonymous dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by rbouqueau** [comment]
Let's follow this discussion at #239
