### ISSUE TITLE
Implementing a custom source using the nodejs API

### ISSUE THREAD

**Issue by nlsdvl** [gpac/gpac#2650]
Hi, sorry if I am missing something available from the documentation. 

I looked at gpac's nodejs doc, at the test/gpac.js, at several filter's source code and documentation, at the doxygen as well as the general filter documentation.  

I'm trying to write a custom source that feeds data into a filter session using the nodejs API.

I have been testing 2 options: 

###  1. using a custom filter

This is my preferred solution, however I keep failing at building a simple graph. 
Here's my code:
```
const process = require("process");
const GPAC_NODEJS = process.env["GPAC_NODEJS"] || "share/nodejs/build/Debug/gpac";
const gpac = require(GPAC_NODEJS);

gpac.init();
gpac.set_logs("all@debug");

const fs = new gpac.FilterSession();
const custom_filter = fs.new_filter("mysource");
custom_filter.set_max_pids(-1);
custom_filter.pids = [];
custom_filter.push_cap('StreamType', 'Visual', gpac.GF_CAPS_OUTPUT);

custom_filter.process = function() 
{
    console.log(`custom_filter.process()`);
    return gpac.GF_OK;
}

custom_filter.configure_pid = function(pid, is_remove) 
{
    console.log(`custom_filter.configure_pid(${pid}, ${is_remove})`);
    return gpac.GF_OK;
}

custom_filter.process_event = function(evt)
{
    console.log(`custom_filter.process_event(${evt})`);
    return true;
}

custom_filter.reconfigure_output = function(pid){
    console.log(`custom_filter.reconfigure_output(${pid})`);
    return gpac.GF_OK;
}

// const f1 = fs.load("pout");
// const f1 = fs.load("fout:force_null");
// const f1 = fs.load_dst("test.mp4");
const f1 = fs.load("inspect:full");
f1.set_source(custom_filter);

fs.run();
fs.print_graph()
```

The custom filter implementation obviously does nothing useful but logging calls, which never happens as the filter is never connected. What am I missing ? 

Do I need to supply a specific argument to the `set_source(...)` function in order to explicitly connect these 2 filters ? 
```
f1.set_source(custom_filter, ARG);
```
I tried several options there, but couldn't figure it out.

### 2. using FIO wrapping

FIO wrapping seems like it could also achieve my goal:

```
const fs = new gpac.FilterSession();
const URL = "myuri"
const fio_wrapper = new gpac.FileIO(url, fio_factory);
const f1 = fs.load_src(fio_wrapper.url);
const f2 = fs.load('inspect');

f2.set_source(f1);
fs.run();
fs.print_graph();
```

My understanding is that gpac first reads the file in an attempt to probe it, then resolves a graph based on the result, is that correct ? Is the ressource url actually involved in the graph resolution (eg. graph resolver inferring the source type from a file extension) ?

At this point I have to log each of the FileIO API functions to figure out what happens in different contexts. Is there additional documentation to understand how the FileIO API works internally in different contexts ?

Finally, is there a case for which the FileIO API solution be favoured over the custom filter when trying to create a source ?

Thanks in advance for any help on this.

**Comment by jeanlf** [comment]
on approach 1:

If the filter is a source, no need for `configure_pid` callback. You will need to:
- setup your pids whenever needed, either at init or in a process callback
- __schedule your source__ for initial processing - this only applies to sources ( I updated the doc, this was indeed missing)

so something like:

```

const fs = new gpac.FilterSession();
const custom_filter = fs.new_filter("mysource");
custom_filter.push_cap('StreamType', 'Visual', gpac.GF_CAPS_OUTPUT);

//we are a source, declare our pids right away
let pid = custom_filter.new_pid();
pid.set_prop('StreamType', 'Visual');
pid.set_prop('Timescale', 100);
pid.is_playing=false;
pid.nb_pck=0;

custom_filter.reschedule();

custom_filter.process = function() 
{
    if (! pid.is_playing) return gpac.GF_EOS;

    if (pid.nb_pck>100) return gpac.GF_EOS;
    let pck = pid.new_pck(0);
    pck.cts = pid.nb_pck;
    pck.send();
    pid.nb_pck++;
    return gpac.GF_OK;
}

custom_filter.process_event = function(evt)
{
    console.log(`custom_filter.process_event type `+ evt.type);
    if (evt.type==gpac.GF_FEVT_PLAY) {
        pid.is_playing=true;
    }
    return true;
}

```


on approach 2:
> My understanding is that gpac first reads the file in an attempt to probe it, then resolves a graph based on the result, is that correct ?

yes, unless you disable data probing (`-no-probe` option)

> Is the ressource url actually involved in the graph resolution (eg. graph resolver inferring the source type from a file extension) ?

only if `-no-probe` is set

> Is there additional documentation to understand how the FileIO API works internally in different contexts ?

Please check the gpac nodejs [test script](https://github.com/gpac/gpac/blob/master/share/nodejs/test/gpac.js) for that. 

> Finally, is there a case for which the FileIO API solution be favoured over the custom filter when trying to create a source ?

usually only for cases involving multiple files for a given source (eg HLS/DASH ), for other cases using a custom source filter should be enough.

**Comment by nlsdvl** [comment]
thank you for the detailed reply @jeanlf, very helpfull.

> schedule your source for initial processing - this only applies to sources ( I updated the doc, this was indeed missing)

Indeed, I didn't get that part at the time. I guess I somehow assumed calling `set_source()` was handling it. Thank you for updating the doc.

**Comment by DenizUgur** [comment]
@jeanlf I wanted to ask something to clarify here

> usually only for cases involving multiple files for a given source (eg HLS/DASH ), for other cases using a custom source filter should be enough.

Does this mean one could create a FileIO for a DASH URL and subsequent segment files will use the same FileIO for requests?

If so, does it inform the FileIO on which file it requests?
