### ISSUE TITLE
For Ubuntu 23.10, libjack-dev needs to be replaced with libjack-jackd2-dev

### ISSUE THREAD

**Issue by emk2203** [gpac/gpac#2663]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/bug-reporting/

For Compilation on Ubuntu Mantic (23.10) and possibly 22.x versions as well, the `libjack-dev` dependency should be replaced by a `libjack-jackd2-dev` dependency. `libjack-dev` install would remove lots of the existing multimedia packages in the system since `libjack0` is not compatible with the `libjack-jackd2-0` used by Ubuntu.

The version v2.2.1 doesn't compile on 23.10. Master from 2023-10-24 does without problem (Easy install).

**Comment by aureliendavid** [comment]
you're right about that

I changed the package in the deb config and in the wiki build instructions

thanks for the report
