### ISSUE TITLE
Can I use MP4Box to affect sidx version?

### ISSUE THREAD

**Issue by elpiptastic** [gpac/gpac#267]
Hi gpac team,

This is a question (from someone new to DASH) rather than an issue.

I'm using MP4Box to package DASH for a customer who is developing an iOS app to stream DASH + WVM + Google iOS WV SDK with a native player.

These encrypted DASH streams are playing out fine on Chrome Desktop and Android, but on iOS (in the above context) playout is failing with this message -  "Cannot parse version 2 of Sidx".

This is triggered in the Google WV library - https://github.com/google/universal-dash-transmuxer/blob/master/library/dash/sidx_contents.cc - and (as I'm sure you are aware) is related to the version of the sidx (SegmentIndexBox).

I'm having a separate discussion with the developer of the universal-dash-transmuxer who is being very helpful, and is looking at potentially updating the code.

But in the meantime, (and this is my question for your team), when I'm using MP4Box to package to DASH are there ways in which I can affect the value of the sidx version?

If I could easily generate DASH with either sidx version 0 or version 2 that would be extremely useful.

I can't see a specific MP4Box param for this -  I'm thinking that perhaps there might be a particular combination of settings that inform this value?

Many thanks.

**Comment by jeanlf** [comment]
AFAIK only version 0 and 1 are defined for sidx, and for the time being we only generate sidx with version 0, not sure what we can do more here ...
