### ISSUE TITLE
Unexpected error at Reproduce HEVC Tile based adaptation guide

### ISSUE THREAD

**Issue by YHLee23232323** [gpac/gpac#2671]
I am trying to use ffmpeg, kvazaar, GPAC to split a mp4 file into tiles.
Following the"HEVC Tile based adaptation guide", here is the command line and results:

```
ffmpeg  -i 008.mp4 -s:v 3840x1920 -r 30 -vf scale=3840x1920 -c:v rawvideo -pix_fmt yuv420p 008.yuv

kvazaar -i 008.yuv --input-res 3840x1920 -o 008.hvc --tiles 3x3 --slices tiles --mv-constraint frametilemargin 

MP4Box -add 008.hvc:split_tiles -fps 30 -new video_tiled.mp4

MP4Box -rem 3 video_tiled.mp4 -out test_tile_lost.mp4

gpac -i test_tile_lost.mp4 hevcmerge vout

``` 

![image](https://github.com/gpac/gpac/assets/149464349/2c63eda4-067f-48a7-8310-bd76d7dc92c8)

![image](https://github.com/gpac/gpac/assets/149464349/36b9b0cd-deb1-4f6d-8b89-8a9fb11c9e30)

What did I miss?

Any help is appreciated!

**Comment by jeanlf** [comment]
hevcmerge is a filter merging raw hevc streams into a tile grid, but what you have in a file after a `:split_tile` (or using `tilesplit` filter) are tiled tracks, where slice headers are not rewritten.

You need to use `gpac -i test_tile_lost.mp4 vout` or `gpac -gui test_tile_lost.mp4`

If you want true merging, you first need to split using `hevcsplit` filter, as [described here](https://github.com/gpac/gpac/wiki/HEVC-Tile-multi-resolution-adaptation-guide)
