### ISSUE TITLE
Remove $ from command-line scripts in the wiki

### ISSUE THREAD

**Issue by oceanjules** [gpac/gpac#2676]
Looking through https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux

And seeing lines like `$ sudo apt install build-essential pkg-config g++ git cmake yasm`

Means that copying them with the quick-copy symbol on the right, copies the leading $-symbol too

Example of a wiki without $ in commands where copied lines could be put into the terminal straight-away: https://github.com/gpac/gpac/wiki/GPAC-build-MP4Box-only-all-platforms

**Comment by rbouqueau** [comment]
Thanks for reporting. Should be fixed!
