### ISSUE TITLE
Capture live multicast stream to MPEG-DASH files

### ISSUE THREAD

**Issue by martidg** [gpac/gpac#268]
Hello,
Is it possible to use GPAC apps to capture the live multicast stream to MPEG-DASH files directly, on the fly?
I tried to use DashCast application and MP4Box wit "grab-ts" otpion but I was able to capture the stream to single file. I wonder If there is a way to save it into DASH format directly.
Thank you,
Martin

**Comment by jeanlf** [comment]
Have you tried https://github.com/gpac/test-engine-live-tools ?
