### ISSUE TITLE
Cannot switch svc layer

### ISSUE THREAD

**Issue by softbearlolz** [gpac/gpac#2682]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ yes] I looked for a similar issue and couldn't find any.
- [ yes] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ yes] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/bug-reporting/

ubuntu 22.04
gpac 2.3-DEV-rev621-g3edb48d2b-master

I use ```MP4Box -add  '/home/moebear/Downloads/DASH-SVC-Toolchain/demultiplex/a.264':svcmode=split a.mp4```

https://drive.google.com/file/d/1A06aGdBOQqQnBlwZbkkKmfaF8LwSbwOS/view?usp=sharing
link to a.264

https://github.com/gpac/gpac/wiki/SVC%20Support%20in%20MP4Box#svc-and-l-hevc-playback

Then I use ```gpac -play a.mp4``` . It pop 3 windows and then occurs many errors, and I cannot use the shortcut ctrl+h, ctrl+l to switch the layer.

**Comment by softbearlolz** [comment]
I solve part of the problem, the opensvc are not contained in default gpac.

still have the following questions:
1. I use ```gpac -play```  and the cpu are always 100% and extremely slow and the video images are broken .
2. Cannot switch the layer by shortcut, ctrl+h show the help menu, same as h.
3.  Always show the lowest quality with 1.

**Comment by rbouqueau** [comment]
Note: you can benchmark gpac on your computer with ```-bench``` and ```-vbench```.

**Comment by softbearlolz** [comment]
> Note: you can benchmark gpac on your computer with `-bench` and `-vbench`.
I play a 2 sec segment with vbench.

```-vbench```
Filter stats - 6 filters

	Filter fin (src=/home/moebear/Downloads/DASH-SVC-Toolchain/decode/0.mp4) : 0 input pids 1 output pids 26 tasks 1456 us process time

		1 packets sent 5000 bytes sent (686.813 pck/sec 27.4725 mbps)

		* output PID 0.mp4: 2 packets sent

	Filter vout (!vsync) : 1 input pids 0 output pids 41 tasks 108656 us process time

		37 packets processed 114203520 bytes processed (340.524 pck/sec 8408.45 mbps)

		* input PID V1: 37 packets received

	Filter mp4dmx : 1 input pids 5 output pids 96 tasks 4329 us process time

		2 packets processed 5000 bytes processed (462 pck/sec 9.24001 mbps)

		121 packets sent 1193497 bytes sent (27951 pck/sec 2205.58 mbps)

		* input PID 0.mp4: 2 packets received

		* output PID V1: 48 packets sent

		* output PID V2: 25 packets sent

		* output PID V3: 48 packets sent

		* output PID V4: 0 packets sent

		* output PID V5: 0 packets sent

	Filter osvcdec : 3 input pids 1 output pids 74 tasks 5586505 us process time

		121 packets processed 1193497 bytes processed (21.6593 pck/sec 1.70911 mbps)

		37 packets sent 114203520 bytes sent (6.6231 pck/sec 163.542 mbps)

		* input PID V1: 48 packets received

		* input PID V2: 25 packets received

		* input PID V3: 48 packets received

		* output PID V1: 37 packets sent

	Filter osvcdec : 1 input pids 1 output pids 4 tasks 68 us process time

		0 packets processed 0 bytes processed (0 pck/sec 0 mbps)



		* input PID V4: 0 packets received

		* output PID V4: 0 packets sent

	Filter osvcdec : 1 input pids 1 output pids 4 tasks 24 us process time

		0 packets processed 0 bytes processed (0 pck/sec 0 mbps)



		* input PID V5: 0 packets received

		* output PID V5: 0 packets sent

Session stats - threads 1

	Thread 1: run_time 5701485 us active_time 5701437 us nb_tasks 251



Total: run_time 5701485 us active_time 5701437 us nb_tasks 251
