### ISSUE TITLE
libgpac-dev unavaible on Ubuntu 23.10

### ISSUE THREAD

**Issue by Om-Thorat** [gpac/gpac#2688]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/bug-reporting/

The package `libgpac-dev` isn't available for the Ubuntu 23.10 Mantic release. [Package search returns no results](https://packages.ubuntu.com/search?suite=mantic&searchon=names&keywords=libgpac), It compiled just fine when building on 23.10 then why is it unavailable? Are there any other issues with gpac on Ubuntu 23.10?

**Comment by rbouqueau** [comment]
Unfortunately we don't decide about this. Linux distribs do. If you like the convenience of the libgpac-dev package, please tell them. I'm sure other people will support you!

**Comment by Om-Thorat** [comment]
Understood, Thanks for the reply!

**Comment by rbouqueau** [comment]
Let us know how it goes. Thanks!
