### ISSUE TITLE
Best flow for performing selective multi-quality 

### ISSUE THREAD

**Issue by MarianoFacundoArch** [gpac/gpac#2699]
Is there any way of using gpac to input a video file and output different qualities, such as, 480p, 720p, 1080p, and forcing some of them to be always generated, such as 480p, and the others only if the video size is at least that size?
What I mean would be, if the input video is 720p, then only 480p and 720p should be generated, but not upscaling to 1080p.
Then, if a video is 240p, then upscale to 480p to have that size at least, and the rest should not be generated.

Among this, also do DRM accordingly

**Comment by jeanlf** [comment]
I would do that either through bash scripting or using a JS filter (or a Python or NodeJS script).  

For the later three, the approach is the same:
- define a custom filter (python/Node) or a JS filter
- check the resolution upon configure_pid callback
- create one, two or three pids depending on the input size
- create rescalers if needed, and set their sources filters to be your custom filter

 Have a look at [JS tests](https://github.com/gpac/testsuite/tree/master/media/jsf) and [python tests](https://github.com/gpac/testsuite/tree/master/media/python) for more details
