### ISSUE TITLE
[DASH] Representation.SegmentList is not supported by DASH-AVC/264.

### ISSUE THREAD

**Issue by vladimir-kazakov** [gpac/gpac#27]
Hi!

While creating DASH media using MP4Box (GPAC rev 5572), I noticed that when I don't specify the "-segment-name" parameter, and the DASH-AVC/264 live profile is used, then I get Representation.SegmentList elements in the MPD. But according to DASH-AVC/264 Interoperability Points v2.0 - "If the Representation.SegmentList is present in a Representation element then this Representation element may be ignored". And media with such MPD doesn't even work in dash.js 1.2.0.

I also checked other profiles, and what I got is (format: profile - element in the Representation - playback status in dash.js 1.2.0):
* dashavc264:live - SegmentList - FAIL
* dashavc264:onDemand - SegmentBase - OK
* live - SegmentTemplate - OK
* onDemand - SegmentBase - OK

So, instead of using SegmentList, SegmentTemplate (like in the "live" case, or while using the "-segment-name" parameter) must be used.

**Comment by jeanlf** [comment]
Indeed, now fixed on rev 5581
