### ISSUE TITLE
when compiling the file, i notice that "gpac/revision.h" is not found, could you tell me where I can download this??

### ISSUE THREAD

**Issue by zsuo** [gpac/gpac#270]

**Comment by rbouqueau** [comment]
This file is generated at compile time. So either:
- you build GPAC yourself and don't have to care for it;
- you use GPAC as a SDK and it is included in every of our builds from gpac.io.

Please give more details if you need it but it doesn't seem to be included in your package.

**Comment by zsuo** [comment]
Ok, thanks a lot~

发件人: Romain Bouqueau
答复: gpac/gpac
日期: 2015年10月5日 星期一 下午4:34
至: gpac/gpac
抄送: 索子晗
主题: Re: [gpac] when compiling the file, i notice that "gpac/revision.h" is not found, could you tell me where I can download this?? (#270)


Closed #270<https://github.com/gpac/gpac/issues/270>.

**Comment by zsuo** [comment]
Hi,
I am building GPAC for IOS, when I follow the rules in README.text.
After step 6:
6) Compile GPAC:
   execute the "gpac/build/xcode/generate_ios.sh" script.
   The script checks that all files have been compiled, print an error message if needed.
   Otherwise it generats a .tar.gz archive into the gpac/bin/iOS directory.

There contains error(shown in the picture):[cid:35C20681-6BCF-409A-B3A1-D9F724B0077E]
Could you tell me how to solve this problem?

Best regards
Zihan suo

发件人: Romain Bouqueau
答复: gpac/gpac
日期: 2015年10月5日 星期一 下午4:34
至: gpac/gpac
抄送: 索子晗
主题: Re: [gpac] when compiling the file, i notice that "gpac/revision.h" is not found, could you tell me where I can download this?? (#270)


Closed #270<https://github.com/gpac/gpac/issues/270>.

**Comment by rbouqueau** [comment]
@zsuo please don't cross post.

**Comment by zsuo** [comment]
By the way, my OS X’s version is 10.11.
发件人: 索子晗
日期: 2015年10月30日 星期五 下午5:22
至: gpac/gpac
主题: Re: [gpac] having a problem when compiling GPAC on Mac... (#304)

Thanks, now I will describe my problem in detail. I downloaded the gpac open source in this webpage:https://sourceforge.net/p/gpac/code/HEAD/tree/trunk/
And I finish the procedures in README_IOS. After the last procedure, I found that it first showed to me :
"gpac/revision.h" is not found

So, I used the revision.h in android package to continue my compiling.
In this revision.h file, the codes are:

#define GPAC_GIT_REVISION "676-g8917b91-master”


Then I compile again, it showed to me that in the file isom_store.c, [cid:C809857D-653C-42A4-9AAD-B50F0665A29D]

which is very strange because the “)” is definitely there.

Could you tell me how to fix this problem?
Thanks a lot.

发件人: Romain Bouqueau
答复: gpac/gpac
日期: 2015年10月30日 星期五 下午4:14
至: gpac/gpac
抄送: 索子晗
主题: Re: [gpac] having a problem when compiling GPAC on Mac... (#304)

tc

**Comment by rbouqueau** [comment]
Don't cross-post. Thank you.
