### ISSUE TITLE
How to Write Only Moof and Mdat Boxes?

### ISSUE THREAD

**Issue by ohjiwoo123** [gpac/gpac#2706]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

## OverView
I am trying to write m4a, m4v files like below   
![image](https://github.com/gpac/gpac/assets/80387186/d4e61a64-00c0-444f-ad68-a4d7ad2d0e84)   

How to write only moof and mdat using Gpac Module API?  

I am trying like below. but it failed to wrtie.  
```
file_ptr = gf_isom_open("output.mp4", GF_ISOM_OPEN_WRITE, NULL);
gf_isom_set_brand_info(file_ptr, GF_ISOM_BRAND_MP42, 0);
gf_isom_setup_track_fragment
gf_isom_start_fragment
gf_isom_fragment_add_sample
fwrite((void*)&file_ptr->moof, 1, sizeof(GF_MovieFragmentBox), wfp);
```
It is right to find it myself, but time is urgent so please understand that I am asking questions.

**Comment by jeanlf** [comment]
you first need to setup the movie, eg  gf_isom_open + gf_isom_new_track + setup sample descriptions + setup track fragments.
Once this is done, call gf_isom_finalize_for_fragment to produce the init segment
then gf_isom_start_fragment (or gf_isom_start_segment if you need different files) + gf_isom_fragment_add_sample


> fwrite((void*)&file_ptr->moof, 1, sizeof(GF_MovieFragmentBox), wfp);

you cannot serialize directly the structures, you need to call the various functions of the API.

You can also use callbacks (gf_isom_set_write_callback) to handle writing in your app

**Comment by ohjiwoo123** [comment]
Thank you for answer!!!! I am gonna try it.

**Comment by ohjiwoo123** [comment]
@jeanlf   
May I ask that how to serialize the data using various functions of the API ??  
and  
I also wonder that how to use gf_isom_set_write_callback this method.. 
If I use gf_isom_set_write_callback this function,
It is applied to next call of gf_isom_write() function ?

**Comment by rbouqueau** [comment]
You can use the search feature of github. It gives results like https://github.com/gpac/gpac/blob/128ca643afb26090d39ac3d4e315605769b42821/src/filters/mux_isom.c#L7639 which is a good starting point!
