### ISSUE TITLE
how to dump raw ts

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#2711]
I have a TS streamed as a TCP source that I want to raw-dump.

The one-liner from the wiki remuxes: ```gpac -i tcp://xxx -o dump.ts```.

I tried to link the source to ```fout``` to no avail: ```gpac -i tcp://xxx @ fout:dst=dump.ts```

What should I do?

**Comment by jeanlf** [comment]
without latest master fix:
`gpac -i tcp://xxx/:ext=ts -o dump.ts`  (or more generally `gpac -i tcp://xxx/:ext=bar -o dump.bar`

for TS, I fixed the sockin prober to announce the ts extension (it was missing, which was preventing the direct copy)

**Comment by rbouqueau** [comment]
Thx!
