### ISSUE TITLE
How to dump thumbs?

### ISSUE THREAD

**Issue by MarianoFacundoArch** [gpac/gpac#2712]
I've been trying to use:
https://github.com/gpac/gpac/wiki/thumbs

So my command was:
```gpac -i "input.mp4" reframer:saps=1 thumbs:snap=30:grid=6x30 -o dump/$num$.png```

But I get:

```
No filter chain found for PID V1 in filter reframer to any loaded filters - NOT CONNECTED
No filter chain found for PID A2 in filter reframer to any loaded filters - NOT CONNECTED
Filters not connected:
 "thumbs" (js=/usr/local/share/gpac/scripts/jsf/thumbs/init.js:snap=30:grid=6x30) (idx=3)
fout (dst=dump/$.png) (idx=4)
```

**Comment by rbouqueau** [comment]
I works here. Two things:
1. What does you input contain? You can check with ```gpac -i input.mp4 inspect```. If all seems normal, would you consider sharing a sample with us?
2. Depending on your shell you may need to escape the ```$``` character in simple quotes ```'$num$.png'```.

**Comment by MarianoFacundoArch** [comment]
Of course,

The output of the command inspect is:
```
PID 1 video inMovie duration 03:49.083 timescale 12288 delay -512 1280x720 fps 24 SAR 1/1 303 kbps 5498 frames codec avc1.4D401F AVC|H264 PL Main@3.1 YUV 4:2:0 8 bpp
PID 2 audio inMovie duration 03:49.088 timescale 44100 44100 Hz 2 channels 128 kbps 9866 frames codec mp4a.40.2 AAC LC (aot=2 implicit)
```

And for the processing command:
```
gpac -i "input.mp4" reframer:saps=1 thumbs:snap=30:grid=6x30 -o "$num$.png"
No filter chain found for PID V1 in filter reframer to any loaded filters - NOT CONNECTED
No filter chain found for PID A2 in filter reframer to any loaded filters - NOT CONNECTED
Filters not connected:
 "thumbs" (js=/usr/local/share/gpac/scripts/jsf/thumbs/init.js:snap=30:grid=6x30) (idx=3)
fout (dst=$.png) (idx=4)
```

I am using the latest commit compiled statically on macoS

**Comment by rbouqueau** [comment]
Is there a way for you to share a sample?

I still think you need to use simple quotes, not double quotes, to avoid the $ to be interpreted.

**Comment by MarianoFacundoArch** [comment]
I fixed it recompiling with all dependencies instead of the minimal version, however now:

<img width="201" alt="image" src="https://github.com/gpac/gpac/assets/19694461/b194e226-b303-48c7-a451-53f64cc63ce2">


Instead of using numbers the file name is just $.png

**Comment by rbouqueau** [comment]
Great. Use single quotes ```'$num$.png'``` instead of double quotes ```"$num$.png"```.

**Comment by MarianoFacundoArch** [comment]
Working! Thaks!
