### ISSUE TITLE
when i mux the video data using gpac, does gpac automatically input cts pts dts value? 

### ISSUE THREAD

**Issue by ohjiwoo123** [gpac/gpac#2714]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

I am gonna try making video fragment mp4.  
I think that  CTS_Offset is using for getting timestamp difference of decoding order.  

PTS : 1 4 2 3   
DTS : 1 2 3 4   
IPBB   

when I muxing the video data using gpac, does gpac automatically input CTS_Offset? 
or 
do I input myself?
something like below,
```
iso_sample.IsRAP= RAP;
iso_sample.data = &buf[index];
iso_sample.dataLength = (frame_size - ADTS_HEADER_SIZE);
iso_sample.DTS = xxx;
iso_sample.CTS_Offset = xxx;
iso_sample.nb_pack = 0;
gf_isom_fragment_add_sample();
```

**Comment by jeanlf** [comment]
If you use libisom API (eg gf_isom_*), you must set the timestamps and RAP flags yourself yes.

To avoid this, you will need to use a filter chain for the muxing (and a GF_FileIO object if your fragments are in separate files)
