### ISSUE TITLE
How to output multiquality dash + hls from multiple mp4 files

### ISSUE THREAD

**Issue by MarianoFacundoArch** [gpac/gpac#2715]
What would be a to-go command to output dash + hls from several .mp4 files (each mp4 file represents one quality, with its own video and audio track configurations).
In fact, video codecs depend from one quality to another sometimes.

Is there a way to do this using GPAC? 
And if it is, how to perform DRM with different keys per each video track (quality) ?

Thanks,

**Comment by rbouqueau** [comment]
You can provide several inputs using several ```-i``` on the command-line. You can then refer to them using ```@``` (backward) or ```@@``` (forward) or FID/SID (example below). From what I understand the input mp4 files are ready to be packaged, so no transcoding is needed.

> And if it is, how to perform DRM with different keys per each video track (quality) ?

Yes. I think you should encrypt the content before providing is to the packager e.g.:
```
gpac -i 1.mp4 @ cecrypt:cfile=1.xml:FID=SRC1 -i 2.mp4 @ cecrypt:cfile=1.xml:FID=SRC2 -o dash.mpd:SID=SRC1,SRC2
```

Of course this command-line misses all options but I hope you understand the mechanism.

**Comment by jeanlf** [comment]
Also if you need to output both DASH and HLS for the same media segments, use the `dual` option, e.g. `-o dash.mpd:dual`

**Comment by MarianoFacundoArch** [comment]
I've been trying lots of options and I'm not being able to specify the hls_key_uri for each quality, at least being able to put skd://KEYID would be great.

I get when encoding
```
[HLS] Missing key URI in one or more keys - will use dummy one URI="gpac:hls:key:locator:null"

[HLS] Missing key URI in one or more keys - will use dummy one URI="gpac:hls:key:locator:null"
```

Should I create a new post to address this?
Thanks!

**Comment by jeanlf** [comment]
for each input SRC, use `-i SRC::#HLSKey=yourkeyuri_and_opts`

**Comment by MarianoFacundoArch** [comment]
@jeanlf Thank you, that surely works for setting the URI, 
I was looking at the documentation and it says:
```

HLSKey | str |   | URI, KEYFORMAT and KEYFORMATVERSIONS for HLS full segment encryption creation, Key URI otherwise ( decoding and sample-AES) | HLSK

```

However, I am not figuring out how to set also the keyformat and keyformatversions in the parameters, it always ends up with my keyformat and keyformatversions put inside the URI.
What am I missing?
Thanks

**Comment by MarianoFacundoArch** [comment]
I found a "hack"

It's using parameters
```::#HLSKey=skd://key",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1```

Is this how it's intended to be done? Or is there a correct way? Here I am "hacking" that I know that it will add '"' double quotes on between my string, so I "tune" the config to make those quotes work for me in the resulting hls.

Is this the way or is there a better way to do so?

Thanks

**Comment by MarianoFacundoArch** [comment]
Hi,
I don't know if anyone had the opportunity to read my previous message, I was not able to find any other way.
Is that the correct one or am I missing anything?
Thanks!

**Comment by rbouqueau** [comment]
Does this example help? https://github.com/search?q=repo%3Agpac%2Ftestsuite%20HLSKey&type=code

**Comment by MarianoFacundoArch** [comment]
Hi @rbouqueau ,
I might be missing something, but I cannot get that to work when in GPAC. In any case I don't really get how to use it.

My current command looks like this:
```
   `cecrypt:cfile=${currentInput.specFile}:FID=SRC${currentSrcId}::#HLSKey=skd://${currentInput.drmKey.keyId}",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1`,
```

I am "hacking" to make it add the skd:// with keyformat in com.apple.streamingkeydelivery and KEYFORMATVERSIONS in 1,
I need to achieve the same result but with the correct way, is there anyway to achieve that?

**Comment by rbouqueau** [comment]
I can't figure out either. Some code is duplicated in ```decrypt_cenc_isma.c``` and ```io_fcrypt.c```. The example only shows how to define ```HLSKey```.
