### ISSUE TITLE
language command does not always work

### ISSUE THREAD

**Issue by astlaurent** [gpac/gpac#272]
It seems that if i specify -lang eng in the command sometimes it will not change the language of the track. 

For example if i do mp4box -lang fr '.\Avengers Age of Ultron(2015).mp4' on a file that has eng tagged stream it will not change it to fr it will stay at eng. 

it seems that it might be when you go between a 2 letter code and a 3 letter code it will not make the change.

**Comment by rbouqueau** [comment]
If you want to change the lang of a track, use ```-add file.mp4:lang=eng```. More info at http://gpac.io/2014/09/23/language-tagging-in-gpac/

**Comment by astlaurent** [comment]
i am confused because sometimes  
mp4box -lang eng file.mp4
works fine. it seems to write out a new file.mp4 tmp file and then rename it to the original name. sometimes the new language code is there and sometimes it is not. If i use the -add feature it seems to import  the original mp4 into a new output container which is not what i want. i simply just need to edit the metadata in the original file.

**Comment by rbouqueau** [comment]
I don't know. @cconcolato @jeanlf any idea about such a behaviour?

**Comment by cconcolato** [comment]
The problem is due to the way we store 3-chars language (eng) codes vs. 2 (en) or 2-2 (en-UK). If you stick to one form, one length, it should work. I will fix it asap.

**Comment by jeanlf** [comment]
I believe this should have been a few weeks ago, re-open if needed
