### ISSUE TITLE
Inquiry about gf_isom_get_sidx_duration function 

### ISSUE THREAD

**Issue by ohjiwoo123** [gpac/gpac#2725]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

Hello, Thank you for your hard work. Sorry for asking a lot of questions recently.  
I want to get earliest_presentation_time value in sidx box.
I tried to use below function
```
GF_EXPORT
GF_Err gf_isom_get_sidx_duration(GF_ISOFile *movie, u64 *sidx_dur, u32 *sidx_timescale)
{
	u64 dur=0;
	u32 i;
	if (!movie || !movie->moov || !sidx_timescale || !sidx_dur)
		return GF_BAD_PARAM;

	if (!movie->main_sidx) return GF_NOT_SUPPORTED;
	*sidx_timescale = movie->main_sidx->timescale;

	for (i=0; i<movie->main_sidx->nb_refs; i++) {
		dur += movie->main_sidx->refs[i].subsegment_duration;
	}
	*sidx_dur = dur;
	return GF_OK;
}
```

My thought about this function,    
this function only return GF_NOT_SUPPORTED    
because movie->main_sidx never allocated.    

I search main_sidx ,   
I could not find using of main_sidx   
![image](https://github.com/gpac/gpac/assets/80387186/c3c1ff47-9a17-48be-85e4-8a42479a9e31)  

how to get earliest_presentation_time value in sidx box ?? 

I am file open with callback mode using "_gpac_isobmff_redirect" and    
making sidx box using ```gf`_isom_close_segment``` now.

**Comment by rbouqueau** [comment]
In your screen capture, the first search results set it: ```mov->main_sidx = (GF_SegmentIndexBox *) a;```.

Could you share some sample code + data to reproduce your behaviour? The error certainly comes from your sequence of calls.

**Comment by ohjiwoo123** [comment]
Code flow  
1 make iso file  
```
file_ptr = gf_isom_open("_gpac_isobmff_redirect", GF_ISOM_OPEN_WRITE, NULL);
// using callback 
err = gf_isom_set_write_callback(file_ptr, mp4_mux_on_data, NULL, NULL, file_ptr, 0);
track_id = gf_isom_new_track(file_ptr, 0, GF_ISOM_MEDIA_AUDIO, SAMPLINGRATE);
err = gf_isom_set_track_enabled(file_ptr, track_id, GF_TRUE);
err = gf_isom_new_mpeg4_description(file_ptr, track_id, stream_desc_ptr, NULL, NULL, &sample_description_index);
err = gf_isom_set_audio_info(file_ptr, track_id, sample_description_index, SAMPLINGRATE, 1, BPS, GF_IMPORT_AUDIO_SAMPLE_ENTRY_v1_MPEG);
err = gf_isom_set_pl_indication(file_ptr, GF_ISOM_PL_AUDIO, aac_profile);
``` 
2 ready to fragment 
```
err = gf_isom_setup_track_fragment(file_ptr, track_id, sample_description_index, 0, 0, 0, 0, 0 , GF_FALSE);
err = gf_isom_finalize_for_fragment(file_ptr, REGULAR_SEGMENT, GF_TRUE);
```
3 add fragment 
```
err = gf_isom_start_segment(file_ptr, "_gpac_isobmff_redirect", GF_TRUE);
err = gf_isom_start_fragment(file_ptr, GF_ISOM_FRAG_MOOF_FIRST);
// add data from my own aac files 
err = gf_isom_fragment_add_sample(file_ptr, track_id, &iso_sample, sample_description_index, AAC_BLOCK_LENGTH, 0, 0, GF_FALSE);
err = gf_isom_set_traf_base_media_decode_time(file_ptr, track_id, AAC_BLOCK_LENGTH*box_offset);
```
**4 trying to read sidx earliest_presentation_time**   
```
u64 sidx_dur = 0;
u32 sidx_timescale = 0;
err = gf_isom_get_sidx_duration(file_ptr, &sidx_dur, &sidx_timescale);
// this show always zero value now.... 
printf("sidx_dur : %ld sidx_timescale: %d\n", sidx_dur, sidx_timescale);
```
5 close sement  
```
err = gf_isom_close_segment(file_ptr, 0, track_id, (AAC_BLOCK_LENGTH*box_offset), 0, 0, GF_FALSE, GF_FALSE, GF_FALSE, GF_FALSE, 0, 0, 0, NULL)
```
6 repeat 3~5    
7 delete memory   
```
gf_isom_delete(file_ptr);
```

**Comment by rbouqueau** [comment]
I don't need a code flow, I need a working example to be able to assist you.

```mov->main_sidx = (GF_SegmentIndexBox *) a;``` is called from:
-  ```gf_isom_parse_movie_boxes_internal()``` which is called from:
- ```gf_isom_parse_movie_boxes()```  which is called from:
  - ```gf_isom_open_file()``` => read => discard
  - ```gf_isom_open_progressive_ex()``` => idem
  - ```gf_isom_load_fragments()``` => idem
  - ```gf_isom_refresh_fragmented()``` => idem
  - ```gf_isom_open_segment()``` => called by the app, read => discard

So the API doesn't seem to be made to retrieve the ```sidx``` duration. Since you are using the low level API you are pushing the timestamps in ```iso_sample```. Can you detail why you need it and what you plan to do with it?
