### ISSUE TITLE
#video and #audio input suffix not working 

### ISSUE THREAD

**Issue by ryanbennettvoid** [gpac/gpac#273]
I'm using MP4Box to DASH an MP4 that contains muxed audio and video. Dash.js doesn't support muxed content, so apparently the inputs must take in video and audio separately.

These are the commands I'm using:
```
ffmpeg -i video.mp4 -r 24 -g 72 -c:v libx264 -c:a libvo_aacenc -ar 44100 -ac 1 intermediate.mp4
MP4Box -dash 10000 -profile dashavc264:onDemand intermediate.mp4#video intermediate.mp4#audio
```

I'm getting the error: `[DASH]: None of the input types are supported for DASHing - nothing to do`

Using just one input `intermediate.mp4` results in a successful DASH, but due to a multiplexed representation, it'll fail to play with Dash.js.

Is this a syntax issue or an issue with the input encoding? Using version 0.5.1-DEV-rev4065.

**Comment by jeanlf** [comment]
hmm strange this is supposed to work, just like #ID=X. I'll have a look asap

**Comment by ryanbennettvoid** [comment]
I just tried on 0.5.2-DEV-rev709 and it works. I guess the feature wasn't included in the older version.
