### ISSUE TITLE
Build Error, undefined reference to `SSL_get_peer_certificate'

### ISSUE THREAD

**Issue by ohjiwoo123** [gpac/gpac#2734]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

The build was going well, but suddenly the error message below appeared, so I would like to inquire.  
```
./lib/libgpac_static.a(downloader.o): In function `gf_ssl_check_cert':  
downloader.c:(.text+0x5b4e): undefined reference to `SSL_get_peer_certificate'  
``` 

All logs
```
[100%] Linking CXX executable mediastreamingserver
/usr/bin/cmake -E cmake_link_script CMakeFiles/mediastreamingserver.dir/link.txt --verbose=1
/usr/bin/c++  -O2 -g -rdynamic CMakeFiles/mediastreamingserver.dir/src/util/src/buffer.cpp.o CMakeFiles/mediastreamingserver.dir/src/util/src/ip.cpp.o CMakeFiles/mediastreamingserver.dir/src/util/src/log.cpp.o CMakeFiles/mediastreamingserver.dir/src/util/src/time.cpp.o CMakeFiles/mediastreamingserver.dir/src/module/isobmff/muxer/src/muxer.cpp.o CMakeFiles/mediastreamingserver.dir/src/protocol/bus.pb.cc.o CMakeFiles/mediastreamingserver.dir/src/server/src/transcoder.cpp.o CMakeFiles/mediastreamingserver.dir/src/server/src/broadcast.cpp.o "CMakeFiles/mediastreamingserver.dir/src/server/src/channel-map.cpp.o" CMakeFiles/mediastreamingserver.dir/src/server/src/channel.cpp.o CMakeFiles/mediastreamingserver.dir/src/server/src/client.cpp.o CMakeFiles/mediastreamingserver.dir/src/server/src/resource.cpp.o CMakeFiles/mediastreamingserver.dir/src/module/nats/util/src/string.cpp.o CMakeFiles/mediastreamingserver.dir/src/main.cpp.o -o mediastreamingserver   -L/home/jwoh/mediastreamingserver/./lib  -L/usr/local/lib  -L/home/jwoh/mediastreamingserver/./pkg/vcpkg/installed/x64-linux/lib  -L/opt/boost/lib  -Wl,-rpath,/home/jwoh/mediastreamingserver/./lib:/usr/local/lib:/home/jwoh/mediastreamingserver/./pkg/vcpkg/installed/x64-linux/lib:/opt/boost/lib -ldl -lboost_date_time -lpthread -lboost_system -lboost_filesystem -lboost_chrono -lboost_thread -lgpac_static -ldl -lpng /usr/lib64/liblzma.so /usr/lib64/libz.so -lssl -lcrypto -lcurl -lyaml-cpp -lnats_static -lprotobuf -lsodium -lboost_date_time -lpthread -lboost_system -lboost_filesystem -lboost_chrono -lboost_thread -lgpac_static -lpng -lssl -lcrypto -lcurl -lyaml-cpp -lnats_static -lprotobuf -lsodium -lpthread
/home/jwoh/mediastreamingserver/./lib/libgpac_static.a(downloader.o): In function `gf_ssl_check_cert':
downloader.c:(.text+0x5b4e): undefined reference to `SSL_get_peer_certificate'
```

The environment is as follows  
```
NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"
```

```
target_link_libraries(
    ${tname}
    ${CMAKE_DL_LIBS}
    boost_date_time
    pthread
    boost_system
    boost_filesystem
    boost_chrono
    boost_thread
    gpac_static dl # gpac
    png # gpac
    Threads::Threads # gpac
    LibLZMA::LibLZMA # gpac
    ZLIB::ZLIB # gpac + ...
    ssl
    crypto
    curl # using libcurl
    yaml-cpp
    nats_static
    protobuf
    sodium
)
```

Special features include `ssl crypto curl yaml-cpp nats_static, etc.,` which are used through vcpkg.

**Comment by aureliendavid** [comment]
Hello, 

It's hard to debug since you're not building gpac but your own project that uses libgpac, I can't test it. 

Basically the error message tells you that the linker didn't find what it needed in the crypto and ssl libs. 

Some things to check:

* make sure libcrypto and libssl are present in the directories you added in your -L directives (I think they are otherwise the error would be different)

* sometimes the link order is important, especially on linux: try to have the -lgpac_static before any other -l in your command line (not sure how to achieve this in cmake but you can try on the command line directly) 

* the problem could also come from the mixing of c++ executable and c library with different naming convention for exported symbols (maybe a missing extern "C") but it's hard to tell from only this

**Comment by ohjiwoo123** [comment]
The openssl version of vcpkg is confirmed to be `3.2.0#2`.  
Looking at the ChangeLog   
```
* Compatibility with OpenSSL 1.1.x
```
https://github.com/gpac/gpac/blob/5f10205c2e07bf22e2aee82145a43351f8fb832a/Changelog#L314   
Is OpenSSL only compatible with 1.1.x?

**Comment by aureliendavid** [comment]
gpac is forward-compatible with openssl up to at least 3.2 (just tested it) so I don't think your issue comes from there, more likely a weird linking issue as I mentioned 

(the line quoted in the gpac changelog was because of api changes between 1.0 and 1.1)

**Comment by ohjiwoo123** [comment]
Thank you for answer    
Additionally, How to off #define GPAC_HAS_SSL this option?   
using ./configure ??

**Comment by aureliendavid** [comment]
you can use 
```
./configure --use-ssl=no
```
to disable it

(see `./configure -h` for more options)
