### ISSUE TITLE
Error in downloading DASH segments with master (gpac-2.3-DEV)

### ISSUE THREAD

**Issue by abhinaba-fbr** [gpac/gpac#2736]
I, am trying to stream DASH using gpac client 2.3-DEV-rev version. However, I get consecutive error in downloading the DASH segments. I am not sure, if its the issue is with the latest version. Because, I worked with 2.0 gpac version and it worked fine a year ago.

**Error -**
`[Core] system failure for file opening of "/tmp/gpac_cache/gpaccache.test" in mode "wb": 13
[Core] system failure for file opening of "/tmp/gpac_cache/gpaccache.test" in mode "wb": 13
[Cache] Cannot write to /tmp/gpac_cache/ directory, using system temp cache
[DASH] Error in downloading new segment http://localhost:8000/chunk-stream0-00001.m4s: Connection to server closed
[DASH] Error in downloading new segment http://localhost:8000/chunk-stream1-00001.m4s: Connection to server closed
[DASH] Error in downloading new segment http://localhost:8000/chunk-stream0-00002.m4s: Connection to server closed
[DASH] Error in downloading new segment http://localhost:8000/chunk-stream1-00002.m4s: Connection to server closed
[DASH] Error in downloading new segment http://localhost:8000/chunk-stream1-00003.m4s: Connection to server closed
[DASH] Error in downloading new segment http://localhost:8000/chunk-stream1-00004.m4s: Connection to server closed
[DASH] Error in downloading new segment http://localhost:8000/chunk-stream1-00005.m4s: Connection to server closed
[DASH] Error in downloading new segment http://localhost:8000/chunk-stream1-00006.m4s: Connection to server closed
[DASH] Error in downloading new segment http://localhost:8000/chunk-stream1-00007.m4s: Connection to server closed
[DASH] Error in downloading new segment http://localhost:8000/chunk-stream1-00008.m4s: Connection to server closed
[DASH] Error in downloading new segment http://localhost:8000/chunk-stream1-00009.m4s: Connection to server closed
[DASH] Too many consecutive segments not found (broken source, sync or signal lost...) - entering end of stream detection mode
` 

- [ x] I looked for a similar issue and couldn't find any.
- [ x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [ x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

**Comment by jeanlf** [comment]
It looks like you have write rights issues with /tmp,  can you cross-check ? What is your OS ?

**Comment by abhinaba-fbr** [comment]
> It looks like you have write rights issues with /tmp, can you cross-check ? What is your OS ?
My write access for /tmp is drwxrwxrwt, I changed it to drwxrwxrwx as well, still I see the similar issue.
