### ISSUE TITLE
Do I making all segment files to one progressive mp4 ??

### ISSUE THREAD

**Issue by ohjiwoo123** [gpac/gpac#2737]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

If I make isomedia file with   
```
file_ptr = gf_isom_open("_gpac_isobmff_redirect", GF_ISOM_OPEN_WRITE, NULL);
gf_isom_set_write_callback
gf_isom_open_segment 
gf_isom_close_segment
```
All segment files managed by callback function  
If I make 10 segments,  
Is it possible to combine 10 segments to one progressive mp4 using gpac API ??

**Comment by jeanlf** [comment]
If you segment the file, you need to prepare it for segmentation (eg use gf_isom_setup_track_fragment and gf_isom_finalize_for_fragment). Concatenating the bytes received in a single file will create a progressive fragmented file.

If you only need a progressive non-fragmented file (moov+mdat), don't use  gf_isom_open_segment/gf_isom_close_segment, just set the storage mode to GF_ISOM_STORE_INTERLEAVED

cf https://github.com/gpac/gpac/blob/master/applications/testapps/mp4mux/main.c
