### ISSUE TITLE
Can I set compatible_versions via mp4box?

### ISSUE THREAD

**Issue by BrandonStudio** [gpac/gpac#2741]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

I want to generate (convert to) an m4a file with `major_brand` `mp42`, `minor_brand` `0`, and `compatible_brands` `M4A mp42isom`. I tried this:
```cmd
mp4box -brand "mp42 :0" file.m4a
```
but got `compatible_brands` `mp4aisomiso2`

Is it possible to change `compatible_brands`? Does `compatible_brands` matter?

**Comment by jeanlf** [comment]
compatible brands are set using -ab and -rb, see ` MP4Box -hx brand`.

Whether they matter will depend on the file reader, some will check them and possibly complain, most will ignore them.

**Comment by jeanlf** [comment]
> Does the order of compatible_brands matter?

usually no, I'm not aware of any derived spec from ISOBMFF requiring a given order on these

> By the way, does spaces in compatible_brands matter?

if the brand 4CC is using a space then yes, otherwise no
