### ISSUE TITLE
Can't start GPAC in live playlist mode

### ISSUE THREAD

**Issue by alex-rsk** [gpac/gpac#2746]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ +] I looked for a similar issue and couldn't find any.
- [ + ] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [+ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

After dozens of hours of googling and thoroughly reading every piece of info, I'm still unable to start dynamic MPD broadcasting.

I've installed GPAC version 2.3-DEV-rev832-g799d9e547-master.
My OS Ubuntu 22

My goal is simple:
I getting short videofiles from time to time, and I want to combine them to "pseudo-stream".
My files have length exactly 30s, and I want to append them dynamically

```
gpac -i pl.m3u:ka=2000 -o live.mpd:dmode=dynamic

```

The playlist is very simple
```
##begin pl,m3u
../segment_0000.mp4
../segment_0001.mp4
##end playlist

```
What I get -- is a bunch of m4s files and few mp4 files, along with live.mpd file.

When i'm trying to play it, i have errors.

FFplay:  
hundreds of such:
```
[dash @ 0x7f2228000cc0] Failed to open fragment of playlist f=0/0   
    Last message repeated 2188 times
[dash @ 0x7f2228000cc0] Failed to open fragment of playlist f=0/0   
```
mpv:
hundreds of such
```
[ffmpeg/demuxer] dash: Failed to open fragment of playlist
[ffmpeg/demuxer] dash: Failed to open fragment of playlist
```

MPD file not containing any relative paths:

```
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 2.3-DEV-rev832-g799d9e547-master at 2024-01-29T19:47:00.512Z -->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.000S" type="dynamic" availabilityStartTime="2024-01-29T19:47:00.510Z" publishTime="2024-01-29T19:47:00.512Z" minimumUpdatePeriod="PT0H0M1.000S" timeShiftBufferDepth="PT0H0M30.000S" profiles="urn:mpeg:dash:profile:full:2011">
 <ProgramInformation moreInformationURL="https://gpac.io">
  <Title>live.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period id="DID1" start="PT0H0M0.000S">
  <AdaptationSet segmentAlignment="true" maxWidth="1280" maxHeight="720" maxFrameRate="25" par="16:9" startWithSAP="1">
   <SegmentTemplate media="segment_0000_dash_track1_$Number$.m4s" initialization="segment_0000_dash_track1_init.mp4" timescale="12800" startNumber="1" duration="12800"/>
   <Representation id="1" mimeType="video/mp4" codecs="avc1.64001F" width="1280" height="720" frameRate="25" sar="1:1" bandwidth="1812813">
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" startWithSAP="1">
   <SegmentTemplate media="segment_0000_dash_track2_$Number$.m4s" initialization="segment_0000_dash_track2_init.mp4" timescale="44100" startNumber="1" duration="44100"/>
   <Representation id="2" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="44100" bandwidth="1407">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```

Any help is really appreciated.

**Comment by jeanlf** [comment]
Apart from the possible playlist reload bug (fixed in bd5ee783 but typo in msg) , I think the problem comes from flushing the stream: if you get 30s of data every 30s, the segment N won't be produced until the N+1 comes in (it will need the first frame of the following to detect the cut)
I've added a `flush` option to flist to force flushing pending segments in the dasher (same as what we already have for pipes), and this seems to work. You will also need the `sigcues` option and dash with the same duration as your sources:

The following example works fine (output tested with ffplay), with 10s files
  
```
#!/bin/sh

echo "##empty" > pl.m3u
rm -rf dash/*

gpac -logs=dash@info -i pl.m3u:ka=2000:flush:sigcues -o dash/live.mpd:dynauto:segdur=10:tsb=-1 &

for i in {1..61} ; do
	echo "Appending src_$i.mp4 to playlist"
	echo "src_$i.mp4" > pl.m3u
	sleep 10
done

#done
echo "#end" > pl.m3u


```
