### ISSUE TITLE
How to decrypt a single segment (DRM) and how to encrypt it back

### ISSUE THREAD

**Issue by MarianoFacundoArch** [gpac/gpac#2747]
Hello,
I have a doubt, I think I remember reading how to do this in the past, but I can't remember if it was in gpac or the other known product (I'm not mentioning it here). The question is how to decrypt a specific segment, let's say, video_dash4.m4s if I have the xml I encrypted the full video with, and also (if needed) the dashinit.mp4 file

Then I want to encrypt it back (Only that segment)

Is that possible?
How?

Thanks!

**Comment by rbouqueau** [comment]
Decrypt: ```gpac --initseg=init.mp4 -i enc.m4s cdcrypt:cfile=enc.xml -our clear.mp4:frag:cmfc:noinit```

There are examples in the testsuite to re-encrypt: https://github.com/gpac/testsuite/blob/4a9b73554a427520c5779b976454705306d76179/scripts/encryption_segment.sh#L19. Let me know if you need help to translate them from MP4Box to gpac.

**Comment by MarianoFacundoArch** [comment]
Hi,
I've tried the decrypt one first, apparently the :noinit is adding the mp4 header all the same to the outputted mp4, which it's not relevant at that point even i think it was not supposed to, but when I encrypt back with:
```
pac --initseg=video_h264_240_videoBitrate_500k_dashinit.mp4 -i clear.mp4 cecrypt:cfile="65b90ca70c6d482b06f6d2d38e63906d.xml" -o clear2.mp4::frag:cmfc:noinit
```

I get: 
```
[iso file] senc box without tenc, assuming MS smooth+piff
Attempt at defining data property CBIV with NULL pointer, not allowed
zsh: segmentation fault  gpac --initseg=video_h264_240_videoBitrate_500k_dashinit.mp4 -i clear.mp4  -o
```

**Comment by rbouqueau** [comment]
> I've tried the decrypt one first, apparently the :noinit is adding the mp4 header 

I think that's because  the .mp4 file extension. Try .m4s instead. GPAC uses a mime-type system that may be inferred from the file extention.

I'm going to have a look at the seg fault.

**Comment by rbouqueau** [comment]
It works here. Would you mind sending me some sample files so that I reproduce?

**Comment by MarianoFacundoArch** [comment]
Of course, I attach the files and provide the commands.

[Click here for accessing the files](https://cloud.scigliano.vip/s/HCcWzdbn7oYMd9s)

The commands I run are (I am outputting an mp4 on purpose with the init sequence here)

First decode in output.mp4:
``` 
gpac --initseg=video_h264_240_videoBitrate_500k_dashinit.mp4 -i video_h264_240_videoBitrate_500k_dash5.m4s  cdcrypt:cfile=65ba491c2aee781a10452d4764ddf497.xml -o output.m4s:frag:cmfc:noinit
```

Content is decrypted correctly in output.mp4

Now, I try to repack:

```
gpac --initseg=video_h264_240_videoBitrate_500k_dashinit.mp4 -i output.m4s cecrypt:cfile=65ba491c2aee781a10452d4764ddf497.xml -o output_encoded.m4s:frag:cmfc:noinit
```

And I get:
```
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
[CENC] Packet encrypted but no SAI info nor constant IV
session last process error Internal Service Error
```

**Comment by jeanlf** [comment]
the init segment you use for encryption is an encrypted init segment, hence it declares an encrypted PID but the segment (clear) has no SAI.

You need to produce a clear version of the init segment:

```
gpac -i init_crypted.mp4 cdcrypt:cfile=drm.xml -o clear_init.mp4
# or simpler:
gpac -i init_crypted.mp4:nocrypt -o clear_init.mp4

```

or if you don't want to produce the clear init, set the `nocrypt` option on the input file or as global opt:

```
gpac --initseg=crypt_initmp4 -i clear_seg.m4s:nocrypt cecrypt:cfile=DRM.xml -o seg_crypted.m4s:frag:cmfc:noinit

gpac --initseg=crypt_initmp4 --nocrypt -i clear_seg.m4s cecrypt:cfile=DRM.xml -o seg_crypted.m4s:frag:cmfc:noinit
```

**Comment by MarianoFacundoArch** [comment]
@jeanlf using the nocrypt on the input file would produce the exact ssame results as if I outputted the unencrypted init segment and then using it to crypt?
If that's the case, why would I want to output the clear init file? I can completely avoid that by using the nocrypt option so that I reduce one extra step?
Thanks

**Comment by jeanlf** [comment]
> using the nocrypt on the input file would produce the exact ssame results as if I outputted the unencrypted init segment and then using it to crypt?

yes

> I can completely avoid that by using the nocrypt option so that I reduce one extra step?

yes

**Comment by jeanlf** [comment]
you can also do it in one pass:

```
gpac --initseg=INIT -i seg_cryp.m4s cdcrypt:cfile=DECRYPT.xml cecrypt:cfile=ENCRYPT.xml -o seg_recryp.m4s:frag:noinit 
```
