### ISSUE TITLE
Feature request - imdt support

### ISSUE THREAD

**Issue by bradh** [gpac/gpac#2749]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

I am trying to test a file that uses `imda`, which needs support for the `imdt` data reference. I see some work to add the `imda` container, but there does not appear to be `imdt` (under `dref`) support.

A couple of samples are attached as zip - the content should be the same in each, but the `_imda.heif` version is reported as invalid in gpac (and it could well be wrong as well).
[rgb_component.zip](https://github.com/gpac/gpac/files/14164077/rgb_component.zip)

**Comment by jeanlf** [comment]
Should now work on master.
Note however that your imda file is wrong, it indicates a construction_method of 2 but it should be 0.

**Comment by bradh** [comment]
Thanks - indeed looks like confusion between `construction_method` and `data_reference_index`.

**Comment by bradh** [comment]
Does this look better?

[rgb_component_imda.zip](https://github.com/gpac/gpac/files/14459564/rgb_component_imda.zip)

**Comment by jeanlf** [comment]
yes, I believe the file is now correct
