### ISSUE TITLE
Images with construction_method=2 not fully supported

### ISSUE THREAD

**Issue by bradh** [gpac/gpac#2754]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

Using `iloc` with `construction_method == 2` appears to work OK for the case where `data_reference_index == 0`. 

It doesn't work for the case where `data_reference_index` is 1, irrespective of whether the `DataEntryUrlBox` uses the flags `0x000001`  method to point to the same file, or whether it uses a file. Instead, it just produces an empty black image.

![image](https://github.com/gpac/gpac/assets/174642/7d6efeef-be7f-4c3d-baf0-fe5c67031766)

Sample files:

[rgb_component_external.zip](https://github.com/gpac/gpac/files/14237180/rgb_component_external.zip)

**Comment by jeanlf** [comment]
for now we don't support reading items with construction_method=2.

However the file is not correct: construction_method=2 means building from other items in the same file, but your file has a single item.
