### ISSUE TITLE
error occurs when building GPAC for IOS

### ISSUE THREAD

**Issue by zsuo** [gpac/gpac#276]
Hi, 
I am building GPAC for IOS, when I follow the rules in README.text.
I have already finished first five steps. When following step 6:
6) Compile GPAC:
   execute the "gpac/build/xcode/generate_ios.sh" script.
   The script checks that all files have been compiled, print an error message if needed.
   Otherwise it generats a .tar.gz archive into the gpac/bin/iOS directory.

There contains error(shown in the picture):
<img width="570" alt="error" src="https://cloud.githubusercontent.com/assets/14800803/10424128/fee1dd54-70fe-11e5-9317-eedd4d2f189f.png">

Could you tell me how to solve this problem?

Best regards
Zihan suo

**Comment by rbouqueau** [comment]
Did you solve your issue?

**Comment by jeanlf** [comment]
now fixed on git and will make it in 0.6.1 on its way (same error occured for regular OSX builds)
