### ISSUE TITLE
uncvdec Arithmetic exception (SIGFPE) decoding version 1 rgba file

### ISSUE THREAD

**Issue by bradh** [gpac/gpac#2762]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

On Linux with gcc, my gpac build from master branch fails with 

```
 ~/gpac/bin/gcc/gpac -gui tests/encode_rgba_version1.heif 
Floating point exception (core dumped)
```

Running under GDB:
```
Thread 20 "gpac" received signal SIGFPE, Arithmetic exception.
[Switching to Thread 0x7fff611ff6c0 (LWP 47650)]
0x00007ffff7984e98 in uncvdec_configure_pid () from /home/bradh/gpac/bin/gcc/libgpac.so.12
(gdb) bt
#0  0x00007ffff7984e98 in uncvdec_configure_pid () at /home/bradh/gpac/bin/gcc/libgpac.so.12
#1  0x00007ffff790e9a9 in gf_filter_pid_configure () at /home/bradh/gpac/bin/gcc/libgpac.so.12
#2  0x00007ffff79104e6 in gf_filter_pid_connect_task () at /home/bradh/gpac/bin/gcc/libgpac.so.12
#3  0x00007ffff792897b in gf_fs_thread_proc () at /home/bradh/gpac/bin/gcc/libgpac.so.12
#4  0x00007ffff74f4775 in RunThread () at /home/bradh/gpac/bin/gcc/libgpac.so.12
#5  0x00007ffff7097b5a in start_thread (arg=<optimised out>) at ./nptl/pthread_create.c:444
#6  0x00007ffff71285fc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

The repro is provided in your dropbox at https://www.mediafire.com/view/qdy6a2zis7cq0s2/encode_rgba_version1.heif/file

It compresses well, so also attaching as zip.
[encode_rgba_version1.zip](https://github.com/gpac/gpac/files/14402358/encode_rgba_version1.zip)

I believe the test file is valid, and uses version 1 of the uncompressed configuration box.
This doesn't happen with my rgb3 equivalent test case - that renders correctly.

**Comment by aureliendavid** [comment]
the file is showing as "Upload still in progress", maybe it didn't finish properly?

can you reupload it? (on the dropbox or elsewhere)

thanks

**Comment by bradh** [comment]
> the file is showing as "Upload still in progress", maybe it didn't finish properly?

Could be. It looked like it was fine, though maybe I didn't click through enough ads or something.

> can you reupload it? (on the dropbox or elsewhere)

Have added it to the original report.

**Comment by aureliendavid** [comment]
thanks for the file

it should be fixed with latest commit

can you recheck?

thanks

**Comment by bradh** [comment]
Works for me.
