### ISSUE TITLE
MP4Box -raws doesn't work on RTP track - "Filters not connected:"

### ISSUE THREAD

**Issue by foxhlchen** [gpac/gpac#2766]
Hi, I got this error when trying to run `MP4Box -raws 3 output.3gp` to extract sample on track 3 of my video file.

```
Filters not connected:
fout (dst=output_track3_$num%03d$:dynext) (idx=1)
writegen (frame) (idx=2)
reframer (SID=1#PID=3:exporter) (idx=3)
```

The message makes no sense to me. 

I build MP4Box myself on RHEL9 and I tried both master branch and latest release (tag v2.2.1). Both of them returned the same message.

The track 3 info of my video file.
```
# Track 3 Info - ID 3 - TimeScale 90000
Media Duration 00:00:15.041
Track is present in Root OD
Track flags: Enabled In Movie In Preview
Media Samples: 361 - CFR 24/sec
1 UDTA types:
        hnti:
Media Type: hint:rtp
        Streaming Hint Track for track ID 1
        RFC6381 Codec Parameters: rtp
        All samples are sync
        Max sample duration: 3750 / 90000
```

**Comment by foxhlchen** [comment]
I tried using v0.8.0. It worked

**Comment by jeanlf** [comment]
Indeed, now fixed on master. Thanks for the report
