### ISSUE TITLE
Problems with stream switching

### ISSUE THREAD

**Issue by diogocosta123** [gpac/gpac#277]
Hello!
I'm working on an altered version of mp4client player to play multiple streams of the same video content. A 3rd party app allows me to manually select the streams.
Everything works fine and as intended when I run it locally, but when I host the content on a server, the player automatically switches to the last stream in the list and locks on it. If I request a change, the player switches to the selected stream for a second and then switches back the previous stream:

![example](https://cloud.githubusercontent.com/assets/9872810/10427713/ca75e800-70e3-11e5-904a-f9be40556cfa.PNG)
I cannot find the reason for this. Do you know what might be causing the issue?

I have generated the content with mp4box and I have not found any issues with the MPD. I'm using node.js to generate the server.

**Comment by rbouqueau** [comment]
There is an option to disable quality switches: ```DASH:DisableSwitching=yes```

There is a documentation of the configuration file installed with GPAC (original file: https://github.com/gpac/gpac/blob/master/doc/configuration.html)

**Comment by diogocosta123** [comment]
Thank you! It's working!
