### ISSUE TITLE
video-audio sync question.

### ISSUE THREAD

**Issue by ohjiwoo123** [gpac/gpac#2774]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

I have a question video audio sync.  
when I try play hls-js, video-audio sync is  out of sync.  

My question is that is there possible to Performance improvement to make segment faster ? 
(Now I am collecting data in segments in 2 sec)   
when i make audio segments it takes about 1.97 seconds (from first audio data to callback),   
video takes 1.98 seconds (from first video data to callback).  
Could this have something to do with the out of sync?  
(Also I am trying to use compress mode using `gf_isom_enable_compression` when I mux the video, Is it good choice ?)  

Seconds question is   
when i use `gf_isom_fragment_add_sample` this function  
https://github.com/gpac/gpac/blob/96b474ec59b3490eed7a874b14f78ad4b3a9d2bd/src/isomedia/movie_fragments.c#L2979C1-L2980C113  
If I push the video I-frame for sample,  
do I set the argument redundant_coding = 0,  
otherwise, P-frame or B-frame, set redundant_coding = 1 ?

**Comment by jeanlf** [comment]
> Could this have something to do with the out of sync?

No, the out of sync comes likely from your the tfdt not being correct (see gf_isom_set_traf_base_media_decode_time)

> (Also I am trying to use compress mode using gf_isom_enable_compression when I mux the video, Is it good choice ?)

No don't use this, there is not a lot of support for compressed movie / movie fragment boxes

> do I set the argument redundant_coding = 0,

Always set it to 0  yes - setting a value if one would indicate a duplication of info (eg a repeat of a frame)

However you should set the sample deps flags using `gf_isom_fragment_set_sample_flags`  again with redundant set to 0 but `dependsOn` set to 2 for I-frames.
