### ISSUE TITLE
Cannot encrypt any video track with audio track, or audio track alone, playback never works.

### ISSUE THREAD

**Issue by MarianoFacundoArch** [gpac/gpac#2776]
There is no way I can encrypt an audio track and get it working, I am creating an .mp4 file with only an audio track on it, no video track, and 

Audio file:
https://github.com/gpac/gpac/assets/19694461/d44305ad-16cc-4974-a055-09479bb6e0bc

DRM Spec file
```
<?xml version="1.0" encoding="UTF-8"?>
<GPACDRM type="cenc">
  <DRMInfo type="pssh" version="0">
    <BS ID128="edef8ba979d64acea3c827dcd51d21ed"/>
    <BS data="0x08011210"/>
    <BS ID128="65ef3cf7c0194e39591b237300000000"/>
  </DRMInfo>
  <DRMInfo type="pssh" version="1">
    <BS ID128="1077efecc0b24d02ace33c1e52e2fb4b"/>
    <BS bits="32" value="1"/>
    <BS ID128="65ef3cf7c0194e39591b237300000000"/>
  </DRMInfo>
  <CrypTrack trackID="0" IsEncrypted="1" IV_size="16" first_IV="0x908e9dff71c68aa391501d11e0c1afca" saiSavedBox="senc">
    <key KID="0x65ef3cf7c0194e39591b237300000000" value="0xe87fb1c0a57028ef89138b42b8eb94fd"/>
  </CrypTrack>
</GPACDRM>
```

It creates an output, but it cannot be played.
I tried creating only an audio output with that file, and it is not working, obviously video+audio happens the same, only video only works for me.
Any clue?

**Comment by MarianoFacundoArch** [comment]
I confirm, it is not working anytime I encrypt the audio tracks, the encryption for the audiotrack itself is not working. When I encrypt video+audio content for example but leave the audio track unencrypted, it works.
It fails to encrypt an audiotrack the result cannot be decoded and played

**Comment by MarianoFacundoArch** [comment]
Tried everything, even manually fragmenting the input file for a second time with a tool. There is no way I can play an encrypted audio track, might there be a bug or am I doing anything wrong?

**Comment by rbouqueau** [comment]
It work here with your sample:

```
$ gpac -i audio.mp4 cecrypt:cfile=DRM.xml -o enc.mp4
```

then:

```
$ gpac --cfile=DRM.xml -play enc.mp4
```

will play the content.

**Comment by MarianoFacundoArch** [comment]
You are right!
The problem is with the safari itself, I will close this post. The only remaining bug that I found is the one that does not name the audio init segments properly.
