### ISSUE TITLE
Can't split MP4 files downloaded from Twitch Transport Stream files

### ISSUE THREAD

**Issue by superbonaci** [gpac/gpac#2784]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Download this Twitch video with [TwitchDownloaderCLI](https://github.com/lay295/TwitchDownloader):

```
TwitchDownloaderCLI videodownload -u 2065608792 -q best -o 2065608792.mp4
```

Try to split it

```
MP4Box -splitx 8130:9200 2065608792.mp4 -out mp4box.mp4
[MP4Mux] Error creating new tx3g sample description: Bad Parameter
Failed to connect filter reframer PID T3 to filter mp4mx: Bad Parameter
splitting: file 1 done
Split failed: Bad Parameter

	Error: Bad Parameter
```

2065608792.mp4 includes 4 chapters, I guess they should be adjusted relative to output file as well (in case it's not done already).
Here is the attachment of these 2 output files (samples):

```
TwitchDownloaderCLI videodownload -u 2065608792 -q 480p -e 16 -o 2065608792_0s_16s.mp4
MP4Box -splitx 8:12 2065608792_0s_16s.mp4 -out mp4box_clip.mp4
```
[2065608792_0s_16s.zip](https://github.com/gpac/gpac/files/14627207/2065608792_0s_16s.zip)

**Comment by jeanlf** [comment]
Indeed, the code was a bit too strict when remuxing broken text tracks. Thanks for the report !

This being said, the file announces `text:text` as media type, which is QT timed text, however the box structure looks like a tx3g text streams.

Chapters are already filtered out while spliting yes.

**Comment by superbonaci** [comment]
They are not broken text tracks, they are generated by Twitch.tv.

**Comment by jeanlf** [comment]
In the attached file, the text track is advertised as `text:text` (QT) tracks but are really `text:tx3g` (3GPP), so at least for this file this is broken IMHO.

**Comment by superbonaci** [comment]
It's probably broken because it's not cut by I-frame but at 16 seconds exactly. however if you download the entire file should be ok: https://www.twitch.tv/videos/2065608792

**Comment by jeanlf** [comment]
You are correct, the full video has a regular QT text track. And spliting works well on it.

**Comment by jeanlf** [comment]
MP4Box will not re-encode, it adjusts the split range to the closest I frame and inject edit lists in the resulting mp4. Under the hood, the [reframer](https://wiki.gpac.io/Filters/reframer/) filter is called, and the option`xround` can be used to select start range adjustment.

**Comment by superbonaci** [comment]
So I can understand, trimming from 8 to 12 seconds, will the output file have different duration than 4 seconds due to adjusting for I-frames, or will audio & video have both 4 exact seconds of duration and all those frames can be decoded?

Maybe it's been already asked and it's covered by the documentation.
