### ISSUE TITLE
gf_media_get_rfc_6381_codec_name() in gpac

### ISSUE THREAD

**Issue by doublex** [gpac/gpac#2785]
Not a bug, just a feature request:
`gf_media_get_rfc_6381_codec_name()` is excellent.
Maybe it would be possible to export the codec-name also with:
````
gpac -i  test.mp4 inspect:full
````

**Comment by jeanlf** [comment]
Yes, this was added some time ago in 0157a8dc81 but I didn't see this issue at the time.

**Comment by doublex** [comment]
You are right.
Sorry for the inconvenience.
