### ISSUE TITLE
Question ROUTE

### ISSUE THREAD

**Issue by j3dd4h** [gpac/gpac#2786]
I'm using below command to send a file using route.
gpac -i ./gpac.zip:mime=application/octet-string -o route://225.1.1.0:6000
Questions:
-How to set a limit the route mux rate?
-This command keep sending the file forever,  how to exit after send file 2x.
Thanks

**Comment by jeanlf** [comment]
> -How to set a limit the route mux rate?

You cannot specify the route mux rate, as it depends on the source media rate for DASH sessions. You can however specifiy  the carousel period (`ROUTECarousel` ) and upload time (`ROUTEUpload`) properties. For example, uploading the file in 1 second every 2 seconds:
`gpac -i ./gpac.zip:mime=application/octet-string:#ROUTECarousel=2000:#ROUTEUpload=1000 -o route://225.1.1.0:6000`

> -This command keep sending the file forever, how to exit after send file 2x.

You cannot exit after a given carousel period, but you can specify a run duration for the route muxer:
 `-o route://225.1.1.0:6000/:runfor=4000`
