### ISSUE TITLE
Add warnings when generating ROUTE sessions from VoD assets that can't work

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#2789]
I can't document it much but we've been able to generate (and capture) faulty sessions this way:
```
gpac -i EncB/manifest.mpd dashin:forward=file -o atsc:// -graph -netcap=dst=netcap.gpc
```

and replay with:
```
gpac -netcap=src=netcap.gpc -play atsc://::max_segs=10
```

The issue with VoD session is that the MPD is scheduled at the end of the session.

There were also questions on using ```:forward=file``` versus ```:forward=mani```. And also with requiring ```atsc://```.

There is an analysis from @touatily available on request.

**Comment by jeanlf** [comment]
Now fixed on master, including a warning if source is static
