### ISSUE TITLE
GPAC segfault, while trying to read info from .TS file

### ISSUE THREAD

**Issue by dukeh3** [gpac/gpac#279]
Hello I have found a strange bug in the latest version ( rev709-g5bf4a71-master ) in MP4Box. 

It segfaults on Linux when trying to get info from a .TS file. 

MP4Box -info -logs all@debug tmf_0_0.ts
[MPEG-2 TS] TS Packet 1 PID 0 CC 0 Encrypted 0
[MPEG-2 TS] Creating table 0 1
[MPEG-2 TS] TS Packet 2 PID 4096 CC 0 Encrypted 0
[MPEG-2 TS] Creating table 2 1
[MPEG-2 TS] PMT Found or updated
stream_type :27 
[MPEG-2 TS] Setting pes framing mode of PID 256 to 0
stream_type :15 
[MPEG-2 TS] Setting pes framing mode of PID 257 to 0
stream_type :21 
[MPEG-2 TS] Setting pes framing mode of PID 258 to 0
[MPEG-2 TS] Setting pes framing mode of PID 256 to 3
[MPEG-2 TS] Setting pes framing mode of PID 257 to 3
[MPEG-2 TS] Setting pes framing mode of PID 258 to 3
[MPEG-2 TS] TS Packet 3 PID 258 CC 0 Encrypted 0
[MPEG-2 TS] PID 258: Got PES packet len 238
[MPEG-2 TS] TS Packet 4 PID 258 CC 1 Encrypted 0
[MPEG-2 TS] PID 258: Adaptation Field found: Discontinuity 0 - RAP 0 - PCR: 0
[MPEG-2 TS] PID 258 Got PES header PTS 0
Segmentation fault

http://cdn.labs.h3.se/rene/gpac_problem_2/tmf_0_0.ts

**Comment by rbouqueau** [comment]
Hi René,
Could you test with the latest version and confirm it works for you?
Thanks

**Comment by dukeh3** [comment]
Yes it does :)
