### ISSUE TITLE
name tkID appends text not replace

### ISSUE THREAD

**Issue by LeeThompson** [gpac/gpac#2794]
I'm trying to remove the title of a track with `mp4box filename.mp4 -name 5=""` but that just keeps the existing title.

If I try to replace it with something else with `mp4box filename.mp4 -name 5="New Text"` I get "`New Text / Old Text`"

`MP4Box - GPAC version 2.2.1-rev0-gb34e3851-release-2.2`

Very frustrating.

**UPDATE:** There were apparently some UDTA's set, perhaps by HandBrake.   I removed those and it worked as expected, still maybe some kind of overriding option wouldn't hurt.   I would've never found this without doing `-info 5`.   (And even then the `-udta` documentation could've been better since I'm not even sure what they are.)

**Comment by jeanlf** [comment]
`-name` sets the track handler UTF8 string (this is often used by players to figure out a track name). It does not deal with udta (UserDataBox) at all, I'll try updating the wiki on that matter. Thanks for the update.
