### ISSUE TITLE
Where can I find fragments getting from the sever via mpd?

### ISSUE THREAD

**Issue by wkdwldnd7487** [gpac/gpac#2797]
I want to know if the fragments are saving in buffer. And which file the buffer exist.

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

**Comment by jeanlf** [comment]
Please file a detailed bug report, including command lines and use cases, if you want us to help.

**Comment by wkdwldnd7487** [comment]
Thank you for reply. I'm now using visual studio 2022, and I built the gpac with v143 , windows SDK 10. When i'm trying to debug the gpac_public/bin/msvc14/gpac.sln, it shows Lnk1104 error with nghttp2.lib and the others.  I add the command argument on visual studio gpac -gui https://dash.akamaized.net/akamai/bbb_30fps/bbb_30fps.mpd.
