### ISSUE TITLE
gpac windows 64 LNK 1104 error.

### ISSUE THREAD

**Issue by wkdwldnd7487** [gpac/gpac#2798]
I'm now using visual studio 2022, and I built the gpac with v143 , windows SDK 10. When i'm trying to debug the gpac_public/build/msvc14/gpac.sln, it shows Lnk1104 error with nghttp2.lib and the others. I add the command argument on visual studio gpac -gui https://dash.akamaized.net/akamai/bbb_30fps/bbb_30fps.mpd.

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

**Comment by jeanlf** [comment]
You need to either compile all extra libs, cf the [wiki](http://wiki.gpac.io/Build/build/GPAC-Build-Guide-for-Windows/), or disable unavailable libraries in gpac/include/gpac/configuration.h (for example, comment `#define GPAC_HAS_HTTP2` if you don't have nghttp2)
