### ISSUE TITLE
wasm build and deployment are broken 

### ISSUE THREAD

**Issue by nlsdvl** [gpac/gpac#2799]
this happened when switching to ffmpeg 7, see the [buildbot](https://buildbot.gpac.io/#/builders/27/builds/516).

as a side effect the automatic deployment is also broken.

the broken build shouldn't be uploaded to [wasmth.gpac.io](https://wasmth.gpac.io).

cc @rbouqueau

**Comment by jeanlf** [comment]
now fixed
