### ISSUE TITLE
"Timescale 600" used regardless of content and options

### ISSUE THREAD

**Issue by lvml** [gpac/gpac#28]
Hi,

I try to prepare an .MP4 file such that my camera (Panasonic LX100) is willing to replay it.
As an supposedly easy first attempt I tried to re-mux an existing video clip the camera recorded using MP4Box, experimenting with options such that the output file would not differ from the input file.

The options that yield the "least visible difference" for the output of `MP4Box -info` for me are:
```
MP4Box -brand mp42:1 -no-iod -no-sys -add P1000457.MP4 P1000999.MP4
```
(You can download the (3.5 MB) sample video file here: http://filebin.ca/1knlOxMESIbK/P1000457.MP4 )

Unluckily, the resulting file P1000999.MP4 still shows at least one significant difference:
```
 * Movie Info *
-       Timescale 90000 - Duration 00:00:02.880
+       Timescale 600 - Duration 00:00:02.880
```
... and this may well be the reason why the camera is unwilling to replay it.

I've tried all sorts of options, including the :timescale=... and :rescale=... syntax, but nothing seems to keep MP4Box from using "Timescale 600" in the output file, as displayed under "* Movie Info *".

Is there some possibility to avoid this and use the original Timescale 90000? Or is this just a bug in MP4Box?

For reference, here's the full output of "-info" for the input file:
```
MP4Box -info P1000457.MP4 
* Movie Info *
        Timescale 90000 - Duration 00:00:02.880
        2 track(s)
        Fragmented File: no
        File suitable for progressive download (moov before mdat)
        File Brand mp42 - version 1
        Created: GMT Tue Dec 16 06:37:43 2014
        Modified: GMT Tue Dec 16 06:37:43 2014

File has no MPEG4 IOD/OD

Track # 1 Info - TrackID 1 - TimeScale 90000 - Media Duration 00:00:02.880
Track has 1 edit lists: track duration is 00:00:02.880
Media Info: Language "und (und)" - Type "vide:avc1" - 72 samples
Visual Track layout: x=0 y=0 width=1280 height=720
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x21
AVC/H264 Video - Visual Size 1280 x 720
        AVC Info: 1 SPS - 1 PPS - Profile High @ Level 3.1
        NAL Unit length bits: 32
        Pixel Aspect Ratio 1:1 - Indicated track size 1280 x 720
        Chroma format 1 - Luma bit depth 8 - chroma bit depth 8
Self-synchronized

Track # 2 Info - TrackID 2 - TimeScale 48000 - Media Duration 00:00:02.922
Track has 1 edit lists: track duration is 00:00:02.880
Media Info: Language "und (und)" - Type "soun:mp4a" - 137 samples
MPEG-4 Config: Audio Stream - ObjectTypeIndication 0x40
MPEG-4 Audio AAC LC - 2 Channel(s) - SampleRate 48000
Synchronized on stream 1
```

**Comment by jeanlf** [comment]
svn Rev 5577 now has -timescale to override movie timescale, and uses source movie timescale when no track is present in dest file.

**Comment by lvml** [comment]
Thanks a lot, your change leveled the differences in TimeScale between the original and the re-muxed file.

There's another difference visible when using -dts to dump sample information, will open a seperate issue on this.
