### ISSUE TITLE
Link Error when compiling on Windows 7

### ISSUE THREAD

**Issue by fcsteagu** [gpac/gpac#280]
Hello,

I was successfully compiling GPAC on Windows 7 so far but today I pulled the changes from the last 2 weeks and I get a linking error:

`
1>------ Rebuild All started: Project: libgpac_dll, Configuration: Debug Win32 ------
1>  export.cpp
1>libgpac_dll.obj : warning LNK4075: ignoring '/EDITANDCONTINUE' due to '/SAFESEH' specification
1>     Creating library ../../bin/Win32/Debug/libgpac.lib and object ../../bin/Win32/Debug/libgpac.exp
1>libgpac_static.lib(meta.obj) : error LNK2019: unresolved external symbol _ispe_New referenced in function _meta_process_image_properties
1>libgpac_static.lib(box_funcs.obj) : error LNK2001: unresolved external symbol _ispe_New
1>libgpac_static.lib(meta.obj) : error LNK2019: unresolved external symbol _rloc_New referenced in function _meta_process_image_properties
1>libgpac_static.lib(box_funcs.obj) : error LNK2001: unresolved external symbol _rloc_New
1>libgpac_static.lib(meta.obj) : error LNK2019: unresolved external symbol _irot_New referenced in function _meta_process_image_properties
1>libgpac_static.lib(box_funcs.obj) : error LNK2001: unresolved external symbol _irot_New
1>libgpac_static.lib(meta.obj) : error LNK2019: unresolved external symbol _ipco_New referenced in function _meta_process_image_properties
1>libgpac_static.lib(box_funcs.obj) : error LNK2001: unresolved external symbol _ipco_New
1>libgpac_static.lib(meta.obj) : error LNK2019: unresolved external symbol _iprp_New referenced in function _meta_process_image_properties
1>libgpac_static.lib(box_funcs.obj) : error LNK2001: unresolved external symbol _iprp_New
1>libgpac_static.lib(meta.obj) : error LNK2019: unresolved external symbol _ipma_New referenced in function _meta_process_image_properties
1>libgpac_static.lib(box_funcs.obj) : error LNK2001: unresolved external symbol _ipma_New
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _ispe_del referenced in function _gf_isom_box_del
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _ispe_Read referenced in function _gf_isom_box_read
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _ispe_Write referenced in function _gf_isom_box_write_listing
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _ispe_Size referenced in function _gf_isom_box_size_listing
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _colr_New referenced in function _gf_isom_box_new
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _colr_del referenced in function _gf_isom_box_del
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _colr_Read referenced in function _gf_isom_box_read
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _colr_Write referenced in function _gf_isom_box_write_listing
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _colr_Size referenced in function _gf_isom_box_size_listing
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _pixi_New referenced in function _gf_isom_box_new
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _pixi_del referenced in function _gf_isom_box_del
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _pixi_Read referenced in function _gf_isom_box_read
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _pixi_Write referenced in function _gf_isom_box_write_listing
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _pixi_Size referenced in function _gf_isom_box_size_listing
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _rloc_del referenced in function _gf_isom_box_del
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _rloc_Read referenced in function _gf_isom_box_read
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _rloc_Write referenced in function _gf_isom_box_write_listing
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _rloc_Size referenced in function _gf_isom_box_size_listing
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _irot_del referenced in function _gf_isom_box_del
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _irot_Read referenced in function _gf_isom_box_read
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _irot_Write referenced in function _gf_isom_box_write_listing
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _irot_Size referenced in function _gf_isom_box_size_listing
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _ipco_del referenced in function _gf_isom_box_del
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _ipco_Read referenced in function _gf_isom_box_read
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _ipco_Write referenced in function _gf_isom_box_write_listing
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _ipco_Size referenced in function _gf_isom_box_size_listing
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _iprp_del referenced in function _gf_isom_box_del
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _iprp_Read referenced in function _gf_isom_box_read
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _iprp_Write referenced in function _gf_isom_box_write_listing
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _iprp_Size referenced in function _gf_isom_box_size_listing
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _ipma_del referenced in function _gf_isom_box_del
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _ipma_Read referenced in function _gf_isom_box_read
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _ipma_Write referenced in function _gf_isom_box_write_listing
1>libgpac_static.lib(box_funcs.obj) : error LNK2019: unresolved external symbol _ipma_Size referenced in function _gf_isom_box_size_listing
1>../../bin/Win32\Debug/libgpac.dll : fatal error LNK1120: 40 unresolved externals
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
`
I have recompiled all the modules and libgac. The only error I get is when I compile libgpac_dll.

**Comment by fcsteagu** [comment]
fixed it. I had to update the project file of VS (libgpac.vcxproj) to include iff.c

**Comment by rbouqueau** [comment]
In which directory did you take your SLN? I'd like to make sure I understand what the issue was. Thanks

**Comment by fcsteagu** [comment]
Actually I had to modify *libgpac.vcxproj* from gpac/build/*msvc11* because
I'm using VS2012. The project file for VS2010 already had the new file
added.

    <ClCompile Include="..\..\src\isomedia\iff.c" />

Best regards

**Comment by rbouqueau** [comment]
Thanks

@cconcolato Maybe we should remove the vc11 project files if they are not maintained?
