### ISSUE TITLE
MPEG-DASH manifest size grows like avalanche

### ISSUE THREAD

**Issue by alex-rsk** [gpac/gpac#2801]
GPAC version 2.0-rev2.0.0+dfsg1-2

We are making stream, consequently feeding MP4Box with new video-fragments
```
MP4Box -dash 10000 -dash-ctx ./stream/context.txt  -rap   -profile dashavc264:live  \
-mpd-refresh 6 -dynamic -bs-switching no \
 -segment-timeline -url-template -time-shift 5 \
./chunks/segment_0001.mp4#video ./chunks/segment_0001.mp4#audio -out ./stream/live.mpd 
```
Everything is working good, except that fact, that MPD manifest grows very quickly.
Hour after it weighs 9 megabytes, which causes video freeze.
On the other hand, when I use Nginx to stream MPD, it keeps manifest size about 25 kilobytes.

Currently I don't see any workaround, except cleaning  it from time to time. But, perhaps, there is some option to keep size in reasonable borders?

**Comment by rbouqueau** [comment]
Your command-line asks for 10s segments, a MPD refresh every 6s and a time-shift buffer depth of 5s. The units may not be the one you expected.

**Comment by alex-rsk** [comment]
Thank you for response.
I have tested with latest GPAC, and nothing changed.

Then I thoroughly checked my command-line params, and it seems I found the reason. 

It seams it was a bug, when I set time-shift to the same value as dash (i.e. microseconds instead of seconds).

Also I have aligned mpd-refresh and dash.

I started the stream and left it for 8 hours.

After that, context.txt was about 100 kbytes, and manifest.mpd weighed 44 kbytes.

I tend to think, that problem is solved now.  We are continue to observe manifest size, though.

Thank you very much!

**Comment by alex-rsk** [comment]
Just found, that, if I rename new input segment to the same name, e.g. "input.mp4" - then it generates small manifests and it doesn't grow.
But this manifest not works in DASH IF player.

Any help would be appreciated

**Comment by alex-rsk** [comment]
Managed it to work playlist through gpac:
```
gpac -i playlist.m3u -o live.mpd:profile=live:dmode=dynamic:sreg:stl
```
Is there option in ```MP4Box``` that makes "sreg" like in ```gpac```?

**Comment by jeanlf** [comment]
> Is there option in MP4Box that makes "sreg" like in gpac?

Yes, just set `sreg` on your target MPD file, eg
MP4Box -dash N [srcs] -dynamic -out live.mpd:sreg

**Comment by alex-rsk** [comment]
This worked out partially.
``` 
MP4Box -dash 10000 -dash-ctx ./stream/context.txt -rap -profile live -mpd-refresh 5 -bs-switching no -segment-timeline -url-template -min-buffer 1000 -time-shift 1800 input.mp4#video -dynamic -out ./stream/stream.mpd:sreg
```
It works!  But only with video track. 

If I add sound track:
```
MP4Box -dash 10000 -dash-ctx ./stream/context.txt -rap -profile live -mpd-refresh 5 -bs-switching no -segment-timeline -url-template -min-buffer 1000 -time-shift 1800 
input.mp4#audio  input.mp4#video -dynamic -out ./stream/stream.mpd:sreg

```

Then it doesn't works.  It seems that there's some bug, b.c. `gpac` streams both tracks

**Comment by alex-rsk** [comment]
`gpac` with dynamic playlist also doesn't work properly. Honestly , I have tested this tool during this year in different flavous and nothing works properly, it seems it is time to move `ffmpeg`. (

**Comment by rbouqueau** [comment]
I can understand how frustrating unresolved issues can be. Please continue to open as many issues as needed.

As you can notice GPAC has only 36 opened issues. It shows how committed we are to solving issues when you compare with other projects.

GPAC is run by volunteers during their free time. We just lack free time, which happens. Either be patient or look for professional services (https://motionspell.com/gpac-licensing/) if that's urgent.

**Comment by alex-rsk** [comment]
Thank you guys for your work, anyways, it is an impressive work.

Its's pitiful that it doesn't suits my needs.

**Comment by jeanlf** [comment]
We had a bug in the context reload of the dasher resulting in new periods being always created with changing filenames, resulting in forever growing manifest (one period per call...) - now fixed.

You will however need to specify the representation ID (and optionally period ID for multi-period) of your input when changing file names:
```
MP4Box .... src1#video:id=vid
MP4Box .... src2#video:id=vid
```

I updated the dasher filter help to reflect this.

Thanks for the report and patience !

> gpac with dynamic playlist also doesn't work properly.

Could you please create an issue for this (context and command line) if it still applies ?
