### ISSUE TITLE
MP4box -split issue, last part is broken, frozen black frame

### ISSUE THREAD

**Issue by avtor2** [gpac/gpac#2806]
I couldn't find any similar issues. I'm using the latest version of GPAC. The duration of my video file is 38 seconds. I want to split it into 15-second parts. However, the last file is always broken: there is a frozen black frame for 5 seconds and after that 3 seconds normal video. But the audio is fine.

Here's the command I'm using:
`MP4Box -split 15 1a088153e.mp4`

[Input file](https://www.dropbox.com/scl/fi/yjwik9i4r84ghkf8w5iyp/1a088153e.mp4?rlkey=w8f48btopfql485pg4mqsa7px&dl=0).
Output [video parts](https://www.dropbox.com/scl/fi/sfe0woor4b3f1jzo6p5pd/1a088153e.tar?rlkey=ddsisttw1l5hl88x9tjn8o5jo&dl=0).

Other videos have different durations, but I always need the segments to be less than 15 seconds. How can I achieve this?

**Comment by jeanlf** [comment]
fixed, thanks for the report and test files.
