### ISSUE TITLE
Better documentation (HOWTO?) of ff* wrappers in GPAC

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#2813]
GPAC leverages FFmpeg libraries. However there is:
- No documentation (e.g. HOWTO) page explaining how to leverage FFmpeg's capabilities from GPAC.
- The option parsing with ```:gpac:``` or ```::``` (to force options to be parsed all at once) or finding custom names (e.g. ``avfoundation``` or ```ffmt=```) need to be documented.

**Comment by jeanlf** [comment]
> No documentation (e.g. HOWTO) page explaining how to leverage FFmpeg's capabilities from GPAC.

we have a specific section in the one-liner, if not enough add an issue in the wiki repo


> The option parsing with :gpac: or :: (to force options to be parsed all at once) or finding custom names (e.g. ``avfoundation or ffmt=```) need to be documented.

the generic escape mechanism is documented in http://wiki.gpac.io/Filters/filters_general/#specifying-encoders-and-decoders, the URL escaping in http://wiki.gpac.io/Filters/filters_general/#generic-declaration

The only specific case which almost always require escaping is ffavf.f option, and this is documented here:
http://wiki.gpac.io/Filters/ffavf/#declaring-a-filter

**Comment by rbouqueau** [comment]
I propose that someone, not you, writes something. Is it an issue to leave it here? We could tag some issues as 'documentation' for instance?

**Comment by jeanlf** [comment]
since we have a repo for the wiki I'd rather move doc issues on the wiki

**Comment by rbouqueau** [comment]
Right. Done.
