### ISSUE TITLE
Fresh Ubuntu/Linux install nightly fails

### ISSUE THREAD

**Issue by rafaelcaricio** [gpac/gpac#2814]
I downloaded the latest nightly build of the `.deb` package and installed in a fresh Linux machine. When trying to list all available filters I get an JS stacktrace error.

```
gpac -h filters
Listing 127 supported filters:
inspect: Inspect packets
probe: Probe source
compositor: Compositor
mp4dmx: ISOBMFF/QT demultiplexer
bifsdec: MPEG-4 BIFS decoder
odfdec: MPEG-4 OD decoder
fin: File input
btplay: BT/XMT/X3D loader
httpin: HTTP input
svgplay: SVG loader
rfimg: JPG/J2K/PNG/BMP reframer
imgdec: PNG/JPG decoder
rfadts: ADTS reframer
rflatm: LATM reframer
rfmp3: MP3 reframer
faad: FAAD decoder
maddec: MAD decoder
j2kdec: OpenJPEG2000 decoder
rfac3: AC3 reframer
a52dec: A52 decoder
rfamr: AMR/EVRC reframer
oggdmx: OGG demultiplexer
vorbisdec: Vorbis decoder
theoradec: Theora decoder
m2tsdmx: MPEG-2 TS demultiplexer
sockin: UDP/TCP input
osvcdec: OpenSVC decoder
lsrdec: MPEG-4 LASeR decoder
safdmx: SAF demultiplexer
dashin: MPEG-DASH and HLS client
cdcrypt: CENC decryptor
cecrypt: CENC encryptor
mp4mx: ISOBMFF/QT multiplexer
rfqcp: QCP reframer
rfh263: H263 reframer
rfmpgvid: M1V/M2V/M4V reframer
nhntr: NHNT reader
nhmlr: NHML reader
rfnalu: AVC/HEVC reframer
m2psdmx: MPEG PS demultiplexer
avidmx: AVI demultiplexer
txtin: Subtitle loader
ttxtdec: TTXT/TX3G decoder
vttdec: WebVTT decoder
ttmldec: TTML decoder
rtpin: RTP/RTSP/SDP input
fout: File output
uflatm: Raw AAC to LATM writer
ufadts: ADTS writer
ufmhas: MHAS writer
reframer: Media Reframer
writegen: Stream to file
ufnalu: AVC/HEVC to AnnexB writer
writeqcp: QCP writer
ufvtt: WebVTT unframer
nhntw: NHNT writer
nhmlw: NHML writer
vobsubdmx: VobSub parser
avimx: AVI multiplexer
aout: Audio output
ufm4v: M4V writer
ufvc1: VC1 writer
resample: Audio resampler
vout: Video output
vcrop: Video crop
vflip: Video flip
rfrawvid: RAW video reframer
rfpcm: PCM reframer
jpgenc: JPG encoder
pngenc: PNG encoder
rewind: Audio/Video rewinder
flist: Sources concatenator
m2tsmx: MPEG-2 TS multiplexer
dasher: DASH and HLS segmenter
tileagg: HEVC tile aggregator
tilesplit: HEVC tile bitstream splitter
pin: pipe input
pout: pipe output
gsfmx: GSF Multiplexer
gsfdmx: GSF demultiplexer
sockout: UDP/TCP output
rfav1: AV1/IVF/VP9 reframer
ufobu: IVF/OBU/annexB writer
routein: ROUTE input
rtpout: RTP Streamer
rtspout: RTSP Server
httpout: HTTP Server
hevcsplit: HEVC tile splitter
hevcmerge: HEVC Tile merger
rfflac: FLAC reframer
rfmhas: MPEH-H Audio Stream reframer
rfprores: ProRes reframer
tssplit: MPEG Transport Stream splitter
bsrw: Compressed bitstream rewriter
bssplit: Compressed layered bitstream splitter
bsagg: Compressed layered bitstream aggregator
ufttxt: TX3G unframer
tx3g2srt: TX3G to SRT
tx3g2vtt: TX3G to WebVTT
tx3g2ttml: TX3G to TTML
vtt2tx3g: WebVTT to TX3G
rfsrt: SRT reframer
ttml2vtt: TTML to WebVTT
ttml2srt: TTML to SRT
mpeghdec: MPEG-H Audio decoder
ffdmx: FFMPEG demultiplexer
ffdmxpid: FFMPEG demultiplexer
ffdec: FFMPEG decoder
ffavin: FFMPEG AV Capture
ffsws: FFMPEG video rescaler
ffenc: FFMPEG encoder
ffmx: FFMPEG multiplexer
ffavf: FFMPEG AVFilter
jsf: JavaScript filter
routeout: ROUTE output
rftruehd: TrueHD reframer
cryptin: CryptFile input
cryptout: CryptFile output
restamp: Packet timestamp rewriter
oggmx: OGG multiplexer
unframer: Stream unframer
writeuf: Stream to unframed format
uncvdec: UNCV decoder
ghidmx: GHI demultiplexer
evgs: EVG video rescaler
ccdec: Closed-Caption decoder
ohevcdec: OpenHEVC decoder
glpush: GPU texture uploader
uncvg: Uncompressed Video File Format Generator Utility
avmix: Audio Video Mixer
thumbs: Thumbnail collection generator
[FreeType] Default fonts not valid, rescanning font directories /usr/share/fonts/
[avgen] Error initializing filter
[avgen] Error: Fonts not found (first was SANS) and no default font available!
Check your GPAC configuration, or use `-rescan-fonts` to refresh font directory.

    at put_image (/usr/share/gpac/scripts/jsf/avgen/init.js:358)
    at <anonymous> (/usr/share/gpac/scripts/jsf/avgen/init.js:247)

Filter avgen failed to setup: Bad Parameter
```

Version: `2.5-DEV-rev17-g8d7cac0b-master`

**Comment by aureliendavid** [comment]
Hi, 

I'm not reproducing it on a clean ubuntu image. 

However it seems the issue has come up before:  https://github.com/gpac/gpac/issues/1725 

You can try running: 

```
rm -rf ~/.gpac
gpac
gpac -rescan-fonts
gpac -h filters
```

**Comment by rafaelcaricio** [comment]
I am using `Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-101-generic x86_64)`.

When I run the rescan fonts command I actually get an error:
```
$ gpac -rescan-fonts
Nothing to do, check usage "gpac -h"
gpac - GPAC command line filter engine - version 2.5-DEV-rev17-g8d7cac0b-master
(c) 2000-2024 Telecom Paris distributed under LGPL v2.1+ - https://gpac.io

Please cite our work in your research:
        GPAC Filters: https://doi.org/10.1145/3339825.3394929
        GPAC: https://doi.org/10.1145/1291233.1291452

session error: Bad Parameter
```

**Comment by aureliendavid** [comment]
this error is "normal" (because we're not supposed to run rescan-fonts on its own, my bad)

but it you run the commands in my previous post, do you still have the original error on `gpac -h filters`?

**Comment by rafaelcaricio** [comment]
Yes, the error persists even after running all those commands in the order you mentioned.

**Comment by rafaelcaricio** [comment]
The machine I am running those commands does not have a window manager. Might be related?

**Comment by aureliendavid** [comment]
Hm, I've tried with a fresh docker image (the official ubuntu:22.04 one, which is pretty minimal and doesn't have a window manager), and with a fresh full vm with desktop environment, and I didn't get the error in any of these cases. 

It has something to do with the fonts engine but I'm not sure what. 

Can you post the contents of your `~/.gpac/GPAC.cfg`? 
(and what command line did you use to install the deb package?) 

Also the error might only impact the avgen filter (maybe others who need fonts), but the rest of gpac should work fine. If you installed gpac for a specific use case you can still try to run it to see if it works or if you get a more specific error. 

Sorry for the vague answers but without reproducing it's hard to debug.

**Comment by aureliendavid** [comment]
Hello, 

Sorry for the delayed response (I was on leave). 

Can you maybe try again with the latest deb package and installing with apt to handle dependencies. 

Something like 

```sh
sudo apt remove gpac
sudo apt purge gpac
wget "https://download.tsi.telecom-paristech.fr/gpac/new_builds/gpac_latest_head_linux64.deb"
apt -f install ./gpac_latest_head_linux64.deb
gpac -hx filters
```

If this is not working can you tell me more about how you installed the fresh ubuntu (any particular options/versions) and the machine so I can try to test a similar set up?

thanks

**Comment by rafaelcaricio** [comment]
Still the same problem.

Machine details:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```

Linux version:
```
$ uname -srm
Linux 5.15.0-101-generic x86_64
```

Honestly, I don't know how the Ubuntu system was installed. I hope this info can help.

**Comment by aureliendavid** [comment]
I'm a bit stumped I have to admit. 

Did you install gpac for a specific use case? Do you get any errors when trying it? The error on the help command should only affect the [avgen](https://wiki.gpac.io/Filters/avgen) filter so it might no affect use cases that don't use the avgen filter. So maybe the error can just be ignored, or other errors might give some more clues. 

Someone in the previous linked above also indicated that they just deleted  `/usr/share/gpac/scripts/jsf/avgen` since they didn't use it.

**Comment by rafaelcaricio** [comment]
That is interesting, indeed. It does not impact my use case. I am raising this issue here as it is not expected. If I find other problems, I will report them. Thanks

**Comment by jeanlf** [comment]
No clue why this happened, but I prevented avgen to load fonts when loaded for doc only. This should avoid this warning.

**Comment by rafaelcaricio** [comment]
@jeanlf I imagine if I download the latest build it will have this fix?

**Comment by jeanlf** [comment]
yes

**Comment by aureliendavid** [comment]
Hello again, 

I think this has been more reliably fixed in the latest master, see https://github.com/gpac/gpac/issues/2867#issuecomment-2158637838 for more details.
