### ISSUE TITLE
GPAC 2.4 and 2.5-dev does not open in Mac Sonoma

### ISSUE THREAD

**Issue by simongcc** [gpac/gpac#2816]
I am using mac package to install
macOS 14.4.1 Sonoma / M1

I have just downloaded GPAC 2.5-dev a few days ago and tried to install.
After installation, I double click to start the application.
The application does not open.
I have tried version back to 2.4. Still the same.
Before install 2.4 and 2.5-dev, there was an older one, I have forgotten the version number but it did open.

See what else information you need to know for troubleshooting.

Tried but of no positive effect:
2.4, 2.5-dev version
reinstalled the Rosetta 2

**Comment by aureliendavid** [comment]
Hi, 

I'm able to run the latest installer and app on a sonoma vm, but it's not an M1 so maybe there are specific issues on the new architecture. 

How does the app fail for you? Does it hang, or is there an error message, on does it just not do anything?

Can you try running in a terminal: 

```
which gpac
rm -rf ~/.gpac
gpac
gpac -gui -logs=all@debug
```

and post the results here?

thanks

**Comment by simongcc** [comment]
Yes, the GPAC is compiled as Intel-based.
When I click to open the App, an normal app will jump and start. It did jump within 0.5s and disappear and nothing happen.
No crash message, no compliant, no freezing, no clues.

**Comment by aureliendavid** [comment]
can you try running the commands in my previous post in a terminal?

also if you're up to it you can try building gpac from source by following the guide at https://wiki.gpac.io/Build/build/GPAC-Build-Guide-for-OSX/

**Comment by simongcc** [comment]
`which gpac`
/Applications/GPAC.app/Contents/MacOS/gpac

`rm -rf ~/.gpac`

`gpac`
[core] Creating default credential key in /Users/someone/.gpac/creds.key, use -cred=PATH/TO_FILE to overwrite
Refreshing all options registry, this may take some time ... done
Nothing to do, check usage "gpac -h"
gpac - GPAC command line filter engine - version 2.5-DEV-rev17-g8d7cac0b-master
(c) 2000-2024 Telecom Paris distributed under LGPL v2.1+ - https://gpac.io

Please cite our work in your research:
	GPAC Filters: https://doi.org/10.1145/3339825.3394929
	GPAC: https://doi.org/10.1145/1291233.1291452

`gpac -gui -logs=all@debug`
It is now opening normally.
Thanks for your suggestion.
