### ISSUE TITLE
How to  transcoding livestream multiple resulation 

### ISSUE THREAD

**Issue by mdsohelmia** [gpac/gpac#2823]
I run this command.

```bash
 gpac -i rtmp://localhost:1935/live @ c=avc:b=4m @@ c=avc:b=2m @@ ffsws:osize=1280x720 @ c=avc:b=1m @1 c=avc:b=500k @ @1 @3 @4 -o live/index.m3u8:segdur=2:dmode=dynamic:profile=live:muxtype=ts
```
I get output this like.
<img width="1142" alt="image" src="https://github.com/gpac/gpac/assets/40440531/841fc742-fe21-4548-a44a-64f950d37b54">

I want to output look likes
<img width="1128" alt="image" src="https://github.com/gpac/gpac/assets/40440531/ceb509fe-a49b-4354-8511-67e0b7a7544c">
can you anyone help build command

**Comment by rbouqueau** [comment]
Use identifiers instead, it will make your life easier :). Assuming that your source is already in h=1080 resolution :
```
gpac -i rtmp://localhost:1935/live @@ c=avc:b=5055k:FID=S5M @@ ffsws:osize=1280x720 @ c=avc:b=3405k:FID=S3M @@ ffsws:osize=960x540 @ c=avc:b=2305k:FID=S2M -o live/index.m3u8:segdur=2:dmode=dynamic:profile=live:muxtype=ts:SID=S2M,S3M,S5M
```

**Comment by mdsohelmia** [comment]
@rbouqueau  Thanks
