### ISSUE TITLE
Dash player workflow

### ISSUE THREAD

**Issue by wkdwldnd7487** [gpac/gpac#2824]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [O] I looked for a similar issue and couldn't find any.
- [O] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

Hi, I was wondering how dash works inside gpac when I play videos on gpac-gui through DASH.
Is the workflow I drew the right flow?
![2](https://github.com/gpac/gpac/assets/56058407/83b2cfcd-b633-4b5e-81a7-3df8fd8d1292)

**Comment by rbouqueau** [comment]
That's a generic drawing.

If you want to know which GPAC filters are instantiated, run your command-line with the ```-graph``` option. This will display the filters being actually loaded. (You can also monitor these filters dynamically by adding ```-r```).

If you want to know which processing and decisions happen, activate the logs with ```-logs=dash@info``` (or more verbose ```-logs=dash@debug```).

We have recently updated our documentation: https://wiki.gpac.io/. Feedback welcome.

If  you still don't have the answer to your question let's continue this discussion here.

**Comment by jeanlf** [comment]
You need to add a feedback loop from the download part ("get segment" in your diagram) and from "buffer" to the "select representation".
