### ISSUE TITLE
ATSC 3.0 DASH with ROUTE 

### ISSUE THREAD

**Issue by manavdeep** [gpac/gpac#2825]
I am trying to use GPAC for transferring DASH files over ROUTE protocol as per ATSC 3.0 standard. Following documentation from the GPAC wiki shows a basic howto guide.
https://wiki.gpac.io/Howtos/route/
On that basis of above howto I am doing the following::
1. I have a directory with correct dash manifest and audio/video segment files. There i am issuing the following command:
`   gpac -i index.mpd dashin:forward=file -o route://225.1.1.0:6000`
   
2. and then I am trying to play it using the following command:
`  gpac -play route://225.1.1.0:6000`

Error:
`[Socket] Asked to set socket receive buffer size to 524288 but system used 425984
[AudioOut] No audio output modules found, cannot load audio output
Filter aout failed to setup: I/O Error
Failed to load filter "aout": I/O Error
session error: I/O Error
Filters not connected:
routein (src=route://225.1.1.0:6000) (idx=1)
No filter chain found for PID PID1 in filter routein to any loaded filters - NOT CONNECTED`

3. Also I tried to do the following and then play udp stream in VLC:
  `gpac -i route://225.1.1.0:6000/ -o udp://225.1.1.10:1234/:ext=ts`
  
  But none of them seem to be playing anything at all.

**Comment by rbouqueau** [comment]
If you use the sample from the tutorial, does it work? ```gpac -i https://akamaibroadcasteruseast.akamaized.net/cmaf/live/657078/akasource/out.mpd dashin:forward=file -o route://225.1.1.0:6000```

**Comment by manavdeep** [comment]
No, same issue. But i am behind a proxy so i figured that URL anyways might not be reachable. Also the index.mpd which i am using is valid mpd file. I can play it in VLC.

**Comment by rbouqueau** [comment]
Definitely you have a network issue. Can you read udp://225.1.1.0:6000 at all?

Secondary issues:
1. You need to fix your GPAC install to fix the "[AudioOut] No audio output modules found" issue. [Instructions](https://wiki.gpac.io/Build/Build-Introduction/).
2. To test if GPAC supports your MPD, I would try ```gpac -play index.mpd``` (or alt. ```gpac -r -i index.mpd reframer:rt=on -o null" and read if indices seem to increment).

**Comment by manavdeep** [comment]
So i connected to a network without proxy and I am getting this:
![Screenshot from 2024-05-07 15-08-08](https://github.com/gpac/gpac/assets/3747933/4d670e35-04d9-4f84-addb-89d06292661a)

**Comment by manavdeep** [comment]
Hey Hi.
I just solved it. Its working for me now. 2 things helped:
1. As you pointed out missing audio libraries. In one system it was working, another it was not. So i re-built the package.
2. I was able to understand the error messages in detail with time. so i cud debug step by step.

I am marking it solved.
> Definitely you have a network issue. Can you read udp://225.1.1.0:6000 at all?
> 
> Secondary issues:
> 
>     1. You need to fix your GPAC install to fix the "[AudioOut] No audio output modules found" issue. [Instructions](https://wiki.gpac.io/Build/Build-Introduction/).
> 
>     2. To test if GPAC supports your MPD, I would try `gpac -play index.mpd` (or alt. ```gpac -r -i index.mpd reframer:rt=on -o null" and read if indices seem to increment).
