### ISSUE TITLE
[MP4Mux] Session aborted before writing to file, use fragmented storage mode to record session

### ISSUE THREAD

**Issue by Kapowpenguin1** [gpac/gpac#2833]
i tried using mp4box to split a 16 gb video into 8 gb segments, but it ended up giving me this error. and only one of the two resulting segments seems to be complete. the other one doesn't contain the rest of the video.

it's strange, bc prior to this video, i wasn't having any trouble splitting up videos. i'm not sure why this one is giving me trouble all of a sudden

for the record, i'm running the "2024-4-17" release of gpac on windows 11

**Comment by jeanlf** [comment]
Could you post  your command line and source file info ?

**Comment by cconcolato** [comment]
Same problem here 
```
❯ gpac -i source.ts reframer:xs=1242264000/90000:nosap -o output.mp4
[MP4Mux] Session aborted before writing to file, use fragmented storage mode to record session
```

**Comment by cconcolato** [comment]
adding `mp4mx:store=frag` worked around the problem.

**Comment by jeanlf** [comment]
This should now be fixed on master, thanks for the report.
