### ISSUE TITLE
[HttpOut] Querystrings are included when finding files to serve.

### ISSUE THREAD

**Issue by hiimdoublej-swag** [gpac/gpac#2834]
Dear maintainers of `gpac`:

The `HttpOut` filter seems to include querystrings when serving files, it's not documented anywhere and I'm not sure if it's intended or not.

Repro case:
- `gpac` command to produce a live manifest from a pipe input
```sh
gpac \
    -log-utc \
    -logs=all@info \
    -i "pipe:///usr/src/app/video_pipe:block_size=1024" \
    -o http://localhost:8080/public.mpd:dmode=dynamic:rdirs=.:reqlog=GET 
```
- Normal request for the file
```sh
$ curl -i "localhost:8080/public.mpd"

HTTP/1.1 200 OK
Server: GPAC 2.3-DEV
Date: Fri, 10 May 2024 06:33:47 GMT
Connection: keep-alive
Keep-Alive: timeout=30
ETag: 1715322826952040
Content-Length: 2615
Content-Type: application/dash+xml

... (content follows)
```

- Request for the same file with querystring
```sh
$ curl "localhost:8080/public.mpd?qweqweq"

HTTP/1.1 404 Not Found
Server: GPAC 2.3-DEV
Date: Fri, 10 May 2024 06:33:41 GMT
Content-Type: text/plain
Content-Length: 47

Resource /public.mpd?qweqweq cannot be resolved⏎
```

As of now, I'm not sure if this behavior is intended. I would think that the querystrings, unless noted otherwise, doesn't make a difference for `HttpOut`.

---

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

**Comment by rbouqueau** [comment]
Thanks for reporting!

**Comment by aureliendavid** [comment]
Hi

this should now be fixed on latest master (see PR for possible caveats)

thanks for reporting

**Comment by hiimdoublej-swag** [comment]
> Hi
> 
> this should now be fixed on latest master (see PR for possible caveats)
> 
> thanks for reporting

Thanks @aureliendavid , I'll find some time to try it out.
However, since the PR seems to only target the "file on disk" case, would it work for the chunked-transfer case (LLDASH Server) too ?

I'll test out both and report back here when I get the chance, thanks for the help so far.
