### ISSUE TITLE
Subtitles provided using stdin pipes or http/https does not work correctly 

### ISSUE THREAD

**Issue by gregkoganvmm** [gpac/gpac#2835]
- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...)

Platform: linux/amd64 (Ubuntu 22.04) or macOS Sonoma 14.4.1

Hello,

Subtitles provided using stdin pipes or http/https does not work correctly - the output is either empty or corrupted.

`gpac -i "https://download.blender.org/demo/movies/ToS/subtitles/TOS-en.srt" -o stdout:ext=vtt`

```
[TXTIn] Corrupted SRT frame 12 after frame 1
WEBVTT

00:23.000 --> 00:24.500
etty freaky.
```
`cat TOS-en.srt|gpac -no-block=all -i stdin -o stdout:ext=vtt` produces nothing

There is a workaround to make it work (hope this helps someone) - adding the `-no-block=all` parameter helps in both cases, but this is hardly obvious. See the full command below:
`cat TOS-en.srt|gpac -no-block=all -i stdin -o stdout:ext=vtt`

`gpac -no-block=all -i "https://download.blender.org/demo/movies/ToS/subtitles/TOS-en.srt" -o stdout:ext=vtt`

**Comment by rbouqueau** [comment]
Thanks for reporting and documenting the issue. We're a bit slower than usual to process issues, thanks for your patience.
