### ISSUE TITLE
netcap with https displays garbage

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#2838]
```
$ gpac -logs=network@debug -i https://livesim2.dashif.org/livesim2/testpic_2s/Manifest.mpd dashin:forward=file -o mabr://225.1.1.0:6000:gpac:NCID=ID1
 -netcap=dst=id=ID1,flute.gpc
[Sock_IPV6] Solving livesim2.dashif.org address
[Sock_IPV6] Host livesim2.dashif.org found
[TLSv1.0] TLS header Certificate Status (22)
[TLSv1.3] TLS handshake Client hello (1)
���Y�ୱ�o.\�__�ݜ�jb��[q� �q��B�E��9G#�k�v�<z�1��h��nķ>�,�0�̨̩̪�+�/��$�(k�#�'g�
�9�     �3��=<5/�ulivesim2.dashif.org

*(

+-3&$ G�g��တ-aչQ��_�������u�Gz�^C
```

Switching the source to HTTP removes the garbage.

PS: can't make netcap work with FLUTE

**Comment by jeanlf** [comment]
Typo in 
> -netcap=dst=id=ID1,flute.gpc

It should be

> -netcap=id=ID1,dst=flute.gpc

**Comment by rbouqueau** [comment]
Thank you. I'm going to fix the misleading howto page on the wiki: https://wiki.gpac.io/Howtos/network-capture/?h=ncid#playing-network-captures

**Comment by rbouqueau** [comment]
See https://github.com/gpac/wiki/commit/f2f3a35f1199c11fdbbb197df22f8fe3227275f3
