### ISSUE TITLE
Force ttml 123.m4s segments to use just one sample(TRUN.samplecount=1)?

### ISSUE THREAD

**Issue by Murmur** [gpac/gpac#2842]
**Force ttml 123.m4s segments to use just one sample(TRUN.samplecount=1)?**

Mp4box writes 1..N samples to a ttml subtitle file (segdur=8s), sometimes it may have just one sometimes `MOOF/TRAF/TRUN.samplecount=3 (dur=1000, dur=4000, dur=3000)` items.

Is it possible to force ttml text lines go to a single sample within a segment file?

```
MP4Box.exe -add sub_eng_gap1.xml:ext=ttml:lang=eng -new temp-sub_eng.mp4
MP4Box.exe -splitx 0:384 temp-sub_eng.mp4 -out temp-sub_eng.mp4
MP4Box.exe -dash 8000 -mem-frags -profile dashavc264:live -bs-switching no -sample-groups-traf -single-traf -subsegs-per-sidx -1 --tfdt64 --tfdt_traf --noroll=yes --btrt=no --truns_first=yes --cmaf=no -segment-name "$RepresentationID$/sub_$Number$$Init=i$" -out "temp-sub_eng.mpd" "temp-sub_eng.mp4:id=sub_eng"
```

See also: https://github.com/gpac/gpac/issues/866 and https://github.com/gpac/gpac/issues/57#issuecomment-78271907

Or is it [NHNTStream](https://concolato.wp.imt.fr/2014/01/27/first-attempt-at-storing-ttml-in-mp4/) only option, I need to preprocess ttml.xml files to NHNT inputs (one per segment splitted by segment timeline + text line times)?

I believe LiveSim2 supports only `one sample per subtitle_123.m4s segment file` at the moment if using my own vod2live test material.

**Comment by jeanlf** [comment]
The dasher is media agnostic and will not modify sample content. 

I added a `ttmlmerge` filter to merge ttml isobmff samples into a single one, restarting at each segment. You can add this before the dasher (cf http://wiki.gpac.io/Howtos/mp4box-filters/#dashing) for your use case.

**Comment by jeanlf** [comment]
I also added ta `ttml_agg` option to dasher to load the `ttmlmerge` filter before output muxer.

**Comment by Murmur** [comment]
@jeanlf Thanks, I used `--ttml_agg` option and it merged xml samples, still need to run on multiple clients to check for compabitility. 
Mp4box command outputs `Arg straf set but not used | Arg sgpd_traf set but not used` warnings but guess we can ignore, small side effect on using `--ttml_agg` option.

```
mp4box -dash 8000 -mem-frags -profile dashavc264:live -bs-switching no ^
  -sample-groups-traf -single-traf -subsegs-per-sidx -1 --tfdt64 --tfdt_traf --noroll=yes --btrt=no ^
  --truns_first=yes --cmaf=no --ttml_agg ^
  -segment-name "$RepresentationID$/sub_$Number$$Init=i$" ^
  -out "temp-sub_eng.mpd" "temp-sub_eng.mp4:id=sub_eng"

MPD] Generating MPD at time 2024-06-10T14:10:20.952Z
[Dasher] End of Period
[Dasher] End of MPD (no more active streams)
Arg straf set but not used
Arg sgpd_traf set but not used
```

**Comment by jeanlf** [comment]
The warning was a bug in arguments tracking, now fixed thanks for the report.

> I was not sure about how to use ttmlmerge but this --ttml_agg does the same thing using a traditional syntax?

yes
