### ISSUE TITLE
Not setting CLOSED-CAPTIONS to none brings problems with subtitles in Apple HLS

### ISSUE THREAD

**Issue by MarianoFacundoArch** [gpac/gpac#2844]
As described in https://github.com/shaka-project/shaka-player/issues/5782
If we don't add the CLOSED-CAPTIONS to none in the m3u8s, whenever we turn on a UI for choosing subtitles (that we add later on through add text track), apple thinks there is an "Undetermined" subtitle track because the M3U8 does not have the CLOSED-CAPTIONS set to none.
Shall we implement this as a default in GPAC?

**Comment by MarianoFacundoArch** [comment]
I confirm the bug is that one, for reference I put a master m3u8 file where I fixed it manually, and it works perfectly with Apple.
The only modification to perform is adding `,CLOSED-CAPTIONS=NONE`
To the end of the #EXT-X-STREAM-INF

I think we should add this as the default behavior in GPAC

```
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-INDEPENDENT-SEGMENTS

#EXT-X-STREAM-INF:BANDWIDTH=3128000,CODECS="avc1.4D401F,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=24,AUDIO="audio",CLOSED-CAPTIONS=NONE
video/720p/media.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=1128000,CODECS="avc1.4D401E,mp4a.40.2",RESOLUTION=640x360,FRAME-RATE=24,AUDIO="audio",CLOSED-CAPTIONS=NONE
video/360p/media.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=5128000,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=24,AUDIO="audio",CLOSED-CAPTIONS=NONE
video/1080p/media.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=1628000,CODECS="avc1.4D401E,mp4a.40.2",RESOLUTION=854x480,FRAME-RATE=24,AUDIO="audio",CLOSED-CAPTIONS=NONE
video/480p/media.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=628000,CODECS="avc1.42C015,mp4a.40.2",RESOLUTION=426x240,FRAME-RATE=24,AUDIO="audio",CLOSED-CAPTIONS=NONE
video/240p/media.m3u8

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",NAME="6",AUTOSELECT=YES,URI="audio/64k/media.m3u8",CHANNELS="2"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",NAME="7",AUTOSELECT=YES,URI="audio/128k/media.m3u8",CHANNELS="2"

```

**Comment by jeanlf** [comment]
done in master, thanks for the links.

**Comment by MarianoFacundoArch** [comment]
Works perfectly!
