### ISSUE TITLE
Unable to use a sequence of JPEG images/frames to convert to .AVI or similar

### ISSUE THREAD

**Issue by Tekunalogy** [gpac/gpac#2846]
Hello, I have tried searching the issues for a potential solution.

I am recording individual JPEG frames saved to a folder in order. They are denoted img_1.jpg to img_x.jpg. I wanted to "containerize" the jpeg frames into an MJPEG formatted video (like .AVI format), and I attempted to use the following command to do so, but it did not work.

```
gpac -i img_%d.jpg compositor:fps=30 vout:ext=avi:fps=30
```

Error: `Failed to load filter for "img_%d.jpg": Requested URL is not valid or cannot be found`

Is this a supported use case? I know I could use img_1.jpg+img_2.jpg+... as stated in the docs, but if I have an arbitrary number of images, this would not be ideal.

I am avoiding using FFmpeg/Gstreamer due to integration constraints for my project, and I already have gpac integrated quite well, so this would be very convenient. Thank you in advance for your consideration and help.

---
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

**Comment by rbouqueau** [comment]
You can also use the '*' pattern instead of '+'. Would that work for you?

Otherwise if you on unix you could generate the img_1.jpg+img_2.jpg+... pattern with ````for i in `ls -v img_*.jpg` ; do echo $i+ ; done````.

**Comment by jeanlf** [comment]
You need to use the flist filter for this: http://wiki.gpac.io/Howtos/playlist/#file-list-mode
