### ISSUE TITLE
ROUTE PACKETS CHECKSUM ERROR

### ISSUE THREAD

**Issue by manavdeep** [gpac/gpac#2850]
Hi, I am using the following command to send dash files over ROUTE protocol to a multicast IP::
gpac -i index.mpd dashin:forward=file -o route://239.255.24.1:8000

Also I am able to play it using this on different machines::
gpac -play route://239.255.24.1:8000

But I have a software wherein I need to feed the PCAP file. 
So I captured the packets, filtered them for the IP and port. But all the packets show the following error with regards to checksum.
What can be done about this
![Screenshot from 2024-05-28 19-25-46](https://github.com/gpac/gpac/assets/3747933/47a57082-d6b7-47a4-be70-d9180d67b1a3)

**Comment by rbouqueau** [comment]
That's because UDP checksums are written by hardware. I get that all the time with any UDP capture, not only ROUTE.

Nothing we can do I guess. Doesn't create any issue. Otherwise please let us know.
