### ISSUE TITLE
Size gets 4x times of original size after splitting?

### ISSUE THREAD

**Issue by Jain2098** [gpac/gpac#2852]
I am new to GPAC and DASH encoding, so I might be missing something. I am using Python with latest Nightly Builds.
What I currently do is first encode the mkv/mp4 videos to my base format using ffmpeg.

**Command:**
```
            encode_command = [
                os.path.join(BIN_DIR, "ffmpeg"),
                "-i", raw_file_location,
                "-c:v", "libx264",
                "-preset", "slow",
                "-crf", "23",
                "-c:a", "aac",
                "-b:a", "96k",
                "-c:s", "mov_text",
                "-movflags", "faststart",
                "-f", "mp4",
                "-y",
                "-map", "0",
                encoded_file_location
            ]
```
This gets encoded successfully.

Now, mp4box processing with the encoded file:
```
            split_command = [
                                MP4BOX_PATH,
                                "-dash", "5000",
                                "-frag", "5000",
                                "-profile", "dashavc264:live",
                                "-segment-name", segment_path_template,
                                "-segment-ext", "null",
                                "-segment-timeline",
                                "-out", manifest_name,
                                "-init-seg", init_segment_path,
                                "-url-template",
                                "7cd2d8fe0b0a:fmt=video/x-matroska#trackID=0:id=vid0:role=main",
                                "7cd2d8fe0b0a:fmt=video/x-matroska#trackID=1:id=aud0:role=main",
                                "7cd2d8fe0b0a:fmt=video/x-matroska#trackID=2:id=sub0",
                                "7cd2d8fe0b0a:fmt=video/x-matroska#trackID=3:id=sub1",
                            ]
```

Now after processing size of the folder gets 4x times. Even if I don't encode the video and directly process mp4box, 3-4x size increase is visible. For example :
last file encoded size was 520MB. and after MP4BOX processing it reached 2GB of the size.
nonEncoded file: 443MB after process is become 1.73GB.

**Comment by jeanlf** [comment]
`-init-seg` should not be used, it's only needed to load mp4 fragments with no moov

I don't understand the syntax of your source :
- `:fmt`is not an option for dash inputs in mp4box - you should see an `Arg fmt set but not used` message
- the `trackID=0` means all tracks are selected

As a result, all the tracks of each specified input gets muxed, hence the file size increase. You can verify this by  adding  `-graph` to your command line.

To select streams from your input, you should use:
```
 "7cd2d8fe0b0a#1:id=vid0:role=main",
"7cd2d8fe0b0a#2:id=aud0:role=main",
"7cd2d8fe0b0a#3:id=sub0",
"7cd2d8fe0b0a#4:id=sub1"
```

Obviously you need to make sure the IDs are indeed the ones from the source, as seen by `gpac -h inspect`

Alternately use `SRC#video`, `SRC#audio`

For finer selection you need latest master and can specify fragments with the same syntax as link options in gpac:
`SRC#StreamType=Video` , `SRC#text2`,  `SRC#StreamType=Audio#CodecID=aac` etc...

See
- http://wiki.gpac.io/Filters/filters_general/#complex-links
- http://wiki.gpac.io/Howtos/mp4box-filters/#filtering-input-streams
