### ISSUE TITLE
Import directory in WASM demo is broken

### ISSUE THREAD

**Issue by jeanlf** [gpac/gpac#2856]
`imp -d` in the wasm cmd line throws exception

**Comment by nlsdvl** [comment]
@jeanlf I wasn't able to reproduce the issue. 
Can you share the error message in the console ? 
I noticed it's possible to hit 'enter' to run the command before the page is fully loaded,  could this be what you're experiencing here ?

**Comment by jeanlf** [comment]
Some more tests:
- osx safari: OK
- osx firefox: KO with exception:
```
Uncaught 
Object { name: "ErrnoError", node: undefined, setErrno: setErrno(errno), errno: 44, message: "No such file or directory", stack: "ensureErrnoError@https://wasm.gpac.io/gpac.js:3430:35\nstaticInit@https://wasm.gpac.io/gpac.js:3438:12\nlibgpac@https://wasm.gpac.io/gpac.js:12371:6\n@https://wasm.gpac.io/:2622:16\nsentryWrapped@https://browser.sentry-cdn.com/7.109.0/bundle.tracing.replay.min.js:2:198366\n", … }
__sentry_captured__: true
errno: 44
message: "No such file or directory"
name: "ErrnoError"
node: undefined
setErrno: function setErrno(errno)
stack: "<generic error, no stack>"
<prototype>: Error: 
2 gpac.js:3430:35
```

- osx chrome: KO with exceptions
```

bundle.tracing.replay.min.js:2 Uncaught ErrnoError {name: 'ErrnoError', node: undefined, errno: 44, message: 'No such file or directory', setErrno: ƒ, …}errno: 44message: "No such file or directory"name: "ErrnoError"node: undefinedsetErrno: ƒ (errno)stack: "<generic error, no stack>"__sentry_captured__: true[[Prototype]]: Error
    at Object.ensureErrnoError (https://wasm.gpac.io/gpac.js:3430:35)
    at Object.staticInit (https://wasm.gpac.io/gpac.js:3438:12)
    at https://wasm.gpac.io/gpac.js:12371:6
    at https://wasm.gpac.io/:2622:9
    at sentryWrapped (https://browser.sentry-cdn.com/7.109.0/bundle.tracing.replay.min.js:2:198366)
sentryWrapped @ bundle.tracing.replay.min.js:2
FileReader (async)
input.onchange @ (index):889
bundle.tracing.replay.min.js:2 Uncaught ErrnoError {name: 'ErrnoError', node: undefined, errno: 44, message: 'No such file or directory', setErrno: ƒ, …}
sentryWrapped @ bundle.tracing.replay.min.js:2
FileReader (async)
input.onchange @ (index):889

```

I haven't tested on linux or windows yet.

**Comment by nlsdvl** [comment]
I just tried on OSX Firefox, Chrome, and Safari on my end but couldn't reproduce.  
I also can't reproduce on windows 11 (Edge, Chrome, Firefox).

I was able to load nested directories with exotic filenames, running GPAC2.5-DEV-rev225-gb779331e-master

It sounds like there may be something more specific on your end, maybe the sequence of events leading to the error ? maybe something specific about the content you're trying to import ?

**Comment by jeanlf** [comment]
It looks like the exception is only thrown when importing a dir into  `/idbfs/*`, it works well when importing in other FS path.

**Comment by nlsdvl** [comment]
Thanks @rbouqueau for taking time to show me how you reproduced. 
The bug occurs when running `imp -d` from a directory which is not the default/root directory.

```
# OK
mkdir data
imp -d data

# OK
mkdir data
imp -d /data

# this does NOT work
mkdir data
cd data
imp -d

# this also does NOT work
mkdir data
cd data
imp -d .
```
