### ISSUE TITLE
Q : Encryption key rotation/rolling for live input (udp)

### ISSUE THREAD

**Issue by Bug2024** [gpac/gpac#2859]
We had tried mpeg dash output with input udp and encryption single key, it's can be play on dash.js player.
How to make  encryption key rotation/rolling  for  live input (udp) ? 
using option keyRoll  made  the manifest missing key & value of "cenc:default_KID " and  not playable.
In [Issue 2043](https://github.com/gpac/gpac/issues/2043#issuecomment-1022958868)  mentioned about "trigger reconfig of the crypto filter", is there other approach?

**Comment by jeanlf** [comment]
please post your command line(s) and sample DRM config so that we can validate if we can reproduce.

**Comment by Bug2024** [comment]
Command:
`gpac  flist:srcs=counter.hvc:floop=-1  reframer:rt=on cecrypt:cfile=drm-roll.xml @  -o out/live.mpd:gpac:profile=live:dmode=dynamic:utcs=https://time.akamai.com/?iso`
       	
drm-roll.xml
`<?xml version="1.0" encoding="UTF-8"?>
<GPACDRM type="CENC AES-CTR">
    <CrypTrack trackID="0" IsEncrypted="1" IV_size="16" first_IV="0x0a610676cb88f302d10ac8bc66e039ed" saiSavedBox="senc" keyRoll="roll=5" >
	    <key KID="0x670c462e95404809bb28a7cfd4d565e6" value="0x754eb95c419241dda5168f61c4941273"/>
	    <key KID="0x365cbe1326e74e91b124a42a548178be" value="0x3080fe16d4ca48b7ba0452c962aec20a"/>
    </CrypTrack>
</GPACDRM>`


When `keyRoll="roll=5"`	was removed from drm-roll.xml, the manifest contain cenc:default_KID.

**Comment by jeanlf** [comment]
The content plays  well in gpac, and the missing `cenc:default_KID` is expected as keys are rolled and each segment contains a `seig` sample group for key mapping.
You can try specifying `dkik=on` option to force injecting the default kid and see if it helps with your player.

> In https://github.com/gpac/gpac/issues/2043#issuecomment-1022958868 mentioned about "trigger reconfig of the crypto filter", is there other approach?

The only way to reconfigure the crypto filter is to change the `CryptInfo` property  - this can be done in flist but can also be done by a custom filter inspecting input packets and setting the property at the desired time.
