### ISSUE TITLE
"Output video codec libx264 not found" but it is installed

### ISSUE THREAD

**Issue by snoop244** [gpac/gpac#286]
Getting the following output when libx264 is installed and verified.  

Options:
    video source: pipe:
    video framerate: 24
    video crop: 0x0
    audio source: 
Configurations:
    id:v1   res:1280x720    vbr:1500000
Input #0, h264, from 'pipe:':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p, 1080x720, 24 fps, 24 tbr, 1200k tbn, 48 tbc
AVCTX give frame duration of 1/48 - keeping requested rate 24, but this may result in unexpected behaviour.

Press q or Q to exit...
Read video frame 0
Read video frame 1

Output video codec libx264 not found
Cannot open output video stream.

Keyboard thread exit

**Comment by jeanlf** [comment]
which platform ? Did you build gpac yourself, or do you try an installer ?

**Comment by rbouqueau** [comment]
On Ubuntu, you need to take the 'ffmpeg*extra' packages.

**Comment by snoop244** [comment]
I built gpac myself on Ubuntu (Raspbian Wheezy).  I followed these instructions, but grabbed the latest gpac code from git: https://gpac.wp.mines-telecom.fr/dashcast/

I compiled ffmpeg as per the instructions on that page.  Sorry for my ignorance, but is ffmpeg*extra a directive when I ./configure gpac, or when I compile ffmpeg?... or is it a simple package I can install with apt-get?  

The link, above, required that I run "sudo apt-get install libx264-dev", which I did successfully before compiling gpac. 

Thanks for your help!

**Comment by rbouqueau** [comment]
Did you also built FFmpeg as stated in the article?

**Comment by snoop244** [comment]
Yes, as stated in the article.

**Comment by rbouqueau** [comment]
Could you share a copy of 2 things with us?

1. The output of GPAC ```./configure```
2. The resulting config.mak file.

thanks

**Comment by jeanlf** [comment]
dashcast is deprecated, use GPAC 0.9.0 DEV
