### ISSUE TITLE
MABR manifest  file is not updated

### ISSUE THREAD

**Issue by j3dd4h** [gpac/gpac#2861]
Command:
gpac -i http://server/m13.m3u8 dashin:forward=file  -o mabr://225.1.1.0:6000
gpac -i mabr://225.1.1.0:6000:odir=output
The manifest file in dump output is not refreshed and the tcpdump capture showing that the manifest (ch13.m3u8) checksum is not updated  ( Content-MD5="3jimN8iItmifPkGWdbuYzA==" ) .
[mabr.log](https://github.com/user-attachments/files/15613536/mabr.log)

**Comment by jeanlf** [comment]
This is now fixed on master, thanks for the report.
