### ISSUE TITLE
Embed eods in MP4Box, to stream it with node-gpac-server

### ISSUE THREAD

**Issue by alex-rsk** [gpac/gpac#2863]
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC.
- [x] I give enough information for contributors to reproduce my issue

Hello again, excuse me for annoying questions, but I really didn't find any information anywhere.

The problem is, that our MPEG-DASH stream suffers from large download time. 1.2 Mb chunks are downloading for 0.7-1s.
Maybe I'm on wrong way totally..but, I decided to try out `node-gpac-server`.
 I read the [article](http://biblio.telecom-paristech.fr/cgi-bin/download.cgi?id=14719), and as I understood, I need to mark each segment with `eods` marker.
 How I can achieve it with `MP4Box`?
 
 Thank you.

**Comment by jeanlf** [comment]
Injecting `eods` marker is done using `--m4cc=eods`- see http://wiki.gpac.io/Filters/mp4mx/#m4cc

`node-gpac-server` is quite old and no longer maintained, I would suggest using gpac instead for that which does not need eods when used as output of dasher. See the httpout tests https://github.com/gpac/testsuite/blob/master/scripts/out_http.sh#L137
