### ISSUE TITLE
-raw creates output file without extension

### ISSUE THREAD

**Issue by GCRaistlin** [gpac/gpac#2866]
Steps to reproduce:
1. Download and unpack [sample file](https://www.upload.ee/files/16730075/Passacaglia.zip.html).
2. Execute
`MP4Box.exe -raw audio:output="Passacaglia G.F. Händel J. Halvorsen Relaxing Piano Music Al" "Passacaglia G.F. Händel J. Halvorsen Relaxing Piano Music Al.mp4"`

This will create file `Passacaglia G.F. Händel J. Halvorsen Relaxing Piano Music Al` instead of expected `Passacaglia G.F. Händel J. Halvorsen Relaxing Piano Music Al.aac`.

Win81 x64, GPAC 2.5-DEV-rev252-g8e99b3cc-master x64.

**Comment by jeanlf** [comment]
This is due to the dot in the desired output name. I pushed a quick patch for this, but it relies on file extension not using a space ...
