### ISSUE TITLE
Misc MPEG-H audio remarks

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#2869]
"When multiplexing 2 mp4 files containing mhm1 sample entries, the output contains an IODS box. Since the IODS box does not make sense for MPEG-H this should not be contained in the output"

"When using fin -> rfmhas -> fout, the output has a SYNC MHAS package before every sample. These should not be there."

Opinion?

**Comment by jeanlf** [comment]
> "When multiplexing 2 mp4 files containing mhm1 sample entries, the output contains an IODS box. Since the IODS box does not make sense for MPEG-H this should not be contained in the output"

Patched, IOD profile injected only for mpeg 1/2/4 audio and mpeg1/2/4 video

> "When using fin -> rfmhas -> fout, the output has a SYNC MHAS package before every sample. These should not be there."

This is the --syncp option which was set to true by default, I moved it to false by default
