### ISSUE TITLE
Add contentType or mediaType to MPD's adaptation set

### ISSUE THREAD

**Issue by tysonite** [gpac/gpac#2877]
As noted in https://github.com/Dash-Industry-Forum/livesim2/issues/197#issuecomment-2167666933, MP4Box generates MPD that does not have contentType (or mimeType) on adaptation set layer, but it is required by livesim2. MPD has only mediaType on representation layer.

It would be handy to add either mimeType, contentType or both to the AdaptationSet. The command line I use to generated MPD is following: `MP4Box  -dash 2000 -rap -frag-rap -dash-profile live  -out dash/napoli_3 -segment-name \$RepresentationID\$\/segment_\$Time\$ -segment-timeline -url-template napoli-v.mp4#video napoli-a.mp4#audio`

The MPD portion that makes livesim2 unhappy is following:
```
 <AdaptationSet segmentAlignment="true" maxWidth="1280" maxHeight="720" maxFrameRate="11988/400" par="16:9" startWithSAP="1">
...
   <Representation id="1" mimeType="video/mp4" codecs="avc1.64001F" width="1280" height="720" frameRate="11988/400" sar="1:1" bandwidth="249110">
   </Representation>
```

**Comment by rbouqueau** [comment]
That looks like a limitation in LiveSim2 of the MPD parsing (which can indeed be quite complex).

**Comment by tysonite** [comment]
Indeed. That's why I propose to enhance MP4Box in order to achieve better interoperability between open-source tools unless there are good reasons to don't do that.

**Comment by rbouqueau** [comment]
Contributions are always welcome indeed :)

**Comment by tobbee** [comment]
I changed livesim2 to dive deeper into adaptationSets and look for contentType or mimeTypes in a representation, but I think it is really strange not to signal it at the adaptationSet-level given that all representations in a adaptationSet must have the same contentType. I also have a hard time believing that there is valid use case where the Representations have different mimeTypes. It is allowed by the standard to signal these parameters at the Representation level, but in my opinion, it is not good praxis to do so.

**Comment by tobbee** [comment]
Nice that you made the change. In general, livesim2 adds a contentType on the AdaptationSet level to its output if its not already there, but the less guess work to derive it, the better.
