### ISSUE TITLE
Docker build examples in web doc is not up to date

### ISSUE THREAD

**Issue by chris-kuhr** [gpac/gpac#2884]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x ] I looked for a similar issue and couldn't find any.
- [ -] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [- ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...).

The web [documentation](https://wiki.gpac.io/Build/build/GPAC-Build-with-Docker/?h=docker) says:
```
## clone gpac repo
git clone https://github.com/gpac/gpac.git
cd gpac

## make changes or checkout a specific branch or commit you want 
... 

## doubly optional: you can change and rebuild the base system containing the dependencies for gpac with
docker build -t gpac/ubuntu-deps -f build/docker/ubuntu-deps.DockerFile .

## build the docker image
docker build -t myimages/gpac -f build/docker/ubuntu.DockerFile .
```

The file names of the Dockerfiles do not match with the ones in the filetree.
It should be named as "xx.Dockerfile" instead of "xx.DockerFile" (with lowercase F).

**Comment by aureliendavid** [comment]
indeed, thanks for the report, should now be fixed
