### ISSUE TITLE
Docker build fails due to an unresolved dependency

### ISSUE THREAD

**Issue by chris-kuhr** [gpac/gpac#2885]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ x] I looked for a similar issue and couldn't find any.
- [ -] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [ x] I give enough information for contributors to reproduce my issue 

When trying to build the docker image from the master branch, the gpac runtime container fails to build and crashes with:
```
#0 37.81 make[2]: Entering directory '/gpac/gpac_public/applications/gpac'
#0 37.81   CC gpac.c
#0 37.81   CC gpac_help.c
#0 37.81   CC compositor_tools.c
#0 38.68 /usr/bin/ld: cannot find -lfaad: No such file or directory
#0 38.68 collect2: error: ld returned 1 exit status
#0 38.68 make[2]: *** [Makefile:88: gpac] Error 1
#0 38.68 make[2]: Leaving directory '/gpac/gpac_public/applications/gpac'
#0 38.68 make[1]: *** [Makefile:15: apps] Error 2
#0 38.68 make[1]: Leaving directory '/gpac/gpac_public/applications'
#0 38.68 make: *** [Makefile:14: all] Error 2
------
ubuntu.Dockerfile:17
--------------------
  15 |     
  16 |     # static build
  17 | >>> RUN make distclean && ./configure --static-bin && make -j
  18 |     RUN rm -rf /gpac/binaries && mkdir -p /gpac/binaries && cp -vf bin/gcc/* /gpac/binaries/ || true
  19 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c make distclean && ./configure --static-bin && make -j" did not complete successfully: exit code: 2
```

This can be resolved by requesting `ubuntu:jammy` in the ubuntu-deps.Dockerfile instead of `ubuntu:latest`.

Result:
```
ubuntu@ffmpeg-dut:~/gpac.git$ docker run --rm gpac:190624                                                                                                                                    
[core] Creating default credential key in /root/.gpac/creds.key, use -cred=PATH/TO_FILE to overwrite                                                                                         
Refreshing all options registry, this may take some time ... done
Nothing to do, check usage "gpac -h"
gpac - GPAC command line filter engine - version 2.5-DEV-rev294-ga6701f828-master
(c) 2000-2024 Telecom Paris distributed under LGPL v2.1+ - https://gpac.io

Please cite our work in your research:
        GPAC Filters: https://doi.org/10.1145/3339825.3394929
        GPAC: https://doi.org/10.1145/1291233.1291452
```

**Comment by aureliendavid** [comment]
Hello, 

Thanks for the report. 

It looks like the latest ubuntu and debian have dropped the static version of `libfaad` (see https://metadata.ftp-master.debian.org/changelogs//main/f/faad2/faad2_2.11.1-1_changelog) 

We had a bug in the configure when detecting the absence of a static lib when the dynamic version is present. 

It should now be fixed and the docker image should build with `ubuntu:latest`. (I also updated the `gpac/ubuntu-deps` image on dockerhub so that the github action which builds `gpac/ubuntu` can use this latest version). 

Please reopen if you have further issues with the dockerfiles.
