### ISSUE TITLE
Filter ffsws not loaded when using GPAC from Docker container

### ISSUE THREAD

**Issue by alex-rsk** [gpac/gpac#2886]
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue

Greetings. 
I'm trying to add rescaler to my MPEG-DASH stream. 
I have two installations of GPAC: local and in the remote Docker container.
Both installations were made from master branch of GPAC (version 2.5-DEV-rev268 in local computer, version 2.5-DEV-rev278-gd594d3f2c-master in container).

When I run it in  my local computer, it works just fine. 
When I run it inside docker container in remote server, it failed with error:
```
Failed to load filter ffsws:osize=320x240: Filter not found 
Arg utcs set but not used
Arg force_flush set but not used
Arg segdur set but not used
```

I checked
```
 gpac -h filters | grep ffsws

 ```
 and there's no such filter in Docker installation. While in local computer it present.

Should I install some library in the container and reinstall GPAC? Or maybe there's some installation flag ?

**Comment by aureliendavid** [comment]
Hello. 

Are you using the official docker image from dockerhub or did you build it yourself? If so what dockerfile did you use? 

Using the dockerhub one I get:

```bash
$ docker pull gpac/ubuntu
$ docker run --rm -it gpac/ubuntu gpac -version
...
gpac - GPAC command line filter engine - version 2.5-DEV-rev296-gce46b1014-master
...

$ docker run --rm -it gpac/ubuntu gpac -h filters | grep ffsws
ffsws: FFmpeg video rescaler
```

In any case filters ff* use the ffmpeg libraries so you need to make sure to have that in your install (check the configure when building for example).

**Comment by alex-rsk** [comment]
We have homebrew docker image, thank you for clue, we'll try official one.

**Comment by aureliendavid** [comment]
If you want to build a more personalized image you can look at the dockerfile we use for the official one as a starting point: https://github.com/gpac/gpac/tree/master/build/docker

You can also look at the wiki page for more info: https://wiki.gpac.io/Build/build/GPAC-Build-with-Docker/

**Comment by alex-rsk** [comment]
Thank you. I  will try.

**Comment by alex-rsk** [comment]
Used full version of gpac docker, without homebrew addition, everything works now.
Thanks!
