### ISSUE TITLE
MP4Box doesn't generate chunks when called without "-segment-timeline -url-template"

### ISSUE THREAD

**Issue by alex-rsk** [gpac/gpac#2887]
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...etc). 

Greetings.
Trying to make MPEG-DASH without segment-timeline.

Command 
```
MP4Box -dash 10000  \
-dash-ctx /dev/shm/broadcast/ozDBQ3NVL7/context.txt \
-profile dashavc264:live \
--utcs="https://time.akamai.com/?iso&ms" \
 -mpd-refresh 5 \
 -dynamic  \
-bs-switching no \
 -insert-utc \
 -min-buffer 15 \
 -mpd-title "ABR test"  \
--force_flush \
-time-shift 30 \
/dev/shm/broadcast/ozDBQ3NVL7/input.mp4#video:sreg:#Bitrate=500k:#Representation=norm:dur=10 \
 /dev/shm/broadcast/ozDBQ3NVL7/input.mp4#audio:sreg:#Bitrate=48k:dur=10 -out \
   /dev/shm/broadcast/ozDBQ3NVL7/manifest.mpd 
```

The player doesn't play, it can not find segments, because they're not generating, except initial segments and 2 first:

![image](https://github.com/gpac/gpac/assets/16610797/3c662480-9e4b-4097-a461-987042adbf96)

Actually, they are absent in the out dir:
![image](https://github.com/gpac/gpac/assets/16610797/27b2a7ba-a4cf-483d-87b4-407b30a22c82)

First run is succesfull. Second and further runs give an error.
Output of the MP4box:
```
[Dasher] No template assigned, using $File$_dash$FS$$Number$
[Dasher] Synchronized clock to remote https://time.akamai.com/?iso&ms - UTC diff (local - remote) 89 ms                               
[Dasher] Input /dev/shm/broadcast/ozDBQ3NVL7/input.mp4: max audio duration 9929/1000 in the period is less than duration 10000/1000, clamping will happen                                                                                                                   
No filter chain found for PID V1 in filter dasher to any loaded filters - NOT CONNECTED                                               
No filter chain found for PID A2 in filter dasher to any loaded filters - NOT CONNECTED                                               
Filters not connected:                                                                                                                
fout (dst=/dev/shm/broadcast/ozDBQ3NVL7/input_dash_track1_init.mp4:gfopt:segdur=10000/1000:dynamic:reschedule:ntp=yes:bs_switch=off:profile=dashavc264.live:buf=1500:!check_dur:tsb=30:refresh=2:state=/dev/shm/broadcast/ozDBQ3NVL7/context.txt:loop:_p_gentime=0x59706cc58338:_p_mpdtime=0x59706cc58340:pssh=v:subs_sidx=0:noinit:frag:xps_inband=no:nofragdef:psshs=moov:mime=(null)::title=ABR Test) (idx=7)  
fout (dst=/dev/shm/broadcast/ozDBQ3NVL7/input_dash_track2_init.mp4:gfopt:segdur=10000/1000:dynamic:reschedule:ntp=yes:bs_switch=off:profile=dashavc264.live:buf=1500:!check_dur:tsb=30:refresh=2:state=/dev/shm/broadcast/ozDBQ3NVL7/context.txt:loop:_p_gentime=0x59706cc58338:_p_mpdtime=0x59706cc58340:pssh=v:subs_sidx=0:noinit:frag:xps_inband=no:nofragdef:psshs=moov:mime=(null)::title=ABR Test) (idx=8)  
                                                     
```

Looks like in the revison 268 it somehow worked. Now its version 2.5-DEV-rev298-g2e71a1ec9-master.
Reminded issue  #2875, but setting/unsetting "#Bitrate" does not change anything.

**UPD**
Creating stream _with_ segment-timeline also get broken! It happened with latest updates of repository, it seems.

@jeanlf

**Comment by jeanlf** [comment]
I have been cleaning up a few things in the dasher context and cannot reproduce with latest master, could you cross-check ?

**Comment by alex-rsk** [comment]
I'm sorry for late response.
I was unable to check the very new version.
Now, checked 2.5-DEV-rev337, and it is working with segment-timeline.

**Comment by alex-rsk** [comment]
Thank you a lot.
