### ISSUE TITLE
using Selective Encryption type RAP, all key frames are not encrypted.

### ISSUE THREAD

**Issue by Waquas97** [gpac/gpac#2889]
I tried encrypting video using selective encryption type RAP, I used the sample DRM RAP XML file given in [Common Encryption](https://wiki.gpac.io/xmlformats/Common-Encryption/#drm_file_2_drmsxml). Afterwards I extracted all the I-frames/keyframes from the encrypted video using FFMPEG, I found that only first keyframe is entirely encrypted and later keyframes  are not entirely encrypted or not encrypted at all. Is this how its supposed to work or am I doing something wrong? Also, I'm interested in knowing how GPAC implements this selective encryption of RAP. Does GPAC identify the particular bytes occupied by the keyframe in the video and then encrypt only that much? I tried looking at the source code but couldn't understand much. I'm a little new to this work so apologize if I'm asking something trivial, I would really appreciate some help.

**Comment by rbouqueau** [comment]
Hi, could you detail what you did so that we can reproduce the issue?

**Comment by Waquas97** [comment]
This is one of the video sample I encrypted:
https://github.com/gpac/gpac/assets/110435893/fd78435a-1bc5-414d-96fe-6fe58a89ddc3

I used the [drm_file_rap.xml ](https://wiki.gpac.io/xmlformats/Common-Encryption/#drm_file_rapxml) as given in the documentation without any changes. I used following command:

```shell
MP4Box -crypt drm_file.xml test.mp4 -out movie_encrypted.mp4

``` 

This is the encrypted video output I got:
https://github.com/gpac/gpac/assets/110435893/deca4b61-9b9d-4d8d-8b5a-00c076f78445


I tried playing it with FFMPEG:
```shell
ffplay -i movie_encrypted.mp4
``` 
The video is playable which was expected but it looks too good for keyframes to be encrypted, therefore I extracted I-frames/keyframes using the following command:
```shell
ffmpeg -i movie_encrypted.mp4 -vf "select=eq(pict_type\,I)" -vsync vfr Iframe-%02d.jpg

``` 
I found that the first keyframe is entirely encrypted, the next keyframes were not encrypted and the last keyframe looks partially encrypted. I tried this with various video samples and I had similar findings, Let me know what I'm doing wrong.

**Comment by jeanlf** [comment]
I have doubts about this extraction command line. Using gpac reframer:
```
gpac -i src.mp4 reframer:saps=1,2,3 inspect:deep
```

gives me 5 frames (which is consistent with info from the bitstream, only 5 IDRs and no CRA pictures), while ffmpeg gives 6 ....

Using gpac to extract the frames without decrypting (naming them using DTS, see below)
```
gpac -i movie_encrypted.mp4 reframer:saps=1,2,3 -o res/dump_$dts$.jpg --decrypt=nokey 
```
Gives me 5 frames quite unreadable.

NOW.... this gets really interesting:
1- split the file at SAP points ((take latest master to reproduce) and play them
```
gpac -i movie_encrypted.mp4 reframer:xs=SAP -o $num$.mp4 
```
The files are broken as expected (use either ffplay or `gpac --decrypt=nokey -play SRC`)

2- dump the entire stream encrypted to jpg, naming them using dts:
```
gpac -i movie_encrypted.mp4 -o frames/$dts$.jpg -decrypt=nokey
```

Compare the frames with same DTS from previous step - same bitstream different result :)

You can try using different decoders (I tried with ffdec native AVC and videotoolbox and see these variations).

You can also extract the entire clear mp4 using the same commands and check the frame difference: what happens to be a not so corrupted scene is the result of the decoding of the previous frames (the one following the previous IDR). The stream has a lot of camera movement so pretty much every pixel ends up being re-coded after the IDR.

A good illustration is the frames after the last scene cut, scene for which there is no camera motion. The decoded frames correspond to the previous GOP, not the new one.

The only logical explanation is a subtle combination, in the decoder, of:
- memory reuse for the reference frame (which one is hard to tell without further inspection)
- error concealment policy

So no bug in GPAC, the frames are indeed encrypted as planned and many thanks for a very nice case study !!
