### ISSUE TITLE
Undefined symbols for architecture x86_64:   "gf_m2ts_demux_new()"

### ISSUE THREAD

**Issue by leandropjp** [gpac/gpac#289]
Hi, I am trying to compile a C++ code with libgpac but I am receiving this message:

Undefined symbols for architecture x86_64:
  "gf_m2ts_demux_new()", referenced from:

When I compile in C (.c) is fine, I don`t receive any error. 
What is the problem?

**Comment by jeanlf** [comment]
are you including gpac headers with extern "C" ?

**Comment by leandropjp** [comment]
No, just the mpegts.h. It is really weird because works fine in .c but not in .cpp.

**Comment by rbouqueau** [comment]
When including C code from C++, you need to add:
```
extern "C"  {
  // your C includes
}
```

**Comment by leandropjp** [comment]
extern "C" {
    GF_M2TS_Demuxer *gf_m2ts_demux_new();
    GF_Err gf_m2ts_process_data(GF_M2TS_Demuxer *ts, char *data, u32 data_size);
}

I tried with this extern "C" and I received this message:

./src/main.cpp:14:40: error: conflicting declaration of 'GF_M2TS_Demuxer* gf_m2ts_demux_new()' with 'C' linkage
     GF_M2TS_Demuxer *gf_m2ts_demux_new();
                                        ^
In file included from ./src/main.cpp:7:0:
/usr/local/include/gpac/mpegts.h:952:18: note: previous declaration with 'C++' linkage
 GF_M2TS_Demuxer *gf_m2ts_demux_new();
                  ^
./src/main.cpp:15:79: error: conflicting declaration of 'GF_Err gf_m2ts_process_data(GF_M2TS_Demuxer*, char*, u32)' with 'C' linkage
     GF_Err gf_m2ts_process_data(GF_M2TS_Demuxer *ts, char *data, u32 data_size);
                                                                               
In file included from ./src/main.cpp:7:0:
/usr/local/include/gpac/mpegts.h:959:8: note: previous declaration with 'C++' linkage
 GF_Err gf_m2ts_process_data(GF_M2TS_Demuxer *ts, char *data, u32 data_size);

**Comment by rbouqueau** [comment]
This is incorrect. Please try:
```
extern "C" {
#include <gpac/mpegts.h>
}
```

then use the function as expected without any redeclaration :)

**Comment by leandropjp** [comment]
Thank you. Now the code is working.
