### ISSUE TITLE
VVC parameter sets dropped on concatenation

### ISSUE THREAD

**Issue by K-os** [gpac/gpac#2892]
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

We came across a problem when muxing multiple VVC bitstreams separately and then concatenating them using MP4Box: The parameter sets are dropped from all but the first source file. Specifically this problem pops up, when the individual bitstreams are encoded with different rates. The encoder stets the base QP in the PPSs differently, so the PPS from the later bitstreams also need to be present.

This is how to reproduce the problem:
```
MP4Box -add out1.266 -new out1.mp4
MP4Box -add out2.266 -new out2.mp4
MP4Box -new cat.mp4 -add out1.mp4 -cat out2.mp4
```
If you try to play the resulting cat.mp4 file, the decoder exits with an error, because it can not decode the second part of the file due to the wrong PPS. A workaround is to specify `--xps_inband=all`, when creating the individual files, but I think the concatenation should detect that the parameter sets are incompatible and also keep those of the later bitstreams. If that is not possible or wanted, at least a warning should be issued, that the file might not be playable.
Note: the PPSs all have the same parameter set ids, since the files were encoded separately, so the content of the raw NAL units needs to be compared.

Also, two more things I noticed when using --xps-inband:
- `--forcesync` is required to ensure `-add` does not drop the in-band parameter sets for CRA-frames, even if they were present in the source file.
- `--xps_inband=all` doesn't work when using `-cat` with MP4 files, I don't know if this is intentional.

I uploaded the raw bitstreams to the provided filedrop, as issue_2892.tar.gz

**Comment by rbouqueau** [comment]
Thanks for reporting!

**Comment by K-os** [comment]
Thanks for the quick fix.

Unfortunately, the file still doesn't play in ffplay, but I guess that is an FFmpeg bug. I now see two vvcC boxes in the SampleDescriptionBox, and the SampleToChunkEntries reference SampleDescriptionIndex 1 & 2. Is that how the player assigns the correct parameter sets to each sample?

**Comment by jeanlf** [comment]
Thanks for the report, now fixed.

> --xps_inband=all doesn't work when using -cat with MP4 files, I don't know if this is intentional.

Yes, I added some simple tracking to mp4box to warn if some argument is unused when not using a filter session

> I now see two vvcC boxes in the SampleDescriptionBox, and the SampleToChunkEntries reference SampleDescriptionIndex 1 & 2. Is that how the player assigns the correct parameter sets to each sample?

Yes that's the usual way, since inband parameter sets are not used. With inband param sets you can work with a single stsd

My recommendation would be to avoid `-cat` of ISOBMFF for such cases as `-cat` cannot manipulate source sample data. 

Using raw inputs with MP4Box:
```
MP4Box -cat out1.266:xps_inband -cat out2.266:xps_inband -new cat.mp4
```

Using a playlist is even simpler (and works with ISOBMFF inputs):
```
gpac flist:srcs=out1.266,out2.266 -o cat.mp4:xps_inband=all
gpac flist:srcs=1.mp4,2.mp4 -o cat.mp4:xps_inband=all
```

**Comment by K-os** [comment]
Ok, thanks for the clarification.

**Comment by K-os** [comment]
Oh, I came across another problem: When using open GOP with --xps_inband=all, the parameter sets are dropped for the CRA frames, when not specifying --forcesync.

For Example: the bitstream out2.266 contains the parameter sets before each CRA frame, but when muxing it with `MP4Box -add out2.266 -new out2.mp4 --xps_inband=all`, only the first parameter set is written to the samples in the MP4. This breaks seeking with FFmpeg: The decoder gets reinitialized, but since no PPS is present at that point, it can't be decoded.

**Comment by jeanlf** [comment]
Correct we were only injecting on SAP1/2 not CRA, now patched on master. Thanks for the report.

**Comment by K-os** [comment]
Thanks, it works now.
