### ISSUE TITLE
New heif converter features. Heif is moving to the new generation of vvif files

### ISSUE THREAD

**Issue by Jamaika1** [gpac/gpac#2896]
New heif converter features. Heif is moving to the new generation of vvif files
https://forum.doom9.org/showpost.php?p=2003531&postcount=325

```
[VVC] Invalid NALU type 2 in vvcC - ignoring
[VVC] Wrong param set size 48422
[isom] not enough bytes in box vvcC: 2 left, reading 86238 (file ..\..\src\isomedia\avc_ext.c, line 3096) - try specifying -no-check (might crash)
[iso file] Read Box "vvcC" (start 204) failed (Invalid IsoMedia File) - skipping
[iso file] Read Box "ipco" (start 196) failed (Invalid IsoMedia File) - skipping
[iso file] Read Box "iprp" (start 188) failed (Invalid IsoMedia File) - skipping
[iso file] Read Box type 000000! (0x00000021) at position 36 has size 0 but is not at root/file level. Forbidden, skipping end of parent box !
[iso file] Box "meta" (start 28) has 293 extra bytes
[iso file] Missing handler in META!
Error opening file vvc.vvif: Invalid IsoMedia File
```
https://github.com/strukturag/libheif/issues/519

**Comment by jeanlf** [comment]
could you upload a test file ?

**Comment by Jamaika1** [comment]
Here are the photos:
https://www.sendspace.com/file/zwz0qe

**Comment by jeanlf** [comment]
The `vvcC` is wrong: it should be a fullItemProperty and is coded as an item property.
Even when forcing a parsing as ItemPropery, the payload is `01000050B1` which is not a valid payload (reserved bits not set to 1, `ptl_present_flag` set but not enough bytes to store it.

Any clue which software generated this ?

I've patched the j2k support on master.

For AV2, we'll wait until the syntax is finalized.

FYI, `-raw` only applies to track, not items. Raw dump of items is done using `-dump-item`. Full extraction is possible using gpac if coded is supported:

```
gpac -i image_21447_24bit_openjpeg.heif -o dump.j2k
```

**Comment by Jamaika1** [comment]
Thanks

**Comment by farindk** [comment]
> The `vvcC` is wrong: it should be a fullItemProperty and is coded as an item property.

According to ISO 14496-15:2019, section 11.7.1.1.2, `vvcC` is a short Box, not a FullBox.
That might be the reason everything is shifted and it looks like `ptl_present_flag` is set, which it is not in the libheif output.

**Comment by jeanlf** [comment]
Quote from spec (7th edition, 2021);
"
This subclause specifies VvcConfigurationBox that carries a VVC decoder configuration record.
This box derives from FullBox and hence contains a version field. This version of the specification defines version 0 of this box. Incompatible changes to the box will be indicated by a change of version number. Readers shall not attempt to decode this box or the referenced CVSs if the version number is unrecognized.
"

In HEIF you also can see this "between the lines" as it states:
"(flags & 1) equal to 1 in an item property of type 'vvcC' associated with a VVC subpicture item indicates that the VVC subpicture item do not contain content intended for displaying"

**Comment by farindk** [comment]
Then it apparently changed after the 2020 DAmd2 document that I have.
I'll change this to a FullBox.

In the 2020 document, the vvcC has some fields for chromaFormat and bitDepth after the ptl block. But I do not see those in the gpac source. Have they also removed them in the 2021 document?
