### ISSUE TITLE
m2tsmux usage question

### ISSUE THREAD

**Issue by acrilique** [gpac/gpac#2897]
I'm rescuing an old project from my department and I need to generate a transport stream file with an URL in the TEMI Location descriptor and with timestamps. The transport stream will be modulated in DVB-T, received and played by a GStreamer app in another computer.  The colleagues that started the project used MP42TS utility to transform an mp4 file to .ts with the following command:

`MP42TS -real-time -rate 30000 -src=input.mp4:ID=103 -pcr-init=750 -insert-ntp -temi http://192.168.0.37/index.xml -dst-file=output.ts`

What they did was run this command, wait for the duration of the file (if the video lasted 5min they waited exactly 5min) and then they stopped execution. I don't think this is the way to go, but before fixing their mistakes I would like to be able to reproduce their workflow with modern GPAC. With the generated .ts file from the command above, I am able to play it back in the receiving computer and I'm also able to retrieve the URL.

I have tried the following two commands:
`gpac -i input.mp4 -o output.ts:pcr_init=750:temi="#N#http://192.168.0.37/index.xml"`
`gpac -i input.mp4 -o output.ts:pcr_init=750:temi="http://192.168.0.37/index.xml"`

The first one plays, and that seems to indicate that the NTP timestamps are placed correctly. The second one doesn't play. I cannot retrieve the URL from any of these. 
I have also tried adding the -real-time and -rate options, but the resulting file didn't even play in VLC.

Thanks in advance for any guidance, and thanks for such a good tool like GPAC.

**Comment by jeanlf** [comment]
You command lines are correct. We had an issue using NTP as base clock for temi location injection when NTP is injected, which was not working when realtime mode was off, resulting in only a few descriptor injected at begining, now fixed.

The `-real-time` option does not exist, you need to use `--realtime`for the TS muxer. Resulting files play fine here with VLC (osx, VLC latest).

You can check the presence of TEMI in your TS using `gpac -i src.ts inspect:deep:full | grep TEMILocation`
 
Could you cross-check ?

**Comment by acrilique** [comment]
First of all, thanks for taking the time to look at this. 

> You command lines are correct. We had an issue using NTP as base clock for temi location injection when NTP is injected, which was not working when realtime mode was off, resulting in only a few descriptor injected at begining, now fixed.

That explains why my colleagues used the --realtime option. I should be able to generate the .ts correctly with or without it, then. 

> The `-real-time` option does not exist, you need to use `--realtime`for the TS muxer. Resulting files play fine here with VLC (osx, VLC latest).

Sorry, I misspelled here, but I actually tried the correct option `--realtime`. The thing is, I tried generating the .ts with gpac 0.8.0 (mp42ts) and the first command I mentioned, and the results are different from what I get if I use modern command with gpac 1.25 (built from src).

Let me explain the differences from what I can see:
**.ts file generated with mp42ts (gpac 0.8.0) with the -real-time and -rate=30000 arguments:**

- Is very big (1.3GB from a 130MB .mp4 source). 
- Plays correctly in VLC.
- gpac -i inspect shows a lot of messages like the following: [ADTSDmx] Unsupported multi-block ADTS frame header - patch welcome
- If I modulate it and play it with our GStreamer app from another device, I can retreive the TEMILocation and access related content and I also can play the video perfectly, without errors.

**.ts file generated with gpac 1.25 (built from source) WITHOUT the --realtime argument, and WITHOUT -rate argument (-rate=30000 caused the video to not play correctly in vlc, the duration was 25 hours for some reason)**

- size is almost the same as the .mp4 source
- Plays correctly in VLC. 
- gpac -i inspect doesnt show any errors, and if I grep TEMILocation it is displayed. 
- If I modulate it and play it with our GStreamer app from another device I CANNOT retreive the TEMILocation, and the video plays, but there is a lot of errors (the video stops, then plays, then stops...) and with GST_DEBUG=3 I can see the following:
```
0:00:54.834064895 30295 0x766c68001470 WARN                basesink gstbasesink.c:3146:gst_base_sink_is_too_late:<sink> warning: Se están desechando muchos búferes.
0:00:54.834073840 30295 0x766c68001470 WARN                basesink gstbasesink.c:3146:gst_base_sink_is_too_late:<sink> warning: There may be a timestamping problem, or this computer is too slow.
0:00:54.868542653 30295 0x766c68001470 WARN            videodecoder gstvideodecoder.c:3665:gst_video_decoder_clip_and_push_buf:<h264dec> Dropping frame due to QoS. start:1091336:52:31.216168331 deadline:1091336:52:31.256168331 earliest_time:1091336:52:31.550582248
0:00:54.899160528 30295 0x766c68001470 WARN            videodecoder gstvideodecoder.c:3665:gst_video_decoder_clip_and_push_buf:<h264dec> Dropping frame due to QoS. start:1091336:52:31.251818743 deadline:1091336:52:31.291818743 earliest_time:1091336:52:31.550582248
```
**same as before, but WITH the --realtime argument**

- Our GStreamer app manages to retreive TEMILocation. The playback keeps having errors. 
- Everything else is the same as without the --realtime argument.
