### ISSUE TITLE
"isLeading" flag set to zero for all samples when re-muxing file

### ISSUE THREAD

**Issue by lvml** [gpac/gpac#29]
(This is a followup to issue #28 - but regarding another difference between original and re-muxed file:)

I try to prepare an .MP4 file such that my camera (Panasonic LX100) is willing to replay it.
As an supposedly easy first attempt I tried to re-mux an existing video clip the camera recorded using MP4Box, experimenting with options such that the output file would not differ from the input file.

The options that yield the "least visible difference" for the output of `MP4Box -info` for me are:
```
MP4Box -brand mp42:1 -no-iod -no-sys -add P1000457.MP4 P1000999.MP4
```
(You can download the (3.5 MB) sample video file here: http://filebin.ca/1knlOxMESIbK/P1000457.MP4 )

After issue #28 was fixed, there is no more difference between original and re-muxed file when looking at the output of `MP4Box -info ...`. But still, the camera is unwilling to play the re-muxed file, so I looked for other relevant differences, and found one in the outputs of `MP4Box -dts P1000457.MP4` and `MP4Box -dts P1000999.MP4`: The "isLeading" flag in the MP4Box written file is set to zero for all samples, while it is set to one for many samples in the original file.

First lines from the `-dts` dump of the original file:
```
#dumping track ID 1 timing: Num DTS CTS Size RAP Offset isLeading DependsOn DependedOn Redundant RAP-SampleGroup Roll-SampleGroup Roll-Distance
Sample 1	DTS 0	CTS 10800	91026	1	131080	1	0	0	0	0	0	0
Sample 2	DTS 3600	CTS 3600	41698	0	222106	0	0	2	0	0	0	0
Sample 3	DTS 7200	CTS 7200	35217	0	263804	0	0	2	0	0	0	0
Sample 4	DTS 10800	CTS 21600	59639	0	299021	1	0	0	0	0	0	0
Sample 5	DTS 14400	CTS 14400	34361	0	358660	0	0	2	0	0	0	0
Sample 6	DTS 18000	CTS 18000	35938	0	393021	0	0	2	0	0	0	0
Sample 7	DTS 21600	CTS 32400	62280	0	428959	1	0	0	0	0	0	0
Sample 8	DTS 25200	CTS 25200	36409	0	491239	0	0	2	0	0	0	0
Sample 9	DTS 28800	CTS 28800	36394	0	527648	0	0	2	0	0	0	0
Sample 10	DTS 32400	CTS 43200	62392	0	564042	1	0	0	0	0	0	0
```

First lines from the `-dts` dump of the MP4Box writte file (as cited above):
```
#dumping track ID 1 timing: Num DTS CTS Size RAP Offset isLeading DependsOn DependedOn Redundant RAP-SampleGroup Roll-SampleGroup Roll-Distance
Sample 1	DTS 0	CTS 10800	91026	1	2776	0	0	0	0	0	0	0
Sample 2	DTS 3600	CTS 3600	41698	0	93802	0	0	2	0	0	0	0
Sample 3	DTS 7200	CTS 7200	35217	0	135500	0	0	2	0	0	0	0
Sample 4	DTS 10800	CTS 21600	59639	0	170717	0	0	0	0	0	0	0
Sample 5	DTS 14400	CTS 14400	34361	0	230356	0	0	2	0	0	0	0
Sample 6	DTS 18000	CTS 18000	35938	0	264717	0	0	2	0	0	0	0
Sample 7	DTS 21600	CTS 32400	62280	0	300655	0	0	0	0	0	0	0
Sample 8	DTS 25200	CTS 25200	36409	0	362935	0	0	2	0	0	0	0
Sample 9	DTS 28800	CTS 28800	36394	0	399344	0	0	2	0	0	0	0
Sample 10	DTS 32400	CTS 43200	62392	0	435738	0	0	0	0	0	0	0
```

I guess that the different offsets might be irrelevant, but the difference in "isLeading" looks fishy, doesn't it?

**Comment by jeanlf** [comment]
Indeed the isLeading flag was droped during import, now fixed in rev 5587. thanks for the report
