### ISSUE TITLE
mux_isom: Fragments not created when multiple tracks are present

### ISSUE THREAD

**Issue by DenizUgur** [gpac/gpac#2904]
I've noticed that when I try to multiplex multiple tracks in a fragmented MP4 file, only one moof is created. If I remove the second track then moof's are created as usual. Is this a bug or I'm doing something wrong in multiplexing multiple tracks?

GPAC version: 2.5-DEV-rev403-g56c7c3ccc-master
OS: Ubuntu 22.04

**Command line used:**
```bash
gpac --g=30 \
  avgen:v:fps=30 \
  @@0 ffsws:osize=1280x720:RSID @ c=avc:b=3000000:minrate=3000000:maxrate=3000000:bufsize=6M:FID=e1 \
  @@0 ffsws:osize=640x360:RSID @ c=avc:b=360000:minrate=360000:maxrate=360000:bufsize=720K:FID=e2 \
  -o test.mp4:cmfc:frag:cdur=1:straf:strun:fragdur:SID=e1,e2
```

**Comment by jeanlf** [comment]
This is the default behaviour. If you need a single track per moof, use `mp4mx:straf` option.

**Comment by DenizUgur** [comment]
Do you mean this:

```bash

**Comment by jeanlf** [comment]
Indeed this was introduced when adding zero-copy fragment muxing and we had no test case checking it. Fixed and updated on testsuite.

**Comment by DenizUgur** [comment]
That's perfect. Thank you
