### ISSUE TITLE
mp4box crashes because of assertion failure

### ISSUE THREAD

**Issue by tcurdt** [gpac/gpac#291]
I am trying to use mp4box (through mpktomp4) but mp4box crashes because of assertion failure.

    error: failure: WARNING: NAL Unit type 0 not handled - adding
    Assertion failed: (prev_nalu_prefix_size==0), function gf_import_avc_h264, file media_tools/media_import.c, line 4761.

I am using `gpac` 0.5.2 on OSX 10.10.5 with

- jpeg ✔
- libogg ✔
- libvorbis ✔
- ffmpeg ✔

**Comment by tcurdt** [comment]
Command is:

    ['MP4Box', '-add', 'foo.mkv.h264#video:trackID=1', '-hint', '-fps', '23.976', 'foo.mp4']

**Comment by jeanlf** [comment]
could you upload the raw h264 somewhere ?

**Comment by jeanlf** [comment]
should now be fixed, reopen if needed

**Comment by tcurdt** [comment]
Now I am getting:

    error: failure: WARNING: NAL Unit type 0 not handled - adding

and lots of

    WARNING: NAL Unit type 0 not handled - adding
    Waring: Error parsing NAL unit
    WARNING: NAL Unit type 0 not handled - adding
    ...
    WARNING: NAL Unit type 0 not handled - adding
    Waring: Error parsing NAL unit
    ...
    Waring: Error parsing NAL unit
    Import results: No SPS or PPS found in the bitstream ! Nothing imported
    Error importing <FILE>.mkv.h264#video:trackID=1: BitStream Not Compliant

Sorry that I cannot provide the video :-/

**Comment by jeanlf** [comment]
can't you provide just the few first frames of the raw bitstream ? Debugging without the file won't be possible I'm afraid ...

**Comment by rbouqueau** [comment]
> Error importing <FILE>.mkv.h264#video:trackID=1

Is the input raw h264, or is it an mkv? GPAC doesn't support MKV import, you need to extract the tracks with another tool first.

**Comment by tcurdt** [comment]
@jeanlf how many bytes do you need?
@rbouqueau the tooling first extracts the h264 stream

**Comment by jeanlf** [comment]
Enough bytes so that the error can be reproduced, hard to say how much without knowing the bitrate and framerate of the encoded sequence. Try dumping the first 500k and reimport I believe this should be enough

**Comment by tcurdt** [comment]
Hm - one can really just cut off the head?
I was just trying this - but that doesn't seem to work:

    cat foo.mkv.h264 | head -c 500000 > foo.mkv.h264.head
    MP4Box -add foo.mkv.h264.head#video:trackID=1 -hint -fps 23.976 foo.mp4

it gives me

    [MPEG-2 TS] TS Packet 1 has error (PID could be 6715)
    [MPEG-2 TS] TS Packet 2 is scrambled - not supported
    [MPEG-2 TS] TS Packet 3 does not start with sync marker
    ...lots of them

which doesn't seem right (to me).

**Comment by jeanlf** [comment]
You should use:
`MP4Box -add foo.mkv.h264.head:fmt=AVC -fps 23.976 foo.mp4`

to test if AVC parsing works

**Comment by tcurdt** [comment]
Ah! OK - now it works and I am to reproduce it.
Here is the beginning of the file:

    curl http://vafer.org/pub/foo.mkv.h264.head > foo.mkv.h264.head

**Comment by jeanlf** [comment]
....

your bitstream is not avc/h264, it's hevc , and works perfectly using
`MP4Box -add foo.mkv.h264.head:fmt=HEVC -fps 23.976 foo.mp4`

**Comment by tcurdt** [comment]
Hm. Interesting. But [`mkvtomp4`](https://github.com/gavinbeatty/mkvtomp4/) calls `MP4box` like this - so doesn't specify any format.

    ['MP4Box', '-add', 'foo.mkv.h264#video:trackID=1', '-hint', '-fps', '23.976', 'foo.mp4']

Is that the problem then?

**Comment by rbouqueau** [comment]
MP4Box detects h264 based on the file extension. The correct file extension should be .h265. Would it be possible to report to the tool maintainer?

**Comment by tcurdt** [comment]
Ah, I see. Question is whether the tool knows about this. I've opened an issue for this. (see https://github.com/gavinbeatty/mkvtomp4/issues/12)

That said - wouldn't it be better to detect it from the data as opposed to rely on the file ext? No idea about the format if that is a possible enhancement.
