### ISSUE TITLE
Cant name subtitle track

### ISSUE THREAD

**Issue by davidboutet** [gpac/gpac#2917]
Hello I have issue with naming the subtitle track.
Here is my command line:
```
MP4Box -add CC_29_FR_535856.srt:lang=fre:name='French full' \
-add FORCED_23_FR_535856.srt:lang=fre:name='French forced':default=1:forced=1:txtflags=0xC0000000 \
-keep-sys  \
1080p_20_51.mp4 \
-out out_1080p_20_51.mp4

```
I was expecting to have a subtitle track name French full and another French forced
But in VLC I have Track 1 - [French] and Track 2 - [French]

Am I doing something wrong?
Thanks for any help

**Comment by todd829** [comment]
Same issue here!
Thanks for any help

**Comment by aureliendavid** [comment]
Hi, 

I suspect this might be a VLC issue. 

Can you check with something like [mediainfo](https://mediaarea.net/en/MediaInfo) that your subtitles tracks are indeed correctly named in your output mp4 file? (`Title` field)

I did some tests and it looks like VLC is only displaying the `Title` of a subtitle track (when we do right click > subtitle > sub track) for `srt`/`subrip `formatted subtitle tracks. 

This is the format used in `mkv` files for subtitle tracks so it will work with those. 

However in `mp4` files, subtitle tracks use the `tx3g` / `mov_text` format and it looks like VLC is just not displaying the `Title` of the track for those even if they are present. 

I tested with a command similar to the original issue and I also see only `"Track 1 [French]"`. But if I convert the resulting file to mkv (with something like `gpac -i test.mp4 -o test.mkv`) and play the mkv file in VLC I will see my track titles. 

So there are two possibilities here: 

1. VLC is not displaying track titles for mp4 subtitle tracks
2. mp4box is not encoding the Title in the correct way / there's another Title field that needs to be filled for it to work

I'm suspecting 1. to be the case, but I'm looking if I can find an mp4 file for which VLC is showing subtitle tracks names. Then this might be an mp4box issue than we can fix. (if anyone can provide such a file it would be help).

**Comment by davidboutet** [comment]
Hello 
thanks for your reply, 
your solution is working well

Thanks again

**Comment by davidboutet** [comment]
Sorry an another thing, but track doesnt display in the TV app(formely Itunes)
Do I need to add somethings specific?
Thanks

**Comment by aureliendavid** [comment]
is it the track name that is not showing (like in the original vlc issue) or the subtitle track itself that is not showing at all?

without being able to test your specific player it's hard to debug

however if it's an apple related player you might try to add `hdlr=stbl` to the subtitle import options

so form my previous example: 

```
MP4Box -add sub1.srt:hdlr=sbtl:lang=fre:name='French full' -udta 1:type=name:str="French full"  -add sub2.srt:hdlr=sbtl:lang=fre:name='French forced' -udta 2:type=name:str="French forced"   -add vid.mp4  -new allmuxed.mp4
```

Now if the track title is still not showing we might have to add the `udta.titl` box (3rd solution from handbrake) but it's a bit more complicated since this box has a more complex structure than the `udta.name` one

**Comment by aureliendavid** [comment]
doing some more tests with quicktime player (which might be similar to your player, but might not), it looks like to recognize multiple subtitle tracks it needs them to be in the same "alternate group", which can be set with the `group` import parameter

so our command line becomes: 

```
MP4Box -add sub1.srt:hdlr=sbtl:group=1:lang=fre:name='French full' -udta 1:type=name:str="French full"  -add sub2.srt:hdlr=sbtl:group=1:lang=fre:name='French forced' -udta 2:type=name:str="French forced"   -add vid.mp4  -new allmuxed.mp4
```

(I'm looking into the `titl` box, will update when I have something)

**Comment by aureliendavid** [comment]
well I must admit, I've given up trying to understand how quicktime works

I made a jsfiddle to help building this kind of command lines, including the `udta.titl` box : https://jsfiddle.net/sqv9Ltun/

(based on https://patchwork.ffmpeg.org/project/ffmpeg/patch/20210721172809.22974-1-jeebjp@gmail.com/ and https://developer.apple.com/documentation/quicktime-file-format/language_code_values for building the titl box)

this gives the same results as the handbrake-encoded example

however quicktime seem to have issues when there are multiple subtitle tracks for the same language

also when it is displaying the title and not just the language seems mysterious 

so I'll let anyone who wants to play with all the command line parameters and the different players to find the right set of options for their particular needs

**Comment by davidboutet** [comment]
Thanks for everything, ill try many combination and I hope to find the right one.
Thank you
