### ISSUE TITLE
MABR  manifest update problem

### ISSUE THREAD

**Issue by j3dd4h** [gpac/gpac#2922]
Sender:
`gpac  -i https://vs-dash-ww-rd-live.akamaized.net/pl/testcard2020/256x144p25/media.m3u8 dashin:forward=file -o mabr://225.1.1.1:6000:gpac:use_inband=true  -logs=route@info`

Receiver:
`gpac -i mabr://225.1.1.1:6000:odir=output  -logs=route@info`

Log
```
[DVB-FLUTE S1] Got file 448402437.m4s (TSI 10 TOI 76) size 95959 in 12111 ms
[DVB-FLUTE RFDT] Unable to extract XML content from package: BitStream Not Compliant - 
#EXTM3U
#EXT-X-TARGETDURATION:4
#EXT-X-VERSION:7
#EXT-X-MAP:URI="IS.mp4"
#EXT-X-MEDIA-SEQUENCE:448402206

#EXTINF:3.84,
448402206.m4s
#EXTINF:3.84,
448402207.m4s
```

Using option use_inband=**true**, the manifest file is not created   and when option use_inband=**false**, the manifest file is not updated ( it was solved https://github.com/gpac/gpac/issues/2861)

**Comment by jeanlf** [comment]
Now fixed on master, thanks for the report
