### ISSUE TITLE
An integer overflow bug in filedump.c

### ISSUE THREAD

**Issue by xiaobaozidi** [gpac/gpac#2927]
Dear Maintainer,

We have identified an integer overflow bug in the [latest commit](https://github.com/gpac/gpac/issues/e2250d68fd)

### **Version**

```

MP4Box - GPAC version 2.5-DEV-rev464-gf5722ca17-master
(c) 2000-2024 Telecom Paris distributed under LGPL v2.1+ - https://gpac.io

Please cite our work in your research:
	GPAC Filters: https://doi.org/10.1145/3339825.3394929
	GPAC: https://doi.org/10.1145/1291233.1291452
```

### **reproduce**
```

./configure --static-build --static-bin --enable-sanitizer --extra-cflags="-fPIC -g"  --extra-ldflags="-ldl -g -lz"
make
./MP4Box -info integer_overflow_poc
```

### **bug information**

```
Duration 00:00:00.000filedump.c:2198:8: runtime error: -1000 is outside the range of representable values of type 'unsigned long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior filedump.c:2198:

```

### **Potential fix**
```
2198         dur = (u64) (( ((Double) (s64) dur)/timescale)*1000);
2199         h = (u32) (dur / 3600000);
2200         m = (u32) (dur/ 60000) - h*60;

```
((Double) (s64) dur)/timescale)*1000 could be overflow so please check before casting to u64

[Integer_overflow_poc.zip](https://github.com/user-attachments/files/16448779/Integer_overflow_poc.zip)

**Comment by aureliendavid** [comment]
I couldn't reproduce this. 

More generally we do not consider integer overflows as proper issues if they have no further consequences. 

They are more a case of "garbage in, garbage out". If the input data has absurd values it is not an issue that we produce absurd values in return. And we can't really add int boundary checks around every single numerical operations. 

These can become real bugs or security issues if the overflow leads to a segfault, or is used in a malloc() later, or in an array subscript, etc..

But all these cases will be caught by ASAN or other tools as proper memory issues that can be reported. 

So I would suggest to run sanitizers with the environment variable `UBSAN_OPTIONS=silence_unsigned_overflow=1` or similar, see https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#silencing-unsigned-integer-overflow for further details. 

And I would also suggest not to open issues about simple int overflows if they don't lead to a proper memory issue. 

But thanks anyway for the various issues you reported.
