### ISSUE TITLE
mp4box crashes during DASH creation

### ISSUE THREAD

**Issue by Eleasar** [gpac/gpac#293]
Versions affected: all latest versions (0.5.2 rev550 works)

Using the following command prompt:

    mp4box -noprog -dash 4000 -out c:\temp\testvideo\Manifest.mpd -profile "dashavc264:live" -sample-groups-traf -bs-switching no -logs all@info c:\temp\Video-und_H264_400kbps.mp4

Tested with the following video (~27MB)
https://www.dropbox.com/s/41igsa42s29oq9f/Video-und_H264_400kbps.mp4?dl=0

Output even with all@info produces just this:

    [DASH] WARNING! DASH Live profile requested but no -segment-name
        using "%s_dash" by default

    DASH-ing file: 4.00s segments 4.00s fragments single sidx per segment
    Spliting segments at GOP boundaries
    DASHing file c:\temp\Video-und_H264_400kbps.mp4

Hope this information is enough. Tested with a few of the 64bit nightly windows build versions and even a 32bit one. Crash report from windows does not seem to include any useful information.

**Comment by jeanlf** [comment]
Now fixed, thanks for files and report !

**Comment by Eleasar** [comment]
Thanks for the fix! That was really fast!
