### ISSUE TITLE
testapps build error

### ISSUE THREAD

**Issue by naeoc4509** [gpac/gpac#2957]
Hi,

As shown in the picture below, are all the test codes in '<gpac>/applications/testapps/' deprecated?

![image](https://github.com/user-attachments/assets/c475a34b-85cc-4b72-98b2-7733f5cee7f3)

All the test codes cause build errors.

If they are deprecated, why aren't they being removed?

**Comment by rbouqueau** [comment]
We talked about removing some of them that were superseeded by filters. We should definitely make sure the remaining ones build.

**Comment by naeoc4509** [comment]
Thank you ~
