### ISSUE TITLE
Question. How to set fintra for GOP size 64 and FPS 25.

### ISSUE THREAD

**Issue by alex-rsk** [gpac/gpac#2958]
This is a question about `fintra` parameter [from "fenc" filter](https://wiki.gpac.io/Filters/ffenc/?h=fintra#ffmpeg-encoder).
I have 25 fps video, and I want to put IDR frame into each 64th frame (GOP size =  64).

I honestly can't understand, how I can achieve this.
Given explanation
```
 fintra=1001/1000 will force an intra every 30 frames on 30000/1001=29.97 fps video
```
gave me a vague undestanding, how to use it.
Given equation:
Gop*1000 / x = FPS, so I solved it as 64000/x = 25, then x = 2560.
So my fintra will be 64000/2560?

**Comment by Murmur** [comment]
`fintra (frac, default: -1/1): force intra / IDR frames at the given period in sec`
Can you give just an exact fraction seconds `fintra=2.56`  or simple `2560/1000` if that's a format it wants?

`1000/25fps=40ms per frame * 64frames = 2560ms interval`

**Comment by alex-rsk** [comment]
>>May I ask a reason for IDR every 64th frame
I make DASH stream from series of MP4 fiels, using MP4Box. 
So I need that my dash segments must be aligned between representations.
For my stream 25 FPS and 8KHz audio,  I calculated that most feasible is 2.56 sec segment.

>>Can you give just an exact fraction seconds fintra=2.56 or simple 2560/1000 if that's a format it wants?
It seems that exact fraction didn't work out, I still see problems with playback.
>>2560/1000
Thank you, I'll try this.

Now i'm trying to get rid of `fintra`, and testing this formula
`c=avc:keyint_min=64:rc:flags=cgop`

**Comment by alex-rsk** [comment]
Closed, 2560/1000 worked. Thanks to @Murmur.
