### ISSUE TITLE
TrackID change?

### ISSUE THREAD

**Issue by combucha** [gpac/gpac#296]
Hi, is any way to rearrange tracks ID's when importing via mp4box?
It always cloning them from original, I don't want audio on ID#1 :/
Can't dump to raw, it's vfr movie.

**Comment by rbouqueau** [comment]
Yes you can remap ids:
```MP4Box -h general```
```-set-track-id id1:id2 changes the id of a track from id1 to id2```

For example:
```MP4box -add file.ts#audio -set-track-id 257:1 -new file.mp4```

Do it help?

**Comment by combucha** [comment]
Yes, thanks.
In first step I import only video and remap its id 2->1, then add audio (auto id remap 1->2).
I tried "swap ids" in one command line [v#2->1:a#1->2] but it wasn't possible (cannot set track id with value 1 because a track already exists)..

**Comment by jeanlf** [comment]
now possible using -swap-track-id ID1:ID2
