### ISSUE TITLE
Unable to build unittests

### ISSUE THREAD

**Issue by nlsdvl** [gpac/gpac#2961]
Unit tests failed to build because of `error: use of undeclared identifier '__ASSERT_FUNCTION'` in `tests.h`.

As a side note, the [build instructions](https://github.com/gpac/gpac/tree/master/unittests#build-and-run) for unittests needs to be changed. the `./configure` option is  `--unittests` instead of `--enable-unittests`.

**Comment by aureliendavid** [comment]
I've encountered this before too, it comes from the NDEBUG flag that undefines asserts in release mode. 

You can add --enable-debug to your configure as a workaround

**Comment by soheibthriber** [comment]
alternatively we can use  "__func__" instead of "__ASSERT_FUNCTION" that works too

**Comment by nlsdvl** [comment]
Thanks for the pointers.

```
./configure --enable-debug --unittests --extra-cflags=-Wno-deprecated
make
``` 

I'm guessing the issue is that `__ASSERT_FUNCTION` is not declared in [Apple's libc](https://github.com/apple-oss-distributions/Libc).
Using `__func__` as suggested by @ resolved the error. 

There ran into another issue after that and opened a PR with the fixes I ended up using: https://github.com/gpac/gpac/pull/2964

**Comment by rbouqueau** [comment]
PR merged, thank you. Please close this issue if ok.
