### ISSUE TITLE
Can't stream gpac-generated MPEG-TS video with rtspout+rtpin (Segfault)

### ISSUE THREAD

**Issue by acrilique** [gpac/gpac#2963]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

___

I've generated Transport Stream files for 2 AVC videos, and I'm trying to make them available via RTSP. In order to serve the files (which are all on the same directory) I'm using the following command: 
```
$ gpac rtspout:mounts=/path/to/my/directory
```
Now if I open another terminal and try to play one of the .mp4 files (`$ gpac -play rtsp://127.0.0.1/video.mp4`), it plays flawlessly. There's a warning related to audio in the server's console, but we can ignore that for now because I also get that warning when trying to play .ts files. The thing is, when doing the latter (playing .ts files with `$ gpac -play rtsp://127.0.0.1/video.ts`) I get a segmentation fault right after the warning, and the server stops. 

The .ts files were created with GPAC, using this command:
```
$ gpac -i input.mp4 -o output.ts:temi="#N#http://an_ip_address/a_resource":rate=10M 
```  
I've already managed to send this Transport Stream files through DVB with a DekTek modulator and play them on the other end with a GStreamer application with the dvbsrc plugin. They can also be played with VLC. This is the output of gpac inspect for an mp4 and a ts file, in case you can spot a difference. 
```
$ gpac -i primavera.mp4 inspect
PID 1 ID 1 video inMovie duration 07:44.084 timescale 12288 delay -512 1920x804 fps 24 SAR 1/1 1324 kbps 11138 frames codec avc1.640028 AVC|H264 PL High@4 YUV 4:2:0 8 bpp
PID 2 ID 2 audio inMovie duration 07:44.167 44100 Hz 2 chan 128 kbps 19990 frames codec mp4a.40.2 AAC LC (aot=2 implicit)

$ gpac -i primavera_fixedrate_10M.ts inspect
PID 2 ID 101 audio service 1 duration 07:44.094 timescale 90000 44100 Hz 2 chan codec mp4a.40.2 AAC LC (aot=2 implicit)
PID 1 ID 102 video service 1 duration 07:44.094 timescale 90000 1920x804 fps 24 SAR 1/1 codec avc1.640028 AVC|H264 PL High@4 YUV 4:2:0 8 bpp
```

Here are the files that I've tried to use for this:
https://www.mediafire.com/file/9z0aq8qehi7rlyg/primavera.mp4/file
https://www.mediafire.com/file/tttwy274c8woec1/f1-rollercoaster_25_frontal.mp4/file
https://www.mediafire.com/file/held6xk8gfendh6/f1-rollercoaster_25_frontal_fixedrate.ts/file
https://www.mediafire.com/file/dnf9zvn0tzexz4t/primavera_fixedrate_10M.ts/file

It would be very useful to be able to stream Transport Stream files with this method, so I hope some of you can spot the issue. Thanks in advance for your help.

**Comment by jeanlf** [comment]
This was indeed not supported, source TS was always demultiplexed. This is now supported on master, with basic seeking support (no RAP location).
Thanks for the test files and detailed issue !
