### ISSUE TITLE
mp4box vobsub subtitles muxing from idx/sub files is broken (or dropped?)

### ISSUE THREAD

**Issue by chr-thien** [gpac/gpac#2967]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Mp4box support for muxing vobsub subtitles into mp4 container seems to be gone.

I tried this simple command:
`mp4box.exe -add in.mp4 -add in.idx -new out.mp4`

Latest working GPAC installer I found was gpac-0.8.0-rev95-g00dfc933-master-x64.
Later revisions do not perform muxing vobsub subtitles from a pair of idx/sub files (I tried GPAC 1.0, 1.0.1, 2.4 and 2.5 latest).
No output file is created.

Windows 11/64Bit , GPAC also 64bit.
I tried 32 bit installers from GPAC - same behaviour. So it's not platform related.

**Comment by jeanlf** [comment]
Support for vobsub is still here, see [related test](https://github.com/gpac/testsuite/blob/master/scripts/vobsub.sh)

This is likely source-related, could you upload your source so that we can reproduce ?

**Comment by chr-thien** [comment]
I did upload idx/sub using above mentioned [link](https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95).

However I uploaded again. Please use this [link for download idx/sub](http://www.mediafire.com/folder/e8bki60ip92f2rj,m84czzdmw7w9ktb/shared)

**Comment by chr-thien** [comment]
I found the problem by comparing your idx test file to my file. My file contains empty tracks.
e.g.:

id: pl, index: 2
id: tr, index: 3

but these tracks do not reference any subtitles.

As I said above, those content was supported up to gpac-0.8.0-rev95-g00dfc933-master-x64.

Output from mp4box 0.8.0:
`VobSub import - subpicture stream 'eng'`
`VobSub import - subpicture stream 'deu'`
`VobSub import - subpicture stream 'pol'`
`VobSub import - subpicture stream 'tur'`

My file was created by vstrip tool.

After removing empty tracks, mp4box from latest installer is able to mux the subtitles.

It would be great, if recent mp4box could at least ignore empty tracks. If not, then idx file preprocessing would be needed before feeding into mp4box.

**Comment by jeanlf** [comment]
Indeed we had a crash with vobsub files with empty tracks, now fixed. I added an option to keep empty vobsub tracks, disabled by default.
Thanks for the report and test content !
