### ISSUE TITLE
DashCast producing invalid segments

### ISSUE THREAD

**Issue by nickdesaulniers** [gpac/gpac#297]
Wish I had better Steps To Reproduce, but I'm seeing occasional .m4s files being produced that are invalid and can't be decoded by browsers.  From running:

```
bin/gcc/DashCast -vf avfoundation -vres 1280x720 -v "Capture screen 0" -vfr 25 -live -no-loop
```

See also: https://github.com/google/shaka-player/issues/215

**Comment by jeanlf** [comment]
dashcast is deprecated, use GPAC 0.9.0 DEV
