### ISSUE TITLE
feature: rtspout, compliance with rfc3986 (uri)

### ISSUE THREAD

**Issue by acrilique** [gpac/gpac#2971]
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

When using gpac rtsout (with this command: `gpac -i /path/to/file.ts -o rtsp://0.0.0.0:8554/mystream`) in conjunction with gstreamer rtspsrc, we get Bad Request responses from the gpac server to the SETUP requests.

Here are my traces:
![imagen](https://github.com/user-attachments/assets/f721c3f3-edeb-473d-adc5-0f50472c0052)

According to [this issue](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3811#note_2570506) the expected behavior of an rtsp peer receiving a response to a DESCRIPTION request with a relative control path in its SDP contents should be:
```
baseurl: 
rtsp://ip/examplestream

attribute of the received SDP in RTSP DESCRIPTION response: 
a=control:something

result of concatenation: 
rtsp://ip/something
```
Setting "force-non-compliant-url" on the rtspsrc g_object allows the connection to work, so this is not really super necessary. I just thought probably gpac aims to be standard-compliant.

Maybe gpac should send `a=control:examplestream/something`, or an absolute path? 

One last thing, not much related: could we add `Content-Type: application/sdp` to the RTSP DESCRIBE response? That would make automatic parsing with programs like Wireshark work.

**Comment by jeanlf** [comment]
This is now fixed on master, thanks for the report
