### ISSUE TITLE
rtspout, mpeg-ts sudden end of stream 

### ISSUE THREAD

**Issue by acrilique** [gpac/gpac#2972]
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Hi I'm testing this command to serve a TS file:
```
$ gpac -i /path/to/file.ts -o rtsp://0.0.0.0:8554/mystream
```

If I play that back from another computer with `gpac -play rtsp://ip:8554/mystream` it works perfectly. 
However, when trying to play it back with a gstreamer pipeline (rtspsrc + rtpmp2tdepay + tsdemux ...) the server exits after like 22 seconds. There's no error message, and I haven't seen anything obvious looking at the debug logs or wireshark traces (there's no RTSP TEARDOWN request sent from gstreamer so it does not seem to be rtspsrc's fault). If I use `rtspout:mounts` instead of serving a specific file, the stream also stops after 22 seconds, but the server keeps open. 

The .ts files I've been using for this have been generated with `gpac -i input.mp4 -o output.ts:temi="#N#http://an_ip_address/a_resource":rate=10M `. They both cause the exact same error described above (the stream shuts down after 22 seconds or so. I have not measured the amount of seconds exactly but it seems to happen at the exact same time). 
I've tried this with "primavera_fixedrate_10M.ts" and f1-rollercoaster_25_frontal_fixedrate.ts" files, which were uploaded to your filedrop for another issue. 

Thanks in advance for your help!

**Comment by jeanlf** [comment]
Can you try logging (-logs=rtp@info or -logs=rtp@debug if not enough) the server ? I suspect a session timeout due to no rtcp reports

**Comment by acrilique** [comment]
Indeed, the last message before shutting down the server is `[RTSP] Timeout on session rtsp://x.x.x.x:8554/mystream after 20003 ms, aborting`.

**Comment by acrilique** [comment]
I missed something very important in wireshark. It seems gstreamer is sending the reports to a different port: 
![imagen](https://github.com/user-attachments/assets/90be7104-6c63-42af-98d3-ef71de81cc1a)

**Comment by acrilique** [comment]
After more testing, I can conclude that the GPAC rtsp server is only using the --firstport value for the response to the RTSP SETUP message. It then uses a randomly chosen port as the source port for the Sender Report RTCP messages. I'll try to find the bug and send a PR but I'm still not so familiar with GPAC's codebase so can't promise anything.

**Comment by jeanlf** [comment]
Indeed we had some weird old code preventing the bind, resulting in non-predictable sender ports being used by the server. Now fixed on mastern thanks for the report

**Comment by acrilique** [comment]
Works like a charm! Thanks
