### ISSUE TITLE
feature: rtspout, support mp2t with playlists

### ISSUE THREAD

**Issue by acrilique** [gpac/gpac#2973]
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

I've created a folder and put in it 2 .ts files generated with `gpac -i input.mp4 -o output.ts:temi="#N#http://an_ip_address/a_resource":rate=10M ` and a playlist.m3u file with 2 lines containing the names of those .ts files. I'm using this command to serve the playlist:
```
$ gpac -i playlist.m3u -o rtsp://0.0.0.0:8554/mystream --floop=-1
```

I then go to another computer and try to play it back using:
```
$ gpac -play rtsp://ip_address:8554/mystream
```

However, playback doesn't seem to start. With `--logs=all@debug` I can see that m2tsdmx is being instantiated, so it's trying to demux my .ts files. 
I assume this feature is desired as support for non-demuxing of .ts files going through rtspout has been added recently in [b11c438](https://github.com/gpac/gpac/commit/b11c438b5c6c9ad35ad840440ae198f6b8d4daef)

**Comment by jeanlf** [comment]
We indeed had a deadlock in the flist code for the specific case of rtsp + ts playlist, now fixed on master.

`flist` will require demuxing inputs as it needs to restamp all frames into a contiguous timeline. 

You can however remux your streams:
```
gpac -i playlist.m3u m2tsmx -o rtsp://0.0.0.0:8554/mystream --floop=-1
```

Latest master will re-inject TEMI descriptors when remuxing.

Having the raw TSs served in a playlist would require restamping the entire stream (incl. PCR) which would be a completely different filter, we're not planning to work on that for now.

**Comment by acrilique** [comment]
Thanks a lot for looking into this. Being able to have TEMI descriptors is exactly what I needed.
