### ISSUE TITLE
negative time sample causing loss of data

### ISSUE THREAD

**Issue by NathanLewis** [gpac/gpac#298]
In line 8166 of src/media_tools/media_import.c as of commit f2dc63a1608619bc625451a7d9ef7a5b760bfbac

There is the conditional statement
```
if (samp->DTS >= pck->stream->first_dts) {
.
.
} else {
      GF_LOG(GF_LOG_ERROR, GF_LOG_CONTAINER, ("[MPEG-2 TS Import] negative time sample - skipping\n"));
}
```
We have found that the samp->DTS value appears to wraparound causing mp4box to needlessly drop data. 
I have made a very simple patch in my own fork of gpac, https://github.com/NathanLewis/gpac that appears to fix the problem.

I have .ts input file which reproduces the data loss problem which I am happy to provide to anyone investigating this but cannot make world viewable due to copyright issues.

Thanks,
Nathan

**Comment by jeanlf** [comment]
could you send me your test file ? I'll have a look at  this issue

**Comment by NathanLewis** [comment]
I've attached the .ts file illustrates the problem. We don't get input
streams where the timestamp wraps around very often but it does happen
occasionally.
running MP4Box -add  cub12.ts cub12.mp4  should produce the negative time
sample error.


Thanks!

**Comment by rbouqueau** [comment]
We cannot see your file. Could you upload it to our dropbox? https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Please put the issue number in the file name or description. Thanks.

**Comment by NathanLewis** [comment]
I uploaded to the DropBox location you provided with the description "issue
298"

Thanks,

Nathan

**Comment by jeanlf** [comment]
I believe this file is not conformant, the PCR seems like it's looping but the time between the PCRs at the loop poin tis more than 25 seconds, which is not allowed in the spec. And there is not explicit discontinuity signaled (either through discontinuity flag of continuity counter changes).

Anyway the importer has been fixed to try to cope with such cases, your file should now import properly.

**Comment by rbouqueau** [comment]
By curiosity, how was this file muxed?

**Comment by dholroyd** [comment]
It seems that in trying to come up with the smallest possible example file, the result has ended up not being perfectly representative.  Apologies! I don't think we are expecting to deal with a multi-second gap, in addition to wraparound!

The workflow hitting an issue was basically,
 * make a .ts file from a 'period of interest' within a live stream (that runs 24/7/365)
 * use mp4box to convert the .ts to mp4

Obviously there will be a point in the stream every ~26.5 hours that will contain a wraparound of the 33-bit PCR, and if the 'period of interest' in the above steps happened to contain that point, the output from mp4box would have been truncated.

It seems the example that was provided is also missing 72 seconds of content -- suspiciously, an integer multiple of the 8-second chunks the input .ts is constructed from.  (Maybe not quite the right chunks got assembled in the test asset, or there is actually some other problem in the pre-mp4box workflow!)
