### ISSUE TITLE
Question. Can I add a still image to watermark a manifest?

### ISSUE THREAD

**Issue by alex-rsk** [gpac/gpac#2983]
I want to make forensic watermarking for each connection to my stream.
For that goal, I plan to add a still image with watermark, unequivocally identifying connection,  to my MPEG-DASH manifest.

1. Does GPAC (or MP4Box) support adding  image to manifest with `compositor` filter?  Please give a clue how to achieve it.

2. Can I postprocess a **ready** manifest file with GPAC or MP4Box to append an xml with  image adaptation set, or should I write my own XML handler?

**Comment by rbouqueau** [comment]
1. Compositor is for modifying picture i.e. you'd have to re-encode each time, is it what you want?
2. You should write your XML handler but GPAC may be able to add a block where you would just replace a line.

**Comment by alex-rsk** [comment]
> 1. Compositor is for modifying picture i.e. you'd have to re-encode each time, is it what you want?

I'm making live stream from consequent mp4 files (perhaps you can remember - I have been struggling for this task for a year), so every mp4 file causes new execution of MP4Box.
So probably it is what I want, I think (but I still doubt).

**Comment by rbouqueau** [comment]
I remember your use-case. `compositor` forces you to transcode which is more heavy than modifying the manifest.

**Comment by alex-rsk** [comment]
I appreciated for council.
