### ISSUE TITLE
MP4Client Osmo4 dose not support newer iphone device.

### ISSUE THREAD

**Issue by liujingchao** [gpac/gpac#30]
I had trying install Osmo4 in my iphone5s. It just show in a small are of screen. And  touch the screen the coordinates mismatched. Can you tell me  how to build it for newer iphone device. Thank you

**Comment by jeanlf** [comment]
you may need to rotate the device first, there are still a few bugs in the UI. Works fine here on a 5s and below (not tested on ios8 though)
