### ISSUE TITLE
MP4Box can't process sbgp or sgpd box

### ISSUE THREAD

**Issue by andrewmabc** [gpac/gpac#300]
I do merge two 3gp files by using the following command:

MP4Box file1.3gp -cat file2.3gp -out output.3gp

I found MP4Box can't process sbgp or sgpd box. If there are sbgp and sgpd boxex in file2.3gp, MP4Box will discard those boxes when concatenating two files.

why does MP4Box not process those boxes? Is it a bug?

**Comment by jeanlf** [comment]
Hmm that's strange, these boxes are processed; maybe we loose them during the cat. Could you post your sample files somewhere ?

**Comment by jeanlf** [comment]
now fixed on git (-add , -cat and -split should be fixed) - reopen if needed
