### ISSUE TITLE
rfsrt timescale

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#3014]
I'm trying to solve timescale conversion issue. It seems that `rfsrt` uses ctx->timescale both as an input parameter, an input retrieved with GF_PROP_PID_TIMESCALE, and a way to for the output timescale, cf:

```
{ OFFS(timescale), "default timescale of the PID", GF_PROP_UINT, "1000", NULL, GF_FS_ARG_HINT_ADVANCED},
```

and 

```
	ts = gf_timestamp_rescale(ts, 1000, ctx->timescale);
	duration = (u32) gf_timestamp_rescale(duration, 1000, ctx->timescale);
```

My typical graph looks like:

```
fin (src=file.ts) (idx=1)
-(PID file.ts) m2tsdmx (dyn_idx=5)
--(PID P1V2) rfnalu (dyn_idx=6)
---(PID P1V2) ccdec (idx=2)
----(PID P1V2) rfsrt (dyn_idx=8)
-----(PID P1V2) tx3g2vtt (idx=3)
------(PID P1V2) txtin (dyn_idx=9)
-------(PID P1V2) inspect (idx=4)
```

Is there a reason to do so? Are some generated data tight to timescale=1000? Should we decorrelate the input and output timescales in the context?

**Comment by rbouqueau** [comment]
@jeanlf any idea ?

**Comment by jeanlf** [comment]
this was a mistake, timestamps shouldn't be rescaled in this case. Now fixed on master

**Comment by rbouqueau** [comment]
It works, thank you!
