### ISSUE TITLE
Using URL as input causes inconsistent segment duration warning - the same files from disk have no such issue

### ISSUE THREAD

**Issue by arkus7** [gpac/gpac#3026]
# Issue
When I pass the URL as the input files to create HLS manifest with `segdur=2` `gpac` prints warning from `Dasher` filter that it will change the target duration to 4 (or sometimes 7), even though all of the input files have segment duration of 2 seconds.

```
[Dasher] Changing HLS target duration from 2 to 4, either increase the segment duration or re-encode the content
[Dasher] Changing HLS target duration from 4 to 4, either increase the segment duration or re-encode the content
[Dasher] Changing HLS target duration from 4 to 4, either increase the segment duration or re-encode the content
[Dasher] Changing HLS target duration from 2 to 4, either increase the segment duration or re-encode the content
[Dasher] Changing HLS target duration from 4 to 4, either increase the segment duration or re-encode the content
[Dasher] Changing HLS target duration from 4 to 4, either increase the segment duration or re-encode the content
[Dasher] Changing HLS target duration from 4 to 7, either increase the segment duration or re-encode the content
```

This happens only when I load the files via URL. When I use the same files but loaded from the disk, no such warning gets printed.

## Example files

Files I've been using for testing:
- [v.mp4](https://www.mediafire.com/file/5qm0r2f8omlaehs/v.mp4/file) - 1080p video
- [a.mp4](https://www.mediafire.com/file/45xpi1eg3bdyjs0/a.mp4/file) - AAC audio

Here are also `MP4Box <file> -diso` outputs which I've used to check if the files have proper fragment duration.
- [v_info.xml](https://www.mediafire.com/file/d3weaqaiu8sn1ws/v_info.xml/file)
- [a_info.xml](https://www.mediafire.com/file/l1o5wwsfzuamkn5/a_info.xml/file)

### Using URL as input
Command (loading from URL, `localhost:3033` is a [simple-http-server](https://github.com/TheWaWaR/simple-http-server) but the same issue appears when loading files from S3):
```
gpac -r -i 'http://localhost:3033/v.mp4:gpac:#HLSPL=1080.m3u8:FID=D1' \
     -i 'http://localhost:3033/a.mp4:gpac:#HLSPL=audio.m3u8:FID=D2' \
     -o "master.m3u8:gpac:sigfrag:profile=onDemand:segdur=2"
```

Output
```
[15:30:58.471Z] GPAC Session Status: mem          0 kb CPU  0
v.mp4 (httpin): v.mp4:          4481778 /         4481778 (100.00)  1201992 kbps
a.mp4 (httpin): a.mp4:           491862 /          491862 (100.00)   390521 kbps
manifest_m3u8 (fout): audio.m3u8: done - wrote 718 bytes
v.mp4 (mp4dmx): Visual (AOM AV1 Video)        900 pck 99392.60 FPS - EOS
manifest_m3u8 (dasher): P1 AS#1.1(V) done (15 segs) AS#2.1(A) done (12 segs)
a.mp4 (mp4dmx): Audio (MPEG-4 AAC Audio)       1293 pck 818354.43 FPS - EOS
Active filters: 6

Logs:
[15:30:58.465Z] [Dasher] Changing HLS target duration from 2 to 4, either increase the segment duration or re-encode the content
[15:30:58.465Z] [Dasher] Changing HLS target duration from 4 to 4, either increase the segment duration or re-encode the content
[15:30:58.467Z] [Dasher] Changing HLS target duration from 2 to 4, either increase the segment duration or re-encode the content
```

### Using local files as input

Command (local files):
```
gpac -r -i 'v.mp4:gpac:#HLSPL=1080.m3u8:FID=D1' \
     -i 'a.mp4:gpac:#HLSPL=audio.m3u8:FID=D2' \
     -o "master.m3u8:gpac:sigfrag:profile=onDemand:segdur=2"
```

Output:
```
[15:30:09.532Z] GPAC Session Status: mem          0 kb CPU  0
v.mp4 (fin): v.mp4: EOS (dispatch canceled after 5000 b, file size 4481778 b)
a.mp4 (fin): a.mp4: EOS (dispatch canceled after 5000 b, file size 491862 b)
manifest_m3u8 (fout): audio.m3u8: done - wrote 932 bytes
v.mp4 (mp4dmx): Visual (AOM AV1 Video)        900 pck 100211.56 FPS - EOS
a.mp4 (mp4dmx): Audio (MPEG-4 AAC Audio)       1293 pck 408918.41 FPS - EOS
manifest_m3u8 (dasher): P1 AS#1.1(V) done (16 segs) AS#2.1(A) done (16 segs)
Active filters: 6
```

I've tested this on versions:
- [x] 2.4-revrelease
- [x] 2.5-DEV-rev810-g9ae3c074-master

Platform: macOS 15.1 (24B83), M1 Max

---

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

**Comment by jeanlf** [comment]
The culprit was using `sigfrag` when reading from non-DASH/HLS inputs. Now fixed on master.

Thanks for the detailed report and the files.
