### ISSUE TITLE
BitRate Element missing in the MulticastGatewayConfiguration (mABR)

### ISSUE THREAD

**Issue by ypo** [gpac/gpac#3028]
In the Multicast Gateway Configuration Instance document, the element  `<MulticastGatewayConfigurationTransportSession> `shall contain a `<BitRate>` element

The mABR XML schema is the following

```
<xs:complexType name="BaseMulticastTransportSessionType>
<xs:sequence>
...
<xs:element name="BitRate" type="BitRateType"/>
...
</xs:sequence>
</xs:complexType>
```

**Comment by jeanlf** [comment]
Indeed, now on master - thanks for the report.
