### ISSUE TITLE
MPD created with MP4BOX work with MP4Client but is not working with dash.js

### ISSUE THREAD

**Issue by leandropjp** [gpac/gpac#303]
Hi, I am trying to create a live stream. I am using the follow command:

MP4Box -dash 1000 -profile live video.mp4

With MP4Client the MPD works fine but when I try to use with dash.js form dash-if  I am receiving this log and the video does not start.

[Log] [dash.js 1.5.1] new MediaPlayer instance has been created  (dash.all.js, line 10)
[Log] Playback initiated!  (dash.all.js, line 10)
[Log] Parsing complete: ( xml2json: 2ms, objectiron: 2ms, total: 0.004s)  (dash.all.js, line 10)
[Log] Manifest has been refreshed at Thu Oct 29 2015 12:46:41 GMT-0300 (BRT)[1446133601295]   (dash.all.js, line 10)
[Log] MediaSource is open!  (dash.all.js, line 10)
[Log] [object Event]  (dash.all.js, line 10)
[Log] Duration successfully set to: 269.933  (dash.all.js, line 10)
[Log] Added 0 inline events  (dash.all.js, line 10)
[Log] video codec: video/mp4;codecs="avc3.428015"  (dash.all.js, line 10)
[Log] [video] stop  (dash.all.js, line 10)
[Log] No audio data.  (dash.all.js, line 10)
[Log] No text data.  (dash.all.js, line 10)
[Log] No fragmentedText data.  (dash.all.js, line 10)
[Log] No muxed data.  (dash.all.js, line 10)
[Log] [video] start  (dash.all.js, line 10)
[Log] loaded video:Initialization Segment:NaN (200, 0ms, 347ms)  (dash.all.js, line 10)
[Log] [video] Initialization finished loading  (dash.all.js, line 10)

In this case I separated the video from the audio but I am just using the video.

**Comment by rbouqueau** [comment]
What does the DASH IF conformance checker say? http://www.dashif.org/conformance.html

**Comment by leandropjp** [comment]
Everything is ok.
![screen shot 2015-10-29 at 2 50 21 pm](https://cloud.githubusercontent.com/assets/4974419/10827288/c45d8ace-7e4c-11e5-9671-6f69ffd61d6e.png)

This is my MPD file.
<?xml version="1.0"?>

<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H4M29.933S" maxSegmentDuration="PT0H0M1.933S" profiles="urn:mpeg:dash:profile:isoff-live:2011">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>video_dash.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H4M29.933S">
  <AdaptationSet segmentAlignment="true" maxWidth="320" maxHeight="240" maxFrameRate="15" par="1:1" lang="und">
   <Representation id="1" mimeType="video/mp4" codecs="avc3.428015" width="320" height="240" frameRate="15" sar="1:1" startWithSAP="1" bandwidth="247271">
    <SegmentTemplate timescale="15000" media="video_dash$Number$.m4s" startNumber="1" duration="14881" initialization="video_dashinit.mp4"/>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>

**Comment by rbouqueau** [comment]
By any chance did you try to report to the dash.js team?

**Comment by leandropjp** [comment]
I will try with them as well. First I put the question here because I saw others issue with dash.js and mp4box here. Do you believe that the problem is with the dash.js?

**Comment by rbouqueau** [comment]
Not necessarily. It could also be the way your content is packaged.

You can find command-lines at:
http://blog.streamroot.io/encode-multi-bitrate-videos-mpeg-dash-mse-based-media-players/
http://www.gpac-licensing.com/2014/08/21/ibc-2014-dash-avc264-support-in-gpac/

**Comment by leandropjp** [comment]
Thank you @rbouqueau . When I use -bs-switching no the dash runs the mpd.
