### ISSUE TITLE
PresentationManifestLocator@transportObjectURI shall be present in the MGC (mABR)

### ISSUE THREAD

**Issue by ypo** [gpac/gpac#3030]
According to 8.3.5 Multicast gateway configuration transport session (A176r6)

"The multicast transport object URI of each presentation manifest shall be determined by the value of the PresentationManifestLocator@transportObjectURI attribute"

"The attribute **shall always** be present in multicast gateway configuration instance document"

```
 <MulticastSession serviceIdentifier="gpac.io:dvb-mabr:service:0" contentPlaybackAvailabilityOffset="PT4S">
    <PresentationManifestLocator manifestId="gpac_mani_serv_0" contentType="application/dash+xml" transportObjectURI="file://Manifest.mpd">Manifest.mpd
  </PresentationManifestLocator>
```

**Comment by jeanlf** [comment]
Indeed, now fixed on master - thanks for the report.

**Comment by ypo** [comment]
Thanks for the update, 

The definition of `@transportObjectURI` is the following :

_"Multicast transport object URI to be used when conveying this presentation manifest in an in-band carousel of multicast transport objects."_

I was expecting that for the FLUTE implementation, the @transportObjectURI and FDT Content-Location are matching, do you have a different interpretation ?

`transportObjectURI="tag:abr.gpac.io;2024/gpac_mani_serv_0"`

`  <File FEC-OTI-FEC-Encoding-ID="0" FEC-OTI-Maximum-Source-Block-Length="65535" Content-Length="1910" Transfer-Length="1910" Content-Location="Manifest.mpd" Content-Type="application/dash+xml" FEC-OTI-Encoding-Symbol-Length="1428" TOI="2" Content-MD5="SaOb3z1I9HUJqmQ6rJ7qNA=="/>`

**Comment by jeanlf** [comment]
I thought the child text of the PresentationManifestLocator was conveying this, the annex A is a bit confusing here. I'll see what I can do

**Comment by ypo** [comment]
> I thought the child text of the PresentationManifestLocator was conveying this, the annex A is a bit confusing here. I'll see what I can do

I agree it's confusing, I think the child text is conveying the location for unicast retrieval / repair, it's define in Section 10.2.2.2

_"When the PresentationManifestLocator element is carried in a multicast gateway configuration:

If the presentation manifest is available for unicast retrieval and/or repair via reference point A, the element
content shall be its URL on the Content hosting function."_

**Comment by jeanlf** [comment]
Should be better now , could you cross-check ?

Note that we don't use URL<->URI remapping for the time being

**Comment by ypo** [comment]
Yes, it looks better for the transportObjectURI

Another question, do you map the PresentationManifestLocator text to the input source ? 
Because the port in the URL is missing

I'm using gpac like this :

`gpac -i http://127.0.0.1:8889/livesim2/B2/Manifest.mpd`

Then I see the URL without the port
`<PresentationManifestLocator>http://127.0.0.1/livesim2/B2/Manifest.mpd</PresentationManifestLocator>`
