### ISSUE TITLE
MPD and Init segments  should be conveyed in MulticastTransportSession instead of MulticastGatewayConfigurationTransportSession (mABR)

### ISSUE THREAD

**Issue by ypo** [gpac/gpac#3031]
### 1- Init Segment

Not clear if it is mandatory, but Init Segment of the Representation should be conveyed in the same carousel as the AV Segments of that representation. 
The element `InitSegments`  should be added to the MGC MulticastTransportSession  to indicate that Init Segment are arouselled.  

See Section  10.2.3.14.2 of  ETSI TS 103 769 V1.2.1

### 2- MPD

 Not clear if it is mandatory as well, but  MPD should conveyed  in a single (could be multiple)  MulticastTransportSession.
The element `PresentationManifests` should be added to the MGC MulticastTransportSession  to indicate that MPD is carouselled in this session.

See Section  10.2.3.14.1  and Annex G.1.3 of  ETSI TS 103 769 V1.2.1

### 3- Example

MulticastTransportSession signaling both the carouselling of MPD (PresentationManifests) and Init Segment

```
<MulticastTransportSession sessionIdleTimeout="60000" transportSecurity="none" id="10" transmissionMode="resource">
      <TransportProtocol protocolIdentifier="urn:dvb:metadata:cs:MulticastTransportProtocolCS:2019:FLUTE" protocolVersion="1"/>
      <EndpointAddress>
        <NetworkDestinationGroupAddress>234.1.1.1</NetworkDestinationGroupAddress>
        <TransportDestinationPort>1235</TransportDestinationPort>
        <MediaTransportSessionIdentifier>10</MediaTransportSessionIdentifier>
      </EndpointAddress>
      <BitRate average="6909104" maximum="6909104"/>
      <UnicastRepairParameters transportObjectReceptionTimeout="50" fixedBackOffPeriod="10" randomBackOffPeriod="20"/>
      <ServiceComponentIdentifier
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" manifestIdRef="gpac_mani_serv_0" xsi:type="DASHComponentIdentifierType" periodIdentifier="P0" adaptationSetIdentifier="1" representationIdentifier="HD"/>
      <ObjectCarousel>
            <PresentationManifests targetAcquisitionLatency="PT2S"/>
           <InitSegments targetAcquisitionLatency="PT2S"/>
      </ObjectCarousel>
      </MulticastTransportSession>
```  

Transporting the MPD and Init segment in the MulticastTransportSession makes sense when multiple services are conveyed in multiple MulticastSession. This allows the mABR Gateway to selectively listen to a specific service without needing to receive manifests from other services

**Comment by jeanlf** [comment]
This depends on use cases and AFAIK this is not mandatory nor explicitly stated in the spec.
You can enable this by using [:use_inband](https://wiki.gpac.io/Filters/routeout/#use_inband) option.
 
The carousel info was indeed missing in MulticastTransportSession for inband mode, now fixed o master.

**Comment by ypo** [comment]
Thanks for the :use_inband tips,

I took the latest, it looks like there is a  " missing to close the serviceIdRef attribute

`<InitSegments serviceIdRef="gpac.io:dvb-mabr:service:0 targetAcquisitionLatency="PT1S"/>`

**Comment by jeanlf** [comment]
indeed thanks for the cross-check, now fixed
