### ISSUE TITLE
FLUTE FDTs  are transmitted expired (mABR)

### ISSUE THREAD

**Issue by ypo** [gpac/gpac#3034]
FDT Expires attribute is statically set to 3916741152 (NTP timestamp, 12/02/2024, 16:39:12),  see [out_route.c](https://github.com/gpac/gpac/blob/83429541ec75cd92d8aa7d0cce6e64f79ae25fd1/src/filters/out_route.c#L1612C1-L1612C117)

According to FLUTE RFC, an FDT Instance is valid until its expiration time, meaning that FLUTE receiver might consider all FDTs generated by gpac as invalid.

I would also recommend to encode the EXT_TIME LCT Extension inside packets transporting FDTs as well. It permits to FLUTE receiver to determine the time offset between the sender and receiver.

**Comment by jeanlf** [comment]
Thanks for the report and suggestion, now in master.
