### ISSUE TITLE
having a problem when compiling GPAC on Mac...

### ISSUE THREAD

**Issue by zsuo** [gpac/gpac#304]
after I finish the last procedure of README_IOS.TXT, it shows that:

** BUILD FAILED **

The following build commands failed:
	CompileC build/gpac4ios.build/Release-iphoneos/libgpac_static.build/Objects-normal/armv7/faad_dec.o /Users/zihan/Desktop/gpac/modules/aac_in/faad_dec.c normal armv7 c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

could you kindly tell me how to fix this problem? thanks a lot~

**Comment by rbouqueau** [comment]
Before anyone anwsers this issue, I'd like to precise that 90% of the issues are solved because we are able to reproduce the problem. So could you provide more info about your environment? (OS version, build, GPAC version, etc.)

Please read http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by zsuo** [comment]
Thanks, now I will describe my problem in detail. I downloaded the gpac open source in this webpage:https://sourceforge.net/p/gpac/code/HEAD/tree/trunk/
And I finish the procedures in README_IOS. After the last procedure, I found that it first showed to me :
"gpac/revision.h" is not found

So, I used the revision.h in android package to continue my compiling.
In this revision.h file, the codes are:

#define GPAC_GIT_REVISION "676-g8917b91-master”


Then I compile again, it showed to me that in the file isom_store.c, [cid:C809857D-653C-42A4-9AAD-B50F0665A29D]

which is very strange because the “)” is definitely there.

Could you tell me how to fix this problem?
Thanks a lot.

发件人: Romain Bouqueau
答复: gpac/gpac
日期: 2015年10月30日 星期五 下午4:14
至: gpac/gpac
抄送: 索子晗
主题: Re: [gpac] having a problem when compiling GPAC on Mac... (#304)

tc

**Comment by rbouqueau** [comment]
> https://sourceforge.net/p/gpac/code/HEAD/tree/trunk/

Use the code from github. The sourceforge is deprecated: http://gpac.io/2015/01/27/leaving-svn-and-sourceforge-using-git-and-github/

For your information, our buildbot builds the code for each revision. So I expect it to work :)

**Comment by zsuo** [comment]
You mean on this page? https://github.com/gpac/gpac

发件人: Romain Bouqueau
答复: gpac/gpac
日期: 2015年10月30日 星期五 下午5:30
至: gpac/gpac
抄送: 索子晗
主题: Re: [gpac] having a problem when compiling GPAC on Mac... (#304)


https://sourceforge.net/p/gpac/code/HEAD/tree/trunk/

Use the code from github. The sourceforge is deprecated: http://gpac.io/2015/01/27/leaving-svn-and-sourceforge-using-git-and-github/

For your information, our buildbot builds the code for each revision. So I expect it to work :)

**Comment by rbouqueau** [comment]
Yes I do.

**Comment by zsuo** [comment]
Sorry，when I use the code from github. The problem also exists.
It always tells me that ‘gpac/revision.h’file not found.
Could you tell me how to fix this problem?
../../include/gpac/version.h:43:10: fatal error: 'gpac/revision.h' file not

      found

#include <gpac/revision.h>

         ^

1 error generated.

发件人: Romain Bouqueau
答复: gpac/gpac
日期: 2015年10月30日 星期五 下午5:30
至: gpac/gpac
抄送: 索子晗
主题: Re: [gpac] having a problem when compiling GPAC on Mac... (#304)


https://sourceforge.net/p/gpac/code/HEAD/tree/trunk/

Use the code from github. The sourceforge is deprecated: http://gpac.io/2015/01/27/leaving-svn-and-sourceforge-using-git-and-github/

For your information, our buildbot builds the code for each revision. So I expect it to work :)

**Comment by jeanlf** [comment]
you first need to configure GPAC on your mac, using ./configure
this will produce the revision.h missing (not produced automatically by the ios xcode project at the current time) - We'll fic this asap

**Comment by zsuo** [comment]
Sorry, I didn’t get your point. Could you kindly show me how to produce the revision.h?

发件人: jeanlf
答复: gpac/gpac
日期: 2015年11月2日 星期一 下午3:16
至: gpac/gpac
抄送: 索子晗
主题: Re: [gpac] having a problem when compiling GPAC on Mac... (#304)


you first need to configure GPAC on your mac, using ./configure
this will produce the revision.h missing (not produced automatically by the ios xcode project at the current time) - We'll fic this asap

**Comment by jeanlf** [comment]
open terminal
go to root dir of gpac source code
type "./configure"
once done, open gpac/build/xcode/gpac4ios


warning: not all extra libs needed by gpac for iOS are available in the gpac_extra_lib package, you may need to either compile the missing ones yourself or tweak the configuration.h file of gpac to not compile against these libraries

**Comment by zsuo** [comment]
Hi, thanks a lot~
However, after I configure and open the guac/build/xcode/gpac4ios. It shows that “faad.h” is not found.


/Users/zihan/Desktop/gpac-master/modules/aac_in/faad_dec.c:40:10: fatal error:

      'faad.h' file not found

#include <faad.h>

         ^

1 error generated.


Could you kindly tell me how to solve this problem?

发件人: jeanlf
答复: gpac/gpac
日期: 2015年11月2日 星期一 下午3:55
至: gpac/gpac
抄送: 索子晗
主题: Re: [gpac] having a problem when compiling GPAC on Mac... (#304)


open terminal
go to root dir of gpac source code
type "./configure"
once done, open gpac/build/xcode/gpac4ios

warning: not all extra libs needed by gpac for iOS are available in the gpac_extra_lib package, you may need to either compile the missing ones yourself or tweak the configuration.h file of gpac to not compile against these libraries

**Comment by zsuo** [comment]
Hi,after I follow your steps, I still couldn’t compile the file successfully. By the way, I have already downloaded the extra_libs from here: https://sourceforge.net/p/gpac/code/HEAD/tree/trunk/gpac_extra_libs/

But the terminal said that:/Users/zihan/Desktop/gpac/modules/aac_in/faad_dec.c:40:10: fatal error:

      'faad.h' file not found

#include <faad.h>

 But I found that this file exists in the extra_lib/include folder, I wonder what’s wrong with that~

Thanks a lot for your answer~

发件人: jeanlf
答复: gpac/gpac
日期: 2015年11月2日 星期一 下午3:55
至: gpac/gpac
抄送: 索子晗
主题: Re: [gpac] having a problem when compiling GPAC on Mac... (#304)


open terminal
go to root dir of gpac source code
type "./configure"
once done, open gpac/build/xcode/gpac4ios

warning: not all extra libs needed by gpac for iOS are available in the gpac_extra_lib package, you may need to either compile the missing ones yourself or tweak the configuration.h file of gpac to not compile against these libraries

**Comment by jeanlf** [comment]
for mac please follow the instructions here :
https://gpac.wp.mines-telecom.fr/2011/05/02/compiling-gpac-for-macos-x/

**Comment by zsuo** [comment]
sorry, I notice that the link you gave me is for macos X 10.5 and 10.6, but mine is 10.11, does it works?

**Comment by jeanlf** [comment]
yes except maybe SDL2 support which is now called SDL2 or libSDL2 instead of SDL-devel

**Comment by zsuo** [comment]
Sorry, I met another problem this time, after compiling in the last step:

How to build GPAC for iOS
=========================

Tested revision: 3239
Tested XCode (SDK): 3.2.6 (4.3)

To compile GPAC in command-line mode, please execute the following steps:

1) Check out the GPAC git repository:
   "git clone https://github.com/gpac/gpac"

2) Get the "gpac_extra_libs.zip" file from:
https://sourceforge.net/p/gpac/code/HEAD/tree/trunk/gpac_extra_libs/

Unzip it in its current directory (ie not a subfolder) so that you have the following directory tree:
   trunk/
      gpac/
         ...
      gpac_extra_libs/
         a52dec/
         AMR_NB/
         ...

3) Compile gpac dependencies (zlib, faad, libpng etc):
   execute "gpac_extra_libs/build/xcode_ios/generate_extra_libs.sh" script.
   execute "gpac_extra_libs/SDL_iOS/generate_SDL.sh

4) Check all gpac dependencies have been successfully compiled:
   $> ls gpac_extra_libs/lib/iOS
      libSDL2.a libglue.a libfaad.a libfreetype.a libjpeg.a libjs.a libmad.a libpng.a

5) Copy the extra_libs to the right place:
   if you checked out as mentionned in 1), execute the "gpac_extra_libs/CopyLibs2Public4iOS.sh" script.
   Otherwise copy manually the libs to the gpac/extra_lib/lib/ios directory.

6) Compile GPAC:
   execute /gpac/configure to generate include/gpac/revision.h
   execute the "gpac/build/xcode/generate_ios.sh" script.
   The script checks that all files have been compiled, print an error message if needed.
   Otherwise it generats a .tar.gz archive into the gpac/bin/iOS directory.

I found that there are many libraries that already exists in extra_lib folder, however, when compiling in Xcode, it doesn’t “see” the file and tells that these libraries can not find these libs.

 Desktop/gpac-master/modules/sdl_out/sdl_out.h:35:10: fatal error:

      'SDL.h' file not found

#include <SDL.h>

         ^

1 error generated.


Can you kindly tell me how to deal with that?


Best regards

发件人: jeanlf
答复: gpac/gpac
日期: 2015年11月9日 星期一 下午2:09
至: gpac/gpac
抄送: 索子晗
主题: Re: [gpac] having a problem when compiling GPAC on Mac... (#304)


yes except maybe SDL2 support which is now called SDL2 or libSDL2 instead of SDL-devel

**Comment by zsuo** [comment]
Hi, I have solved this problem by adding these .h files into the header search paths. However, after that it tells me that “winsock.h and windows.h.“ these two .h files don’t exist.
And actually, they truly do not exist in this folder. Can you kindly tell me where to find these .h files?

发件人: 索子晗
日期: 2015年11月10日 星期二 下午1:39
至: gpac/gpac
主题: Re: [gpac] having a problem when compiling GPAC on Mac... (#304)

Sorry, I met another problem this time, after compiling in the last step:

How to build GPAC for iOS
=========================

Tested revision: 3239
Tested XCode (SDK): 3.2.6 (4.3)

To compile GPAC in command-line mode, please execute the following steps:

1) Check out the GPAC git repository:
   "git clone https://github.com/gpac/gpac"

2) Get the "gpac_extra_libs.zip" file from:
https://sourceforge.net/p/gpac/code/HEAD/tree/trunk/gpac_extra_libs/

Unzip it in its current directory (ie not a subfolder) so that you have the following directory tree:
   trunk/
      gpac/
         ...
      gpac_extra_libs/
         a52dec/
         AMR_NB/
         ...

3) Compile gpac dependencies (zlib, faad, libpng etc):
   execute "gpac_extra_libs/build/xcode_ios/generate_extra_libs.sh" script.
   execute "gpac_extra_libs/SDL_iOS/generate_SDL.sh

4) Check all gpac dependencies have been successfully compiled:
   $> ls gpac_extra_libs/lib/iOS
      libSDL2.a libglue.a libfaad.a libfreetype.a libjpeg.a libjs.a libmad.a libpng.a

5) Copy the extra_libs to the right place:
   if you checked out as mentionned in 1), execute the "gpac_extra_libs/CopyLibs2Public4iOS.sh" script.
   Otherwise copy manually the libs to the gpac/extra_lib/lib/ios directory.

6) Compile GPAC:
   execute /gpac/configure to generate include/gpac/revision.h
   execute the "gpac/build/xcode/generate_ios.sh" script.
   The script checks that all files have been compiled, print an error message if needed.
   Otherwise it generats a .tar.gz archive into the gpac/bin/iOS directory.

I found that there are many libraries that already exists in extra_lib folder, however, when compiling in Xcode, it doesn’t “see” the file and tells that these libraries can not find these libs.

 Desktop/gpac-master/modules/sdl_out/sdl_out.h:35:10: fatal error:

      'SDL.h' file not found

#include <SDL.h>

         ^

1 error generated.


Can you kindly tell me how to deal with that?


Best regards

发件人: jeanlf
答复: gpac/gpac
日期: 2015年11月9日 星期一 下午2:09
至: gpac/gpac
抄送: 索子晗
主题: Re: [gpac] having a problem when compiling GPAC on Mac... (#304)


yes except maybe SDL2 support which is now called SDL2 or libSDL2 instead of SDL-devel

**Comment by zsuo** [comment]
Hi, I have solved this problem by adding these .h files into the header search paths. However, after that it tells me that “winsock.h and windows.h.“ these two .h files don’t exist.
And actually, they truly do not exist in this folder. Can you kindly tell me where to find these .h files?

发件人: 索子晗
日期: 2015年11月10日 星期二 下午1:39
至: gpac/gpac
主题: Re: [gpac] having a problem when compiling GPAC on Mac... (#304)

Sorry, I met another problem this time, after compiling in the last step:

How to build GPAC for iOS
=========================

Tested revision: 3239
Tested XCode (SDK): 3.2.6 (4.3)

To compile GPAC in command-line mode, please execute the following steps:

1) Check out the GPAC git repository:
   "git clone https://github.com/gpac/gpac"

2) Get the "gpac_extra_libs.zip" file from:
https://sourceforge.net/p/gpac/code/HEAD/tree/trunk/gpac_extra_libs/

Unzip it in its current directory (ie not a subfolder) so that you have the following directory tree:
   trunk/
      gpac/
         ...
      gpac_extra_libs/
         a52dec/
         AMR_NB/
         ...

3) Compile gpac dependencies (zlib, faad, libpng etc):
   execute "gpac_extra_libs/build/xcode_ios/generate_extra_libs.sh" script.
   execute "gpac_extra_libs/SDL_iOS/generate_SDL.sh

4) Check all gpac dependencies have been successfully compiled:
   $> ls gpac_extra_libs/lib/iOS
      libSDL2.a libglue.a libfaad.a libfreetype.a libjpeg.a libjs.a libmad.a libpng.a

5) Copy the extra_libs to the right place:
   if you checked out as mentionned in 1), execute the "gpac_extra_libs/CopyLibs2Public4iOS.sh" script.
   Otherwise copy manually the libs to the gpac/extra_lib/lib/ios directory.

6) Compile GPAC:
   execute /gpac/configure to generate include/gpac/revision.h
   execute the "gpac/build/xcode/generate_ios.sh" script.
   The script checks that all files have been compiled, print an error message if needed.
   Otherwise it generats a .tar.gz archive into the gpac/bin/iOS directory.

I found that there are many libraries that already exists in extra_lib folder, however, when compiling in Xcode, it doesn’t “see” the file and tells that these libraries can not find these libs.

 Desktop/gpac-master/modules/sdl_out/sdl_out.h:35:10: fatal error:

      'SDL.h' file not found

#include <SDL.h>

         ^

1 error generated.


Can you kindly tell me how to deal with that?


Best regards

发件人: jeanlf
答复: gpac/gpac
日期: 2015年11月9日 星期一 下午2:09
至: gpac/gpac
抄送: 索子晗
主题: Re: [gpac] having a problem when compiling GPAC on Mac... (#304)


yes except maybe SDL2 support which is now called SDL2 or libSDL2 instead of SDL-devel

**Comment by jiapei100** [comment]
yes... 
**gpac SDL2 support**  required...
