### ISSUE TITLE
Question about AudioSampleEntryV1 (GF_IMPORT_AUDIO_SAMPLE_ENTRY_v1_MPEG) 

### ISSUE THREAD

**Issue by ohjiwoo123** [gpac/gpac#3040]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

Hello, I wonder that how to use AudioSampleEntryV1.    
In the ISO_IEC_14996-12 (ISOBMFF),
They mentioned that AudioSampleEntryV1 is used,
```
when it is desired to indicate an audio sampling rate greater than the value that can be represented in the samplerate field, the following may be used
```

I think that, If Audio SampleRate is set 96000, It should be used AudioSampleEntryV1.   
In gpac module, How to use `AudioSampleEntryV1` ?   
Could you let me know code level?   

I search that Based on `GF_IMPORT_AUDIO_SAMPLE_ENTRY_v1_MPEG`   
But, I failed to find.     

I tried below code    
```
# Skip making Audio Track 
# SAMPLINGRATE = 96000
gf_isom_new_mpeg4_description(file_ptr, track_id, stream_desc_ptr, NULL, NULL, &sample_description_index)
gf_isom_set_audio_info(file_ptr, track_id, sample_description_index, SAMPLINGRATE, 1, BPS, GF_IMPORT_AUDIO_SAMPLE_ENTRY_v1_MPEG)
```

But Audio SampleRates in mp4a box is still 30464, not 96000 
<img width="1547" alt="30464" src="https://github.com/user-attachments/assets/453651a7-306b-42ae-bd97-2b67e2308040">   

(It means that AudioSampleEntryV1 is not applied, AudioSampleEntryV0 is used. )

**Comment by jeanlf** [comment]
Support for high sample rate was simply missing, now added on master. Note that this is independent from V0 or V1, both boxes use 16.16 format for the default sample rate , so a 'srat' box is needed for proper signaling.

Thanks for the report and analysis.
