### ISSUE TITLE
MP4Box - incorrect codec string generation

### ISSUE THREAD

**Issue by Ashkael0** [gpac/gpac#3048]
Hello, I was experimenting with MP4Box DASH segment creation and I noticed that the codec string in the .mpd file is wrong.

I ran the following commands on [this](https://www.mediafire.com/file/j5vujome9h6u2wm/mp4box_test.mp4/file) file
```bash
MP4Box -dash 2000 \
  -frag 2000 \
  -rap \
  -segment-name segments/mp4box_test_ \
  -out manifest.mpd \
  mp4box_test.mp4#video \
  mp4box_test.mp4#audio
```

The resulting [.mpd file](https://www.mediafire.com/file/3q883ygodf5fg6a/mp4box_test.mpd/file) says that my codec is `codecs="av01.0.01M.08.0.111.01.01.01.0"`, however, it should be `codecs="av01.0.01M.08.0.110.01.01.01.0"`.

Pasting them right underneath each other so its easier to see the difference:
```txt
av01.P.LLT.DD.M.CCC.cp.tc.mc.F --> codec string syntax
av01.0.01M.08.0.111.01.01.01.0 --> codec string from MP4Box
av01.0.01M.08.0.110.01.01.01.0 --> correct codec string
```
The difference is in the last digit of `CCC` component. The `CCC` indicates the chroma subsampling and the last digit is monochrome flag, so if the video is not monochromatic, it should always be 0. Here is the link to page 131 of av1 specification in which this is mentioned: https://aomediacodec.github.io/av1-spec/av1-spec.pdf#page=131

Interestingly, the av1 codec string has two monochrome flags, one is `M` and the other one is the last digit of `CCC` and for some reason MP4Box gets the `M` correct, but the `CCC` wrong.

This is the data snippet I get when running `MP4Box -info mp4box_test.mp4` command. Both highlighted values act as monochrome flags and should be the same:
![image](https://github.com/user-attachments/assets/9ff8d202-e710-4fbd-82a8-ead04a24758b)

[MDN documentation](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/codecs_parameter#av1) about av1 codec syntax.

**Comment by rbouqueau** [comment]
The monochrome is the 0 before. The 110 you're pointing at is "The chromaSubsampling parameter value, represented by a three-digit decimal, SHALL have its first digit equal to subsampling_x and its second digit equal to subsampling_y. If both subsampling_x and subsampling_y are set to 1, then the third digit SHALL be equal to chroma_sample_position, otherwise it SHALL be set to 0." ([source](https://aomediacodec.github.io/av1-isobmff/v1.3.0.html#codecsparam)).

What do you think?

**Comment by Ashkael0** [comment]
I've seen that part, but I believe they have some logical contradictions on their documentation about how they use the `subsampling_x`, `subsampling_y`, and `chroma_sample_position` values (or I'm just drastically misunderstanding something).

For example, the [5.5.2 Color config syntax](https://aomediacodec.github.io/av1-spec/av1-spec.pdf#page=44) has this:
```
if ( mono_chrome ) {
    color_rangecolor_range
    subsampling_x = 1
    subsampling_y = 1
    chroma_sample_position = CSP_UNKNOWN
    separate_uv_delta_q = 0
    return
```
If my understanding is correct, it doesn't make sense to have subsampling values as `1` for monochromatic images, as monochromatic images should have no chroma samples to position, only luma samples.

Then later in the same section [5.5.2 Color config syntax](https://aomediacodec.github.io/av1-spec/av1-spec.pdf#page=44) they say this:
```
if ( subsampling_x && subsampling_y ) {
    chroma_sample_position
}
```
which confirms what you cited in your message, however, when you scroll down to [page 131](https://aomediacodec.github.io/av1-spec/av1-spec.pdf#page=131), they seem to say that `subsampling_x`, `subsampling_y`, and `mono_chrome` are what is specifying the chroma subsampling format:
![image](https://github.com/user-attachments/assets/26adbf8b-0e77-4558-981a-8ccd6bdb40fa)

I'm guessing that [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/codecs_parameter#av1) copied this table when they explained av1 codec parameter string. This is the part which talks about chroma subsampling:
![image](https://github.com/user-attachments/assets/b0a00f87-6661-449a-b269-d6336d817170)

I mainly base my reasoning on this table, and [MDN](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/codecs_parameter#av1) also says that "The default value is 110 (4:2:0 chroma subsampling).", and since my video has `yuv420` pixel format, I picked `110` as being the real value, but to be honest, at this point I'm not sure anymore, since the av1 specification either doesn't make sense, or am I severely misunderstanding something.

**Comment by rbouqueau** [comment]
Yes 'chroma subsampling format' is how chroma channels are subsampled (horizontally, vertically, or both). 'chroma_sample_position' is where the chroma value was sampled(vertical, colocated, ...). Subtle difference indeed.

**Comment by Ashkael0** [comment]
Thank you for taking your time to clear things up for me.
