### ISSUE TITLE
Error "bit out of range 0 - FD_SETSIZE on fd_set"

### ISSUE THREAD

**Issue by alex-rsk** [gpac/gpac#3051]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ x] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [ x] I give enough information for contributors to reproduce my issue 

Hello. 

 I'm running the same command for long time each 10s. Command is executing from thread.

```
MP4Box -dash 2560 -dash-ctx /dev/shm/broadcast/context.txt \
 -profile dashavc264.live --utcs="https://time.akamai.com/?iso&ms" -mpd-refresh 3 \
 -dynamic -bs-switching no -segment-timeline -url-template -insert-utc -logs=all@debug \
 -log-file=/opt/streamer/storage/logs/mp4box.log -min-buffer 31  \
--sflush=end -time-shift 61.44 -tmp /tmp/stream  
/dev/shm/broadcast/norm.mp4#video:id=norm:#Representation=hd /dev/shm/broadcast/low.mp4#video:id=low:#Representation=360p  \
/dev/shm/broadcast/norm.mp4#audio:id=audio_low \ 
/dev/shm/broadcast/subtitle_en.vtt:id=subtitle_en:#Role=subtitle:#Language=en:duration=2.56:#Bitrate=200:#Represent ation=lang_en \
 -out /dev/shm/broadcast/KO31ED9BD7/manifest.mpd 
```

2 hours after it write one error

```
 bit out of range 0 - FD_SETSIZE on fd_set ***: terminated
```
mp4box log: https://pastebin.com/fGn2EwnP

Next runs of command doesn't produce nothing :  neither manifest nor messages, in `stderr` or `stdout`. 

But manual running of this command works fine.

GPAC version  2.5-DEV-rev725-g49e819a43-master

**Comment by alex-rsk** [comment]
Found out that we left plenty of unclosed file descriptors.

**Comment by rbouqueau** [comment]
Is there a way to reproduce? I'd like to see if GPAC can emit a clearer error message.

**Comment by alex-rsk** [comment]
I'm afraid, that there's no clear way to reproduce, because we detected leakage of file descriptors aside from MP4Box process.
You can, though, make intentional leakage of file descriptors, e.g. 
```
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <time.h>


int main() {
    // Open a file descriptor
    char *filename = malloc(1024);
    int c = 0;
    while (1) {
           char *filename = malloc(128);
           sprintf(filename, "/tmp/random_file_%d", ++c);
           printf("%s", filename);
           
           int fd = open(filename, O_WRONLY | O_CREAT);
           if (fd == -1) {
               perror("open");
               exit(1);
           }
    
           // I INTENTIONNALY don't close the file descriptors
           printf("File descriptor %d is open \n", fd);
           pid_t pid = getpid();    
           char *commandstr = malloc(128);

           sprintf(commandstr, "ls -l /proc/%d/fd | wc -l",  (int)pid);
           printf("%s\n", commandstr);
           system(commandstr);
           free(commandstr);

           sleep(2);
    }

    free(filename);
    return 0;
}
```
And run MP4Box command above.

We calling MP4Box each ten seconds, you can do the same with `while` and `sleep` in bash.
