### ISSUE TITLE
Create a MP4Box mini configuration + separate sln

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#308]
Do http://gpac.io/2015/07/29/gpac-build-mp4box-only-all-platforms/ with MSVC

**Comment by frank-e** [comment]
Please publish a ZIP with all required files to start this MP4box mini "sln" on a Windows box claiming to be able to open "sln" files for C++ 2010 or C++ 10 (?) Or far better, ditch the "sln" and publish the result, an mp4box.exe working on Windows. So far I can only tell that downloading the raw libgpac.vcxproj and mp4box.vcxproj isn't good enough for the "sln" business, and I certainly do not have a ..\..\version.bat.

**Comment by rbouqueau** [comment]
Did you follow the instructions from https://gpac.io/2015/07/29/gpac-build-mp4box-only-all-platforms/ ? It gives a pointer to the .sln. I've just tested for you and it works.

I confirm that opening the vcxproj alone doesn't make sense - vcxproj are meant to be part of a sln (with configuration manager, scripts, etc.).

What do you mean by a zip? How would it be generated? What would it contain?
