### ISSUE TITLE
Long videos don't play to end, due to sum of segment lengths > video duration

### ISSUE THREAD

**Issue by matthew-mahony** [gpac/gpac#31]
I have an hour long video, and I noticed the last few seconds are not being played.  (I am using the DASH-IF player after using mp4box to segment the video).  I use the segment timeline option, so I summed up all the segment durations to be 3581 seconds, although the original video is 3575 seconds.

I assume the video doesn't play to the end because the player thinks it has reached the end of the video, based on the video duration of 3575 seconds.  (I verified segments up to #1917 are requested, although mp4box generated 1919 segments).  If I manually edit the duration to match the sum of the segments, the video plays to the end.  But that seems like such a hack to me, and is a pain if I need to fix other long videos.

How can the sum of the segments exceed the video duration?  Is it possible the video duration is inaccurate?

I attached the generated .mpd file.  (Needed to change the extension to make it uploadable). 

![1_hour_dash](https://cloud.githubusercontent.com/assets/6590913/5668545/48ce09c4-9725-11e4-8e4b-16ac0191e25c.jpg)

**Comment by matthew-mahony** [comment]
I am wondering if the segment lengths are inaccurate.  Maybe they are rounded up, and for a long video all the rounding sums up to a few seconds of error.

**Comment by kuon** [comment]
I am not sure if this is related to the issue I have, #97.

**Comment by kuon** [comment]
Btw, to upload a file, copy it inline (look at gihub markdown for code blocks) or use a [gist](https://gist.github.com/).
