### ISSUE TITLE
Live Video Streaming from webcam in ubuntu 14.04

### ISSUE THREAD

**Issue by priyochatterjee08** [gpac/gpac#311]
I am using dashCast to capture from webcam:

DashCast -vf video4linux2 -v4l2f mjpeg -vfr 30 -vres 1280x720 -v /dev/video0 -af alsa -a plughw:PCH,0 -conf dashcast.conf -live -out /outdir

dashcast.mpd is getting generated but with errors. when I play with dash.js, it is searching for different segment time than available and it is showing "length not defined".

I am not getting the MP4Box right command for dash-ctx. Moreover, in my dash.mpd duration is less than timescale which is wrong I guess.

My mpd is given below:

<?xml version="1.0"?>
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" availabilityStartTime="2015-11-05T11:53:16.966Z" minBufferTime="PT1.000000S"  type="dynamic" profiles="urn:mpeg:dash:profile:full:2011" minimumUpdatePeriod="PT1000S">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>dashcast.mpd</Title>
 </ProgramInformation>
 <Period start="PT0H0M0.000S" id="P1">
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="false">
   <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
   <SegmentTemplate timescale="48000" duration="47104" media="$RepresentationID$_$Number$_gpac.m4s" startNumber="1" initialization="$RepresentationID$_init_gpac.mp4"/>
   <Representation id="a1" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="48000" startWithSAP="1" bandwidth="128000">
   </Representation>
   <Representation id="a2" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="48000" startWithSAP="1" bandwidth="256000">
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="false">
   <SegmentTemplate timescale="25" duration="25" media="$RepresentationID$_$Number$_gpac.m4s" startNumber="1" initialization="$RepresentationID$_init_gpac.mp4"/>
   <Representation id="v1" mimeType="video/mp4" codecs="avc1.64001f" width="1280" height="720" frameRate="25" sar="1:1" startWithSAP="1" bandwidth="800000">
   </Representation>
   <Representation id="v2" mimeType="video/mp4" codecs="avc1.64001e" width="640" height="360" frameRate="25" sar="1:1" startWithSAP="1" bandwidth="400000">
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>

while capturing the video with ffmpeg, when I run command   MP4Box -dash 1000 -frag 1000 -rap -dash-profile live test.mp4, it is showing moov-atom not defined.

So, I tried with -movflags empty_moov+omit_tfhd_offset+frag_keyframe+default_base_moof, still it is showing error:

Thanks in advance.

**Comment by jeanlf** [comment]
please post/upload your MPD and dashcast logs if you want us to help ...
