### ISSUE TITLE
crypt with widevine does not encrypt the file

### ISSUE THREAD

**Issue by bmurphy1976** [gpac/gpac#314]
I'm trying to use MP4Box to generate an mpeg-dash (html5) video using widevine drm+encryption however when I create the mpd the video is not getting encrypted.  Here's my test `crypt.xml`:

```xml
<GPACDRM type="CENC AES-CTR">
  <DRMInfo type="pssh" version="0">
    <BS ID128="edef8ba979d64acea3c827dcd51d21ed"/>
    <BS data64="CAESENK2NtpQt1e8uSmYXsadcR8aCG1lZGlhZmx5IiA4ODk2YzY5MWU1Y2I0ODdlYWVhZWYwZjczM2M5ZDQ1NjIA"/>
  </DRMInfo>
  <DRMInfo type="pssh" version="0">
    <BS ID128="edef8ba979d64acea3c827dcd51d21ed"/>
    <BS data64="CAESEAjJX4cAF1xjs+K5D94erakaCG1lZGlhZmx5IiA4ODk2YzY5MWU1Y2I0ODdlYWVhZWYwZjczM2M5ZDQ1NjIA"/>
  </DRMInfo>
  <CrypTrack IV_size="8" first_IV="0xea5cf671846578e0" isEncrypted="1" saiSavedBox="senc" trackID="1">
    <key KID="0xd2b636da50b757bcb929985ec69d711f" value="0x980eb34b69b908e0332cd8a956d5e501"/>
  </CrypTrack>
  <CrypTrack IV_size="8" first_IV="0xdf7a5be5f0a9297c" isEncrypted="1" saiSavedBox="senc" trackID="2">
    <key KID="0x08c95f8700175c63b3e2b90fde1eada9" value="0xff4db46688652e0a5275190f43b759fd"/>
  </CrypTrack>
</GPACDRM>
```

Here is the command I run to create an mpd:

```
$ MP4Box -crypt crypt.xml -dash 10 -profile onDemand -out output/output.mpd input/video.mp4 input/audio.m4a
```

The generated audio and video files are playable in VLC and I get no diagnostics output from MP4Box indicating anything has gone wrong.  

The output mpd contains the following:

```xml
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.5.2-DEV-rev944-g875bb9f-master  at 2015-11-06T21:09:52.862Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H0M10.624S" maxSegmentDuration="PT0H0M0.042S" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>output/output.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H0M10.624S">
  <AdaptationSet segmentAlignment="true" maxWidth="1920" maxHeight="1080" maxFrameRate="90000/3768" par="1:1" lang="und" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
   <Representation id="1" mimeType="video/mp4" codecs="avc1.640028" width="1920" height="1080" frameRate="90000/3768" sar="1:1" startWithSAP="1" bandwidth="13696716">
    <BaseURL>video_dashinit.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="918-3889">
      <Initialization range="0-917"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" par="1:1" lang="und" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
   <Representation id="2" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="48000" startWithSAP="1" bandwidth="103856">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <BaseURL>audio_dashinit.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="848-6855">
      <Initialization range="0-847"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```

**Comment by rbouqueau** [comment]
MP4Box doesn't support crypt and dash on the same command-line ATM. I have added a message to make this more explicit. Sorry for the confusion.

**Comment by bmurphy1976** [comment]
Thanks, I can confirm that I am able to generate encrypted files now by using a two step process:

(1) encrypt the audio and video streams:

```bash
$ MP4Box -crypt crypt.xml -out output/audio.m4a input/audio.m4a
$ MP4Box -crypt crypt.xml -out output/video.mp4 input/video.mp4
```

(2) package the streams as mpeg-dash:

```bash
$ MP4Box -crypt crypt.xml -dash 10 -profile onDemand -out output/output.mpd output/audio.m4a output/video.mp4
```

I haven't yet been able to establish playback however.  I can get various javascript players to fetch the decryption key from the widevine api, however, the video still doesn't play.  It appears chrome is still having trouble decrypting the streams.  I'll follow up here with more info as I discover it.

**Comment by rbouqueau** [comment]
Compatibility has been reported for many DRMs. You can check more at https://html5.cablelabs.com/mse-eme/doc/overview.html

I close the issue. Re-open if needed.

**Comment by Duna** [comment]
@bmurphy1976 Did you successfully play encrypted video in a player? A short code snippets of how did you achieve the encoding, crypt.xml file and the player configuration would be useful to the community

**Comment by rbouqueau** [comment]
Hi @Duna , this thread is old. Did you have a look at the wiki and testsuite?

https://github.com/gpac/testsuite/tree/filters/scripts

https://github.com/gpac/gpac/wiki/encryption-filters

We're looking for ways to improve our documentation. Please let us know about what is not clear for w.r.t. what you're trying to achieve.

**Comment by bmurphy1976** [comment]
@Duna I stopped using GPAC years ago and switched to https://github.com/google/shaka-packager
