### ISSUE TITLE
Cannot build MP4Client on windows. Where is the latest gpac_extra_libs package?

### ISSUE THREAD

**Issue by joerango** [gpac/gpac#315]

**Comment by rbouqueau** [comment]
svn://svn.code.sf.net/p/gpac/code/trunk/gpac_extra_libs/ , see http://gpac.io/2011/04/18/command-line-gpac-compiling-on-windows-x86-using-free-microsoft-visual-c/

If you only try to build MP4Box, you may be interested in http://gpac.io/2015/07/29/gpac-build-mp4box-only-all-platforms/

I think #21 is on the run which should definitely solve the issue.
CC @nguyen-viet-thanh-trung 

Please close this issue if ok for you.

**Comment by joerango** [comment]
Thanks for the links. 
#21 looks like the ideal solution.
