### ISSUE TITLE
Recent changes to Makefile break installation on MacOS X

### ISSUE THREAD

**Issue by stephenjolly** [gpac/gpac#317]
Commit https://github.com/gpac/gpac/commit/a3363ba3edbd8346f4035f7e407ab27a39cedf4d introduces some new "cp" invocations to the Makefile with the "--no-preserve" command-line flag.

This flag is specific to GNU cp, so its introduction causes "make install" to fail on MacOS X with the error "cp: illegal option -- -".

**Comment by jeanlf** [comment]
now fixed thanks for the report
