### ISSUE TITLE
How can I control the generation rate of MPD file in the DashCast.

### ISSUE THREAD

**Issue by JamesXu20150314** [gpac/gpac#318]
Hello,

I want to know whether or not the generation rate of MPD file is connected with the -seg-dur.
What's more, how can I control the generation rate of the MPD file.

Thanks,

JamesXu

**Comment by jeanlf** [comment]
MPD is generated with each new segments, so indeed generation rate is equal to -seg-dur, and cannot be modified for the time being. You can however specify the refresh rate, as used by the client, of the MPD  using -mpd-refresh
