### ISSUE TITLE
How to add a subtitle to live-mpd?

### ISSUE THREAD

**Issue by MaggiQ** [gpac/gpac#319]
Hello!

I am trying to add a subtitle to my mpd file, but mp4box tells me not supported for dashing. I understand that and if I remove the last line it works fine (without the subtitle ofcourse)

    MP4Box -dash 4000 -frag-rap -profile dashavc264:live -bs-switching no ^
    -no-frags-default -segment-name $RepresentationID$/segment_ ^
    -noprog -out D:\o\movie\play.mpd ^
    D:\o\video_1920x1080_3500.mp4:id=video_1920x1080_3500 ^
    D:\o\sub_0.srt:id=sub_fr:fmt=VTT

So how can I make the manifest to work with dashed files and a whole subtitle file?

Example I would like it to be added like this:

    <AdaptationSet id="21" mimeType="text/vtt" lang="fr">
        <Representation id="21">
            <BaseURL>subs/s-pt-fr.vtt</BaseURL>
        </Representation>
    </AdaptationSet>

I hope I made myself somewhat clear; thanks in advance :)

**Comment by rbouqueau** [comment]
Yes. For side WebVTT files, you have to add the AS manually to your MPD.
