### ISSUE TITLE
Cannot DASH or play video with Japanese file name

### ISSUE THREAD

**Issue by matthew-mahony** [gpac/gpac#323]
I need to use mp4box to DASH a video with a Japanese file name, but I get the error:
Cannot open file ????????.mp4 for dashing: Requested URL is not valid or cannot be found

When trying to play the video in the mp4client, I get the same error.

**Comment by jeanlf** [comment]
do you have that sample file? Could you tried logging everything (-logs all@debug) to give us a hint on what could be wrong ?

**Comment by matthew-mahony** [comment]
These are the files I'm trying to DASH (I had to change the extension to .txt for GitHub to allow me to upload, make sure to change them back to .mp4).

I didn't get any additional information with the "-logs all@debug" command line.  I tried again with the latest nightly build, and I get a slightly different error message:
[DASH] Cannot open file ╡∙╤╡ú╝F¼Ppⁿ½pΘ+pΘ±pΓΩpΓ╜.audioOnly.mp4 for dashing: Requested URL is not valid or cannot be found
DASH Setup Error: Requested URL is not valid or cannot be found



[日本語のタイトル.audioOnly.txt](https://github.com/gpac/gpac/files/39184/audioOnly.txt)
[日本語のタイトル_200000_640x480.txt](https://github.com/gpac/gpac/files/39185/_200000_640x480.txt)
[日本語のタイトル_1000000_640x480.txt](https://github.com/gpac/gpac/files/39186/_1000000_640x480.txt)

**Comment by cconcolato** [comment]
Strange. I downloaded your files, stored them with their japanese names. I can view them properly in the file explorer but not in the console using ls or dir. Then I tried to debug in VS2015 but the argv argument does not contain the right thing. If I try `MP4Box -info 日本語のタイトル.audioOnly.mp4`, the file name contains 8 japanese characters (forgive my ignorance about the exact naming kanji, hiragana, katakana ...), but I get argv containing 8 chars whose values are 0x3f. I would have expected to get a UTF-8 or UTF-16 encoding of them, so more chars than 8 and with meaningful values ... Any idea, what's wrong here?

**Comment by cconcolato** [comment]
Apparently simply changing main to wmain provides a correct value in argv (which now contains wchar), but this would mean changing all string processing in mp4box !! Is there a way to get an UTF-8 encoding in argv ?

**Comment by cconcolato** [comment]
This seems to work well on Linux and Mac, and to be only problematic on Windows. As a workaround for now, you can use the short names (as shown in `dir /x`) and MP4Box should work fine. Can you try?

**Comment by cconcolato** [comment]
I've tried patching MP4Box for supporting japanese names in the utfarg branch (see e335f75). Calling `MP4Box -info 日本語のタイトル.audioOnly.mp4` now works for me both on the Windows cmd and in Console2 with bash. Can you try?

**Comment by matthew-mahony** [comment]
I'm having problems building.  The code in the utfarg branch has a few simple compilation erros (like 'identifier "filename" is undefined').  Once I fix those, I get linker errors.  I tried to follow the instructions at https://gpac.wp.mines-telecom.fr/2011/04/18/command-line-gpac-compiling-on-windows-x86-using-free-microsoft-visual-c/ to build the extra_libs project, but the instructions are tailored to SVN, so I'm guessing they are out of date.

Are there updated instructions to build from source on GitHub?  Or is there an automated build for this branch that I can download?

**Comment by cconcolato** [comment]
I made some mistakes in the initial commit. I had to fix and rebase my commits. The latest commit is 9380155, have you used this one? What version of Visual Studio are you using?

**Comment by matthew-mahony** [comment]
This is the version of os_file.c that I have.  Note the argument name is "file_name", but the fopen command uses "filename".

```c
GF_EXPORT
FILE *gf_fopen(const char *file_name, const char *mode)
{
	FILE *res;

#if defined(WIN32)
	res = fopen(filename, mode);
	if (!res) {
		const char *str_src;
		wchar_t *wname;
		wchar_t *wmode;
		size_t len;
		size_t len_res;
		GF_LOG(GF_LOG_INFO, GF_LOG_CORE, ("[Core] Could not open file in UTF-8 mode, trying UTF-16\n"));
		
		len = (strlen(name) + 1)*sizeof(wchar_t);
```

**Comment by cconcolato** [comment]
Indeed, the code had some mistakes ... That's what happens when coding on Mac for Windows (or vice-versa). Sorry for that. Can you check the latest commit: 9bf5dfb ?

**Comment by matthew-mahony** [comment]
I was able to build and verify mp4box runs now.  However, the output files do not have the correct characters.  Since the output files are opened with write/create mode, they are successfully opened with fopen, and the filename ends up with gibberish characters.  (See attached).  

![outputfilenames](https://cloud.githubusercontent.com/assets/6590913/11344646/9ae2d2f6-91e0-11e5-912e-253d390dfb82.png)

Is there any problem with always opening a file with the _wfopen_s function?  Or can the filename be checked for unicode characters, and use _wfopen_s when necessary?  Such as:

```c
	if (!contains_unicode_character(file_name)) {
		res = fopen(file_name, mode);
	} else {
           //use _wfopen_s
...
```

Thanks,

Matt

**Comment by jeanlf** [comment]
this should now be fixed. I also tested with dashing the file, the mpd will contain, if needed, the utf8 name as baseURL (this seems compliant with the spec but I haven't tested with dash-js).

**Comment by cconcolato** [comment]
I just fixed mp4client as well (df07f4c). It can now open your mp4 file. Note that for all log messages in GPAC we still output UTF-8, so some messages like "Opening URL ..." will look wrong. If you want to view them correctly you need to set your code page in the console to UTF-8 using `CHCP 65001`.

**Comment by cconcolato** [comment]
The utfarg branch has been merged to the master branch. Please use the master branch. I'm closing the issue as we think your problems are solved. Please reopen if this is not the case.

**Comment by gikarasojo** [comment]
@cconcolato Hello, I'm trying to dash my video file which

1. I separated audio from video using the command 
```
ffmpeg -i joke.mp4 -c:v copy -an video.mp4
ffmpeg -i joke.mp4 -c:a copy -vn audio.mp4 
```

2. I produced several bitrates using the command
```
ffmpeg -i 'video.mp4' -an -c:v libx264 -preset veryslow -profile:v high -level 4.2 -b:v 2000k -minrate 2000k -maxrate 2000k -bufsize 4000k -g 96 -keyint_min 96 -sc_threshold 0 -filter:v "scale='trunc(oh*a/2)*2:576'" -pix_fmt yuv420p joke-2000k.mp4
ffmpeg -i 'video.mp4' -an -c:v libx264 -preset veryslow -profile:v high -level 4.2 -b:v 1500k -minrate 1500k -maxrate 1500k -bufsize 3000k -g 96 -keyint_min 96 -sc_threshold 0 -filter:v "scale='trunc(oh*a/2)*2:480'" -pix_fmt yuv420p joke-1500k.mp4
ffmpeg -i 'video.mp4' -an -c:v libx264 -preset veryslow -profile:v high -level 4.2 -b:v 1000k -minrate 1000k -maxrate 1000k -bufsize 2000k -g 96 -keyint_min 96 -sc_threshold 0 -filter:v "scale='trunc(oh*a/2)*2:360'" -pix_fmt yuv420p joke-1000k.mp4
ffmpeg -i 'video.mp4' -an -c:v libx264 -preset veryslow -profile:v high -level 4.2 -b:v 700k -minrate 700k -maxrate 700k -bufsize 1400k -g 96 -keyint_min 96 -sc_threshold 0 -filter:v "scale='trunc(oh*a/2)*2:288'" -pix_fmt yuv420p joke-700k.mp4 
```

3. I now try to dash my generated video files of different bitrates using the command

```
mkdir dash_unprotected
MP4Box -dash 4000 -rap -frag-rap -sample-groups-traf -profile dashavc264:live -bs-switching no -segment-name dash_$RepresentationID$_$Number$ -url-template joke-700k.mp4 joke-1000k.mp4 joke-1500k.mp4 joke-2000k.mp4 audio.mp4 -out "dash_unprotected/manifest.mp4"
```
But the dash process fails and i get the below error
```
[DASH]: Files have non-proportional track layouts (180x288 vs 224x360) but sample size and aspect ratio match, assuming precision issue
DASH-ing files: 4.00s segments 4.00s fragments single sidx per segment
Spliting segments and fragments at GOP boundaries
[DASH] Generating MPD at time 2017-06-30T12:14:12Z
DASHing file joke-700k.mp4
[ISOBMF DASH] Cannot open dash_unprotected/dash_/bin/dash$init.mp4 for writing
Error while DASH-ing file: Requested URL is not valid or cannot be found
Error DASHing file: Requested URL is not valid or cannot be found
```
Below is my video file **joke.txt** ( rename it to **joke.mp4**)
[joke.txt](https://github.com/gpac/gpac/files/1115070/joke.txt)

**Comment by cconcolato** [comment]
@gikarasojo I downloaded your file and used your command lines, and have no problem. Try maybe using a more recent version of MP4Box. BTW, your problem does not seem related to Japanese names, so please file a separate issue.

**Comment by gikarasojo** [comment]
@cconcolato I was able to the the problem, the issue was that i had placed my folder `dash_unprotected` in a place that required permissions to access it. that is, i forgot to add `sudo` command at the beginning of `MP4Box` command.
