### ISSUE TITLE
Unnecessary "par" attribute appears in the mpd when DASH an audio file

### ISSUE THREAD

**Issue by fanzc** [gpac/gpac#324]
Hi,
When I am dashing a AAC-LC audio file with following command:
`MP4Box -rap -profile live -dash 2000 -out template.mpd test.m4a`

In the template.mpd file, the `par` attribute appears in the `AdpatationSet` element:
`<AdaptationSet segmentAlignment="true" par="1:1" lang="und">`

This issue only occurs when I updated from 0.5.2-DEV-rev552-g5a1b427-master to 0.5.2-DEV-rev1006-g9f09b13-HEAD

**Comment by jeanlf** [comment]
indeed, now fixed thanks for the report
