### ISSUE TITLE
Errors Building MP4Box with Make within last 24hours

### ISSUE THREAD

**Issue by davidjmerritt** [gpac/gpac#325]
Hello,

I was building MP4Box on Centos 7 Minimal Installation today and ran into errors when compiling.  I have followed the same protocol a few times in the past, most recently about 36 hours ago, so I am stumped as to why I am running into these issues.  

I followed the instruction on this page: https://gpac.wp.mines-telecom.fr/ under the "Build MP4Box with Make" section.  I have bolded the commands and pasted the outputs below each command for reference.

Any help would be greatly appreciated!

Thanks!,
David  

<b>git clone https://github.com/gpac/gpac.git</b>
Cloning into 'gpac'...
remote: Counting objects: 76973, done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 76973 (delta 36), reused 0 (delta 0), pack-reused 76894
Receiving objects: 100% (76973/76973), 73.74 MiB | 5.78 MiB/s, done.
Resolving deltas: 100% (62815/62815), done.

<b>cd gpac</b>

<b>git pull</b>
Already up-to-date.

<b>./configure --static-mp4box --use-zlib=no</b>
WARNING!! : you have forced not to use ZLIB. This will disable some core functionalities of GPAC.

** System Configuration
Install prefix: /usr/local
Source path: /home/david/gpac
C   compiler: gcc
C++ compiler: g++
make: make
CPU: x86_64
Big Endian: no

** GPAC 0.5.2-DEV rev1009-g984d462-master Core Configuration **
debug version: no
GProf enabled: no
Static build enabled: yes
Memory tracking enabled: no
Fixed-Point Version: no
IPV6 Support: yes
Static Modules: no

** Detected libraries **
zlib: force-no
OSS Audio: yes
ALSA Audio: no
Jack Audio: no
PulseAudio Audio: no
DirectFB support: no
SDL Support: no
OpenGL support: no
TinyGL support: no
OpenSSL support: no
Mozilla XUL/GECKO support: no
DVB Support: yes
XMLRPC Support: no
wxWidgets support: no

** Extra Libraries used **
SpiderMonkey: no
FreeType: no
JPEG: no
OpenJPEG: no
PNG: no
MAD: no
FAAD: no
XVID: no
FFMPEG: no
Xiph OGG: no
Platinum UPnP: no
AVCap: no
A52 (AC3): no
OpenSVCDecoder: no
OpenHEVCDecoder: no
Freenect: no

Creating config.mak
Check config.log for detection failures
Done - type 'make help' for make info, 'make' to build

<b>make -j4</b>
make -C src all
make[1]: Entering directory `/home/david/gpac/src'
cat .deps/utils/os_divers.dep .deps/utils/os_file.dep .deps/utils/list.dep .deps/utils/bitstream.dep .deps/utils/error.dep .deps/utils/alloc.dep .deps/utils/url.dep .deps/utils/configfile.dep .deps/utils/sha1.dep .deps/utils/base_encoding.dep .deps/utils/os_net.dep .deps/utils/os_thread.dep .deps/utils/os_config_init.dep .deps/utils/cache.dep .deps/utils/downloader.dep .deps/utils/xml_parser.dep .deps/utils/utf.dep .deps/utils/token.dep .deps/utils/color.dep .deps/utils/os_module.dep .deps/utils/math.dep .deps/utils/path2d.dep .deps/utils/path2d_stroker.dep .deps/utils/module.dep .deps/utils/uni_bidi.dep .deps/utils/ringbuffer.dep .deps/utils/unicode.dep .deps/utils/map.dep .deps/mcrypt/cbc.dep .deps/mcrypt/cfb.dep .deps/mcrypt/ctr.dep .deps/mcrypt/des.dep .deps/mcrypt/ecb.dep .deps/mcrypt/g_crypt.dep .deps/mcrypt/ncfb.dep .deps/mcrypt/nofb.dep .deps/mcrypt/ofb.dep .deps/mcrypt/rijndael-128.dep .deps/mcrypt/rijndael-192.dep .deps/mcrypt/rijndael-256.dep .deps/mcrypt/stream.dep .deps/mcrypt/tripledes.dep .deps/scenegraph/base_scenegraph.dep .deps/scenegraph/mpeg4_animators.dep .deps/scenegraph/commands.dep .deps/scenegraph/mpeg4_nodes.dep .deps/scenegraph/mpeg4_valuator.dep .deps/scenegraph/vrml_interpolators.dep .deps/scenegraph/vrml_proto.dep .deps/scenegraph/vrml_route.dep .deps/scenegraph/vrml_script.dep .deps/scenegraph/vrml_smjs.dep .deps/scenegraph/vrml_tools.dep .deps/scenegraph/x3d_nodes.dep .deps/scenegraph/svg_attributes.dep .deps/scenegraph/svg_types.dep .deps/scenegraph/svg_smjs.dep .deps/scenegraph/smil_anim.dep .deps/scenegraph/smil_timing.dep .deps/scenegraph/svg_properties.dep .deps/scenegraph/dom_events.dep .deps/scenegraph/dom_smjs.dep .deps/scenegraph/xbl_process.dep .deps/scenegraph/xml_ns.dep .deps/scenegraph/html5_media_smjs.dep .deps/scenegraph/html5_mse_smjs.dep .deps/scenegraph/webvtt_smjs.dep .deps/ietf/rtcp.dep .deps/ietf/rtp.dep .deps/ietf/rtp_packetizer.dep .deps/ietf/rtp_pck_3gpp.dep .deps/ietf/rtp_pck_mpeg12.dep .deps/ietf/rtp_pck_mpeg4.dep .deps/ietf/rtsp_command.dep .deps/ietf/rtsp_common.dep .deps/ietf/rtsp_response.dep .deps/ietf/rtsp_session.dep .deps/ietf/sdp.dep .deps/ietf/rtp_depacketizer.dep .deps/ietf/rtp_streamer.dep .deps/bifs/arith_decoder.dep .deps/bifs/bifs_codec.dep .deps/bifs/bifs_node_tables.dep .deps/bifs/com_dec.dep .deps/bifs/com_enc.dep .deps/bifs/conditional.dep .deps/bifs/field_decode.dep .deps/bifs/field_encode.dep .deps/bifs/memory_decoder.dep .deps/bifs/predictive_mffield.dep .deps/bifs/quantize.dep .deps/bifs/script_dec.dep .deps/bifs/script_enc.dep .deps/bifs/unquantize.dep .deps/isomedia/avc_ext.dep .deps/isomedia/box_code_3gpp.dep .deps/isomedia/box_code_apple.dep .deps/isomedia/box_code_base.dep .deps/isomedia/box_code_drm.dep .deps/isomedia/box_code_meta.dep .deps/isomedia/box_dump.dep .deps/isomedia/box_funcs.dep .deps/isomedia/data_map.dep .deps/isomedia/drm_sample.dep .deps/isomedia/isom_intern.dep .deps/isomedia/isom_read.dep .deps/isomedia/isom_store.dep .deps/isomedia/isom_write.dep .deps/isomedia/media.dep .deps/isomedia/media_odf.dep .deps/isomedia/meta.dep .deps/isomedia/movie_fragments.dep .deps/isomedia/sample_descs.dep .deps/isomedia/stbl_read.dep .deps/isomedia/stbl_write.dep .deps/isomedia/track.dep .deps/isomedia/tx3g.dep .deps/isomedia/iff.dep .deps/isomedia/hint_track.dep .deps/isomedia/hinting.dep .deps/isomedia/box_code_adobe.dep .deps/isomedia/ttml.dep .deps/odf/desc_private.dep .deps/odf/descriptors.dep .deps/odf/odf_code.dep .deps/odf/odf_codec.dep .deps/odf/odf_command.dep .deps/odf/qos.dep .deps/odf/slc.dep .deps/odf/ipmpx_code.dep .deps/odf/oci_codec.dep .deps/odf/ipmpx_dump.dep .deps/odf/ipmpx_parse.dep .deps/odf/odf_dump.dep .deps/odf/odf_parse.dep .deps/media_tools/isom_tools.dep .deps/media_tools/dash_segmenter.dep .deps/media_tools/av_parsers.dep .deps/media_tools/img.dep .deps/media_tools/media_import.dep .deps/media_tools/mpegts.dep .deps/media_tools/m3u8.dep .deps/media_tools/mpd.dep .deps/media_tools/dash_client.dep .deps/media_tools/media_export.dep .deps/media_tools/m2ts_mux.dep .deps/media_tools/filestreamer.dep .deps/media_tools/avilib.dep .deps/media_tools/mpeg2_ps.dep .deps/media_tools/gpac_ogg.dep .deps/media_tools/ismacryp.dep .deps/media_tools/isom_hinter.dep .deps/media_tools/saf.dep .deps/media_tools/vobsub.dep .deps/media_tools/text_import.dep .deps/media_tools/html5_media.dep .deps/media_tools/html5_mse.dep .deps/media_tools/webvtt.dep .deps/scene_manager/scene_manager.dep .deps/scene_manager/text_to_bifs.dep .deps/scene_manager/loader_bt.dep .deps/scene_manager/loader_xmt.dep .deps/scene_manager/loader_isom.dep .deps/scene_manager/loader_qt.dep .deps/scene_manager/loader_svg.dep .deps/scene_manager/swf_parse.dep .deps/scene_manager/swf_bifs.dep .deps/scene_manager/swf_svg.dep .deps/scene_manager/scene_dump.dep .deps/scene_manager/scene_stats.dep .deps/scene_manager/scene_engine.dep .deps/scene_manager/encode_isom.dep .deps/terminal/channel.dep .deps/terminal/clock.dep .deps/terminal/decoder.dep .deps/terminal/term_node_init.dep .deps/terminal/input_sensor.dep .deps/terminal/media_control.dep .deps/terminal/media_manager.dep .deps/terminal/media_memory.dep .deps/terminal/media_object.dep .deps/terminal/media_sensor.dep .deps/terminal/mpeg4_inline.dep .deps/terminal/network_service.dep .deps/terminal/object_browser.dep .deps/terminal/object_manager.dep .deps/terminal/scene.dep .deps/terminal/terminal.dep .deps/terminal/svg_external.dep .deps/compositor/audio_input.dep .deps/compositor/audio_mixer.dep .deps/compositor/audio_render.dep .deps/compositor/bindable.dep .deps/compositor/camera.dep .deps/compositor/compositor.dep .deps/compositor/compositor_2d.dep .deps/compositor/compositor_3d.dep .deps/compositor/compositor_node_init.dep .deps/compositor/drawable.dep .deps/compositor/events.dep .deps/compositor/font_engine.dep .deps/compositor/hc_flash_shape.dep .deps/compositor/hardcoded_protos.dep .deps/compositor/mesh.dep .deps/compositor/mesh_collide.dep .deps/compositor/mesh_tesselate.dep .deps/compositor/mpeg4_animstream.dep .deps/compositor/mpeg4_audio.dep .deps/compositor/mpeg4_background.dep .deps/compositor/mpeg4_background2d.dep .deps/compositor/mpeg4_bitmap.dep .deps/compositor/mpeg4_composite.dep .deps/compositor/mpeg4_form.dep .deps/compositor/mpeg4_geometry_2d.dep .deps/compositor/mpeg4_geometry_3d.dep .deps/compositor/mpeg4_geometry_ifs2d.dep .deps/compositor/mpeg4_geometry_ils2d.dep .deps/compositor/mpeg4_gradients.dep .deps/compositor/mpeg4_grouping.dep .deps/compositor/mpeg4_grouping_2d.dep .deps/compositor/mpeg4_grouping_3d.dep .deps/compositor/mpeg4_layer_2d.dep .deps/compositor/mpeg4_layer_3d.dep .deps/compositor/mpeg4_layout.dep .deps/compositor/mpeg4_lighting.dep .deps/compositor/mpeg4_path_layout.dep .deps/compositor/mpeg4_sensors.dep .deps/compositor/mpeg4_sound.dep .deps/compositor/mpeg4_text.dep .deps/compositor/mpeg4_textures.dep .deps/compositor/mpeg4_timesensor.dep .deps/compositor/mpeg4_viewport.dep .deps/compositor/navigate.dep .deps/compositor/offscreen_cache.dep .deps/compositor/svg_base.dep .deps/compositor/svg_filters.dep .deps/compositor/svg_font.dep .deps/compositor/svg_geometry.dep .deps/compositor/svg_grouping.dep .deps/compositor/svg_media.dep .deps/compositor/svg_paint_servers.dep .deps/compositor/svg_text.dep .deps/compositor/texturing.dep .deps/compositor/texturing_gl.dep .deps/compositor/visual_manager.dep .deps/compositor/visual_manager_2d.dep .deps/compositor/visual_manager_2d_draw.dep .deps/compositor/visual_manager_3d.dep .deps/compositor/visual_manager_3d_gl.dep .deps/compositor/x3d_geometry.dep .deps/laser/lsr_enc.dep .deps/laser/lsr_dec.dep .deps/laser/lsr_tables.dep > ".depend"
make[1]: Leaving directory `/home/david/gpac/src'
make[1]: Entering directory `/home/david/gpac/src'
  CC utils/os_divers.c
  CC utils/os_file.c
  CC utils/list.c
  CC utils/bitstream.c
  CC utils/error.c
  CC utils/alloc.c
  CC utils/url.c
  CC utils/configfile.c
  CC utils/sha1.c
  CC utils/base_encoding.c
  CC utils/os_net.c
  CC utils/os_thread.c
  CC utils/os_config_init.c
  CC utils/cache.c
utils/cache.c: In function ‘gf_cache_create_entry’:
utils/cache.c:482:10: warning: variable ‘err’ set but not used [-Wunused-but-set-variable]
   GF_Err err;
          ^
utils/cache.c:526:10: warning: variable ‘err’ set but not used [-Wunused-but-set-variable]
   GF_Err err;
          ^
  CC utils/downloader.c
  CC utils/xml_parser.c
  CC utils/utf.c
  CC utils/token.c
  CC utils/color.c
  CC utils/os_module.c
  CC utils/math.c
  CC utils/path2d.c
  CC utils/path2d_stroker.c
  CC utils/module.c
  CC utils/uni_bidi.c
  CC utils/ringbuffer.c
  CC utils/unicode.c
  CC utils/map.c
  CC ietf/rtcp.c
  CC ietf/rtp.c
  CC ietf/rtp_packetizer.c
  CC ietf/rtp_pck_3gpp.c
  CC ietf/rtp_pck_mpeg12.c
  CC ietf/rtp_pck_mpeg4.c
  CC ietf/rtsp_command.c
  CC ietf/rtsp_common.c
  CC ietf/rtsp_response.c
  CC ietf/rtsp_session.c
  CC ietf/sdp.c
  CC ietf/rtp_depacketizer.c
  CC ietf/rtp_streamer.c
  CC bifs/arith_decoder.c
  CC bifs/bifs_codec.c
  CC bifs/bifs_node_tables.c
  CC bifs/com_dec.c
  CC bifs/com_enc.c
  CC bifs/conditional.c
  CC bifs/field_decode.c
  CC bifs/field_encode.c
  CC bifs/memory_decoder.c
  CC bifs/predictive_mffield.c
  CC bifs/quantize.c
  CC bifs/script_dec.c
  CC bifs/script_enc.c
  CC bifs/unquantize.c
  CC odf/desc_private.c
  CC odf/descriptors.c
  CC odf/odf_code.c
  CC odf/odf_codec.c
odf/odf_code.c: In function ‘gf_odf_write_kw’:
odf/odf_code.c:2633:9: warning: variable ‘e’ set but not used [-Wunused-but-set-variable]
  GF_Err e;
         ^
  CC odf/odf_command.c
odf/odf_command.c: In function ‘gf_odf_write_od_remove’:
odf/odf_command.c:171:9: warning: variable ‘e’ set but not used [-Wunused-but-set-variable]
  GF_Err e;
         ^
odf/odf_command.c: In function ‘gf_odf_del_ipmp_update’:
odf/odf_command.c:570:9: warning: variable ‘e’ set but not used [-Wunused-but-set-variable]
  GF_Err e;
         ^
  CC odf/qos.c
  CC odf/slc.c
odf/slc.c: In function ‘gf_odf_write_slc’:
odf/slc.c:261:9: warning: variable ‘e’ set but not used [-Wunused-but-set-variable]
  GF_Err e;
         ^
  CC odf/ipmpx_code.c
  CC odf/oci_codec.c
  CC odf/ipmpx_dump.c
  CC odf/ipmpx_parse.c
  CC odf/odf_dump.c
  CC odf/odf_parse.c
  CC laser/lsr_enc.c
  CC laser/lsr_dec.c
  CC laser/lsr_tables.c
  CC isomedia/avc_ext.c
  CC isomedia/box_code_3gpp.c
isomedia/box_code_3gpp.c: In function ‘styl_Write’:
isomedia/box_code_3gpp.c:601:9: warning: variable ‘e’ set but not used [-Wunused-but-set-variable]
  GF_Err e;
         ^
  CC isomedia/box_code_apple.c
  CC isomedia/box_code_base.c
isomedia/box_code_base.c: In function ‘mp4a_AddBox’:
isomedia/box_code_base.c:3511:12: warning: variable ‘e’ set but not used [-Wunused-but-set-variable]
     GF_Err e;
            ^
  CC isomedia/box_code_drm.c
isomedia/box_code_drm.c: In function ‘schm_Write’:
isomedia/box_code_drm.c:196:9: warning: variable ‘e’ set but not used [-Wunused-but-set-variable]
  GF_Err e;
         ^
  CC isomedia/box_code_meta.c
  CC isomedia/box_dump.c
  CC isomedia/box_funcs.c
  CC isomedia/data_map.c
  CC isomedia/drm_sample.c
  CC isomedia/isom_intern.c
  CC isomedia/isom_read.c
  CC isomedia/isom_store.c
  CC isomedia/isom_write.c
isomedia/isom_write.c: In function ‘gf_isom_set_media_timescale’:
isomedia/isom_write.c:3538:3: error: stray ‘\302’ in program
   if (! stbl || !stbl->TimeToSample) {
   ^
isomedia/isom_write.c:3538:3: error: stray ‘\240’ in program
isomedia/isom_write.c: In function ‘gf_isom_estimate_size’:
isomedia/isom_write.c:3818:9: warning: variable ‘e’ set but not used [-Wunused-but-set-variable]
  GF_Err e;
         ^
make[1]: *** [isomedia/isom_write.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/home/david/gpac/src'
make: *** [all] Error 2

<b>sudo make install</b>
install -d "/usr/local"
install -d "/usr/local/lib"
install -d "/usr/local/bin"
install  -m 755 bin/gcc/MP4Box "/usr/local/bin"
install: cannot stat ‘bin/gcc/MP4Box’: No such file or directory
make: *** [install] Error 1

**Comment by jeanlf** [comment]
I believe this was fixed last night, could you check it?

**Comment by davidjmerritt** [comment]
Just tested and can firmed it's compiling properly now.
