### ISSUE TITLE
Is there a way to split a mp4 into 2 mp4, one is metadata.mp4 and another is mediadata.mp4

### ISSUE THREAD

**Issue by aicco** [gpac/gpac#326]
According to ISO/IEC 14496 Part10, the definition of 'dref' tells us that the media data can be placed in another file,so can I split a normal mp4 file into 2 mp4 file,one is metadata.mp4 and the other is mediadata.mp4?

**Comment by cconcolato** [comment]
If I understand your question, you want to have an MP4 containing the 'moov' box and another mp4 containing the 'mdat' box. Is that the case?

**Comment by aicco** [comment]
Yes!  If we can do this , we can modify the 'moov' ' data freely , add things,delete things,and don't worry about the absolute offset of media data. I think according to the ISO/IEC , we can achieve it theoretically.

**Comment by cconcolato** [comment]
`MP4Box -flat file.mp4` can reorder the boxes in the MP4 file to have first the `ftyp` box, then the `mdat`, then the `moov`. That can help you edit the `moov` without changing the offsets and without splitting into 2 files.

**Comment by aicco** [comment]
Thanks! That really helps me!But I have a little more questions,this question has confused me for a very long time and I still don't find the answer.
http://video.stackexchange.com/questions/16947/many-boxes-atoms-never-used

**Comment by jeanlf** [comment]
1- correct reference  is ISO/IEC 14496-12 not "part 10"
2- the file format has many purposes, so indeed in most applications you won't use all the boxes.

**Comment by aastha01chauhan** [comment]
like splitting a mp4 file into meta data file mp4 file and media.mp4 file as the issue states

**Comment by rbouqueau** [comment]
Here is a program that takes a MP4 files and split it in chunk files: https://github.com/cta-wave/Test-Content-Generation/blob/master/chunked/isobmff_chunker.py. You would need to modify the main function.

Could you dump the box structure of your file here? You can get it with: https://gpac.github.io/mp4box.js/test/filereader.html

**Comment by aastha01chauhan** [comment]
![image](https://github.com/gpac/gpac/assets/63860869/ef47da93-b552-4623-a415-0dc1265e838d)
Hi, this is box view in treemap view
were you talking about this?

**Comment by rbouqueau** [comment]
Yes but click on the 'Box View' tab please. We need to see the top boxes.

**Comment by aastha01chauhan** [comment]
Hi, I wanted my mp4 files to be in this format. https://github.com/uwdb/lightdb/tree/master/test/resources/red10
Where one file stores mp4 and the other stores just the metadata.mp4
A normal video player is unable to open the metadata.mp4 file

**Comment by aastha01chauhan** [comment]
> Yes but click on the 'Box View' tab please. We need to see the top boxes.

![image](https://github.com/gpac/gpac/assets/63860869/0d1af0c1-7187-4d41-9728-a00af1be1ba5)
is this what we want?

**Comment by rbouqueau** [comment]
I needed the default view. But the info is still on this subtab: there is just a 'moov' and a 'mdat' box.

You can modify the [script](https://github.com/cta-wave/Test-Content-Generation/blob/master/chunked/isobmff_chunker.py#L75) by writing a new file when seeing the 'mdat' (instead of the 'styp' in the current code). The code to create a new file is line 81.

**Comment by aastha01chauhan** [comment]
> I needed the default view. But the info is still on this subtab: there is just a 'moov' and a 'mdat' box.
> 
> You can modify the [script](https://github.com/cta-wave/Test-Content-Generation/blob/master/chunked/isobmff_chunker.py#L75) by writing a new file when seeing the 'mdat' (instead of the 'styp' in the current code). The code to create a new file is line 81.

Thank you. Do you think that will help me achieve something like this?
https://github.com/uwdb/lightdb/tree/master/test/resources/red10
Where one file stores mp4 and the other stores just the metadata.mp4
A normal video player is unable to open the metadata.mp4 file

**Comment by aastha01chauhan** [comment]
also, could you point out how can I get started with 

> Hi, I wanted my mp4 files to be in this format. https://github.com/uwdb/lightdb/tree/master/test/resources/red10 Where one file stores mp4 and the other stores just the metadata.mp4 A normal video player is unable to open the metadata.mp4 file @jeanlf

any thoughts on this @jeanlf?

**Comment by aastha01chauhan** [comment]
how can I get an m4s extension file for my mp4 file as it is required by this script? I tried renaming MP4 to m4s it did not work

**Comment by aastha01chauhan** [comment]
@jeanlf I tried using the mp4box command as you said, but it does not seem to copy the metadata box to the new file
![image](https://github.com/gpac/gpac/assets/63860869/bf2cfc5d-c06c-4a5a-89f0-0fbf347bb4f7)

**Comment by jeanlf** [comment]
Hmm not normal, dref always should work on ISOBMF sources - could you share your src file ?

**Comment by aastha01chauhan** [comment]
https://drive.google.com/file/d/1QlBPB5Zsy6M021oQyOcsu-yNAGuojAaa/view?usp=sharing

**Comment by aastha01chauhan** [comment]
are there any restrictions on type of videos? Is there any reason why dref is not working for this one?
