### ISSUE TITLE
Regression tests on latest nightly builds (Android)

### ISSUE THREAD

**Issue by fcsteagu** [gpac/gpac#327]
Hi,
I have noticed that videos, animations and user interaction in a BIFS scene running on an Android device are very (very) slow compared to how it used to be a while ago. For example in a more complex scene the TouchSensor is not even triggered most of the time (e.g. clicking a button).

Here's a simple example from regression tests where some interpolators are used with Layer3D: _bifs-3D-positioning-layer3D-views.bt_.
I don't know how can I see the fps on the Android device but there are no more than 5 fps. Could you investigate this issue or at least give me some hints on how should I proceed to fix this?

Thank you!

**Comment by jeanlf** [comment]
Latest versions now use GLES2 for 3D rendering and bitmap (video or images) bliting, make sure your device has a decent support for GLES2. You can also post the GPAC.cfg file to see if something is wrong in your setup.

**Comment by fcsteagu** [comment]
The device that I'm using is an LG Flex 2 (released in 2015, very powerful) and I'm also using some other devices for testing (e.g. Google Nexus 5, Samsung Galaxy S3/4).

I have attached my GPAC.cfg (renamed it to TXT in order to be able to upload it here).

I still believe that the problem is not related to the device...

[GPAC.txt](https://github.com/gpac/gpac/files/39245/GPAC.txt)

**Comment by jeanlf** [comment]
We can indeed reproduce the issue on some phones, we'll investigate and let you know

**Comment by fcsteagu** [comment]
Great news!
I was doing some more tests and I realized that on Google Nexus 5 it works _slightly_ better compared to LG Flex 2, the one that Viet has. I assume therefore that it might be also related to the device but I'm sure the problem is deeper than that.

I have tried to use the old config that I had but it makes no difference.
Then I was comparing the log files of the two devices and I got something strange in the one of LG Flex 2:

_I/Adreno  ( 9241): QUALCOMM build                   : d809d99, Ie081474390
 I/Adreno  ( 9241): Build Date                       : 04/28/15
 I/Adreno  ( 9241): OpenGL ES Shader Compiler Version: E031.25.03.07
 I/Adreno  ( 9241): Local Branch                     : LA.BF64.1.2.1_RB2.05.01.00.081.009
 I/Adreno  ( 9241): Remote Branch                    : 
 I/Adreno  ( 9241): Remote Branch                    : 
 I/Adreno  ( 9241): Reconstruct Branch               : 
 D/libc-netbsd(  424): res_queryN name = xxxxx succeed
 I/System.out( 9137): propertyValue:false
 D/libc-netbsd( 9137): [getaddrinfo]: hostname=xxxxx; servname=(null); cache_mode=(null), netid=0; mark=0
 D/libc-netbsd( 9137): [getaddrinfo]: ai_addrlen=0; ai_canonname=xxxxx; ai_flags=4; ai_family=0
 I/GBMv2   (  460): >>>GBM state is 1<<<
 I/MSM-irqbalance(  705): Decided to move IRQ159 from CPU4 [P:0] to CPU1 [P:1] (banned)
 D/KeyguardUpdateMonitor( 3337): isSimPinSecure() return  false
 D/KeyguardUpdateMonitor( 3337): isSimPinSecure() return  false
 D/KeyguardUpdateMonitor( 3337): isSimPinSecure() return  false
 **I/Adreno  ( 9241): GetNativeFormatFromQctPixelFormat: Invalid qct format (611)
 I/Adreno  ( 9241): GetNativeFormatFromQctPixelFormat: Invalid qct format (611)
 I/Adreno  ( 9241): GetNativeFormatFromQctPixelFormat: Invalid qct format (611)
 I/Adreno  ( 9241): GetNativeFormatFromQctPixelFormat: Invalid qct format (611)
 I/Adreno  ( 9241): GetNativeFormatFromQctPixelFormat: Invalid qct format (612)
 I/Adreno  ( 9241): GetNativeFormatFromQctPixelFormat: Invalid qct format (612)
 I/Adreno  ( 9241): GetNativeFormatFromQctPixelFormat: Invalid qct format (612)
 I/Adreno  ( 9241): GetNativeFormatFromQctPixelFormat: Invalid qct format (612)**
 D/KeyguardUpdateMonitor( 3337): isSimPinSecure() return  false
 D/KeyguardUpdateMonitor( 3337): isSimPinSecure() return  false
 I/ActivityManager( 1286): Displayed com.gpac.Osmo4/.Osmo4: +390ms
 I/Timeline( 1286): Timeline: Activity_windows_visible id: ActivityRecord{34ce091a u0 com.gpac.Osmo4/.Osmo4 t128} time:91217063
 D/KeyguardUpdateMonitor( 3337): isSimPinSecure() return  false
** V/GLSurfaceView( 9241): glGetString(7937) returns Adreno (TM) 430;**
 I/Osmo4Renderer( 9241): Creating instance from thread Thread[GLThread 1503,5,main]
 I/LibrariesLoader( 9241): Loading library GLESv2...
[...]_

**Comment by fcsteagu** [comment]
I was trying to debug Osmo4 on this LG Flex 2 and voila, it seems that the device has support for arm64-v8a. Maybe this is one of the problems?

_ABIs targetted by application: armeabi armeabi-v7a x86
Device API Level: 22
Device CPU ABIs: arm64-v8a  
ERROR: The device does not support the application's targetted CPU ABIs!
       **Device supports:  arm64-v8a** 
       Package supports: armeabi armeabi-v7a x86_

**Comment by jeanlf** [comment]
We believe we found the issue ( clipping was using discard or return , not well supported on gles2). Could you check if this solves your issue ?

**Comment by fcsteagu** [comment]
Hello,

I did some tests and the performance is __slightly__ better but unfortunately it does not fix the issue. If I turn the device horizontally (landscape mode) I still have exactly the same problem.

I noticed that in more complex scenes the TouchSensor is triggered very hard and the animation (e.g. resizing of a 2d shape) is again very slow.

I have found some weird behaviour in some other files from regression tests:
*bifs-2D-positioning-layer2D.bt* - the rotation of the shape is slow
*bifs-2D-painting-xlineproperties-compositetexture2D.bt* - the animated circles are not displayed
*bifs-2D-positioning-layout-scroll-on-off.bt* - the layout area is kind of shifted down. Because of this I think the text is not correctly rendered, when using layout to wrap it.

__I can provide you a more complex scene if you'd like but I need to create it first. The ones that I have are way to big.__ Please let me know if you would like me to create such a scene for testing purposes.

**Comment by jeanlf** [comment]
I just pushed a new version of the shaders without dynamic for loops which might also be problematic. Could you give it another try ?

**Comment by fcsteagu** [comment]
I don't notice visible improvements unfortunately.
Moreover I think the last changes introduced a bug in the layout node (bifs-2D-positioning-layout-scroll-on-off.bt). The shapes are still visible when they go out  of the layout but they are black (probably the texture is not applied...).

**Comment by fcsteagu** [comment]
I see no difference. Does the nigthly build already have the update?
thanks

**Comment by jeanlf** [comment]
yes they are up to date. Could you try with tha latest fix I pushed ? It might solve some of our issues (let's hope ...)

**Comment by fcsteagu** [comment]
hmmmmm I think you are on the right track!
**the interactivity and animations are MUCH better** but the layout node (layout2d also) are not rendered correctly. For example in _bifs-2D-positioning-layout-scroll-on-off.bt_ the circle and the square are not visible at all and in a more complex scene only a part of it it's rendered (everything is shifted to the left and down).

**Comment by rbouqueau** [comment]
Can we consider this issue solved?
