### ISSUE TITLE
AVG reports a virus 

### ISSUE THREAD

**Issue by ben-law** [gpac/gpac#328]
AVG and many other virus scanners reports a virus in the GPAC Windows installation and also in Osmo4.exe

**Comment by rbouqueau** [comment]
Where did the installer came from?

**Comment by cconcolato** [comment]
We've had issues in the past with the official builds and other anti-virus like Symantec but it was a false positive. We contacted Symantec to be on their white list, they checked and indeed Symantec does not report the installers as viruses. Maybe a similar thing could be done with AVG?

**Comment by ben-law** [comment]
@rbouqueau - The installer was downloaded from the official site.
@cconcolato - Thanks for the information. Will also try to get the software white-listed by AVG
