### ISSUE TITLE
Can MP4Box write "udta" atoms into the "moov" section?

### ISSUE THREAD

**Issue by lvml** [gpac/gpac#33]
I am still trying to convince my camera to replay an .MP4 file it recorded which I then re-muxed with MP4Box (as mentioned in issues #28 and #29 ). It seems that the one relevant remaining difference between the original and the re-muxed file is that the original contains a "udta" atom inside the "moov" section (hex "00 01 00 00 75 64 74 61" + 65528 bytes  of data) that contains some camera vendor specific stuff, I can see the camera model name in there as well as a JFIF preview-image of the video.

Now I wonder: Is there a feature available in MP4Box to insert such an "udta" atom into the "moov" section of the output file? If not, could one be implemented? (Just copying a blob from some binary input file into the "udta" atom should be sufficient.)

**Comment by jeanlf** [comment]
There is now such a feature in rev 5601. In your case :
-dump-udta PANA file.mp4 -out test.udta: will dump root udta(s) of type PANA as a set of boxes
-udta 0:box=test.udta file.mp4: will import root udta from test.udta

let me know if this help

**Comment by lvml** [comment]
Thanks a lot for implementing this feature!
The copying of the udta atom into the destination file works well.
But still, the camera refused to play the re-muxed file.
The remaining differences are really tiny, and I wonder how any of it might be relevant:

* the remuxed file contains a "free" section after the "moov" section that is sized such that the "mdat" begins at offset 0x20000. I modified isom_store.c a little to write a "free" section before "mdat" to make "mdat" begin at 0x20000, too, but that did not help. (However, my "free" writing wrote this section before "moov" - I found no easy way to write "free" after "moov" as in the original.)

* another minimal difference is about the interleaving - `MP4Box -info 1 ` on original vs. remuxed shows this diff (also when using `-inter 480`):
```
-       Chunk durations: min 480 ms - max 480 ms - average 480 ms
-       Chunk sizes (bytes): min 566720 - max 566720 - average 566720
+       Chunk durations: min 440 ms - max 520 ms - average 480 ms
+       Chunk sizes (bytes): min 443206 - max 684423 - average 574668
```

* The amount of samples described in `moov/trak/mdia/minf/stbl/stsc` differs a little: In the original file, 6 samples are described, only 3 in the remuxed file. I've got no idea about the function of this table...

Any ideas left?

**Comment by jeanlf** [comment]
you may try to change the interleaving size (using -inter switch), that's what the stsc table is about

**Comment by pengbins** [comment]
Does this diffrence matters?

> * the remuxed file contains a "free" section after the "moov" section that is sized such that the "mdat" begins at offset 0x20000. I modified isom_store.c a little to write a "free" section before "mdat" to make "mdat" begin at 0x20000, too, but that did not help. (However, my "free" writing wrote this section before "moov" - I found no easy way to write "free" after "moov" as in the original.)

Is it possibale to write "free" between "moov" and "mdata" as in the original ?

**Comment by jeanlf** [comment]
It shouldn't, free boxes are supposed to be skipped by file readers. You can try using a boxpatch to delete/insert the free box, see [this example](https://github.com/gpac/testsuite/blob/filters/scripts/boxpatch.sh).
