### ISSUE TITLE
Error while trying to create dashcast stream using libx265

### ISSUE THREAD

**Issue by trrahul** [gpac/gpac#331]
I'm trying to create a h265 encoded stream from webcam using the following command.

DashCast -vf video4linux2  -v4l2f mjpeg -v /dev/video0 -conf dashcast.conf -live-media

The content of dashcast.conf is

[v1]
type=video
codec=libx265
bitrate=1000000
framerate=25
width=640
height=480

But I'm getting this error.

Options:
    video source: /dev/video0
    video format: video4linux2
    v4l2 format: mjpeg
    video crop: 0x0
    audio source: 
Configurations:
    id:v1   res:640x480 vbr:1000000
[mjpeg @ 0xb194e0] Changeing bps to 8
Input #0, video4linux2,v4l2, from '/dev/video0':
  Duration: N/A, start: 50349.327770, bitrate: N/A
    Stream #0:0: Video: mjpeg, yuvj422p(pc, bt470bg/unknown/unknown), 1280x720, -5 kb/s, 30 fps, 30 tbr, 1000k tbn, 1000k tbc
AVCTX give frame duration of 1/1000000 - keeping requested rate -1, but this may result in unexpected behaviour.
[swscaler @ 0xb91ea0] deprecated pixel format used, make sure you did set range correctly
Press q or Q to exit...
[dashcast] Live system dropped a video frame
[dashcast] Live system dropped a video frame
x265 [info]: HEVC encoder version 1.8+1-5dcc9d3a928c400b
x265 [info]: build info [Linux][GCC 4.8.4][64 bit] 8bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX AVX2 FMA3 LZCNT BMI2
x265 [info]: Main profile, Level-3 (Main tier)
x265 [info]: Thread pool created using 4 threads
x265 [info]: frame threads / pool features       : 1 / wpp(8 rows)
[dashcast] Live system dropped a video frame
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : hex / 57 / 2 / 2
x265 [info]: Keyframe min / max / scenecut       : 25 / 250 / 40
x265 [info]: Lookahead / bframes / badapt        : 20 / 4 / 2
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 0
x265 [info]: References / ref-limit  cu / depth  : 3 / 0 / 0
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 1 / 1.0 / 32 / 1
x265 [info]: Rate Control / qCompress            : ABR-1000 kbps / 0.60
x265 [info]: tools: rd=3 psy-rd=0.30 signhide tmvp strong-intra-smoothing
x265 [info]: tools: deblock sao
Cannot parse HEVC/H265 SPS/PPS
Bad Parameter: dc_gpac_video_write_config
Bad Parameter: gf_isom_start_segment
Cannot open output video file.
Generating MPD at 2015-11-24T19:17:46.040Z
StartTime: 2015-11-24T19:17:46.040Z - startNumber 1 - last number 1
Keyboard thread exit
[dashcast] Live system dropped a video frame
[dashcast] Live system dropped a video frame

What could be the problem? Changing codec to libx264 in the conf file works fine.

**Comment by jeanlf** [comment]
that's likely a misalignment of versions , which GPAC version are you using ?

**Comment by trrahul** [comment]
I'm using version 0.5.0

**Comment by jeanlf** [comment]
please only try dashcast with the latest version on git. On which OS are you trying this ?

**Comment by trrahul** [comment]
I'm using Ubuntu 14.04

**Comment by jeanlf** [comment]
OK and how did you install avcodec and libx265 ?

**Comment by trrahul** [comment]
I installed libx265 by following this guide.
https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu

To install ffmpeg, I downloaded the latest source and I had to edit the ffmpeg configure file. I changed cc_default="gcc" to cc_default="gcc -fPIC" 
and 
host_cc_default="gcc" to host_cc_default="gcc -fPIC" 
otherwise building resulted in a error.

I used the following commade to configure.
./configure --pkg-config-flags="--static" --enable-shared --disable-stripping --enable-gpl --enable-version3 --enable-runtime-cpudetect --enable-pthreads --enable-libx265 --enable-libx264 --enable-avresample --enable-x11grab --enable-nonfree --enable-libvo-aacenc --enable-libpulse

**Comment by jeanlf** [comment]
this should now be fixed, thanks for the report. Re-open if needed

**Comment by trrahul** [comment]
Yes, it works now. Thank you. I am getting a lot of ``` [dashcast] Live system dropped a video frame```. Could you tell me what casues the frame drops?

**Comment by trrahul** [comment]
Thank you, this error is gone now. Now  I'm getting segementation fault when I try to play the stream.
``` 
rahul@inntot-HP-15-Notebook-PC:~/DASH/temp/output$ MP4Client dashcast.mpd
Using config file in /home/rahul/.gpac directory 
System info: 3884 MB RAM - 4 cores
Modules Found : 37 
Loading GPAC Terminal
Terminal Loaded in 129 ms
Opening URL dashcast.mpd
Segmentation fault (core dumped)
```
Also I'm getting lots of ``` [video_encoder] Rep v1 UTC diff at segment close: 20105 is lower than cumulated segment duration 23000 (diff -2895) - frame rate is probably not correct or frames were lost! ``` and ``` [dashcast] Live system dropped a video frame ``` from DashCast

This is what I have in dashcast.mpd
```
<?xml version="1.0"?>
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" availabilityStartTime="2015-11-26T05:26:53.232Z" minBufferTime="PT1.000000S" timeShiftBufferDepth="PT00H00M10S" type="dynamic" profiles="urn:mpeg:dash:profile:full:2011">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>dashcast.mpd</Title>
 </ProgramInformation>
 <Period start="PT0H0M0.000S" id="P1">
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="false">
   <SegmentTemplate timescale="10" duration="10" media="$RepresentationID$_$Number$_gpac.m4s" startNumber="1" initialization="$RepresentationID$_init_gpac.mp4"/>
   <Representation id="v1" mimeType="video/mp4" codecs="hvc1.1.6.L90.90" width="640" height="480" frameRate="10" sar="1:1" startWithSAP="1" bandwidth="1000000">
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>

```
