### ISSUE TITLE
"pcr" in pcrb box is 48-bits long, but gpac reads and writes 64 bits for it

### ISSUE THREAD

**Issue by brendanlong** [gpac/gpac#34]
In [the DASH spec](http://standards.iso.org/ittf/PubliclyAvailableStandards/c065274_ISO_IEC_23009-1_2014.zip) (6.4.7.2 MPEG-2 TS PCR information box):

    aligned(8) class MPEG2TSPCRInfoBox extends Box(‘pcrb’, 0) {
        unsigned int(32) subsegment_count;
        for( i = 1; i <= subsegment_count; i++){
            unsigned int(42) pcr;
            unsigned int(6) pad = 0;
        }
    }

`pcr` + `pad` is 48 bits long, but in [`src/isomedia/box_code_base.c`](https://svn.code.sf.net/p/gpac/code/trunk/gpac/src/isomedia/box_code_base.c) functions you read and write them as 64-bit values:

    GF_Err pcrb_Read(GF_Box *s,GF_BitStream *bs)
    {
	    u32 i;
	    GF_PcrInfoBox *ptr = (GF_PcrInfoBox*) s;

	    ptr->subsegment_count = gf_bs_read_u32(bs);
	    ptr->size -= 4;

	    ptr->pcr_values = gf_malloc(sizeof(u64)*ptr->subsegment_count);
	    for (i=0; i<ptr->subsegment_count; i++) {
		    u64 data1 = gf_bs_read_u32(bs);
		    u64 data2 = gf_bs_read_u32(bs);
		    ptr->size -= 8;
		    ptr->pcr_values[i] = (data1 << 10) | (data2 >> 22);

	    }
	    return GF_OK;
    }

    GF_Err pcrb_Write(GF_Box *s, GF_BitStream *bs)
    {
	    GF_Err e;
	    u32 i;
	    GF_PcrInfoBox *ptr = (GF_PcrInfoBox*) s;

	    e = gf_isom_box_write_header(s, bs);
	    if (e) return e;

	    gf_bs_write_u32(bs, ptr->subsegment_count);

	    for (i=0; i<ptr->subsegment_count; i++ ) {
		    u32 data1 = (u32) (ptr->pcr_values[i] >> 10);
		    u32 data2 = (u32) ((ptr->pcr_values[i]& 0x3FF) << 22);

		    gf_bs_write_u32(bs, data1);
		    gf_bs_write_u32(bs, data2);
	    }
	    return GF_OK;
    }

    GF_Err pcrb_Size(GF_Box *s)
    {
	    GF_Err e;
	    GF_PcrInfoBox *ptr = (GF_PcrInfoBox*) s;
	    e = gf_isom_box_get_size(s);
	    if (e) return e;

	    ptr->size += 4;
	    ptr->size += ptr->subsegment_count * 8;

	    return GF_OK;
    }

**Comment by jeanlf** [comment]
thanks for the report, should now be now fixed in rev 5613.
