### ISSUE TITLE
MP4BOX vobsub extraction results in bad .idx file

### ISSUE THREAD

**Issue by gsnyder2015** [gpac/gpac#341]
If I extract VOBSUB .idx and .sub files from an MP4 file, the resulting .idx file is bad.  This used to work in previous versions of mp4box.  The problem appears to be the offsets are written to the file as a decimal string instead of in hex like it used to.  This is an issue in the latest overnight build and goes back at least as far as gpac-0.5.2-DEV-rev724

For example:

Current output:
langidx: 0
id: en, index: 0
timestamp: 00:01:11:371, filepos: 000000000
timestamp: 00:01:28:621, filepos: 000004096
timestamp: 00:01:36:496, filepos: 000006144
timestamp: 00:01:44:104, filepos: 000010240

Previous (correct) output:
langidx: 0
id: en, index: 0
timestamp: 00:01:11:371, filepos: 000000000
timestamp: 00:01:28:621, filepos: 000001000
timestamp: 00:01:36:496, filepos: 000001800
timestamp: 00:01:44:104, filepos: 000002800

**Comment by jeanlf** [comment]
indeed there is a bug on windows version. Could you check if this now works with last git ?

**Comment by gsnyder2015** [comment]
Thanks for the quick response.  I'm only using the nightly builds. Can I check it on the next nightly build?

**Comment by jeanlf** [comment]
Yes,now available

**Comment by gsnyder2015** [comment]
Looks good.  The subs open up in BDSup2sub now without error.  Thanks again.
