### ISSUE TITLE
DASHCAST: MP4Client

### ISSUE THREAD

**Issue by irrz** [gpac/gpac#342]
Hello there,

I did set up the code in my Linux Ubuntu platform, and I typed the command of Live streaming from my webcam, as the following command "DashCast -vf video4linux2 -vfr 30 -vres 650x480 -v /device/video0 -live".

I got some of the output coming in changeable files in the "Output" folder, which is in the directory of GPAC.

However, I want to visualise these streams, by using the MP4Client for example, as it is stated in your documentation. But unfortunately I don't know how to manage the viewing of this live stream by the use of the MP4Client.

I am really intersted in making some contribution in this field, and I am looking forward to getting the answer of how to visualise the output files.

All regards,

**Comment by trrahul** [comment]
Assuming your output folder has a dashcast.mpd file,  type in ```MP4Client dashcast.mpd```.

**Comment by jeanlf** [comment]
correct.
If you want to keep all the files, add the following option "-time-shift -1". With that, once you are done recording, changing the type of session from "type=dynamic" to "type=static" in the MPD will allow replay of the session.
