### ISSUE TITLE
Compiling GPAC on Raspberry Pi

### ISSUE THREAD

**Issue by matt2xu** [gpac/gpac#343]
Hi,

I'm trying to compile GPAC on a Raspberry Pi 2 (model B) with the aim of playing DASH content using MP4Client.

Has this been done before?
Is it even possible? I mean, I have managed to compile GPAC (with disable-vrml because configure cannot find the Javascript library), but when I run MP4Client it doesn't display anything. I tried configure with disable-3d (because MP4Client complained about not being able to open a GL display), but it doesn't seem to help. Since the Raspberry Pi has a somewhat non-standard architecture (Broadcom SoC with integrated GPU), maybe there is something specific that I need to set?

I am compiling directly on the board, so I don't need to set up a cross-compiling environment, and also the board is fast enough so compilation is reasonably fast.

Thank you,
Matthieu

**Comment by jeanlf** [comment]
this should be possible, although not tested here. Which distro do you use ?
I would suggest to use libSDL for audio/video output support in case of troubles

**Comment by matt2xu** [comment]
I'm on Raspbian (the distribution recommended by the board makers). I'll see what happens if I keep only SDL and disable the other options.

**Comment by rbouqueau** [comment]
Could you solve your issue?

**Comment by matt2xu** [comment]
In a way, I switched to omxplayer with ffmpeg, which I also compiled on the Raspberry Pi 2.
