### ISSUE TITLE
manifest.mpd reports codecs="avc3.42c01e" causing some incompatibilities with some browsers (dash.js)

### ISSUE THREAD

**Issue by arnaudleyder** [gpac/gpac#345]
I am on Windows 10 64-bits with GPAC version 0.5.2-DEV-rev1067-g9cfa0d1-master 64 bits.
I am dashing with:
```mp4box.exe -dash 10000 -profile live -out out/manifest.mpd .\audio.mp4 .\video.mp4```

I am getting:
```xml
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.5.2-DEV-rev1067-g9cfa0d1-master  at 2015-12-02T13:18:45.519Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H10M53.846S" maxSegmentDuration="PT0H0M10.005S" profiles="urn:mpeg:dash:profile:isoff-live:2011">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>out/manifest.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H10M53.846S">
  <AdaptationSet segmentAlignment="true" lang="eng">
   <Representation id="1" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="48000" startWithSAP="1" bandwidth="129649">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <SegmentTemplate timescale="48000" media="audio_dash$Number$.m4s" startNumber="1" duration="479988" initialization="audio_dashinit.mp4"/>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" maxWidth="640" maxHeight="360" maxFrameRate="24" par="16:9" lang="eng">
   <Representation id="2" mimeType="video/mp4" codecs="avc3.42c01e" width="640" height="360" frameRate="24" sar="1:1" startWithSAP="1" bandwidth="538804">
    <SegmentTemplate timescale="12288" media="video_dash$Number$.m4s" startNumber="1" duration="122880" initialization="video_dashinit.mp4"/>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```
This works great with dash.js 1.5.1 but for one details:
codecs="avc3.42c01e" is causing Internet Explorer 11 to not recognize the stream (black screen). If I manually change to codecs="avc1.42c01e" in the manifest then it works as expected.

Question:
Is avc3.42c01e a standard codec notation? I was under the impression that avc1.xxxx was. 
How can I make it so that codecs information are reported with avc1.xxxx instead of avc3.xxxx in manifest.mpd?

Thanks
Arnaud

**Comment by jeanlf** [comment]
if avc3 is not supported, you have to disable bitstream switching when generating the MPD - add "-bs-switching no" to MP4Box command line

**Comment by arnaudleyder** [comment]
Thanks for the feedback. Just adding for reference that using -profile dashavc264:onDemand also solves this issue.
