### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by DejanNinic** [gpac/gpac#346]
Hi,
had to post my question here, couldn't found any other contact addresses.
I'm writting Linux gui for MP4Box. Thinking of calling it MP4Bg or MP4BG but am afraid of eventual copyright issues because of "MP4" in the name.
Of course, GPAC team uses it, but that is different.
Please advise and after that this topic can be erased.
Thanks in advance.

**Comment by jeanlf** [comment]
We don't know about any copyright on "MP4" names, but we are not lawyers so you'd better check with one if you want to be sure ....
