### ISSUE TITLE
[AVAudioResampleContext @ 0x7ff1000012e0] Invalid input channel layout: 0

### ISSUE THREAD

**Issue by trrahul** [gpac/gpac#347]
While trying to run this command `DashCast -vf video4linux2 -vres 320x240 -vfr 24 -v4l2f mjpeg -v /dev/video0 -af alsa -a plughw:1,0 -live` , I get the error 

```
Input #0, alsa, from 'plughw:1,0':
  Duration: N/A, start: 1449489842.427411, bitrate: 1536 kb/s
    Stream #0:0: Audio: pcm_s16le, 48000 Hz, 2 channels, s16, 1536 kb/s
[AVAudioResampleContext @ 0x7ff1000012e0] Invalid input channel layout: 0
Could not open the audio resampler. Aborting.
An error occurred while reading audio frame.
```

 It is also mentioned in https://github.com/gpac/gpac/issues/198.

`arecord -l` displays  the following

```
**** List of CAPTURE Hardware Devices ****
card 1: PCH [HDA Intel PCH], device 0: ALC282 Analog [ALC282 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

and I could record audio with arecord. What could be the problem here?

**Comment by jeanlf** [comment]
dashcast is deprecated, use GPAC 0.9.0 DEV
