### ISSUE TITLE
MP42TS bitrate accuracy

### ISSUE THREAD

**Issue by angusbell** [gpac/gpac#348]
I'd like some explanation of how accurate the bitrate of transport streams created by MP42TS is.

For example, I multiplexed one audio and one video in the same service, specifying -rate 8000.

The command line reported:
> Done muxing - 300 sec - average rate 8009 kbps 1597738 packets written

This suggests that the actual bitrate is 8,009,000 bps, and that it may not be constant. However, if I open the resulting stream in some other tools, they all report the bitrate as 8,000,000 bps. This includes DVB Analyser, DekTec StreamXpress, Tektronix Multiplexer and Tektronix TS Compliance Analyser.

It's important to us that the bitrate of the transport stream is accurate and constant.

First of all, please confirm whether my assumption is correct: that specifying "-rate 1" indicates a requested bitrate of 1000 bps, as opposed to 1024 bps.

Secondly, can you comment on the above conflicting diagnostics?

**Comment by jeanlf** [comment]
1) all rates are in N* 1000 bits per seconds yes
2) I need to check, likely a rounding issue in the stat dumping

**Comment by jeanlf** [comment]
2) should be fixed, it was a bug in printing the results

**Comment by angusbell** [comment]
thanks for that - so does that mean that the rate specified in the input parameter was always correct?

and can you explain wha's meant by "average rate"? does it mean that the number of bits per second is constant or not?

**Comment by jeanlf** [comment]
yes the rate specified as input was correct

maybe we should say in the stats "average bitrate" only when the -rate option is not given, that would clarify things ...

**Comment by angusbell** [comment]
thanks for your help!
