### ISSUE TITLE
DashCast transcoding LIVE TS file from Enigma 2 (HTTP.TS) 

### ISSUE THREAD

**Issue by adetheprince** [gpac/gpac#351]
Hi there, Back to Gpac after playing around with ffmpeg.

I have managed to transcode the live stream that is coming from Http input as .ts ( Enigma 2 Dreambox )using ffmpeg with no problem, but tried to play around with Dashcast and I am just ending up with errors , tried so many commands that I found them on Gpac website but to no lack. Here is the command I used for transcoding live ts to mpd file.

DashCast -av http://puplic-ip.ts -vfr 30 -vres 1280x720  -seg-dur 1000 -frag-dur 200 -conf /usr/local/nginx/html/config/testconf.conf -live -out /usr/local/nginx/html/dashed -mpd livetest.mpd

And I get this erros

MPD refresh time not set in live - defaulting to segment duration
Options:
    video source: http://puplic-ip.ts
    video framerate: 30
    video resolution: 1280x720
    video crop: 0x0
    audio source: http://puplic-ip.ts
Configurations:
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mpeg2video @ 0x122cca0] mpeg_decode_postinit() failure
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mp1 @ 0x1222980] Header missing
[mpegts @ 0x11fcc00] max_analyze_duration reached
[mpegts @ 0x11fcc00] Estimating duration from bitrate, this may be inaccurate
Input #0, mpegts, from 'http://puplic-ip.ts':
  Duration: N/A, start: 54677.575367, bitrate: 15192 kb/s
  Program 54140
  Program 54115
  Program 54165
  Program 54113
  Program 54120
  Program 54110
  Program 54175
  Program 54107
  Program 54180
  Program 54112
  Program 54185
  Program 54170
  Program 54101
  Program 54167
  Program 54102
  Program 54103
  Program 54150
  No Program
    Stream #0.0[0x90c]: Video: mpeg2video (Main), yuv420p, 704x576 [PAR 12:11 DAR 4:3], 15000 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0.1[0x906]: Audio: mp1, 0 channels, s16p
    Stream #0.2[0x90d]: Audio: mp2, 48000 Hz, 2 channels, s16p, 192 kb/s
AVCTX give frame duration of 1/50 - keeping requested rate 30, but this may result in unexpected behaviour.
Error: invalid audio sample rate: 0
Press q or Q to exit...
Keyboard thread exit

puplic-ip is replaced with my real puplic-ip ,so file works fine with mp4client/vlc before transcoding . 
here is the ffmpeg that works with no issue. 

ffmpeg -i http://public-ip.ts -c:a libfdk_aac -ab:a 256k -c:v libx264 -s:v 640x360 -b:v 768k -ar 44100 -f segment -segment_time 10 -segment_list_type flat -segment_list_type m3u8 -segment_list /usr/share/nginx/html/livestreams/playlist.m3u8 -segment_format mpegts -segment_list_flags +live stream-%09d.ts.

. ffmpeg works fine with the above code, so I am amusing all lib are fine but just cant figure it out.

**Comment by jeanlf** [comment]
which version of ffmpeg, libavcodec, libavformat and GPAC are you using ?are you sure the same version of libav* are used for both DashCast and ffmpeg ?

**Comment by adetheprince** [comment]
Hi Jeanlf

Not sure how do i get all that but if you mean this? or Can you tell me the command to get that as I installed ffmpeg from build.


ffmpeg
ffmpeg version N-76583-g3df9ec5 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
  configuration: --prefix=/home/satdoc/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/satdoc/ffmpeg_build/include --extra-ldflags=-L/home/satdoc/ffmpeg_build/lib --bindir=/home/satdoc/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      55.  5.100 / 55.  5.100
  libavcodec     57. 15.100 / 57. 15.100
  libavformat    57. 14.100 / 57. 14.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 15.100 /  6. 15.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfi

**Comment by jeanlf** [comment]
for gpac, you need to check which libav* was picked (eg /usr/lib or ...) in config.mak and check the version of the libs based on that info

**Comment by jeanlf** [comment]
dashcast is deprecated, use GPAC 0.9.0 DEV
