### ISSUE TITLE
Can't play output of DashCast on Chrome with Dash.js

### ISSUE THREAD

**Issue by ayuk23** [gpac/gpac#352]
Our team is trying to play videos encoded in DashCast with the Dash.js player on Chrome. For some reason it seems like the output of our DashCast encoding can't be played. Oddly, we get can the videos to play on one of our team member's browsers using IE, but the videos cannot be played on any of our computers using Chrome.

DashCast -v SampleVideo_720x480_50mb.mp4 -seg-dur 1000 -frag-dur 200 -mpd-refresh 1 -low-delay

Below is our console log.

[dash.js 1.5.1] new MediaPlayer instance has been created 
dash.all.js:11 Playback initiated! 
dash.all.js:11 Parsing complete: ( xml2json: 5ms, objectiron: 1ms, total: 0.006s) 
dash.all.js:11 Manifest has been refreshed at Wed Dec 16 2015 02:01:50 GMT-0500 (EST)[1450249310743]  
dash.all.js:11 MediaSource is open! 
dash.all.js:11 [object Event] 
dash.all.js:11 Duration successfully set to: 0 
dash.all.js:11 Added 0 inline events 
dash.all.js:11 video codec: video/mp4;codecs="avc1.64001e" 
dash.all.js:11 [video] stop 
dash.all.js:11 No audio data. 
dash.all.js:11 No text data. 
dash.all.js:11 No fragmentedText data. 
dash.all.js:11 No muxed data. 
dash.all.js:11 [video] start 
dash.all.js:11 [video] Getting the request for time: 0 
dash.all.js:11 [video] Index for time 0 is 0 
dash.all.js:11 [video] SegmentTemplate: 0 / 1 
dash.all.js:11 loaded video:Initialization Segment:NaN (200, 0ms, 63ms) 
dash.all.js:11 [video] Initialization finished loading 
dash.all.js:11 [video] Getting the request for time: 1 
dash.all.js:11 [video] Index for time 1 is 0 
dash.all.js:11 [video] SegmentTemplate: 0 / 1 
dash.all.js:11 [video] Signal complete. 
dash.all.js:11 [video] Stalling Buffer 
dash.all.js:11 [video] Waiting for more buffer before starting playback. 
dash.all.js:11 [video] Getting the request for time: 0 
dash.all.js:11 [video] Index for time 0 is 0 
dash.all.js:11 <video> loadedmetadata 
dash.all.js:11 Starting playback at offset: 0 
dash.all.js:11 [video] seek: 0 
dash.all.js:11 [video] Getting the request for time: 0 
dash.all.js:11 [video] Index for time 0 is 0 
dash.all.js:11 [video] SegmentTemplate: 0 / 1 
dash.all.js:11 [video] Signal complete. 
dash.all.js:4 GET http://137.112.104.147:8088/output/v1_1_gpac.m4s net::ERR_INCOMPLETE_CHUNKED_ENCODINGd 
dash.all.js:11 failed video:Media Segment:0 (0, 29ms, 122964ms) 
dash.all.js:11 Failed loading fragment: video:Media Segment:0, retry in 500ms attempts: 3 

Any help would be appreciated. Thanks!

**Comment by jeanlf** [comment]
That's likely a Chrome issue, closing. Have you tried searching for possible cause of this error ? Plenty of discussions out there on the topic.

**Comment by ayuk23** [comment]
We've been searching for multiple days. Could you possibly point me to one of these discussions that solves this error? I have yet to find anything similar.

**Comment by leandropjp** [comment]
@ayuk23 the mpd generated does not have publish time and the available start time is 1900 and the dash.js could use this year as the start of the streaming as result he will looking for segments with big numbers. I did the change in my dashcast and recompiled. All mpd information is in controller.c

**Comment by ayuk23** [comment]
@leandropjp Thanks for the response! I'm a bit unclear still exactly what you mean. What should the publish time and start time be set to in order for it to work?

**Comment by leandropjp** [comment]
@ayuk23 First of all, you need to check the mpd generated by the dashcast ( http://dashif.org/conformance.html ) to check if the mpd is compatible with dash.js. If not, you to check what is the problem. When I checked the mpd was without MPD@publishtime, which one is required by the dash.js. So, go to controller.c inside your dashcast folder, I put manually the publishtime inside the MPD. I used the MP4Box publish time code and put inside controller.c 
This is my code but I still have some audio problems using DashCast with UDP Streaming.

`
fprintf(f, "<?xml version=\"1.0\"?>\n");
	fprintf(f, "<MPD xmlns=\"urn:mpeg:dash:schema:mpd:2011\" "
	        "%s=\"%s\" "
	        "minBufferTime=\"PT%fS\" %s type=\"%s\" "
	        "profiles=\"urn:mpeg:dash:profile:full:2011\"",
	        (cmddata->mode == ON_DEMAND) ? "mediaPresentationDuration" : "availabilityStartTime",
	        (cmddata->mode == ON_DEMAND) ? presentation_duration : availability_start_time,
	        cmddata->min_buffer_time, time_shift,
	        (cmddata->mode == ON_DEMAND) ? "static" : "dynamic");

//set publish time
#ifndef _WIN32_WCE
		gtime = sec - GF_NTP_SEC_1900_TO_1970;
		t = gmtime(&gtime);
		fprintf(mpd, " publishTime=\"%d-%02d-%02dT%02d:%02d:%02dZ\"", 1900+t->tm_year, t->tm_mon+1, t->tm_mday, t->tm_hour, t->tm_min, t->tm_sec);
#else
		GetSystemTime(&syst);
		fprintf(mpd, " publishTime=\"%d-%02d-%02dT%02d:%02d:%02dZ\"", syst.wYear, syst.wMonth, syst.wDay, syst.wHour, syst.wMinute, syst.wSecond);
#endif
`

**Comment by ayuk23** [comment]
@leandropjp Thanks for your help. It doesn't seem to be working as I'm constantly getting build errors with the new code from undefined or incorrectly defined references, that I've been tweaking around for hours to try to fix... :(

Anyway that you could post your whole controler.c file so that I could try it? Also, out of curiousity, are you using a similar command as 
"DashCast -v video.mp4 -seg-dur 1000 -frag-dur 200 -mpd-refresh 1 -low-delay"

Thanks again for all of your help!

**Comment by ulrichghislain** [comment]
Hello i need a help please , i'am a beginner on dashcast 
i have a stream mpeg2ts and i want to have a stream dashcast 
this is command that i'm typing
"DashCast -av udp://@239.x.x.x:1234?fifo_size=3000000 -live -seg-dur 8000 -mpd-refresh 8 -time-shift -1 -min-buffer 10 -npts -conf config_dashcast.conf -ast-offset 16000" then i just have a folder output empty (no chunk stream inside)

i get this error in command ---->"[mpegts @ 0x24561e0] Could not find codec parameters for stream 6 (Unknown: none ([5][0][0][0] / 0x0005)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options"

----->"Assertion desc failed at libswscale/swscale_internal.h:674
thanks in advance
