### ISSUE TITLE
extract audio using mp4box.js

### ISSUE THREAD

**Issue by mdownplane** [gpac/gpac#355]
I can't tell from the limited documentation how to do this.  It is clearly possible in the command line version: MP4Box -raw 2 file.mp4
What is the equivalent in the JavaScript version?

Thanks.

**Comment by jeanlf** [comment]
no equivalent, you would have to code it yourself, mp4box.js doesn't provide tools for importing/extracting into other formats, it only gives tools to manipulate the samples in ISO files

**Comment by cconcolato** [comment]
Actually, mp4box.js can do what you want. Look for the extraction option: 
https://github.com/gpac/mp4box.js#extraction
File an issue with MP4Box.js if this is not working for you.
