### ISSUE TITLE
how to add decoding gif

### ISSUE THREAD

**Issue by sky-code** [gpac/gpac#356]
How to add gif support into MP4Box?

I Need to convert svg to mp4 "as is", but svg contains gif animated images and MP4Box just ignore this images, how can i add gif decoder into MP4Box?

Please see https://github.com/sky-code/svg_mp4_examples examples of svg with external and inlined gif images and result of convert operation

In general how to convert svg "as is" into any video format with all animations, images and other stuff? Just like a browser render svg, but render in video file

**Comment by jeanlf** [comment]
there's no official support for gif storage in isobmf files, you should try converting them to PNG first if possible
