### ISSUE TITLE
-url-template not reliable, may try to load non-existing segment

### ISSUE THREAD

**Issue by blacktrash** [gpac/gpac#360]
Test stream: http://media.blacktrash.org/fp/test/night1.mpd

The dash.js (I can't get Osmo to work on OS X, only white screen) sample player tries to load http://media.blacktrash.org/fp/test/night1/dash/1-6.m4s as last audio segment which does not exist.

Counter example without template: http://stream.flowplayer.org/night1.mpd works without problems.

Segment template for the audio representation is:

```xml
<SegmentTemplate timescale="44100" media="$RepresentationID$-$Number$.m4s" startNumber="1" duration="88064" initialization="$RepresentationID$-.mp4"/>
```

Maybe because 88064 / 44100 = 1.99691609977324263038 is minutely less than 2 (2 second segments)?

See also: https://github.com/Dash-Industry-Forum/dash.js/issues/950

Maybe related or duplicate of #223.

**Comment by rbouqueau** [comment]
Not related to #223. If you take the source and execute ```MP4Box -info``` on it, what does it print? I'm suspecting the audio is really shorter that the period duration.

**Comment by blacktrash** [comment]
Which source? The init 1-.mp4? Or the mpd?
I'm certain that the MP4 before segmenting has audio and video tracks of the same duration. I'll have to re-run because those MP4s are temporary.

**Comment by rbouqueau** [comment]
> I'm certain that the MP4 before segmenting has audio and video tracks of the same duration. I'll have to re-run because those MP4s are temporary.

That's the one I'm talking about.

I think the period duration is not consistent between audio and video. So dash.js expects a last tiny audio segment (that may exist (or not) according to the spec). I think the video is 10s and the audio is 9.98s (MPEBox -info will confirm or infirm this).

Audio and video cannot be exactly the same size because of AAC framining anyway. So if y hypothesis is correct, I would expect that dash.js supports this.

**Comment by blacktrash** [comment]
As you can see the duration is exactly the same for the video and audio streams, it's the same for all other segmented streams, as well as for the `out_*` files created by MP4Box in the same directory:
```
$ MP4Box -info night1-360p.mp4
* Movie Info *
        Timescale 1000 - Duration 00:00:10.000
        2 track(s)
        Fragmented File: no
        File Brand isom - version 512
        Created: UNKNOWN DATE   Modified: UNKNOWN DATE
File has no MPEG4 IOD/OD

iTunes Info:
        Encoder Software: Lavf57.21.100
1 UDTA types: meta (1)

Track # 1 Info - TrackID 1 - TimeScale 12800 - Media Duration 00:00:10.000
Track has 1 edit lists: track duration is 00:00:10.000
Media Info: Language "und (und)" - Type "vide:avc1" - 250 samples
Visual Track layout: x=0 y=0 width=640 height=360
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x21
AVC/H264 Video - Visual Size 640 x 360
        AVC Info: 1 SPS - 1 PPS - Profile Main @ Level 3.1
        NAL Unit length bits: 32
        Pixel Aspect Ratio 1:1 - Indicated track size 640 x 360
        SPS#1 hash: 99CDBE4ACA5C41BA5114374E034772EAD0C5E0A9
        PPS#1 hash: DDFC20980FA58C749DA8A636F7ED75EE48E3ED79
Self-synchronized
        RFC6381 Codec Parameters: avc1.4d401f
        Average GOP length: 62 samples

Track # 2 Info - TrackID 2 - TimeScale 44100 - Media Duration 00:00:10.000
Track has 1 edit lists: track duration is 00:00:10.000
Media Info: Language "und (und)" - Type "soun:mp4a" - 216 samples
MPEG-4 Config: Audio Stream - ObjectTypeIndication 0x40
MPEG-4 Audio SBR - 2 Channel(s) - SampleRate 22050 - SBR: SampleRate 44100 Type MPEG-4 Audio AAC LC
Synchronized on stream 1
        RFC6381 Codec Parameters: mp4a.40.5
Alternate Group ID 1
        All samples are sync

$ ffprobe -v warning -show_entries stream=profile,duration night1-360p.mp4
[STREAM]
profile=Main
duration=10.000000
[/STREAM]
[STREAM]
profile=HE-AAC
duration=10.000000
[/STREAM]
```
MP4Box -info gets the AAC profile wrong though, it's ok though in the resulting mpd.

**Comment by rbouqueau** [comment]
Happy new year!

> MP4Box -info gets the AAC profile wrong though

1) Could you please explicit so that we can solve the issue? :)

> Track # 2 Info - TrackID 2 - TimeScale 44100 - Media Duration 00:00:10.000
Track has 1 edit lists: track duration is 00:00:10.000
Media Info: Language "und (und)" - Type "soun:mp4a" - 216 samples
MPEG-4 Config: Audio Stream - ObjectTypeIndication 0x40
MPEG-4 Audio SBR - 2 Channel(s) - SampleRate 22050 - SBR: SampleRate 44100 Type MPEG-4 Audio AAC LC

If I do the math: 1024 / 22050 * 216 = 10.03s. So the indicated duration may either be modified by the edit list or last-segment-duration-adjusted-to-fit-strict-segment-duration or wrong.

2) Could you share with me the content so that I reproduce? (we have an anonymous dropbox if it can help: )

3) And could you give me your MP4Box command-line to generate the MPD?

Thanks

**Comment by rbouqueau** [comment]
Anonymous dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by blacktrash** [comment]
1) otoh, from the mpd (only 5 audio segments are created):
```
88064 / 44100 * 5 = 9.9845804988662131519
```

2) No prob. Exactly what content do you want me to upload? The MP4 files which are segmented?

3)
```
$MP4BOX -dash 2000 -rap -frag-rap -bs-switching merge  \
-segment-name "${dashdir}/\$RepresentationID\$-\$Number\$" -base-url "${dashdir}/" \
-out night1.mpd \
night1-360p.mp4#audio \
night1-216p-lo.mp4#video night1-216p.mp4#video night1-270p.mp4#video night1-360p.mp4#video \
night1-540p.mp4#video night1-576p.mp4#video night1-720p.mp4#video night1-1080p.mp4#video
```
The mpd is afterwards massaged because of the base url paths bug, but that does not affect this issue.

**Comment by blacktrash** [comment]
What I meant with 'wrong profile' is: `Type MPEG-4 Audio AAC LC`, where in fact it's AAC HE, as indicated by the correct codec id `mp4a.40.5`.

I am aware that AAC is 'messy' because - layman's speak - of its initialization when it comes to duration.
I don't mess with edit lists; what I do to circumvent sync and end of video issues (playlists!) both for HLS and Dash is trimming the original audio minimally at both ends _before_ encoding (and muxing) to MP4. That's why you see almost the same duration for both streams.

**Comment by rbouqueau** [comment]
The info are still inconsistent, so I am interested in the source night1-360p.mp4 file. Thanks.

**Comment by blacktrash** [comment]
Sure, I'll upload later today.
As for LC instead of HE, I'm sort of not surprised because single channels are evaluated, and at least mono HE detection is a bit of a lottery: http://sourceforge.net/p/opencore-amr/mailman/message/31876971/ if you're interested.

**Comment by blacktrash** [comment]
@rbouqueau - night1-360p.mp4 uploaded.

**Comment by rbouqueau** [comment]
> @rbouqueau - night1-360p.mp4 uploaded.

1) How was this file generated? The last sample duration is manually set to 680 / 44100 which is wrong. MediaInfo also reports a -31ms between the declared ISOBMF duration and the media duration.

2) You didn't provide your DASH command-line. If I execute ```MP4Box -dash 2000 -profile live night1-360p.mp4```, I get in my MPD::
```<SegmentTemplate timescale="1000" media="night1-360p_dash$Number$.m4s" startNumber="1" duration="2000" initialization="night1-360p_dashinit.mp4"/>```

=> Segment duration is exactly 2s. Can you confirm that you are using the latest GPAC?

> As for LC instead of HE, I'm sort of not surprised because single channels are evaluated, and at least mono HE detection is a bit of a lottery: http://sourceforge.net/p/opencore-amr/mailman/message/31876971/ if you're interested.

Thank you. The display by MP4Box can certainly be improved - it gives the right technical information whether it is MPEG2 or 4 AAC and then is there are some additions (SBR and PS, which are parts of HE-AAC v1 and v2). 
As you mention, the RFC6381 is correct (mp4a.40.5). So the detection is ok. It is a display improvement. Let me have a look and I'll be back here.

NB: MediaInfo writes 'HE-AAC / LC'.

**Comment by rbouqueau** [comment]
Ok so there seem to have 2 reasons for writing AAC-LC: 1) backward compatibility depending on the (SBR) signalling and 2) that's what is written in the container and conformant with ISO 14496-3:2001 Table 1.15.

The information written should display HE-AACv1 so that people see the name. I'll improve this.

**Comment by rbouqueau** [comment]
Done.

**Comment by blacktrash** [comment]
> > @rbouqueau - night1-360p.mp4 uploaded.
> 
> 1) How was this file generated? The last sample duration is manually set to 680 / 44100 which is wrong. MediaInfo also reports a -31ms between the declared ISOBMF duration and the media duration.

Yes, as I said, the only way to get really reliable sync, startup time, and end of video detection for both HLS segmenting _and_ MPEG-DASH is to trim the audio _before_ encoding. Please see these for all the dirty details:

http://sourceforge.net/p/opencore-amr/mailman/message/32912437/
https://trac.ffmpeg.org/ticket/3859

If I don't do that, in this case end of video detection will fail in generic HLS for certain sources, as well as MPEG-DASH.

> 2) You didn't provide your DASH command-line.

I did: https://github.com/gpac/gpac/issues/360#issuecomment-168482751

> If I execute ```MP4Box -dash 2000 -profile live night1-360p.mp4```, I get in my MPD::
> ```<SegmentTemplate timescale="1000" media="night1-360p_dash$Number$.m4s" startNumber="1" duration="2000" initialization="night1-360p_dashinit.mp4"/>```

There are likely not problems when you do not separate the audio track. As there are none without template. If there was a 6th (audio only?) segment created (likely when I do not trim the audio), I would run exactly in the end of video issues mentioned above.

An overlong audio track may be more correct in theory, but in practice it does not help. Maybe just leave it as is, at least without template I get streams which work reliably.

> => Segment duration is exactly 2s.

Sure. I get the same for the _video_ tracks in http://media.blacktrash.org/fp/test/night1.mpd 

> Can you confirm that you are using the latest GPAC?

```
MP4Box -version
MP4Box - GPAC version 0.5.2-DEV-rev971-g61bef99-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration:
Features: GPAC_64_BITS GPAC_HAS_SSL GPAC_HAS_JPEG GPAC_HAS_PNG
```

Extracted from nightly build.

Unfortunately I can't compile myself anymore for quite some time because of https://github.com/gpac/gpac/issues/353

**Comment by blacktrash** [comment]
@rbouqueau - I'm uploading the other MP4s now, so you can replicate my command line.

In short: If possible I'd like `-url-template` to work as reliably as without segment template - http://stream.flowplayer.org/night1.mpd  - if not possible, I hope that everything continues to work without template (no non-existing files are actually written into the mpd) ;-)

**Comment by rbouqueau** [comment]
> Yes, as I said, the only way to get really reliable sync, startup time, and end of video detection for both HLS segmenting _and_ MPEG-DASH is to trim the audio _before_ encoding

Ok. For my information, what kind of device triggers these issues? It would be interesting to know if we need to fix something or display a warning.

> An overlong audio track may be more correct in theory, but in practice it does not help. Maybe just leave it as is, at least without template I get streams which work reliably.

Is dash.js the only player to behave badly?

MP4Box doesn't extract the last 20ms segments (number 6) - I am going to investigate why when I find  time. But according to the specs, the last segment is not forbidden to be longer. So I expect players to be able to deal with this.

For me MP4Box is conformant and it seems dangerous to make fixes only to please this or that player. Does it make sense?

**Comment by blacktrash** [comment]
* On Monday, January 04, 2016, you wrote:
> > Yes, as I said, the only way to get really reliable sync, startup time, and end of video detection for both HLS segmenting _and_ MPEG-DASH is to trim the audio _before_ encoding
> 
> Ok. For my information, what kind of device triggers these issues?

I can't give feedback on devices. I only can comment on web implementations; and there it boils down to:

- the 'YouTube' player http://dash-mse-test.appspot.com/dash-player.html - haven't been able to make it work with anything created by MP4Box; entirely possible that there's a combination which may work, but I haven't found it, and stopped bothering - also all dash.js samples I tried it in it don't work

- dash.js http://dashif.org/reference/players/javascript/v1.6.0/samples/dash-if-reference-player/index.html - which does what I need - except for the template, which works most of the time but not reliably when the video is in dange of ending on a segment 'border' with aac potentially overlapping

As for segmenters and AAC one has to deal especially with the problem that in MP4 VOD the AAC track starts with a negative PTS, and this causes problems regarding async and required first IDR frame in a stream, and you have to ensure that both audio and video track have the same duration, otherwise end of video is not properly detected. With HLS this can be observed in devices which play HLS natively; typical practical problem case: the replay button does not appear, or playlists do not play through; harder to detect: sync may be minimally off.

- Apple HLS segmenter deals with this (closed source, so we can't say how exactly): both audio and video tracks/programs/streams have exactly same duration after segmenting - note that I'm no advocate of the Apple segmenter because it 'overoptimizes' in other areas, may clip overall duration in strange ways etc.
- ffmpeg HLS segmenter and MP4Box -dash can be taught to deal with it, as mentioned, but trimming the audio at start and end before encoding to MP4; without trimming the chances of this happening are increased

> It would be interesting to know if we need to fix something or display a warning.

Not sure whether that's worth it or possible in a reliable fashion. To me it looks like there is some inherent fundamental problem when turning an MP4 containing AAC audio into a stream, whether it's TS or DASH.

> > An overlong audio track may be more correct in theory, but in practice it does not help. Maybe just leave it as is, at least without template I get streams which work reliably.
> 
> Is dash.js the only player to behave badly?

As I said, it's the only player I can make work with MP4Box -dash - I can't get Osmo to work at all - would be nice for testing, and then be able to tell the dash.js guys: works in the Osmo player; other than that I guess my prophecy that I'll be sent back and forth:
https://github.com/Dash-Industry-Forum/dash.js/issues/950#issuecomment-166621450
will turn out to be true ;-)

> MP4Box doesn't extract the last 20ms segments (number 6) - I am going to investigate why when I find  time. But according to the specs, the last segment is not forbidden to be longer. So I expect players to be able to deal with this.
> 
> For me MP4Box is conformant and it seems dangerous to make fixes only to please this or that player. Does it make sense?

I agree in practical terms in as much as that I'm ok with giving up on the segment template in favour of reliability.

It would be interesting to find out whether the AAC muxing problem can be solved at all.

**Comment by rbouqueau** [comment]
I understand. Would it be ok to forward this thread to the DASH-IF mailing-list? I feel like these interoperability issues are important, but they go beyond what we can address on this forum. Note that you could get some professional help under NDA with www.gpac-licensing.com.

For your Mac OS issues, could you open a separate issue so that we fix it together?

**Comment by blacktrash** [comment]
> I understand. Would it be ok to forward this thread to the DASH-IF mailing-list?

Sure, if you're talking about https://groups.google.com/forum/#!forum/dashjs - I am subscribed, so I can follow there too.

> I feel like these interoperability issues are important, but they go beyond what we can address on this forum. Note that you could get some professional help under NDA with www.gpac-licensing.com.

We may come back to that if we decide to incorporate DASH into the Flowplayer Drive platform https://flowplayer.org/docs/drive.html - thanks.

For the moment we are ok as it looks like reliability is ensured by not using template, so we can give some general advice for how to make the Flowplayer dashjs plugin work https://github.com/flowplayer/flowplayer-mpegdash

> For your Mac OS issues, could you open a separate issue so that we fix it together?

Will do, probably rather for MP4Client (which is also broken) than Osmo.

**Comment by sandersaares** [comment]
Not directly what you are talking about here, I think, but I have previously investigated the topic of differing audio/video stream lengths and discussed it with DASH-IF members and some player vendors. In case it benefits you, I will list my conclusions based on this research:

* Ideal DASH should never have a template reference a segment that does not exist. This is not explicitly defined in DASH or DASH-IF IOP but is the interpretation shared by everyone who has expressed an opinion.
* However, having some fragments return 404 at the end for one or more adaptation sets happens a lot in practice and much content already exists like this, making targeting the ideal scenario impractical.
* Furthermore, lost segments are normal in case of live streaming! If a segment gets lost on the way to the origin server, it should be skipped by good players, instead of breaking playback for all viewers! DASH-IF IOP briefly mentions lost segments, though this is not really expanded upon in depth.

In conclusion, players must deal satisfactorily with adaptation sets that have 404 segments at the end. How exactly they do it has not yet been of interest to me - the problem scenario is when the player treats 404 as a fatal error and shuts down everything (even if the 404 was for some segment that is to be played 60 seconds in the future!).

Dash.js seems to gracefully handle 404 segments at the end of adaptation sets, though I have not checked what exactly its behavior is (I suspect it ends playback at the 404). It is not one of the players on our "problematic players" list, at least.

So far, I have not found a player that can skip over lost segments during live streaming - they all stop when a segment gets lost. The best you can do is app-level retry code, which is decidedly suboptimal. Overall, the quality of DASH players during live streaming is atrocious - I have yet to see a satisfactory implementation. Skipping over lost segments would certainly be one of the expected features.

We are currently considering pre-processing content to force even adaptation sets, to at least help the problematic players out with the on-demand video case.

Note that all of this is about segments - whether the data inside the segments is synchronized in end-time has not been a topic of relevance to me. My expectations there are in-line with what YouTube expects of partner submissions (500 millisecond tolerance).

If mp4box can do something to help out here, it might be desirable. A warning when the inputs for different adaptation sets do not all contain enough data to form all segments (for adaptation sets of equal length) would be a good first step. A command-line option to cut everything to the length of the shortest stream would be another potentially desirable feature.

**Comment by rbouqueau** [comment]
@blacktrash Fix pushed for the average duration. Let me know if that fixes your issue.

> > I understand. Would it be ok to forward this thread to the DASH-IF mailing-list?

> Sure, if you're talking about https://groups.google.com/forum/#!forum/dashjs - I am subscribed, so I can follow there too.

No. I meant the private the DASH-IF lists. But apparently @sandersaares already raised the issue so I won't.

> If mp4box can do something to help out here, it might be desirable.

> A warning when the inputs for different adaptation sets do not all contain enough data to form all segments (for adaptation sets of equal length) would be a good first step.

I understand but the core issue is that the container (MP4) duration is not equal to the media (AAC) duration.

**Comment by sandersaares** [comment]
In the case that I investigated, the difference between container and media duration was not relevant - it was purely a case of the streams being of different length, according to all the different layers of data.

I feel that the two scenarios should be best viewed as different - certainly, in the previous DASH-IF discussion, we did not touch upon the implications of different layers of the data giving different durations. Your idea of raising for discussion the topic described in this item seems to have merit.

**Comment by rbouqueau** [comment]
Ok thanks.

> the implications of different layers of the data giving different durations. 

Long story short this is covered by standards: the highest layer prevails (e.g. DASH prevails on MP4 which prevails on AAC). The issue is that most players operate in pull mode and will require clock adjustments.

> A warning when the inputs for different adaptation sets do not all contain enough data to form all segments (for adaptation sets of equal length) would be a good first step.

I am on it. Just thinking of displaying some data either after the DASHing occured or to probe the inputs (or both).

The issue is that MP4Box has the -dash-live/-dash-ctx options. These options make it complex it to retrieve segments info because they also cause subtle changes at the container level.

Let me know if you have ideas or questions. That's the right time.

**Comment by rbouqueau** [comment]
> Just thinking of displaying some data either after the DASHing occured or to probe the inputs (or both).

Both are non trivial. We currently don't store that much data about the input and output of the DASHing.

**Comment by blacktrash** [comment]
> @blacktrash Fix pushed for the average duration. Let me know if that fixes your issue.

I'm afraid it does not. At least dash.js still looks for a 6th segment. The `SegmentTemplate` is exactly the same.
What I don't really understand is how the calculated segment duration becomes less than 2 seconds - `88064 / 44100 * 5 = 9.9845804988662131519`, which sort of lets one _expect_ a problem with _exactly_ 10s duration already, MP4Box reports exactly 10 seconds, and yet another calculation yields 10.3s, and both of the latter would probably still be longer if I did not trim the audio (certainly causing trouble). At least the video is meticulously split every 2 seconds, IDR frames are strictly every 2 seconds. - One would assume that there would be some kind of problem without segment template, but there isn't.

**Comment by rbouqueau** [comment]
I think you don't use the last version, my MPD looks like this:
```
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.5.2-DEV-rev1125-gd7c3b1a-master  at 2016-01-15T18:55:29.359Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H0M10.000S" maxSegmentDuration="PT0H0M2.012S" profiles="urn:mpeg:dash:profile:isoff-live:2011">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>night1-360p_dash.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H0M10.000S">
  <AdaptationSet segmentAlignment="true" lang="und">
   <Representation id="1" mimeType="audio/mp4" codecs="mp4a.40.5" audioSamplingRate="44100" startWithSAP="1" bandwidth="66352">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <SegmentTemplate timescale="44100" media="night1-360p_dash_track2_$Number$.m4s" startNumber="1" duration="88200" initialization="night1-360p_dash_track2_init.mp4"/>
   </Representation>
  </AdaptationSet></Period>
</MPD>
```

It looks right, right?

PS: command line ```-dash 2000 -profile live night1-360p.mp4#audio```

**Comment by blacktrash** [comment]
* On Friday, January 15, 2016, you wrote:
> I think you don't use the last version,

$ MP4Box -version
MP4Box - GPAC version 0.5.2-DEV-rev1125-gd7c3b1a-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: --prefix=/usr/local --use-openjpeg=no
Features: GPAC_64_BITS GPAC_HAS_SSL GPAC_HAS_JPEG GPAC_HAS_PNG

which means it contains
https://github.com/gpac/gpac/commit/d7c3b1a3f30e341c02f155478dbeca449261a351

> my MPD looks like this:
> ```
> <snip ...>
>     <SegmentTemplate timescale="44100" media="night1-360p_dash_track2_$Number$.m4s" startNumber="1" duration="88200" initialization="night1-360p_dash_track2_init.mp4"/>
> <snip ...>
> ```
> 
> It looks right, right?

Yes, that's what I would expect.

> PS: command line ```-dash 2000 -profile live night1-360p.mp4#audio```

Why `-live`, it's VOD? I can try that, but why should it make a difference? Maybe I have to comit `-rap` and `-frag-rap` (although at least `-rap` makes sense with my IDR frame placing) or start again playing with some options. I must have `-bs-switching merge` though because AVC3 does not fare well in Safari. Did you try in conjunction with video?

**Comment by blacktrash** [comment]
@rbouqueau - with your minimal command line I get the 88200 duration, so there must be a bug somewhere else. Try my original command line at https://github.com/gpac/gpac/issues/360#issuecomment-168482751 and you'll see that duration is 88064 instead of 88200.
I'll experiment some more, but there is certainly an inconsistency.

**Comment by blacktrash** [comment]
Ah! The culprit is `-segment-name`! Although this only seems to have a negative effect in conjunction with `-url-template`.
To take up your example:
```
MP4Box -dash 2000 -profile live -segment-name '$RepresentationID$-$Number$' night1-360p.mp4#audio
```
and you'll get the wrong duration.

Could this be caused by https://github.com/gpac/gpac/issues/246 - some file(s) being overwritten?

Yikes, in combination with #219 it's hard to tweak a path handling which is not default ;-) At least it got us looking down completely the wrong avenue.

**Comment by blacktrash** [comment]
@rbouqueau - just to confirm: https://github.com/gpac/gpac/commit/d7c3b1a3f30e341c02f155478dbeca449261a351 is required to fix this problem, but also `-segment-name` must not be used, at the very least the option is unsafe with certain patterns.

**Comment by blacktrash** [comment]
FYI, here's the working sample without `-segment-name` being used: http://media.blacktrash.org/fp/test/night1-fix.mpd - also works in the DASH-IF sample player.

**Comment by rbouqueau** [comment]
First thank you very much for the detailed analysis.

The fix was not general enough. It should be fixed now.

Have a nice week-end!

**Comment by blacktrash** [comment]
Hm, in theory, yes; in practice:
```
$ MP4Box -version 2>&1 | head -n1
MP4Box - GPAC version 0.5.2-DEV-rev1127-gc5ec91b-master
$ MP4Box -dash 2000 -profile live -segment-name '$RepresentationID$-$Number$' night1-360p.mp4#audio
$ awk '/SegmentTemplate/ { print $5 }' night1-360p_dash.mpd
duration="88064"
```

In theory, there is no difference between theory and practice ;-)

**Comment by rbouqueau** [comment]
Ok. The part of the code would require to be split into many sub-functions. I moved the code before any writing of the 'duration' attribute. I hope that was my last commit on this!

**Comment by blacktrash** [comment]
Looking good! Thanks a lot. - I share your hope; therefore closing.
