### ISSUE TITLE
DashCast source code not compiling

### ISSUE THREAD

**Issue by khalidcawl** [gpac/gpac#363]
I am using Ubuntu 14.04 LTS. I downloaded the latest GPAC source and tried to build. However, the dashcast source is creating error when I execute make. It shows the following error:

make[2]: *** [video_encoder.o] Error 1
make[2]: Leaving directory `/home/khalid/gpac/applications/dashcast'
make[1]: *** [apps] Error 2
make[1]: Leaving directory `/home/khalid/gpac/applications'
make: *** [all] Error 2

How should I fix this to get the latest GPAC that has all apps running fine, most importantly dashcast?

Thank you.

**Comment by rbouqueau** [comment]
Happy new year.

Could you please precise what the error message is?

I don't have time right now, but I remember other people had a similar issue on github on the older sf forums. See https://www.google.fr/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=dashcast+Ubuntu+14.04

**Comment by khalidcawl** [comment]
Hi. I have gone through most of those links on the search result. To make the error message more precise, I have independently ran 'make' for the dash cast application only. Here is the output on the terminal. It has problem with the video_encoder class/object as it seems. 

khalid@khalid:~/gpac/applications/dashcast$ sudo make
[sudo] password for khalid: 
  CC video_encoder.c
video_encoder.c: In function ‘dc_video_encoder_open’:
video_encoder.c:89:42: error: ‘PIX_FMT_YUV420P’ undeclared (first use in this function)
  video_output_file->codec_ctx->pix_fmt = PIX_FMT_YUV420P;
                                          ^
video_encoder.c:89:42: note: each undeclared identifier is reported only once for each function it appears in
video_encoder.c: In function ‘dc_video_encoder_encode’:
video_encoder.c:226:5: warning: ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2957) [-Wdeprecated-declarations]
     video_codec_ctx->coded_frame->pts = video_codec_ctx->coded_frame->pkt_pts = pkt.pts;
     ^
video_encoder.c:226:5: warning: ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2957) [-Wdeprecated-declarations]
video_encoder.c:227:5: warning: ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2957) [-Wdeprecated-declarations]
     video_codec_ctx->coded_frame->pkt_dts = pkt.dts;
     ^
video_encoder.c:228:5: warning: ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2957) [-Wdeprecated-declarations]
     video_codec_ctx->coded_frame->key_frame = (pkt.flags & AV_PKT_FLAG_KEY) ? 1 : 0;
     ^
make: *** [video_encoder.o] Error 1
khalid@khalid:~/gpac/applications/dashcast$

**Comment by rbouqueau** [comment]
Did you have the chance to have a look at #285 ?

**Comment by khalidcawl** [comment]
Hi rbouqueau,
I have tried that issue and other similar solutions. None of them worked for me. The compilation errors after I execute make are still there.

Thanks for your help! Appreciate it.

**Comment by rbouqueau** [comment]
@jeanlf it seems to be an FFmpeg version misdetection. We need to clear that point.

**Comment by jeanlf** [comment]
hmm I cannot reproduce this on 14.04LTS (tested with libavcodec 56.20.100). Could you try with latest git from both GPAC and ffmpeg ?

**Comment by khalidcawl** [comment]
Yeah I actually fetched the latest of both libraries and still could not make it work. Anyways, I have abandoned using GPAC for my project at all. Thanks for the help. I appreciate it.
