### ISSUE TITLE
The high level API should not expose structure members

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#365]
For example, https://github.com/rbouqueau/gpac_opengl_shared_context/blob/4cae41f49f77625aaebe48b6efdb2a38935c86de/player.c#L50 may look cryptic for most API users. Instead of writing an extensive documentation, it would be better to lock access to this variables.

**Comment by jeanlf** [comment]
not sure what you mean here, this structure is the interface between the GF_Terminal and the outside world, it seems logical to be fully exposed to the outside world
