### ISSUE TITLE
AVC recovery point SEI and roll group / roll_distance=0

### ISSUE THREAD

**Issue by sneaker2** [gpac/gpac#366]
When encoding "OpenGOP" using x264 we will get one IDR at the beginning and a number of I frames marked with a recovery point SEI message. When muxing using mp4box these recovery point samples will not be put into the "rap " group but instead be marked via the "roll" group with a "roll_distance" of "0".
1.) Why "roll" instead of "rap "?
2.) Why "roll_distance" of "0"? According to ISO/IEC 14496-12:2015 chapter 10.1.1.3 "The value zero must not be used".

```
[sgpd: Sample Group Description Box]
    position = 18587
    size = 26
    version = 1
    flags = 0x000000
    grouping_type = roll
    default_length = 2 (constant)
    entry_count = 1
    roll_distance[0] = 0
[sbgp: Sample to Group Box]
    position = 18613
    size = 68
    version = 0
    flags = 0x000000
    grouping_type = roll
    entry_count = 6
    entry[0]
        sample_count = 477
        group_description_index = 0 (not in this grouping type)
    entry[1]
        sample_count = 1
        group_description_index = 1
    entry[2]
        sample_count = 479
        group_description_index = 0 (not in this grouping type)
    entry[3]
        sample_count = 1
        group_description_index = 1
    entry[4]
        sample_count = 479
        group_description_index = 0 (not in this grouping type)
    entry[5]
        sample_count = 1
        group_description_index = 1
```
Version used:
MP4Box - GPAC version 0.5.2-DEV-rev1114-g1108040-master

[opengop.txt](https://github.com/gpac/gpac/files/78821/opengop.txt)
Sample download:
https://www.sendspace.com/file/okhvkn

**Comment by nguyen-viet-thanh-trung** [comment]
Thank you for your report. It should be fixed now.
