### ISSUE TITLE
DashCast transcode a live/non-live stream in multiple qualities (eg. bitrate and resolution)???

### ISSUE THREAD

**Issue by JamesXu20150314** [gpac/gpac#367]
Hello,

I want to transcode a live/non-live stream in multiple qualities (eg. bitrate and resolution) by DashCast in windows 64bit.

The command is:

D:\wamp\www>DashCast -vf dshow  -vres 1280x720 -vfr 24 -v video="screen-capture-recorder" -live -npt
s -time-shift -1 -seg-dur 2000

The config file is:

[v1] 
type=video 
width=1280 
height=720 
bitrate=800000 
[v2]
type=video 
width=640 
height=360 
bitrate=400000 
[a1]
type=audio
bitrate=128000
[a2]
type=audio
bitrate=256000

But when I run this command, I will recieved this error:

[swscaler @ 00000000002cd320] [swscaler @ 00000000002b7fe0] bad src image pointers
bad src image pointers
Video scaler: error while resizing picture.
Video scaler: error while resizing picture.
[swscaler @ 00000000002cd320] [swscaler @ 00000000002b7fe0] bad src image pointers
bad src image pointers
Video scaler: error while resizing picture.
Video scaler: error while resizing picture.
[swscaler @ 00000000002cd320] [swscaler @ 00000000002b7fe0] bad src image pointers
bad src image pointers
Video scaler: error while resizing picture.
Video scaler: error while resizing picture.
[swscaler @ 00000000002cd320] [swscaler @ 00000000002b7fe0] bad src image pointers
bad src image pointers
Video scaler: error while resizing picture.
...

What's the problem with this?

Who can tell me a correct way to transcode a live/non-live stream in multiple qualities (eg. bitrate and resolution) by DashCast in windows 64bit.

Thanks,

James.

**Comment by jeanlf** [comment]
Dashcast is deprecated, use GPAC 0.9.0 DEV
