### ISSUE TITLE
MP4Client DASH metrics

### ISSUE THREAD

**Issue by MarcMacia** [gpac/gpac#368]
Is there a way to get a log for MP4Client DASH metrics/stats? I want a similar file that results from "MP4Client -rti" but with the estimated bandwidth, the representation bitrate, the buffer occupancy (in bytes and in seconds), the representation level, etc. along with the cpu and memory. I want to make by myself a graphic like the "stats window" in the Osmo4 GUI using this information.

Thanks in advance.

**Comment by cyriac83** [comment]
Same here. Any help is appreciated!

**Comment by lala9** [comment]
I'm in the same situation. Any help would be really useful.

**Comment by jeanlf** [comment]
you can use the log system for that, `dash@info`

**Comment by paperflight** [comment]
Is there a method to get the bandwidth, buffer, and fps statistics shown in gpac player statistic option?
