### ISSUE TITLE
MP4Client does not work on OS X

### ISSUE THREAD

**Issue by blacktrash** [gpac/gpac#369]
```
$ MP4Client http://stream.flowplayer.org/drive.mpd
Using config file in /Users/chris/.gpac directory
System info: 8192 MB RAM - 8 cores
Modules Found : 30
Loading GPAC Terminal
Terminal Loaded in 112 ms
Opening URL http://stream.flowplayer.org/drive.mpd
Service Connected
[Codec] ODM1 ES2: Cannot find decoder for stream type MPEG-4 Audio SBR
 Stream Setup Failure: Media Codec not found
[Compositor] GLES Vertex shader not found, disabling shaders
[Compositor] GLES Fragment shader not found, disabling shaders
[Compositor] GLES Vertex shader not found, disabling shaders
[Compositor] GLES Fragment shader not found, disabling shaders
[Compositor] GLES Vertex shader not found, disabling shaders
[Compositor] GLES Fragment shader not found, disabling shaders
GL Error 1280 file compositor/visual_manager_3d_gl.c line 2771
GL Error 1282 file compositor/visual_manager_3d_gl.c line 2771
GL Error 1282 file compositor/visual_manager_3d_gl.c line 2771
# [...]
GL Error 1282 file compositor/visual_manager_3d_gl.c line 2771
GL Error 1282 file compositor/visual_manager_3d_gl.c line 2771
GL Error 1282 file compositor/visual_manager_3d_gl.c line 2771
q
[socket] cannot select, BAD descriptor
CoreAnimation: warning, deleted thread with uncommitted CATransaction; set CA_DEBUG_TRANSACTIONS=1 in environment to log backtraces.
Service Disconnected
Deleting terminal... done (in 83 ms) - ran for 5195 ms
GPAC cleanup ...
$ MP4Box -version
MP4Box - GPAC version 0.5.2-DEV-rev1115-gedd2b7c-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: --prefix=/usr/local --use-openjpeg=no
Features: GPAC_64_BITS GPAC_HAS_SSL GPAC_HAS_JPEG GPAC_HAS_PNG
```

Any ideas?

See: https://github.com/gpac/gpac/issues/360#issuecomment-170244464

**Comment by jeanlf** [comment]
hmm it looks like your GLSL shaders are not found. have you tried removing your config file ($HOME/.gpac/GPAC.cfg) and relaunch the player with no argument ?

for thesocket error, I guess this is related to the access rights to the MPD, I have the same error using a web browser

**Comment by blacktrash** [comment]
Aha, that's better.
- without arguments keyboard interaction does not work
- seems to have trouble with audio: `[Codec] ODM2 ES2: Cannot find decoder for stream type MPEG-4 Audio AAC LC`

But certainly better.

**Comment by jeanlf** [comment]
you mean keyboard interaction with the prompt, or with the UI ?
Did the ./configure detect the faad2 decoder (you can post config.mak if needed) ?

**Comment by blacktrash** [comment]
- keyboard with prompt in terminal, but only when not playing a stream
- faad2: ah, I haven't faad2 installed - but it seems to use ffmpeg or libavcodec to decode video? Shouldn't the native ffmpeg decoder be able to do the job?

**Comment by jeanlf** [comment]
1) hmm strange I can use the prompt here (for example 'z' gives 'not seekable'

2) not for the time being, we need to patch our code to use ffmpeg builtin aac decoder

**Comment by blacktrash** [comment]
@jeanlf - thanks for the update, I can live with that state.
