### ISSUE TITLE
DashCast  $Time$ token

### ISSUE THREAD

**Issue by cjpdev** [gpac/gpac#37]
Hi 

Does DashCast support the $Time$ token, for file segments names and for the SegmentTemplate.

MP4Box has a -segment-name option, but can find anything like this for DashCast.

Thanks

**Comment by jeanlf** [comment]
this is not yet supported, we'll see what we can do

**Comment by cjpdev** [comment]
Thanks

**Comment by jeanlf** [comment]
This feature is now available in 0.9.0 dev branch (through gpac, dashcast is now deprecated)
