### ISSUE TITLE
Osmozilla/Osmo4 Browser Plugin Download?

### ISSUE THREAD

**Issue by jenjet333** [gpac/gpac#371]
Hi. This is most likely a stupid question, but where can I install the plugin that allows Osmo4 to be integrated into the browser? I've been currently following the instructions found here: https://gpac.wp.mines-telecom.fr/player/browser-integration/

I've installed the latest dev build for GPAC on Windows, but when I navigate to my webpage on Mozilla Firefox, I get an error that says "A plugin is needed to display this content"

**Comment by rbouqueau** [comment]
I am not sure it still works, please read as-is https://github.com/gpac/node-gpac-dash/issues/1#issuecomment-171210706

A patch would be highly welcome on this :)

**Comment by jeanlf** [comment]
this plugin is deprecated
