### ISSUE TITLE
'Video scaler: error while resizing picture.'(DashCast Problem)

### ISSUE THREAD

**Issue by LindaXiaomi** [gpac/gpac#372]
Hello,

I use DashCast on ubuntu 14.04 for transcoding a live stream in multiple qualities.
However, I encounter such problem "Video scaler: error while resizing picture."

Here is my command:
DashCast -vf video4linux2 -vfr 24 -v4l2f yuyv422 -v /dev/video0 -conf dashcast.conf -live

Here is my dashcast.conf:
[v1]
type=video
bitrate=800000
width=1280
height=720
crop_x=0
low_delay=yes
crop_y=0
codec=libx264

[v2]
type=video
bitrate=400000
width=640
height=360
crop_x=0
low_delay=yes
crop_y=0
codec=libx264

Who can give me some guidelines?
Thanks.

Linda.

**Comment by LindaXiaomi** [comment]
My GPAC version is GPAC 0.5.1-DEV rev5619

**Comment by jeanlf** [comment]
Dashcast is deprecated, use GPAC 0.9.0
