### ISSUE TITLE
Error open dashcast generated m4s while using mp4client

### ISSUE THREAD

**Issue by reallxl** [gpac/gpac#374]
hi all,

i am trying to use mp4box for live streaming dash content under window 7 64bit platform,
i used a 46 second long pre-recorded V/A mp4 as my source file,
first i used mp4box to divide it into 2 mp4 containing only 1 track each,
then i used the video only file for the test,

my command is:
mp4box -dash-live 6000 -mpd-refresh 12 -out test.mpd src.mp4

then i use mp4client:
mp4client test.mpd

i got log messge:

> Opening URL test.mpd
> Service Connected
> [GLSL] Failed to compile vertex shader: ERROR: 0:17: '' : syntax error: incorrect preprocessor directive
> 
> [Compositor] Failed to compile vertex shader
> [SyncLayer] ES1 (test.mpd): Something really wrong, decoding buffer exceeded (1271327 ms vs 3000 max) - trashing buffers

i could see player GUI popped up, but nothing actually displayed...
any help or advise would be appreciated!

**Comment by reallxl** [comment]
some information update,

i tested with the following file
http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-85.mp4

using command:
mp4box -dash-live 4000 -mpd-refresh 12 -out test.mpd car-20120827-85.mp4
mp4client test.mpd

the result is good and i could see the movie playing

but when i turned to used mp4box generated dashified fmp4 file i mentioned in the main post
i just got a black window popped up and couldn't see anything displayed...
i ensured that every .m4s file starts with an IDR frame explicitly

need some help:(

**Comment by rbouqueau** [comment]
There's been changes on the GL stack recently. What's you GPAC version? (MP4Box -version)

**Comment by reallxl** [comment]
hi @rbouqueau ,

MP4Box - GPAC version 0.5.2-DEV-rev1110-g9f2bf6e-master

**Comment by reallxl** [comment]
i also have another question which might be quite unrelated to the topic,
i've also tried dashcast using the following command:
dashcast -v car-20120827-85.mp4 -live-media -mpd test.mpd
and then
mp4client test.mpd

but i always got the result like:
[IsoMedia] Error opening new segment v1_6_gpac.m4s at UTC 1452842128061: Requested URL is not valid or cannot be found
[IsoMedia] Error opening new segment v1_7_gpac.m4s at UTC 1452842128062: Requested URL is not valid or cannot be found
[IsoMedia] Error opening new segment v1_8_gpac.m4s at UTC 1452842128065: Requested URL is not valid or cannot be found
...

does anybody has any idea about this?

**Comment by reallxl** [comment]
I noticed that I should use the original (non-fragmented) mp4 files instead of the mp4box-pre-fragmented ones... in this way, I can see the movie playing in MP4Client now

but still, when I try to use dashcast instead, I still get error as described above

**Comment by nguyen-viet-thanh-trung** [comment]
Maybe relate to #379

**Comment by jeanlf** [comment]
Dashcast is deprecated, use GPAC 0.9.0
