### ISSUE TITLE
Crash with mp42ts due to heap corruption

### ISSUE THREAD

**Issue by mmilitzer** [gpac/gpac#375]
Hi,

I've been experiencing crashes using the mp42ts tool. Some debugging shows that the write in l. 1406 of src/isomedia/stbl_write.c can corrupt the heap:

stbl->SampleSize->sizes[stbl->SampleSize->sampleCount] = size;

The problem is that there are scenarios in which the stbl->SampleSize->sizes buffer is allocated to just stbl->SampleSize->sampleCount elements by the preceding gf_realloc() in l. 1396. E.g. in my case I had stbl->SampleSize->sampleCount=100 while stbl->SampleSize->alloc_size was still 0. This causes the ALLOC_INC() macro to set stbl->SampleSize->alloc_size also to 100 and then to alloc just 100 elements for the buffer. In result, l.1406 then writes behind the end of the buffer.

I've inlined a tiny patch below which fixed the issue for me. Obviously, there are many other ways to o how to fix it. Whichever way you do it, the stbl->SampleSize->sizes buffer just must be at least sized to stbl->SampleSize->sampleCount+1 elements after the realloc no matter what - and that's currently not the case...

Proposed patch:
```
diff --git a/src/isomedia/stbl_write.c b/src/isomedia/stbl_write.c
index 7eaf3e2..c0ff3de 100644
--- a/src/isomedia/stbl_write.c
+++ b/src/isomedia/stbl_write.c
@@ -1390,7 +1390,7 @@ void stbl_AppendSize(GF_SampleTableBox *stbl, u32 size)
        if (!stbl->SampleSize->sizes || (stbl->SampleSize->sampleCount==stbl->SampleSize->alloc_size)) {
                Bool init_table = (stbl->SampleSize->sizes==NULL) ? 1 : 0;
                ALLOC_INC(stbl->SampleSize->alloc_size);
-               if (stbl->SampleSize->sampleCount>stbl->SampleSize->alloc_size)
+               if (stbl->SampleSize->sampleCount>=stbl->SampleSize->alloc_size)
                        stbl->SampleSize->alloc_size = stbl->SampleSize->sampleCount+1;
 
                stbl->SampleSize->sizes = (u32 *)gf_realloc(stbl->SampleSize->sizes, sizeof(u32)*stbl->SampleSize->alloc_size);
```

**Comment by nguyen-viet-thanh-trung** [comment]
Fixed now ! Thank you for your report
