### ISSUE TITLE
MP4Box error when trying to dump subtitle track

### ISSUE THREAD

**Issue by BraveThrasher** [gpac/gpac#376]
When I try to dump a text track from a mp4 file recorded by my dashcam (it stores gps-data and g-sensor data in a text track) with MP4Box version 0.5.2-DEV-rev1127, it fails. 

The executed command:
> MP4Box.exe -v -srt 3 "d:\DashCam\REC_2016_01_14_06_50_13_F.MP4"

The verbose output is as follows:
> [iso file] Current top box start before parsing 0 
> [iso file] Read Box type ftyp size 32 start 0 
> [iso file] Current top box start before parsing 32 
> [iso file] Read Box type moov size 34914 start 32 
> [iso file] Read Box type mvhd size 108 start 40 
> [iso file] Read Box type udta size 384 start 148
> [iso file] Read Box type AMBA size 128 start 156
> [iso file] Read Box type free size 248 start 284
> [iso file] Read Box type trak size 17257 start 532
> [iso file] Read Box type tkhd size 92 start 540
> [iso file] Read Box type edts size 36 start 632
> [iso file] Read Box type elst size 28 start 640
> [iso file] Read Box type mdia size 17121 start 668
> [iso file] Read Box type mdhd size 32 start 676
> [iso file] Read Box type hdlr size 46 start 708
> [iso file] Read Box type minf size 17035 start 754
> [iso file] Read Box type vmhd size 20 start 762
> [iso file] Read Box type dinf size 36 start 782
> [iso file] Read Box type dref size 28 start 790
> [iso file] Read Box type url  size 12 start 806
> [iso file] Read Box type stbl size 16971 start 818
> [iso file] Read Box type stsd size 203 start 826
> [iso file] Read Box type avc1 size 187 start 842
> [iso file] Read Box type colr size 18 start 928
> ICC colour profile not supported[iso file] Read Box "colr" failed (Feature Not Supported)
> [iso file] Read Box "avc1" failed (Feature Not Supported)
> [iso file] Read Box "stsd" failed (Feature Not Supported)
> [iso file] Read Box "stbl" failed (Feature Not Supported)
> [iso file] Read Box "minf" failed (Feature Not Supported)
> [iso file] Read Box "mdia" failed (Feature Not Supported)
> [iso file] Read Box "trak" failed (Feature Not Supported)
> [iso file] Read Box "moov" failed (Feature Not Supported)
> Error opening file REC_2016_01_14_06_50_13_F.MP4: Feature Not Supported 

Using the GUI tool YAMB to dump the track it generates a correct srt file. YAMB uses MP4Box version 0.4.6-DEV with exactly the same command as above.

Am I missing something obviuos? Or is this a bug?

**Comment by rbouqueau** [comment]
Would it be possible to share a sample file? We have an anonymous dropbox if it can help: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by BraveThrasher** [comment]
I have uploaded a sample file (REC_2016_01_14_06_50_13_F.MP4) to the anonymous dropbox.

**Comment by nguyen-viet-thanh-trung** [comment]
Error "Feature Not Supported" should be fixed now, but it seems that your sample is not compatible with Quicktime file format: in your 'text' box, your text name is not a Pascal string, it doesn't begin with its size. Could you please verify it ?

**Comment by BraveThrasher** [comment]
The file has been created by my dashcam (Thinkware F750). I don't know what and how to verify.

**Comment by rbouqueau** [comment]
It could be related to an old bug I processed: https://sourceforge.net/p/gpac/bugs/183/

@BraveThrasher Does it work well with other tools?

And can you tell me which version of MP4Box your YAMP use? (call 'MP4Box -version' to know)

Thanks

**Comment by BraveThrasher** [comment]
The version of MP4Box that comes with YAMB is version 0.4.6-DEV (build 1 - Jun 29 2009) - compiled by Kurtnoise.
Not sure if it is a coincidence but it appears to be compiled by the creator of the bug you mentioned.

**Comment by rbouqueau** [comment]
We now support these strings. It should be available soon from our buildbot. Please re-open if you still have issues!

**Comment by cconcolato** [comment]
Side remark and question: 
Exporting the data from the text track shows binary data, not text. The track probably should not be a text track but rather a metadata track. 
Do you have a documentation of this binary data?

**Comment by cconcolato** [comment]
Partially answering myself :)
The data format seems to be: 
- size on 1 byte, and then text content such as: gsensori,4,512,002,073,097 or 
- 0 byte followed by text such as JGNRMC,055014.00,A,5108.73924,N,00524.21937,E,65.073,33.99,140116,,,A*7B followed by 0x0d, 0x0a, 0x0a.

**Comment by rbouqueau** [comment]
Interesting analysis. It seems that my patch doesn't cover this all:

> size on 1 byte, and then text content such as: gsensori,4,512,002,073,097

Pascal string: code is ok.

> 0 byte followed by text such as JGNRMC,055014.00,A,5108.73924,N,00524.21937,E,65.073,33.99,140116,,,A*7B followed by 0x0d, 0x0a, 0x0a.

Code not ok: if the [size is not ok](https://github.com/gpac/gpac/commit/c4636e5ec2095061a6e5e2047c6f5f1fd304ca27#diff-7bdc1d8d1a57a47cf5ba02b5e7b940d7R464) then I look for letters only until the end of the box. I add a NULL ending char in the end.

Should we fix it?

**Comment by BraveThrasher** [comment]
The gsensori stuff is data from my dashcam's g-sensors, logged every 100 ms I believe.
The $GNRMC stuff is GPS data, see http://www.gpsinformation.org/dale/nmea.htm#RMC , logged every second.

I created a console app that uses MP4Box to dump it as an srt. From that srt I take the GNRMC lines to create a gpx-file I can use in the VIRB Edit application from Garmin.

**Comment by rbouqueau** [comment]
@BraveThrasher Are you happy with our current implementation or could we improve it?

**Comment by BraveThrasher** [comment]
As it does what I expect I'm happy with the current implementation. 
Thanks!

**Comment by abhinavkssk** [comment]
Sorry for reviving an old issue, but @cconcolato how did you manage to decode the binary data to the below data format?

>Partially answering myself :)
>The data format seems to be:
>
>    size on 1 byte, and then text content such as: gsensori,4,512,002,073,097 or
>    0 byte followed by text such as >JGNRMC,055014.00,A,5108.73924,N,00524.21937,E,65.073,33.99,140116,,,A*7B followed by 0x0d, 0x0a, 0x0a.

I'm using MP4Box to dump the same raw file, but am unable to recover this information from inspecting the binary file 

`
