### ISSUE TITLE
[HEVC] [MP4Box] Supported raw formats don't mention HEVC.

### ISSUE THREAD

**Issue by vladimir-kazakov** [gpac/gpac#38]
Hi!

I noticed that MP4Box (GPAC rev 5612, 64-bit, Windows) doesn't show that it can HEVC. So, when doing `CMD> mp4box -h format`, the list doesn't contain anything about HEVC.

I faced with this problem when I was trying to work with a .h265 file. MP4Box was reporting me that the file is corrupted (#39). It was surprising to me, since on the GPAC's web-site I saw that HEVC is supported. So, when I took a look at the supported formats, I didn't find anything related to HEVC. Although by looking at other supported formats (their extensions), I changed the extension of my file to .265, and the file was processed without any problems.

So, it would be nice if `CMD> mp4box -h format` would show that HEVC is supported, and which its extensions are known.

And one more thing related to this issue: the section header for supported raw formats and header has too many "p"-s in the word "supported".

**Comment by jeanlf** [comment]
thanks for the report, should now be fixed in rev 5613
