### ISSUE TITLE
When changing framerate of a video, how do you change audio track's rate as well?

### ISSUE THREAD

**Issue by nick-s-b** [gpac/gpac#382]
Hi all,

I have a poorly encoded video of a webcast (I presume it came from a WebEx screencast) and the main issue is that the framerate of the mp4 file is double than it should be. If I play it with VLC and slow down the playback speed to 0.5x, everything's normal and I can understand the audio. If I play it at 1x, I can't understand anything and everything's too fast.

Framerate reported by MediaInfo and ffprobe is 10fps. 

My first stab at this problem was to use mp4box to change the framerate to 5fps. I actually succeeded at "slowing" down the video but I failed at slowing down the audio. Here's what I tried:

    $ mp4box -add source.mp4\#video -raw 1 -new video

this created "video_track1.cmp" file.

    $ mp4box -add source.mp4\#audio -raw 2 -new audio

this created "audio_track2.aac" file.

I then tried combining them with:

    $ mp4box -add video_track1.cmp:fps=5 -add audio_track2.aac:fps=5 -new output.mp4

This actually partially worked and produced a output.mp4 that had video portion correct and it played at the right speed but the audio was still playing too fast. Duration of the audio track in output.mp4 was exactly 1/2 of the duration of the video track. So the `:fps=5` part did not affect the audio track at all.

How do I fix the audio track? I don't mind re-encoding it with ffmpeg if that's the only option. I actually did try to slow down the audio track by re-encoding with ffmpeg but it sounded horrible and audio had an echo. Slowdown with VLC sounded perfect however.

    $ ffmpeg -i out.m4a -filter:a "atempo=0.5" -vn outputaudio.aac

What am I doing wrong?

**Comment by rbouqueau** [comment]
As you may know, MP4Box doesn't re-encode your content.

There is no option to rescale the audio track. Note also that the ':fps=5' you used is ignored at import (i.e. when you submit raw data to MP4Box) because MP4Box re-detect the proper value.

But there is an option to rescale the timing: ':rescale=' when adding. The initial timescale is found using 'MP4Box -info source.mp4' (there is a general timescale (to ignore), then one per track).

**Comment by nick-s-b** [comment]
@rbouqueau Thank you for pointing me at `:rescale`! I saw it when looking at the "import" section of the mp4box help page but didn't investigate it further.

My source video's metadata looks like this:

> $ mp4box -info source.mp4
> * Movie Info *
> 	Timescale 1000 - Duration 00:33:53.634
> 	2 track(s)
> 	Fragmented File: no
> 	File Brand isom - version 512
> 	Created: UNKNOWN DATE	Modified: UNKNOWN DATE
> File has no MPEG4 IOD/OD
> 
> iTunes Info:
> 	Encoder Software: Lavf56.19.100
> 
> Track # 1 Info - TrackID 1 - TimeScale 11988 - Media Duration 00:33:53.633
> Track has 2 edit lists: track duration is 00:33:53.734
> Media Info: Language "Undetermined" - Type "vide:mp4v" - 20337 samples
> Visual Track layout: x=0 y=0 width=640 height=480
> MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x20
> MPEG-4 Visual Size 640 x 480 - Simple Profile @ Level 1
> Pixel Aspect Ratio 1:1 - Indicated track size 640 x 480
> Self-synchronized
> 
> Track # 2 Info - TrackID 2 - TimeScale 48000 - Media Duration 00:33:53.538
> Track has 1 edit lists: track duration is 00:33:53.496
> Media Info: Language "Undetermined" - Type "soun:mp4a" - 95323 samples
> MPEG-4 Config: Audio Stream - ObjectTypeIndication 0x40
> MPEG-4 Audio AAC LC - 3 Channel(s) - SampleRate 48000
> Synchronized on stream 1
> Alternate Group ID 1

if I run mp4box with `:fps=5` for the video part, the TimeScale of the video part looks like this:

> Track # 1 Info - TrackID 1 - TimeScale 5000 - Media Duration 01:07:47.400
> Media Info: Language "Undetermined" - Type "vide:mp4v" - 20337 samples
> Visual Track layout: x=0 y=0 width=640 height=480
> MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x20
> MPEG-4 Visual Size 640 x 480 - Simple Profile @ Level 1
> Pixel Aspect Ratio 1:1 - Indicated track size 640 x 480
> Self-synchronized

Which is great. However, audio track is still the same and sounds too fast and the duration is still `Media Duration 00:33:53.538` which is 1/2 of what it should be.

I've tried the following commands with no success:

    $ mp4box -add video_track1.cmp:fps=5 -add audio_track2.aac:timescale=5000 -new out.mp4

and

    $ mp4box -add video_track1.cmp:fps=5 -add audio_track2.aac:rescale=11988 -new out.mp4

With no success. I'm not exactly sure what I should use for `timescale` and/or `rescale` options. Any ideas? I have no idea how to change "Media Duration" of audio part. I succeeded with video track but audio still eludes me.

Thanks!

**Comment by rbouqueau** [comment]
'timescale' just changes the parameter while 'rescale' hard-set the value (which should change the audio track duration at the container level)

Would you mind sharing the content? https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by rbouqueau** [comment]
Did you solve your issue?

**Comment by jeanlf** [comment]
You cannot reimport the file so that audio speed is lower, you have to re-encode it (MP4Box can't do this for you)
