### ISSUE TITLE
gpac's sourceforge page doesn't have a redirection link to GitHub

### ISSUE THREAD

**Issue by juzzlin** [gpac/gpac#383]
It's possible to set a notification in the sourceforge page indicating that the project has moved to GitHub. Example here: http://sourceforge.net/projects/dustrac/

**Comment by rbouqueau** [comment]
Thanks, that's a good idea. Let me have a look

**Comment by rbouqueau** [comment]
I was able to add the link at several places, but not to add the blue banner. I couldn't find anymore help from sourceforge or on google. I'm probably missing something simple. Could anyone advise?

**Comment by juzzlin** [comment]
It seems that in the Project Admin page you can set the project status to "Moved" and then you can enter the new URL. In my project this is below the icon setting and it reads:
Project Status: Moved to: https://github.com/juzzlin/DustRacing2D

**Comment by rbouqueau** [comment]
I finally found it. It is in admin->Metadata, then on the top of the page you have 2 implicit columns. Under the project logo, click on the edit next to 'active'.

Thank you!
