### ISSUE TITLE
PSSH data

### ISSUE THREAD

**Issue by andrewgayter** [gpac/gpac#386]
ffmpeg git-cc83177
Dash.js v1.6
GPAC MP4Box 0.5.2-DEV-rev1115
Windows 8.1
Chrome v49.0.2623.13
Widevine Modular

I've created test video and test audio. I can confirm that the video plays correctly in dash.js if dashed ondemand with MP4Box. If I add Widevine encryption to both the audio and video and re-dash using MP4Box the content does not play. It fails to identify the required DRM key system  in parsePSSHList. However, if I add ContentProtection elements containing the DRM system ID and PSSH data into both adaptionsets in the MPD the DRM system is correctly identified as com.widevine.alpha and a call made to the license server.

When examining demo mpd files from Cablelabs, BitDash I notice that the PSSH data within their MPD files contains elements according to the Widevine CENC header https://html5.cablelabs.com/mse-eme/doc/creation.html#encryption, but the example PSSH found here https://github.com/cablelabs/mse-eme/tree/master/create/encrypt/widevine/cryptgen only contains key Id, content Id and track type.

I've attempted to use PSSH data from Cablelabs/BitDash (PSSH containing the system id) in my own MP4Box encryptions without additional contentprotection elements in the MPD, but this fails in the same way as PSSH boxes that do not contain the system id.

Failure is that the content does not play. There are no errors in the console and no trace that a DRM key system has been selected (as mentioned the parsePSSHList dash.js function fails)

The only way I can progress is by putting contentprotection elements into the adaptionsets that contain the system id and PSSH data.

It appears that MP4Box isn't adding the correct DRM info to the content headers when using Widevine PSSH boxes. However, it appears to correctly assign PlayReady PSSH boxes.

Is this a known issue, with the workaround being the one I've already found?

**Comment by rbouqueau** [comment]
Hi, thank you for the precise report. Did you try to report to the CableLabs people? It seems like they should handle the DRM specificities.

**Comment by rbouqueau** [comment]
Not a GPAC issue and no news for 6 months. Reopen if you have news.
