### ISSUE TITLE
Have a GPAC Vagrant image

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#387]
First I'd like to make tests so that people can take and run a GPAC player from wherever they are (no download available, practical sessions).

**Comment by rbouqueau** [comment]
I made a first test: https://github.com/rbouqueau/gpac_vagrant

Notes:
- the VM for dev is huge: over 700MB with no GUI!
- maybe deploy on a small X env with only the installed GPAC (static?)

**Comment by bearcave9** [comment]
Hi, I looked into your first test and the tutorial enlisted there. I'd like further work on this. Could you please assign me on this and provide any other details that you think might be helpful for me.

**Comment by rbouqueau** [comment]
I cannot assign to you (Github...). The first step would be to reproduce my steps. We'd like people to be able to download a VM or container to make easy GUI tests (e.g. the GPAC/MP4Client player).

Let us know if you have any question :)

**Comment by jeanlf** [comment]
can we close this ?

**Comment by jeanlf** [comment]
I suggest we close and if you want to, add your vagrant repo to the gpac organization repos on github
