### ISSUE TITLE
DashCast build instructions refer to the out-of-date svn repo

### ISSUE THREAD

**Issue by joeyparrish** [gpac/gpac#388]
The build instructions at https://gpac.wp.mines-telecom.fr/dashcast/ refer to the svn repo, which seems to be one year out-of-date.  Please update the instructions from:

`svn co svn://svn.code.sf.net/p/gpac/code/trunk/gpac gpac`

To:

`git clone https://github.com/gpac/gpac.git`

**Comment by rbouqueau** [comment]
Done. Thanks for reporting!
