### ISSUE TITLE
[DASH] Set fourcc

### ISSUE THREAD

**Issue by timdp** [gpac/gpac#389]
If I run a DASH segment I grabbed from YouTube through `MP4Box -info`, I get

```
File Brand dash - version 0
```

Checking that same file with `ffprobe`, I see:

```
major_brand     : dash
minor_version   : 0
compatible_brands: iso6avc1mp41
```

With DASH segments produced using `MP4Box`, the former gives me:

```
File Brand iso5 - version 1
```

and the latter

```
major_brand     : iso5
minor_version   : 1
compatible_brands: avc1iso5dsmsmsixdash
```

My files seem to be playing fine, but I was just wondering if there's an elegant way to override the fourcc when using `MP4Box -dash`, and if it would make sense to replace `iso5` with `dash`.

[The docs](https://gpac.wp.mines-telecom.fr/mp4box/mp4box-documentation/) say MP4Box's `-add` lets you append `:stype=4CC`, but in order to use that, it looks like I'd have to transmux the files that `MP4Box -dash` produces in a postprocessing step, correct?

**Comment by rhargreaves** [comment]
I'd like to know too. FWIW I tried using `-brand M4A` to set the brand too as AtomicParsley does not recognise `iso5` files but to no avail.

**Comment by jeanlf** [comment]
The styp option overrides the codec 4cc in the file, not the styp brand (the option was there before the introduction of styp box, we might want to change the name). For the current time there is no wahy to tell MP4Box to change stype brands in the DASH segmenter, but that's a nice feature request, we'll try to add that soon.

**Comment by jeanlf** [comment]
this has been integrated in GPAC 0.9.0 DEV
