### ISSUE TITLE
[HEVC] [MP4Box] Wrong error while importing raw HEVC (.h265) into .mp4.

### ISSUE THREAD

**Issue by vladimir-kazakov** [gpac/gpac#39]
Hi!

I noticed that MP4Box (GPAC rev 5612, 64-bit, Windows), when importing raw .h265 into .mp4, shows this error:

> CMD> mp4box -add 720p.h265 720p.mp4
> [Importer] Unknown input file type for "720p.h265"
> [Importer] Unknown input file type for "720p.h265"
> Error importing 720p.h265: Corrupted Data in file/stream

Changing the file extension from .h265 to .265 solves the issue, but by looking at other raw formats and their extensions using `CMD> mp4box -h format`, I guess the .h265 extension must be supported as well.

**Comment by jeanlf** [comment]
thanks for the report, should now be fixed in rev 5613
