### ISSUE TITLE
Mux MP4 - MP4Box doesn't keep input framerate

### ISSUE THREAD

**Issue by donchh** [gpac/gpac#390]
Hi, 

I'm using GPAC 0.5.0+svn5324~dfsg1-1+b3 on Debian 8.1

When i try to create a MP4 file, MP4Box don't keep the input framerate, but it set 25 fps per default.

I can pass the parameter -fps to have a proper file (and avoid a desync audio/video), but according to the documentation, without argument the framerate of the input file should be kept : 

-fps FrameRate
              overrides the input video frame rate or specifies it for SUB subtitles.

Is there a workaround or a way to keep the input framerate when creating a MP4 file ? 

Thanks !

**Comment by rbouqueau** [comment]
Hi,

Would it be possible for you to test with the latest version. Binaries at http://gpac.io/downloads/gpac-nightly-builds/, or build with almost no deps from: http://gpac.io/2015/07/29/gpac-build-mp4box-only-all-platforms/

**Comment by donchh** [comment]
Hi @rbouqueau ,

I have try the last version 0.6.0 and it seems to be fixed. (Passthough for fps is now supported)

Thanks for the tips
