### ISSUE TITLE
mp4box -lang complains about 2-letter language code

### ISSUE THREAD

**Issue by sandersaares** [gpac/gpac#392]
DASH uses the en-US variant of language codes and thus, I wish to add such codes (either en or en-US style) to my tracks. Indeed, mp4box operates quite correctly when I do so with `mp4box -lang 1=en myfile.mp4` and I have no issues with the output.

However, it generates this dangerously misleading message during operation:

    The given code is not a valid one: es, using 'und' as 3-letter code

I am not at all interested in the 3-letter codes but users viewing the operation logs now think that something is broken. Having this "error" message is undesirable for me. If possible, it would be nice to have some mode of operation that ignores the 3-letter language codes in its diagnostic output (and actual operation).

**Comment by cconcolato** [comment]
The 3-letter code is the legacy format used in MP4. We have to set one. We given a non-3-letter code, we try to find one. There was a bug in the code to find the 3-letter from the 2 letter. I've fixed it. Reopen the issue if this is not the case.
