### ISSUE TITLE
Does mp4box support hardware accelerated AES?

### ISSUE THREAD

**Issue by sandersaares** [gpac/gpac#395]
I am interested in understanding if mp4box supports hardware-accelerated AES. In a sense, I am asking "Is it possible to make mp4box -crypt faster" but I imagine hardware acceleration is the main method to accomplish this.

The scenario in question is one where we might have a large amount of data that needs to be encrypted on the fly - obviously, very good performance would be needed from the encryption process in such a scenario.

If it does not currently use hardware-accelerated AES such as AES-NI, is it technically compatible? I am not familiar with how the hardware accelerated AES instructions work, so I wonder if what I ask about is perhaps impossible.

**Comment by rbouqueau** [comment]
Thank you. I also wonder. There is a chance that GPAC can take advantage of OpenSSL direct. Here are some links to check:
- https://www.cryptopp.com
- OpenSSL => http://stackoverflow.com/questions/25284119/how-can-i-check-if-openssl-is-support-use-the-intel-aes-ni
- https://en.wikipedia.org/wiki/OpenBSD_Cryptographic_Framework / https://github.com/freebsd/freebsd/tree/master/sys/opencrypto
- NSS (https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS) used by Firefox and Chrome

To test perfs: https://software.intel.com/en-us/articles/download-the-intel-aesni-sample-library

**Comment by jeanlf** [comment]
Now supported through openSSL integration
