### ISSUE TITLE
SBR Issue

### ISSUE THREAD

**Issue by bytos** [gpac/gpac#398]
When using batch files it is inconvenient to have to set -sbr for certain files, or having to use separate batch files.

Is it not possible for mp4box to determine if the audio file is ADTS/HE-AAC?

Noticed I couldn't mux and .h264 and an .aac, later learned about the -sbr option.

**Comment by jeanlf** [comment]
no, detecting SBR or PS in AAC packaged in ADTS requires almost full decoding of the frame. You have to manually set the flag (either -sbr or :sbr option in -add )
