### ISSUE TITLE
Two Audio Streams

### ISSUE THREAD

**Issue by bytos** [gpac/gpac#399]
When muxing .h264 and .aac I get a .mp4 with two identical audio streams.

mp4box.exe -add %%A:fps=23.976 -add "%%~nA.aac":sbr "%%~nA.mp4"

![ss](https://cloud.githubusercontent.com/assets/16452541/12735792/0ae5ccb2-c921-11e5-91cb-e4a4f948ebb8.png)

**Comment by combucha** [comment]
Give -info of your %%A.
Looks like %AA is not raw video, but mp4 with audio, that could explain two audio streams after muxing.

**Comment by jeanlf** [comment]
also make sure you sepcify -new if you want to create a new file

**Comment by bytos** [comment]
Working fine now, thanks.

mp4box.exe" -raw 1:output="%%~nA.h264" -raw 2:output="%%~nA.aac" %%A
mp4box.exe" -add %%A:fps=23.976 -add "%%~nA.aac":sbr "%%~nA.mp4"

**Comment by combucha** [comment]
%%A**#1**:fps=23.976
