### ISSUE TITLE
set-track-id 

### ISSUE THREAD

**Issue by amuth** [gpac/gpac#401]
Hello,

with rev376 the command "mp4box.exe -add "d:\test.mp4#2" -set-track-id 2:1 -new "d:\extract.m4a" works without any problems. The 2nd track of the source mp4 is an aac-audio track. The aac-track-id of the new file is #1.

If I use but the current build rev1175, I get back an error and the aac-track-id is still #2.

Please help me.

**Comment by jeanlf** [comment]
indeed now fixed, thanks for the report

**Comment by amuth** [comment]
very nice
