### ISSUE TITLE
Problem with umlaut

### ISSUE THREAD

**Issue by amuth** [gpac/gpac#403]
Hello,

with rev376 the command ' mp4box -raw 1 "d:\test_ü.mp4" -out "d:\test_ü.hevc" ' works without any problems.

If I use but the current build rev1182, the extracted filename is " test_Ã¼.hevc " and not " test_ü.hevc " !

Please help me.

**Comment by jeanlf** [comment]
what platform are you testing on ?

**Comment by amuth** [comment]
Windows 7 x64 German

**Comment by cconcolato** [comment]
Strange, I cannot reproduce your issue. I'm testing in Windows 10 x64 French. The output file does have the ü. Are you using the "cmd" console or another one? How do the files look like in Windows File Explorer?

**Comment by amuth** [comment]
I'm using the "cmd.exe" and I saved the mp4 file on "d:\test\ü.mp4". 
![screenshot](https://cloud.githubusercontent.com/assets/16451876/12945974/52188706-cff1-11e5-9a6f-8121a89e8e04.png)

**Comment by cconcolato** [comment]
OK. I can reproduce your problem. It comes from the -out. If you omit it, the name will be ü_track1.hevc. Will check what we can do.

**Comment by cconcolato** [comment]
Should work with this latest commit. Reopen if this is not the case.

**Comment by amuth** [comment]
Thanks very much
