### ISSUE TITLE
Split with-in second?

### ISSUE THREAD

**Issue by combucha** [gpac/gpac#405]
I have a video with RAPs at sample 1,301,307,453...
RAP 301 & 307 are close to each other, in the same second.
Split option can adjust only to one of them and choosing RAP 307.
However it's not "true decodable keyframe", that playable is 6 frames before.
Splitted fragment plays with frozen glitch at beginning (from RAP 453 video is playing fine).
If StartTime:EndTime could be defined as double-precision number (like -fps) that could solve the problem, right?

**Comment by rbouqueau** [comment]
> I have a video with RAPs at sample 1,301,307,453...

I don't know how you retrieved this information. Can you check with http://gpac.io/2015/11/02/check-key-frame-alignment-with-mp4box/?

> If StartTime:EndTime could be defined as double-precision number (like -fps) that could solve the problem, right?

That's already the case.

Could you share a sample + your command-lines?
Dropbox at https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95 if necessary

**Comment by combucha** [comment]
RAPs were checked with mp4box -dts, ffprobe also reports these frames as type I

It happened in movie with blackness between scenes - real I-frame was pure black, while few frames later on rough scene change was second I-frame, which was not decodable-independent as that black one. Was that other kind of I-frame, marked as sync sample but not viewable at random access?

Will try to find other file with two RAP's in the same second. as mentioned one was fixed in hex editor and I have no access to it now. I manually cut out that 6 frames from raw stream, -cat'ed with raw of 'broken split' and it worked as expected without glitch.

**Comment by rbouqueau** [comment]
Ok. Please let us know when you have a sample.

**Comment by rbouqueau** [comment]
Closing because of lack of sample. Please re-open if needed.
