### ISSUE TITLE
Using generated dashinit mp4 for progressive download

### ISSUE THREAD

**Issue by luckcfm** [gpac/gpac#406]
I'm trying to use the generated dashinit as a backup source from my vod files but when I create the dashinit mp4 with mp4box It seems that the faststart option is missing which I had in the previous file, is there a way to keep the faststart option for progressive download with the mp4box?

Thanks.

**Comment by rbouqueau** [comment]
What you call the "dashinit" is a fragmented mp4. This file is suitable for progressive download.

Could you provide with a full example + command-line so that we can reproduce the issue?

**Comment by luckcfm** [comment]
Hi @rbouqueau  thanks for the reply. 

Here's a sample file http://srv21.viacast.tv/lorde.mp4 , I can only play the video when the whole file is downloaded. 


I'm using the following command-line:
 mp4box -dash 10000 -frag 1000 -rap path\yourfile.mp4

**Comment by rbouqueau** [comment]
What's your player?

**Comment by luckcfm** [comment]
I'm using jwplayer 7,  but for my tests I'm using the default from my browser (chrome).

**Comment by rbouqueau** [comment]
Chrome doesn't play it well. However Firefox and VLC do. Let me have a look at the file structure to see what we have.

**Comment by rbouqueau** [comment]
By the way why DASHing it?

**Comment by luckcfm** [comment]
I'm working in a solution where I'll have multiple sources for backup porpuses and the dash will be the main source for multiple bitrate.

**Comment by luckcfm** [comment]
And I want to keep a single file on my storage instead of keeping the original mp4 and the fragmented one  :P

**Comment by rbouqueau** [comment]
Fixed in 1283686c3e4c4c25e4b7a6ad0a73d43c52afe13b thanks to @jeanlf

**Comment by cconcolato** [comment]
FYI if you enable CORS on your server, MSE-based players like MP4Box.js (download.tsi.telecom-paristech.fr/gpac/mp4box.js/) would work too.
