### ISSUE TITLE
DashCast [libx264@xxxxxxxxxx] non-strictly-monotonic PTS

### ISSUE THREAD

**Issue by xshrinix** [gpac/gpac#407]
C:\GPAC> DashCast -v C:\demo\abc.mp4 -vfr 24 -conf C:\demo\dashcast.conf -out C:\xampp\htdocs\dash\

[34m[1mOptions:
    video source: C:\demo\abc.mp4
    video framerate: 24
    video crop: 0x0
    audio source:
[0m[34m[1mConfigurations:
    id:v1       res:1920x1080   vbr:1000000
    id:v2       res:1280x720    vbr:800000
    id:v3       res:640x360     vbr:400000
[0mInput #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\demo\abc.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2014-02-06 06:07:23
  Duration: 00:02:10.05, start: 0.000000, bitrate: 194 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 480x360 [SAR 1:1 DAR 4:3], 120 kb/s, 30 fps, 30 tbr, 60 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 71 kb/s (default)
    Metadata:
      creation_time   : 2014-02-06 06:07:23
      handler_name    : IsoMedia File Produced by Google, 5-11-2011
AVCTX give frame duration of 1/60 - keeping requested rate 24, but this may result in unexpected behaviour.
Press q or Q to exit...
[libx264 @ 0000000002c09980] using SAR=1/1
[libx264 @ 0000000002c09980] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX AVX2 FMA3 LZCNT BMI2
[libx264 @ 0000000002c09980] profile High, level 4.0
[libx264 @ 0000000002c09980] 264 - core 142 r2431 ac76440 - H.264/MPEG-4 AVC codec - Copyright 2003-2014 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=24 keyint_min=2 scenecut=40 intra_refresh=0 rc_lookahead=24 rc=abr mbtree=1 bitrate=1000 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[libx264 @ 00000000047ca920] using SAR=1/1
[libx264 @ 00000000047ca920] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX AVX2 FMA3 LZCNT BMI2
[libx264 @ 00000000047ca920] profile High, level 3.1
[libx264 @ 00000000047ca920] 264 - core 142 r2431 ac76440 - H.264/MPEG-4 AVC codec - Copyright 2003-2014 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=24 keyint_min=2 scenecut=40 intra_refresh=0 rc_lookahead=24 rc=abr mbtree=1 bitrate=800 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[libx264 @ 00000000047dc360] using SAR=1/1
[libx264 @ 00000000047dc360] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX AVX2 FMA3 LZCNT BMI2
[libx264 @ 0000000002c09980] non-strictly-monotonic PTS
[libx264 @ 00000000047dc360] profile High, level 3.0
[libx264 @ 00000000047dc360] 264 - core 142 r2431 ac76440 - H.264/MPEG-4 AVC codec - Copyright 2003-2014 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=24 keyint_min=2 scenecut=40 intra_refresh=0 rc_lookahead=24 rc=abr mbtree=1 bitrate=400 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[libx264 @ 00000000047ca920] non-strictly-monotonic PTS
[libx264 @ 00000000047dc360] non-strictly-monotonic PTS

**Comment by jeanlf** [comment]
dashcast is deprecated, use GPAC 0.9.0 DEV
