### ISSUE TITLE
[Dashcast] CPU loading is 98% during dashcast execution.

### ISSUE THREAD

**Issue by mindole** [gpac/gpac#408]
When I execute dashcast command as follows : 
DashCast -vf dshow  -vres 1280x720 -vfr 24 -v video="WebCam SC-10HDP12631N" -pixf yuv420p -live

I used the latest GPAC win64 binaries.
During encoding dash segments, the CPU usage percentage is extremely high (95%) on my PC.
My laptop PC has Quard-core processor.
Can I divide the load with Quard-core processor during dashcast ?

Thanks in advance.

**Comment by jeanlf** [comment]
nothing we can do about that, we rely on ffmpeg+x264 for the encoding. You can try using low delay mode (-low-delay) or lower the resolution.

**Comment by ulrichghislain** [comment]
Hello i need a help please , i'am a beginner on dashcast 
i have a stream mpeg2ts and i want to have a stream dashcast 
this is command that i'm typing
"DashCast -av udp://@239.x.x.x:1234?fifo_size=3000000 -live -seg-dur 8000 -mpd-refresh 8 -time-shift -1 -min-buffer 10 -npts -conf config_dashcast.conf -ast-offset 16000" then i just have a folder output empty (no chunk stream inside)

i get this error in command ---->"[mpegts @ 0x24561e0] Could not find codec parameters for stream 6 (Unknown: none ([5][0][0][0] / 0x0005)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options"

----->"Assertion desc failed at libswscale/swscale_internal.h:674
thanks in advance
