### ISSUE TITLE
[Dashcast]How to know the information audio input to use dashcast command 

### ISSUE THREAD

**Issue by mindole** [gpac/gpac#409]
I'd like to capture with video "screen-capture-recorder" and audio "microphone" using dashcast.

I am using dashcast for WIN 64 binary.

So, how can I get the information regarding audio
I know that it should be used the option -a plughw:[x],[y]
x is the card number y is the device number.
How can I get the information above in the windows platform..

Thank you so much in advance..

**Comment by jeanlf** [comment]
dashcast is deprecated, use GPAC 0.9.0 DEV
