### ISSUE TITLE
How do I fix BufferLength and RebufferLength in mp4client 

### ISSUE THREAD

**Issue by JeevanPokhrel** [gpac/gpac#411]
I configured the BufferLength and RebufferLength in the config file in GPAC however it changes automatically as the video is playing.
How do I fix during the entire playback?

Regards,
JP

**Comment by JeevanPokhrel** [comment]
In the configuration file, regarding bufferlength and rebufferlength it is written that "A module may decide to use a different value based on protocol and network jitters". However, in my case I would like to fix the values of buffer length and rebuffer length during the entire playback period. How do I fix it during the entire playback?

I will be waiting for your response.
Thank you  
JP

**Comment by jeanlf** [comment]
BufferLength and RebufferLength values are not reconfigure once the playback is started, what makes you think they are ? What kind of stream are you playing ?

**Comment by JeevanPokhrel** [comment]
I am working with mpeg-dash. I configured the bufferlength 12000ms and rebuffer length 4000ms. If the network quality is good than no change occur in the corresponding buffer lengths. However, I found that whenever the network quality degrades (For this I inserted packet losses in the network), the player after some time elapse changes the rebuffer length to 40ms (minimum value).

**Comment by rbouqueau** [comment]
> the player after some time elapse changes the rebuffer length to 40ms (minimum value)

Where do you see that? In the GPAC.cfg?

**Comment by JeevanPokhrel** [comment]
I see it in the player statistics. If I am right, if I fix the rebuffer length to 4000 ms (minimum bufferlength) then in the run time (playback) buffer should not be less that this value (4000 ms), and  it  should start rebuffering, till it reaches maximum buffer length ( maxbuffer length 12000 ms).
However, when the network quality is very bad, realtime buffer reaches the minimum value.
I have attached the screen shot.
![screenshot](https://cloud.githubusercontent.com/assets/2299369/13079710/dded185e-d4c5-11e5-9561-b0676c47877f.JPG)

**Comment by rbouqueau** [comment]
1) wha'ts your GPAC version?
2) could you share access to your test content?

**Comment by JeevanPokhrel** [comment]
hi,
I am using the latest version of GPAC gpac-0.5.2 for windowsxp 32 bit.
I have attached a manifest as txt file here with the email.
[manifest.txt](https://github.com/gpac/gpac/files/134535/manifest.txt)

I could not attach all my video here since its is of very big size so I have attached one of the segment
[video-1segment.tar.gz](https://github.com/gpac/gpac/files/134547/video-1segment.tar.gz)

If it is fine please let me know.
.

**Comment by JeevanPokhrel** [comment]
Please let me know if you find any solution to this issue?
I tried to attach my content here but the file size is very large...is there any other way?
Regards,
JP

**Comment by rbouqueau** [comment]
Why don't you shorten the content, try to see if you can reproduce the issue, and then share it with us?

And would you mind try with the latest GPAC please?

**Comment by jeanlf** [comment]
that was a bug in the rebuffering for dash should now be fixed. Could you check and reopen if needed ?
