### ISSUE TITLE
MPD File puts incorrect codec for DTS audio

### ISSUE THREAD

**Issue by jeprojects** [gpac/gpac#412]
When using the following mp4box command:

> MP4Box -dash 5000 -rap -frag-rap -profile onDemand -out video.mp4 audio.mp4

Audio is DTS

The mpd file is output like this:

`<Representation id="6" mimeType="audio/mp4" codecs="mp4a.a9" audioSamplingRate="48000" startWithSAP="1" bandwidth="1512196">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <BaseURL>audio_dashinit.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="902-1653">
      <Initialization range="0-901"/>
    </SegmentBase>
   </Representation>`

The codec seems incorrect and doesn't work with mpeg dash players like Exoplayer (Android).

If I change the codecs="dtsc", everything works fine in Exoplayer.

Is there a reason why MP4BOX isn't putting the codec correctly?

**Comment by rbouqueau** [comment]
Hi, thanks for reporting. Could you share a sample so that I can reproduce?
Dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by jeprojects** [comment]
Hi @rbouqueau,

I have uploaded an audio sample.

**Comment by rbouqueau** [comment]
Thanks. I could reproduce. There is indeed a bug: GPAC sets a generic value while DTS 9302K62400C states which exact value to add.

I'll keep you posted here.

**Comment by jeprojects** [comment]
@rbouqueau Thanks very much for looking into this. I also get mp4a.40.2 for AAC audio too. Is this the same bug?

**Comment by rbouqueau** [comment]
I am not sure to understand. The values come from https://tools.ietf.org/html/rfc6381 and are all correct. With DTS, the value MP4Box outputs is generic at the moment ; a better value is possible and described in a DTS document. I'm going to implement it. Clearer?

**Comment by jeprojects** [comment]
@rbouqueau Ok thanks.

**Comment by rbouqueau** [comment]
At the same time, the sample entry is not correct. Do you know which muxer was initially used?

One of the strength of MP4 is its ability to manipulate (e.g. split or DASH) content without any knowledge.  If the source content is improperly signaled, it may cause issues.

**Comment by jeprojects** [comment]
I grabbed the sample from here: http://www.demo-world.eu/download-2d-trailers/?file=thx_eclipse_long_lossless-DWEU.mkv&pic=thx_eclipse.jpg

And extracted the audio using:

> ffmpeg -y -i dtstest.mkv -map 0:1 -c:a copy -map_metadata -1 audio0.mp4

**Comment by cconcolato** [comment]
According to the MP4 Registration Authority, there are 2 ways to set the track type and codecs: using an MPEG-4 Systems audio track mp4a with the object type A9 (http://mp4ra.org/object.html), and the other one is using a separate track type 'dtsc' (http://mp4ra.org/codecs.html). We should probably put dtsc by default unless the -mpeg4 flag is set. 

Regarding DASH, the file you provided uses mp4a so MP4Box keeps that value to produce the MPD. I don't think  we should change the mpd generation. It should respec the input.

**Comment by rbouqueau** [comment]
> Regarding DASH, the file you provided uses mp4a so MP4Box keeps that value to produce the MPD. I don't think we should change the mpd generation. It should respec the input.

I think we should change the GPAC MPD generation to extend the current RFC 6381. And return 'dtsc' for 0xA9 as DTS recommends (4.2.1 in http://www.dts.com/~/media/b9e4cd8e8915416b84e77e56a4a254c0/9302K62400D_DTS_DASH_Spec.pdf).

**Comment by rbouqueau** [comment]
Email sent to DASH-IF for clarification. As far as I understand, the MPEG DASH spec says we 'shall' use RFC6381 so MP4Box seems correct here.
