### ISSUE TITLE
Mp4box changes resolution when using chroma 444

### ISSUE THREAD

**Issue by tmpcrt** [gpac/gpac#413]
Hello.
Seems like there is a problem when muxing .264 files to .mp4 if the original .264 video uses chroma 4:4:4 (8 or 10 bit).

I have a video of 1000x800 resolution uncompressed .avi bgr24 and I did some tests:

.avi to .264 commands after pass 1:

```
x26410.exe ^
--pass 2 ^
--profile high444 ^
--preset slow ^
--output-csp i444 ^
--range pc ^
--fps 30 ^
--sar 1:1 ^
--stats "C:\testshit.stats" ^
--bitrate 6000 ^
--output testshit44410bit.264 "C:\testshit.avi"
```

Using x264 (8 or 10 bit) and using profile (high or high10) and using --output-csp i420:

- .264 video -> no problem
- muxing it with Mp4box -> no problem

Using x264 (8 or 10 bit) and using profile **high444** and using **--output-csp i444**:

- .264 video -> no problem
- muxing it with Mp4box -> **problem** (changes width to 992 and, for example, MPC-HC reports resolution as "1000x800 (RdA 31:25)" 992x800.)

I have tested with mp4box version that comes with MP4boxgui 0606, mp4box rev563 and rev1180 using this commands:

` -add "C:\testshit44410bit.264:fps=30.000:delay=0:name=testshit44410bit.264" -itags tool="My MP4Box GUI 0.6.0.6 blablabla" -brand mp42 -new "C:\testshit44410bit.mp4"`

Latest Mediainfo and x264 18jan2016 version.

**Comment by rbouqueau** [comment]
Thanks for reporting. To help us go faster could you share a sample with us? https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by tmpcrt** [comment]
I uploaded to the link you posted a file called x264.zip that contains original .avi and the processed files. Hope it helps you.

**Comment by rbouqueau** [comment]
Thank you very much. I am on it.

**Comment by rbouqueau** [comment]
Should be fixed! thanks for the precise report, it helped a lot. Re-open if necessary.
