### ISSUE TITLE
Unable to create MPEG-DASH content.

### ISSUE THREAD

**Issue by merargin** [gpac/gpac#414]
I am getting "Option -dash unknown. Please check usage" while executing the following command.

MP4Box -frag 3000 -dash 3000 -segment-name segment_file file.mp4

Please someone guide me to create the content.

**Comment by rbouqueau** [comment]
Please read this: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/ and complete the bug description.

What does 'MP4Box -version' output?

**Comment by merargin** [comment]
I feel sorry for not providing sufficient details. 

MP4 version: 

MP4Box - GPAC version 0.4.5 (build 33)
GPAC Copyright: (c) Jean Le Feuvre 2000-2005
		(c) ENST 2005-200X

PS: I am using CentOS

**Comment by rbouqueau** [comment]
Please update, your version it too old. Here are some short command-lines to build: https://gpac.wp.mines-telecom.fr/2015/07/29/gpac-build-mp4box-only-all-platforms/
