### ISSUE TITLE
Service CanHandleURL returns false when URL is remote and MimeType is incorrect

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#416]
Typically we could open a Smooth Streaming URL. But if it is the mime type is plain/text like in
http://www.bok.net/tmp/dash/smooth_tfdt/stream.ism/Manifest
or
http://www.bok.net/tmp/dash/smooth_no_tfdt/stream.ism/Manifest

then we return immediately.

**Comment by rbouqueau** [comment]
Any comment on this?

**Comment by jeanlf** [comment]
fixed
