### ISSUE TITLE
v0.5.2 fails to build against FFmpeg 3.0

### ISSUE THREAD

**Issue by zmwangx** [gpac/gpac#417]
FFmpeg recently pushed out the 3.0 release, and gpac v0.5.2 seems to have trouble building against it (OS X 10.11.3):

```
> ./configure --disable-wx --prefix=/usr/local/Cellar/gpac/0.5.2 --mandir=/usr/local/Cellar/gpac/0.5.2/share/man --disable-x11-shm --disable-x11-xv
...
> make
...
  CC ffmpeg_decode.c
  CC ffmpeg_demux.c
  CC ffmpeg_load.c
Undefined symbols for architecture x86_64:
  "_av_close_input_file", referenced from:
      _FFD_CanHandleURL in ffmpeg_demux.o
      _FFD_CloseService in ffmpeg_demux.o
      _FFD_ConnectService in ffmpeg_demux.o
  "_avpicture_deinterlace", referenced from:
      _FFDEC_ProcessData in ffmpeg_decode.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [gm_ffmpeg_in.dylib] Error 1
make[1]: *** [plugs] Error 2
make: *** [all] Error 2
```

Full logs here: https://gist.github.com/anonymous/2bd2fbada48fb6591d9d#file-02-make. Building master against FFmpeg 3.0 was a success, though.

Therefore, would you please consider cutting a release to address this compatibility issue? This issue is unfortunately blocking FFmpeg 3.0 at [Homebrew](https://github.com/Homebrew/homebrew/pull/49178) (a stable release is required there).

**Comment by rbouqueau** [comment]
I just tried with the latest GPAC master with FFmpeg 3 (https://github.com/FFmpeg/FFmpeg/releases/tag/n3.1-dev). It works.

GPAC 0.5.2 is now too old. We need urgently to make a new version. See also #370

**Comment by rbouqueau** [comment]
We're going to tag a new version by the end of the week so that stable versus dev is easier for homebrew people (great job by the way!)

**Comment by zmwangx** [comment]
Cool, thanks for the quick reaction!

**Comment by rbouqueau** [comment]
Release done: https://github.com/gpac/gpac/releases/tag/v0.6.0. Thanks for your patience. Please close the issue if it solves it.

**Comment by zmwangx** [comment]
Yep build issue resolved. Thanks again.
