### ISSUE TITLE
[DASH] Add the way to specify custom DASH profiles / interoperability points / extensions.

### ISSUE THREAD

**Issue by vladimir-kazakov** [gpac/gpac#42]
Hi!

At this moment, MP4Box allows to specify only specific DASH profiles (the `-profile` option). But DASH-IF IOP mentions (in section 1) that content authors may signal the specific subset of DASH-IF IOP. As far as I know (correct me if I'm wrong), the only thing that is needed is to be able to specify custom extension identifiers (Table 1) in MPD@profiles, which will describe the actual media.

Right now, MP4Box uses generic "http://dashif.org/guildelines/dash264" for the DASH-264/AVC case, for example. But it would be nice if it would be possible to specify custom identifiers, like "http://dashif.org/guidelines/dashif#sd", for example.

Perhaps, there could be another option added to MP4Box for that purpose. Maybe something like `-profile-extension`, or anything like that. So, the idea is that you still have to specify the `-profile`, but if you want another identifier, then you additionally specify it in the `-profile-extension`.

**Comment by jeanlf** [comment]
Now possible using -profile-ext
