### ISSUE TITLE
MP4Box mix the stdout and stderr up

### ISSUE THREAD

**Issue by jose-oc** [gpac/gpac#423]
MP4Box mix the **stdout** and **stderr** up when you run the command in a linux terminal.

You can test it by running MP4Box and separating the standard output and the error output into different files, i.e.:
`MP4Box -diso -std sintel_trailer-480p.mp4 > std.out 2> std.err`

The information for that mp4 file should be in the _std.out_ file but in fact the _std.out_ is empty but the file _std.err_ contains the information for the mp4 file, this is the result of the MP4Box command.
It should be in the other way around since no error happens.

**Comment by jeanlf** [comment]
that is correct, now fixed thanks for the report

**Comment by Maciejszuchta** [comment]
I noticed the same behaviour on 
`MP4Box - GPAC version 0.8.0-rev1-gc1990d5c-master
(c) Telecom ParisTech 2000-2018 - Licence LGPL v2
GPAC Configuration: (static configuration file)
Features: GPAC_64_BITS GPAC_MEMORY_TRACKING GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG`
When I run mp4box commands from .Net app all information is redirected to standard error.

![image](https://user-images.githubusercontent.com/12434636/84129803-bafe1a80-aa42-11ea-82e0-9fd170d22f79.png)

**Comment by rbouqueau** [comment]
I've just tried the top post and it works. @wtn What did you try?
