### ISSUE TITLE
fps vs timescale vs rescale

### ISSUE THREAD

**Issue by gits68** [gpac/gpac#426]
Hi,

Could you explain clearly the difference between the fps, timescale and rescale options ?
What this really means : !! THIS IS IGNORED FOR IsoMedia IMPORT !!
In others words, when fps doesn't work, when to use timescale instead of fps, etc.

Thanks in advance.

**Comment by rbouqueau** [comment]
From the MP4Box help:
```
-fps FPS               forces frame rate for video and SUB subtitles import
                        FPS is either a number or expressed as timescale-increment
                        * For raw H263 import, default FPS is 15
                        * For all other imports, default FPS is 25

```

```
-timescale VAL       sets movie timescale to VAL ticks per second (default is 600)
```

```
":rescale=TS\"        forces media timescale to TS !! changes the media duration
```

> !! THIS IS IGNORED FOR IsoMedia IMPORT !!

GPAC does two things: 1) import data from codecs (h264, hevc, aac, etc.) and external containers (avi, ts, etc.) and 2) manipulate ISOBMF/MP4. This message says the parameter only applies to 1).

Please let us know if you need further explanantions. It may help improve the documentation so any input is welcome.
