### ISSUE TITLE
 Files have non-proportional track layouts (854x480 vs 640x360) error

### ISSUE THREAD

**Issue by HimanshuN** [gpac/gpac#427]
hello,
when I am writing the following command for creating a single mpd file for two different resolution videos, this error is comming. Though the dashinit files and mpd have been created successfully but this mpd is not accepted by my dash player.

the error is  " Files have non-proportional track layouts (854x480 vs 640x360) but sample size and aspect ratio match, assuming precision issue "

and the command I am using is : 
MP4Box -dash 2000 -rap -frag-rap -profile onDemand -out mpd v480.mp4#video v360.mp4#video v480.mp4#audio

where v480 is 854 * 480 video and v360 is 640 * 360

please help me

**Comment by rbouqueau** [comment]
Could you provide the GPAC version and any useful information as stated in http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Then coul you share with us the MPD and the input files so that we can reproduce.
Anonymous dropbox at https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by HimanshuN** [comment]
I am using GPAC version 0.5.1-DEV-rev4065.

this folder contains all my input and output files 

https://www.mediafire.com/folder/2k9cpqp2fgl1x/files_mpd

Input files I am using are 

v480.mp4 is 480p resolution
v360.mp4 is 360p resolution

and after running this command 
"MP4Box -dash 2000 -rap -frag-rap -profile onDemand -out mpd v480.mp4#video v360.mp4#video v480.mp4#audio" 

this message was printed
"[DASH]: Files have non-proportional track layouts (720x480 vs 480x360) but sample size and aspect ratio match, assuming precision issue"

and following files were created

mpd.mpd, 
v360_track1_dashinit.mp4, 
v480_track1_dashinit.mp4, 
v480_track2_dashinit.mp4 

I also want to know that what does this non proportional track layouts means ? I also searched it on internet but find know relevant definition about this error.

**Comment by rbouqueau** [comment]
Your GPAC version is out of age (4y old: https://sourceforge.net/p/gpac/code/4065/), could you please update?

**Comment by jeanlf** [comment]
v480 is not 854x480 but 720x480 (double-checked with ffmpeg), so the MPD contains 2 adaptation sets each one with a video, no error here.
