### ISSUE TITLE
xvid with custom quand matrix won't playback (no video)

### ISSUE THREAD

**Issue by gits68** [gpac/gpac#428]
Hi,

for playback reason, I've changed the container of almost all my avi files to mp4.
in others words, my tv play mp4 files much better than avi files, same content, just container change.
unfortunatelly, I've some file which doesn't play back at all, i.e., the sound is ok, but no images.
they play well using avi container.
the only reason I've found is that these videos have a "custom quant matrix" instead of a h263 standard matrix.

a sample file is located at http://cyrillelefevre.free.fr/tmp/novideo.avi (2Mo, 30sec)
http://cyrillelefevre.free.fr/tmp isn't browsable, that's normal.

remux with mp4box -add novideo.avi#video:lang=fra:timescale=25000:name= -add novideo.avi#audio:lang=fra:mpeg4:name= -new novideo.mp4

also tried without success with ffmpeg -i novideo.avi -vcodec copy -acodec copy novideo.mp4

any ideas to bypass/solve this problem ?

PS : video are played through plex on a TV brand/model LG 55LX5590.

**Comment by jeanlf** [comment]
closing, this is not related to GPAC, remuxed file plays well with Kodi/VLC/ffplay/MP4Client. Maybe check with Plex guys ?
