### ISSUE TITLE
Export to srt - wrong output filename

### ISSUE THREAD

**Issue by amuth** [gpac/gpac#429]
Hello,

I use mp4box 0.6.0 rev 9. I want to export subtitles with the command:

mp4box.exe -srt 3 "D:\abc.mp4" -out "d:\abc_track3_deu.srt"

The Output-File-Name is but "abv_track3_deu_3_text.srt"

The error is not very critical, but a solution would not be bad.

**Comment by rbouqueau** [comment]
@jeanlf I see that we do that for other dumps as well:
```strcat(szBuf, "_ismacryp.xml");```

Is it expected?

**Comment by jeanlf** [comment]
This is now fixed for all dump options, thanks for the report
