### ISSUE TITLE
HLS Encryption support

### ISSUE THREAD

**Issue by canatella** [gpac/gpac#435]
As of now, the HLS encryption support is limited to exporting the key url and AES initialization vector too the mpegts demuxer.

Looking at the ismacrypt module I do not see how that architecture could be used for HLS. Indeed, the mpegts demuxer needs the data to be decrypted before the packet can be decoded and dispatched to the IPMP module. 

What would you consider a good architecture for this ? I think that a new module interface would be needed that could be called between the mpd_in reader and the mpegts demuxer.

**Comment by rbouqueau** [comment]
Hi! Would you have a sample stream so that I can make a test?

**Comment by canatella** [comment]
Nope, it uses HLS encryption, the access to the keys are secured. But anyway, does what I said previously makes sense for you ?

**Comment by rbouqueau** [comment]
I understand but I wonder if it doesn't almost work already. I need to build such a stream to test.

**Comment by canatella** [comment]
Well has of know there is no call to aes decryption before sending data to the demuxer so it cannot work.

**Comment by rbouqueau** [comment]
Ok so we are talking about AES-128, not SAMPLE-AES correct?

**Comment by canatella** [comment]
Yes, AES-128 indeed.

**Comment by jeanlf** [comment]
do we still need to look at this? seems that most services now use per-sample AES when used in TS, or switched to fMP4 ...

**Comment by jeanlf** [comment]
closing this. For those interested, the proper way to do that with 0.9.0 would be to to add  IV/KID properties on the input handler (http, file), have the TS demuxer exclude pids with such properties and create a filter to do this decryption, outputing a regular TS

**Comment by rbouqueau** [comment]
@jeanlf Can we leave this issue open until someone tries what you suggest?
