### ISSUE TITLE
[DASH] When constructing sub-stream URLs, the ?... part of the URL is dropped

### ISSUE THREAD

**Issue by canatella** [gpac/gpac#44]
When trying to play a dash stream where the sub-stream URLs contains parameters like http://foo.com/my/stream.ts?foo=bar&baz=bar, the ?foo=bar&baz=bar part is dropped due to the code at line 673 of src/media_tools/m3u8.c:

```c
	char *fullURL = strstr(currentLine, "?");
	if (fullURL) {
		/*some URL contains garbage after the filename*/
		size_t len = fullURL-currentLine;
		fullURL = gf_malloc(len+1);
		strncpy(fullURL, currentLine, len);
		fullURL[len] = '\0';
	} else {
		fullURL = currentLine;
	}
```

Using only
```c
fullURL = currentLine;
```
fixes the problem.

**Comment by canatella** [comment]
See 000960772c770f1e0c9e72bd933385ca5071379e for my ugly fix.

**Comment by rbouqueau** [comment]
Fixed by @jeanlf 's commit
