### ISSUE TITLE
Problems playing live multi-period stream

### ISSUE THREAD

**Issue by ct1n** [gpac/gpac#440]
MP4Client seems to have problems playing this stream: http://31.14.160.192:8000/ah/manifest.mpd

**Comment by perses** [comment]
When running with "-logs dash@debug" it looks like MP4Client is stuck in an infinite loop. The following messages keep repeating:
  [MPD_IN] Received Service Query Next request from input service GPAC IsoMedia Reader
  [IsoMedia] No more segments - done playing file
  [IsoMedia] Track #1 end of stream reached

**Comment by jeanlf** [comment]
this should have been fixed a while ago
