### ISSUE TITLE
-cat files where target is bigger than 2GB fails

### ISSUE THREAD

**Issue by arnaudleyder** [gpac/gpac#445]
MP4Box version:
MP4Box - GPAC version 0.6.1-rev0-g72d766c-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: --host=x86_64-linux-gnu --prefix=/usr --build=x86_64-linux-gnu --mandir=${prefix}/share/man --extra-cflags=-Wall -g -fPIC -DPIC --cc=ccache cc CXX=ccache g++
Features: GPAC_64_BITS GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG

OS: Ubuntu 14.04.4 LTS 64 bits

Cmd: MP4Box -cat edlive2.mp4 -cat edlive2.mp4 edlive3.mp4
edlive2.mp4 is 1.74 GB 

Output:
Appending file edlive2.mp4
No suitable destination track found - creating new one (type vide)
No suitable destination track found - creating new one (type soun)
Appending file edlive2.mp4
Error writing data (No space left on device): 1 blocks to write but 0 blocks written
Error appending edlive2.mp4: I/O Error

Additional info:
df -h
Filesystem             Size  Used Avail Use% Mounted on
udev                   5.9G  4.0K  5.9G   1% /dev
tmpfs                  1.2G  512K  1.2G   1% /run
/dev/md1               4.0G  914M  3.1G  23% /
none                   4.0K     0  4.0K   0% /sys/fs/cgroup
none                   5.0M     0  5.0M   0% /run/lock
none                   5.9G     0  5.9G   0% /run/shm
none                   100M     0  100M   0% /run/user
/dev/mapper/vg00-usr   103G  3.9G   95G   4% /usr
/dev/mapper/vg00-var   699G   19G  652G   3% /var
/dev/mapper/vg00-home   54G   16M   51G   1% /home

So I have enough space on my HDD. I am on a 64-bits OS. Still it seems the -cat command fails as soon as the output is over 2GB. I can -cat files fine when I am below the 2GB mark.

Can you please tell me if I am doing something wrong? Is there a flag to pass to MP4Box for large mp4 files?

Thanks

**Comment by jeanlf** [comment]
have you tried specifying another location for temp files using -tmp option ? It looks like your tmpfs is full

**Comment by arnaudleyder** [comment]
The -tmp flag did the trick. Thanks.

**Comment by omgbox** [comment]
thanks -tmp help me too :dancer:
