### ISSUE TITLE
Nightly build corrupted

### ISSUE THREAD

**Issue by combucha** [gpac/gpac#452]
Hi, latest gpac nb is broken:
http://download.tsi.telecom-paristech.fr/gpac/latest_builds/win32/gpac-0.6.2-DEV-rev48-g30b4af0-master-win32.exe
File is only ~10MB.

I used to grab latest exes from there, but for example if I wanted "stable" 0.6.1 do I have to compile it myself or looking for exe on third party sites?

**Comment by jeanlf** [comment]
Thanks for the report, the broken installer has been fixed. 
I also added direct links to 0.6.1 release for all platforms on our download page, so that you don't have to compile it yourself.
