### ISSUE TITLE
DashCast: Inconsistent issue with availabilityStartTime with dynamic mpd in live video

### ISSUE THREAD

**Issue by carterh062** [gpac/gpac#453]
Hi,
It seems that to get the DASH-MPEG standard to work well with 8000 millisecond segments and SegmentTemplate, the availabilityStartTime needs to be about 20 seconds behind, so i have set in my DashCast command `-ast-offset 20000`. This generally works and ensures that the Dash Player will not look for segments that are so close to realtime that they have yet to be uploaded and registered by my CDN (S3 -> Cloudfront). 

However, though sometimes it plays perfectly and the mpd is correct, other times it will set the availabilityStartTime in the mpd to be this: `availabilityStartTime="1900-01-01T00:00:20.000Z"`. Because of this, the player (dash.js) will look for enormous segment numbers and will not find them, causing the live video to be unplayable. 

Is there something that I am doing wrong in my command? I'm not using a conf file, and my full command looks like this, omitting the input (-av) option, :`-live -seg-dur 8000 -ast-offset 20000 -min-buffer 16.0 -npts -low-delay -out /output`. 

It appears to work consistently without the -ast-offset option and it sets the ast correctly. However, that will frequently cause the player to look for segments that don't exist yet.

It consistently sets the ast incorrectly when using a conf file as follows: 

[v1]
type=video
width=1920
height=1080
bitrate=4000000
[a1]
type=audio
bitrate=128000

Thanks so much,
Carter

**Comment by carterh062** [comment]
Actually, just tested this without the -ast-offset option and it set the availabilityStartTime to 1900-01-01T00:00:20.000Z again, so I guess that option is not the source of the problem.

**Comment by jawerty** [comment]
+1

**Comment by carterh062** [comment]
I happened to be uploading the mpd to S3 using python. Using the standard xml library in python, I was able to format the availabilityStartTime as a string correctly in python, change the xml, and upload it to get around this.

**Comment by jawerty** [comment]
+2

**Comment by jeanlf** [comment]
dashcast is now deprecated, use GPAC 0.9.0
