### ISSUE TITLE
mp4box generates incorrect element order in DASH manifest for encrypted adaptation set

### ISSUE THREAD

**Issue by sandersaares** [gpac/gpac#454]
When I use latest mp4box (0.6.2-DEV-rev56-g30c5f14-master) to package CENC encrypted mp4 files, the generated presentation manifest contains the following:

```
<AdaptationSet segmentAlignment="true" maxWidth="1920" maxHeight="1080" maxFrameRate="30" par="16:9" lang="und">
			<SegmentTemplate timescale="30" media="$RepresentationID$/$Number%04d$.m4s" startNumber="1" duration="120" initialization="$RepresentationID$/init.mp4" />
			<ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="7a4a1d66-0a65-4172-9267-38840795e42d" />
```

However, according to DASH specification the correct order is the opposite - `ContentProtection` must be before `SegmentTemplate`. This causes [validation of the manifest](http://dashif.org/conformance) to fail.

Here is the mp4box command line used:

```
mp4box.exe -noprog -dash-strict 4000 -out "ooo2\Encrypted\Manifest.mpd" -profile "dashavc264:live" -sample-groups-traf -bs-switching no "temp2\EncryptStreams\v-288-400k.mp4" "temp2\EncryptStreams\v-360-800k.mp4" "temp2\EncryptStreams\v-480-1200k.mp4" "temp2\EncryptStreams\v-720-2100k.mp4" "temp2\EncryptStreams\v-1080-3000k.mp4" "temp2\EncryptStreams\a.mp4" "temp2\EncodeTextStreams\TOS-zh.mp4" -segment-name $RepresentationID$\$Number%04d$$Init=init$
```

**Comment by rbouqueau** [comment]
> according to DASH specification

Not seen in DASH second edition. Not seen either in DASH IF IOP 3.0. Do you have a pointer on the spec? Or might it be an issue in the validator?

Note that we may change its location if it leads to better interoperability. What is your use-case?

PS: that's not the first issue on this element location, https://github.com/gpac/gpac/search?q=ContentProtection&type=Issues&utf8=%E2%9C%93

**Comment by sandersaares** [comment]
See DASH 2nd edition Annex B "MPD schema". AdaptationSetType is an extension of RepresentationBaseType and both define their contents as sequences (sets of elements with specific order) and extensions themselves are always treated as sequences, as well.

Thus, ContentProtection (from RepresentationBaseType) must be before SegmentTemplate (from AdaptationSetType).

**Comment by cconcolato** [comment]
I think you're right. Can you submit a patch?

**Comment by sandersaares** [comment]
I am afraid I lack the required skills to contribute any code on the topic - all I can contribute is my understanding of the inputs and outputs and hope someone else can make good use of this!

**Comment by cconcolato** [comment]
I've just fixed it for those 2 descriptors (https://github.com/gpac/gpac/commit/b03ae9ae4719e00656790be09cde2002fa131514), but it still has descriptor order problems in general. We'll have to fix it more globally. HTH.

**Comment by jeanlf** [comment]
can we close this then ?

**Comment by sandersaares** [comment]
I confirm the order is now correct, at least for those 2 descriptors.
