### ISSUE TITLE
i am unable to use mp4client in gpac,following issue is occuring

### ISSUE THREAD

**Issue by sas987** [gpac/gpac#457]
`
![screenshot from 2016-03-16 01 49 27](https://cloud.githubusercontent.com/assets/17861003/13793217/de9025b4-eb1b-11e5-86e9-c6df5d29772f.png)
Thanks` for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by sas987** [comment]
hey i downloaded latest gpac but couldn't succeded

**Comment by jeanlf** [comment]
this is not the latest version of GPAC, the config file is now called GPAC.cfg on all platforms, not .gpactrc, and is stored in $HOME/.gpac on linuxes/unixes/BSDs.
Make sure you either use the git version or the 0.6.1 release
