### ISSUE TITLE
 Commit "More fixes on AVI audio dumping and misc fixes"  breaks playing on Android

### ISSUE THREAD

**Issue by canatella** [gpac/gpac#46]
Commit 5fccaca14a3f653f9a49981707675a72d42d4ff4 "More fixes on AVI audio dumping and misc fixes" breaks playing on android, Audio is stuttering and playing http://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4, it skips after some seconds right to the end.

**Comment by canatella** [comment]
As a matter of fact on version before that commit, Osmo4 on android is not showing any picture on my Oneplus One and LG 4X HD. I think it's linked to libstagefright because it works ok on my GPAC integration with software decoding.

**Comment by nguyen-viet-thanh-trung** [comment]
Which Android version have you got in your phone ? Could you please verify in the file osmo/debug_libs.txt  whether you have some exceptions while loading the libraries ?

**Comment by canatella** [comment]
Android 4.4.4 on both LG and Oneplus. 

Indeed there is an exception:

*** Exceptions:
stlport_shared: Couldn't load stlport_shared from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.gpac.Osmo4-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.gpac.Osmo4-2, /vendor/lib, /system/lib]]]: findLibrary returned null(class java.lang.UnsatisfiedLinkError)

**Comment by nguyen-viet-thanh-trung** [comment]
This bug should by fixed in the latest version. Could you please test it ?

**Comment by canatella** [comment]
With osmo4-0.5.2-DEV-rev35-gd2da0a8-master.apk, the movie starts but there are lots of audio skips during the first 30 seconds.

With osmo4-0.5.2-DEV-rev35-gd2da0a8-master-stagefright.apk, the movie starts but lots of frame drop. Same audio skips during the first 30 seconds.

Nothing in debug_libs.txt. 

Which commit is the fix ?

**Comment by nguyen-viet-thanh-trung** [comment]
osmo4-0.5.2-DEV-rev35-gd2da0a8-master.apk and osmo4-0.5.2-DEV-rev35-gd2da0a8-master-stagefright.apk are built from the same commit, with and without libstagefright.
Have you got only probleme with audio during the first 30 seconds, and then it's ok ?

**Comment by canatella** [comment]
Yes.

**Comment by nguyen-viet-thanh-trung** [comment]
Did you play a local file or an URL ? I tried to download and play the file in your first comment, it worked well. When I played directly your URL it took me time for buffering. Perharps it is the same situation with you ?

**Comment by canatella** [comment]
Yes indeed it was an URL.

2015-02-06 18:58 GMT+01:00 nguyen-viet-thanh-trung <notifications@github.com
>:

> Did you play a local file or an URL ? I tried to download and play the
> file in your first comment, it worked well. When I played directly your URL
> it took me time for buffering. Perharps it is the same situation with you ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gpac/gpac/issues/46#issuecomment-73282756>.
>



-- 
Damien MERENNE   <dam@cosinux.org>

**Comment by rbouqueau** [comment]
Can we close the issue?
