### ISSUE TITLE
Is it possible to create mp4 without audio track?

### ISSUE THREAD

**Issue by Tim666** [gpac/gpac#462]
Sorry for stupid question.
I have avi file with several ac3 audio tracks.
I try to create mp4 file from avi
`mp4box.exe -add "e:\test.avi#video:fps=23.976:packed" "e:\test.mp4"`
And get error "Unsupported AVI audio format"  I think it's result that mp4box doesn't support AC3 
But I didn't ask to put audio track to output file.
Does exist any option to disable audio output to result file?

**Comment by nguyen-viet-thanh-trung** [comment]
Hi,
You can export your avi video track to its native format by: MP4Box -aviraw video test.avi, then import the raw file.

**Comment by jeanlf** [comment]
could you upload your file somewhere?

**Comment by Tim666** [comment]
I can put MediaInfo for this file.
It's a pity, I've found out that my TV doesn't support H.263 in mp4 container but supports it in the .avi file only and mp4box doesn't help me. 
Thank for your help.

`
General
Complete name                            : E:\ve\test.avi
Format                                   : AVI
Format/Info                              : Audio Video Interleave
File size                                : 356 MiB
Duration                                 : 22mn 57s
Overall bit rate mode                    : Variable
Overall bit rate                         : 2 169 Kbps
Movie name                               : Пилот (Pilot)
Director                                 : by Volshebnik
Writing application                      : VirtualDubMod 1.5.10.2 (build 2542/release)
Writing library                          : VirtualDubMod build 2542/release

Video
ID                                       : 0
Format                                   : MPEG-4 Visual
Format profile                           : Advanced Simple@L4
Format settings, BVOP                    : 2
Format settings, QPel                    : No
Format settings, GMC                     : No warppoints
Format settings, Matrix                  : Default (H.263)
Muxing mode                              : Packed bitstream
Codec ID                                 : XVID
Codec ID/Hint                            : XviD
Duration                                 : 22mn 57s
Bit rate                                 : 1 579 Kbps
Width                                    : 720 pixels
Height                                   : 400 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 23.976 (23976/1000) fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.229
Stream size                              : 259 MiB (73%)
Writing library                          : XviD 1.2.1 (UTC 2008-12-04)

Audio 1
ID                                       : 1
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : 2000
Duration                                 : 22mn 57s
Bit rate mode                            : Constant
Bit rate                                 : 192 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Frame rate                               : 31.250 fps (1536 spf)
Compression mode                         : Lossy
Stream size                              : 31.5 MiB (9%)
Alignment                                : Split accross interleaves
Interleave, duration                     : 42 ms (1.00 video frame)
Interleave, preload duration             : 500 ms
Title                                    : MTV

Audio 2
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : 2000
Duration                                 : 22mn 57s
Bit rate mode                            : Constant
Bit rate                                 : 192 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Frame rate                               : 31.250 fps (1536 spf)
Compression mode                         : Lossy
Stream size                              : 31.5 MiB (9%)
Alignment                                : Split accross interleaves
Interleave, duration                     : 42 ms (1.00 video frame)
Interleave, preload duration             : 500 ms
Title                                    : NTV

Audio 3
ID                                       : 3
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Mode                                     : Joint stereo
Mode extension                           : MS Stereo
Codec ID                                 : 55
Codec ID/Hint                            : MP3
Duration                                 : 22mn 57s
Bit rate mode                            : Variable
Bit rate                                 : 192 Kbps
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 KHz
Compression mode                         : Lossy
Stream size                              : 30.3 MiB (9%)
Alignment                                : Aligned on interleaves
Interleave, duration                     : 26 ms (0.63 video frame)
Interleave, preload duration             : 103 ms
Title                                    : ENG
Writing library                          : LAME3.98 
Encoding settings                        : -m j -V 4 -q 3 -lowpass 18.6 --abr 192
`
P.S. Anyway If there is no enough information and you want to continue this issue for improving mp4box I can make short sample file for this case.
