### ISSUE TITLE
Naming the init file

### ISSUE THREAD

**Issue by jegjessing** [gpac/gpac#464]
When I execute MP4Box with parameters for placing the segment files in a folder, the segment files are located just as wanted.
My problem is, that I would also like to have the init file in the same folder, but no arguments I make enables this possibility :-(
**So I get this name of the init file**
initialization="34_init.mp4"
**And the segments**
 media="34/segment_$Number$.m4s" 

What I would like is:
initialization="34/34_init.mp4"
media="34/segment_$Number$.m4s" 

How do I do that? I have tried with **-mpd-info-url=34/34_init.mp4**, but no luck

**Another thing is**
I have 3 input files
* zzz_lowband.mp4
* zzz_midband.mp4
* zzz_highband.mp4
I would like to have the segments in:
34/lowband/segments...
34/midband/segments...
34/highband/segments...

It this possible?

Thanks in advance

**Comment by sandersaares** [comment]
-segment-name $RepresentationID$\\$Number%04d$$Init=init$

This works for me. Everything is in representation-specific subfolders.

**Comment by jegjessing** [comment]
Thanks, found a for me, better way :-)
