### ISSUE TITLE
libtool: unrecognized option `-s'

### ISSUE THREAD

**Issue by 4getit** [gpac/gpac#467]
Although I could a few weeks ago, somehow, I'm no longer able to build MP4box (on OS X 10.11.4).

When doing:

git clone https://github.com/gpac/gpac.git
cd gpac
git pull
./configure --static-mp4box --use-zlib=no
make -j4

make fails with libtool: unrecognized option `-s'

**Comment by RodolpheFouquet** [comment]
Hi,

Are you using libtool from the XCode command line tools?

You might need to use libtool from homebrew/macports. 

https://github.com/Homebrew/homebrew/blob/master/Library/Formula/libtool.rb

**Comment by 4getit** [comment]
I closed the issue already because I figured it was something on my end. 
You are right that was it. I can build again now. Thank you.

**Comment by rbouqueau** [comment]
I'm trying to figure out if we can improve our libtool detection so that other users don't run into the same issues. Seems to be GNU versus BSD, correct? Would looking for the '-s' flag be sufficient?

**Comment by 4getit** [comment]
I'm afraid I don't know a solution other than installing other libtools until it works. 
But if you want, I can test things. I have 2 environments now. One where it works and the other with the error.

**Comment by jeanlf** [comment]
Strange, just tested on same OSX version without any issue, using libtool from XCode 7.3 (7D175) and latest xcode command line tools installed. Are you using the same xcode version ?
