### ISSUE TITLE
new segment not found error and live streaming using DashCast

### ISSUE THREAD

**Issue by HimanshuN** [gpac/gpac#469]
can anyone please help me to achieve live streaming using DashCast. 
I am trying this command : 
DashCast -vf video4linux2 -v4l2f mjpeg -v /dev/video0 -af alsa -out output/ -npts 

which is creating segments, then on new terminal I am using 

MP4Client output/dashcast.mpd

which is running successfully for sometime but then shows error of not finding new segments.
This error is because the MP4Client is searching segments at faster rates than DastCast creating it. Moreover this dashcast.mpd is not running with Dash.js

I have also tried -live and -live-media commands but with that the situation is getting worse as it is giving either error of "Live system dropped a video frame" or making improper frames which in result not showing any result.

I am new to this field, please suggest something to work it out.

Thanks in advance,
Himanshu

**Comment by ulrichghislain** [comment]
Hello i need a help please , i'am a beginner on dashcast 
i have a stream mpeg2ts and i want to have a stream dashcast 
this is command that i'm typing
"DashCast -av udp://@239.x.x.x:1234?fifo_size=3000000 -live -seg-dur 8000 -mpd-refresh 8 -time-shift -1 -min-buffer 10 -npts -conf config_dashcast.conf -ast-offset 16000" then i just have a folder output empty (no chunk stream inside)

i get this error in command ---->"[mpegts @ 0x24561e0] Could not find codec parameters for stream 6 (Unknown: none ([5][0][0][0] / 0x0005)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options"

----->"Assertion desc failed at libswscale/swscale_internal.h:674

**Comment by jeanlf** [comment]
dashcast is now deprecated, use GPAC 0.9.0
