### ISSUE TITLE
Mp4box calculates wrong time using split

### ISSUE THREAD

**Issue by combucha** [gpac/gpac#470]
Over 2hrs dvdrip, sync sample box looks like this:

SyncSampleEntry sampleNumber="1"
SyncSampleEntry sampleNumber="301"
SyncSampleEntry sampleNumber="601"
SyncSampleEntry sampleNumber="901"
SyncSampleEntry sampleNumber="1201"
...
SyncSampleEntry sampleNumber="76764"
SyncSampleEntry sampleNumber="77064"
SyncSampleEntry sampleNumber="77364"
SyncSampleEntry sampleNumber="77664"
SyncSampleEntry sampleNumber="77964"
...
SyncSampleEntry sampleNumber="184737"
SyncSampleEntry sampleNumber="185037"
SyncSampleEntry sampleNumber="185337"
SyncSampleEntry sampleNumber="185637"
SyncSampleEntry sampleNumber="185937"
...

It's constant framerate movie, I wanted to cut out range between samples 77364 -> 185337.
In time domain it is 2581 -> 6184 s.

Execution:
C:\mp4box-0.6.1-rev0-g72d766c-master-win32>mp4box -splitz 2583:6186 vid.mp4
Adjusting chunk start time to previous random access at 1345.51 sec
Adjusting chunk end time to previous random access at 6184.04 sec
Extracting chunk vid_1345_6184.mp4 - duration 4838.53s (1345.51s->6186.00s)

I don't get how it's been adjusted to RAP at 1345s, it's 20 minutes earlier point (sample 40305).
There must be something borked,

**Comment by rbouqueau** [comment]
It indeed looks like a bug. Could you share your sample? (we have an anonymous dropbox, please put your issue number: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95)

**Comment by combucha** [comment]
It's too big for my slow upload.
Can share only a -diso's but don't know if it helps you solve issue in any way.
Original: http://www81.zippyshare.com/v/HZUcCh3u/file.html
Split: http://www14.zippyshare.com/v/xL2eafwy/file.html

**Comment by combucha** [comment]
Some addition to issue.
I was able to properly split file in mp4box after remuxing it in ffmpeg.
Basic remux cmd: ffmpeg -i %IN_FILE% -c copy %OUT_FILE%
I checked remuxed file stss table and ffmpeg marked sample 40326 as RAP.

SyncSampleEntry sampleNumber="40305"
**SyncSampleEntry sampleNumber="40326"**
SyncSampleEntry sampleNumber="40359"

This entry was missing as RAP in original file and mp4box split adjusts wrong start chunk time to random access point before that "missing" one. Broken split from previous post however is not splitted correctly, first SyncSampleEntry is sampleNumber="34" and video has frozen glitch at beginning. Thing somehow related with #405, ss 40305 and "invisible" ss 40326 are within same second.

**Comment by rbouqueau** [comment]
A sample would tremendously help (also in #405). Is there anything we can do to help you upload the data? Or is there a way that you split the faulting file so that you isolate the part that fails?

**Comment by combucha** [comment]
Since that "hidden RAP" seems causing problem, I've cut out small range around it to test purposes.
"Hidden RAP" (revealed after ffmpeg remux) is now at sample 640 (21.3s).
Mp4box behaviour with different start split points defined after ss640:

mp4box -splitz 29:50 1324_1375.mp4
Adjusting chunk start time to previous random access at 21.32 sec
Adjusting chunk end time to previous random access at 40.97 sec
Extracting chunk 1324_1375_21_40.mp4 - duration 19.65s (21.32s->50.00s)

mp4box -splitz 30:50 1324_1375.mp4
Adjusting chunk start time to previous random access at 30.00 sec
Adjusting chunk end time to previous random access at 40.97 sec
Extracting chunk 1324_1375_29_40.mp4 - duration 10.98s (30.00s->50.00s)

mp4box -splitz 40:50 1324_1375.mp4
Adjusting chunk start time to previous random access at 21.32 sec
Adjusting chunk end time to previous random access at 40.97 sec
Extracting chunk 1324_1375_21_40.mp4 - duration 19.65s (21.32s->50.00s)

Test file sent to dropbox, sorry for content.

**Comment by nguyen-viet-thanh-trung** [comment]
It should be fixed now, could you try the latest version ?

**Comment by combucha** [comment]
Can't see the difference:

C:\gpac-0.6.2-DEV-rev294-g679cd0a-master-win32>mp4box -splitz 30:50 1324_1375.mp4
Adjusting chunk start time to previous random access at 30.00 sec
Adjusting chunk end time to previous random access at 40.97 sec
Extracting chunk 1324_1375_29_40.mp4 - duration 10.98s (30.00s->50.00s)

C:\gpac-0.6.2-DEV-rev294-g679cd0a-master-win32>mp4box -splitz 31:50 1324_1375.mp4
Adjusting chunk start time to previous random access at 21.32 sec
Adjusting chunk end time to previous random access at 40.97 sec
Extracting chunk 1324_1375_21_40.mp4 - duration 19.65s (21.32s->50.00s)

Still goes to 21.3s point and produced file has first RAP at sample 34.

**Comment by rbouqueau** [comment]
It seems that your GPAC version (https://github.com/gpac/gpac/commit/c19ab83) is older than the fix (2d769e34a8a24fbaa5fef9b1577a34dc6b00a549).

**Comment by combucha** [comment]
Seems you have right.

**Comment by nguyen-viet-thanh-trung** [comment]
@combucha  please try the latest version (ie. rev320)

**Comment by combucha** [comment]
Ok, seems adjusting times have been almost fixed.
The only thing that remained (to solve or clarify) is that sample 640 (21,32s).
Mp4box doesn't list this entry as RAP:
SyncSampleEntry sampleNumber="1" -> 0s
SyncSampleEntry sampleNumber="149" -> 4,93s
SyncSampleEntry sampleNumber="398" -> 13,24s
SyncSampleEntry sampleNumber="619" -> 20,62s
SyncSampleEntry sampleNumber="673" -> 22,42s
But split option "see" this point:
C:\gpac-0.6.2-DEV-rev320-gc4476af-master-win32>mp4box -splitz 22:50 1324_1375.mp4
Adjusting chunk start time to previous random access at 21.32 sec
Adjusting chunk end time to previous random access at 40.97 sec
Extracting chunk 1324_1375_21_40.mp4 - duration 19.65s (21.32s->50.00s)

What actually happening here?
Splitted file has glitch at start, 33 first frames aren't decodable.

**Comment by nguyen-viet-thanh-trung** [comment]
It's because the sample 640 is marked as belonging to a 'rap' group, When you dump your file, you have something like:
<SampleGroupDescriptionBox grouping_type="rap " default_length="1">
<BoxInfo Size="25" Type="sgpd"/>
<FullBoxInfo Version="1" Flags="0x0"/>
<VisualRandomAccessEntry num_leading_samples_known="no"/>
</SampleGroupDescriptionBox>
<SampleGroupBox grouping_type="rap ">
<BoxInfo Size="36" Type="sbgp"/>
<FullBoxInfo Version="0" Flags="0x0"/>
<SampleGroupBoxEntry sample_count="639" group_description_index="0"/>
<SampleGroupBoxEntry sample_count="1" group_description_index="1"/>
</SampleGroupBox>
</SampleTableBox>

**Comment by nguyen-viet-thanh-trung** [comment]
It's because the sample 640 is marked as belonging to a 'rap' group. When you dump your file, you wil get some info like:
`<SampleGroupDescriptionBox grouping_type="rap " default_length="1">
<BoxInfo Size="25" Type="sgpd"/>
<FullBoxInfo Version="1" Flags="0x0"/>
<VisualRandomAccessEntry num_leading_samples_known="no"/>
</SampleGroupDescriptionBox>
<SampleGroupBox grouping_type="rap ">
<BoxInfo Size="36" Type="sbgp"/>
<FullBoxInfo Version="0" Flags="0x0"/>
<SampleGroupBoxEntry sample_count="639" group_description_index="0"/>
<SampleGroupBoxEntry sample_count="1" group_description_index="1"/>
</SampleGroupBox>
</SampleTableBox>`

**Comment by combucha** [comment]
I see...I assume I should expect "glitch mines" if splitting at such points. Thanks
