### ISSUE TITLE
Problem with playback of segment of specific files

### ISSUE THREAD

**Issue by jegjessing** [gpac/gpac#471]
I have trancoded a lot of files and all goes well, but some files fails on playback after dashing them, like this one:
http://movietrailers.apple.com/movies/independent/identicals/identicals-tlr_h1080p.mov

I can trancode then just fine using ffmpeg. The resulting files can be played just fine all the way through on all bitrates that I generate. BUT after dashing the file and trying to play the segmented files, it stops at 1:30, every thime.
I've tried to do it again and again, same result
An example of parameters that I use for ffmpeg: -y -c:a libfdk_aac -ac 2 -ab 128k -c:v libx264 -x264opts 'keyint=48:min-keyint=48:no-scenecut:fps=24' -b:v 2048k
        -b:a 128k -bufsize 1000k -vf "scale=-2:720"
and the dash arguments are like:
-dash 2000 -frag 2000 -rap (plus base-url, mpd title and some other "soft" parameters)
I don't know what happens at 1:30, but something sure throws off dash here.
Any help would be much appreciated

**Comment by rbouqueau** [comment]
Do you mean that you dashed a .mov? Most players only support .mp4.

**Comment by jegjessing** [comment]
Yeah, no I used ffmpeg to transcode it to mp4 first

**Comment by rbouqueau** [comment]
> -dash 2000 -frag 2000 -rap

Did you consider trying the command-lines from Bitmovin and from the DASH IF?
http://www.gpac-licensing.com/2014/11/03/bitmovin-leverage-mp4box-package-contents-bitdash-player/
http://www.gpac-licensing.com/2014/08/21/ibc-2014-dash-avc264-support-in-gpac/

**Comment by rbouqueau** [comment]
Closing because of lack of data.
