### ISSUE TITLE
Chunked encoding not supported for DASH segments

### ISSUE THREAD

**Issue by Rokamun** [gpac/gpac#472]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!
- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Playback of a stream where the segments are served using chunked encoding fails with these errors:

[HTTP] Error parsing reply: Dialog Failure with remote peer for URL http://192.168.178.42:8080/dash/bbb/chunk_1_18125.m4s
[DASH] FAILED to download http://192.168.178.42:8080/dash/bbb/chunk_1_18125.m4s = Dialog Failure with remote peer...
[DASH] Error in downloading new segment: http://192.168.178.42:8080/dash/bbb/chunk_1_18125.m4s Dialog Failure with remote peer - starting countdown for 625 ms

The issue seems to be caused by a download of another segment being started while the previous segment hasn't been fully received yet, and MP4Client being unable to deal with the resulting reply. See attached wireshark capture of a failed HTTP dialog where this is clearly visible.

This seem to be the case at least for versions 6.2 and 5.X.

[mp4client_downloadfail.pcapng.zip](https://github.com/gpac/gpac/files/202033/mp4client_downloadfail.pcapng.zip)

**Comment by rbouqueau** [comment]
Hello Balder, thanks for reporting. We appreciate. My colleagues told me parallel downloads were introduced last week only (after the latest release) so that's weird!

Would there be a way to reproduce on our end? You can drop me an email with a binary for any platform (preferably window or linux). Thanks!

**Comment by Rokamun** [comment]
Hey Romain,

I've send you the latest MistServer builds, I've triggered the problem in Linux, so I would pick those binaries. 

To trigger it add an stream to MistServer and run MP4Client over the output.

The syntax for DASH streams is the following for MistServer:

http://**HOST**:**PORT**/dash/**STREAMNAME**/index.mpd

**Comment by rbouqueau** [comment]
Received, thanks!

**Comment by jeanlf** [comment]
this is working on git and quite tested now, reopen if needed
