### ISSUE TITLE
hevc losing frames

### ISSUE THREAD

**Issue by Selur** [gpac/gpac#479]
MP4box seems to have problems with hevc content and sometimes breaks the first gop.
> MP4Box -par 1=32:27 -add "H:\Output\original hevc_20_07_53_4610_02.265"#video:fps=23.976 -brand hvc1 -mpeg4 -tmp "H:\Temp" -new "H:\Output\mp4box_remux.mp4"

-> first gop broken (r2d2 isn't really visible)
> ffmpeg -r 25 -i "H:\Output\original hevc_20_07_53_4610_02.265" -c copy h:\Output\ffmpeg_remux.mp4

-> fine
> mkvmerge --ui-language en -o "H:\Output\mkvmerge_remux.mkv" --disable-track-statistics-tags -d 0 --default-track 0:yes --default-duration 0:24000/1001fps --aspect-ratio-factor 0:1.185 --compression -1:none --forced-track 0:yes --no-audio --no-subtitles "H:\Output\original hevc_20_07_53_4610_02.265"

-> fine

uploaded the source and the muxed files to my google share as [mp4box_hevc.7z](https://drive.google.com/folderview?id=0B_WxUS1XGCPAUTlILW54VThMTFU&usp=sharing)

**Comment by nguyen-viet-thanh-trung** [comment]
It should be fixed now, could you try the latest version ?

**Comment by Selur** [comment]
Just checked -> seems to be fixed :)

Thanks!
