### ISSUE TITLE
MP4Box: TTML (EBU-TT-D) mimeType looks wrong

### ISSUE THREAD

**Issue by cjpdev** [gpac/gpac#48]
When dashing a EBU-TT-D subtitle track, the generated MPD seems to have the wrong value for the mime type  minetype="video/mp4"

<Representation id="sub" mimeType="video/mp4" codecs="stpp" startWithSAP="1" bandwidth="9212">

The DVB spec:  7 DASH Specific Aspects for Subtitles , The signalling of subtitling codecs for the codec parameter uses RFC6381 [6] as shown in the Table 10:

minetype=application/mp4

**Comment by rbouqueau** [comment]
I confrm that the DASH-IF doc (http://dashif.org/w/2014/08/DASH-IF-IOP-v2.90.pdf) says:
```SMPTE Timed
Text [15] with
ISO BMFF encapsulation

@mimetype:application/mp4 @codecs:stpp

ISO/IEC 14496-12 [5]
ISO/IEC 14496-30 [21] ```

**Comment by cjpdev** [comment]
Thanks

Does the Mp4Client support TTML (EBU-TT-D) subtitles?

**Comment by rbouqueau** [comment]
Not yet. This development (EBU-TTD in MP4Box) was sponsored by DASH-IF/EBU (http://gpac.wp.mines-telecom.fr/2014/08/23/ebu-ttd-support-in-gpac/) but it didn't include the playback.

GPAC supports WebVTT playback however. You can read more at:
 - http://gpac.wp.mines-telecom.fr/2014/08/23/ebu-ttd-support-in-gpac/
 - http://gpac.wp.mines-telecom.fr/2014/09/04/subtitling-with-gpac/

**Comment by cjpdev** [comment]
Thanks

Looking at the MP4Box code, I can see that in "dash_segmenter.c" : line 1757,
it does not check is the representation is anyother type other than (video|audio)

fprintf(dash_cfg->mpd, " mimeType=\"%s/mp4\" codecs=\"%s\"", audio_only ? "audio" : "video", szCodecs);

**Comment by cjpdev** [comment]
Change my version to does this:

	if(strcmp (szCodecs,"stpp") == 0)
	{
		fprintf(dash_cfg->mpd, " mimeType=\"%s/mp4\" codecs=\"%s\"", audio_only ? "audio" : "video", szCodecs);
	} else {
		fprintf(dash_cfg->mpd, " mimeType=\"application/mp4\" codecs=\"%s\"", szCodecs);
	}

**Comment by cconcolato** [comment]
The DASH-IF guidelines are contradictory with the MIME Type registration for MP4 files (https://tools.ietf.org/html/rfc4337#page-3) which says that if that application/mp4 should be used only if no audio and no visual data is present in the file. Subtitles are visual data, so the video/mp4 should apply.

**Comment by cjpdev** [comment]
It also says that (if the file contains neither visual nor audio presentations, but
only, for example, MPEG-J or MPEG-7, use application/mp4;).

The subtitle track only contains xml data , so if (application/mp4) is used for MPEG-J or MPEG-7, then xml should also use (application/mp4) ?

Side note:
Dash.js :uses "application/ttml+xml", which is not part of (DASH-IF) or (DASH DVB)

**Comment by rbouqueau** [comment]
> if the file contains neither visual nor audio presentations

@cconcolato said "Subtitles are visual data, so the video/mp4 should apply".

> Dash.js :uses "application/ttml+xml", which is not part of (DASH-IF) or (DASH DVB)

"application/ttml+xml" is for TTML which is not in MP4 files.

**Comment by cjpdev** [comment]
Okay 
  Thanks

**Comment by kozmaz87** [comment]
"application/ttml+xml" is for TTML which is not in MP4 files. not supported by gpac either. I just tried to load sidecar subtitles. How am I supposed to load it now?

**Comment by nickshanks** [comment]
Subtitles are not visual data, they are purely textual data, which may be rendered aurally via text-to-speech, rendered aurally or electromagnetically as morse code, rendered visually via mapping to a sequence of rasterised glyph outlines, rendered haptically via a refreshable Braille device, translated into Klingon and beamed across the universe, hashed for security purposes, or just piped to some other part of a program for any number of other operations. If anything, text/mp4 should apply, but that is not a registered media type, so the use application/mp4 for a file containing only subtitles is correct.

**Comment by nigelmegitt** [comment]
See https://www.w3.org/TR/ttml-profile-registry/ for the reference on this (or look see the [IANA registration](https://www.iana.org/assignments/media-types/application/ttml+xml)):

> TTML defines a MIME type/subtype, `application/ttml+xml`

This is definitive.
