### ISSUE TITLE
0.6.1 fails to compile with --static-mp4box

### ISSUE THREAD

**Issue by Geyup** [gpac/gpac#483]
My Specs;

Slackware 14.1 x86_64
gpac 0.6.1 - compiled from source

My compile flags
```
LDFLAGS="-L/usr/lib${LIBDIRSUFFIX}" \
./configure \
  --prefix=/usr \
  --mandir=/usr/man \
  --disable-opt \
  --cpu=${ARCH} \
  --static-mp4box \
  --extra-cflags="$SLKCFLAGS" \

make -j1 2>&1 | tee $OUTPUT/make-${PRGNAM}.log
make install DESTDIR=$PKG
make install-lib DESTDIR=$PKG
```

0.6.1 will compile and install ok if I don't use the ```--static-mp4box``` option.

Actually in the past I was able to compile any version of gpac with ```--static-mp4box```, now I can't. I'm not sure what has changed on my box to of caused this...

hmm

Here's the output of make;

http://dpaste.com/3XFP5RM

**Comment by rbouqueau** [comment]
Several things: unless you are distrib maintainer, you should not install anything in /usr, but in /usr/local instead.

You build issue comes from an interference with a previously installed GPAC. Please 'sudo make uninstall' before building:
```
make[2]: Entering directory `/tmp/foo/gpac-0.6.1/applications/mp4box'
[...]
/usr/lib64/libgpac_static.a(ismacryp.o)
```

**Comment by Geyup** [comment]
Hello rbouqueau,

I apologize, I thought I had gpac uninstalled when I was compiling.

By the way, I've been using Slackware a very LONG TIME LOL... :)

Slackware users don't compilie into /usr/local, to be honest not sure why we're not doing it, but what I do have as example is two versions of gcc, and for situations of multipile versions of something, I install into /usr/local.

Have a look at https://slackbuilds.org/ you'll not find one created Slackware script installing into /usr/local 

Also Eric Hameleers a Slackware Maintainer, doesn't create any build scripts for installing into /usr/local either.

http://www.slackware.com/~alien/slackbuilds/

AND in all the years I've been running Slackware and installing into /usr I've never had any problems, but we're talking about someone that uses build scripts to install, uninstall and maintain a system, the correct way. :)

Cheers
