### ISSUE TITLE
MP4Client locked on wrong simple bifs

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#485]
[square.zip](https://github.com/gpac/gpac/files/214565/square.zip)

**Comment by jeanlf** [comment]
could you be more specific? Parsing fails but client is not locked at all on my machine, what is the command line you are using ?

**Comment by rbouqueau** [comment]
You are right. I rebuilt all and the deadlock (in the audio mixer) went away. Sorry for the false alert
