### ISSUE TITLE
Live UDP Source support boken ?   - [dashcast] Live system dropped a video frame

### ISSUE THREAD

**Issue by Svyatk0** [gpac/gpac#487]
Hi guys.

I have a fresh installation of the GPAC version 0.6.2-DEV-rev262-g3f28607-master on Ubuntu Server 15.10. 

I have followed the guide https://gpac.wp.mines-telecom.fr/dashcast/ on installing, building and configuring FFMPEG, H264 and GPAC. All setup went through without issues. and i am at the stage of testing DashCast with live multicast sources. 

My aim is to reproduce the test described here: http://www.gpac-licensing.com/2014/07/09/lowering-dash-live-latency-240ms/ though its a bit dated, i was hoping things have improved :-)

anyways, i am having an issue when using Dashcast with live UDP source. 
thats my basic command which fails with the error of 

> [dashcast] Live system dropped a video frame

here is my command and output: 

> y@GPAC:~/dash$ sudo DashCast -av "udp://236.44.100.1:5200?fifo_size=100000&buffer_size=500000" -live -out output -mpd livetest.mpd
> MPD refresh time not set in live - defaulting to segment duration
> Options:
>     video source: udp://236.44.100.1:5200?fifo_size=100000&buffer_size=500000
>     video crop: 0x0
>     audio source: udp://236.44.100.1:5200?fifo_size=100000&buffer_size=500000
> Configurations:
>     id:v1       res:640x480     vbr:1000000
>     id:a1       abr:192000
> [udp @ 0x9ca980] attempted to set receive buffer to size 500000 but it only ended up set as 425984non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] non-existing PPS 0 referenced
> [h264 @ 0x9defe0] decode_slice_header error
> [h264 @ 0x9defe0] no frame!
> [h264 @ 0x9defe0] Increasing reorder buffer to 1
> [h264 @ 0x9defe0] Increasing reorder buffer to 2
> Input #0, mpegts, from 'udp://236.44.100.1:5200?fifo_size=100000&buffer_size=500000':
>   Duration: N/A, start: 82340.481244, bitrate: N/A
>   Program 1
>     Stream #0:0[0x6e]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt470bg), 320x180 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn
>     Stream #0:1[0xd2]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 102 kb/s
> AVCTX give frame duration of 1/50 - keeping requested rate 25, but this may result in unexpected behaviour.
> [h264 @ 0x9dea80] co located POCs unavailable
> [h264 @ 0x9dea80] co located POCs unavailable
> [dashcast] Live system dropped a video frame
> [dashcast] Live system dropped a video frame
> [dashcast] Live system dropped a video frame
> [dashcast] Live system dropped a video frame
> [dashcast] Live system dropped a video frame
> [dashcast] Live system dropped a video frame
> [dashcast] Live system dropped a video frame
> [dashcast] Live system dropped a video frame

I have tried this with various udp sources to make sure its not the source, and the result is always the same, as soon as i tell DashCast its a -Live content i am getting the error. 

Now, interestingly enough, if i dont tell it its live and do a straight command 

>  DashCast -av "udp://236.44.100.1:5200?fifo_size=100000&buffer_size=500000" -out output -mpd livetest.mpd 

Its happily chunking away, without complaining. I didnt try the playback, but the files do start getting created in the output folder. 

I didnt try this with the actual camera or screen capture source as this would be of no use to me, but i can certainly confirm that FFMPEG is happily demuxing the sources i am trying to use with DashCast
here is my FFMPEG build 

> ffmpeg version N-79345-g9149e9c Copyright (c) 2000-2016 the FFmpeg developers
>   built with gcc 5.2.1 (Ubuntu 5.2.1-22ubuntu2) 20151010
>   configuration: --enable-shared --disable-debug --enable-libx264 --enable-avresample --enable-gpl
>   libavutil      55. 20.100 / 55. 20.100
>   libavcodec     57. 34.100 / 57. 34.100
>   libavformat    57. 33.100 / 57. 33.100
>   libavdevice    57.  0.101 / 57.  0.101
>   libavfilter     6. 41.100 /  6. 41.100
>   libavresample   3.  0.  0 /  3.  0.  0
>   libswscale      4.  1.100 /  4.  1.100
>   libswresample   2.  0.101 /  2.  0.101
>   libpostproc    54.  0.100 / 54.  0.100

would anyone be able to advise what could be causing this ? 

Thanks

Svyatko

**Comment by rbouqueau** [comment]
The HTTP server and dashcast/mp4client command-lines to reproduce are available at https://github.com/gpac/node-gpac-dash

**Comment by Svyatk0** [comment]
Thanks, I have got that, but that's the server part, I am still struggling with DashCast bit to get the content to the Node Server

**Comment by Svyatk0** [comment]
the "-Live " bit is breaking the DashCast for me and I cant see what doesn't it like.

**Comment by jeanlf** [comment]
dashcast is now deprecated, use GPAC 0.9.0
