### ISSUE TITLE
DashCast will begin pseudo-encoding very quickly at certain times.

### ISSUE THREAD

**Issue by carterh062** [gpac/gpac#493]
Hello all,

I've been searching online for a while about this issue, and have found one thread from a few years ago, that seems to mention the exact problem, but not describe a solution for it. That thread is here:
https://sourceforge.net/p/gpac/discussion/287547/thread/6fa58849/

The issue that I am seeing, which is interestingly my only remaining issue with DashCast at this point ( aside from some a/v sync issues, if anyone needs assistance or an FAQ on DashCast I may be able to offer some help or guidance. ) is that with multiple video representations (various bitrates and outputs for  the dash segments), DashCast will begin encoding ONLY video segments very quickly (audio continues perfectly). However, upon further inspection of these video segments, one will note that they are not actually video segments, and though named correctly, contain no parseable MPEG-DASH data. 

**Assuming 8 second segments, the scenario where the issue prevents itself will look like this.**

1) Segments are encoded about every ~7-8 seconds until some arbitrary segment number ( e.g `v1_seg_655.m4s, v2_seg_655.m4s, a1_seg_655.m4s`)
2) Suddenly, every second or so, a new video segment will come out numbered after the previous and audio will continue encoding every ~7-8 seconds as expected. The new video segments will be corrupted and unusable. 
3) Another note is that CPU usage of DashCast will spike at this point, using 15-20x what the normal command would use.
4) One can kill and restart the DashCast command and have it start from the beginning which will solve the issue until it occurs again in the next iteration. 

**MY INFORMATION**
FFMPEG feeding DashCast cmd: `/usr/local/bin/ffmpeg -analyzeduration 14M -i rtmp://localhost:1935/nginx-rtmp -loglevel panic -y -filter_complex [0:v]scale=1280:-1:lanczos[w1280_1] -map 0:a -c:a aac -ar 44100 -ac 2 -map [w1280_1] -f mpegts udp://127.0.0.1:1234?pkt_size=1316`

DashCast cmd: `DashCast -av udp://127.0.0.1:1234?fifo_size=1000000 -live -seg-dur 8000 -conf /tmp/dashcast.conf -demux-buffer 500000 -mpd-refresh 8 -min-buffer 8.0 -gdr -npts -low-delay -out /media/ephemeral0/dash`

DashCast config:
[v1-600k]
type=video
low_delay=yes
framerate=30
height=360
width=640
codec=libx264
bitrate=600000
crop_y=0
crop_x=0
[v2-1200k]
type=video
low_delay=yes
framerate=30
height=720
width=1280
codec=libx264
bitrate=1200000
crop_y=0
crop_x=0
[v3-184k]
type=video
low_delay=yes
framerate=30
height=360
width=640
codec=libx264
bitrate=184000
crop_y=0
crop_x=0
[a1-64k]
channels=1
bitrate=64000
samplerate=44100
codec=aac
type=audio
[a2-128k]
channels=1
bitrate=128000
samplerate=44100
codec=aac
type=audio

FFMPEG Versioning information:
ffmpeg version N-78994-gbd2cc3c Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04.1)
  configuration: --enable-shared --disable-debug --enable-libx264 --enable-avresample --enable-gpl
  libavutil      55. 19.100 / 55. 19.100
  libavcodec     57. 28.100 / 57. 28.100
  libavformat    57. 28.100 / 57. 28.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 39.102 /  6. 39.102
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100

**MY THOUGHTS**
I have a few thoughts on the issue that may help in coming to some sort of solution but are just thoughts I've had throughout this debacle.
--I know that it is directly related to number of outputs. The more outputs there are, the faster DashCast will encounter this problem.
--I know that when running other encoding(such as HLS or RTSP) on the same machine, DashCast will also encounter the problem faster.
-Because of the above two points, the issue most certainly has something to do with CPU usage.
-I also know that the issue prevents itself whether I use `-live-media` or just `-live`. Live seems to be the right choice for UDP input, but the response from `-live-media` is much more succinct and shows actual legible output when the issue happens which is : `[dashcast] Live system dropped a video frame` 
-Finally I fear that perhaps the container format `mpegts` from my `ffmpeg` command could be part of the problem as well. 
I reiterate that these are just my thoughts and don't necessarily have anything to do with the issue.

Thank you so much for taking a look at this and please let me know if there is anything else you need from me,
Carter

**Comment by ulrichghislain** [comment]
Hello i need a help please , i'am a beginner on dashcast 
i have a stream mpeg2ts and i want to have a stream dashcast 
this is command that i'm typing
"DashCast -av udp://@239.x.x.x:1234?fifo_size=3000000 -live -seg-dur 8000 -mpd-refresh 8 -time-shift -1 -min-buffer 10 -npts -conf config_dashcast.conf -ast-offset 16000" then i just have a folder output empty (no chunk stream inside)

i get this error in command  ---->"[mpegts @ 0x24561e0] Could not find codec parameters for stream 6 (Unknown: none ([5][0][0][0] / 0x0005)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options"

----->"Assertion desc failed at libswscale/swscale_internal.h:674
"

**Comment by jeanlf** [comment]
dashcast is now deprecated, use GPAC 0.9.0
