### ISSUE TITLE
extra-libs compilation failed

### ISSUE THREAD

**Issue by rauf** [gpac/gpac#497]
Hello,

I  was trying to build gpac for Android according to instructions (but in Android Studio) on https://github.com/gpac/gpac/blob/master/build/android/README.

While compiling the extra-libs (point 3), it failed because the gcc path does not exist. However, there is a path through "arm-linux-androideabi-4.9", seems like only a version mismatch.

![screenshot from 2016-04-25 01-48-38](https://cloud.githubusercontent.com/assets/14014693/14770154/e675c49c-0a87-11e6-8560-2a14e2196bd5.png)

**Comment by nguyen-viet-thanh-trung** [comment]
Thank you for your feedback. The script has been updated here: http://download.tsi.telecom-paristech.fr/gpac/gpac_extra_libs.zip
Could you please retry it ?

**Comment by rauf** [comment]
`./compile_ffmpeg_android.sh` shows permission denied (on line 16) 
but if you make `compile_ffmpeg_android.sh` executable, it works fine.

**Comment by nguyen-viet-thanh-trung** [comment]
Hi,
Seem that you didn't unzip the libraries 's source code. Please run unzip_all.sh before ./gpac_build_all_extra_libs <ANDROID_NDK_DIR>

**Comment by rauf** [comment]
@nguyen-viet-thanh-trung 

I ran `unzip_all.sh` before `./gpac_build_all_extra_libs`, it now shows internal compiler error.

![screenshot from 2016-04-26 15-37-15](https://cloud.githubusercontent.com/assets/14014693/14814648/ccbd8a74-0bc4-11e6-90a3-5688316808fd.png)

**Comment by nguyen-viet-thanh-trung** [comment]
It was a temporal error due to NDK !

**Comment by sunzhibindev** [comment]
Same problem. What's your NDK version?

**Comment by aureliendavid** [comment]
You can check updated build instructions for android here: https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Android
