### ISSUE TITLE
wrong frame size

### ISSUE THREAD

**Issue by amuth** [gpac/gpac#498]
Hello,

the frame size is recognized incorrectly when importing h264 video.

**Comment by amuth** [comment]
![1 mediainfo_h264](https://cloud.githubusercontent.com/assets/16451876/14783766/2ea1d426-0af2-11e6-8821-0e72d0b929f0.png)
![2 command](https://cloud.githubusercontent.com/assets/16451876/14783774/394eaee4-0af2-11e6-954a-c3c8bdb29a26.png)
![3 mediainfo_mp4](https://cloud.githubusercontent.com/assets/16451876/14783777/3eb05374-0af2-11e6-9232-4265c5604565.png)

**Comment by nguyen-viet-thanh-trung** [comment]
Please upload your files to: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

and also give us your command so that you can reproduce your issue.

**Comment by amuth** [comment]
Upload completed.

**Comment by nguyen-viet-thanh-trung** [comment]
It should be fixed now, could you please retry ?

**Comment by amuth** [comment]
Nice, problem fixed.
