### ISSUE TITLE
check pkgconfig for static libgpac

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#5]
Apparently we don't fill it correctly. Also see https://sourceforge.net/p/gpac/bugs/341/

**Comment by moulei** [comment]
Hi,

Any changes in gpac compiled against x264?

**Comment by rbouqueau** [comment]
Not yet, but someone sponsored a side feature via www.gpac-licensing.com so I may fix it last month.

**Comment by moulei** [comment]
What is gpac-licensing.com for?

You mean fix it ```next``` month? :)

**Comment by rbouqueau** [comment]
Yes, I meant "next" :)
"gpac licensing" offers commercial support (i.e. paying and fast). On github there is only community support so it may take more time.

**Comment by moulei** [comment]
Ahh ok...

thanks
