### ISSUE TITLE
osmo4 android app GpacInstanceError

### ISSUE THREAD

**Issue by rauf** [gpac/gpac#500]
While running osmo4 android app, I am getting GpacInstanceError due to failure to load some of the libraries  ( https://github.com/gpac/gpac/blob/master/applications/osmo4_android/src/com/gpac/Osmo4/GPACInstance.java#L58 ). 
On emulator, the app shows the error while on device the app just force closes.

**Comment by nguyen-viet-thanh-trung** [comment]
Hi,
1. Which device and Android version did you use for testing ?
2. Which module was failed to load ? It could be found in debug_libs.txt in /sdcard/osmo/log.
3. Is this the same result if you use our nightly build version ?

**Comment by fcsteagu** [comment]
Hi Viet,

I also have an issue related to this.
I always get the following unsatisfied link error:

> Loading library dl...Failed to load dl, error=dlopen failed: cannot locate symbol "__cxa_finalize" referenced by "/system/lib/libdl.so"...::UnsatisfiedLinkError.

This happens on all the devices that I'm using (Android 4, 5 and 6).

Thanks!

**Comment by nguyen-viet-thanh-trung** [comment]
@rauf @fcsteagu  I had some fixes in new commit, could you please retry ?

**Comment by rauf** [comment]
@nguyen-viet-thanh-trung 

1. I used Moto G 1st gen with cm13 ROM (Android 6.0.1)

2. libdl, javaenv, gpac, gm_droid_cam, gm_droid_mpegv, gpacwrapper are failing to load. Also. it is failing to create the /sdcard/osmo/log directory. This can be due to behavior change in permissions in Android 5.0 and later.

See this gist for more info (from Android Studio logcat) https://gist.github.com/rauf/461268f72caddb1d514348342272ad88

3. The latest nightly build is not installing on my mobile.

**Comment by rauf** [comment]
Hey, @nguyen-viet-thanh-trung 

I tried your new commit and results are nearly the same.
log:  https://gist.github.com/rauf/c21542c76afabe75f9a2eb2f2fedc092

**Comment by rbouqueau** [comment]
@rauf how did you solve the ```__cxa_finalize``` issue?

**Comment by rauf** [comment]
@rbouqueau my problem cause was that I was using the wrong emulator (for wrong ABI). Also, Viet pushed a commit which rectified the issue.

**Comment by SrujithPoondla** [comment]
@rauf How did you solve your issue? I am also having same issue.
Error Log here : [(https://gist.github.com/SrujithPoondla/ff6e42b7a281a253ee89045b07d7b22e)]

**Comment by rauf** [comment]
@SrujithPoondla are you using the correct emulator?

**Comment by SrujithPoondla** [comment]
@rauf I am using Nexus 5X, the problem is I couldn't find proper documentation for building the apk with Android Studio. So I think I am doing mistake some where. In brief I will tell the procedure I followed so that you can point out any step i missed out.

1. Check out the GPAC GIT repository
2. Download extra libraries
3. compiling extra libs from downloaded files
4. To where i should copy all those compiled libraries? as there is no folder named lib according to readme in build/android/

**Comment by rauf** [comment]
@SrujithPoondla  Create the folder manually and if you are having trouble compiling extra libs, here are the pre complied libs: https://www.dropbox.com/s/4u2fo5sw116z59w/gpac_extra_libs.zip?dl=0
