### ISSUE TITLE
Build fails with mingw64 since 003fce2e

### ISSUE THREAD

**Issue by wiiaboo** [gpac/gpac#501]
Platform: MSYS2 64-bit in Windows 8.1 64-bit
Compiler: MinGW64 GCC 5.3.0 32 and 64-bit

```bash
$ mkdir build-64bit && cd build-64bit
$ ../configure --build=x86_64-w64-mingw32 --prefix=/local64 --disable-shared --static-mp4box
```
[configure output](https://i.fsbn.eu/0ICa.txt)
```bash
$ make
```
[make output](https://i.fsbn.eu/6wpF.txt)

**Comment by jeanlf** [comment]
this was fixed by #4f4bb1f , thanks for the report. Reopen if still failing

**Comment by wiiaboo** [comment]
Confirmed working. By the way, Travis mingw tests seem to be using the wrong options. Most/all the external libs should be turned off due to "static-mp4box" and zlib is explicitely turned off in configure, but it's still being used.

Probably caused by https://travis-ci.org/gpac/gpac/jobs/126308256#L152

**Comment by rbouqueau** [comment]
Well catched. Thank you :)

**Comment by rbouqueau** [comment]
That's really a travis issue. Taking the VM and reproducing the steps works fine :/

**Comment by wiiaboo** [comment]
Seems to be working fine with the last commit, no?

**Comment by rbouqueau** [comment]
Oh yeah that's right! Thanks @jeanlf :)
