### ISSUE TITLE
Delay in Live streaming !

### ISSUE THREAD

**Issue by irrz** [gpac/gpac#505]
Hello there,

Hope you are all fine and enjoying your time.

I am running the DashCast with HEVC codec, however while making live streaming I experience a delay of about 5 seconds!.
Is there any way to reduce this delay, although I am using a quite powerful machine as you can see in bellow:

 ​Streamer specifications:
RAM: 7.5 GB​
Processor Type​: Intel Xeon​
Processor Speed​: 3.40GHz x 8​
Operating System​: Linux Ubuntu-14.04 LTS 64-bit​

CLIENT​ Specifications:
RAM: 6 GB​
Processor Type​: Intel Core i5​
Processor Speed​: 1.70GHz 2.40​
Operating System​: Windows 8.1/ 10- 64-bit 
 ​
WebCam​ Specifications:
Producer​: HP​
Model​: HD 4310​
Resolution​: 1080p​

With my thanks to your cooperation in anticipation
- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by ulrichghislain** [comment]
Hello i need a help please , i'am a beginner on dashcast 
i have a stream mpeg2ts and i want to have a stream dashcast 
this is command that i'm typing
"DashCast -av udp://@239.x.x.x:1234?fifo_size=3000000 -live -seg-dur 8000 -mpd-refresh 8 -time-shift -1 -min-buffer 10 -npts -conf config_dashcast.conf -ast-offset 16000" then i just have a folder output empty (no chunk stream inside)

i get this error in command ---->"[mpegts @ 0x24561e0] Could not find codec parameters for stream 6 (Unknown: none ([5][0][0][0] / 0x0005)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options"

----->"Assertion desc failed at libswscale/swscale_internal.h:674

**Comment by jeanlf** [comment]
use the -low-delay flag this should prevent extra buffering by the video encoder
