### ISSUE TITLE
MP4Box -isma test if needed

### ISSUE THREAD

**Issue by 4getit** [gpac/gpac#506]
I am using the -isma option but there doesn't seem to be a way to find out if it's needed.
When I run MP4Box -isma the second time, it just starts to rewrite again.

Is there a way to find out (with -info ?) if -isma is needed or not?

**Comment by nguyen-viet-thanh-trung** [comment]
Hi,

When you use MP4Box -info with an encrypted file, we should have something like:
*Encrypted stream - ISMA scheme iAEC (version 1)
scheme location: urn:gpac:isma:encryption_scheme
KMS location: key in file
Selective Encryption: Yes

and your track type should be "vide:encv"

**Comment by nguyen-viet-thanh-trung** [comment]
Re-open if you need more info
