### ISSUE TITLE
MP4Client SIGSEGV at startup on Arch Linux

### ISSUE THREAD

**Issue by yan12125** [gpac/gpac#507]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

---

Just built against the latest commit b16f730. When starting MP4Client from command line, it throws segmentation fault. Here's some GDB outputs:

```
$ gdb /usr/bin/MP4Client
Reading symbols from /usr/bin/MP4Client...done.
(gdb) r
Starting program: /usr/bin/MP4Client 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Using config file in /home/yen/.gpac directory
System info: 7971 MB RAM - 4 cores
Modules Found : 35 
Loading GPAC Terminal
[New Thread 0x7ffff2552700 (LWP 9890)]
[Core] Plugin GPAC 2D Raster not found in 35 modules.

Thread 2 "MP4Client" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff2552700 (LWP 9890)]
0x00007ffff63be53d in XQueryExtension () from /usr/lib/libX11.so.6
(gdb) up
#1  0x00007ffff63b2352 in XInitExtension () from /usr/lib/libX11.so.6
(gdb) up
#2  0x00007ffff3f6938f in XextAddDisplay () from /usr/lib/libXext.so.6
(gdb) up
#3  0x00007ffff1945438 in XvUngrabPort () from /usr/lib/libXv.so.1
(gdb) up
#4  0x00007ffff1b4a6bf in X11_DestroyOverlay (xwin=0x7fffec0017c0) at x11_out.c:45
45          XvUngrabPort(xwin->display, xwin->xvport, CurrentTime );
(gdb) p xwin->display
$1 = (Display *) 0x0
(gdb) p xwin->xvport
$2 = 0
(gdb) 
```

Seems XvUngrabPort doesn't check whether display is NULL or not. Running under X11 using Xfce4. `$DISPLAY` set to `:0.0`.

Some related package versions:
libx11 1.6.3-1
libxext 1.3.3-1
libxv 1.0.10-1

**Comment by yan12125** [comment]
Not sure why, but c77fdae is working. Closing?

Some packages are upgraded since May:
libx11 1.6.4-1
libxext 1.3.3-1
libxv 1.0.11-1

**Comment by rbouqueau** [comment]
Ok for your information, we have a general task to ease distrib builds to work out of the box for our player. Some work has been done. I'm closing, please feel free to reopen if it occurs again.
