### ISSUE TITLE
 use new rate adaption algorithms in DASH player

### ISSUE THREAD

**Issue by AustinDGY** [gpac/gpac#508]
I would like to do some changes and adapt a new rate adaption algorithm in DASH player (OSMO4) in the GPAC framework, but I felt confused about how to do it. Is it enough to just read and modify the code in  gpac/src/media_tools/dash_client.c ? I would appreciate it a lot if anyone could give some instructions.

**Comment by rbouqueau** [comment]
Yes, the code is in dash_client.c.

I've started to move the code in the mpd_in module, so that rewriting an algorithm becomes easier: https://github.com/gpac/gpac/compare/master...rbouqueau:rateAdaptationCustom . There are still some layers to separate to finish this work.

**Comment by AustinDGY** [comment]
@rbouqueau 
Thanks a lot！
So at present, I have to read and understand the code in dash_client.c to adapt a new algorithm?

**Comment by rbouqueau** [comment]
Yes but only the parts that are changed in my previous link

**Comment by jeanlf** [comment]
also check the latest git that supports BBA and BOLA as examples
