### ISSUE TITLE
Cant install gpac 

### ISSUE THREAD

**Issue by Comandoraf** [gpac/gpac#509]
Hi,
Im tying to install gpac.
I downloaded the newest release from https://gpac.wp.mines-telecom.fr/downloads/
And I can't install it. I got error: Dependency is not satisfiable: libavcodec-extra-53 (>= 4:0.8-1~)
I have Ubuntu 15.04 32-bit

I cant add anty label to this issue... or I just dont know how

**Comment by rbouqueau** [comment]
The easiest on Linux seems to rebuild gpac yourself. Should take less than one hour:
http://gpac.io/2011/04/20/compiling-gpac-on-ubuntu/

We need to improve this part of the documentation.

> I cant add anty label to this issue... or I just dont know how

You can add labels on the column, right to this message.

Please close the issue when you are done. And don't hesitate to share your feedback :)

**Comment by Comandoraf** [comment]
I did what as you told and it works now. Thanks :) I have Labels locked - can't add any
