### ISSUE TITLE
MPD for single-file representation uses <SegmentBase> for media file and <RepresentationIndex> is broken because <SegmentBase> isn't a folder

### ISSUE THREAD

**Issue by brendanlong** [gpac/gpac#51]
Sorry for the long title. I created a MPD like this:

    MP4Box -dash 30000 ~/Videos/Lifting_Off_4K.ts ~/Videos/Lifting_Off.1080p.ts \
        ~/Videos/Lifting_Off.360p.ts -out lifting-off.mpd \
        -profile 'dashavc264:onDemand'

And it created 3 representations like this:

    <Representation id="1" mimeType="video/mp2t" width="3840" height="2160" audioSamplingRate="48000" codecs="avc1.640033,mp4a.40.02" startWithSAP="1" bandwidth="24527754">
     <BaseURL>Lifting_Off_4K_dash1.ts</BaseURL>
     <SegmentBase>
      <RepresentationIndex sourceURL="Lifting_Off_4K_dash.six"/>
     </SegmentBase>
    </Representation>

If I'm reading this correctly, the MPD is saying that the index is at `Lifting_Off_4K_dash1.ts/Lifting_Off_4K_dash.six`. I don't see any special cases for when `<BaseURL>` is a file, so I think MP4Box is wrong here.

**Comment by brendanlong** [comment]
The <SegmentBase> was also missing @presentationTimeOffset

**Comment by cconcolato** [comment]
According to RFC 3896 (see http://tools.ietf.org/html/rfc3986#section-5.2.3, last bullet point), the "merge" of the BaseURL element content and of the sourceURL attribute does not produce `Lifting_Off_4K_dash1.ts/Lifting_Off_4K_dash.six` but simply `Lifting_Off_4K_dash.six`. MP4Box is correct here I think.

**Comment by brendanlong** [comment]
You're right, thanks for pointing me to this.
