### ISSUE TITLE
Live streaming with unmux 264/aac can not work

### ISSUE THREAD

**Issue by SilviaJC** [gpac/gpac#510]
I have consulted on dash.js forum the question. Please see here: https://github.com/Dash-Industry-Forum/dash.js/issues/1385
I use ffmpeg receive streaming, output MP4 file(every 4 secs), then separate file, one is video encoded 264 (There will be multiple files for ABS, but now only test one video file), other is audio encoded aac (Lavf57.25.100). The first I only test video and only audio, they are working properly. However, when mix video and audio error occurred.

chrome ver: 49.0.2623.87 m
dash.js ver: 2.2
GPAC ver: 0.5, and latest 
System: centoOS Linux 32bits

My DASH commend line is: 
MP4Box -min-buffer 2000 -time-shift 10 -dash 2000 -frag 2000 -dash-live 2000 -mpd-refresh 4 -profile "dashavc264:live" -bs-switching no -rap -segment-name video/segment_ -out mpdtest.mpd MacrossDelta/MacrossDelta_audio_02.mp4#audio ff+box/MacrossDelta_1500k_02_N.mp4#video

MPD check on http://dashif.org/conformance.html
![image](https://cloud.githubusercontent.com/assets/19261628/15108089/8e6c3e5e-1606-11e6-8dc5-638030b94b6a.png)
MPD Download:
[chrome_console_log-2.txt](https://github.com/Dash-Industry-Forum/dash.js/files/256283/chrome_console_log-2.txt)
Chrome console log as follows:
[mpdtest_mpd.txt](https://github.com/Dash-Industry-Forum/dash.js/files/256285/mpdtest_mpd.txt)

Can't get next segment.
![image](https://cloud.githubusercontent.com/assets/19261628/15108044/453a5162-1606-11e6-864e-19fb798199c4.png)

If there is no clear description of anywhere, please let me know. I do not have enough knowledge confirmed this issue. Someone can give me some advice to try? or this is a known Issues?
Any help I will be very grateful, thank you.

**Comment by rbouqueau** [comment]
I am not sure to understand your question.

You can use MPEG DASH with raw elementary streams such as H264 and AAC.

However dash.js is a player editer by the DASH Industry Forum (DASH-IF). The DASH-IF writes recommendations/profiles for the industry on how to use MPEG-DASH to gain interoperability. The DASH-IF profiles mandates the use of the MP4 containers (hence forbids raw elementary streams).

**Comment by SilviaJC** [comment]
@rbouqueau I Know DASH-IF recommend using MP4 containers.
My question is how to use MP4Box with live commend that can play audio and video by one MPD.
The commend line occurred error on browser in my case.

- [x] play audio with live commend.
- [x] play video with live commend.
- [ ]  play audio + video with live commend.
- [x] play audio + video with onDemand commend.

**Comment by rbouqueau** [comment]
That's clearer.

> -dash 2000 -frag 2000 -dash-live 2000

Please leave the latest one only: -dash-live 2000
Other ones are redundant for what you're trying to do.

With my content here (from http://download.tsi.telecom-paristech.fr/gpac/DASH_CONFORMANCE/TelecomParisTech/sources/) it works here. Can you reproduce?

**Comment by SilviaJC** [comment]
@rbouqueau It can be reproduced. There are same error log and message when I leave command "-dash 2000 -frag 2000"

**Comment by rbouqueau** [comment]
> It can be reproduced

How? Please provide your command-line and source content (preferably from http://download.tsi.telecom-paristech.fr/gpac/DASH_CONFORMANCE/TelecomParisTech/sources/).

For full guidelines on bug filing: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by SilviaJC** [comment]
I use source content that you provided.
Command-line is: MP4Box -min-buffer 2000 -time-shift 10 -dash-live 2000 -mpd-refresh 4 -profile "dashavc264:live" -bs-switching no -out mpdtest.mpd GITHUB_GPAC_SAMPLE/counter_audio.mp4 GITHUB_GPAC_SAMPLE/counter_video_360.mp4

**Comment by rbouqueau** [comment]
I've just tried with MP4Client dans dash.js 2.1.1 + nightly in Chrome 50.0.2661.94 m and both work with your command-line. At this point, it is not a GPAC issue.
