### ISSUE TITLE
MP4Box: SegmentList XML Markdown node is not started correctly in DASH manifest

### ISSUE THREAD

**Issue by mariobla91** [gpac/gpac#511]
Hello,

I am running on FEDORA 23, 64bit and this GPAC version: 
MP4Box - GPAC version 0.6.2-DEV-rev455-gb16f730-master

Currently, I am trying to generate a DASH segments and manifest with byte ranges and segment timeline for duration of each segment. I will parse that .mpd file to create a .csv file with information needed for my system.
I am using this command:
`/usr/local/bin/MP4Box 
	-dash 1 
	-frag-rap 
	-no-frags-default 
	-segment-timeline 
	-tmp [...]/temp/ac4245ba-bdb8-48ca-a926-10a5495cdfc4 
	-out [...]/temp/ac4245ba-bdb8-48ca-a926-10a5495cdfc4/[filename]-video-timescaled_dash.mpd 
	[...]/temp/ac4245ba-bdb8-48ca-a926-10a5495cdfc4/[filename]-video-timescaled.mp4`

This generates this part of manifest file:
```xml
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.6.2-DEV-rev455-gb16f730-master  at 2016-05-12T06:49:51.925Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H6M52.181S" maxSegmentDuration="PT0H0M1.000S" profiles="urn:mpeg:dash:profile:full:2011">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>[...]/temp/ac4245ba-bdb8-48ca-a926-10a5495cdfc4/[filename]-video-timescaled_dash.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H6M52.181S">
  <AdaptationSet segmentAlignment="true" maxWidth="1280" maxHeight="720" maxFrameRate="25" par="16:9" lang="eng">
   <SegmentList timescale="1000"
    <SegmentTimeline>
     <S t="0" d="1021"/>
     <S d="1000" r="410"/>
     <S d="160"/>
    </SegmentTimeline>
   </SegmentList>
   <Representation id="1" mimeType="video/mp4" codecs="avc3.64001f" width="1280" height="720" frameRate="25" sar="1:1" startWithSAP="1" bandwidth="2102397">
    <BaseURL>[filename]-video-timescaled_dashinit.mp4</BaseURL>
    <SegmentList>
     <Initialization range="0-856"/>
      <SegmentURL mediaRange="857-409557" indexRange="857-900"/>
      <SegmentURL mediaRange="409558-896687" indexRange="409558-409601"/>
      <SegmentURL mediaRange="896688-1321282" indexRange="896688-896731"/>
      ...
      ...
	...
```

File looks like any other but there is a mistake: ```<SegmentList timescale="1000" ```. There is a missing character '>' at the end. That is why I get this error when parsing in Java:
<p>[Fatal Error] [filename]-video-timescaled_dash.mpd:11:5: Element type "SegmentList" must be followed by either attribute specifications, ">" or "/>".<br/>
Exception in thread "main" org.xml.sax.SAXParseException; systemId: file: [filename]-video-timescaled_dash.mpd; lineNumber: 11; columnNumber: 5; Element type "SegmentList" must be followed by either attribute specifications, ">" or "/>".<br/>
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)</p>

I have wrote all information I have. I am not very skilled with reporting issues, so if I did something wrong I apologize. 
I am looking for a way to fix this mistake as fast as possible, so if I can patch it quickly that would be an option, before a release fix comes. I might need help with patching this because I do not even know where to look for this bug in the code. 

Thank you very much for help.

**Comment by rbouqueau** [comment]
Thanks for reporting. Let me have a look

**Comment by rbouqueau** [comment]
Should be solved. Re-open otherwise.

FYI your command-line is incorrect: with ```-segment-timeline```, you must use ```-url-template``` (to enable templates) and then ```-segment-name``` including the ```$Time$``` token (to describe correct filenames).

You can find examples at http://www.gpac-licensing.com/2014/08/21/ibc-2014-dash-avc264-support-in-gpac/

**Comment by mariobla91** [comment]
Thank you for the help.

But it breaks my use-case. I want to produce one, single video file with all segments within it. And to have a dash manifest contain all information about how to extract every segment out. 
That is why I had timeline with without -segment-name because I don't want all those files but one big file that I can upload somewhere on remote data storage. With a information about byte ranges and timeline I can retrieve and stream it how ever I like.

I checked a link you provided, this section: On Demand processing (all profiles)
None of those commands provide me a solution I described up there.

Can you please assist me with finding a solution to this?

Thank you.

**Comment by rbouqueau** [comment]
It makes sense to use a single segment. We have an option to force it (```-single-segment```). But why not use an on-demand profile directly?

**Comment by mariobla91** [comment]
on-demand profile does not provide me with any information about duration, even with `-url-template` and `-segment-timeline`.

Ok, i have tried this: 
MP4Box -dash 1 -frag-rap -no-frags-default -url-template -segment-timeline -single-file
And this command produces everything in manifest as before. With timeline, and byte ranges.

I checked your commits, it looks like you fixed handling my wrong command. Great that you have but there is a still problem with dash manifest and XML format. `<SegmentList timescale="1000"` this line is missing '>' at the end. As I described before.

I can not reopen this issue because GitLab does not allow to reopen if contributor closes. And I cannot put any tags on the issue, I think can't either because the right column is read-only.

Thank you very much for patience and assistance.

**Comment by rbouqueau** [comment]
Could you please share your full command-line?

> With timeline, and byte ranges.

This information is also contained in the 'sidx' box. Could you provide me with a use-case where the player would also need this information at the manifest level? How would it parse both the timeline and the ranges? (I think I'm missing something here)

> ```-dash 1```

This value is in ms so I assume you mean 1000.

**Comment by mariobla91** [comment]
This is a full command:
`/usr/local/bin/MP4Box -dash 1 -frag-rap -no-frags-default -url-template -segment-timeline -single-file -tmp [...]/temp/2d9753ca-4b74-450a-b283-434d65fb6c95 -out [...]/temp/2d9753ca-4b74-450a-b283-434d65fb6c95/[filename]-video-timescaled_dash.mpd [...]/temp/2d9753ca-4b74-450a-b283-434d65fb6c95/[filename]-video-timescaled.mp4`

I am currently only parsing manifest file to output timeline and byte range. Because I will upload a generated file (.mp4) to some network file storage (NFS) and parse timeline and byte range to be able to fetch a single segment from NFS.

`dash 1` is because I want to segment a file on IDR frame. And in the combination with `-frag-rap` I am doing that. I don't see why would DASH segment files on a given time, 1 or 5 sec, because it is not always encoded that way so mistakes on decoding are too big.

**Comment by rbouqueau** [comment]
Why do you need DASH then? With a progressive downloadable MP4, you download the beginning of the file and then you get the list of frames, RAPs, offsets and whatever you need for each track. Execute ```MP4Box -diso source.mp4``` and look at the resulting XML.

**Comment by rbouqueau** [comment]
@jeanlf do you remember what this block is for? https://github.com/gpac/gpac/blob/45d4f1f18c01768344efdd632d637c7d23c5d154/src/media_tools/dash_segmenter.c#L2192

```mpd_timeline_bs``` contains a full element so the resulting MPD is not XML-compliant.

Thanks.

**Comment by mariobla91** [comment]
I will reconstruct my parsed output on another service (microservices) that will support DASH and HLS. :) 

Thank you for all the help. But actually that XML problem is my main concern here.

**Comment by mariobla91** [comment]
Any update on the XML problem ? 

Thank you.

**Comment by rbouqueau** [comment]
The XML problem is a side-effect. Give us some time to think about the design of exposing several segment listing patterns in the MPD. Of course any input in the meantime is warmly welcome.

**Comment by mariobla91** [comment]
Oh, I see. Is there any way I can get segment duration and byte ranges for each segment using other commands, instead of this that combines different segment listings. 
Any kind of output will work for me :)
Thank you

**Comment by Fell-x27** [comment]
MP4Box - GPAC version 0.7.0-rev1516-gbd5c9af-master
Problem still exists.
