### ISSUE TITLE
How to set a customized buffer length when playing DASH contents using GPAC player ?

### ISSUE THREAD

**Issue by AustinDGY** [gpac/gpac#514]
When playing DASH contents , I  noticed in the statistics window that the player has a bufferlength about maybe 6 second, which I think is some kinds of short, and  I want to try some longger buffer length.(I did't mean the buffer to be filled before starting decoding which can be set in the GPAC configuration documentation ).  How can I make this happen? 
Thanks a lot！

**Comment by rbouqueau** [comment]
May #411 help?

**Comment by AustinDGY** [comment]
@rbouqueau Yes，thanks a lot.
