### ISSUE TITLE
Dynamic DASH content doesn't work properly

### ISSUE THREAD

**Issue by Comandoraf** [gpac/gpac#516]
System info:
- Ubuntu 15.04 32-bit
- GPAC version 0.6.2-DEV-rev455-gb16f730-master

Im trying to generate dash live dynamic content. First of all MP4Box with dash works fine for this MP4Box -dash 2000 -out stream.mpd ~/Downloads/awakens.mp4
and
MP4Box -dash 2000 -profile live -out stream.mpd ~/Downloads/awakens.mp4#video ~/Downloads/awakens.mp4#audio
It doesn't work for switch -dynamic and for -dash-live. 
MP4Box -dash-live 2000 -mpd-refresh 2.0 -out stream.mpd ~/Downloads/awakens.mp4#video ~/Downloads/awakens.mp4#audio

When im trying to play mpd file with MP4Client there are lags of video and after lag it goes faster(there is no leak of frames and audio goes normal) - and then, because of video's lags video and audio are not synchronized at all. After end of audio (not video) there is info:
```
[IsoMedia] Error opening new segment awakens_dash_track1_78.m4s at UTC 1463145252527: Requested URL is not valid or cannot be found
[IsoMedia] Error opening new segment awakens_dash_track2_73.m4s at UTC 1463145252883: Requested URL is not valid or cannot be found
[IsoMedia] Error opening new segment awakens_dash_track2_74.m4s at UTC 1463145252917: Requested URL is not valid or cannot be found
[IsoMedia] Error opening new segment awakens_dash_track2_75.m4s at UTC 1463145253528: Requested URL is not valid or cannot be found
[IsoMedia] Error opening new segment awakens_dash_track2_76.m4s at UTC 1463145254027: Requested URL is not valid or cannot be found
```

**Comment by rbouqueau** [comment]
Did you check about keyframe alignment? (you downloaded the file from youtube, right?)
https://gpac.wp.mines-telecom.fr/2015/11/02/check-key-frame-alignment-with-mp4box/

**Comment by Comandoraf** [comment]
Thanks a lot it works now. For others: http://www.gpac-licensing.com/2014/11/03/bitmovin-leverage-mp4box-package-contents-bitdash-player/
