### ISSUE TITLE
Initialization element missing from MP4Box-generated manifest

### ISSUE THREAD

**Issue by wosmond** [gpac/gpac#524]
I'm encountering a strange issue that is certainly user error, but I can't find the cause. I have generated what should be a DASH-compatible file using FFmpeg, but when I run it through the MP4Box to segment the mp4 and generate the manifest, the resulting .mpd doesn't have an Initialization element in the AdaptationSet. The resulting manifest doesn't play in my test environment, but when I add the Initialization element manually then it works. What's particularly puzzling to me is that this used to work, and as I'm using the Debian-packaged version of gpac (with MP4Box version 0.5.1-DEV-rev5324) the application itself hasn't changed since the last time I did this successfully.

The above would indicate to me that there is some problem with the source file that results in MP4Box not seeing some expected data in the source file and that being the cause of the missing Initialization element, but I'm not sure what kind of data that would be, or why the file would magically work if I put the element in manually.

The specific command I'm using to generate the manifest is:

`MP4Box -dash 1000 -rap -frag-rap -profile onDemand -mpd-title test -out manifest.mpd transcoded.mp4`

If this is the wrong location for user help-type questions let me know, the sourceforge forums directed me here.

**Comment by rbouqueau** [comment]
Hi, could you please post enough information for us to reproduce? Like a sample file and both MPDs (correct and incorrect).

In case you didn't try it, please use the latest GPAC version. It is easy to build: http://gpac.io/2015/07/29/gpac-build-mp4box-only-all-platforms/ (binaries at https://gpac.io/downloads/gpac-nightly-builds/)

**Comment by rbouqueau** [comment]
Please re-open when providing information to reproduce.
