### ISSUE TITLE
[Android] Stream freeze at seemingly random times.

### ISSUE THREAD

**Issue by canatella** [gpac/gpac#53]
When playing a stream on Android, it freezes after some time for about 30 seconds then starts again. I cannot reproduce it on PC and I cannot reproduce it on the Osmo4Android build because of issue 46. It might be a kind of race condition as it's harder to reproduce when activating logs and easier to reproduce with  GF_TERM_NO_DECODER_THREAD. Note that on Android, its using GF_TERM_NO_COMPOSITOR_THREAD as its the jvm thread that's doing the blitting. 

 Here are links to two traces: https://www.dropbox.com/s/3v0kvv4y6lfxsx5/gpac-log-before.gz?dl=0, https://www.dropbox.com/s/yl1dm2kp938ikvb/gpac-log-after.gz?dl=0. In the before trace, at the end the problem is happening. You can see that there are no more ffmpeg decoder traces. In the after traces the first ffmpeg traces are where the stream started playing again.

**Comment by nguyen-viet-thanh-trung** [comment]
fixed now !
