### ISSUE TITLE
Dialog Failure with remote peer

### ISSUE THREAD

**Issue by Erkanos** [gpac/gpac#530]
Hello,
This is the first time i'm using GPAC, lastest version on Windows x86. The command line i have used is:
`mp4client.exe C:\60719414.mpd`

This is the error reported:
`[HTTP] Error parsing reply: Dialog Failure with remote peer for URL http://ss-dash.site.com:80/111/11111111/60719414.ism/QualityLevels(437668,id=NUM)/Fragments(video=i)?expire=NUM&path_depth=3&token=NUM
[DASH] FAILED to download http://ss-dash.site.com/111/11111111/60719414.ism/QualityLevels(437668,id=NUM)/Fragments(video=i)?expire=NUM&path
_depth=3&token=NUM = Dialog Failure with remote peer...Cannot open C:\60719414.mpd: Dialog Failure with remote peer`
The strange thing i see is **video=i**, is not wrong? I think it must be something like video=123456789? My only objective is use mp4client for see the video instead of the browser, if is possible and not violate any rules or copyright. Inside the MPD the info about the site that i have removed from this post

Thanks

File: "MPD Test" uploaded today on mediafire, name of the file is 60719414.mpd

Complete log
`mp4client.exe -logs media@debug C:\60719414.mpd`

`System info: 2047 MB RAM - 1 cores
Modules Found : 32
Loading GPAC Terminal
[Terminal] Creating terminal
[Terminal] compositor loaded
[Terminal] downloader loaded
[Terminal] Terminal created - loading config
Terminal Loaded in 141 ms
Opening URL C:\60719414.mpd
[Terminal] Connecting to C:\60719414.mpd
[Terminal] Creating new root scene
[Terminal] root scene created
[Terminal] Looking for plugin for URL C:\60719414.mpd
[Terminal] No mime type found - checking by extension mpd
[Terminal] Trying module[54]=GPAC MPD Loader, mime=application/dash+xml
[Terminal] Found input plugin GPAC MPD Loader for URL C:\60719414.mpd (no mime type)
[HTTP] Error parsing reply: Dialog Failure with remote peer for URL
[DASH] FAILED to download = Dialog Failure with remote peer...
[Terminal] Service connection ACK received from C:\60719414.mpd - Dialog Failure with remote peer
Cannot open C:\60719414.mpd: Dialog Failure with remote peer`

Inside the MPD both option are true
`segmentAlignment="true" bitstreamSwitching="true"`

**Comment by rbouqueau** [comment]
The content is conformant.

@jeanlf there is a deadlock also, may I ask you to have a look?

**Comment by jeanlf** [comment]
reply is a 400 bad request (now logged to stderr by default on last git). Your segment urls  use query parameters which are very likely authentication tokens (expire= and token=), I guess the token are not valid for your session; in any case it's not possible to debug by just using the MPD, authentication has to be done just before processing the mpd ...

"video=i" is the init segment in your MPD

CLosing, as I don't think there is any issue with GPAC here, it's an issue of authentication rather than MPD processing. Re-open if you have more info/tools to test this
