### ISSUE TITLE
Add emsg box to mp4

### ISSUE THREAD

**Issue by Comandoraf** [gpac/gpac#531]
Hi,
Is there a possibility to add emsg box to mp4 as specified in dash specification using MP4Box?
I see, that I can use -set-meta and -add-meta, but this is "meta" box type. I want to add data to emsg box type

**Comment by rbouqueau** [comment]
That's planned. If I implemented it, would you have a test use-case?

**Comment by Comandoraf** [comment]
Sure, are you already working on it? When it could be ready?

**Comment by rbouqueau** [comment]
I'd like it to be ready for the GPAC 0.7.0 release this summer.

Please provide your use-case if you wish to accelerate the development.

**Comment by ulrichghislain** [comment]
Hello i need a help please , i'am a beginner on dashcast 
i have a stream mpeg2ts and i want to have a stream dashcast 
this is command that i'm typing
"DashCast -av udp://@239.x.x.x:1234?fifo_size=3000000 -live -seg-dur 8000 -mpd-refresh 8 -time-shift -1 -min-buffer 10 -npts -conf config_dashcast.conf -ast-offset 16000" then i just have a folder output empty (no chunk stream inside)

i get this error in command ---->"[mpegts @ 0x24561e0] Could not find codec parameters for stream 6 (Unknown: none ([5][0][0][0] / 0x0005)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options"

----->"Assertion desc failed at libswscale/swscale_internal.h:674

**Comment by jeanlf** [comment]
No, this needs further investigation. What kind of info do we want to pass to emsg (DASH only, user-defined, schemeid, etc), would we insert that info at each generated segment (eg timing and duration of events), ...
Also note that it is quite simple to prepend on the fly an emsg box of your liking to any segment, and you can use [-bin](https://github.com/gpac/gpac/wiki/mp4box-dump-opts) and GPAC [binary XML](https://github.com/gpac/gpac/wiki/NHML-Format#the-nhml-file-format) to produce them.

Once we have more feedback on people's needs with emsg and GPAC, we could start working on that. Closing until then, feel free to re-open.
