### ISSUE TITLE
Still no support for VC-1 and DTS

### ISSUE THREAD

**Issue by filler56789** [gpac/gpac#536]
Both L-Smash and ffmpeg can mux VC-1 video and DTS audio into MP4 "since ages ago". ¿Is it so hard to adapt their source-code to the GPAC framework?

**Comment by rbouqueau** [comment]
I do have some code for DTS that's pretty complete and it should indeed be included in GPAC or as an external library.

For VC-1, I'll let other contributors and users have their say. What is your practical use-case for VC-1 in MP4?

**Comment by filler56789** [comment]
Thanks for making clear that the GPAC team does not want to add support for VC-1 and DTS.

https://sourceforge.net/p/gpac/discussion/287546/thread/43881fa9/

and

http://forum.doom9.org/showthread.php?p=1735121#post1735121

**Comment by rbouqueau** [comment]
I do have some code for DTS that's pretty complete and it should indeed be included in GPAC or as an external library.

For VC-1, I'll let other contributors and users have their say. What is your practical use-case for VC-1 in MP4?

**Comment by cconcolato** [comment]
@filler56789 The GPAC team never said it does not want to add support for new codecs. As indicated in the SourceForge thread, our time is limited. We add what we need, or what is requested when we have time. Some complain that we added HEVC support instead of VC-1. We had funding to add HEVC, not for VC-1 (yet?). If any one provides a PR for VC-1 or any other codec, we'd be happy to merge! Remember GPAC is open-source and free!

**Comment by filler56789** [comment]
cconcolato wrote:

**The GPAC team never said it does not want to add support for new codecs.**

And so what? No matter what one says or does not say, because actions and behaviors speak louder than words.

rbouqueau wrote:

**What is your practical use-case for VC-1 in MP4?**

what was YOUR "practical use" for MPEG-4 ASP in MP4?

what was YOUR "practical use" for MPEG-1 and MPEG-2 video in MP4?

what was YOUR "practical use" for OBSCURE audio formats such as AMR, EVRC and SMV?

Last but not least: why didn't you go ask that same question to the FFmpeg team?

**Comment by jeanlf** [comment]
I wonder why we didn't close that one sooner. Ah yes I remember, waiting for apologies...

**Comment by filler56789** [comment]
_jeanlf wrote:_

> I wonder why we didn't close that one sooner.

MY ANSWER: because you and your GPAC friends are just a bunch of lazy idiots, sophists and liars.
