### ISSUE TITLE
DashCast starts stream but does not create MPD file.

### ISSUE THREAD

**Issue by AlexJuca** [gpac/gpac#538]
I tried using the following command to stream video from my webcam and simultaneously create an mpd that I can use to visualize the stream on a webpage with shaka player.

DashCast -vf video4linux2 -vres 640x480 -vfr 10 v4l2f mjpeg -v /dev/video0 -af alsa -seg-dur 500 -live -out tmp/ -mpd tmp/test_dash.mpd

Here are the logs. 

MPD refresh time not set in live - defaulting to segment duration Options:     video source: /dev/video0     video format: video4linux2     v4l2 format: mjpeg     video framerate: 24     video resolution: 640x480     video crop: 0x0     audio source:      audio format: alsa Configurations:     id:v1	res:640x480	vbr:1000000     id:a1	abr:192000 [video4linux2 @ 0xc9b160] The driver changed the time per frame from 1/24 to 1/30 [mjpeg @ 0xc9d780] overread 8 [video4linux2 @ 0xc9b160] Estimating duration from bitrate, this may be inaccurate Input #0, video4linux2, from '/dev/video0':   Duration: N/A, start: 4999.963121, bitrate: N/A     Stream #0.0: Video: mjpeg, yuvj422p, 640x480, -5 kb/s, 1000k tbn, 30 tbc AVCTX give frame duration of 1/30 - keeping requested rate 24, but this may result in unexpected behaviour. [mjpeg @ 0xc9d780] overread 8 [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame [dashcast] Live system dropped a video frame

Am I doing anything wrong?

**Comment by ulrichghislain** [comment]
Hello i need a help please , i'am a beginner on dashcast 
i have a stream mpeg2ts and i want to have a stream dashcast 
this is command that i'm typing
"DashCast -av udp://@239.x.x.x:1234?fifo_size=3000000 -live -seg-dur 8000 -mpd-refresh 8 -time-shift -1 -min-buffer 10 -npts -conf config_dashcast.conf -ast-offset 16000" then i just have a folder output empty (no chunk stream inside)

i get this error in command ---->"[mpegts @ 0x24561e0] Could not find codec parameters for stream 6 (Unknown: none ([5][0][0][0] / 0x0005)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options"

----->"Assertion desc failed at libswscale/swscale_internal.h:674

**Comment by alon21034** [comment]
I had the same problem, too. I used DashCast to process a RTSP stream from a IP cam, and the MPD file was not generated automatically.

After some efforts, I found that its because the audio data from the IP cam was somehow wrong. I commented the codes related to audio, such as `audio_data_conf.filename`, in `dc_write_mpd` in `controler.c`. Then the MPD file is generated and works well.

I'm not sure there are some bugs in dashcast or just because of the problem of the IP cam.

**Comment by DF9TS** [comment]
In my case: 
Dashcast does not produce .mpd files, although .mpd file creation is stated in Dashcast screen log (see below). m4s files and v1_init_gpac.mp4 are created as expected.

Disclaimer: I am new to Dashcast. I tried to follow GPAC website instructions to the point. Apologies in case this is not a bug but an operating mistake on my side

**=== Environment**

- Computer is Quad i7-6500HQ 12GB RAM
- I am using Dashcast and MP4Box compiled from github on July 21 2016.
- I compiled GPAC and Dashcast exactly as stated on GPAC web site
- ... but had to use libavcodec-extra-56 (-extra-53 not in Debian Jessie)
- OS is a Linux Debian Jessie, fresh build from July 20 2016, running in Virtualbox 5.1.0 r108711
- MP4Box  and Dashcast version:  GPAC version 0.6.2-DEV-rev673-gcf249c1-master

**=== Content preparation**

- Content was taken from 
http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_2160p_60fps_normal.mp4

- Transcoding with x264, x264 from Debian Jessie, version  2:0.142.2431+gita5831aa-1+b2
- x264 command line:
x264 --output intermediate_2400k.264 --fps 30 --preset slow --bitrate 4000 --vbv-maxrate 4000 --vbv-bufsize 4000 --min-keyint 30 --keyint 30 --scenecut 0 --no-scenecut --pass 1 --video-filter "resize:width=1280,height=720" bbb_sunflower_2160p_60fps_normal.mp4 

- Muxing with MP4Box, no audio track

- MP4Box command line:
MP4Box -add /media/win10/kodi.tv/d1/intermediate_2400k.264 -fps 30 /media/win10/kodi.tv/d1/bbb_sunflower_720p_30fps_3500kbps_normal.mp4 
Created file plays ok in MP4Client

**=== Dashcast**

- Dashcast Command line:
DashCast -v bbb_sunflower_720p_60fps_4000kbps_normal.mp4 -seg-dur 500 -live-media -out output -mpd bbb.mpd

- Output on Terminal when starting Dashcast indicates .mpd files are created:

gerd@debian:~/dashcast$ DashCast -v /media/win10/kodi.tv/d1/bbb_sunflower_720p_60fps_4000kbps_normal.mp4 -seg-dur 500 -live-media -out output -mpd bbb.mpd
Options:
    video source: /media/win10/kodi.tv/d1/bbb_sunflower_720p_60fps_4000kbps_normal.mp4
    video crop: 0x0
    audio source: 
Configurations:
    id:v1	res:640x480	vbr:1000000
    id:a1	abr:192000
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/media/win10/kodi.tv/d1/bbb_sunflower_720p_60fps_4000kbps_normal.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isomavc1
    creation_time   : 2016-07-21 08:48:20
  Duration: 00:10:34.53, start: 0.000000, bitrate: 7884 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 3936 kb/s, 60 fps, 60 tbr, 60k tbn, 120 tbc (default)
    Metadata:
      creation_time   : 2016-07-21 08:48:20
      handler_name    : 264@GPAC0.6.2-DEV-rev673-gcf249c1-master
    Stream #0:1(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 3936 kb/s, 60 fps, 60 tbr, 60k tbn, 120 tbc (default)
    Metadata:
      creation_time   : 2016-07-21 11:56:01
      handler_name    : 264@GPAC0.6.2-DEV-rev673-gcf249c1-master
AVCTX give frame duration of 1/120 - keeping requested rate -1, but this may result in unexpected behaviour.
[libx264 @ 0xb1f004a0] using SAR=1/1
[libx264 @ 0xb1f004a0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX LZCNT
Press q or Q to exit...
[libx264 @ 0xb1f004a0] profile High, level 3.1
[libx264 @ 0xb1f004a0] 264 - core 142 r2431 a5831aa - H.264/MPEG-4 AVC codec - Copyleft 2003-2014 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=4 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=60 keyint_min=6 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=1000 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Generating MPD at 2016-07-21T12:36:37.068Z
StartTime: 2016-07-21T12:36:37.068Z - startNumber 1 - last number 1
[video_encoder] Rep v1 UTC diff 1270 bigger than segment duration 0 - some frame where probably lost. Adjusting
Generating MPD at 2016-07-21T12:36:37.068Z
StartTime: 2016-07-21T12:36:37.068Z - startNumber 1 - last number 1
Generating MPD at 2016-07-21T12:36:38.338Z
StartTime: 2016-07-21T12:36:37.068Z - startNumber 1 - last number 3
Generating MPD at 2016-07-21T12:36:38.355Z
StartTime: 2016-07-21T12:36:37.068Z - startNumber 1 - last number 4
Generating MPD at 2016-07-21T12:36:39.304Z
StartTime: 2016-07-21T12:36:37.068Z - startNumber 1 - last number 5
Generating MPD at 2016-07-21T12:36:39.837Z
StartTime: 2016-07-21T12:36:37.068Z - startNumber 1 - last number 6
Generating MPD at 2016-07-21T12:36:40.337Z
StartTime: 2016-07-21T12:36:37.068Z - startNumber 1 - last number 7
Generating MPD at 2016-07-21T12:36:40.813Z
StartTime: 2016-07-21T12:36:37.068Z - startNumber 1 - last number 8

# But no such .mpd files can be found in output directory:

gerd@debian:~/dashcast$ ls output
v1_100_gpac.m4s  v1_11_gpac.m4s  v1_18_gpac.m4s  v1_31_gpac.m4s  v1_6_gpac.m4s   v1_82_gpac.m4s  v1_88_gpac.m4s  v1_93_gpac.m4s  v1_99_gpac.m4s
v1_101_gpac.m4s  v1_13_gpac.m4s  v1_19_gpac.m4s  v1_37_gpac.m4s  v1_78_gpac.m4s  v1_83_gpac.m4s  v1_89_gpac.m4s  v1_94_gpac.m4s  v1_9_gpac.m4s
v1_102_gpac.m4s  v1_14_gpac.m4s  v1_1_gpac.m4s   v1_3_gpac.m4s   v1_79_gpac.m4s  v1_84_gpac.m4s  v1_8_gpac.m4s   v1_95_gpac.m4s  v1_init_gpac.mp4
v1_103_gpac.m4s  v1_15_gpac.m4s  v1_20_gpac.m4s  v1_41_gpac.m4s  v1_7_gpac.m4s   v1_85_gpac.m4s  v1_90_gpac.m4s  v1_96_gpac.m4s
v1_104_gpac.m4s  v1_16_gpac.m4s  v1_21_gpac.m4s  v1_4_gpac.m4s   v1_80_gpac.m4s  v1_86_gpac.m4s  v1_91_gpac.m4s  v1_97_gpac.m4s
v1_10_gpac.m4s   v1_17_gpac.m4s  v1_22_gpac.m4s  v1_5_gpac.m4s   v1_81_gpac.m4s  v1_87_gpac.m4s  v1_92_gpac.m4s  v1_98_gpac.m4s

**Comment by Victordmdb** [comment]
I'm getting the same issue. I can see an output but no mpd file, why is it not being created?

**Comment by mindole** [comment]
I have been getting the same issue.
I am using the latest GPAC version :  0.6.2-DEV-rev681-g32e98cd-master

When I execute the command below, Only v1_init_gpac.mp4 and .m4s files are generated.
But, no mpd file created.

# DashCast -v Animation.mp4 -vres 640x480 -vfr 25 -live-media -low-delay -frag 200 -insert-utc -seg-marker eods -min-buffer 0.2 -pixf yuv420p -mpd dashcast.mpd
Options:
    video source: Animation.mp4
    video framerate: 25
    video resolution: 640x480
    video crop: 0x0
    audio source: 
Configurations:
    id:v1       res:640x480     vbr:800000
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Animation.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2013-07-22 13:38:40
  Duration: 00:01:22.50, start: 0.000000, bitrate: 434 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 640x358, 335 kb/s, 25 fps, 25 tbr, 50 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 95 kb/s (default)
    Metadata:
      creation_time   : 2013-07-22 13:38:42
      handler_name    : IsoMedia File Produced by Google, 5-11-2011
AVCTX give frame duration of 1/50 - keeping requested rate 25, but this may result in unexpected behaviour.
[libx264 @ 0x7fcbd4000920] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
Press q or Q to exit...
[libx264 @ 0x7fcbd4000920] profile Constrained Baseline, level 3.0
[libx264 @ 0x7fcbd4000920] 264 - core 148 r2643 5c65704 - H.264/MPEG-4 AVC codec - Copyleft 2003-2015 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=7 lookahead_threads=7 sliced_threads=1 slices=7 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=25 keyint_min=2 scenecut=0 intra_refresh=0 rc=abr mbtree=0 bitrate=800 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
Generating MPD at 2016-08-10T03:19:32.771Z
StartTime: 2016-08-10T03:19:32.771Z - startNumber 1 - last number 1
Generating MPD at 2016-08-10T03:19:32.771Z
StartTime: 2016-08-10T03:19:32.771Z - startNumber 1 - last number 1
Generating MPD at 2016-08-10T03:19:33.726Z
StartTime: 2016-08-10T03:19:32.771Z - startNumber 1 - last number 2
Generating MPD at 2016-08-10T03:19:34.728Z
StartTime: 2016-08-10T03:19:32.771Z - startNumber 1 - last number 3
Generating MPD at 2016-08-10T03:19:35.726Z
StartTime: 2016-08-10T03:19:32.771Z - startNumber 1 - last number 4
Generating MPD at 2016-08-10T03:19:36.726Z
StartTime: 2016-08-10T03:19:32.771Z - startNumber 1 - last number 5
Generating MPD at 2016-08-10T03:19:37.726Z
StartTime: 2016-08-10T03:19:32.771Z - startNumber 1 - last number 6
Generating MPD at 2016-08-10T03:19:38.725Z
StartTime: 2016-08-10T03:19:32.771Z - startNumber 1 - last number 7
Generating MPD at 2016-08-10T03:19:39.728Z
StartTime: 2016-08-10T03:19:32.771Z - startNumber 1 - last number 8
Generating MPD at 2016-08-10T03:19:40.726Z

**Comment by Victordmdb** [comment]
I think I figured out the cause of the issue.  If you go into controler.c, into the dc_write_mpd function, comment out this line:
 if (!audio_data_conf) return;

It seems to not have a purpose at this time. So remove and recompile that file with gcc

**Comment by mindole** [comment]
Thanks to your comment, this problem was solved out..

**Comment by Victordmdb** [comment]
Good to know @mindole! How are you reading the mpd stream btw? I set up a simple html page with dashjs player on a python simplehttpserver, but i can't seem to get anything out of it

**Comment by jeanlf** [comment]
Thanks for the report, now patched on git
