### ISSUE TITLE
Problem with merge tracks.

### ISSUE THREAD

**Issue by Jamaika1** [gpac/gpac#539]
I am referring to merge video tracks, audio and subtitles. (function -catx)
_mp4box.exe -mpeg4 -add video1.h265:xps_inband:noedit:trailing:name= -add audio1.aac:name= -add subtitle_all.ttxt:disable:name="No color, font, display flags in the LAVFilters" -catx "video2.h265 +audio2.aac" -catx "videoX.h265 +audioX.aac" output.mp4_
How to make time was counted relative to the video track and not on the longest track? Is there such a function?
http://i64.tinypic.com/2h4mjih.jpg
Interestingly, chapters no problem time.
Do all {:X} functions track -add need to save to the -catx?
Does function {:xps_inband} always changing codec with hvc1 to hev1?
Maybe a silly question. Is MP4Box supports crafted files h264/h265 Matroska?

**Comment by jeanlf** [comment]
sorry reformulate, not sure what you mean here
