### ISSUE TITLE
[HLS/DASH] How to avoid displaying audio only representation

### ISSUE THREAD

**Issue by canatella** [gpac/gpac#54]
Hello,

When starting with the minimum bandwidth representation, GPAC plays the audio stream only. I'd like it to start with the minimum bandwidth repersentation with both audio _and_ video. I know about GF_NET_SERVICE_QUALITY_QUERY and GF_NET_SERVICE_QUALITY_SWITCH command but when can I call them ? Also how to detect which representation is the one with lowest bandwidth and both audio and video ? And finally, how to make sure that if bandwidth decrease, GPAC won't switch to the audio only representation ? It seems that for my streams, the quality_ranking is always 0.

Thanks!

**Comment by rbouqueau** [comment]
The issue is mainly to start with the lowest quality. In this case, it would be great to look for the presence of audio. What do you think?
