### ISSUE TITLE
How to do live dash streaming with small ts files (Every 10 seconds,I have one more ts files)?

### ISSUE THREAD

**Issue by hanyufeng520** [gpac/gpac#542]
Hello, I am a new guy of gpac, and my question is 
1.I have many small ts files which contains H264 and AAC codec data
2.Every 10 seconds ,I have one more ts files.

I want to streaming these ts files to implement live streaming, how to use gpac to achieve my goal ? 

Hope to get your answers.Thanks very much.

**Comment by rbouqueau** [comment]
We have a project that does exactly that: HLS to DASH. https://github.com/gpac/node-gpac-dash

**Comment by hanyufeng520** [comment]
@rbouqueau Very thanks for your answers.But I need to push my dash to another web server.So could you help to check my commands.
The first 24 seconds: I have -0.ts
MP4Box -dash 24000.00 -dash-ctx ctx.txt -profile live -0.ts:period=P1 -out test.mpd

The second 24s: I have -1.ts
MP4Box -dash 24000.00 -dash-ctx ctx.txt -profile live -1.ts:period=P2 -out test.mpd

at this time I use mp4client to open the stream 
 MP4Client http://localhost/live/test.mpd

The third 24s: I have -2.ts
MP4Box -dash 24000.00 -dash-ctx ctx.txt -profile live -2.ts:period=P3 -out test.mpd

The fouth 24s: I have -3.ts
MP4Box -dash 24000.00 -dash-ctx ctx.txt -profile live -3.ts:period=P4 -out test.mpd


I find the mp4client  stopped and just played the first and the seconds 24s' content.
It means the MP4Client just played 48s and don't continue to play.

So the question is why the MP4Client don't play the third and the fourth 24s' content ?I used the wrong command or something else ?

Could you give me some suggestions about this problem ?Thank you very much.

**Comment by rbouqueau** [comment]
I am not sure to have understood your initial request. Why don't you stream the ts directly?

**Comment by hanyufeng520** [comment]
@rbouqueau  Because I used HLS before.So it works.And now ,I need to use mpeg-dash.
So I gernerate the ts files every  10 seconds.When I have one ts file,I use MP4Box to dash it,and start the client to watch the stream, and later when I have one more file ,I use mp4box to dash the seconds ts file again(the MP4Box will also update the mpd file,right?). 

So the target is I just start the client only once after the first ts file dashed with mp4box, and later I only use MP4Box to dash the second/third... files,  and the client can always playing .

**Comment by rbouqueau** [comment]
Which client do you use to "start the stream"?

Also what does "But I need to push my dash to another web server." mean? What prevents you from using https://github.com/gpac/node-gpac-dash for your need?

**Comment by hanyufeng520** [comment]
@rbouqueau Thanks for you fast reply.

Also what does "But I need to push my dash to another web server." mean? What prevents you from using https://github.com/gpac/node-gpac-dash for your need?

I means I need to push my files to another web-server,it's appache.

Which client do you use to "start the stream"?
I use MP4Client with the command  only once in the windows command widow : MP4client http://localhost/live/test.mpd .

OK.Let me introduce my problem again.
I have capture card which will provide one frame and audio every 33.3 ms (My format is P30).

The video will be encoded as H264 and save it to file when i have 24 seconds,it means if I have 24*1000/33.3 = 720 frames I need to store these frames to file let's call it 1.h264. Also every 24 seconds, I aslo store the audio which will be encoded as AAC data ,I save these aac data to file , let's call it 1.aac.

When I have 1.h264 and 1.aac , I use ffmpeg to mutex them as 1.ts file then I use MP4Box with the command :

MP4Box  -dash-ctx  DASH.txt -dash 10000 -profile live -segment-ext mp4 -out tetst.mpd -add 1.ts -fps 30 DASH.mp4

when I have 2.h264 and 2.aac , I use ffmpeg to mutex them as 2.ts  I use MP4Box with the command again:

MP4Box  -dash-ctx  DASH.txt -dash 24000 -profile live -segment-ext mp4 -out tetst.mpd -add 2.ts -fps 30 DASH.mp4

when I have 3.h264 and 3.aac , I use ffmpeg to mutex them as 3.ts  I use MP4Box with the command again:

MP4Box  -dash-ctx  DASH.txt -dash 24000 -profile live -segment-ext mp4 -out tetst.mpd -add 3.ts -fps 30 DASH.mp4

Let's image that : I've dashed 3 files, so I have 24*3 = 72s video now. I start the mp4client with the command :MP4client http://localhost/live/test.mpd .

when I have 4.h264 and 4.aac , I use ffmpeg to mutex them as 4.ts  I use MP4Box with the command again:

MP4Box  -dash-ctx  DASH.txt -dash 24000 -profile live -segment-ext mp4 -out tetst.mpd -add 4.ts -fps 30 DASH.mp4

......
when I have n.h264 and n.aac , I use ffmpeg to mutex them as n.ts  I use MP4Box with the command again:

MP4Box  -dash-ctx  DASH.txt -dash 24000 -profile live -segment-ext mp4 -out tetst.mpd -add n.ts -fps 30 DASH.mp4


The current results with problem:

I generate many files ,but the MP4Client seems only play the first three segment  24*3 = 72 seconds(Please note ,when I have three segment I start the Mp4client) ,So here I have the problem ,I want to the mp4client can always playing  for every 24 seconds I have new files to added.


Another question :Does my command is correct or not ?

MP4Box  -dash-ctx  DASH.txt -dash 24000 -profile live -segment-ext mp4 -out tetst.mpd -add n.ts -fps 30 DASH.mp4   (n means 1,2,3,4,.....)

**Comment by rbouqueau** [comment]
> I means I need to push my files to another web-server,it's appache.

Why don't you mount or mirror the DASH output folder to the Web publishing folder? I think this question is unrelated to DASH or to any tool we have discussed here up to now.

> OK.Let me introduce my problem again.

Thanks for the description. https://github.com/gpac/node-gpac-dash is the right tool for what you describe. Just modify the FFmpeg command-line to take you input card as the FFmpeg input.

**Comment by hanyufeng520** [comment]
@rbouqueau Thank you very much.
I can't use ffmpeg command line to generate the  ts files because I need to encode the video from CUDA , but I can use the interfaces of ffmepg to generate the ts files(H264+AAC).

So how can I use node-gpac-dash with these ts files ?
Could you please tell me which commands I should use ?

Thanks for you time.

**Comment by rbouqueau** [comment]
I don't understand. What do your command-lines look like?

**Comment by hanyufeng520** [comment]
@rbouqueau I mean using my 1.ts  2.ts  3.ts  .......n.ts          to generate live streaming.

 like : MP4Box -dash-ctx DASH.txt -dash 10000 -profile live -segment-ext mp4 -out tetst.mpd -add 1.ts -fps 30 DASH.mp4

Thank you.

**Comment by hanyufeng520** [comment]
@rbouqueau Sorry to interrupt you again,Could you please tell me what's the command of MP4box can generate the following mpd files ?

<Representation id="1" width="3840" height="2160" bandwidth="12000000">
        <SubRepresentation contentComponent="1" bandwidth="12000000" codecs="avc1.640033"/>
        <SubRepresentation contentComponent="2" bandwidth="384000" codecs="mp4a.40.2"/>
</Representation>


I use MP4Box -dash-ctx DASH.txt -dash 10000 -profile live -segment-ext mp4 -out tetst.mpd -add 1.ts -fps 30 DASH.mp4 , the result mpd file looks like the following : 

   <Representation id="1" mimeType="video/mp4" codecs="avc3.640033,mp4a.40.2" width="3840" height="2160" frameRate="30" sar="1:1" audioSamplingRate="48000" startWithSAP="1" bandwidth="11730905">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="6"/>
    <SegmentTemplate timescale="1000" media="DASH_dash$Number$.mp4" startNumber="1" duration="14266" initialization="DASH_dashinit.mp4"/>
   </Representation>

**Comment by hanyufeng520** [comment]
Could you please tell me what's the command of MP4box can generate the following mpd files ?

<Representation id="1" width="3840" height="2160" bandwidth="12000000">
        <SubRepresentation contentComponent="1" bandwidth="12000000" codecs="avc1.640033"/>
        <SubRepresentation contentComponent="2" bandwidth="384000" codecs="mp4a.40.2"/>
</Representation>

**Comment by hanyufeng520** [comment]
@rbouqueau Could you please tell me which commands with MP4Box can generate this king of MPD file ?

Representation id="1" width="3840" height="2160" bandwidth="12000000"
     SubRepresentation contentComponent="1" bandwidth="12000000" codecs="avc1.640033"
     SubRepresentation contentComponent="2" bandwidth="384000" codecs="mp4a.40.2"
Representation

**Comment by jeanlf** [comment]
closing, open a more precise issue if needed
