### ISSUE TITLE
help wanted：the log files

### ISSUE THREAD

**Issue by AustinDGY** [gpac/gpac#550]
How to set a log file to store the logs that I see in the console when using MP4client with console?
Is this possible?
I noticed that in the configuration document that
"LogFile [value: filename]
Specifies where to output GPAC's log. By default, the logs are written to stdout. Note that GPAC may be compiled without log support. **This is not used by MP4Client**."
Thanks a lot.

**Comment by rbouqueau** [comment]
```
$ MP4Client -h
[...]
        -log-file file: sets output log file. Also works with -lf
[...]
```
