### ISSUE TITLE
mp4box dashing generates empty text adaptation set

### ISSUE THREAD

**Issue by sandersaares** [gpac/gpac#553]
Version used: gpac-0.6.2-DEV-rev591-g878a3f3-master-x64
Command executed: `mp4box -dash-strict 4000 -profile "dashavc264:live" test.mp4 -out out\Manifest.mpd`
Input file: [test.zip](https://github.com/gpac/gpac/files/313469/test.zip)
Description: this input file contains a TTML stream with one sample at around the 30 second mark

Expected result: mp4box generates valid DASH video
Actual result: init segment is generated but no segments are generated and the manifest appears incomplete

```
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.6.2-DEV-rev591-g878a3f3-master  at 2016-06-14T08:33:20.650Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H0M0.000S" profiles="urn:mpeg:dash:profile:isoff-live:2011,http://dashif.org/guidelines/dash264">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>out\Manifest.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period>
  <AdaptationSet segmentAlignment="true">
  </AdaptationSet>
 </Period>
</MPD>
```

There is no visible command line output printed by mp4box in response to this command. Adding `-logs debug@all` produces this line (besides other seemingly uninteresting lines):

```
[DASH] No samples in movie, rewriting moof and exit
```

**Comment by sandersaares** [comment]
This remains an annoying issue that rarely comes up (but is very destructive when it does). Are there plans to fix it?

**Comment by aureliendavid** [comment]
I think I see the problem. 

I pushed a change that should fix it, please report back if this resolves your issue. 

Thanks.

**Comment by sandersaares** [comment]
I confirm the issue is resolved. Thanks for action!
