### ISSUE TITLE
Segment and presentation duration rounding difference creates small gap in timeline

### ISSUE THREAD

**Issue by sandersaares** [gpac/gpac#554]
I have been attempting to create a deterministic understanding of the timing logic used by mp4box, with the idea being to always have representations of the same length and not to have any "missing time" anywhere. In this exploration, I ran into a scenario that appears suspicious to me,

Version: gpac-0.6.2-DEV-rev591-g878a3f3-master-x64
Command executed: `mp4box -dash-strict 4000 -profile "dashavc264:live" -out Out\Manifest.mpd video.mp4`
Input file: [video.zip](https://github.com/gpac/gpac/files/314018/video.zip)
Description: this input contains a video stream that is 95 frames long, at 24 frames per second rate.

Output from this command:
- 1 media segment containing the 95 frames, with the duration in the manifest marked as 3.958s
- Manifest with the presentation duration marked as 3.95**9**s

```
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.6.2-DEV-rev591-g878a3f3-master  at 2016-06-14T13:29:44.751Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H0M3.959S" maxSegmentDuration="PT0H0M3.958S" profiles="urn:mpeg:dash:profile:isoff-live:2011,http://dashif.org/guidelines/dash264">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>Out\Manifest.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H0M3.959S">
  <AdaptationSet segmentAlignment="true" maxWidth="2048" maxHeight="872" maxFrameRate="24" par="2048:872" lang="und">
   <Representation id="1" mimeType="video/mp4" codecs="avc3.640028" width="2048" height="872" frameRate="24" sar="1:1" startWithSAP="1" bandwidth="208136">
    <SegmentTemplate timescale="12288" media="video_dash$Number$.m4s" startNumber="1" duration="48640" initialization="video_dashinit.mp4"/>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```

Expected result: presentation duration is equal to the duration of the 1st and only segment.

From my observations, it would appear that the presentation duration is always rounded up, whereas in this case the segment duration is rounded down (from 3.9583333333...). This means that there exists 1 millisecond on the timeline that is not backed by any segment files.

Without deeper analysis, it sounds like always using the same rounding algorithm might perhaps correct this?

**Comment by jeanlf** [comment]
I believe we can close this one, reopen if needed
