### ISSUE TITLE
Unable to segment [DASH] video with multiple tracks of different duration

### ISSUE THREAD

**Issue by KashyapKammachiSreedhar** [gpac/gpac#557]
When I try to DASH the video file it only generates segment from track 2; TrackID 1002.
Is it possible to generate segments from both the tracks separately?

I use the following command

MP4Box -v -dash 500 isomfile_22.mp4#trackID=1001:role=video isomfile_22.mp4#trackID=1002:role=video

Below is the video info:

* Movie Info *
	Timescale 1000 - 2 tracks
	Computed Duration 00:00:02.080 - Indicated Duration 00:00:02.080
	Fragmented File: no
	File suitable for progressive download (moov before mdat)
	File Brand iso8 - version 0
	Created: UNKNOWN DATE	Modified: UNKNOWN DATE
File has no MPEG4 IOD/OD

Track # 1 Info - TrackID 1001 - TimeScale 1000
Media Duration 00:00:02.000 - Indicated Duration 00:00:02.000
Media Info: Language "Undetermined (und)" - Type "vide:hvc1" - 50 samples
Visual Track layout: x=0 y=0 width=3072 height=1536
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x23
HEVC Video - Visual Size 3072 x 1536
	HEVC Info: Profile Main @ Level 6.2 - Chroma Format YUV 4:2:0

	NAL Unit length bits: 32 - general profile compatibility 0x60000000

	Parameter Sets: 1 VPS 1 SPS 1 PPS 
	SPS resolution 3072x1536
	Bit Depth luma 8 - Chroma 8 - 1 temporal layers
	VPS#1 hash: CD08EB58F7A523C2E0997A19BD43F2C52D652471
	SPS#1 hash: BD3CB3C28DD9B747633AD73B595000C63E2FFEC8
	PPS#1 hash: 62C4003CFB2A59377DD75A3C4C1DC48D6C7AE529

Self-synchronized
	RFC6381 Codec Parameters: hvc1.1.6.L186.0
	Average GOP length: 50 samples

Track # 2 Info - TrackID 1002 - TimeScale 1000
Media Duration 00:00:02.080 - Indicated Duration 00:00:02.080
Media Info: Language "Undetermined (und)" - Type "vide:hvc2" - 52 samples
Visual Track layout: x=0 y=0 width=3072 height=1536
Unknown track type
	RFC6381 Codec Parameters: hvc2.1.6.L186.0
	Average GOP length: 52 samples

Version of GPAC/MP4Box being used

MP4Box - GPAC version 0.6.2-DEV-rev597-g07b3a93-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: 
Features: GPAC_64_BITS GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG

**Comment by rbouqueau** [comment]
It works here. Please give steps to reproduce.
