### ISSUE TITLE
mp4box generates unexpected adaptation set groups during dashing

### ISSUE THREAD

**Issue by sandersaares** [gpac/gpac#558]
Version used: gpac-0.6.2-DEV-rev591-g878a3f3-master-x64
Command executed: `mp4box.exe -dash-strict 4000 -profile "dashavc264:live" audio.mp4 video-288-400k.mp4 TOS-en.ttml.mp4 TOS-en.vtt.mp4 -out out\Manifest.mpd video-360-800k.mp4 TOS-es.ttml.mp4 TOS-es.vtt.mp4 audio_high.mp4 TOS-zh.ttml.mp4 TOS-zh.vtt.mp4`
Input: https://mega.nz/#!w9AlzbQY!wQ6sp8LIFHFGBfiy68aUocWurTDqpHKDl3fSmGqexwo
Description: 2 audio tracks, 2 video streams (different qualities), 3 webvtt subtitle tracks, 3 ttml subtitle tracks (same languages as webvtt - these are alternative encodings of the same data)

Actual result:

| Adaptation set | Group |
| --- | --- |
| Audio (en) | 1 |
| Audio (et) | 1 |
| Video | auto (attribute not present) |
| Text (en-US, VTT) | 2 |
| Text (en-US, TTML) | 3 |
| Text (es, VTT) | 2 |
| Text (es, TTML) | 3 |
| Text (zh, VTT) | 3 |
| Text (zh, TTML) | 3 |

Expected result: all text tracks are in the same group (e.g. 2), as they are simply alternatives for the player to choose from, depending on what codec it understands

Note that zh language text tracks are correctly marked as being in the same group, for some reason, whereas other languages are separate.

Is there some workaround available for this? I tried a `:group=123` suffix but to no effect.

**Comment by jeanlf** [comment]
this has been patched in GPAC 0.9.0 DEV by allowing mixed codecs adaptation sets
