### ISSUE TITLE
UDTA remove

### ISSUE THREAD

**Issue by combucha** [gpac/gpac#560]
Hi, how to remove this atoms from mp4?
Video and audio tracks has them injected: 1 UDTA types: name (1)
It's pure text (advertising).

**Comment by combucha** [comment]
Here's the example file:
http://www28.zippyshare.com/v/9I3R9zAt/file.html
Is it possible erase these boxes with mp4box -udta command?

**Comment by rbouqueau** [comment]
Did you try this? https://github.com/gpac/gpac/blob/3d17f9524b48e8564bba50055c3502e660c41a64/applications/mp4box/main.c#L292

**Comment by combucha** [comment]
Yes I did. No luck. But maybe I do something wrong.
Anyway please try yourself with sample (reupped): http://www34.zippyshare.com/v/OaNUwxmJ/file.html
-in case of succesful remove tell me the commandline please
-in case of failed remove tell me that it indeed doesn't work
regards

**Comment by jeanlf** [comment]
this was added in GPAC 0.9.0 see https://github.com/gpac/gpac/blob/filters/tests/scripts/mp4box-udta.sh
