### ISSUE TITLE
Unable to specify multiple roles when dashing

### ISSUE THREAD

**Issue by sandersaares** [gpac/gpac#561]
I wish to mark a subtitle stream as being a subtitle stream (role=subtitle) and as being the main subtitle stream (role=main).

Version used: gpac-0.6.2-DEV-rev591-g878a3f3-master-x64
Command: `mp4box -dash-strict 4000 -profile "dashavc264:live" TOS-es.ttml.mp4:role=main:role=subtitle -out Out\Manifest.mpd`
Input: [TOS-es.ttml.mp4.zip](https://github.com/gpac/gpac/files/317815/TOS-es.ttml.mp4.zip)

Actual result: only the last role descriptor is emitted in the manifest
Expected result: both role descriptors are emitted in the manifest

**Comment by jeanlf** [comment]
MP4Box now supports multiple role per input - reopen if needed
