### ISSUE TITLE
Dashing applies main role to multiple audio streams, without even asking for any role on audio streams

### ISSUE THREAD

**Issue by sandersaares** [gpac/gpac#562]
Version used: gpac-0.6.2-DEV-rev591-g878a3f3-master-x64
Command: `mp4box -dash-strict 4000 -profile "dashavc264:live" -out out\Manifest.mpd audio.mp4 in.mp4 TOS-zh.ttml.mp4:role=subtitle`
Input: [main-role-on-both-audios.zip](https://github.com/gpac/gpac/files/317854/main-role-on-both-audios.zip)
Description: 2 audio streams and 1 text stream

Actual result: text stream gets the expected "subtitle" role; both audio streams get the "main" role
Expected result: text stream gets the expected "subtitle" role; no roles declared on audio streams

Removing the subtitle role also gets rid of the undesired audio roles.

**Comment by jeanlf** [comment]
this should now be fixed in GPAC 0.9.0 dev, reopen if needed
