### ISSUE TITLE
MP4Box to generate 'saio' v0 box

### ISSUE THREAD

**Issue by atadlate** [gpac/gpac#564]
I'm using MP4Box (0.6.2-DEV-rev591-g878a3f3-master) to package CENC encrypted mp4 files. I'm using Widevine for the DRM part and am trying to achieve playback on an iOS device using Widevine's iOS SDK. Now, playback on iOS has to go through a DASH to HLS transmux, which is ensured by [this library](https://github.com/google/universal-dash-transmuxer). But it seems the latter doesn't play well with 'saio' v1 box. A 'saio' v0 box that contains the same value for the offset works correctly. The location of it can remain exactly the same, just version of it is old which their transmuxer requires.

Obviously, I've first enquired about whether an udate of the transmuxer was planned, to accept v1 boxes. Meanwhile, I'm trying to find a workaround. Now, this is a silly and naive question, but is there a way to let MP4Box generates 'saio' v0 box? An older version of the software maybe?

Thanks a lot for your help.

**Comment by cconcolato** [comment]
Quickly looking at the code https://github.com/gpac/gpac/blob/8d256bc27fdb4bccfa5cc561dc5cb596c6d91d09/src/isomedia/drm_sample.c#L890 it seems that we indeed force v1 saio but I don't get why. @rbouqueau, since you made the patch, can you check if we can revert to v0 i.e. using 32-bits values?

**Comment by rbouqueau** [comment]
That was a patch from @nguyen-viet-thanh-trung ! de6f8c1b366b9950aa48f9571c9844ffdf4e83d6

**Comment by cconcolato** [comment]
Apparently, a simple revert is not possible as 64-bit values may be needed for very large (non-fragmented) files. We should probably write a saio version that depends on the input file size.

**Comment by atadlate** [comment]
Thanks a lot for your feedback.

**Comment by sarge** [comment]
Hi all, am taking a look at this.

disclaimer: this is my first foray into the mp4 format and gpac. Long time user, first time contributor.

I have taken a quick look and have experimented with reverting the >4GB patch. Which seems to work. I was wondering if it would be permissible to mix v0 and v1 saio in the same file? 

The idea being that if the offset is greater than 32 bit write the offset as 64 bit and mark the version as 1.

Alternatively as @cconcolato suggests getting hold of the size of the file and making the switch based on that. Though it seems that information is not local.

**Comment by rbouqueau** [comment]
Any news on this? It seems important and the patch seems not far!

**Comment by sarge** [comment]
Thanks for taking the time to look at this.

My testing scenario involves a fix on the google shaka transmuxer which is preventing playback of content >2GB and <4GB. That bug has not been acknowledged as yet. A recent release apparently fixed this, but I still believe there is unsigned int being cast to a signed int somewhere.
Until that I have that end to end solution, I am not full comfortable with my fix.

**Comment by jeanlf** [comment]
now in GPAAC 0.9.0 - note that we throw an error if offset gets larger than 32 bit when using `:saio32`
