### ISSUE TITLE
control IV value in MP4box Encryption

### ISSUE THREAD

**Issue by jingke2000** [gpac/gpac#566]
I use GPAC/MP4box to encrypt my VOD content as reference for my work on DASH Common Encryption. I need the IV value to increment by 1 each time with a new sample. However, MP4box seems to generate the IVs from first IV in different way. How can I specify the method of IV value change in mp4box?

**Comment by nguyen-viet-thanh-trung** [comment]
Hi, 
MP4Box changes the IVs  as described in the CENC specification:
- For 64-bit (8-byte) IV_Sizes, initialization vectors for subsequent samples can be created by
incrementing the initialization vector of the previous sample
- For 128-bit (16-byte) IV_Sizes, initialization vectors for subsequent samples should be created by
adding the block count of the previous sample to the initialization vector of the previous sample.

If you have a strange behavious, please provide us an input for testing.

**Comment by jingke2000** [comment]
Thanks. This makes sense.
