### ISSUE TITLE
Mp4box delay video with b-frames

### ISSUE THREAD

**Issue by combucha** [gpac/gpac#569]
Hi, I think mp4box slightly incorrect writes edit list in case of video positive delay.
Entry of delay (media_time=-1) is ok, but next entry of track starts from 0, while it should be set equal to ctts with b-frame stream (just like in not delayed video). media_time=0 causes a/v desync here.

I've played also for a while with negative vid delay option (b-framed streams).
Seems mp4box should increase in this case user defined delay by ctts/vid_timescale value.
If it only injects straight recalculated -delay, audio plays too early (time of ctts shift).
There's also impossibilty to set up negative delay when this delay is equal to ctts shift time (which entry is already written for synced playing).

What do you think?

**Comment by rbouqueau** [comment]
Hi, thanks for reporting. Do you have file examples that could help us investigate your issue?

We have an anonymous dropbox if necessary (please put the issue number in the filename): https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by combucha** [comment]
I created some sample for this case.
The problem might be player which properly handles edit lists of mp4. I use MPC-HC.
Test video: http://www50.zippyshare.com/v/Uv0cXY3h/file.html
It's 2fps clip with sound that start playing at frame 4 (2s), ctts shift in elst present to a/v sync.
Low framerate allow catching results of a/v desync live during playing.
```
<EditListBox EntryCount="1">
<BoxInfo Size="28" Type="elst"/>
<FullBoxInfo Version="0" Flags="0x0"/>
<EditListEntry Duration="6000" MediaTime="8" MediaRate="1"/>
</EditListBox>
```

Now let's delay test vid by 1s: mp4box -delay 1=1000
```
<BoxInfo Size="48" Type="edts"/>
<EditListBox EntryCount="2">
<BoxInfo Size="40" Type="elst"/>
<FullBoxInfo Version="0" Flags="0x0"/>
<EditListEntry Duration="600" MediaTime="-1" MediaRate="1"/>
<EditListEntry Duration="6000" MediaTime="0" MediaRate="1"/>
</EditListBox>
```
After 1s of empty edit (-1) video is played from start, but 0 is not start of b-frame stream, it's 8 here.
Audio in such delayed video plays like in b-frame stream muxed with :noedit option - to early (shift=missing ctts offset).

**Comment by rbouqueau** [comment]
The sample expired and I didn't download it. Does anyone have access to it?

**Comment by combucha** [comment]
I've re-uploaded test vid to your mediafire dropbox.

**Comment by rbouqueau** [comment]
Thank you. Unfortunately not received... The link is: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by combucha** [comment]
Weird, had upload completed info. Retry#2 to dropbox.
+zippyshare backup in case of dropbox fail#2: http://www81.zippyshare.com/v/njhyPWb9/file.html

**Comment by rbouqueau** [comment]
I received the notification. Thanks

**Comment by jeanlf** [comment]
any news on this ?

**Comment by jeanlf** [comment]
Just did reimport test on your files, the edit list seems ok I believe we fixed this issue some time ago. As far as the user-specified delay option is concerned, this is the intended behaviour, we don't want to adjust based on the timing of the first frame you have to compensate for that in your command line. Reopen if needed
