### ISSUE TITLE
portable (standalone) mp4box ?

### ISSUE THREAD

**Issue by hydra3333** [gpac/gpac#570]
I and some others are not in a position to use an installer just to have mp4box available.
Would it be possible to create a non-installer standalone portable mp4box, nightly ?
LOTS of software have portable versions.
Thanks

**Comment by rbouqueau** [comment]
Sure. We had similar requests in the past but coudn't get enough information to proceed... May I ask you a few questions:
1) What's the target OSes for this?
2) Which tools do you need? MP4Box only?
3) What would be the form of the delivery? (e.g. is a compressed archive ok?)

PS: building GPAC with near-zero dependency is easy: http://gpac.io/2015/07/29/gpac-build-mp4box-only-all-platforms/

**Comment by darkdragon-001** [comment]
For me stable version would be enough.
1) Windows
2) MP4Box only
3) compressed archive

**Comment by jeanlf** [comment]
my suggestion for windows would be to install on any location and get the binaries from that directory. I don't think we will ever provide that for other platforms.

**Comment by Almeonamy** [comment]
How can we get portable version for Linux?

**Comment by aureliendavid** [comment]
For linux you can follow the instructions in this section: https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux#mp4box-only to build a portable mp4box

**Comment by hydra3333** [comment]
> my suggestion for windows would be to install on any location and get the binaries from that directory. I don't think we will ever provide that for other platforms.

Well ... as long as it does not require elevated privilege to install and/or creates registry entries etc. That's the point of portable versions.

**Comment by aureliendavid** [comment]
7zip is able to unpack the NSIS installers that gpac uses

you should be able to extract the binaries with it and them use them as unelevated user

**Comment by hydra3333** [comment]
Beaut !  Thanks.

**Comment by Almeonamy** [comment]
> For linux you can follow the instructions in this section: https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux#mp4box-only to build a portable mp4box

Is there any way to get portable version for Linux without Linux-machine?
We want to deploy our service to Linux-server, but for developing we use only Windows.

**Comment by Almeonamy** [comment]
> 7zip is able to unpack the NSIS installers that gpac uses
> 
> you should be able to extract the binaries with it and then use them as an unelevated user

I tried to unpack .dep file by 7zip and move the files to our's project folder. But the mp4box doesn't work without any errors or output.

**Comment by aureliendavid** [comment]
hm, that's an unusual set-up

on windows 10 you could use [wsl](https://docs.microsoft.com/en-us/windows/wsl/install-win10) and build yourself a linux version with the guide I linked above ; or use a vm

you can also use the binaries extracted from the .deb installer but you have to add the directory containing the `libgpac.so` file (`usr/lib` inside the deb) to the `LD_LIBRARY_PATH` environment variable on linux (you'll also have to install the dependencies listed here https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux#setting-up since the libgpac in this case comes from a full build)

**Comment by Almeonamy** [comment]
When we try to build filters branch we get this error:
`make[1]: *** No rule to make target '/root/build_folder/gpac_public/include/gpac/modules/raster2d.h', needed by 'compositor/mpeg4_grouping_2d.o'. Stop.`

**Comment by aureliendavid** [comment]
see https://github.com/gpac/gpac/issues/1460
