### ISSUE TITLE
Adding new representations to an already existent mpd file using mp4box.

### ISSUE THREAD

**Issue by kshank09** [gpac/gpac#576]
Is there a way to do this using mp4box? I know you can add multiple representations within a single command to generate a single mpd, but can you update an existing mpd with mp4box to add in a new representation after the file is already generated? I couldn't find this information anywhere. Thanks.

**Comment by jeanlf** [comment]
No this is not possible, mp4box does not read MPDs at all, and I doubt this will ever be the case.
