### ISSUE TITLE
Add support for all CENC encryption schemes

### ISSUE THREAD

**Issue by sandersaares** [gpac/gpac#577]
CENC describes 4 different encryption schemes, of which mp4box only supports a subset (only 'cenc', I believe?). I would like to request that support be added for the other encryption schemes, too, as they may become relevant in the near future (especially with fMP4-HLS).

This is implemented by [shaka-packager](https://github.com/google/shaka-packager/issues/78) - achieving feature-parity here would be nice.

**Comment by jeanlf** [comment]
support has been added some time ago ...
