### ISSUE TITLE
Segmentation fault when using MP4Box

### ISSUE THREAD

**Issue by qjia7** [gpac/gpac#58]
The steps to produce this bug:
1. git clone https://github.com/gpac/gpac.git
2. cd gpac
3. ./configure
4. make
5 sudo make install
6. MP4Box -dash-live 4000 -out final.mp4 -dash-profile live -mpd-refresh 100000 -min-buffer 4000 -segment-name pigeon pigeon.mp4  // assume you have pigeon.mp4 file in current directly
Live DASH-ing - press 'q' to quit, 's' to save context and quit
Segmentation fault (core dumpped) 

My environment is ubuntu14.04

**Comment by qjia7** [comment]
Ping @jeanlf @rbouqueau

**Comment by jeanlf** [comment]
indeed now fixed thanks for the report
