### ISSUE TITLE
Timescales question

### ISSUE THREAD

**Issue by combucha** [gpac/gpac#581]
Hi
I have raw .264 stream encoded at 30000/1001 fps.
If I mux it "blindly" without -fps option, mp4box sets up 120000/4004.
If I mux with -fps=29.97, mp4box sets up 30000/1001.
Both are the same and correct, but why mp4box just not divide values to the lowest possible?
Similar with 25fps (25000/1000 instead of just 25/1).

Other timescale case, stream encoded at 2997/100 (round ntsc).
Mp4box sets up 11988/400 (as above 4 times higher).
But in this case I can't restore original 2997/100 timescale because fps=29.97 mp4box interprets as 30000/1001.
In this case It is impossible override framerate of ntsc_stream with framerate of rounded_ntsc_stream. (It's just few ms difference in 1hour clip, but it is incorrect, and rise with movie lenght).

It all could be fixed, if mp4box -fps allow specify it also as -fps=num:den (similar to -par style option).
Any thoughts?

**Comment by rbouqueau** [comment]
> If I mux it "blindly" without -fps option, mp4box sets up 120000/4004.
If I mux with -fps=29.97, mp4box sets up 30000/1001.
Both are the same and correct, but why mp4box just not divide values to the lowest possible?

We replicate the data from the raw H264.

If you want us to have a look, please upload a sample at https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

> It all could be fixed, if mp4box -fps allow specify it also as -fps=num:den (similar to -par style option).
Any thoughts?

Makes sense. Should I tag it as a feature request?

**Comment by combucha** [comment]
Would be great, thanks.

**Comment by rbouqueau** [comment]
Note that I read the help and found that you should be able specify the timescale (e.g. 30000) and the increment (e.g. 1001) as the FPS: ```-fps 30000-1001```. May I ask you to try and tell me if it works for you?

Source commit: e69ecc7c3fc2bf449a98497fd8e1bfc54253a274

**Comment by combucha** [comment]
Indeed such option exists.
But not working in this case:
mp4box -add "raw_30000_1001.h264" -fps 2997-100 newfile.mp4
Result file has unmodified timescale/increment.

**Comment by rbouqueau** [comment]
Ok. Could you please provide us with a sample file?

**Comment by combucha** [comment]
http://www22.zippyshare.com/v/3KTLfumS/file.html

**Comment by rbouqueau** [comment]
It works here:
```
$ MP4Box -add raw_30000_1001.h264 -new out.mp4
[avc-h264] Possible Variable Frame Rate: VUI "fixed_frame_rate_flag" absent.
AVC-H264 import - frame size 640 x 360 at 29.970 FPS
AVC Import results: 300 samples (305 NALUs) - Slices: 2 I 103 P 195 B - 1 SEI - 2 IDR
Stream uses forward prediction - stream CTS offset: 2 frames
Saving out.mp4: 0.500 secs Interleaving

$ MP4Box -info out.mp4
* Movie Info *
        Timescale 600 - 1 track
        Computed Duration 00:00:10.010 - Indicated Duration 00:00:10.010
        Fragmented File: no
        File suitable for progressive download (moov before mdat)
        File Brand isom - version 1
        Created: GMT Sun Jul 03 06:38:13 2016
        Modified: GMT Sun Jul 03 06:38:13 2016

File has root IOD (9 bytes)
Scene PL 0xff - Graphics PL 0xff - OD PL 0xff
Visual PL: AVC/H264 Profile (0x7f)
Audio PL: No audio capability required (0xff)
No streams included in root OD

Track # 1 Info - TrackID 1 - TimeScale 120000
Media Duration 00:00:10.010 - Indicated Duration 00:00:10.010
Track has 1 edit lists: track duration is 00:00:10.010
Media Info: Language "Undetermined (und)" - Type "vide:avc1" - 300 samples
Visual Track layout: x=0 y=0 width=640 height=360
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x21
AVC/H264 Video - Visual Size 640 x 360
        AVC Info: 1 SPS - 1 PPS - Profile High @ Level 3.1
        NAL Unit length bits: 32
        Chroma format 1 - Luma bit depth 8 - chroma bit depth 8
        SPS#1 hash: E9E03F65067E4289397283DD2856A48BC8F3A041
        PPS#1 hash: 57B6A76E3C7BFCCAEFC8060C61076BBA234904B3
Self-synchronized
        RFC6381 Codec Parameters: avc1.64001f
        Average GOP length: 300 samples


$ MP4Box -add raw_30000_1001.h264 -fps 30000-1001 -new out2.mp4
AVC-H264 import - frame size 640 x 360 at 29.970 FPS
AVC Import results: 300 samples (305 NALUs) - Slices: 2 I 103 P 195 B - 1 SEI - 2 IDR
Stream uses forward prediction - stream CTS offset: 2 frames
Saving out2.mp4: 0.500 secs Interleaving

$ MP4Box -info out2.mp4
* Movie Info *
        Timescale 600 - 1 track
        Computed Duration 00:00:10.010 - Indicated Duration 00:00:10.010
        Fragmented File: no
        File suitable for progressive download (moov before mdat)
        File Brand isom - version 1
        Created: GMT Sun Jul 03 06:39:06 2016
        Modified: GMT Sun Jul 03 06:39:06 2016

File has root IOD (9 bytes)
Scene PL 0xff - Graphics PL 0xff - OD PL 0xff
Visual PL: AVC/H264 Profile (0x7f)
Audio PL: No audio capability required (0xff)
No streams included in root OD

Track # 1 Info - TrackID 1 - TimeScale 30000
Media Duration 00:00:10.010 - Indicated Duration 00:00:10.010
Track has 1 edit lists: track duration is 00:00:10.010
Media Info: Language "Undetermined (und)" - Type "vide:avc1" - 300 samples
Visual Track layout: x=0 y=0 width=640 height=360
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x21
AVC/H264 Video - Visual Size 640 x 360
        AVC Info: 1 SPS - 1 PPS - Profile High @ Level 3.1
        NAL Unit length bits: 32
        Chroma format 1 - Luma bit depth 8 - chroma bit depth 8
        SPS#1 hash: E9E03F65067E4289397283DD2856A48BC8F3A041
        PPS#1 hash: 57B6A76E3C7BFCCAEFC8060C61076BBA234904B3
Self-synchronized
        RFC6381 Codec Parameters: avc1.64001f
        Average GOP length: 300 samples
```

Do you confirm it is different for you? What's your MP4Box version?

**Comment by combucha** [comment]
I have the same result, but it's incorrect.
You won't see difference by flushing -info, it's all about small fractions.
2997/100 (round_ntsc) has frame time 33.3667000333667... ms
30000/1001 (ntsc) is a little shorter 33.366666666666... ms
Thousands of frames and the same clip will have noticable different durations at "29.970".
If mp4box could take user defined -fps 2997-100 and rewrite tables exactly with this timescale and this increment, output will be ok.

**Comment by rbouqueau** [comment]
I see what you mean, let me have a look

**Comment by jeanlf** [comment]
now in GPAC 0.9.0
