### ISSUE TITLE
Problem with encoding audio with mp4Box

### ISSUE THREAD

**Issue by mohitYogi** [gpac/gpac#583]
I was trying to encrypt this video named "oggy.mp4".
For this purpose,
- Firstly I seperated audio and video from the audio using "raw" command.
- then I converted, two audio tracks to mp4 tracks.
- after that I encrypted the video, with file "oggy_encoder.xml"
- Finally I created the dash file using the encrypted video and unencrypted audio.
Now, there is problem with the audio in finally prepared file oggy_audio_dashinit.mp4.
Need help with this.
Attaching all the used files and logs by chrome(using shaka player).
I have uploaded zip file to media fire.

**Comment by rbouqueau** [comment]
This procedure is known to work: https://html5.cablelabs.com/mse-eme/doc/creation.html

Does it allow you to cover your use-case? Can you reproduce with it?

**Comment by mohitYogi** [comment]
@rbouqueau  I have followed the procedure, created the the dashinit files, but there is an error in encoding audio. Kindly re-read the information I stated previously.

**Comment by rbouqueau** [comment]
The procedure is clear, but what are you trying to achieve? Which command-lines did you execute, with which tools, which versions, on which platform? At this point I don't know how I can help you.

If you have an issue with Chrome for playback or the CableLabs encoding, you might also consider creating issues on these tools bugtrackers.

**Comment by mohitYogi** [comment]
@rbouqueau I have used mp4box, in command line mode, on win7-32bit.
I am trying to create a Shaka Player compatible encrypted video, in which audio is unencrypted, and audio is encrypted using this file attached.

command lines I used is:
MP4Box -raw 1 oggy.mp4
MP4Box -raw 2 oggy.mp4
MP4Box -add oggy_track1.h264 -new oggy_video.mp4
mp4box -add oggy_track2.aac -new oggy_audio.mp4
MP4Box -crypt oggy-encoder.xml oggy_video.mp4 -out oggy_encrypt_video.mp4
MP4Box -dash 5000  -out manifestOggy.mpd oggy_audio.mp4 oggy_encrypt_video.mp4

[encodingFile.txt](https://github.com/gpac/gpac/files/349391/encodingFile.txt)

**Comment by rbouqueau** [comment]
What encrytion does Shaka support? What did you test in that perspective (i.e. how did you generate your GPAC xml)?

**Comment by mohitYogi** [comment]
It supports clearkey. But it not an issue of shaka player.
I have tested the generated audio_dshinit.mp4 file in OSMO4 player provided with package of mp4box, it is also not able to play it.

**Comment by mohitYogi** [comment]
Firstly I thought that it is an error of Shaka player, for that I created an issue at, [https://github.com/google/shaka-player/issues/417](url). you can check the discussion.

**Comment by rbouqueau** [comment]
W3C Clearkey is not implemented in GPAC: https://github.com/gpac/gpac/issues/239

**Comment by rbouqueau** [comment]
A link to see what DRM scheme is supported by your browser: http://www.radiantmedialyzer.net/

**Comment by fastfading** [comment]
the same here 
MP4Box -crypt oggy-encoder.xml oggy_video.mp4 -out oggy_encrypt_video.mp4
MP4Box -dash 5000 -out manifestOggy.mpd oggy_audio.mp4 oggy_encrypt_video.mp4
only video encrypted,  audio  not
