### ISSUE TITLE
MP4Box Not Extracting Audio

### ISSUE THREAD

**Issue by bytos** [gpac/gpac#585]
With this .mp4 file I only get the .h264 video file and no .acc audio file (https://www.rt.com/shows/crosstalk/350122-cold-war-nato-role):

![s1](https://cloud.githubusercontent.com/assets/16452541/16732227/1df368f8-474a-11e6-8b7c-257addc6929d.png)

![s2](https://cloud.githubusercontent.com/assets/16452541/16732939/68d9fcee-474d-11e6-8d99-77fecf4452e7.png)

mp4box.exe -raw 1:output="%%~nA.h264" -raw 2:output="%%~nA.aac" %%A

The original mp4 plays normally in player, but if I use the command line below I get 5 seconds of audio in a m4a file:

mp4box.exe -raw 2:output="%%~nA.m4a" %%A

**Comment by rbouqueau** [comment]
It works here. Could you make sure you use the latest MP4Box version?

**Comment by bytos** [comment]
I downloaded the latest version 0.61 (x64) and used it to test the files above.

Also, noticed that the file that worked without issue was downloaded via a downloader instead of the browser.

**Comment by rbouqueau** [comment]
I used a browser (Chrome 51). Would it be possible to share a file that doesn't work? We have an anonymous dropbox if necessary (please put the issue number in the filename): 
https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by bytos** [comment]
I'm using latest Vivaldi snapshot (x86).

Funny, now when clicking the download button the browser plays the videos in a new page (easy to grab the URL).

I'm uploading the file, but upstream is a bit slow.

**Comment by rbouqueau** [comment]
It's the same file but truncated. The error message you quote seems accurate. What do you expect from us?

**Comment by bytos** [comment]
In retrospect, since FileBlender (ffmpeg?) worked on the truncated file it seems MP4Box is less tolerant of the condition of the input file (FileBlender 23:28 min vs MP4Box 5 sec).

**Comment by combucha** [comment]
In this case everything works as expected.
I downloaded whole file, truncated it to get the same warning msg and mp4box extracted as much as it could. It was 23:28s, not 5s.
This syntax:
`mp4box.exe -raw 2:output="%%~nA.m4a" %%A`
seems wrong, you cannot output to m4a using this method.
Your output file is raw aac stream here, not container m4a.
This can generate playback issues on player side.
