### ISSUE TITLE
Support OpenJPEG 2

### ISSUE THREAD

**Issue by jcowgill** [gpac/gpac#592]
Debian bug: https://bugs.debian.org/826814

OpenJPEG 1 is about to be removed from Debian so the OpenJPEG code in GPAC needs to be ported to OpenJPEG 2, or the JPEG2000 reader will have to be disabled in Debian (and probably other downstreams when they start removing OpenJPEG 1).

**Comment by jeanlf** [comment]
now in GPAC 0.9.0 DEV
