### ISSUE TITLE
android extra_libs package is broken

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#594]
The source code of the extra libs (zlib, etc.) are put inside .zip. Why? Should we revert this change, or update the READMEs accordingly?

**Comment by aureliendavid** [comment]
I think it's ok now? 

https://github.com/gpac/gpac/tree/master/build/android mentions unzipping sources before building

**Comment by jeanlf** [comment]
see https://github.com/gpac/deps_android
