### ISSUE TITLE
SRD Player and MPD

### ISSUE THREAD

**Issue by 21praveen** [gpac/gpac#595]
How to create MPD for SRD and If OSMO4 support SRD?

**Comment by rbouqueau** [comment]
Have you read the following links?
http://gpac.io/2016/05/25/srd/
and https://github.com/gpac/gpac/search?utf8=%E2%9C%93&q=srd

**Comment by jeanlf** [comment]
I have updated [http://gpac.io/2016/05/25/srd/] to indicate how SRD parameters are passed to MP4Box. Hope this helps.
