### ISSUE TITLE
Concatenating files with Chapter Tracks leads to incorrect total duration

### ISSUE THREAD

**Issue by greenwoodma** [gpac/gpac#599]
Simple Summary: Concatenating two files with chapters together, using the latest version of MP4Box (MP4Box - GPAC version 0.6.2-DEV-rev681-g32e98cd-master) results in the chapter track being longer than the video/audio tracks which results in the total duration of the file being wrongly reported.

I've been producing M4V files using Handbrake (version 0.10.2 for x86_64) that have a chapter track. Each are produced using the normal profile with the extra settings of web optomised and fast deinterlace. Each of these files, on their own, work flawlessly in a number of media players. On occasion I want to concetenate two or more of these files together to produce a single file. After some experimentation I've been doing this using MP4Box with the following command line (Note that usually the -force-cat option isn't really needed and it appears to make no difference to the following anyway):

```
MP4Box -force-cat -cat part1.m4v part2.m4v -new merged.m4v
```

When I then open the merged file I find that the length of the video is longer than the sum of the two parts. The exact extra duration seems to vary and I haven't yet spotted any obvious patterns. This happens with every set of files I've tried that have a chapter track. The result is that the video plays normally but ends before it's reached the stated duration, but at the point you would expect if you simply add the lengths of the two parts together. It also means that if you seak past the actual end some players get rather upset!

As an example here is the output from -info for two input files

\* Movie Info *
    Timescale 1000 - 3 tracks
    Computed Duration 01:41:18.840 - Indicated Duration 01:41:18.840
    Fragmented File: no
    File suitable for progressive download (moov before mdat)
    File Brand mp42 - version 512
    Created: GMT Sat Jul 30 12:27:08 2016
    Modified: GMT Sat Jul 30 12:27:08 2016

File has no MPEG4 IOD/OD

iTunes Info:
    Encoder Software: HandBrake 0.10.2 2015090200
1 UDTA types: meta (1) 

Track # 1 Info - TrackID 1 - TimeScale 90000
Media Duration 01:41:18.840 - Indicated Duration 01:41:18.840
Track has 1 edit lists: track duration is 01:41:18.840
Media Info: Language "Undetermined (und)" - Type "vide:avc1" - 151970 samples
Visual Track layout: x=0 y=0 width=1015 height=424
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x21
AVC/H264 Video - Visual Size 714 x 424
    AVC Info: 1 SPS - 1 PPS - Profile Main @ Level 4
    NAL Unit length bits: 32
    Pixel Aspect Ratio 64:45 - Indicated track size 1015 x 424
    Chroma format YUV 4:2:0 - Luma bit depth 8 - chroma bit depth 8
    SPS#1 hash: 3523075FCABC05AE3056F84F3CBDC8777E720AE8
    PPS#1 hash: 8C412D9B36B16186B36C96A052D45F2432B0757F
Self-synchronized
    RFC6381 Codec Parameters: avc1.4d4028
    Average GOP length: 76 samples

Track # 2 Info - TrackID 2 - TimeScale 48000
Media Duration 01:41:17.802 - Indicated Duration 01:41:17.802
Track has 1 edit lists: track duration is 01:41:17.781
Media Info: Language "English (eng)" - Type "soun:mp4a" - 284897 samples
1 UDTA types: name (1) 
MPEG-4 Config: Audio Stream - ObjectTypeIndication 0x40
MPEG-4 Audio AAC LC - 2 Channel(s) - SampleRate 48000
Synchronized on stream 1
    RFC6381 Codec Parameters: mp4a.40.2
Alternate Group ID 1
    All samples are sync

Track # 3 Info - TrackID 3 - TimeScale 1000
Media Duration 01:41:18.440 - Indicated Duration 01:41:18.440
Track has 1 edit lists: track duration is 01:41:18.440
Track is disabled
Media Info: Language "Undetermined (und)" - Type "text:text" - 27 samples
Unknown Text Stream
 Size 0 x 0 - Translation X=0 Y=0 - Layer 0
    RFC6381 Codec Parameters: text
    All samples are sync

and for the second file

\* Movie Info *
    Timescale 1000 - 3 tracks
    Computed Duration 01:57:29.760 - Indicated Duration 01:57:29.760
    Fragmented File: no
    File suitable for progressive download (moov before mdat)
    File Brand mp42 - version 512
    Created: GMT Sat Jul 30 13:39:12 2016
    Modified: GMT Sat Jul 30 13:39:12 2016

File has no MPEG4 IOD/OD

iTunes Info:
    Encoder Software: HandBrake 0.10.2 2015090200
1 UDTA types: meta (1) 

Track # 1 Info - TrackID 1 - TimeScale 90000
Media Duration 01:57:29.760 - Indicated Duration 01:57:29.760
Track has 1 edit lists: track duration is 01:57:29.760
Media Info: Language "Undetermined (und)" - Type "vide:avc1" - 176244 samples
Visual Track layout: x=0 y=0 width=1010 height=422
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x21
AVC/H264 Video - Visual Size 710 x 422
    AVC Info: 1 SPS - 1 PPS - Profile Main @ Level 4
    NAL Unit length bits: 32
    Pixel Aspect Ratio 21845:15346 - Indicated track size 1010 x 422
    Chroma format YUV 4:2:0 - Luma bit depth 8 - chroma bit depth 8
    SPS#1 hash: EA4CDB1C10724A8D592EC3C564199C7569802852
    PPS#1 hash: 8C412D9B36B16186B36C96A052D45F2432B0757F
Self-synchronized
    RFC6381 Codec Parameters: avc1.4d4028
    Average GOP length: 86 samples

Track # 2 Info - TrackID 2 - TimeScale 48000
Media Duration 01:57:29.664 - Indicated Duration 01:57:29.664
Track has 1 edit lists: track duration is 01:57:29.642
Media Info: Language "English (eng)" - Type "soun:mp4a" - 330453 samples
1 UDTA types: name (1) 
MPEG-4 Config: Audio Stream - ObjectTypeIndication 0x40
MPEG-4 Audio AAC LC - 2 Channel(s) - SampleRate 48000
Synchronized on stream 1
    RFC6381 Codec Parameters: mp4a.40.2
Alternate Group ID 1
    All samples are sync

Track # 3 Info - TrackID 3 - TimeScale 1000
Media Duration 01:57:29.120 - Indicated Duration 01:57:29.120
Track has 1 edit lists: track duration is 01:57:29.120
Track is disabled
Media Info: Language "Undetermined (und)" - Type "text:text" - 21 samples
Unknown Text Stream
 Size 0 x 0 - Translation X=0 Y=0 - Layer 0
    RFC6381 Codec Parameters: text
    All samples are sync

If I then merge these two files using the command line I talked about above, I get a file that gives the following info

\* Movie Info *
    Timescale 1000 - 3 tracks
    Computed Duration 03:46:33.600 - Indicated Duration 03:46:33.600
    Fragmented File: no
    File suitable for progressive download (moov before mdat)
    File Brand M4V  - version 1
    Created: GMT Sat Jul 30 18:27:22 2016
    Modified: GMT Sat Jul 30 18:27:22 2016

File has root IOD (9 bytes)
Scene PL 0xff - Graphics PL 0xff - OD PL 0xff
Visual PL: ISO Reserved Profile (0x15)
Audio PL: AAC Profile @ Level 2 (0x29)
No streams included in root OD

Track # 1 Info - TrackID 1 - TimeScale 90000
Media Duration 03:38:48.600 - Indicated Duration 03:38:48.600
Track has 3 edit lists: track duration is 03:38:48.600
Media Info: Language "Undetermined (und)" - Type "vide:avc1" - 328214 samples
Visual Track layout: x=0 y=0 width=1015 height=424
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x21
AVC/H264 Video - Visual Size 714 x 424
    AVC Info: 1 SPS - 1 PPS - Profile Main @ Level 4
    NAL Unit length bits: 32
    Pixel Aspect Ratio 64:45 - Indicated track size 1015 x 424
    Chroma format YUV 4:2:0 - Luma bit depth 8 - chroma bit depth 8
    SPS#1 hash: 3523075FCABC05AE3056F84F3CBDC8777E720AE8
    PPS#1 hash: 8C412D9B36B16186B36C96A052D45F2432B0757F
Self-synchronized
    RFC6381 Codec Parameters: avc1.4d4028
    Average GOP length: 81 samples

Track # 2 Info - TrackID 2 - TimeScale 90000
Media Duration 03:38:48.504 - Indicated Duration 03:38:48.504
Track has 3 edit lists: track duration is 03:38:47.423
Media Info: Language "English (eng)" - Type "soun:mp4a" - 615350 samples
1 UDTA types: name (1) 
MPEG-4 Config: Audio Stream - ObjectTypeIndication 0x40
MPEG-4 Audio AAC LC - 2 Channel(s) - SampleRate 48000
Synchronized on stream 1
    RFC6381 Codec Parameters: mp4a.40.2
Alternate Group ID 1
    All samples are sync

Track # 3 Info - TrackID 3 - TimeScale 90000
Media Duration 03:19:57.857 - Indicated Duration 03:19:57.857
Track has 3 edit lists: track duration is 03:46:33.600
Track is disabled
Media Info: Language "Undetermined (und)" - Type "text:text" - 48 samples
Unknown Text Stream
 Size 0 x 0 - Translation X=0 Y=0 - Layer 0
    RFC6381 Codec Parameters: text
    All samples are sync

Here you can see that both the video and audio tracks are 03:38:48 in length which matches the sum of the lengths of the two parts. The chapter track is shown as having an "indicated duration" of 03:19:57 but a "track duration" of 03:46:33 which is approximately 8 minutes longer than it should be. When this file is played the length is reported as 3 hours and 46 minutes, but if you try and watch or seek past 03:38:48 it causes the player to stop, which makes sense as there is no audio or video data.

My feeling is that there is  a bug somewhere in the concatenation of the two chapter tracks causing the duration to be wrongly reported.

I have figured out a work around which might allow you to shed some light on the issue. Once I have the merged file I extract the chapter information to a TTXT file using the command

```
MP4Box -ttxt 3 merged.m4v
```

The resulting file looks fine and the last TextSample element has a sampleTime of 03:19:57.857 matching the indicated duration of the track.

The final stage is then to combine the audio and video from the merged file with this chapter track using the command

```
MP4Box -add merged.m4v#video -add merged.m4v#audio -add merged_3_text.ttxt:chap -new final.m4v
```

Extracting the info from this file gives

\* Movie Info *
    Timescale 1000 - 3 tracks
    Computed Duration 03:38:48.600 - Indicated Duration 03:38:48.600
    Fragmented File: no
    File suitable for progressive download (moov before mdat)
    File Brand M4V  - version 1
    Created: GMT Sun Jul 31 08:28:23 2016
    Modified: GMT Sun Jul 31 08:28:23 2016

File has root IOD (9 bytes)
Scene PL 0xff - Graphics PL 0xff - OD PL 0xff
Visual PL: ISO Reserved Profile (0x15)
Audio PL: AAC Profile @ Level 2 (0x29)
No streams included in root OD

Track # 1 Info - TrackID 1 - TimeScale 90000
Media Duration 03:38:48.600 - Indicated Duration 03:38:48.600
Track has 3 edit lists: track duration is 03:38:48.600
Media Info: Language "Undetermined (und)" - Type "vide:avc1" - 328214 samples
Visual Track layout: x=0 y=0 width=1015 height=424
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x21
AVC/H264 Video - Visual Size 714 x 424
    AVC Info: 1 SPS - 1 PPS - Profile Main @ Level 4
    NAL Unit length bits: 32
    Pixel Aspect Ratio 64:45 - Indicated track size 1015 x 424
    Chroma format YUV 4:2:0 - Luma bit depth 8 - chroma bit depth 8
    SPS#1 hash: 3523075FCABC05AE3056F84F3CBDC8777E720AE8
    PPS#1 hash: 8C412D9B36B16186B36C96A052D45F2432B0757F
Self-synchronized
    RFC6381 Codec Parameters: avc1.4d4028
    Average GOP length: 81 samples

Track # 2 Info - TrackID 2 - TimeScale 90000
Media Duration 03:38:48.504 - Indicated Duration 03:38:48.504
Track has 3 edit lists: track duration is 03:38:47.423
Media Info: Language "English (eng)" - Type "soun:mp4a" - 615350 samples
1 UDTA types: name (1) 
MPEG-4 Config: Audio Stream - ObjectTypeIndication 0x40
MPEG-4 Audio AAC LC - 2 Channel(s) - SampleRate 48000
Synchronized on stream 1
    RFC6381 Codec Parameters: mp4a.40.2
Alternate Group ID 1
    All samples are sync

Track # 3 Info - TrackID 3 - TimeScale 1000
Media Duration 03:38:48.600 - Indicated Duration 03:38:48.600
Track is disabled
Media Info: Language "Undetermined (und)" - Type "text:tx3g" - 48 samples
Unknown Text Stream
 Size 0 x 0 - Translation X=0 Y=0 - Layer 0
    RFC6381 Codec Parameters: tx3g
    All samples are sync

As you can see the chapter track now has an indicated duration that matches the audio and video tracks and this file plays perfectly in the media players I've tried. The only differences I can see are that the chapter track no longer has an edit list and is reported as type text:tx3g instead of text:text as well as the TimeScale being 1000 instead of 90000, but I'm not sure if any of those would cause the issue.

**Comment by rbouqueau** [comment]
> Track has 3 edit lists: track duration is 03:46:33.600

I'm pretty sure this doesn't work correctly in most players. Would you be able to share a sample so that I can reproduce? This way it makes it easier to help you use the right workflow or fix GPAC. Thanks

**Comment by greenwoodma** [comment]
Yes, I don't think it's the players that are at fault here, either I'm doing something stupid or GPAC is getting confused by what I'm doing. I'll try and put a small sample together for you to look at (the ones I had are all around 10GB in size!)

**Comment by rbouqueau** [comment]
Thank you.

Yes I think it is not related but the edit list stuff could lead to a/v sync issues so you might want to solve them too.

**Comment by rbouqueau** [comment]
Any news on getting a sample?

**Comment by greenwoodma** [comment]
Sorry about the delay and thanks for the reminder. I've now put together a small sample that shows the problem. You can grab the zip file from http://greenwoodma.servehttp.com/data/mp4box-merge-issue.zip

The zip files contains four files:

part1.m4v and part2.m4v: these are simple m4v files both of which have a chapter track
simple-merge.m4v: this is the result of simply using -cat to join the two files but results in a joined file of the wrong length
complex-merge.m4v: this uses the multi-step approach documented in my original post to join the two files which gives the correct length and chapter positions (i.e. the result I would expect from using the simple approach)

Hopefully that should help you look into the issue, but if you have any questions or need any more info please just ask.

**Comment by levicki** [comment]
I am not sure if this information will help and/or whether it deserves a separate issue, but there seems to be a similar problem with wrong total duration when muxing chapters together with audio and video.

With version 0.6.1-rev0-g72d766c-master I am getting total duration of 01:47:43 for 01:35:07 video and audio tracks when I mux with chapters in TTXT format where the last chapter timestamp is 01:30:24.160.

The curious part is that the previos chapter timestamp is 01:13:04.400. The difference between those is 00:17:19.760 and when you add that difference to the last chapter timestamp you get to 01:47:43.

Please let me know if I should open a separate issue for this or add more information here -- to me it seems that it might be the root cause for the problem reported here.

**Comment by rbouqueau** [comment]
More information is always welcome, we'll split if necessary :)

**Comment by levicki** [comment]
Ok, let me know what you need (chapters file, m4v structure, etc) and I will attach when I can.

**Comment by levicki** [comment]
@rbouqueau 
I don't know if it is of any help in narrowing down the problem but I just realized that the wrong total time bug exists only for 3GPP (TTXT) chapters format.

However, if I use -add ````"Chapters.txt:chap:lang=eng:name=Chapters"```` to import chapters in Ogg Vorbis format it works fine.

**Comment by vizzerdrix55** [comment]
I might have discovered a similar problem with wrong calculated duration after concatenating two MP4s

I have two files:

1. `intro.mp4` with a duration of 5 seconds
2. `content.mp4` with a duration of 00:42:24 (HH:MM:SS)

I concatenaded `intro.mp4` and` content.mp4` to a new file `combinedFile.mp4` using the following command on a windows:
`MP4Box -cat "intro.mp4" -cat "content.mp4" -new combinedFile.mp4`

When I open `combinedFile.mp4` in VLC Player or look at the duration in Windows Explorer it shows 4 seconds. When I play `combinedFile.mp4` it plays the whole duration of 00:42:29

You find the MP4 Box informations about the files here:

- [intro_mboxinfo.txt](https://github.com/gpac/gpac/files/3157589/intro_mboxinfo.txt)
- [combinedFile_mboxinfo.txt](https://github.com/gpac/gpac/files/3157590/combinedFile_mboxinfo.txt)
- [content_mboxinfo.txt](https://github.com/gpac/gpac/files/3157591/content_mboxinfo.txt)

The expected behaviour would be to show the right duration of 00:42:29 in VLC Player and Windows Explorer which is not the case.

You can download one of the mp4's here. I'm not able to upload content.mp4 nor combinedfile.mp4 because there is copyright protected material on them. Sorry for this but you might be able to analyse the problem with the mboxinfo-files, When I cut the file `content.mp`4 (e.g. just the first 5 seconds) there is no unexpected behaviour. This might be important for fixing the bug.
- [intro.mp4](https://drive.switch.ch/index.php/s/yZOagl6DJwTZeHo) (286 KB)

I don't know if this has something to do with chapter tracks, so please feel free to split to a separate issue.

System informations:
MP4Box - GPAC version 0.7.0-rev0-gbd5c9af-master
Windows 10 Pro

PS: the file content.mp4 is a TV-capture with different audio tracks (german and french) on each channel. This is intended

**Comment by jeanlf** [comment]
should now be fixed, thanks for the files
