### ISSUE TITLE
Make a static build of MP4Box easier

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#6]
...a and add to the https://travis-ci.org/gpac/gpac/builds/42405732

And notifiy at https://sourceforge.net/p/gpac/bugs/341/ (related to #5)

**Comment by cconcolato** [comment]
Adding the commit reference: 91dd9f6 

The TravisCI configuration looks weird to me. Why do we need all the packages like x11 ... to build mp4box statically? 

Also TravisCI does not need a make clean, it starts with a clean virtual machine.

**Comment by jeanlf** [comment]
--static-mp4box will not use all modules, but the configure does not change (hence the display of the detected config). 

are you sure a clean VM is used with each env ? we had bugs on travisCI before the make clean was introduced (https://travis-ci.org/gpac/gpac/builds/50523813) 
anyway it doesn't hurt to add this
