### ISSUE TITLE
Segfault on Archlinux

### ISSUE THREAD

**Issue by jowehrli** [gpac/gpac#60]
Hi,

When I try to run MP42TS on the last GPAC version with : *./bin/gcc/MP42TS -src ~/Downloads/Burn.mp4 -dst-rtp 234.0.0.10:50004* I've got a segfault just after the little "waiting time" (buffering?).

I run **gdb** with : *gdb -arg ./bin/gcc/MP42TS -src ~/Downloads/Burn.mp4 -dst-rtp 234.0.0.10:50004*

The backtrace shows this : 

* 0x00007ffff6f308f4 in pthread_mutex_lock () from /usr/lib/libpthread.so.0*
* 0x00007ffff7a06706 in ?? () from /usr/local/lib/libgpac.so.4*
* 0x00007ffff7a16f10 in gf_m2ts_mux_process () from /usr/local/lib/libgpac.so.4*
* 0x0000000000405940 in main ()*

I have the libpthread v. 2.21.

Does anyones have any informations about this?

**Comment by jeanlf** [comment]
I cannot reproduce this here, it's likely an issue with the input mp4 file. Could you post it somewhere ?

**Comment by jowehrli** [comment]
Yes, you can download the file [Here](https://drive.switch.ch/public.php?service=files&t=14166d119373f9e750641d29aff4668e)

**Comment by jeanlf** [comment]
Hmm just tried on Arch x64 but no pb here (alos using libpthread-2.21) - are you using 64bits arch linux?

**Comment by jowehrli** [comment]
Yes I used the arch 64.

**Comment by rbouqueau** [comment]
An idea would be to run Valgrind with ```--tool=helgrind```. It should be able to detect if MP42TS did something wrong with concurrency.

@jowehrli Can you give it a try?

**Comment by jowehrli** [comment]
Yes of course.

I run valgrind with : *valgrind --tool=helgrind ./bin/gcc/MP42TS -src ~/Downloads/Burn2.mp4 -dst-rtp 234.0.0.10:50004*

This is the result : 

==18071== Helgrind, a thread error detector
==18071== Copyright (C) 2007-2013, and GNU GPL'd, by OpenWorks LLP et al.
==18071== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==18071== Command: ./bin/gcc/MP42TS -src /home/jowehrli/Downloads/Burn2.mp4 -dst-rtp 234.0.0.10:50004
==18071== 
Setting up program ID 1 - send rates: PSI 200 ms PCR 100 ms - PCR offset 0
PID: 101
PID: 102
==18071==   13029 - TS time  13440 - avg bitrate        0
==18071== Process terminating with default action of signal 11 (SIGSEGV)
==18071==  Access not within mapped region at address 0x74F7
==18071==    at 0x5ADD8F4: pthread_mutex_lock (in /usr/lib/libpthread-2.21.so)
==18071==    by 0x4C31948: pthread_mutex_lock (in /usr/lib/valgrind/vgpreload_helgrind-amd64-linux.so)
==18071==    by 0x5056C05: ??? (in /usr/local/lib/libgpac.so.4.2.0)
==18071==    by 0x50677EF: gf_m2ts_mux_process (in /usr/local/lib/libgpac.so.4.2.0)
==18071==    by 0x40593F: main (in /home/jowehrli/Test/gpac-master/bin/gcc/MP42TS)
==18071==  If you believe this happened as a result of a stack
==18071==  overflow in your program's main thread (unlikely but
==18071==  possible), you can try to increase the size of the
==18071==  main thread stack using the --main-stacksize= flag.
==18071==  The main thread stack size used in this run was 8388608.
==18071== 
==18071== For counts of detected and suppressed errors, rerun with: -v
==18071== Use --history-level=approx or =none to gain increased speed, at
==18071== the cost of reduced accuracy of conflicting-access information
==18071== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)

**Comment by rbouqueau** [comment]
Thanks. Would would be able to make a debug build so that we can see the file/line where the error occurs?

@jeanlf do you have a VM for this distrib?

**Comment by jeanlf** [comment]
yes, virtualbox, gpac debug build, no errors seen so far

**Comment by rbouqueau** [comment]
@jeanlf Do you get the same error with Helgrind?

**Comment by jowehrli** [comment]
I find the problem. It was the libgpac.so.4 in */usr/local/lib/libgpac.so.4*. This library was from a previous installation (the last SVN version I guess).

So I guess there is an incompability between this 2 versions.

If a run a *make install* command, my problem is gone.

Thank you for the help.

**Comment by rbouqueau** [comment]
Ok, thank you for your feedback. There may be an ABI mis-numbering from our side too.
