### ISSUE TITLE
GPAC DASH sequences cause decoder errors on Mac

### ISSUE THREAD

**Issue by joeyparrish** [gpac/gpac#600]
[GPAC's DASH sequences](https://gpac.wp.mines-telecom.fr/2012/02/23/dash-sequences/) cause decoder errors on Safari.  For example, ["live profile with bitstream switching support, Audio+Video"](http://download.tsi.telecom-paristech.fr/gpac/DASH_CONFORMANCE/TelecomParisTech/mp4-live/mp4-live-mpd-AV-BS.mpd) and ["main profile, multiple files with bitstream switching support, Audio+Video"](http://download.tsi.telecom-paristech.fr/gpac/DASH_CONFORMANCE/TelecomParisTech/mp4-main-multi/mp4-main-multi-mpd-AV-BS.mpd).  (We have not exhaustively tested all sequences GPAC hosts, so there may be others.)

[Shaka Player](https://github.com/google/shaka-player) is using these as test vectors to ensure compatibility with GPAC, but our tests for these fail on Safari.  As far as we can tell, there are two features that make the failing GPAC vectors unique in our tests: multiple SPS/PPS in the init segments, and no sample duration.

Would you consider regenerating your vectors without these features for Safari compatibility?  Or if you don't want to completely replace them, would you consider generating variants of these vectors that work with Safari?

Since these work fine on Chrome and Firefox on Mac, I am about to file a bug on WebKit about this.  I will update here with a link once I've done so.

**Comment by joeyparrish** [comment]
https://bugs.webkit.org/show_bug.cgi?id=160459

**Comment by joeyparrish** [comment]
Correction: These work on Chrome & Firefox on other platforms, but not on Mac.  So the content seems to be incompatible not with Safari, but with the platform's H.264 decoder.

**Comment by blacktrash** [comment]
Safari does not support avc3, and in recent versions finally reports this correctly returning `false` for `MediaSource.isTypeSupported("video/mp4;codecs=avc3.42c01e")`.
Chrome and Firefox use their own decoders, and I've seen avc3 work in these.
avc3 is/may also be not supported in IE11: https://github.com/gpac/gpac/issues/345 - therefore I tend to use `-bs-switching no`.

**Comment by cconcolato** [comment]
> no sample duration

In those segments, the sample duration is indicated in moov/mvex/trex/default_sample_duration. Is it problematic for Safari? MP4Box has the option `-no-frags-default` to avoid using trex defaults (as Smooth Streaming does not seem to like that either). We could add sequences for that.

> multiple SPS/PPS in the init segment

What do you mean? These sequences uses "avc1" so indeed SPS/PPS are in the init segment. And "avc3" does not seem supported (check https://cconcolato.github.io/media-mime-support/), so don't know what we should do here.

**Comment by cconcolato** [comment]
If you meant that in bitstream switching mode, [this init segment](http://download.tsi.telecom-paristech.fr/gpac/DASH_CONFORMANCE/TelecomParisTech/mp4-live/mp4-live-mpd-AV-BS_set1_init.mp4) has multiple PPS/SPS. Yes, but given that the picture size changes, what do you want us to do (if "avc3" is not supported)?

**Comment by blacktrash** [comment]
Sorry, I believed bs switching meant avc3, maybe I was mistaken.
I can confirm that the streams do not work in Safari and Firefox 48, but they do work in Chrome on Mac here.

**Comment by TheModMaker** [comment]
Does the picture size change within a stream?  The same init segment is used for different streams which is why there are multiple SPS/PPS.   Usually, each stream has its own init segment that has a single SPS/PPS.

I encoded a stream (using a modified [shaka packager](https://github.com/google/shaka-packager)) with  a single SPS and the same stream using multiple SPS (added a fake one that was not used) and the stream failed to play on Safari.  The only difference was the contents of the decoder configuration `avcC` box.

As for sample duration, when I put the generated media through ffmpeg, it says `Encoder did not produce proper pts, making some up`.  I see that it uses default frame duration, but it may not be supported on Mac.  It would be good to add some example streams without default duration to see if that is the problem.

**Comment by rbouqueau** [comment]
Is there still something to do here?

**Comment by joeyparrish** [comment]
I just retested on both Chrome and Firefox on Mac.  Both still fail to decode, so [the findings in my earlier comment](https://github.com/gpac/gpac/issues/600#issuecomment-237020515) are still the case.

**Comment by jeanlf** [comment]
I don't think we will change these sequences, they are correct.
