### ISSUE TITLE
GPAC SSL cert has invalid date

### ISSUE THREAD

**Issue by joeyparrish** [gpac/gpac#601]
To reproduce:

1. Use Chrome to open https://download.tsi.telecom-paristech.fr/gpac/DASH_CONFORMANCE/TelecomParisTech/mp4-main-ogop/mp4-main-ogop-mpd-AV-BS.mpd
2. Chrome reports "Your connection is not private" and "NET::ERR_CERT_DATE_INVALID"
3. Click "NET:ERR_CERT_DATE_INVALID" to expand details
4. See "Expires on: Feb 2, 2016"

This expired cert prevents access of these assets from secure domains, such as https://shaka-player-demo.appspot.com/demo/

**Comment by jeljeli** [comment]
HI @joeyparrish 

We updated the SSL cert and the problem should be fixed now.

**Comment by joeyparrish** [comment]
Awesome, thanks!
