### ISSUE TITLE
spurious dependency on libavdevice in gm_ffmpeg_in.so (gpac-libs)

### ISSUE THREAD

**Issue by sergiomb2** [gpac/gpac#602]
still present on gpac-libs-0.6.1,  all detail in this link: https://bugzilla.rpmfusion.org/show_bug.cgi?id=3366
Patch propose here: https://bugzilla.rpmfusion.org/attachment.cgi?id=1453

Hope get some feedback 

Thanks.

**Comment by rbouqueau** [comment]
Applied, thanks!
