### ISSUE TITLE
GPAC Dashcast read from buffer, and output to buffer

### ISSUE THREAD

**Issue by Victordmdb** [gpac/gpac#603]
Dashcast can take inputs from files or URLs, but if I would like to integrate it into another program, can it take as input a buffer and output to another buffer or a socket?

I've been looking at the code and it seems like it is mainly for cli, or am I wrong?

**Comment by Victordmdb** [comment]
As for input, I've found that avformat_open_input can take a dummy file  and read from mem:
http://stackoverflow.com/questions/9604633/reading-a-file-located-in-memory-with-libavformat

**Comment by Victordmdb** [comment]
Here is an example from ffmpeg for using a buffer as input
http://www.ffmpeg.org/doxygen/trunk/doc_2examples_2avio_reading_8c-example.html

**Comment by jeanlf** [comment]
dashcast is deprecated use GPAC 0.9.0 DEV
