### ISSUE TITLE
when generate the dash segment by using GPAC, sbgp box's group description index is turns into 1 instead of 65537

### ISSUE THREAD

**Issue by RavikiranMuniraj** [gpac/gpac#607]
Hi

I am trying to create the playready dash content using GPAC latest releasae v0.6.2

I have generated the drm xml file by using one of the online tool. My drm.xml file will looks like below

```xml
<GPACDRM type="CENC AES-CTR">
  <DRMInfo type="pssh" version="0">
    <BS ID128="9a04f07998404286ab92e65be0885f95"/>
    <BS bits="32" endian="little" value="768"/>
    <BS bits="16" endian="little" value="1"/>
    <BS bits="16" endian="little" value="1"/>
    <BS bits="16" endian="little" value="758"/>
    <BS data64="PABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgBBAEEAQQBBAEUAQQBBAFEAQQBCAEEAUQBBAEIAQQBBAEEAQQBBAEEAQQBRAD0APQA8AC8ASwBJAEQAPgA8AEMASABFAEMASwBTAFUATQA+ADUAVAB6AEkAWQBRADIAaAByAE8AWQA9ADwALwBDAEgARQBDAEsAUwBVAE0APgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcAA6AC8ALwBwAGwAYQB5AHIAZQBhAGQAeQAuAGQAaQByAGUAYwB0AHQAYQBwAHMALgBuAGUAdAAvAHAAcgAvAHMAdgBjAC8AcgBpAGcAaAB0AHMAbQBhAG4AYQBnAGUAcgAuAGEAcwBtAHgAPwBQAGwAYQB5AFIAaQBnAGgAdAA9ADEAJgBhAG0AcAA7AGEAbQBwAFUAcwBlAFMAaQBtAHAAbABlAE4AbwBuAFAAZQByAHMAaQBzAHQAZQBuAHQATABpAGMAZQBuAHMAZQA9ADEAPAAvAEwAQQBfAFUAUgBMAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA="/>
  </DRMInfo>
  <CrypTrack IV_size="8" first_IV="0xb20688aa36c9c132" isEncrypted="1" saiSavedBox="senc" trackID="1">
    <key KID="0x10000000100010001000100000000001" value="0x3a2a1b68dd2bd9b2eeb25e84c4776668"/>
  </CrypTrack>
</GPACDRM>
```
**Command used to generate the encrypted content :** 
MP4Box -crypt drm.xml mp4-onDemand-h264bl_low.mp4 -out mp4-onDemand-h264bl_low_playready.mp4

**Command used to generate the dash content :**
MP4Box -frag 10000 -dash 30000 -profile onDemand -segment-name segment_file mp4-onDemand-h264bl_low_playready.mp4

**Command used to generate to see the box information :**
MP4Box -diso <segment file name>

```xml
<BoxInfo Size="28" Type="sbgp"/>
<FullBoxInfo Version="0" Flags="0x0"/>
<SampleGroupBoxEntry sample_count="72" group_description_index="1"/>
</SampleGroupBox>
```
According to the ISO BMFF spec, Section 8.9.4, the group description indexes in the 'sbgp' boxes must start at 0x10001. i.e., 65537
[](https://sourceforge.net/p/gpac/bugs/300/)

Please confirm which GPAC software release have the fix for this

**Comment by jeanlf** [comment]
No, the code is correct: sample group description index in SampleToGroupBox start at 0x10001 for entries refering to SampleGroupDescriptionBox entries defined in the movie fragment, but start at 0 for the ones defined in the movie sample table, as is your case here. If you want to force sample group descriptions in movie fragments, use -sample-groups-traf option
