### ISSUE TITLE
temp directory not being cleaned up

### ISSUE THREAD

**Issue by stax76** [gpac/gpac#61]
mp4box writes files to the temp dir using filenames such as gpac_00302fa0.tmp, these files are large and remain after mp4box terminates, what's interesting is it happens only when mp4box is executed by a GUI such as StaxRip or MeGUI.

**Comment by jeanlf** [comment]
No clue where that could come from, as it cannot be reproduced with MP4Box ... Any hint from the authors of these GUI wrappers ?

**Comment by stax76** [comment]
I searched my code for  gpac and tmp and stepped through it with the debugger so I'm 99% sure it's not my GUI writing these files.

**Comment by rbouqueau** [comment]
Interesting. By any chance, did you see some error messages or did you record any log?

I have updated the naming of temporary files recently May or June 2015) because of possible name collisions (very rare due to error randomization).

I have also notice a Windows-only issue with ProcessMonitor for MPEG-DASH .mpd.tmp: just after the file is created, Windows (explorer.exe) locks it for a short amount of time which might lead to an error. Do you know if it would be possible to run MP4Box in a directory so that no service is scruiting the folder? Could anyone seeing the issue could try to monitor what happens with the files? https://technet.microsoft.com/en-us/library/bb896645.aspx

**Comment by DigitalPhreaker** [comment]
Hi rbouqueau,

Just saw your reply; thanks for the information and I'll run a test right now with Process Monitor running to let you know what happens.

**Comment by camkego** [comment]
I also see this same issue. Each run of mp4box leaves a temp file in C:\Users\username\AppData\Local\Temp\2

**Comment by rbouqueau** [comment]
@camkego @all please check for testcases so that we can reproduce. There must be a leak in a handle. We'll try to watch this more carefully (if you build and run GPAC with the mem-tracker you should be able to see these leaks).

**Comment by camkego** [comment]
@rbouqueau here is a reproduction using today's release [gpac-0.5.2-DEV-rev623-g1ede7f5-master-x64.exe]

This reproduction shows the un-deleted temp file left behind in the user's temp directory after packing an MP4 using mp4box -add a.h264 -add b.aad -new outname.mp4
This file should have been deleted, but it was not.

It is simple to reproduce the issue with the following steps, the issue appears to happen consistently and 100% of the time for me.


1. Confirm temp dir is clean
2. Extract h264 from BigBuckBunny
3. Extract AAC from BBB
4. Confirm temp dir is clean
5. Re-package into a new MP4 using mp4box
6. Directory command show un-deleted, un-cleaned up temporary file left behind

![image](https://cloud.githubusercontent.com/assets/868689/9772015/8bb2b436-56ee-11e5-946b-51c6afad7fba.png)

Please let me know if I can help further.

**Comment by rbouqueau** [comment]
Thank you. Hopefully I can reproduce with the GPAC mem tracker:
```
E:\Users\rbouqueau\Documents\Works\tmp>C:\Works\gpac\gpac_private\gpac_public\bin\x64\Debug\mp4box.exe -mem-track -add BigBuckBunny_320x180.mp4 -add BigBuckBunny_320x180_track2.aac -new tmp.mp4
IsoMedia import BigBuckBunny_320x180.mp4 - track ID 1 - Video (size 320 x 180)
IsoMedia import BigBuckBunny_320x180.mp4 - track ID 2 - Audio (SR 48000 - 2 channels)
AAC ADTS import  - sample rate 48000 - MPEG-4 audio - 2 channels
Saving tmp.mp4: 0.500 secs Interleaving

[MemTracker] Printing the current state of allocations (1 open file handles) :
[MemTracker] Memory Block 000000000049FA30 (size 4) allocated
        in file ..\..\src\isomedia\isom_read.c at line 664
        string dump: und
[MemTracker] Memory Block 000000000049FA70 (size 4) allocated
        in file ..\..\src\isomedia\isom_read.c at line 664
        string dump: und
[MemTracker] Total: 8 bytes allocated in 2 blocks
```

**Comment by rbouqueau** [comment]
Should be ok now. Let me know otherwise. Thanks all for your patience and reproducable test cases.

**Comment by camkego** [comment]
I tested against gpac-0.5.2-DEV-rev649-g361314a-master-x64, issue appears fixed. Thank you for fixing.
Cameron
