### ISSUE TITLE
mp4box uses incorrect frame rate when dashing H.265 content

### ISSUE THREAD

**Issue by sandersaares** [gpac/gpac#610]
Version: 0.6.2-DEV-rev683-g7b29fbe-master
Command: `mp4box -dash-strict 4000 -profile "dashavc264:live" in_short-H265-288-400k.mp4 -out out\Manifest.mpd`
Input file: [in_short-H265-288-400k.zip](https://github.com/gpac/gpac/files/432209/in_short-H265-288-400k.zip)

Actual result: content is marked as being encoded at 25 fps.
Expected result: content is marked as being encoded at 29.97 fps.

Generated output:

```xml
 <AdaptationSet segmentAlignment="true" maxWidth="512" maxHeight="288" maxFrameRate="25" par="16:9" lang="und">
   <Representation id="1" mimeType="video/mp4" codecs="hev1.2.4.L63.90" width="512" height="288" frameRate="25" sar="1:1" startWithSAP="1" bandwidth="405793">
    <SegmentTemplate timescale="1200000" media="in_short-H265-288-400k_dash$Number$.m4s" startNumber="1" duration="4727041" initialization="in_short-H265-288-400k_dashinit.mp4"/>
   </Representation>
  </AdaptationSet>
```

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by rbouqueau** [comment]
MP4Box infers the duration of the samples (hence the frame rate) based on the duration of the mp4 samples (the second one in most cases) divided by the timescale.

In your source MP4:
```
Timescale = 1200000
```
```
Sample 0 duration: 48000
Sample 1 duration: 48000
Sample 2 duration: 40041
Sample3 duration: 40040
...
```

Inferred framerate: 1200000 / 48000 = 25.

Do you have an idea why the muxer starts at 25fps before switching at frame 3? Is there something we can deduce to improve mp4box?

**Comment by sandersaares** [comment]
Thanks for fast reply! The original timing is generated by x265 - from raw YUV frames combined with an fps value - so I suppose the key to the mystery is in the x265 timing logic. Interesting - I did not realize frame rate was not explicitly signaled but is instead calculated based on sample durations.

Other tools (FFprobe, MediaInfo, mp4info) appear to give a value close to 29.97 for the frame rate for this input file. Perhaps there might be some value in mp4box using similar logic in order to have behavior similar to other tools?

**Comment by rbouqueau** [comment]
> Perhaps there might be some value in mp4box using similar logic in order to have behavior similar to other tools?

We could consider the global duration. But this may not be so easy to compute (already fragmented content, etc.). Let me check with the rest of the team.

**Comment by rbouqueau** [comment]
> The original timing is generated by x265

1) How did you check that?
2) Do you know which muxer was used?

**Comment by sandersaares** [comment]
I am perhaps not understanding what exactly you are asking. Here is how this test file was generated: I took a file with raw YUV frames, provided it to x265, provided an `--fps 29.97` parameter and x265 generated an H.265 data stream, for which FFprobe reports the same timestamps as you did above.

**Comment by rbouqueau** [comment]
> x265 generated an H.265 data stream, for which FFprobe reports the same timestamps as you did above.

IIUC ffprobe executed on the raw H265, correct?

**Comment by sandersaares** [comment]
Right.

**Comment by rbouqueau** [comment]
Did you have the opportunity to report the issue to them?

**Comment by sandersaares** [comment]
I lack the detailed understanding of media timing necessary to communicate this issue to x265 (if there even is one). I suspect, since every tool that I have tried - besides mp4box - does treat the output as 29.97 fps, they would just say working as intended.
