### ISSUE TITLE
DashCast couldn't process the input of RTP or UDP Stream via VLC (Live system dropped a video frame)

### ISSUE THREAD

**Issue by mindole** [gpac/gpac#611]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!
- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

The GPAC version tested : gpac_0.6.2-DEV-rev683-g7b29fbe-master_amd64.deb
Issue description : 
DashCast couldn't generate any segment files, init file and mpd file for input Stream of UDP/RTSP from VLC player

You can reproduce this issue with following steps  :

Test Case 1. :  Not working
// Transcode the input stream, display the transcoded stream and send it to a multicast IP address
%vlc -vvv Animation.mp4 --network-caching=10 --sout '#transcode{vcodec=h264,venc=x264{keyint=25,idrinit=25,bframes=0,ref=1,hrd=cbr,crf=28,vb=4500,preset=ultrafast,tune=zerolatency,vbv-maxrate=5500},fps=25.00,threads=48,deinterlace,audio-sync}:duplicate{dst=display,dst=udp{caching=10,mux=ts,dst=127.0.0.1:9092,name="testTS2"}}'
// To capture UDP streams and transcode and segment it in 1000-millisecond segments for a live service:
# DashCast -v "udp://@127.0.0.1:9092?fifo_size=100000" -live -low-delay -frag 200 -insert-utc -seg-marker eods -min-buffer 0.2 -ast-offset -800 -pixf yuv420p

Test Case 2 : Not working
// Transcode the input stream, display the transcoded stream and send it to RTP Streams
% vlc -vvv Animation.mp4 --sout='#transcode{vcodec=h264,vb=0,scale=0}:duplicate{dst=display,dst=rtp{sdp=rtsp://:8554/session.sdp}}'
// To capture RTP streams and segment it, stored the log to log.txt
DashCast -v rtsp://@localhost:8554/session.sdp -live -log-file log.txt

Test Case 3 : Not working
// Without Transcode the input stream, display the transcoded stream and send it to RTP Streams
% vlc -vvv Animation.mp4 --sout='#duplicate{dst=display,dst=rtp{sdp=rtsp://:8554/session.sdp}}'
// To capture RTP streams and segment it, stored the log to log.txt
DashCast -v rtsp://@localhost:8554/session.sdp -live -log-file log.txt

Please find the attachment (log.txt and DashCast_RTSP.PNG) for Test Case 2 in the link below : 
https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by jeanlf** [comment]
dashcast is deprecated use GPAC 0.9.0 DEV
