### ISSUE TITLE
GPAC 0.5.0 error when installing on Ubuntu MATE (Odroid XU4, armv7)

### ISSUE THREAD

**Issue by mensurdurakovic** [gpac/gpac#612]
Hi! I want to install GPAC 0.5.0 version on Ubuntu MATE on Odroid XU4. I only use this version because -dev versions have some bugs when merging videos). So far, I have successfully installed it on Rasbian and Ubuntu 14.04. but I have problems when trying to install it on this distro for Odroid.
I have .zip file with 0.5.0 version and what I am doing is, after I extract it:

```
cd gpac
chmod +x configure
./configure --disable-opengl --use-js=no --use-ft=no --use-jpeg=no --use-png=no --use-faad=no --use-mad=no --use-xvid=no --use-ffmpeg=no --use-ogg=no --use-vorbis=no --use-theora=no –use-openjpeg=no
sudo make
sudo make install
sudo cp bin/gcc/libgpac.so /usr/lib
MP4Box -version 
```

but now when I try 

sudo make

it runs but after some time, I get this error message:

```
/usr/bin/ld: utils/os_divers.o: relocation R_ARM_THM_MOVW_ABS_NC against `__stack_chk_guard' can not be used when making a shared object; recompile with -fPIC
utils/os_divers.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:292: recipe for target 'libgpac.so' failed
make[1]: *** [libgpac.so] Error 1
make[1]: Leaving directory '/home/pi/gpac/src'
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 2
```

I have tried with options --with-pic=no and --enable-shared when running ./configure script
Any way to fix this ? Any help would be appreciated ?

**Comment by rbouqueau** [comment]
Hi,

Before anyone else answers your question, may I ask you details about this:

> I only use this version because -dev versions have some bugs when merging videos

We'd be happy to fix these issues. Have they already been reported?

We only provide support for master and the latest release (0.6.1 as of today).

> /usr/bin/ld: utils/os_divers.o: relocation R_ARM_THM_MOVW_ABS_NC against `__stack_chk_guard' can not be used when making a shared object; recompile with -fPIC

Did you try to rebuild with -fpic? Add ```--extra-cflags="-fPIC -DPIC``` to your configure.

**Comment by rbouqueau** [comment]
Any news here?

**Comment by jeanlf** [comment]
Is this still the case with latest git ?
