### ISSUE TITLE
MP4Box returning incorrect Return Code

### ISSUE THREAD

**Issue by richardbushell** [gpac/gpac#613]
I seem to be getting INCORRECT return codes occasionally from within my CMD batch script when using: MP4Box -brand

I'm guessing that very occasionally Windows may not have quite released the Write Process Lock after the previous CMD statement writing an mp4 file.

MP4Box -brand should be overwriting my original file, and I note it uses this process:
It first creates a temporary file named with the prefix 'out_' e.g. out_file.mp4
Then it tries to remove/delete the original file.
Then rename the temporary file to the original name.

WHEN THIS PROCESS FAILS IT STILL RETURNS A RETURN CODE OF 0 (for SUCCESS)
(e.g if the original file is read-only, or perhaps it's still locked because it's not yet been released by Windows writing process, or maybe even a read error when trying to execute the command internally.)

I tested this by making the original file read-only. MP4Box -brand failed of course. But I still got a Return Code of 0 for success.

I am mis-interpreting this problem? Or if not, then perhaps a default failed Return Code of 1 should be pre-set internally until MP4Box completes it's processing, and then finally a Return 0 issued only if it has definitely completed successfully.

Please advise.

**Comment by rbouqueau** [comment]
We need to reproduce to be able to fix. Could you please provide a simple patch or script (batch or sh) so that we can reproduce?

Also please detail your MP4Box version. I made improvements about the parallel processing of MP4Box on Windows. There were concurrency issues in the tmp folder (windows only).

**Comment by richardbushell** [comment]
As I stated the simplest way to reproduce is to make the source   file.mp4   read-only.
Then:-
MP4Box  -brand  mp42:0  file.mp4
(fails of course as it's read only).
But you still get a Return Code of 0 for success, when reading the errorlevel on the next CMD line.

**Comment by rbouqueau** [comment]
Thanks for the precise instruction. It should be fixed now.
