### ISSUE TITLE
Dashing reports audioSamplingRate as half of expected value with HE-AAC v2

### ISSUE THREAD

**Issue by sandersaares** [gpac/gpac#614]
Command: mp4box -dash-strict 4000 -profile "dashavc264:live" -out out\Manifest.mpd audio.mp4
Input: [audio.zip](https://github.com/gpac/gpac/files/444571/audio.zip)

The input is a 48000 Hz HE-AAC v2 stream. The output has audioSamplingRate of 24000 Hz marked in the manifest. I would have expected a value of 48000, instead.

```
<Representation id="1" mimeType="audio/mp4" codecs="mp4a.40.29" audioSamplingRate="24000" startWithSAP="1" bandwidth="65106">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <SegmentTemplate timescale="24000" media="audio_dash$Number$.m4s" startNumber="1" duration="95232" initialization="audio_dashinit.mp4"/>
   </Representation>
```

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by sandersaares** [comment]
Ah, I assume this is due to the backwards compatibility features of AAC, so HE-AAC v2 at 48 KHz is seen as AAC-LC at 24 KHz by older players. Sounds like mp4box takes the sampling rate info from the wrong place?

```
    MPEG-4 Audio Decoder Config:
      Sampling Frequency: 24000
      Channels: 1
      Extension:
        Object Type: Spectral Band Replication
        SBR Present: yes
        PS Present:  yes
        Sampling Frequency: 48000
```

**Comment by rbouqueau** [comment]
Ok it seems like DASH-IF clarified this part in their latest doc: http://dashif.org/wp-content/uploads/2016/06/DASH-IF-IOP-v3.3.pdf :+1: 
```@au-
2 dioSamplingRate signals the resulting sampling rate after SBR is applied```
