### ISSUE TITLE
DashCast sound grabbing issues

### ISSUE THREAD

**Issue by lenovo101** [gpac/gpac#615]
Hi all,

I am trying to perform a screen+sound capture and stream as a mpeg-dash feed with DashCast. When I try to capture sound from m laptops microphone I get the following message:

**[AVAudioResampleContext @ 0x7f8984000c60] Invalid input channel layout: 0
Could not open the audio resampler. Aborting.
An error occurred while reading audio frame.**

The command I use is DashCast -vf x11grab -vfr 25 -v :1.0 -a plughw:1,0 -af alsa -npts -time-shift -1 -low-delay -frag-dur 1000 -seg-dur 1000 -live

Is there any way I can specify which channel layout to use? Also, if I wish to intercept audio playing through my sound card and use it for the dash stream what would I have to type?

Thanks.

Version: 0.5.2 -426-gc5ad4e4+dfsg5-1build1

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!
- [ ] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
dashcast is deprecated use GPAC 0.9.0 DEV
