### ISSUE TITLE
Asking for help on output part 

### ISSUE THREAD

**Issue by zecheng-li** [gpac/gpac#617]
Hi,I am a beginner in this area, I know this is not a bug but forgive me in advance because I really think this thing for a long time.  My professor told me to build a streaming system that using webcam or MP4 file through the dashcast transfer to a server( so is my localhost, which is /var/www/html,etc), and says that all the people can access the address on my localhost to see my streaming.
And I am using this code currently:
DashCast -v /var/www/html/test1.mp4 -seg-dur 500 -live-media -out output -mpd /var/www/html/test1.mpd

It gives me a lot of [dashcast] Live system dropped a video frame
And [Core] system failure for file opening of output//var/www/html/test1.mpd in mode w: 2

Would you guys please give me some guidances? About this? Or give me an example to follow, because I am really eager to know the answer of it.

**Comment by jeanlf** [comment]
try -out /var/www/html/ -mpd test1.mpd
for the live system warning, try changing the capture frame rate
