### ISSUE TITLE
Muxing TTML IMSC1 Image Profile subtitles with MP4Box

### ISSUE THREAD

**Issue by ghost** [gpac/gpac#619]
When I try to mux a TTML XML file with associated PNG subtitles, MP4Box shows the following error.

`[EBU-TTD] No sample imported. Might be an error. Check your content.`

But muxing TTML text subtitles works correctly. My GPAC software's version is `0.6.1-rev0-g72d766c-master`.

**Comment by rbouqueau** [comment]
The feature is not supported. We can only parse EBU-TTD. Please read http://gpac.io/2014/08/23/ebu-ttd-support-in-gpac/ and http://gpac.io/2014/09/04/subtitling-with-gpac/ and let's see how we can progress on this.

**Comment by rbouqueau** [comment]
Hi, after a discussion with @cconcolato I am more aware of the IMSC image profile. There will be some progress when we find some resources to implement it.

**Comment by kit90** [comment]
Thanks for looking into this issue.  IIRC, currently GPAC (or ffmpeg/libav) cannot play back an TTML track muxed inside MP4 or extract this track as a single XML document. It would be great if these features could be added in GPAC too. By the way, recent TVs and Blu-ray Players from [Samsung](http://skp.samsungcsportal.com/integrated/popup/FaqDetailPopup3.jsp?seq=1044217&cdsite=in&status=A) support playback of MP4 with embedded TTML. If someone has these players, it might be helpful in testing. :)

**Comment by sdroege** [comment]
ISMC1 (and SMPTE S2052-1) images should be placed as a sub-sample into the container according to ISO 14496-30. Question is how the import should work then, only handle base64 encoded in-XML images? Or have a way to provide external PNGs?

**Comment by jeanlf** [comment]
TTML image embedding in MP4 is now supported (playback not yet supported), feedback welcome !

**Comment by nithin-mk** [comment]
Thanks @jeanlf ! :-) I'm the creator of this issue. My previous GitHub account got deleted; so I couldn't get the notification in time. I will test this and let you know!
