### ISSUE TITLE
MP4Box generating an invalid file that can't play properly

### ISSUE THREAD

**Issue by jyavenard** [gpac/gpac#622]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!
- [ ] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: 

Download file at https://people.mozilla.org/~jyavenard/mediatest/testi.mp4

run: MP4Box -dash 1000 -frag-rap -rap testi.mp4 

now attempt to play the generated file, this causes failure with various media framework.
Attempting to play it with ffplay 3.1 shows:
[h264 @ 0x7f85240f6a00] co located POCs unavailableq=    0B f=0/0  
    Last message repeated 1 times
[h264 @ 0x7f8524164000] co located POCs unavailableq=    0B f=0/0  
    Last message repeated 1 times

Visual distortion can be seen during playback

seems that the last sample table in the last moof is invalid.

**Comment by rbouqueau** [comment]
Thanks for reporting. I can't reproduce here. What's your GPAC version?

**Comment by jyavenard** [comment]
gpac of the day using the nightly build.. let me check that the testi.mp4 is still the one..

**Comment by cconcolato** [comment]
Can't reproduce either with ffplay version N-71209-gd759844, or vlc 2.2.1.
