### ISSUE TITLE
Dashcast - 2nd segment always skipped and 3rd segment empty of Live Media stream

### ISSUE THREAD

**Issue by Victordmdb** [gpac/gpac#623]
I'm using Dashcast on Ubuntu 16. I've tried it on the latest build of Gpac, but it still seems to happen. Is this a resource issue? Because dash.js and shaka both have issues with reading live streams with missing segments, so it tends to break at the beginning of the video.

My command is 'DashCast -v bunny.avi -out output/ -live-media', and I've tried with ntps, mpd-refresh, low-delay and a few others, but nothing seems to have an effect.

Looking at the source code, this seems to be caused by the 2nd while loop in 'video_encoder_thread' in 'controler.c', line 731, which seems to be buffering frames too long.

Any ideas on how to fix?

**Comment by Victordmdb** [comment]
Does anyone else have this issue? Or is it just me.

**Comment by Victordmdb** [comment]
I was wondering if @rbouqueau or @jeanlf you guys had maybe seen this problem already?

**Comment by rbouqueau** [comment]
I don't use dashcast anymore since we have a clean replacement (although not iso functional): https://github.com/gpac/signals/tree/master/src/apps/dashcastx

**Comment by Victordmdb** [comment]
Ok that looks cool, what are the main differences feature wise between this old dashcast and the signals version? Is it possible to create custom pipeline modules?

**Comment by rbouqueau** [comment]
Differences: see command usages: https://github.com/gpac/gpac/blob/master/applications/dashcast/cmd_data.c#L412 and https://github.com/gpac/signals/blob/master/src/apps/dashcastx/options.cpp#L65. Signals/dashcastx is able not to transcode.

Note that the Signals project is not public yet. There are a few things that would help external users use it, see https://github.com/gpac/signals/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.0.0 and https://github.com/gpac/signals/releases/tag/untagged-8175a45abdffe988e75a

We published the codebase some time ago. However there are parts of the work that are not public yet. Dashcastx got improvements regarding low latency, timeshift buffers, subfolders, etc. Send me an email if you want an access to it.

> Is it possible to create custom pipeline modules?

Absolutely :)

**Comment by Victordmdb** [comment]
Yea if I could have access that would be awesome! I would like to see if it's possible to integrate OpenCV using the pipeline method.

**Comment by rbouqueau** [comment]
romain _a_ gpac.io
