### ISSUE TITLE
Bad Parameter (receiving VoD issue)

### ISSUE THREAD

**Issue by irrz** [gpac/gpac#624]
Hello there,
I will get to the point straightaway,
When I make a live streaming using x.265, i recieve segments very fine at the client side (By using MP4Client). However, when I make VoD, I receive a message that "Cannot open http://<ip address of the server>/dash/dashvod/dashcast.mpd:  Bad Parameter", although the time at both sides exactly the same (UTC zonetime).

I use the following commands at the server side:
⦁ ffmpeg -i <path&name of videofile> -c:v rawvideo -s:v 1280x720 -r 25 -pix_fmt yuv420p output.yuv
⦁ ffmpeg -f rawvideo -pix_fmt yuv420p -s:v 1280x720 -r 25 -i output.yuv -c:v libx265 -f rawvideo output.265
⦁ MP4Box -add output.265 output.h265 
⦁ DashCast -v output.h265 -seg-dur 10000 -out /opt/lampp/htdocs/dash -conf dashcast.conf

At the Client side (Windows 8.1 OS):
⦁ mp4client http://<ip address of the server>/dash/dashvod/dashcast.mpd
Please find the attached files 
<img width="834" alt="vod issue" src="https://cloud.githubusercontent.com/assets/16091677/18250830/6d861974-737d-11e6-89e8-e71a1d6e9464.png">

**Comment by jeanlf** [comment]
dashcast is deprecated use GPAC 0.9.0 DEV
