### ISSUE TITLE
encode / decode a video to be the only one able to read her

### ISSUE THREAD

**Issue by LeonCosnyd** [gpac/gpac#626]
Hi, I would like more information about GPAC. 

I need a tool that can encode / decode a video. The aim is to be the only one able to read the video. A bit like "my own codec".

Do you think it is possible to change the GPAC's code to do this ? Or maybe it already exists ?

Thanks.

**Comment by jeanlf** [comment]
just changing the sinaling of the video type will likely not be enough. One nice and robust way to do that is to encrypt your files, check [https://gpac.wp.mines-telecom.fr/mp4box/encryption/](url)
