### ISSUE TITLE
Latest two "installers" for 64-bit Windows are broken

### ISSUE THREAD

**Issue by filler56789** [gpac/gpac#629]
0.6.2 rev695 and the previous one.
The filesizes are (much) smaller than the filesizes of the 32-bit installers.

Also: please stop wrapping the dämn files in an installer.
Stop complicating everything, Many users like myself are interested only in MP4Box, and manually unpacking the stupid installers is a P.I.T.A. Just wrap the files in a .ZIP or .7Z archive, problem solved.

**Comment by rbouqueau** [comment]
Thanks for reporting. Some of our installers are broken (that's an upload issue).

For MP4Box, we plan to provide static MP4Box builds. Please note that the installer is an archive that you can open with 7zip.

**Comment by filler56789** [comment]
Well, it's interesting that ONLY the 64-bit packages have had "upload issues".
And no, the problem is not recent, it's many months old.

**Comment by rbouqueau** [comment]
> Well, it's interesting that ONLY the 64-bit packages have had "upload issues".

Maybe for now but this issue happens on all platforms.

> no, the problem is not recent, it's many months old

That's correct. The installer are hosted by an entity (that's a lot of bandwidth) and they probably changed something in their configuration.

I'm closing for now, but if you have any idea to help, please write to us.
