### ISSUE TITLE
Dashing audio track incorrectly changes saiz value from 8 to 10

### ISSUE THREAD

**Issue by sandersaares** [gpac/gpac#633]
Command: `mp4box -dash-strict 4000 -profile "dashavc264:live" -bs-switching no -sample-groups-traf audio2.mp4 -out out\Manifest.mpd`
Version: gpac-0.6.2-DEV-rev723-g321745c-master-x64
Input file: [audio2.zip](https://github.com/gpac/gpac/files/466731/audio2.zip)

The input is an encrypted audio track using the HE-AACv2 codec. The size of the sample aux information is marked as 8 in the saiz box (this is correct).

After dashing with the above command, the saiz box claims a sample aux information of 10 bytes, which is incorrect.

**Comment by jeanlf** [comment]
indeed, thanks for the report now fixed.
