### ISSUE TITLE
m3u8 to mpd

### ISSUE THREAD

**Issue by fogelito** [gpac/gpac#634]
I have converted a manifest m3u8 to mpd in the link:
[http://video-walla.akamaized.net/11/5.mpd](http://video-walla.akamaized.net/11/5.mpd)

but i can not get it played in no player
can you help please?

**Comment by jeanlf** [comment]
something is wrong in the mpd, the first segment has no URL. 
I just ran mpd->m3u8 on http://video-walla.akamaized.net/11/5.m3u8 and cannot reproduce the issue (works well with MP4Client), could you confirm ?
