### ISSUE TITLE
Muxing 3D MVC video with MP4Box

### ISSUE THREAD

**Issue by ghost** [gpac/gpac#636]
Hi, many 3D camcorders like the JVC GS-TD1 store MVC video in MP4 files. Some sample files are [ez0027.mp4](http://av.watch.impress.co.jp/video/avw/docs/424/208/ez0027.mp4) and [ez0028.mp4](http://av.watch.impress.co.jp/video/avw/docs/424/208/ez0028.mp4) in this [web page](http://av.watch.impress.co.jp/docs/series/zooma/424208.html). These files have both views stored in the same track. There are MVC-specific `mvci`, `mvcg`, `vwid` and `mvcC` boxes in the track. I can confirm that Cyberlink PowerDVD automatically plays these files in 3D when I open them. 

When I tried muxing a raw MVC stream with MP4Box, it created a MP4 file with a `svcC` box, and it cannot be played in 3D. It also displayed the following error.
`[avc-h264] MVC not supported - skipping parsing end of Subset SPS`

Since SVC muxing support is already implemented in MP4Box, and SVC and MVC have similar NAL units, would it be possible to support MVC muxing too? There is a free MVC encoder / decoder available now (Intel Media SDK with its command-line front end [FRIM](http://forum.doom9.org/showthread.php?t=169651)). It would be great if MP4Box could support MVC muxing / demuxing as well. (GPAC version: `0.6.1-rev0-g72d766c-master`)

**Comment by jeanlf** [comment]
update support for a few of MVC boxes - I'm still having issues parsing these bitstreams ...

**Comment by jeanlf** [comment]
now in master, thanks for the files

**Comment by nithin-mk** [comment]
Thanks @jeanlf ! :-) I'm the creator of this issue. My previous GitHub account got deleted; so I couldn't get the notification in time. I will test this and let you know!
