### ISSUE TITLE
mp4box hint large file error

### ISSUE THREAD

**Issue by feng247** [gpac/gpac#640]
Hi, i am using mp4box + darwin streaming server as rtsp server, they runs ok before. But a day ago, mp4box hint a large mp4 file report a error:

```
Hinting file with Path-MTU 1450 Bytes
[ODF] Error reading descriptor (tag 6 size 16): Invalid MPEG-4 Descriptor
Hinting track ID 1 - Type "mp4v:mp4v" (MP4V-ES) - BW 4350 kbps
[ODF] Error reading descriptor (tag 6 size 16): Invalid MPEG-4 Descriptor
Hinting track ID 2 - Type "mp4a:mp4a" (mpeg4-generic) - BW 341 kbps
Saving f1.mp4: 0.500 secs Interleaving
```

the command is : mp4box.exe -hint f1.mp4
the size of f1.mp4 is 2.86G
i tried some other files, and found if the file is bigger than 2G , mp4box would printf error like above.

the version of mp4box is latest, and the exe is built through gpac_mp4box_mini project
am i some thing missing or the command is wrong?

**Comment by rbouqueau** [comment]
Thanks for reporting. Would it be posible for you to share a sample for this issue? https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by feng247** [comment]
in the url above, the speed of upload is very slow, only 30 kB/s, so i give up, sorry.
i test 10 files, every is bigger than 2G, and every can get error like above.
if possble, you can find a large mp4 file and test it.

**Comment by rbouqueau** [comment]
ok we'll try it

**Comment by jeanlf** [comment]
should now be fixed, thanks for the report
