### ISSUE TITLE
Custom sample type parser expects too much data

### ISSUE THREAD

**Issue by eras** [gpac/gpac#642]
- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

I'm using gpac version b60f90a92c38b3aaf10b41533e25a14f1c6c3f3a. I have uploaded an example file demonstrating the issue with the description "GPAC issue custom sample descriptor example file".

Reproducing the issue:

    MP4Box -v -diso gpac-custom-sample-desciptor.mp4

This will result in the following output (among the rest):

    ...
    [iso file] Read Box type uri  size 44 start 8
    [iso file] Read Box type uriI size 28 start 52
    [iso file] Warning Read Box type .... (0x00000000) size 0 - patching to size=8 ...
    [iso file] Read Box type .... size 8 start 80
    [iso file] Box "...." has 8 extra bytes
    [iso file] Read Box type trak size 888 start 1896
    ...

It also results in the following output in the produced XML:

    <SampleDescriptionBox DataReferenceIndex="1" ExtensionDataSize="0">
    <BoxInfo Size="0" Type="urim"/>
    <UnknownBox>
    <BoxInfo Size="44" Type="uri "/>
    </UnknownBox>
    <UnknownBox>
    <BoxInfo Size="28" Type="uriI"/>
    </UnknownBox>
    <UnknownBox>
    <BoxInfo Size="8" Type="...."/>
    </UnknownBox>
    </SampleDescriptionBox>

The reason why it finds 8 extra bytes is this piece of code (src/isomedia/box_code_base.c starting from line 6613) starts here:

    GF_GenericSampleEntryBox *genm;
    /*remove entry*/
    gf_list_rem(trak->Media->information->sampleTable->SampleDescription->other_boxes, i-1);
    genm = (GF_GenericSampleEntryBox *) gf_isom_box_new(GF_ISOM_BOX_TYPE_GNRM);
    genm->size = a->size-8; <---
    bs = gf_bs_new(a->data, a->dataSize, GF_BITSTREAM_READ);
    gf_bs_read_data(bs, genm->reserved, 6);
    genm->dataReferenceIndex = gf_bs_read_u16(bs);

Here the parent box size is set to the box size minus the box header (size+type). Then the code reads 6 reserved bytes plus 2 bytes for the data reference index. So now the box has 8 fewer bytes to process for the remaining boxes. Next the remaining bytes are processed:

    if (gf_bs_available(bs)) {
            u64 pos = gf_bs_get_position(bs);
            //try to parse as boxes
            GF_Err e = gf_isom_read_box_list((GF_Box *) genm, bs, mp4s_AddBox);

The function gf_isom_read_box_list_ex then loops until the parent box size is consumed:

    while (parent->size) {
    	e = gf_isom_parse_box_ex(&a, bs, parent_type, GF_FALSE);
    	...
    	if (parent->size < a->size) {
    	        ...
    	} else {
    		parent->size -= a->size;
    	}
    	...
    }
    return GF_OK;

However, once it has processed all the boxes, there are still 8 bytes left (that were already parsed for the reserved bytes and data reference index). This results in it finding an empty box with no size (the buffer seems to contain zeroes instead of the actual content in the file).

It seems to me the appropriate solution would be to arrange the genm box to have a size 8 fewer than it currently is before entering the gf_isom_read_box_list function.

The reason why ie. GF_ISOM_MEDIA_AUDIO processing doesn't have the same issue is that the gf_isom_audio_sample_entry_read function it calls reduces the parent box size when it reads it. But the same parent box size reduction doesn't happen in the default switch.

Thanks and keep up the good work!

**Comment by jeanlf** [comment]
Indeed now fixed, thanks for the report
