### ISSUE TITLE
Playback support for HTTP no-cached fragmented MP4

### ISSUE THREAD

**Issue by cconcolato** [gpac/gpac#644]
The ISOBMFF module supports parsing either:
- from an ISOBMFF file that contains all bytes from its beginning (including ftyp, moov ...), possibly growing;
- or from multiple ISOBMFF segments being fed to it as files or memory buffers. The data has to be box-aligned, and even movie fragment aligned. It does not do the box/fragment-alignment nor the garbage collecting of the data. This is done implicitely by the MPD/HLS module.

These two modes do not allow for playback of a plain HTTP long-running download (i.e. not using the cache, and not using the DASH module) of a fragmented mp4 such as http://patchy.ddvtech.com:8080/live.mp4. 

The module should create its own memory buffer when receiving non-cached data, split the data at fragments boundary, parse and discard fragments as they are discovered, whether the transfer is chunked or not.

**Comment by rbouqueau** [comment]
NB: we fixed some stuff with Jean at the beginnning of the year 1283686c3e4c4c25e4b7a6ad0a73d43c52afe13b

**Comment by jeanlf** [comment]
added a while back in filters and in the [testsuite](https://github.com/gpac/testsuite/blob/filters/scripts/http.sh)
