### ISSUE TITLE
Osmo4 bad rendering of the scene

### ISSUE THREAD

**Issue by traianlavric** [gpac/gpac#645]
Hi,

I was trying to use Osmo4 (last nightly build) on a Samsung Galaxy S2 (Android 4.1.2). 
It seems there is a rendering error probably related to OpenGL.
Please find attached two screenshots below:

![screenshot_2016-09-27-19-00-16](https://cloud.githubusercontent.com/assets/2527837/18883905/7705cf0c-84e5-11e6-8a9a-b4d492bf16f7.png)

![screenshot_2016-09-27-19-03-14](https://cloud.githubusercontent.com/assets/2527837/18883912/7b10857e-84e5-11e6-93e4-ece6d8457960.png)

Is seems that the scene is not correctly centered and it's shifted to the right and up.

Thanks!

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
This should be fixed in 1.0
