### ISSUE TITLE
Sensor-based navigation on android

### ISSUE THREAD

**Issue by emmanouil** [gpac/gpac#646]
360video sensor-based navigation does not work on recent android build(s)

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!
-  I looked for a similar issue and couldn't find any.
- I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by rbouqueau** [comment]
Do we have some progress on this?

**Comment by emmanouil** [comment]
tested it today, it works now
