### ISSUE TITLE
MP4box moves the video stream by 67ms causing AV sync issues

### ISSUE THREAD

**Issue by sonaldev** [gpac/gpac#648]
Hi,

I am trying to dash a video only mp4 with the following command:

MP4Box -dash 2000 -profile dashavc264:onDemand -bs-switching no -rap -frag-rap -out manifest.mpd video.mp4

Before running mp4box, the pts and dts of the frames start at 0. After running mp4box, the pts and dts of all frames are moved by 67ms.

I am seeing the exact 67 ms added to several different video streams that I run the above command on. Attached is the ffprobe show_frames output of the video before and after running mp4box. 
[before.txt.zip](https://github.com/gpac/gpac/files/501742/before.txt.zip)
[after.txt.zip](https://github.com/gpac/gpac/files/501743/after.txt.zip)

Before running mp4box, I demux the audio and video streams using ffmpeg and use MP4Box to dash the streams separately. MP4Box does not change the pts and dts of audio stream but sometimes, MP4Box adds the 67ms offset to the video stream. When it does, there is an AV sync issue when I put the audio and video MPDs together.

Please help me understand where the 67ms offset comes from.

**Comment by jeanlf** [comment]
could you provide your test file please ?

**Comment by sonaldev** [comment]
Hi jeanlf, sorry for the delay. Please find the test file attached.
[testvideo.mp4.zip](https://github.com/gpac/gpac/files/504003/testvideo.mp4.zip)

Note that the start time on the file now is 0. After running the above mp4box command, it changes to 67ms.

**Comment by combucha** [comment]
I've tested it, all is good on my side.

Original testvideo.mp4 probe:
`frames.frame.0.media_type="video"
frames.frame.0.stream_index=0
frames.frame.0.key_frame=1
frames.frame.0.pkt_pts=0
frames.frame.0.pkt_pts_time="0.000000"
frames.frame.0.pkt_dts=0
frames.frame.0.pkt_dts_time="0.000000"
frames.frame.0.best_effort_timestamp=0
frames.frame.0.best_effort_timestamp_time="0.000000"
frames.frame.0.pkt_duration=512
frames.frame.0.pkt_duration_time="0.033333"
frames.frame.0.pkt_pos="48"
frames.frame.0.pkt_size="8793"
frames.frame.0.width=832
frames.frame.0.height=468
frames.frame.0.pix_fmt="yuv420p"
frames.frame.0.sample_aspect_ratio="1:1"
frames.frame.0.pict_type="I"
frames.frame.0.coded_picture_number=0
frames.frame.0.display_picture_number=0
frames.frame.0.interlaced_frame=0
frames.frame.0.top_field_first=0
frames.frame.0.repeat_pict=0`

Dashed testvideo_dashinit.mp4 probe:
`frames.frame.0.media_type="video"
frames.frame.0.stream_index=0
frames.frame.0.key_frame=1
frames.frame.0.pkt_pts=0
frames.frame.0.pkt_pts_time="0.000000"
frames.frame.0.pkt_dts=0
frames.frame.0.pkt_dts_time="0.000000"
frames.frame.0.best_effort_timestamp=0
frames.frame.0.best_effort_timestamp_time="0.000000"
frames.frame.0.pkt_duration="N/A"
frames.frame.0.pkt_duration_time="N/A"
frames.frame.0.pkt_pos="3102"
frames.frame.0.pkt_size="8793"
frames.frame.0.width=832
frames.frame.0.height=468
frames.frame.0.pix_fmt="yuv420p"
frames.frame.0.sample_aspect_ratio="1:1"
frames.frame.0.pict_type="I"
frames.frame.0.coded_picture_number=0
frames.frame.0.display_picture_number=0
frames.frame.0.interlaced_frame=0
frames.frame.0.top_field_first=0
frames.frame.0.repeat_pict=0`

ffprobe version N-75794-gd1c8368 built with gcc 5.2.0 (GCC)
MP4Box - GPAC version 0.6.2-DEV-rev997-g397b871-master

**Comment by sonaldev** [comment]
Hi jeanlf, thanks for taking a look.

I got the latest version of mp4box from git as follows and I see the 67ms offset in the testvideo_dashinit.mp4.

git clone https://github.com/gpac/gpac.git
cd gpac
git pull
./configure --static-mp4box --use-zlib=no
make -j4
sudo make install

Attached are the testvideo_dashinit.mp4 and its ffprobe output that I see.

What do you think is different between our setups?

Really appreciate your help with this!
[testvideo_dashinit.zip](https://github.com/gpac/gpac/files/504783/testvideo_dashinit.zip)

[testvideo_dashinit.mp4.frames.txt](https://github.com/gpac/gpac/files/504785/testvideo_dashinit.mp4.frames.txt)

**Comment by combucha** [comment]
I'm not jeanif :)
Checked your dashinit and it also starts from 0, seems your ffprobe version calculate times wrong. There were some problems with it in past afair.

**Comment by sonaldev** [comment]
Thanks a lot again, combucha! Sorry for mixing up names :)

You are right that the latest version of ffprobe shows that the testvideo_dashinit.mp4 starts at 0. However, with the latest version of ffprobe, it appears that mp4box is changing the start_time of the audio stream from 1.003s to 2.006s. 

To recap, I demux the audio and video streams using ffmpeg and use MP4Box to dash the streams separately. It appears that after running mp4box, the timestamps of one of the streams are moved causing them to play out of sync when I put the MPDs together.

Please help in figuring out why the audio and video go out of sync after dashing with mp4box.

All test files are [here](https://www.dropbox.com/sh/wgwax6k6xlkf2lk/AABq5TWTOYuQm2Om5mJGcL15a?dl=0).

Commands for repro:
ffmpeg -i original.mp4 -map 0:v:0 -c copy  -an -y dash-demux-video.mp4 -map 0:a:0 -c copy -vn -y dash-demux-audio.mp4

MP4Box -dash 2000 -profile dashavc264:onDemand -bs-switching no -rap -frag-rap -out videomanifest.mpd dash-demux-video.mp4

MP4Box -dash 2000 -profile dashavc264:onDemand -bs-switching no -rap -frag-rap -out audiomanifest.mpd dash-demux-audio.mp4

Versions:
ffmpeg, ffprobe version 3.1.4
MP4Box - GPAC version 0.6.2-DEV-rev1001-g6755ece-master

**Comment by combucha** [comment]
I see problem mutates, now you are talking about shift of dashed audio ;)
Checked your new dropbox files, my old ffprobe reports them as fine.
Can't run newer compiled ff-versions, got scrambled xp sys files...

ffprobe -show_streams dash-demux-audio_dashinit.mp4
```
[STREAM]
index=0
codec_name=aac
codec_long_name=AAC (Advanced Audio Coding)
profile=LC
codec_type=audio
codec_time_base=1/48000
codec_tag_string=mp4a
codec_tag=0x6134706d
sample_fmt=fltp
sample_rate=48000
channels=1
channel_layout=mono
bits_per_sample=0
id=N/A
r_frame_rate=0/0
avg_frame_rate=0/0
time_base=1/48000
start_pts=48144
start_time=1.003000
duration_ts=272540672
duration=5677.930667
bit_rate=68840
max_bit_rate=68840
bits_per_raw_sample=N/A
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=1
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
TAG:language=und
TAG:handler_name=SoundHandler
[/STREAM]
```
Audio starts at 1.003s, as defined by positive delay entry in edit list of dashed mp4 (and original too).
There is also second entry, but with start time 0 and duration 0, so it doesn't shift anything.
Your ffprobe reports start time second later, but tehre's no reason for it, imo - borked ffprobe.

**Comment by sonaldev** [comment]
Thanks again combucha! You are right that the timestamps are probably not the root cause of the AV sync issue that I am struggling with.

Let's ignore the timestamps for now and I would love your help in debugging why dashing with mp4box is introducing an AV sync issue.

Repro steps:
MP4Box -dash 2000 -profile dashavc264:onDemand -bs-switching no -rap -frag-rap -out manifest_audio.mpd musk_sd.mp4#audio
MP4Box -dash 2000 -profile dashavc264:onDemand -bs-switching no -rap -frag-rap -out manifest_video.mpd musk_sd.mp4#video

Then I combined the MPDs as in attached manifest.mpd and tried to playback with mp4client. AV sync issue repros. 

All test files here https://www.dropbox.com/sh/once5qx1ard7hvq/AAAyqBt9Zk2tDOhPUc4ZiflJa?dl=0

**Comment by sonaldev** [comment]
Starting a new thread for the AV sync issue.
