### ISSUE TITLE
DASH-AVC/264 profile does not include @subsegmentAlignment and @subsegmentStartsWithSAP

### ISSUE THREAD

**Issue by tieleman** [gpac/gpac#65]
From the DASH-AVC/264 IOP 2.00:

```
If the MPD@type is equal to "static" and the MPD@profiles attribute includes "urn:mpeg:dash:profile:isoff-on-demand:2011" then
*􏰁 AdaptationSet elements with AdaptationSet@subsegmentAlignment not present, or set to 'false' may be ignored.
􏰁* Representation elements with a @subsegmentStartsWithSAP value ab-sent, zero or greater than 2 may be ignored.
*􏰁 If the Representation element does not contain a BaseURL element then this Representation element may be ignored.
```

I'm using the following options:

`MP4Box -dash 4000 -profile dashavc264:onDemand video.mp4 video_180.mp4 audio.mp4 -out out/dash`

The resulting MPD does not include the `@subsegmentAlignment` and `subsegmentStartsWithSAP` attributes, which allows a client to ignore them per the spec.

The resulting MPD is:

```xml
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.5.2-DEV-rev128-gd792da9-master  on 2015-03-16T09:44:20Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500000S" type="static" mediaPresentationDuration="PT0H14M48.03S" maxSegmentDuration="PT0H0M4.00S" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011, http://dashif.org/guildelines/dash264">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>out/dash.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H14M48.03S">
  <AdaptationSet segmentAlignment="true" maxWidth="640" maxHeight="360" maxFrameRate="24" par="16:9" lang="und">
   <Representation id="1" mimeType="video/mp4" codecs="avc1.42c01f" width="640" height="360" frameRate="24" sar="540:409" startWithSAP="1" bandwidth="978613">
    <BaseURL>video_dashinit.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="935-3630">
      <Initialization range="0-934"/>
    </SegmentBase>
   </Representation>
   <Representation id="2" mimeType="video/mp4" codecs="avc1.42c01f" width="320" height="180" frameRate="24" sar="540:409" startWithSAP="1" bandwidth="487754">
    <BaseURL>video_180_dashinit.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="935-3630">
      <Initialization range="0-934"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" lang="eng">
   <Representation id="3" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="48000" startWithSAP="1" bandwidth="129952">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <BaseURL>audio_dashinit.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="851-3558">
      <Initialization range="0-850"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```

**Comment by jeanlf** [comment]
do you have the same issue using -rofile onDemand ?

**Comment by tieleman** [comment]
Using `-profile onDemand` yields a `subsegmentStartsWithSAP="1"` but no `subsegmentAlignment="true"`.

I think the code in `dash_segmenter.c#4230` is not correct. It should also check for the DASH-AVC/264 profile and the `subsegmentAlignment` code does not appear to be working.

**Comment by tieleman** [comment]
The main issue with the way `strcmp` is used in a lot of the source is that it not only returns a 0 or a negative value, but also positive values (which map to `true`!) if the string differs, consider:

```c
#include <stdio.h>
#include <string.h>
 
int main ()
{
  char str1[] = "video/mp4";
  char str2[] = "video/mp2t";
  int ret = strcmp(str1, str2);

  if (!ret) {
    printf("Not equal\n" );
  } else {
    printf("Equal\n" );
  }

  printf("Exact value of ret is: %d\n", ret );

  return 0;
}
```

This will print "Equal" even though the strings are obviously not equal (return value is 2). 😬 Therefore, I think it should be an explicit test against 0:

`if (ret != 0)`

**Comment by tieleman** [comment]
Ok, hang on, I might be reading this wrong. What is the expected behaviour here? Should the `subsegmentAlignment` be added if it *is* `video/mp2t`, or if it *isn't* `video/mp2t`. The spec got me confused a bit.

**Comment by jeanlf** [comment]
i've just been cleaning up this part of the code, could you check it out ?

**Comment by tieleman** [comment]
Hi @jeanlf, that indeed looks a lot better. Output seems correct, both for `dashavc264:onDemand` and `onDemand`. I think this is a good solution, thanks.

**Comment by tieleman** [comment]
Ok, I just checked the spec and put a result file through the DASH-IF validator and it seems that `@subsegmentStartsWithSAP` may only occur on the `AdaptationSet` element and *not* on the `Representation` element. Even though it is inherited it should be explicitly be set on `AdaptationSet`. The spec isn't overly clear on this unfortunately, but it seems to be the case.

**Comment by jeanlf** [comment]
indeed, now back to <AS>. Need a way to compute its value though, for now it's hardcoded to "1"

**Comment by tieleman** [comment]
Thank you @jeanlf, that seems to do the trick for now. The DASH-IF MPD validator seems to be ok with it. 😊
