### ISSUE TITLE
Help with gpac log files

### ISSUE THREAD

**Issue by khansamra** [gpac/gpac#650]
Hi, sorry if my question might sound naive, am new to gpac and will like know where the MP4client stores its log files ( from GF_LOG), and also i have tried using printf to write some of the variables/parameters to a file  but its writing an empty file, just wondering if there is something i need to alter to allow writing to a file with printf. Any help will be appreciated.

**Comment by rbouqueau** [comment]
> Hi, sorry if my question might sound naive, am new to gpac and will like know where the MP4client stores its log files ( from GF_LOG)

You can use the ```-lf logfilename``` option to store the logs inside a file.

> i have tried using printf to write some of the variables/parameters to a file

Use ```fprintf()``` to write to a file

**Comment by khansamra** [comment]
Thank you so much.
