### ISSUE TITLE
Update Android's README for compilation instructions

### ISSUE THREAD

**Issue by RodolpheFouquet** [gpac/gpac#651]
We are now using android studio, I should update the compilation instructions ASAP.

**Comment by SrujithPoondla** [comment]
Could you please update the compilation instructions for Android-studio?

**Comment by xgw** [comment]
+1. I need the doc as well. I'll appreciate if you update the docs for android studio users

**Comment by jeanlf** [comment]
https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Android
