### ISSUE TITLE
chunk download decision

### ISSUE THREAD

**Issue by khansamra** [gpac/gpac#652]
Hello,
Am implementing an adaptive streaming adaptation algorithm using gpac and have been looking at the dash_do_rate_adaptation function. Please am trying to figure out how and when  the MP4Client decides  to get the next chunk while playing the current chunk. Does this happen immediately after downloading the current segment, does it wait after a period of time or just based on the current buffer occupancy? Any help will be appreciated to know where(function) and when this decision takes place. 
Thank you.

**Comment by jeanlf** [comment]
The decision is taken at the end of the download of the current chunk. There is currently no way to postpone this decision to a later time but we are working on adding this feature any time soon.

PS: Code for adaptation logic has been refactored recently, check it out. The selected adaptation algo is called from dash_do_rate_adaptation in src/media_tools/dash/client.c
