### ISSUE TITLE
AV sync issue after dashing with MP4Box

### ISSUE THREAD

**Issue by sonaldev** [gpac/gpac#659]
Need help in debugging why dashing with mp4box is introducing an AV sync issue.

Repro steps:
MP4Box -dash 2000 -profile dashavc264:onDemand -bs-switching no -rap -frag-rap -out manifest_audio.mpd musk_sd.mp4#audio
MP4Box -dash 2000 -profile dashavc264:onDemand -bs-switching no -rap -frag-rap -out manifest_video.mpd musk_sd.mp4#video

Then I combined the MPDs as in attached manifest_combined.mpd and tried to playback with mp4client. AV sync issue repros.

All test files here https://www.dropbox.com/sh/once5qx1ard7hvq/AAAyqBt9Zk2tDOhPUc4ZiflJa?dl=0

MP4Box and MP4client versions 0.6.2-DEV-rev1001-g6755ece-master
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by combucha** [comment]
I've noticed that original mp4 file loaded into Osmo4 is played with shifted audio too, just like manifest_combined.mpd
This shift is small and positive (audio is played too early, we hear voice before mouth moves), but clearly noticable.
Can you confirm that?

**Comment by sonaldev** [comment]
Yes, you are right. In Osmo4, the original mp4 of the test video is also played with audio too early. I don't see the same problem in either ffplay or VLC player. The dash however is out of sync on both Shaka and Osmo4. 

I also uploaded another such sample here. https://www.dropbox.com/sh/419l1k059pfa0nn/AAB8UYpRjXwM3ZK1PhxsV7dPa?dl=0
For this one, original mp4 plays fine on both VLC and ffplay. But on osmo4, the video starts fine but you can notice video begins to lag around the 1 minute mark. Dashing with mp4box as above also drifts on osmo4. Plays out of sync on shaka from the beginning.

Thanks again for helping debug!

**Comment by rbouqueau** [comment]
```
$ MP4Box -info another_sd_frag_sample.mp4
* Movie Info *
        Timescale 1000 - 2 tracks
        Computed Duration 00:32:52.834 - Indicated Duration 00:32:50.432
        Fragmented File: no
        File suitable for progressive download (moov before mdat)
        File Brand isom - version 512
        Created: UNKNOWN DATE   Modified: UNKNOWN DATE
File has no MPEG4 IOD/OD

iTunes Info:
        Encoder Software: Lavf56.40.101
1 UDTA types: meta (1)

Track # 1 Info - TrackID 1 - TimeScale 90000
Media Duration 00:32:49.666 - Indicated Duration 00:32:49.666
Track has 2 edit lists: track duration is 00:32:52.834
Media Info: Language "Undetermined (und)" - Type "vide:avc1" - 58090 samples
Visual Track layout: x=0 y=0 width=360 height=640
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x21
AVC/H264 Video - Visual Size 360 x 640
        AVC Info: 1 SPS - 1 PPS - Profile Main @ Level 3.1
        NAL Unit length bits: 32
        Chroma format YUV 4:2:0 - Luma bit depth 8 - chroma bit depth 8
        SPS#1 hash: 89C65BE20C308DFF481A8A7BDFE93AF98F79D824
        PPS#1 hash: EAF8566A5F8584BB4DE2697AB5A2B500EA8A9B5C
Self-synchronized
        RFC6381 Codec Parameters: avc1.4d401f
        Average GOP length: 26 samples

Track # 2 Info - TrackID 2 - TimeScale 48000
Media Duration 00:32:50.432 - Indicated Duration 00:32:50.432
Track has 2 edit lists: track duration is 00:32:52.711
Media Info: Language "Undetermined (und)" - Type "soun:mp4a" - 92364 samples
MPEG-4 Config: Audio Stream - ObjectTypeIndication 0x40
MPEG-4 Audio AAC LC - 1 Channel(s) - SampleRate 48000
Synchronized on stream 1
        RFC6381 Codec Parameters: mp4a.40.2
Alternate Group ID 1
        All samples are sync
```

This part is faulty: ```Track has 2 edit lists```. FFmpeg and VLC don't handle multiple edit lists while gpac/mp4client/osmo does. So the comparison doesn't stand.

Also assembling two MPDs has a risk to loose the initial sync (as you experience). Is there a need to process both tracks separately?

**Comment by sonaldev** [comment]
Thanks for your help @rbouqueau! Will figure out how to fix the AV sync issue and post in this thread.

**Comment by sonaldev** [comment]
Fixed the issue by dashing the audio and video together with mp4box.
