### ISSUE TITLE
Live Encryption

### ISSUE THREAD

**Issue by Natarajan92** [gpac/gpac#661]
Is it possible to do real time live dash streaming with CENC encryption (Playready DRM/Widevine DRM) by taking UDP stream as input to generate dash files ?

**Comment by rbouqueau** [comment]
With the existing GPAC tools, not yet:
 - dashcast misses the CENC part.
 - MP4Box misses the live ts input.

Please note that https://github.com/gpac/node-gpac-dash uses ffmpeg to cut the ts stream (into HLS segments) and then pushes the HLS segments to MPEG-DASh conversion.

Another possibility is to extend https://github.com/gpac/signals to support cenc (there is dashcastx which is a clean rewrite of dashcast).

**Comment by Natarajan92** [comment]
Hi rbouqueau,

As you said can we use https://github.com/gpac/node-gpac-dash to generate live Dash stream along with encryption ? If so how ?  In the Readme.md of node-gpac-dash, i didnt see any possibilites to take udp as input to encrypt and generate dash stream.

**Comment by rbouqueau** [comment]
wrong repo sorry, I meant https://github.com/gpac/test-engine-live-tools

**Comment by Natarajan92** [comment]
Oh ok!, by using that repo can we Encrypt the live contents ? 
Clear live dash stream is created with that test-engine-live-tool by taking udp as a input and ts segments are converted which is converted to .m4s for dash stream. In between we need DRM encryption in that. 

Is that test-engine-live-tool has the ability for encryption ?

**Comment by rbouqueau** [comment]
Launch mp4box with your encryption parameters before dashing (as you would for encrypting any content). That's an additional step in the workflow.

Make sure it works on a VoD content before exploring live. Live is way more complex.

**Comment by jeanlf** [comment]
this is now feasible with GPAC 0.9.0 DEV, I need to add a wiki entry

**Comment by klimentLambevski** [comment]
@jeanlf Any update on the wiki?

**Comment by jeanlf** [comment]
yep:
[https://github.com/gpac/gpac/wiki/encryption](https://github.com/gpac/gpac/wiki/encryption
)

do not hesitate to comment / suggest improvements
