### ISSUE TITLE
Handling of partial encrypted blocks in CENS Pattern Encryption scheme

### ISSUE THREAD

**Issue by tbertschi** [gpac/gpac#662]
Hello,

I'm not sure if it's an issue, but I have a question about the way CENS Pattern Encryption is implemented in the latest GPAC: 

The question relates to handling of partial encrypted blocks overlapping the end of a NAL SubSample (e.g. the BytesOfProtectedData of the subsample). I have noticed that GPAC pads the incomplete block and still applies the AES-128-CTR encryption on the padded block. The padding of the encrypted block is then removed, and the partial encrypted block stored at the end of the subsample pattern.

I was wondering if this is correct according standard (Common Encryption, ISO/IEC 23001-7, 3rd edition, June 2015). In fact, according standard (section 10.3), "The BytesOfProtectedData size SHALL be a multiple of 16 bytes to avoid partial cipher blocks in Subsamples". So, that case should in fact not happen and GPAC should not have generated a SENC box with non-block aligned clear/protected sections in a subsample.

Still in case it happens, section 9.6.1 says: "If the last Block pattern in a Subsample is incomplete, the partial pattern SHALL be followed until truncated by the BytesOfProtectedData size, and any partial crypt_byte_block SHALL remain unencrypted."

Do you care to comment on that point?

Thanks in advance and best regards,

Thierry Bertschi
Nagravision S.A.

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!
- [ x] I looked for a similar issue and couldn't find any.
- [ x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
full compliance to CENC should have been fixed some time ago, reopen if needed
