### ISSUE TITLE
Dynamic tiles in DASH

### ISSUE THREAD

**Issue by Iman-sm** [gpac/gpac#666]
Hi,
I was interested to know if it is possible to create dynamic tiles (like changing position or size) for mpeg DASH to stream. I know the corresponding command to create normal tiles in MP4Box and by the looks of it, such an action is not possible (yet, maybe for future?). yet I was wondering if it is even possible to create and stream dynamic tiles in DASH. I couldn't find anything in mpeg DASH's specification regarding the possibility of such a thing in DASH's concept.
Regards

**Comment by jeanlf** [comment]
there are some thoughts on dynamic ROI for DASH at MPEG but for the time being this is not possible in GPAC
