### ISSUE TITLE
Question about HEVC Motion-constrained Tile-based adaptation, generating MPD with MP4Box

### ISSUE THREAD

**Issue by divan333** [gpac/gpac#668]
Hello,

I am trying to create MPEG DASH MPD file supporting SRD based on multi-tile H.265 input (so that the result should be similar to: http://download.tsi.telecom-paristech.fr/gpac/SRD/srd_hevc/multi_rate_p60/hevc_srd.mpd) 

The HEVC file was encoded with 8x8 uniformly spaced tiles.

However, I am not successful with generating MPD which contains proper tile information, I have tried the following:

Approach 1:

MP4Box -v -add test_multitile.hevc:FMT=HEVC -fps 30 -new test_multitile.mp4
MP4Box -dash 1000 test_multitile.mp4

^ The result is a MPD file without SRD support

Approach 2:

MP4Box -v -add test_multitile.hevc:FMT=HEVC:split_tiles -fps 30 -new test_multitile.mp4
MP4Box -dash 1000 test_multitile.mp4

^ The result is a MPD file with two adaptation sets with SRD, but with incorrect dimensions (first one is the full resolution: 3840x2160, second one is 448x256)

I am obviously doing something wrong. 

Can somebody please help me how to properly mux the multi-tile HEVC stream and create the DASH MPD with MP4Box?

Thank you!

**Comment by divan333** [comment]
After some more investigation, I think the culprit is the Annex B -> MP4 muxing operation:

MP4Box -v -add test_multitile.hevc:FMT=HEVC:split_tiles -fps 30 -new test_multitile.mp4

The resulting file contains two tracks: one 'hvc2' and one 'hvt1', so it appears that only the first tile (0, 0, w, h) has been muxed into its corresponding 'hvt1' track and the other tiles have been ignored.

So, the question is actually how to properly mux multi-tile Annex B HEVC bitstream into multi-tile MP4 file which can be then used for generating proper DASH MPD with SRD?

Thanks!

**Comment by rbouqueau** [comment]
Have you already tried the command-line from http://gpac.io/2016/05/25/srd/? : 
```
MP4Box -dash 1000 [other dash params]  source.mp4:desc_as=<SupplementalProperty schemeIdUri=\"urn:mpeg:dash:srd:2014\" value=\"0,0,1,1,1,2,2\"/>
```

**Comment by jeanlf** [comment]
can you upload the content somewhere ? I suspect that your multi-tile setup is single-slice. Tiles from a given slice cannot be split across several tracks

**Comment by divan333** [comment]
Dear Romain, Jean,

Many thanks for your help.

Indeed, after some looking I found out that the HEVC Annex B stream is, indeed, multi-tile but single-slice. It was encoded with kvazaar encoder, and it looks like this encoder cannot be configured to output one separate slice per tile.

Do you know of encoders capable of outputting multi-tile streams with tiles encoded as separate slices?

Thanks!

**Comment by jeanlf** [comment]
kvazaar has support for this now, check [https://gpac.wp.imt.fr/2017/02/01/hevc-tile-based-adaptation-guide/]

**Comment by confiwent** [comment]
I have a problem when I execute the command:`MP4Box -add output.hevc:split_tiles -new video_tiled.mp4` It has the errors:
`Cannot find file output.hevc:split_tiles` 
`Error importing output.hevc:split_tiles: Requested URL is not valid or cannot be found`
 It seems that the command `:split_tiles` does not work. How can I do it? My MP4Box version is 0.5.1-DEV-rev5619

**Comment by elhigu** [comment]
And here is working link...  https://gpac.wp.imt.fr/2017/02/01/hevc-tile-based-adaptation-guide/ the one in previous comment was pointing to dead end.
