### ISSUE TITLE
DashCast doesn't support GDIGrab Input

### ISSUE THREAD

**Issue by hadi77ir** [gpac/gpac#669]
As you may now, there are several ways to capture the screen using FFMPEG. One is to use GDIGrab device (like you have described for X11 with x11grab). If you want to know how to use it, visit [official FFMPEG devices page](https://www.ffmpeg.org/ffmpeg-devices.html#gdigrab).

But after using latest nightly binaries of GPAC for Windows, I found out that those binaries don't support GDIGrab! Saying it is an unknown video format!

Please fix it as soon as possible, as it is quite necessary for screen streaming on Windows.

Thanks.

**Comment by rbouqueau** [comment]
Naive question: why not use the direct show support that allows to make screen captures and is already implement?

```DashCast -vf dshow  -vres 1280x720 -vfr 24 -v video=\"screen-capture-recorder\" -live (please install http://screencapturer.sf.net/)```

**Comment by rbouqueau** [comment]
https://github.com/gpac/gpac/blob/master/applications/dashcast/cmd_data.c#L502

**Comment by hadi77ir** [comment]
While FFMPEG has support for native screen capturing, why install another software?
Also, I'm going to use DashCast in a portable app, so it's important to NOT install DirectShow filters.

While it has x11grab support for Linux/X11, why it can't/shouldn't support gdigrab?

**Comment by rbouqueau** [comment]
I've checked the dashcast code and we don't filter anything. So if you don't have support for GDIGrab, it means that our FFmpeg build doesn't support (too old, or not enabled by default?). Would you mind building dashcast with gdigrab support and report if you have any issue?

**Comment by jeanlf** [comment]
and dashcast is now deprecated, use GPAC 0.9.0
