### ISSUE TITLE
[Android] Stream from apple freeze  after 20 s 

### ISSUE THREAD

**Issue by franckyM** [gpac/gpac#67]
The reference HLS stream freezes after 20s on the lastest osmo4-0.5.2-DEV-rev128-gd792da9-master-stagefright.apk

http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8

Last logs : I/GF_LOG_CODEC(16457): [FAAD] Error decoding AU PCE shall be the first element in a frame
I/GPAC_WRAPPER(16457): Rebuilding methods for thread 1969997840
I/GPAC_WRAPPER(16457): Getting current Thread 1969997840...
I/GPAC_WRAPPER(16457): Getting current Thread DONE = 0x73ddc520, now registering before exit...
I/GPAC_WRAPPER(16457): Registering DONE for 1969997840
I/GF_LOG_CODEC(16457): [FAAD] Error decoding AU Bitstream value not allowed by specification
I/GF_LOG_CODEC(16457): [FAAD] Error decoding AU Invalid number of channels
I/GF_LOG_CODEC(16457): [FAAD] Error decoding AU Invalid number of channels
I/GF_LOG_CODEC(16457): [FAAD] Error decoding AU Bitstream value not allowed by specification
D/GPAC_WRAPPER(16457): GPAC_EventProc() Message=108
D/GPAC_WRAPPER(16457): GPAC_EventProc() Message=108
I/GF_LOG_CODEC(16457): [FAAD] Error decoding AU Bitstream value not allowed by specification
I/GF_LOG_CODEC(16457): [FAAD] Error decoding AU Bitstream value not allowed by specification
I/GF_LOG_CODEC(16457): [FAAD] Error decoding AU Channel coupling not yet implemented

**Comment by franckyM** [comment]
Can also be reproduced on the last  gpac-0.5.2-DEV-rev131-g2de8de1-master.dmg 

/Applications/Osmo4.app/Contents/MacOS/Osmo4 http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8

( what is strange the bitrate should change after 10s not after 20s )

**Comment by rbouqueau** [comment]
On Windows it works.

@jeanlf strangely, ffmpeg reports missing frames that I can see when playing slowly Oo

**Comment by nguyen-viet-thanh-trung** [comment]
@rbouqueau Which version did you try in windows ? I can reproduce this bug in windows 64 bits rev 132

**Comment by rbouqueau** [comment]
@nguyen-viet-thanh-trung MP4Box - GPAC version 0.5.2-DEV-rev107-g7e867f8-master

Do you cant me to try with the latest?

**Comment by rbouqueau** [comment]
FYI I have reset my gpac.cfg. Now I can see some issues. In particular FAAD doesn't seem happy. Investigating.

**Comment by rbouqueau** [comment]
I can't reproduce with thi command-line: ```MP4Client -opt DASH:StartRepresentation=maxQuality http://devimages.appleone/samples/bipbop/bipbopall.m3u8```

So it is related to the quality switching.

**Comment by nguyen-viet-thanh-trung** [comment]
Maybe it related to #54. In fact, in DASH, we switch quality (or Representation) in a AdaptationSet (audio, video, ...) but in HLS stream both audio and video are in the same playlist

**Comment by rbouqueau** [comment]
Not sure. I've seen GPAC play with other HLS streams recently.

**Comment by jeanlf** [comment]
that's what I found out: the lower bitrate (gear1) uses PID 257 for audio and PID 258 for video. Other bitrates use PID257 for video and 258 for audio. And the PMT section_number is alwaus the same (meaning no change in stream config). So after playing back the low bitrate and switching up, the video decoder is fed AAC audio and the audio decoder is fed H264 ones !!

Not sure what we can do about this, but you can instruct the client to use maxQuality by default (config file, DASH section, StartRepresentation=maxBandwidth). And maybe file a bug to Apple ;)

**Comment by cconcolato** [comment]
FYI, the following stream works (even if it gives many warning and error messages):
http://qtdevseed.apple.com/qadrift/_media/_streams/bipbop_devimages/bipbop_gears_alt_16x9/bipbop_16x9_variant_subs.m3u8
