### ISSUE TITLE
Forced Flag

### ISSUE THREAD

**Issue by amuth** [gpac/gpac#670]
Hi,

the current nightly build ignore the "txtflags=...". 

I use the command:

mp4box.exe -add "d:\video.hevc#1" -add "d:\audio.m4a#1" -add "d:\sub_forced.srt#1:txtflags=0xC0000000:enable:hdlr=sbtl:tx3g:layer=-1:group=2:delay=0:lang=DEU:name=deutscher Untertitel (erzwungen)" -new "d:\muxed.mp4" 

For more information have a lock at: 

https://trac.videolan.org/vlc/ticket/16803
or 
https://trac.mpc-hc.org/ticket/5815

Thanks

**Comment by amuth** [comment]
Version 0.6.1 rev0's works still - but not 0.6.2 rev 1001 and later

**Comment by rbouqueau** [comment]
By any chance, would you have two mp4s: one that works, and one that is broken? That would help. Dropbox at https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by amuth** [comment]
upload finished.

**Comment by rbouqueau** [comment]
Thanks but do you think it is possible to upload the mp4 files? If I can catch the diffing bytes, I may fix it fast.

**Comment by amuth** [comment]
I can't help you with the bytes.

PS. I have used the same command in both examples.

**Comment by amuth** [comment]
Problem fixed. Thank you very much

**Comment by jeanlf** [comment]
so no bug on our side ?

**Comment by amuth** [comment]
Everything perfectly since version 1.046

**Comment by amuth** [comment]
Please close
