### ISSUE TITLE
Current git HEAD doesn't compile for me.

### ISSUE THREAD

**Issue by bat999** [gpac/gpac#673]
Hi

This compiles OK...
git checkout 23d343f80fb65ee3de4a84d1eaa6aec48e0e1c06; make distclean; ./configure --static-mp4box --use-zlib=no; make

@mint ~/gpac/bin/gcc $ ./MP4Box -version
MP4Box - GPAC version 0.6.2-DEV-rev1031-g23d343f-HEAD
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: --static-mp4box --use-zlib=no
Features: GPAC_DISABLE_3D GPAC_DISABLE_SWF_IMPORT 

But current HEAD doesn't compile for me...
git checkout 1ec12cfd841475653e16d070bdfcbbdf4e6dbc28; make distclean; ./configure --static-mp4box --use-zlib=no; make

These are the errors...
CC compositor/texturing_gl.c
compositor/texturing_gl.c: In function ‘gf_sc_texture_push_image’:
compositor/texturing_gl.c:1040:36: error: ‘nb_views’ undeclared (first use in this function)
   gf_mo_get_nb_views(txh->stream, &nb_views);
                                    ^
compositor/texturing_gl.c:1040:36: note: each undeclared identifier is reported only once for each function it appears in
compositor/texturing_gl.c:1041:37: error: ‘nb_layers’ undeclared (first use in this function)
   gf_mo_get_nb_layers(txh->stream, &nb_layers);
                                     ^
compositor/texturing_gl.c:1043:40: error: ‘nb_frames’ undeclared (first use in this function)
  if (txh->raw_memory || nb_views == 1) nb_frames = 1;
                                        ^
compositor/texturing_gl.c: In function ‘gf_sc_texture_get_transform’:
compositor/texturing_gl.c:1471:30: error: ‘GF_VisualManager {aka struct _visual_manager}’ has no member named ‘current_view’
   if (txh->compositor->visual->current_view%2 != 0 && !txh->compositor->multiview_mode){
                              ^
../config.mak:143: recipe for target 'compositor/texturing_gl.o' failed
make[1]: *** [compositor/texturing_gl.o] Error 1
make[1]: Leaving directory '/home/user/gpac/src'
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 2

------------------
@mint ~ $ cat /etc/issue
Linux Mint 18 Sarah \n \l
-------------------

**Comment by jeanlf** [comment]
Indeed, now fixed. Thanks for the report

**Comment by bat999** [comment]
Thanks :-)
$ MP4Box -version
MP4Box - GPAC version 0.6.2-DEV-rev1042-gb4e3cda-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: --static-mp4box --use-zlib=no
Features: GPAC_DISABLE_3D GPAC_DISABLE_SWF_IMPORT
