### ISSUE TITLE
VCustom Parameter in dash cast

### ISSUE THREAD

**Issue by rebotnix** [gpac/gpac#675]
is vcustom param working in dash cast?

I tried this one for profiling encoder into baseline.

[v1]
type=video
width=1280
height=720
bitrate=2500000
vcustom="profile=baseline"

same with
vcustom="-profile=baseline"
vcustom="preset=fast"

or with
custom="preset-fast". 

Is vcustom maybe not working in *.conf yet?

**Comment by jeanlf** [comment]
dahscast is now deprecated, use GPAC 0.9.0
