### ISSUE TITLE
DashCast Live Stream - playback unreliable if the segment duration is set less than  16 sec.

### ISSUE THREAD

**Issue by mjoogoo** [gpac/gpac#676]
Hi I'm new to Dashcast.
My objective of creating an MPEG Dash live streaming service (input rtmp, output DASH live available on a portal) 
In my current test setup I use as input file in loop mode.
I test the resulting generated stream with dashjs and with the bitmovin player. In both case the playback interrupts after some seconds with no real error displayed in the player debug.
The only way I managed to have continuos playback of the stream for long itme (> 15 mins) is setting the segment duration  to 16 seconds, that generate a big delay between the input file and the resulting stream. 
Here follow the dashcast command I currently use (working config):
DashCast -conf dashcast.conf -v video10.mp4 -a AudioEng.m4a -npts -mpd-refresh 2 -seg-dur 16000 -live-media -low-delay -out /home/fgiuffrida/SOURCES/ECODEMO/dashcasttest/output -mpd stream.mpd -time-shift 120 -min-buffer 1.0

the dashcast.conf is:
[v1]
type=video
framerate=25
width=720
height=576
bitrate=2482000
codec=libx264
[a1]
type=audio
bitrate=128000
codec=aac
channels=2
samplerate=44000

My input for now are a video file 25 fps and the related audio aac 128k/44100
Audio video quality is good, video keep in sync and ho noises as it is 44100
I tried with chrome and firefox, chrome look more reliable.

Thanks
Francesco.

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/ (I build gpac from git)
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by JamesXu20150314** [comment]
What's the version of your dashcast, I can try to do the same thing with you. However, do you know the problem "[dshow @ 0000000001427b00] real-time buffer 106% full! frame dropped!".
We can help each other.

**Comment by mjoogoo** [comment]
Thanks for spotting the issue.
Dashcast I use is included inn  GPAC 0.6.2-DEV
real-time buffer 106%, any idea how do solve the problem?
I moved on from dashcast and now using to ffmpeg + nginx-rtmp that works fluid, but it would be good to  be able to have both solutions working... .

**Comment by JamesXu20150314** [comment]
Hi mjoogoo,

Oh, that is a good idea to solve this problem.
When comes to the question about the Dashcast, it can cut single bitrate stream. I failed to cut multibitrate streams. R u cut a live/non-live stream in multiple qualities.

James Xu

**Comment by jeanlf** [comment]
dashcast is now deprecated, use GPAC 0.9.0
