### ISSUE TITLE
The source code thinks that I have an old ffmpeg

### ISSUE THREAD

**Issue by Zenitur** [gpac/gpac#679]
Hi! I'm building a repository with Qt 5 for SLES. I need x264 package, and one of the dependencies is gpac. I have no problem to compile the source in SLES 12, but have the problem in SLES 11.

`#ifdef FFMPEG_OLD_HEADERS`
`#include <ffmpeg/avformat.h>`
`#else`
`#include <libavformat/avformat.h>`
`#endif`

I have ffmpeg 3.0 but the compiler anyway sets this variable.

Configuration: SLES 11 SP4, GCC 4.8, ffmpeg 3.0
Repository: https://build.opensuse.org/package/show/home:linux4humans:qt5.6/gpac
RPM SPEC file: https://build.opensuse.org/package/view_file/home:linux4humans:qt5.6/gpac/gpac.spec?expand=1
Full build log: [fail_build_log.zip](https://github.com/gpac/gpac/files/571688/fail_build_log.zip)

**Comment by rbouqueau** [comment]
I have a workaround for this. x264 uses only a small part of GPAC that should be covered by this command-line: http://gpac.io/2015/07/29/gpac-build-mp4box-only-all-platforms/. Let us know if it works.

**Comment by Zenitur** [comment]
Thank you!

Suddenly I saw that x264 and libx264 are SEPARATE packages! o_0 I don't need x264 and gpac too :-)
Now my trouble is Mplayer's configure see ffmpeg but can't use it. The problem is in my side, not in gpac side, so I'm closing the bug
