### ISSUE TITLE
subsamples disappear while DASHing

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#683]

**Comment by jeanlf** [comment]
cannot reproduce here with hevc subsample info, do you have a test file ?

**Comment by rbouqueau** [comment]
yes thx, see attachement [out.zip](https://github.com/gpac/gpac/files/578588/out.zip)

**Comment by jeanlf** [comment]
file is not conformant, the first entry should have a sample_delta of at least 1, not 0. Last git has a patch for that, and the fragment subsamples are OK.

**Comment by rbouqueau** [comment]
thank you!
