### ISSUE TITLE
Question node-gpac-dash compatibility with dash.js

### ISSUE THREAD

**Issue by troppoli** [gpac/gpac#684]
gpac-

I've been looking at node-gpac-dash and don't have any trouble running the node server, serving up a dashcast stream of my webcam and can play it nicely with MP4Client, nice work!

I'm using the "Low-latency DASH Server with live content" scenario. This doesn't seem to be compatible with other dash clients, like dash.js. It would be super helpful to know a little more about why all these demos work with MP4Client but some don't work with browser dash clients.

A short paragraph in the read me for that repo would go a long way, and I'm sure that @cconcolato  could write it in his sleep ;)

**Comment by rbouqueau** [comment]
Hi, thank you. I think the right place for such an issue is the node-gpac-dash repository. node-gpac-dash works with dash.js but not with the lowest latency settings. I think the lowest latency I've seen was 4.5s under dash.js.
