### ISSUE TITLE
DashCast generated mpd fails validation, won't play

### ISSUE THREAD

**Issue by troppoli** [gpac/gpac#686]
I'm setting up a dashcast with this command line:

DashCast  -vres 640x480 -vfr 30 -pixf yuyv422 -vf dshow -v video="Integrated Webcam" -live -low-delay -frag 200 -insert-utc -seg-marker eods -min-buffer 0.2 -ast-offset -800

I've attached the generated mpd file, changing the extension to .txt to allow it to be attached.

[dashcast.txt](https://github.com/gpac/gpac/files/579084/dashcast.txt)

When I run this mpd through http://dashif.org/conformance.html I get validation errors:

> location="/*[local-name()='MPD' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']">
> If MPD is of type "dynamic" publishTime shall be defined.
> 
> Schematron validation not successful - DASH is not valid!

This dashcast fails to play with either dash.js or shaka player.

[dash.js.log.txt](https://github.com/gpac/gpac/files/579128/dash.js.log.txt)
[shaka.log.txt](https://github.com/gpac/gpac/files/579127/shaka.log.txt)

It's not clear from the logs why they don't play, but starting with an invalid mpd seems to be the start of every issue being promptly closed on their end.

**Comment by troppoli** [comment]
I can get playback if I remove the -seg-marker eods option, neither dash.js or shaka will read the segment files with a marker box in them.

**Comment by jeanlf** [comment]
the publishTime issue should now be fixed for dashcast. For the segment marker, you don't need it if you are not using our low latency setup. Not sure why these players don't properly escape on unrecognized boxes though, likely an issue in the underlying media pipeline of the browser.
