### ISSUE TITLE
Error writing data (Bad address)

### ISSUE THREAD

**Issue by zim32** [gpac/gpac#691]
Some strange errors with different combinations of audio/video track selectors.

Example:

`MP4Box -dash-live 4000 -frag 4000 -subdur 4000 -time-shift 20 -dash-ctx ctx.txt -mpd-refresh 1 -profile live -dynamic -out manifest.mpd ./source/movie-2.mp4#video ./source/movie-2.mp4#audio `

Live DASH-ing - press 'q' to quit, 's' to save context and quit
Error writing data (Bad address): 1 blocks to write but 0 blocks written
Next generation scheduled in 3985 ms                        
Slept for 3986 ms before generation
[iso file] Incomplete box mfra                              
[iso file] Incomplete MDAT while file is not read-only
[ISOBMF DASH] Cannot open movie-2_dash_track2_init.mp4 for writing
Error while DASH-ing file: Invalid IsoMedia File            
Error DASHing file: Invalid IsoMedia File

If I don't specify video track everything is fine

`MP4Box -dash-live 4000 -frag 4000 -subdur 4000 -time-shift 20 -dash-ctx ctx.txt -mpd-refresh 1 -profile live -dynamic -out manifest.mpd ./source/movie-2.mp4 ./source/movie-2.mp4#audio`

Live DASH-ing - press 'q' to quit, 's' to save context and quit
Next generation scheduled in 3985 ms                        
Slept for 3984 ms before generation
Next generation scheduled in 3987 ms                 

If I don't specify audio track - error:

`MP4Box -dash-live 4000 -frag 4000 -subdur 4000 -time-shift 20 -dash-ctx ctx.txt -mpd-refresh 1 -profile live -dynamic -out manifest.mpd#video ./source/movie-2.mp4`

Error writing data (Bad address): 1 blocks to write but 0 blocks written
Next generation scheduled in 3990 ms                        
Slept for 3989 ms before generation
[iso file] Incomplete box mfra
[iso file] Incomplete MDAT while file is not read-only
[ISOBMF DASH] Cannot open movie-2_dashinit.mp4 for writing
Error while DASH-ing file: Invalid IsoMedia File 

**MP4Box version**
MP4Box - GPAC version 0.6.2-DEV-rev1055-gae717dc-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: 
Features: GPAC_64_BITS GPAC_DISABLE_3D

**Source file info**
`MP4Box -info ./source/movie-2.mp4 `
* Movie Info *
	Timescale 1000 - 2 tracks
	Computed Duration 00:00:00.000 - Indicated Duration 00:00:00.000
	Fragmented File: yes - duration 00:00:00.000
50 fragments - 2 SegmentIndexes
	File suitable for progressive download (moov before mdat)
	File Brand iso5 - version 512
		Compatible brands: iso6 mp41
	Created: UNKNOWN DATE	Modified: UNKNOWN DATE
File has no MPEG4 IOD/OD

iTunes Info:
	Encoder Software: Lavf56.25.101
1 UDTA types: meta (1) 

Track # 1 Info - TrackID 1 - TimeScale 12288
Media Duration 00:00:00.000 - Indicated Duration 00:00:00.000
Media Info: Language "Undetermined (und)" - Type "vide:avc1" - 0 samples
Fragmented track: 1185 samples - Media Duration 00:00:49.375
Visual Track layout: x=0 y=0 width=1920 height=1080
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x21
AVC/H264 Video - Visual Size 1920 x 1080
	AVC Info: 1 SPS - 1 PPS - Profile High @ Level 5
	NAL Unit length bits: 32
	Pixel Aspect Ratio 1:1 - Indicated track size 1920 x 1080
	Chroma format YUV 4:2:0 - Luma bit depth 8 - chroma bit depth 8
	SPS#1 hash: 46EBB3B8F7C743A9CA82281CC69727368F277CEE
	PPS#1 hash: DC73BC45117A5611E4C7638CE58777ED2E22E887
Self-synchronized
	RFC6381 Codec Parameters: avc1.640032
	No sync sample found

Track # 2 Info - TrackID 2 - TimeScale 32000
Media Duration 00:00:00.000 - Indicated Duration 00:00:00.000
Media Info: Language "Undetermined (und)" - Type "soun:mp4a" - 0 samples
Fragmented track: 1536 samples - Media Duration 00:00:49.203
MPEG-4 Config: Audio Stream - ObjectTypeIndication 0x40
MPEG-4 Audio AAC LC - 2 Channel(s) - SampleRate 32000
Synchronized on stream 1
	RFC6381 Codec Parameters: mp4a.40.2
Alternate Group ID 1
	All samples are sync

**Comment by jeanlf** [comment]
it looks like you dash with MP4Box while encoding with ffmpeg. You're lucky this even works at all (file io won't be synchronized). Use GPAC 0.9.0 to do this
