### ISSUE TITLE
MP4box

### ISSUE THREAD

**Issue by CyberGhost84** [gpac/gpac#692]
hey,

i am getting this error when trying edit the audio language tag.

```
find /Volumes/PlexMedia\ 2/Anime\ TV\ Shows/Naruto\ Shippuden/Season\ 1 -iname '*.mp4' -execdir MP4Box -lang ger {} \;
Error opening file Naruto Shippuden s01e31.mp4: Invalid IsoMedia File
[iso file] Incomplete MDAT while file is not read-only
```

can anyone help me out?

here is the file i tested:

https://www.dropbox.com/s/oitqszvayd8rwc4/Naruto%20Shippuden%20s01e01.mp4?dl=0

Thank you guys :)

**Comment by rbouqueau** [comment]
Hi,

I could reproduce: the file is incomplete. Could you try to re-download it from your source ane retry please?

**Comment by CyberGhost84** [comment]
you mean the file i tested?

https://www.dropbox.com/s/7hslkp1qd48bg7d/Naruto%20Shippuden%20s01e01.mp4.zip?dl=0

**Comment by rbouqueau** [comment]
Yes

**Comment by CyberGhost84** [comment]
Thats the file like it is downloaded from source: i can play it in vlc 
, plex etc...

**Comment by rbouqueau** [comment]
Yes, but it doesn't mean the file is correct. Please reimport it first to eliminate errors: ```MP4Box -add myfile.mp4 myfile_correct.mp4```. Check the file is still ok for you (e.g. truncated, missing tracks, etc.) Then apply your modifications.

Let me know if it works for you.

**Comment by CyberGhost84** [comment]
Yes that worked :)
thank you

possible to do that with multiples files/folder at once?

**Comment by CyberGhost84** [comment]
`MP4Box -add myfile.mp4 myfile_correct.mp4
`
possible to do that with multiples files/folder at once?
also is there a way to change the language tag of an audio stream in avi files?

is there away to make you guys a donation for your help u gaved me?

thanks again

**Comment by rbouqueau** [comment]
> possible to do that with multiples files/folder at once?

Not with MP4Box, but you should be able to write a unix shell script for that.

> also is there a way to change the language tag of an audio stream in avi files?

We only handle mp4 files, not avi. Although you could import tham in MP4 ('MP4Box -add file.avi file.mp4) and apply the tags then. Would it suit your need?

> is there away to make you guys a donation for your help u gaved me?

Thanks for proposing. We don't take donations for the open-source part. However we have an industry part if you need some professional support at some point.

**Comment by CyberGhost84** [comment]
> Not with MP4Box, but you should be able to write a unix shell script for that.

Could you maybe help me with that :/?

> We only handle mp4 files, not avi. Although you could import tham in MP4 ('MP4Box -add file.avi file.mp4) and apply the tags then. Would it suit your need?

Yes that will work me but i have over 200 files that i need to import:/

> is there away to make you guys a donation for your help u gaved me?

ok thank you :)

**Comment by rbouqueau** [comment]
> Could you maybe help me with that :/?

Something like that:
```
for i in `ls -lR *.mp4`; do
  newName=$(echo $i | sed 's/\.mp4$/_correct.mp4/'); 
  MP4Box -add $i $newName
done
```
should do the trick. Test it locally first.

> Yes that will work me but i have over 200 files that i need to import:/

On my laptop with a SSD, processing your file took me 12s. 12s * 200 = 2400s = 40 minutes. If you can automatize the whole process, that sounds quite fast.

**Comment by CyberGhost84** [comment]
```
for i in `ls -lR *.mp4`; do
  newName=$(echo $i | sed 's/\.mp4$/_correct.mp4/'); 
  MP4Box -add $i $newName
done
```
Many thanks :)

So for my avi files to be mp4 files and change the audio tag that will be then:

```
for i in `ls -lR *.avi`; do
  newName=$(echo $i | sed 's/\.avi$/_correct.mp4/'); 
  MP4Box -add $i $newName
done
```

Right :/?

Thanks again :)

**Comment by rbouqueau** [comment]
This would allow you to import you AVI into MP4s, yes.

**Comment by CyberGhost84** [comment]
```
for i in `ls -lR *.mp4`; do
  newName=$(echo $i | sed 's/\.mp4$/_correct.mp4/'); 
  MP4Box -add $i $newName
done
```

i think i am not using the script like i have to?

```
Last login: Tue Nov 15 11:46:55 on ttys000
CyberGhost:Season 1 CyberGhost$ for i in `ls -lR *.avi`; do
>   newName=$(echo $i | sed 's/\.avi$/_correct.mp4/'); 
>   MP4Box -add $i $newName
> done
Option -rw-r--r-- unknown. Please check usage
[Importer] Unknown input file type for "1"
Error importing 1: Requested URL is not valid or cannot be found
```

I get an error importing:/

**Comment by rbouqueau** [comment]
I did it fast. either you can remove the -l in ls -lR => ls -R but I don't know how it handles the directories, or you can use find: 
```
for i in `find . -name '*.mp4'`; do
  newName=$(echo $i | sed 's/\.mp4$/_correct.mp4/'); 
  MP4Box -add $i $newName
done
```

I think you'll get some better help on stackoverflow for these issues :)

**Comment by CyberGhost84** [comment]
ok thank you for your time and help
