### ISSUE TITLE
Utilize padding for in place editing

### ISSUE THREAD

**Issue by ghost** [gpac/gpac#693]
The [TagEditor project][1] supports padding, which allows in place editing of a
file:

~~~sh
$ time tageditor -s cover=y.jpg --max-padding 100000 -f z.mp4
real    0m1.988s
~~~

However MP4Box rewrites the entire file; this can be slow with large files:

~~~sh
$ time mp4box -itags cover=y.jpg z.mp4
real    0m12.911s
~~~

Does MP4Box support in place editing of files?

[1]://github.com/Martchus/tageditor#padding

**Comment by svnpenn** [comment]
https://github.com/Martchus/tageditor/issues/9

**Comment by svnpenn** [comment]
https://github.com/axiomatic-systems/Bento4/issues/104

**Comment by jeanlf** [comment]
Not really planned for the moment. We would need to know how much space to reserve up-front when creating the tagging box, and it will not work when editing tags on files without any reserved space in that box.

**Comment by jeanlf** [comment]
Now on git, adding a howto on the topic asap

**Comment by jeanlf** [comment]
Howto: https://github.com/gpac/gpac/wiki/mp4box-inplace
