### ISSUE TITLE
Question about new functions attachments for HEVC

### ISSUE THREAD

**Issue by Jamaika1** [gpac/gpac#695]
Can you ask for about examples of applications with new functions attachments (maybe covers) for HEVC?
- [ ] Are these functions only player GPAC? _"set-meta ABCD"_
- [ ] What can image formats be added? 
- [ ] Can the attachment be combined interactively with pages XML?

Code:
" -set-meta args       sets given meta type - syntax: "ABCD[:tk=ID]"\n"
"                       * ABCD: four char meta type (NULL or 0 to remove meta)\n"
"                       * [:tk=ID]: if not set use root (file) meta\n"
"                                if ID is 0 use moov meta\n"  
"                                if ID is not 0 use track meta\n"  
" -add-item args       adds resource to meta\n"  
"                       * syntax: file_path + options (\':\' separated):\n"  
"                        file_path "this" or "self": item is the file itself\n"  
"                        tk=ID:            meta location (file, moov, track)\n"  
"                        name=str:         item name\n"  
"                        type=itype:       item 4cc type (not needed if mime is provided)\n"  
"                        mime=mtype:       item mime type\n"  
"                        encoding=enctype: item content-encoding type\n"  
"                        id=id:	           item ID\n"  
"                        ref=4cc,id:       reference of type 4cc to an other item\n"  
"                      Image Item options\n"  
"                        image-size=wxh      sets the width and height of the image.\n"  
"                        image-pasp=wxh      sets the pixel aspect ratio property of the image.\n"  
"                        image-rloc=wxh      sets the location of this image within another image item.\n"  
"                        image-irot=a        sets the rotation angle for this image to 90*a degrees anti-clockwise.\n"  
"                        image-hidden        indicates that this image item should be hidden.\n"  
" -rem-item args       removes resource from meta - syntax: item_ID[:tk=ID]\n"  
" -set-primary args    sets item as primary for meta - syntax: item_ID[:tk=ID]\n"  
" -set-xml args        sets meta XML data\n"  
"                       * syntax: xml_file_path[:tk=ID][:binary]\n"  
" -rem-xml [tk=ID]     removes meta XML data\n"  
" -dump-xml args       dumps meta XML to file - syntax file_path[:tk=ID]\n"  
" -dump-item args      dumps item to file - syntax item_ID[:tk=ID][:path=fileName]\n"  
" -package             packages input XML file into an ISO container\n"  
"                       * all media referenced except hyperlinks are added to file\n"  
" -mgt                 packages input XML file into an MPEG-U widget with ISO container.\n"  
"                       * all files contained in the current folder are added to the widget package\n"  
);Adding support for MPEG Image File Format (mainly HEVC, incl. tiles)

**Comment by cconcolato** [comment]
I'm not sure I understand the question. If the question is how to create MPEG Image Files according to IFF, the current uses are:
To create a single image item:
```
MP4Box -add-image file.hvc:id=1 -set-primary 1 -ab heic -new iff_hevc_single_item.heic
```
To create N items from a tiled HEVC stream:
```
MP4Box -add-image counter_tiled_track1.hvc:tilemode=base:id=1 -set-primary 1 -ab heic -new iff_hevc_tile_multiple_items_tbas.heic
```

Currently, MP4Box uses the first sample of the HEVC stream to create the image item(s). This needs to be extend to be able to specify a sample time (instead of 0), to support the usual import parameters (e.g fmt, ...), etc. Tests and documentation are needed too ...

**Comment by Jamaika1** [comment]
Thanks for the answer. I do not understand. Can you to transcribe more?
Very interesting examples. You'd have to write out something more about .heic images.
https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format

More interested in adding new functions "udta" ref and type. How is it used?
I have a file Panasonic. How to add a file to the metadata in the file mp4?
General
Complete name: D: \ london_eye.mov
Format: MPEG-4
Format profile: QuickTime
Codec ID: qt 2011.07 (qt / master)
File size: 141 MiB
Duration: 12 sec 0 ms
Overall bit rate mode: Variable
Overall bit rate: 98.3 Mb / s
Encoded date: UTC 2016-03-13 12:15:57
Tagged date: UTC 2016-03-13 12:15:57
**PANA: .............** <<-file txt info PANA

or
**Attachment: counter_tiled_track1.hvc**

What does function :tilemode? Is it the same thing :type?
