### ISSUE TITLE
Question - how to ecrypt not fragmented mp4 file and play it in any browser

### ISSUE THREAD

**Issue by acumarav** [gpac/gpac#699]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X ] I looked for a similar issue and couldn't find any.

I am trying to encrypt not-fragmented ISOBMFF mp4 file and play it in any browser using EME, I am using js code similar to this example: https://www.html5rocks.com/en/tutorials/eme/basics/
just my encrypted mp4 files instead of webm. The problem is that browser (Chrome, FF, Edge) do not raise 'encrypted' event  and start to play encrypted data (random green squares appear).
According to this spec:
https://www.w3.org/TR/2014/WD-encrypted-media-20140828/cenc-format.html#detect-encrypt
 Browser should detect encrypted content and raise the event but it does not. 
So my question - is it because of incorrectly encrypted mp4 or because of the browser.
Is there any examples for mp4?
Thank you

**Comment by rbouqueau** [comment]
Did you have the opportunity to read this? https://html5.cablelabs.com/mse-eme/doc/overview.html

**Comment by tsuria** [comment]
I see the samples, but cannot find any code or binaries like playready.jar or encrypt.sh helper. Is it commercial tools?

**Comment by rbouqueau** [comment]
It used to be here https://github.com/cablelabs/mse-eme
Could you drop them an email? I will too.

**Comment by rbouqueau** [comment]
The author doesn't work at CableLabs anymore. A copy found at https://github.com/abdul/mse-eme

**Comment by jeanlf** [comment]
also check https://github.com/gpac/gpac/wiki/Common-Encryption
