### ISSUE TITLE
Attaching info to cached segment

### ISSUE THREAD

**Issue by canatella** [gpac/gpac#70]
Regarding pull request #69, is there a way to attach custom data to a download session or to a cached file ? It would allow me to associate the key and iv of a segment to it's local copy and move the decryption at a better place. Also, could you point me to a good place where to do the decrypting ?

Thanks.

**Comment by jeanlf** [comment]
With GPAC 0.9.0, files are transmitted to consumers as data packets, and can therefore have any property you want attached to it. Loot at the source code of [fin](fin) and [httpin](httpin).
