### ISSUE TITLE
DashCast live segment Problem

### ISSUE THREAD

**Issue by JamesXu20150314** [gpac/gpac#701]
Hi all,

I have a problem about the tools dashcast.

I segment the region of my screen in Win 10 64bit.

My command is:

E:\wamp\www>DashCast -vf dshow -vres 320x240 -vfr 5 -v video="e2eSoft VCam" -npts -low-delay -time-shift -1 -seg-dur 2000 -live

Here is my conf file:
![image](https://cloud.githubusercontent.com/assets/11470231/20549453/41307f40-b167-11e6-8609-e1f4ceae7792.png)

The problem as follows:
![image](https://cloud.githubusercontent.com/assets/11470231/20549479/8a9f3c70-b167-11e6
![image](https://cloud.githubusercontent.com/assets/11470231/20549487/a212ca16-b167-11e6-97e5-0a2aa67792bc.png)

And my dashcast version as follows:
![image](https://cloud.githubusercontent.com/assets/11470231/20549508/eb9e93ea-b167-11e6-8425-02f18f94ccd6.png)

Who can help me. I will very grateful for your help.

James

**Comment by JamesXu20150314** [comment]
At the begin of the segment:
![image](https://cloud.githubusercontent.com/assets/11470231/20549860/039ca5b0-b16b-11e6-946c-95245b6e3cdb.png)

**Comment by jeanlf** [comment]
dashcast is deprecated, pleaseu use GPAC 0.9.0
