### ISSUE TITLE
MP4Box -chap miscalculates the chapter start time when microseconds are specified

### ISSUE THREAD

**Issue by QuestionDriven** [gpac/gpac#706]
###  Issue
MP4Box miscalculates the chapter start time when microseconds are specified in the chapterfile.

If you specify CHAPTER2=00:01:30.048293, then the CHAPTER2 start from 00:02:18.293.
The calculation logic seem to be 00:01:30 + 048 seconds + 293 milliseconds.

Microseconds might not be supported as a spec but this behavior makes it really hard to find the root cause when it's occured. So, I hope it will be fixed in some way and be documented somewhere.

###  How to reproduce
**1.  Prepare a chapterfile with microseconds specified like below**
```
CHAPTER1=00:00:00.000000
CHAPTER1NAME=test1
CHAPTER2=00:01:30.048293
CHAPTER2NAME=test2
CHAPTER3=00:03:00.054876
CHAPTER3NAME=test3
CHAPTER4=00:04:30.103168
CHAPTER4NAME=test4
```

**2.  Execute the mp4box command with -chap option**
` mp4box -chap chapterfile input.mp4` 

**3. Check the Result with -info option**
` mp4box -info input.mp4`

```
Chapters:
	Chapter #1 - 00:00:00.000 - "test1"
	Chapter #2 - 00:02:18.293 - "test2"
	Chapter #3 - 00:03:54.876 - "test3"
	Chapter #4 - 00:06:13.168 - "test4"
```
**4. Misc.**
a file named *input*.chap, which contains below, is automatically created by the mp4box -chap when this issue occurred.
```
AddChapterBySecond(0,test1)
AddChapterBySecond(138,test2)
AddChapterBySecond(234,test3)
AddChapterBySecond(373,test4)
```  

###  Environment
- Mac OSX 10.11.6
- MP4Box -version
MP4Box - GPAC version 0.6.2-DEV-rev1133-gc77fdae-master
- GPAC: downloaded from here
http://download.tsi.telecom-paristech.fr/gpac/latest_builds/macosx_64/gpac-0.6.2-DEV-latest-master.dmg

**Comment by jeanlf** [comment]
now fixed in GPAC 0.9.0, thanks for the report
