### ISSUE TITLE
DashCast (built on Fedora) I am not able to stream, does not stop running with input .mp4 file

### ISSUE THREAD

**Issue by cbrady60** [gpac/gpac#709]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

This is my first time using this tool. I followed instructions on https://gpac.wp.mines-telecom.fr/dashcast/ to build everything since I am on Fedora. I am on Fedora (see below) so I could not find several of the dependencies from  the line from the url which are Debian specific ...
 sudo apt-get install make pkg-config g++ zlib1g-dev firefox-dev libfreetype6-dev libjpeg62-dev libpng12-dev libopenjpeg-dev libmad0-dev libfaad-dev libogg-dev libvorbis-dev libtheora-dev liba52-0.7.4-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavresample-dev libxv-dev x11proto-video-dev libgl1-mesa-dev x11proto-gl-dev linux-sound-base libxvidcore-dev libssl-dev libjack-dev libasound2-dev libpulse-dev libsdl1.2-dev dvb-apps libavcodec-extra-53 libavdevice-dev libmozjs185-dev

Do you have detailed instructions for building on Fedora/Centos, because I do not discount the possibility that I have an incorrect library even though I got no errors during build.

[recording2_DashCast_output.txt](https://github.com/gpac/gpac/files/625686/recording2_DashCast_output.txt)

[dashcast_conf.txt](https://github.com/gpac/gpac/files/625687/dashcast_conf.txt)

[tar.gz](https://github.com/gpac/gpac/files/625695/tar.gz)

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/  
The linux installers are for Ubuntu, I am on fedora...  
# uname -a
Linux localhost.localdomain 3.19.8-100.fc20.x86_64 #1 SMP Tue May 12 17:08:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
# cat /etc/issue
Fedora release 20 (Heisenbug)
Kernel \r on an \m (\l)

- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

I have attached the following:
dashcast_conf.txt - Configuration file used renamed from dashcast.conf
recording2_DashCast_output.txt - The DashCast command line execution and output.
tar.gz - Contains the output directory produced by DashCast as well as the recording2.mp4 file used as input 

Let me know if I need to send more info.

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by cbrady60** [comment]
I am going to download debian nightly build and  try converting to rpm with downloaded version of alien I just found out about.

**Comment by cbrady60** [comment]
Tried using "alien" conversion of builds gpac_0.6.2-DEV-rev1166-g517222a-master_amd64.deb and libgpac-dev_0.6.2-DEV-rev1166-g517222a-master_amd64.deb  from https://gpac.wp.mines-telecom.fr/downloads/gpac-nightly-builds/ to rpms. Installation of these converted rpms mostly failed as they require older versions of libraries that are not compatible (checked rpmfind.net) with the version of Fedora I have.

Then tried latest builds at https://gpac.wp.mines-telecom.fr but DashCast not in bin directory. 
Help needed.

**Comment by cbrady60** [comment]
Correction for previous comment ... Then  tried latest builds at  https://gpac.wp.mines-telecom.fr/downloads/gpac-nightly-builds/  but DashCast not in bin directory

**Comment by cbrady60** [comment]
I had let DashCast run for maybe 30min before killing it and the outtput to stdout just kept repeating

**Comment by cbrady60** [comment]
From looking at the version of code that came when I followed the instructions from https://gpac.wp.mines-telecom.fr/dashcast i see that the code looks for a "switch.conf" file even if one is not supplied. I do not have one or know what the contents should be. So there seems to be several areas where it could be "operator error".

**Comment by cbrady60** [comment]
Any suggestions, recommendations or info?

**Comment by jeanlf** [comment]
Dashcast is deprecated, please use GPAC 0.9.0
