### ISSUE TITLE
[Android] Camera fail

### ISSUE THREAD

**Issue by fcsteagu** [gpac/gpac#71]
I'm using a BT file to open the camera but the video stream seems to be rotated (90deg counterclockwise) and there are horizontal green and pink lines. The pixels become all green when the camera is covered.
In the portrait mode I get these lines and the camera view is not scaled properly while in the landscape mode the lines are not that visible but the pixel colors are messed up.
I have attached 2 screenshots.
The BT code that I'm using is:

```
    Shape {
        appearance Appearance {
            texture DEF MT MovieTexture {
                url ["hw://camera"]
            }
        }
         geometry Rectangle {
                size 800 480
         }
    }
```

I don't know if the issue is related to OpenGL but this is one of the messages that I get in the logs:
`9372-9542/com.gpac.Osmo4 W/Adreno-ES20﹕ <process_gl_state_enables:511>: GL_INVALID_ENUM`

![screenshot_2015-03-18-15-07-46](https://cloud.githubusercontent.com/assets/2527837/6710413/cc504f46-cd80-11e4-8a0d-b7fde231497b.png)
![screenshot_2015-03-18-15-07-28](https://cloud.githubusercontent.com/assets/2527837/6710414/cc5237ca-cd80-11e4-99ff-51936d74c554.png)

**Comment by nguyen-viet-thanh-trung** [comment]
It should be an issue in preview with certain Android devices: http://stackoverflow.com/questions/3841122/android-camera-preview-is-sideways.
The proposed solution doesn't work with me in Nexus 5.

**Comment by jeanlf** [comment]
I think this was a bug in glsl code but has been fixed some time ago. Reopen if needed
