### ISSUE TITLE
Question : Could some one brief the procedure how SRD feature is implemented in osmo4_androidstudio

### ISSUE THREAD

**Issue by SrujithPoondla** [gpac/gpac#710]
I couldn't find which part of the code is parsing .mpd or leveraging the content form .mpd to play the video. Could anyone help in this? @jeanlf @rbouqueau 

Is there any possibility of displaying only specific tiles in the video using osmo4 app?

**Comment by SrujithPoondla** [comment]
I could find the parsing of mpd file but couldn't understand how the SRD feature is implemented, Could some one brief it?

**Comment by jeanlf** [comment]
we have two variants of SRD support:
* SRD regions are independent videos: if 2D, one rect per tile is created (src/terminal/scene.c@gf_scene_regenerate) if 3D one sub-sphere per region is created (src/compositor/hardcoded_protos.c@TraverseVRGeometry for the rendering code)

* SRD regions are actually HEVC tiles forming a single bitstream: in 2D a single rectangle is created, in 3D a single sphere (again check src/terminal/scene.c@gf_scene_regenerate)

HTH,
