### ISSUE TITLE
Android mediadec_dec module crashes on some streams

### ISSUE THREAD

**Issue by canatella** [gpac/gpac#711]
On my device, all HLS and some Dash streams crash Osmo4.

Device: OnePlus 2, Android 6.0.1
Sample streams: 
- http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8
- http://rdmedia.bbc.co.uk/dash/ondemand/bbb/2/client_manifest-common_init.mpd

GPAC Nightly: osmo4-0.6.2-DEV-rev1172-g3782ef6-master.apk

Log:

12-06 17:13:51.313  8786  8786 D Osmo4   : Copy assets of shaders
12-06 17:13:51.533  8786  8803 I GPAC_WRAPPER: Selected JNI VERSION[0]
12-06 17:13:51.533  8786  8803 I GPAC_WRAPPER: Registering com/gpac/Osmo4/GPACInstance natives
12-06 17:13:51.533  8786  8803 I GPAC_WRAPPER: Registering 12 methods...
12-06 17:13:51.533  8786  8803 I GPAC_WRAPPER: Registering natives DONE, now registering pthread_keys with destructor=0xdd648309
12-06 17:13:51.534  8786  8803 I GPAC_WRAPPER: Initializing GPAC with URL=http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8...
12-06 17:13:51.534  8786  8803 I GPAC_WRAPPER: GPAC.cfg found in /storage/emulated/0/osmo/, force using it.
12-06 17:13:51.534  8786  8803 I GPAC_WRAPPER: Loading User Config GPAC.cfg...
12-06 17:13:51.535  8786  8803 I GPAC_WRAPPER: loading modules in directory /data/data/com.gpac.Osmo4/lib...
12-06 17:13:51.537  8786  8803 D GPAC_WRAPPER: Loading GPAC terminal, m_user=0xdf753014...
12-06 17:13:51.538  8786  8803 V GPAC_WRAPPER: SetupLogs()
12-06 17:13:51.564  8786  8807 I GPAC_WRAPPER: Rebuilding methods for thread -582481616
12-06 17:13:51.564  8786  8807 I GPAC_WRAPPER: Getting current Thread -582481616...
12-06 17:13:51.564  8786  8807 I GPAC_WRAPPER: Getting current Thread DONE = 0xdd599118, now registering before exit...
12-06 17:13:51.564  8786  8807 I GPAC_WRAPPER: Registering DONE for -582481616
12-06 17:13:51.567  8786  8803 D GPAC_WRAPPER: Setting term size m_user=0xdf753014...
12-06 17:13:51.567  8786  8803 D GPAC_WRAPPER: GPAC_EventProc() Message=88
12-06 17:13:51.567  8786  8803 I GPAC_WRAPPER: Unknown Message 88
12-06 17:13:51.567  8786  8803 D GPAC_WRAPPER: File loaded at startup=/data/data/com.gpac.Osmo4/gui/gui.bt.
12-06 17:13:51.567  8786  8803 I GPAC_WRAPPER: Connecting to http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8...
12-06 17:13:51.627  8786  8803 V GPAC_WRAPPER: init end
12-06 17:13:51.627  8786  8803 D GPAC_WRAPPER: Saving config file...
12-06 17:13:51.627  8786  8803 I GPAC_WRAPPER: Initialization complete, config file saved.
12-06 17:13:51.627  8786  8803 I Osmo4   : GPAC is ready
12-06 17:13:51.627  8786  8803 V GPAC_WRAPPER: resize start
12-06 17:13:51.628  8786  8803 D GPAC_WRAPPER: GPAC_EventProc() Message=88
12-06 17:13:51.628  8786  8803 I GPAC_WRAPPER: Unknown Message 88
12-06 17:13:51.628  8786  8803 V GPAC_WRAPPER: resize end
12-06 17:13:52.000  8786  8811 I GPAC_WRAPPER: Rebuilding methods for thread -589563600
12-06 17:13:52.000  8786  8811 I GPAC_WRAPPER: Getting current Thread -589563600...
12-06 17:13:52.000  8786  8811 I GPAC_WRAPPER: Getting current Thread DONE = 0xdd599370, now registering before exit...
12-06 17:13:52.000  8786  8811 I GPAC_WRAPPER: Registering DONE for -589563600
12-06 17:13:52.031  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=112
12-06 17:13:52.031  8786  8811 I GPAC_WRAPPER: Unknown Message 112
12-06 17:13:52.031  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=125
12-06 17:13:52.031  8786  8811 I GPAC_WRAPPER: Unknown Message 125
12-06 17:13:52.031  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=101
12-06 17:13:52.031  8786  8811 V GPAC_WRAPPER: MessageBox start Connected
12-06 17:13:52.031  8786  8811 D Osmo4   : Connected
12-06 17:13:52.032  8786  8811 V GPAC_WRAPPER: MessageBox done Connected
12-06 17:13:52.055  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=102
12-06 17:13:52.055  8786  8811 I GPAC_WRAPPER: Unknown Message 102
12-06 17:13:52.055  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=88
12-06 17:13:52.055  8786  8811 I GPAC_WRAPPER: Unknown Message 88
12-06 17:13:52.055  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=129
12-06 17:13:52.055  8786  8811 V GPAC_WRAPPER: We received Sensor Request for turning OFF location sensors
12-06 17:13:52.056  8786  8811 I Osmo4   : Received Un-Register Sensors call
12-06 17:13:52.056  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=88
12-06 17:13:52.056  8786  8811 I GPAC_WRAPPER: Unknown Message 88
12-06 17:13:52.056  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=111
12-06 17:13:52.056  8786  8811 I GPAC_WRAPPER: Unknown Message 111
12-06 17:13:52.056  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=125
12-06 17:13:52.056  8786  8811 I GPAC_WRAPPER: Unknown Message 125
12-06 17:13:52.056  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=108
12-06 17:13:52.057  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=108
12-06 17:13:52.057  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=108
12-06 17:13:52.057  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=108
12-06 17:13:52.057  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=108
12-06 17:13:52.057  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=108
12-06 17:13:52.057  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=108
12-06 17:13:52.057  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=108
12-06 17:13:52.058  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=108
12-06 17:13:52.058  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=108
12-06 17:13:52.058  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=108
12-06 17:13:52.058  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=108
12-06 17:13:52.058  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=108
12-06 17:13:52.058  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=108
12-06 17:13:52.058  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=108
12-06 17:13:52.058  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=108
12-06 17:13:52.058  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=108
12-06 17:13:52.058  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=108
12-06 17:13:52.058  8786  8811 D GPAC_WRAPPER: GPAC_EventProc() Message=108
12-06 17:13:52.067  8786  8807 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 8807 (Thread-16347)
12-06 17:13:52.134  8817  8817 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-06 17:13:52.134  8817  8817 F DEBUG   : Build fingerprint: 'OnePlus/OnePlus2/OnePlus2:6.0.1/MMB29M/1447840920:user/release-keys'
12-06 17:13:52.134  8817  8817 F DEBUG   : Revision: '0'
12-06 17:13:52.134  8817  8817 F DEBUG   : ABI: 'arm'
12-06 17:13:52.134  8817  8817 F DEBUG   : pid: 8786, tid: 8807, name: Thread-16347  >>> com.gpac.Osmo4 <<<
12-06 17:13:52.134  8817  8817 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
12-06 17:13:52.134  8817  8817 F DEBUG   :     r0 00000000  r1 dd48073c  r2 00000000  r3 00000000
12-06 17:13:52.134  8817  8817 F DEBUG   :     r4 ef4c80c0  r5 00000000  r6 e056dcf5  r7 000003f4
12-06 17:13:52.134  8817  8817 F DEBUG   :     r8 f74dbec0  r9 dd480840  sl 00000000  fp e0482000
12-06 17:13:52.134  8817  8817 F DEBUG   :     ip e0571f3c  sp dd480738  lr e056dd2d  pc e055de6c  cpsr 600f0030
12-06 17:13:52.137  8817  8817 F DEBUG   :
12-06 17:13:52.137  8817  8817 F DEBUG   : backtrace:
12-06 17:13:52.137  8817  8817 F DEBUG   :     #00 pc 00005e6c  /system/lib/libmediandk.so (AMediaCodec_dequeueInputBuffer+5)
12-06 17:13:52.137  8817  8817 F DEBUG   :     #01 pc 00001d29  /data/app/com.gpac.Osmo4-1/lib/arm/libgm_mediacodec_dec.so
12-06 17:13:52.137  8817  8817 F DEBUG   :     #02 pc 001c4b9b  /data/app/com.gpac.Osmo4-1/lib/arm/libgpac.so
12-06 17:13:52.137  8817  8817 F DEBUG   :     #03 pc 001c5629  /data/app/com.gpac.Osmo4-1/lib/arm/libgpac.so
12-06 17:13:52.137  8817  8817 F DEBUG   :     #04 pc 001c5745  /data/app/com.gpac.Osmo4-1/lib/arm/libgpac.so (MM_Loop+108)
12-06 17:13:52.137  8817  8817 F DEBUG   :     #05 pc 0014c5ed  /data/app/com.gpac.Osmo4-1/lib/arm/libgpac.so (RunThread+136)
12-06 17:13:52.137  8817  8817 F DEBUG   :     #06 pc 0003fa43  /system/lib/libc.so (_ZL15__pthread_startPv+30)
12-06 17:13:52.137  8817  8817 F DEBUG   :     #07 pc 00019fd5  /system/lib/libc.so (__start_thread+6)

From what I could see from my own build, it seems that in mediacodec_dec.c, in MCDec_AttachStream:

- esd->decoderConfig->objectTypeIndication == GPAC_OTI_VIDEO_AVC is true
- esd->decoderConfig->decoderSpecificInfo->data is NULL

so it goes through the return GF_OK at line 381 and does not allocate ctx->codex.

Then it crashes in MCDec_ProcessData on line 530 when AMediaCodec_dequeueInputBuffer tries to access ctx->pointer which is NULL.

I've tried with multiple stream and it's always the same problem. It's more or less working for other streams:  http://www.bok.net/dash/tears_of_steel/cleartext/stream.mpd, or on some local files but then if I download a segment from the failing stream and try to play them locally, it's still crashing.

**Comment by jeljeli** [comment]
we're working on this. we have a version that supports HLS, we're into the testing.
This version will shortly be available

**Comment by canatella** [comment]
Working better now but I still have problems with the first stream after +/- 1 minute. The seconds as lots of skips. Tell me if I can do anything to help.

**Comment by jeanlf** [comment]
should have been fixed some time ago, please reopen if needed
