### ISSUE TITLE
+ How to create default subtitles?

### ISSUE THREAD

**Issue by surikat1978** [gpac/gpac#713]
Good day !
How to create default subtitles . (automatically played together with the video). mp4 fragments without cut - in one file.

MP4Box -dash 1000 -profile live video.mp4#trackID=2:id=audio video.mp4#trackID=1:id=video video.mp4#trackID=3:id=subtitle -out video.mpd

What's missing here?

**Comment by rbouqueau** [comment]
If you set ```-profile live``` then you are explicitly asking for multiple segments. Try with ```-profile ondemand```.
