### ISSUE TITLE
Feature request: option to add rotate flag

### ISSUE THREAD

**Issue by Selur** [gpac/gpac#723]
Reencoding a rotated android video and try to remux the reencode atm. I use ffmpeg with
` -metadata:s:v:0 rotation=90 `

since I prefer MP4Box I was wondering there either is an option I'm not aware of or if one could be added to add a rotation flag ?

sample of a video with the flag: http://forum.gleitz.info/attachment.php?attachmentid=99239&d=1482082115

**Comment by rbouqueau** [comment]
This is somewhere in my roadmap too! Thanks for the sample.

**Comment by vdutell** [comment]
*bump* Any update on this?

**Comment by jeanlf** [comment]
done in GPAC 0.9.0 using the `TrackMatrix`property of PID (use `-add foo:sopt:#TrackMatrix=a,b,c,d,e,f,g,h,i` for MP4Box, or `gpac -i source:#TrackMatrix=a,b,c,d,e,f,g,h,i ...`
