### ISSUE TITLE
HLS live stream assertion failing

### ISSUE THREAD

**Issue by canatella** [gpac/gpac#724]
On master branch, this assertion is triggered when playing live hls

    src/media_tools/dashclient.c:2198 assert(seg_url->hls_utc_start_time);

for this reason: my test stream does have a #EXT-X-PROGRAM-DATE-TIME, so  attributes->playlist_utc_timestamp  is never set in m3u8.c:443, so playlist element utc_start_time is set to 0 in m3u8.c:157, in mpd.c:1891, utc_start_time is set to start_time and on the next line, hls_utc_start_time is set to utc_start_time. For the first segment of an HLS live stream, start_time is set to 0 in mpd.dc:1806 which triggers the assertion.

Removing the assertion of course fixes the problem but maybe it was added there for a reason...

**Comment by jeanlf** [comment]
I think you're correct, now fixed on git
