### ISSUE TITLE
Android - MediaCodec decoding does not work (Galaxy S7, Nexus 5), HEVC and H.264 streams

### ISSUE THREAD

**Issue by divan333** [gpac/gpac#725]
Hi,

With the latest osmo4 revision on Android (osmo4-0.6.2-DEV-rev1258-gb731e76-master.apk) I am not able to play back any HEVC or H.264 streams on my Android devices. I also tried to build osmo4 from the Git repository of 19.12.2016, with the same result.

Only first video frame is shown on the screen, and then nothing happens anymore. No audio is played back, looks like the playback is frozen.

Devices tested are: Samsung Galaxy S7 with Android 6.0.1 and Google Nexus 5 also with Android 6.0.1

I tried, for example this stream:

https://s3.amazonaws.com/x265.org/video/Tears_400_x265.mp4

But the same problem also happens with H.264 content.

Please find the log file attached below. Looks like Android MediaCodec is not happy and throws "AMEDIACODEC_INFO_TRY_AGAIN_LATER" message. If I revert back the changes from https://github.com/gpac/gpac/issues/717, some streams decode but with artifacts / jerky movements and some only get few lines rendered, but audio still works. If I enable changes from #717 then I am stuck with one frame and no audio.

Here is a snapshot from the log, please let me know if you need more info:

Any help would be greatly appreciated!

12-21 13:09:38.281 15230-15267/? I/GPAC_WRAPPER: GPAC.cfg found in /storage/emulated/0/osmo/, force using it.
12-21 13:09:38.281 15230-15267/? I/GPAC_WRAPPER: Loading User Config GPAC.cfg...
12-21 13:09:38.281 15230-15267/? I/GPAC_WRAPPER: loading modules in directory /data/data/com.gpac.Osmo4/lib...
12-21 13:09:38.281 15230-15267/? D/GPAC_WRAPPER: Loading GPAC terminal, m_user=0xdd8ca014...
12-21 13:09:38.291 15230-15267/? V/GPAC_WRAPPER: SetupLogs()
12-21 13:09:38.311 15230-15267/? V/GPAC Android Audio: [Android Audio] Setup for 2 buffers
12-21 13:09:38.311 15230-15273/? I/GPAC Android Audio: [Android Audio] Configure Output for 2 channels...
12-21 13:09:38.311 15230-15273/? V/GPAC Android Audio: [Android Audio] SampleRate : 44100
12-21 13:09:38.311 15230-15273/? V/GPAC Android Audio: [Android Audio] BitPerSample : 16
12-21 13:09:38.321 15230-15273/? V/GPAC Android Audio: [Android Audio] Buffer Size : 14176
12-21 13:09:38.321 15230-15273/? V/GPAC Android Audio: [Android Audio] Buffer Length ms : 80
12-21 13:09:38.321 15230-15267/? I/GF_LOG_MUTEX: [Thread MediaManager] Couldn't set priority(2) for thread ID 0xd7f00930
12-21 13:09:38.321 15230-15274/? I/GPAC_WRAPPER: Rebuilding methods for thread -672134864
12-21 13:09:38.321 15230-15274/? I/GPAC_WRAPPER: Getting current Thread -672134864...
12-21 13:09:38.321 15230-15274/? I/GPAC_WRAPPER: Getting current Thread DONE = 0xeedf5240, now registering before exit...
12-21 13:09:38.321 15230-15274/? I/GPAC_WRAPPER: Registering DONE for -672134864
12-21 13:09:38.321 15230-15274/? I/GF_LOG_MUTEX: [Thread MediaManager] Couldn't set priority(2) for thread ID 0xd7f00930
12-21 13:09:38.321 15230-15267/? D/GPAC_WRAPPER: Setting term size m_user=0xdd8ca014...
12-21 13:09:38.321 15230-15267/? D/GPAC_WRAPPER: GPAC_EventProc() Message=88
12-21 13:09:38.321 15230-15267/? I/GPAC_WRAPPER: Unknown Message 88
12-21 13:09:38.321 15230-15267/? D/GPAC_WRAPPER: File loaded at startup=/data/data/com.gpac.Osmo4/gui/gui.bt.
12-21 13:09:38.321 15230-15267/? I/GPAC_WRAPPER: Connecting to /data/data/com.gpac.Osmo4/gui/gui.bt...
12-21 13:09:38.341 15230-15267/? D/GPAC_WRAPPER: GPAC_EventProc() Message=101
12-21 13:09:38.341 15230-15267/? V/GPAC_WRAPPER: MessageBox start Connected
12-21 13:09:38.341 15230-15267/? D/Osmo4: Connected
12-21 13:09:38.341 15230-15267/? V/GPAC_WRAPPER: MessageBox done Connected
12-21 13:09:38.341 15230-15267/? V/GPAC_WRAPPER: init end
12-21 13:09:38.341 15230-15267/? D/GPAC_WRAPPER: Saving config file...
12-21 13:09:38.341 15230-15267/? I/GPAC_WRAPPER: Initialization complete, config file saved.
12-21 13:09:38.341 15230-15267/? V/WRAPPER_JNI: Returned Handle = 0xdd8ca000
12-21 13:09:38.341 15230-15267/? I/Osmo4: GPAC is ready
12-21 13:09:38.341 15230-15267/? I/Osmo4Renderer: Surface changed from thread Thread[GLThread 258,5,main]
12-21 13:09:38.341 15230-15267/? I/LibrariesLoader: Resizing to 1440x2560
12-21 13:09:38.341 15230-15267/? V/WRAPPER_JNI: resize::start
12-21 13:09:38.341 15230-15267/? V/GPAC_WRAPPER: resize start
12-21 13:09:38.341 15230-15267/? D/GPAC_WRAPPER: GPAC_EventProc() Message=88
12-21 13:09:38.341 15230-15267/? I/GPAC_WRAPPER: Unknown Message 88
12-21 13:09:38.341 15230-15267/? V/GPAC_WRAPPER: resize end
12-21 13:09:38.341 15230-15267/? V/WRAPPER_JNI: resize::end
12-21 13:09:38.361 15230-15274/? D/GPAC_WRAPPER: GPAC_EventProc() Message=88
12-21 13:09:38.361 15230-15274/? I/GPAC_WRAPPER: Unknown Message 88
12-21 13:09:38.361 15230-15273/? V/GPAC Android Audio: [Android Audio] ConfigureOutput DONE.
12-21 13:09:38.381 15230-15230/? D/ViewRootImpl: #3 mView = null
12-21 13:09:38.391 15230-15230/? E/ViewRootImpl: sendUserActionEvent() mView == null
12-21 13:09:38.391 15230-15230/? I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@d87aa45 time:206505
12-21 13:09:38.391 15230-15274/? D/GPAC_WRAPPER: GPAC_EventProc() Message=118
12-21 13:09:38.391 15230-15274/? I/GPAC_WRAPPER: Needs to display/hide the Virtual Keyboard (118)
12-21 13:09:38.391 15230-15274/? V/GPAC_WRAPPER: Done showing virtual keyboard (118)
12-21 13:09:38.441 15230-15274/? D/GPAC_WRAPPER: GPAC_EventProc() Message=118
12-21 13:09:38.441 15230-15274/? I/GPAC_WRAPPER: Needs to display/hide the Virtual Keyboard (118)
12-21 13:09:38.441 15230-15274/? V/GPAC_WRAPPER: Done showing virtual keyboard (118)
12-21 13:09:38.451 15230-15274/? D/GPAC_WRAPPER: GPAC_EventProc() Message=88
12-21 13:09:38.451 15230-15274/? I/GPAC_WRAPPER: Unknown Message 88
12-21 13:09:38.461 15230-15274/? D/GPAC_WRAPPER: GPAC_EventProc() Message=88
12-21 13:09:38.461 15230-15274/? I/GPAC_WRAPPER: Unknown Message 88
12-21 13:09:38.461 15230-15274/? D/GPAC_WRAPPER: GPAC_EventProc() Message=88
12-21 13:09:38.461 15230-15274/? I/GPAC_WRAPPER: Unknown Message 88
12-21 13:09:40.731 15230-15274/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=129
12-21 13:09:40.731 15230-15274/com.gpac.Osmo4 V/GPAC_WRAPPER: We received Sensor Request for turning OFF location sensors
12-21 13:09:40.731 15230-15274/com.gpac.Osmo4 I/Osmo4: Received Un-Register Sensors call
12-21 13:09:40.851 15230-15267/com.gpac.Osmo4 D/libGLESv2: DTS_GLAPI : DTS is not allowed for Package : com.gpac.Osmo4
12-21 13:09:40.861 15230-15267/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=110
12-21 13:09:40.861 15230-15267/com.gpac.Osmo4 I/GPAC_WRAPPER: Unknown Message 110
12-21 13:09:41.261 15230-15230/com.gpac.Osmo4 D/ViewRootImpl: ViewPostImeInputStage processPointer 0
12-21 13:09:41.281 15230-15267/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=5
12-21 13:09:41.281 15230-15267/com.gpac.Osmo4 V/GPAC_WRAPPER: onMouseDown start
12-21 13:09:41.281 15230-15267/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=2
12-21 13:09:41.281 15230-15267/com.gpac.Osmo4 V/GPAC_WRAPPER: onMouseDown end
12-21 13:09:41.321 15230-15267/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=5
12-21 13:09:41.321 15230-15267/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=5
12-21 13:09:41.321 15230-15267/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=5
12-21 13:09:41.361 15230-15267/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=5
12-21 13:09:41.361 15230-15267/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=5
12-21 13:09:41.441 15230-15230/com.gpac.Osmo4 D/ViewRootImpl: ViewPostImeInputStage processPointer 1
12-21 13:09:41.661 15230-15230/com.gpac.Osmo4 D/ViewRootImpl: ViewPostImeInputStage processPointer 0
12-21 13:09:41.701 15230-15230/com.gpac.Osmo4 D/ViewRootImpl: ViewPostImeInputStage processPointer 1
12-21 13:09:42.291 15230-15230/com.gpac.Osmo4 D/ViewRootImpl: ViewPostImeInputStage processPointer 0
12-21 13:09:42.311 15230-15267/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=5
12-21 13:09:42.311 15230-15267/com.gpac.Osmo4 V/GPAC_WRAPPER: onMouseDown start
12-21 13:09:42.311 15230-15267/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=2
12-21 13:09:42.311 15230-15267/com.gpac.Osmo4 V/GPAC_WRAPPER: onMouseDown end
12-21 13:09:42.351 15230-15267/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=5
12-21 13:09:42.351 15230-15267/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=5
12-21 13:09:42.391 15230-15230/com.gpac.Osmo4 D/ViewRootImpl: ViewPostImeInputStage processPointer 1
12-21 13:09:43.011 15230-15230/com.gpac.Osmo4 D/ViewRootImpl: ViewPostImeInputStage processPointer 0
12-21 13:09:43.091 15230-15230/com.gpac.Osmo4 D/ViewRootImpl: ViewPostImeInputStage processPointer 1
12-21 13:09:43.211 15230-15230/com.gpac.Osmo4 I/InjectionManager: dispatchPrepareOptionsMenu :com.gpac.Osmo4.Osmo4
12-21 13:09:43.221 15230-15230/com.gpac.Osmo4 D/AbsListView: Get MotionRecognitionManager
12-21 13:09:43.231 15230-15230/com.gpac.Osmo4 E/MotionRecognitionManager: mSContextService = android.hardware.scontext.ISContextService$Stub$Proxy@9f11dc8
12-21 13:09:43.231 15230-15230/com.gpac.Osmo4 E/MotionRecognitionManager: motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@36cce61
12-21 13:09:43.231 15230-15230/com.gpac.Osmo4 E/MotionRecognitionManager: motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@36cce61
12-21 13:09:43.251 15230-15230/com.gpac.Osmo4 D/ViewRootImpl: #1 mView = android.widget.PopupWindow$PopupDecorView{f46ef9d V.E...... ......I. 0,0-0,0}
12-21 13:09:43.271 15230-15250/com.gpac.Osmo4 D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [992x1766]-format:1
12-21 13:09:43.311 15230-15230/com.gpac.Osmo4 W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
12-21 13:09:43.331 15230-15230/com.gpac.Osmo4 D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
12-21 13:09:44.201 15230-15230/com.gpac.Osmo4 D/ViewRootImpl: ViewPostImeInputStage processPointer 0
12-21 13:09:44.281 15230-15230/com.gpac.Osmo4 D/ViewRootImpl: ViewPostImeInputStage processPointer 1
12-21 13:09:44.351 15230-15230/com.gpac.Osmo4 I/InjectionManager: dispatchOptionsItemSelected :com.gpac.Osmo4.Osmo4
12-21 13:09:44.361 15230-15230/com.gpac.Osmo4 D/Instrumentation: checkStartActivityResult() : Intent { act=android.intent.action.PICK dat=file:///data/user/0/com.gpac.Osmo4 typ=vnd.android.cursor.dir/lysesoft.andexplorer.file VirtualScreenParam=Params{mDisplayId=-1, null, mFlags=0x00000000)} (has extras) }
12-21 13:09:44.361 15230-15230/com.gpac.Osmo4 D/Instrumentation: checkStartActivityResult() : intent is instance of [Intent].
12-21 13:09:44.391 15230-15267/com.gpac.Osmo4 D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1440x2560]-format:2
12-21 13:09:44.391 15230-15267/com.gpac.Osmo4 I/Osmo4Renderer: Surface changed from thread Thread[GLThread 258,5,main]
12-21 13:09:44.391 15230-15267/com.gpac.Osmo4 I/LibrariesLoader: Resizing to 1440x2560
12-21 13:09:44.391 15230-15267/com.gpac.Osmo4 V/WRAPPER_JNI: resize::start
12-21 13:09:44.391 15230-15267/com.gpac.Osmo4 V/GPAC_WRAPPER: resize start
12-21 13:09:44.391 15230-15267/com.gpac.Osmo4 V/GPAC_WRAPPER: resize end
12-21 13:09:44.391 15230-15267/com.gpac.Osmo4 V/WRAPPER_JNI: resize::end
12-21 13:09:44.451 15230-15230/com.gpac.Osmo4 W/ResourcesManager: getTopLevelResources: /data/app/com.gpac.Osmo4-1/base.apk / 1.0 running in com.gpac.Osmo4 rsrc of package com.gpac.Osmo4
12-21 13:09:44.451 15230-15230/com.gpac.Osmo4 D/RelationGraph: garbageCollect()
12-21 13:09:44.471 15230-15230/com.gpac.Osmo4 D/Activity: performCreate Call Injection manager
12-21 13:09:44.491 15230-15230/com.gpac.Osmo4 I/InjectionManager: dispatchOnViewCreated > Target : com.gpac.Osmo4.extra.FileChooserFragment isFragment :true
12-21 13:09:44.491 15230-15230/com.gpac.Osmo4 I/InjectionManager: dispatchOnViewCreated > Target : com.gpac.Osmo4.extra.FileChooserActivity isFragment :false
12-21 13:09:44.491 15230-15230/com.gpac.Osmo4 D/SecWifiDisplayUtil: Metadata value : SecSettings2
12-21 13:09:44.491 15230-15230/com.gpac.Osmo4 D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{ed8807d I.E...... R.....ID 0,0-0,0}
12-21 13:09:44.521 15230-15250/com.gpac.Osmo4 D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1440x2560]-format:1
12-21 13:09:44.611 15230-15230/com.gpac.Osmo4 I/InjectionManager: dispatchCreateOptionsMenu :com.gpac.Osmo4.extra.FileChooserActivity
12-21 13:09:44.611 15230-15230/com.gpac.Osmo4 I/InjectionManager: dispatchPrepareOptionsMenu :com.gpac.Osmo4.extra.FileChooserActivity
12-21 13:09:44.641 15230-15230/com.gpac.Osmo4 W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
12-21 13:09:44.661 15230-15230/com.gpac.Osmo4 D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
12-21 13:09:44.711 15230-15250/com.gpac.Osmo4 D/OpenGLRenderer: endAllActiveAnimators on 0xdc607e80 (ListPopupWindow$DropDownListView) with handle 0xd787a0e0
12-21 13:09:44.711 15230-15230/com.gpac.Osmo4 I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@62a16d4 time:212825
12-21 13:09:44.741 15230-15230/com.gpac.Osmo4 D/ViewRootImpl: #3 mView = null
12-21 13:09:44.961 15230-15230/com.gpac.Osmo4 I/Osmo4: onStop called on activity
12-21 13:09:44.971 15230-15230/com.gpac.Osmo4 V/ActivityThread: updateVisibility : ActivityRecord{f418f34 token=android.os.BinderProxy@d87aa45 {com.gpac.Osmo4/com.gpac.Osmo4.Osmo4}} show : false
12-21 13:09:45.321 15230-15230/com.gpac.Osmo4 D/ViewRootImpl: ViewPostImeInputStage processPointer 0
12-21 13:09:45.521 15230-15230/com.gpac.Osmo4 D/ViewRootImpl: ViewPostImeInputStage processPointer 1
12-21 13:09:48.971 15230-15230/com.gpac.Osmo4 D/ViewRootImpl: ViewPostImeInputStage processPointer 0
12-21 13:09:49.071 15230-15230/com.gpac.Osmo4 D/ViewRootImpl: ViewPostImeInputStage processPointer 1
12-21 13:09:49.141 15230-15230/com.gpac.Osmo4 I/Osmo4: Requesting opening local file /storage/emulated/0/Tears_400_x265.mp4
12-21 13:09:49.141 15230-15267/com.gpac.Osmo4 I/LibrariesLoader: connect(/storage/emulated/0/Tears_400_x265.mp4)
12-21 13:09:49.141 15230-15267/com.gpac.Osmo4 E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
12-21 13:09:49.171 15230-15267/com.gpac.Osmo4 V/WRAPPER_JNI: connect::start
12-21 13:09:49.171 15230-15267/com.gpac.Osmo4 V/GPAC_WRAPPER: Starting to connect ...
12-21 13:09:49.171 15230-15267/com.gpac.Osmo4 V/GPAC Android Audio: [Android Audio] Play: 0
12-21 13:09:49.171 15230-15267/com.gpac.Osmo4 V/GPAC Android Audio: [Android Audio] Play DONE (0).
12-21 13:09:49.191 15230-15267/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=110
12-21 13:09:49.191 15230-15267/com.gpac.Osmo4 I/GPAC_WRAPPER: Unknown Message 110
12-21 13:09:49.191 15230-15267/com.gpac.Osmo4 V/GPAC Android Audio: [Android Audio] Play: 1
12-21 13:09:49.191 15230-15267/com.gpac.Osmo4 V/GPAC Android Audio: [Android Audio] Play DONE (1).
12-21 13:09:49.201 15230-15274/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=101
12-21 13:09:49.201 15230-15274/com.gpac.Osmo4 V/GPAC_WRAPPER: MessageBox start Disconnected
12-21 13:09:49.201 15230-15274/com.gpac.Osmo4 D/Osmo4: Disconnected
12-21 13:09:49.201 15230-15274/com.gpac.Osmo4 V/GPAC_WRAPPER: MessageBox done Disconnected
12-21 13:09:49.221 15230-15267/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=101
12-21 13:09:49.221 15230-15267/com.gpac.Osmo4 V/GPAC_WRAPPER: MessageBox start Connected
12-21 13:09:49.221 15230-15267/com.gpac.Osmo4 D/Osmo4: Connected
12-21 13:09:49.221 15230-15267/com.gpac.Osmo4 V/GPAC_WRAPPER: MessageBox done Connected
12-21 13:09:49.231 15230-15267/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=102
12-21 13:09:49.231 15230-15267/com.gpac.Osmo4 I/GPAC_WRAPPER: Unknown Message 102
12-21 13:09:49.241 15230-15267/com.gpac.Osmo4 I/ACodec:  [] Now uninitialized
12-21 13:09:49.241 15230-15446/com.gpac.Osmo4 I/OMXClient: Using client-side OMX mux.
12-21 13:09:49.271 15230-15446/com.gpac.Osmo4 I/ACodec: [OMX.Exynos.hevc.dec] Now Loaded
12-21 13:09:49.271 15230-15446/com.gpac.Osmo4 I/ACodec: [OMX.Exynos.hevc.dec] Now Loaded->Idle
12-21 13:09:49.271 15230-15267/com.gpac.Osmo4 I/mediacodec_dec: Video size: 1920 x 800
12-21 13:09:49.271 15230-15267/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=88
12-21 13:09:49.271 15230-15267/com.gpac.Osmo4 I/GPAC_WRAPPER: Unknown Message 88
12-21 13:09:49.281 15230-15267/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=88
12-21 13:09:49.281 15230-15267/com.gpac.Osmo4 I/GPAC_WRAPPER: Unknown Message 88
12-21 13:09:49.281 15230-15267/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=129
12-21 13:09:49.281 15230-15267/com.gpac.Osmo4 V/GPAC_WRAPPER: We received Sensor Request for turning OFF location sensors
12-21 13:09:49.281 15230-15267/com.gpac.Osmo4 I/Osmo4: Received Un-Register Sensors call
12-21 13:09:49.281 15230-15267/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=88
12-21 13:09:49.281 15230-15267/com.gpac.Osmo4 I/GPAC_WRAPPER: Unknown Message 88
12-21 13:09:49.281 15230-15267/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=111
12-21 13:09:49.281 15230-15267/com.gpac.Osmo4 I/GPAC_WRAPPER: Unknown Message 111
12-21 13:09:49.281 15230-15267/com.gpac.Osmo4 V/GPAC_WRAPPER: connected ...
12-21 13:09:49.281 15230-15267/com.gpac.Osmo4 V/WRAPPER_JNI: connect::end
12-21 13:09:49.281 15230-15446/com.gpac.Osmo4 I/ACodec: [OMX.Exynos.hevc.dec] Now Idle->Executing
12-21 13:09:49.281 15230-15446/com.gpac.Osmo4 I/ACodec: [OMX.Exynos.hevc.dec] Now Executing
12-21 13:09:49.281 15230-15267/com.gpac.Osmo4 D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1440x2560]-format:2
12-21 13:09:49.281 15230-15267/com.gpac.Osmo4 I/Osmo4Renderer: Surface changed from thread Thread[GLThread 258,5,main]
12-21 13:09:49.281 15230-15267/com.gpac.Osmo4 I/LibrariesLoader: Resizing to 1440x2560
12-21 13:09:49.281 15230-15267/com.gpac.Osmo4 V/WRAPPER_JNI: resize::start
12-21 13:09:49.281 15230-15267/com.gpac.Osmo4 V/GPAC_WRAPPER: resize start
12-21 13:09:49.281 15230-15267/com.gpac.Osmo4 V/GPAC_WRAPPER: resize end
12-21 13:09:49.281 15230-15267/com.gpac.Osmo4 V/WRAPPER_JNI: resize::end
12-21 13:09:49.331 15230-15267/com.gpac.Osmo4 D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1440x2560]-format:2
12-21 13:09:49.331 15230-15267/com.gpac.Osmo4 I/Osmo4Renderer: Surface changed from thread Thread[GLThread 258,5,main]
12-21 13:09:49.331 15230-15267/com.gpac.Osmo4 I/LibrariesLoader: Resizing to 1440x2560
12-21 13:09:49.331 15230-15267/com.gpac.Osmo4 V/WRAPPER_JNI: resize::start
12-21 13:09:49.331 15230-15267/com.gpac.Osmo4 V/GPAC_WRAPPER: resize start
12-21 13:09:49.331 15230-15267/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=88
12-21 13:09:49.331 15230-15267/com.gpac.Osmo4 I/GPAC_WRAPPER: Unknown Message 88
12-21 13:09:49.331 15230-15267/com.gpac.Osmo4 V/GPAC_WRAPPER: resize end
12-21 13:09:49.331 15230-15267/com.gpac.Osmo4 V/WRAPPER_JNI: resize::end
12-21 13:09:49.391 15230-15274/com.gpac.Osmo4 I/mediacodec_dec: AMEDIACODEC_INFO_TRY_AGAIN_LATER
12-21 13:09:49.391 15230-15274/com.gpac.Osmo4 I/GF_LOG_CODEC: [ODM1] Decoding Error Bad Parameter
12-21 13:09:49.391 15230-15250/com.gpac.Osmo4 D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1440x2560]-format:1
12-21 13:09:49.441 15230-15230/com.gpac.Osmo4 I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@d87aa45 time:217553
12-21 13:09:49.491 15230-15274/com.gpac.Osmo4 I/mediacodec_dec: AMEDIACODEC_INFO_TRY_AGAIN_LATER
12-21 13:09:49.491 15230-15274/com.gpac.Osmo4 I/GF_LOG_CODEC: [ODM1] Decoding Error Bad Parameter
12-21 13:09:49.501 15230-15274/com.gpac.Osmo4 I/mediacodec_dec: AMEDIACODEC_INFO_OUTPUT_FORMAT_CHANGED
12-21 13:09:49.501 15230-15274/com.gpac.Osmo4 I/GF_LOG_CODEC: [ODM1] Decoding Error Bad Parameter
12-21 13:09:49.501 15230-15274/com.gpac.Osmo4 I/mediacodec_dec: OutputIndex: 0
12-21 13:09:49.511 15230-15274/com.gpac.Osmo4 I/mediacodec_dec: OutputIndex: 1
12-21 13:09:49.531 15230-15267/com.gpac.Osmo4 V/GPAC Android Audio: [Android Audio] Play: 0
12-21 13:09:49.541 15230-15267/com.gpac.Osmo4 V/GPAC Android Audio: [Android Audio] Play DONE (0).
12-21 13:09:49.541 15230-15267/com.gpac.Osmo4 V/GPAC Android Audio: [Android Audio] Play: 1
12-21 13:09:49.541 15230-15267/com.gpac.Osmo4 V/GPAC Android Audio: [Android Audio] Play DONE (1).
12-21 13:09:49.611 15230-15274/com.gpac.Osmo4 I/mediacodec_dec: AMEDIACODEC_INFO_TRY_AGAIN_LATER
12-21 13:09:49.611 15230-15274/com.gpac.Osmo4 I/GF_LOG_CODEC: [ODM1] Decoding Error Bad Parameter
12-21 13:09:49.711 15230-15274/com.gpac.Osmo4 I/mediacodec_dec: AMEDIACODEC_INFO_TRY_AGAIN_LATER
12-21 13:09:49.711 15230-15274/com.gpac.Osmo4 I/GF_LOG_CODEC: [ODM1] Decoding Error Bad Parameter
12-21 13:09:49.731 15230-15230/com.gpac.Osmo4 D/ViewRootImpl: #3 mView = null
12-21 13:09:49.811 15230-15274/com.gpac.Osmo4 I/mediacodec_dec: AMEDIACODEC_INFO_TRY_AGAIN_LATER
12-21 13:09:49.811 15230-15274/com.gpac.Osmo4 I/GF_LOG_CODEC: [ODM1] Decoding Error Bad Parameter
12-21 13:09:49.911 15230-15274/com.gpac.Osmo4 I/mediacodec_dec: AMEDIACODEC_INFO_TRY_AGAIN_LATER
12-21 13:09:49.911 15230-15274/com.gpac.Osmo4 I/GF_LOG_CODEC: [ODM1] Decoding Error Bad Parameter
12-21 13:09:50.011 15230-15274/com.gpac.Osmo4 I/mediacodec_dec: AMEDIACODEC_INFO_TRY_AGAIN_LATER
12-21 13:09:50.011 15230-15274/com.gpac.Osmo4 I/GF_LOG_CODEC: [ODM1] Decoding Error Bad Parameter
12-21 13:09:50.111 15230-15274/com.gpac.Osmo4 I/mediacodec_dec: AMEDIACODEC_INFO_TRY_AGAIN_LATER
12-21 13:09:50.111 15230-15274/com.gpac.Osmo4 I/GF_LOG_CODEC: [ODM1] Decoding Error Bad Parameter
12-21 13:09:50.221 15230-15274/com.gpac.Osmo4 I/mediacodec_dec: AMEDIACODEC_INFO_TRY_AGAIN_LATER
12-21 13:09:50.221 15230-15274/com.gpac.Osmo4 I/GF_LOG_CODEC: [ODM1] Decoding Error Bad Parameter
12-21 13:09:50.321 15230-15274/com.gpac.Osmo4 I/mediacodec_dec: AMEDIACODEC_INFO_TRY_AGAIN_LATER
12-21 13:09:50.321 15230-15274/com.gpac.Osmo4 I/GF_LOG_CODEC: [ODM1] Decoding Error Bad Parameter

**Comment by jeljeli** [comment]
- Mediacodec_dec does not support hevc streams for now, a version that decodes hevc will be available soon
- Please give me the h264 stream with which you tested

**Comment by divan333** [comment]
Hi jeljeli,

Thanks for the info. Interesting, I do not know if it was a phone / VM reboot but I am now getting some h.265 files to play with osmo4! (with the #717 patch) , and h.264 files play as well apart from some exhibiting jitters (every half a second or so looks like wrong frame being rendered), like this one:

http://www.dvdloc8.com/clip.php?movieid=12167&clipid=2 (The Simpsons trailer, CE-High profile)

I do not see anything suspicious in the log, but if you need it I can provide it.

Tested on Samsung Galaxy S7.

Thx!
Ivan

**Comment by azhar5678** [comment]
hey divan can u upload ur apk ,because iam unable to generate on window 7 32 bit

**Comment by jeanlf** [comment]
we have been stabilizing mediacodec support for 0.8.0, please recheck and reopen if needed
