### ISSUE TITLE
Android - Crash or error when opening HEVC tiled DASH stream

### ISSUE THREAD

**Issue by divan333** [gpac/gpac#726]
Dear GPAC team,

When trying to open http://download.tsi.telecom-paristech.fr/gpac/SRD/srd_hevc/multi_rate_p60/hevc_srd.mpd HEVC tiled stream on Android (Samsung Galaxy S7, Google Nexus 5, both Android 6.0.1), I get the following:

1. Using osmo4 nightly build (osmo4-0.6.2-DEV-rev1258-gb731e76-master.apk), I get a "simple" crash after trying to open the above DASH URL, log shows this:

12-21 13:50:34.821 23167-23182/com.gpac.Osmo4 E/Osmo4: Failed to rename /data/user/0/com.gpac.Osmo4/recentURLs.txt.tmp to /data/user/0/com.gpac.Osmo4/recentURLs.txt
12-21 13:50:34.851 23167-23196/com.gpac.Osmo4 I/LibrariesLoader: connect(http://download.tsi.telecom-paristech.fr/gpac/SRD/srd_hevc/multi_rate_p60/hevc_srd.mpd)
12-21 13:50:34.871 23167-23167/com.gpac.Osmo4 D/ViewRootImpl: MSG_RESIZED: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
12-21 13:50:34.891 23167-23196/com.gpac.Osmo4 V/WRAPPER_JNI: connect::start
12-21 13:50:34.891 23167-23196/com.gpac.Osmo4 V/GPAC_WRAPPER: Starting to connect ...
12-21 13:50:34.891 23167-23196/com.gpac.Osmo4 V/GPAC Android Audio: [Android Audio] Play: 0
12-21 13:50:34.891 23167-23196/com.gpac.Osmo4 V/GPAC Android Audio: [Android Audio] Play DONE (0).
12-21 13:50:34.931 23167-23196/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=110
12-21 13:50:34.931 23167-23196/com.gpac.Osmo4 I/GPAC_WRAPPER: Unknown Message 110
12-21 13:50:34.931 23167-23196/com.gpac.Osmo4 V/GPAC Android Audio: [Android Audio] Play: 1
12-21 13:50:34.931 23167-23196/com.gpac.Osmo4 V/GPAC Android Audio: [Android Audio] Play DONE (1).
12-21 13:50:34.931 23167-23201/com.gpac.Osmo4 A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdd2b7644 in tid 23201 (Thread-418)

2. If I build osmo4 on my own (Git pull from 19.12.2016), and start a debugging session from Android Studio ("Debug app"), sometimes, instead of crash, osmo4 will not crash, but report problems trying to open the stream, like this below:

12-21 14:02:31.791 28529-28564/com.gpac.Osmo4 I/LibrariesLoader: connect(http://download.tsi.telecom-paristech.fr/gpac/SRD/srd_hevc/multi_rate_p60/hevc_srd.mpd)
12-21 14:02:31.821 28529-28564/com.gpac.Osmo4 V/WRAPPER_JNI: connect::start
12-21 14:02:31.821 28529-28564/com.gpac.Osmo4 V/GPAC_WRAPPER: Starting to connect ...
12-21 14:02:31.841 28529-28564/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=101
12-21 14:02:31.841 28529-28564/com.gpac.Osmo4 V/GPAC_WRAPPER: MessageBox start Connected
12-21 14:02:31.841 28529-28564/com.gpac.Osmo4 D/Osmo4: Connected
12-21 14:02:31.841 28529-28564/com.gpac.Osmo4 V/GPAC_WRAPPER: MessageBox done Connected
12-21 14:02:31.841 28529-28571/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=101
12-21 14:02:31.841 28529-28571/com.gpac.Osmo4 V/GPAC_WRAPPER: MessageBox start Disconnected
12-21 14:02:31.841 28529-28571/com.gpac.Osmo4 D/Osmo4: Disconnected
12-21 14:02:31.841 28529-28571/com.gpac.Osmo4 V/GPAC_WRAPPER: MessageBox done Disconnected
12-21 14:02:31.841 28529-28529/com.gpac.Osmo4 D/ViewRootImpl: MSG_RESIZED: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
12-21 14:02:32.001 28529-28564/com.gpac.Osmo4 V/GPAC_WRAPPER: connected ...
12-21 14:02:32.001 28529-28564/com.gpac.Osmo4 V/WRAPPER_JNI: connect::end
12-21 14:02:32.111 28529-30801/com.gpac.Osmo4 I/GPAC_WRAPPER: Rebuilding methods for thread -708314832
12-21 14:02:32.111 28529-30801/com.gpac.Osmo4 I/GPAC_WRAPPER: Getting current Thread -708314832...
12-21 14:02:32.111 28529-30801/com.gpac.Osmo4 I/GPAC_WRAPPER: Getting current Thread DONE = 0xd647cb30, now registering before exit...
12-21 14:02:32.111 28529-30801/com.gpac.Osmo4 I/GPAC_WRAPPER: Registering DONE for -708314832
12-21 14:02:32.111 28529-30801/com.gpac.Osmo4 I/GF_LOG_CONTAINER: [iso file] Read Box "sgpd" failed (Invalid IsoMedia File) - skipping
12-21 14:02:32.111 28529-30801/com.gpac.Osmo4 I/GF_LOG_CONTAINER: [iso file] Read Box "stbl" failed (Invalid IsoMedia File) - skipping
12-21 14:02:32.111 28529-30801/com.gpac.Osmo4 I/GF_LOG_CONTAINER: [iso file] Read Box "minf" failed (Invalid IsoMedia File) - skipping
12-21 14:02:32.111 28529-30801/com.gpac.Osmo4 I/GF_LOG_CONTAINER: [iso file] Read Box "mdia" failed (Invalid IsoMedia File) - skipping
12-21 14:02:32.111 28529-30801/com.gpac.Osmo4 I/GF_LOG_CONTAINER: [iso file] Read Box "trak" failed (Invalid IsoMedia File) - skipping
12-21 14:02:32.111 28529-30801/com.gpac.Osmo4 I/GF_LOG_CONTAINER: [iso file] Read Box "moov" failed (Invalid IsoMedia File) - skipping
12-21 14:02:32.111 28529-30801/com.gpac.Osmo4 I/GF_LOG_NETWORK: [IsoMedia] : error while opening gmem://7162@0xd5cae000, error=Invalid IsoMedia File

Any help would be appreciated!
Thanks!

**Comment by jeanlf** [comment]
The issue comes from the fact that this is some old content, before final version of LHEVC file format. I just updated the sequences, they should work fine now (at least on desktop, haven't checked on android). 

Also be aware that we currently don't have hardware HEVC support on android and rely on FFMPEG, not openHEVC for the deocding, which can be a bit slower

Let us know if this works better

**Comment by divan333** [comment]
Thanks! Updated MPD file now plays when it gets opened, but I do get crashes 50% of the time on Android nightly build osmo4-0.6.2-DEV-rev1345-gef0517f-master.apk, no such crashes are seen on PC version (then again, PC version played even the old MPD).

This is what gets logged:

01-19 14:10:21.610 3511-6792/com.gpac.Osmo4 A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xeea10644

**Comment by divan333** [comment]
Looks like at least one of the Android crashes is related to the call to dec->ReleaseScene(dec) in gf_scene_disconnect() in /src/terminal/scene.c and related to SVG parser, so it looks like crash happens before the new (mpd) stream is opened.

Here is the log output:

01-19 14:24:57.760 9460-9509/com.gpac.Osmo4 I/LibrariesLoader: connect(http://download.tsi.telecom-paristech.fr/gpac/SRD/srd_hevc/multi_rate_p60/hevc_srd.mpd)
01-19 14:24:57.760 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [ODM1] At 28984 frame TS 0 next frame TS 0 too late in no-drop mode, enabling drop - resync mode 0
01-19 14:24:57.770 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Compositor] done flushing frame in 0 ms
01-19 14:24:57.780 9460-9460/com.gpac.Osmo4 D/ViewRootImpl: MSG_RESIZED: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 V/WRAPPER_JNI: connect::start
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 V/GPAC_WRAPPER: Starting to connect ...
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 V/GPAC Android Audio: [Android Audio] Play: 0
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 V/GPAC Android Audio: [Android Audio] Play DONE (0).
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 I/GF_LOG_SYNC: [Audio] pausing master clock - time 31784411 (sys time 31785664)
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [ODM1 /data/data/com.gpac.Osmo4/gui/gui.bt] CH65534: At OTB 29132 requesting PAUSE (clock init 1)
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [ODM1050 /data/data/com.gpac.Osmo4/gui/extensions/player/applications-multimedia.svg] CH65534: At OTB 29122 requesting PAUSE (clock init 1)
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [ODM1 /data/data/com.gpac.Osmo4/gui/extensions/H2B2VS/H2B2VS.png] CH1: At OTB 29026 requesting PAUSE (clock init 1)
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [ODM1050 /data/data/com.gpac.Osmo4/gui/extensions/bifs_tests/applications-other.svg] CH65534: At OTB 29126 requesting PAUSE (clock init 1)
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [ODM1050 /data/data/com.gpac.Osmo4/gui/extensions/showroom/osmo.bt] CH65534: At OTB 29127 requesting PAUSE (clock init 1)
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [ODM1050 /data/data/com.gpac.Osmo4/gui/icons/audio.svg] CH65534: At OTB 29127 requesting PAUSE (clock init 1)
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [ODM1050 /data/data/com.gpac.Osmo4/gui/icons/tray.svg] CH65534: At OTB 29127 requesting PAUSE (clock init 1)
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [ODM1050 /data/data/com.gpac.Osmo4/gui/icons/list.svg] CH65534: At OTB 29128 requesting PAUSE (clock init 1)
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [ODM1050 /data/data/com.gpac.Osmo4/gui/icons/osmo.svg] CH65534: At OTB 29128 requesting PAUSE (clock init 1)
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [ODM1050 /data/data/com.gpac.Osmo4/gui/extensions/player/applications-multimedia.svg] CH 65534 At OTB 29122 requesting STOP
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [ODM1 /data/data/com.gpac.Osmo4/gui/extensions/H2B2VS/H2B2VS.png] CH 1 At OTB 29026 requesting STOP
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [ODM1050 /data/data/com.gpac.Osmo4/gui/extensions/bifs_tests/applications-other.svg] CH 65534 At OTB 29126 requesting STOP
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [ODM1050 /data/data/com.gpac.Osmo4/gui/extensions/showroom/osmo.bt] CH 65534 At OTB 29127 requesting STOP
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [ODM1050 /data/data/com.gpac.Osmo4/gui/icons/audio.svg] CH 65534 At OTB 29127 requesting STOP
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [ODM1050 /data/data/com.gpac.Osmo4/gui/icons/tray.svg] CH 65534 At OTB 29127 requesting STOP
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [ODM1050 /data/data/com.gpac.Osmo4/gui/icons/list.svg] CH 65534 At OTB 29128 requesting STOP
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [ODM1050 /data/data/com.gpac.Osmo4/gui/icons/osmo.svg] CH 65534 At OTB 29128 requesting STOP
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [ODM1 /data/data/com.gpac.Osmo4/gui/gui.bt] CH 65534 At OTB 29132 requesting STOP
01-19 14:24:57.800 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Scene] disconnecting
01-19 14:24:57.830 9460-9514/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Scene] disconnecting
01-19 14:24:57.830 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Scene] disconnecting
01-19 14:24:57.830 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Scene] removing ODM 1050
01-19 14:24:57.830 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Terminal] Unregistering codec GPAC SVG Parser
01-19 14:24:57.830 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Scene] disconnecting
01-19 14:24:57.830 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Terminal] Unregistering codec GPAC Image Decoder
01-19 14:24:57.830 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Scene] removing ODM 1
01-19 14:24:57.830 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Scene] removing ODM 1050
01-19 14:24:57.830 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Scene] disconnecting
01-19 14:24:57.830 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Scene] removing ODM 1050
01-19 14:24:57.830 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Terminal] Unregistering codec GPAC SVG Parser
01-19 14:24:57.830 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Scene] disconnecting
01-19 14:24:57.830 9460-9509/com.gpac.Osmo4 D/GPAC_WRAPPER: GPAC_EventProc() Message=110
01-19 14:24:57.830 9460-9509/com.gpac.Osmo4 I/GPAC_WRAPPER: Unknown Message 110
01-19 14:24:57.830 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Scene] removing ODM 1050
01-19 14:24:57.830 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Terminal] Unregistering codec GPAC Context Loader
01-19 14:24:57.840 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Scene] disconnecting
01-19 14:24:57.840 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Scene] removing ODM 1050
01-19 14:24:57.840 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Terminal] Unregistering codec GPAC SVG Parser
01-19 14:24:57.840 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Scene] disconnecting
01-19 14:24:57.840 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Scene] removing ODM 1050
01-19 14:24:57.840 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Terminal] Unregistering codec GPAC SVG Parser
01-19 14:24:57.840 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Scene] disconnecting
01-19 14:24:57.840 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Scene] removing ODM 1050
01-19 14:24:57.840 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Terminal] Unregistering codec GPAC SVG Parser
01-19 14:24:57.840 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Scene] disconnecting
01-19 14:24:57.840 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Scene] removing ODM 1050
01-19 14:24:57.840 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [Terminal] Unregistering codec GPAC SVG Parser
01-19 14:24:57.840 9460-9509/com.gpac.Osmo4 I/GF_LOG_SYNC: [SyncLayer] Starting ES 65534
01-19 14:24:57.840 9460-9509/com.gpac.Osmo4 I/GF_LOG_MEDIA: [ODM1] CH65534: At OTB 0 starting channel
01-19 14:24:57.840 9460-9514/com.gpac.Osmo4 A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdcbf5644 in tid 9514 (Thread-938)

**Comment by jeljeli** [comment]
Could you please extend a bit on the crash scenario and give me the backtrace of the program crash (it's available in logs)? because I can't reproduce the problem with my device

**Comment by JamesXu20150314** [comment]
The Android cannot play any dash stream and ordinary video (aac). It will crash all the time.
The version is  
![image](https://user-images.githubusercontent.com/11470231/39752994-d861cbaa-52ef-11e8-9a20-5a4277ea70b5.png)

Have you tested it?

**Comment by jeanlf** [comment]
we have been stabilizing mediacodec support for 0.8.0, please recheck and reopen if needed
