### ISSUE TITLE
How Play SVC  files by gpac?

### ISSUE THREAD

**Issue by a-erfanian** [gpac/gpac#727]
Hello
I'm gonna to read and play video files encoded with H.264/SVC  from an Apache web server by DASH streaming.but I don't know how to do that.
Would you help me to do that?
thanks.

**Comment by jeanlf** [comment]
you will need to compile GPAC with openSVC support (or use the nightly installers from our site). You will hve to split the SVC file in two tracks, the easiest way is to do that at import:

`MP4Box -add source.264:svcmode=split -new split_avc_svc.mp4

you can then dash the content as usual using MP4Box, the different layers will be in different files/representations. This work also for SHVC.

To play it, use MP4Client. Quality switching in the playback is triggered by ctrl+h (higher quiality) and ctrl+l (lower quality)
