### ISSUE TITLE
problem demuxing PCM

### ISSUE THREAD

**Issue by stax76** [gpac/gpac#732]
https://github.com/stax76/staxrip/issues/130

**Comment by rbouqueau** [comment]
> log file and sample source file: https://forum.doom9.org/showthread.php?p=1803342&highlight=staxrip#post1803342

From #796

**Comment by rbouqueau** [comment]
```MP4Box -raw 2 C0089.mp4``` + reimport as raw 48000/16/stereo/big-endian in Audacity: audio is perfect.

Oh Jesus.MOV: same.

> It looks mp4box demuxes a corrupt wav file

This is not 'wav' but raw PCM. I am not familiar with your software but let me know if there is anything we can do to improve the detection/processing on your side.

PS: the files are quite broken on many aspects, let us know if there are other side issues you'd like us to have a look at.

**Comment by stax76** [comment]
Thanks for the support. I solved it in staxrip by demuxing PCM with ffmpeg.

**Comment by rbouqueau** [comment]
Ok, closing for now.
