### ISSUE TITLE
Add 'iods' atom

### ISSUE THREAD

**Issue by doublex** [gpac/gpac#733]
Is there a command-line option to add a "iods" atom?
I am asking because I get the warning message: "File has no MPEG4 IOD/OD"

**Comment by rbouqueau** [comment]
MP4Box adds the IOD by default (unless you use the ```-no-iod``` option). To add the IOD, reimport your MP4:
```
MP4Box -add file.mp4 -new newFile.mp4
```

**Comment by sergeevabc** [comment]
Sorry, do I need IOD for M$A audio file?
