### ISSUE TITLE
MP4Box: Error - 2 input names specified, please check usage

### ISSUE THREAD

**Issue by rtudor** [gpac/gpac#737]
I am a new user of MP4Box on a Mac running OS X Yosemite 10.10.5.
I am trying to remove a track from an MP4 file using the -rem trackID command in Terminal and I am receiving the following error message: Error - 2 input names specified, please check usage.
Does anyone have any idea what the problem is?

**Comment by rbouqueau** [comment]
What did you try? ```MP4Box -rem 1 file.mp4``` works here (with ```1``` being the trackID you can get with ```MP4Box -info file.mp4```).

**Comment by rtudor** [comment]
Thanks, rbouqueau. I was using MP4Box -rem trackID 1 file.mp4.
Now the "2 input names error" makes sense and I feel like a bit of an idiot :)
