### ISSUE TITLE
Signalling of CEA 608 and 708 in MPD file

### ISSUE THREAD

**Issue by Natarajan92** [gpac/gpac#738]
Hi all, 

Am trying to signal the closed caption of CEA-608 and CEA-708 in manifest file after packaging. The mediainfo of encoded mp4 file is having the information of embedded subtitle information (CEA 608 and 708). So, In order to signal it in manifest file what I need to do ? 

I have searched the commands of MP4Box but as per the Guidelines of DASH-IF organization, I hope there is no option in MP4Box to signal the closed caption in CEA 608 and 708

For example : 

* ) Signaling presence of CEA-608 closed caption service languages in English 

<Accessibility schemeIdUri="urn:scte:dash:cc:cea-608:2015" value="eng"/>

So may I know how to signal the CEA 608 and 708 while creating manifest ? 

Can you please suggest me an option to do it 

Thanks, 
Natarajan S

- [ ] I looked for a similar issue and couldn't find any.
CHECKED
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
CHECKED

**Comment by rbouqueau** [comment]
Hi,

If I believe the lastest DASHIF profile to date (http://dashif.org/wp-content/uploads/2016/12/DASH-IF-IOP-v4.0-clean.pdf), section 6.4.3, one should add an accessibility descriptor at the AdaptationSet level.

If I read the GPAC doc (http://gpac.io/mp4box/dash/), adding a descriptor at the AdaptationSet level can be done with the ```:desc_as_c=VALUE``` prefix.

Here is what I tried (random DASH command-line with the descriptor):
```MP4Box -dash 100000 counter_video_180.mp4:desc_as="<Accessibility schemeIdUri="urn:scte:dash:cc:cea-608:2015"/>"```

The mpd is:
```
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.6.2-DEV-rev1324-gc18932a-master  at 2017-01-17T17:23:45.935Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H10M0.000S" maxSegmentDuration="PT0H1M40.000S" profiles="urn:mpeg:dash:profile:full:2011">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>counter_video_180_dash.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H10M0.000S">
  <AdaptationSet segmentAlignment="true" maxWidth="320" maxHeight="180" maxFrameRate="25" par="16:9" lang="und">
   <Accessibility schemeIdUri=urn:scte:dash:cc:cea-608:2015/>
   <Representation id="1" mimeType="video/mp4" codecs="avc3.42C00D" width="320" height="180" frameRate="25" sar="1:1" startWithSAP="1" bandwidth="51032">
    <BaseURL>counter_video_180_dashinit.mp4</BaseURL>
    <SegmentList timescale="25000" duration="2500000">
     <Initialization range="0-863"/>
      <SegmentURL mediaRange="864-722643" indexRange="864-907"/>
      <SegmentURL mediaRange="722644-1343815" indexRange="722644-722687"/>
      <SegmentURL mediaRange="1343816-1964783" indexRange="1343816-1343859"/>
      <SegmentURL mediaRange="1964784-2585840" indexRange="1964784-1964827"/>
      <SegmentURL mediaRange="2585841-3206870" indexRange="2585841-2585884"/>
      <SegmentURL mediaRange="3206871-3827439" indexRange="3206871-3206914"/>
    </SegmentList>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```

**Comment by Natarajan92** [comment]
Hi Rbouqueau, 

Thanks for your help and steps to add the <Accessibility> tag. But when I performed the manifest file validation, the validator gives error as 

SAXException: Open quote is expected for attribute "schemeIdUri" associated with an element type "Accessibility".

Validation not successful! Invalid


Even I have checked with the MPD which you provided, both says same error as open quote is expected. 

Am trying to add open quotes while generating MPD. Meanwhile, If you know any option let me know please. 

Thanks
Anand Natarajan S

**Comment by rbouqueau** [comment]
I updated my initial command-line and mpd to escape the quotes. Note that this depends on your terminal so please adapt it to your own use-case.

I don't know which validator you use, but this one is now happy: http://www-itec.uni-klu.ac.at/dash/?page_id=605

**Comment by Natarajan92** [comment]
Hi rbouqueau,

Thanks, at the same time I have also tried with command to escape quotes. It worked. 

Am also using the same Validator only, Now it is proper .
