### ISSUE TITLE
Using $Time$ in -segment-name gives weird results in manifest

### ISSUE THREAD

**Issue by akunaatrium** [gpac/gpac#74]
I tried creating a DASH video with dashavc264:live profile using time based segment addressing scheme but in the MPD the media attribute value of SegmentTemplate element becomes something that is not expected. Basically, the command line to create the DASH video is the following:

`mp4box.exe -dash 10000 -rap -sample-groups-traf -profile dashavc264:live -segment-name seg_$RepresentationID$_$Time$ video.mp4 audio.mp4 -out manifest.mpd`

The media attribute in the generated MPD looks like this:
`media="seg_$RepresentationID$_$Time$$Number$.m4s"`

What is see as the issue here is that $Number$ placeholder is also present in the template string. To me it looks like a hybrid between time based and number based addressing scheme but my goal is to create a DASH video solely with time based addressing scheme.

Also, considering the fact that the $Number$ is present in the template string, the segment file names still do not include the numbers, they only include the time values.

Am I doing something wrong or is there a possible defect in mp4box?

Anvar

**Comment by rbouqueau** [comment]
You're missing a ``` -segment-timeline``` in your command-line. See http://www.gpac-licensing.com/2014/08/21/ibc-2014-dash-avc264-support-in-gpac/ for examples.

**Comment by akunaatrium** [comment]
Very nice, works now. Thanks!
