### ISSUE TITLE
client is requesting for segment which is not yet created

### ISSUE THREAD

**Issue by Natarajan92** [gpac/gpac#740]
Hi all, 

We are trying to create live channel stream in Mpeg-Dash with the use of MP4Box.The playback is smooth and it is playing long time(approx. 1hr), If we start the playback immediately once stream conversion started. 

If playback is started later, it is playing for few minutes and apache log gives 404 for segments 

 when we debug the problem, we came to know that the request from client device for segment  is not yet created in server. 

Command used for MP4Box packaging is 

" MP4Box -dash-ctx dash-live.txt -dash 4000 -rap -frag-rap -sample-groups-traf -mpd-refresh 4 -no-frags-default -bs-switching no -min-buffer 4000 -time-shift 180 -segment-name live_$RepresentationID$_ -keep-utc -insert-utc -ast-offset  6 -profile dashavc264:live -url-template -dynamic -subsegs-per-sidx -1 -out dash.mpd " 

Can anyone say, why client requests for future segement, before it is generated  ? 

I can provide additional information, If any required 

Thanks 
Natarajan S
Note : Server and client both are in same time zone, same time 

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
this could be a clock drift between the two machines. Have you tried running the client on the same machine as the server ?

**Comment by jeanlf** [comment]
this should be fixed now, please check #885
