### ISSUE TITLE
tx3g and raw commands

### ISSUE THREAD

**Issue by amuth** [gpac/gpac#741]
Please fix the current BUG:

https://trac.videolan.org/vlc/ticket/17860

**Comment by fcartegnie** [comment]
Seems more PEBKAK than a GPAC bug.
as \fad SSA tags does not belong to SRT at all, so that's expected not having them converted.
Mixed SRT with SSA...

**Comment by jeanlf** [comment]
Indeed, we don't support SSA subtitles in GPAC.
