### ISSUE TITLE
Can not encrypt .mp4 using "cens"/"CENC AES-CTR Pattern" with latest nightly build gpac-0.6.2-DEV-rev1359-g0373a51-master-win32.exe

### ISSUE THREAD

**Issue by starstarbear** [gpac/gpac#743]
Attached

- drm_file.xml  with config info 
-cmd: MP4BOX -crypt drm_file.xml big_buck_bunny.mp4 -out cenc_ctr_pattern.mp4
 
Error message: [CENC/ISMA] Encryption type not sopported
                         Error: Feature Not Supported

Upload .zip contains drm_file.xml and my .mp4 clip

Could you help figure out how to encrypt that clip using cens? Thanks for help! 

[encrypt.zip](https://github.com/gpac/gpac/files/728082/encrypt.zip)

**Comment by starstarbear** [comment]
i guess that latest nightly build does not support CENS yet. 

I locally build a MP4BOX with master branch code, it seems CENS is working.

But I am using the config file obtained from https://github.com/gpac/gpac/blob/master/tests/media/encryption/drm_cens.xml

I also uploaded drm_file.xml what I am using right now. 

I pops up "[CENC] Using scheme type cens, constant IV shall not be used, using constant IV as first IV". 

Could you explain why it pops up this message? For CENS, should we still use first IV or constant IV?
What's the difference? Thx a lot!
![drm_file xml](https://cloud.githubusercontent.com/assets/25232483/22304442/736df2ba-e305-11e6-86f9-5e0a9bafd923.png)

**Comment by jeanlf** [comment]
constant_IV_size and constant_IV attributes shall only be used foe AES-CBC modes (cbc and cbcs). The warning here tells you that the value specified for constant_IV will be used as first IV. You can check the latest cenc tests (gpac/tests/media/encryption)
