### ISSUE TITLE
Problem playing back tiled HEVC generated with MP4Box (was working previously)

### ISSUE THREAD

**Issue by divan333** [gpac/gpac#745]
Hello,

I am having issues with playback of tiled HEVC MP4 streams with the latest GPAC nightly (gpac-0.6.2-DEV-rev1362-ge748b05-master-x64.exe), I have uploaded the source HEVC file, MP4 file generated with mp4box and command lines and logs to the dropbox, which I hope can help.

Problem happens on both Windows and Android builds.

Please note, the file plays back correctly with older version of mp4client (1035-g8969ba8-master) but  unfortunately I do not know when exactly the problem appeared between this revision and the latest one.

Here are some observations:

1. MP4 file is generated with the following mp4box command line (rev1362):

c:\gpac\mp4box.exe -v -add multitile_3x3_UHD_qp40.hevc:FMT=HEVC:split_tiles:novpsext:fps=30:timescale=90000 -fps 30 -new multitile_3x3_UHD_qp40.mp4

2. MP4 file is attempted to be played back with the following mp4client command line:

C:\GPAC\mp4client.exe -log-file mp4client.log -logs all@info multitile_3x3_UHD_qp40.mp4

3. I did some basic debugging, and at least one problem seems to be that isor_reader_get_sample() returns samples of size 0, and the playback is stuck because decoder never receives actual data.

If more info/data is needed, please let me know.

Any help would be greatly appreciated.

Thank you!

--

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [YES ] I looked for a similar issue and couldn't find any.
- [ YES] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ YES] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by divan333** [comment]
OK, removing of the following line makes playback working:

/src/isomedia/media.c, function Media_GetSample, line 433:

  if ((*samp)->dataLength == 0) return GF_OK;

If the above line is commented out, the playback is working (I understand that the function will proceed with rewriting the sample with data from tile tracks and the length of the sample will be updated).

I understand this change has been added in this commit: https://github.com/gpac/gpac/commit/a6d89377c4858e16adfbed25249f0b2d01ccb216

**Comment by jeanlf** [comment]
Indeed thanks for the report, should now be fixed
