### ISSUE TITLE
Compiling gpac from source on raspberry pi 3

### ISSUE THREAD

**Issue by martinmelo00** [gpac/gpac#749]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I'm running raspberry debian jessie and performing a sudo apt-get install gpac only get version 0.5.0 of gpac.  Searching I can find a newer build for gpac.  I decidedly tried to compile locally on the raspberry pi but despite what is seemingly error less make and make install I cannot seem to find the binaries and run them.  

I believe I have gotten all dependencies installed and I've followed botht eh instructions here:
http://stuff.stevenreid.uk/2015/04/01/install-mp4client-mp4box-and-dashcast-on-raspbian/
and here:
https://gpac.wp.imt.fr/2011/04/20/compiling-gpac-on-ubuntu/

Please see the following for compilation output:

sudo ./configure --disable-all --use-js=no --use-ft=no --use-zlib=yes --use-jpeg=no --use-png=no --use-faad=yes --use-mad=no --use-xvid=system --use-ffmpeg=system --use-ogg=no --use-vorbis=no --use-theora=no --use-openjpeg=no --cpu=armv8

** System Configuration
Install prefix: /usr/local
Source path: /home/pi/Development/src/github.com/gpac
C   compiler: gcc
C++ compiler: g++
make: make
CPU: unknown
Big Endian: no

** GPAC 0.6.2-DEV rev Core Configuration **
debug version: no
GProf enabled: no
Static build enabled: no
Memory tracking enabled: no
Fixed-Point Version: no
IPV6 Support: yes
Static Modules: no
Player disabled
Scene Manager disabled
Core tools disabled
SVG disabled
MPEG-4/VRML/X3D disabled
X3D disabled
OD Full support disabled
OD Parsing disabled
BIFS coder disabled
BIFS encoder disabled
LASeR coder disabled
SAF container disabled
Scene encoder engine disabled
Cubic QTVR import disabled
AVI disabled
OGG disabled
MPEG-2 PS disabled
MPEG-2 TS disabled
MPEG-2 TS Multiplexer disabled
AV Parsers disabled
Media importers disabled
Media exmporters disabled
SWF import disabled
Scene Graph disabled
Scene statistics disabled
Scene dump disabled
Scene encoder to ISO FF disabled
Scene loader from ISO FF disabled
BT/WRL Scene loader disabled
XMT/X3D Scene loader disabled
OD dump disabled
ISOM dump disabled
MCrypt disabled
ISO File Format disabled
ISO File Format write disabled
ISO File Format hinting disabled
ISO File Format fragments disabled
ISO File Format Adobe HDS disabled
RTP/RTSP/SDP streaming disabled
VobSub disabled
3GPP/Apple TimedText disabled
TTML TimedText disabled
HLS and DASH Manifest Disabled
Adaptive HTTP Streaming Client disabled
HEVC Support disabled

** Detected libraries **
zlib: system
OSS Audio: yes
ALSA Audio: no
Jack Audio: yes
PulseAudio Audio: no
DirectFB support: no
X11 Shared Memory support: yes (path: /usr/X11R6)
X11 XVideo support: yes
SDL Support: no
OpenGL support: no
TinyGL support: no
OpenSSL support: no
Mozilla XUL/GECKO support: no
DVB Support: no
XMLRPC Support: no
wxWidgets support: no

** Extra Libraries used **
SpiderMonkey: no
FreeType: no
JPEG: no
OpenJPEG: no
PNG: no
MAD: no
FAAD: yes
XVID: system
FFMPEG: system
Xiph OGG: no
Platinum UPnP: no
AVCap: no
A52 (AC3): system
OpenSVCDecoder: no
OpenHEVCDecoder: no
Freenect: no

Creating config.mak
Check config.log for detection failures
Done - type 'make help' for make info, 'make' to build

and for the make step:

 sudo make
make -C src all
make[1]: Entering directory '/home/pi/Development/src/github.com/gpac/src'
cat .deps/utils/os_divers.dep .deps/utils/os_file.dep .deps/utils/list.dep .deps/utils/bitstream.dep .deps/utils/error.dep .deps/utils/alloc.dep .deps/utils/url.dep .deps/utils/configfile.dep .deps/isomedia/avc_ext.dep .deps/isomedia/box_code_3gpp.dep .deps/isomedia/box_code_apple.dep .deps/isomedia/box_code_base.dep .deps/isomedia/box_code_drm.dep .deps/isomedia/box_code_meta.dep .deps/isomedia/box_dump.dep .deps/isomedia/box_funcs.dep .deps/isomedia/data_map.dep .deps/isomedia/drm_sample.dep .deps/isomedia/isom_intern.dep .deps/isomedia/isom_read.dep .deps/isomedia/isom_store.dep .deps/isomedia/isom_write.dep .deps/isomedia/media.dep .deps/isomedia/media_odf.dep .deps/isomedia/meta.dep .deps/isomedia/movie_fragments.dep .deps/isomedia/sample_descs.dep .deps/isomedia/stbl_read.dep .deps/isomedia/stbl_write.dep .deps/isomedia/track.dep .deps/isomedia/tx3g.dep .deps/isomedia/iff.dep .deps/odf/desc_private.dep .deps/odf/descriptors.dep .deps/odf/odf_code.dep .deps/odf/odf_codec.dep .deps/odf/odf_command.dep .deps/odf/qos.dep .deps/odf/slc.dep .deps/media_tools/isom_tools.dep .deps/media_tools/dash_segmenter.dep .deps/media_tools/av_parsers.dep .deps/media_tools/webvtt.dep > ".depend"
  CC utils/os_divers.c
  CC utils/os_file.c
  CC utils/list.c
  CC utils/bitstream.c
  CC utils/error.c
  CC utils/alloc.c
  CC utils/url.c
  CC utils/configfile.c
  CC odf/desc_private.c
  CC odf/descriptors.c
odf/descriptors.c: In function ‘gf_odf_avc_cfg_write’:
odf/descriptors.c:586:2: warning: implicit declaration of function ‘gf_avc_is_rext_profile’ [-Wimplicit-function-declaration]
  if (gf_avc_is_rext_profile(cfg->AVCProfileIndication)) {
  ^
  CC odf/odf_code.c
  CC odf/odf_codec.c
  CC odf/odf_command.c
  CC odf/qos.c
  CC odf/slc.c
  CC isomedia/avc_ext.c
  CC isomedia/box_code_3gpp.c
  CC isomedia/box_code_apple.c
  CC isomedia/box_code_base.c
  CC isomedia/box_code_drm.c
  CC isomedia/box_code_meta.c
  CC isomedia/box_dump.c
  CC isomedia/box_funcs.c
  CC isomedia/data_map.c
  CC isomedia/drm_sample.c
  CC isomedia/isom_intern.c
  CC isomedia/isom_read.c
  CC isomedia/isom_store.c
  CC isomedia/isom_write.c
  CC isomedia/media.c
  CC isomedia/media_odf.c
  CC isomedia/meta.c
  CC isomedia/movie_fragments.c
  CC isomedia/sample_descs.c
  CC isomedia/stbl_read.c
  CC isomedia/stbl_write.c
  CC isomedia/track.c
  CC isomedia/tx3g.c
  CC isomedia/iff.c
  CC media_tools/isom_tools.c
  CC media_tools/dash_segmenter.c
  CC media_tools/av_parsers.c
  CC media_tools/webvtt.c
OBJS utils/os_divers.o utils/os_file.o utils/list.o utils/bitstream.o utils/error.o utils/alloc.o utils/url.o utils/configfile.o      isomedia/avc_ext.o isomedia/box_code_3gpp.o isomedia/box_code_apple.o isomedia/box_code_base.o isomedia/box_code_drm.o isomedia/box_code_meta.o isomedia/box_dump.o isomedia/box_funcs.o isomedia/data_map.o isomedia/drm_sample.o isomedia/isom_intern.o isomedia/isom_read.o isomedia/isom_store.o isomedia/isom_write.o isomedia/media.o isomedia/media_odf.o isomedia/meta.o isomedia/movie_fragments.o isomedia/sample_descs.o isomedia/stbl_read.o isomedia/stbl_write.o isomedia/track.o isomedia/tx3g.o isomedia/iff.o    odf/desc_private.o odf/descriptors.o odf/odf_code.o odf/odf_codec.o odf/odf_command.o odf/qos.o odf/slc.o  media_tools/isom_tools.o media_tools/dash_segmenter.o media_tools/av_parsers.o media_tools/webvtt.o
LIBS -lm -L/usr/local/lib
mv ../bin/gcc/libgpac.so ../bin/gcc/libgpac.so.7.5.0
ln -sf libgpac.so.7.5.0 ../bin/gcc/libgpac.so.7
ln -sf libgpac.so.7.5.0 ../bin/gcc/libgpac.so
make[1]: Leaving directory '/home/pi/Development/src/github.com/gpac/src'
make -C applications all
make[1]: Entering directory '/home/pi/Development/src/github.com/gpac/applications'
set -e; for i in  ; do make -C $i all; done
make[1]: Leaving directory '/home/pi/Development/src/github.com/gpac/applications'
make -C modules all
make[1]: Entering directory '/home/pi/Development/src/github.com/gpac/modules'
set -e; for i in  ; do make -C $i all; done
make[1]: Leaving directory '/home/pi/Development/src/github.com/gpac/modules'

lastly the make install step:

sudo make install
install -d "/usr/local"
install -d "/usr/local/lib"
install -d "/usr/local/bin"
if [ -d  /usr/local/lib/pkgconfig ] ; then \
install  -m 644 gpac.pc "/usr/local/lib/pkgconfig" ; \
fi
install -d "/usr/local/lib/gpac"
install bin/gcc/*.so "/usr/local/lib/gpac"
rm -f /usr/local/lib/gpac/libgpac.so
rm -f /usr/local/lib/gpac/nposmozilla.so
make installdylib
make[1]: Entering directory '/home/pi/Development/src/github.com/gpac'
install  -m 755 bin/gcc/libgpac.so.7.5.0 /usr/local/lib/libgpac.so.7.5.0
ln -sf libgpac.so.7.5.0 /usr/local/lib/libgpac.so.7
ln -sf libgpac.so.7.5.0 /usr/local/lib/libgpac.so
ldconfig || true
make[1]: Leaving directory '/home/pi/Development/src/github.com/gpac'
install -d "/usr/local/man"
install -d "/usr/local/man/man1"
install  -m 644 /home/pi/Development/src/github.com/gpac/doc/man/mp4box.1 /usr/local/man/man1/
install  -m 644 /home/pi/Development/src/github.com/gpac/doc/man/mp4client.1 /usr/local/man/man1/
install  -m 644 /home/pi/Development/src/github.com/gpac/doc/man/gpac.1 /usr/local/man/man1/
install -d "/usr/local/share/gpac"
install  -m 644 /home/pi/Development/src/github.com/gpac/doc/gpac.mp4 /usr/local/share/gpac/
install -d "/usr/local/share/gpac/gui"
install  -m 644 /home/pi/Development/src/github.com/gpac/gui/gui.bt "/usr/local/share/gpac/gui/"
install  -m 644 /home/pi/Development/src/github.com/gpac/gui/gui.js "/usr/local/share/gpac/gui/"
install  -m 644 /home/pi/Development/src/github.com/gpac/gui/gwlib.js "/usr/local/share/gpac/gui/"
install  -m 644 /home/pi/Development/src/github.com/gpac/gui/mpegu-core.js "/usr/local/share/gpac/gui/"
install  -m 644 /home/pi/Development/src/github.com/gpac/gui/webvtt-renderer.js "/usr/local/share/gpac/gui/"
install -d "/usr/local/share/gpac/gui/icons"
install -d "/usr/local/share/gpac/gui/extensions"
install -d "/usr/local/share/gpac/shaders/"
cp --no-preserve=mode,ownership,timestamp /home/pi/Development/src/github.com/gpac/gui/icons/* /usr/local/share/gpac/gui/icons/
cp -R --no-preserve=mode,ownership,timestamp /home/pi/Development/src/github.com/gpac/gui/extensions/* /usr/local/share/gpac/gui/extensions/
cp --no-preserve=mode,ownership,timestamp /home/pi/Development/src/github.com/gpac/shaders/* /usr/local/share/gpac/shaders/

After all these steps I cannot find MP4Box or DashCast.  The binaries are not found in /usr/local/bin/ and they results in unknown bash commands.  Any help would be greatly appreciated.  I was prompted to try and update the version of gpac per this issue:
https://github.com/gpac/gpac/issues/538

Again any and all help would be greatly appreciated. Thanks.

**Comment by aureliendavid** [comment]
Hi, 

I think if you use `./configure` with the `--disable-all` flag it won't produce any binaries, it will only build the `libgpac.so` shared library. 

The binaries are in the `applications/` folder. You can see in your make output that when it goes there it has nothing to build: 

```
make -C applications all
make[1]: Entering directory '/home/pi/Development/src/github.com/gpac/applications'
set -e; for i in ; do make -C $i all; done
make[1]: Leaving directory '/home/pi/Development/src/github.com/gpac/applications'
```

at the top of the file `applications/Makefile` you can see some conditions that defines which binaries are going to be built:

```
ifeq ($(MP4BOX_STATIC),yes)
APPDIRS+=mp4box 
else

ifeq ($(DISABLE_PLAYER), no)
APPDIRS+=mp4client 
endif

ifeq ($(DISABLE_ISOFF), no)
APPDIRS+=mp4box 
ifeq ($(DISABLE_M2TS_MUX), no)
APPDIRS+=mp42ts 
endif

ifneq ($(CONFIG_WIN32), yes)
ifneq ($(CONFIG_FFMPEG), no)
ifneq ($(DISABLE_CORE_TOOLS), yes)
ifneq ($(DISABLE_AV_PARSERS), yes)
APPDIRS+=dashcast
endif
endif
endif
endif
```

My advice would be to adjust your `./configure` options so that the tools you need are built. 

Hope this helps.

**Comment by martinmelo00** [comment]
Thank you very much for your input.  I finally go it compiling but looks like now I'm having other issues.  I'll close this in favor of creating a new issue for the problem!
