### ISSUE TITLE
Webm dashing with MP4Box

### ISSUE THREAD

**Issue by kiloreux** [gpac/gpac#750]
I wanted to do a dash video with MP4Box. 
I generated 2 videos and 2 audios with FFmpeg using the following settings.

`ffmpeg -i oceans.mp4 -map 0:a -map -0:d -map -0:s -acodec libvorbis -ab 45k -ar 44100 -f webm  -preset veryfast -vn  -strict -2 audio_45k` 

`ffmpeg -i oceans.mp4 -map 0:a -map -0:d -map -0:s -acodec libvorbis -ab 64k -ar 44100 -f webm  -preset veryfast -vn  -strict -2 audio_64k`

`ffmpeg -i oceans.mp4 -map 0 -map -0:d -map -0:s -c:v libvpx -c:a libvorbis  -f webm  -pix_fmt yuv420p -x264opts keyint=30:min-keyint=30:no-scenecut -r 30    -s 480x270 -crf 28     -g 30     -b:v 460000     -maxrate 500000    -bufsize 500000    -b:a 32000     -ac 2     -ar 44100     -preset veryfast     -an true 270.webm`

`ffmpeg -i oceans.mp4 -map 0 -map -0:d -map -0:s -c:v libvpx -c:a libvorbis  -f webm  -pix_fmt yuv420p -x264opts keyint=30:min-keyint=30:no-scenecut -r 30 -s 640x360 -crf 28 -g 30 -b:v 800000 -maxrate 1000000 -bufsize 1000000 -b:a 64000 -ac 2 -ar 44100  -preset veryfast -an true 360p.webm`

When trying to generate a dash of these using MP4Box, with the following command, 

`MP4Box -dash 4000 -rap -frag-rap -profile onDemand -segment-name segment -out dashed.mpd  ./audio_45k ./audio_64k ./270.webm ./360.webm`

It gives the following error, 
`[DASH]: File ./audio_45k not supported for dashing - skipping
[DASH]: Cannot open file ./audio_45k for dashing: Feature Not Supported
[DASH]: File ./audio_64k not supported for dashing - skipping
[DASH]: Cannot open file (null) for dashing: Feature Not Supported
[DASH]: Cannot open file (null) for dashing: Requested URL is not valid or cannot be found
[DASH]: Cannot open file (null) for dashing: Requested URL is not valid or cannot be found
[DASH] Error: no suitable file found for dashing.
`

I tried using MP4Box add but same thing. I get an error. 

Would love to get some help on this!

**Comment by rbouqueau** [comment]
We don't support WebM but that a subject of interest. See also https://gpac.wp.imt.fr/jobs/google-summer-of-code-ideas/. Let us know if you wish to contribute :)

**Comment by jeanlf** [comment]
Webm dashing is supported in 1.0 through libavformat, see [--muxtype](https://github.com/gpac/gpac/wiki/dasher#muxtype) option.
