### ISSUE TITLE
printing variables to a file

### ISSUE THREAD

**Issue by djjeff** [gpac/gpac#751]
Hi,
Read a couple answers about writing log files with -lf but it seems not to be working for me. With the earlier versions of gpac i can use printf to print variables (e.g printf("bandwidth is : %d\n",bandwidth);)  and have them written to a file with a simple **MP4Client  abc.mpd >mylog.txt** . Do i have to enable anything to be able to have same achieved in the newer versions of gpac.

Thanks,

jeff

**Comment by jeanlf** [comment]
"-lf" redirects only gpac logs, eg logs done through the GF_LOG() macro. You can change your printf() into GF_LOG and define your own log tool type if needed, or use one of the predefined tools.
