### ISSUE TITLE
MP4Client failed to playback hevc-tiled dash contents

### ISSUE THREAD

**Issue by xixi10111011** [gpac/gpac#755]
I installed GPAC by using nightly builds http://gpac.io/downloads/gpac-nightly-builds/
http://download.tsi.telecom-paristech.fr/gpac/latest_builds/linux64/gpac/gpac_0.6.2-DEV-rev1395-g8d096e5-master_amd64.deb

MP4Client -gui http://download.tsi.telecom-paristech.fr/gpac/SRD/srd_hevc/multi_rate/hevc_srd.mpd#LIVE360

MP4Client failed to playback hevc-tiled dash contents
log shows:
[Codec] ODM1 ES1: Cannot find decoder for stream type MPEG-H HEVC Video
Deleting terminal... done (in 166 ms) - ran for 8887 ms
GPAC cleanup .

please help, thanks

**Comment by jeanlf** [comment]
Could you try rebuilding gpac from source (also rebuild openhevc) and see if you have the same issue ?

**Comment by alejandraimaz** [comment]
I have the same issue, I rebuilt GPAC and openHEVC and still doesn't work

**Comment by jeanlf** [comment]
Have you tried removing the GPAC config ($HOME/.gpac/GPAC.cfg) before relaunching the client after rebuild?

**Comment by alejandraimaz** [comment]
Yes and now I got this:

GPAC config file GPAC.cfg not found in $HOME/.gpac - creating new file
Using config file in $HOME/.gpac directory
System info: 15992 MB RAM - 8 cores
Modules Found : 38 
Loading GPAC Terminal
[Core] Cannot load module file /usr/lib/gpac//gm_gpac_js.so, error is /usr/lib/gpac//gm_gpac_js.so: undefined symbol: gf_sg_js_has_instance
[Core] Cannot load library gm_gpac_js.so
[Core] Cannot load module file /usr/lib/gpac//gm_widgetman.so, error is /usr/lib/gpac//gm_widgetman.so: undefined symbol: gf_sg_js_has_instance
[Core] Cannot load library gm_widgetman.so
[Thread MediaManager] Couldn't set priority(2) for thread ID 0x2b8f1700
[Thread MediaManager] Couldn't set priority(2) for thread ID 0x2b8f1700
Terminal Loaded in 710 ms
Hit 'h' for help

Deleting terminal... done (in 96 ms) - ran for 8416 ms
GPAC cleanup ...

**Comment by aureliendavid** [comment]
@alejandraimaz what command are you running exactly? how does it not work (crash, blank screen, ..)?

**Comment by alejandraimaz** [comment]
I am running:  
MP4Client -gui manifest.mpd#LIVE360
And I get what showed above and a black screen (MP4Client player)

**Comment by JamesXu20150314** [comment]
Can you show your MPD file content?
And what's your command to tile the video?
