### ISSUE TITLE
MP4BOX duplicates one stream for all "AdaptationSets" when creating .mpd from a muxed-source

### ISSUE THREAD

**Issue by Dikoian** [gpac/gpac#756]
### MP4BOX - Version Info
_MP4Box - GPAC version 0.6.1-revrelease
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: --disable-wx --disable-pulseaudio --prefix=/usr/local/Cellar/gpac/0.6.1 --mandir=/usr/local/Cellar/gpac/0.6.1/share/man --disable-x11
Features: GPAC_64_BITS GPAC_HAS_SSL_ 

### Downloadable Source files and results
Download zip file containing muxed Source file **"MULTIPLEX_DASH.mp4"**, Muxed init-file **"MULTIPLEX_DASH_dashinit.mp4"** and .mpd-file **"OHD_25_multivideo.mpd"**.
**Download link:** https://pluto.twotype.se/~thomas/Bug_MP4BOX_Files/mp4box_bug_material.zip

### Reason why reporting this as a bug
According **Romain** over at http://stackoverflow.com, my mp4box script is correct and this should be reported as a bug.
**Stackoverflow forum thread:** http://stackoverflow.com/questions/42230812/segment-audio-video-and-create-mpd-with-mp4box

### Bug-information

- When running scrips below, the created .mpd file is not created correctly. The .mpd only uses one stream for all **"AdaptationSets"**. Look at downloadable files for result.
- To re-create the issue, use the muxed **"MULTIPLEX_DASH.mp4"** as source and run command below.

### MP4BOX - Script

```
MP4Box -dash 4000
       -profile dashavc264:onDemand
       -bs-switching no
       -url-template
       -mpd-title multivideo_vod_mpd
           MULTIPLEX_DASH.mp4:trackID=1:id=v0:role=v0
           MULTIPLEX_DASH.mp4:trackID=2:id=v1:role=v1
           MULTIPLEX_DASH.mp4:trackID=3:id=v2:role=v2
           MULTIPLEX_DASH.mp4:trackID=4:id=v3:role=v3
           MULTIPLEX_DASH.mp4:trackID=5:id=v4:role=v4
           MULTIPLEX_DASH.mp4:trackID=6:id=v5:role=v5
           MULTIPLEX_DASH.mp4:trackID=7:id=v6:role=v6
           MULTIPLEX_DASH.mp4:trackID=8:id=v7:role=v7
           MULTIPLEX_DASH.mp4:trackID=9:id=a0
           MULTIPLEX_DASH.mp4:trackID=10:id=a1
           MULTIPLEX_DASH.mp4:trackID=11:id=a2
       -out OHD_25_multivideo.mpd

```

**Comment by jeanlf** [comment]
this has been fixed in GPAC 0.9.0
