### ISSUE TITLE
MP4Box apparently interleaving 0.500 secs even when specify -inter 0

### ISSUE THREAD

**Issue by markmarz** [gpac/gpac#760]
All I want to do is move the MOOV atom. According to docs -inter 0 should do it without interleaving. Console messages indicate otherwise.

```
C:\temp>mp4box -version
MP4Box - GPAC version 0.6.1-rev0-g72d766c-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: (static configuration file)
Features: GPAC_64_BITS GPAC_MEMORY_TRACKING GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG

C:\temp>mp4box -inter 0 input.mp4 -out output.mp4
Saving to output.mp4: 0.500 secs Interleaving

C:\temp>
```

**Comment by rbouqueau** [comment]
Thanks for reporting. It should be fixed now. Reopen if needed.

**Comment by markmarz** [comment]
Am I pulling the right version? I get the same result as before. Don't want to reopen if I'm doing something dumb.

https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/
gpac-0.6.2-DEV-rev1406-gfa9ab95-master-x64.exe

C:\temp>mp4box -version
MP4Box - GPAC version 0.6.2-DEV-rev1406-gfa9ab95-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: (static configuration file)
Features: GPAC_64_BITS GPAC_MEMORY_TRACKING GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG

C:\temp>mp4box -inter 0 "Gay Purr-ee (1962).mp4" -out output.mp4
Saving to output.mp4: 0.500 secs Interleaving

**Comment by rbouqueau** [comment]
It is rev1409, I think you need to wait for a little more minutes for the buildbot to finish :)

**Comment by markmarz** [comment]
Ah! Will do, thanks!

**Comment by aureliendavid** [comment]
Hi @rbouqueau 

The fix seems to break some tests :

```
*** Subtest "Split": executing "MP4Box -noprog -for-test  -add ./external_media/scalable/shvc.265:svcmode=split -new ./results/temp/shvc-split.mp4" ***
HEVC import - frame size 1920 x 800 at 25.000 FPS
LHVC detected - 3840 x 1600 at 25.000 FPS
HEVC Import results: 502 samples (2013 NALUs) - Slices: 11 I 117 P 876 B - 1004 SEI - 1 IDR
Stream uses forward prediction - stream CTS offset: 3 frames
OpenGOP detected - adjusting file brand
[HEVC] Failed to update HEVC/LHVC sample (track 1, base sample num 1)
Error importing ./external_media/scalable/shvc.265:svcmode=split: Invalid Mode while accessing the file
```

(the file is here: http://download.tsi.telecom-paristech.fr/gpac/gpac_test_suite/resources/media/scalable/shvc.265)

I haven't had time to check why yet, but I'm reporting :)

**Comment by rbouqueau** [comment]
Thank you. Let me have a look.
