### ISSUE TITLE
Create MPD file and DASHable segments with lots of small MP4 video files

### ISSUE THREAD

**Issue by kvasukib** [gpac/gpac#762]
Hello all,

We are working on a problem, where we have a large set of images of a video, from which we create a bunch of video segments. After this process we have multiple video files which played together will have the whole video. For example, output1.mp4, output2.mp4,output3.mp4, output4.mp4, output5.mp4 combined together represents a single video called output.mp4. Now we want the video segments to be streamed using DASH protocol.

We can think of two approaches.
1. Use MP4Box for each video segment by using "-single-segment". So it generates just one segment and a MPD file for it. Now merge all MPDs into one MPD. And give the single master MPD to the DASH player to stream the video.

2. Use MP4Box to create one MPD file for all the videos.

We are not sure about the feasibility of these approaches. Can you guide us on what would be the ideal solution for this problem by using MP4Box or is there any other tool available which can solve this problem?

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [Y ] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by rbouqueau** [comment]
>  For example, output1.mp4, output2.mp4,output3.mp4, output4.mp4, output5.mp4 combined together represents a single video called output.mp4

By "combine" you mean "concatenate", right?

Both your approches work. Approach 1. will result in several ```Period```s while 2. will get only one.

> Can you guide us on what would be the ideal solution for this problem by using MP4Box or is there any other tool available which can solve this problem?

Could you make a sentence to explain what the problem is?

**Comment by kvasukib** [comment]
Yes, by combine, I mean "concatenate".

Is it possible to achieve (2) with MP4Box, i.e is it possible to pass multiple videos as input to MP4Box to generate 1 MPD file?

**Comment by rbouqueau** [comment]
Ok. Not with MP4Box at this point: we expect people to combine MPDs (which is XML) by their own means.

**Comment by kvasukib** [comment]
@rbouqueau Thank you!
