### ISSUE TITLE
mpeg-dash unable to play audio

### ISSUE THREAD

**Issue by evangeline123** [gpac/gpac#763]
I have used ffmpeg and mp4box to create mpeg-dash videos. when i try to play the videos, i only get the video and by checking the network status, i can see that only video segments are being played, not the audio. how can i fix this??

this is my mp4box command: 

`MP4Box -dash 4000 -profile onDamand -rap -segment-name %s_ -out manifest.mpd video1.mp4 video2.mp4 audio.mp4`

**Comment by rbouqueau** [comment]
There are not enough information to reproduce. How was the content generated? Which version of MP4Box? Which player?

Please read:
 - encoding: https://blog.streamroot.io/encode-multi-bitrate-videos-mpeg-dash-mse-based-media-players-22/ or http://www.gpac-licensing.com/2014/11/03/bitmovin-leverage-mp4box-package-contents-bitdash-player/
 - packaging: http://www.gpac-licensing.com/2014/08/21/ibc-2014-dash-avc264-support-in-gpac/

**Comment by evangeline123** [comment]
I created the videos with this command:

`ffmpeg -i cmain720.MTS -movflags faststart -r 24 -vcodec libx264 -preset slow -tune zerolatency -tune fastdecode -b:v 700k -maxrate 700k -bufsize 1000k -g 96 -an -s 1280*720 main720_700.mp4`

and audio with this:

`ffmpeg -i cmain720.MTS -movflags faststart -acodec libmp3lame -b:a 128k -vn main720_300_audio.mp4`

this is the version:

MP4Box - GPAC version 0.5.2-DEV-revVersion: 0.5.2-426-gc5ad4e4+dfsg5-1build1


and I am playing them with video.js

here is my demo:

http://79.175.133.185/static/videos/main_dash/index3.html

**Comment by rbouqueau** [comment]
Thanks. If you update your mp4box and use the command-lines that are recommended (see the articles in my previous message), does it work?

**Comment by evangeline123** [comment]
I have read that topic, and used the recommended commands, but still no switching

**Comment by rbouqueau** [comment]
Could you share your content (dropbox at https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95) + command-lines so that we reproduce?

**Comment by evangeline123** [comment]
sure, thanks

**Comment by evangeline123** [comment]
I shared my main video, and these are my command lines:

ffmpeg -i hd_1.mp4 -movflags faststart -r 24 -vcodec libx264 -preset slow -tune zerolatency -tune fastdecode -b:v 300k -maxrate 300k -bufsize 400k -g 96 -an -s 640*360 video1.mp4

ffmpeg -i hd_1.mp4 -movflags faststart -r 24 -vcodec libx264 -preset slow -tune zerolatency -tune fastdecode -b:v 700k -maxrate 700k -bufsize 1000k -g 96 -an -s 1280*720 video2.mp4

ffmpeg -i hd_1.mp4 -movflags faststart -acodec libmp3lame -b:a 128k -vn main720_300_audio.mp4

ffmpeg -i hd_1.mp4 -movflags faststart -acodec libmp3lame -b:a 320k -vn main720_700_audio2.mp4

MP4Box -dash 4000 -profile onDamand -rap -segment-name %s_ -out manifest.mpd video1.mp4 video2.mp4 audio1.mp4 audio2.mp4

**Comment by rbouqueau** [comment]
2 remarks:
 1. Since you have issues with audio and you are not using the same codec (mp3) as recommended (aac), could you re-encode your audio and test again please?
 2. How could we test with the same player as you? Is there a link?

**Comment by evangeline123** [comment]
yes I will re-encode the videos with aac. 
the player is video.js, and I have a simple code that works with relative paths. I can share the player code and you can test the videos in that player.

**Comment by evangeline123** [comment]
re-encoding with libfdk_ aac seems to have solved my isue. i tried it with another video and its switching between sound and video, now i should try it with my main video.
thanks
