### ISSUE TITLE
on-demand video playback delay

### ISSUE THREAD

**Issue by evangeline123** [gpac/gpac#764]
I have used ffmpeg and mp4box to create a non-adaptive mpeg-dash, and I am doing it by using only one bitrate in each video (its just a test). here is my demo link. my video has a delay about 15 seconds when I seek in the video and its so bad for my purpose. why am I having this delay?? is it a buffering problem?? I would realy appreciate any help

http://79.175.133.185/static/videos/main_dash/

**Comment by jeanlf** [comment]
we wouuld need more info to solve that (which player is being used, duration of segments, GOP size etc ...). Reopen if needed
