### ISSUE TITLE
Incorrect duration in segment template due to improper rounding

### ISSUE THREAD

**Issue by fumminger** [gpac/gpac#765]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ X] I looked for a similar issue and couldn't find any.
- [ X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

====

Steps to reproduce
=============
- Steps will work on Windows 10 or Linux, with v0.6.1 or the latest nightly build.
- Use the following ffmpeg command to generate test material
     ffmpeg -f lavfi -i smptebars=duration=10:size=3840x2160:rate=30000/1001  -vf "drawtext=text=\'pts %{pts}\':fontcolor=white:fontsize=120:x=w/2:y=h/2:shadowx=-3:shadowy=3" -an -y test.mp4
- Use the following MP4Box command to generate an MPD file:
   MP4Box -min-buffer 250 -profile live -bs-switching no -rap -out test.mpd -dash-scale 30000 -dash 30030 test.mp4#video
- The MPD file will have a single AdaptationSet with a single Representation. The SegmentTemplate for that Representation will have a duration of 30029.
- The duration should be 30030. 30029 is an impossible value given the frame rate.
- This is 100% reproducible

Version
=====
Windows 10, downloaded from https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/
MP4Box -version
MP4Box - GPAC version 0.6.2-DEV-rev1383-g4b83ff6-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: (static configuration file)
Features: GPAC_64_BITS GPAC_MEMORY_TRACKING GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG

Ubuntu 16.04, built from source from Branch_v0.6.1 
MP4Box -version
MP4Box - GPAC version 0.6.1-rev1-g733cc1a-Branch_v0.6.1
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: --static-mp4box
Features: GPAC_64_BITS GPAC_DISABLE_3D

Fix
===
The bug may be fixed may be fixed by properly rounding the value for duration from Double to u32 wherever it is printed in gpac_public\src\media_tools\dash_segmenter.c
A diff file with the fix is attached. This is diffed against v0.6.1.
[dash_segmenter.zip](https://github.com/gpac/gpac/files/809373/dash_segmenter.zip)

**Comment by rbouqueau** [comment]
Thanks for reporting. Let me check, I remember having written a patch (merged) for framerate rounding with DASH.

**Comment by rbouqueau** [comment]
Fixed, thanks for reporting!
