### ISSUE TITLE
MP4Box creates empty file when wrapping HE-AAC ADTS in M4A container

### ISSUE THREAD

**Issue by pjbcr** [gpac/gpac#766]
Hello,

I have a bunch of aac that I'm trying to wrap in a m4a container.
But when I use mp4box to wrap it it just creates a 1KB, 1sec file.

I tried with gpac-0.6.1-rev0-g72d766c-master-win32, gpac-0.6.1-rev0-g72d766c-master-x64 and the latest dev build, gpac-0.6.2-DEV-rev1406-gfa9ab95-master-x64

I'm using Windows 7 N 64bit with media pack installed.

Below is a few debugs I did.
Not sure if relevant, but MP4Box detects the wrong amount of channels.
I'm attaching both original and the created file by mp4box.
I also tried using the -flat, -ipod and other switches but all with the same result.

Thanks for your attention!

[v6_dev.zip](https://github.com/gpac/gpac/files/811876/v6_dev.zip)

####################################################################
D:\Pedro\Desktop\mp4box_test\v6_dev>mp4box -version
MP4Box - GPAC version 0.6.2-DEV-rev1406-gfa9ab95-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: (static configuration file)
Features: GPAC_64_BITS GPAC_MEMORY_TRACKING GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG

D:\Pedro\Desktop\mp4box_test\v6_dev>mp4box -info sweet_dreams.aac
Import probing results for sweet_dreams.aac:
File has 1 tracks
        Track 1 type: Audio (....)

D:\Pedro\Desktop\mp4box_test\v6_dev>mp4box -info 1 sweet_dreams.aac
Import probing results for track sweet_dreams.aac#1:
Track type: Audio (....)
Source: .... - SampleRate 7350 - 4 channels

Import Capabilities:
        Can use AAC-SBR signaling
        Can use AAC-PS signaling
        Can force MPEG-4 Systems signaling

D:\Pedro\Desktop\mp4box_test\v6_dev>mp4box -add sweet_dreams.aac -new result_dev.m4a
MPEG-4 AAC in LOAS import - sample rate 7350 - 4 channels
Setting up iTunes/iPod file...
Saving result_dev.m4a: 0.500 secs Interleaving

D:\Pedro\Desktop\mp4box_test\v6_dev>

Using Media Info
######################### ORIGINAL FILE ######################################
General
Complete name                            : D:\Pedro\Desktop\mp4box_test\v6_dev\sweet_dreams.aac
Format                                   : ADTS
Format/Info                              : Audio Data Transport Stream
File size                                : 1.84 MiB
Overall bit rate mode                    : Variable
Track name                               : Sweet Dreams (Are Made Of This) 2k12 (Lazybox Bootleg Mix)
Performer                                : Eurythmics
Genre                                    : Electronic Hands Up Eurodance

Audio
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format version                           : Version 2
Format profile                           : HE-AAC / LC
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 44.1 kHz / 22.05 kHz
Frame rate                               : 21.533 FPS (1024 spf)
Compression mode                         : Lossy
Stream size                              : 1.84 MiB (100%)

##################### RESULT FILE #######################################
General
Complete name                            : D:\Pedro\Desktop\mp4box_test\v6_dev\result_dev.m4a
Format                                   : MPEG-4
Format profile                           : Apple audio with iTunes info
Codec ID                                 : M4A  (isom/M4A /mp42)
File size                                : 830 Bytes
Duration                                 : 1 s 0 ms
Overall bit rate mode                    : Constant
Overall bit rate                         : 6 640 b/s
Encoded date                             : UTC 2017-02-28 22:10:26
Tagged date                              : UTC 2017-02-28 22:10:26

Audio
ID                                       : 1
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Codec ID                                 : 40
Duration                                 : 1 s 0 ms
Bit rate mode                            : Constant
Bit rate                                 : 936 b/s
Channel(s)                               : 2 channels
Sampling rate                            : 7 350 Hz
Frame rate                               : 7.178 FPS (1024 spf)
Compression mode                         : Lossy
Stream size                              : 117 Bytes (14%)
Title                                    : aac@GPAC0.6.2-DEV-rev1406-gfa9ab95-master
Encoded date                             : UTC 2017-02-28 22:10:26
Tagged date                              : UTC 2017-02-28 22:10:27

**Comment by jeanlf** [comment]
these files are broken, can't mux them using ffmpeg either
```
ffmpeg -i sweet_dreams.aac -c:a copy test.mp4
ffmpeg version N-93022-g260f1960e7 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple LLVM version 10.0.0 (clang-1000.11.45.5)
  configuration: --enable-avresample --enable-libx264 --enable-gpl --disable-iconv --enable-libaom
  libavutil      56. 26.100 / 56. 26.100
  libavcodec     58. 44.100 / 58. 44.100
  libavformat    58. 26.100 / 58. 26.100
  libavdevice    58.  6.101 / 58.  6.101
  libavfilter     7. 48.100 /  7. 48.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
[aac @ 0x7fd491001000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7fd491001000] Inconsistent channel configuration.
[aac @ 0x7fd491001000] get_buffer() failed
[aac @ 0x7fd491801200] decoding for stream 0 failed
[aac @ 0x7fd491801200] Estimating duration from bitrate, this may be inaccurate
[aac @ 0x7fd491801200] Could not find codec parameters for stream 0 (Audio: aac (Main), 5.1, fltp, 693 kb/s): unspecified sample rate
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, aac, from 'sweet_dreams.aac':
  Metadata:
    genre           : Electronic Hands Up Eurodance
    title           : Sweet Dreams (Are Made Of This) 2k12 (Lazybox Bootleg Mix)
    artist          : Eurythmics
  Duration: 00:00:22.25, bitrate: 695 kb/s
    Stream #0:0: Audio: aac (Main), 5.1, fltp, 693 kb/s
[mp4 @ 0x7fd492018600] sample rate not set
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
    Last message repeated 1 times
```

**Comment by rsporsche** [comment]
FYI winamp plays the aac file just fine.
I've been having a similar problem with files I record from an online radio station using python and urllib2. I found that if I truncate the beginning of the aac file then it works ok.
Previously I had done this via trial and error. Today I noticed that when viewing the aac file's fileinfo in winamp it showed 'header found at: 428 bytes' and if I did this:
tail -c +428 file.aac > file2.aac
then I was able to successfully wrap file2.aac using:
mp4box -add file2.aac -new file.m4a
I guess the aac file is technically corrupt but I'm also assuming that the aac format is resilient against packet loss so unless it's completely corrupted it should be possible to read most of the file? At least H.264 is designed this way with it's NAL units.

**Comment by jeanlf** [comment]
this should now be fixed in 0.9.0 thanks for the insight!

**Comment by rsporsche** [comment]
Brilliant, can't wait to try it

**Comment by pjbcr** [comment]
Thank you @rsporsche!
I knew the files were not completely corrupted, but I couldn't, with my limited knowledge, refute jean's statement.
If this fix woks it will help me convert big part of my audio library without having to re-encode everything!
