### ISSUE TITLE
convert MKV to mpeg-dash

### ISSUE THREAD

**Issue by evangeline123** [gpac/gpac#768]
I have created some mpeg-dash video with mp4 videos and they work fine, now I have a mkv video file, and I converted it to mp4 with : 

`ffmpeg -i a.mkv -acodec copy -vcodec copy a.mp4 `

and then I made the video streams with: 

`ffmpeg -i a.mp4 -movflags faststart -r 24 -vcodec libx264 -preset slow -tune zerolatency -tune fastdecode -b:v 300k -maxrate 300k -bufsize 400k -g 96 -an -s 640*360 a300.mp4`

and then made the dash file:

`MP4Box -dash 4000 -profile onDamand -rap -segment-name %s_ -out manifest.mpd a300.mp4 audio.mp4`

I tried to play it with videoJS but It seems like it can not play the mpd file. 
I tried these codes with other mp4 files and it works fine!
any ideas?

**Comment by jeanlf** [comment]
check your command line, you have "onDamand" instead of "onDemand". I would suggest to also try with "dashavc264:onDemand" profile

**Comment by evangeline123** [comment]
I tried that too, but still no playback @jeanlf

**Comment by jeanlf** [comment]
did you manage to get that working ?

**Comment by jeanlf** [comment]
I believe this is an encoding issue and not a dashing one - 0.9.0 should give you more warnings if something is wrong with the input in terms of segmentation
