### ISSUE TITLE
onDemand profile and creating the segments

### ISSUE THREAD

**Issue by evangeline123** [gpac/gpac#769]
I am using onDemand profile to create my mpeg-dash using mp4box, and it is working fine, but it does not create small segments and just uses byte range to play the mpeg-dash.
is there any way to use that option and create the segments too?? 

`MP4Box -dash 4000 -profile onDamand -rap -segment-name %s_ -out manifest.mpd audio.mp4 video1.mp4 video2.mp4`

**Comment by jeanlf** [comment]
"onDemand" (not "onDamand") profile in DASH uses a single file (segment) with sidx info in each file to get byte-ranges to subsegments. To create several segments, use "live" profile
