### ISSUE TITLE
different number of segments for audio and video

### ISSUE THREAD

**Issue by evangeline123** [gpac/gpac#771]
I am creating live profile dash using mp4box, and it is creating different number of segments for audio and video. audio has less segments. how can I fix this? it is causing some problems in playback

`MP4Box -dash 4000 -rap -profile live -segment-name %s_ -frag-rap -out dash2/manifest.mpd 1500.mp4 700.mp4 audio.mp4`

demo:

http://79.175.133.185/static/videos/main_dash/ondemand.html

**Comment by rbouqueau** [comment]
This issue will be marked as invalid if you don't provide all the requested information. Thank you.

**Comment by evangeline123** [comment]
I added the information

**Comment by rbouqueau** [comment]
Could you give a link to the content so that we can reproduce? Could you give the platform/gpac version etc. so that we make sure we are all talking about the same artifacts?

We would highly appreciate if you could read this: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/. Thanks

**Comment by evangeline123** [comment]
my gpac version is:
MP4Box - GPAC version 0.6.1-revrelease

and I uploaded my videos here:
https://expirebox.com/download/13f55053e777781bb111b565cd961c28.html

does -profile: live has something to do with this problem??

**Comment by rbouqueau** [comment]
> I am creating live profile dash using mp4box, and it is creating different number of segments for audio and video. audio has less segments. how can I fix this?

The duration of your content is not the same so it is expected to have a different number of segments. Please read the documentation and use the ```:duration``` attribute to force the duration of your media.
