### ISSUE TITLE
MP4Box -dash create HLS m3u8 for fragmented MP4

### ISSUE THREAD

**Issue by atane-webmaster** [gpac/gpac#772]
Apple announced support of fragmented MP4 for HLS m3u8 ( https://developer.apple.com/videos/play/wwdc2016/504/ )
MP4Box works like a charm to create MP4 fragments and Media Presentation Description (.mpd) for MPEG-DASH

Question 1: How to create with MP4Box m3u8 for HLS with fragmented mp4 (instead of MPEG-TS fragments)
Question 2: When creating with MP4Box -dash MPD with fragmented mp4, is it possible/how to create an m3u8 pointing to the existing fragmented mp4 files previously created with MP4Box -dash

Using Linux Ubuntu 16.04LTS 
Using for MP4Box (through git clone)
MP4Box - GPAC version 0.6.2-DEV-rev1411-g77620ef-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: 
Features: GPAC_64_BITS GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG

**Comment by RostorX** [comment]
Same request for me :)

**Comment by sunilkumarmohanty** [comment]
I am also waiting for the same... Is there a way to use Mp4Box for the same

**Comment by ycinfinity** [comment]
In addition，how to encrypt fMP4 by using 'cbcs' for Fairplay?

**Comment by jeanlf** [comment]
For the MPD->M3U8 it shouldn't be too hard to add once we merge PR #784 (almost there ...).

For fMP4 in cbcs, check https://gpac.wp.imt.fr/mp4box/encryption/common-encryption/

**Comment by ycinfinity** [comment]
Hi @jeanlf , thanks for your answer.
This is my drm_crypt.xml for 'cbcs' encryption.
```
<?xml version="1.0" encoding="UTF-8"?>
<GPACDRM type="CENC AES-CBC Pattern">
<DRMInfo type="pssh" version="1">
<BS ID128="0x1077EFECC0B24D02ACE33C1E52E2FB4B"/>
<BS value="1" bits="32"/>
<BS ID128="0x279926496a7f5d25da69f2b3b2799a7f"/>
</DRMInfo>
<CrypTrack trackID="1" IsEncrypted="1" constant_IV_size="16" constant_IV="0x92dfe22e1cbd54651fce92cd54d34078" crypt_byte_block = "1" skip_byte_block = "9" saiSavedBox="senc">
<key KID="0x279926496a7f5d25da69f2b3b2799a7f" value="0x5172f0c47fb41ac5efad2d354d3db2be"/>
</CrypTrack>
</GPACDRM>
```
It can't work.  Do you know what's wrong?

Thanks

**Comment by JapSeyz** [comment]
@jeanlf Any news on this? A way to convert a .mpd to .m3u8 with support for fragmented MP4s would allow MP4BOX to be used for both DASH and HLS

**Comment by ronak2121** [comment]
Likewise I'm trying to do this by hand, but I'm not able to create valid streams by copying the mediaRanges from the MPD

**Comment by ronak2121** [comment]
Hi,

I tried to handdoctor my own m3u8 using mp4box's generated mpd, but I was unable to make it play. Our streams are purely audio only with no video tracks.

But, the main issues I saw was that the HLS spec requires that the brand requires iso6, and not iso5 like MP4Box generates. I'm not sure if the remaining boxes in the generated MP4 are also completely following the HLS spec: https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-3.3.

Just thought I'd let you know.

Ronak

**Comment by loadhigh** [comment]
I was able to manually convert the onDemand profile DASH mpd representations into their respective prog_index.m3u8 by parsing the SIDX box to find out the offset of each fragment. The only part that's hard to make (but doable using ffprobe) is the iframe_index.m3u8, which I doubt is even required.

**Comment by gokerwin** [comment]
I also want to get MPD->M3U8  for fragmented MP4s with HLS.   @loadhigh how do you get  every fragment's duration for #EXTINF tag ?

**Comment by loadhigh** [comment]
Here's the pseudocode:
```
<% 
index_range = dash_rep.attr("indexRange")
sidx = parse_sidx(dash_rep)
time_scale = sidx.time_scale
offset = index_range.end
entries = sidx.entries
target_duration = max(entries.map (entry) -> { 
  return entry.sub_segment_duration / (float)time_scale
})
%>
#EXTM3U
#EXT-X-TARGETDURATION:<%=round(target_duration) %>
#EXT-X-VERSION:7
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MAP:URI="<%= uri %>",BYTERANGE="<%= offset %>@0"
<% 
   entries.each (entry)-> {
   duration = round(entriy.sub_segment_duration / time_scale, 5)
%>
#EXTINF:<%= duration %>,
#EXT-X-BYTERANGE:<%= entry.referenced_size %>@<%= offset %>
<%= url %>
<%
   offset += entry.referenced_size
  }
%>
#EXT-X-ENDLIST
```

**Comment by DerouineauNicolas** [comment]
Hi,
I'm currently implementing this feature in gpac. You can checkout the branch here:

https://github.com/DerouineauNicolas/gpac/tree/m3u8_mpd_rext

So far, expected use is the following:

MP4Box -dash 1000 $OUT_DIR/file.mp4#video $OUT_DIR/file.mp4#audio -m3u8-from-mpd $OUT_DIR/hls.m3u8 -segment-name test-\$RepresentationID\$-\$Number%d\$ -out $OUT_DIR/file.mpd

Feedbacks are welcome.

**Comment by gokerwin** [comment]
@DerouineauNicolas  I have tried your m3u8_mpd_rext version, but the fragment's duration doesn't look very accurate,  every fragment's duration is same。
```
#EXTM3U
#EXT-X-TARGETDURATION:309
#EXT-X-VERSION:
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MAP:URI="test-569JNRXZghiklms%d$init.mp4"

#EXTINF:3.000000
test-569JNRXZghiklms%d$1.m4s
#EXTINF:3.000000
test-569JNRXZghiklms%d$2.m4s
#EXTINF:3.000000
test-569JNRXZghiklms%d$3.m4s
#EXTINF:3.000000
test-569JNRXZghiklms%d$4.m4s
#EXTINF:3.000000
test-569JNRXZghiklms%d$5.m4s
#EXTINF:3.000000
test-569JNRXZghiklms%d$6.m4s
#EXTINF:3.000000
test-569JNRXZghiklms%d$7.m4s
#EXTINF:3.000000
test-569JNRXZghiklms%d$8.m4s
#EXTINF:3.000000
test-569JNRXZghiklms%d$9.m4s
#EXTINF:3.000000
 @test-569JNRXZghiklms%d$10.m4s
```

**Comment by DerouineauNicolas** [comment]
@gokerwin I have pushed commit 49c1170677b0c795681a548610fef00304dd6eb0 which is fixing this issue. Can you try it and tell me if it works on your side ?

**Comment by RostorX** [comment]
@DerouineauNicolas do you have a compiled windows 0.7.2 dev to download so I can test too ?

**Comment by DerouineauNicolas** [comment]
@RostorX I have to merge some stuff from another branch to fix compilation on windows, I'll let you know when it's ready.

**Comment by DerouineauNicolas** [comment]
@RostorX Here is a windows version of the m3u8_rext version (http://the.ndero.ovh/gpac_build/gpac-0.7.2-DEV-latest-buildbot-m3u8rext-x64.exe). Please note that it was generated with our continuous integration tool, so I didn't test it on windows.

**Comment by rybi** [comment]
@DerouineauNicolas is there a compiled mac version to test it? Thanks!

**Comment by RostorX** [comment]
@DerouineauNicolas  thanks Nicolas for the windows build, but due to the fact that I use these parameters: MP4Box -dash-strict 4000 -rap -bs-switching no -profile dashavc264:onDemand for creating the MPD the M3U8 doesn't work all the segments seems empty:
#EXTM3U
#EXT-X-TARGETDURATION:14
#EXT-X-VERSION:
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-INDEPENDENT-SEGMENTS

**Comment by DerouineauNicolas** [comment]
@RostorX I have made some commits to fix bugs and try to fix your issue. Could you try the updated installers here (http://the.ndero.ovh/gpac_build/) ? Please note that the branch is called buildbot-m3u8rext.

So far, the branch is tested two ways:

MP4Box -noprog -for-test -dash 1000 ./results/temp/file.mp4#video ./results/temp/file.mp4#audio -m3u8-from-mpd ./results/temp/hls.m3u8 -segment-name test-$RepresentationID$-$Number%d$ -out ./results/temp/file.mpd

MP4Box -noprog -for-test -dash-strict 1000 -rap -bs-switching no -profile dashavc264:onDemand ./results/temp/file.mp4#video ./results/temp/file.mp4#audio -m3u8-from-mpd ./results/temp/hls.m3u8 -out ./results/temp/file.mpd

The dashavc264:onDemand profile is storing segments in a single file. So I printed the bytes offset, length and duration in the m3u8. This is still highly experimental, I'll be happy to get feedback.

**Comment by DerouineauNicolas** [comment]
@rybi A compiled mac version is available in the above mentioned directory (not tested).

**Comment by dustinkerstein** [comment]
I'd love to give this a test. Are there any recent builds available? It seems as though the gpac_build url no longer has any contents.

**Comment by Themrdop** [comment]
Is this functionality integrated in some way in the main branch?

**Comment by rroller** [comment]
Any hopes of getting this into mainline?

**Comment by jeanlf** [comment]
HLS generation was added to GPAC 0.9.0, I need to add a wiki entry on that - meanwhile you can check [this test](https://github.com/gpac/gpac/blob/filters/tests/scripts/hls-gen.sh)

**Comment by Almeonamy** [comment]
@jeanlf 
Test's link leads to 404.
And I can't find the wiki or other document about generation "mpd to m3u8".

**Comment by aureliendavid** [comment]
> Test's link leads to 404.
> And I can't find the wiki or other document about generation "mpd to m3u8".
> And where can we find the version 0.9.0?

here's an updated link to the test: https://github.com/gpac/testsuite/blob/filters/scripts/hls-gen.sh

the 0.9.0 version corresponds to the `filters` branch on github, you can build it or find binaries here: https://gpac.wp.imt.fr/downloads/gpac-filters-branch/

**Comment by Almeonamy** [comment]
The generated m3u8 contains this string:
`#EXT-X-MAP:BYTERANGE="912@0"`
The string doesn't contain URI.
The hls.js can't parse it and tries to load resource from "null" uri.

**Comment by jeanlf** [comment]
indeed, should now be fixed

**Comment by mnAdroid** [comment]
@jeanlf Could you give me sth like a tutorial how to use it?
I installed the latest version from here: https://gpac.wp.imt.fr/downloads/gpac-filters-branch/
tried: `MP4Box -dash 4000 out_audio.mp4#audio -m3u8-from-mpd hls.m3u8 -out file.mpd` and get 
> Option -m3u8-from-mpd unknown, please check usage.

**Comment by docjojo** [comment]
same here: Option -m3u8-from-mpd unknown. Please check usage

**Comment by DerouineauNicolas** [comment]
-m3u8-from-mpd argument was used only in my GPAC branch. If you look at the test on main branch (https://github.com/gpac/testsuite/blob/filters/scripts/hls-gen.sh), you need to use the option -out file.m3u8:dual.

**Comment by docjojo** [comment]
Thank you for your quick response.
If I use:
mp4box -dash 2000 -rap -bs-switching no -profile vod -out file.m3u8:dual audio.mp4 360p.mp4 720p.mp4
I only get file.mpd - where is the .m3u8 file?
What am I doing wrong?

**Comment by jeanlf** [comment]
`vod` is not a known profile. 
With latest git:
```
% MP4Box -dash 1000 -rap -bs-switching no -profile onDemand -out temp/live.m3u8:dual src.mp4
% ls temp
live.m3u8		live.mpd		live_1.m3u8		src_dashinit.mp4
```
 
This works as well with other profiles, or with using `-out temp/live.mpd:dual`

**Comment by docjojo** [comment]
Thank you jeanlf.

MP4Box - GPAC version 0.8.0-revrelease
This is the latest version - no?

Your command results in:
MP4Box -dash 1000 -rap -bs-switching no -profile onDemand -out live.m3u8:dual bostalsee.mp4
DASH-ing file - single segment
Subsegment duration 1.000 - Fragment duration: 1.000 secs
Spliting segments at GOP boundaries
DASHing file bostalsee.mp4
[DASH] Generating MPD at time 2020-04-30T08:56:21.627Z  

bostalsee.mp4, bostalsee_dashinit.mp4, live.mpd

No .m3u8 file.
What's wrong?
Regards, Chris

**Comment by jeanlf** [comment]
no, 0.8.0 is not the latest version, you must use 0.9.0 (filters branch) for this feature

**Comment by docjojo** [comment]
Thank you. 
I have MP4Box - GPAC version 0.9.0-DEV-rev79-g1e681607-filters running now.
Your command works. 
live.mpd, live.m3u8 and live_1.m3u8
Great.
Both source work with videojs player.

However 
-seeking with .m3u8 source will stall the player.
-seeking with .mpd source will stall the player and throw error: 
TypeError: lastMatchedSample is undefined

Any advice you have for me?
I was hoping to use a single video file as the source for both HLS and DASH.
Is the video.ts format a problem for mp4box or any other setting required?
