### ISSUE TITLE
mpeg-dash playback on safari

### ISSUE THREAD

**Issue by evangeline123** [gpac/gpac#775]
I have used mp4box to create my dash video and mpd maniferst. I can play the videos on android and all browsers, but not on safari (10+). is there anyway to make this manifest playable on safari? or is there a way to convert mpd to m3u8?

demo:

http://79.175.133.185/static/videos/bighero2000/index.html

**Comment by blacktrash** [comment]
Plays fine here in Safari 10.0.3 on Mac OS 10.12.3.
But imho Safari's MediaSource implementation is still highly problematic: https://github.com/Dash-Industry-Forum/dash.js/search?q=Safari&type=Issues&utf8=%E2%9C%93
