### ISSUE TITLE
MPEG-DASH m4v + m4a = mp4

### ISSUE THREAD

**Issue by Modern888** [gpac/gpac#778]
There is an Instagram cache (MPEG-DASH).
Files init.m4v, init.m4a (moov); segmentXXX.m4v, segmentXXX.m4a (moof mdat).
Files are not opened by media players (VLC).

How can I assemble these files into one MP4 file?

**Comment by jeanlf** [comment]
physical concatenation of init.m4v+segmentXXX.m4v, and init.m4a+segmentXXX.m4a, then merge the two files using MP4Box:
`MP4Box -add video.m4v -add audio.m4v -new av.mp4`

**Comment by Modern888** [comment]
How to physical concatenation of init.m4v+segmentXXX.m4v, and init.m4a+segmentXXX.m4a ?
What utilities to use?

**Comment by rbouqueau** [comment]
'cat' on unix, 'type' on windows. Same syntax: ```cat init.m4v segmentXXX.m4v > file.m4v```

**Comment by Modern888** [comment]
![12312](https://cloud.githubusercontent.com/assets/26431470/23947025/e6299062-098d-11e7-8efd-c3653f7ea38c.jpg)

**Comment by rbouqueau** [comment]
Read the previous message again. Remove MP4Box from your command-line and since you are on windows: ```type init.m4v segmentXXX.m4v > file.m4v```

**Comment by Modern888** [comment]
Thanks, all worked well!

**Comment by mohammadyacn314** [comment]
@jeanlf 
`MP4Box -add video.m4v -add audio.m4v -new av.mp4`

audio.m4v  or audio.m4a ??

i have lots of  2 kind . m4v and m4a ! i should merge them to pack.(mp4 or ...) then merge all the packs to single file . mp4 or flv or mkv . just play in media player .
..............................................................................................................
0.m4v + 0.m4a =  0.mp4
1.m4v + 1.m4a = 1.mp4
2.m4v + 2.m4a = 2.mp4
.
.
.

0.mp4 + 1.mp4 + 2.mp4 + ... = singlefile.mp4

..............................................................................................................

i wanna use your method . bcoz mine make video low quality and green screen overlay.

mine : copy \B 0.m4a + 0.m4v     0.mp4
