### ISSUE TITLE
'lmsg' written as brand to last segment

### ISSUE THREAD

**Issue by richardbushell** [gpac/gpac#78]
Is it possible for MP4Box to write 'lmsg' as the brand to last segment in a stream whilst DASHing? (as required by DASH Conformance).

**Comment by jeanlf** [comment]
Not sure what you want, this is already written in the last segment. It is not written when using the live mode / -dynamic as we don't know which is the last segment. Is this what you meant ?

**Comment by richardbushell** [comment]
Yes, we are using a LIVE profile (which is of course fine for On-Demand too), as many prefer or require this segmented file output for their CDNs.

 

Perhaps you can allow this (if taking a fixed file input), or simply add a flag option on the command line to set this if desired?

 

The DASH Validator is not happy with this non-conformance.


Kind regards

Richard

 

  _____  

 


Richard Bushell
Managing Director
Living.TV

Freephone
Freefax

0800 377 77 25
0800 098 88 76

Email
Web

 <mailto:rb@living.tv> rb@living.tv
 <http://www.living.tv> www.living.tv 

 

  _____  


  _____  


	

 <http://www.living.tv/> 

		

Living.TV produce stunning corporate videos to utilise on your website, email and other marketing. Then, our 100,000 streaming servers provide the highest quality video-streaming on the planet. Viewers enjoy glorious high-definition playback of your video, without buffering. View examples at   <http://www.living.tv/> www.living.tv

	
	

  _____  

  _____  


 <http://living.tv/video> 

 <http://living.tv/livingtvmediapack> 

 <http://facebook.com/livingtv1>    <http://twitter.com/livingtv1>    <http://linkedin.com/company/living.tv>    <http://google.com/+livingtv1> 

Watch our Video,
Read our Media Pack,
and Please Follow Us...

**Comment by richardbushell** [comment]
I refer to STATIC type MPDs using SEGMENT TEMPLATE under a LIVE profile. Should these have 'lmsg'? Validator complains that they should be present as brand in last segment.
