### ISSUE TITLE
NHML encoding is not honoring last element's duration attribute

### ISSUE THREAD

**Issue by avibrazil** [gpac/gpac#783]
Take the [attached NHML](https://github.com/gpac/gpac/files/854590/example.nhml.txt), it has a duration attribute on the last JPEG sample. With or without this last duration attribute, two players that I tested (VLC and Mac native player) show an inconsistent ending for the resulting media. VLC ignores it and stop playing. The Mac native player plays the last sample for a random number of minutes (around 5 minutes, and not 3 seconds as defined in my NHML).

I guess MP4Box is simply ignoring the duration attribute, leading to unpredictable results in players. They can not know for how long to show a JPEG file. My guess comes from the fact that if I reverse engineer the resulting media file and extract an NHML for that track, it comes with no duration attribute, somehow incompatible with the original NHML file I used.

Encoding:

MP4Box audio.m4a -add bug_attached_file.nhml

Extracting:

MP4Box -nhml 2 audio.m4a

So please make sure the duration attribute is honored when encoding NHML tracks.

Thank you in advance

**Comment by jeanlf** [comment]
I think this was fixed some time ago, the current revision does take the duration into account. Could you re-check and re-open if needed ?
