### ISSUE TITLE
mp4box udp stream to dash with AR manipulation not working

### ISSUE THREAD

**Issue by salvaaod** [gpac/gpac#789]
Hi, I am trying to get mp4box to take a udp ts stream and create a dash file and change its aspect ratio.

I am using the following command:
MP4Box -grab-ts udp://127.0.0.1:1234 -par "68=16:11"  -dash-live 20000 file.ts  -mpd-refresh 10000

The only thing that this command does is dumping the stream to a file.ts, no dash is created or aspect ratio is modified.

Is Mp4box -grab-ts command supposed to work to manipulate aspect ratio of the incoming stream and create a live dash file or is there something wrong somewhere?

Thanks.

**Comment by rbouqueau** [comment]
That's not how it works. The 'grab-ts', 'par', and 'dash' options follow different paths in the library. There is room for improvement when parsing the arguments.

The right option is to use dashcast or dashcastx (and modify them when you need to fix your PAR).
