### ISSUE TITLE
MP4Box - create both MPD and M3U8

### ISSUE THREAD

**Issue by philhar** [gpac/gpac#790]
Now that Apple support fMP4 streaming, is it possible to configure MP4Box to create MP4 segments referenced by both an MPD and M3u8 Manifest?

**Comment by RostorX** [comment]
I'm also interested to know if it's possible to do that in just one pass.
Thanks :)

**Comment by ivan1986** [comment]
And DASH with TS also
https://www.slideshare.net/agiladi/alex-giladi-dashtsr3

**Comment by jeanlf** [comment]
This is now supported in GPAC 0.9.0 DEV, see [this test](https://github.com/gpac/gpac/blob/filters/tests/scripts/hls-gen.sh)
