### ISSUE TITLE
MP4Box -dash can not create mpd?段错误 (核心已转储)

### ISSUE THREAD

**Issue by jf1321261366** [gpac/gpac#791]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

Hello! When I input MP4Box -dash  10000 -frag 10000  -rap  -frag-rap test_result/test1.mp4, it will recur "段错误 (核心已转储)", who can help me solve this problem?Thank you.

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by jeanlf** [comment]
works fine here, could you upload your test file ?

**Comment by jf1321261366** [comment]
Thank you, very much! I change the test video,then I can get the mpd, I find if the test mp4 video can not be very long ! I want to konw how to compile gpac on the windows10.
![Uploading QQ截图20170406175613.jpg…]()

**Comment by jf1321261366** [comment]
it does not work!
MP4Box -add file.mkv new_file.mp4
MP4Box -add file.flv new_file.mp4
MP4Box -add file.wmv new_file.mp4
and so on


it works!
MP4Box -add file.avi new_file.mp4
MP4Box -add file.mpg new_file.mp4

why?

**Comment by jf1321261366** [comment]
it does not work!
MP4Box -add file.mkv new_file.mp4
MP4Box -add file.flv new_file.mp4
MP4Box -add file.wmv new_file.mp4
and so on

it works!
MP4Box -add file.avi new_file.mp4
MP4Box -add file.mpg new_file.mp4

why?
