### ISSUE TITLE
Is it possible to stream 'cenc' protected content in RTP with (or without) using hint track

### ISSUE THREAD

**Issue by Angelus75** [gpac/gpac#792]
Hi,

Not sure it is the good place for this question since it is more a question than an issue but I didn't find better place.
I wonder if it is possible to use MP4Box rtp in order to stream ISOBMFF content protected with common encryption, and in this case, how content protection information is transmitted.

Thanks.

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x ] I looked for a similar issue and couldn't find any.
- [x ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
Unfortunately this is not possible, since there is currently no defined RTP payload formats for the carriage of CENC protected content.
