### ISSUE TITLE
[iso file] Unknown box type COVR

### ISSUE THREAD

**Issue by jf1321261366** [gpac/gpac#793]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

MP4Box -info test.mp4

issues:
[iso file] Unknown box type COVR
[isom] not enough bytes in box ilst: 8 left, reading 111
[iso file] Read Box "ilst" failed (Invalid IsoMedia File) - skipping
*** Error in `MP4Box': double free or corruption (fasttop): 0x000000000174ff50 ***
已放弃 (核心已转储)

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by rbouqueau** [comment]
Thanks for reporting. Despite you checked the box, we don't have enough information to reproduce. Could you please share a sample? We have an anonymous dropbox if it can help: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by jeanlf** [comment]
I believe this was fixed some time ago, reopen if needed
