### ISSUE TITLE
no video in the dash reault file of MPEG-4 Visual format

### ISSUE THREAD

**Issue by evangeline123** [gpac/gpac#794]
I am using MP4Box to create dash video from some videos. when the source video codec is in h264, the final result is fine is playback and has video and audio, but when the source codec is in a different format, like MPEG-4 Visual, the final dash file has no video. 

here is my code for mp4box:

`MP4Box -dash 4000 -rap -segment-name %s_ -bs-switching merge -out manifest.mpd merge1.mp4#video merge1.mp4#audio` 

and this is the output of mediainfo command for the source video with codec h264:
 
`Complete name                            : 1_low.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom
File size                                : 24.4 MiB
Duration                                 : 8mn 47s
Overall bit rate                         : 388 Kbps
Writing application                      : Lavf57.63.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Baseline@L3.0
Format settings, CABAC                   : No
Format settings, ReFrames                : 1 frame
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 8mn 47s
Bit rate                                 : 320 Kbps
Width                                    : 450 pixels
Height                                   : 360 pixels
Display aspect ratio                     : 5:4
Frame rate mode                          : Constant
Frame rate                               : 25.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.079
Stream size                              : 20.1 MiB (82%)
Writing library                          : x264 core 148 r2643 5c65704
Encoding settings                        : cabac=0 / ref=1 / deblock=1:1:1 / analyse=0x1:0x131 / me=umh / subme=9 / psy=1 / psy_rd=0.40:0.00 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=11 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=0 / weightp=0 / keyint=300 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=2pass / mbtree=1 / bitrate=320 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=320 / vbv_bufsize=2048 / nal_hrd=none / filler=0 / ip_ratio=1.41 / aq=1:0.60

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 8mn 47s
Bit rate mode                            : Constant
Bit rate                                 : 64.0 Kbps
Channel count                            : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Stream size                              : 4.03 MiB (17%)
`

and here is the output for the different format:

`Complete name                            : 1.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom
File size                                : 134 MiB
Duration                                 : 8mn 47s
Overall bit rate                         : 2 129 Kbps
Writing application                      : Lavf53.32.100

Video
ID                                       : 1
Format                                   : MPEG-4 Visual
Format profile                           : Simple@L1
Format settings, BVOP                    : No
Format settings, QPel                    : No
Format settings, GMC                     : No warppoints
Format settings, Matrix                  : Default (H.263)
Codec ID                                 : 20
Duration                                 : 8mn 47s
Bit rate mode                            : Constant
Bit rate                                 : 1 996 Kbps
Width                                    : 720 pixels
Height                                   : 576 pixels
Display aspect ratio                     : 5:4
Frame rate mode                          : Constant
Frame rate                               : 25.000 fps
Standard                                 : PAL
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.193
Stream size                              : 126 MiB (94%)
Writing library                          : Lavc53.61.100

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 8mn 47s
Duration_LastFrame                       : -11ms
Bit rate mode                            : Constant
Bit rate                                 : 128 Kbps
Channel count                            : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Stream size                              : 8.05 MiB (6%)
`
how can I fix this>

demo for the MPEG-4 Visual format video:

https://streamable.com/gm3i0

and demo for the video with h264 codec:

https://streamable.com/j1xu7

**Comment by jeanlf** [comment]
Dashing with MPEG-4 part 2 works fine here. I suppose the issue comes from your "merge" files, you shouldn't have more than one video track in the dash inputs when using #video or #audio selectors.
