### ISSUE TITLE
Urgent** problem with dash delay and very short segment size

### ISSUE THREAD

**Issue by evangeline123** [gpac/gpac#795]
I have created my mp4 dash with mp4box and I  set the duration to 4000. now when i start to play the output format, the delay is alot when I seek in the video and it seems like it is downloading all the segments and the segment duration does'nt seem to be 4000! the size of segments are very small

here is my mp4box comamnd:

MP4Box -dash 4000 -rap -segment-name %s_ -bs-switching no -out manifest.mpd merge1.mp4#video merge2.mp4#video merge1.mp4#audio merge2.mp4#audio

and output:

http://79.175.133.185/static/videos/ToCheckIfBacktoryWorks5/index.html

the source video mediainfo:

General
Complete name                            : 1_low.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom
File size                                : 190 MiB
Duration                                 : 1h 8mn
Overall bit rate                         : 386 Kbps
Writing application                      : Lavf57.52.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Baseline@L3.0
Format settings, CABAC                   : No
Format settings, ReFrames                : 1 frame
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 1h 8mn
Bit rate                                 : 320 Kbps
Width                                    : 640 pixels
Height                                   : 360 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.056
Stream size                              : 156 MiB (82%)
Writing library                          : x264 core 148 r2643 5c65704
Encoding settings                        : cabac=0 / ref=1 / deblock=1:1:1 / analyse=0x1:0x131 / me=umh / subme=9 / psy=1 / psy_rd=0.40:0.00 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=11 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=0 / weightp=0 / keyint=300 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=2pass / mbtree=1 / bitrate=320 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=320 / vbv_bufsize=2048 / nal_hrd=none / filler=0 / ip_ratio=1.41 / aq=1:0.60
Language                                 : English

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 1h 8mn
Bit rate mode                            : Constant
Bit rate                                 : 64.0 Kbps
Channel count                            : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Stream size                              : 31.5 MiB (17%)
Language                                 : English

this is so urgent, I would realy appreciate any help. check the segments behaviour with developer tool and network tab. why is it acting like this?? it acts normal for a few seconds and when I seek the video forward, it suddenly starts to send many requests for other segments.

**Comment by rbouqueau** [comment]
> I have created my mp4 dash with mp4box and I set the duration to 4000. now when i start to play the output format, the delay is alot when I seek in the video and it seems like it is downloading all the segments and the segment duration does'nt seem to be 4000!

With the GPAC player (MP4Client), it is almost instantaneous. Please contact the provider of your player.
