### ISSUE TITLE
problem demuxing pcm

### ISSUE THREAD

**Issue by stax76** [gpac/gpac#796]
log file and sample source file: https://forum.doom9.org/showthread.php?p=1803342&highlight=staxrip#post1803342

**Comment by rbouqueau** [comment]
Thanks for the sample. Much appreciated :)

Duplicate of #732 . Closing.

**Comment by stax76** [comment]
Sorry, I didn't remember having reported the same thing before, I though it was a bug instead of a unsupported feature.

I check the output now and if it isn't a proper audio file I call the ffmpeg demuxing function instead.

**Comment by rbouqueau** [comment]
No problem. I left it open with the hope to have a look to your samples. Thanks
