### ISSUE TITLE
audio and video playback is not sync in mpeg-dash output

### ISSUE THREAD

**Issue by evangeline123** [gpac/gpac#797]
I used this command to create my dash video files:

MP4Box -dash 4000 -rap -segment-name %s_ -bs-switching no -out manifest.mpd 1_low#video 1_med#video 1_high.mp4#video 1_low.mp4#audio 1_med.mp4#audio 1_high.mp4#audio

when I try to play it on android ExoPlayer, after seeking the video forward, the audio starts to play but the video freezes for about a few seconds and then it starts playing. 

here is my video's manifest link to play on exo player:
http://94.182.180.36:9004/behseema/OlumTarbiati_Ravanshenasi/Ravanshenasi/RaveshhayeEslah_TaghireRaftar/AghaJani/1/dash_1/manifest.mpd

is there anyway to sync audio and video?? so they start to play at the same time?!

**Comment by jeanlf** [comment]
content plays back fine with MP4Client and dash-js, although there seems to be some audio recording issues at the begining of the stream after the logo. Likely an ExoPlayer issue, please check with them.

**Comment by evangeline123** [comment]
I searched a little about this issue and saw that some other users have had this problem with exoplayer. could this be related to using one stream for audio and video??
