### ISSUE TITLE
Dashing and the video length

### ISSUE THREAD

**Issue by evangeline123** [gpac/gpac#798]
I have tried this command to make dash output and I used it on a 10 minutes videos and a 70 minutes video. the first one plays very well and has a very low delay when I play it on videoJS and ExoPlayer. but when I use the same command for a longer video, It has some problem in playing and the seek delay is much more than the first one.

MP4Box -dash 4000 -rap -segment-name %s_ -bs-switching no  -out Dash/manifest.mpd low.mp4#video med.mp4#video high.mp4#video low.mp4#audio med.mp4#audio high.mp4#audio

here is the video info using mediainfo:

for 70 minutes video:

Complete name                            : High.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 535 MiB
Duration                                 : 1h 8mn
Overall bit rate                         : 1 086 Kbps
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 1904-01-01 00:00:00
Writing application                      : Lavf56.40.101

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L5
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 16 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 1h 8mn
Bit rate                                 : 952 Kbps
Nominal bit rate                         : 1 024 Kbps
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.041
Stream size                              : 469 MiB (88%)
Writing library                          : x264 core 148 r2643 5c65704
Encoding settings                        : cabac=1 / ref=16 / deblock=1:1:1 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=10 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=100 / keyint_min=25 / scenecut=42 / intra_refresh=0 / rc_lookahead=60 / rc=cbr / mbtree=1 / bitrate=1024 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=1024 / vbv_bufsize=2000 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
Language                                 : English
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 1904-01-01 00:00:00

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 1h 8mn
Duration_LastFrame                       : 43ms
Bit rate mode                            : Constant
Bit rate                                 : 128 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Frame rate                               : 46.875 fps (1024 spf)
Compression mode                         : Lossy
Stream size                              : 63.0 MiB (12%)
Language                                 : English
Default                                  : Yes
Alternate group                          : 1
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 1904-01-01 00:00:00

and the 10 minutes  video:

Complete name                            : high.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 188 MiB
Duration                                 : 11mn 1s
Overall bit rate                         : 2 384 Kbps
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 1904-01-01 00:00:00
Writing application                      : Lavf56.40.101

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.2
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 11mn 1s
Bit rate                                 : 2 000 Kbps
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 50.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.043
Stream size                              : 157 MiB (83%)
Writing library                          : x264 core 148 r2643 5c65704
Encoding settings                        : cabac=1 / ref=3 / deblock=1:1:1 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=10 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=100 / keyint_min=25 / scenecut=42 / intra_refresh=0 / rc_lookahead=40 / rc=cbr / mbtree=1 / bitrate=2000 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=2000 / vbv_bufsize=4000 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
Language                                 : English
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 1904-01-01 00:00:00

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 11mn 1s
Bit rate mode                            : Constant
Bit rate                                 : 384 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Frame rate                               : 46.875 fps (1024 spf)
Compression mode                         : Lossy
Stream size                              : 30.3 MiB (16%)
Language                                 : English
Default                                  : Yes
Alternate group                          : 1
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 1904-01-01 00:00:00

could anyone explain to me why this is happening and how to fix it? 
does dash playback really depends on video length??

**Comment by rbouqueau** [comment]
Your encoding is not ok, see ```keyint=100 / keyint_min=25 / scenecut=42```. Please check http://gpac.io/2015/11/02/check-key-frame-alignment-with-mp4box/

By the way I noticed that you opened 12 issues in 6 weeks. That's a lot. Issues help either you or us, and these 12 issues helped yourself only. I know it is not easy to start in a new domain but I would appreciate if you could use the community help more wisely. Thanks.

**Comment by evangeline123** [comment]
I am a beginner in encoding and multimedia.I'm sorry if I have opened to many topics, I will try to ask wisely from now on.
So the problem is my keyint and scenecut?? I have a deadline to fix this problem and I have tried any possible option. But could not solve it. Could you please explain more? I would really appreciate it

**Comment by rbouqueau** [comment]
You can take some inspiration from:
 - https://blog.streamroot.io/encode-multi-bitrate-videos-mpeg-dash-mse-based-media-players/
 - or http://www.gpac-licensing.com/2014/11/03/bitmovin-leverage-mp4box-package-contents-bitdash-player/
