### ISSUE TITLE
setting min-keyint and keyint

### ISSUE THREAD

**Issue by mar02500** [gpac/gpac#800]
I have two videos that I encoded them with ffmpeg, like:

ffmpeg -i 1_video.mp4 -c:v libx264 -x264opts 'keyint=100:min-keyint=25:no-scenecut' -b:v 2048k -maxrate 2048k -bufsize 4000k -acodec copy  mixed-refs 1  -flags +loop -coder 1 -mbtree 1 -preset medium video2.mp4

ffmpeg -i 1_video.mp4 -c:v libx264 -x264opts 'keyint=100:min-keyint=25:no-scenecut' -b:v 1048k -maxrate 1048k -bufsize 2000k -acodec copy  mixed-refs 1  -flags +loop -coder 1 -mbtree 1 -preset medium video3.mp4

MP4Box -dash 4000 -rap -segment-name %s_ -bs-switching no  -out Dash/mnfst.mpd video1.mp4#video video2.mp4#video  video2.mp4#audio video2.mp4#audio 

according to mp4box tutorials that I have read about making mpeg-dash, I know that I have to set keyint and minkey int equal and also related to segment duration. so I tries using min-keyint=100, but the result video had the min-keyint=51 

so I returned to 25. because the FPS is 25 also.

the first issue is about this, because when I played the dash file, and seek the video forward, it loads the frame and freezes for about 1 or 2 seconds and then starts to play. is this issue related to NOT setting these 2 flags equal??

**Comment by rbouqueau** [comment]
Please read https://blog.streamroot.io/encode-multi-bitrate-videos-mpeg-dash-mse-based-media-players/ and check your result with http://gpac.io/2015/11/02/check-key-frame-alignment-with-mp4box/. Note that if you have issues with FFmpeg encoding parameters, the FFmpeg bug reporter is probably a better place than here.
