### ISSUE TITLE
HEVC muxing totally broken with 0.7.0

### ISSUE THREAD

**Issue by Selur** [gpac/gpac#801]
using: MP4Box - GPAC version 0.7.0-rev1-g544b69041-ab-suite
any hevc raw file I throw at it:

> G:\Hybrid>MP4Box -par 1=1:1 -add "H:\Output\15_42_59_6410_01.265"#video:fps=25 -brand hvc1 -itags tool="Hybrid 2017.04.17.1" -tmp "H:\Output" -new "H:\Output\15_42_59_6410__02.mp4"
[32mHEVC import - frame size 640 x 352 at 25.000 FPS
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[0m[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[0m[33mError parsing slice header: byte_align not found at end of header !
[0m[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[0m[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[0m[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[0m[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[0m[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[0m[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[0m[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[0m[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[0m[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[0m[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[0m[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[0m[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[0m[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[0m[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[0m[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[0m[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[0m[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[33mError parsing slice header: byte_align not found at end of header !
[0m[33mError parsing slice header: byte_align not found at end of header !
[32mHEVC Import results: 429 samples (433 NALUs) - Slices: 3 I 140 P 286 B - 1 SEI - 3 IDR
[0m[32mStream uses forward prediction - stream CTS offset: 2 frames
[0mSaving H:\Output\15_42_59_6410__02.mp4: 0.500 secs Interleaving

older versions work fine.

the .265 file was created using:
`ffmpeg -y -loglevel fatal -threads 8 -i "F:\TestClips&Co\test.avi" -map 0:0 -an -sn  -vsync 0 -pix_fmt yuv420p  -f yuv4mpegpipe - | x265 --input - --y4m --limit-modes --no-open-gop --crf 18.00 --cbqpoffs -2 --crqpoffs -2 --psy-rd 2.50 --rdoq-level 2 --psy-rdoq 10.00 --aq-mode 0 --deblock=-1:-1 --limit-sao --range limited --colormatrix bt470bg --output "H:\Output\15_42_59_6410_01.265"`

**Comment by jeanlf** [comment]
could you check with latest git ? I have found the same issue with some other test streams and just fixed it, let us know if that fixes your stream as well

**Comment by Selur** [comment]
just build:
`MP4Box - GPAC version 0.7.0-rev2-g62da06f89-ab-suite`
and it doesn't show the 'Error parsing slice header: byte_align not found at end of header !' error any more, but the output is still broken.
Muxing the attached hevc file: [18_30_05_3410_01.zip](https://github.com/gpac/gpac/files/930415/18_30_05_3410_01.zip) using:

`MP4Box -par 1=1:1 -add "H:\Output\18_30_05_3410_01.265"#video:fps=25 -brand hvc1 -itags tool="Hybrid 2017.04.17.1" -tmp "H:\Output" -new "H:\Output\18_30_05_3410__02.mp4"`

the resulting file just shows a black picture and ffplay throws a lot of:
> [hevc @ 000002651f3861e0] PPS id out of range: 0
> [hevc @ 000002651f3861e0] Error parsing NAL unit #0.

errors when trying to playback the muxed file.

**Comment by jeanlf** [comment]
There was indeed a bug in PAR rewrite for HEVC, thanks for the report. This should now be fixed.

**Comment by Selur** [comment]
I can confirm that the new version  (MP4Box - GPAC version 0.7.0-rev3-g10dc09ce9-ab-suite) fixes the issue. :D Thanks!
