### ISSUE TITLE
Audio file deletion is not same as video file deletion

### ISSUE THREAD

**Issue by Natarajan92** [gpac/gpac#804]
Hi, 
We are creating MPEG-DASH live streams and testing playback for it's consistency. But after 72hours or so from the start of live stream packaging we are facing playback problem , that's because of 404 for audio segments. 

Please have a look into below description and attached text file.. ! 

The MP4Box command we used to package is below 

> 
mp4box_opts: [
    '-logs', 'all@error', '-log-file', 'mp4box.log', '-dash-ctx', path.join(defaultConfig.outputDir, 'dash-live.txt'),
    '-dash', '4000', '-frag', '4000', '-rap', '-frag-rap', '-ast-offset', '0', 
    '-mpd-refresh', '4', '-bs-switching', 'no', '-min-buffer', '4000', '-url-template', '-time-shift', '60',
    '-mpd-title', 'Evolution MPEG-DASH live stream', '-mpd-info-url', 'http://127.0.0.1:8080/', 
    '-segment-name', 'live_$RepresentationID$_', '-out', path.join(defaultConfig.outputDir, 'live'), 
    '-dynamic', '-subsegs-per-sidx', '-1' 
]
>

On first day of execution, it is keeping 17 segments of audio and video in server and deleting older segments . Same segment numbers also maintained for both audio and video . . 

After 48hours (2Days later), 17 segments of video file is maintained in server but 13files of audio segments is maintained, **It is deleting more audio files** . On what basis the segments are deleted ? Either it is based on number of files or based on segment duration ? 

 Please refer the attached text file. 
[Mp4boxLiveproblem.txt](https://github.com/gpac/gpac/files/934164/Mp4boxLiveproblem.txt)

**As days goes on the number of audio files is getting reduced and while playing we are facing 404 (File Not Found ) for audio segment request** 

Any help regarding this issue ? What we need to do overcome this issue ? 

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by Natarajan92** [comment]
Hi, 

For your clarity on the above issue, am attaching text file with information on dash packaging. In that if you look for > NbSegmentsRemoved of audio and video representations, it will be clear that deletion of audio and video segments are not same
[dash-live.txt](https://github.com/gpac/gpac/files/978144/dash-live.txt)


Thanks,
Natarajan S

**Comment by jeanlf** [comment]
this should now be fixed, please see #885
