### ISSUE TITLE
mov demuxing not working

### ISSUE THREAD

**Issue by stax76** [gpac/gpac#806]
Hi,

selur, a staxrip user and me (three different sample clips) noticed mov demuxing stopped working in recent builds.

Thanks

**Comment by rbouqueau** [comment]
Hi,

Thanks for reporting. Would it be possible to share some files with us? Dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

I have mov files (including the ones with raw audio that you shared with us recently) and saw no problem.

Thanks

**Comment by stax76** [comment]
Hi,

thanks for the support, did you receive the file?

Thanks

**Comment by rbouqueau** [comment]
No I did not... :/ Would you mind sending again?

**Comment by stax76** [comment]
http://www.mediafire.com/file/opb368yo8e4uefw/10_000_BC.mov

**Comment by jeanlf** [comment]
this should now be fixed, thanks for the report

**Comment by stax76** [comment]
Great, thank for the support.
