### ISSUE TITLE
Generating an MPD manifest from a fMP4 w/o generating segments 

### ISSUE THREAD

**Issue by rosipov** [gpac/gpac#808]
I'm running the following command on a fragmented MP4 in an attempt to generate a DASH MPD manifest file that references the input files: 
`MP4Box -dash 1000 -profile dashavc264:onDemand -out food_review.mpd food_review_low.mp4 food_review_med.mp4 food_review_high.mp4`

Instead I am getting three segmentation files ("food_review_low_dashinit.mp4", etc) generated for each input video which the mpd manifest file references. 

Is it possible to use MP4Box in order to generate an MPD file that references the fragmented mp4 videos rather than creating seperate segments? 

- ✅ I looked for a similar issue and couldn't find any.
- ✅ I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- ✅ I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by rbouqueau** [comment]
That's because of this option: ```-profile dashavc264:onDemand```. Replace it with ```-profile dashavc264:live``` to get separate files for segments.

You can also read http://www.gpac-licensing.com/2014/08/21/ibc-2014-dash-avc264-support-in-gpac/

**Comment by cconcolato** [comment]
It is not currently possible to generate an MPD without generating the segments (live or ondemand). What is the problem you're trying to solve? Is it that it is hard to extract manually from the MP4 the information to put into the MPD? Why don't you want MP4Box to generate the segments? Are there features that are lost in the DASHing process? Or is it to save CPU ? One workaround is to DASH the inputs for a short time (using the -subdur option) and then to manually replace the MPD URLs with your input file(s).

**Comment by rosipov** [comment]
Ultimately my goal is to generate a DASH manifest and a HLS playlist that references a single fragmented MP4 or a set of fragmented MP4s with varying bitrates. Having to upload separate segments in addition to the original videos would greatly increase the bandwidth and storage costs from my CDN. 

Being able to generate a DASH manifest that references the fragmented MP4(s) is my obstacle right now.

**Comment by jeanlf** [comment]
you mean your fragmented files are already uploaded somewhere on your CDN ? How can you make sure that they are DASH- or HLS- compliant (brands, compatible flags used in fragments, etc.) ?

**Comment by rosipov** [comment]
No - my source files and fragmented files are stored locally.
Ideally I would like to upload a single set of fragmented MP4's (thus saving bandwidth + storage) which would be referenced by HLS and DASH manifests similar to the approach taken with CMAF.

**Comment by kleijnweb** [comment]
I also need this (using a single fMP4 for HLS, DASH and non-ABR playback), for both performance (caching) and storage space reasons. I haven't found any tool capable of doing this though, is it even possible?

**Comment by jeanlf** [comment]
partial answer: with GPAC 0.9.0, you can publish both DASH and HLS at the same time, see [this test](https://github.com/gpac/gpac/blob/filters/tests/scripts/hls-gen.sh). We still need to investigate how MP4/HLS playlist generation could be done from source fragmented files.

**Comment by jeanlf** [comment]
This is now possible with GPAC 0.9.0 - note however that in order to generate a manifest for dash onDemand profiles, the input must already be compliant to the dash self-initialized media segment (i.e. shall have a correct sidx after the moov). See [this test](https://github.com/gpac/gpac/blob/filters/tests/scripts/dash-genmanifest.sh).

Only ISOBMFF single track single file inputs are supported.

**Comment by ashuvssut** [comment]
the link @jeanlf provided seems broken

Here's the one: https://github.com/gpac/gpac/wiki/dasher#manifest-generation-only-mode
