### ISSUE TITLE
split with interleaving

### ISSUE THREAD

**Issue by tetzank** [gpac/gpac#81]
Is there a way to specify interleaving when splitting a file?

I have a problem that splitted files trigger a bug in Chromium when played back in an HTML5 video-tag. The file is split like that:
`$ MP4Box -splits 250000 file.mp4`

When i remux the splitted files afterwards with:
`$ MP4Box -inter 500 file_001.mp4`
the bug is not triggered.

So, i guess the splitted files are not interleaved in a nice way which is the default in other commands.

Is there a way to do this in one command?

**Comment by jeanlf** [comment]
This is already supported:
`$ MP4Box -splits 250000 -inter 500 file.mp4 `

**Comment by tetzank** [comment]
Mhmm, i still get the bug in Chromium when i use your command. Another:
`$ MP4Box -inter 500 file_001.mp4`
afterwards gets around it.

So, what could be the difference? What is the second command doing to the file?

Is there a way to dump the chunk information or something, so one could see the difference?

**Comment by cconcolato** [comment]
Can you give more details on the bugs in Chromium? Can you share file? 

There are several ways to inspect the chunk information:
- MP4Box -diso file.mp4 will create an XML representation of the file. You can find the chunk information in the stsc and stco boxes (alternatively you can use our [online file analyzer](http://download.tsi.telecom-paristech.fr/gpac/mp4box.js/filereader.html), feedback welcome on how to improve it)
- MP4Box -dts file.mp4 will give you a text file with the size and offset for each sample.

HTH.

**Comment by tetzank** [comment]
Chromium fires many tiny range requests when one jumps into the second half of the video. I haven't filed a bug report yet, as i wanted to understand first what's wrong with the video file.

Here are step-by-step instructions to reproduce with a public video:

get video https://durian.blender.org/download/
`$ wget 'http://mirrorblender.top-ix.org/movies/sintel-1280-surround.mp4'`

split file:
`$ MP4Box -splits 150000 -inter 500 sintel-1280-surround.mp4`

open first part sintel-1280-surround_001.mp4 here in Chromium:
https://tetzank.github.io/videojs-shortcuts/demo_playlist.html

open Console with Ctrl+Shift+j and switch to the Network tab

press play and then jump near the end of the video

In the network tab you'll see many tiny requests. Over the internet this adds too much overhead and delay, so the video can't be played back smoothly.

It can be fixed with:
`$ MP4Box -inter 500 sintel-1280-surround_001.mp4`

**Comment by jeanlf** [comment]
You can also view chunk interleaving info per track as follows:
`MP4Box -info TrackID file.mp4`

**Comment by jeanlf** [comment]
Indeed we were not using the drift-free interleaving in split, now fixed thanks for the report
