### ISSUE TITLE
Unequal duration between audio/video and webvtt causes MP4Box to run forever?

### ISSUE THREAD

**Issue by scycheng314** [gpac/gpac#810]
If I am trying to 'dash' some (short - 20s) audio & video tracks with a (long - 42 minutes) webvtt MP4 file. MP4Box does not every seem to finish. Aborted after 15 minutes or so.

Full test data uploaded to mediafire. OS/X 10.12.4.
```
spencer@Taklamakan:Test$ MP4Box -version
MP4Box - GPAC version 0.7.0-rev4-gb6f0157aa-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: 
Features: GPAC_64_BITS GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG 
```
Execution appears to get stuck at 99/100. I have uploaded my test data and some process capture using Activity Monitor.

```
spencer@Taklamakan:Test$ /usr/local/bin/MP4Box -dash 10000 -lang en-US -frag 1000 -rap -frag-rap -cprt 'Anhui GuangXing Linked-Video Communication Technology Co., Ltd' -subsegs-per-sidx 10  -out segs/Aruba.mpd  -profile full -bs-switching multi -rap -frag-rap  -segment-name %s -url-template  segs/Aruba_h265_1080p.mp4#video  segs/Aruba_h265_720p.mp4#video  segs/Aruba_h265_480p.mp4#video  segs/Aruba_h264_1080p.mp4#video  segs/Aruba_h264_720p.mp4#video segs/Aruba_h264_480p.mp4#video  segs/Aruba_audio_1.m4a#audio segs/Aruba_audio_2.m4a#audio segs/Aruba_audio_3.m4a#audio segs/Aruba_subtitle.vtt.mp4:role=subtitle
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel                            
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel                            
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
[iso file] Unknown box type fiel
^CO File Fragmenting: |=================== | (99/100)       
spencer@Taklamakan:Test$ tar czf bug.tar.gz segs 
```

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X ] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
I can't see you test file anywhere, where is it posted ?

**Comment by scycheng314** [comment]
Re-uploaded to https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by cconcolato** [comment]
The problem should be fixed. It did not come from the duration mismatch (I've added a warning for that). It came from the special handling of subtitle samples (we duplicate the sample when it overlaps a segment boundary). I'm closing the issue. Reopen if there is still a problem.
