### ISSUE TITLE
Access Unit Delimiter is misplaced after h264 elementary setream extraction

### ISSUE THREAD

**Issue by Shevach** [gpac/gpac#812]
i work with the following version of MP4Box:

MP4Box - GPAC version 0.5.1-DEV-rev5290M

The following issue with MP4Box is observed when input mp4-file contains AVC/H.264 video with different SPS (i.e. some SPS in mdat-box differ from that specified in AVCc). 

To reproduce the issue i uploaded a small video excerpt in format m4:
https://app.box.com/s/34170boalfl1eo63mcmll5u5gnn5pat3

The nal layout in the mp4 file is correct and the file itself is compliant:

Nal        aud (9 ), refIdc 0, offset a0, size 2 (dec 2)
Nal        sps (7 ), refIdc 3, offset a6, size 22 (dec 34)
Nal        pps (8 ), refIdc 3, offset cc, size 4 (dec 4)
Nal        sei (6 ), refIdc 0, offset d4, size a (dec 10)
Nal        sei (6 ), refIdc 0, offset e2, size 5a (dec 90)
Nal        sei (6 ), refIdc 0, offset 140, size 7 (dec 7)
Nal        idr (5 ), refIdc 3, offset 14b, size 36 (dec 54)

Nal        aud (9 ), refIdc 0, offset 2c0, size 2 (dec 2)
Nal        sei (6 ), refIdc 0, offset 2c6, size 5a (dec 90)
Nal        sei (6 ), refIdc 0, offset 324, size 7 (dec 7)
Nal      slice (1 ), refIdc 2, offset 32f, size 9 (dec 9)

Nal        aud (9 ), refIdc 0, offset 479, size 2 (dec 2)
Nal        sei (6 ), refIdc 0, offset 47f, size 5a (dec 90)
Nal        sei (6 ), refIdc 0, offset 4dd, size 7 (dec 7)
Nal      slice (1 ), refIdc 0, offset 4e8, size 9 (dec 9)
....

However, upon extraction of h264 elementary stream by the following command:

MP4Box -raw 1 bigbang.mp4 -out es.h264

For the very first video frame the access unit delimiter (AUD) is not the first NAL as required by the standard. The nal layout in the extracted stream:

Frame #0
nal 7 (sps)
nal 8 (pps)
nal 9 (aud)
nal 7 (sps)
nal 8 (pps)
nal 6 (sei)
nal 6 (sei)
nal 6 (sei)
nal 5 (idr)

Frame #1
nal 9 (aud)
nal 6 (sei)
nal 6 (sei)
nal 1 (pb-frame)

...

So, MP4Box misplaces AUD for the first frame, AUD must be the first  NAL.

**Comment by jeanlf** [comment]
this has been fixed in 0.8.0
