### ISSUE TITLE
DASH streaming, stuck at Buffer 49/100 

### ISSUE THREAD

**Issue by divan333** [gpac/gpac#813]
Dear GPAC team,

If I try to play the following DASH stream (please see commandline), mp4client is stuck at 49/100 buffering and never gets to display the first frame. GPAC version is GPAC/0.7.0-rev4-gb6f0157-master, downloaded as nightly Windows 64-bit build.

NOTE: Reducing BufferLength from 3000 to 500 in [Network] gets the first stream below to play a little bit, and then it gets stuck as well. 

File plays back locally (as MP4).

Command line is as follows:

[1] - Single 8 Mbit/s stream: 

mp4client.exe -log-file mp4client.log -logs all@info http://46.4.123.44:8080/DASH/8mbps_multitile/multitile4x4_UHD_8Mbps.mpd

[2] - Two streams, 8 Mbit/s and 3 Mbit/s, with switching: 

mp4client.exe -log-file mp4client.log -logs all@info http://46.4.123.44:8080/DASH/8mbps_3mbps_multitile/multitile4x4_UHD_8Mbps_3Mbps.mpd

Log file is attached (for BufferLength = 3000).

The DASH stream has been also created with the same version of GPAC, command line as follows:

Mux:: MP4Box.exe -v -add stream.hevc:FMT=HEVC:split_tiles -fps 30 -new video1.mp4

DASH:  MP4Box.exe -dash 1000 -rap -frag 1000 -frag-rap -bs-switching inband -url-template -out I:\apache24\htdocs\multitile4x4_UHD_8Mbps_3Mbps.mpd audio.m4a video1.mp4 video2.mp4

Any help is appreciated!

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [YES ] I looked for a similar issue and couldn't find any.
- [YES ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [YES ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
I believe this was fixed for 0.8.0, reopen if needed
