### ISSUE TITLE
Makefile typo

### ISSUE THREAD

**Issue by ocam-ua** [gpac/gpac#815]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

There is a typo in Makefile [at line 115](https://github.com/gpac/gpac/blob/master/Makefile#L115) which prevents DashCast from installing on system.

**Comment by rbouqueau** [comment]
Thanks for reporting, this is now fixed
