### ISSUE TITLE
Error DASHing file: I/O Error

### ISSUE THREAD

**Issue by Natarajan92** [gpac/gpac#818]
Hi, 

With the help of **test-engine-live-tool**, we are doing Mpeg-Dash live stream packaging test. After some time the MP4Box packaging has been stopped by throwing below error

**Error:** 

[0m[32m[DASH] Generating MPD at time 2017-04-30T20:51:10.540Z
[0m[32m[DASH] Current Period Duration: 1.01991e+10
[0mmv: cannot stat ` /test/stream6/live.mpd.tmp': No such file or directory
**[31m[DASH] Error moving file /test/stream6/live.mpd.tmp to  /test/stream6/live.mpd: I/O Error**

[0m[32m[DASH] Current Period Duration: 1.01994e+10
[0mError DASHing file: I/O Error
Error while processing segments: 1
**Error DASHing file: I/O Error**  

How to fix it ? what cause the error to be thrown  ? 
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by Natarajan92** [comment]
HI, 

Do we got any update for the following error 

**[0m[32m[DASH] Generating MPD at time 2017-04-30T20:51:10.540Z
[0m[32m[DASH] Current Period Duration: 1.01991e+10
[0mmv: cannot stat ` /test/stream6/live.mpd.tmp': No such file or directory
[31m[DASH] Error moving file /test/stream6/live.mpd.tmp to /test/stream6/live.mpd: I/O Error**

**Comment by atwleung** [comment]
I see this issue intermittently on my raspberry pi

**Comment by Natarajan92** [comment]
But we are facing the issue on Server that has 250 GB RAM. So do you think it related to low memory ?

**Comment by atwleung** [comment]
Not sure, I am also trying the -tmp flag to see if I can get around this: https://sourceforge.net/p/gpac/bugs/309/

**Comment by atwleung** [comment]
I also saw this error on my Mac. My Mac was running low in disk usage:

df -h
Filesystem      Size   Used  Avail Capacity  iused   ifree %iused  Mounted on
/dev/disk1     233Gi  220Gi   12Gi    95% 57716172 3236402   95%   /
devfs          337Ki  337Ki    0Bi   100%     1166       0  100%   /dev
map -hosts       0Bi    0Bi    0Bi   100%        0       0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%        0       0  100%   /home

After I free up more disk space, PLUS the -tmp flag, my test-engine-live-encoder can now run over 45 minutes without crashing.

Kindly see if this helps.

**Comment by atwleung** [comment]
I think the -tmp is really the key to avoid this.

As long as I modify test-engine-live-tool's config.js 
var defaultPackaging = {
  mp4box_opts: [
...
    '-tmp', '/tmp/'
  ]
}

and make sure I have the '-tmp', '/tmp/', then I can run test-engine-live-tool for hours without seeing the error:
[DASH] Error moving file /opt/local/apache2/htdocs/dash_output_dir/live.mpd.tmp to /opt/local/apache2/htdocs/dash_output_dir/live.mpd: I/O Error

As long as  '-tmp', '/tmp/', line is absent, my test-engine-live-tool would report the error after around 20 minutes of running.

**Comment by Natarajan92** [comment]
@atwleung 
 For us the issue arises after 6-days and we are also using -tmp param in configuration file.

**Comment by atwleung** [comment]
@Natarajan92 is it possible that there could be a cron job running once a week to clean up your /tmp directory? Maybe when such clean up triggers, it would remove live.mpd.tmp and screw up the rest of test-engine-live-tools?

**Comment by Natarajan92** [comment]
@atwleung , we have not used /tmp directory to save live.mpd.tmp
We are using like this in MP4Box command  **'-tmp', defaultConfig.outputDir,** 

 defaultConfig.outputDir - Is the location where we are saving segmented files

**Comment by jeanlf** [comment]
Closing, I believe this is more a disk management issue that a pb with mp4box
