### ISSUE TITLE
MP4BOX: Corrupted data when writing a smaller xml element following a larger xml element

### ISSUE THREAD

**Issue by astinov** [gpac/gpac#819]
The issue occurs on Windows 10 with the latest version (0.7.0) of MP4BOX. I'm using the following command:

mp4box -noprog 
-set-meta face:tk=0 -set-xml <filename1.xml>:tk=0 
-set-meta face:tk=2 -set-xml <filename2.xml>:tk=2 
-set-meta face:tk=3 -set-xml <filename3.xml>:tk=3 
-set-meta face:tk=4 -set-xml <filename4.xml>:tk=4 
-out <tempFile> <outputFile>

When filename1 has more data than filename2, the write result is corrupted. Extra data is included in the CDATA chunk for filename2.xml which comes from filename1.xml (a portion of it is visible in the chunk immediately after the data from filename2.xml)

**Comment by aureliendavid** [comment]
@astinov I'm a bit late to this but I can't reproduce the issue. Is the problem still present? If so can you provide sample data to reproduce it?

**Comment by astinov** [comment]
Hi David,

Actually we just got another instance where mp4box was corrupting data, but
what we found is that the nightly build fixed the issue. So we are
currently asking users to download that. Do you guys have any plans for an
official release based on that?

Lubo

**Comment by aureliendavid** [comment]
Glad to hear it's fixed. 

All nightlies available at https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/ are considered official releases (continuous integration). The main version numbers change very rarely, only when some milestone is reached. So it is recommended to use the latest build.
