### ISSUE TITLE
MP4Box currently broken - only the first segment is being generated.

### ISSUE THREAD

**Issue by richardbushell** [gpac/gpac#82]
I am sure that you already know, but MP4Box is now only creating the first segment only when DASHing files. e.g. an init segment and the first segment (e.g. the first 8 second segment of a 54 second file). No subsequent segments are being generated!

It was working perfectly previously, something get broken in the code in the last day or so, you may want to work backwards through the commits and track it down....

**Comment by richardbushell** [comment]
Plus the figures being produced in the MPD file for the Bandwidth are wrong (less than 1/6 of the correct bandwidth figures being written previously).

**Comment by jeanlf** [comment]
using wich command line ?

**Comment by richardbushell** [comment]
Same I I've been using for the last few weeks for testing:
MP4Box -dash 8000 -frag 8000 -rap -frag-rap -no-frags-default -profile dashavc264:live -segment-name %s -url-template -out "test.mpd"

**Comment by richardbushell** [comment]
Oops missed off the input file, corrected below:
MP4Box -dash 8000 -frag 8000 -rap -frag-rap -no-frags-default -profile dashavc264:live -segment-name %s -url-template -out "test.mpd" video.m4v audio.m4a

**Comment by jeanlf** [comment]
indeed, now fixed thanks for the report
