### ISSUE TITLE
Information lose

### ISSUE THREAD

**Issue by amuth** [gpac/gpac#820]
When I import a HEVC file, the following information is lost:

Writing Library
Encoding settings

How can I keep this information? See screenshots....

![hevc source](https://cloud.githubusercontent.com/assets/16451876/25660331/0a5cf5f6-300c-11e7-8f14-721593d7647e.png)
![mp4 generated with 0 6 2 and all informations](https://cloud.githubusercontent.com/assets/16451876/25660330/0a5cb2b2-300c-11e7-9107-6983ca6fc487.png)
![mp4 generated with 0 7 2](https://cloud.githubusercontent.com/assets/16451876/25660332/0a5d55a0-300c-11e7-8f55-6d5729c612f9.png)

**Comment by rbouqueau** [comment]
I can't reproduce with one HEVC sample I tested. Would it be possible to upload yours? We have a dropbox if necessary: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

PS: you can shorten your input in-plae (so make a copy before applying this command) with ```truncate -s SIZE filename```

**Comment by amuth** [comment]
file uploaded: test.hevc

**Comment by rbouqueau** [comment]
It works here (```MP4Box -add test.hevc test.mp4```), see attachment (modified extension for github). How is it for you? Do you use GPAC latest version?

[test.mp4.pdf](https://github.com/gpac/gpac/files/974411/test.mp4.pdf)

**Comment by amuth** [comment]
I use the latest x64 Version - gpac-0.7.2-DEV-rev18-gfadb8e2-master-x64.exe

Command: mp4box.exe" -par 1=1:1 -add "d:\test.hevc#1:name=H.265" "test.mp4"

**Comment by rbouqueau** [comment]
Thanks. That the ```-par``` option that removes it. Let me investigate.

**Comment by amuth** [comment]
I know - but only since version 0.7.2...

**Comment by rbouqueau** [comment]
Useful info. And do you know which previous version did work?

**Comment by rbouqueau** [comment]
I checked the files, they seem identical (except the presence of the PixelAspectRatioBox). I also tried to install the latest mediainfo but it doesn't work.

I am interested in a version of MP4Box that would work. At this point I think the PixelAspectRatioBox triggers a different code path in MediaInfo.

**Comment by aureliendavid** [comment]
I think it comes more or less from this commit https://github.com/gpac/gpac/commit/10dc09ce91466b160773aa6b6310f4fca04fab20 but that I wasn't all the way correct before either

I wrote a PR (https://github.com/gpac/gpac/pull/821) that seems to correct things. It does two things:
 * in `gf_media_hevc_change_par()` I don't think we needed to take a `nal_hdr_size` of 2 into account, we just copy the whole sps
 * in `avc_add_emulation_bytes()` a fun fun fun bug: without a cast as unsigned, `0xff < 0x03` is true

**Comment by aureliendavid** [comment]
@amuth you can now test with this version: gpac-0.7.2-DEV-rev24-g2669667-master-x64

**Comment by amuth** [comment]
Very nice. Thanks
