### ISSUE TITLE
Strange result when -cat files with :dur= option (missing reference)

### ISSUE THREAD

**Issue by Prividen** [gpac/gpac#826]
If I try to -cat mp4 files, it works fine:
`$ MP4Box -new  -cat cam1-2017-04-03-00-03-45.mp4 good_file.mp4`
`Appending file cam1-2017-04-03-00-03-45.mp4`
`No suitable destination track found - creating new one (type vide)`
`Saving good_file.mp4: 0.500 secs Interleaving`

But if i try to -cat files with :dur option, it produce broken result:

`$ MP4Box -new  -cat cam1-2017-04-03-00-03-45.mp4:dur=60 broken_file.mp4`
`IsoMedia import cam1-2017-04-03-00-03-45.mp4 - track ID 1 - Video (size 1920 x 1080)`
`Appending file cam1-2017-04-03-00-03-45.mp4:dur=60)`
`No suitable destination track found - creating new one (type vide)`
`Saving broken_file.mp4: 0.500 secs Interleaving`

when i try to rewind such broken file in VLC, it show garbage image till next I-frame, and wrote to console:
[h264 @ 0x7f6330cb4cc0] reference picture missing during reorder
[h264 @ 0x7f6330cb4cc0] Missing reference picture

Also, avprobe -show_packets for good file show "flags=K" for I-frames and "flags=_" for other frames.
For broken files it show: 
- "flags=_" for all frames, if file was created by MP4Box v. 0.6.1
- "flags=K" for all frames, if file was created by MP4Box v. 0.7.1

No any other difference between good and broken files in avprobe or mediainfo output (but normal file has a bit larger size).

**Comment by Prividen** [comment]
cam1-2017-04-03-00-03-45.mp4 uploaded to https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by jeanlf** [comment]
I believe this was fixed some time ago, cannot reproduce with 0.9.0. Reopen if needed
