### ISSUE TITLE
MP4Client quality adaptation not working when playing SRD tiled video

### ISSUE THREAD

**Issue by ChangSurrey** [gpac/gpac#827]
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with dropbox (see links provided below). 

Hello, 

I have a 8-minute 360 video that is divided into 5x5 tiles. The video was prepared using the latest version of kvazaar. 2 representations are prepared - 500kbps and 5Mbps. 

It is then converted into DASH format using the latest version of MP4Box with the following command: 

`MP4Box -dash 2000 -profile live -out ba.mpd -segment-name segment/%s 500k.mp4 5M.mp4`

The whole video set (including MPD file and all segments) can be downloaded at: 
https://www.dropbox.com/s/hvflbdx442r5y2g/blue-angel.tar.gz?dl=0

I'm streaming the video in a local network setup as follows: 

[Server] <-> [Network Impairment Node] <-> [Client]

where the network impairment node is able to add delays and packet loss to the path (using standard Linux tc netem). 

While MP4Client can play the video without any problem, I notice that no matter how poor the network is, MP4Client always chooses the 5Mbps representation and does not switch to a lower quality. This causes the video playback to stall every 2 seconds. 

Looking into the log file (using MP4Client's dash@debug option), which can be downloaded at https://www.dropbox.com/s/39w79kkjfzoixw8/mp4client-400ms.log?dl=0

I can see the following output: 

`[DASH] Rate Adaptation - download rate 11872 kbps - 3 quality levels (cumulated representations rate 5045 kbps)`

while the actual download throughput is less than 1Mbps, which is observed by running Wireshark on the client machine. 

It's important to note that this issue seems to apply to SRD tiled video only. When I play non-tiled video using the same setup, MP4Client is able to correctly adapt representations based on network condition. 

Thanks! 
Chang

**Comment by ChangSurrey** [comment]
Hello again, 

I have identified something in the log file (the 2nd URL above) which should be directly caused by this issue. 

Basically, when the video was divided into 5x5 tiles and converted into DASH format, 1 base track and 25 tile tracks were created, making 26 adaptation sets in total. 

Now, if we examine the log file (see the 2nd URL above), at line 526: 

`[DASH] Download http://131.227.60.91:80/video/blue-angel/blue-angel-500k-tiled_dash_track1_2.m4s complete at UTC 1494410793861 ms`
(which is the video's segment 2's track 1, i.e., the base track)

If we look at line 528, we can see that dash_client.c correctly calculates the download throughput of segment 2's track 1: 

`[DASH] AS#1 got blue-angel-500k-tiled_dash_track1_2.m4s stats: 1484 bytes in 0.001 sec (11872 kbps) - duration 2 sec - Media Rate: indicated 6 - computed 5 kbps - buffer 3999 ms`

However, if we look at the subsequent lines, it can be seen that none of the download throughput of the remaining 25 tracks are calculated by dash_client.c. 

Unfortunately, for a tiled video's segments, their base tracks are all very tiny in size (in this case, 1484 bytes) and can always be downloaded within 0.001s or 1ms. It's the actual video tile tracks' download throughput that matter when estimating network condition and making adaptation decisions, which are not calculated here. 

Personally I'm not good enough at C programming to fix this issue, but I hope my discovery can help someone fix this issue soon? 

Thanks
Chang

**Comment by ChangSurrey** [comment]
Any opinion on this issue?

**Comment by OmarEltobgy** [comment]
Hi Chang, 

In these days, I am working on implementing the same network setup that you are describing. 
However, I am stuck in the first step of generating the dash files
An error saying '[DASH] Require segment starts with RAP but next segment will not be compatible' keeps appearing
I think this is a problem using kavazaar assigning the Random Access Points (which i think is the intra frames)

So, Would you please send me the commands that you used for kavazaar and MP4Box to generate the mp4 file ?

**Comment by ChangSurrey** [comment]
Hello, 

I see the same warning message too (I don't think it's an error message). However, I don't think this affects the playback of the video. 

The kvazaar command I used is: 
`kvazaar --input blue-angel.yuv --input-res 3840x1906 --input-fps 30 --bitrate 10000000 --tiles 5x5 --slices tiles --mv-constraint frametilemargin --output blue-angel-5M.hevc`

The MP4Box command is: 
`MP4Box -add blue-angel-5M.hevc:split_tiles -new 5M.mp4`

**Comment by shkp4j** [comment]
Hi ChangSurrey,
Did you use the same input file blue-angel.yuv that you used for 5M, to generate 500K hevc file? 

kvazaar --input blue-angel.yuv --input-res 3840x1906 --input-fps 30 --bitrate 10000000 --tiles 5x5 --slices tiles --mv-constraint frametilemargin --output blue-angel-5M.hevc 

I used the same command to prepare multiple representation by assigning different bitrate but my hevc seems very short and when packaged with MP4Box, and dashed with MP4Box - dash   with multiple representations, I find only one segment m4s.

**Comment by JamesXu20150314** [comment]
Hi,

Where was the log's location? 
How did you control the rendering of 360 tiles, and how did you render it.
Could you provide some guidelines?

Thanks.

**Comment by shkp4j** [comment]
Hi,
Was there any follow up / fix of this issue? 
Thank you.

**Comment by lutchenxl** [comment]
Hi, Chang
I download the segments from the URL you provided.

For 500kbps,the files name is 500k_track1_1.m4s to 500k_track26_246.m4s.Only considering
track number,it is from track1 to track 26.

For 5Mbps,the files name is 5M_track2_1.m4s to 5M_track26_246.m4s.Only considering
track number,it is from track2 to track 26.

So are there 5M_track1_x.m4s?

**Comment by jeanlf** [comment]
we have been fixing things with throughput estimation, please try 0.8.0 or 0.9.0 DEV and reopen if needed
