### ISSUE TITLE
Cannot Play Any HLS Stream

### ISSUE THREAD

**Issue by franckyM** [gpac/gpac#828]
I can 't play any HLS Stream : I tried several HLS stream with the latest Nightly build on MAC OSX 
gpac-0.7.2-DEV-rev58-g99b2689-master.dmg

Opening URL http://b028.wpc.azureedge.net/80B028/Samples/a38e6323-95e9-4f1f-9b38-75eba91704e4/5f2ce531-d508-49fb-8152-647eba422aec.ism/Manifest(format=m3u8-aapl)
[DASH] Error - cannot connect service: MPD creation problem Bad Parameter
[MPD_IN] Error - cannot initialize DASH Client for http://b028.wpc.azureedge.net/80B028/Samples/a38e6323-95e9-4f1f-9b38-75eba91704e4/5f2ce531-d508-49fb-8152-647eba422aec.ism/Manifest(format=m3u8-aapl): Bad Parameter
 Cannot open http://b028.wpc.azureedge.net/80B028/Samples/a38e6323-95e9-4f1f-9b38-75eba91704e4/5f2ce531-d508-49fb-8152-647eba422aec.ism/Manifest(format=m3u8-aapl): Bad Parameter

**Comment by rbouqueau** [comment]
It plays here (on Windows 10). I let someone on Mac OS test but there should be no difference.

**Comment by jeanlf** [comment]
Working here on SX with the current git, can you still reproduce ?
