### ISSUE TITLE
Encryption: I/O error when input and output file paths are same

### ISSUE THREAD

**Issue by aaani** [gpac/gpac#830]
Hello,
I am trying to encrypt files with mp4box. It works fine unless I use the same file path for input and output file. (I want it to overwrite the original file with the encrypted file). Following is the error I get:

```
~ Mp4box -crypt /Users/ani/work/mp4box-crypt/input/crypt.xml -out /Users/ani/work/archive/hd-00002.mp4 /Users/ani/work/archive/hd-00002.mp4

Saving to /Users/ani/work/archive/hd-00002.mp4: 0.500 secs Interleaving

[Core] system failure for file opening of out_/Users/ani/work/archive/hd-00002.mp4 in mode w+b: 2
Error: I/O Error

	Error: I/O Error
```

I am on `MP4Box - GPAC version 0.7.1-revrelease`. I am wondering if this is how it's supposed to work, or if it's a bug?

**Comment by aureliendavid** [comment]
I think it's pretty much normal. 

To do it in-place you can remove the -out part :

`Mp4box -crypt /Users/ani/work/mp4box-crypt/input/crypt.xml  /Users/ani/work/archive/hd-00002.mp4`

should do the trick.

**Comment by aaani** [comment]
That works. Thanks!
