### ISSUE TITLE
mp4box says "VUI "fixed_frame_rate_flag" absent." but it's actually not absent.

### ISSUE THREAD

**Issue by sneaker2** [gpac/gpac#833]
Hi,

whenever I import H.264 elemtary streams using mp4box it says "_[avc-h264] Possible Variable Frame Rate: VUI "fixed_frame_rate_flag" absent._". This even happens with samples that do have said flag set to 1. I haven't seen any actual issues with the output files.

Sample "fixed_frame_rate_flag_NOT_absent.264" uploaded to MediaFire.
mp4box is latest Windows nightly (gpac-0.7.2-DEV-rev67-g975c0eb-master-win32).

**Comment by rbouqueau** [comment]
Thanks for reporting. Should be fixed now. Reopen if you still see the issue!
