### ISSUE TITLE
qsvenc output fails to mux

### ISSUE THREAD

**Issue by stax76** [gpac/gpac#834]
There is a issue with qsvenc both avc and hevc.

https://github.com/stax76/staxrip/issues/188

**Comment by rbouqueau** [comment]
Hi, thanks for reporting. I have some qsv samples from a Haswell CPU and can't reproduce. Who it be possible to update some samples please?

**Comment by stax76** [comment]
Hi, here is a avc and a hevc sample encoded with skylake:

https://drive.google.com/open?id=0B-gPKiJYuKuIQnhxVldrcWhYaVU


The MP4Box build I used is from here:

https://forum.doom9.org/showthread.php?p=1807856#post1807856

**Comment by rbouqueau** [comment]
Thanks. I see the message only with HEVC (I am going to investigate what needs to be implemented here).

The output files, both for AVC and HEVC, seem ok. Did you see any troubles on the output files?

**Comment by stax76** [comment]
I only remember there was a problem and reverted back to an older build.

**Comment by rbouqueau** [comment]
I've just added some checks to remove the warning when these lists are empty. However when the lists are not empty, we need to parse very deep in the stream to retrieve the right information.

@jeanlf provided me with additional streams.

The generated streams can be read by VLC. I'd be interested by a case where the resulting stream would be unreadable. Did anyone see such streams?

**Comment by stax76** [comment]
Would it be possible to get a windows build?

**Comment by rbouqueau** [comment]
http://download.tsi.telecom-paristech.fr/gpac/latest_builds/win64/gpac-0.7.2-DEV-rev77-g49f5e93-master-x64.exe

Reminder: you can open it with 7zip if you don't actually mean to execute the installer.

**Comment by stax76** [comment]
Thanks, I found your reply while going through my gmail spam mail folder, apparently gmail classified it as spam due to the exe extension.

For staxrip I would need a small static build though. With this build I get:

```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
            Error Muxing using MP4Box 0.6.2 x64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Muxing using MP4Box 0.6.2 x64 failed with exit code: -1073741819 (0xC0000005)

The exit code might be a system error code: Die Anweisung in 0xp verwies auf Arbeitsspeicher bei 0xp. Der Vorgang s konnte im Arbeitsspeicher nicht durchgeführt werden.

AVC-H264 import - frame size 1280 x 720 at 29.970 FPS

Start:    12:39:18
End:      12:39:18
Duration: 00:00:00
```

staxrip couldn't capture the full error console output, maybe there is something wrong with my redirection code, first it hangs about 10 seconds and then it crashes, this is how it looks in CMD:

![screenshot 7](https://cloud.githubusercontent.com/assets/11410540/26676405/f1c60668-46c7-11e7-8e0f-5323109f68b6.png)

**Comment by stax76** [comment]
Next time I install Windows I should install the English version...

**Comment by rbouqueau** [comment]
No problem. I will have a look at your issue.

**Comment by stax76** [comment]
sample and log are here:

https://drive.google.com/open?id=0B-gPKiJYuKuIQnhxVldrcWhYaVU

again qsvenc was used

**Comment by rbouqueau** [comment]
should be fixed (haven't had a look at your sample) - close issue if ok

static build available temporarilly at http://gpac-licensing.com/downloads/mp4box.exe

**Comment by stax76** [comment]
The link don't work.

**Comment by rbouqueau** [comment]
Could you retry please?

**Comment by stax76** [comment]
Download works now, thanks. I'll run some tests shortly.

**Comment by stax76** [comment]
Everything works well now. Thanks for the support!

**Comment by rbouqueau** [comment]
Great! Thanks for helping
