### ISSUE TITLE
Loop in dash-live with growing file

### ISSUE THREAD

**Issue by trijb** [gpac/gpac#835]
Hi,
first of all, i'm not sure if this is a bug or a misuse of the tool. I've searched for similar issues and didn't find anything alike.

I´m trying to generate dash live streaming with ffmpeg and mp4box. I'm using ffmpeg to generate a file(black background with a burned TC)  and then feed mp4box with the growing file.
 
Commands:

`ffmpeg -re -f lavfi -i color=s=nhd -map 0:v -filter_complex drawtext="fontfile='FreeSans.ttf':timecode='00\:00\:00\:00': r=25: x=(w-tw)/2: y=(h-th)/25: fontcolor=white: fontsize=42: box=1: boxcolor=0x00000099"  -vcodec libx264 -g 1 -b:v 800k -pix_fmt yuv422p -movflags empty_moov+omit_tfhd_offset+frag_keyframe+default_base_moof -f mp4  -frag_duration 2 -y /tmp/longTC_2.mp4`

`mp4box -dash-live 2000 -fps 25 -frag 1000 -profile "dashavc264:live"  -mpd-title "DASH-LIVE stream" -rap -frag-rap -insert-utc -mpd-refresh 30 -time-shift 1200 -min-buffer 2000  -bs-switching no -out /streaming/live/dash.mpd   /tmp/longTC_2.mp4:role=main`

Also tested with: 

`mp4box -dash-ctx /streaming/live/dash-live.txt -dash-live 2000 -profile "dashavc264:live" -mpd-title "DASH-LIVE stream" -ast-offset 12 -no-frags-default -rap -frag-rap -insert-utc -mpd-refresh 30 -time-shift 1200 -min-buffer 2000  -bs-switching no -out /streaming/live/dash.mpd  -subsegs-per-sidx -1 /tmp/longTC_2.mp4:role=main`

(and multiple variants: -last-dynamic, add id to period, long etc )

The result is always the same, when the live session is launched, mp4box packages the whole mp4 file generated by ffmpeg available at the moment and goes to slept until the next iteration (the next lines corresponds to an execution that the file already had 1m1s of duration )

> Live DASH-ing - press 'q' to quit, 's' to save context and quit
Next generation scheduled in 61338 ms (DASH time 61520 ms)

In the next scheduled: 

> Live DASH-ing - press 'q' to quit, 's' to save context and quit
Next generation scheduled in 61338 ms (DASH time 61520 ms)
Slept for 2665038 ms before generation
Next generation scheduled in 61492 ms (DASH time 123040 ms)

The result is that the segments are being regenerated from the beginning of the file (it looks like it's resetting the file pointer or not seeking to the last position ), so:

longTC_2_dash0.m4s has burned TC 00:00:00:00
and 
longTC_2_dash30..3N.m4s has burned TC 00:00:00:00 again

If you concatenate all files and play them with ffplay (for example) you can see the loop:

`cat longTC_2_dashinit.mp4 $(ls -vx longTC_2_dash*.m4s) > fullfileconcat.mp4`

NOTE: the init file (longTC_2_dashinit.mp4) contains the box 'mvex' which in turn contains box 'mehd'. this box indicates the expected time of the segment set. This time is filled with the first available packet (in this case 61520) and never updated, so in order to play the concatenated file it would be necessary to open it with a hex editor and just skip this box.

I left in dropbox all the files that are generated and the concatenated one (loop_dash_live_issue_835)
Any ideas will be appreciated

This issue happens with the  0.7.0-rev0-gbd5c9af-master  version and with the development branch from github. Tested both on windows 10 and ubuntu 16.04.

Thanks in advance and sorry for my bad english :)

**Comment by DerouineauNicolas** [comment]
Hi,
At the moment MP4Box is not able  to take a live stream as a dash input. Did you try with dashcast ?

**Comment by trijb** [comment]
Hi,
Thanks for the quick response.

Yes, but i also have some issues. (dashcast version 0.7.0)

Same loop problem with this command:
`dashcast -v /tmp/longTC_2.mp4 -vfr 25 -npts  -seg-dur 2000 -out /streaming/live -mpd dash.mpd  -mpd-refresh 30 -time-shift 600 -insert-utc -live-media`

And this .conf file:

> [v1]
type=video
bitrate=700000
framerate=25
width=640
height=360
crop_x=0
low_delay=no
crop_y=0
codec=libx264

> [a1]
type=audio
bitrate=96000
samplerate=44100
channels=2
codec=aac

And if i attach "-no-loop" I have an error and the process exit, looks like the proccess run faster that the input so swscaler has no media 

> Generating MPD at 2017-06-01T13:56:21.958Z
StartTime: 2017-06-01T13:56:18.655Z - startNumber 1 - last number 6
[swscaler @ 000000000239ea00] bad src image pointers
Video scaler: error while resizing picture.
Video scaler got an end of input tbuffer!
Video encoder got an end of buffer!
[video_encoder] Rep v1 UTC diff at segment close: 4017 is lower than cumulated segment duration 14000 (diff -9983) - frame rate is probably not correct or frames were lost!
Generating MPD at 2017-06-01T13:56:22.500Z
StartTime: 2017-06-01T13:56:18.655Z - startNumber 1 - last number 7
[libx264 @ 000000000245fd80] frame I:47    Avg QP: 7.04  size:  2896
[libx264 @ 000000000245fd80] frame P:67    Avg QP: 7.02  size:   979
[libx264 @ 000000000245fd80] frame B:201   Avg QP: 9.21  size:   490
[libx264 @ 000000000245fd80] consecutive B-frames: 14.9%  0.0%  0.0% 85.1%
[libx264 @ 000000000245fd80] mb I  I16..4: 78.4% 18.3%  3.3%
[libx264 @ 000000000245fd80] mb P  I16..4:  0.0%  0.0%  0.2%  P16..4:  0.5%  0.1%  0.2%  0.0%  0.0%    skip:98.8%
[libx264 @ 000000000245fd80] mb B  I16..4:  0.0%  0.0%  0.1%  B16..8:  0.2%  0.1%  0.2%  direct: 0.0%  skip:99.3%  L0:47.8% L1:44.8% BI: 7.4%
[libx264 @ 000000000245fd80] final ratefactor: -3.19
[libx264 @ 000000000245fd80] 8x8 transform intra:18.2% inter:14.2%
[libx264 @ 000000000245fd80] coded y,uvDC,uvAC intra: 3.4% 0.0% 0.0% inter: 0.3% 0.0% 0.0%
[libx264 @ 000000000245fd80] i16 v,h,dc,p: 95%  1%  4%  0%
[libx264 @ 000000000245fd80] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 43% 17% 40%  0%  0%  0%  0%  0%  0%
[libx264 @ 000000000245fd80] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 43% 13% 12%  5%  5%  7%  3%  8%  2%
[libx264 @ 000000000245fd80] i8c dc,h,v,p: 100%  0%  0%  0%
[libx264 @ 000000000245fd80] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 000000000245fd80] ref P L0: 73.4%  3.7% 13.5%  9.4%
[libx264 @ 000000000245fd80] ref B L0: 66.4% 24.0%  9.6%
[libx264 @ 000000000245fd80] ref B L1: 85.9% 14.1%
[libx264 @ 000000000245fd80] kb/s:190.62
Keyboard thread exit
Duration: PT00H00M12.000S

**Comment by DerouineauNicolas** [comment]
Hi,
I won't be able to help you with dashcast, but using an external loop with MP4Box seems to do the trick:

while true;
do

   MP4Box -dash-ctx /tmp2/dash-live.txt -dash-live 2000 -dash-run-for 1000 -profile "dashavc264:live" -mpd-title "DASH-LIVE stream" -ast-offset 12 -no-frags-default -rap -frag-rap -insert-utc -mpd-refresh 30 -time-shift 1200 -min-buffer 2000 -bs-switching no -out /tmp2/dash.mpd -subsegs-per-sidx -1 /tmp2/test.mp4:role=main

   sleep 1

done

Can you try and tell me if it works for you ? It works on my side

**Comment by trijb** [comment]
Hello, sorry for the delay in the response.
Yes, I tested it and it works correctly in short periods, but, when the live session lasts at least a few hours the problem rise again.
The file to dashify can be big enought to lost the liveness effect of the streaming.
I'll keep trying to find out how to do it with the changes you've made. 
Thank you very much for the help. 
Regards

**Comment by jeanlf** [comment]
Didi you try with the script or with the latest revisions of MP4Box ?

**Comment by jeanlf** [comment]
No news, reopen if needed
