### ISSUE TITLE
Dashed Segments in sub-directories for each Representation using MP4Box?

### ISSUE THREAD

**Issue by richardbushell** [gpac/gpac#84]
I am trying to get the Segments to write to sub-directories when using -url-template addressing scheme, so that each representation's segment files are in different directories:

I have tried several combinations such as:
-segment-name $RepresentationID$\%s
-segment-name $RepresentationID$\$RepresentationID$
-segment-name $RepresentationID$\$Number$

BUT even though the path looks valid, MP4Box always generates an error:
[Core] system failure for file opening of out\ibeani_i2\ibeani_i2_track1_.mp4 in mode w+b: 0x00000003

I wish to generate in the MPD:
<SegmentTemplate media="$RepresentationID$/ibeani_i2_track1_$Number$.m4s" ...>

Does MP4Box not allow for sub-directories? Do all files of all representations have to be in the same folder? OR am I doing something wrong???

**Comment by richardbushell** [comment]
Sorry, forgot I can't paste tag brackets in the posts, this should read:
I wish to generate in the MPD:
SegmentTemplate media="$RepresentationID$/ibeani_i2_track1_$Number$.m4s"

**Comment by jeanlf** [comment]
could you check the last version of the code ?

**Comment by richardbushell** [comment]
Tried in latest nightly currently showing (build 239), still the same error. Which build number is this implemented in?

**Comment by jeanlf** [comment]
you can check the short hash of the commit by browsing the history, and find if the corresponding build is already vailable on our download page. In this case the hash is e6de3ba, and the installers are the latest ones

**Comment by richardbushell** [comment]
I follow that hash ( e6de3ba ) and it shows me the code changes you made, but where can I see if that has been incorporated into a build and what the build number is? Sorry, can't find that?

**Comment by cconcolato** [comment]
The name of the version contains the hash. Search for the hash in 
http://gpac.wp.mines-telecom.fr/downloads/gpac-nightly-builds/. In this case, you'll see:
gpac-0.5.2-DEV-rev240-ge6de3ba-master-win32.exe

**Comment by richardbushell** [comment]
OK, seen it. Didn't recognise it as it appended a 'g' in front of the hash. Does it always append a lead 'g' to the hash name?

**Comment by cconcolato** [comment]
Yes. I had the same problem. Apparently, g is for git ... don't know how to remove it ...

**Comment by richardbushell** [comment]
OK, thanks. Shame you can't remove the 'g', I think a lot of people will miss the commit id connection. But, now I know it'll be much easier to spot the builds that correspond to each commit for testing.

Anyway, the sub-directories for each representation now works perfectly for a single video and single audio representation, thanks!

The only thing that seems different is that the '_init' suffix no longer appends to the init segment file names in the respective directories. It would be nice to keep that as before.

**Comment by richardbushell** [comment]
Hi Jean
Any chance you could amend the code to append the '_init' suffix to the init segment file names in the respective directories. It does append this when it's not in a directory, but is currently omitting it when it's in a directory.

**Comment by jeanlf** [comment]
the "init" suffix is disabled whenever the segment template uses $RepresentationID$ or $Bandwidth$ (it is only used to avoid overwriting files)

if you want it back you must specify it in the template, eg 
'-segment-name $RepresentationID$\seg_$Init=init$"  ... '
