### ISSUE TITLE
How can I encrypt MP4 file for Fairplay DRM?

### ISSUE THREAD

**Issue by ycinfinity** [gpac/gpac#842]
Apple has already supported fragment MP4. According to https://developer.apple.com/videos/play/wwdc2016/504/ this video, the Fairplay encryption mode of fragment MP4 should be 'cbcs'. In addition to this, I can't find any demo or tutorial about 'cbcs' working with fragment MP4.  

Can mp4box encrypt MP4 file for Fairplay?

Thanks

**Comment by hungvo2010** [comment]
Could you show your solution?
