### ISSUE TITLE
MP4client not working with Win64 installer (gpac-0.7.0-rev0-gbd5c9af-master-x64 and gpac-0.7.2-DEV-rev86-g81601a2-master-x64)

### ISSUE THREAD

**Issue by crittlc** [gpac/gpac#843]
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Hi,

I downloaded the latest installers for Windows 64 bit (I tried both _gpac-0.7.0-rev0-gbd5c9af-master-x64_ and _gpac-0.7.2-DEV-rev86-g81601a2-master-x64_), but something seems to be missing in my installation for MP4Client.

Here is the error log:
> System info: 32651 MB RAM - 24 cores
> Modules Found : 34
> Loading GPAC Terminal
> [Core] Plugin GPAC 2D Raster not found in 34 modules.
> [Compositor] Failed to initialize compositor: I/O Error
> GF_COMPOSITOR_THREAD_INIT_FAILED : Deleting compositor.
> [Terminal] Failed to create Compositor.
> 
> Init error - check you have at least one video out and one rasterizer...
> Found modules:
> Available modules:
>         gm_aac_in.dll
>         gm_ac3_in.dll
>         gm_bifs_dec.dll
>         gm_ctx_load.dll
>         gm_dektec_out.dll
>         gm_dummy_in.dll
>         gm_dx_hw.dll
>         gm_ffmpeg_in.dll
>         gm_ft_font.dll
>         gm_gdip_raster.dll
>         gm_gpac_js.dll
>         gm_img_in.dll
>         gm_ismacryp.dll
>         gm_isom_in.dll
>         gm_laser_dec.dll
>         gm_mp3_in.dll
>         gm_mpd_in.dll
>         gm_mpegts_in.dll
>         gm_mse_in.dll
>         gm_nvdec.dll
>         gm_odf_dec.dll
>         gm_ogg.dll
>         gm_openhevc_dec.dll
>         gm_opensvc_dec.dll
>         gm_platinum.dll
>         gm_rtp_in.dll
>         gm_saf_in.dll
>         gm_soft_raster.dll
>         gm_svg_in.dll
>         gm_timedtext.dll
>         gm_vtt_in.dll
>         gm_wav_out.dll
>         gm_widgetman.dll
>         gm_xvid_dec.dll`
 
I am sure that _GPAC 2D Raster_ was checked during the installation.

On the same PC, version 0.6.1 worked fine.

Thanks for any feedback!

**Comment by aureliendavid** [comment]
Is the `gm_soft_raster.dll` file indeed present in your install directory?

Can you provide the GPAC.cfg file used? When running mp4client from a command prompt, it should say

`Using config file in <path_to_GPAC.cfg>`

Also can you try to run it with full logs, with something like 

`mp4client -logs all@debug -log-file debug.log -run-for 0`

and join the debug.log file?

thanks

**Comment by crittlc** [comment]
Thanks for your answer.

Yes, I have the file `gm_soft_raster.dll` (43520 Bytes).

Attaching` GPAC.cfg` and `debug.log`.
[GPAC.cfg.txt](https://github.com/gpac/gpac/files/1060288/GPAC.cfg.txt)
[debug.log.txt](https://github.com/gpac/gpac/files/1060289/debug.log.txt)

**Comment by aureliendavid** [comment]
Thanks for the info. I was able to reproduce it. 

In your GPAC.cfg, if you replace

`gm_soft_raster.dll=GR22:yes`

by

`gm_soft_raster.dll=GR23:yes`

I think it should work.

Is it possible that your GPAC.cfg was an old one that remained from an install of version <0.7? In that case you can try to just delete it and launch mp4client and it should re-generate a proper one.

Hope that helps.

**Comment by crittlc** [comment]
Got it, thanks!

Yes I had an old 0.6.1 installed, but uninstalled it before installing the new one: maybe it did not clean also the `AppData\Roaming\GPAC` folder.

BTW, your trick of just deleting the file worked, but then I could not open my files any more (for information, I attach the "fresh" cfg file), so I succesfully replaced the entry as suggested by you.
[GPAC - fresh.cfg.txt](https://github.com/gpac/gpac/files/1060910/GPAC.-.fresh.cfg.txt)
