### ISSUE TITLE
MP4Client log file

### ISSUE THREAD

**Issue by irrz** [gpac/gpac#846]
Hello there,
I am running DashCast on the server side for VoD streaming, and the bitrates (250,500,1000,2000Kbps) are done via a config file.

I want to do further evaluation but I want to get the size (bitrate) of each frame once the segmentation is occur.
Is there any way I can extract all frames or segments' information from either DashCast command line or in MP4Client?

Thanks
Irrz

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
At MP4Client level you can use 
```
MP4Client -logs dash@info $URL
```
and you will see the download stats of each segment (duration, size, rate, download speed)

At dashcast level (just updated the logs, so checkout new version), you can use -logs dash@info to get the segment write times and sizes, and -logs dash@debug to also get each encoded frame size
