### ISSUE TITLE
Install failure in mac OX

### ISSUE THREAD

**Issue by huangsherry** [gpac/gpac#848]
I met a problem when I try to install the gpac pulled from the git. The error listed here.

`
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../bin/gcc/libgpac_static.a(tripledes.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../bin/gcc/libgpac_static.a(arith_decoder.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../bin/gcc/libgpac_static.a(predictive_mffield.o) has no symbols
ld: warning: ignoring file /usr/local/lib/libz.dylib, file was built for i386 which is not the architecture being linked (x86_64): /usr/local/lib/libz.dylib
Undefined symbols for architecture x86_64:
  "_deflate", referenced from:
      _gf_gz_compress_payload in base_encoding.o
      _gf_import_nhml_dims in media_import.o
  "_deflateEnd", referenced from:
      _gf_gz_compress_payload in base_encoding.o
      _gf_import_nhml_dims in media_import.o
  "_deflateInit_", referenced from:
      _gf_gz_compress_payload in base_encoding.o
      _gf_import_nhml_dims in media_import.o
  "_deflateSetDictionary", referenced from:
      _gf_import_nhml_dims in media_import.o
  "_gzclose", referenced from:
      _xml_sax_read_file in xml_parser.o
      _gf_xml_sax_del in xml_parser.o
      _load_bt_done in loader_bt.o
      _load_bt_run in loader_bt.o
  "_gzeof", referenced from:
      _xml_sax_read_file in xml_parser.o
      _gf_xml_sax_peek_node in xml_parser.o
      _gf_bt_check_line in loader_bt.o
      _gf_bt_get_string in loader_bt.o
  "_gzgetc", referenced from:
      _gf_bt_check_line in loader_bt.o
  "_gzgets", referenced from:
      _gf_bt_check_line in loader_bt.o
      _gf_sm_load_bt_initialize in loader_bt.o
  "_gzopen", referenced from:
      _gf_xml_sax_parse_file in xml_parser.o
      _gf_sm_load_bt_initialize in loader_bt.o
  "_gzread", referenced from:
      _gf_xml_sax_parse_file in xml_parser.o
      _xml_sax_read_file in xml_parser.o
      _gf_xml_sax_peek_node in xml_parser.o
  "_gzrewind", referenced from:
      _gf_xml_sax_peek_node in xml_parser.o
      _gf_bt_peek_node in loader_bt.o
  "_gzseek", referenced from:
      _gf_xml_sax_peek_node in xml_parser.o
      _gf_bt_check_line in loader_bt.o
      _gf_bt_peek_node in loader_bt.o
      _gf_sm_load_bt_initialize in loader_bt.o
  "_gztell", referenced from:
      _gf_xml_sax_peek_node in xml_parser.o
      _gf_bt_check_line in loader_bt.o
  "_inflate", referenced from:
      _gf_gz_decompress_payload in base_encoding.o
      _gf_media_export_nhml in media_export.o
  "_inflateEnd", referenced from:
      _gf_gz_decompress_payload in base_encoding.o
      _gf_media_export_nhml in media_export.o
  "_inflateInit_", referenced from:
      _gf_gz_decompress_payload in base_encoding.o
      _gf_media_export_nhml in media_export.o
  "_uncompress", referenced from:
      _gf_swf_read_header in swf_parse.o
      _swf_def_bits_jpeg in swf_parse.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../bin/gcc/libgpac.dylib] Error 1
make: *** [all] Error 2`

Configure information is listed here: 
`
** System Configuration
Install prefix: /usr/local
Source path: /Users/shenglan.huang/lowLatency/gpac
C   compiler: gcc
C++ compiler: g++
make: make
CPU: x86_64
Big Endian: no

** GPAC 0.7.2-DEV rev Core Configuration **
debug version: no
GProf enabled: no
Static build enabled: no
Memory tracking enabled: no
Fixed-Point Version: no
IPV6 Support: yes
Static Modules: no

** Detected libraries **
zlib: system
OSS Audio: no
ALSA Audio: no
Jack Audio: no
PulseAudio Audio: no
DirectFB support: no
SDL Support: yes
OpenGL support: yes
TinyGL support: no
OpenSSL support: no
Mozilla XUL/GECKO support: no
XMLRPC Support: no
wxWidgets support: no

** Extra Libraries used **
SpiderMonkey: system
FreeType: system
JPEG: system
OpenJPEG: no
PNG: system
MAD: system
FAAD: system
XVID: system
FFMPEG: system
Xiph OGG: system
Platinum UPnP: no
AVCap: no
Xiph Vorbis: system
Xiph Theora: system
A52 (AC3): system
OpenSVCDecoder: no
OpenHEVCDecoder: no
Freenect: no

Creating config.mak
config.h is unchanged
Check config.log for detection failures
Done - type 'make help' for make info, 'make' to build`
Thanks.

**Comment by huangsherry** [comment]
Problem solved:
This is because zlib is installed as i386, so you have to build it for x86-64. Here's how to do it:
you first have to remove old zlib files: sudo rm /opt/local/lib/libz*
Download zlib source code from its webpage
Extract the source, and open a terminal in source location
./configure, make and sudo make install

**Comment by jgravois** [comment]
thanks for taking the time to explain exactly how you solved this problem. it was a lifesaver for me today.
