### ISSUE TITLE
Dashing tracks with different keys must create multiple adaptation sets

### ISSUE THREAD

**Issue by sandersaares** [gpac/gpac#849]
Version: gpac-0.7.2-DEV-rev105-gbdd7fde-master-x64
Command: `mp4box.exe -dash-strict 4000 -out out\Manifest.mpd -profile "dashavc264:live" -sample-groups-traf -bs-switching no SD-1.mp4 SD-2.mp4 HD-1.mp4 HD-2.mp4`
Input data: https://media.axprod.net/mp4box/multikey.zip

The input data set contains two SD video tracks encrypted with one key and two HD video tracks encrypted with a different key.

Expected behavior: representations with different keys are in different adaptation sets.
Actual behavior: all representations are in one adaptation set.

Relevant references:

* DASH-IF IOP 4.0 section 7.7.1 p1
* DASH-IF IOP 4.0 section 7.7.2 p1-2
* DASH-IF IOP 4.0 section 7.7.5

**Comment by jeanlf** [comment]
We currently haven't implemented new DASH-IF IOPs. Note that if you know the crypto info before dashing you can always alter mapping representation to adaptation set using :desc_as switches and XML comments. In your case this means something like:

```
MP4Box -dash-strict 4000 -out Manifest.mpd -profile "dashavc264:live" -sample-groups-traf -bs-switching no SD-1.mp4:desc_as="<!-- sd -->" SD-2.mp4:desc_as="<!-- sd -->" HD-1.mp4:desc_as="<!-- hd -->" HD-2.mp4:desc_as="<!-- hd -->"
```

I'll soon patch the code to allow non-XML in these descriptors (obviously only for the selection process, not to write them in the file ...)

**Comment by sandersaares** [comment]
Thank you for informing about the workaround! That should work quite well in my case, yes, as I know beforehand in my workflows which files should go in which adaptation sets.

**Comment by jeanlf** [comment]
good to know - you may now also directly use :desc_as=SD to avoid the XML comment in the  MPD.
