### ISSUE TITLE
Getting YUV file out of the dashed files

### ISSUE THREAD

**Issue by OmarEltobgy** [gpac/gpac#851]
- [yes] I looked for a similar issue and couldn't find any.
- [yes] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [yes] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Greetings, 

I followed this blog post to generate a MPEG DASH tiled HEVC stream: https://gpac.wp.imt.fr/2016/05/25/srd/
So, now i have the mpd and m4s files for each tile each second with different qualities.

I would like to ask how i can choose offline a prespecified qualities for each tile each second and decode these tile qualities each second and concatenate them to produce a YUV stream or even an HEVC stream of different tile qualities that i can use an HEVC decoder to get the YUV file. 

So, can i use the source code APIs to do such a thing ? 

Best Regards,
Omar Eltobgy

**Comment by jeanlf** [comment]
if you know offline the target tile qualities you will use then no need for the player, only select and concatenate the given tiles in a single file (since you have init segments and all tile files).
