### ISSUE TITLE
Avoiding the Temp file

### ISSUE THREAD

**Issue by geoffjukes** [gpac/gpac#852]
Hi,

I have 264mb of M4A files that I am trying to concate into a single file using the `-cat` option. 

Unfortunately I only have 500mb of useable space (it's an AWS Lambda function) and so I collect the files one at a time, 'cat' them into the growing combined file, then clean up. 

This works great until I get close to the 250mb mark, at which point the temp file cannot be created. 

Is there any way to 'cat' the files directly into the target, without creating a temp file first? All the files are 100% the same in encoding, frequency, channels. 

Many thanks,

Geoff

**Comment by geoffjukes** [comment]
The exact command I am using (in a loop) is: `MP4Box -quiet -flat -cat small.m4a combined.m4 -tmp /tmp`

**Comment by geoffjukes** [comment]
I think that something else might be going wrong. The total runtime of the combined file should be 7:58:59, and I have a copy that I made using MP4Box version 5.0. 

I tested the same commands on a server with plenty of room. the 'combined' file came out exactly the same size, but with the same issue - iTunes reports the length as 4:37:08 - but Windows reports the correct runtime. 

I'm running the concat on a Linux host (Ubuntu 16.04)

**Comment by geoffjukes** [comment]
Its a bug. Not sure what. 

Version "MP4Box - GPAC version 0.5.0-rev" works
Version "MP4Box - GPAC version 0.5.2-DEV-revVersion: 0.5.2-426-gc5ad4e4+dfsg5-1build1" does not
Version "MP4Box - GPAC version 0.7.2-DEV-rev105-gbdd7fde-master" does not

**Comment by geoffjukes** [comment]
ok, sorry for all the spam. But I figure this might be useful for others to know. 

Some time between 0.5.0 and 0.5.2, a change was made such that it is necessary to `-add` the first file (to create the new file) before `-cat`ing the subsequent files. I found a hint in an old SF ticket. 

My original question still stands though - can I avoid a temp file when `cat`ing?

**Comment by aureliendavid** [comment]
I don't think it's directly possible to avoid tmp files for this. 

-raw-cat appends directly to the input file but that would result in an invalid file in your case. 

My suggestion would have been to use -tmp /dev/shm to store the temp files in memory instead but it seems like AWS Lambda doesn't provide /dev/shm. 

I suppose your memory is limited too (and I don't know what commands you can run with Lambda), but maybe you can try mounting a tmpfs drive to simulate /dev/shm (like this for example: https://unix.stackexchange.com/a/188540)

**Comment by geoffjukes** [comment]
Thank you for the response, and confirmation. I had explored the tmpfs options, but it's not currently possible :(

Fortunately, I think my primary issue was the `-add`-before-`-cat`. I just tested my edge-case (the large set of files) and the now I've added `-flat` to the command, the resultant file comes in under the 250mb threshold.

Sorry again for the spam, but it helped me solve my issue :)
