### ISSUE TITLE
 Cannot open service: IP Connection Failed while playing live manifest from OSMO MP4CLient

### ISSUE THREAD

**Issue by shreyasreedhar** [gpac/gpac#854]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!
Hi ,

I am trying to play a dynamic (live manifest)using MP4Client GPAC Player. But i hit with the below error 

Version used :gpac-0.6.2-DEV-rev1515-g90e8f49-master-x64
 OS Windows 7 

Enter the absolute URL
http://..../manifest.mpd
[Terminal] Error fetching mime type for URL http://.../manifest.mpd: IP Connection Failed
 Cannot open service: IP Connection Failed

I have run the osmo in administrator mode 
I have firewall allowed for this application
I am able to get the manifest from this http url by putting it in a firefox or chrome browser

Last four lines of help 
        EXPERIMENTAL/UNSTABLE OPTIONS
        C: Enable Streaming Cache
        S: Stops Streaming Cache and save to file
        A: Aborts Streaming Cache
        M: specifies video cache memory for 2D objects

MP4Client - GPAC command line player - version 0.6.2-DEV-rev1515-g90e8f49-mas

GPAC Written by Jean Le Feuvre (c) 2001-2005 - ENST (c) 2005-200X

Please let me know what could be the problem

**Comment by rbouqueau** [comment]
Can you download the mpd from wget or your browser?

**Comment by shreyasreedhar** [comment]
Yes i am able to download the mpd if i give the http://.../.mpd file from a chrome/firefox webbrowser
Its a clear live manifest

**Comment by jeanlf** [comment]
might be a certificate issue, could you try:
```
MP4Client -opt Downloader:AllowBrokenCertificate=yes $URL
```
 ?

**Comment by shreyasreedhar** [comment]
hi , i tried doing this when i give this command and press enter i get the below msgs continuously 

![image](https://user-images.githubusercontent.com/27345798/27283329-59df4abe-5511-11e7-9ae4-c904a6661ba2.png)
![image](https://user-images.githubusercontent.com/27345798/27283344-6a078082-5511-11e7-86a4-afd8b9f78f34.png)

**Comment by jeanlf** [comment]
can you give the command line you used? It seems like the prompt input is incorrect ...

**Comment by shreyasreedhar** [comment]
I issued 
MP4Client -opt Downloader:AllowBrokenCertificate=yes http://..../.mpd 
in the console 
Please let me know if  this is the right way of doing it ?

**Comment by rbouqueau** [comment]
Since the error message is 

> [Terminal] Error fetching mime type for URL http://.../manifest.mpd: IP Connection Failed

1) Can you check what the mime type from your web server is?

2) Could you also post the complete log please? Github accepts attachments.

**Comment by aureliendavid** [comment]
@shreyasreedhar is it still an issue with the latest version?

**Comment by digitalTrilunaire** [comment]
@aureliendavid Did you find a solution or is it just a bad compilation?

**Comment by aureliendavid** [comment]
I don't remember. Is it still an issue?

(I think I was just browsing through the issues to see which ones were still current)

**Comment by digitalTrilunaire** [comment]
It is not an issue. I had a missing package (I don't know which one). I was compiling it with mingw64 program.

**Comment by aureliendavid** [comment]
thanks for the follow-up
