### ISSUE TITLE
Relative position of "Role" element to "ContentProtection" element in manifest is wrong

### ISSUE THREAD

**Issue by sandersaares** [gpac/gpac#855]
DASH specifies a normative XSD with a fixed order of elements. It requires ContentProtection to be present before Role. However, mp4box generates the opposite order.

Version: gpac-0.7.2-DEV-rev133-g732afbe-master-x64
Command: `mp4box.exe -dash-strict 4000 -out out/Manifest.mpd -profile "dashavc264:live" -bs-switching no video-H264-288-400k.mp4:role=main`
Input files: [video-H264-288-400k.zip](https://github.com/gpac/gpac/files/1084433/video-H264-288-400k.zip)

Expected behavior:

```xml
  <AdaptationSet segmentAlignment="true" maxWidth="512" maxHeight="288" maxFrameRate="24" par="16:9" lang="und">
   <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="3018ca15-3a0f-40b4-974d-6557c6542efa"/>
   <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
```

Actual behavior

```xml
  <AdaptationSet segmentAlignment="true" maxWidth="512" maxHeight="288" maxFrameRate="24" par="16:9" lang="und">
   <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
   <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="3018ca15-3a0f-40b4-974d-6557c6542efa"/>
```

Validated with http://dashif.org/conformance

**Comment by jeanlf** [comment]
This should be fixed in GPAC 0.9.0 dev
