### ISSUE TITLE
Availability start time is wrongly mentioned in Manifest file 

### ISSUE THREAD

**Issue by Natarajan92** [gpac/gpac#859]
We are generating mpeg-dash live stream with the help of mp4box and test-engine-live tool. After packaging the manifest file validation gives us error on "Availability Start time" 

Error description: 

Start MPD validation
====================

Line:Col[10:21]:cvc-datatype-valid.1.2.1: ’2017-06-22T07:04:64.750Z’ is not a valid value for ‘dateTime’.
Line:Col[10:21]:cvc-attribute.3: The value ’2017-06-22T07:04:64.750Z’ of attribute ‘availabilityStartTime’ on element ‘MPD’ is not valid with respect to its type, ‘dateTime’.
Line:Col[10:21]:Invalid value 64 for Second field.
MPD validation not successful – DASH is not valid! Invalid 

MPD file is available in this location for your reference - http://www.mediafire.com/file/w6vpmjx5zw3wxpm/live.mpd 

What will be the cause? If any additional details required we will provide you for analysis.

Thanks, 
Natarajan S

- [x] I looked for a similar issue and couldn't find any.

- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by aureliendavid** [comment]
I have no idea how's that possible but it seems like it generated a timestamp where the number of seconds was greater than 60 for `availabilityStartTime` (`07:04:64` is not a valid time..)

What OS are you using? What timezone are you on? I'm guessing if you try to re-generate the mpd the issue disappears?

**Comment by Natarajan92** [comment]
Hi David, 

OS - Red Hat Enterprise Linux Server 6.9 64bit
Time Zone - MDT (Thu Jun 22 04:32:37 MDT 2017)

If we re-process the live stream packaging process, it disappears. But why it cause invalid seconds ? How to confirm it whether it won't repeat in future ? 
This may cause playback problem in some devices too ? 

As you are saying it is related to timestamp, Do we need to change any parameters on encoding or packaging side? . We are using ffmpeg for encoding.
