### ISSUE TITLE
MP4Box exits with "Bad Parameter" error when trying to dash live

### ISSUE THREAD

**Issue by matthew-mahony** [gpac/gpac#860]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X ] I looked for a similar issue and couldn't find any.
- [X ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I am having a problem where mp4box exits early when trying to dash live.  My setup is as follows:
A "remote client" streams from a webcam with ffmpeg:
ffmpeg -f dshow -i video="HP HD Webcam" -f dshow -i audio="Microphone (Realtek High Definition Audio)" -c:v libx264 -r 30 -rtbufsize 100M -f mpegts -movflags frag_keyframe+empty_moov -frag_duration 2 -force_key_frames expr:gte(t,n_forced*2.0) -c:a aac udp://localhost:8080/liveTest

The server reads the stream with ffmpeg, and saves it to a file:
ffmpeg -i udp://localhost:8080/liveTest -c:v libx264 -rtbufsize 100M -an -f mp4 -movflags frag_keyframe+empty_moov -frag_duration 2 -force_key_frames expr:gte(t,n_forced*2.0) d:\test\out.video.mp4 -c:a aac -vn -frag_duration 2 d:\test\out.audio.mp4

And mp4box dashes the video/audio for the DASH-IF player:
MP4Box -dash-live 2000 -rap -frag-rap -subdur 2000 -profile "dashavc264:live" -bs-switching no -dynamic -mpd-refresh 60 -time-shift 10800 -insert-utc -out d:\test\liveTest.mpd d:\test\out.video.mp4 d:\test\out.audio.mp4

Note: I am testing this on a single machine, so the remote client and server are the same for right now.

MP4Box runs for a few iterations, but always exits with an "Error DASHing file: Bad Parameter":
D:\test>mp4box.exe -dash-live 2000 -rap -frag-rap -subdur 2000 -profile "dashavc264:live" -bs-switching no -dynamic -mpd-refresh 60 -time-shift 10800 -insert-utc -out d:\test\liveTest.mpd d:\test\out.video.mp4 d:\svt\videos\aLiveT
est\out.audio.mp4
Live DASH-ing - press 'q' to quit, 's' to save context and quit
[DASH] WARNING! DASH Live profile requested but no -segment-name
        using "%s_dash" by default

DASH-ing files: 2.00s segments 2.00s fragments single sidx per segment
Spliting segments and fragments at GOP boundaries
DASHing file d:\test\out.video.mp4
DASHing file d:\test\out.audio.mp4
[DASH] Segment duration is smaller than required (require 2 s but DASH-ing only 1.98469 s)
[DASH] Generating MPD at time 2017-06-27T22:04:00.297Z
[DASH] Current Period Duration: 2
Next generation scheduled in 1942 ms (DASH time 2000 ms)
Slept for 1942 ms before generation
DASH-ing files: 2.00s segments 2.00s fragments single sidx per segment
Spliting segments and fragments at GOP boundaries
DASHing file d:\test\out.video.mp4
DASHing file d:\test\out.audio.mp4
[DASH] Segment duration is smaller than required (require 2 s but DASH-ing only 1.99791 s)
[DASH] Generating MPD at time 2017-06-27T22:04:02.275Z
[DASH] Current Period Duration: 4
Next generation scheduled in 1964 ms (DASH time 4000 ms)
Slept for 1964 ms before generation
DASH-ing files: 2.00s segments 2.00s fragments single sidx per segment
Spliting segments and fragments at GOP boundaries
DASHing file d:\test\out.video.mp4
[DASH] Segment duration is smaller than required (require 2 s but DASH-ing only 0.466667 s)
DASHing file d:\test\out.audio.mp4
[DASH] Segment duration is smaller than required (require 2 s but DASH-ing only 1.99592 s)
[DASH] Generating MPD at time 2017-06-27T22:04:04.272Z
[DASH] Current Period Duration: 6
Next generation scheduled in 1945 ms (DASH time 5976 ms)
Slept for 1944 ms before generation
DASH-ing files: 2.00s segments 2.00s fragments single sidx per segment
Spliting segments and fragments at GOP boundaries
DASHing file d:\test\out.video.mp4
DASHing file d:\test\out.audio.mp4
[DASH] Segment duration is smaller than required (require 2 s but DASH-ing only 1.99794 s)
[DASH] Generating MPD at time 2017-06-27T22:04:06.255Z
[DASH] Current Period Duration: 8
Next generation scheduled in 1959 ms (DASH time 7973 ms)
Slept for 1958 ms before generation
[DASH] Generating segments and MPD 0.978 seconds too late
DASH-ing files: 2.00s segments 2.00s fragments single sidx per segment
Spliting segments and fragments at GOP boundaries
DASHing file d:\test\out.video.mp4
DASHing file d:\test\out.audio.mp4
Error while DASH-ing file: Bad Parameter
Error DASHing file: Bad Parameter

I ran this in the debugger, and the Bad Parameter error comes from the file stbl_read.c, from the line:
'''
	if (SampleNumber > sdep->sampleCount) return GF_BAD_PARAM;
'''

I noticed before the Bad Parameter error, there was always a previous DASH iteration that dashes less than the expected 2s segment.  (In the above example, one iteration only dashes 0.4667 of the 2s segment).  I wonder if that is the real cause of the problem, and after that happens mp4box is out of sync.  I checked the source video, and verified there are I-frames at every 2s, and nothing in between, so I don't know why mp4box segments at 0.4667s.

The above results are from a code I built today (27-Jun-2017).  Note I built from the gpac_mp4box_mini.sln.  

Also note I don't have the same problem with an old 0.5.2 build from a long time ago.  That build will continue DASHing the file indefinitely.  However, I have a different problem with that build, where it seems mp4box DASHes slightly slower than the playback, so the player eventually gets ahead of the available segments and stops playing.  But that's an old build, and I figure everyone would rather focus on the problem with the most recent build.

**Comment by jeanlf** [comment]
Could you share a test video ?

**Comment by matthew-mahony** [comment]
Here is a video.  Keep in mind this video is recorded live.

When trying to DASH it live, mp4box quit after a little more than 10s:
D:\test>MP4Box -dash-live 2000 -rap -frag-rap -subdur 2000 -profile "dashavc264:live" -bs-switching no -dynamic -mpd-refresh 60 -time-shift 10800 -insert-utc -out d:\test\liveTest.mpd d:\test\out.video.mp4 d:\test\out.audio.mp4
Live DASH-ing - press 'q' to quit, 's' to save context and quit
[DASH] WARNING! DASH Live profile requested but no -segment-name
        using "%s_dash" by default

DASH-ing files: 2.00s segments 2.00s fragments single sidx per segment
Spliting segments and fragments at GOP boundaries
DASHing file d:\test\out.video.mp4
DASHing file d:\test\out.audio.mp4
[DASH] Segment duration is smaller than required (require 2 s but DASH-ing only 1.98469 s)
[DASH] Generating MPD at time 2017-06-28T17:18:03.863Z
[DASH] Current Period Duration: 2
Next generation scheduled in 1929 ms (DASH time 2000 ms)
Slept for 1929 ms before generation
DASH-ing files: 2.00s segments 2.00s fragments single sidx per segment
Spliting segments and fragments at GOP boundaries
DASHing file d:\test\out.video.mp4
DASHing file d:\test\out.audio.mp4
[DASH] Segment duration is smaller than required (require 2 s but DASH-ing only 1.99791 s)
[DASH] Generating MPD at time 2017-06-28T17:18:05.863Z
[DASH] Current Period Duration: 4
Next generation scheduled in 1919 ms (DASH time 4000 ms)
Slept for 1918 ms before generation
DASH-ing files: 2.00s segments 2.00s fragments single sidx per segment
Spliting segments and fragments at GOP boundaries
DASHing file d:\test\out.video.mp4
DASHing file d:\test\out.audio.mp4
[DASH] Segment duration is smaller than required (require 2 s but DASH-ing only 1.99592 s)
[DASH] Generating MPD at time 2017-06-28T17:18:07.854Z
[DASH] Current Period Duration: 6
Next generation scheduled in 1925 ms (DASH time 6000 ms)
Slept for 1925 ms before generation
[DASH] Generating segments and MPD 4.59137e-08 seconds too late
DASH-ing files: 2.00s segments 2.00s fragments single sidx per segment
Spliting segments and fragments at GOP boundaries
DASHing file d:\test\out.video.mp4
DASHing file d:\test\out.audio.mp4
[DASH] Segment duration is smaller than required (require 2 s but DASH-ing only 1.99692 s)
[DASH] Generating MPD at time 2017-06-28T17:18:09.843Z
[DASH] Current Period Duration: 8
Next generation scheduled in 1948 ms (DASH time 8000 ms)
Slept for 1946 ms before generation
DASH-ing files: 2.00s segments 2.00s fragments single sidx per segment
Spliting segments and fragments at GOP boundaries
DASHing file d:\test\out.video.mp4
DASHing file d:\test\out.audio.mp4
[DASH] Segment duration is smaller than required (require 2 s but DASH-ing only 1.99791 s)
[DASH] Generating MPD at time 2017-06-28T17:18:11.919Z
[DASH] Current Period Duration: 10
Next generation scheduled in 1864 ms (DASH time 10000 ms)
Slept for 1864 ms before generation
DASH-ing files: 2.00s segments 2.00s fragments single sidx per segment
Spliting segments and fragments at GOP boundaries
DASHing file d:\test\out.video.mp4
[DASH] Segment duration is smaller than required (require 2 s but DASH-ing only 1.83333 s)
DASHing file d:\test\out.audio.mp4
[DASH] Segment duration is smaller than required (require 2 s but DASH-ing only 1.99592 s)
[DASH] Generating MPD at time 2017-06-28T17:18:13.838Z
[DASH] Current Period Duration: 12
Next generation scheduled in 1917 ms (DASH time 11964 ms)
Slept for 1918 ms before generation
[DASH] Generating segments and MPD 0.965 seconds too late
DASH-ing files: 2.00s segments 2.00s fragments single sidx per segment
Spliting segments and fragments at GOP boundaries
DASHing file d:\test\out.video.mp4
DASHing file d:\test\out.audio.mp4
Error while DASH-ing file: Bad Parameter
Error DASHing file: Bad Parameter


[out.video.zip](https://github.com/gpac/gpac/files/1109771/out.video.zip)

**Comment by matthew-mahony** [comment]
Any ideas on what is going on here?

**Comment by jeanlf** [comment]
Using your test file and current git I cannot reproduce your issue, is this tha case for you?

**Comment by matthew-mahony** [comment]
My issue happens when the file is still be written to.  I found the "-no-cache" argument fixes the problem.  That arguments opens the input file every dash cycle.  I don't know exactly why that fixed the problem, but at least it is working now!

**Comment by jeanlf** [comment]
yes, that option was designed for this use case (might need a better name though)
