### ISSUE TITLE
After some time running the video is freezed (dash-live) [proposed Label] help wanted

### ISSUE THREAD

**Issue by jorgeluengo** [gpac/gpac#862]
After some time running the video is freezed. In my opinion there is something wrong with the the audio video sync but I don't now what is the reason; or maybe It has to do with the GOP length and the -dash-live parameter. The Average GOP length is 48 samples and I was running the following MP4Box command: 
`MP4Box -subdur 6000 -dash-live 2000  -profile "dashavc264:live" -mpd-title "DASH-LIVE stream" -rap -frag-rap -insert-utc -mpd-refresh 6 -time-shift 6 -min-buffer 2000 -bs-switching no -segment-name piece_live%s -dynamic -out reencoded_audiolive.mpd reencoded48_audio.mp4#video reencoded48_audio.mp4#audio`
I read the @rbouqueau article https://gpac.wp.imt.fr/2015/11/02/check-key-frame-alignment-with-mp4box/ but I didn't understood how to configure the GOP and the dash-live DUR parameters. Could someone help me with the relation between GOP and DUR and how to fix this? Thanks!

**Comment by DerouineauNicolas** [comment]
Hi, 
The duration of your segments shoud be a multiple of your GoP duration in seconds (Number of frames in GoP/Video FPS).

**Comment by jorgeluengo** [comment]
Therefore, if the GOP avg is 48, and the fps are 24, it means that the duration should be 2000 milliseconds, is't it? I think that this is what I was doing with "-dash-live 2000", but probably I'm wrong, could you give me some help? Many thanks!

**Comment by DerouineauNicolas** [comment]
It is possible that your video content is using variable GoP length. How was it encoded ?

**Comment by jorgeluengo** [comment]
I don't think so, since the video was encoded using ffmpeg and the following flags: 'keyint=48:min-keyint=48:no-scenecut'.  Any other idea?

**Comment by rbouqueau** [comment]
Can you provide a sample please?

**Comment by jorgeluengo** [comment]
You can download an example from this link. Thanks!
http://ge.tt/9pbtxbl2

**Comment by rbouqueau** [comment]
Thanks. Content seems encoded ok. I let @DerouineauNicolas or any other help you go further.

**Comment by jorgeluengo** [comment]
Thank you @rbouqueau

**Comment by cconcolato** [comment]
Your video has indeed a GoP size of 48 but the video length is 3355 samples, so the last GoP is not of the same duration. This creates some drift after some loops: there is a difference between the number of actual segment being produced by MP4Box and the one computed from the MPD for playback. 

To avoid this problem, you can:
a) edit your input files to make sure your audio and video have the same duration, and that it is an exact multiple of the GoP size
b) or use reencoded48_audio.mp4#video:dur=XXXX where XXXX is a duration that is an exact multiple of the GoP Size.
Note that option b) works but has some issues of efficiency. We are working on it.

**Comment by jorgeluengo** [comment]
I have tried the second option, using using ffmpeg for taking the video length info from it and using this parameter (adjusting it to the GOP size, for this video 138s)  as the dur=XXX. It works for a while but it continue having some freezes. Regarding option a) I didn't find the right option in ffmpeg to do that.  
Any other idea?

**Comment by jorgeluengo** [comment]
This is the MP4Box command that I was using for this:
`MP4Box -subdur 6000 -dash-live 2000 -dash-ctx status  -profile "dashavc264:live" -mpd-title "DASH-LIVE stream" -rap -frag-rap -insert-utc -mpd-refresh 6 -time-shift 6 -min-buffer 2000 -bs-switching no -segment-name piece_$videoName48%s -dynamic -out $videoName.mpd $video#video:dur=$durationSecs $video#audio:dur=$durationSecs`

**Comment by jorgeluengo** [comment]
It works better without adjusting the video length to the GOP size, (139s) for this video, but it doesn't work perfect.

**Comment by cconcolato** [comment]
For option b): The GoP size is 48 in this video. There are 3355 samples, so if you want complete GoP you should have 69 GoPs which make 48*69=3312 frames. The frame rate is 24000/1001, so you should specify a dur of 3312*1001/24000=138.138s. 138 or 139 will give wrong results. I haven't tested though, we may have some precision issues ... It would be better if we could specify the dur in terms of frames. We'll see.

For a), you can try using MP4Box exporting and importing only the needed media duration.

**Comment by jeanlf** [comment]
this should now be fixed , please see #885
