### ISSUE TITLE
Dashing a short subtitle-TTML.xml file to the longer video, splitting not run at the same time?

### ISSUE THREAD

**Issue by Murmur** [gpac/gpac#866]
I have read this topic and various gpac blogs but don't have the clear answer.
https://github.com/gpac/gpac/issues/521

**I have a 3min(180sec) videofile** dashed to 6sec segment files. **I need later run separate processes** to split subtitle-langx-ttml.xml files. **Subtitles don't span over the entire video duration,** some files may have just 00:10-00:40(30sec) of text elements.

What is the best way to serve ttml.xml content so that playback does not interrupt at 00:40 for 404NotFound subtitle.m4s errors?

1.  Use `:dur=180` attribute for subtitle.mp4 input file, do not place an empty placeholder P text element to the end of xml file? Last text element is cloned on remaining segment files however not rendered anymore.
2. Use `:dur=180` attribute for subtitle.mp4 input file, add an empty 1sec begin=00:41/end=00:42 placeholder P text element to the end of xml file? Remaining segment files have an empty text element however not rendered.
3. Modify sub-ttml.xml file to have an empty P text element spanned over begin=00:41/end=03:00 duration? Does not sound a good solution.
4. Something else available in mp4box tool or best practices being used? 

```
mp4box -add subeng.xml:ext=ttml -new temp-subtitles.mp4
mp4box -dash 12000 -mem-frags -profile dashavc264:live
  -bs-switching no -sample-groups-traf -single-traf -subsegs-per-sidx 1
  -segment-name "$RepresentationID$/sub_$Number$$Init=i$"
  -out temp-subtitles.mpd
  "temp-subtitles.mp4:dur=180:id=subeng"
  - - - - -
  <AdaptationSet segmentAlignment="true" lang="eng" mimeType="application/mp4" codecs="stpp" contentType="text">
    <SegmentTemplate timescale="1000" media="$RepresentationID$/sub_$Number$.m4s" startNumber="1" duration="12000" initialization="$RepresentationID$/sub_i.mp4"/>
    <Representation id="sub_eng" startWithSAP="1" bandwidth="1577">
    </Representation>
  </AdaptationSet>  
```

**Comment by nigelmegitt** [comment]
One option is to serve an empty content TTML file for the segments where there is nothing to display. For more details have a look at https://github.com/rbouqueau/TTML_in_MP4_DASH_statement and for examples see https://github.com/rbouqueau/TTML_in_MP4_DASH_statement/wiki/ebuttd_in_isobmff_samples . Some of the samples show the empty TTML document.

**Comment by Murmur** [comment]
Is this something mp4box is able to do at runtime? I have read earlier links you provided but am not sure how should I prepend or append an empty ttml files on appropriate sub-XX.m4s segment numbers.

**Comment by cconcolato** [comment]
In my understanding, mp4box only implements option 1. This should give a correct result. Is this a problem?

**Comment by Murmur** [comment]
I have not run an extensive test on various devices but will do in the coming weeks. I will go for option 1 and not worry about the minor overhead of the remaining segments (carrying the last P element for no use). It is just how DASH wants to work, all representations should have a segment available from the start to finish.

**Comment by Murmur** [comment]
Followup to the previous comment. Do I need to parse ttml.xml source file, generate appropriate sub.media file with a segmentation data I wish to have (possible adding an empty leading and trailing ttml chunks to fill video duration), generate sub.nhml to list byte segmentation offsets. Then use that file as an input for mp4box dash segment generator?

I read this comment about the issue and wondering if this is only way to force `MDAT/TRAF(1-1) single sample` ttml segment files?
https://github.com/gpac/gpac/issues/99

**Comment by jeanlf** [comment]
sorry for the late follow up, any news on your investigations?

**Comment by Murmur** [comment]
I went for option 1 `:dur=180` and not worry about the redundancy data in segments, any extra text payload is nothing compared to video+audio data being downloaded. Clientside is using the dashsj player only so may be differences in ShakaPlayer behaviour is not a concern anymore.

**Comment by jeanlf** [comment]
ok closing for now then. Thanks for the update
