### ISSUE TITLE
DashCast's config file

### ISSUE THREAD

**Issue by irrz** [gpac/gpac#867]
Hello guys,

I have encoded different videos using FFmpeg. Then I wanted to segment them using DashCast, however, I realised that I have to introduce a configuration file.
If I do that, this would mean the encoded files from FFmpeg will be encoded again!!

Is there any way I can disable using -conf option and just make DashCast only doing segmentations for the existing videos. The encoded videos are .mp4 

Thanks

**Comment by jeanlf** [comment]
Nope, you have to use MP4Box to perform the segmentation, DashCast will transcode

**Comment by irrz** [comment]
Thanks a lot
