### ISSUE TITLE
CopyLibs2Public

### ISSUE THREAD

**Issue by ahmadi86** [gpac/gpac#869]
I tried to build GPAC on Windows according to the instructions provided here: 
[Command-line GPAC compiling on Windows (x86) using free Microsoft Visual C++](https://gpac.wp.imt.fr/2011/04/18/command-line-gpac-compiling-on-windows-x86-using-free-microsoft-visual-c/)

The batch file CopyLibs2Public.bat in gpac_extra_libs that you get by calling 
`svn co   svn://svn.code.sf.net/p/gpac/code/trunk/gpac_extra_libs/
`
is old and different than the one stored here: 
http://download.tsi.telecom-paristech.fr/gpac/gpac_extra_libs.zip

Here you can see [the difference](https://www.diffchecker.com/Tq8PemaZ).

Also, in both versions the link https://ftp.mozilla.org/pub/mozilla.org/mozilla.org/xulrunner/releases/7.0.1/sdk/xulrunner-7.0.1.en-US.win32.sdk.zip
is broken and should be replaced by 
https://ftp.mozilla.org/pub/xulrunner/releases/7.0.1/sdk/xulrunner-7.0.1.en-US.win32.sdk.zip

And "dektec_dtapi_5.2.zip" does not exist in gpac_extra_libs folder.

**Comment by aureliendavid** [comment]
I think the one on sourceforge is deprecated. @rbouqueau is that right? Can we remove it?

I've updated the one on http://download.tsi.telecom-paristech.fr/gpac/gpac_extra_libs.zip to a newer version that include fixes for #869 and #870.

**Comment by rbouqueau** [comment]
> I think the one on sourceforge is deprecated. @rbouqueau is that right? Can we remove it?

I think so but it's been a long time for me.

We planned to provide a multi-platform package: https://github.com/rbouqueau/gpac_extra_libs

> I've updated the one on http://download.tsi.telecom-paristech.fr/gpac/gpac_extra_libs.zip to a newer version that include fixes for #869 and #870.

Let's just make sure this is what is written in the docs.

**Comment by aureliendavid** [comment]
I went by this recent-ish commit by jean : https://github.com/gpac/gpac/commit/7f391a64cf801d0df0127edb6ae3653d145c9cca

I also updated the article at https://gpac.wp.imt.fr/2011/04/18/command-line-gpac-compiling-on-windows-x86-using-free-microsoft-visual-c/
