### ISSUE TITLE
Cleanup routine.

### ISSUE THREAD

**Issue by canatella** [gpac/gpac#87]
It would be nice to have a bit of documentation on when it is allowed to call gf_term_disconnect() && gf_term_del() and from which threads. On android, the application can be shutdown at anytime so I need this information to handle correct cleanup of gpac memory.

Thanks,

**Comment by jeanlf** [comment]
Sure we will add this. The basic constraint is that gf_term_disconnect shall not be called from within the main event callback, I will add protection against this in the code

**Comment by rbouqueau** [comment]
Just a word to say we have a autogenerated doxygen while very incomplete (either by lack of doc or simply by formatting):
http://download.tsi.telecom-paristech.fr/gpac/doc/gpac/
http://download.tsi.telecom-paristech.fr/gpac/doc/libgpac/

**Comment by canatella** [comment]
04-03 13:04:03.737  7540  7557 D gpac   : preparing player
04-03 13:04:03.737  7540  7557 V gpac   : gpac/GF_LOG_MUTEX [Mutex veygo_player] At 2129901473 Grabbed by thread Main Process
04-03 13:04:03.737  7540  7557 V gpac   : gpac/GF_LOG_CORE Refreshing list of modules in directory /data/gpac/modules...
04-03 13:04:03.737  7540  7557 V gpac   : gpac/GF_LOG_CORE [Core] Cannot open directory /data/gpac/modules/ for enumeration: 2
04-03 13:04:03.737  7540  7557 V gpac   : gpac/GF_LOG_CORE Loaded 0 modules from directory /data/gpac/modules.
...
04-03 13:04:11.017  7540  7557 V gpac   : disconnected, cleaning up
04-03 13:04:11.017  7540  7557 V gpac   : ./src/cpp/media_player_impl.cpp:622
04-03 13:04:41.387  7540  7557 V gpac   : ./src/cpp/media_player_impl.cpp:626
04-03 13:04:41.507   217   217 I DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-03 13:04:41.507   217   217 I DEBUG   : Build fingerprint: 'oneplus/bacon/A0001:4.4.4/KTU84Q/XNPH05Q:user/release-keys'
04-03 13:04:41.517   217   217 I DEBUG   : Revision: '0'
04-03 13:04:41.517   217   217 I DEBUG   : pid: 7540, tid: 7557, name: Thread-5510  >>> co.veygo.platform.tests <<<
04-03 13:04:41.517   217   217 I DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 35fa2648
04-03 13:04:41.657   217   217 I DEBUG   :     r0 00000000  r1 77d52010  r2 7131ffc8  r3 71322728
04-03 13:04:41.657   217   217 I DEBUG   :     r4 7131ff70  r5 77d52010  r6 00000000  r7 00000001
04-03 13:04:41.657   217   217 I DEBUG   :     r8 76477ae8  r9 76379ee4  sl 76261a88  fp 76477afc
04-03 13:04:41.657   217   217 I DEBUG   :     ip fffffffc  sp 76477a60  lr 756a1573  pc 7569c47c  cpsr 40070030
04-03 13:04:41.657   217   217 I DEBUG   :     d0  0000000000000000  d1  0000000000000000
04-03 13:04:41.657   217   217 I DEBUG   :     d2  0000000000000000  d3  0000000000000000
04-03 13:04:41.657   217   217 I DEBUG   :     d4  fe8000003f000001  d5  000122e800000000
04-03 13:04:41.657   217   217 I DEBUG   :     d6  0000000000000000  d7  00000000000022ec
04-03 13:04:41.657   217   217 I DEBUG   :     d8  0000000000000000  d9  0000000000000000
04-03 13:04:41.657   217   217 I DEBUG   :     d10 0000000000000000  d11 0000000000000000
04-03 13:04:41.657   217   217 I DEBUG   :     d12 0000000000000000  d13 0000000000000000
04-03 13:04:41.657   217   217 I DEBUG   :     d14 0000000000000000  d15 0000000000000000
04-03 13:04:41.657   217   217 I DEBUG   :     d16 77cc484077cc4818  d17 77cc489077cc4868
04-03 13:04:41.657   217   217 I DEBUG   :     d18 0000000000000000  d19 0000000000000000
04-03 13:04:41.657   217   217 I DEBUG   :     d20 0000000000000000  d21 0000000000000000
04-03 13:04:41.657   217   217 I DEBUG   :     d22 0000000000000000  d23 0000000000000000
04-03 13:04:41.657   217   217 I DEBUG   :     d24 0000000000000000  d25 4008000000000000
04-03 13:04:41.657   217   217 I DEBUG   :     d26 4024000000000000  d27 0000000000000001
04-03 13:04:41.657   217   217 I DEBUG   :     d28 00000000000000e6  d29 00000000000000e5
04-03 13:04:41.657   217   217 I DEBUG   :     d30 0000000000000001  d31 4000000000000000
04-03 13:04:41.657   217   217 I DEBUG   :     scr 20000012
04-03 13:04:41.657   217   217 I DEBUG   : 
04-03 13:04:41.657   217   217 I DEBUG   : backtrace:
04-03 13:04:41.657   217   217 I DEBUG   :     /Users/dam/Development/android-ndk-r10b/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-addr2line: 'nil'orm-jni.so
04-03 13:04:41.657   217   217 I DEBUG   :     /Users/dam/Desktop/gpac/gpac/vendor/gpac/src/terminal/network_service.c:1213

04-03 13:04:41.657   217   217 I DEBUG   :     /Users/dam/Desktop/gpac/gpac/vendor/gpac/src/media_tools/dash_client.c:4570

04-03 13:04:41.657   217   217 I DEBUG   :     /Users/dam/Desktop/gpac/gpac/vendor/gpac/src/media_tools/dash_client.c:4616

04-03 13:04:41.657   217   217 I DEBUG   :     /Users/dam/Desktop/gpac/gpac/vendor/gpac/modules/mpd_in/mpd_in.c:1444

04-03 13:04:41.657   217   217 I DEBUG   :     /Users/dam/Desktop/gpac/gpac/vendor/gpac/src/utils/os_module.c:45

04-03 13:04:41.657   217   217 I DEBUG   :     /Users/dam/Desktop/gpac/gpac/vendor/gpac/src/utils/module.c:237

04-03 13:04:41.657   217   217 I DEBUG   :     /Users/dam/Desktop/gpac/gpac/src/cpp/media_player_impl.cpp:628
 (veygo::platform::MediaPlayerImpl::destroy()+56)
04-03 13:04:41.657   217   217 I DEBUG   :     /Users/dam/Desktop/gpac/gpac/djinni/jni/NativeMediaPlayer.cpp:196 (discriminator 1)
 (Java_co_veygo_platform_MediaPlayer_00024CppProxy_native_1release+10)
04-03 13:0

**Comment by jeanlf** [comment]
what are your code sequence for connect/disconnect ? hard to see from the trace. I fixed crashes in calling gf_term_disconnect from the event proc but ibviously this was not it/not enough ...

**Comment by canatella** [comment]
I'm receiving the connect event and then before calling
gf_term_process_step, I call gf_term_disconnect from the main thread.

**Comment by jeanlf** [comment]
this should now be fixed in 1.0, the threading model has been quite modified to avoid such cases
