### ISSUE TITLE
Compiling libfaad on Windows

### ISSUE THREAD

**Issue by ahmadi86** [gpac/gpac#870]
I tried to build gpac_extra_libs on Windows 10, using VS2015 Community. For libfaad, the function `lrintf` is defined in two places:
1. Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\math.h
2. gpac_extra_libs\faad2\libfaad\common.h 

To get it to compile, I commented the second one.

**Comment by aureliendavid** [comment]
thanks, fixed in http://download.tsi.telecom-paristech.fr/gpac/gpac_extra_libs.zip
