### ISSUE TITLE
MP4Box for multiple QP motion constrained HEVC tiles

### ISSUE THREAD

**Issue by 21praveen** [gpac/gpac#875]
I am trying to create a motion constrained segmented video for HEVC Tile-based adaptation. 

I encoded them into 4 QP using kvazaar. 

kvazaar --input YachtRide_1920x1080_120fps_420_8bit_YUV.yuv  --tiles 3x3 --slices tiles --mv-constraint frametilemargin --qp 25 --output out1.hevc

kvazaar --input YachtRide_1920x1080_120fps_420_8bit_YUV.yuv  --tiles 3x3 --slices tiles --mv-constraint frametilemargin --qp 30 --output out2.hevc

kvazaar --input YachtRide_1920x1080_120fps_420_8bit_YUV.yuv  --tiles 3x3 --slices tiles --mv-constraint frametilemargin --qp 35 --output out3.hevc

kvazaar --input YachtRide_1920x1080_120fps_420_8bit_YUV.yuv  --tiles 3x3 --slices tiles --mv-constraint frametilemargin --qp 40 --output out4.hevc

Then I used MP4BOX for packaging.

MP4Box -add out1.hevc:split_tiles -new video_tiled1.mp4

MP4Box -add out2.hevc:split_tiles -new video_tiled2.mp4

MP4Box -add out3.hevc:split_tiles -new video_tiled3.mp4

MP4Box -add out4.hevc:split_tiles -new video_tiled4.mp4

Finally DASHing them as : 
MP4Box -dash 1000 -profile live -out t.mpd video_tiled1.mp4 video_tiled2.mp4 video_tiled3.mp4 video_tiled4.mp4

The output thus generated is showing only one quality and is not able to switch to other quality while being played through MP4Client. 
 I verified the configuration of MP4Client by the sample given at http://download.tsi.telecom-paristech.fr/gpac/SRD/srd_hevc/multi_rate_p60/hevc_srd.mpd, where the player is showing other quality as well and able to change the quality level through GUI.  Am I DASHing the video in wrong way?

**Comment by jeanlf** [comment]
You cannot change the QP between tiled qualities, this will change the PPS, so combining the tiles will no longer work (see section on DASH in https://gpac.wp.imt.fr/2017/02/01/hevc-tile-based-adaptation-guide/) . You need to play with the target bitrate of the encoder. Using different QPs  could be possible by enforcing diffferent PPS IDs at the encoder level for each tiles, but this has not been tested at all.
