### ISSUE TITLE
DashCast - sincronize output folder with ftp?

### ISSUE THREAD

**Issue by chanof** [gpac/gpac#876]
Hi there, I'm trying to create a live with dashcast, I want to understand if the dashcast process that create output folder should take place on the web server or whether I can sync the output on my computer with an ftp on a webserver. This cause i don't have a webserver and i want to use an hosting service for the media distribution
Thanks a lot

**Comment by jeanlf** [comment]
You should be able to sync the output to your server, provided that you do the sync quite often, at least at the DASH segment duration.

**Comment by chanof** [comment]
Thanks for support!
