### ISSUE TITLE
Error: styp-1 "violates Section 7.3.1. of ISO/IEC 23009-1:2012(E)"

### ISSUE THREAD

**Issue by Natarajan92** [gpac/gpac#877]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

We are creating dash live stream with mp4box and packaging commands are below 

**MP4Box -logs all@error -dash-ctx /mnt/test/livestream/dash-live.txt -tmp /mnt/test/liveStream/ -dash 4800 -frag 4800 -rap -frag-rap -ast-offset 0 -mpd-refresh 4 -bs-switching no -min-buffer 4800 -url-template -time-shift 120 -mpd-info-url http://127.0.0.1:8080/ -segment-name live_$RepresentationID$_ -out /mnt/test/livestream/live.mpd -dynamic -subsegs-per-sidx -1 <inputs>**

When we validate our live stream url in this validator (http://dashif.org/conformance.html), We are seeing Errors and warnings. 

How to solve this errors and warnings ? 

**Error details:** 

WARNING: unknown mvex atom 'trep'
### Brand 'lmsg' found as a compatible brand for segment number 2 (not the last segment 6); violates Section 7.3.1. of ISO/IEC 23009-1:2012(E): In all cases for which a Representation contains more than one Media Segment ... If the Media Segment is not the last Media Segment in the Representation, the 'lmsg' compatibility brand shall not be present.
tfdt base media decode time 323552.100089 not equal to accumulated decode time 0.000000 for track 256 for the first fragment of the movie. This software does not handle incomplete presentations. Applying correction.

**Comment by jeanlf** [comment]
this should be fixed in 0.9.0 DEV
