### ISSUE TITLE
Audio streaming

### ISSUE THREAD

**Issue by chanof** [gpac/gpac#878]
Hi, for the first test i would try to send only audio, an wav file into dashcast live.media
I use the code below
DashCast -a piano2.wav  -seg-dur 100  -live-media

The audio streamed result "segmented" also by listen

These are the error occurred
Unable to delete the file output/a1_1082_gpac.m4s
[audio_encoder] UTC dur 100733 bigger than segment duration 1183 - some frame where probably lost. Adjusting

Someone know how to fix it?
Thanks!

**Comment by jeanlf** [comment]
Dashcast is now deprecated, please use GPAC 0.9.0
