### ISSUE TITLE
ADTS AAC extracted by MP4Box from M4A with 7.1 channels reported as only 5.0 channels

### ISSUE THREAD

**Issue by LigH-de** [gpac/gpac#881]
Might be related to #183 - reason may be same or different.

Samples available at: http://www.mediafire.com/?9lz533ddlj111

According to a report in a German video forum, using MP4Box to extract raw streams from an MP4 video with 7.1 channel AAC results in a raw AAC audio file which is detected as only 5.0 channel by MediaInfo and ffmpeg (ffplay), and MPC-HC (using LAV Filters natively as decoders, which are based on ffmpeg/libav*) gets stuck when playing an MKV multiplexed with this audio using mkvtoolnix; but VLC can play the remux.

To test this issue, I downloaded some [Dolby TrueHD trailers](https://thedigitaltheater.com/index.php/dolby-trailers/), extracted the 7.1 THD audio with conversion to FLAC using eac3to v3.31, converted the FLAC audio to LC-AAC in MeGUI using QAAC x64 v2.64 (CoreAudioToolbox 7.10.9.0 from iTunes installer), then extracted the AAC to raw/ADTS files using MP4Box from gpac-0.7.2-DEV-rev206-gf32d687-master-x64 (`mp4box -raw * ~.m4a`).

The sample archives in the MediaFire folder linked above contain all intermediate files and verbose reports generated by MediaInfo 0.7.97 (CLI, 2017-06-29) and ffprobe (N-86720-gf1baafac71, 2017-07-06).

_Brief snippets:_

**M4A:**

```
Complete name                            : Dolby_Catalyst_Lossless-thedigitaltheater.mkv.m4a
Format                                   : MPEG-4

Channel(s)                               : 8
Channel(s)                               : 8 channels
Channel positions                        : Front: L C R, Side: L R, Back: L R, LFE
Channel positions                        : 3/2/2.1
ChannelLayout                            : C L R Ls Rs Rls Rrs LFE
```

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Dolby_Catalyst_Lossless-thedigitaltheater.mkv.m4a':

    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 7.1, fltp, 367 kb/s (default)
```

**ADTS:**

```
Complete name                            : Dolby_Catalyst_Lossless-thedigitaltheater.mkv_track1.aac
Format                                   : ADTS

Channel(s)                               : 5
Channel(s)                               : 5 channels
Channel positions                        : Front: L C R, Side: L R
Channel positions                        : 3/2/0
ChannelLayout                            : C L R Ls Rs
```

```
[aac @ 0000000002626480] channel element 1.2 is not allocated
    Last message repeated 612 times
[aac @ 0000000002613dc0] decoding for stream 0 failed
[aac @ 0000000002613dc0] Estimating duration from bitrate, this may be inaccurate
[aac @ 0000000002613dc0] Could not find codec parameters for stream 0 (Audio: aac (LC), 5.0, fltp, 11 kb/s): unspecified sample rate
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, aac, from 'Dolby_Catalyst_Lossless-thedigitaltheater.mkv_track1.aac':
  Duration: 00:06:56.09, bitrate: 11 kb/s
    Stream #0:0: Audio: aac (LC), 5.0, fltp, 11 kb/s
```

**Comment by LigH-de** [comment]
MeGUI: [logfile-17-07-21_10-33-34.txt](https://github.com/gpac/gpac/files/1165100/logfile-17-07-21_10-33-34.txt)

**Comment by hydra44** [comment]
I can confirm the same behaviour on my system

**Comment by rbouqueau** [comment]
It seems like:

 - The original MP4 from CoreAudioToolbox signals 7.1. But GPAC only detects 5.0:
```
D:\Works\gpac\issues\881_aac_5.0_7.1\src>MP4Box -info Dolby_Catalyst_Lossless-thedigitaltheater.mkv.m4a
* Movie Info *
        Timescale 48000 - 1 track
        Computed Duration 00:00:13.077 - Indicated Duration 00:00:13.077
        Fragmented File: no
        File suitable for progressive download (moov before mdat)
        File Brand M4A  - version 0
                Compatible brands: M4A  mp42 isom
        Created: GMT Fri Jul 21 08:34:54 2017
        Modified: GMT Fri Jul 21 08:34:55 2017

File has no MPEG4 IOD/OD

iTunes Info:
        Encoder Software: qaac 2.64, CoreAudioToolbox 7.10.9.0, AAC-LC Encoder, TVBR q91, Quality 96
1 UDTA types: meta (1)

Track # 1 Info - TrackID 1 - TimeScale 48000
Media Duration 00:00:13.077 - Indicated Duration 00:00:13.077
Media Info: Language "Undetermined (und)" - Type "soun:mp4a" - 613 samples
MPEG-4 Config: Audio Stream - ObjectTypeIndication 0x40
MPEG-4 Audio AAC LC - 5 Channel(s) - SampleRate 48000
Self-synchronized
        RFC6381 Codec Parameters: mp4a.40.2
        All samples are sync
```

 - Extraction and reimport with MP4Box confirm:
```
D:\Works\gpac\issues\881_aac_5.0_7.1\src>MP4Box -raw 1 D:\Works\gpac\issues\881_aac_5.0_7.1\src\Dolby_Catalyst_Lossless-thedigitaltheater.mkv.m4a
Extracting MPEG-4 AAC

D:\Works\gpac\issues\881_aac_5.0_7.1\src>MP4Box -raw 1 D:\Works\gpac\issues\881_aac_5.0_7.1\src\Dolby_Catalyst_Lossless-thedigitalthe
ater.mkv.m4a
D:\Works\gpac\issues\881_aac_5.0_7.1\src>MP4Box -add D:\Works\gpac\issues\881_aac_5.0_7.1\src\Dolby_Catalyst_Lossless-thedigitaltheater.mkv_track1.aac -new tmp.mp4
AAC ADTS import  - sample rate 48000 - MPEG-4 audio - 5 channels
```

 - The extracted AAC and reimported MP4 have 5 channels only with MP4Box and MediaInfo.
 - FFmpeg can handle the file correctly.

 - However I note that file sizes are very close (may be a clue ):
```
21/07/2017  10:34           605 014 Dolby_Catalyst_Lossless-thedigitaltheater.mkv.m4a
09/08/2017  17:53           604 633 Dolby_Catalyst_Lossless-thedigitaltheater.mkv_track1.aac
09/08/2017  17:54           603 636 tmp.mp4
```

@jeanlf I let you go further in this as this is related to an issue you previously solved.

**Comment by LigH-de** [comment]
I wonder whether there is a difference between header fields in the M4A container and the AAC content, respectively the ADTS "raw" output — or the structure of the AAC content is slightly off standards, and only a more "tolerant" code (trying different interpretations of variable-length fields) can handle it.

Are there any CLI parameters for MP4Box, or additional 3rd-party tools, which will report most verbosely how M4A and ADTS headers are interpreted? Or would that require running MP4Box in a source project in a debugging session with watched variables, so a user-only (non-developer) can't easily help?

**Comment by jeanlf** [comment]
ADTS is not a really good container for multi-channel, as it can only signal up to 7 channels. Exporting MC-AAC should be done using LATM, which keeps the AAC config.
That being said, the 5 is what we read from the audio config in the file (2 front, 2 back, 1 lfe), not sure why we don't see the same channel count as others. I'll dig into that

**Comment by jeanlf** [comment]
got it, we forgot cpe count, this should now be fixed. Thanks for the files and detailed report
