### ISSUE TITLE
Dashcast can't loop due to non-strictly-monotonic PTS

### ISSUE THREAD

**Issue by chanof** [gpac/gpac#882]
HI there ,I sent a live-media, but i have two issues, dashcast can't loop video or audio transmissions due to 
[libx264] non-strictly-monotonic PTS 
Invalid DTS..
Someone could help me?
The second one issues is that i can't run -av transmissions
The audio encoder error occured UTC dur bigger then segment duration
Thanks in advance
Gianmaria

**Comment by jeanlf** [comment]
dashcast is now deprecated, use GPAC 0.9.0 DEV
