### ISSUE TITLE
mp4box crashes on Windows 10

### ISSUE THREAD

**Issue by uwillmore** [gpac/gpac#884]
I recently started using mp4box, after it was recommended to me on the ffmpeg user email list.to extract the raw video from an AVI video and then use ffmpeg to extract the audio and combine it with the raw video to get the scaled mp4 video I need. Alas, I am having problems with mp4box.

I first downloaded the windows version in 64 bit format from this site:
https://gpac.wp.imt.fr/downloads/
but whenever I tried to run any command, it crashes with this message from Windows:

**mp4box has stopped working. A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.**

So I downloaded the 32 bit version and that worked fine for me while I was processing small files. But yesterday, I tried to extract raw video from a 700,000 kb file and the 32 bit version of mp4box crashed with the same message from Windows (see above).

So I downloaded the latest versions (32 bit and 64 bit for Windows)  from the daily build site (https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/) and tried again, but got the same results. The 64 bit version doesn't work at all and the 32 bit version only works on small files. I tried this with revision 195, the first one in the list of files available for download on the nightly builds page and with revision 200, hoping that the higher revision number may indicate that this is the latest revision, not the first one in the list. 

I tried starting the debugger when I got the error message, but since I don't have the source code I don't get much info. The debugger says the problem was caused by an unhandled exception, but that's all it can tell without source code.
The system Application log also shows and error but gain, there is no useful information other than the application (mp4box) and the time of the error. The log can't record what the application does not pass on. 

BTW, the mp4box command I am using is:
mp4box -aviraw audio hd.avi

The video is NOT interlaced, although it is supposed to be, which is why I need to extract the raw video before I can scale it using ffmpeg. 
I tried attaching my test file but I was told that you don't support that file type.   So if you want to get my test file called hd.avi, you can get it here:
https://www.dropbox.com/sh/61kb841ayiwj28l/AAC46KAoNSCiI85LwFjM9tpba?dl=0

Just remember the 64 bit version crashed even on the small test video, while the 32 bit version runs fine on the small file. I can provide a larger file if you need one, but I don't have the space on my dropbox page. I would need ftp access or something like that to give you a copy of one of my larger videos. 

I am running Windows 10 Pro 64 bit version, with 16 GB of ram and an Intel i7 CPU.

I really need to solve this ASAP. So if there is something I can do to get either version to work, let me know. And if I did not include some detail you need, just contact me and I will try to provide the info you need.

Thanks
URW
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ x] I looked for a similar issue and couldn't find any.
- [ x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by aureliendavid** [comment]
I think I found what caused the crash. 

Can you retest with this version: https://download.tsi.telecom-paristech.fr/gpac/latest_builds/win64/gpac-0.7.2-DEV-rev208-g90af13a-master-x64.exe ? 

On my system it now correctly extracts the pcm audio from your file (playable with audacity for example).

**Comment by uwillmore** [comment]
Hi there,




And thanks for working on this and getting back to me so quickly.




Unfortunately,  I don't have a long avi video at home, so I can't test until I get to the office on Monday. But I will download and test the new version as soon as I get in on Monday and get back to you as soon as I tested.




Thanks again for responding so quickly




Ute




Get Outlook for Android







From: A. David


Sent: Friday, July 28, 04:12


Subject: Re: [gpac/gpac] mp4box crashes on Windows 10 (#884)


To: gpac/gpac


Cc: uwillmore, Author






I think I found what caused the crash.




Can you retest with this version: https://download.tsi.telecom-paristech.fr/gpac/latest_builds/win64/gpac-0.7.2-DEV-rev208-g90af13a-master-x64.exe ?




On my system it now correctly extracts the pcm audio from your file (playable with audacity for example).

**Comment by uwillmore** [comment]
Yes you did find and fix the problem!  I just finished testing and even the largest video I have (3.5 GP) is no problem for the new version you created.




Thank you so very much for taking care of this so quickly! When I reported the bug on Thursday, I thought it would be weeks or months before I would heard anything more about this. So I was very surprised when I found you message in my spam folder on Saturday. 




Now that we have a working version, I have a couple of questions.




When will you fix the 32 bit version and when will you release these new versions? I would like to get the official version, and since some of our clients run old systems,  we would prefer to use the 32 bit version.






I know we need to get a license but my supervisor will take care of that. My guess is that he'll want to wait until the official 32 bit release is fixed or he at least knows when that will happen, before he starts the process of obtaining a license.




Again, thank you so much for fixings this problem for me. You saved me a lot of work, stress and headaches trying to find a replacement for mp4box.




Sincerely,




Ute Willmore 


Get Outlook for Android







From: A. David


Sent: Friday, July 28, 04:12


Subject: Re: [gpac/gpac] mp4box crashes on Windows 10 (#884)


To: gpac/gpac


Cc: uwillmore, Author






I think I found what caused the crash.




Can you retest with this version: https://download.tsi.telecom-paristech.fr/gpac/latest_builds/win64/gpac-0.7.2-DEV-rev208-g90af13a-master-x64.exe ?




On my system it now correctly extracts t pcm audio from your file (playable with audacity for example).

**Comment by aureliendavid** [comment]
all versions should now include this fix, including win32 builds - so you can use any of the files at https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/ where revNNN NNN>=208

**Comment by uwillmore** [comment]
Thank you very much!  You have been great!




Ute Willmore




Get Outlook for Android







On Tue, Aug 1, 2017 at 12:32 AM -0600, "A. David" <notifications@github.com> wrote:












all versions should now include this fix, including win32 builds - so you can use any of the files at https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/ where revNNN NNN>=208
