### ISSUE TITLE
Clock drift and 404 issues in live DASH simulator

### ISSUE THREAD

**Issue by jeanlf** [gpac/gpac#885]
The DASH live simulator has been modified to fix a number of different issues:
- non-aligned audio and video durations would cause desync after a few loops
- forcing duration of media input was not properly working
- drift would occur between the media timeline (ie tfdt) and the MPD segment startTime when using templates without segment timeline, causing potential 404 and other weird behaviours in seek requests

We also added the possibility to force a new period rather than looping the source content (using -no-loop switch)

This should fix quite a few issues on the live simulator, but don't hesitate to reopen this issue if needed.

**Comment by Natarajan92** [comment]
Hi Jeanlf

Thanks for your commit on this to rectify the errors soon, But when we try to package asset with your latest commit we are getting error.

Command used - 

MP4Box -dash 4000 -rap -frag-rap -sample-groups-traf -profile onDemand -bs-switching no /Channel2/video1_19.ts -out /EvoChannel2/live.mpd

**Error : 
MP4Box: symbol lookup error: MP4Box: undefined symbol: gf_dasher_enable_cached_inputs**


MP4Box - GPAC version 0.7.2-DEV-revUNKNOWN_REV
Cloned from git - https://github.com/gpac/gpac/tree/53296c0

If anything is wrong on our side let us know

**Comment by aureliendavid** [comment]
If you built it from source this is probably due to an incomplete build or a binary linked against an old libgpac library. 

You can try to do a full rebuild or use a pre-built version at https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/
