### ISSUE TITLE
Playing 360 video side by side

### ISSUE THREAD

**Issue by kaushik-ayinala** [gpac/gpac#889]
Does GPAC support playing 360 degree video side by side ?, So that we can watch videos directly with HMD (Head Mounted Display).  

If GPAC does not support then can you give me some pointers on how to extend/modify the GPAC to play videos side by side?.

Thanks for help in advance.

**Comment by jeanlf** [comment]
Yes, you need to modify the StereoType key to SideBySide or StereoHeadset (cf doc/configuration.html):

`MP4Client -opt Compositor:StereoType=SideBySide -Compositor:NumViews=2 $URL`
