### ISSUE TITLE
MP4box adds 0 value  btrt atom to ISMA file. 

### ISSUE THREAD

**Issue by exxamedia** [gpac/gpac#895]
Tried using GPAC 0.7.2 32-bit build for Windows. Looking to add a properly populated btrt atom to an encoded file.

Encoded a file with FFmpeg using x264, ran through `MP4Box -isma -out 47.mp4`

Output attached. [out_47.zip](https://github.com/gpac/gpac/files/1209849/out_47.zip)

Please advise how to properly create BTRT atom in MP4 and populate its values appropriately. Thank you!

**Comment by aureliendavid** [comment]
A btrt is added when importing an avc/hevc element to a mp4, so if you have an already encoded file you can run 

`MP4Box -add <input_file> -new <out_file.mp4>`

even if the input_file is alreay an mp4. 

The out_file should have a btrt box filled with its values.
