### ISSUE TITLE
Play encoded .mp4

### ISSUE THREAD

**Issue by UltraDosaaf** [gpac/gpac#896]
Is there any chance to decode [this video](https://github.com/gpac/gpac/files/1210948/videocam_1501316.zip) using GPAC? The most successfull tool that I've been used to extract video info says: "No movie found in the file".

PS: the file header in HexEditor looks like this:

![2017-08-09_12-17-13](https://user-images.githubusercontent.com/25608313/29114378-60cf42ba-7cf4-11e7-9306-a65d4b8147ed.png)

**Comment by rbouqueau** [comment]
It won't play because the file is seriously truncated.

**Comment by UltraDosaaf** [comment]
You mean it is just one piece of viedo file?

**Comment by rbouqueau** [comment]
I mean that the file is incomplete. It is not a valid mp4 file.

**Comment by aureliendavid** [comment]
if the file corrupted nothing can be done
