### ISSUE TITLE
Question about GPAC's hybrid broadcast broadband demo

### ISSUE THREAD

**Issue by bayantaani** [gpac/gpac#899]
I have been following GPAC's demo on hybrid broadcast broadband of UHD SHVC video streams:
http://download.tsi.telecom-paristech.fr/gpac/demos_hybrid/

In the demo, the base layer is broadcasted in TS format using multicast UDP, while the enhancement layer is sent in a DASH session. On the client side, MP4Client is able to play the video with both layers (which are sent separately) in sync. My question is how does MP4Client take 2 separate streams and play them out in sync? which part of the client source code is responsible for that?

**Comment by bayantaani** [comment]
@pclouds @tieleman @wiiaboo @kazuki @fcartegnie 
Can you please take a look at my question?

**Comment by jeanlf** [comment]
We use TEMI extensions in TS to carry the location of the DASH session as well as the timecode of the media stream in the MP4. Most of the code in charge of external media handling and sync'ing is at the end of  gpac/src/terminal/scene.c
