### ISSUE TITLE
Bug lang attribute

### ISSUE THREAD

**Issue by amuth** [gpac/gpac#900]
I only changed the position of "lang" attribute for both commands.

On the second command I get an error message:
 "The given code is not a valid one: ENG:name=englischer Untertitel (erzwungen):, using 'und' as 3-letter code..."

mp4box.exe -inter 500 -par 1=1:1 -add "d:\test.hevc#1:name=H265" -add "d:\test.srt#1:name=englischer Untertitel (erzwungen):lang=ENG:txtflags=0xC0000000" -new "D:\test_muxed.mp4"

mp4box.exe -inter 500 -par 1=1:1 -add "d:\test.hevc#1:name=H265" -add "d:\test.srt#1:lang=ENG:name=englischer Untertitel (erzwungen):txtflags=0xC0000000" -new "D:\test_muxed.mp4"

**Comment by aureliendavid** [comment]
Good catch, thanks. 

Should be fixed now (in rev >= 231).
