### ISSUE TITLE
MPD is not as expected when context file is used while converting MP4 to DASH

### ISSUE THREAD

**Issue by anitac19sep** [gpac/gpac#903]
Hi,

We want to package multiple MP4 files (of 10 seconds each) into DASH content such that the resolution may vary across these files. We are indicating the discontinuity of resolution by inserting a new period in MPD. Further, we are using -dash-ctx option and multiple MP4Box commands to achieve this. Please find the 4 commands below that we used to package 4 different MP4 files of 10 seconds each.

```
Command1: MP4Box -quiet -dash-strict 10000 -rap -dash-scale 1000 -tfdt 0 -moof-sn 0 -subsegs-per-sidx -1 -mpd-title "dash-chunked-transcode" -dash-ctx ctx.txt -mpd-info-url abc.com -segment-name test_0 input_480_270_1159kbps.mp4:period=0:id=0 -out manifest.mpd
Command2: MP4Box -quiet -dash-strict 10000 -rap -dash-scale 1000 -tfdt 10000 -subsegs-per-sidx -1 -mpd-title "dash-chunked-transcode" -dash-ctx ctx.txt -mpd-info-url abc.com -segment-name test_0 input_480_270_1133kbps.mp4:period=0:id=0 -out manifest.mpd
Command3: MP4Box -quiet -dash-strict 10000 -rap -dash-scale 1000 -tfdt 20000 -moof-sn 2 -subsegs-per-sidx -1 -mpd-title "dash-chunked-transcode" -dash-ctx ctx.txt -mpd-info-url abc.com -segment-name test_1 input_768_432_785kbps.mp4:period=1:id=0 -out manifest.mpd
Command4: MP4Box -quiet -dash-strict 10000 -rap -dash-scale 1000 -tfdt 30000 -subsegs-per-sidx -1 -mpd-title "dash-chunked-transcode" -dash-ctx ctx.txt -mpd-info-url abc.com -segment-name test_1 input_768_432_783kbps.mp4:period=1:id=0 -out manifest.mpd
```

Please note the manifest file at the end of each command with GPAC version 0.7.1:
Same is present at [Observations_GPACv0.7.1.zip](https://github.com/gpac/gpac/files/1292113/Observations_GPACv0.7.1.zip)

Note the SegmentList within manifest file post Command3 (complete manifest file is present in the directory Command3_Segment11). 
```
<Period id="0" duration="PT0H0M20.000S">
	<SegmentList timescale="12800" duration="128000">
		<Initialization sourceURL="test_0init.mp4"/>
		<SegmentURL media="test_01.m4s"/>
		<SegmentURL media="test_02.m4s"/>
	</SegmentList>
</Period>
<Period id="1" duration="PT0H0M10.000S">
	<SegmentList timescale="12800" duration="128000">
		<Initialization sourceURL="test_1init.mp4"/>
		<SegmentURL media="test_01.m4s"/>
		<SegmentURL media="test_02.m4s"/>
		<SegmentURL media="test_11.m4s"/>
	</SegmentList>
</Period>
```
My question is that, why does period 1 has 3 segments? I expected it to have only test_11.m4s. Looks like GPAC maintains this list of segment internally and doesn't clear when new period starts.

Additional information:
1. How I obtained GPAC: 
Downloaded using the command: wget https://github.com/gpac/gpac/archive/v0.7.1.tar.gz
Built the same post that.

2. Operating System: CentOS Linux release 7.1 64 bit

3. Application used: MP4Box

4. GPAC version: 
MP4Box - GPAC version 0.7.1-revrelease

Further, I tried executing the four commands with the latest nightly build of GPAC. (GPAC version 0.7.2-DEV-revUNKNOWN_REV). Behaviour with this version is little different. 
Note the SegmentList within manifest file post Command3 (complete manifest file is present in the directory Command3_Segment11 inside 
[Observations_GPACv0.7.2-DEV.zip](https://github.com/gpac/gpac/files/1292247/Observations_GPACv0.7.2-DEV.zip)
).
```
<Period id="0" duration="PT0H0M10.000S">
	<SegmentList timescale="12800" duration="128000">
		<Initialization sourceURL="test_0init.mp4"/>
		<SegmentURL media="test_01.m4s"/>
		<SegmentURL media="test_01.m4s"/>
	</SegmentList>
</Period>
<Period id="1" start="PT0H0M10.000S" duration="PT0H0M10.000S">
	<SegmentList timescale="12800" duration="128000">
		<Initialization sourceURL="test_1init.mp4"/>
		<SegmentURL media="test_01.m4s"/>
		<SegmentURL media="test_11.m4s"/>
	</AdaptationSet>
</Period>
```
I expected it to have only test_11.m4s in period 1, but it has both test_01.m4s and test_11.m4s. Which looks wrong.

Regards,
Anita

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by jeanlf** [comment]
This should have been fixed in 0.9.0, please test and reopen if needed
