### ISSUE TITLE
IOS build issue: gpac_extra_libs/js/src/jstypes.h:231:14: fatal error: 'jsautocfg.h' file not found

### ISSUE THREAD

**Issue by MaxBotvinevDemo** [gpac/gpac#904]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by MaxBotvinevDemo** [comment]
Hi 
I have a problem when build for IOS
../gpac_extra_libs/js/src/jstypes.h:231:14: fatal error: 'jsautocfg.h' file not found

There is such file (jsautocfg.h) in ../build/android directory. But not in ../js/src

Can you give a clue?

**Comment by MaxBotvinevDemo** [comment]
If I copy jsautocfg to ../js/src there is another issue:

../gpac_extra_libs/libjpg/jerror.c:78:3: error: 
      implicitly declaring library function 'exit' with type 'void (int)
      __attribute__((noreturn))' [-Werror,-Wimplicit-function-declaration]

**Comment by aureliendavid** [comment]
I think you may be using an outdated version of the extra_libs package, because we're not supposed to include jsautocfg.h in jstypes.h. 

Did you download it recently here: http://download.tsi.telecom-paristech.fr/gpac/gpac_extra_libs.zip ?

If not can you retry with this package?
