### ISSUE TITLE
Better support for iOS 11-generated HEIF/HEIC

### ISSUE THREAD

**Issue by avibrazil** [gpac/gpac#905]
Apparently, MP4Box does not support HEIF/HEIC as generated by iOS 11 devices. Here are samples I took with my iPhone 7+ myself, useful for tests and debug.

https://avi.alkalay.net/clipboard/HEIF-iOS-11.zip

Zip file contains videos, regular photos, photos with depth and photo bursts.

I'm particularly interested in MP4Box support for iOS 11 HEIF tags and metadata.

This is what I get with GPAC 0.6.1 on Fedora Linux:

```
$ MP4Box -info IMG_4453.HEIC
[iso file] Read Box "infe" failed (Invalid IsoMedia File)
[iso file] Read Box "iinf" failed (Invalid IsoMedia File)
[iso file] Read Box "meta" failed (Invalid IsoMedia File)
Error opening file IMG_4453.HEIC: Invalid IsoMedia File
```

And this is 0.7.1:

```
$ MP4Box -info IMG_4449.HEIC
ESC[33mICC colour profile not supported
ESC[0mESC[33mICC colour profile not supported
ESC[0mRoot Meta type: "pict" - 55 resource item(s)
Primary Item - ID 49
Item #1 - ID 1 - Name:
Item #2 - ID 2 - Name:
Item #3 - ID 3 - Name:
Item #4 - ID 4 - Name:
Item #5 - ID 5 - Name:
Item #6 - ID 6 - Name:
Item #7 - ID 7 - Name:
Item #8 - ID 8 - Name:
Item #9 - ID 9 - Name:
Item #10 - ID 10 - Name:
Item #11 - ID 11 - Name:
Item #12 - ID 12 - Name:
Item #13 - ID 13 - Name:
Item #14 - ID 14 - Name:
Item #15 - ID 15 - Name:
Item #16 - ID 16 - Name:
Item #17 - ID 17 - Name:
Item #18 - ID 18 - Name:
Item #19 - ID 19 - Name:
Item #20 - ID 20 - Name:
Item #21 - ID 21 - Name:
Item #22 - ID 22 - Name:
Item #23 - ID 23 - Name:
Item #24 - ID 24 - Name:
Item #25 - ID 25 - Name:
Item #26 - ID 26 - Name:
Item #27 - ID 27 - Name:
Item #28 - ID 28 - Name:
Item #29 - ID 29 - Name:
Item #30 - ID 30 - Name:
Item #31 - ID 31 - Name:
Item #32 - ID 32 - Name:
Item #33 - ID 33 - Name:
Item #34 - ID 34 - Name:
Item #35 - ID 35 - Name:
Item #36 - ID 36 - Name:
Item #37 - ID 37 - Name:
Item #38 - ID 38 - Name:
Item #39 - ID 39 - Name:
Item #40 - ID 40 - Name:
Item #41 - ID 41 - Name:
Item #42 - ID 42 - Name:
Item #43 - ID 43 - Name:
Item #44 - ID 44 - Name:
Item #45 - ID 45 - Name:
Item #46 - ID 46 - Name:
Item #47 - ID 47 - Name:
Item #48 - ID 48 - Name:
Item #49 - ID 49 - Name:
Item #50 - ID 50 - Name:
Item #51 - ID 51 - Name:
Item #52 - ID 52 - Name:  - MimeType: application/rdf+xml
Item #53 - ID 53 - Name:
Item #54 - ID 54 - Name:  - MimeType: application/rdf+xml
File has no movie (moov) - static data container
```

**Comment by jeanlf** [comment]
the result you get with 0.6.x are normal, the HEIF spec was not frozen at that time. The parsing you see with .07.1+ is OK,  what other info would youlike to see (you can check the content of these files with -diso)

**Comment by avibrazil** [comment]
Discussion about this topic is happening on bug #901

**Comment by deweydb** [comment]
@avibrazil I'm not 100% sure what you are asking for here, but if you're looking for the metadata it is in the last item in the set.  You can extract it with a combination of gpac and [exiftool](https://www.sno.phy.queensu.ca/~phil/exiftool/) like this:

```
$ MP4Box -dump-item 54:path=exif.hevc IMG_5921.HEIC
$ exiftool exif.hevc
```

And you can copy that meta data into a new image like this:

`$ exiftool -TagsFromFile exif.hevc target.jpg`

Hopefully this helps!

**Comment by avibrazil** [comment]
@deweydb these are useful examples

I’d like to be able to read, display and specially **WRITE** EXIF and XMP data to HEIF/HEIC files.
MP4Box does that today to MP4 files, but not HEIF yet.

**Comment by deweydb** [comment]
@avibrazil is it not possible to do that with exiftool ?

**Comment by avibrazil** [comment]
No, exiftool still doesn't support HEIF/HEIC.
I contacted Phil Harvey from ExifTool and sent him some samples.
But HIEF/HEIC support won't be there any time soon.

**Comment by cconcolato** [comment]
Reading Exif data from HEIF/HEIC files can be done by extracting the EXIF item from the files. Then exiftool can read it perfectly. 
Writing exif into HEIF should work with MP4Box by adding an item, once your Exif binary data is ready.

**Comment by avibrazil** [comment]
@cconcolato OK

Now, what is the recipe to extract the EXIF part? And to reinsert it again on a HEIF file?

What about IPTC and XMP for more advanced tags such as regions, face recognition data, image subject and comments ?

Thank you in advance

**Comment by avibrazil** [comment]
ExifTool added read support for HEIF/HEIC.

http://u88.n24.queensu.ca/exiftool/forum/index.php/topic,8550.msg44137.html?PHPSESSID=lrc085ihbqpil54q44tcq5on97#msg44137
