### ISSUE TITLE
Unable to package tiled content.

### ISSUE THREAD

**Issue by sanilraut** [gpac/gpac#906]
Hi,

-I created hevc content using: 

kvazaar --input outputFile_1280x720.yuv --input-res=1280x720 --preset veryslow --tiles 3x3 --slices tiles --mv-constraint frametilemargin --aud --output tiled_1280x720threebythree.265

-mediainfo tiled_1280x720threebythree.265 
General
Complete name                            : tiled_1280x720threebythree.265
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
File size                                : 26.8 MiB

Video
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main@L6.2@Main
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits

-Next I packaged the hevc stream as per https://gpac.wp.imt.fr/2017/02/01/hevc-tile-based-adaptation-guide/
 
MP4Box -v -add tiled_1280x720threebythree.265:FMT=HEVC:split_tiles -fps 30 -new multitile.mp4
 
MP4Box -info multitile.mp4 
* Movie Info *
	Timescale 600 - Duration 00:01:44.966
	1 track(s)
	Fragmented File: no
	File suitable for progressive download (moov before mdat)
	File Brand iso4 - version 1
	Created: GMT Sat Sep 16 22:15:40 2017
	Modified: GMT Sat Sep 16 22:15:40 2017

File has no MPEG4 IOD/OD

Track # 1 Info - TrackID 1 - TimeScale 30000 - Media Duration 00:01:44.966
Media Info: Language "und (und)" - Type "vide:hvc1" - 3149 samples
Visual Track layout: x=0 y=0 width=1280 height=720
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x23
HEVC Video - Visual Size 1280 x 720
	HEVC Info: Profile Main @ Level 6.2 - Chroma Format 1
	NAL Unit length bits: 32 - general profile compatibility 0x60000000
	Parameter Sets: 1 VPS 1 SPS 1 PPS 
	SPS resolution 1280x720
	Bit Depth luma 8 - Chroma 8 - 2 temporal layers
	VPS#1 hash: 9E811E99CCFE114792C63911120CBE88BA7BD8CD
	SPS#1 hash: 3338A461062622F082C25A2B6551ABD80FE8A887
	PPS#1 hash: 17BD5AC3D2A94D2F795ED82A5A25B503A981E39A

Self-synchronized
	RFC6381 Codec Parameters: hvc1.1.6.L186.80
	Average GOP length: 62 samples

MP4Box version:

 MP4Box -version
MP4Box - GPAC version 0.7.2-DEV-rev265-g9b1c2ef5-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: --host=i686-linux-gnu --prefix=/usr --build=i686-linux-gnu --mandir=${prefix}/share/man --extra-cflags=-Wall -g -fPIC -DPIC --cc=ccache cc CXX=ccache g++
Features: GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG 

-I am not able to try out MP4Box -rem 3 multititle.mp4 -out test_tile_lost.mp4 as there is only one TrackID available. 

Can someone please let me know what I am missing here.

Thanks,
Sanil

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by sanilraut** [comment]
Issue: https://github.com/gpac/gpac/issues/827 helped. Closing

**Comment by wxy0321** [comment]
@sanilraut I have encountered the exact same problem. Can you explain exactly how #827 helped?
