### ISSUE TITLE
How to compile mp4box to get ios execute file?

### ISSUE THREAD

**Issue by briandbl** [gpac/gpac#907]
I refer the link to https://gpac.wp.imt.fr/category/compiling/ to get Mac version execution version. How to get the execution file for ios(my Apple iphone devices). The document is not clear. anyone who have some advice or some methods to help me.

thanks

**Comment by aureliendavid** [comment]
you can't really build the mp4box command line binary for ios, however you can build the osmo4/mp4client player by using the project file in `build/xcode/gpac4ios.xcodeproj` with xcode
