### ISSUE TITLE
Question: how is mp4box meant to be used for appending data to existing period (dash-ctx mode)

### ISSUE THREAD

**Issue by sandersaares** [gpac/gpac#912]
I wish to append new segments to a dynamic MPD generated by successive calls to mp4box, using dash-ctx mode. However, I find that each invocation of mp4box results in a new period being added instead. This is not desirable - I simply wish to add more data to the existing period.

Is this a supported scenario and, if so, how am I meant to invoke mp4box in order to achieve appending of data?

I tried manually specifying the period name but that appeared to result in overwritten segments instead of appended.

Example input files (audio only for small download size) to be appended to make one large segment: 
[in.zip](https://github.com/gpac/gpac/files/1354925/in.zip)

**Comment by jeanlf** [comment]
Sorry for the late follow-up.
Multi-period was a bit messy in 0.8.0 and only worked properly with the -subdur option. This should no longer be the case with 0.9.0, a single period will be used by default unless codec configuration / other stream state change is detected (or a new period is forced). Please try with 0.9.0 and reopen if needed.
