### ISSUE TITLE
Question: does mp4box understand changes in aspect ratio when dashing?

### ISSUE THREAD

**Issue by sandersaares** [gpac/gpac#913]
In some types of video streams, you can have the aspect ratio change in the middle of the stream (e.g. a TV channel that interleaves 4:3 and 16:9 movies). I would expect any aspect ratio change to result in a new period in generated DASH.

I do not currently have useful test data in this form so I cannot simply try it out but I thought I should just ask - is this supported? Does mp4box understand changes like this and handle them? Or does it just use whatever metadata it detects at the start of the input stream and ignore changes?

**Comment by rbouqueau** [comment]
Hi Sander,

If you are using the ```-dash-ctx``` I think you are entering an untested zone. Let us know how your tests work. We'll find a way.

**Comment by jeanlf** [comment]
this should be taken into account in GPAC 0.9.0
