### ISSUE TITLE
problem with unsigned int32 rollover

### ISSUE THREAD

**Issue by lotharkript** [gpac/gpac#920]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X ] I looked for a similar issue and couldn't find any.
- [ X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/

Using other tools, generate a 33 hours audio only long file (maybe using AAC codec). 
Then using Mp4Box, to remux it.
The orignal will have a STTS table like this (one entry with 5235839 samples at 1024 duration)
```
           <stts>
              <Address Value="0x0000000056F53BBA"/>
              <HeaderSize Value="8"/>
              <DataSize Value="24"/>
              <Size Value="32"/>
              <ParserReadBytes Value="32"/>
              <Version Value="0"/>
              <Flags Value="0x00000000"/>
              <EntryCount Value="2"/>
              <Entry Index="0">
                <SampleCount Value="5235839"/>
                <SampleDelta Value="1024"/>
              </Entry>
              <Entry Index="1">
                <SampleCount Value="1"/>
                <SampleDelta Value="498"/>
              </Entry>
            </stts>
```

After using MP4Box, you will get new entries, with one sampleDelta of 0
```
            <stts>
              <Address Value="0x0000000000000256"/>
              <HeaderSize Value="8"/>
              <DataSize Value="32"/>
              <Size Value="40"/>
              <ParserReadBytes Value="40"/>
              <Version Value="0"/>
              <Flags Value="0x00000000"/>
              <EntryCount Value="3"/>
              <Entry Index="0">
                <SampleCount Value="1041535"/>
                <SampleDelta Value="1024"/>
              </Entry>
              <Entry Index="1">
                <SampleCount Value="1"/>
                <SampleDelta Value="0"/>
              </Entry>
              <Entry Index="2">
                <SampleCount Value="4194304"/>
                <SampleDelta Value="1024"/>
              </Entry>
            </stts>
```

The problem is that in the code, you are multiplying u32 * u32 to get some DTS
In this case, you will get 5235839 * 1024 = 1066531840 (instead of 5361499136)

The follow patch seems to fix the problem for me:
```
---
 src/isomedia/box_code_base.c | 2 +-
 src/isomedia/stbl_read.c     | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/src/isomedia/box_code_base.c b/src/isomedia/box_code_base.c
index ec380ffaa..90a4f473e 100644
--- a/src/isomedia/box_code_base.c
+++ b/src/isomedia/box_code_base.c
@@ -6149,7 +6149,7 @@ GF_Err stts_Read(GF_Box *s, GF_BitStream *bs)
 		ptr->entries[i].sampleDelta = gf_bs_read_u32(bs);
 #ifndef GPAC_DISABLE_ISOM_WRITE
 		ptr->w_currentSampleNum += ptr->entries[i].sampleCount;
-		ptr->w_LastDTS += ptr->entries[i].sampleCount * ptr->entries[i].sampleDelta;
+		ptr->w_LastDTS += (u64) ptr->entries[i].sampleCount * ptr->entries[i].sampleDelta;
 #endif
 
 		if (!ptr->entries[i].sampleDelta) {
diff --git a/src/isomedia/stbl_read.c b/src/isomedia/stbl_read.c
index a5d2ea614..029212ada 100644
--- a/src/isomedia/stbl_read.c
+++ b/src/isomedia/stbl_read.c
@@ -96,7 +96,7 @@ GF_Err stbl_findEntryForTime(GF_SampleTableBox *stbl, u64 DTS, u8 useCTS, u32 *s
 			curDTS += ent->sampleDelta;
 		}
 		//we're switching to the next entry, update the cache!
-		stbl->TimeToSample->r_CurrentDTS += ent->sampleCount * ent->sampleDelta;
+		stbl->TimeToSample->r_CurrentDTS += (u64) ent->sampleCount * ent->sampleDelta;
 		stbl->TimeToSample->r_currentEntryIndex += 1;
 		stbl->TimeToSample->r_FirstSampleInEntry += ent->sampleCount;
 	}
-- 
2.15.0.rc0.271.g36b669edcc-goog
```

**Comment by lotharkript** [comment]
Interesting or not, it seems iTunes has exactly the same problem.
If you take a 33 hours AAC audio, containing 5235839 samples at 1024, the duration should be 5309140746

but when using iTunes to convert the audio to m4a, the mdhd duration will show at 1066531840 which is 5309140746 - 2^32

**Comment by aureliendavid** [comment]
that is interesting :)

thanks for the report, I'll look into it

**Comment by aureliendavid** [comment]
@lotharkript would you be able to upload your test file to https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95 ?

**Comment by aureliendavid** [comment]
Should be ok with the above fix, please reopen if needed. Thanks for the report.

**Comment by lotharkript** [comment]
Thanks for catching one more roll over I did not.

But should we also do it here:
https://github.com/gpac/gpac/blob/master/src/isomedia/stbl_read.c#L69

`
curDTS -= (u64)ent->sampleDelta * ent->sampleCount;
`

**Comment by aureliendavid** [comment]
ha, this one escaped my grep! well spotted, i'll add it in a later commit, thanks

**Comment by aureliendavid** [comment]
included in https://github.com/gpac/gpac/commit/fcc671b6778fb7ca7927bc9a7f0da3d380b2dca4
