### ISSUE TITLE
MP4Box appends PPS data to the last frame in each GOP

### ISSUE THREAD

**Issue by soundav** [gpac/gpac#922]
The MP4Box's .mp4 output from .h264 input seems to contain misplaced PPS data in the tracks.

**How to reproduce the issue**
**Test Data:**
Let's use ffmpeg to create a test .mp4 file,
_ffmpeg -f lavfi -i testsrc=duration=15.3:size=qcif:rate=10 -g 60 testsrc_1.mp4_ 

Then use MP4Box to extract the raw .h264 file,
_mp4box -raw 1 testsrc_1.mp4_

**Test:**
Let's use MP4Box to produce a .mp4 file from raw h264 file,
_mp4box -add testsrc_1_track1.h264  testsrc_1_track1.mp4_

Now, when if we use ISO-Viewer to go through the track NALU, 
We can see that PPS bits are added to the Last Non-IDR frame of each GOP.

**Example:**
.
.
Entry{sample=SampleImpl{offset=30411{size=52}} - 52bytes [NonIDR{type:1,idc:0,size:38}, PPS{type:8,idc:3,size:6}]
Entry{sample=SampleImpl{offset=30463{size=2644}} - 2644bytes [IDR{type:5,idc:3,size:2640}]
.
.

**Comment by jeanlf** [comment]
I believe this was fixed recently, could you re-check?
