### ISSUE TITLE
OSMO4 emptied my %TEMP% directory on startup

### ISSUE THREAD

**Issue by Torkell** [gpac/gpac#923]
I just installed GPAC (using the installer at https://download.tsi.telecom-paristech.fr/gpac/release/0.7.0/gpac-0.7.0-rev0-gbd5c9af-master-x64.exe), started "Osmo4 (with console)", and while the application was starting it deleted almost all the files in my %TEMP% directory (assigned to "C:\Temp" on my PC - Windows 7 Pro 64-bit).

It should **not** do that.

Especially without any warning that it is about to **destroy user data** - on my PC, C:\Temp contained quite a lot of stuff including files that I had created/downloaded and had yet to move elsewhere. Excuse me while I dig out an undeleter...

---

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- - (one go at deleting my data is quite enough, thankyou...)
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by Torkell** [comment]
From a quick browse through the code I think I can see a potential cause: `gf_dm_clean_cache()` will delete `dm->cache_directory` if it is larger than `dm->max_cache_size`. And `dm->cache_directory` appears to come from `gf_get_default_cache_directory()` which on my system probably calls `GetTempPath()`, returning the value of `%TEMP%`.

If that is the case then `gf_get_default_cache_directory()` should be changed to return an application-private subdirectory of whatever it discovers as the system temp directory. That way at least it will only stomp over its own files and not blat my data as well.

**Comment by rbouqueau** [comment]
Hi, thanks for reporting. We've also noticed that it can have nasty effects for some users. Let us discuss that internally.

**Comment by aureliendavid** [comment]
Hi, thanks for the report. 

This is indeed a pretty bad bug. 

It should now be fixed (from rev312 and up at https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/). 

It will now only count the gpac_cache_* files to compute the current cache size, and only cleanup these files when the limit is reached. 

On new installs (or when GPAC.cfg is deleted), the default cache dir will now be a "gpac_cache" subdir of the system tmp dir to make it easier to see what files are written by gpac.
