### ISSUE TITLE
DRM encrypt already existing init.mp4,seg_1.m4s,seg_x.m4s files?

### ISSUE THREAD

**Issue by Murmur** [gpac/gpac#924]
Is it possible to encrypt already existing nondrm init+segment files?

Current mp4box drm&packaging command use the original non-protected video.mp4 file, such as created by ffmpeg transcoding.
```
MP4Box -crypt temp-gpacdrm.xml temp-v1.mp4 -out drm/temp-v1.mp4
MP4Box -crypt temp-gpacdrm.xml temp-v2.mp4 -out drm/temp-v2.mp4
MP4Box -crypt temp-gpacdrm.xml temp-v3.mp4 -out drm/temp-v3.mp4
MP4Box -crypt temp-gpacdrm.xml temp-a1.mp4 -out drm/temp-a1.mp4
cd ./drm
MP4Box -dash 6000 -frag 6000 -mem-frags -rap -profile dashavc264:live -profile-ext urn:hbbtv:dash:profile:isoff-live:2012 
   -min-buffer 3000  -bs-switching no -sample-groups-traf -single-traf -subsegs-per-sidx 1 
   -segment-name $RepresentationID$_$Number$$Init=i$ -segment-timeline 
   -out manifest.mpd 
   temp-v1.mp4#trackID=1:id=v1:period=p0 
   temp-v2.mp4#trackID=1:id=v2:period=p0 
   temp-v3.mp4#trackID=1:id=v3:period=p0 
   temp-a1.mp4#trackID=1:id=a1:period=p0
```

Is it possible without any `demux-nonprotectedsegments-to-video1.mp4-ffmpeg-or-something` tricks to to create drm segments? Say I progressively receive new segment files one by one over the long period of time and must process them one by one to drm/v1_X.m4s segment files.
```
v1_i.mp4, v1_1.m4s, v1_X.m4s, ...
v2_i.mp4, v2_1.m4s, v2_X.m4s, ...
a1_i.mp4, a1_1.m4s, a1_X.m4s ...
manifest.mpd
```

Example of gpacdrm.xml file with multiple pssh objects.
```
<?xml version="1.0" encoding="UTF-8" ?>
<GPACDRM type="CENC AES-CTR">
<!-- 
  kid=0x43215678123412341234123412341234
  key=0x12341234123412341234123412341234
  iv=0x22ee7d4745d3a26a
--> 

<!-- Playready -->
<DRMInfo type="pssh" version="0">
  <BS ID128="9A04F07998404286AB92E65BE0885F95"/>
  <BS bits="32" endian="little" value="518"/>
  <BS bits="16" endian="little" value="1"/>
  <BS bits="16" endian="little" value="1"/>
  <BS bits="16" endian="little" value="508"/>
  <BS data64="PABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgBlAEYAWQBoAFEAegBRAFMATgBCAEkAUwBOAEIASQAwAEUAagBRAFMATgBBAD0APQA8AC8ASwBJAEQAPgA8AEMASABFAEMASwBTAFUATQA+AG0AdQBoAGoAVAA5AHUAQwBhAHMAcwA9ADwALwBDAEgARQBDAEsAUwBVAE0APgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA=="/>
</DRMInfo>

<!-- Widevine -->
<DRMInfo type="pssh" version="0">
  <BS ID128="EDEF8BA979D64ACEA3C827DCD51D21ED"/>
  <BS data="0x08011210"/>
  <BS ID128="43215678123412341234123412341234"/>
</DRMInfo>

<!-- Marlin -->
<DRMInfo type="pssh" version="0">
  <BS ID128="69f908af481646ea910ccd5dcccb0a3a"/>
  <BS data="0x000000186d61726c000000106d6b69640000000000000000"/>
</DRMInfo>

<!-- CENC -->
<DRMInfo type="pssh" version="0">
  <BS ID128="1077efecc0b24d02ace33c1e52e2fb4b"/>
  <BS bits="32" value="1"/>
  <BS ID128="43215678123412341234123412341234"/>
</DRMInfo>

<CrypTrack trackID="1" IsEncrypted="1" IV_size="8" first_IV="0x22ee7d4745d3a26a" saiSavedBox="senc">
  <key KID="0x43215678123412341234123412341234" value="0x12341234123412341234123412341234"/>
</CrypTrack>

</GPACDRM>
```

**Comment by rbouqueau** [comment]
We had a discussion recently. It could be done, but the API in GPAC is not optimal at the moment. We'll keep you updated here but it may take some time. Let us know if you are able to contribute in any way.

**Comment by Murmur** [comment]
Do you think this is a basic|intermediate level of changes to GPAC cmdline and internal workflow or does it need an extensive changes here and there? I have not thought about the cmdline interface how this should look.

Is it just one file per command or multiple input segments could be given, I don't know what would be the best.
```
Single segment per command, no manifest just encrypt segment file.
MP4Box -crypt gpacdrm.xml -cryptonly v1_i.mp4 -out drm/v1_i.mp4
MP4Box -crypt gpacdrm.xml -cryptonly v1_1.m4s -out drm/v1_1.m4s
MP4Box -crypt gpacdrm.xml -cryptonly v1_2.m4s -out drm/v1_2.m4s
Multiple input segments, output to folder using the original name.
MP4Box -crypt gpacdrm.xml -cryptonly v1_1.m4s v1_2.m4s v1_3.m4s -out drm/
```

**Comment by jeanlf** [comment]
No that’s not a trivial modif, we need to think about this:
- we’ll need to pass both init seg, segment and crypt info, do we pass the init seg name in the crypt info?
- do we want to recreate the init segment with encryption setup at each call?
- we need to make sure crypto config doesn’t change between calls
- we need to find a way to keep non standard boxes from the source segment which is not possible with the current fragmenter

**Comment by jeanlf** [comment]
There's a first draft in GPAC 0.9.0:
```
MP4Box -crypt DRM.xml seg_init.mp4 -out seg_init_crypted.mp4
MP4Box -crypt DRM.xml -init-seg seg_init.mp4 seg_N.m4s -out seg_N_crypted.m4s
```
You need to provide the _non-crypted_ initial segment.

Note that in the process, I also added -seg-init for the dump to avoid both the file concatenation and moov boxes dump:
```
MP4Box -diso -init-seg seg_init.mp4 seg_N.m4s
```

 
There are still a few limitations for the encryption: 
- we loose sidx if any: do we really care about the use case ?
- we loose internal fragmentation of segment: we could patch by adding fragmentation option, but that will not be identical
- we loose additionnal boxes in segment if any and loose styp brands

Could you give it a try ?

**Comment by Murmur** [comment]
Wow thanks, yes I can create a test case and see what happens. I don't have access to HbbTVs for the next one month so they wait for august.
* I am fine without SIDX lookup table, my latest mp4box scripting does not insert SIDX atom
* I have some test content with multi-moof/mdat pairs for preparing low latency testing but for now a single moof/mdat is fine.
* may or may not create side effects loosing some atoms, remains to be seen

Will let you know once test case is ready.

**Comment by jeanlf** [comment]
I'm working on a patch to keep fragmentation (boundaries of trun at the begining, maybe default sample flags later), but first I need to cleanup a bit the isomedia code.

**Comment by jeanlf** [comment]
Done, we keep both fragmentation patterns (identical to source in all cases) and rewrite sidx info (leading to same sidx subsegments at least for most simple cases)
