### ISSUE TITLE
[Question] Dump subtitle as .srt without indicating track number ?

### ISSUE THREAD

**Issue by jalba69** [gpac/gpac#925]
Hello, 
I'm not sure if it's the right place to ask this but i found no other way so here i am.
I usually dump the content of a mp4 using this command : 

**Mp4Box.exe -dump-cover -dump-chap-ogg -raw * input_file.mp4**

Only problem i have with this is that the subtitles are extracted in a .tx3g format and i would like to get them out in .srt format ( they are originaly .srt in the input_file.mp4 ) , if using the command line : 
**Mp4Box.exe -srt 3 input_file.mp4** 
i can get them out after i indicate the _TrackID 3_ where the subtitle is placed.

What i would like to know is if it's possible to accomplish all this in a single step, without having to indicate the track numbers for the subtitles files, i tried to add a wildcard for the srt track like **_-srt *_** but this doesn't seems to work sadly.

The goal is to input a mp4 and dump all content, cover, chapters in ogg format, subtitles in .srt format + all audio and video tracks, without having to indicate any track numbers like the **_-raw *_** command allows it, maybe i am missing something but for now i did not found a way to do this in a single command.

Thank you very much in advance.

**Comment by aureliendavid** [comment]
Hi, 

It's not currently possible to have `-raw *` dump subtitles as srt files. Additionally, the tx3g file will only contain the binary samples and no timing or formatting data so it's not usable as is. 

However I've added the possibility to use `*` with the `-srt` switch to dump all text/subtitle tracks as srt. 

So in one command

`MP4Box -dump-cover -dump-chap-ogg -raw * -srt * input_file.mp4`

should do what you want, just ignore the .tx3g files generated.

**Comment by jalba69** [comment]
Fantastic, it's perfect like this with the * wildcard for srt's

Thank you very much for this, you can't imagine how much this little change will simplify my life :) 

Thanks again.
