### ISSUE TITLE
AAC file not supported? 'TS packet does not start with sync marker'

### ISSUE THREAD

**Issue by rfunduk** [gpac/gpac#926]
GPAC installed via Homebrew (Mac OS X 10.11.6) - 0.7.1-revrelease

I'm not really thinking this is a bug, to be honest... but I am at a loss trying to explain what is happening. Happy to be directed elsewhere!

So, background: I was using MP4Box happily, but then I upgraded HandBrake for an unrelated reason and all of the sudden all my audio is garbled/underwater/low-bitrate sounding. Turns out it's because libav's AAC encoder replaced FDK. So I went on a wild goose chase extracting the audio from my source and then converting to AAC with FDK, and then providing _that_ instead of the audio ripped directly from the HandBrake encoded file. The workflow is exactly the same as it was before except I was extracting the AAC audio resulting from the HandBrake encode and providing that.

Since it will undoubtably help -- I uploaded the originals. The mediafire link in the template asked me for a description and I said `rfunduk-arian501-gpac`, hopefully you have them :)

Ok, so hopefully that all made sense. Here's what happens when I try to use MP4Box as I have been all along, except with the FDK'd audio:

```
MP4Box -dash 5000 -frag 5000 -rap -frag-rap -profile full -segment-name dash_seg_%s_ -min-buffer 5000 -bs-switching no -out ariane501--manifest.mpd ariane501--sd.mp4#video ariane501--hd.mp4#video ariane501.aac#audio
[MPEG-2 TS] TS Packet 1 is scrambled - not supported
[MPEG-2 TS] TS Packet 2 is scrambled - not supported
[MPEG-2 TS] TS Packet 3 does not start with sync marker
[MPEG-2 TS] TS Packet 4 does not start with sync marker
[MPEG-2 TS] TS Packet 5 does not start with sync marker
... many more lines like this, and finally
[MPEG-2 TS] TS Packet 214 does not start with sync marker
[DASH] File ariane501.aac not supported for dashing - skipping
DASH Setup Error: Feature Not Supported
```

What feature is not supported? What is a 'sync marker'? Etc. Let me know if I left out any critical info/etc!

**Comment by rfunduk** [comment]
Oh I also noticed on the 'how to file a bug' page I should get a more verbose log: https://ryanfunduk.com/rfunduk-ariane501-gpac.log

**Comment by jeanlf** [comment]
the dasher currently only accepts TS or MP4 files as input. Import your aac file to mp4 first:
`MP4Box -add ariane501.aac -new ariane501-audio.mp4`
and use the generated file as input to you dash command

**Comment by rfunduk** [comment]
Ah I see. So in my previous workflow, when HandBrake would encode the audio, and I then extracted it with ffmpeg (`-vn -acodec copy`), that produced _an mp4 with only audio_.

I changed my process to extract a WAV (ffmpeg `-vn -f wav`) and then encode as AAC separately, and now I don't have an mp4, of course.

Makes a lot of sense. Thanks for the help!
