### ISSUE TITLE
fragmented mp4 to unfragmented mp4 

### ISSUE THREAD

**Issue by wakhgando** [gpac/gpac#927]
how to convert fragmented mp4 to unfragmented mp4 ?
because i am not able to play in PC.

**Comment by jeanlf** [comment]
just redo the file interleaving, either flat (moov at the end):
`MP4Box -flat frag.mp4 -out unfrag.mp4`
or with a given interleaving:
`MP4Box -inter 500 frag.mp4 -out unfrag.mp4`
