### ISSUE TITLE
 how to make it playable on PC ? 

### ISSUE THREAD

**Issue by wakhgando** [gpac/gpac#928]
i have downloaded this movie but it is encrypted in mediainfo. how to make it playable on PC ? 

[https://a56avoddashs3ww-a.akamaihd.net/d/2$o-57kEyyDe_VLCwMfFll1rx8qSA~/ondemand/sin-dub-iad/7925/3405/64bd/4f29-ba34-885b2260d343/ba945d08-7843-45d2-90ea-d347ba493031_video_1.mp4
](url)

**Comment by rbouqueau** [comment]
Do you know the encryption scheme? And do you have the key to decrypt it?

**Comment by wakhgando** [comment]
this is the MPD file and i downloaded this.
[https://a56avoddashs3ww-a.akamaihd.net/d/2$o-57kEyyDe_VLCwMfFll1rx8qSA~/sin/7925/3405/64bd/4f29-ba34-885b2260d343/ba945d08-7843-45d2-90ea-d347ba493031_corrected.mpd](url)

**Comment by rbouqueau** [comment]
The MPD doesn't contain the keys, but it tells you that you need support for the PlayReady 2.0 DRM. The Open-Source version of GPAC don't support that.

**Comment by wakhgando** [comment]
is there any solution to decrypt this?

**Comment by rbouqueau** [comment]
Yes, with the decryption key. When using a DRM the key is transferred separately from the content.

**Comment by wakhgando** [comment]
where i will check transferred decryption key to decrypt this one.
