### ISSUE TITLE
mp4box generates multiple segments when dashing even if segment length argument is longer than video

### ISSUE THREAD

**Issue by sandersaares** [gpac/gpac#929]
Version: gpac-0.7.2-DEV-latest-master-x64.exe
Input file: [01_000002.zip](https://github.com/gpac/gpac/files/1430196/01_000002.zip)
Command: `mp4box -dash 999999999 -profile "dashavc264:live" -bs-switching no -sample-groups-traf -out out\Manifest.mpd 01_000002.mp4`

The large segment size is there to make sure that nothing is actually segmented - I just want to split the MP4 into the "DASH components" of init segment + media segment + manifest.

Expected result: DASH presentation with 1 media segment.
Actual result: DASH presentation with 2 media segments.

`dash-strict` seems to produce same behavior.

**Comment by Murmur** [comment]
Mediainfo gives a duration of 4004 ms, let's use is as a scale value then scale*4=16016 segment duration just for the sake of random thoughts.

```
MP4Box - GPAC version 0.7.2-DEV-rev312-gbb11c06cd-ab-suite
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/local64 --disable-shared --enable-static --static-mp4box
Features: GPAC_64_BITS GPAC_DISABLE_3D

mp4box -mem-frags -sample-groups-traf -subsegs-per-sidx 1 -dash 16016 -dash-scale 4004 
   -frag-rap -profile "dashavc264:live" -bs-switching no -sample-groups-traf 
   -out out/Manifest.mpd 01_000002.mp4#video
```

This gives me manifest.mpd, seg_1.m4s(208kB) and seg_init.mp4(1kB) files. I did not try to playback this so really don't know if is a workable solution or can explain why mp4box did not work as expected in your command.
```
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.7.2-DEV-rev312-gbb11c06cd-ab-suite  at 2017-11-03T06:24:37.372Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H0M6.089S" maxSegmentDuration="PT0H0M4.004S" profiles="urn:mpeg:dash:profile:isoff-live:2011,http://dashif.org/guidelines/dash264">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>Manifest.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H0M6.089S">
  <AdaptationSet segmentAlignment="true" maxWidth="1920" maxHeight="1080" maxFrameRate="24000/1001" par="16:9" lang="und">
   <Representation id="1" mimeType="video/mp4" codecs="avc1.640028" width="1920" height="1080" frameRate="90000/3754" sar="1:1" startWithSAP="0" bandwidth="427209">
    <SegmentTemplate media="01_000002_dash_track1_$Number$.m4s" timescale="90000" startNumber="1" duration="360000" initialization="01_000002_dash_track1_init.mp4"/>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```

**Comment by aureliendavid** [comment]
I think this is fixed? At least I can't reproduce it. Please reopen if needed.

**Comment by JavaCoder5** [comment]
How can I generate .m4s chunks with one init.mp4 for a mp4 file using MP4BOX
