### ISSUE TITLE
How to use the SRD extension on manifest file for locally generated live video stream (v4l2) ?

### ISSUE THREAD

**Issue by Tunagit** [gpac/gpac#930]

**Comment by Tunagit** [comment]
Hello, 
I'm trying to use DashCast (or MP4Box) in order to Dash a live video generated locally.
I can either use SRD with MP4Box or the support for v4l2 lib on DashCast but can't use both in a sigle application.
When I try to entry a dynamic mp4 media file (generated with v4l2-utils) as MP4Box input I get a "truncated file error".
Can you help me out? Thx a lot.

**Comment by jeanlf** [comment]
This is too vague. Please give us at least your command lines and reopen
