### ISSUE TITLE
Concatenate tile tracks of hevc 

### ISSUE THREAD

**Issue by OmarEltobgy** [gpac/gpac#933]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Greetings, 

I used kavazaar too generate a tiled hevc stream. 
After that i used MP4Box split_tiles option to generate an mp4 file that has a separate track for each tile
If i want to do the opposite and get the original hevc stream.

I tried using the raw command and i got the raw hevc stream for all the tracks but i don't know how to merge them to get a single hevc stream that i can send to a single decoder or player.

I tried concatenation of all the tracks but when i played the resulting hevc stream, it gave random noise not the original video.

Another question, after dashing the mp4 file of the tile hevc stream, we have an initialization segment for each track and the m4s files for each segment and track pair. Now i want to concatenate all these files to get the mp4 file to play. What is the right arrangement to concatenate these files.

Thanks in advance

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
using -raw on the tile base track will extract the entire HEVC bitstream.

After dashing with MP4Box, the only neeed IS is the one of the tile base track - note the representation in MPD is still an ongoing discussion at MPEG, the generated MPD for tiles may change in the near future

**Comment by OmarEltobgy** [comment]
I don't understand what you mean by the tile base track 

As an example when i have a 2x4 tiled video, i got 9 tracks 
The first one (an initialization header) is in hvc2 format and then one track for each tile with hvt1 format

When i try to user -raw command, i have to specify a trackID 
When i put the trackID as 1 (which i think this is what you mean by base track) the output is a small file in size which i assume it only has the initialization data without the video data of each tile

When i put the trackID as 2, i got a file with extension hvt which i think it corresponds to the data of the 1st tile

When i tried concatenation of all tracks, it didn't work 
So, would you please tell me how to use the raw command to get this tile base track 

Also, for the dash i still don't understand what is meant by the tile base track 
I have a lot of segments for each tile and i don't know which of them to merge
However, i don't care about the final MPD representation, i just want to merge tiles with different qualities at different segments and play the resulting hevc stream on any player

**Comment by jeanlf** [comment]
the tile base track is the hvc2 track carrying sps/pps/vps/sei global to the stream.
You should have the complete bitstream when doing a -raw on that track, which version of MP4Box are you using ?

**Comment by OmarEltobgy** [comment]
It is MP4Box - GPAC version 0.5.2-DEV -revVersion: 0.5.2-426-gc5ad4e4+dfsg5-1build1

When i use split_tiles for the hevc stream, the mp4 file output has a separate hvc2 track for each file so the number of hvc2 tracks i have is equal to the number of tiles in the stream generated by kvazaar. And when i do -raw on each tile track i get the bitstream of the corresponding tile only

**Comment by jeanlf** [comment]
you will need the latest version of MP4Box for that

**Comment by OmarEltobgy** [comment]
In the latest MP4Box version, when i tried to follow this link for the tile based hevc streaming
https://gpac.wp.imt.fr/2017/02/01/hevc-tile-based-adaptation-guide/

When i executed this command 
MP4Box -add video_tiled.hvc:split_tiles -new video_tiled.mp4
There was an error because of using split_tiles 
Error importing video_tiled:split_tiles: Requested URL is not valid or cannot be found

This error didn't happen in the previous versions

**Comment by aureliendavid** [comment]
that's strange I can't reproduce it

what version / os are you using ? can you maybe upload your input file to https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95 ?

**Comment by OmarEltobgy** [comment]
When i downloaded the latest version on github and compiled it, it worked. 
However, when i downloaded it from the ubuntu linux 16.04 download manager using apt-get install gpac, it didn't have the split_tiles options. Also, the same error happens when i use the nighty builds for ubuntu linux 16.04.

Now, i still don't know how to concatenate the dashed tiled files to get an hevc stream. 
After dashing the tiled hevc stream, i get a lot of m4s files, one file for each segment tile quality combination and also some header files. How can i concatenate tiles with different qualities at each segment to get the resulting hevc stream ?

**Comment by fujunustc** [comment]
Have you finish this problem？I have the same problem。
I use this command to pack .hvc file into .mp4 file:
`mp4box -add PeopleOnStreet_2560x1600_30_crop_bitrate_800000.hvc:split_tiles -new PE.mp4`
And then I can use the following command to extract the whole hevc bitstream:
`mp4box -raw 1 PE.MP4`
But after dashing the tiled hevc stream, i get a lot of m4s files too. And How to combine two or two more tracks to form a single conformant HEVC stream?
