### ISSUE TITLE
Decoding Error Feature Not Supported

### ISSUE THREAD

**Issue by OmarEltobgy** [gpac/gpac#934]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Greetings,

I am trying to install GPAC on Ubuntu 16.04. 
I used the Debian Linux 64 version gpac_0.7.0_amd64.deb
However, when i try to play the configuration mp4 file 
It gives me this error:
[SysDec] Codec GPAC BIFS Decoder AU CTS 0 Decode error Feature Not Supported
[ODM0] Decoding Error Feature Not Supported

I also tried the latest nightly build version and it also has the same problem

Would you please help me ?
Thanks in advance

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by aureliendavid** [comment]
By configuration mp4 you mean the /usr/share/gpac/gpac.mp4 file included in the package? 

Can you post the entire command you're using and its output? Can you also include your ~/.gpac/GPAC.cfg file?

**Comment by OmarEltobgy** [comment]
This is an MP4 file from this link 
https://gpac.wp.imt.fr/player/ 
It tests all the features of the gpac player 

This is the command i am using: 
MP4Client configuration.mp4

I am having a difficulty to install MP4Client on Ubuntu 16.04
I tried using the latest nighty build and the Debian Linux 64 version gpac_0.7.0_amd64.deb and also the gpac program from apt-get install gpac and even i downloaded the code from github and compiled it

The output is either:
Using config file in /home/oeltobgy/.gpac directory
System info: 32081 MB RAM - 4 cores
Modules Found : 35 
Loading GPAC Terminal
[Thread MediaManager] Couldn't set priority(2) for thread ID 0x00000000
[Thread MediaManager] Couldn't set priority(2) for thread ID 0x853a5700
Segmentation fault (core dumped)

OR 
Using config file in /home/oeltobgy/.gpac directory
System info: 32081 MB RAM - 4 cores
Modules Found : 35 
Loading GPAC Terminal
[Thread MediaManager] Couldn't set priority(2) for thread ID 0x00000000
[Thread MediaManager] Couldn't set priority(2) for thread ID 0x853a5700
[SysDec] Codec GPAC BIFS Decoder AU CTS 0 Decode error Feature Not Supported
[ODM0] Decoding Error Feature Not Supported

OR 
Using config file in /home/oeltobgy/.gpac directory
System info: 32081 MB RAM - 4 cores
Modules Found : 35 
Loading GPAC Terminal
[Thread MediaManager] Couldn't set priority(2) for thread ID 0x00000000
[Thread MediaManager] Couldn't set priority(2) for thread ID 0x853a5700
[Core] Plugin GPAC 2D Raster not found in 35 modules.

Previously, i successfully downloaded and installed a previous commit from github and it worked fine but now i can't install the latest commit

**Comment by aureliendavid** [comment]
hm, there may be some mix up in versions, try something like: 

clean up: 

```
sudo apt-get remove gpac ; sudo apt-get purge gpac
sudo dpkg -P gpac
rm -f ~/.gpac/GPAC.cfg
```

install latest version: 

```
wget http://download.tsi.telecom-paristech.fr/gpac/new_builds/linux64/gpac/gpac_0.7.2-DEV-rev317-g0d7912d3-master_amd64.deb
dpkg -i gpac_0.7.2-DEV-rev317-g0d7912d3-master_amd64.deb
```

check what is installed: 

```
# should show version 0.7.2-DEV-rev317-g0d79
dpkg -l gpac

# should show /usr/bin/MP4Client
which MP4Client
```

test : 

```
wget http://gpac.sourceforge.net/demos/configuration.mp4
MP4Client configuration.mp4
```

**Comment by OmarEltobgy** [comment]
Wow! This worked! 
Thank you so much. 
Actually i see that the nightly build are updated in this week, i was working on other revision version. 
Also, purge and remving the gpac.conf file is important to solve my problem as i downloaded multiple gpac versions

Thanks again!

**Comment by OmarEltobgy** [comment]
I had another question and it would be great if you can help me

I have a dashed tiled video that i generated following this tutorial
https://gpac.wp.imt.fr/2017/02/01/hevc-tile-based-adaptation-guide/

After generating the dash tile segments and init files, i want to choose a quality representation for each tile in each segment and then concatenate these files and generate the corresponding hevc stream

This is very important to me and i would be so grateful if you helped me solve this problem

**Comment by jeanlf** [comment]
do you want to choose the quality/representation at the client side, or do manual concatenation of files ?

**Comment by OmarEltobgy** [comment]
I want to manually concatenate the files

**Comment by jeanlf** [comment]
that's a bit tedious - first get the init segment:
`cat seg_init.mp4 > concat.mp4`

Then  for each segment duration (say it resoves to number N), cat the base tile track (of type hvc2/hev2):
`cat tile_base_N.mp4 >> concat.mp4`

 then the cat set of files you want from the tiles (say we have a 2x2 grid, all in high quality except third tile), concat them in order

`cat tile_1_N_q1.mp4 >> concat.mp4`
`cat tile_2_N_q1.mp4 >> concat.mp4`
`cat tile_3_N_q2.mp4 >> concat.mp4`
`cat tile_4_N_q1.mp4 >> concat.mp4`

you can then extract the raw hevc bitstream:
 `MP4Box -raw 1 concat.mp4`
