### ISSUE TITLE
Accumulative error in segment duration for audio segments 

### ISSUE THREAD

**Issue by anitac19sep** [gpac/gpac#935]
Hi,

We are using MP4Box to segment video and audio and generate MPEG-DASH output. We specify 10 seconds as segment duration using following commands for both audio and video. Video segments are exactly 10 seconds but audio segments are of 9.984 seconds. We know that this is expected behaviour because AAC doesn't encode audio sample by audio sample but use a time window (1024 samples for AAC) and that explains the 9.984 seconds which corresponds to 468 audio frames. 
We also see that number of audio segments are higher than the number of video segments, 91 vs 90 for a 15-minute input clip. 

> Commands used:
> MP4Box -quiet -dash-strict 10000 -rap -dash-scale 1000 -tfdt 0 -moof-sn 0 -subsegs-per-sidx -1 -mpd-title "dash-chunked-transcode" -dash-ctx ctx.txt -mpd-info-url abc.com -segment-name test_0 input_h264_480x270_1159kbps_aac_48KHz.mp4#video:period=0:id=0 -out manifest_video.mpd
> 
> MP4Box -quiet -dash-strict 10000 -rap -dash-scale 1000 -tfdt 0 -moof-sn 0 -subsegs-per-sidx -1 -mpd-title "dash-chunked-transcode" -dash-ctx ctx.txt -mpd-info-url abc.com -segment-name test_0 input_h264_480x270_1159kbps_aac_48KHz.mp4#audio:period=0:id=0 -out manifest_video.mpd

Can mp4box use varying audio segment duration in such cases? It is possible to perform a better segmentation in this case. MP4Box can keep track of the accumulative error and can try to correct it over time. 
Take below example, 
In current implemenation error with respect to user configuration after:

> First segment - (10 - 9.984) = 0.016 (error of 768 samples)
> Second segment - (20 - 19.968) = 0.032 (error of 1536 samples)
> Third segment - 0.048 (error of 2308 samples)
> Fourth segment - 0.064 (error of 3072 samples)
> and so on...

If error correction is implemented, the errors can be minimized as below.

> First segment - 
> Error = (10 - 9.984) = 0.016 (error of 768 samples)
> Second segment (**create a segment of 10.0053 sec instead of 9.984**) 
> Error = (20 - 19.989) = 0.010 (error of 512 samples)
> Third segment (**create a segment of 10.0053 sec instead of 9.984**)
> Error = 0.0054 (error of 256 samples)
> and so on...

In this approach, we can minimize the error and it is a better segmentation approach and conforms to dash standard.

This is not really a bug but an enhancement request. This enhancement is required to avoid issues in ad-insertion use cases. When there are multiple periods in the MPD file, if audio and video segments are not in sync and drifting apart then many players detect gaps and stops playing the DASH content. There may be AV sync loss over time as well because of this.
To address these issues, this enhancement is required.

Thanks and Regards,
Anita

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by rbouqueau** [comment]
> Can mp4box use varying audio segment duration in such cases?

You explicitely asked MP4Box to act so. Please replace ``` -dash-strict``` by ```-dash``` in your command-line.
