### ISSUE TITLE
jpg to heic format

### ISSUE THREAD

**Issue by guoying1030** [gpac/gpac#936]
Gpac can support converting jpg heic format? Using 
MP4Box -add-image 5912e59cN0c9bda5b.jpg -ab heic -new 1.heic
JPEG import 5912e59cN0c9bda5b.jpg - size 800 x 800
Error: Codec not supported to create HEIF image items

        Error: Feature Not Supported

**Comment by jeanlf** [comment]
for the time being only regular items can be used to store jpg in heif:
`MP4Box -add-item test:jpeg:mime=image/jpeg -ab heic -new test.heic`

support for jpg image items requires extracting part of the jpeg file which is not yet supported
