### ISSUE TITLE
MP4Box packaging Widevine DRM in DASH: Missing fields in ContentProtection element

### ISSUE THREAD

**Issue by jmcubero** [gpac/gpac#943]
Hi,

Thanks in advance for any help. Please let me know if I should send more information privately.

**Summary**
I am trying to use MP4Box for generating a MPEG-DASH content encrypted with Widevine. As a result, I'm missing some elements in the generated manifest.

**Expected result**
Obtain a dash manifest file that includes the following elements
`<ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"/>
<ContentProtection value="Widevine" schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
<cenc:pssh>PsshInfo_aaaaaaa</cenc:pssh>
</ContentProtection>`

**Actual results**
I do obtain only the following element in the manifest:

`<ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"/>`

Once I manually added the `schemeIdUri` element to the manifest xml file, I tried retrieving the license server info with a reference player (I used shaka player), and it will give me an INVALID_SERVER_CERTIFICATE error (https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6004).

**Repro steps**
These are the steps I followed:

`MP4Box -crypt crypt.xml video.mp4 -out video_crypto.mp4`
`MP4Box -dash 600 -rap -profile onDemand -out video.mpd video_crypto.mp4#video`

This is the content of crypt.xml:

`<?xml version="1.0" encoding="UTF-8" ?>
<GPACDRM type="CENC AES-CTR">
 <DRMInfo type="pssh" version="0">
    
    <BS ID128="EDEF8BA979D64ACEA3C827DCD51D21ED"/>
    <BS data64="PSSHheaderData"/>
  </DRMInfo>  
   <CrypTrack trackID="1" IsEncrypted="1" IV_size="8" first_IV="0x22ee7d4745d3a26a" saiSavedBox="senc">
	<key KID="0x051bccd01e1956498601c6cbf6e7a07d" value="0xxxxxxxx"/>
  </CrypTrack>
</GPACDRM>`

**Environment info**
My version of MP4Box:
`$ mp4box -version
MP4Box - GPAC version 0.7.2-DEV-rev339-geda3b37c-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: (static configuration file)
Features: GPAC_64_BITS GPAC_MEMORY_TRACKING GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG
`

OS: I've got the same results on Windows and Linux

Regression info: I've got the same results with `MP4Box - GPAC version 0.7.2-DEV-rev148-ge082e56-master`. I didn't try older versions

**Comment by srampur** [comment]
AFAIK, the cenc:pssh tag MAY be present in ContentProtection tag or present in the pssh box in moov atom. And MP4Box writes the pssh atom header instead of adding the contentprotection tag.
Please check http://dashif.org/wp-content/uploads/2016/11/DASH-IF-CPIX-v2-0.pdf.

**Comment by BucherTomas** [comment]
DASH-IF-IOP now recommends having the cenc:pssh element present in the MPD, please see 7.7.1. ISO BMFF Content Protection Constraints in http://dashif.org/wp-content/uploads/2017/09/DASH-IF-IOP-v4.1-clean.pdf .
This especially makes sense when encrypting content with multiple keys. The client then can create license requests based solely on the MPD instead of needing to parse PSSH boxes from multiple init segments individually.

We would appreciate having the cenc:pssh elements present in the MPD as well.

With regards to OP's INVALID_SERVER_CERTIFICATE error, if this happens when contacting the license server in order to acquire the license, it possibly hints at inability of the server (also called Widevine Proxy) to process the server certificate requests. You would need to discuss this with owners of the license server you are trying to contact.

**Comment by jmcubero** [comment]
Thank you for your answers.

I worked with the license server provider and found out that I won't get that INVALID_SERVER_CERTIFICATE error if I do the same steps with 0.7.0-rev0-gbd5c9af-master, instead of the one that I was using (0.7.2-DEV-rev148-ge082e56-master).

Master 0.7.0 won't write the cenc:pssh in the manifest either (as you guys said, is recommended, but optional), but the player will be able to get the key and decrypt the content correctly.

I used shaka player on web browser and exoplayer on Android

**Comment by BucherTomas** [comment]
@jmcubero  I tried with Windows build of MP4Box - GPAC version 0.7.2-DEV-rev256-gccc9350-master and it is working fine with Shaka against two different Widevine license providers, note that mine has revision between your two, so I wouldn't say that 0.7.2 is unusable in this regard.
It appears that there must be some other factor in play in your case.

**Comment by jeanlf** [comment]
now fixed on git

**Comment by jeanlf** [comment]
thanks, now fixed
