### ISSUE TITLE
using non-gui MP4Client with parameter -cfg not working in current version

### ISSUE THREAD

**Issue by jq5** [gpac/gpac#944]
Hi All,

I'm having an issue where I pass the config file to MP4Client:

in past versions of GPAC, namely 0.5.x, the following code works (I know I'm passing the default GPAC config file, but this is only an example):

MP4Client -exit -cfg ~/.gpac/GPAC.cfg -lf ./bbb_x264_clientID1.txt -logs dash:network@debug http://www-itec.uni-klu.ac.at/ftp/datasets/DASHDataset2014/ElephantsDream/1sec/ElephantsDream_1s_simple_2014_05_09.mpd

But in the current version, 0.7.x, I get the following output:
Several input URLs provided ("/home/ubuntu/.gpac/GPAC.cfg", "http://www-itec.uni-klu.ac.at/ftp/datasets/DASHDataset2014/ElephantsDream/1sec/ElephantsDream_1s_simple_2014_05_09.mpd"). Check your command-line.

This seems to stem from the following change of code, in gpac/applications/mp4client/main.c:

v0.5.x
else if (!gui_mode) {
			if (arg[0] != '-') {
				url_arg = arg;
			}

v0.7.x
if (!gui_mode) {
			if (arg[0] != '-') {
				if (url_arg) {
					fprintf(stderr, "Several input URLs provided (\"%s\", \"%s\"). Check your command-line.\n", url_arg, arg);
					return 1;
				}
				url_arg = arg;
			}

For the life of me I can't see why "url_arg" should get the value "/home/ubuntu/.gpac/GPAC.cfg" in the preceding code in v0.7.x

Thank you for all your help

**Comment by aureliendavid** [comment]
problem was that we look for -cfg first, but then when we parse the other arguments we don't ignore the path given to -cfg so it becomes an input url

the bug was present in 0.5 too but since we overwrote input_url in case of multiple ones instead of exiting with an error, it was invisible

should be fixed with da7db92

**Comment by jq5** [comment]
Thank you very much for the very swift reply and fix.  works perfectly now :)
