### ISSUE TITLE
Could somebody tell me How can I make Multiple period MPD using one contents with live profile.

### ISSUE THREAD

**Issue by universalarchi** [gpac/gpac#946]
I am trying to make MPD like "https://download.tsi.telecom-paristech.fr/gpac/DASH_CONFORMANCE/TelecomParisTech/mp4-live-periods/mp4-live-periods-mpd.mpd"
But I don't know how command line is composed.
So Please somebody tell me how can I do that with mp4box.

**Comment by jeanlf** [comment]
simply specify the periodID in the name of your representation, eg 
`-dash 1000 ... file1.mp4#period=P1 file2.mp4#period=P2`
