### ISSUE TITLE
Osmo4 does not show pictures when playing back my timeline segmented MPD

### ISSUE THREAD

**Issue by donghaima** [gpac/gpac#947]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x ] I looked for a similar issue and couldn't find any.
- [x ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

---------------------------------
Hi Experts,
I am trying to playback the live timeline segments that are generated by a custom DASH packager. Experimenting with three different players: the Osmo4 Player, the DASH IF Reference Javascript Player, and the VLC, I found that the Osmo4 Player does not show pictures on the display window (blank window); while the other two players are playing back fine. 

The Osmo4 Player does play the sample live timeline MPD (http://vm2.dashif.org/livesim-dev/segtimeline_1/testpic_2s/Manifest.mpd) from the DASH IF site though. So I am guess that Osmo4 might not like something in my MPD file, the DASH IF JS Player and VLC on the other hand might be just more forgiving.

I am attaching my MPD file here. Please let me know if you see anything obvious incorrect in my MPD.  I have fed my MPD to the MPD Validator on the DASH IF site and no error is reported by the MPD Validator.

Also attached please find the dash@info logs from Osmo4 when I play my MPD file. 

Any helps are truly appreciated!

Thanks,
-Donghai Ma
  

[Osmo4-timeline-no-picture.log](https://github.com/gpac/gpac/files/1560712/Osmo4-timeline-no-picture.log)

[dash.mpd.txt](https://github.com/gpac/gpac/files/1560701/dash.mpd.txt)

**Comment by aureliendavid** [comment]
would it be possible to upload the video segments (or some of them, maybe zipped) to https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95 so we can test playback?

**Comment by donghaima** [comment]
I updated a tarball that contains:
- timeline segment files
- dynamic MPD file (when I played this file with Osmo4, no pictures displaying in the player window)
- static MPD file (created from the above dynamic MPD) - i am able to play this MPD with Osmo4
 
tarball link:
http://www.mediafire.com/file/l4h1uxe3os5ppv4/dash-ll-origin.tgz

**Comment by aureliendavid** [comment]
Hi, 

Thanks for the data. 

Both these files seem to play properly with MP4Client (or Osmo4) for me. 

However, looking at your original post, there are a few things you can check : 

 - check the SegmentTimeline is correct in your mpd, specifically check that the t attribute of the first S element of the timeline corresponds to an existing segment file (there were some 404s in your original log file) - also check the durations are correct (in your data there is one segment that is slightly shorter than the others)
 - check that the presentationTimeOffset value is less than the time of first segment (or remove it, I'm not sure)
 - if you test the live version locally you can try removing minimumUpdatePeriod

(also check that you're using the latest version of GPAC)

Good luck, keep us posted.

**Comment by donghaima** [comment]
Hi Aurélien,
Just came back from the Christmas break and spent some time looking at this issue. The If I remove presentationTimeOffset@SegmentTemplate, the Osmo4 Player plays properly. But I don't understand the reason to remove the presentationTimeOffset attribute. Would you explain? 

Thanks,
-Donghai

**Comment by aureliendavid** [comment]
Well to be honest I came up with that by trial & error and I'm not sure I understand it myself :)

Maybe someone with a better understanding of the dash spec can weight in. 

It looks like other players have had similar issues: https://github.com/google/shaka-player/issues/593

Among other things it says that

`Current play position is the composition time of the currently presented samples minus @presentationTimeOffset`

so I guess that offset should at least be smaller than the timestamp of the first sample in the timeline. 

But again, that's mostly guesswork.

**Comment by aureliendavid** [comment]
I think this can be closed (reopen if needed)
