### ISSUE TITLE
MP4box: import with :name=file:// fails

### ISSUE THREAD

**Issue by zathorian** [gpac/gpac#948]
Hello,

When using a recent version of mp4box with the :name=file:// command the track name will not be written to the file.

E.g. this command line on a Windows 10 x64 system:
"D:\tools\mp4box\mp4box.exe" -add "D:\sample.264#trackID=1:fps=23.976:par=1:1:name=" -add "D:\sample.aac#trackID=1:lang=jpn**:name=file://D:\sampleTRACKNAME0.txt**:delay=9" -chap "D:\sample_chptmp.txt" -tmp "D:\\TEMP" -new "D:\sample.mp4"

The txt file has only one line with 1234 in it and is a UTF8 encoded file.
I have to add it with a file:// command to be able to write UTF strings.

Using this version it fails (tried also older builds):
MP4Box - GPAC version 0.7.2-DEV-rev356-g028a7cfa-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: (static configuration file)
Features: GPAC_MEMORY_TRACKING GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG

Error in the output is:
Unrecognized import option \sampleTRACKNAME0.txt, ignoring

It did work in the past e.g. with this version:
MP4Box - GPAC version 0.7.0-rev3-g10dc09c-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: (static configuration file)
Features: GPAC_MEMORY_TRACKING GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG

I am not able to test inbetween.

Thank you very much for your tool and your support!

**Comment by aureliendavid** [comment]
should be fixed now, you can re-try with http://download.tsi.telecom-paristech.fr/gpac/new_builds/win64/gpac-0.7.2-DEV-rev357-g7115eeb8-master-x64.exe or later and reopen the issue if needed

thanks for the report
