### ISSUE TITLE
MP4Box muxing corrupts end time of last subtitle

### ISSUE THREAD

**Issue by dustsigns** [gpac/gpac#95]
When muxing an SRT subtitle file (as well as additional audio/video tracks) using MP4Box, the end time of the last subtitle gets corrupted/changed. When demuxing the created MP4 file again, the end time of the last subtitle turns out to be the same as the end time of the second-to-last subtitle (making the duration of the last subtitle negative). During playback (for example in MPC HC) this leads to the last subtitle being shown from its start until the end of the video, which is quite irritating.
The current version as well as several others before it are affected by this problem. I eventually found a very old version (0.4.6 from 2010) which does not exhibit this problem, so it seems to have been introduced in a version after that.

**Comment by jeanlf** [comment]
There was indeed an issue at mp4 import time that would chang ethe duration of the last sample, could you check if that solves your issu ?

**Comment by dustsigns** [comment]
I'll check it with the next nightly build, since I'm a bit short with time at the moment.

**Comment by dustsigns** [comment]
I downloaded the nightly build (gpac-0.5.2-DEV-rev257-gccf222f-master-x64.exe) from http://gpac.wp.mines-telecom.fr/downloads/gpac-nightly-builds/. According to the file name and the GIT repo commit history, it should contain the patch that you linked to above. However, the issue still persists.
Consider the following example SRT file that I used for testing:

> 1
> 00:00:11,053 --> 00:00:16,600
> Schneewittchen und die sieben Zwerge
>
> 2
> 01:22:40,998 --> 01:22:47,171
> ...und wenn sie nicht gestorben sind,
> dann leben sie noch heute.

After muxing this file (and an additional AVC video track) using MP4Box and demuxing it right thereafter, the file becomes:

> 1
> 00:00:11,053 --> 00:00:16,600
> Schneewittchen und die sieben Zwerge
>
> 2
> 01:22:40,998 --> 00:00:16,600
> ...und wenn sie nicht gestorben sind,
> dann leben sie noch heute.

Note the incorrect second time code of subtitle number 2.
Maybe I am using a wrong version (which does not yet contain the fix)?

**Comment by jeanlf** [comment]
hmm that's strange I just tested with [1] both import of the srt and re-import of the mp4 file, with or without additional video and everything worked fine.

Could you post your srt+video / exact command line used ?

[1] https://github.com/gpac/gpac/blob/master/regression_tests/auxiliary_files/subtitle.srt

**Comment by dustsigns** [comment]
I mux with:

> mp4box.exe  -add "test.264:fps=23.976" -add "test.srt" -new "test.mp4"

I demux with:

> mp4box.exe -srt "test.mp4"

I just tried again with the subtitle file I posted above. Although the demuxed file is now correct (I must have messed up the file names before), the last subtitle in the video is still shown for much longer than its time span would allow for (tested with MPC HC). For the sake of completeness, I want to add that the problem still occurs when muxing with the new version of MP4Box, but demuxing with an older one.

 The (new) version seems to be correct, although the copyright year is off:

> mp4box.exe -version
> MP4Box - GPAC version 0.5.2-DEV-rev257-gccf222f-master
> GPAC Copyright (c) Telecom ParisTech 2000-2012
> GPAC Configuration: (static configuration file)
> Features: GPAC_64_BITS GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG

**Comment by jeanlf** [comment]
just did
`MP4Box -add test.264:fps=23.976 -add subs.srt -new test.mp4`

then

`MP4Box -srt 2 test.mp4`

then 
`diff subs.srt test_2_text.srt`

no diff. Are you sure this is not an issue while visualising the content ?

**Comment by dustsigns** [comment]
It works fine with the old version of MP4Box.

**Comment by rbouqueau** [comment]
What's the state of this issue?

**Comment by dustsigns** [comment]
I did not test any newer versions since my last post. The issue still persists for me. Are there any updates or is there any further information required?

**Comment by rbouqueau** [comment]
Yes. Apparently @jeanlf tried to help you but couldn't reproduce. Could you provide us with a sample please?

A dropbox to upload: http://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by cconcolato** [comment]
I just tested and can't reproduce the problem either. Taking the 2 subtitles given above -add followed by -srt gives me the same subtitles, unmodified. You are probably not using the right version of mp4box.

**Comment by dustsigns** [comment]
That's strange... I downloaded the newest version and can't reproduce the issue either. It seems as if the bug has been fixed. Sorry for the confusion.

**Comment by rbouqueau** [comment]
No pb. Thanks everybody for reporting and testing. Please re-open if you see the bug :)
