### ISSUE TITLE
Syntax for using MP4box command line to name & swap Audio tracks

### ISSUE THREAD

**Issue by fantoma2000** [gpac/gpac#950]
Hello,

I looked around but do not find any example that would help me finding my error in usage. Please help me with command line syntax to use MP4box. 

My MP4 file with all the correct codec but I need to do:

1.  Set lang for audio track 1 and 2 to vie
2.  Name the audio track 1 & 2
3.  Swap the audio tracks from 1 to 2 and 2 to 1

After reading the doc, this is what tried and unsuccessfully.

MP4box.exe input.mp4 -out output.mp4 -lang 2=vie -lang 3=vie -name 2=“vocal on” -name 3=“vocal off” -swap-track-id 2:3,3:2

Thank you for helping. Thank you

**Comment by aureliendavid** [comment]
Hi, 

Several things: 

- for you points 1. and 2. your syntax is correct but a bug prevented it to work, should be fixed now
- for the id swap, the syntax `-swap-track-id 2:3` should be enough

So, 

`MP4box.exe input.mp4 -out output.mp4 -lang 2=vie -lang 3=vie -name 2=“vocal on” -name 3=“vocal off” -swap-track-id 2:3`

should now work. 

**However**, the swap-track-id command only swaps the ids, not the actual position of the tracks. So after that command, the first audio track of output.mp4 will have ID 3 but it will still be the same first audio track as before (with name "vocal on" in your example). 

If you want to change the actual order of the tracks, one solution is to re-import them in a different order in a new file. So, after the previous command has been run (and the ID swapped), you can run something like

`MP4Box -add output.mp4#trackID=1 -add output.mp4#trackID=2 -add output.mp4#trackID=3 -new output_ordered.mp4`

to get them in the right order. 
 

Hope this helps.

**Comment by fantoma2000** [comment]
Thank you very much. I will download the newest version and try it.

**Comment by fantoma2000** [comment]
Hello, apparently, I am still lost.  where can I download the version that would fix the bug?  I thought I got the right one but it didn't seem to work.  Thank you.

**Comment by aureliendavid** [comment]
https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/

any build with rev >= 358 include the fix for your points 1 & 2

for example http://download.tsi.telecom-paristech.fr/gpac/new_builds/win64/gpac-0.7.2-DEV-rev362-gb12b86e9-master-x64.exe
