### ISSUE TITLE
Segmentation Fault when passing an mpd link

### ISSUE THREAD

**Issue by tayapski** [gpac/gpac#952]
I installed my gpac package by compiling the source from the tag v0.7.0. I'm currently using Ubuntu 16.04.3.

I keep getting segmentation fault when I run MP4Client. Below is the command I run:
`MP4Client -lf ~/log_file_dec_27_2017_23_33.log -logs all@info http://www-itec.uni-klu.ac.at/ftp/datasets/DASHDataset2014/ElephantsDream/15sec/ElephantsDream_15s_onDemand_2014_05_09.mpd`

I have also attached the log file I generated. Near the bottom end of the log file, it says:
> [iso file] Incomplete file while reading for dump - aborting parsing

Is this what's causing the segmentation fault? If so, how do I fix it?
[log_file_dec_27_2017_23_33.log](https://github.com/gpac/gpac/files/1589342/log_file_dec_27_2017_23_33.log)

**Comment by rbouqueau** [comment]
The latest message from your log seems to be related to the NVidia HW Decoder:
```
[Codec] Found decoder NVidia HW Decoder for stream type MPEG-4 AVC|H264 Video
[NVDec] GPU Device GeForce 940MX (idx 0) has SM 5.0 compute capability
```

Could you remove /usr/local/lib/gpac/gm_nvdec.so and retry?

**Comment by tayapski** [comment]
Looks like that fixed the problem. Thanks a lot!

**Comment by rbouqueau** [comment]
Closing for now.
CC @jeanlf @aureliendavid we need to check about the nvidia stuff by default.
