### ISSUE TITLE
Playready encrypted stream not playing

### ISSUE THREAD

**Issue by aaani** [gpac/gpac#954]
I am using mp4box to encrypt and dash chunks for playback on Shaka player on Microsoft Edge and IE11. (Edge 16 has [this](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12658991/) known issue so I am trying in Edge 15 and below). 

Encoding Steps (On macOS Sierra 10.12.6):
```
➜  playready MP4Box -version 
MP4Box - GPAC version 0.7.1-revrelease
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: --disable-wx --disable-pulseaudio --prefix=/usr/local/Cellar/gpac/0.7.1 --mandir=/usr/local/Cellar/gpac/0.7.1/share/man --disable-x11
Features: GPAC_64_BITS GPAC_HAS_SSL 
➜  playready MP4Box -crypt crypt.xml data/video_sintel_trailer-720p.mp4 -out data/mp4box_enc_video_sintel_trailer-720p.mp4                                              
[iso file] Unknown box type ID32
Saving to data/mp4box_enc_video_sintel_trailer-720p.mp4: 0.500 secs Interleaving
➜  playready Mp4box -dash 2000 -profile dashavc264:onDemand -mpd-refresh 4.0 -rap data/mp4box_enc_video_sintel_trailer-720p.mp4 -out data/output2/720.mpd
[iso file] Unknown box type ID32
[iso file] Unknown box type ID32
[iso file] Unknown box type ID32
[iso file] Unknown box type ID32
```

This is what my crypt.xml file looks like
```
<GPACDRM type="CENC AES-CTR">
    <DRMInfo type="pssh" version="0">
        <BS bits="32" endian="little" value="518"/>
        <BS bits="16" endian="little" value="1"/>
        <BS bits="16" endian="little" value="1"/>
        <BS bits="16" endian="little" value="508"/>
        <BS data64="PABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgBiADIAVQBhADQAZAB2AGsAUgBEAFMAOAB0AEcAawBOAEYAVwBUAEUASABBAD0APQA8AC8ASwBJAEQAPgA8AEMASABFAEMASwBTAFUATQA+AHkAcwBIADkAOQBaADIAagBBAHAAMAA9ADwALwBDAEgARQBDAEsAUwBVAE0APgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA=="/>
    </DRMInfo>

    <CrypTrack trackID="1" IsEncrypted="1" IV_size="8" first_IV="0x22ee7d4745d3a26a" saiSavedBox="senc">
        <key KID="0xe11a656fe4db3444bcb4690d1564c41c" value="0x767c4c46ae57bae75f61403a9d99e99f"/>
    </CrypTrack>
</GPACDRM>
```
I am using microsoft's test server for license - 
https://test.playready.microsoft.com/service/rightsmanager.asmx?cfg=(persist:false,sl:150,contentkey:dnxMRq5XuudfYUA6nZnpnw==,allowunknownhd:true,allowunknownhsd:true)

I am getting these errors in Edge:
![image](https://user-images.githubusercontent.com/3347504/34590290-6a4c1182-f17b-11e7-8b21-f1d54706d1da.png)

Surprisingly, the same steps work with shaka packager and I get the playback in Edge. Here is the command I use with Shaka player,
```
packager in=/work/playready/data/sintel_trailer-720p.mp4,stream=video,output=/work/playready/data/output/video_sintel_trailer-720p.mp4  --mpd_output /work/playready/data/output/720.mpd --enable_playready_encryption --playready_key_id e11a656fe4db3444bcb4690d1564c41c --playready_key 767c4c46ae57bae75f61403a9d99e99f
```
----------------------
I uploaded 4 files to the mediafire url:
video_sintel_trailer-720p.mp4 - Input media  file (Video only)
mp4box_enc_video_sintel_trailer-720p.mp4 - Encrypted media file

720.mpd - Manifest after dashing
mp4box_enc_video_sintel_trailer-720p_dashinit.mp4 - dashed ondemand file

I also tried with `MP4Box - GPAC version 0.7.2-DEV-rev358-g433fbcc35-master` and got the same error. 
With v0.6.1 - I don't get `Unknown box type` warning but the end result is same. No playback in edge. If I remember correctly the error code is different and I am happy to provide more details if you need it.

Any help is appreciated. Thanks!

**Comment by Murmur** [comment]
Please see this topic you should find example gpacdrm.xml, PlayreadyTestServer url, and mp4box command lines. Is there any difference as I can see you have used different set of mp4box arguments.
https://github.com/w3c/encrypted-media/issues/436

**Comment by aaani** [comment]
Thanks @Murmur. Setting the `-sample-groups-traf` flag fixed the issue for me.
