### ISSUE TITLE
with HEVC/H265 files, mp4box -nhml may output wrong "isRAP".

### ISSUE THREAD

**Issue by 299792458m** [gpac/gpac#955]
I made h265 file(by x265) and imported the raw h265 to mp4box
and exported nhml file
and imported nhml file without any change
> mp4box -new -add video.h265 video.mp4
> mp4box -nhml 1:full video.mp4
> mp4box -add video_track1.nhml video_nhml.mp4

at this case, I got a strange mp4 file which takes a lot time when jumping. (like no key frame)
the original video.mp4 can jump correctly.

And next, I tried by nhnt(mp4box -nhnt 1 video.mp4 & import)
at this case, I got jumpable file.

I looked for the differences between the nhml and nhnt files.
I'm not sure, but in the nhml file, the almost all "isRAP" was "no"(except 1st one) and with nhnt file looks the some RAP bit are "yes".

with h264 files, this problem doesn't occur.

So, I think there is something wrong in exporting nhml with h265 file.
Does one know about this problem?

**Comment by rbouqueau** [comment]
Could you share your x265 command-line and the h265 sample file so that we reproduce. We have an anonymous dropbox to share the sample in case github can't host it: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by 299792458m** [comment]
this is ordinary x265 sample and it looks to be reproduced the problem.(I included nhml/nhnt files I extracted)
[Tears_400_x265.zip](https://github.com/gpac/gpac/files/1609995/Tears_400_x265.zip)

And the code I tested originaly was
x265 --crf 20 --preset medium --output-depth 8 --no-progress

**Comment by rbouqueau** [comment]
The file uses Open-GOPS. Here is what I did

```
>MP4Box -raw 1 Tears_400_x265.mp4
Extracting MPEG-H HEVC stream to hevc

>MP4Box -add Tears_400_x265_track1.hvc -new tmp.mp4
HEVC import - frame size 1920 x 800 at 24.000 FPS
HEVC Import results: 335 samples (360 NALUs) - Slices: 7 I 61 P 267 B - 7 SEI - 1 IDR
Stream uses forward prediction - stream CTS offset: 3 frames
OpenGOP detected - adjusting file brand
Saving tmp.mp4: 0.500 secs Interleaving
```

You can force MP4Box to mark all I frame as sync (which provides a faster seeking) with ```:forcesync```:
```
>MP4Box -add Tears_400_x265_track1.hvc:forcesync -new tmp2.mp4
HEVC import - frame size 1920 x 800 at 24.000 FPS
[HEVC Import] Forcing non-IDR samples with I slices to be marked as sync points - resulting file will not be ISO conformant
[HEVC Import] No valid SEI Recovery Point found although needed - forcing
HEVC Import results: 335 samples (360 NALUs) - Slices: 7 I 61 P 267 B - 7 SEI - 1 IDR
Stream uses forward prediction - stream CTS offset: 3 frames
OpenGOP detected - adjusting file brand
Saving tmp2.mp4: 0.500 secs Interleaving
```

@jeanlf @all Is there a specific status on this subject on our side. Or should we communicate with the x265 devs so that their default params lead to a correct seeking policy?

**Comment by 299792458m** [comment]
I mean the nhml file is different from nhnt file at the "isRAP" flag. 
Aren't they same things??? (or is it misplaced?)

**Comment by jeanlf** [comment]
NHNT declares closed and open GOP SAPs as RAP (limitation of the format), while NHML only declares closed GOP as RAP.
I just patched NHML import/export to keep open gop info (new attribute SAPType) and regenerate the rap sample group.
That being said and as Romain pointed out, your file is open GOP, so not all clients will handle seeking properly in MP4 (they need to check both the sync table and the rap sample group). 

Hope this helps

**Comment by 299792458m** [comment]
I understand the nhnt limitation and newest mp4box works fine.
thanks for your great works!
