### ISSUE TITLE
MP4Box dash Problem (live profile) for segments

### ISSUE THREAD

**Issue by JamesXu20150314** [gpac/gpac#956]
Hello,

When I use MP4Box dash a video, I produce such problem:
![image](https://user-images.githubusercontent.com/11470231/34760300-42299186-f61a-11e7-9430-8ebdba3b32b3.png)

My command is 

MP4Box -dash 1000 -profile live -out dash.mpd video.mp4 

My video is normal video:
![image](https://user-images.githubusercontent.com/11470231/34760390-a263f9d8-f61a-11e7-8237-18d44d2513af.png)

Who know why?

Thank you.

**Comment by JamesXu20150314** [comment]
I solved it.

Thanks.

**Comment by DanielMartine** [comment]
I've the same issue, could you say which is your fix?
Thanks
