### ISSUE TITLE
Perform sanity check on output file extension

### ISSUE THREAD

**Issue by GyanD** [gpac/gpac#957]
I thought there was some chance that mp4box outputs MOVs as well, so I did a test: `mp4box -add in.mp4 -new out.mov`. To my surprise, this "worked" i.e. output file was created and no error or warning was thrown.

Unsurprisingly, output file is ISOBMFF but the lack of exception on the extension may confuse some users who try something similar. Suggest a basic check be added.

Thanks,
Gyan

P.S. version is g7115eeb Dec-18-2017.

**Comment by jeanlf** [comment]
well in the case of mov that doesn't hurt since that's (almost) the same file format. More disturbing with other extensions, but we don't know what the user is trying to do (may want to use its own extension) so we won't change this behaviour.
