### ISSUE TITLE
-dash-live how to delete old segments?

### ISSUE THREAD

**Issue by chanof** [gpac/gpac#958]
Hi there,I'm studying how to get a "pseudo live" on osx, I take this opportunity to say that the tools of gpac are rich in documentation, also suitable for those who are not a professionist like me.

COMMAND LINE:
sudo MP4Box -dash-live 1000 -frag 16000 -profile live -subdur 1000 -mpd-refresh 1000 -time-shift 3000 video_test.mp4

Give me a good result on Osmo, mi first stable result, but for the moment I'm unable to run it on dash.js.

MPD FILE:
<?xml version="1.0"?>

<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="dynamic" publishTime="2018-01-10T12:54:37Z" availabilityStartTime="2018-01-10T12:53:54.826Z" timeShiftBufferDepth="PT0H50M0.000S" mediaPresentationDuration="PT0H0M16.227S" maxSegmentDuration="PT0H0M1.333S" profiles="urn:mpeg:dash:profile:isoff-live:2011">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>video_test_dash.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period id="DID1" start="PT0H0M0.000S">
  <AdaptationSet segmentAlignment="true" maxWidth="320" maxHeight="240" maxFrameRate="15" par="4:3" lang="eng">
   <ContentComponent id="1" contentType="audio" />
   <ContentComponent id="2" contentType="video" />
   <Representation id="1" mimeType="video/mp4" codecs="mp4a.40.2,mp4v.20.2" width="320" height="240" frameRate="15" sar="1:1" startWithSAP="1" bandwidth="61364">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="1"/>
    <SegmentTemplate media="video_test_dash$Number$.m4s" timescale="1000" startNumber="1" duration="1000" initialization="video_test_dashinit.mp4"/>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>

First thing to improve, I would like to understand how to delete segments too old, in this case a video of two mb after a few minutes begins to weigh over 200 mb.
Could you help me about?
Thanks
Gianmaria

**Comment by rbouqueau** [comment]
First you shouldn't need to 'sudo'.

Second that's the role of the ```-time-shift``` option. You set it to 3000 seconds.

**Comment by chanof** [comment]
Hi, Thanks so much for this quick support! i use sudo cause i use osx, please let me know if there are particular warnings for osx use, may i ask if for you the mpd is correct for dash.js till know i can't visualize, i will start to check better the client side but i'm not sure about the server side yet

<?xml version="1.0"?>

<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="dynamic" publishTime="2018-01-10T13:25:31Z" availabilityStartTime="2018-01-10T13:24:23.900Z" timeShiftBufferDepth="PT0H0M16.000S" mediaPresentationDuration="PT0H0M16.227S" maxSegmentDuration="PT0H0M1.333S" profiles="urn:mpeg:dash:profile:isoff-live:2011">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>video_test_dash.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period id="DID1" start="PT0H0M0.000S">
  <AdaptationSet segmentAlignment="true" maxWidth="320" maxHeight="240" maxFrameRate="15" par="4:3" lang="eng">
   <ContentComponent id="1" contentType="audio" />
   <ContentComponent id="2" contentType="video" />
   <Representation id="1" mimeType="video/mp4" codecs="mp4a.40.2,mp4v.20.2" width="320" height="240" frameRate="15" sar="1:1" startWithSAP="1" bandwidth="61364">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="1"/>
    <SegmentTemplate media="video_test_dash$Number$.m4s" timescale="1000" startNumber="1" duration="1000" initialization="video_test_dashinit.mp4"/>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>

Thanks a lot
Gianmaria

**Comment by chanof** [comment]
should i write another thread?
