### ISSUE TITLE
Compile in Fedora 20 fails

### ISSUE THREAD

**Issue by nirjuli** [gpac/gpac#96]
# ./configure --enable-pic 
# ./configure --enable-pic
which: no jpeg-config in (/usr/local/bin)

** System Configuration
Install prefix: /usr/local
Source path: /home/gama/UtilityProgram/gpac
C   compiler: gcc
C++ compiler: g++
make: make
CPU: x86_64
Big Endian: no

** GPAC 0.5.0 rev Core Configuration **
debug version: no
GProf enabled: no
Static build enabled: no
Memory tracking enabled: no
Use standard memory allocator: no
fixed-point version: no
IPV6 Support: yes

** Detected libraries **
zlib: system
OSS Audio: yes
ALSA Audio: yes
Jack Audio: yes
PulseAudio Audio: yes
DirectFB support: no
X11 Shared Memory support: yes (path: /usr/X11R6)
X11 XVideo support: yes
SDL Support: yes
OpenGL support: yes
TinyGL support: no
OpenSSL support: no
Mozilla XUL/GECKO support: no
DVB Support: yes
XMLRPC Support: no
wxWidgets support: no

** Extra Libraries used **
SpiderMonkey: no
FreeType: system
JPEG: no
OpenJPEG: system
PNG: system
MAD: system
FAAD: system
XVID: system
FFMPEG: system
Xiph OGG: system
Platinum UPnP: no
AVCap: no
Xiph Vorbis: system
Xiph Theora: system
A52 (AC3): system
OpenSVCDecoder: no
Freenect: system

Creating config.mak
config.h is unchanged
Done - type 'make help' for make info, 'make' to build

Then tried to make with make command
Then it returns
mv ../bin/gcc/libgpac.so ../bin/gcc/libgpac.so.2.0.0
ln -sf libgpac.so.2.0.0 ../bin/gcc/libgpac.so.2
ln -sf libgpac.so.2.0.0 ../bin/gcc/libgpac.so
make[1]: Leaving directory `/home/gama/UtilityProgram/gpac/src'
make -C applications all
make[1]: Entering directory `/home/gama/UtilityProgram/gpac/applications'
set -e; for i in  mp4client  mp4box mp42ts ; do make -C $i all; done 
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/applications/mp4client'
gcc -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/MP4Client main.o extract.o -L../../bin/gcc -lgpac -lpthread -ldl
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/applications/mp4client'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/applications/mp4box'
gcc -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/MP4Box main.o filedump.o fileimport.o live.o -L../../bin/gcc -L../../extra_lib/lib/gcc -lgpac
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/applications/mp4box'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/applications/mp42ts'
gcc -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/mp42ts main.o -L../../bin/gcc -lgpac
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/applications/mp42ts'
make[1]: Leaving directory `/home/gama/UtilityProgram/gpac/applications'
make -C modules all
make[1]: Entering directory `/home/gama/UtilityProgram/gpac/modules'
set -e; for i in aac_in ac3_in audio_filter bifs_dec dummy_in soft_raster mp3_in isom_in odf_dec rtp_in timedtext img_in saf_in mpegts_in ismacryp mpd_in ctx_load svg_in laser_dec svg_in widgetman osd ft_font ffmpeg_in xvid_dec ogg freenect oss_audio alsa jack sdl_out pulseaudio x11_out ; do make -C $i all; done 
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/aac_in'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_aac_in.so aac_in.o faad_dec.o -L../../bin/gcc -lgpac -lm -lfaad
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/aac_in'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/ac3_in'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_ac3_in.so ac3_in.o liba52_dec.o -L../../bin/gcc -lgpac -lm -la52
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/ac3_in'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/audio_filter'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_audio_filter.so audio_filter.o -lm -L../../bin/gcc -lgpac
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/audio_filter'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/bifs_dec'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_bifs_dec.so bifs_dec.o -lm -L../../bin/gcc -lgpac
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/bifs_dec'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/dummy_in'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_dummy_in.so dummy_in.o -lm -L../../bin/gcc -lgpac
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/dummy_in'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/soft_raster'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_soft_raster.so ftgrays.o raster_load.o raster_565.o raster_argb.o raster_rgb.o stencil.o surface.o -lm -L../../bin/gcc -lgpac
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/soft_raster'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/mp3_in'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_mp3_in.so mp3_in.o mad_dec.o -L../../bin/gcc -lgpac -lm -lmad
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/mp3_in'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/isom_in'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_isom_in.so load.o read.o read_ch.o cache.o -L../../bin/gcc -lgpac -lm
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/isom_in'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/odf_dec'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_odf_dec.so odf_dec.o -lm -L../../bin/gcc -lgpac
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/odf_dec'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/rtp_in'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_rtp_in.so rtp_in.o rtp_session.o rtp_signaling.o rtp_stream.o sdp_fetch.o sdp_load.o -L../../bin/gcc -lgpac -lm
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/rtp_in'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/timedtext'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_timedtext.so timedtext_dec.o timedtext_in.o -lm -L../../bin/gcc -lgpac
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/timedtext'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/img_in'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_img_in.so img_dec.o img_in.o bmp_dec.o png_dec.o jpeg_dec.o jp2_dec.o -lm -L../../bin/gcc -lgpac -lopenjpeg
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/img_in'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/saf_in'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_saf_in.so saf_in.o -lm -L../../bin/gcc -lgpac
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/saf_in'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/mpegts_in'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_mpegts_in.so mpegts_in.o -lm -L../../bin/gcc -lgpac
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/mpegts_in'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/ismacryp'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_ismacryp.so ismacryp.o -lm -L../../bin/gcc -lgpac
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/ismacryp'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/mpd_in'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_mpd_in.so mpd_in.o -lm -L../../bin/gcc -lgpac
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/mpd_in'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/ctx_load'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_ctx_load.so ctx_load.o -lm -L../../bin/gcc -lgpac
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/ctx_load'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/svg_in'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_svg_in.so svg_in.o -lm -L../../bin/gcc -lgpac -lz
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/svg_in'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/laser_dec'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_laser_dec.so laser_dec.o -lm -L../../bin/gcc -lgpac
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/laser_dec'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/svg_in'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_svg_in.so svg_in.o -lm -L../../bin/gcc -lgpac -lz
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/svg_in'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/widgetman'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_widgetman.so widgetman.o unzip.o widget.o wgt_load.o -lm -L../../bin/gcc -lgpac -lz
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/widgetman'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/osd'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_osd.so osd.o -lm -L../../bin/gcc -lgpac
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/osd'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/ft_font'
gcc -shared -Wl,--warn-common -Wl,-z,defs -o ../../bin/gcc/gm_ft_font.so ft_font.o  -L../../bin/gcc -lgpac -lfreetype -lz -lm
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/ft_font'
make[2]: Entering directory `/home/gama/UtilityProgram/gpac/modules/ffmpeg_in'
gcc -O3  -Wall -fno-strict-aliasing -Wno-pointer-sign -fPIC -DPIC -fvisibility="hidden" -DGPAC_HAVE_CONFIG_H -I"/home/gama/UtilityProgram/gpac" -Wno-deprecated-declarations -I"/home/gama/UtilityProgram/gpac/include" -I/usr/include/ffmpeg  -c -o ffmpeg_decode.o ffmpeg_decode.c 
In file included from ffmpeg_decode.c:25:0:
ffmpeg_in.h:120:17: error: ‘AVCODEC_MAX_AUDIO_FRAME_SIZE’ undeclared here (not in a function)
  char audio_buf[AVCODEC_MAX_AUDIO_FRAME_SIZE];
                 ^
ffmpeg_decode.c: In function ‘FFDEC_AttachStream’:
ffmpeg_decode.c:172:4: warning: implicit declaration of function ‘avcodec_alloc_context’ [-Wimplicit-function-declaration]
    *ctx = avcodec_alloc_context();
    ^
ffmpeg_decode.c:172:9: warning: assignment makes pointer from integer without a cast [enabled by default]
    *ctx = avcodec_alloc_context();
         ^
ffmpeg_decode.c:320:3: warning: implicit declaration of function ‘avcodec_open’ [-Wimplicit-function-declaration]
   if (avcodec_open((*ctx), (*codec) )<0) return GF_NON_COMPLIANT_BITSTREAM;
   ^
make[2]: *** [ffmpeg_decode.o] Error 1
make[2]: Leaving directory `/home/gama/UtilityProgram/gpac/modules/ffmpeg_in'
make[1]: *** [plugs] Error 2
make[1]: Leaving directory `/home/gama/UtilityProgram/gpac/modules'
make: *** [all] Error 2

Please help to resolve the issue

**Comment by jeanlf** [comment]
Could you try using the code on git rather than 0.5.0 source?
