### ISSUE TITLE
MP4Box how to create a playlist to stream?

### ISSUE THREAD

**Issue by chanof** [gpac/gpac#960]
Hi, i try to obtain a playlist that is constantly played in loop for pseudo live use with -dash-live option.
How can i modify it to obtain a sequence of videos, and after the last loop again on the first to the infinite until q is press?
COMMAND LINE
sudo MP4Box -dash-live 1000 -frag 1000 -profile live -subdur 1000 -mpd-refresh 1000 -time-shift 3 -bs-switching merge -segment-name output-seg -out manifest.mpd simp.mp4

May i need the same resolution between the playlist files? Or there are some requests for conformity between the files?
Thanks!
Gianmaria

**Comment by chanof** [comment]
It is possible?

**Comment by DanielMartine** [comment]
I think not till now: https://github.com/gpac/gpac/issues/762

**Comment by jeanlf** [comment]
no but will be there soon
