### ISSUE TITLE
Adding custom atoms to MP4 files?

### ISSUE THREAD

**Issue by charlizesmith** [gpac/gpac#963]
Hi,

Is it possible to add some custom atom in the header of a MP4 video file?

Would the library "MP4Box" be useful for this purpose?

I need to add the terms "beam" and "loop" in the header of MP4 files before the "moov" atom.

More information can be found here :

https://stackoverflow.com/questions/44893316/whatsapp-video-as-gif-sharing-on-android-programatically

I do not want to edit the headers via too much calculations, as the answer suggests. Is there a simple way to add the atom "loop" to any MP4 files?

How does one go about using your library, and adding a custom atom to any MP4 file?

Use Case :-

WhatsApp does a smart thing. Their animated GIFs are actually MP4 files (which contain this atom "loop"), and the MP4 files which it wants to treat as videos in their UI, they do not add that "loop" atom. We wish to do something similar.

Any help would be truly appreciated!

**Comment by Murmur** [comment]
This answer is not a GPAC related but I have used mp4parser java library to modify(add,delete,change) mp4 boxes. See this project, it's a rather simple to use, lot of examples available.
https://github.com/sannies/mp4parser/blob/master/examples/src/main/java/org/mp4parser/examples/metadata/MetaDataInsert.java

**Comment by charlizesmith** [comment]
Thanks...

Is mp4parser a command line utility? Would you be kind enough to provide a
command for inserting a custom atom?

**Comment by Murmur** [comment]
You need to compile mp4parser java library then you may create a commandline utility. See examples/*.java files they are ready-to-use command lines applications. If you know a basic level of Java then it should be easy to create customized command lline application.

**Comment by jeanlf** [comment]
now in GPAC 0.9.0, see [this test](https://github.com/gpac/gpac/blob/filters/tests/scripts/mp4box-boxpatch.sh)

**Comment by rajhlinux** [comment]
"now in GPAC 0.9.0, see [this test](https://github.com/gpac/gpac/blob/filters/tests/scripts/mp4box-boxpatch.sh)"

That link does work any more.

**Comment by rbouqueau** [comment]
Since then the test suite has migrated to a separate repo. You can find the related content here:
- [boxpatch with ```mp4box```](https://github.com/gpac/testsuite/blob/261434761a44b277159b223264cf1b2fc451b084/scripts/mp4box-boxpatch.sh#L9)
- [boxpatch with ```gpac```](https://github.com/gpac/testsuite/blob/261434761a44b277159b223264cf1b2fc451b084/scripts/boxpatch.sh#L9)
- [boxpatch from javascript](https://github.com/gpac/testsuite/blob/261434761a44b277159b223264cf1b2fc451b084/scripts/jsfilter.sh#L29)

PS: patch files are located [here](https://github.com/gpac/testsuite/tree/261434761a44b277159b223264cf1b2fc451b084/media/boxpatch)

**Comment by forthrin** [comment]
1. What is the command line for adding a `loop` atom to an MP4 file?

2. Do macOS "mpv" and "Messages" adhere to it?

**Comment by rbouqueau** [comment]
1. Do you have a file example to share?
2. No idea, you should ask on their discussion forums.

**Comment by forthrin** [comment]
1.  Any MP4 file containing an H.264 video.

**Comment by rbouqueau** [comment]
I mean an example with a ```loop``` atom. We need to know where it's located (it seems between the ```ftyp``` and the ```moov```) and confirm that it is an empty box (with no syntax element).
