### ISSUE TITLE
DashCast "Codec is not supported" with Ubuntu 16.04

### ISSUE THREAD

**Issue by marcodellemarche** [gpac/gpac#966]
Hi everyone! I've installed gpac following all the instructions on Ubuntu 16.04. This is what it's happening:
$ sudo DashCast -vf video4linux2 -vres 640x480 -vfr 30 -v4l2f yuyv422 -pixf yuv42p2 -v /dev/video0 -af alsa -a plughw:1,0 -live

MPD refresh time not set in live - defaulting to segment duration
Options:
    video source: /dev/video0
    video format: video4linux2
    v4l2 format: yuyv422
    video framerate: 30
    video resolution: 640x480
    video crop: 0x0
    audio source: plughw:1,0
    audio format: alsa
Configurations:
    id:v1	res:640x480	vbr:0
Input #0, video4linux2,v4l2, from '/dev/video0':
  Duration: N/A, start: 13614.540518, bitrate: 147456 kb/s
    Stream #0:0: Video: rawvideo (YUY2 / 0x32595559), yuyv422, 640x480, 147456 kb/s, 30 fps, 30 tbr, 1000k tbn, 1000k tbc
**Codec is not supported.
Cannot open input video.**

If you need any log or detail please just let me know how to get it, unfortunately I'm new about this topic. What could it be the issue?

**Comment by jeanlf** [comment]
can you grab this video using ffmpeg ?

**Comment by jeanlf** [comment]
dashcast is now deprecated, please use GPAC 0.9.0 DEV
