### ISSUE TITLE
Windows batch file (with MP4Box) no longer works as it did in the past

### ISSUE THREAD

**Issue by Vangelis66** [gpac/gpac#969]
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/

Hello 😃 
Apologies if this is a known (recent) bug or a change by design 😕 
Some years ago I wrote (actually I forked the script from someone else, then adapted it to MP4Box) the following Windows batch script: 
```bat
ECHO OFF
REM MP4Box Prompt
REM Open a command prompt to run MP4Box

TITLE MP4Box Prompt

IF NOT EXIST mp4box.exe (
  CLS
  ECHO mp4box.exe could not be found.
  GOTO:error
)

PROMPT $G
CLS
mp4box -version
SET PATH=%PATH%
ECHO.
ECHO For help run: mp4box -h
ECHO.

CMD /F:ON /Q /K
GOTO:EOF

:error
  ECHO.
  ECHO Press any key to exit.
  PAUSE >nul
  GOTO:EOF
```
I have saved that script as file `mp4box-prompt.bat`

My primary OS is Windows 7 SP1 32-bit (but I also occasionally use Windows Vista SP2 32-bit). 
In May 2017, I had compiled myself the following MP4Box static build: 
```
MP4Box - GPAC version 0.7.2-DEV-rev27-g6542fabd8-ab-suite
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: --host=i686-w64-mingw32 --build=i686-w64-mingw32 --target=i6
86-w64-mingw32 --prefix=/local32 --disable-shared --enable-static --static-mp4bo
x
Features: GPAC_DISABLE_3D
```
When files `mp4box.exe` and `mp4box-prompt.bat` are in the same directory, running the batch file will produce the following output in a command prompt window: 
```
MP4Box - GPAC version 0.7.2-DEV-rev27-g6542fabd8-ab-suite
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: --host=i686-w64-mingw32 --build=i686-w64-mingw32 --target=i6
86-w64-mingw32 --prefix=/local32 --disable-shared --enable-static --static-mp4bo
x
Features: GPAC_DISABLE_3D

For help run: mp4box -h

>
```
I recently acquired the following static build of MP4Box (presumably also built by [media-autobuild_suite](https://github.com/jb-alvarado/media-autobuild_suite)): 
```
MP4Box - GPAC version 0.7.2-DEV-rev357-g7115eeb89-ab-suite
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: --host=i686-w64-mingw32 --build=i686-w64-mingw32 --target=i6
86-w64-mingw32 --prefix=/local32 --disable-shared --enable-static --static-mp4bo
x
Features: GPAC_DISABLE_3D
```
This build works OK if I open manually a command prompt window and CD to its location on disk (this is how I copied its `-version` info), HOWEVER, **if I run the posted batch file from the same directory, a cmd window flashes for fractions of a second (and I can tell it's not empty) and then instantly vanishes**...

Prior to posting, I repeated that test with latest win32 GPAC nightly build (**gpac-0.7.2-DEV-rev367-ga7a79f45-master-win32.exe** at this time) and _I could reproduce_; FYI, you need files `mp4box.exe`, `js.dll`, `libeay32.dll`, `ssleay32.dll` and `mp4box-prompt.bat` _in the same directory_!

Any insight will be highly appreciated (as is the app itself ! ㊗️ ) Ideally, I'd like to keep using my custom batch file with mp4box.exe - do I need to change some syntax by adding some newly added switch?

Thanks in advance...
Regards.

**Comment by rbouqueau** [comment]
Have you tried checking that all you binary dependencies are present? You can use http://www.dependencywalker.com/ for that purpose.

In batch errors can lead to silent fails.

**Comment by aureliendavid** [comment]
your script works fine for me

have you tried launching it from a command prompt instead of double-clicking it ? it should prevent the flashing window and let you know what went wrong

you can also remove the ECHO OFF line in the script to see what it's doing and where it fails

**Comment by aureliendavid** [comment]
I don't think there's an issue here. Reopen if needed.
