### ISSUE TITLE
SegmentTimeline in MPD not in par with sidx boxes

### ISSUE THREAD

**Issue by kuon** [gpac/gpac#97]
When I dash an mp4(h264/aac 48k) with MP4Box, with RAP/keyframes every 10 seconds, I have the proper timing in the generated mp4, but the segments in SegmentTimeline differs.

(I'm going to limit to the first 3 segments, as the issue is the same for the whole file)

The first three sidx boxes have earliest presentation times of (timescale 12288) respectively:
0, 122880, 245760 which are exactly 0, 10 and 20 seconds.

The tfdt boxes have the following track offsets:
video (timescale 12288): 0, 122880, 245760
audio (timescale 48000): 0, 484352, 964608 (which are aligned to aac encoding window of 1024 samples)

The SegmentTimeline starts with:

``` xml
<SegmentList timescale="1000">
 <SegmentTimeline>
     <S t="0" d="10090"/>
     <S d="10005" r="1"/>
     <S d="10000"/>
```

I understand that the audio being longer creates this issue (484352/48000 = 1009.06~). What I do not understand is why my segments are not interlapping in the timeline. I expect something like:

``` xml
<SegmentList timescale="1000">
 <SegmentTimeline>
     <S t="0" d="10090"/>
     <S t="10000" d="10005"/>
     <S t="20000" d="10005"/>
     <S t="30000" d="10000"/>
```

Because to play the time (in ts 1000) 10045 for example, I will need segment 1 for audio, but segment 2 for video.

_Thinking out loud_:
It's not going to cause issue with short videos as even if the user seeks at 10045, segment 2 will start playing, and nobody is going to notice the 45ms of missing sound, but this can cause minor issue with long video, if I have a 2hours video (720 segments) and the user seeks near the end, at 1h40, I'll have 3 seconds of sync error.

**Comment by jeanlf** [comment]
you cannot have overlapping segments in a rep, forbidden by the spec when using segmentAlignment=true (which is what everybody uses)

With mux AV and MP4Box, the SegmentTimeline is indexed on the video track, I don't understand why this is not the case in your sample. I just tried with a multiplexed AV file with a slightly varying gop size, and the segment timeline is aligned with the sidx. Could you post a sample file ?

**Comment by kuon** [comment]
If I can't have overlapping segments in a rep, I guess I'd expect the following:

```xml
<SegmentList timescale="1000">
 <SegmentTimeline>
     <S t="0" d="10000" r="3"/>
```

The file I'm using is here:

http://kura-tests.s3.amazonaws.com/playback_short.mp4

It is encoded from original high res video with the following ffmpeg command:

```
ffmpeg -i big_buck_bunny_1080p_h264.mov -y -c:v libx264 -tune film -crf 24 -preset medium -force_key_frames "expr:gte(t,n_forced*10)" -c:a libfdk_aac -b:v 400k -b:a 64k -ac 1 -vf scale="trunc(oh*a/2)*2:144" -movflags faststart -f mp4 -t 50  playback_short.mp4
```

Then I dash it with:

```
MP4Box -dash  10000 -frag 10000  -rap  -frag-rap -segment-timeline  playback_short.mp4
```

Which produces:

```
   <SegmentList timescale="1000">
    <SegmentTimeline>
     <S t="0" d="10090"/>
     <S d="10005" r="1"/>
     <S d="10000" r="1"/>
    </SegmentTimeline>
   </SegmentList>
```

Timing in sidx and tfdt boxes:

```
stream 1, timescale 12288
earliest pres 0 (0)
track offset 0
track offset 0

stream 1, timescale 12288
earliest pres 122880 (10)
track offset 122880
track offset 484352

stream 1, timescale 12288
earliest pres 245760 (20)
track offset 245760
track offset 964608

stream 1, timescale 12288
earliest pres 368640 (30)
track offset 368640
track offset 1444864

stream 1, timescale 12288
earliest pres 490496 (39)
track offset 491520
track offset 1924096
```

I notice now that the earliest presentation time of the sidx box in the last fragment is not the same as the video track offset of the tfdt box.

**Comment by kuon** [comment]
I am wondering if I can simply ignore the SegmentTimeline and use 10 seconds for each segments (as I force keyframe with ffmpeg).

**Comment by jeanlf** [comment]
This has been fixed some time ago in master and in filters branch, reopen if needed
