### ISSUE TITLE
MP4Box: noticed delay between videos

### ISSUE THREAD

**Issue by DanielMartine** [gpac/gpac#971]
Hello, I would like to ask about a strange behavior that I found reading the terminal while MP4Box processed a video for the live.
Some videos react to the -segdur in an inflexible way: the next segment always is scheduled after 16000ms in my case.
Other videos once finished when they have to start again in loop have a delay even if without apparent errors: instead of getting the next segment 16000ms after the last, I can notice a delay that always occurs at the end/start of the video and is added from time to time.
I tried to change the duration of the video to always get even seconds (aligned with the gop), but the problem persists, I would like to know which differences in the videos trigger these reactions and if it can be a problem. below my commands:

`ffmpeg -y -i in.mp4 -c:a copy -c:v libx264 -x264opts 'keyint=48:min-keyint=48:no-scenecut' -r 24 -b:v 1500k -maxrate 1500k -bufsize 1000k -vf "scale=-1:800" out.mp4
`

`MP4Box -dash-live 8000 -subdur 16000 -profile dashavc264:live -mpd-refresh 240.0 -bs-switching no -time-shift 80 -min-buffer 4000 -insert-utc -out manifest.mpd out.mp4#video out.mp4#audio
`
could i also ask for a possible correction of the commands, do they seem correct for a live stream to dash.js?
Thanks a lot,
Dan

**Comment by chanof** [comment]
I sorry.. i understand that this issue mast be again the same of #949
Thanks for your work!
Dan

**Comment by DanielMartine** [comment]
What about with -dash-ctx?

**Comment by aureliendavid** [comment]
does this still happen? if so can you provide a video example and instruction to reproduce it?

thanks
