### ISSUE TITLE
add new adaptive algorithm based on SRD

### ISSUE THREAD

**Issue by fujunustc** [gpac/gpac#973]
I encode a 360 video at N tiles by kvazaar encoder and each tile is encoded independently.  And at the same time, I encode it at M bitrate levels for adaptive bitrate control. I use mp4box to generate dashed content. I want to add a new adaptive algorithm which only play tiles in field of vision based on gpac framework. My question is how to set representations in FOV downloaded. 
And then after finishing adaptive algorithm and compiling, I wonder know how to use command line to enable algorithm.

**Comment by JamesXu20150314** [comment]
Hi, 

How did you solve this problem?
Could you share your methods?
And how did you render the FOV content?

Thanks.

**Comment by fujunustc** [comment]
Hi, :-)

I haven't integrated a new algorithm into mp4client and primitive ideas still are simulated by python.  As a consequence, I might not give you a hand.

As for rendering fov content to HMD, OpenHMD will be a useful alternative to achieve that function. However, I just have finished adding OCulus Rift as new input sensor in mp4client and haven't finished the part of rendering.  Concerning rendering, we might cooperate with each other.

Best regards!





在2018-04-08 14:42:42，ZhiminXunotifications@github.com写道：

Hi,

How did you solve this problem?
Could you share your methods?
And how did you render the FOV content?

Thanks.

**Comment by fujunustc** [comment]
you might refer to issue#509

**Comment by JamesXu20150314** [comment]
I am very glad to your reply.

I have not located the rendering function in GPAC for ERP.  

If I solved this problem, I will share my method.

Thanks.
