### ISSUE TITLE
Compiler question

### ISSUE THREAD

**Issue by fujunustc** [gpac/gpac#975]
Hey. Is there any guideline to compile in windows10 with vs2013?

**Comment by jeanlf** [comment]
the regular windows compilation instructions should work
https://gpac.wp.imt.fr/2011/04/18/command-line-gpac-compiling-on-windows-x86-using-free-microsoft-visual-c/

let us know if that's not the case

**Comment by fujunustc** [comment]
Yeah, I have read this and I open `gpac-master\gpac-master\build\msvc10\gpac_mp4box_mini.sln` to compile projects named mp4box and libgpac, which work well. And then I open `gpac-master\gpac-master\build\msvc10\gpac.sln`  to compile project named mp4client. Although there is no error during compiling, I run it and it doesn't work . The warning message is 'Application failed to start 0xc00007b normally'.
I don't install SDL in my PC and other libs are from `gpac_extra_libs`. At the same time, I have install MFC for visual studio 2013.

**Comment by jeanlf** [comment]
did the dx_hw  module compiled ?

**Comment by fujunustc** [comment]
Emm，I haven't compiled it. I just compiled applications one by one. Thanks, I'll try it soon.

**Comment by fujunustc** [comment]
If I only compile dx_hw module, i can pass the compiling.

**Comment by fujunustc** [comment]
I still have the probelm. I appreciate someone provide a solution containing three projects: libgpac, mp4box,mp4client. Thanks again.

**Comment by rbouqueau** [comment]
Did you install the DirectX SDK as the instructions mandate?

**Comment by fujunustc** [comment]
I install June 2010 DirectX SDK, but it didn't work. I will try February 2010 SDK later.

**Comment by fujunustc** [comment]
I also try compile it on ubuntu16.04, but there is any way to enable openhevc and opensvc.

**Comment by fujunustc** [comment]
I download sources code from here, but I run command ./configure, which shows openhevc is disable. So I go to project named openhevc and use the following command:
`svn checkout https://gpac.svn.sourceforge.net/svnroot/gpac/trunk` 
this version support openhevc but it doesn't support the syntax  'split_tiles' when use mp4box.
