### ISSUE TITLE
Convert Live MPEG2 TS segment to MP4

### ISSUE THREAD

**Issue by grvsaxena419** [gpac/gpac#976]
I am looking for some help with above. My usecase is described below - 

I am using ffmpeg to produce live hls segments. These hls segments are generated sequentially for live and contain presentation time and other metadata inside. I want to also support MPEG DASH and I was looking for a way to convert these HLS segments to fragmented MP4. I was looking for a way to do this using MP4Box if possible. 

I am planning to run MP4Box command line every time there is a new HLS segment created for a particular bitrate. This would allow me to generate corresponding MP4 fragment with necessary metadata. I am planning to build my own tool to generate manifest and hence would not need the manifest generation support. I need following from MP4Box - 

1. A command to generate MP4 while preserving Live timestamps etc. I used below but, it doesn't generate live related boxes e.g. sidx is missing. Also resultant file has green bars in it.

> MP4Box -add in.ts out.mp4 -dash-ctx DASH.txt -profile live -segment-ext mp4

2. A command to split this into initialization fragment and content fragment. 

In addition, I did try to do this with ffmpeg as well. It produces a valid video clip but, misses out on Live metadata.

/usr/local/bin/ffmpeg -y  -i in.ts -codec copy  -loglevel verbose -debug_ts -copyts -bsf:a aac_adtstoasc -movflags empty_moov+omit_tfhd_offset+frag_keyframe+default_base_moof out.mp4

Any help would be appreciated.

**Comment by rbouqueau** [comment]
There is a sample program available at https://github.com/gpac/test-engine-live-tools

It should fit your need. Let us know.

**Comment by grvsaxena419** [comment]
Thanks for the help.

I took a brief look and it looks like its using ffmpeg in conjunction with mp4box. I am assuming in my case that's already complete since I already have mpeg ts files to be used with mp4box. 
I'll take a deeper look at the example to better understand it and reach out if I have any questions.

**Comment by jeanlf** [comment]
This is now possible using GPAC 0.9.0 DEV:
```gpac -i fragment.ts -o test.mpd:dur=-1```

This will generate a single dash segment (dash duration -1 is max possible duration) using the source timing and an init segment.
You can then tweak the dasher and isobmf muxer for things such as sidx, moof seq num, etc
