### ISSUE TITLE
How to remove Tile track from video. I tried with rem option but it is not working. Where exactly in the code is Client Requesting the Server for the tiles ?

### ISSUE THREAD

**Issue by swetheendra** [gpac/gpac#977]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] I looked for a similar issue and couldn't find any.
- [ ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
could you please detail more what you are trying to do and the command lines you are using ?

**Comment by swetheendra** [comment]
Hi Thank you for your reply. I was trying following command
Mp4Box -rem 2 video.mp4 -out sample.mp4 to remove tile from video.

Also can you help me to find place at which code is written where client is
requesting server about the tiles that are getting streamed.

Thanks

**Comment by sanilraut** [comment]
@swetheendra : 
a. Try MP4Box -info <mp4 file> to check the number of tracks.
b. If it is a packaging issue, refer the following issues: https://github.com/gpac/gpac/issues/906 and https://github.com/gpac/gpac/issues/827

**Comment by jeanlf** [comment]
please make sure you follow the guide [here](https://gpac.wp.imt.fr/2017/02/01/hevc-tile-based-adaptation-guide/)
