### ISSUE TITLE
how to enable openhevc

### ISSUE THREAD

**Issue by fujunustc** [gpac/gpac#979]
My environment:
ubuntu 16.04 LTS desktop x64

Question: How to enable openhevc when compiling gpac
this is my step:
Step one:
I download gpac source code from https://github.com/gpac/gpac and extra libs from http://download.tsi.telecom-paristech.fr/gpac/gpac_extra_libs.zip.
Step two:
I install ffmpeg and use the following command line
`sudo apt-get install zlib1g-dev xulrunner-1.9.2-dev libfreetype6-dev
libjpeg62-dev libpng12-dev libopenjpeg-dev libmad0-dev libfaad-dev
libogg-dev libvorbis-dev libtheora-dev liba52-0.7.4-dev libavcodec-dev
libavformat-dev libavutil-dev libswscale-dev libxv-dev x11proto-video-dev
libgl1-mesa-dev x11proto-gl-dev linux-sound-base libxvidcore-dev
libwxbase2.8-dev libwxgtk2.8-dev wx2.8-headers libssl-dev libjack-dev
libasound2-dev libpulse-dev libsdl1.2-dev dvb-apps`
Step three:
Because my os is x64. Hence, I choose to download last version of openhevc from https://github.com/OpenHEVC/openHEVC. And then I compile it and copy libLibOpenHevcWrapper.a to extra_libs/lib/gcc.
Step four:
go to the gpac-master fold and then use `./configure`
the response is : 
`C   compiler: gcc
C++ compiler: g++
make: make
CPU: x86_64
Big Endian: no

** GPAC 0.7.2-DEV rev Core Configuration **
debug version: no
GProf enabled: no
Static build enabled: no
Memory tracking enabled: no
Fixed-Point Version: no
IPV6 Support: yes
Static Modules: no

** Detected libraries **
zlib: system
OSS Audio: yes
ALSA Audio: yes
Jack Audio: yes
PulseAudio Audio: yes
DirectFB support: no
X11 Shared Memory support: yes (path: /usr/X11R6)
X11 XVideo support: yes
SDL Support: yes
OpenGL support: yes
TinyGL support: no
OpenSSL support: yes
Mozilla XUL/GECKO support: no
DVB Support: yes
XMLRPC Support: no
wxWidgets support: no

** Extra Libraries used **
SpiderMonkey: system
FreeType: system
JPEG: system
OpenJPEG: system
PNG: system
MAD: system
FAAD: system
XVID: system
FFMPEG: system
Xiph OGG: system
Platinum UPnP: no
AVCap: no
Xiph Vorbis: system
Xiph Theora: system
A52 (AC3): system
OpenSVCDecoder: yes
OpenHEVCDecoder: no
Freenect: no

Creating config.mak
config.h is unchanged
Check config.log for detection failures
Done - type 'make help' for make info, 'make' to build
`
we can see openHEVCDecoder is unable. 
Is there someone to offer some help? Thanks.

**Comment by aureliendavid** [comment]
You're on the right track, just two things:

 * you don't need the gpac_extra_libs.zip package for linux, you can apt-get all the dependencies (I think)
 * you need to build the [`ffmpeg_update`](https://github.com/OpenHEVC/openHEVC/tree/ffmpeg_update) branch of openhevc - it's supposed to become the default branch of the repo but the switch hasn't been done yet

Also, to build the ffmpeg_update branch, you need to use the ffmpeg-style configure instead of cmake. 

Here's how it's built for gpac: 

```
./configure --disable-debug --disable-iconv
make openhevc-static

mkdir -p ../../gpac_public/extra_lib/lib/gcc
cp ./libopenhevc/libopenhevc.a ../../gpac_public/extra_lib/lib/gcc
```

Note that the library has changed name and location.

**Comment by fujunustc** [comment]
I follow your tips, however, it still exits. Hence I wonder know which version of gpac you use and the version of ffmpeg.

**Comment by aureliendavid** [comment]
gpac - HEAD of branch master
openhevc - HEAD of branch ffmpeg_update

were you able to build the libopenhevc.a lib from the ffmpeg_update branch of openhevc? (you might need a git reset --hard HEAD if you tried with cmake before)

**Comment by fujunustc** [comment]
I'm able to build the libopenhevc.a lib from the ffmpeg_update branch of openhevc. However, after I copy it to extra_lib/lib/gcc,  then I go to gpac-master folder and use ./configure . Openhevc is still unable, what a strange.

**Comment by aureliendavid** [comment]
you did copy the libopenhevc.a to your gpac-master/extra_lib/lib/gcc?

you can find the problem by trying what the configure is trying, i.e. go to your gpac-master folder, create a file named `oh.c` with this content: 

```
#include <stdio.h>
#include <libopenhevc/openhevc.h>
int main( void ) { oh_init(1, 1); return 0; }
```

and try to compile it with: 

`gcc -v -O3 -Wall -fno-strict-aliasing -Wno-pointer-sign -fPIC -DPIC oh.c -I./extra_lib/include -lopenhevc -lm -lpthread -Wl,--warn-common -Wl,-z,defs -L./extra_lib/lib/gcc`

if there's an error it should tell you what's wrong

**Comment by fujunustc** [comment]
Thanks for help, I'll try it and tell you result.

**Comment by fujunustc** [comment]
It works. Thanks for your help.

**Comment by fujunustc** [comment]
I try to compile gpac in windows 10. Although I pass compiling, I can't play mp4 files encoded by kvazaar encoder. The error message was
`ODM1 ES1: Cannot find decoder for stream type MPEG-H HEVC Video`.
And then i compiled openhevc_dec module, i found it was lack of openhevc.lib.
Hence, Is there any command lines to generate openhevc.lib from ffmpeg-update in window?
@aureliendavid

**Comment by aureliendavid** [comment]
Here's the script I use to build it on windows : [build_openhevc.txt](https://github.com/gpac/gpac/files/1710166/build_openhevc.txt) (renamed to .bat)

It takes two arguments : 
 - `x86` or `x64` for the first one
 - the second one is the location of init script for the visual studio tools, this can be for example: 
    * for VS2017: `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat"`
    * for VS2010: `"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat"`

It uses cygwin and needs the cygwin bash command to be in the PATH. 

some needed cygwin packages: yasm, pkg-config, make

it will produce two libs : 
 - `openhevc.lib` needs to be copied to `<gpac-master-dir>/extra_lib/x64/release`
 - `openhevc-1.dll` needs to be copied to `<gpac-master-dir>/bin/x64/release`

since openhevc now use the same build process as ffmpeg, you can check this doc for more info and other methods: http://ffmpeg.org/platform.html#Microsoft-Visual-C_002b_002b-or-Intel-C_002b_002b-Compiler-for-Windows

**Comment by fujunustc** [comment]
In release 0.7.0, this doesn't work.
the error message is still```
 [Codec] ODM1 ES1: Cannot find decoder for stream type MPEG-H HEVC Video
 Stream Setup Failure: Media Codec not found

```

**Comment by aureliendavid** [comment]
I meant that openhevc used to be built with cmake, now it's done with a ./configure && make (which are inspired by the ffmpeg ones). 

Here's the gist of the script we use to build openhevc on linux for gpac (adapt to your paths). 

```

cd ./openHEVC/

git checkout --force ffmpeg_update
git fetch
git reset --hard FETCH_HEAD

make clean
./configure --disable-debug --disable-iconv
make openhevc-static || exit 1

mkdir -p ../../gpac_public/extra_lib/lib/gcc
cp ./libopenhevc/libopenhevc.a ../../gpac_public/extra_lib/lib/gcc

```

then run the gpac ./configure and it should find it. If not try https://github.com/gpac/gpac/issues/979#issuecomment-362525583

**Comment by gabriel7771** [comment]
It worked, thanks!
