### ISSUE TITLE
Segment time is wrong if video is shorter than segment duration

### ISSUE THREAD

**Issue by kuon** [gpac/gpac#98]
If I segment a 2 seconds video with 10 seconds segments, the SegmentTimeline have

```xml
<S t="2046" d="2046"/>
```

Instead of:

```xml
<S t="0" d="2046"/>
```

Command used:
```
MP4Box -dash  10000 -frag 10000  -rap  -frag-rap -segment-timeline bunny_test.mp4
```

Video used:
http://kura-tests.s3.amazonaws.com/bunny_test.mp4

While I don't usually segment video that short, I found this behaviour while writing unit tests, so I'm wondering if this is normal.

**Comment by jeanlf** [comment]
indeed, now fixed thanks for the report
