### ISSUE TITLE
Playing #360LIVE in OSMO4 Android, 360 Video with HEVC tiling

### ISSUE THREAD

**Issue by 21praveen** [gpac/gpac#982]
Hi,
How can we play 360 LIVE profile in OSMO4 on Android for HEVC tiling? I tried adding #360 at the end of URL but it is not working. I also searched in preferences and options but couldn't find anything. Although adding #360 at end of URL  worked on UBUNTU. 

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...).

**Comment by JamesXu20150314** [comment]
Hello,

Could you attach your commands (both Ubuntu and Android for 360 LIVE) for us?

Thanks.

**Comment by 21praveen** [comment]
I use something like this in Ubuntu:

MP4Client http://url/a.mpd#360 

For Android, I was using GUI.
I realized that GUI was not fully loaded. Maybe because of my Android version issue. Not it is working fine.

**Comment by JamesXu20150314** [comment]
Okay.

I have another problem, how did you render your content (ERP or other)?

Is it can be modified in GPAC source?
