### ISSUE TITLE
How to create dash respecting IDR of input MP4

### ISSUE THREAD

**Issue by jamichen** [gpac/gpac#984]
Hi, I'm new to MP4box and I would appreciate any valuable tips that can help solve my problem.

Recently, I'm working on creating dash streams that has GOP alignment with source, which means all dash streams must have exact same IDR and IDR PTS as source (which is not transcoded to bear regular IDR interval). I was able to make all transcodings using ffmpeg to align with source, but after running mp4box, the dash files shows IDR and PTS misalignment, which I cannot figure out why.
For example, the source file dash_v4_passthrough.mp4 (also a dash file after mp4box) has IDR indexed 1:31:54:84:110:140:164:194:224:227:257
with PTS of IDR at
0, 1.2, 2.12, 3.226667, 4.306667, 5.506667, 6.46, 7.461667, 8.475, 8.628333, 9.828333

The transcoded video after ffmpeg passthrough_hq1_sd.mp4 has exactly the same IDR index and PTS as source. But, after I run mp4box command:
MP4Box -dash 2000 -profile dashavc264:onDemand -bs-switching no -rap -frag-rap -out manifest.mpd dash-demux-video.mp4

The output dash file dash_passthroughaligned.mp4 now has IDR indexed:
1:31:54:84:110:163:193:223:226:256 (you can see there is 1 IDR less)
with PTS of IDR at 
0, 1.2, 2.12, 3.22, 4.346667, 6.386667, 7.415, 8.415, 8.588333, 9.821667 (PTS of IDR also changed)

Now, does MP4box support dash fragment that keeps IDR and timestamp as input? I assum -dash 2000 will try to find the closest IDR within 2s, but I don't know why it also changes IDR index and timestamp. Ideally, I want my dash output bearing the same IDR structure of mp4 input. Any idea? Thank you!

[dash_v4_passthrough.mp4.zip](https://github.com/gpac/gpac/files/1712732/dash_v4_passthrough.mp4.zip)
[passthrough_hq1_sd.mp4.zip](https://github.com/gpac/gpac/files/1712733/passthrough_hq1_sd.mp4.zip)
[dash_passthroughaligned.mp4.zip](https://github.com/gpac/gpac/files/1712734/dash_passthroughaligned.mp4.zip)

**Comment by aureliendavid** [comment]
Hi, 

I'm trying to reproduce your issue. Can you clarify which files is the input, which is the output, and the command line used?

Also what method/tool are you using to get the IDR-frames index/pts?

thanks

**Comment by jamichen** [comment]
Hi, the input is passthrough_hq1_sd, the output is dash_passthroughaligned. And the command line is 

MP4Box -dash 2000 -profile dashavc264:onDemand -bs-switching no -rap -frag-rap -out manifest.mpd passthrough_hq1_sd.mp4

I use ffprobe 3 to check the IDR/pts of the input and output. Thanks!

**Comment by aureliendavid** [comment]
Are you using the latest git version of gpac? On what OS are you testing?

Here what I get: 

```
$ ffprobe -loglevel error -select_streams v:0 -show_entries frame=key_frame,pict_type,pkt_pts_time,pkt_pts_time,coded_picture_number -of csv=print_section=0 passthrough_hq1_sd.mp4 | grep "1,"
1,0.000000,I,0
1,1.200000,I,30
1,2.120000,I,53
1,3.226667,I,83
1,4.306667,I,109
1,5.506667,I,139
1,6.460000,I,163
1,7.461667,I,193
1,8.475000,I,223
1,8.628333,I,226
1,9.828333,I,256

$ MP4Box -dash 2000 -profile dashavc264:onDemand -bs-switching no -rap -frag-rap -out manifest.mpd passthrough_hq1_sd.mp4
DASH-ing file - single segment
Subsegment duration 2.000 - Fragment duration: 2.000 secs
Spliting segments and fragments at GOP boundaries
DASHing file passthrough_hq1_sd.mp4
[DASH] Generating MPD at time 2018-02-13T09:16:35.075Z

$ ffprobe -loglevel error -select_streams v:0 -show_entries frame=key_frame,pict_type,pkt_pts_time,pkt_pts_time,coded_picture_number -of csv=print_section=0 passthrough_hq1_sd_dashinit.mp4 | grep "1,"
1,0.000000,I,0
1,1.200000,I,30
1,2.120000,I,53
1,3.226667,I,83
1,4.346667,I,109
1,5.546667,I,139
1,6.486667,I,163
1,7.488333,I,193
1,8.501667,I,223
1,8.661667,I,226
1,9.861667,I,256
```

The PTS times are slightly different (I'm not sure why, maybe a float rounding issue), but the IDR indices are the same. 

However if I look at the dash_passthroughaligned.mp4 file you joined, I get: 

```
$ ffprobe -loglevel error -select_streams v:0 -show_entries frame=key_frame,pict_type,pkt_pts_time,pkt_pts_time,coded_picture_number -of csv=print_section=0 dash_passthroughaligned.mp4 | grep "1,"
1,0.000000,I,0
1,1.200000,I,30
1,2.120000,I,53
1,3.220000,I,83
1,4.346667,I,109
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x564d71654980] Failed to add index entry
1,6.460000,I,165
1,7.448333,I,195
1,8.461667,I,225
1,8.661667,I,228
1,9.861667,I,258
```


Which looks closer to what you had. Am I doing something different than you?

**Comment by jamichen** [comment]
Hi David, thanks for confirming. I double checked I was using v0.6 of gpac on linux, and the results I got was dash_passthroughaligned.mp4. If I run with new version 0.7, I get the same result as yours (which is correct). I think this is a version discrepancy. We are using old version in prod, it needs an update.
