### ISSUE TITLE
Closing ISOBaseMediaFileTrace tag generated unexpectedly

### ISSUE THREAD

**Issue by mlondon1** [gpac/gpac#985]
Ever since I updated to recent builds (or from Master), when I run MP4Box to get full info 

ex:
mp4box -diso -std some_file.mp4 > mp4box_out.xml 2>&1

I am seeing a closing tag without an opening tag in the resulting XML:
</ISOBaseMediaFileTrace>

This seems to be a new bug that is causing us headaches.  Any ideas?

**Comment by rbouqueau** [comment]
Thanks for reporting. I can't reproduce with the audio version of the GPAC DASH sequence source counter. Could you share a sample? We have an anonymous dropbox in case it can help: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by mlondon1** [comment]
I uploaded a sample to you.

**Comment by rbouqueau** [comment]
Thank you. I can't reproduce. Can you check your MP4Box version? Do you use a specific platform?

**Comment by mlondon1** [comment]
MP4Box - GPAC version 0.7.1-revrelease

GPAC Copyright (c) Telecom ParisTech 2000-2012

GPAC Configuration: --disable-wx --disable-pulseaudio
--prefix=/usr/local/Cellar/gpac/0.7.1
--mandir=/usr/local/Cellar/gpac/0.7.1/share/man --disable-x11

Features: GPAC_64_BITS GPAC_HAS_SSL

I use a Mac 10.11.6

**Comment by rbouqueau** [comment]
Not ok for me: I don't know where "release" comes from in your revision number.

Could you please build a new MP4Box with these instructions? http://gpac.io/2015/07/29/gpac-build-mp4box-only-all-platforms/
