### ISSUE TITLE
Can I rename files in Temp. folder?

### ISSUE THREAD

**Issue by irrz** [gpac/gpac#986]
Hello guys,
I have pre-encoded videos using DashCast, and I am streaming them via MP4Client on Windows OS. 
I disabled the CleanCache. and now I can receive them in the Temp. folder in C partition.

My question is that "is there any way to let the name on the Temp. folder become in an orderanry way; so instead of getting files such as gpac_cache_82ECE62E83D1E98E745DB7AA3FFFE3C71210626F.mp4, i simply get them as 1.mp4, 2.mp4... etc"?

I hope i can find an answer here for this issue.

Thanks a lot

**Comment by jeanlf** [comment]
`MP4Client -uncache`
 is what you are looking for (cf MP4Client -h)

**Comment by irrz** [comment]
Please find the attached screenshot; you can see the long name of the output files (*.mp4) having a very long name which takes me longer time to rename all of them and sometimes it results in a very incorrect ordering! 
I am wondering if there is either a way to let them named as (1.mp4, 2.mp4) automatically? or i can get them as one concatenated file afterwards? The reason i am doing this is that i am wanting to see how the objective metrics would act in different segments sizes under different network conditions. ![temp folder](https://user-images.githubusercontent.com/16091677/36208065-b69445da-118f-11e8-9ed5-8ac59e6aa7d2.PNG)

My config file which is placed on the GPAC folder is attached too.
[Config.pdf](https://github.com/gpac/gpac/files/1724266/Config.pdf)

My command in the cmd as the following:
mp4client -gui http://<ip>

With my thanks in anticipation

**Comment by rbouqueau** [comment]
Could this be related to #2 ?

**Comment by irrz** [comment]
No it's not to be honest. I am receiving the VoD chunks in the Temp. folder, however, if I wanted to concatinate them using the FFmpeg with such a long name, then the FFmpeg will give me an error related to the longer names. the only solution i found is to rename them manually, but i have at each stream over than 1200 chunks and this would make it a nightmare for me to rename them all, although i have used a program to rename them all but the FFmpeg couldn't concatenate them and the reason i would say because of the incorrect order that they are given.

So, i was thinking if there is a way in the source code i can change the name to be like gpac_cache_1.mp4, gpac_cache_2.mp4, ...etc

Thanks
