### ISSUE TITLE
group selection

### ISSUE THREAD

**Issue by fujunustc** [gpac/gpac#987]
Hey, may I ask how to choose some of all groups to display during a period in application of video streaming basd on   tiles?   @wiiaboo

**Comment by jeanlf** [comment]
which groups are you talking about ?

**Comment by fujunustc** [comment]
Groups contain the syntax of adaptation set and some additional attributes. Here, more specially, I just want to download tiles in field of vision rather than download all tiles. Hence, I might disable some groups which are not in FOV. 
If convenient, could you provide some tips to make mp4client work with Oculus？ I have skimmed Compositor.c , but I find it is not easy to modify.
Thanks for being aware of this issue.

**Comment by fujunustc** [comment]
If convenient, give some response please.

**Comment by fujunustc** [comment]
@jeanlf

**Comment by jeanlf** [comment]
use -logs dash@debug to understand why the content gets stuck - also if possible upload your test sequences somewhere. 
Playing with the group selection state is likely not enough to proposerly resume, you may need to issue a seek() on the previously unselected group - check the code in modules/mpd_in (look for GF_NET_CHAN_PLAY and GF_NET_CHAN_STOP)

**Comment by fujunustc** [comment]
### download information
```C
[DASH] Downloading http://localhost:8080/seq/outspace_10M_dash_track16_4.m4s starting at UTC 1520240707400 ms
[MPD_IN] End of file /seq/outspace_10M_dash_track16_4.m4s download at UTC 1520240707401 ms - estimated bandwidth 3292384 kbps - started file or last chunk at UTC 1520240707400
[DASH] Download http://localhost:8080/seq/outspace_10M_dash_track16_4.m4s complete at UTC 1520240707401 ms
[DASH] Added file to cache (16/74 in cache): http://localhost:8080/seq/outspace_10M_dash_track16_4.m4s
```
### play information
```C
[IsoMedia] playing new segment gmem://118799@11BF1548 (has next dep 1)
[IsoMedia] Opening current segment in non-progressive mode (completely downloaded)
[IsoMedia] Track 1 - cur sample 180 - new sample count 240
[IsoMedia] Enhancement layer available in cache - refreshing it
[MPD_IN] Received Service Query Next request from input service GPAC IsoMedia Reader
[MPD_IN] Had to wait for 0 ms for the only cache file to be downloaded
[MPD_IN] Next Segment is http://localhost:8080/seq/outspace_10M_dash_track16_4.m4s
[MPD_IN] Waited 0 ms - Elements in cache: 37/74
	Cache file name gmem://411548@20AD8AE0
	segment start time 8 sec
[IsoMedia] playing new segment gmem://411548@20AD8AE0 (has next dep 1)
```
### delete cache information
```C
[DASH] deleting cache file http://localhost:8080/seq/outspace_10M_dash_track16_4.m4s : gmem://411548@20AD8AE0
```
As seen from above, it seems there is no problem.

### all debug information in my enviroment
[test.zip](https://github.com/gpac/gpac/files/1780216/test.zip)

### modify dash_client.c is here

[dash_client.zip](https://github.com/gpac/gpac/files/1780199/dash_client.zip)

I modify the following functions

-  `void gf_dash_group_select(GF_DashClient *dash, u32 idx, Bool select)`

-  `dash_main_thread_proc(void *par)`.

###  data
[data link](https://www.dropbox.com/s/9d2058fp6ugocu4/seq.zip?dl=0)

**Comment by fujunustc** [comment]
Emm,  could you have some reponse,please?

**Comment by 21praveen** [comment]
@fujunustc Make sure track1 and track2 are always downloaded.

**Comment by fujunustc** [comment]
@21praveen  First, in this example, I did not determine FOV. Second, I'm track1 and track2 are sure to be downloaded. However, when i enable 15th  tile back, it is still stuck. Could you tell how to modify code or where to modify code? In this example, I just use `gf_dash_group_select(dash, 15, GF_FALSE);
`.

**Comment by 21praveen** [comment]
Don't call the  gf_dash_download_resource function for the tile that you don't want to download. Don't modify the group. Let me know if you are able to determine FOV. My email is praveen@comp.nus.edu

**Comment by fujunustc** [comment]
Thanks! I think you could skim the module named `psvr` and you will know you can modify orientation(yaw, pitch, roll) to change FOV.

**Comment by fujunustc** [comment]
Could you give some suggestions on this @jeanlf ? I have try the function of seek, however, the problem is still existed.

**Comment by fujunustc** [comment]
@jeanlf

**Comment by shkp4j** [comment]
@fujunustc  could you share how you resolved this?

**Comment by JamesXu20150314** [comment]
Hello fujunustc,

@fujunustc have you implemented the scheme that only requests FOV tiles?

**Comment by fujunustc** [comment]
Sorry, I haven't finished it.

在2018-05-21 16:56:07，ZhiminXunotifications@github.com写道：

Hello fujunustc,

@fujunustc have you implemented the scheme that only requests FOV tiles?
