### ISSUE TITLE
MP4Box: Parsing <font> tag in srt subtitles.

### ISSUE THREAD

**Issue by MikZyth** [gpac/gpac#989]
If a subtitle with `<i>` tag comes right after subtitle with `<font>` tag, then it (and all subsequent subtitles with `<i>` tag) will be displayed in color set by the `<font>` tag (i.e. from a previous subtitle) until a "clean" subtitle (without tags) is reached.

Simple example:
`﻿1`
`00:00:05,000 --> 00:00:10,000`
`<font color="#ffff00">Text line 1</font>`

`2`
`00:00:12,000 --> 00:00:15,000`
`<i>Text line 2</i>`

`3`
`00:00:17,000 --> 00:00:20,000`
`<i>Text line 3</i>`

`4`
`00:00:22,000 --> 00:00:24,000`
`Text line 4`

In this example, `Text line 2` and `Text line 3` will be displayed in yellow color.

If you try to export that subtitle stream with srt convertion from the resulting mp4-file (MP4Box -srt 4 file.mp4), then the tags will be screwed up in the exported file.

MP4 file was made using `MP4Box GPAC version 0.7.2-DEV-rev415-g5c3781e7-master` official nightly build on `Ubuntu 16.04 LTS 64 bit`.
The file was tested in QuickTime Player on latest macOS High Sierra (version 10.13.) and MP4Client from the same build.

**Comment by aureliendavid** [comment]
Hi, 

You're right and I thought this was going to be a quickfix but the more I dig into it the more problems I find with SRTs (with import, and export, and playback). 

So I'll try to make a proper fix for all of that but it'll probably take a bit of time to write and test. 

I'll update the issue with my progress. Thanks for the report.

**Comment by jeanlf** [comment]
this is now fixed on master, thanks for the report
