### ISSUE TITLE
Packaging TTML produces an empty .mp4 file

### ISSUE THREAD

**Issue by akunaatrium** [gpac/gpac#99]
Here is a subtitle file in TTML format: http://jmp.sh/tdhTk8I

When trying package it into a new .mp4 file using this command:
`mp4box.exe -v -add subtitles.ttml -new output.mp4`

The result on stdout is:
```
TTML Import
Found root attribute name xmlns:ttm, value http://www.w3.org/ns/ttml#metadata
Found root attribute name xmlns:tts, value http://www.w3.org/ns/ttml#styling
Found root attribute name xmlns:ttp, value http://www.w3.org/ns/ttml#parameter
Found root attribute name xml:lang, value en
Found root attribute name xmlns, value http://www.w3.org/ns/ttml
TTML: incomplete sample (begin=-1, end=-1, text="NULL"). Skip.
TTML: incomplete sample (begin=-1, end=-1, text="NULL"). Skip.
TTML: incomplete sample (begin=-1, end=-1, text="NULL"). Skip.
TTML: incomplete sample (begin=-1, end=-1, text="NULL"). Skip.
TTML: incomplete sample (begin=-1, end=-1, text="NULL"). Skip.
TTML: incomplete sample (begin=-1, end=-1, text="NULL"). Skip.
TTML: incomplete sample (begin=-1, end=-1, text="NULL"). Skip.
TTML: incomplete sample (begin=-1, end=-1, text="NULL"). Skip.
TTML: incomplete sample (begin=-1, end=-1, text="NULL"). Skip.
TTML: incomplete sample (begin=-1, end=-1, text="NULL"). Skip.
TTML: incomplete sample (begin=-1, end=-1, text="NULL"). Skip.
TTML: incomplete sample (begin=-1, end=-1, text="NULL"). Skip.
TTML: incomplete sample (begin=-1, end=-1, text="NULL"). Skip.
TTML: incomplete sample (begin=-1, end=-1, text="NULL"). Skip.
TTML: incomplete sample (begin=-1, end=-1, text="NULL"). Skip.
TTML: incomplete sample (begin=-1, end=-1, text="NULL"). Skip.
TTML: incomplete sample (begin=-1, end=-1, text="NULL"). Skip.
TTML: incomplete sample (begin=-1, end=-1, text="NULL"). Skip.
TTML: incomplete sample (begin=-1, end=-1, text="NULL"). Skip.
TTML: incomplete sample (begin=-1, end=-1, text="NULL"). Skip.
TTML: incomplete sample (begin=-1, end=-1, text="NULL"). Skip.
last_sample_duration=0, last_sample_end=0
Note: TTML import - EBU-TTD detected
Saving output.mp4: 0.500 secs Interleaving
```

The output.mp4 file is saved but it doesn't contain the subtitles. Basically, I could feed in a 100 KB subtitle file but the resulting .mp4 would still be 1 KB, containing just the container and an empty track. Here is mp4box -info:

```
* Movie Info *
        Timescale 600 - Duration 00:00:00.000
        1 track(s)
        Fragmented File: no
        File suitable for progressive download (moov before mdat)
        File Brand isom - version 1
        Created: GMT Wed Apr 08 05:35:49 2015
        Modified: GMT Wed Apr 08 05:35:49 2015

File has no MPEG4 IOD/OD

Track # 1 Info - TrackID 1 - TimeScale 1000 - Media Duration 00:00:00.000
Media Info: Language "und (und)" - Type "subt:stpp" - 0 samples
XML Subtitle Stream - namespace http://www.w3.org/ns/ttml
 Size 0 x 0 - Translation X=0 Y=0 - Layer 0
        RFC6381 Codec Parameters: stpp
        All samples are sync
```

Version of mp4box: 0.5.2-DEV-rev248-g39d5978-master

Anvar

**Comment by rbouqueau** [comment]
Thanks for reporting. I could reproduce. It seems like EBU-TTD is wrongly detected. I'll have a look later today.

**Comment by rbouqueau** [comment]
Should be fixed. The timing format finishes with ":frame_num" which is not supported in the current parsing (for EBU-TTD).

Please close if it works for you.

**Comment by akunaatrium** [comment]
Will wait for the next build. How often are the builds released? Multiple times a day?

**Comment by rbouqueau** [comment]
It is a buildbot, trigged at each commit :)

**Comment by akunaatrium** [comment]
Thanks, looks good for now. I don't have a player to test the subtitles but I can see that the output .mp4 now indeed contains the subtitles.

**Comment by rbouqueau** [comment]
For playback, you can find people working on it at https://github.com/gpac/gpac/issues/57

**Comment by akunaatrium** [comment]
I want to ask about one more thing which I noticed looks weird. The output .mp4 file containing the subtitles have the XML structure repeated when looked at the inside of it. Using the same TTML input, the .mp4 will contain each sentence wrapped inside of the whole structure of the TTML document. It's hard to explain better, but if you open the output .mp4 file with Notepad++ for example, it becomes evident immediately.
I smell a potential defect but I am not sure. Is that desired and specified behaviour?

**Comment by rbouqueau** [comment]
Yes. Samples are full XML documents with hopefully only the requested data. It makes a lot of redundant data as you noticed.

**Comment by cconcolato** [comment]
As @rbouqueau said, MP4 samples containing TTML contain a entire TTML document. Ideally, only the header should be repeated and the different paragraphs that don't have the same timing should not. In practice, if your documents are simple (no overlapping in time between paragraphs), MP4Box (via -add) should be able to generate samples without redundant data. If your documents are complex, you probably want to edit your documents to remove redundancy and ask MP4Box to use them without modifying them (via -nhml for now, via -add in the future).

**Comment by akunaatrium** [comment]
Ok, there may be some sense in having all the redundancy in the .mp4. But when I created a DASH video with 60 second segment lengths, the subtitle segments also contained all the redundancy (like the whole XML structure repeated for every sentence). I would expect that an actual subtitle segment contains the full structure only once and that structure to contain the different texts during the 60 seconds.

Here is a sample 60 second subtitle segment that contains this redundancy: http://jmp.sh/YiVhYIL

**Comment by cconcolato** [comment]
> there may be some sense in having all the redundancy in the .mp4

The redundancy should be avoided. In your case, the TTML header is longer than the timed text content, so clearly this packaging is inefficient. You want to have only one TTML sample per segment. To have that, as of now, you have to create each TTML file corresponding to a segment and import these TTML files using NHML. We plan on adding that feature so that you can simply import the whole document and indicate the segment duration.

**Comment by akunaatrium** [comment]
Nice, I get it now, thanks for the explanation!
