### ISSUE TITLE
Video/audio out of sync during play

### ISSUE THREAD

**Issue by DanielMartine** [gpac/gpac#996]
Hi there, testing the latest version with the addition `-bound` with `-dash-live`
I can notice a problem of audio / video synchronization that occurs only after some loops of the video in input:
The problem starts to occur only when the loop begins repetitions:
For example if I watch a video of 20 minutes, audio and video are synchronized, when the video repeats its self as desired with -dash-live the delay between audio and video begins to grow, which will become evident after 3, 4 repetitions.
if I reload the page the audio will be back synchronized.
The problem is only visible after the repetition of several loops.
There are no errors from mp4box or on chrome console.
The test was performed with video.js contrib dash.

**command:**
`MP4Box -dash-live 8000 -subdur 8000 -bound -profile dashavc264:live -mpd-refresh 3600.0 -time-shift 24 -min-buffer 4000 -insert-utc -no-cache -out manifest.mpd 1080set.mp4#video 720set.mp4#video 360set.mp4#video 1080set.mp4#audio 720set.mp4#audio 360set.mp4#audio`

Apart from the additional information, I think there is a small difference in duration between audio and video that grow with the increase of repetitions, it is not reported by MP4Box, after some repetitions it becomes audible, reloading the page brings the streaming back synchronized.
It would seem that `-bound` has no effect while someone is watching?! 

**Additional:**
Videos that i use for test is the concatenation (ffmpeg concat demux) of many videos prevoiusly encoded with closed gop, unfortunately I still can not get a timestamp without any discrepancies between one video and another

**encode command:**
`ffmpeg -y -i "$f" -i ../logo/logo.png -c:a aac -b:a 384k -ar 48000 -ac 2 -async 1 -c:v libx264 -x264opts keyint=$GOP:min-keyint=$GOP:no-scenecut -bf 0 -r $FPSC -b:v 4800k -maxrate 4800k -bufsize 3000k -profile:v main -crf 22 -t $DUR -filter_complex "[0:v][1:v]overlay=main_w-overlay_w-10:10,scale=1920:1080,setsar=1" ../buffer/${NAME}-1080.mp4`

**concat command:**
`ffmpeg -f concat -safe 0 -i 1080list.txt -t $TOTDUR -c copy ../output/1080set.mp4`

**PTS timestamp:**
```
[...]
382.021016
384.021016
386.021016 the concat demux effect:
388.043047
390.043047
392.043047
[...]
```
For the the full script to encode and concat:
https://stackoverflow.com/questions/48770268/bash-script-automate-ffmpeg-encoding-for-mpeg-dash/48776153#48776153

**If you need i can upload the video used for test**

Thanks!

**Comment by aureliendavid** [comment]
Can you test if this also happens without -bound?

thanks

**Comment by DanielMartine** [comment]
Without `-bound` the sync issue is not present

**Comment by DanielMartine** [comment]
It is possible that `-bound` make the streaming going out of sync faster than without.. i need to do some more tests to be sure.
This is tha video used for test: https://www.sendspace.com/file/kj17x5

**Comment by DanielMartine** [comment]
**TWO HOURS PER TEST ON DESKTOP:**
with      -bound: chrome on osx negative test
with      -bound: safari on osx positive: audio before video
without -bound: chrome on osx negative test
without -bound:  safari on osx positive: audio before video

**TWO HOURS PER TEST ON ANDROID/CHROME**
Always negative

**Observation:** 
I'm not sure that on chrome the test is totally negative, it could only take longer to notice the out of sync (audio/video) issue.
I need all night to be sure that chrome is without this issue, i ll back tomorrow

Tested with video.js contrib dash

**Comment by DanielMartine** [comment]
Using chrome there is no delay.
I confess I'm a little confused about where the issue may be at this point.
Have you been helped to give you an idea?
I think that maybe the problem could be in the way I prepared the video: encode + concat, but it would be extremely useful an error message from MP4Box about, to know if the video is ideoneous and if not  which problem the video have.
However it is only a hypothesis

**Comment by DanielMartine** [comment]
I noticed that the PTS discrepancy created by the concat operation, generates a delay between audio and video:
video streams suffers a delay of a few milliseconds between concatency and the other,
The audio stream instead does not suffer any delay.
The result of the concertion is a longer video stream than the audio stream.
Adding the repetitions of the loop on MP4Box as -dash-live the delay increases (only on safari) and becomes noticeble after some repetitions (audio before video).
Resample audio stream to match the timestamp during concat process with aresample ffmpeg audio filter fix the issue.
Now it is in sync with all common browsers!
